[#capi-provision]
= Installing a managed cluster with Cluster API

You can install an OCP managed cluster with the cluster API using the `metal3` infrastructure provider and the openshift assisted bootstrap and control plane providers.

//Use supported RHCOS OCP images: Red Hat CoreOS (RHCOS) The exact RHCOS image version used should match the target OpenShift version.
//Needs to be rewritten: We need supported OCP images that match the target OCP version later in the process, I assume.

.Prerequisites

* You need the `MultiClusterEngine` resource either from the {acm-short} installation, or the {mce-short} standalone installation.
* Assisted service needs to be enabled, which is the default setting.
You need to configure DNS entries for the expected endpoints. DNS entries must be resolvable from the bootstrap cluster and the hosts that form the workload cluster. See the following endpoints:
  - `api.<baseDomain>`: The API endpoint for the cluster.
  - `api-int.<baseDomain>`: The internal API endpoint for the cluster.
  - `*.apps.<baseDomain>`: The wildcard DNS entry for the cluster's applications.

[steps-capi-workload]
==  Provisioning a workload with Cluster API

. Change the default behavior
oc edit multiclusterengines.multicluster.openshift.io -n multicluster-engine

# set enabled to true for the following values in .spec.overrides:
----
    - configOverrides: {}
      enabled: true
      name: assisted-service
    - configOverrides: {}
      enabled: true
      name: cluster-api
..
    - configOverrides: {}
      enabled: true
      name: cluster-api-provider-metal3-preview
    - configOverrides: {}
      enabled: true
      name: cluster-api-provider-openshift-assisted-preview
----    
. You need to enable cim https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.13/html/clusters/cluster_mce_overview#enable-cim 

. You need to configure a `Cluster` resource with `clusterNetwork` specifications, `controlPlaneRef` specifications, and `infrastructureRef` specifications. See the following example `Cluster` resource `OpenshiftAssistedControlPlane` is the control place and `Metal3Cluster` is the infrastructure:

[source,yaml]
----
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-multinode
  namespace: test-capi
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 172.18.0.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef: <1>
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha2
    kind: OpenshiftAssistedControlPlane
    name: <your-name>
    namespace: <your-namespace>
  infrastructureRef: <2>
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: <your-name>
    namespace: <your-namespace>
----
1. 
2. 

. Run the command to apply.

. Configure the `OpenshiftAssistedControlPlane` resource that includes the distribution version, API VIPs, and SSH keys. The following YAML defines the control plane configuration, including the distribution version, API VIPs, and SSH keys.

[source,yaml]
----
apiVersion: controlplane.cluster.x-k8s.io/v1alpha2
kind: OpenshiftAssistedControlPlane
metadata:
  name: test-multinode
  namespace: test-capi
  annotations: {}
spec:
  openshiftAssistedConfigSpec:
    sshAuthorizedKey: "{{ ssh_authorized_key }}"
    nodeRegistration:
      kubeletExtraLabels:
      - 'metal3.io/uuid="${METADATA_UUID}"'
  distributionVersion: 4.19.0 #we should be able to make this a variable
  config:
    apiVIPs:
    - 192.168.222.40
    ingressVIPs:
    - 192.168.222.41
    baseDomain: lab.home
    pullSecretRef:
      name: "pull-secret"
    sshAuthorizedKey: "{{ ssh_authorized_key }}"
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3MachineTemplate
      name: test-multinode-controlplane
      namespace: test-capi
  replicas: 3
----
1.`.spec.config.sshAuthorizedKey` can be used to access the provisioned OpenShift Nodes
2.`.spec.openshiftAssistedConfigSpec.sshAuthorizedKey` can be used to access nodes in the boot (also known as discovery) phase.
3. Specify your {ocp-short} version in the `distributionVersion` field of the `OpenshiftAssistedControlPlane` resource. The value for the `distributionVersion` must match one of the tags that can be found in the OCP release page:https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/ 
RHCOS image must match the version * [OCP Releases](https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/)
//will rewrite (but I think we already say this early)

. Apply

. If you do not have a pull secret, you need to create a pull secret. Set the `pullSecretRef` field to the name of the secret that contains the pull secret. 

.. `.spec.config.pullSecretRef` and `.spec.openshiftAssistedConfigSpec.pullSecretRef` in the `OpenshiftAssistedControlPlane` resource.
.. `.spec.template.spec.pullSecretRef` in any `OpenshiftAssistedConfigTemplate` attached to MachineSets.
.. See {ocp-short} link:https://console.redhat.com/openshift/install/pull-secret[pull secret]. See _Using image pull secrets_ for more information.
//use siteconfig as example.


. Configure the `Metal3Cluster` infrastructure resource. 

[source,yaml]
----
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: test-multinode
  namespace: test-capi
spec:
  controlPlaneEndpoint:
    host: test-multinode.lab.home
    port: 6443
  noCloudProvider: true
----
1. The `host` is composed by the `<clusterName>.<baseDomain>*` value. The `clusterName` is defined in the `Cluster` resource, while `baseDomain` is defined in the `OpenshiftAssistedControlPlane` resource.

. oc apply

. Configure the `Metal3MachineTemplate` resource for the control plane nodes that is referenced from the `OpenshiftAssistedControlPlane`

[source,yaml]
----
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-multinode-controlplane
  namespace: test-capi
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: test-multinode-controlplane-template
      image:
        checksum: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/dev-4.19/sha256sum.txt
        checksumType: sha256
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/dev-4.19/rhcos-dev-4.19-x86_64-nutanix.x86_64.qcow2
        format: qcow2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
   name: test-multinode-controlplane-template
   namespace: test-capi
spec:
   clusterName: test-multinode
----
1. Make sure clusterName is set to the same value as in the `Cluster` resource
2. names need to match
3.

. Apply command

. Configure worker nodes with the `MachineDeployment` resource. 

[source,yaml]
----
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: test-multinode-worker
  namespace: test-capi
  labels:
    cluster.x-k8s.io/cluster-name: test-multinode
spec:
  clusterName: test-multinode
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: test-multinode
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: test-multinode
    spec:
      clusterName: test-multinode
      bootstrap:
        configRef:
          name: test-multinode-worker
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
          kind: OpenshiftAssistedConfigTemplate
      infrastructureRef:
        name: test-multinode-workers-2
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: Metal3MachineTemplate
----
1. including the bootstrap configuration is referenced below (how to install)
2. infrastructure reference points to the resource below (how to provision)

. Run apply

. Create the `OpenshiftAssistedConfigTemplate` resource that is referenced in the `MachineDeployment`. The following YAML defines the bootstrap configuration for worker nodes. This is used to register the nodes with the OpenShift Assisted Installer.

+
[source,yaml]
----
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: OpenshiftAssistedConfigTemplate
metadata:
  name: test-multinode-worker
  namespace: test-capi
  labels:
    cluster.x-k8s.io/cluster-name: test-multinode
spec:
  template:
    spec:
      nodeRegistration:
        kubeletExtraLabels:
          - 'metal3.io/uuid="${METADATA_UUID}"'<1>
      sshAuthorizedKey: "{{ ssh_authorized_key }}" <2>
----
1. The METADATA_UUID env var is being loaded on the node, and can be leveraged by this templating. (must be this)
2. Enter your ssh

. Create the `Metal3MachineTemplate` that is referenced in the `MachineDeployment`.

+
[source,yaml]
----
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
   name: test-multinode-workers-2
   namespace: test-capi
spec:
   nodeReuse: false
   template:
      spec:
         automatedCleaningMode: metadata
         dataTemplate:
            name: test-multinode-workers-template
      image:
        checksum: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/dev-4.19/sha256sum.txt
        checksumType: sha256
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/dev-4.19/rhcos-dev-4.19-x86_64-nutanix.x86_64.qcow2
        format: qcow2
----
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
   name: test-multinode-workers-template
   namespace: test-capi
spec:
   clusterName: test-multinode
----

. Run the following command to save the YAML file and provision a cluster.

+
[source,bash]
----
oc apply -f cluster.yaml
----

. You can verify that the resources are available.

.. For example, run  `oc get cluster` to check your `Cluster` resource
.. See the following output:

----
status:
  conditions:
  - lastTransitionTime: "2025-06-25T11:23:38Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-06-25T11:23:38Z"
    status: "True"
    type: ControlPlaneReady
  - lastTransitionTime: "2025-06-25T10:37:03Z"
    status: "True"
    type: InfrastructureReady
---

//https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/4.19.0/rhcos-4.19.0-x86_64-nutanix.x86_64.qcow2
//https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/4.19.0/sha256sum.txt