[#capi-provision]
= Installing a managed cluster with Cluster API

You can install an {ocp-short} managed cluster with the Cluster API by using the `metal3` infrastructure provider and the {ocp-short} assisted bootstrap and control plane providers.

.Prerequisites

* You need the `MultiClusterEngine` resource either from the {acm-short} installation, or the {mce-short} standalone installation.
* The following API base domain must point to the static API VIP: `api.<cluster_name>.<base_domain>`
* The following application base domain must point to the static IP address for Ingress VIP: `*.apps.<cluster_name>.<base_domain>`

[steps-capi-workload]
==  Provisioning a workload with Cluster API

. Enable the services that you need to provision a workload. By default, `assisted-service`, cluster-api-provider-metal3-preview, and `cluster-api-provider-openshift-assisted-preview` are disabled. Run the following command to edit the resource: 

+
[source,bash]
----
oc edit multiclusterengines.multicluster.openshift.io -n multicluster-engine
----

. Set `enabled: true` in `.spec.overrides` for the `assisted-service` component, the `cluster-api-provider-metal3-preview` component, and the `cluster-api-provider-openshift-assisted-preview` component. See the following `configOverrides` values:

+
[source,yaml]
----
    - configOverrides: {}
      enabled: true
      name: assisted-service
    - configOverrides: {}
      enabled: true
      name: cluster-api
...
    - configOverrides: {}
      enabled: true
      name: cluster-api-provider-metal3-preview
    - configOverrides: {}
      enabled: true
      name: cluster-api-provider-openshift-assisted-preview
----

. Enable the {cim} service. See link:../assisted_installer/ai_enable_cim.adoc#enable-cim[Enabling the {cim} service] for the procedure.

. Configure a `Cluster` resource with `clusterNetwork` specifications, `controlPlaneRef` specifications, and `infrastructureRef` specifications. See the following `Cluster` resource:

+
[source,yaml]
----
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-multinode #should this be <cluster-name>
  namespace: test-capi
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 172.18.0.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef: <1>
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha2 <1>
    kind: OpenshiftAssistedControlPlane
    name: <your-name> # <cluster-name>?
    namespace: <your-namespace>
  infrastructureRef: <2>
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1 <2>
    kind: Metal3Cluster
    name: <your-name>
    namespace: <your-namespace>
----
1. `OpenshiftAssistedControlPlane` is the control plane.
2. `Metal3Cluster` is the infrastructure.

. Apply the YAML content by running the following command:

+
[source,bash]
----
oc apply -f <filename>.yaml
----

. Configure the `OpenshiftAssistedControlPlane` resource that includes the distribution version, API VIPs, and SSH keys. The following YAML defines the control plane configuration, including the distribution version, API VIPs, and SSH keys. See the following YAML sample:

+
[source,yaml]
----
apiVersion: controlplane.cluster.x-k8s.io/v1alpha2
kind: OpenshiftAssistedControlPlane
metadata:
  name: test-multinode
  namespace: test-capi
  annotations: {}
spec:
  openshiftAssistedConfigSpec:
    sshAuthorizedKey: "{{ ssh_authorized_key }}" <1>
    nodeRegistration:
      kubeletExtraLabels:
      - 'metal3.io/uuid="${METADATA_UUID}"'
  distributionVersion: 4.x.0 <2>
  config:
    apiVIPs:
    - 192.168.222.40
    ingressVIPs:
    - 192.168.222.41
    baseDomain: lab.home
    pullSecretRef:
      name: "pull-secret"
    sshAuthorizedKey: "{{ ssh_authorized_key }}" <3>
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3MachineTemplate
      name: test-multinode-controlplane
      namespace: test-capi
  replicas: 3
----
1.`.spec.openshiftAssistedConfigSpec.sshAuthorizedKey` is used to access nodes in the boot (also known as discovery) phase.
2. Specify your {ocp-short} version in the `distributionVersion` field. The value for the `distributionVersion` must match one of the tags from the {ocp-short} release. See link:https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/[{ocp-short} Releases].
3.`.spec.config.sshAuthorizedKey` is used to access the provisioned {ocp-short} nodes.

. Apply the YAML content by running the following command:

+
[source,bash]
----
oc apply -f <filename>.yaml
----

. If you do not have a pull secret, you need to create a pull secret to enable your clusters to pull images from container registries. Complete the following steps to create a pull secret:

. Create a YAML file to pull images. See the following example of a file that is named `pull-secret.yaml`:

+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: <your-namespace> <1>
data:
  .dockerconfigjson: <encoded_docker_configuration> <2>
type: kubernetes.io/dockerconfigjson
----
<1> Ensure that the `namespace` value matches the target namespace.
<2> Specify the base64-encoded configuration file as the value. 

. Run the following command to apply the file:

+
[source,bash]
----
oc apply -f pull-secret.yaml
----

. Configure the `Metal3Cluster` infrastructure resource. 

+
[source,yaml]
----
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: test-multinode
  namespace: test-capi
spec:
  controlPlaneEndpoint:
    host: test-multinode.lab.home <1>
    port: 6443
  noCloudProvider: true
----
1. The `host` is the `<clusterName>.<baseDomain>*` value with the `clusterName` from the `Cluster` resource, and the `baseDomain` is defined in the `OpenshiftAssistedControlPlane` resource.

. Apply the file. Run the following command:

+
[source,bash]
----
oc apply -f <filename>.yaml
----

. Configure the `Metal3MachineTemplate` resource for the control plane nodes that is referenced from the `OpenshiftAssistedControlPlane` resource. See the following YAML sample:

+
[source,yaml]
----
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-multinode-controlplane
  namespace: test-capi
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: test-multinode-controlplane-template
      image: <1>
        checksum: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/4.19.0/sha256sum.txt
        checksumType: sha256
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/4.19.0/rhcos-4.19.0-x86_64-nutanix.x86_64.qcow2
        format: qcow2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
   name: test-multinode-controlplane-template
   namespace: test-capi
spec:
   clusterName: test-multinode <2>
----
1. The `distributionVersion` the version from link:https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/[{ocp-short} Releases].
2. Set the `clusterName` to the same value that it is in the `Cluster` resource


. Apply the file. Run the following command:

+
[source,bash]
----
oc apply -f <filename>.yaml
----

. Configure worker nodes with the `MachineDeployment` resource. See the following example:

+
[source,yaml]
----
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: test-multinode-worker
  namespace: test-capi
  labels:
    cluster.x-k8s.io/cluster-name: test-multinode
spec:
  clusterName: test-multinode
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: test-multinode
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: test-multinode
    spec:
      clusterName: test-multinode
      bootstrap: <1>
        configRef:
          name: test-multinode-worker
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1 
          kind: OpenshiftAssistedConfigTemplate
      infrastructureRef: <2>
        name: test-multinode-workers-2
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: Metal3MachineTemplate
----
1. The bootstrap configuration is also referenced in the next resource for installation.
2. The infrastructure reference points to the resource to provision.

. Apply the file. Run the following command:

+
[source,bash]
----
oc apply -f <filename>.yaml
----

. Create the `OpenshiftAssistedConfigTemplate` resource that is referenced in the `MachineDeployment`. The following YAML defines the bootstrap configuration for worker nodes. This is used to register the nodes with the {ai}.

+
[source,yaml]
----
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: OpenshiftAssistedConfigTemplate
metadata:
  name: test-multinode-worker
  namespace: test-capi
  labels:
    cluster.x-k8s.io/cluster-name: test-multinode
spec:
  template:
    spec:
      nodeRegistration:
        kubeletExtraLabels:
          - 'metal3.io/uuid="${METADATA_UUID}"'<1>
      sshAuthorizedKey: "{{ ssh_authorized_key }}" <2>
----
1. The `kubeletExtraLabels` must be this exact value.
2. Enter your `sshAuthorizedKey`.

. Create the `Metal3MachineTemplate` that is referenced in the `MachineDeployment` resource.

+
[source,yaml]
----
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
   name: test-multinode-workers-2
   namespace: test-capi
spec:
   nodeReuse: false
   template:
      spec:
         automatedCleaningMode: metadata
         dataTemplate:
            name: test-multinode-workers-template
      image:
        checksum: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/4.19.0/sha256sum.txt
        checksumType: sha256
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/4.19.0/rhcos-4.19.0-x86_64-nutanix.x86_64.qcow2
        format: qcow2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
   name: test-multinode-workers-template
   namespace: test-capi
spec:
   clusterName: test-multinode
----

. Run the following command to save the YAML file and provision a cluster.

+
[source,bash]
----
oc apply -f cluster.yaml
----

. Verify that the resources are available. 

.. Run `oc get cluster` to check your `Cluster` resource.

+
See the following output and check for the status:

+
[source,yaml]
----
status:
  conditions:
  - lastTransitionTime: "2025-06-25T11:23:38Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-06-25T11:23:38Z"
    status: "True"
    type: ControlPlaneReady
  - lastTransitionTime: "2025-06-25T10:37:03Z"
    status: "True"
    type: InfrastructureReady
----

.. Run the `oc get metal3cluster --namespace test-capi test-multinode -o yaml` command to check your cluster infrastructure.

+
See the following output and check for the status:

+
[source,yaml]
----
status:
  conditions:
  - lastTransitionTime: "2025-06-25T10:37:03Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-06-25T10:37:03Z"
    status: "True"
    type: BaremetalInfrastructureReady
----

.. Run the `oc get openshiftassistedcontrolplane --namespace test-capi test-multinode -o yaml` command to check your control plane.

+ 
See the following output and check for the status:

+
[source,yaml]
----
status:
  conditions:
  - lastTransitionTime: "2025-06-25T11:23:38Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-06-25T11:23:38Z"
    status: "True"
    type: ControlPlaneReady
  - lastTransitionTime: "2025-06-25T10:45:48Z"
    status: "True"
    type: KubeconfigAvailable
  - lastTransitionTime: "2025-06-25T10:38:25Z"
    status: "True"
    type: MachinesCreated
  - lastTransitionTime: "2025-06-25T11:10:54Z"
    status: "True"
    type: MachinesReady
  - lastTransitionTime: "2025-06-25T11:23:38Z"
    status: "True"
    type: UpgradeCompleted
----

.. Run the `oc get machinedeployment --namespace test-capi test-multinode-worker -o yaml` command to check your machine deployments.

+ 
See the following output and check for the status:

+
[source,yaml]
----
status:
  conditions:
  - lastTransitionTime: "2025-06-25T11:10:29Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-06-25T11:10:29Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-25T11:10:29Z"
    status: "True"
    type: MachineSetReady
----

.. Run the `kubectl get machine -l cluster.x-k8s.io/cluster-name=test-multinode -n test-capi -o yaml` command to check your machines.

+ 
See the following output and check for the status:

+
[source,yaml]
----
 status:
    conditions:
    - lastTransitionTime: "2025-06-25T11:09:57Z"
  	status: "True"
  	type: Ready
    - lastTransitionTime: "2025-06-25T10:38:20Z"
  	status: "True"
  	type: BootstrapReady
    - lastTransitionTime: "2025-06-25T11:09:57Z"
  	status: "True"
  	type: InfrastructureReady
    - lastTransitionTime: "2025-06-25T11:10:29Z"
  	status: "True"
  	type: NodeHealthy
----

. Access the cluster. 

.. Run the following command to get the `kubeconfig` file:

+
[source,bash]
----
oc get secret -n test-capi  test-multinode-admin-kubeconfig -o json | jq -r .data.kubeconfig | base64 --decode > kubeconfig
----

.. Run the following command to use the `kubeconfig` file to access the cluster:

+
[source,bash]
----
export KUBECONFIG=$(realpath kubeconfig)
oc get nodes
----