[#edge-mgr-images]
= Operating system images for the {rhem}

Image-based operating systems allow the operating system and the configuration and applications to be versioned, deployed, and updated as a single unit.

Using an image-based operating system reduces operational risks with the following capability:

* Minimizing drift between tested and deployed environments.
* Reducing failed updates through transactional updates and rollbacks, and reducing maintenance and replacement costs.

The {rhem} focuses on image-based Linux operating systems that run bootable container image (`bootc`). For more information, see https://bootc-dev.github.io/bootc/[bootc].

*Important:* The `bootc` tool does not update package-based operating systems.

Learn how to build images from the following:

* Choose a base `bootc` operating system image, such as a Fedora, CentOS, or RHEL image.
* Create a container file that layers the following items onto the base `bootc` image:
    ** The {rhem} agent and configuration.
    ** Optional: Any drivers specific to your target deployment environment.
    ** Optional: Host configuration, for example certificate authority bundles, and application workloads that are common to all deployments.
* Build, publish, and sign a `bootc` operating system image using `podman` and `skopeo`.
* Create an operating system disk image by using `bootc-image-builder`.
* Build, publish, and sign an operating system disk image using `skopeo`.
 
*Note:* The operating system disk image contains partitions, volumes, the file system, and the initial `bootc` image. The operating system disk image only needs to be created once, during provisioning.

For subsequent device updates, only the `bootc` operating system image is required, which contains the files in the file system.

See the following image building topics:

* xref:../edge_manager/edge_mgr_build_images.adoc#edge-mgr-build[Building a _bootc_ operating system image for the {rhem}]
* xref:../edge_manager/edge_mgr_images_consider.adoc#build-images-consider[Special considerations for building images]
* xref:../edge_manager/edge_mgr_build_images_platform.adoc#edge-mgr-build-platforms[Building for specific target platforms]