[build-images-consider]
= Special considerations for building images
//let's make life easier on ourselves and reduce this file name and anchor...I will do filename when the build is up -- brandi 3/17

The following topics cover special considerations for building images for the {rhem}:

* <<buildtime-runtime,Build-time configuration over dynamic runtime configuration>>
* <<usr-directory,Configuration in `/usr` directory>>
* <<dropin-directory,Drop-in directories>>
* <<os-img-script,Operating system images with scripts>>

[#buildtime-runtime]
== Build-time configuration over dynamic runtime configuration

Add configuration to the operating system image at build time.
Adding configuration at build time ensures that the configurations are tested, distributed, and updated together.
In cases when build-time configuration is not feasible or desirable, you can dynamically configure devices at runtime instead with the {rhem}.

Dynamic runtime configuration is preferable in the following cases:
* You have a configuration that is deployment or site-specific, such as a hostname or a site-specific network credential.
* You have secrets that are not secure to distribute with the image.
* You have application workloads that need to be added, updated, or deleted without reboot or they are on a faster cadence than the operating system.

[#usr-directory]
== Configuration in `/usr` directory

Place configuration files in the `/usr` directory if the configuration is static and the application or service supports that configuration.
By placing the configuration in the `/usr` directory, the configuration remains read-only and fully defined by the image.

It is not feasible or desirable to place the configuration in the `/usr` directory in the following cases:

* The configuration is deployment or site-specific.
* The application or service only supports reading configuration from the `/etc` directory.
* The configuration might need to be changed at runtime. 

[#dropin-directory]
== Drop-in directories

Use drop-in directories to add, replace, or remove configuration files that the service aggregates.
Do not directly edit your configuration files that might cause deviation from the target configuration.

*Note:* You can identify drop-in directories by the `.d/` at the end of the directory name.
For example, `/etc/containers/certs.d`, `/etc/cron.d`, and `/etc/NetworkManager/conf.d`.

[#os-img-script]
== Operating system images with scripts

Avoid executing scripts or commands that change the file system.
The `bootc` or the {rhem} can overwrite the changed files that might cause a deviation or failed integrity checks.

Instead, run such scripts or commands during image building, so changes are part of the image.
Alternatively, use the configuration management mechanisms of the {rhem}.

[#additional-resources-image-consideration]
== Additional resources

* See https://bootc-dev.github.io/bootc/building/guidance.html[Generic guidance for building images].
* For more information about configuring devices at runtime, see xref:../edge_manager/edge_mgr_manage_os_config.adoc#manage-os-config[Operating system configuration for edge devices].

