[#device-resources"]
= Monitoring device resources

You can set up resource monitors for device resources and create alerts when the use of resources crosses a defined threshold. 
When the agent alerts the {rhem} service, the service sets the device status to `degraded` or `error`, depending on the severity level.
The service suspends the rollout of updates and alerts the user.

*Important:* Device resource monitoring does not replace observability solutions.
If your use case requires streaming logs and metrics from devices into an observability stack and the network bandwidth of the device allows this, see Adding Device Observability.
//TODO add link for observability in ACM

Resource monitors take the following parameters:

[%header,cols="1,4]
|===
|Parameter |Description
|`MonitorType` |The resource to monitor.
The `CPU`, `Memory` and `Disk` resources are currently supported.
|`SamplingInterval` |The interval in which the monitor samples use. Specified as a positive integer followed by a time unit: `s` for seconds, `m` for minutes, `h` for hours.
|`AlertRules` |A list of alert rules.
|`Path` |For `Disk` monitor only. The absolute path to the directory to monitor. 
Utilization reflects the file system containing the path, even if the defined path is not a mount point.
|===

Alert rules take the following parameters:

[%header,cols="1,4]
|===
|Parameter |Description
|`Severity` |The severity of the alert rule can be `Info`, `Warning`, or `Critical`. 
Only one alert rule is allowed per severity level and monitor.
|`Duration` |The duration that resource use is measured and averaged over when sampling. Specified as a positive integer followed by a time unit: `s` for seconds, `m` for minutes, `h` for hours. The duration must be smaller than the sampling interval.
|`Percentage` |The usage threshold that triggers the alert, as percentage value. The value ranges from 0 to 100 without the % sign.
|`Description` |A human-readable description of the alert. Add details about the alert to help with debugging. 
By default, the alert description is `load is above >% for more than`.
|===

[#device-resources-cli"]
== Monitoring device resources using the CLI

Monitor the resources of your device through the CLI, providing you with the tools and commands to track performance and troubleshoot issues.
Complete the following steps:

* Add resource monitors in the `spec.resources` section of the device specification. For example, add the following monitor for your disk:

+
[source,yaml]
----
apiVersion: flightctl.io/v1alpha1
kind: Device
metadata:
  name: <device_name>
spec:
[...]
  resources:
  - monitorType: Disk
    samplingInterval: 5s <1> 
    path: /application_data <2>
    alertRules:
    - severity: Warning <3>
      duration: 30m
      percentage: 75
      description: Disk space for application data is >75% full for over 30m.
    - severity: Critical <4>
      duration: 10m
      percentage: 90
      description: Disk space for application data is >90% full over 10m.
[...]
----
<1> Samples usage every 5 seconds.
<2> Checks disk use on the filesystem associated with the `/applications_data` path. 
<3> Triggers a warning if the average use exceeds 75% for more than 30 minutes
<4> Triggers a critical alert if the average use exceeds 90% for over 10 minutes.