[#rhem-enrollment]
= Device enrollment

*Technology Preview:* You need to enroll devices to a {rhem} service before you can start managing them. The {rhem} agent that runs on a device handles the device enrollment.

When the agent starts on a device, the agent searches for the configuration in the `/etc/flightctl/config.yaml` file. The file defines the following configurations:

* The enrollment endpoint, which is the {rhem} service that the agent connects to for enrollment.
* The enrollment certificate, which is the X.509 client certificate and key that the agent only uses to securely request enrollment from the {rhem} service.
* *Optional:* Any additional agent configuration.

The agent starts the enrollment process by searching for the enrollment endpoint, the {rhem} service, that is defined in the configuration file.

After establishing a secure, mTLS-protected network connection with the service, the agent submits an enrollment request to the service.

The request includes a description of hardware and operating system of the device, a X.509 certificate signing request, and the cryptographic identity of the device.

The enrollment request must be approved by an authorized user. After the request is approved, the device becomes trusted and managed by the {rhem} service.

[#enrollment-methods]
== Enrollment methods

You can provision the enrollment endpoint and certificate to the device in the following ways:

Early binding:: You can build an operating system image that includes the enrollment endpoint and certificate.
Devices using an early binding image can automatically connect to the defined {rhem} service to request enrollment, without depending on any provisioning infrastructure.

The devices share the same long-lived X.509 client certificate. However, in this case, the devices are bound to a specific service and owner.

Late binding:: You can define the enrollment endpoint and certificate at provisioning time instead of including them in the operating system image. Devices using a late binding image are not bound to a single owner or service and can have device-specific, short-lived X.509 client certificates.

However, late binding requires virtualization or bare metal provisioning infrastructure that can request device-specific enrollment endpoints and certificates from the {rhem} service and inject them into the provisioned system by using mechanisms such as https://cloud-init.io/[cloud-init], https://coreos.github.io/ignition/supported-platforms/[Ignition], or https://anaconda-installer.readthedocs.io/en/latest/kickstart.html[kickstart].

*Note:* The enrollment certificate is only used to secure the network connection for submitting an enrollment request. The enrollment certificate is not involved in the actual verification or approval of the enrollment request. The enrollment certificate is no longer used with enrolled devices, as the devices rely on device-specific management certificates instead.