[#edge-mgr-images]
= Operating system images for using with the {rhem}

Image-based operating systems allow the operating system and its configuration and applications to be versioned, deployed, and updated as a single unit.
Using an image-based operating system reduces operational risks by doing the following:

* Minimizing potential drift between what is tested and what is deployed to a large number of devices.
* Minimizing the risk of failed updates that require expensive maintenance or replacement through transactional updates and rollbacks.

The {rhem} focuses on image-based Linux operating systems that run bootable container image (`bootc`).
For more information, see https://bootc-dev.github.io/bootc/[bootc].

*Important:* The `bootc` tool does not update package-based operating systems.

For more information, see the _Additional resources_ section.

[#images-process]
== The image building process

At a high level, the image building process works as follows:

. Choose a base `bootc` operating system image, such as a Fedora, CentOS, or RHEL image.
. Create a container file that layers the following items onto the base `bootc` image:
* The {rhem} agent and configuration.
* Optional: Any drivers specific to your target deployment environment.
* Optional: Host configuration, for example certificate authority bundles, and application workloads that are common to all deployments.
. Build, publish, and sign a `bootc` operating system image using `podman` and `skopeo`.
. Create an operating system disk image by using `bootc-image-builder`.
. Build, publish, and sign an operating system disk image using `skopeo`.

*Note:* The operating system disk image contains partitions, volumes, the file system, and the initial `bootc` image.
The operating system disk image only needs to be created once, during provisioning.
For subsequent device updates, only the `bootc` operating system image is required, which contains the files in the file system.

[#additional-resources-rhem-images]
== Additional resources

* See xref:../edge_manager/edge_mgr_build_images.adoc#edge-mgr-build[Building bootc image and disk image with the {rhem}].
* See xref:../edge_manager/edge_mgr_images_special_considerations.adoc#images-special-considerations[Special considerations for building images].