[#edge-mgr-intro]
= {rhem} (Technology Preview)

*Technology Preview:* The {rhem} provides streamlined management of edge devices and applications through a declarative approach. 

By defining the required state of your edge devices, which includes your operating system versions, host configurations, and application deployments, the {rhem} automatically implements and maintains these configurations across your entire device fleet.

By using the {rhem} on {acm}, you can manage non-Kubernetes workloads and your operating system configuration on a Red Hat Enterprise Linux machine consistently with how you manage it on {ocp}.

See the following topics to learn more about using {rhem} on {acm-short}. All features are in *Technology Preview* status:

* xref:../edge_manager/edge_mgr_arch.adoc#rhem-architecture[{rhem} architecture]
* xref:../edge_manager/edge_mgr_enable.adoc#rhem-enable[Enabling the {rhem}]
//* xref:../edge_manager/edge_mgr_provisioning_intro#provisioning-devices-intro[Provisioning devices]
* xref:../edge_manager/edge_mgr_manage_devices_intro.adoc#manage-devices-intro[Managing devices]
* xref:../edge_manager/edge_mgr_fleets.adoc#device_fleets[Device fleets]