[#mce-rbac]
= {mce-short} role-based access control

RBAC is validated at the console level and at the API level. Actions in the console can be enabled or disabled based on user access role permissions. View the following sections for more information on RBAC for specific lifecycles in the product:

* <<overview-of-roles,Overview of roles>>
* <<cluster-lifecycle-RBAC,Cluster lifecycle RBAC>>
** <<cluster-pools-rbac,Cluster pools RBAC>>
** <<console-api-rbac-cluster,Console and API RBAC table for cluster lifecycle>>
** <<credentials-role-based-access-control,Credentials role-based access control>>

[#overview-of-roles]
== Overview of roles

Some product resources are cluster-wide and some are namespace-scoped. You must apply cluster role bindings and namespace role bindings to your users for consistent access controls. View the table list of the following role definitions that are supported:

[#roles-definition]
=== Table of role definition
|===
| Role | Definition

| `cluster-admin`
| This is an {ocp-short} default role. A user with cluster binding to the `cluster-admin` role is an {ocp-short} super user, who has all access. 
| `open-cluster-management:cluster-manager-admin`
| A user with cluster binding to the `open-cluster-management:cluster-manager-admin` role is a super user, who has all access. This role allows the user to create a `ManagedCluster` resource.

| `open-cluster-management:admin:<managed_cluster_name>`
| A user with cluster binding to the `open-cluster-management:admin:<managed_cluster_name>` role has administrator access to the `ManagedCluster` resource named,  `<managed_cluster_name>`. When a user has a managed cluster, this role is automatically created.

| `open-cluster-management:view:<managed_cluster_name>`
| A user with cluster binding to the `open-cluster-management:view:<managed_cluster_name>` role has view access to the `ManagedCluster` resource named,  `<managed_cluster_name>`.

| `open-cluster-management:managedclusterset:admin:<managed_clusterset_name>`
| A user with cluster binding to the `open-cluster-management:managedclusterset:admin:<managed_clusterset_name>` role has administrator access to `ManagedCluster` resource named `<managed_clusterset_name>`. The user also has administrator access to `managedcluster.cluster.open-cluster-management.io`, `clusterclaim.hive.openshift.io`, `clusterdeployment.hive.openshift.io`, and `clusterpool.hive.openshift.io` resources, which has the managed cluster set labels: `cluster.open-cluster-management.io` and `clusterset=<managed_clusterset_name>`. A role binding is automatically generated when you are using a cluster set. See xref:../cluster_lifecycle/create_clusterset.adoc#creating-a-managedclusterset[Creating a _ManagedClusterSet_] to learn how to manage the resource.

| `open-cluster-management:managedclusterset:view:<managed_clusterset_name>`
| A user with cluster binding to the `open-cluster-management:managedclusterset:view:<managed_clusterset_name>` role has view access to the `ManagedCluster` resource named, <managed_clusterset_name>`. The user also has view access to `managedcluster.cluster.open-cluster-management.io`, `clusterclaim.hive.openshift.io`, `clusterdeployment.hive.openshift.io`, and `clusterpool.hive.openshift.io` resources, which has the managed cluster set labels: `cluster.open-cluster-management.io`, `clusterset=<managed_clusterset_name>`. For more details on how to manage managed cluster set resources, see xref:../cluster_lifecycle/create_clusterset.adoc#creating-a-managedclusterset[Creating a _ManagedClusterSet_].

| `admin, edit, view`
| Admin, edit, and view are {ocp-short} default roles. A user with a namespace-scoped binding to these roles has access to `open-cluster-management` resources in a specific namespace, while cluster-wide binding to the same roles gives access to all of the `open-cluster-management` resources cluster-wide.
|===

*Important*:

* Any user can create projects from {ocp-short}, which gives administrator role permissions for the namespace.

* If a user does not have role access to a cluster, the cluster name is not visible. The cluster name is displayed with the following symbol: `-`.

RBAC is validated at the console level and at the API level. Actions in the console can be enabled or disabled based on user access role permissions. View the following sections for more information on RBAC for specific lifecycles in the product.

[#cluster-lifecycle-RBAC]
== Cluster lifecycle RBAC

View the following cluster lifecycle RBAC operations:

- Create and administer cluster role bindings for all managed clusters. For example, create a cluster role binding to the cluster role `open-cluster-management:cluster-manager-admin` by entering the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:cluster-manager-admin --user=<username>
----
+
This role is a super user, which has access to all resources and actions. You can create cluster-scoped `managedcluster` resources, the namespace for the resources that manage the managed cluster, and the resources in the namespace with this role. You might need to add the `username` of the ID that requires the role association to avoid permission errors.

- Run the following command to administer a cluster role binding for a managed cluster named `cluster-name`:
+
----
oc create clusterrolebinding (role-binding-name) --clusterrole=open-cluster-management:admin:<cluster-name> --user=<username>
----
+
This role has read and write access to the cluster-scoped `managedcluster` resource. This is needed because the `managedcluster` is a cluster-scoped resource and not a namespace-scoped resource.

** Create a namespace role binding to the cluster role `admin` by entering the following command:
+
----
oc create rolebinding <role-binding-name> -n <cluster-name> --clusterrole=admin --user=<username>
----
+
This role has read and write access to the resources in the namespace of the managed cluster.


- Create a cluster role binding for the `open-cluster-management:view:<cluster-name>` cluster role to view a managed cluster named `cluster-name` Enter the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:view:<cluster-name> --user=<username>
----
+
This role has read access to the cluster-scoped `managedcluster` resource. This is needed because the `managedcluster` is a cluster-scoped resource.


- Create a namespace role binding to the cluster role `view` by entering the following command:
+
----
oc create rolebinding <role-binding-name> -n <cluster-name> --clusterrole=view --user=<username>
----
+
This role has read-only access to the resources in the namespace of the managed cluster.

- View a list of the managed clusters that you can access by entering the following command:
+
----
oc get managedclusters.clusterview.open-cluster-management.io
----
+
This command is used by administrators and users without cluster administrator privileges.

- View a list of the managed cluster sets that you can access by entering the following command:
+
----
oc get managedclustersets.clusterview.open-cluster-management.io
----
+
This command is used by administrators and users without cluster administrator privileges.

[#cluster-pools-rbac]
=== Cluster pools RBAC

View the following cluster pool RBAC operations:

** As a cluster administrator, use cluster pool provision clusters by creating a managed cluster set and grant administrator permission to roles by adding the role to the group. View the following examples:
+
- Grant `admin` permission to the `server-foundation-clusterset` managed cluster set with the following command:
+
----
oc adm policy add-cluster-role-to-group open-cluster-management:clusterset-admin:server-foundation-clusterset 
server-foundation-team-admin
----
+
- Grant `view` permission to the `server-foundation-clusterset` managed cluster set with the following command:
+
----
oc adm policy add-cluster-role-to-group open-cluster-management:clusterset-view:server-foundation-clusterset server-foundation-team-user
----

** Create a namespace for the cluster pool, `server-foundation-clusterpool`. View the following examples to grant role permissions:
+
- Grant `admin` permission to `server-foundation-clusterpool` for the `server-foundation-team-admin` by running the following commands:
+
----
oc adm new-project server-foundation-clusterpool

oc adm policy add-role-to-group admin server-foundation-team-admin --namespace  server-foundation-clusterpool
----

** As a team administrator, create a cluster pool named `ocp46-aws-clusterpool` with a cluster set label, `cluster.open-cluster-management.io/clusterset=server-foundation-clusterset` in the cluster pool namespace:
+
- The `server-foundation-webhook` checks if the cluster pool has the cluster set label, and if the user has permission to create cluster pools in the cluster set.
+
- The `server-foundation-controller` grants `view` permission to the `server-foundation-clusterpool` namespace for `server-foundation-team-user`.

** When a cluster pool is created, the cluster pool creates a `clusterdeployment`. Continue reading for more details:
+
- The `server-foundation-controller` grants `admin` permission to the `clusterdeployment` namespace for `server-foundation-team-admin`.

- The `server-foundation-controller` grants `view` permission `clusterdeployment` namespace for `server-foundation-team-user`.
+
*Note:* As a `team-admin` and `team-user`, you have `admin` permission to the `clusterpool`, `clusterdeployment`, and `clusterclaim`.

[#console-api-rbac-cluster]
=== Console and API RBAC table for cluster lifecycle

View the following console and API RBAC tables for cluster lifecycle:

.Console RBAC table for cluster lifecycle
|===
| Resource | Admin | Edit | View 

| Clusters
| read, update, delete
| -
| read

| Cluster sets
| get, update, bind, join
| edit role not mentioned
| get


| Managed clusters
| read, update, delete
| no edit role mentioned
| get

| Provider connections
| create, read, update, and delete
| -
| read

|===

.API RBAC table for cluster lifecycle
|===
| API | Admin | Edit | View


| `managedclusters.cluster.open-cluster-management.io`  

_You can use `mcl` (singular) or `mcls` (plural) in commands for this API._
| create, read, update, delete
| read, update
| read

| `managedclusters.view.open-cluster-management.io`

_You can use `mcv` (singular) or `mcvs` (plural) in commands for this API._
| read
| read
| read

| `managedclusters.register.open-cluster-management.io/accept`
| update
| update
| 

| `managedclusterset.cluster.open-cluster-management.io`  

_You can use `mclset` (singular) or `mclsets` (plural) in commands for this API._
| create, read, update, delete
| read, update
| read

| `managedclustersets.view.open-cluster-management.io`
| read
| read
| read

| `managedclustersetbinding.cluster.open-cluster-management.io`  

_You can use `mclsetbinding` (singular) or `mclsetbindings` (plural) in commands for this API._
| create, read, update, delete
| read, update
| read

| `klusterletaddonconfigs.agent.open-cluster-management.io`
| create, read, update, delete
| read, update
| read

| `managedclusteractions.action.open-cluster-management.io`
| create, read, update, delete
| read, update
| read

| `managedclusterviews.view.open-cluster-management.io`
| create, read, update, delete
| read, update
| read

| `managedclusterinfos.internal.open-cluster-management.io`
| create, read, update, delete
| read, update
| read

| `manifestworks.work.open-cluster-management.io`
| create, read, update, delete
| read, update
| read

| `submarinerconfigs.submarineraddon.open-cluster-management.io`
| create, read, update, delete
| read, update
| read

| `placements.cluster.open-cluster-management.io`
| create, read, update, delete
| read, update
| read
|===

[#credentials-role-based-access-control]
=== Credentials role-based access control

The access to credentials is controlled by Kubernetes. Credentials are stored and secured as Kubernetes secrets. The following permissions apply to accessing secrets in {acm}:

* Users with access to create secrets in a namespace can create credentials.
* Users with access to read secrets in a namespace can also view credentials.
* Users with the Kubernetes cluster roles of `admin` and `edit` can create and edit secrets.
* Users with the Kubernetes cluster role of `view` cannot view secrets because reading the contents of secrets enables access to service account credentials.
