[#discovery-enable-cli]
= Enable Discovery using the CLI

Enable discovery using the CLI to find clusters that are available from Red Hat OpenShift Cluster Manager.

**Required access**: Administrator

[#enable-prerequisites]
== Prerequisites

* Create a credential to connect to Red Hat OpenShift Cluster Manager.

[#setup-discovery]
== Discovery set up and process

*Note:* The `DiscoveryConfig` must be named `discovery` and must be created in the same namespace as the selected `credential`. See the following `DiscoveryConfig` sample:

[source,yaml]
----
apiVersion: discovery.open-cluster-management.io/v1
kind: DiscoveryConfig
metadata:
  name: discovery
  namespace: <NAMESPACE_NAME>
spec:
  credential: <SECRET_NAME>
  filters:
    lastActive: 7
    openshiftVersions:
    - "4.10"
    - "4.11"
    - "4.8"
----

. Replace `SECRET_NAME` with the credential that you previously set up.
. Replace `NAMESPACE_NAME` with the namespace of `SECRET_NAME`.
. Enter the maximum time since last activity of your clusters (in days) to discover. For example, with `lastActive: 7`, clusters that active in the last 7 days are discovered.
. Enter the versions of Red Hat OpenShift clusters to discover as a list of strings. *Note:* Every entry in the `openshiftVersions` list specifies an OpenShift major and minor version. For example, specifying `"4.11"` will include all patch releases for the OpenShift version `4.11`, for example `4.11.1`, `4.11.2`.

[#view-discovered-cluster]
== View discovered clusters 

View discovered clusters by running `oc get discoveredclusters -n <namespace>` where `namespace` is the namespace where the discovery credential exists.

[#discovered-clusters]
=== DiscoveredClusters

Objects are created by the Discovery controller. These `DiscoveredClusters` represent the clusters that are found in OpenShift Cluster Manager by using the filters and credentials that are specified in the `DiscoveryConfig` `discoveredclusters.discovery.open-cluster-management.io` API. The value for `name` is the cluster external ID:

[source,yaml]
----
apiVersion: discovery.open-cluster-management.io/v1
kind: DiscoveredCluster
metadata:
  name: fd51aafa-95a8-41f7-a992-6fb95eed3c8e
  namespace: <NAMESPACE_NAME>
spec:
  activity_timestamp: "2021-04-19T21:06:14Z"
  cloudProvider: vsphere
  console: https://console-openshift-console.apps.qe1-vmware-pkt.dev02.red-chesterfield.com
  creation_timestamp: "2021-04-19T16:29:53Z"
  credential:
    apiVersion: v1
    kind: Secret
    name: <SECRET_NAME>
    namespace: <NAMESPACE_NAME>
  display_name: qe1-vmware-pkt.dev02.red-chesterfield.com
  name: fd51aafa-95a8-41f7-a992-6fb95eed3c8e
  openshiftVersion: 4.10
  status: Stale
----




