[#certificates-byo]
= Bringing your own observability Certificate Authority (CA) certificates

When you install {acm}, only Certificate Authority (CA) certificates for observability are provided by default. If you do not want to use the default observability CA certificates generated by {acm-short}, you can choose to bring your own observability CA certificates before you enable observability.

[#openssl-commands-ca]
== Generating CA certificates by using OpenSSL commands

Observability requires two CA certificates, one for the server-side and the other is for the client-side.

* Generate your CA RSA private keys with the following commands:

+
[source,bash]
----
openssl genrsa -out serverCAKey.pem 2048
openssl genrsa -out clientCAKey.pem 2048
----

* Generate the self-signed CA certificates using the private keys. Run the following commands:

+
[source,bash]
----
openssl req -x509 -sha256 -new -nodes -key serverCAKey.pem -days 1825 -out serverCACert.pem
openssl req -x509 -sha256 -new -nodes -key clientCAKey.pem -days 1825 -out clientCACert.pem
----

[#create-secrets-byo-certs]
== Creating the secrets associated with your own observability CA certificates

Complete the following steps to create the secrets:

. Create the `observability-server-ca-certs` secret by using your certificate and private key. Run the following command:

+
[source,bash]
----
oc -n open-cluster-management-observability create secret tls observability-server-ca-certs --cert ./serverCACert.pem --key ./serverCAKey.pem
----

. Create the `observability-client-ca-certs` secret by using your certificate and private key. Run the following command:

+
[source,bash]
----
oc -n open-cluster-management-observability create secret tls observability-client-ca-certs --cert ./clientCACert.pem --key ./clientCAKey.pem
----

[#replace-cert-rbac]
== Replacing certificates for _rbac-query-proxy_ route

You can replace certificates for the `rbac-query-proxy` route. See xref:../secure_cluster/cert_byo.adoc#openssl-commands-ca[Generating CA certificates by using OpenSSL commands] to create certificates.

When you create a Certificate Signing Request (CSR) by using the `csr.cnf` file, update the `DNS.1` field in the `subjectAltName` section to match the host name of the `rbac-query-proxy` route.

Complete the following steps:

. Retrieve the host name by running the following command:

+
[source,bash]
----
oc get route rbac-query-proxy -n open-cluster-management-observability -o jsonpath="
{.spec.host}"
----

. Run the following command to create a `proxy-byo-ca` secret by using the generated certificates:

+
[source,bash]
----
oc -n open-cluster-management-observability create secret tls proxy-byo-ca --cert ./ca.crt --key ./ca.key
----

. Run the following command to create a `proxy-byo-cert` secret by using the generated certificates:

+
[source,bash]
----
oc -n open-cluster-management-observability create secret tls proxy-byo-cert --cert ./ingress.crt --key ./ingress.key
----

[#additional-resources-cert-byo]
== Additional resources

- See link:../observability/customize_observability.adoc#customizing-route-cert[Customizing route certification].
- See link:../observability/customize_observability.adoc#customizing-certificates-object-store[Customizing certificates for accessing the object store].
