[#fine-grain-rbac]
= Managing fine-grained role-based access control

{acm} supports fine-grained role-based access control (RBAC). As a cluster administrator, you can manage and control permissions at the namespace level on managed clusters rather than at the cluster level. Grant permissions to a namespace without granting permission to the entire managed cluster, or virtual machine. 

*Required access:* Cluster administrator

*Note:* Action buttons are disabled from the console if the user-role access is impermissible.

If you installed operators that create cluster roles, you do not need to create them. You can create `clusterroles` manually if you need to create them. 

To learn about {ocp-short} default and virtualization roles and permissions, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/virtualization/about#authorization_virt-security-policies[Authorization] in the {ocp-short} documentation.

See xref:../secure_cluster/rbac_implement_rhacm.adoc#rhacm-rbac-implement[Implementing role-based access control] for more details about {acm-short} role-based access.

You can grant access to the following roles for {ocp-virt-short}, which are extensions of the default roles:

- `kubevirt.io:view`: only view resources
- `kubevirt.io:edit`: modify resources
- `kubevirt.io:admin`: view, modify, delete resources; grant permissions

.Prerequisites

See the following requirement to manage fine-grained role-based access control:

. In your `MultiClusterHub` custom resource `spec.overrides.components` field, set `fine-grained-rbac-preview` to `true` to enable the feature.
. In your `MultiClusterHub` custom resource `spec.overrides.components` field, set `search` to `enabled` to retrieve a list of managed clusters namespaces that can represent virtual machines that are used for access control.
. On the hub cluster, label `clusterroles` with the `rbac.open-cluster-management.io/filter=vm-clusterroles` filter so that you see cluster roles in the console when you create or edit cluster permissions.
. Ensure you have virtual machines by creating or migrating them on the hub cluster, which gives the managed cluster namespaces.
. Verify that the `ClusterPermission` resource is created and is in ready status.

[#assign-fine-grain-rbac]
== Assigning fine-grained role-based access control

You can assign users to manage virtual machines with fine-grained role-based access control. 

. As a cluster administrator, click *AccessControlManagement* > *Add Access Control* in the console.
. *Optional:* Click the *YAML* option on to see the metadata that you enter populate in the *Access Control YAML* window.
. Add the `Basic information`, such as the cluster name and the user.
. Add the `Role Binding` information.
. Add the `Cluster Role Binding` information.
. Review and click *Add*.

See the following example of the `ClusterRole` resource, with roles for {ocp-virt-short} and the `ClusterRoleBinding`resource:

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acm-vm-rbac-required
rules:
- apiGroups: ["clusterview.open-cluster-management.io"]
  resources: ["kubevirtprojects"]
  verbs: ["list"]
- apiGroups: ["clusterview.open-cluster-management.io"]
  resources: ["managedclusters"]
  verbs: ["list","get","watch"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters"]
  verbs: ["get"]
  resourceNames: ["cluster01", "cluster02", "cluster03"]
- apiGroups: ["view.open-cluster-management.io"]
  resources: ["managedclusterviews"]
  verbs: ["create", "get", "delete"]
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachines"]
  verbs: ["delete"]
- apiGroups: ["action.open-cluster-management.io"]
  resources: ["managedclusteractions"]
  verbs: ["create", "get", "delete"]
- apiGroups: ["snapshot.kubevirt.io"]
  resources: ["virtualmachinesnapshots"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acm-vm-rbac-required
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acm-vm-rbac-required
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user1
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: group1
----