[#ansible-config-cluster]
= Configuring {aap-short} tasks to run on managed clusters

{mce-short} is integrated with {aap} so that you can create prehook and posthook Ansible job instances that occur before or after creating or upgrading your clusters. Configuring prehook and posthook jobs for cluster destroy, and cluster scale actions are not supported.

*Required access:* Cluster administrator

* <<prerequisites-for-ansible-integration-cluster,Prerequisites>>
* <<ansible-template-run-cluster-console,Configuring an Automation template to run on a cluster by using the console>>
* <<ansible-template-create,Creating an Automation template>>
* <<ansible-status-job-cluster,Viewing the status of an Ansible job>>

[#prerequisites-for-ansible-integration-cluster]
== Prerequisites

You must meet the following prerequisites to run Automation templates on your clusters:

* {ocp-short} 4.12 or later

* Install the {aap-short} Resource Operator to connect Ansible jobs to the lifecycle of Git subscriptions. For best results when using the Automation template to launch {aap-short} jobs, the {aap-short} job template should be idempotent when it is run. You can find the {aap-short} Resource Operator in the {ocp-short} _OperatorHub_. 


[#ansible-template-run-cluster-console]
== Configuring an _Automation_ template to run on a cluster by using the console

You can specify the Automation template that you want to use for a cluster when you create the cluster, when you import the cluster, or after you create the cluster.

To specify the template when creating or importing a cluster, select the Ansible template that you want to apply to the cluster in the _Automation_ step. If there are no Automation templates, click *Add automation template* to create one.

To specify the template after creating a cluster, click *Update automation template* in the action menu of an existing cluster. You can also use the *Update automation template* option to update an existing automation template.

[#ansible-template-create]
== Creating an Automation template

To initiate an Ansible job with a cluster installation or upgrade, you must create an Automation template to specify when you want the jobs to run. They can be configured to run before or after the cluster installs or upgrades.

To specify the details about running the Ansible template while creating a template, complete the steps in the console:

. Select *Infrastructure* > *Automation* from the navigation.

. Select the applicable path for your situation:  
+
* If you want to create a new template, click *Create Ansible template* and continue with step 3.

* If you want to modify an existing template, click *Edit template* from the _Options_ menu of the template that you want to modify and continue with step 5.

. Enter a unique name for your template, which contains lowercase alphanumeric characters or a hyphen (-).

. Select the credential that you want to use for the new template.
. After you select a credential, you can select an Ansible inventory to use for all the jobs. To link an Ansible credential to an Ansible template, complete the following steps:
 
.. From the navigation, select *Automation*. Any template in the list of templates that is not linked to a credential contains a *Link to credential* icon that you can use to link the template to an existing credential. Only the credentials in the same namespace as the template are displayed.

.. If there are no credentials that you can select, or if you do not want to use an existing credential, select *Edit template* from the _Options_ menu for the template that you want to link.

.. Click *Add credential* and complete the procedure in xref:../credentials/credential_ansible.adoc#creating-a-credential-for-ansible[Creating a credential for {aap-short}] if you have to create your credential.

.. After you create your credential in the same namespace as the template, select the credential in the _{aap-short} credential_ field when you edit the template. 

. If you want to initiate any Ansible jobs before the cluster is installed, select *Add an Automation template* in the _Pre-install Automation templates_ section.

. Select between a `Job template` or a `Workflow job template` in the modal that appears. You can also add `job_tags`, `skip_tags`, and workflow types.
+
* Use the *Extra variables* field to pass data to the `AnsibleJob` resource in the form of `key=value` pairs. 

* Special keys `cluster_deployment` and `install_config` are passed automatically as extra variables. They contain general information about the cluster and details about the cluster installation configuration. 

. Select the name of the prehook and posthook Ansible jobs to add to the installation or upgrade of the cluster. 

. Drag the Ansible jobs to change the order, if necessary.  

. Repeat steps 5 - 7 for any Automation templates that you want to initiate after the cluster is installed in the _Post-install Automation templates_ section, the _Pre-upgrade Automation templates_ section, and the _Post-upgrade Automation templates_ section. When upgrading a cluster, you can use the `Extra variables` field to pass data to the `AnsibleJob` resource in the form of `key=value` pairs. In addition to the `cluster_deployment` and `install_config` special keys, the `cluster_info` special key is also passed automatically as an extra variable containing data from the `ManagedClusterInfo` resource.

Your Ansible template is configured to run on clusters that specify this template when the designated actions occur. 

[#ansible-status-job-cluster]
== Viewing the status of an Ansible job

You can view the status of a running Ansible job to ensure that it started, and is running successfully. To view the current status of a running Ansible job, complete the following steps: 

. In the menu, select *Infrastructure* > *Clusters* to access the _Clusters_ page.

. Select the name of the cluster to view its details.

. View the status of the last run of the Ansible job on the cluster information. The entry shows one of the following statuses:
+
* When an install prehook or posthook job fails, the cluster status shows `Failed`.
* When an upgrade prehook or posthook job fails, a warning is displayed in the _Distribution_ field that the upgrade failed.

[#ansible-rerun-job-cluster]
== Running a failed Ansible job again

You can retry an upgrade from the _Clusters_ page if the cluster prehook or posthook failed.

To save time, you can also run only the failed Ansible posthooks that are part of cluster automation templates. Complete the following steps to run only the posthooks again, without retrying the entire upgrade:

. Add the following content to the root of the `ClusterCurator` resource to run the install posthook again:
+
[source,yaml]
----
operation:
  retryPosthook: installPosthook
----

. Add the following content to the root of the `ClusterCurator` resource to run the upgrade posthook again:
+
[source,yaml]
----
operation:
  retryPosthook: upgradePosthook
----

After adding the content, a new job is created to run the Ansible posthook.

[#specify-ansible-inventory]
== Specifying an Ansible inventory to use for all jobs

You can use the `ClusterCurator` resource to specify an Ansible inventory to use for all jobs. See the following example:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: test-inno
  namespace: test-inno
spec:
  desiredCuration: upgrade
  destroy: {}
  install: {}
  scale: {}
  upgrade:
    channel: stable-4.13
    desiredUpdate: 4.13.1
    monitorTimeout: 150
    posthook:
    - extra_vars: {}
      clusterName: test-inno
      type: post_check
      name: ACM Upgrade Checks
    prehook:
    - extra_vars: {}
      clusterName: test-inno
      type: pre_check
      name: ACM Upgrade Checks
    towerAuthSecret: awx
----

To verify that the inventory is created, you can check the `status` field in the `ClusterCurator` resource for messages specifying that all jobs completed successfully.
 
