[#ansible-config-hosted-cluster]
= Configuring {aap-short} jobs to run on hosted clusters

{aap} is integrated with {mce-short} so that you can create prehook and posthook {aap-short} job instances that occur before or after you create or update hosted clusters.

*Required access:* Cluster administrator

* <<ansible-hosted-cluster-install,Running an {aap-short} job to install a hosted cluster>>
* <<ansible-hosted-cluster-update,Running an {aap-short} job to update a hosted cluster>>
* <<ansible-hosted-cluster-delete,Running an {aap-short} job to delete a hosted cluster>>

.Prerequisites

You must meet the following prerequisites to run Automation templates on your clusters:

* A supported version of {ocp-short}

* Install the {aap-short} Resource Operator to connect {aap-short} jobs to the lifecycle of Git subscriptions. When you use the Automation template to start {aap-short} jobs, ensure that the {aap-short} job template is idempotent when it is run. You can find the {aap-short} Resource Operator in the {ocp-catalog}. 

[#ansible-hosted-cluster-install]
== Running an {aap-short} job to install a hosted cluster

To start an {aap-short} job that installs a hosted cluster, complete the following steps:

. Create the `HostedCluster` and `NodePool` resources, including the `pausedUntil: true` field. If you use the `hcp create cluster` command line interface command, you can specify the `--pausedUntil: true` flag.

+
See the following examples:

+
[source,yaml]
----
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: my-cluster
  namespace: clusters
spec:
  pausedUntil: 'true'
----

+
[source,yaml]
----
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: my-cluster-us-east-2
  namespace: clusters
spec:
  pausedUntil: 'true'
----

. Create a `ClusterCurator` resource with the same name as the `HostedCluster` resource and in the same namespace as the `HostedCluster` resource. See the following example:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: my-cluster
  namespace: clusters
  labels:
    open-cluster-management: curator
spec:
  desiredCuration: install
  install:
    jobMonitorTimeout: 5
    prehook:
      - name: Demo Job Template
        extra_vars:
          variable1: something-interesting
          variable2: 2
      - name: Demo Job Template
    posthook:
      - name: Demo Job Template
    towerAuthSecret: toweraccess
----

. If your {aap-short} Tower requires authentication, create a secret resource. See the following example:

+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: toweraccess
  namespace: clusters
stringData:
  host: https://my-tower-domain.io
  token: ANSIBLE_TOKEN_FOR_admin
----

[#ansible-hosted-cluster-update]
== Running an {aap-short} job to update a hosted cluster

To run an {aap-short} job that updates a hosted cluster, edit the `ClusterCurator` resource of the hosted cluster that you want to update. See the following example:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: my-cluster
  namespace: clusters
  labels:
    open-cluster-management: curator
spec:
  desiredCuration: upgrade
  upgrade:
    desiredUpdate: 4.17.1 <1>
    monitorTimeout: 120
    prehook:
      - name: Demo Job Template
        extra_vars:
          variable1: something-interesting
          variable2: 2
      - name: Demo Job Template
    posthook:
      - name: Demo Job Template
    towerAuthSecret: toweraccess
----

<1> For details about supported versions, see _Hosted control planes_.

== Running an {aap-short} job to update the control plane and specific node pools

To run an {aap-short} job that updates the control plane and specific node pools, edit the `nodePoolNames` field in your `ClusterCurator` resource of the hosted cluster that you want to update. See the following example:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: my-hosted-cluster
  namespace: clusters
spec:
  desiredCuration: upgrade
  upgrade:
    desiredUpdate: "4.17.1"
    nodePoolNames:
      - my-nodepool-1
      - my-nodepool-2
----

== Running an {aap-short} job to update the control plane

To run an {aap-short} job that updates the control plane, set the `upgradeType` field to `ControlPlane` in your `ClusterCurator` resource of the hosted cluster that you want to update. See the following example:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: my-hosted-cluster
  namespace: clusters
spec:
  desiredCuration: upgrade
  upgrade:
    desiredUpdate: "4.17.1"
    upgradeType: ControlPlane
----

== Running an {aap-short} job to update the node pools

To run an {aap-short} job that updates all node pools associated with your hosted cluster, set the `upgradeType` field to `NodePools` in your `ClusterCurator` resource that you want to update. See the following example:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: my-hosted-cluster
  namespace: clusters
spec:
  desiredCuration: upgrade
  upgrade:
    desiredUpdate: "4.17.1"
    upgradeType: NodePools
----

== Running an {aap-short} job to update specific node pools

To run an {aap-short} job that updates only specific node pools, set the `upgradeType` field to `NodePools` in your `ClusterCurator` resource and list the node pools that you want to update in the `nodePoolNames` field. See the following example:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: my-hosted-cluster
  namespace: clusters
spec:
  desiredCuration: upgrade
  upgrade:
    desiredUpdate: "4.17.1"
    upgradeType: NodePools
    nodePoolNames:
      - my-nodepool-1
      - my-nodepool-2
----

== Running an {aap-short} job to update the cluster channel

To run an {aap-short} job that updates the cluster channel without changing the version, add the cluster channel to the `channel` field. See the following example:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: my-hosted-cluster
  namespace: clusters
spec:
  desiredCuration: upgrade
  upgrade:
    channel: "fast-4.17"
----

== Running an {aap-short} job to update the cluster version and channel

To run an {aap-short} job that updates the cluster version and channel, add the cluster version to the channel to the `desiredUpdate` field and add the cluster channel to the `channel` field. See the following example:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: my-hosted-cluster
  namespace: clusters
spec:
  desiredCuration: upgrade
  upgrade:
    desiredUpdate: "4.17.1"
    channel: "fast-4.17"
----

[#ansible-hosted-cluster-delete]
== Running an {aap-short} job to delete a hosted cluster

To run an {aap-short} job that deletes a hosted cluster, edit the `ClusterCurator` resource of the hosted cluster that you want to delete. See the following example:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: my-cluster
  namespace: clusters
  labels:
    open-cluster-management: curator
spec:
  desiredCuration: destroy
  destroy:
    jobMonitorTimeout: 5
    prehook:
      - name: Demo Job Template
        extra_vars:
          variable1: something-interesting
          variable2: 2
      - name: Demo Job Template
    posthook:
      - name: Demo Job Template
    towerAuthSecret: toweraccess
----

*Note:* Deleting a hosted cluster on AWS is not supported.

[#ansible-hosted-cluster-additional-resources]
== Additional resources

* For more information about the hosted control plane command line interface, `hcp`, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/hosted_control_planes/preparing-to-deploy-hosted-control-planes#installing-the-hosted-control-plane-command-line-interface[Installing the hosted control planes command-line interface]. 

* For more information about hosted clusters, including supported versions, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/hosted_control_planes/hosted-control-planes-overview#hosted-control-planes-overview_hcp-overview[Introduction to hosted control planes]. 
