[#add-host-host-inventory]
= Adding hosts to the host inventory by using the Discovery Image

After creating your host inventory (infrastructure environment), you can discover your hosts and add them to your inventory. To add hosts to your inventory, choose a method to download an ISO file and attach it to each server. For example, you can download ISO files by using a virtual media, or by writing the ISO to a USB drive.

*Important:* To prevent the installation from failing, keep the Discovery ISO media connected to the device during the installation process and set each host to boot from the device one time.

[#add-host-prereqs]
== Prerequisites

- You must enable the central infrastructure management service. See _Enabling the central infrastructure management service_ for more information.
- You must create a host inventory. See _Creating a host inventory by using the console_ for more information.

[#add-host-steps-console]
== Adding hosts by using the console

Download the ISO file by completing the following steps:

. Select *Infrastructure* > *Host inventory* in the console.

. Select your infrastructure environment from the list.

. Click *Add hosts* and select *With Discovery ISO*.

+
You now see a URL to download the ISO file. Booted hosts appear in the host inventory table. Hosts might take a few minutes to appear. 

+
*Note:* By default, the ISO that is provided is a _minimal_ ISO. The minimal ISO does not contain the root file system, `RootFS`. The `RootFS` is downloaded later. To get the full ISO, replace `minimal.iso` in the URL with `full.iso`.

. Approve each host so that you can use it. You can select hosts from the inventory table by clicking *Actions* and selecting *Approve*.

[#add-host-steps-cli]
== Adding hosts by using the command line interface

The URL to download the ISO file in the `isoDownloadURL` property is in the status of your `InfraEnv` resource. See _Creating a host inventory by using the command line interface_ for more information about the `InfraEnv` resource.

Each booted host creates an `Agent` resource in the same namespace. 

1. Run the following command to view the download URL in the `InfraEnv` custom resource:

+
[source,bash]
----
oc get infraenv -n <infra env namespace> <infra env name> -o jsonpath='{.status.isoDownloadURL}'
----

+
See the following output:

+
[source,bash]
----
https://assisted-image-service-assisted-installer.apps.example-acm-hub.com/byapikey/eyJhbGciOiJFUzI1NiIsInC93XVCJ9.eyJpbmZyYV9lbnZfaWQcTA0Y38sWVjYi02MTA0LTQ4NDMtODasdkOGIxYTZkZGM5ZTUifQ.3ydTpHaXJmTasd7uDp2NvGUFRKin3Z9Qct3lvDky1N-5zj3KsRePhAM48aUccBqmucGt3g/4.16/x86_64/minimal.iso
----

. Use the URL to download the ISO file and boot your hosts with the ISO file.

. Approve each host.

[#additional-resources-add-host]
== Additional resources

- See xref:../cluster_lifecycle/cim_enable.adoc#enable-cim[Enabling the central infrastructure management service]
- See xref:../cluster_lifecycle/cim_create_console.adoc#create-host-inventory-console[Creating a host inventory by using the console]
- See xref:../cluster_lifecycle/cim_create_cli.adoc#create-host-inventory-cli[Creating a host inventory by using the command line interface]
