[#create-host-inventory-console]
= Creating a host inventory by using the console

You can create a host inventory (infrastructure environment) to discover physical or virtual machines that you can install your {ocp-short} clusters on.

[#create-host-inventory-prereqs-console]
== Prerequisites

- You must enable the central infrastructure management service. See _Enabling the central infrastructure management service_ for more information.

[#create-host-inventory-console-steps]
== Creating a host inventory

Complete the following steps to create a host inventory by using the console:

. From the console, navigate to *Infrastructure* > *Host inventory* and click *Create infrastructure environment*.
. Add the following information to your host inventory settings:
+
- Name: A unique name for your infrastructure environment. Creating an infrastructure environment by using the console also creates a new namespace for the `InfraEnv` resource with the name you chose. If you create `InfraEnv` resources by using the command line interface and want to monitor the resources in the console, use the same name for your namespace and the `InfraEnv`.
- Network type: Specifies if the hosts you add to your infrastructure environment use DHCP or static networking. Static networking configuration requires additional steps.
- Location: Specifies the geographic location of the hosts. The geographic location can be used to define which data center the hosts are located.
- Labels: Optional field where you can add labels to the hosts that are discovered with this infrastructure environment. The specified location is automatically added to the list of labels.
- Infrastructure provider credentials: Selecting an infrastructure provider credential automatically populates the pull secret and SSH public key fields with information in the credential. For more information, see _Creating a credential for an on-premises environment_.
- Pull secret: Your {ocp-short} link:https://console.redhat.com/openshift/install/pull-secret[pull secret] that enables you to access the {ocp-short} resources. This field is automatically populated if you selected an infrastructure provider credential.
- SSH public key: The SSH key that enables the secure communication with the hosts. You can use it to connect to the host for troubleshooting. After installing a cluster, you can no longer connect to the host with the SSH key. The key is generally in your `id_rsa.pub` file. The default file path is `~/.ssh/id_rsa.pub`. This field is automatically populated if you selected an infrastructure provider credential that contains the value of a SSH public key. 
- If you want to enable proxy settings for your hosts, select the setting to enable it and enter the following information:
** HTTP Proxy URL: The URL of the proxy for HTTP requests.
** HTTPS Proxy URL: The URL of the proxy for HTTP requests. The URL must start with HTTP. HTTPS is not supported. If you do not provide a value, your HTTP proxy URL is used by default for both HTTP and HTTPS connections.
** No Proxy domains: A list of domains separated by commas that you do not want to use the proxy with. Start a domain name with a period (`.`) to include all of the subdomains that are in that domain. Add an asterisk (`*`) to bypass the proxy for all destinations.
- Optionally add your own Network Time Protocol (NTP) sources by providing a comma separated list of IP or domain names of the NTP pools or servers.

If you need advanced configuration options that are not available in the console, continue to _Creating a host inventory by using the command line interface_.

If you do not need advanced configuration options, you can continue by configuring static networking, if required, and begin adding hosts to your infrastructure environment.

[#access-host-inventory]
== Accessing a host inventory

To access a host inventory, select *Infrastructure* > *Host inventory* in the console. Select your infrastructure environment from the list to view the details and hosts.

[#additional-resources-host-inv-console]
== Additional resources

- See xref:../cluster_lifecycle/cim_.adoc#enable-cim[Enabling the central infrastructure management service]
- See link:../../clusters/credentials/credential_on_prem.adoc#creating-a-credential-for-an-on-premises-environment[Creating a credential for an on-premises environment]
- See xref:../cluster_lifecycle/cim_create_cli.adoc#create-host-inventory-cli[Creating a host inventory by using the command line interface]
- If you completed this procedure as part of the process to configure hosted control planes on bare metal, your next steps are to complete the following procedures:
* xref:../cluster_lifecycle/cim_add_host.adoc#add-host-host-inventory[Adding hosts to the host inventory by using the Discovery Image]
* xref:../cluster_lifecycle/cim_auto_add_host.adoc#auto-add-host-host-inventory[Automatically adding bare metal hosts to the host inventory]
