[#cim-intro]
= Host inventory introduction

The host inventory management and on-premises cluster installation are available using the {mce-short} central infrastructure management feature. Central infrastructure management runs the Assisted Installer (also called infrastructure operator) as an operator on the hub cluster.

You can use the console to create a host inventory, which is a pool of bare metal or virtual machines that you can use to create on-premises {ocp-short} clusters. These clusters can be standalone, with dedicated machines for the control plane, or link:../../clusters/hosted_control_planes/hosted_intro.adoc#hosted-control-planes-intro[hosted control planes], where the control plane runs as pods on a hub cluster.

You can install standalone clusters by using the console, API, or GitOps by using Zero Touch Provisioning (ZTP). See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/scalability_and_performance/index#installing-disconnected-rhacm_ztp-preparing-the-hub-cluster[Installing GitOps ZTP in a disconnected environment] in the {ocp} documentation for more information on ZTP.

A machine joins the host inventory after booting with a Discovery Image. The Discovery Image is a Red Hat CoreOS live image that containins the following:

- An agent that performs discovery, validation, and installation tasks.
- The necessary configuration for reaching the service on the hub cluster, including the endpoint, token, and static network configuration, if applicable.

You generally have a single Discovery Image for each infrastructure environment, which is a set of hosts sharing a common set of properties. The `InfraEnv` custom resource definition represents this infrastructure environment and associated Discovery Image. The image used is based on your {ocp-short} version, which determines the operating system version that is selected.

After the host boots and the agent contacts the service, the service creates a new `Agent` custom resource on the hub cluster representing that host. The `Agent` resources make up the host inventory.

You can install hosts in the inventory as OpenShift nodes later. The agent writes the operating system to the disk, along with the necessary configuration, and reboots the host.

Continue reading to learn more about host inventories and central infrastructure management:

* xref:../cluster_lifecycle/cim_enable.adoc#enable-cim[Enabling the central infrastructure management service]
* xref:../cluster_lifecycle/cim_enable_aws.adoc#enable-cim-aws[Enabling central infrastructure management on Amazon Web Services]
* xref:../cluster_lifecycle/cim_create_console.adoc#create-host-inventory-console[Creating a host inventory by using the console]
* xref:../cluster_lifecycle/cim_create_cli.adoc#create-host-inventory-cli[Creating a host inventory by using the command line interface]
* xref:../cluster_lifecycle/cim_network_cli.adoc#cim-network-config[Configuring advanced networking for an infrastructure environment]
* xref:../cluster_lifecycle/cim_add_host.adoc#add-host-host-inventory[Adding hosts to the host inventory by using the Discovery Image]
* xref:../cluster_lifecycle/cim_auto_add_host.adoc#auto-add-host-host-inventory[Automatically adding bare metal hosts to the host inventory]
* xref:../cluster_lifecycle/cim_manage.adoc#manage-host-inv[Managing your host inventory]
* xref:../cluster_lifecycle/create_cluster_on_prem.adoc#creating-a-cluster-on-premises[Creating a cluster in an on-premises environment]
