[#create-host-inventory-console]
= Creating a host inventory by using the console

To create host inventory by using the console, complete the following steps:

. From the navigation menu, navigate to *Infrastructure* > *Host inventory* and click *Create infrastructure environment*.
. Add the following information to your host inventory settings: 
+
- Name: A unique name for your infrastructure environment. 
- Network type: Specifies which types of hosts can be added to your infrastructure environment.
- Location: Specifies the geographic location of the host. The geographic location can be used to easily determine where your data on a cluster is stored when you are creating the cluster. 
- Labels: Optional field where you can add labels to the infrastructure environment so you can more easily find and group the environment with other environments that share a characteristic. The selections that you made for the network type and location are automatically added to the list of labels.
- Host inventory credential: If you have a host inventory credential, select the credential to automatically populate the fields with information in the credential.  
- Pull secret: Your {ocp-short} link:https://console.redhat.com/openshift/install/pull-secret[pull secret] that enables you to access the {ocp-short} resources. This field is automatically completed if you selected a host inventory credential.
- SSH public key: The SSH key that enables the secure communication with the hosts. This is generally in your `id_rsa.pub` file. The default file path is `~/.ssh/id_rsa.pub`. This field is automatically completed if you selected a host inventory credential that contained the value of an SSH public key. 
- If you want to enable proxy settings across all of your clusters, select the setting to enable it. This requires that you enter the following information:
** HTTP Proxy URL: The URL that should be used when accessing the discovery service. 
** HTTPS Proxy URL: The secure proxy URL that should be used when accessing the discovery service. Note that the format must be `http`, as `https` is not yet supported. 
** No Proxy domains: A comma-separated list of domains that should bypass the proxy. Begin a domain name with a period `.` to include all of the subdomains that are in that domain. Add an asterisk `*` to bypass the proxy for all destinations. 

You can now continue by adding hosts to your infrastructure environment. 

[#access-host-inventory]
== Accessing a host inventory

To access a host inventory, select *Infrastructure* > *Host inventory* in the console. Select your infrastructure environment from the list to view the details and hosts.