[#add-host-host-inventory]
= Adding hosts to the host inventory by using the Discovery Image

After creating your host inventory (infrastructure environment) you can discover your hosts and add them to your inventory. To add hosts to your inventory, choose a method to download an ISO and attach it to each server. For example, you can download ISOs by using a virtual media or writing the ISO to a USB drive.

*Important:* To prevent the installation from failing, keep the Discovery ISO media connected to the device during the installation process and set each host to boot from the device one time.

[#add-host-prereqs]
== Prerequisites

- You must enable the central infrastructure management service. See _Enabling the central infrastructure management service_ for more information.
- You must create a host inventory. See _Creating a host inventory by using the console_ for more information.

[#add-host-steps-console]
== Adding hosts by using the console

Download the ISO by completing the following steps:

. Select *Infrastructure* > *Host inventory* in the console.

. Select your infrastructure environment from the list.

. Click *Add hosts* and select *With Discovery ISO*.

You now see a URL to download the ISO. Booted hosts appear in the host inventory table. Hosts might take a few minutes to appear. You must approve each host before you can use it. You can select hosts from the inventory table by clicking *Actions* and selecting *Approve*.

[#add-host-steps-cli]
== Adding hosts by using the command line interface

You can see the URL to download the ISO in the `isoDownloadURL` property in the status of your `InfraEnv` resource. See Creating a host inventory by using the command line interface for more information about the `InfraEnv` resource.

Each booted host creates an `Agent` resource in the same namespace. You must approve each host before you can use it.

[#additional-resources-add-host]
== Additional resources

- See xref:../cluster_lifecycle/cim_enable.adoc#enable-cim[Enabling the central infrastructure management service]
- See xref:../cluster_lifecycle/cim_create_console.adoc#create-host-inventory-console[Creating a host inventory by using the console]
- See xref:../cluster_lifecycle/cim_create_cli.adoc#create-host-inventory-cli[Creating a host inventory by using the command line interface]
