[#config-agent-proxy]
= Configuring _AgentClusterInstall_ proxy

The proxy defines the proxy settings used for the configuration.

[#config-proxy]
== Configuring _AgentClusterInstall_

To configure the `AgentClusterInstall` proxy resource, complete the following steps:

. Add the proxy setting to configure the `AgentClusterInstall` proxy specification. See the following YAML sample:

+
[source,yaml]
----
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
proxy:
  httpProxy: http://<username>:<password>@<proxy.example.com>:<port> <1>
  httpsProxy: https://<username>:<password>@<proxy.example.com>:<port> <2>
  noProxy: <wildcard-of-domain>,<provisioning-network/CIDR>,<BMC-address-range/CIDR> <3>
----
<1> `httpProxy` is the URL of the proxy for HTTP requests. Replace the username and password values with your credentials for your proxy server. Replace `proxy.example.com` with the path of your proxy server.
<2> `httpsProxy` is the URL of the proxy for HTTPS requests. Replace the values with your credentials. Replace `port` with the communication port with the proxy server.
<3> `noProxy`	is a comma-separated list of domains and CIDRs for which the proxy should not be used. Replace `wildcard-of-domain` with an entry for domains that should bypass the proxy. Replace `provisioning-network/CIDR` with the IP address of the provisioning network and the number of assigned IP addresses, in CIDR notation. Replace `BMC-address-range/CIDR` with the BMC address and the number of addresses, in CIDR notation.

. Additional step here?

[#resources-creating-cluster-proxy]
== Additional resources

