[#claiming-clusters-from-cluster-pools]
= Claiming clusters from cluster pools

`ClusterClaim` resources are used to check out clusters from cluster pools. A claim is completed when a cluster is running and ready in the cluster pool. The cluster pool automatically creates new running and hibernated clusters in the cluster pool to maintain the requirements that are specified for the cluster pool.

*Note:* When a cluster that was claimed from the cluster pool is no longer needed and is destroyed, the resources are deleted. The cluster does not return to the cluster pool.

*Required access*: Administrator

[#claim_prerequisite]
== Prerequisite

You must have the following available before claiming a cluster from a cluster pool:

A cluster pool with or without available clusters. If there are available clusters in the cluster pool, the available clusters are claimed. If there are no available clusters in the cluster pool, a cluster is created to fulfill the claim. See xref:../cluster_lifecycle/cluster_pool_manage.adoc#creating-a-clusterpool[Creating a cluster pool] for information about how to create a cluster pool. 

[#claim_cluster]
== Claim the cluster from the cluster pool

When you create a cluster claim, you request a new cluster from the cluster pool. A cluster is checked out from the pool when a cluster is available. The claimed cluster is automatically imported as one of your managed clusters, unless you disabled automatic import. 

Complete the following steps to claim a cluster:
        
. From the navigation menu, click *Infrastructure* > *Clusters*, and select the _Cluster pools_ tab.

. Find the name of the cluster pool you want to claim a cluster from and select *Claim cluster*.

If a cluster is available, it is claimed and immediately appears in the _Managed clusters_ tab. If there are no available clusters, it might take several minutes to resume a hibernated cluster or provision a new cluster. During this time, the claim status is `pending`. Expand the cluster pool to view or delete pending claims against it.

The claimed cluster remains a member of the cluster set that it was associated with when it was in the cluster pool. You cannot change the cluster set of the claimed cluster when you claim it. 

*Note:* Changes to the pull secret, SSH keys, or base domain of the cloud provider credentials are not reflected for existing clusters that are claimed from a cluster pool, as they have already been provisioned using the original credentials. You cannot edit cluster pool information by using the cosole, but you can update it by updating its information using the CLI interface. You can also create a new cluster pool with a credential that contains the updated information. The clusters that are created in the new pool use the settings provided in the new credential.


