[#managedclustersets-intro]
= _ManagedClusterSets_

A `ManagedClusterSet` is a group of managed clusters. A managed cluster set, can help you manage access to all of your managed clusters. You can also create a `ManagedClusterSetBinding` resource to bind a `ManagedClusterSet` resource to a namespace.

Each cluster must be a member of a managed cluster set. When you install the hub cluster, a `ManagedClusterSet` resource is created called `default`. All clusters that are not assigned to a managed cluster set are automatically assigned to the `default` managed cluster set. You cannot delete or update the `default` managed cluster set.

Continue reading to learn more about how to create and manage managed cluster sets:

* xref:../cluster_lifecycle/create_clusterset#creating-managedclusterset[Creating a _ManagedClusterSet_]
* xref:../cluster_lifecycle/assign_rbac_clusterset.adoc#assign-rbac-managedclusterset[Assigning RBAC permissions to _ManagedClusterSets_]
* xref:../cluster_lifecycle/create_clustersetbinding.adoc#creating-managedclustersetbinding[Creating a _ManagedClusterSetBinding_ resource]
* xref:../cluster_lifecycle/remove_cl_clusterset.adoc#removing-cluster-managedclusterset[Removing a cluster from a _ManagedClusterSet_]
