[#creating-a-cluster-proxy]
= Creating a cluster in a proxy environment

You can create a {ocp} cluster when your hub cluster is connected through a proxy server. One of the following situations must be true for the cluster creation to succeed:

* {mce-short} has a private network connection with the managed cluster that you are creating, with managed cluster access to the Internet by using a proxy.

* The managed cluster is on a infrastructure provider, but the firewall ports enable communication from the managed cluster to the hub cluster.

To create a cluster that is configured with a proxy, complete the following steps:

. Configure the `cluster-wide-proxy` setting on the hub cluster by adding the following information to your `install-config` YAML that is stored in your Secret:
+
[source,yaml]
----
apiVersion: v1
kind: Proxy
baseDomain: <domain>
proxy:
  httpProxy: http://<username>:<password>@<proxy.example.com>:<port>
  httpsProxy: https://<username>:<password>@<proxy.example.com>:<port>
  noProxy: <wildcard-of-domain>,<provisioning-network/CIDR>,<BMC-address-range/CIDR>
----
+
Replace `username` with the username for your proxy server.
+
Replace `password` with the password to access your proxy server.
+
Replace `proxy.example.com` with the path of your proxy server.
+
Replace `port` with the communication port with the proxy server.
+
Replace `wildcard-of-domain` with an entry for domains that should bypass the proxy.
+ 
Replace `provisioning-network/CIDR` with the IP address of the provisioning network and the number of assigned IP addresses, in CIDR notation.
+
Replace `BMC-address-range/CIDR` with the BMC address and the number of addresses, in CIDR notation.
+
After you add the previous values, the settings are applied to your clusters. 

. Provision the cluster by completing the procedure for creating a cluster. See _Creating a cluster_ to select your provider.

*Note:* You can only use `install-config` YAML when deploying your cluster. After deploying your cluster, any new changes you make to `install-config` YAML do not apply. To update the configuration after deployment, you must use policies. See _Pod policy_ for more information.

[#resources-creating-cluster-proxy]
== Additional resources

- See xref:../cluster_lifecycle/create_intro.adoc#create-intro[Cluster creation introduction] to select your provider.

- See link:../../governance/pod_policy.adoc#pod-policy[Pod policy] to learn how to make configuration changes after deploying your cluster.

- See link:../cluster_lifecycle/cluster_lifecycle_intro.adoc#cluster-intro[Cluster lifecycle introduction] for more topics.

- Return to <<creating-a-cluster-proxy,Creating a cluster in a proxy environment>>.
