[#creating-managedclustersetbinding]
= Creating a _ManagedClusterSetBinding_ resource

A `ManagedClusterSetBinding` resource binds a `ManagedClusterSet` resource to a namespace. Applications and policies that are created in the same namespace can only access clusters that are included in the bound managed cluster set resource.

Access permissions to the namespace automatically apply to a managed cluster set that is bound to that namespace. If you have access permissions to that namespace, you automatically have permissions to access any managed cluster set that is bound to that namespace. If you only have permissions to access the managed cluster set, you do not automatically have permissions to access other managed cluster sets on the namespace.

You can create a managed cluster set binding by using the console or the command line. 

[#creating-managedclustersetbinding-console]
== Creating a _ManagedClusterSetBinding_ by using the console

Complete the following steps to create a `ManagedClusterSetBinding` by using the console:

. From the {ocp-short} console, navigate to *Infrastructure* > *Clusters* and select the _Cluster sets_ tab.

. Select the name of the cluster set that you want to create a binding for.

. Navigate to *Actions* > *Edit namespace bindings*.

. On the _Edit namespace bindings_ page, select the namespace to which you want to bind the cluster set from the drop-down menu.

[#creating-a-managedclustersetbinding-cli]
== Creating a _ManagedClusterSetBinding_ by using the CLI

Complete the following steps to create a `ManagedClusterSetBinding` by using the CLI:

. Create the `ManagedClusterSetBinding` resource in your YAML file.
+
*Note:* When you create a managed cluster set binding, the name of the managed cluster set binding must match the name of the managed cluster set to bind. Your `ManagedClusterSetBinding` resource might resemble the following information:
+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: <namespace>
  name: <cluster_set>
spec:
  clusterSet: <cluster_set>
----

. Ensure that you have the bind permission on the target managed cluster set. View the following example of a `ClusterRole` resource, which contains rules that allow the user to bind to `<cluster_set>`:

+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <clusterrole>
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclustersets/bind"]
    resourceNames: ["<cluster_set>"]
    verbs: ["create"]
----
