[#creating-a-cluster-on-amazon-web-services]
= Creating a cluster on Amazon Web Services

You can use the {mce-short} console to create a {ocp} cluster on Amazon Web Services (AWS). 

When you create a cluster, the creation process uses the {ocp-short} installer with the Hive resource. If you have questions about cluster creation after completing this procedure, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-aws[Installing on AWS] in the {ocp-short} documentation for more information about the process.  

* <<aws_prerequisites,Prerequisites>>
* <<aws-creating-your-cluster-info,Creating your AWS cluster>>
* <<aws-creating-your-cluster-with-the-console,Creating your cluster with the console>>

[#aws_prerequisites]
== Prerequisites

See the following prerequisites before creating a cluster on AWS:

* You must have a deployed hub cluster.
* You need an AWS credential. See xref:../credentials/credential_aws.adoc#creating-a-credential-for-amazon-web-services[Creating a credential for Amazon Web Services] for more information.
* You need a configured domain in AWS. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-aws#installing-aws-account[Configuring an AWS account] for instructions on how to configure a domain.
* You must have Amazon Web Services (AWS) login credentials, which include user name, password, access key ID, and secret access key. See link:https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html[Understanding and Getting Your Security Credentials].
* You must have an {ocp-short} image pull secret. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/images/managing-images#using-image-pull-secrets[Using image pull secrets].

+
*Note:* If you change your cloud provider access key on the cloud provider, you also need to manually update the corresponding credential for the cloud provider on the console. This is required when your credentials expire on the cloud provider where the managed cluster is hosted and you try to delete the managed cluster.

[#aws-creating-your-cluster-info]
== Creating your AWS cluster

See the following important information about creating an AWS cluster:

* When you review your information and optionally customize it before creating the cluster, you can select *YAML: On* to view the `install-config.yaml` file content in the panel. You can edit the YAML file with your custom settings, if you have any updates.

* When you create a cluster, the controller creates a namespace for the cluster and the resources. Ensure that you include only resources for that cluster instance in that namespace. 

* _Destroying_ the cluster deletes the namespace and all of the resources in it.

* If you want to add your cluster to an existing cluster set, you must have the correct permissions on the cluster set to add it. If you do not have `cluster-admin` privileges when you are creating the cluster, you must select a cluster set on which you have `clusterset-admin` permissions.

* If you do not have the correct permissions on the specified cluster set, the cluster creation fails. Contact your cluster administrator to provide you with `clusterset-admin` permissions to a cluster set if you do not have any cluster set options to select.

* Every managed cluster must be associated with a managed cluster set. If you do not assign the managed cluster to a `ManagedClusterSet`, it is automatically added to the `default` managed cluster set.

* If there is already a base DNS domain that is associated with the selected credential that you configured with your AWS account, that value is populated in the field. You can change the value by overwriting it. This name is used in the hostname of the cluster.

* The release image identifies the version of the {ocp-short} image that is used to create the cluster. Select the image from the list of images that are available. If the image that you want to use is not available, you can enter the URL to the image that you want to use. 

* The node pools include the control plane pool and the worker pools. The control plane nodes share the management of the cluster activity. The information includes the following fields:

+
** Region: Specify the region where you want the node pool.
+
** CPU architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool. Valid values are _amd64_, _ppc64le_, _s390x_, and _arm64_.
+
** Zones: Specify where you want to run your control plane pools. You can select multiple zones within the region for a more distributed group of control plane nodes. A closer zone might provide faster performance, but a more distant zone might be more distributed.
+
** Instance type: Specify the instance type for your control plane node. You can change the type and size of your instance after it is created. 
+
** Root storage: Specify the amount of root storage to allocate for the cluster. 

* You can create zero or more worker nodes in a worker pool to run the container workloads for the cluster. This can be in a single worker pool, or distributed across multiple worker pools. If zero worker nodes are specified, the control plane nodes also function as worker nodes. The optional information includes the following fields:
+
** Zones: Specify where you want to run your worker pools. You can select multiple zones within the region for a more distributed group of nodes. A closer zone might provide faster performance, but a more distant zone might be more distributed.
+
** Instance type: Specify the instance type of your worker pools. You can change the type and size of your instance after it is created.
+
** Node count: Specify the node count of your worker pool. This setting is required when you define a worker pool.
+
** Root storage: Specify the amount of root storage allocated for your worker pool. This setting is required when you define a worker pool.

* Networking details are required for your cluster, and multiple networks are required for using IPv6. You can add an additional network by clicking *Add network*. 

* Proxy information that is provided in the credential is automatically added to the proxy fields. You can use the information as it is, overwrite it, or add the information if you want to enable a proxy. The following list contains the required information for creating a proxy:  
+
** HTTP proxy: Specify the URL that should be used as a proxy for `HTTP` traffic. 
+
** HTTPS proxy: Specify the secure proxy URL that should be used for `HTTPS` traffic. If no value is provided, the same value as the `HTTP Proxy URL` is used for both `HTTP` and `HTTPS`.
+
** No proxy sites: A comma-separated list of sites that should bypass the proxy. Begin a domain name with a period `.` to include all of the subdomains that are in that domain. Add an asterisk `*` to bypass the proxy for all destinations. 
+
** Additional trust bundle: One or more additional CA certificates that are required for proxying HTTPS connections.

[#aws-creating-your-cluster-with-the-console]
== Creating your cluster with the console

To create a new cluster, see the following procedure. If you have an existing cluster that you want to _import_ instead, see xref:../cluster_lifecycle/import_intro.adoc#import-intro[Cluster import introduction].

*Note:* You do not have to run the `oc` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured under the management of {mce-short}. 


. Navigate to *Infrastructure* > *Clusters*. 

. On the _Clusters_ page. Click *Cluster* > *Create cluster* and complete the steps in the console. 

. **Optional:** Select *YAML: On* to view content updates as you enter the information in the console.

If you need to create a credential, see xref:../credentials/credential_aws.adoc#creating-a-credential-for-amazon-web-services[Creating a credential for Amazon Web Services] for more information.

The name of the cluster is used in the hostname of the cluster.

If you are using {product-title} and want to configure your managed cluster klusterlet to run on specific nodes, see xref:../cluster_lifecycle/adv_config_cluster.adoc#create-cluster-configuring-nodeselector-tolerations[Optional: Configuring the klusterlet to run on specific nodes] for the required steps.

[#aws-creating-additional-resources]
== Additional resources

* The AWS private configuration information is used when you are creating an AWS GovCloud cluster. See xref:../cluster_lifecycle/create_aws_govcloud.adoc#creating-a-cluster-on-amazon-web-services-govcloud[Creating a cluster on Amazon Web Services GovCloud] for information about creating a cluster in that environment. 

* See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-aws#installing-aws-account[Configuring an AWS account] for more information.

* See xref:../cluster_lifecycle/release_image_intro.adoc#release-images-intro[Release images] for more information about release images.

* Find more information about supported instant types by visiting your cloud provider sites, such as link:https://aws.amazon.com/ec2/instance-types/[AWS General purpose instances].

