[#create-a-cluster-cli]
= Creating a cluster with the CLI

The {mce} uses internal Hive components to create {ocp} clusters. See the following information to learn how to create clusters.

* <<create-a-cluster-prereq,Prerequisites>>
* <<create-a-cluster-with-clusterdeployment,Create a cluster with ClusterDeployment>>
* <<create-a-cluster-with-clusterpool,Create a cluster with cluster pool>>

[#create-a-cluster-prereq]
== Prerequisites

- If you use the Nutanix platform, use the `x86_64` architecture for the `releaseImage` in the `ClusterImageSet` resource and set the `visible` label value to `'true'`. See the following example:
+
[source,yaml]
----
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    visible: 'true'
  name: img4.x.47-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.x.47-x86_64
----

- Review the hub cluster `KubeAPIServer` certificate verification strategy and update the strategy if needed. To learn what strategy to use for your setup, see xref:../cluster_lifecycle/adv_config_cluster.adoc#config-hub-kube-api-server[Configuring the hub cluster `KubeAPIServer` verification strategy].

[#create-a-cluster-with-clusterdeployment]
== Create a cluster with ClusterDeployment

A `ClusterDeployment` is a Hive custom resource that is used to control the lifecycle of a cluster.

Follow the link:https://github.com/openshift/hive/blob/master/docs/using-hive.md#using-hive[Using Hive] documentation to create the `ClusterDeployment` custom resource and create an individual cluster.

[#create-a-cluster-with-clusterpool]
== Create a cluster with ClusterPool

A `ClusterPool` is also a Hive custom resource that is used to create multiple clusters. 

Follow the link:https://github.com/openshift/hive/blob/master/docs/clusterpools.md[Cluster Pools] documentation to create a cluster with the Hive `ClusterPool` API.
