[#importing-managed-agent]
= Importing a managed cluster by using agent registration

After you install {mce}, you are ready to import a cluster and manage it by using the agent registration endpoint. Continue reading the following topics to learn how to import a managed cluster by using the agent registration endpoint. To import a managed cluster by using the console, see xref:../cluster_lifecycle/import_gui.adoc#importing-managed-cluster-console[Importing a managed cluster by using the console]. To import a managed cluster by using the CLI, see xref:../cluster_lifecycle.adoc/import_cli.adoc#importing-managed-cluster-cli[Importing a managed cluster by using the CLI].

* <<import-gui-prereqs,Prerequisites>>
* <<creating-new-pull-secret,Creating a new pull secret>>
* <<importing-cluster,Importing a cluster>>
* <<run-import-commands-manually,Additional steps for running import commands manually>>
* <<import-configuring-cluster-api,Optional: Configuring the cluster API address>>
* <<removing-an-imported-cluster,Removing a cluster>>

[#import-agent-prereqs]
== Prerequisites

* A deployed hub cluster. If you are importing bare metal clusters, the hub cluster must be installed on {ocp-short} version 4.9 or later. 
* A cluster you want to manage.
* The `base64` command line tool.
* A defined `multiclusterhub.spec.imagePullSecret` if you are importing a cluster that was not created by {ocp-short}. This secret might have been created when {mce} was installed. See xref:../install_upgrade/adv_config_install.adoc#custom-image-pull-secret[Custom image pull secret] for more information about how to define this secret.
+
If you need to create a new secret, see xref:../cluster_lifecycle/import_gui.adoc#creating-new-pull-secret[Creating a new pull secret].

[#supported-architectures-agent]
== Supported architectures

* Linux (x86_64, s390x, ppc64le)
* macOS

[#cluster-import-agent]
== Importing a cluster by using the 

//WARNING YOU ARE ENTERING DRAFT CONTENT, PROCEED WITH CAUTION

Before using agent registration endpoint on the managed cluster, complete the following steps:

Before using agent-registration from the managed cluster side, we need to complete the following steps:

    The agent-registration URL
    The cacert of agent-registration server
    The token that can be authenticated and autherizated by the agent-registration server.
    Enable auto-approve in ClusterManager.

          

To get the agent-registration server URL, we need run this command on the hub side:

export agent_registration_host=$(oc get route -n multicluster-engine agent-registration -o=jsonpath="{.spec.host}")

Not that, if hub is behind a cluster-wide-proxy, make sure using the URL that managed cluster can access.

 

Using the following command to get the cacert:

_oc get configmap -n kube-system kube-root-ca.crt -o=jsonpath="
{.data['ca\.crt']}

" > ca.crt_

 

We don’t limit the token's source as long as its assciated User has the get permisson on NonResourceURL /agent-registration/* . Here, we provide a simple way of get the token, it creates a serviceaccount and binds it with the ClusterRole managedcluster-import-controller-agent-regitration-client which has get permission for nonResourceURLs: ["/agent-registration/*"] :

cat << EOF | oc apply -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: managed-cluster-import-agent-registration-sa
  namespace: multicluster-engine
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: managed-cluster-import-agent-registration-sa-token
  namespace: multicluster-engine
  annotations:
    kubernetes.io/service-account.name: "managed-cluster-import-agent-registration-sa"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-cluster-import-agent-registration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: managedcluster-import-controller-agent-regitration-client
subjects:
  - kind: ServiceAccount
    name: managed-cluster-import-agent-registration-sa
    namespace: multicluster-engine
EOF

export token=$(oc get secret -n multicluster-engine managed-cluster-import-agent-registration-sa-token -o=jsonpath='{.data.token}' | base64 -d)

 

Next, we enable to auto-approval  by patching the following content to cluster-manager, but you can also set auto-approval mode to Disable and manually approve CSR requests from the managed clusters.

oc patch clustermanager cluster-manager --type=merge -p '{"spec":{"registrationConfiguration":{"featureGates":[
{"feature": "ManagedClusterAutoApproval", "mode": "Enable"}

], "autoApproveUsers":["system:serviceaccount:multicluster-engine:agent-registration-bootstrap"]}}}'
 

Finally, switch to the managed cluster context, and run the following commands to import the managed cluster to the hub:

 

curl --cacert ca.crt -H "Authorization: Bearer $token" https://$agent_registration_host/agent-registration/crds/v1 | oc apply -f -

curl --cacert ca.crt -H "Authorization: Bearer $token" https://$agent_registration_host/agent-registration/manifests/<clusterName>?klusterletconfig=<klusterletconfigName> | oc apply -f -

 

Specify the <clusterName> and <klusterletconfigName>(Optional) in the above commands.