[#import-intro]
= Cluster import

You can import clusters from different Kubernetes cloud providers. After you import, the target cluster becomes a managed cluster for the {mce-short} hub cluster. You can generally complete the import tasks anywhere that you can access the hub cluster and the target managed cluster, unless otherwise specified.

* A hub cluster cannot manage _any_ other hub cluster, but can manage itself. The hub cluster is configured to automatically be imported and self-managed. You do not need to manually import the hub cluster. 

* If you remove a hub cluster and try to import it again, you must add the `local-cluster:true` label to the `ManagedCluster` resource.

*Important:* Cluster lifecycle now supports all providers that are certified through the Cloud Native Computing Foundation (CNCF) Kubernetes Conformance Program. Choose a vendor that is recognized by CNFC for your hybrid cloud multicluster management. 

See the following information about using CNFC providers:

* Learn how CNFC providers are certified at link:https://www.cncf.io/training/certification/software-conformance/[Certified Kubernetes Conformance]. 

* For Red Hat support information about CNFC third-party providers, see link:https://access.redhat.com/third-party-software-support[Red Hat support with third party components], or link:https://access.redhat.com/support/contact/[Contact Red Hat support].

* If you bring your own CNFC conformance certified cluster, you need to change the {ocp-short} CLI `oc` command to the Kubernetes CLI command, `kubectl`. 

Read the following topics to learn more about importing a cluster so that you can manage it:

*Required user type or access level*: Cluster administrator

* xref:../cluster_lifecycle/import_gui.adoc#importing-managed-cluster-console[Importing an existing cluster by using the console]
* xref:../cluster_lifecycle/import_cli.adoc#importing-managed-cluster-cli[Importing a managed cluster by using the CLI]
* xref:../cluster_lifecycle/import_agent.adoc#importing-managed-agent[Importing a managed cluster by using agent registration]
* xref:../cluster_lifecycle/import_ocp.adoc#import-ocp-cluster[Importing an on-premises {ocp} cluster]
