:_mod-docs-content-type: CONCEPT

[#placement-prioritizerpolicy]
= Prioritizer policy

[role="_abstract"]
The `prioritizerPolicy` parameter ranks `ManagedClusters` so a placement can select the highest scoring clusters.

View the following examples to learn how to prioritize `ManagedClusters` by using the `prioritizerPolicy` parameter with placement.

- The following example selects a cluster with the largest allocatable memory:
+
*Note:* Similar to Kubernetes _Node Allocatable_, 'allocatable' is defined as the amount of compute resources that are available for pods on each cluster.
+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement
  namespace: ns1
spec:
  numberOfClusters: 1
  prioritizerPolicy:
    configurations:
      - scoreCoordinate:
          builtIn: ResourceAllocatableMemory
----

- The following example selects a cluster with the largest allocatable CPU and memory, and makes placement sensitive to resource changes:
+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement
  namespace: ns1
spec:
  numberOfClusters: 1
  prioritizerPolicy:
    configurations:
      - scoreCoordinate:
          builtIn: ResourceAllocatableCPU
        weight: 2
      - scoreCoordinate:
          builtIn: ResourceAllocatableMemory
        weight: 2
----

- The following example selects two clusters with the largest `addOn` score CPU ratio, and pins the placement decisions:
+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement
  namespace: ns1
spec:
  numberOfClusters: 2
  prioritizerPolicy:
    mode: Exact
    configurations:
      - scoreCoordinate:
          builtIn: Steady
        weight: 3
      - scoreCoordinate:
          type: AddOn
          addOn:
            resourceName: default
            scoreName: cpuratio
----

.Additional resources

* link:https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#node-allocatable[Node Allocatable]
* xref:../cluster_lifecycle/placement_intro.adoc#placement-intro[Placement]
