:_mod-docs-content-type: CONCEPT

[#built-in-taints]
= Built-in taints

[role="_abstract"]
Built-in taints are automatically added to managed clusters based on their availability status.

* `cluster.open-cluster-management.io/unavailable` - This taint is added to a managed cluster when the cluster has a condition of `ManagedClusterConditionAvailable` with status of `False`. The taint has the effect of `NoSelect` and an empty value to prevent an unavailable cluster from being selected by placements. An example of this taint is provided in the following content:
+

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: cluster1
spec:
  hubAcceptsClient: true
  taints:
    - effect: NoSelect
      key: cluster.open-cluster-management.io/unavailable
      timeAdded: '2022-02-21T08:11:54Z'
----

* `cluster.open-cluster-management.io/unreachable` - This taint is added to a managed cluster when the status of the condition for `ManagedClusterConditionAvailable` is either `Unknown` or has no condition. The taint has the effect of `NoSelect` and an empty value to prevent an unreachable cluster from being selected by placements. An example of this taint is provided in the following content:
+

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: cluster1
spec:
  hubAcceptsClient: true
  taints:
    - effect: NoSelect
      key: cluster.open-cluster-management.io/unreachable
      timeAdded: '2022-02-21T08:11:06Z'
----
