[#placement-overview]
= Placement overview

See the following information about how placement with managed clusters works:

* Kubernetes clusters are registered with the hub cluster as cluster-scoped `ManagedClusters`.

* The `ManagedClusters` are organized into cluster-scoped `ManagedClusterSets`.

* The `ManagedClusterSets` are bound to workload namespaces.

* The namespace-scoped placements specify a portion of `ManagedClusterSets` that select a working set of the potential `ManagedClusters`.

* Placements filter `ManagedClusters` from `ManagedClusterSets` by using `labelSelector` and `claimSelector`.

* The placement of `ManagedClusters` can be controlled by using taints and tolerations.

* Placements rank the clusters by the requirements and select a subset of clusters from them.

* Placements do not select managed clusters that you are deleting.

*Notes:* 

* You must bind at least one `ManagedClusterSet` to a namespace by creating a `ManagedClusterSetBinding` in that namespace. 
* You must have role-based access to `CREATE` on the virtual sub-resource of `managedclustersets/bind`.

[#placement-resources]
== Additional resources
//i believe we need to change from xref to link or add extra directory
//placements-clusters-api

- See xref:../cluster_lifecycle/taints_tolerations.adoc#taints-tolerations-managed[Using taints and tolerations to place managed clusters] for more information.
- See link:../api/placement.json.adoc#placements-clusters-api[Placements API] to learn more about the API.
- Return to xref:../clusters/cluster_lifecycle/placement_intro.adoc#placement-intro[Selecting _ManagedClusters_ with placement].
