[#release-images-connected]
= Maintaining a custom list of release images when connected

You might want to use the same release image for all of your clusters. To simplify, you can create your own custom list of release images that are available when creating a cluster. Complete the following steps to manage your available release images:

. Fork the link:https://github.com/stolostron/acm-hive-openshift-releases/tree/backplane-2.4[acm-hive-openshift-releases GitHub].

. Add the YAML files for the images that you want available when you create a cluster. Add the images to the `./clusterImageSets/stable/` or `./clusterImageSets/fast/` directory by using the Git console or the terminal.

. Create a `ConfigMap` in the `multicluster-engine` namespace named `cluster-image-set-git-repo`. See the following example, but replace `2.x` with {mce-version}:

[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-image-set-git-repo
  namespace: multicluster-engine
data:
  gitRepoUrl: <forked acm-hive-openshift-releases repository URL> 
  gitRepoBranch: backplane-<2.x>
  gitRepoPath: clusterImageSets
  channel: <fast or stable>
----
You can retrieve the available YAML files from the main repository by merging changes in to your forked repository with the following procedure:

. Commit and merge your changes to your forked repository.
. To synchronize your list of fast release images after you clone the `acm-hive-openshift-releases` repository, update the value of channel field in the `cluster-image-set-git-repo` `ConfigMap` to `fast`.
. To synchronize and display the stable release images, update the value of channel field in the `cluster-image-set-git-repo` `ConfigMap` to `stable`.

After updating the `ConfigMap`, the list of available stable release images updates with the currently available images in about one minute.

. You can use the following commands to list what is available and remove the defaults. Replace `<clusterImageSet_NAME>` with the correct name:
+
----
oc get clusterImageSets
oc delete clusterImageSet <clusterImageSet_NAME>
----

View the list of currently available release images in the console when you are creating a cluster.

For information regarding other fields available through the `ConfigMap`, view the link:https://github.com/stolostron/cluster-image-set-controller/blob/main/README.md[cluster-image-set-controller GitHub repository README].
