[#cluster-image-set]
= Locating _ClusterImageSets_

The YAML files referencing the release images are maintained in the _acm-hive-openshift-releases_ GitHub repository. The files are used to create the list of the available release images in the console. This includes the latest fast channel images from {ocp-short}. 

The console only displays the latest release images for the three latest versions of {ocp-short}. For example, you might see the following release image displayed in the console options, with <4.x> changed to the proper release version that you are using:

`quay.io/openshift-release-dev/ocp-release:<4.x>.1-x86_64`

The console displays the latest versions to help you create a cluster with the latest release images. If you need to create a cluster that is a specific version, older release image versions are also available.

*Note:* You can only select images with the `visible: 'true'` label when creating clusters in the console. An example of this label in a `ClusterImageSet` resource is provided in the following content. Replace `4.x.1` with the current version of the product:

[source,yaml]
----
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    visible: 'true'
  name: img4.x.1-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.x.1-x86_64
----
 
Additional release images are stored, but are not visible in the console. To view all of the available release images, run the following command:

----
oc get clusterimageset
----

The repository has the `clusterImageSets` directory, which is the directory that you use when working with the release images. The `clusterImageSets` directory has the following directories:

- Fast: Contains files that reference the latest versions of the release images for each supported {ocp-short} version. The release images in this folder are tested, verified, and supported.

- Releases: Contains files that reference all of the release images for each {ocp-short} version (stable, fast, and candidate channels)
+
*Note:* These releases have not all been tested and determined to be stable.

- Stable: Contains files that reference the latest two stable versions of the release images for each supported {ocp-short} version..
+
*Note:* By default, the current list of release images updates one time every hour. After upgrading the product, it might take up to one hour for the list to reflect the recommended release image versions for the new version of the product.
