[#release-images-specify]
= Specifying release images

When you create a cluster on a provider by using {mce}, specify a release image to use for your new cluster. To specify a release image, see the following topics:

- <<cluster-image-set,Locating _ClusterImageSets_>>
- <<config-cluster-image-set,Configuring _ClusterImageSets_>>
- <<manual-release-image-cross-arch,Creating a release image to deploy a cluster on a different architecture>>

[#cluster-image-set]
== Locating _ClusterImageSets_

The YAML files referencing the release images are maintained in the _acm-hive-openshift-releases_ GitHub repository. The files are used to create the list of the available release images in the console. This includes the latest fast channel images from {ocp-short}. 

The console only displays the latest release images for the three latest versions of {ocp-short}. For example, you might see the following release image displayed in the console options:

`quay.io/openshift-release-dev/ocp-release:4.12.1-x86_64`

The console displays the latest versions to help you create a cluster with the latest release images. If you need to create a cluster that is a specific version, older release image versions are also available.

*Note:* You can only select images with the `visible: 'true'` label when creating clusters in the console. An example of this label in a `ClusterImageSet` resource is provided in the following content. Replace `4.x.1` with the current version of the product:

[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    visible: 'true'
  name: img4.x.1-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.x.1-x86_64
----
 
Additional release images are stored, but are not visible in the console. To view all of the available release images, run the following command:

----
oc get clusterimageset
----

The repository has the `clusterImageSets` directory, which is the directory that you use when working with the release images. The `clusterImageSets` directory has the following directories:

- Fast: Contains files that reference the latest versions of the release images for each supported {ocp-short} version. The release images in this folder are tested, verified, and supported.

- Releases: Contains files that reference all of the release images for each {ocp-short} version (stable, fast, and candidate channels)
+
*Note:* These releases have not all been tested and determined to be stable.

- Stable: Contains files that reference the latest two stable versions of the release images for each supported {ocp-short} version..
+
*Note:* By default, the current list of release images updates one time every hour. After upgrading the product, it might take up to one hour for the list to reflect the recommended release image versions for the new version of the product.

[#config-cluster-image-set]
== Configuring _ClusterImageSets_

You can configure your `ClusterImageSets` with the following options:

- Option 1: To create a cluster in the console, specify the image reference for the specific `ClusterImageSet` that you want to us. Each new entry you specify persists and is available for all future cluster provisions See the following example entry: 
+
----
quay.io/openshift-release-dev/ocp-release:4.6.8-x86_64
----

- Option 2: Manually create and apply a `ClusterImageSets` YAML file from the `acm-hive-openshift-releases` GitHub repository.

- Option 3: To enable automatic updates of `ClusterImageSets` from a forked GitHub repository, follow the `README.md` in the _cluster-image-set-controller_ GitHub repository.

[#manual-release-image-cross-arch]
== Creating a release image to deploy a cluster on a different architecture

You can create a cluster on an architecture that is different from the architecture of the hub cluster by manually creating a release image that has the files for both architectures. 

For example, you might need to create an `x86_64` cluster from a hub cluster that is running on the `ppc64le`, `aarch64`, or `s390x` architecture. If you create the release image with both sets of files, the cluster creation succeeds because the new release image enables the {ocp-short} release registry to provide a multi-architecture image manifest. 

{ocp-short} 4.12 and later supports multiple architectures by default. You can use the following `clusterImageSet` to provision a cluster. Replace `4.x.0` with the current version:

[source,yaml]
----
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    visible: 'true'
  name: img4.x.0-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.x.0-multi
----

To create the release image for {ocp-short} images that do not support multiple architectures, complete steps similar to the following example for your architecture type:

. From the link:https://quay.io/repository/openshift-release-dev/ocp-release[{ocp-short} release registry], create a link:https://docs.docker.com/registry/spec/manifest-v2-2/[manifest list] that includes `x86_64`, `s390x`, `aarch64`, and `ppc64le` release images.

.. Pull the manifest lists for both architectures in your environment from the link:https://quay.io/repository/openshift-release-dev/ocp-release?tab=tags[Quay repository] by running the following example commands. Replace `4.x.1` with the current version of the product:
+
----
podman pull quay.io/openshift-release-dev/ocp-release:4.x.1-x86_64
podman pull quay.io/openshift-release-dev/ocp-release:4.x.1-ppc64le
podman pull quay.io/openshift-release-dev/ocp-release:4.x.1-s390x
podman pull quay.io/openshift-release-dev/ocp-release:4.x.1-aarch64
----

.. Log in to your private repository where you maintain your images by running the following command. Replace `<private-repo>` with the path to your repository.:
+
----
podman login <private-repo>
----


.. Add the release image manifest to your private repository by running the following commands that apply to your environment. Replace `4.x.1` with the current version of the product. Replace `<private-repo>` with the path to your repository:
+
----
podman push quay.io/openshift-release-dev/ocp-release:4.x.1-x86_64 <private-repo>/ocp-release:4.x.1-x86_64
podman push quay.io/openshift-release-dev/ocp-release:4.x.1-ppc64le <private-repo>/ocp-release:4.x.1-ppc64le
podman push quay.io/openshift-release-dev/ocp-release:4.x.1-s390x <private-repo>/ocp-release:4.x.1-s390x
podman push quay.io/openshift-release-dev/ocp-release:4.x.1-aarch64 <private-repo>/ocp-release:4.x.1-aarch64
----

.. Create a manifest for the new information by running the following command:
+
---- 
podman manifest create mymanifest
----

.. Add references to both release images to the manifest list by running the following commands. Replace `4.x.1` with the current version of the product. Replace `<private-repo>` with the path to your repository:
+
----
podman manifest add mymanifest <private-repo>/ocp-release:4.x.1-x86_64
podman manifest add mymanifest <private-repo>/ocp-release:4.x.1-ppc64le
podman manifest add mymanifest <private-repo>/ocp-release:4.x.1-s390x
podman manifest add mymanifest <private-repo>/ocp-release:4.x.1-aarch64
----

.. Merge the list in your manifest list with the existing manifest by running the following command. Replace `<private-repo>` with the path to your repository. Replace `4.x.1` with the current version:
+
----
podman manifest push mymanifest docker://<private-repo>/ocp-release:4.x.1
----

. On the hub cluster, create a release image that references the manifest in your repository.

.. Create a YAML file that contains information that is similar to the following example. Replace `<private-repo>` with the path to your repository. Replace `4.x.1` with the current version:
+
[source,yaml]
----
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    visible: "true"
  name: img4.x.1-appsub
spec:
  releaseImage: <private-repo>/ocp-release:4.x.1
----

.. Run the following command on your hub cluster to apply the changes. Replace `<file-name>` with the name of the YAML file that you created in the previous step:
+
----
oc apply -f <file-name>.yaml
----

. Select the new release image when you create your {ocp-short} cluster. 

. If you deploy the managed cluster by using the {product-title-short} console, specify the architecture for the managed cluster in the _Architecture_ field during the cluster creation process.

The creation process uses the merged release images to create the cluster. 

[#release-img-spec-add-res]
== Additional resources

- See the link:https://github.com/stolostron/acm-hive-openshift-releases[acm-hive-openshift-releases] GitHub repository for the YAML files that reference the release images.

- See the link:https://github.com/stolostron/cluster-image-set-controller/blob/main/README.md[cluster-image-set-controller GitHub repository] GitHub repository to learn how to enable enable automatic updates of `ClusterImageSets` from a forked GitHub repository.