[#release-images]
= Release images

When you create a cluster on a provider by using {mce-short}, you must specify a release image to use for the new cluster. The release image specifies which version of {ocp} is used to build the cluster. By default,`clusterImageSets` is on and calls the latest {ocp-short} release information.

YAML files reference the release images that are maintained in the `acm-hive-openshift-releases` GitHub repository.

You can configure your `ClusterImageSets` with the following options. You first disable the included subscription that automatically updates the latest fast channel images. 

Disable the automatic curation of the latest fast `ClusterImageSets` by using an installer parameter on the `multiclusterhub` resource. Toggle the `spec.disableUpdateClusterImageSets` parameter between `true` and `false`, the subscription installed with {product-title-short} is disabled or enabled, respectively. If you want to curate your own images, set the `spec.disableUpdateClusterImageSets` to `true` to disable the subscription.

- *Option 1:* Specify the image reference for the specific `ClusterImageSet` that you want to use in the console when creating a cluster. Each new entry you specify persists and is available for all future cluster provisions. See the following example entry: 
+
----
quay.io/openshift-release-dev/ocp-release:4.6.8-x86_64
----

- *Option 2:* Manually create and apply a `ClusterImageSets` YAML file from the `acm-hive-openshift-releases` GitHub repository.

- *Option 3:* Follow the `README.md` in the `acm-hive-openshift-releases` GitHub repository to enable automatic updates of `ClusterImageSets` from a forked GitHub repository.

The `subscription` directory contains files that specify where the list of release images is pulled from. Default release images for {product-title-short} are provided in a Quay.io directory and are referenced by the files in the repository.

You can also pause and unpause you fast Channel subscription with the following procedure if you have a stable channel subscription and are logged in to the hub cluster.

. Run the following command to pause:
+
----
make pause-stable
----
+
You can also run the following command:
----
oc -n hive patch appsub hive-clusterimagesets-subscription-stable-0 --type='json' -p='[{"op":"replace","path": "/metadata/labels/subscription-pause","value":"true"}]'
----

. Run the following command to unpause:
----
make unpause-stable
----

+
You can also run the following command:
----
oc -n hive patch appsub hive-clusterimagesets-subscription-stable-0 --type='json' -p='[{"op":"replace","path": "/metadata/labels/subscription-pause","value":"false"}]'
----
*Note:* Only release images with the label of: `visible: 'true'` are available to select when creating clusters in the console. An example of this label in a `ClusterImageSet` resource is provided in the following content: 

[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    visible: 'true'
  name: img4.10.1-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.10.1-x86_64
----
 
Additional release images are stored, but are not visible in the console. To view all of the available release images, run `kubectl get clusterimageset`.

Continue reading to learn more about release images:

* xref:../cluster_lifecycle/release_images.adoc#release-images[Release images]
* xref:../cluster_lifecycle/release_image_connected.adoc#maintaining-a-custom-list-of-release-images-while-connected[Maintaining a custom list of release images while connected]
* xref:../cluster_lifecycle/release_image_disconn.adoc#maintaining-a-custom-list-of-release-images-while-disconnected[Maintaining a custom list of release images while disconnected]

