[#release-images-disconnected]
= Maintaining a custom list of release images while disconnected

In some cases, you need to maintain a custom list of release images when the hub cluster has no Internet connection. You can create your own custom list of release images that are available when creating a cluster. Complete the following steps to manage your available release images while disconnected:

. While you are on a connected system, navigate to the link:https://github.com/stolostron/acm-hive-openshift-releases/tree/backplane-2.4[acm-hive-openshift-releases GitHub repository] to access the cluster image sets that are available.

. Copy the `clusterImageSets` directory to a system that can access the disconnected {mce-short} cluster.

. Add the mapping between the managed cluster and the disconnected repository with your cluster image sets by completing the following steps that fits your managed cluster:
+
  * For an {ocp-short} managed cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/images/image-configuration#images-configuration-registry-mirror_image-configuration[Configuring image registry repository mirroring] for information about using your `ImageContentSourcePolicy` object to complete the mapping. 
 
  * For a managed cluster that is not an {ocp-short} cluster, use the `ManageClusterImageRegistry` custom resource definition to override the location of the image sets. See xref:../cluster_lifecycle/specify_img_registry.adoc#specify-registry-img-on-managed-clusters-for-import[Specifying registry images on managed clusters for import] for information about how to override the cluster for the mapping.  

. Add the YAML files for the images that you want available when you create a cluster by using the console or CLI to manually add the `clusterImageSet` YAML content.

. Modify the `clusterImageSet` YAML files for the remaining {ocp-short} release images to reference the correct offline repository where you store the images. Your updates resemble the following example where `spec.releaseImage` refers to the image registry that you are using:

+
[source,yaml]
----
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
  name: img4.13.8-x86-64-appsub
spec:
  releaseImage: IMAGE_REGISTRY_IPADDRESS_or_DNSNAME/REPO_PATH/ocp-release:4.12.8-x86_64
----
+
Ensure that the images are loaded in the offline image registry that is referenced in the YAML file.

. Create each of the `clusterImageSets` by entering the following command for each YAML file:
+
----
oc create -f <clusterImageSet_FILE>
----
+
Replace `clusterImageSet_FILE` with the name of the cluster image set file. For example:
+
----
oc create -f img4.11.9-x86_64.yaml
----
+
After running this command for each resource you want to add, the list of available release images are available.

. Alternately you can paste the image URL directly in the create cluster console. Adding the image URL creates new `clusterImageSets` if they do not exist.

. View the list of currently available release images in the console when you are creating a cluster.
