[#updating-disconnected-cluster]
= Updating a disconnected cluster

You can use {update-service} with {mce-short} to update clusters in a disconnected environment.

In some cases, security concerns prevent you from connecting clusters directly to the internet. Configuring {update-service} to know when updates are available, even when your managed cluster is not connected to the internet.

{update-service} is a separate operator that monitors the available versions of your managed clusters in a disconnected environment, and makes them available for updating your managed clusters. After you configure {update-service}, it can perform the following actions:

* Monitor when updates are available for your disconnected clusters.
* Identify which updates are mirrored to your local site for updating by using the graph data file.
* Notify you that an update is available for your cluster by using the console.

Follow the steps in link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/updating_clusters/performing-a-cluster-update#updating-cluster-cli[Updating a cluster using the CLI] in the {ocp} documentation on your managed cluster to update your cluster in a disconnected environment.
