[#applications-console]
= Applications console

The console includes an applications dashboard for managing the application lifecycle.
You can use the console dashboard to create and manage applications.
You can also view the status of your applications.
The dashboard includes enhanced capabilities, which your developers and operations personnel can use to create, deploy, update, manage, visualize, and monitor applications across your clusters.

See the following application console capabilities:

* Use the topology view to visualize deployed applications across your clusters, including any associated channels and subscriptions.
* Access a topology view that encompasses the new application resource definitions, including channels, subscriptions, and placement rules.
* View individual status in the context of an application, including deployments, updates, and subscriptions.
* Add and edit channels, subscriptions, placement rules, and applications.

For more information, see xref:managing-applications-with-the-console[Managing applications with the console].
