[#application-resource-samples]
= Application resource samples

Within Red Hat Advanced Cluster Management for Kubernetes, applications are composed of multiple application resources.
The foundational resources for Red Hat Advanced Cluster Management for Kubernetes applications are the `application` resource and the `deployable` resource.

In addition, you can use channel, subscription, and placement rule resources to help you deploy, update, and manage your overall applications.

Both single and multi-cluster applications use the same Kubernetes specifications, but multi-cluster applications involve more automation of the deployment and application management lifecycle.

All of the application component resources for Red Hat Advanced Cluster Management for Kubernetes applications are defined in YAML file spec sections.
When you need to create or update an application component resource, you need to create or edit the appropriate spec section to include the labels for defining your resource.

View the following application resource samples:

* xref:app_sample[Application samples]
* xref:deployable_sample[Deployable samples]
* xref:secret_sample[Secret samples]
* xref:channel_sample[Channel samples]
* xref:subscription_sample[Subscription samples]
* xref:placement_sample[Placement rule samples]
