[#managing-applications]
= Managing applications

Review the following topics to learn more about creating, deploying, and managing your applications.
This guide assumes that users are familiar with Kubernetes concepts and terminology.
Key Kubernetes terms and components are not defined.
For more information about Kubernetes concepts, see https://kubernetes.io/docs/home/[Kubernetes Documentation]

The application management functions provide you with unified and simplified options for constructing and deploying applications and application updates.
With these functions, your developers and DevOps personnel can create and manage applications across environments through channel and subscription-based automation.

* xref:app_lifecycle[Application lifecycle]
* xref:app_resources[Application resources]
* xref:managing_apps[Managing application resources]
* xref:managing_deployables[Managing deployables]
* xref:managing_channels[Managing channels]
* xref:managing_subscriptions[Managing subscriptions]
* xref:managing_placement_rules[Managing placement rules]
* xref:managing_secrets[Managing secrets]
* xref:deployment_app[Deploying an application resource]
* xref:deployment_rollout[Deploying application resources with a rolling update]
* xref:managing_apps_console[Managing applications with the console]
* xref:app_resource_samples[Application resources samples]
