= Applications (applications.app.k8s.io) APIs


[[_rhacm-docs_apis_application_jsonoverview]]
== Overview
This documentation is for the Application resource for Red Hat Advanced Cluster Management for Kubernetes. Application resource has four possible requests: create, query, delete and update.


=== Version information
[%hardbreaks]
__Version__ : 1.0.0


=== Contact information
[%hardbreaks]
__Contact Email__ : apiteam@swagger.io


=== License information
[%hardbreaks]
__License__ : Apache 2.0
__License URL__ : http://www.apache.org/licenses/LICENSE-2.0.html
__Terms of service__ : http://swagger.io/terms/


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* applications.app.k8s.io : Create and manage applications


=== External Docs
[%hardbreaks]
__Description__ : Find out more about Swagger.
__URL__ : http://swagger.io




[[_rhacm-docs_apis_application_jsonpaths]]
== Paths

[[_rhacm-docs_apis_application_jsoncreateapplication]]
=== Create a application
....
POST /app.k8s.io/v1beta1/namespaces/{namespace}/applications
....


==== Description
Create a application.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|**Body**|**body** +
__required__|Parameters describing the application to be created.|<<_rhacm-docs_apis_application_jsonapplication,Application>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `application/yaml`


==== Tags

* applications.app.k8s.io


==== Example HTTP request

===== Request path
----
/app.k8s.io/v1beta1/namespaces/string/applications
----


===== Request header
[source,json]
----
"string"
----


===== Request body
[source,json]
----
{
  "apiVersion" : "app.k8s.io/v1beta1",
  "kind" : "Application",
  "metadata" : {
    "labels" : {
      "app" : "nginx-app-details"
    },
    "name" : "nginx-app-3",
    "namespace" : "ns-sub-1"
  },
  "spec" : {
    "componentKinds" : [ {
      "group" : "apps.open-cluster-management.io",
      "kind" : "Subscription"
    } ]
  },
  "selector" : {
    "matchLabels" : {
      "app" : "nginx-app-details"
    }
  },
  "status" : { }
}
----


[[_rhacm-docs_apis_application_jsonqueryapplications]]
=== Query all applications
....
GET /app.k8s.io/v1beta1/namespaces/{namespace}/applications
....


==== Description
Query your applications for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `application/yaml`


==== Tags

* applications.app.k8s.io


==== Example HTTP request

===== Request path
----
/app.k8s.io/v1beta1/namespaces/string/applications
----


===== Request header
[source,json]
----
"string"
----


[[_rhacm-docs_apis_application_jsonqueryapplication]]
=== Query a single application
....
GET /app.k8s.io/v1beta1/namespaces/{namespace}/applications/{application_name}
....


==== Description
Query a single application for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**application_name** +
__required__|Name of the application that you wan to query.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* applications.app.k8s.io


==== Example HTTP request

===== Request path
----
/app.k8s.io/v1beta1/namespaces/string/applications/string
----


===== Request header
[source,json]
----
"string"
----


[[_rhacm-docs_apis_application_jsondeleteapplication]]
=== Delete a application
....
DELETE /app.k8s.io/v1beta1/namespaces/{namespace}/applications/{application_name}
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**application_name** +
__required__|Name of the application that you want to delete.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* applications.app.k8s.io


==== Example HTTP request

===== Request path
----
/app.k8s.io/v1beta1/namespaces/string/applications/string
----


===== Request header
[source,json]
----
"string"
----




[[_rhacm-docs_apis_application_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_application_jsonapplication]]
=== Application

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__required__|**Example** : `"string"`|string
|**kind** +
__required__|**Example** : `"string"`|string
|**metadata** +
__required__|**Example** : `"object"`|object
|**spec** +
__required__|**Example** : `"object"`|<<_rhacm-docs_apis_application_jsonapplication_spec,spec>>
|===

[[_rhacm-docs_apis_application_jsonapplication_spec]]
**spec**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**assemblyPhase** +
__optional__|**Example** : `"string"`|string
|**componentKinds** +
__optional__|**Example** : `[ "object" ]`|< object > array
|**descriptor** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_application_jsonapplication_descriptor,descriptor>>
|**info** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_application_jsonapplication_info,info>> > array
|**selector** +
__optional__|**Example** : `"object"`|object
|===

[[_rhacm-docs_apis_application_jsonapplication_descriptor]]
**descriptor**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**description** +
__optional__|**Example** : `"string"`|string
|**icons** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_application_jsonapplication_descriptor_icons,icons>> > array
|**keywords** +
__optional__|**Example** : `[ "string" ]`|< string > array
|**links** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_application_jsonapplication_descriptor_links,links>> > array
|**maintainers** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_application_jsonapplication_descriptor_maintainers,maintainers>> > array
|**notes** +
__optional__|**Example** : `"string"`|string
|**owners** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_application_jsonapplication_descriptor_owners,owners>> > array
|**type** +
__optional__|**Example** : `"string"`|string
|**version** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_application_jsonapplication_descriptor_icons]]
**icons**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**size** +
__optional__|**Example** : `"string"`|string
|**src** +
__required__|**Example** : `"string"`|string
|**type** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_application_jsonapplication_descriptor_links]]
**links**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**description** +
__optional__|**Example** : `"string"`|string
|**url** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_application_jsonapplication_descriptor_maintainers]]
**maintainers**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**email** +
__optional__|**Example** : `"string"`|string
|**name** +
__optional__|**Example** : `"string"`|string
|**url** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_application_jsonapplication_descriptor_owners]]
**owners**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**email** +
__optional__|**Example** : `"string"`|string
|**name** +
__optional__|**Example** : `"string"`|string
|**url** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_application_jsonapplication_info]]
**info**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**name** +
__optional__|**Example** : `"string"`|string
|**type** +
__optional__|**Example** : `"string"`|string
|**value** +
__optional__|**Example** : `"string"`|string
|**valueFrom** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_application_jsonapplication_info_valuefrom,valueFrom>>
|===

[[_rhacm-docs_apis_application_jsonapplication_info_valuefrom]]
**valueFrom**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**configMapKeyRef** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_application_jsonapplication_info_valuefrom_configmapkeyref,configMapKeyRef>>
|**ingressRef** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_application_jsonapplication_info_valuefrom_ingressref,ingressRef>>
|**secretKeyRef** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_application_jsonapplication_info_valuefrom_secretkeyref,secretKeyRef>>
|**serviceRef** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_application_jsonapplication_info_valuefrom_serviceref,serviceRef>>
|**type** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_application_jsonapplication_info_valuefrom_configmapkeyref]]
**configMapKeyRef**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__optional__|**Example** : `"string"`|string
|**fieldPath** +
__optional__|**Example** : `"string"`|string
|**key** +
__optional__|**Example** : `"string"`|string
|**kind** +
__optional__|**Example** : `"string"`|string
|**name** +
__optional__|**Example** : `"string"`|string
|**namespace** +
__optional__|**Example** : `"string"`|string
|**resourceVersion** +
__optional__|**Example** : `"string"`|string
|**uid** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_application_jsonapplication_info_valuefrom_ingressref]]
**ingressRef**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__optional__|**Example** : `"string"`|string
|**fieldPath** +
__optional__|**Example** : `"string"`|string
|**host** +
__optional__|**Example** : `"string"`|string
|**kind** +
__optional__|**Example** : `"string"`|string
|**name** +
__optional__|**Example** : `"string"`|string
|**namespace** +
__optional__|**Example** : `"string"`|string
|**path** +
__optional__|**Example** : `"string"`|string
|**resourceVersion** +
__optional__|**Example** : `"string"`|string
|**uid** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_application_jsonapplication_info_valuefrom_secretkeyref]]
**secretKeyRef**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__optional__|**Example** : `"string"`|string
|**fieldPath** +
__optional__|**Example** : `"string"`|string
|**key** +
__optional__|**Example** : `"string"`|string
|**kind** +
__optional__|**Example** : `"string"`|string
|**name** +
__optional__|**Example** : `"string"`|string
|**namespace** +
__optional__|**Example** : `"string"`|string
|**resourceVersion** +
__optional__|**Example** : `"string"`|string
|**uid** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_application_jsonapplication_info_valuefrom_serviceref]]
**serviceRef**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__optional__|**Example** : `"string"`|string
|**fieldPath** +
__optional__|**Example** : `"string"`|string
|**kind** +
__optional__|**Example** : `"string"`|string
|**name** +
__optional__|**Example** : `"string"`|string
|**namespace** +
__optional__|**Example** : `"string"`|string
|**path** +
__optional__|**Example** : `"string"`|string
|**port** +
__optional__|**Example** : `0`|integer (int32)
|**resourceVersion** +
__optional__|**Example** : `"string"`|string
|**uid** +
__optional__|**Example** : `"string"`|string
|===





