[#managing-memory-usage-policies]
= Managing memory usage policies

Apply a memory usage policy to limit or restrict your memory and compute usage.
Learn to create, apply, view, and update your memory usage policy in the following sections.

[#creating-a-memory-usage-policy]
== Creating a memory usage policy

You can create a YAML file for your memory usage policy from the command line interface (CLI) or from the console.
View the following sections to create a memory usage policy:

[#creating-a-memory-usage-policy-from-the-cli]
=== Creating a memory usage policy from the CLI

Complete the following steps to create a memory usage policy from the CLI:

. Create a YAML file for your memory usage policy by running the following command:
+
----
kubectl create -f memorypolicy-1.yaml
----

. Apply the policy by running the following command:
+
----
kubectl apply -f <memory-policy-file-name>  --namespace=<namespace>
----

. List and verify the policies by running the following command:
+
----
kubectl get memorypolicy --namespace=<namespace>
----

Your memory usage policy is created from the CLI.

[#viewing-your-policy-from-the-cli]
==== Viewing your policy from the CLI

Complete the following steps to view your memory usage policy from the CLI:

. View details for a specific memory usage policy by running the following command:
+
----
kubectl get memorypolicy <policy-name> -n <namespace> -o yaml
----

. View a description of your memory usage policy by running the following command:
+
----
kubectl describe memorypolicy <name> -n <namespace>
----

[#creating-an-memory-usage-policy-from-the-console]
=== Creating an memory usage policy from the console

As you create a memory usage policy from the console, a YAML file is also created in the YAML editor.
Complete the following steps to create the memory usage policy from the console:

. Log in to your Red Hat Advanced Cluster Management for Kubernetes console.
. From the navigation menu, click *Governance and risk*.
. Click *Create policy*.
. Select *Limitrange* from the _Specifications_ field.
Parameter values are automatically set.
You can edit your values.
. Click *Create*.

[#viewing-your-memory-usage-policy-from-the-console]
==== Viewing your memory usage policy from the console

You can view any memory usage policy and its status from the console.

. Log in to your cluster from the console.
. From the navigation menu, click *Govern risk* to view a table list of your policies.
*Note*: You can filter the table list of your policies by selecting the All policies tab or Cluster violations tab.
. Select one of your policies to view more details.
. View the policy violations by selecting the _Violations_ tab.

[#updating-memory-usage-policies]
== Updating memory usage policies

[#deleting-a-memory-usage-policy]
=== Deleting a memory usage policy

Delete the memory usage policy from the CLI or the console.

* Delete a memory usage policy from the CLI:
 .. Delete a memory usage policy by running the following command:
// verify command `namespace`
+
----
 kubectl delete policy <memorypolicy-name> -n <mcm namespace>
----
+
After your policy is deleted, it is removed from your target cluster or clusters.

 .. Verify that your policy is removed by running the following command:
+
----
 kubectl get policy <memorypolicy-name> -n <mcm namespace>
----
* Delete a memory usage policy from the console:
 .. From the navigation menu, click *Govern risk* to view a table list of your policies.
 .. Click the *Options* icon for the policy you want to delete in the policy violation table.
 .. Click *Remove*.
 .. From the _Remove policy_ dialog box, click *Remove policy*.

Your memory usage policy is deleted.

View a sample of a memory usage policy, see _Memory usage policy sample_ from the xref:memory-usage-policy[Memory usage policy] page.
See xref:kubernetes-configuration-policy-controller[Kubernetes configuration policy controller] to learn about other configuration policies.
See xref:manage-security-policies[Manage security policies] to manage other policies.
