[#managing-a-namespace-policy]
= Managing a namespace policy

Namespace policies are applied to define specific rules for your namespace.
Learn to create, apply, view, and update your memory usage policy in the following sections.

[#creating-a-namespace-policy]
== Creating a namespace policy

You can create a YAML file for your namespace policy from the command line interface (CLI) or from the console.
View the following sections to create a namespace policy:

[#creating-a-namespace-policy-from-the-cli]
=== Creating a namespace policy from the CLI

Complete the following steps to create a namespace policy from the CLI:

. Create a YAML file for your namespace policy by running the following command:
+
----
kubectl create -f namespacepolicy-1.yaml
----

. Apply the policy by running the following command:
+
----
kubectl apply -f <namespace-policy-file-name>  --namespace=<namespace>
----

. List and verify the policies by running the following command:
+
----
kubectl get namespacepolicy --namespace=<namespace>
----

Your namespace policy is created from the CLI.

[#viewing-your-namespace-policy-from-the-cli]
==== Viewing your namespace policy from the CLI

Complete the following steps to view your namespace policy from the CLI:

. View details for a specific namespace policy by running the following command:
+
----
kubectl get namespacepolicy <policy-name> -n <namespace> -o yaml
----

. View a description of your namespace policy by running the following command:
+
----
kubectl describe namespacepolicy <name> -n <namespace>
----

[#creating-a-namespace-policy-from-the-console]
=== Creating a namespace policy from the console

As you create a namespace policy from the console, a YAML file is also created in the YAML editor.
Complete the following steps to create a namespace policy from the console:

. Log in to your Red Hat Advanced Cluster Management for Kubernetes console.
. From the navigation menu, click *Governance and risk*.
. Click *Create policy*.
. Select *Namespace* from the _Specifications_ field.
Parameter values are automatically set.
You can edit your values.
. Click *Create*.

[#viewing-your-namespace-policy-from-the-console]
==== Viewing your namespace policy from the console

You can view any namespace policy and its status from the console.

. Log in to your cluster from the console.
. From the navigation menu, click *Governance and risk* to view a table list of your policies.

NOTE: You can filter the table list of your policies by selecting the _All policies_ tab or _Cluster violations_ tab.

. Select one of your policies to view more details.
. View the policy violations by selecting the _Violations_ tab.

[#updating-namespace-policies]
== Updating namespace policies

[#deleting-a-namespace-policy]
=== Deleting a namespace policy

Delete a namespace policy from the CLI or the console.

* Delete a namespace policy from the CLI:
 .. Delete a namespace policy by running the following command:
// verify command `namespace`
+
----
 kubectl delete policy <memorypolicy-name> -n <mcm namespace>
----
+
After your policy is deleted, it is removed from your target cluster or clusters.

 .. Verify that your policy is removed by running the following command:
+
----
 kubectl get policy <memorypolicy-name> -n <mcm namespace>
----
* Delete a namespace policy from the console:
 .. From the navigation menu, click *Govern risk* to view a table list of your policies.
 .. Click the *Options* icon for the policy you want to delete in the policy violation table.
 .. Click *Remove*.
 .. From the _Remove policy_ dialog box, click *Remove policy*.

Your namespace policy is deleted.

View a sample of a namespace policy, see _Namespace policy sample_ on the xref:namespace-policy-page[Namespace policy page].
See xref:kubernetes-configuration-policy-controller[Kubernetes configuration policy controller] to learn about other configuration policies.
See xref:manage-security-policies[Manage security policies] to manage other policies.
