[#deploying-application-resources-with-a-rolling-update]
= Deploying application resources with a rolling update

If you want to roll out an update for a subscription to your managed clusters, you can configure the deployment to occur on only a percentage of your managed clusters at a time.
When the deployment on those clusters is successful, the deployment is rolled out incrementally to the remaining clusters.

When you run a percentage rollout, the rolling update happens on only the specified percentage of clusters.
As the deployment completes on one cluster, the deployment begins on another cluster while maintaining the percentage of clusters that are made unavailable.
If an error occurs during the deployment to one cluster, the deployment to that cluster is stopped.
The cluster remains unavailable until the error is resolved and the deployment can complete on that cluster.
Meanwhile, the overall deployment continues on the remaining clusters.
The cluster or clusters where an error occurred are still counted towards the percentage of clusters where the rolling update occurs.
If the number of clusters where occurred matches the specified percentage for the rolling update, the overall rollout for the deployment is stopped until the errors are resolved.

With a percentage rollout, you can phase in a deployment to your clusters to find any bugs or issues during the rollout before the deployment begins on all clusters.
For instance, you can use a percentage rollout when you need to deploy a patch to your clusters.
You can start your deployment with a rollout of the patch to 10% of your clusters to view the success of the deployment as the rolling update occurs.
When the deployment is successful on a cluster, the deployment continues to another cluster to reach the 10% of clusters until the overall deployment reaches 100% completion.
By limiting the deployment to only a percentage of clusters you can determine earlier whether a deployment is failing and stop the deployment to correct any issues.

The rolling update for a deployment runs on the hub cluster.
The deployment rollout occurs for the managed cluster namespaces that exist on the hub cluster.
When the rolling update is completed, the updates can be propagated to the actual managed clusters, such as by using an existing subscription for each managed cluster.
The managed cluster namespaces that are updated are defined by the placement rule for the subscription or deployable.

[#about-this-task]
== About this task

You can configure a percentage rollout for a subscription or directly for a deployable resource.

* <<configuring-a-rolling-update-for-a-subscription,Configuring a rolling update for a subscription>>
* <<rolling_update_sample,Rolling update sample>>

A rolling update for a subscription uses the rolling update feature that is included in the Kubernetes resource definition.
To configure this feature for a deploying a subscription, you need to create or update the following Kubernetes resources:

. The initial subscription resource.
+
This resource is used to define and deploy the initial resource that later updated through the rolling update.
As part of the definition for this initial resource, you need to identify that a rolling update is used for deploying updates.
You also need to identify the percentage of clusters to be updated at a time, the associated target resource, and the placement rule that identifies the target clusters.

. The target subscription resource.
+
This resource defines the version of the subscription that is being deployed through the rolling update.

. The placement rule for the initial subscription resource.
+
This placement rule identifies the clusters where the initial and target resource is deployed.
The rolling update does not target any clusters that are not defined by the placement rule.
+  *Note:* This placement rule must be associated with only the initial resource.
The rolling update uses only the placement rule that is associated with the initial resource.
Do not include parameters in the target subscription resource to associate that resource with a placement rule.

[#limitations-and-known-issues]
=== Limitations and known issues

* For a subscription rolling update, the initial and target subscription must be included within the same namespace.
* Target subscriptions cannot define any placement rule.
The initial subscription must define the placement rule for the rolling update.

[#configuring-a-rolling-update-for-a-subscription]
== Configuring a rolling update for a subscription

If you have existing subscriptions that you want to configure to use a rolling update, you need to create your target subscription and update your initial existing subscription to include the required annotations.

[#prerequisites]
=== Prerequisites

* You have an initial subscription that points to the initial version of a Kubernetes resource or Helm chart and a placement rule for defining the resource or chart deployment.
+
This initial subscription serves as the channel subscription and includes the settings for defining the channel and package information for the subscription.
+
For more information about how to define a subscription, see link:managing_subscriptions.html[Creating and managing subscriptions].
+
For more information about how to define a placement rule, see link:managing_placement_rules.html[creating and managing placement rules].

* The subscription that points to the initial resource or chart version is deployed to your target managed clusters and has been used to deploy the initial version of the resource or chart to the same target managed clusters.

At this stage no rolling update is configured and any change to the initial version at the source is then deployed to all managed clusters.

[#procedure]
=== Procedure

. Create the target subscription resource YAML definition to point to the newer version of the resource or chart to deploy.
This definition must use the same definition structure as any subscription application resource kind.
However, this target subscription must not include the annotations for defining a rolling update and must not define any placement rule.
. Update the initial subscription YAML definition to include the following annotations to indicate that a rolling update is used for updating the subscription:
+
[source,yaml]
----
annotations:
  apps.open-cluster-management.io/rollingupdate-target:
  apps.open-cluster-management.io/rollingupdate-maxunavailable:
----

 ** The `apps.open-cluster-management.io/rollingupdate-target` annotation identifies the target subscription.
 ** The `apps.open-cluster-management.io/rollingupdate-maxunavailable` annotation identifies the maximum percentage of clusters that can be deployed at a time and rendered unavailable during the update.
The actual number of clusters is determined by rounding down to an absolute value.
By default, the maximum percentage is 25%.
 ** The definition does not include any other configurations for the managing the rolling update.

+
For example, the following snippet of a YAML definition shows sample values for these annotations:
+
[source,yaml]
----
metadata:
annotations:
    apps.open-cluster-management.io/rollingupdate-target: target-subscription-name
    apps.open-cluster-management.io/rollingupdate-maxunavaialble: 30
name: initial-subscription-name
namespace: default
----
+
In the preceding example, the rolling update includes 30% of clusters.
+
You can use the Kubernetes CLI (kubectl) tool to add the annotations to an existing subscription instead of directly modifying the YAML definition.
Use the following command to add the annotations to a subscription:
+
[source,yaml]
----
kubectl annotate --overwrite subscriptions.apps.open-cluster-management.io sub-orig -n ns-sub-1 apps.open-cluster-management.io/rollingupdate-target=sub-target apps.open-cluster-management.io/rollingupdate-maxunavaialble=30
----

For example definitions of resources that use a rolling update, see <<rolling_update_sample,Rolling update sample>>.

With the subscription resources created or updated, the rolling update begins and the new target subscription and updated initial subscription are deployed to the managed clusters.
Then, the target subscription that is on the managed clusters is used to detect the new version of the resource or chart for deployment.
