[#installing]
= Installing

Learn how to install and uninstall Red Hat Advanced Cluster Management for Kubernetes.
Before you install Red Hat Advanced Cluster Management for Kubernetes, review the required hardware and system configuration for each product.

You can install the Red Hat Advanced Cluster Management for Kubernetes online on Linux with a supported version of Red Hat OpenShift Container Platform.

High-level installation flow:

. You must have a supported version of OpenShift Container Platform installed and configured.
. Install the Operator for Red Hat Advanced Cluster Management for Kubernetes from the catalog.

After you install and deploy the Red Hat Advanced Cluster Management for Kubernetes, view the documentation on how to use the features.

Installing Red Hat Advanced Cluster Management for Kubernetes sets up a multi-node cluster production environment.
You can install Red Hat Advanced Cluster Management for Kubernetes in either standard or high availability configurations.

The intallation process includes the following topics:

* xref:requirements-and-recommendations[Requirements and recommendations]
* xref:preparing-your-hub-cluster-for-installation[Preparing your hub cluster for installation]
* xref:sizing-your-cluster[Sizing your hub cluster]
* xref:installing-while-connected-online[Installing online when connected]
* link:install_disconnected[Installing on disconnected networks]
