[#known-issues]
= Known issues

////
Please follow this format:

Title of known issue, be sure to match header and make title, header unique

Hidden comment: Release: #issue
Known issue with workaround if:

- Doesn't work the way it should
- Straightforward to describe
- Good to know before getting started
- Quick workaround, of any
- Applies to most, if not all, users
- Something that is likely to be fixed next release (never preannounce)

Or consider a troubleshooting topic.
////

Review the known issues for Red Hat Advanced Cluster Management for Kubernetes.

* <<installation-known-issues,Installation known issues>>
* <<web-console-known-issues,Web console known issues>>
* <<cluster-management-issues,Cluster management known issues>>
* <<application-management-known-issues,Application management known issues>>
* <<security-known-issues,Security known issues>>

[#installation-known-issues]
== Installation known issues

[#host-adoption-failed]
=== Host adoption failed

// 1.0.0:1220

Bare metal hosts are not supported.
An error message appears when you try to validate the host adoption.

[#upgrading-an-ibm-red-hat-openshift-kubernetes-service-managed-cluster-is-not-supported]
=== Upgrading an IBM Red Hat OpenShift Kubernetes Service managed cluster is not supported

// 1.0.0:2131

You cannot upgrade an IBM Red Hat OpenShift Kubernetes Service managed cluster by using the Red Hat Advanced Cluster Management for Kubernetes interface.

[#importing-certain-versions-of-ibm-red-hat-openshift-kubernetes-service-clusters-is-not-supported]
=== Importing certain versions of IBM Red Hat OpenShift Kubernetes Service clusters is not supported

// 1.0.0:2179

You cannot import IBM Red Hat OpenShift Kubernetes Service version 3.11 clusters.
Later versions of IBM OpenShift Kubernetes Service are supported.

[#certificate-manager-must-not-exist-during-an-installation]
=== Certificate manager must not exist during an installation

// 1.0.0:678

Certificate manager must not exist on a cluster when you install Red Hat Advanced Cluster Management for Kubernetes.

When certificate manager already exists on the cluster, Red Hat Advanced Cluster Management for Kubernetes installation fails.

To resolve this issue, verify if the certificate manager is present in your cluster by running the following command:

----
   kubectl get crd | grep certificates.certmanager
----

[#cis-policy-controller-is-not-installed]
=== CIS policy controller is not installed

// 1.0.0:1087

The CIS policy controller is disabled by default when you install Red Hat Advanced Cluster Management for Kubernetes, If you create a CIS policy, you might receive the following message:

----
   CIS policy controller is not installed
----

You must enable the CIS policy controller.
For more information, see _Enable the CIS controller_ on the link:../security[CIS policy controller page] to update the policy.

[#all-users-with-access-to-the-advanced-cluster-management-for-kubernetes-component-namespaces-are-automatically-granted-cluster-administrator-access]
=== All users with access to the Advanced Cluster Management for Kubernetes component namespaces are automatically granted cluster administrator access

// 1.0.0:2135

The Advanced Cluster Management for Kubernetes components are installed in a single namespace.
A `ServiceAccount` with a `ClusterRoleBinding` automatically gives cluster administrator privileges to Advanced Cluster Management for Kubernetes and to any ID with access to the namespace.
For security, do not give anyone access to this namespace who does not already have cluster administrator access.

The `multicluster-endpoint`, which is the agent on the managed cluster, also requires cluster administrator privileges.
The `multicluster-endpoint` is deployed into the `multicluster-endpoint` namespace.
For security, do not give anyone access to the `multicluster-endpoint` namespace who does not already have cluster administrator access.

[#web-console-known-issues]
== Web console known issues

[#ldap-user-names-are-case-sensitive]
=== LDAP user names are case-sensitive

// 1.0.0:before 1.0.0.1

LDAP user names are case-sensitive.
You must use the name exactly the way it is configured in your LDAP directory.

[#console-features-might-not-display-in-firefox-earlier-versions]
=== Console features might not display in Firefox earlier versions

// 1.0.0:before 1.0.0.1

The product supports Mozilla Firefox 74.0 or the latest version that is available for Linux, macOS, and Windows.
Upgrade to the latest version for the best console compatibility.

[#unable-to-search-using-values-with-empty-spaces]
=== Unable to search using values with empty spaces

// 1.0.0:1726

From the console and Visual Web Terminal, users are unable to search for values that contain an empty space.

[#at-logout-user-kubeadmin-gets-extra-browser-tab-with-blank-page]
=== At logout user kubeadmin gets extra browser tab with blank page

// 1.0.0:2191

When you are logged in as `kubeadmin` and you click the *Log out* option in the drop-down menu, the console returns to the login screen, but a browser tab opens with a `/logout` URL.
The page is blank and you can close the tab without impact to your console.

[#console-documentation-links-in-technical-preview-might-be-incorrect]
=== Console documentation links in technical preview might be incorrect

// 1.0.0:816

For technical preview, documentation links were removed from the console, but a few might still be exposed.
Any links to the documentation for preview are temporarily not updated with the correct links.

[#search-is-unavailable-or-missing-data-for-a-brief-period]
=== Search is unavailable or missing data for a brief period

// 1.0.0:1918

The memory used by the search data store grows slowly over time and causes pods to restart, when the limit is reached.
Search becomes unavailable or the data is out of sync with the managed clusters.
The memory leak accelerates when more managed clusters are added.

You might encounter the following issues:

* Search becomes unavailable or data is out of sync for a brief period.
* Search is unable to display some cluster status.

To mitigate this problem, you can increase the memory limit in the `search-pod-xxxxx-redisgraph` deployment to reduce the frequency of pod restarts.
Complete the following steps to update the deployment:

* Run the following command to increase the memory limit in the `search-pod-xxxxx-redisgraph` deployment from the command line interface (CLI):
+
----
 oc patch deployment search-prod-xxxxx-redisgraph -n open-cluster-management -p '{"spec": {"template": {"spec": {"containers":[{"name":"redisgraph","resources": {"limits": {"memory": "4Gi"}}}]}}}}'
----

* Update your `search-pod-xxxxx-redisgraph` deployment from the console:
 .. Log in to the Red Hat Advanced Cluster Management for Kubernetes cluster.
 .. Navigate to the _Search_ page and enter `search-prod-xxxxx-redisgraph` deployment.
 .. Update the `containers.resources.limit.memory` parameter and increase the memory value.

NOTE: Your maximum memory is restricted by either your quota, policies, or physical limits of the nodes on your cluster.

[#cluster-management-issues]
== Cluster management known issues

[#etcd-operator-does-not-reconcile-the-cluster]
=== _etcd-operator_ does not reconcile the cluster

// 1.0.0:2010

When you upgrade your OpenShift Container Platform cluster and the etcd persistence is not enabled, the `etcd-operator` does not reconcile you managed clusters.
As a result, your managed clusters are removed and you lose most data.

[#application-management-known-issues]
== Application management known issues

[#application-not-deployed-after-an-updated-placement-rule]
=== Application not deployed after an updated placement rule

// 1.0.0:1449

If applications are not deploying after an update to a placement rule, verify that the `endpoint-appmgr` pod is running.
The `endpoint-appmgr` is the subscription container that needs to run on endpoint clusters.

You can run `oc get pods -n multicluster-endpoint` to verify.

You can also search for `kind:pod cluster:yourcluster` in the console and see if the `endpoint-appmgr` is running.

If you cannot verify, attempt to import the cluster again and verify again.

[#subscription-operator-does-not-create-an-scc]
=== Subscription operator does not create an SCC

// 1.0.0:1764

Learn about Red Hat Openshift Container Platform SCC at link:ht1.0.0s://docs.openshift.com/container-platform/4.3/authentication/managing-security-context-constraints.html#security-context-constraints-about_configuring-internal-oauth[Managing Security Context Constraints (SCC)], which is an additional configuration required on the managed cluster.

Different deployments have different security context and different service accounts.
The subscription operator cannot create an SCC automatically.
Administrators control permissions for pods.
A Security Context Constraints (SCC) CR is required to enable appropriate permissions for the relative service accounts to create pods in the non-default namespace:

To manually create an SCC CR in your namespace, complete the following:

. Find the service account that is defined in the deployments.
For example, see the following `nginx` deployments:

----
nginx-ingress-52edb
nginx-ingress-52edb-backend
----

. Create an SCC CR in your namespace to assign the required permissions to the service account or accounts.
See the following example where `kind: SecurityContextConstraints` is added:

----
apiVersion: security.openshift.io/v1
defaultAddCapabilities:
kind: SecurityContextConstraints
metadata:
  name: ingress-nginx
  namespace: ns-sub-1
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:my-operator:nginx-ingress-52edb
- system:serviceaccount:my-operator:nginx-ingress-52edb-backend
----

[#helm-release-name-is-not-exact-on-topology-view]
=== Helm release name is not exact on Topology view

// 1.0.0:1593

The _Application Topology_ view from the _Topology_ menu displays only a summary of the application content.
To view complete and accurate content of the application, complete the following procedure:

. Navigate to the _Applications_ menu.
. Select your application.
. You can view a complete topology and summary cards for your selected application.

[#security-known-issues]
== Security known issues

[#certificate-policies-fail-to-report-status]
=== Certificate policies fail to report status

// 1.0.0:2302

You can create and apply multiple certificate policies on a single managed cluster, but each policy must have a different parameter value for the `namespaceSelector`.
When mulitiple policies on the same managed cluster use the same `namespaceSelector` value, only one of the policies work as expected.

For more information, see link:../security[Certificate policy controller].

[#any-authenticated-user-can-import-clusters]
=== Any authenticated user can import clusters

// 1.0.0:2312

Any authenticated user of OpenShift Container Platform can provision projects and have administrator privileges to the project and its associated namespace.
As the administrator of a namespace, you can generate commands to import clusters into Red Hat Advanced Cluster Management for Kubernetes.
To run the generated commands and import the cluster, you must have cluster administrator privileges on the managed cluster.
For more information view the link:../security[Role based access control] table.
