[#namespace-policy]
= Namespace policy

Apply the namespace policy to define specific rules for your namespace.

[#namespace-policy-yaml-structure]
== Namespace policy YAML structure

[source,yaml]
----
   apiVersion: policy.mcm.ibm.com/v1alpha1
   kind: Policy
   metadata:
     name: policy-namespace-1
     namespace:
   spec:
     complianceType:
     remediationAction:
     namespaces:
       exclude:
       include:
     object-templates:
       - complianceType:
         objectDefinition:
           kind:
           apiVersion:
           metadata:
             name:
        ...
----

[#namespace-policy-table]
== Namespace policy table

// this table is a place holder until i update the parameters

|Field|Description| |-- | -- | | apiVersion | Required.
Set the value to `policy.mcm.ibm.com/v1alpha1`.
// current place holder until this info is updated
| | kind | Required.
Set the value to `Policy` to indicate the type of policy.
| | metadata.name | Required.
The name for identifying the policy resource.
| | metadata.namespaces | Optional.
| | spec.namespace | Required.
The namespaces within the hub cluster that the policy is applied to.
Enter parameter values for `include`, which are the namespaces you want to apply to the policy to.
`exclude` specifies the namespaces you explicitly do not want to apply the policy to.
*Note*: A namespace that is specified in the object template of a policy controller, overrides the namespace in the corresponding parent policy.| | remediationAction | Optional.
Specifies the remediation of your policy.
The parameter values are `enforce` and `inform`.
*Important*: Some policies may not support the enforce feature.| | disabled | Required.
Set the value to `true` or `false`.
The `disabled` parameter provides the ability to enable and disable your policies.| | spec.complianceType | Required.
Set the value to `"musthave"`| | spec.object-template| Optional.
Used to list any other Kubernetes object that must be evaluated or applied to the managed clusters.
|

[#namespace-policy-sample]
== Namespace policy sample

Apply the namespace policy to define specific rules for your namespace.
Your namespace policy might resemble the following YAML file:

[source,yaml]
----
   apiVersion: policy.mcm.ibm.com/v1alpha1
   kind: Policy
   metadata:
     name: policy-namespace-1
     namespace: mcm
   spec:
     complianceType: musthave
     remediationAction: inform
     namespaces:
       exclude: ["kube-*"]
       include: ["default"]
     object-templates:
       - complianceType: musthave
         objectDefinition:
           kind: Namespace # must have namespace 'prod'
           apiVersion: v1
           metadata:
             name: prod
        ...
----

// wil create another file, create_ns_pol where i will add the following tasks

[#applying-the-namespace-policy]
=== Applying the namespace policy

Complete the following steps to apply the memory usage policy from the console:

. Log in to your Red Hat Advanced Cluster Management for Kubernetes console.
. From the navigation menu, click *Governance and risk*.
. Click *Create policy*.
. Select *Namespace* from the _Specifications_ field.
