
[[_rhacm-docs_apis_helmreleases_jsonpaths]]
== Paths

[[_rhacm-docs_apis_helmreleases_jsoncreatehelmrelease]]
=== Create a helmrelease
....
POST /apps.open-cluster-management.io/v1/namespaces/{namespace}/helmreleases
....


==== Description
Create a helmrelease.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|**Body**|**body** +
__required__|Parameters describing the helmrelease to be created.|<<_rhacm-docs_apis_helmreleases_jsonhelmrelease,HelmRelease>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `application/yaml`


==== Tags

* helmreleases.apps.open-cluster-management.io


==== Example HTTP request

===== Request body
[source,json]
----
{
  "apiVersion" : "apps.open-cluster-management.io/v1",
  "kind" : "HelmRelease",
  "metadata" : {
    "name" : "nginx-ingress",
    "namespace" : "default"
  },
  "repo" : {
    "chartName" : "nginx-ingress",
    "source" : {
      "helmRepo" : {
        "urls" : [ "https://kubernetes-charts.storage.googleapis.com/nginx-ingress-1.26.0.tgz" ]
      },
      "type" : "helmrepo"
    },
    "version" : "1.26.0"
  },
  "spec" : {
    "defaultBackend" : {
      "replicaCount" : 3
    }
  }
}
----


[[_rhacm-docs_apis_helmreleases_jsonqueryhelmreleases]]
=== Query all helmreleases
....
GET /apps.open-cluster-management.io/v1/namespaces/{namespace}/helmreleases
....


==== Description
Query your helmreleases for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `application/yaml`


==== Tags

* helmreleases.apps.open-cluster-management.io


[[_rhacm-docs_apis_helmreleases_jsonqueryhelmrelease]]
=== Query a single helmrelease
....
GET /apps.open-cluster-management.io/v1/namespaces/{namespace}/helmreleases/{helmrelease_name}
....


==== Description
Query a single helmrelease for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**helmrelease_name** +
__required__|Name of the helmrelease that you wan to query.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* helmreleases.apps.open-cluster-management.io


[[_rhacm-docs_apis_helmreleases_jsondeletehelmrelease]]
=== Delete a helmrelease
....
DELETE /apps.open-cluster-management.io/v1/namespaces/{namespace}/helmreleases/{helmrelease_name}
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**helmrelease_name** +
__required__|Name of the helmrelease that you want to delete.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* helmreleases.apps.open-cluster-management.io



