[#red-hat-advanced-cluster-management-for-kubernetes-policy-controllers]
= Red Hat Advanced Cluster Management for Kubernetes policy controllers

Use the Red Hat Advanced Cluster Management for Kubernetes governance and risk policy framework to create custom policy controllers.
The policy controllers are Kubernetes CustomResourceDefinition (CRD) instance.
For more information about CRDs, see https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions].

Create and customize policies with the out of the box policy templates.
View the following topics to learn more about the following Red Hat Advanced Cluster Management for Kubernetes policy controllers to enforce policies:

* xref:../governance/config_policy_ctrl[Configuration policy controller]
* xref:../governance/cert_policy_ctrl[Certificate policy controller]
* xref:../governance/iam_policy_ctrl[IAM policy controller]
* xref:../governance/cis_policy_ctrl[CIS policy controller]

IMPORTANT: Some policy controllers may not support the enforce feature.
If the enforce feature is not supported by the controller, you must remediate it manually.
See, `remediationAction` in the link:../policy_overview.md#policy_elements_2[Policy elements section].
