[#policy-controllers]
= Policy controllers

Use the Red Hat Advanced Cluster Management for Kubernetes governance and risk policy framework to create custom policy controllers.
The policy controllers are Kubernetes CustomResourceDefinition (CRD) instance.
For more information about CRDs, see https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions].

Create and customize policies with the out of the box policy templates.
*Important*: Some policy controllers may not support the enforce feature.
If the enforce feature is not supported by the controller, you must remediate it manually.
Only the configuration policy controller supports the `enforce` feature.

View the following topics to learn more about the following Red Hat Advanced Cluster Management for Kubernetes policy controllers:

* xref:configuration-policy-controller[Configuration policy controller]
* xref:certificate-policy-controller[Certificate policy controller]
* xref:iam-policy-controller[IAM policy controller]
* xref:cis-policy-controller[CIS policy controller]

Refer to xref:governance-and-risk[Governance and risk] for more topics about managing your policies.
