= Subscriptions (subscriptions.apps.open-cluster-management.io) APIs


[[_rhacm-docs_apis_subscriptions_jsonoverview]]
== Overview
This documentation is for the Subscription resource for Red Hat Advanced Cluster Management for Kubernetes. The Subscription resource has four possible requests: create, query, delete and update.


=== Version information
[%hardbreaks]
__Version__ : 1.0.0


=== Contact information
[%hardbreaks]
__Contact Email__ : apiteam@swagger.io


=== License information
[%hardbreaks]
__License__ : Apache 2.0
__License URL__ : http://www.apache.org/licenses/LICENSE-2.0.html
__Terms of service__ : http://swagger.io/terms/


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* subscriptions.apps.open-cluster-management.io : Create and manage subscriptions


=== External Docs
[%hardbreaks]
__Description__ : Find out more about Swagger.
__URL__ : http://swagger.io




[[_rhacm-docs_apis_subscriptions_jsonpaths]]
== Paths

[[_rhacm-docs_apis_subscriptions_jsoncreatesubscription]]
=== Create a subscription
....
POST /apps.open-cluster-management.io/v1/namespaces/{namespace}/subscriptions
....


==== Description
Create a subscription.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|**Body**|**body** +
__required__|Parameters describing the subscription to be created.|<<_rhacm-docs_apis_subscriptions_jsonsubscription,Subscription>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `subscription/yaml`


==== Tags

* subscriptions.apps.open-cluster-management.io


==== Example HTTP request

===== Request path
----
/apps.open-cluster-management.io/v1/namespaces/string/subscriptions
----


===== Request header
[source,json]
----
"string"
----


===== Request body
[source,json]
----
{
  "apiVersion" : "apps.open-cluster-management.io/v1",
  "kind" : "Subscription",
  "metadata" : {
    "name" : "sample_subscription",
    "namespace" : "default",
    "labels" : {
      "app" : "sample_subscription-app"
    },
    "annotations" : {
      "apps.open-cluster-management.io/github-path" : "apps/sample/",
      "apps.open-cluster-management.io/github-branch" : "sample_branch"
    }
  },
  "spec" : {
    "channel" : "channel_namespace/sample_channel",
    "packageOverrides" : [ {
      "packageName" : "my-sample-application",
      "packageAlias" : "the-sample-app",
      "packageOverrides" : [ {
        "path" : "spec",
        "value" : {
          "persistence" : {
            "enabled" : false,
            "useDynamicProvisioning" : false
          },
          "license" : "accept",
          "tls" : {
            "hostname" : "my-mcm-cluster.icp"
          },
          "sso" : {
            "registrationImage" : {
              "pullSecret" : "hub-repo-docker-secret"
            }
          }
        }
      } ]
    } ],
    "placement" : {
      "placementRef" : {
        "kind" : "PlacementRule",
        "name" : "demo-clusters"
      }
    }
  }
}
----


[[_rhacm-docs_apis_subscriptions_jsonquerysubscriptions]]
=== Query all subscriptions
....
GET /apps.open-cluster-management.io/v1/namespaces/{namespace}/subscriptions
....


==== Description
Query your subscriptions for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `subscription/yaml`


==== Tags

* subscriptions.apps.open-cluster-management.io


==== Example HTTP request

===== Request path
----
/apps.open-cluster-management.io/v1/namespaces/string/subscriptions
----


===== Request header
[source,json]
----
"string"
----


[[_rhacm-docs_apis_subscriptions_jsonquerysubscription]]
=== Query a single subscription
....
GET /apps.open-cluster-management.io/v1/namespaces/{namespace}/subscriptions/{subscription_name}
....


==== Description
Query a single subscription for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|**Path**|**subscription_name** +
__required__|Name of the subscription that you wan to query.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* subscriptions.apps.open-cluster-management.io


==== Example HTTP request

===== Request path
----
/apps.open-cluster-management.io/v1/namespaces/string/subscriptions/string
----


===== Request header
[source,json]
----
"string"
----


[[_rhacm-docs_apis_subscriptions_jsondeletesubscription]]
=== Delete a subscription
....
DELETE /apps.open-cluster-management.io/v1/namespaces/{namespace}/subscriptions/{subscription_name}
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|**Path**|**subscription_name** +
__required__|Name of the subscription that you want to delete.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* subscriptions.apps.open-cluster-management.io


==== Example HTTP request

===== Request path
----
/apps.open-cluster-management.io/v1/namespaces/string/subscriptions/string
----


===== Request header
[source,json]
----
"string"
----




[[_rhacm-docs_apis_subscriptions_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_subscriptions_jsonsubscription]]
=== Subscription

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__required__|**Example** : `"string"`|string
|**kind** +
__required__|**Example** : `"string"`|string
|**metadata** +
__required__|**Example** : `"object"`|<<_rhacm-docs_apis_subscriptions_jsonsubscription_metadata,metadata>>
|**spec** +
__required__|**Example** : `"object"`|<<_rhacm-docs_apis_subscriptions_jsonsubscription_spec,spec>>
|**status** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_subscriptions_jsonsubscription_status,status>>
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_metadata]]
**metadata**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**annotations** +
__optional__|**Example** : `"object"`|object
|**labels** +
__optional__|**Example** : `"object"`|object
|**name** +
__optional__|**Example** : `"string"`|string
|**namespace** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_spec]]
**spec**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**channel** +
__required__|**Example** : `"string"`|string
|**name** +
__optional__|**Example** : `"string"`|string
|**overrides** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_subscriptions_jsonsubscription_overrides,overrides>> > array
|**packageFilter** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_subscriptions_jsonsubscription_packagefilter,packageFilter>>
|**packageOverrides** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_subscriptions_jsonsubscription_packageoverrides,packageOverrides>> > array
|**placement** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_subscriptions_jsonsubscription_placement,placement>>
|**timewindow** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_subscriptions_jsonsubscription_timewindow,timewindow>>
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_overrides]]
**overrides**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**clusterName** +
__required__|**Example** : `"string"`|string
|**clusterOverrides** +
__required__|**Example** : `[ "object" ]`|< object > array
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_packagefilter]]
**packageFilter**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**annotations** +
__optional__|**Example** : `{
  "string" : "string"
}`|< string, string > map
|**filterRef** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_subscriptions_jsonsubscription_packagefilter_filterref,filterRef>>
|**labelSelector** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_subscriptions_jsonsubscription_packagefilter_labelselector,labelSelector>>
|**version** +
__optional__|**Pattern** : `"([0-9]+)((\\.[0-9]+)(\\.[0-9]+)\|(\\.[0-9]+)?(\\.[xX]))$"` +
**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_packagefilter_filterref]]
**filterRef**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**name** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_packagefilter_labelselector]]
**labelSelector**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**matchExpressions** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_subscriptions_jsonsubscription_packagefilter_labelselector_matchexpressions,matchExpressions>> > array
|**matchLabels** +
__optional__|**Example** : `{
  "string" : "string"
}`|< string, string > map
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_packagefilter_labelselector_matchexpressions]]
**matchExpressions**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**key** +
__required__|**Example** : `"string"`|string
|**operator** +
__required__|**Example** : `"string"`|string
|**values** +
__optional__|**Example** : `[ "string" ]`|< string > array
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_packageoverrides]]
**packageOverrides**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**packageAlias** +
__optional__|**Example** : `"string"`|string
|**packageName** +
__required__|**Example** : `"string"`|string
|**packageOverrides** +
__optional__|**Example** : `[ "object" ]`|< object > array
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_placement]]
**placement**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**clusterSelector** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_subscriptions_jsonsubscription_placement_clusterselector,clusterSelector>>
|**clusters** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_subscriptions_jsonsubscription_placement_clusters,clusters>> > array
|**local** +
__optional__|**Example** : `true`|boolean
|**placementRef** +
__optional__|**Example** : `"object"`|<<_rhacm-docs_apis_subscriptions_jsonsubscription_placement_placementref,placementRef>>
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_placement_clusterselector]]
**clusterSelector**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**matchExpressions** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_subscriptions_jsonsubscription_placement_clusterselector_matchexpressions,matchExpressions>> > array
|**matchLabels** +
__optional__|**Example** : `{
  "string" : "string"
}`|< string, string > map
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_placement_clusterselector_matchexpressions]]
**matchExpressions**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**key** +
__required__|**Example** : `"string"`|string
|**operator** +
__required__|**Example** : `"string"`|string
|**values** +
__optional__|**Example** : `[ "string" ]`|< string > array
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_placement_clusters]]
**clusters**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**name** +
__required__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_placement_placementref]]
**placementRef**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__optional__|**Example** : `"string"`|string
|**fieldPath** +
__optional__|**Example** : `"string"`|string
|**kind** +
__optional__|**Example** : `"string"`|string
|**name** +
__optional__|**Example** : `"string"`|string
|**namespace** +
__optional__|**Example** : `"string"`|string
|**resourceVersion** +
__optional__|**Example** : `"string"`|string
|**uid** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_timewindow]]
**timewindow**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**daysofweek** +
__optional__|**Example** : `[ "string" ]`|< string > array
|**hours** +
__optional__|**Example** : `[ "object" ]`|< <<_rhacm-docs_apis_subscriptions_jsonsubscription_timewindow_hours,hours>> > array
|**location** +
__optional__|**Example** : `"string"`|string
|**windowtype** +
__optional__|**Example** : `"string"`|enum (active, blocked, Active, Blocked)
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_timewindow_hours]]
**hours**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**end** +
__optional__|**Example** : `"string"`|string
|**start** +
__optional__|**Example** : `"string"`|string
|===

[[_rhacm-docs_apis_subscriptions_jsonsubscription_status]]
**status**

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**lastUpdateTime** +
__optional__|**Example** : `"string"`|string (date-time)
|**message** +
__optional__|**Example** : `"string"`|string
|**phase** +
__optional__|**Example** : `"string"`|string
|**reason** +
__optional__|**Example** : `"string"`|string
|**statuses** +
__optional__|**Example** : `"object"`|object
|===





