[#add-ons-klusterlet]
= Enabling klusterlet add-ons on clusters from the multicluster engine for Kubernetes operator 

After you install {product-title} and then create or import clusters with the multicluster engine for Kubernetes operator, you can enable the klusterlet add-ons for those managed clusters.

The klusterlet add-ons are not enabled by default if you created or imported clusters with the multicluster engine for Kubernetes operator. Additionally, klusterlet add-ons are not enabled by default after {product-title-short} is installed.

See the following available klusterlet add-ons:

- application-manager
- cert-policy-controller
- config-policy-controller
- iam-policy-controller
- governance-policy-framework
- search-collector

Complete the following steps to enable the klusterlet add-ons for the managed clusters after the {product-title-short} is installed:

. Create a YAML file that is similar to the following `KlusterletAddonConfig`, with the `spec` value that represents the add-ons:

+
[source,yaml]
----
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: <cluster_name>
  namespace: <cluster_name>
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
----
+
**Note:** The `policy-controller` add-on is divided into two add-ons: The `governance-policy-framework` and the `config-policy-controller`. As a result, the `policyController` controls the `governance-policy-framework` and the `config-policy-controller` `managedClusterAddons`.

. Save the file as `klusterlet-addon-config.yaml`.
. Apply the YAML by running the following command on the hub cluster:

+
----
oc apply -f klusterlet-addon-config.yaml
----
 
. To verify whether the enabled `managedClusterAddons` are created after the `KlusterletAddonConfig` is created, run the following command:

+
----
oc get managedclusteraddons -n <cluster namespace>
----

