[#red-hat-advanced-cluster-management-for-kubernetes-contributing-external]
= Contributing to Red Hat Advanced Cluster Management for Kubernetes staged documentation

IMPORTANT: **This contributing doc is for EXTERNAL USERS. **If you are a Red Hat associate, please use BugZilla or our _internal_ https://github.com/stolostron/backlog/issues/new/choose[GitHub documentation team template].

See the following information to contribute to the docs as an external user.

[#how-do-i-submit-a-change]
== How do I submit a change?

Because most changes need to be reviewed by development, doc, and QE, open an issue with the suggestion and let the team make the changes after discussion. 

You can create a PR if your change is small and requires no debate, but **we still need a GitHub issue** opened for tracking purposes. You must fork the project and create your own branch to create a pull request. 

The documentation source is in https://asciidoc.org/[AsciiDoc] format, and the content that is provided in PRs must conform to the AsciiDoc requirements. You can find some guidance for authoring in AsciiDoc in the https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference].

Note: All PRs outside of a typo fix require an issue.

Open an issue here: https://github.com/stolostron/rhacm-docs/issues/new[https://github.com/open-cluster-management/rhacm-docs/issues/new]. Complete the template with the information that is required for your requested change. 

[#how-is-my-issue-handled]
== How is my issue handled?

Your new issue goes into the _new_ issues column on our ZenHub board, where it will be assigned to the correct writer. This is our open, doc-only board. Internal issues between development and doc are in the team's backlog and treated the same.

Once the change from your issue is accepted, reviewed, and merged into the staging docs for that release, we will let you know in the issue comments and you can close the issue.


[#what-branch-am-i-on]
== What branch am I on?

You are currently viewing the a staged default branch, which is the _in-progress_ branch. **WARNING:** The default branch is in progress and used for internal development only. You need to checkout a _supported_ branch before you create a PR.

We support documentation for the current release, and the previous 2 releases (n-2). We refresh these releases weekly. If you need an update that is exclusive to a previous release, https://github.com/stolostron/rhacm-docs/issues/new[open an issue] and propose that change. 


[#which-branch-do-i-choose]
=== Which branch do I choose?

Currently supported versions and branches:

[%header,cols=3*] 
|===
|Release
|Branch
|Release status

|2.6
|https://github.com/stolostron/rhacm-docs/tree/2.6_stage[2.6_stage]
|Live: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/[Red Hat Advanced Cluster Management for Kubernetes version 2.6]

|2.5
|https://github.com/stolostron/rhacm-docs/tree/2.5_stage[2.5_stage]
|Live: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/[Red Hat Advanced Cluster Management for Kubernetes version 2.5]

|2.4
|https://github.com/stolostron/rhacm-docs/tree/2.4_stage[2.4_stage]
|Live: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/[Red Hat Advanced Cluster Management for Kubernetes version 2.4]

|===


