[#channels]
= Operator channels

With the {gk-operator}, you have access to two types of channels to help you make upgrades. These channels are the `stable` channel and the `y-stream version` channel.

With the `stable` channel, you can access the latest available version, including z-streams if relevant. For example, with the `stable` channel, you can access `v1.2.0`, `v1.2.1`, and also `v1.3.0`, if `v1.2.1` were released before `v1.3.0`. In this example, if another version `v1.2.2` were released after `v1.3.0`, it would not be included in the `stable` channel.

With the `y-stream version` channel, you can access all the z-streams for a particular y-stream. For example, the channel `1.2` could have `v1.2.0`, `v1.2.1`, `v1.2.2`, and more, but it would not include `v1.3.0`.

== Operator versioning

The {gk-operator} version aligns with the Open Policy Agent Gatekeeper version, reserving the z-stream for operator updates. For example, a newly released {gk-operator} might start with a version of `v1.2.2` to align with the currently available Open Policy Agent Gatekeeper `v1.2.2`. But an earlier operator update might release with {gk-operator} version `v1.2.3` even though the deployed Gatekeeper is still equal to `v1.2.2`. To view the aligning Open Policy Agent Gatekeeper for a particular operator version, see the associated {gk-operator} Errata.