[#configure-gatekeeper-operator]
= Configuring the {gate} 

To install Gatekeeper on your hub cluster, install the {gate} from the {ocp} catalog. See _Adding Operators to a cluster_ in the {ocp-short} documentation. Configure the {acm-short} Gatekeeper policy by using the governance framework.

After you install the {gate}, you must configure the {gate} custom resource to install Gatekeeper.

*Required access*: Cluster administrator

[#gatekeeper-custom-resource]
== Gatekeeper custom resource sample

The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster, using the given configuration. To work with a {gate} custom resource, use the following sample YAML: 

[source,yaml]
----
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    replicas: 1
      auditEventsInvolvedNamespace: Enabled <1>
    logLevel: DEBUG
    auditInterval: 10s
    constraintViolationLimit: 55
    auditFromCache: Enabled
    auditChunkSize: 66
    emitAuditEvents: Enabled
    resources:
      limits:
        cpu: 500m
        memory: 150Mi
      requests:
        cpu: 500m
        memory: 130Mi
  validatingWebhook: Enabled
  mutatingWebhook: Enabled
  webhook:
    replicas: 3
    emitAdmissionEvents: Enabled
    admissionEventsInvolvedNamespace: Enabled <2>
    disabledBuiltins: - http.send
    operations: <3>
     - "CREATE"
     - "UPDATE"
     - "CONNECT"
    failurePolicy: Fail
    resources:
      limits:
        cpu: 480m
        memory: 140Mi
      requests:
        cpu: 400m
        memory: 120Mi
  nodeSelector:
    region: "EMEA"
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              auditKey: "auditValue"
          topologyKey: topology.kubernetes.io/zone
  tolerations:
    - key: "Example"
      operator: "Exists"
      effect: "NoSchedule"
  podAnnotations:
    some-annotation: "this is a test"
    other-annotation: "another test"
----
*Note:* For versions 3.14 or later, you cam implement the following features to this YAML:

<1> Enable the `auditEventsInvolvedNamespace` parameter to manage the namespace audit event you want to create. When you enable this parameter, the Gatekeeper controller deployment gets the following argument: `--audit-events-involved-namespace: true`.
<2> Enable the `admissionEventsInvolvedNamespace` parameter to manage the namespace admission event you want to create. When you enable this parameter, the Gatekeeper controller deployment gets the following argument: `--admission-events-involved-namespace: true`.
<3> To manage your webhook operations, use the following values for the `operations` parameter, `"CREATE"`, `"UPDATE"`, `"CONNECT"`, and `"DELETE"`.

[#configuring-audit-sync]
== Configuring _auditFromCache_ for sync details

For versions 3.14 or later, the {gate} exposes a setting in the {gate} custom resource for the audit configuration with the `auditFromCache` parameter, which is disabled by default. If you enable `auditFromCache`, you need to set `config.gatekeeper.sh` with the objects to sync to the cache. For more information, see _Configuring Audit_ in the Gatekeeper documentation.

When you set the `auditFromCache` parameter to `Automatic`, the {gate} collects resources from constraints and inserts those resources into your Gatekeeper `Config` resource. If the resource does not exist, the {gate} creates the `Config` resource.

To configure the `auditFromCache` parameter for resource collection from constraints, complete the following steps: 

. Set `auditFromCache` to `Automatic` in the `Gatekeeper` resource. See the following example:

+
[source,yaml]
----
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper 
metadata: 
  name: gatekeeper 
spec: 
  audit: replicas: 2 
    logLevel: DEBUG 
    auditFromCache: Automatic
----


. To verify that the resources are added to your `Config` resource, view that the `syncOnly` parameter section is added. Run the following command:

+
[source,bash]
----
oc get configs.config.gatekeeper.sh config -n openshift-gatekeeper-system
----
+
Your `Config` resource might resemble the following example:

+
[source,yaml]
----
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
 name: config
 namespace: "openshift-gatekeeper-system"
spec:
 sync:
   syncOnly:
   - group: ""
     version: "v1"
     kind: "Namespace"
   - group: ""
     version: "v1"
     kind: "Pod"
----

. Get the explanation of the `auditFromCache` setting to view the description of the custom resource by running the following command:

+
[source,bash]
----
oc explain gatekeeper.spec.audit.auditFromCache
----

[#additional-resources]
== Additional resources 

 For more information, see link:https://open-policy-agent.github.io/gatekeeper/website/docs/audit/#configuring-audit[Configuring Audit] in the Gatekeeper documentation.