[#gatekeeper-operator-overview]
= Gatekeeper operator overview 

Gatekeeper is a validating webhook with auditing capabilities. You can install Gatekeeper on a {ocp} cluster from the {ocp} operator catalog. With {rhacm}, you can install Gatekeeper on your {ocp} managed cluster by using the {gate} policy to install the Red Hat {gate}. After you install Gatekeeper, use it for the following benefits: 

- Deploy and check Gatekeeper `ConstraintTemplates` and constraints on managed clusters by using the {product-title-short} policy integration. 
- Enforce Kubernetes custom resource definition-based policies that run with your Open Policy Agent (OPA).
- Evaluate Kubernetes resource compliance requests for the Kubernetes API by using the Gatekeeper constraints.
- Use OPA as the policy engine and use Rego as the policy language.

*Prerequisite:* You need a {acm} or {ocp} Plus subscription to install Gatekeeper and apply Gatekeeper policies to your cluster. Gatekeeper is supported only on {ocp-short} versions, except version 3.11, supported by the latest version of {acm-short}.

To learn more about using the Gatekeeper operator, see the following resources:

- xref:../gatekeeper_operator/requirements.adoc#requirements[Requirements]
- xref:../gatekeeper_operator/channels.adoc#channels[Operator channels]
- xref:../gatekeeper_operator/gatekeeper_policy_constraints.adoc#gatekeeper-policy[Integrating Gatekeeper constraints and constraint templates]
- xref:../gatekeeper_operator/manage_gatekeeper.adoc#managing-gatekeeper-operator-policies[Managing Gatekeeper operator policies]

[#operator-versions]
== Operator versions

The {gate} version aligns with the Open Policy Agent Gatekeeper version, reserving the z-stream for operator updates. For example, a newly released {gate} might start with a version of `v1.2.2` to align with the currently available Open Policy Agent Gatekeeper `v1.2.2`. But an earlier operator update might release with the {gate} version `v1.2.3` even though the deployed Gatekeeper is still equal to `v1.2.2`. To view the aligning Open Policy Agent Gatekeeper for a particular operator version, see the associated {gate} Errata.