[#gatekeeper-operator-overview]
= Gatekeeper operator overview 

Gatekeeper is a validating webhook with auditing capabilities. Install Gatekeeper on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper on your {ocp} managed cluster by using the {gate} policy to install the Red Hat {gate}. After you install Gatekeeper, use it for the following benefits: 

- Deploy and check Gatekeeper `ConstraintTemplates` and constraints on managed clusters by using the {acm-short} policy integration. 
- Enforce Kubernetes custom resource definition-based policies that run with your Open Policy Agent (OPA).
- Evaluate Kubernetes resource compliance requests for the Kubernetes API by using the Gatekeeper constraints.
- Use OPA as the policy engine and use Rego as the policy language.

*Prerequisite:* You need a {acm} or {ocp} Plus subscription to install Gatekeeper and apply Gatekeeper policies to your cluster. Gatekeeper is only supported on {ocp-short} versions, except for version 3.11.

To learn more about using the Gatekeeper operator, see the following resources:

- xref:../gatekeeper_operator/requirements.adoc#requirements[Requirements]
- xref:../gatekeeper_operator/channels.adoc#channels[Operator channels]
- xref:../gatekeeper_operator/gatekeeper_policy_constraints.adoc#integrating-gatekeeper-constraints-templates[Integrating Gatekeeper constraints and constraint templates]
- xref:../gatekeeper_operator/manage_gatekeeper.adoc#managing-gatekeeper-operator-installation-policies[Managing Gatekeeper operator policies]