[#managing-gatekeeper-operator-installation-policies]
= Managing the {gate} installation policies

Use the {acm-short} policy to install the {gate} and Gatekeeper on a managed cluster. 

*Required access*: Cluster administrator

To create, view, and update your {gate} installation policies, complete the following sections: 

. <<working-custom-resource,Working with the {gate} custom resource>>
. <<configuring-audit-sync,Configuring _auditFromCache_ for sync details>>
. <<installing-gatekeeper-operator-policy,Installing Gatekeeper using a Gatekeeper operator policy>>
. <<creating-a-gatekeeper-policy-from-the-console,Creating a Gatekeeper policy from the console>>
. <<upgrading-gatekeeper-gatekeeper-operator,Upgrading Gatekeeper and the Gatekeeper operator>>
. <<updating-gatekeeper-operator-policy,Updating Gatekeeper operator policy>>
. <<deleting-gatekeeper-operator-policy,Deleting Gatekeeper operator policy>>
. <<uninstalling-gatekeeper,Uninstalling Gatekeeper policy, Gatekeeper, and Gatekeeper operator policy>>

[#working-custom-resource]
== Working with the {gate} custom resource

The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster using the given configuration. If you want to work with a {gate} custom resource, use the following sample YAML: 

[source,yaml]
----
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    replicas: 1
      auditEventsInvolvedNamespace: Enabled <1>
    logLevel: DEBUG
    auditInterval: 10s
    constraintViolationLimit: 55
    auditFromCache: Enabled
    auditChunkSize: 66
    emitAuditEvents: Enabled
    resources:
      limits:
        cpu: 500m
        memory: 150Mi
      requests:
        cpu: 500m
        memory: 130Mi
  validatingWebhook: Enabled
  mutatingWebhook: Enabled
  webhook:
    replicas: 3
    emitAdmissionEvents: Enabled
    admissionEventsInvolvedNamespace: Enabled <2>
    disabledBuiltins: - http.send
    operations: <3>
     - "CREATE"
     - "UPDATE"
     - "CONNECT"
    failurePolicy: Fail
    resources:
      limits:
        cpu: 480m
        memory: 140Mi
      requests:
        cpu: 400m
        memory: 120Mi
  nodeSelector:
    region: "EMEA"
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              auditKey: "auditValue"
          topologyKey: topology.kubernetes.io/zone
  tolerations:
    - key: "Example"
      operator: "Exists"
      effect: "NoSchedule"
  podAnnotations:
    some-annotation: "this is a test"
    other-annotation: "another test"
----
*Note:* For versions 3.14 or later, you cam implement the following features to this YAML:

<1> Enable the `auditEventsInvolvedNamespace` parameter to manage the namespace audit event you want to create. When you enable this parameter, the Gatekeeper controller deployment gets the following argument: `--audit-events-involved-namespace: true`.
<2> Enable the `admissionEventsInvolvedNamespace` parameter to manage the  namespace admission event you want to create. When you enable this parameter, the Gatekeeper controller deployment gets the following argument: `--admission-events-involved-namespace: true`.
<3> To manage your webhook operations, use the following values for the `operations` parameter, `"CREATE"`, `"UPDATE"`, `"CONNECT"`, and `"DELETE"`.

To install the Gatekeeper operator with {rhacm-short}, use the governance framework. The {gate} is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.16/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[{ocp-short} documentation] for more information.

[#configuring-audit-sync]
== Configuring _auditFromCache_ for sync details

For versions 3.14 or later, the {gate} exposes a setting in the {gate} custom resource for the audit configuration with the parameter `auditFromCache`, which is disabled by default. If you enable `auditFromCache`, then you need to set `config.gatekeeper.sh` with the objects to sync to the cache. For more information, see link:https://open-policy-agent.github.io/gatekeeper/website/docs/audit/#configuring-audit[Configuring Audit] in the Gatekeeper documentation.

The {gate} collects resources from constraints, and you can install and insert those resources into your config resource. If resources do not exist, use the operator to create config resources.

To configure `auditFromCache` with "Automatic", complete the following steps: 

. Set `auditFromCache` to `Automatic` in the `Gatekeeper` resource. See the following example:

+
[source,yaml]
----
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper 
metadata: 
  name: gatekeeper 
spec: 
  audit: replicas: 2 
    logLevel: DEBUG 
    auditFromCache: Automatic
----

+

. See the {gate} adds the `syncOnly` parameter section to your config file. See the following example:

+
[source,yaml]
----
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
 name: config
 namespace: "openshift-gatekeeper-system"
spec:
 sync:
   syncOnly:
   - group: ""
     version: "v1"
     kind: "Namespace"
   - group: ""
     version: "v1"
     kind: "Pod"
----

. Get the explanation of the `auditFromCache` setting by running the following command from your terminal:

+
[source,bash]
----
oc explain gatekeeper.spec.audit.auditFromCache
----

[#installing-gatekeeper-operator-policy]
== Installing Gatekeeper using a Gatekeeper operator policy

To install the Gatekeeper operator policy, use the configuration policy controller. During the install, the operator group and subscription pull the Gatekeeper operator to install it in your managed cluster. Then, the Gatekeeper operator creates a Gatekeeper custom resource to configure Gatekeeper. See the <<working-custom-resource,Gatekeeper operator custom resource>> sample.

To view the status of the Gatekeeper operator policy, see the {acm-short} configuration policy controller because it checks the Gatekeeper operator policy and supports the  `enforce` remediation action. When you set the controller to `enforce` it automatically creates the Gatekeeper operator objects on the managed cluster. 

[#creating-a-gatekeeper-policy-from-the-console]
== Creating a Gatekeeper policy from the console

To create the policy from the console, complete the following steps:

. Install the Gatekeeper policy by creating a policy from the console. 
.. *Optional:* Go to the _Additional resources_ section for a reference to the sample YAML to deploy `policy-gatekeeper-operator.yaml`.

. After you log in to your cluster, go to the _Governance_ page.

. Select *Create policy*. 

. As you complete the form, select *Gatekeeper Operator* from the _Specifications_ field. The parameter values for your policy are automatically populated and the policy is set to `inform` by default. 

. Set your remediation action to `enforce` to install Gatekeeper.

*Note:* Default values are generated by the operator.

[#upgrading-gatekeeper-gatekeeper-operator]
== Upgrading Gatekeeper and the Gatekeeper operator

You can upgrade the versions for Gatekeeper and the {gate}. When you install the {gate} with the Gatekeeper operator policy, notice the value for `upgradeApproval`. The operator upgrades automatically when you set `upgradeApproval` to `Automatic`.

If you set `upgradeApproval` to `Manual`, you must manually approve the upgrade for each cluster of the {gate}.

[#updating-gatekeeper-operator-policy]
== Updating Gatekeeper operator policy

Update the Gatekeeper operator policy by completing the following: 

- <<viewing-gatekeeper-operator-policy-from-the-console,Viewing Gatekeeper operator policy from the console>>
- <<disabling-gatekeeper-operator-policy,Disabling Gatekeeper operator policy>>

[#viewing-gatekeeper-operator-policy-from-the-console]
=== Viewing Gatekeeper operator policy from the console

View your Gatekeeper operator policy and its status from the console by completing the following steps:

. Log in to your cluster from the console.
. Click *Governance* to view a table list of your policies.
. Filter the table list of your policies by selecting the _Policies_ tab or _Cluster violations_ tab.
. Select the `policy-gatekeeper-operator` policy to view more details. View the policy violations by selecting the _Clusters_ tab.

[#disabling-gatekeeper-operator-policy]
=== Disabling Gatekeeper operator policy

If you need to disable your `policy-gatekeeper-operator` policy, complete the following steps:

. After you log in to your {acm} console, go to the _Governance_ page to view a table list of your policies.
. Select the *Actions* icon for the `policy-gatekeeper-operator` policy.
. Click *Disable*. The _Disable Policy_ dialog box appears.
. Click *Disable policy*. 

[#deleting-gatekeeper-operator-policy]
== Deleting Gatekeeper operator policy

If you need to delete your the Gatekeeper operator policy, you can do so from the CLI or the console.

To delete your Gatekeeper operator policy from your CLI, complete the following steps: 

. Delete Gatekeeper operator policy by running the following command:
+
----
oc delete policies.policy.open-cluster-management.io <policy-gatekeeper-operator-name> -n <namespace>
----
+

 . Verify that you deleted your policy by running the following command:
+
----
oc get policies.policy.open-cluster-management.io <policy-gatekeeper-operator-name> -n <namespace>
----

To delete your Gatekeeper operator policy from the console, complete the following steps:

. Go to the _Governance_ page to view a table list of your policies.
. Click the *Actions* icon for the `policy-gatekeeper-operator` policy. 
. Click *Remove* to delete the policy. 
. From the _Remove policy_ dialog box, click *Remove policy*.

[#uninstalling-gatekeeper]
== Uninstalling Gatekeeper policy, Gatekeeper, and Gatekeeper operator policy

To uninstall Gatekeeper policy, complete the following:

- <<removing-gatekeeper-constraint,Removing Gatekeeper _Constraint_>>
- <<removing-gatekeeper-instance,Removing Gatekeeper instance>>
- <<removing-gatekeeper-operator,Removing Gatekeeper operator>>

[#removing-gatekeeper-constraint]
=== Removing Gatekeeper _Constraint_

To remove the Gatekeeper constraint and `ConstraintTemplate` from your managed cluster, complete the following steps:

. Edit your Gatekeeper constraint or `ConstraintTemplate` policy. 
. Locate the template that you used to create the Gatekeeper `Constraint` and `ConstraintTemplate`.
. Delete the entries from the list of templates. (Or delete the policy if they're the only templates.)
. Save and apply the policy.

[#removing-gatekeeper-instance]
=== Removing Gatekeeper instance 

To remove the Gatekeeper instance from your managed cluster, complete the following steps:

. Edit your Gatekeeper operator policy. 
. Locate the `ConfigurationPolicy` template that you used to create the Gatekeeper custom resource.
. Change the value for `complianceType` of the `ConfigurationPolicy` template to `mustnothave`.

[#removing-gatekeeper-operator]
=== Removing Gatekeeper operator

To remove the Gatekeeper operator from your managed cluster, complete the following steps: 

. Edit your Gatekeeper operator policy. 
. Locate the `OperatorPolicy` template that you used to create the Subscription CR.
. Change the value for `complianceType` of the `OperatorPolicy` template to `mustnothave`.

[#additional-resources-gk-operator]
== Additional resources

For more details, see the following resources: 

- xref:../gatekeeper_operator/gatekeeper_policy_constraints.adoc#integrating-gatekeeper-constraints-templates[Integrating Gatekeeper constraints and constraint templates].

- link:https://github.com/open-cluster-management-io/policy-collection/blob/main/stable/CM-Configuration-Management/policy-gatekeeper-operator-downstream.yaml[Policy Gatekeeper].

- For an explanation of the optional parameters that can be used for the Gatekeeper operator policy, see link:https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md[Gatekeeper Helm Chart].

- For a list of topics to integrate third-party policies with the product, see xref:../governance/third_party_policy_intro.adoc#integrate-third-party-policy-controllers[Integrate third-party policy controllers]. 

