[#import-discover-rosa]
= Automating import for discovered {rosa} on AWS clusters

Automate the import of {rosa} clusters by using {product-title-short} policy enforcement for faster cluster management, without manually importing individual clusters.

*Required access:* Cluster administrator

* <<autoimport-disc-prereq,Prerequisites>>
* <<creating-rosa-policy,Creating the automatic import policy>>
* <<create-rosa-placement,Creating the placement definition>>
* <<bind-rosa-placement,Binding the import policy to a placement definition>>

[#autoimport-disc-prereq]
== Prerequisites

* You need {product-title-short} installed. See the {product-title-short} link:../../install/install_overview.adoc#installing[Installing and upgrading] documentation.
* You need to learn about _Policies_. See the introduction to link:../../governance/grc_intro.adoc#governance[Governance] in the {product-title-short} documentation.

[#creating-rosa-policy]
== Creating the automatic import policy

The following policy and procedure is an example of how to import all your discovered {rosa} clusters automatically. 
 
Log in to your hub cluster from the CLI to complete the following procedure:

. Create a YAML file with the following example and apply the changes that are referenced:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-rosa-autoimport
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/description: OpenShift Service on AWS discovered clusters can be automatically imported into
Red Hat Advanced Cluster Management as managed clusters with this policy. You can select and configure those managed clusters so you can import. Configure filters or add an annotation if you do not want all of your OpenShift Service on AWS clusters to be automatically imported.      
spec: 
  remediationAction: inform <1>
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rosa-autoimport-config
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: discovery-config
                  namespace: open-cluster-management-global-set
                data:
                  rosa-filter: "" <2>
          remediationAction: enforce
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-rosa-autoimport
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |
            {{- /* find the ROSA DiscoveredClusters */ -}}
            {{- range $dc := (lookup "discovery.open-cluster-management.io/v1" "DiscoveredCluster" "" "").items }}
              {{- /* Check for the flag that indicates the import should be skipped */ -}}
              {{- $skip := "false" -}}
              {{- range $key, $value := $dc.metadata.annotations }}
                {{- if and (eq $key "discovery.open-cluster-management.io/previously-auto-imported")
                           (eq $value "true") }}
                  {{- $skip = "true" }}
                {{- end }}
              {{- end }}
              {{- /* if the type is ROSA and the status is Active */ -}}
              {{- if and (eq $dc.spec.status "Active") 
                         (contains (fromConfigMap "open-cluster-management-global-set" "discovery-config" "rosa-filter") $dc.spec.displayName)
                         (eq $dc.spec.type "ROSA")
                         (eq $skip "false") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: discovery.open-cluster-management.io/v1
                kind: DiscoveredCluster
                metadata:
                  name: {{ $dc.metadata.name }}
                  namespace: {{ $dc.metadata.namespace }}
                spec:
                  importAsManagedCluster: true
              {{- end }}
            {{- end }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-rosa-managedcluster-status
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |
            {{- /* Use the same DiscoveredCluster list to check ManagedCluster status */ -}}
            {{- range $dc := (lookup "discovery.open-cluster-management.io/v1" "DiscoveredCluster" "" "").items }}
              {{- /* Check for the flag that indicates the import should be skipped */ -}}
              {{- $skip := "false" -}}
              {{- range $key, $value := $dc.metadata.annotations }}
                {{- if and (eq $key "discovery.open-cluster-management.io/previously-auto-imported")
                           (eq $value "true") }}
                  {{- $skip = "true" }}
                {{- end }}
              {{- end }}
              {{- /* if the type is ROSA and the status is Active */ -}}
              {{- if and (eq $dc.spec.status "Active")
                         (contains (fromConfigMap "open-cluster-management-global-set" "discovery-config" "rosa-filter") $dc.spec.displayName)
                         (eq $dc.spec.type "ROSA")
                         (eq $skip "false") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  name: {{ $dc.spec.displayName }}
                  namespace: {{ $dc.spec.displayName }}
                status:
                  conditions:
                    - type: ManagedClusterConditionAvailable
                      status: "True"
              {{- end }}
            {{- end }}
----
<1> To enable automatic import, change the `spec.remediationAction` to `enforce`. 
<2> Optional: Specify a value here to select a subset of the matching {rosa} clusters, which are based on _discovered_ cluster names. The `rosa-filter` has no value by default, so the filter does not restrict cluster names without a subset value.
 
. Run `oc apply -f <filename>.yaml -n <namespace>` to apply the file.

[#create-rosa-placement]
== Creating the placement definition 

You need to create a placement definition that specifies the managed cluster for the policy deployment.

. Create the placement definition that selects only the `local-cluster`, which is a hub cluster that is managed. Use the following YAML sample:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-openshift-plus-hub
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: name
      	    operator: In
      	    values:
      	    - local-cluster
----

. Run `oc apply -f placement.yaml -n <namespace>`, where `namespace` matches the namespace that you used for the policy that you previously created. 

[#bind-rosa-placement]
== Binding the import policy to a placement definition

After you create the policy and the placement, you need to connect the two resources.

. Connect the resources by using a `PlacementBinding`. See the following example where `placementRef` points to the `Placement` that you created, and `subjects` points to the `Policy` that you created:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-rosa-autoimport
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-policy-rosa-autoimport
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: policy-rosa-autoimport
----

. To verify, run the following command:

+
----
oc get policy policy-rosa-autoimport -n <namespace>
---- 
