[#adding-hosts-to-an-infrastructure-environment]
= Adding hosts to an infrastructure environment

You can use the {product-title} console to add hosts to an infrastructure environment. Adding the hosts makes it easier to select the already-configured hosts when you are creating a cluster. 

Complete the following steps to add a host:

. From the {product-title-short} navigation, select *Infrastructure* > *Infrastructure environments*.

. Select the infrastructure environment where you want to add the host to view its settings.

. Select the _Hosts_ tab to view the hosts that are already added to that environment and to add a host. Available hosts might take a few minutes to appear in the table. 

. Select *Discovery ISO* or *Baseboard Management Controller (BMC)* to enter the information for your host. 

. If you select the *Discovery ISO* option, complete the following steps:
 
.. Copy the command that is provided in the console to download the ISO or select *Download Discovery ISO*. 

.. Run the command on a bootable device to start each host.

.. For added security, select *Approve host* for each of the discovered hosts. This additional step offers some protection in case your ISO file is changed and run by an unauthorized person. 

.. Rename the hosts that are named, `localhost` to unique names.  

. If you select *Baseboard Management Controller (BMC)* option, complete the following steps:
+
*Note:* The BMC option for adding hosts can only be used when the platform of your {product-title-short} hub cluster is bare metal, Red Hat OpenStack Platform, VMware vSphere, or was installed using the user-provisioned infrastructure (UPI) method and the platform is `None`. 

.. Add the connection details for the BMC of your host. 

.. Select *Add host* to start the boot process. The host is automatically booted by using the discovery ISO image, and is added to the list of hosts when it is started. 
+
When you add a host by using the BMC option, the host is automatically approved.

You can now create an on-premises cluster on this infrastructure environment. See xref:../multicluster_engine/create_cluster_on_prem.adoc#creating-a-cluster-on-premises[Creating a cluster in an on-premises environment] for more information about creating a cluster.
