[#managing-cluster-pools]
= Managing cluster pools (Technology preview)

Cluster pools provide rapid and cost-effective access to configured {ocp} clusters on-demand and at scale. Cluster pools maintain a configurable and scalable number of {ocp-short} clusters on Amazon Web Services, Google Cloud Platform, or Microsoft Azure in a hibernating state that can be claimed when they are needed. They are especially useful when providing or replacing cluster environments for development, continuous integration, and production scenarios.

ClusterClaim resources are used to checkout clusters from cluster pools. After a cluster is checked out from a cluster pool, the checked out cluster is resumed and brought to a ready state. The cluster pool will automatically create a new hibernated cluster, to replace the claimed one, in the cluster pool.

*Note:* When a cluster that was claimed from the cluster pool is no longer needed and is destroyed, the resources are deleted. The cluster does not return to the cluster pool.

* <<creating-a-clusterpool,Creating a cluster pool>>
* <<adding-clusters-to-a-clusterpool,Adding clusters to a cluster pool>>
* <<scaling-a-clusterpool,Scaling a cluster pool>>
* <<updating-the-clusterpool-release-image,Updating the cluster pool release image>>
* <<deleting-a-clusterpool,Deleting a cluster pool>>

[#creating-a-clusterpool]
== Creating a cluster pool

The procedure for creating a cluster pool is similar to the procedure for creating a cluster. Clusters in a cluster pool are not created for immediate use.

*Required access*: admin

[#pool_prerequisites]
=== Prerequisites

You must have the following prerequisites before creating a cluster pool:

* A deployed {product-title} hub cluster
* Internet access for your {product-title} hub cluster so it can create the Kubernetes cluster on the provider environment.
* An AWS, GCP, or Microsoft Azure provider credential.
See link:../credentials/credential_intro.adoc#credentials[Managing credentials overview] for more information.
* A configured domain in your provider environment.
See your provider documentation for instructions about how to configure a domain.
* Provider login credentials.
* A {ocp-short} image pull secret.
See https://docs.openshift.com/container-platform/4.7/openshift_images/managing_images/using-image-pull-secrets.html[Using image pull secrets].

[#pool_create]
=== Create a cluster pool

To create a cluster pool, complete the following steps:

. From the navigation menu, click *Infrastructure* > *Clusters*.

. Select the *Cluster pools* tab to view cluster pools that you can access.

. Select *Create cluster pool*. 

. Enter a name for your cluster pool.

. Enter the namespace where you want to create your cluster pool. You can select an existing namespace from the list, or type the name of a new one to create one. The cluster pool does not have to be in the same namespace as the clusters.

. Optional: Select a cluster set name if you want the RBAC roles for your cluster pool to share the role assignments of an existing cluster set. 

. Enter the number of clusters that you want available in your cluster pool by adding the number to the cluster pool size.
  
. Select *Next*.

. Enter the required information in the remaining steps to complete to provision your cluster pool. The procedure from this point on is the same as the procedure for creating clusters. 
+
For specific information about the information that is required for your provider, see the following information:
+
* xref:../clusters/create_ocp_aws.adoc#creating-a-cluster-on-amazon-web-services[Creating a cluster on Amazon Web Services]
* xref:../clusters/create_google.adoc#creating-a-cluster-on-google-cloud-platform[Creating a cluster on Google Cloud Platform]
* xref:../clusters/create_azure.adoc#creating-a-cluster-on-microsoft-azure[Creating a cluster on Microsoft Azure]

10. After all of the information is entered, select *Create* to create the cluster pool. After at least one cluster is available in the pool, a *Claim cluster* button appears.

