[#multicluster_engine_overview]
= Cluster lifecycle overview

Your cluster is created by using the {ocp} cluster installer with the Hive resource. After you install {ocp-short} and the {mce}, you can manage clusters with cluster lifecycle features with your {ocp-short} hub cluster. If you install {product-title-short}, you get more advanced cluster management and {mce-short} is installed automatically. 

*Note:* {product-title-short} is not a requirement for the Cluster lifecycle features.

You can create, manage, and monitor other Kubernetes clusters with the hub cluster. Those managed clusters are created and managed by the {mce-short}, which is installed automatically with {product-title-short}.  

The managed clusters are Kubernetes clusters that are managed by the hub cluster with {mce-short}. You can create clusters by using the {product-title-short} hub cluster, while you can also import existing clusters to be managed by the hub cluster.

Find more information about the process of installing {ocp-short} clusters at https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/installing/ocp-installation-overview[OpenShift Container Platform installation overview].

The cluster lifecylce component is provided by the {mce}. After you install {product-title}, you can continue adding and managing clusters in the cluster lifecycle phase. Start with link:../clusters/cluster_lifecycle/cluster_lifecycle_intro.adoc#cluster-overview[Cluster lifecycle overview] and all the documentation for that operator. 

For {ocp-short} users without {product-title-short}, see information about using {mce-short} with {ocp-short} https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/architecture/mce-overview-ocp[Cluster management with multicluster engine on OpenShift Container Platform].


Release images are the version of {ocp-short} that you use when you create a cluster. For clusters that are created using {product-title-short}, you can enable automatic upgrading of your release images. For more information about release images in {product-title-short}, see xref:../cluster_lifecycle/release_images.adoc#release-images[Release images].

* xref:about/mce_intro.adoc#mce-intro[About the multicluster engine for Kubernetes operator]
* xref:release_notes/release_notes_intro.adoc#mce-release-notes[Release notes]
* xref:install_upgrade/install_intro.adoc#mce-install-intro[Install]
* xref:credentials/credential_intro.adoc#credentials[Managing credentials]
* xref:cluster_lifecycle/cluster_lifecycle_intro.adoc#cluster-overview[The multicluster engine for Kubernetes operator cluster lifecycle overview]
* xref:discovery/discovery_intro.adoc#discovery-intro[Discovery service introduction]
* xref:api/api_intro.adoc#apis[APIs]
* xref:support_troubleshooting/troubleshooting_mce_intro.adoc#troubleshooting-mce[Troubleshooting]

The components of the cluster lifecycle management architecture are included in the link:../clusters/cluster_lifecycle/cluster_lifecycle_arch.adoc#cluster-lifecycle-arch[Cluster lifecycle architecture].


