[#cluster-lifecycle-architecture]
= Cluster lifecycle architecture


{product-title} has two main types of clusters: _hub clusters_ and _managed clusters_, which are created and managed by the multicluster engine for Kubernetes operator. See the link:../multicluster_engine/multicluster_engine_overview.adoc#mce-overview[The multicluster engine for Kubernetes overview] that covers everything from installation to troubleshooting.

To continue adding and managing clusters in the cluster lifecycle phase, you must start with link:../multicluster_engine/cluster_lifecycle_intro.adoc#cluster-overview[The multicluster engine operator cluster lifecycle overview] and all the documentation for that operator.

Your cluster is created by using the {ocp} cluster installer with the Hive resource. You can find more information about the process of installing clusters at https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/installing/ocp-installation-overview[OpenShift Container Platform installation overview] in the {ocp-short} documentation.  

The components of the cluster lifecycle management architecture are included in the link:../multicluster_engine/cluster_lifecycle_arch.adoc#cluster-lifecycle-arch[Cluster lifecycle architecture].

The hub cluster is the main cluster with {product-title} installed. You can create, manage, and monitor other Kubernetes clusters with the hub cluster. The managed clusters are Kubernetes clusters that are managed by the hub cluster. You can create clusters by using the {product-title-short} hub cluster, while you can also import existing clusters to be managed by the hub cluster.

Release images are the version of {ocp-short} that you use when you create a cluster. For clusters that are created using {product-title-short}, you can enable automatic upgrading of your release images. For more information about release images in {product-title-short}, see xref:../clusters/release_images_acm.adoc#release-images-acm[Release images].
