[#managing-cluster-labels]
= Managing cluster labels

//heavy with UI steps, can be merged into the other cluster claims doc which has multiple sections already

Add a label to your cluster to select group resources.
See https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[Labels and Selectors] for more information.

You can add new labels, remove existing labels, and edit existing labels for your clusters. 

To manage your labels, navigate to *Infrastructure* > *Clusters* and find your cluster in the _Clusters_ table. Use the *Options* menu for the cluster to select *Edit labels*.

* To add a new label, enter a label in the _Edit labels_ dialog box. Your entry must be in the following format: `Key=Value`. If you are adding multiple labels, separate the labels by pressing `enter`, adding a comma, or adding a space between the labels. 
+
Labels are only saved after you click *Save*.
 
* To remove an existing label, click the *Remove* icon for the label that you want to remove in the list.

* To update an existing label, you can reassign its key to a new value by adding a new label using the same key with a different value. For example, you can change `Key=Value` by entering `Key=NewValue` to update the value of `Key`.

*Tip*: You can also edit a cluster label from the cluster details page. In the navigation menu, click *Infrastructure* > *Clusters*. 
From the Clusters page, access the details page for the cluster by clicking the name of the cluster. Select the *Edit* icon in the _Labels_ section. The _Edit labels_ dialog box is displayed.