[#claiming-clusters-from-cluster-pools]
= Claiming clusters from cluster pools

ClusterClaim resources are used to check out clusters from cluster pools. After a cluster is checked out from a cluster pool, the checked out cluster is brought to a ready state. The cluster pool automatically creates a new hibernated cluster in the cluster pool to replace the claimed one.

*Note:* When a cluster that was claimed from the cluster pool is no longer needed and is destroyed, the resources are deleted. The cluster does not return to the cluster pool.

*Required access*: Cluster administrator

[#claim_prerequisites]
== Prerequisites

You must have the following prerequisites before claiiming a cluster from a cluster pool:

* ???

[#claim_cluster]
== Claim the cluster from the cluster pool

To checkout a cluster from the cluster pool, resume the cluster and claim it as one of your managed clusters. 
        
. From the navigation menu, click *Infrastructure* > *Clusters*.

. Select the *Cluster pools* tab.

. Find the name of the cluster pool you want to claim a cluster from and select *Claim cluster*.

. Enter a cluster claim name to help identify the cluster.

. Select *Claim*.

. The claimed cluster comes out of hibernation and appears in the *Managed Cluster* tab with a status of `Resuming`.  After the cluster reaches a status of  `Ready`, the cluster is available for use.
