[#managing-cluster-pools]
= Managing cluster pools (Technology preview)

Cluster pools provide rapid and cost-effective access to configured {ocp} clusters on-demand and at scale. Cluster pools maintain a configurable and scalable number of {ocp-short} clusters on Amazon Web Services, Google Cloud Platform, or Microsoft Azure in a hibernating state that can be claimed when they are needed. They are especially useful when providing or replacing cluster environments for development, continuous integration, and production scenarios.

`ClusterClaim` resources are used to check out clusters from cluster pools. After a cluster is checked out from a cluster pool, the checked out cluster is resumed and brought to a ready state. The cluster pool automatically creates a hibernated cluster in the cluster pool, to replace the claimed one.

*Note:* When a cluster that was claimed from the cluster pool is no longer needed and is destroyed, the resources are deleted. The cluster does not return to the cluster pool.

* <<pool_prerequisites,Prerequisites>>
* <<pool_create,Create a cluster pool>>
* xref:../clusters/cluster_claim.adoc#claiming-clusters-from-cluster-pools[Claiming clusters from cluster pools]
* xref:../clusters/cluster_pool_scale.adoc#scaling-cluster-pools[Scaling cluster pools]
* xref:../clusters/cluster_pool_rel_img_update.adoc#updating-the-cluster-pool-release-image[Updating the cluster pool release image]
* xref:../clusters/cluster_pool_destroy.adoc#destroying-a-cluster-pool[Destroying a cluster pool]

The procedure for creating a cluster pool is similar to the procedure for creating a cluster. Clusters in a cluster pool are not created for immediate use.

*Required access*: Administrator

[#pool_prerequisites]
=== Prerequisites

See the following prerequisites before creating a cluster pool:

* You need to deploy a {product-title} hub cluster.
* You need Internet access for your {product-title} hub cluster so that it can create the Kubernetes cluster on the provider environment.
* You need an AWS, GCP, or Microsoft Azure provider credential. See link:../credentials/credential_intro.adoc#credentials[Managing credentials overview] for more information.
* You need a configured domain in your provider environment. See your provider documentation for instructions about how to configure a domain.
* You need provider login credentials.
* You need your {ocp-short} image pull secret. See https://docs.openshift.com/container-platform/4.9/openshift_images/managing_images/using-image-pull-secrets.html[Using image pull secrets].

**Note:** Adding a cluster pool with this procedure configures it so it automatically imports the cluster to be managed by {product-title-short} when you claim a cluster from the pool. If you would like to create a cluster pool that does not automatically import the claimed cluster for management with the cluster claim, add the following annotation to your `clusterClaim` resource:

[source,yaml]
----
kind: ClusterClaim
metadata:
  annotations:
    cluster.open-cluster-management.io/createmanagedcluster: "false"
----

The word `"false"` must be surrounded by quotation marks to indicate that it is a string.

[#pool_create]
=== Create a cluster pool

To create a cluster pool, complete the following steps:

. From the navigation menu, click *Infrastructure* > *Clusters*.

. Select the _Cluster pools_ tab to view cluster pools that you can access.

. Select *Create cluster pool*. 

. Select the infrastructure provider for your cluster pool.

. Select the infrasctructure credential that you want to use for the cluster pool. You can create one by selecting *Add credential*, if it is not available in the list. 

. Select *Next* to continue to the cluster pool details.

. Enter a name for your cluster pool.

. Enter the namespace where you want to create your cluster pool. You can select an existing namespace from the list, or type the name of a new one to create one. The cluster pool does not have to be in the same namespace as the clusters.
+
When you create a cluster pool in a cluster set, the `namespace admin` permission is applied to all of the users with `clusterset admin` permissions for the namespace where you add the cluster pool. Similarly, the `namespace view` permission is applied to the users with `clusterset view` permissions. 

. Optional: Select a cluster set name if you want the RBAC roles for your cluster pool to share the role assignments of an existing cluster set. The cluster set for the clusters in the cluster pool can only be set when you create the cluster pool. You cannot change the cluster set association for the cluster pool or for the clusters in the cluster pool after you create the cluster pool. Any cluster that you claim from the cluster pool is automatically added to the same cluster set as the cluster pool.
+
*Note:* If you do not have `cluster admin` permissions, you must select a cluster set. The request to create a cluster set is rejected with a forbidden error if you do not include the cluster set name in this situation. If no cluster sets are available for you to select, contact your cluster administrator to create a cluster set and give you `clusterset admin` permissions to it.

. Enter the number of clusters that you want available in your cluster pool by adding the number to the cluster pool size.
  
. Select *Next*.

. Enter the required information in the remaining steps to complete to provision your cluster pool. The procedure from this point on is the same as the procedure for creating clusters. 
+
For specific information about the information that is required for your provider, see the following information:
+
* xref:../clusters/create_ocp_aws.adoc#creating-a-cluster-on-amazon-web-services[Creating a cluster on Amazon Web Services]
* xref:../clusters/create_google.adoc#creating-a-cluster-on-google-cloud-platform[Creating a cluster on Google Cloud Platform]
* xref:../clusters/create_azure.adoc#creating-a-cluster-on-microsoft-azure[Creating a cluster on Microsoft Azure]

. After all of the information is entered, select *Create* to create the cluster pool. After at least one cluster is available in the pool, a *Claim cluster* button appears.



