[#creating-a-cluster-on-openstack]
= Creating a cluster on Red Hat OpenStack Platform

You can use the {product-title} console to deploy a {ocp} cluster on Red Hat OpenStack Platform.

When you create a cluster, the creation process uses the {ocp-short} installer with the Hive resource. If you have questions about cluster creation after completing this procedure, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/installing/installing-on-openstack[Installing on OpenStack] in the {ocp-short} documentation for more information about the process.

* <<openstack-prerequisites,Prerequisites>>
* <<openstack-creating-your-cluster-with-the-console,Creating your cluster with the console>>

[#openstack-prerequisites]
== Prerequisites

You must have the following prerequisites before creating a cluster on Red Hat OpenStack Platform:

* A {product-title-short} hub cluster that is deployed on {ocp-short} version 4.6, or later.
* Internet access for your {product-title-short} hub cluster so it can create the Kubernetes cluster on Red Hat OpenStack Platform.
* A Red Hat OpenStack Platform credential. See link:../credentials/credential_openstack.adoc#creating-a-credential-for-openstack[Creating a credential for Red Hat OpenStack Platform] for more information.
* A {ocp-short} image pull secret. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/images/managing-images#using-image-pull-secrets[Using image pull secrets].
* The following information for the Red Hat OpenStack Platform instance where you are deploying:
** Flavor name for the control plane and worker instances.  For example, m1.xlarge.
** Network name for the external network to provide the floating IP addresses.
** Required floating IP addresses for API and ingress instances.
** DNS records for:
*** `api.<cluster_name>.<base_domain>`, which must point to the floating IP address for the API.
*** `*.apps.<cluster_name>.<base_domain>`, which must point to the floating IP address for ingress.

[#openstack-creating-your-cluster-with-the-console]
== Creating your cluster with the console

To create clusters from the {product-title-short} console, complete the following steps:

. From the navigation menu, navigate to *Infrastructure* > *Clusters*, and click *Create cluster* on the _Clusters_ page. Complete the steps in the console.
+
*Note:* This procedure is for creating a cluster.
If you have an existing cluster that you want to import, see xref:../clusters/import.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a target managed cluster to the hub cluster] for those steps.

. Select your infrastructure provider credential from the available credentials on the list. If you do not have one configured, or if you want to configure a new one, select *Add credential*. See link:../credentials/credential_openstack.adoc#creating-a-credential-for-openstack[Creating a credential for Red Hat OpenStack Platform] for more information about creating a credential.

. Add the name and details for your cluster. The name is used in the hostname of the cluster. The name must contain fewer than 15 characters.
+
*Note:* This value must match the name that you used to create the DNS records listed in the credential prerequisites section.
+
*Note:* The Red Hat Advanced Cluster Managament for Kubernetes controller creates a namespace for clusters you create. Destroying the cluster deletes the namespace. Only use resources of the cluster instance for this namespace.
+
*Tip:* You can view the `yaml` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.
+
.. Specify a _Cluster set_, if you want to add it to an existing cluster set. If you do not have `cluster-admin` privileges when you are creating the cluster, you must select a cluster set on which you have `clusterset-admin` permissions. If you do not have the correct permissions on the specified cluster set, the cluster creation fails. Contact your cluster administrator to provide you with `clusterset-admin` permissions to a cluster set if you do not have cluster set options to select.
+
Every managed cluster must be associated with a managed cluster set. If you do not assign the managed cluster to a `ManagedClusterSet`, it is automatically added to the `default` managed cluster set.

.. Specify the _Base DNS domain_ information that you configured for your Red Hat OpenStack Platform account. If there is already a base domain associated with the selected credential, that value is populated in that field. You can change the value by overwriting it. This value must match the name that you used to create the DNS records listed in the prerequisites section. This name is used in the hostname of the cluster.
+
See https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html/users_and_identity_management_guide/domains[Managing domains] in the Red Hat OpenStack Platform documentation for more information. 

.. Specify a _Release image_ that you want to use for the cluster. This identifies the version of the {ocp-short} image that is used to create the cluster. If the version that you want to use is available, you can select the image from the list of images. If the image that you want to use is not a standard image, you can enter the URL to the image that you want to use. See xref:../clusters/release_images.adoc#release-images[Release images] for more information about release images.
+
*Note:* Only release images for {ocp-short} versions 4.6.x and higher are supported.

.. Add any _Additional Labels_ that you want to associate with your cluster. These labels help to identify the cluster and limit search results.

. Enter details about the Node pools, including the control plane pool and the worker pools. The control plane nodes share the management of the cluster activity. The optional information includes the following fields:

.. Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool. Valid values are _amd64_, _ppc64le_, _s390x_, and _aarch64_.

.. Specify an _Instance type_ for your control plane node. You can change the type and size of your instance after it is created.

. Enter details about your worker pools. You can create one or more worker nodes in a worker pool to run the container workloads for the cluster. They can be in a single worker pool, or distributed across multiple worker pools. If zero worker nodes are specified, the control plane nodes also function as worker nodes. The optional information includes the following fields:
+
.. Add a name for your worker pool.

.. Specify an _Instance type_ for your worker pools. You can change the type and size of your instance after it is created.

.. Enter a _Node count_ for your worker pool. This setting is required when you define a worker pool.
+
You can define additional worker pools by clicking *Add worker pool*.

. Enter the networking details for your cluster. You must provide the values for one or more networks for an IPv4 network. For an IPv6 network, you must define more than one network.
+
You can add an additional network by clicking *Add network*. You must have more than one network if you are using IPv6 addresses.

. Add your proxy information, if you want to enable a proxy. Proxy information that is provided in the credential is automatically added. 
+
* HTTP proxy URL: The URL that should be used as a proxy for `HTTP` traffic. 

* HTTPS proxy URL: The secure proxy URL that should be used for `HTTPS` traffic. If no value is provided, the same value as the `HTTP Proxy URL` is used for both `HTTP` and `HTTPS`.

* No proxy domains: A comma-separated list of domains that should bypass the proxy. Begin a domain name with a period (.) to include all of the subdomains that are in that domain. Add an asterisk (*) to bypass the proxy for all destinations. 

* Additional trust bundle: The contents of the certificate file that is required to access the mirror registry.

. Add an optional _Ansible Automation Template_ to run either before or after your cluster installs or upgrades.
+
You can click *Add automation template* to create a template.  

. Review your information and optionally customize it.
.. Click the *YAML* slider to *On* to view the `install-config.yaml` file content in the panel. 
.. Edit the YAML file with your custom settings. 

. Select *Create* to create the cluster. 
+
*Note:* You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured under the management of {product-title-short}.

Your cluster is created. Continue with xref:../clusters/access_cluster.adoc#accessing-your-cluster[Accessing your cluster] for instructions for accessing your cluster. 
