[#creating-a-cluster-on-virtualization]
= Creating a cluster on Red Hat Virtualization

You can use the {product-title} console to create a {ocp} cluster on Red Hat Virtualization. 

When you create a cluster, the creation process uses the {ocp-short} installer with the Hive resource. If you have questions about cluster creation after completing this procedure, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/installing/installing-on-aws[Installing on AWS] in the {ocp-short} documentation for more information about the process.  

* <<virtualization_prerequisites,Prerequisites>>
* <<virtualization-creating-your-cluster-with-the-console,Creating your cluster with the console>>
* <<virtualization_accessing-your-cluster,Accessing your cluster>>

[#virtualization_prerequisites]
== Prerequisites

You must have the following prerequisites before creating a cluster on Red Hat Virtualization:

* A deployed {product-title} hub cluster

* Internet access for your {product-title} hub cluster so it can create the Kubernetes cluster on Red Hat Virtualization

* A Red Hat Virtualization credential. See link:../credentials/credential_virtualization.adoc#creating-a-credential-for-virtualization[Creating a credential for Red Hat Virtualization] for more information.

* A configured domain and virtual machine proxy for the oVirt Engine virtual machines. See https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.0/html-single/installation_guide/index[Installation Guide] in the Red Hat Virtualization documentation for instructions on how to configure a domain.

* Red Hat Virtualization login credentials, which include your Red Hat Customer Portal username and password. 

* A {ocp-short} image pull secret. You can download your pull secret from: https://console.redhat.com/openshift/install/pull-secret[Pull secret]. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/images/managing-images#using-image-pull-secrets[Using image pull secrets] for more information about pull secrets.

*Note:* If you change your cloud provider access key, you must manually update the provisioned cluster access key. For more information, see the known issue, link:../release_notes/known_issues.adoc#automatic-secret-updates-for-provisioned-clusters-is-not-supported[Automatic secret updates for provisioned clusters is not supported].

[#virtualization-creating-your-cluster-with-the-console]
== Creating your cluster with the console

To create clusters from the {product-title} console, complete the following steps:

. From the navigation menu, navigate to *Infrastructure* > *Clusters*.

. Ensure that the *Managed cluster* tab is selected. 

. On the _Clusters_ page, Click *Create cluster* to begin creating your cluster.
+
*Note:* This procedure is for creating a cluster.
If you have an existing cluster that you want to import, see xref:../clusters/import.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a target managed cluster to the hub cluster] for those steps.

. Select your *Red Hat Virtualization* for the infrastructure provider. The remaining steps are based on your selections.

. Select your infrastructure provider credential from the available credentials on the list. If you do not have one configured, or if you want to configure a new one, select *Add credential*. See link:../credentials/credential_virtualization.adoc#creating-a-credential-for-virtualization[Creating a credential for Red Hat Virtualization] for more information about creating a credential.

. Add the details for your cluster:

.. The name is used in the hostname of the cluster.
+
*Tip:* You can view the `yaml` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.

.. Specify a _Cluster set_, if you want to add it to an existing cluster set. If you do not have `cluster-admin` privileges when you are creating the cluster, you must select a cluster set on which you have `clusterset-admin` permissions to create the cluster. If you do not select a cluster set, the cluster creation fails. Contact your cluster administrator to provide you with `clusterset-admin` permissions to a cluster set if you do not have cluster set options to select.

.. If there is already a base domain associated with the selected credential, that value is populated in that field. You can change the value by overwriting it.

.. Specify a _Release image_ that you want to use for the cluster. This identifies the version of the {ocp-short} image that is used to create the cluster. If the version that you want to use is available, you can select the image from the list of images. If the image that you want to use is not a standard image, you can enter the URL to the image that you want to use. See xref:../clusters/release_images.adoc#release-images[Release images] for more information about release images.

.. Add any _Additional Labels_ that you want to associate with your cluster. These labels help to identify the cluster and limit search results.

. Enter the number of Cores, Sockets, Memory, and Disk size for the the control plane pool. The three control plane nodes share the management of the cluster activity. The optional information includes the following fields:

. Enter the pool name, number of cores, memory allocation, disk size allocation, and node count for your worker pools. Your worker nodes within the worker pool can be in a single worker pool, or distributed across multiple worker pools.  
+
You can define additional worker pools by clicking *Add worker pool*.

. Enter the networking details from your preconfigured oVirt environment. This information is required. Multiple networks are required for using IPv6.
+
* oVirt network name
* vNIC Profile ID
* API VIP
* Ingress VIP
* Network type - The default value is `OpenShiftSDN`. OVNKubernetes is the required setting for using IPv6. 
* Cluster network CIDR - This is a number and list of IP addresses that can be used for the pod IP addresses. This block must not overlap another network block. The default value is `10.128.0.0/14`.  
* Network host prefix - Sets the subnet prefix length for each node. The default value is `23`. 
* Service network CIDR -  Provides a block of IP addresses for services. This block must not overlap another network block. The default value is `172.30.0.0/16`.
* Machine CIDR - Provides a block of IP addresses that are used by the {ocp-short} hosts. This block must not overlap another network block. The default value is `10.0.0.0/16`.
+
You can add an additional network by clicking *Add network*. You must have more than one network if you are using IPv6 addresses. 

. If you want to enable a proxy, enter the proxy information: 
+
* HTTP Proxy URL: The URL that should be used as a proxy for `HTTP` traffic. 

* HTTPS Proxy URL: The secure proxy URL that should be used when using `HTTPS` traffic. If no value is provided, the same value as the `HTTP Proxy URL` is used for both `HTTP` and `HTTPS`. 

* No Proxy domains: A comma-separated list of domains that should bypass the proxy. Begin a domain name with a period (.) to include all of the subdomains that are in that domain. Add and asterisk (*) to bypass the proxy for all destinations. 

. Add an optional _Ansible Automation Template_ to run either before or after your cluster installs or upgrades.
+
You can click *Add automation template* to create a template.  
. Review your information and optionally customize it.
.. Click the *YAML* slider to *On* to view the `install-config.yaml` file content in the panel. 
.. Edit the YAML file with your custom settings. 

. Select *Create* to create the cluster. 
+
*Note:* You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured under the management of {product-title-short}. 

[#virtualization_accessing-your-cluster]
== Accessing your cluster

To access a cluster that is managed by {product-title}, complete the following steps:

. From the {product-title-short} navigation menu, navigate to *Infrastructure* > *Clusters*.
. Select the name of the cluster that you created or want to access. The cluster details are displayed.
. Select *Reveal credentials* to view the user name and password for the cluster. Note these values to use when you log in to the cluster.
. Select *Console URL* to link to the cluster.
. Log in to the cluster by using the user ID and password that you found in step 3.
