[#creating-a-cluster-on-bare-metal]
= Creating a cluster on bare metal

You can use the {product-title} console to create a {ocp} cluster in a bare metal environment.

* <<bare-prerequisites,Prerequisites>>
* <<bare_creating-your-cluster-with-the-console,Creating your cluster with the console>>
* <<bare_accessing-your-cluster,Accessing your cluster>>

[#bare-prerequisites]
== Prerequisites

You need the following prerequisites before creating a cluster in a bare metal environment:

* A deployed {product-title} hub cluster on {ocp-short} version 4.6 or later.
* Internet access for your {product-title} hub cluster (connected) or a connection to an internal or mirror registry that has a connection to the Internet (disconnected) to retrieve the required images for creating the cluster.
* Bare metal credential:
see link:../credentials/credential_bare.adoc#creating-a-credential-for-bare-metal[Creating a credential for bare metal] for more information.
* Login credentials for your bare metal environment, which include user name, password, and Baseboard Management Controller Address.
* A configured bare metal asset, if you are are enabling certificate verification. See xref:../clusters/bare_assets.adoc#creating-and-modifying-bare-metal-assets[Creating and modifying bare metal assets] for more information.
* A {ocp-short} image pull secret;
see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/images/managing-images#using-image-pull-secrets[Using image pull secrets].
+
*Notes:*
+
** The bare metal asset, managed bare metal cluster, and its related secret must be in the same namespace.
+
** If you change your cloud provider access key, you must manually update the provisioned cluster access key. For more information, see the known issue, link:../release_notes/known_issues.adoc#automatic-secret-updates-for-provisioned-clusters-is-not-supported[Automatic secret updates for provisioned clusters is not supported].

[#bare_creating-your-cluster-with-the-console]
== Creating your cluster with the console

To create clusters from the {product-title-short} console, complete the following steps:

. From the navigation menu, navigate to *Infrastructure* > *Clusters*.
. On the _Clusters_ page, Click *Create cluster*.
+
*Note:* This procedure is for creating a cluster.
If you have an existing cluster that you want to import, see xref:../clusters/import.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a target managed cluster to the hub cluster] for those steps.
. Select your Kubernetes distribution and *Bare Metal* for the infrastructure provider. The remaining steps are based on your selections.
. Select your credential from the available credentials on the list.
If you do not have one configured, or want to configure a new one, select *Add credential*. See link:../credentials/credential_bare.adoc#creating-a-credential-for-bare-metal[Creating a credential for bare metal] for more information about creating a credential.
. Add the details for your cluster:
.. Enter a name for your cluster. For a bare metal cluster, this name cannot be an arbitrary name. It is associated with the cluster URL. Make sure that the cluster name that you use is consistent with your DNS and network setup.
+
*Tip:* You can view the `yaml` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.
.. Specify a _Cluster set_, if you want to add it to an existing cluster set. If you do not have `cluster-admin` privileges when you are creating the cluster, you must select a cluster set on which you have `clusterset-admin` permissions to create the cluster. If you do not select a cluster set, the cluster creation fails. Contact your cluster administrator to provide you with `clusterset-admin` permissions to a cluster set if you do not have cluster set options to select.
.. Specify the _Base DNS domain_ information that you configured for your bare metal provider account. The base domain of your provider is used to create routes to your {ocp} cluster components. It is configured in your cluster provider's DNS as a Start of Authority (SOA) record. If there is already a base domain associated with the selected credential, that value is populated in that field. You can change the value by overwriting it, but this setting cannot be changed after the cluster is created.
See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/installing/installing-on-bare-metal[Installing on bare metal] in the {ocp-short} documentation for more information. This name is used in the hostname of the cluster.
.. Specify a _Release image_ that you want to use for the cluster. This identifies the version of the {ocp-short} image that is used to create the cluster. If the version that you want to use is available, you can select the image from the list of images. If the image that you want to use is not a standard image, you can enter the url to the image that you want to use. See xref:../clusters/release_images.adoc#release-images[Release images] for more information about release images.
.. Add the _Additional Labels_ that you want to associate with your cluster. These labels help to identify the cluster and limit search results.
. Select your hosts from the list of hosts that are associated with your credential. Select a minimum of three bare metal assets that are on the same bridge networks as the hypervisor.
+
The list of hosts is compiled from the existing bare metal assets. If you do not have any bare metal assets created, then you can create or import them before you continue with the creation process by selecting *Import assets*. For more information about creating bare metal assets, see xref:../clusters/bare_assets.adoc#creating-and-modifying-bare-metal-assets[Creating and modifying bare metal assets]. Alternatively, you can select *Disable certificate verification* to bypass the requirement.
. Configure the cluster networking options. The following tables shows the networking options and their descriptions:
+
|===
| Parameter | Description | Required or Optional

| Provisioning network CIDR | The CIDR for the network to use for provisioning. The example format is: 172.30.0.0/16. | Required
| Provisioning network interface | The name of the network interface on the control plane nodes that are connected to the provisioning network. | Required
| Provisioning network bridge | The name of the bridge on the hypervisor that is attached to the provisioning network. | Required
| External network bridge | The name of the bridge of the hypervisor that is attached to the external network. | Required
| API VIP | The Virtual IP to use for internal API communication. The DNS must be pre-configured with an A/AAAA or CNAME record so the `api.<cluster_name>.<Base DNS domain>` path resolves correctly. | Required
| Ingress VIP | The Virtual IP to use for ingress traffic. The DNS must be pre-configured with an A/AAAA or CNAME record so the `*.apps.<cluster_name>.<Base DNS domain>` path resolves correctly. | Optional
| Network type | The pod network provider plug-in to deploy. Only the OpenShiftSDN plug-in is supported on {ocp-short} 4.3. The OVNKubernetes plug-in is available as a technical preview on {ocp-short} versions 4.3, 4.4, and 4.5. It is generally available on {ocp-short} version 4.6, and later. OVNKubernetes must be used with IPv6. The default value is `OpenShiftSDN`. | Required
| Cluster network CIDR | A block of IP addresses from which pod IP addresses are allocated. The OpenShiftSDN network plug-in supports multiple cluster networks. The address blocks for multiple cluster networks must not overlap. Select address pools large enough to fit your anticipated workload. The default values is 10.128.0.0/14. | Required
| Network host prefix | The subnet prefix length to assign to each individual node. For example, if hostPrefix is set to 23, then each node is assigned a /23 subnet out of the given CIDR, allowing for 510 (2^(32-23)-2) pod IP addresses. The default is 23. | Required
| Service network CIDR | A block of IP addresses for services. OpenShiftSDN allows only one serviceNetwork block. The address must not overlap any other network block. The default value is 172.30.0.0/16. | Required
| Machine CIDR | A block of IP addresses used by the {ocp-short} hosts. The address block must not overlap any other network block. The default value is 10.0.0.0/16. | Required
|===
+
You can add an additional network by clicking *Add network*. You must have more than one network if you are using IPv6 addresses. 
. Add an optional _Ansible Automation Template_ to run either before or after your cluster installs or upgrades.
+
You can click *Add automation template* to create a template.  
. Review your information and select *Create* to create the cluster. 
+
*Note:* You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured under the management of {product-title-short}.

[#bare_accessing-your-cluster]
== Accessing your cluster

To access a cluster that is managed by {product-title}, complete the following steps:

. From the {product-title} navigation menu, navigate to *Infrastructure* > *Clusters*.
. Select the name of the cluster that you created or want to access.
The cluster details are displayed.
. Select *Reveal credentials* to view the user name and password for the cluster.
Note these values to use when you log in to the cluster.
. Select *Console URL* to link to the cluster.
. Log in to the cluster by using the user ID and password that you found in step 3.
