[#creating-a-cluster-on-premises]
= Creating a cluster in an on-premises environment

You can use the {product-title} console to create an on-premises {ocp} cluster.

* <<on-prem-prerequisites,Prerequisites>>
* <<on-prem-creating-your-cluster-with-the-console,Creating your cluster with the console>>
* <<on-prem-accessing-your-cluster,Accessing your cluster>>

[#on-prem-prerequisites]
== Prerequisites

You need the following prerequisites before creating a cluster in an on-premises environment:

* A deployed {product-title} hub cluster on {ocp-short} version 4.9, or later.
* A configured infrastructure environment with configured hosts.
* Internet access for your {product-title} hub cluster (connected) or a connection to an internal or mirror registry that has a connection to the Internet (disconnected) to retrieve the required images for creating the cluster.
* A configured on-premises credential. See link:../credentials/credential_on_prem.adoc#creating-a-credential-for-an-on-premises-environment[Creating a credential for an on-premises environment] for more information.
* A {ocp-short} image pull secret; see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/images/managing-images#using-image-pull-secrets[Using image pull secrets].

[#on-prem-creating-your-cluster-with-the-console]
== Creating your cluster with the console

To create clusters from the {product-title-short} console, complete the following steps:

. From the navigation menu, navigate to *Infrastructure* > *Clusters*.
. On the _Clusters_ page, Click *Create cluster*.
. Select *On-premises* for the infrastructure provider. The remaining steps are based on your selection.
. Select your credential from the available credentials on the list.
If you do not have one configured, or want to configure a new one, select *Add credential*. See link:../credentials/credential_on_prem.adoc#creating-a-credential-for-an-on-premises-environment[Creating a credential for an on-premises environment] for more information about creating a credential.
. Add the details for your cluster:
.. Enter a name for your cluster.
+
*Tip:* You can view the `yaml` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.
.. Specify a _Cluster set_, if you want to add it to an existing cluster set. If you do not have `cluster-admin` privileges when you are creating the cluster, you must select a cluster set on which you have `clusterset-admin` permissions to create the cluster. If you do not select a cluster set, the cluster creation fails. Contact your cluster administrator to provide you with `clusterset-admin` permissions to a cluster set if you do not have cluster set options to select.
.. Specify the _Base DNS domain_ information that you configured for your provider account. The base domain of your provider is used to create routes to your {ocp} cluster components. It is configured in your cluster provider's DNS as a Start of Authority (SOA) record. If there is already a base domain associated with the selected credential, that value is populated in that field. You can change the value by overwriting it, but this setting cannot be changed after the cluster is created.
+
*Tip:* After you review and save the cluster at this point, your cluster is saved as an incomplete cluster. You can close the creation process and finish the creation process later by the cluster name on the _Clusters_ page. 
.. If you want your cluster to be a Single Node OpenShift (SNO) cluster, select the SNO option. A SNO cluster only creates one node, rather than the three nodes that are created by a standard cluster.  
.. Specify a _Release image_ that you want to use for the cluster. This identifies the version of the {ocp-short} image that is used to create the cluster. If the version that you want to use is available, you can select the image from the list of images. If the image that you want to use is not a standard image, you can enter the URL to the image that you want to use. See xref:../clusters/release_images.adoc#release-images[Release images] for more information about release images.
.. Add the _Additional Labels_ that you want to associate with your cluster. These labels help to identify the cluster and limit search results.
. Select whether you want to select the hosts yourself, or if you want them to be selected automatically. The number of hosts is based on the number of nodes that you selected. For example, a SNO cluster only requires one host, while a standard three-node cluster requires 3 hosts. 
+
The locations of the available hosts that meet the requirements for this cluster are displayed in the list of *Host locations*. For distribution of the hosts and a more high-availability configuration, select multiple locations. 

. After your hosts finish binding and display a `Bound` status, select a subnet for your cluster from the list of options for the bound host.

. Add the following IP addresses: 
+
* _API VIP_: The IP address to use for internal API communication.
+
*Note:* This value must match the name that you used to create the DNS records listed in the prerequisites section. If not provided, the DNS must be pre-configured so that `api.` resolves correctly.

* _Ingress VIP_: The IP address to use for ingress traffic.
+
*Note:* This value must match the name that you used to create the DNS records listed in the prerequisites section. If not provided, the DNS must be pre-configured so that `test.apps.` resolves correctly.

Your cluster is installing. You can view the status of the installation on the *Clusters* navigation page. 

[#on-prem-accessing-your-cluster]
== Accessing your cluster

To access a cluster that is managed by {product-title}, complete the following steps:

. From the {product-title} navigation menu, navigate to *Infrastructure* > *Clusters*.
. Select the name of the cluster that you created or want to access.
The cluster details are displayed.
. Select *Reveal credentials* to view the user name and password for the cluster.
Note these values to use when you log in to the cluster.
. Select *Console URL* to link to the cluster.
. Log in to the cluster by using the user ID and password that you found in step three.
