[#creating-a-cluster-on-openstack]
= Creating a cluster on Red Hat OpenStack Platform

You can use the {product-title} console to deploy a {ocp} cluster on Red Hat OpenStack Platform.

* <<openstack-prerequisites,Prerequisites>>
* <<openstack-creating-your-cluster-with-the-console,Creating your cluster with the console>>
* <<accessing-your-cluster],Accessing your cluster>>

[#openstack-prerequisites]
== Prerequisites

You must have the following prerequisites before creating a cluster on Red Hat OpenStack Platform:

* A {product-title-short} hub cluster that is deployed on {ocp-short} version 4.6, or later.
* Internet access for your {product-title-short} hub cluster so it can create the Kubernetes cluster on Red Hat OpenStack Platform.
* A Red Hat OpenStack Platform credential. See link:../credentials/credential_openstack.adoc#creating-a-credential-for-openstack[Creating a credential for Red Hat OpenStack Platform] for more information.
* A {ocp-short} image pull secret. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/images/managing-images#using-image-pull-secrets[Using image pull secrets].
* The following information for the Red Hat OpenStack Platform instance where you are deploying:
** Flavor name for the master and worker instances.  For example, m1.xlarge.
** Network name for the external network to provide the floating IP addresses.
** Required floating IP addresses for API and ingress instances.
** DNS records for:
*** `api.<cluster_name>.<base_domain>`, which must point to the floating IP address for the API.
*** `*.apps.<cluster_name>.<base_domain>`, which must point to the floating IP address for ingress.

[#openstack-creating-your-cluster-with-the-console]
== Creating your cluster with the console

To create clusters from the {product-title-short} console, complete the following steps:

. From the navigation menu, navigate to *Infrastructure* > *Clusters*.

. On the _Clusters_ page, click *Create cluster*.
+
*Note:* This procedure is for creating a cluster.
If you have an existing cluster that you want to import, see xref:../clusters/import.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a target managed cluster to the hub cluster] for those steps.
. Select your Kubernetes distribution and *Red Hat OpenStack* for the infrastructure provider. The remaining steps are based on your selections.
. Select your infrastructure provider credential from the available credentials on the list. If you do not have one configured, or if you want to configure a new one, select *Add credential*. See link:../credentials/credential_openstack.adoc#creating-a-credential-for-openstack[Creating a credential for Red Hat OpenStack Platform] for more information about creating a credential.
. Add the details for your cluster:
.. Enter a name for your cluster. This name is used in the hostname of the cluster. The name must contain fewer than 15 characters.
+
*Note:* This value must match the name that you used to create the DNS records listed in the credential prerequisites section.
+
*Tip:* You can view the `yaml` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.
.. Specify a _Cluster set_, if you want to add it to an existing cluster set. If you do not have `cluster-admin` privileges when you are creating the cluster, you must select a cluster set on which you have `clusterset-admin` permissions to create the cluster. If you do not select a cluster set, the cluster creation fails. Contact your cluster administrator to provide you with `clusterset-admin` permissions to a cluster set if you do not have cluster set options to select.
.. Specify the _Base DNS domain_ information that you configured for your Red Hat OpenStack Platform account. If there is already a base domain associated with the selected credential, that value is populated in that field. You can change the value by overwriting it. This value must match the name that you used to create the DNS records listed in the prerequisites section.
+
See https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html/users_and_identity_management_guide/domains[Managing domains] in the Red Hat OpenStack Platform documentation for more information. This name is used in the hostname of the cluster.
.. Specify a _Release image_ that you want to use for the cluster. This identifies the version of the {ocp-short} image that is used to create the cluster. If the version that you want to use is available, you can select the image from the list of images. If the image that you want to use is not a standard image, you can enter the url to the image that you want to use. See xref:../clusters/release_images.adoc#release-images[Release images] for more information about release images.
+
*Note:* Only release images for {ocp-short} versions 4.6.x and higher are supported.
.. Add the _Additional Labels_ that you want to associate with your cluster. These labels help to identify the cluster and limit search results.
. Enter details about the master node. There are three master nodes that are created for your cluster in the master pool. The master nodes share the management of the cluster activity. The optional information includes the following fields:
.. Specify an _Instance type_ for your master node. You can change the type and size of your instance after it is created. The default value is _m1.xlarge_.
. Enter details about your worker pools. You can create one or more worker nodes in a worker pool to run the container workloads for the cluster. They can be in a single worker pool, or distributed across multiple worker pools. If zero worker nodes are specified, the master nodes also function as worker nodes. The optional information includes the following fields:
.. Add a name for your worker pool.
.. Specify an _Instance type_ for your worker pools. You can change the type and size of your instance after it is created. The default value is _m1.xlarge_.
.. Enter a _Node count_ for your worker pool. This setting is required when you define a worker pool.
+
You can define additional worker pools by clicking *Add worker pool*.
. Enter the networking details for your cluster. You must provide the values for one or more networks for an IPv4 network. For an IPv6 network, you must define more than one network.
.. Add the _External network name_, which is the name of the external Red Hat OpenStack Platform network.
.. Add the _API floating IP address_. The existing floating IP address is for the the external network for the {ocp-short} API. This value must match the name that you used to create the DNS records listed in the prerequisites section. 
.. Add the _Ingress floating IP_ address. The existing floating IP address is on the external network for the ingress port. This value must match the name that you used to create the DNS records listed in the prerequisites section. The existing floating IP address is on the external network for the ingress port.
.. Add the _External DNS IP addresses_ supports name resolution on the private network. 
.. Select your _Network type_, which specifies the pod network provider plug-in to deploy. The possible values are `OVNKubernetes` or `OpenShiftSDN`. The default value is `OpenShiftSDN`. OVNKubernetes is the required setting for using IPv6. 
.. Select a _Cluster network CIDR_. The group of IP addresses that are reserved for use by the cluster. Ensure that you specify enough for your cluster, and that they do not include the IP addresses of other clusters in the range. The default value is `10.128.0.0/14`.  
.. Specify the _Network host prefix_, which sets the prefix length to assign to each individual node. The default value is `23`. 
.. Specify the _Service network CIDR_, which provides a block of IP addresses for services. This block must not overlap another network block. The default value is `172.30.0.0/16`.
.. Specify the _Machine CIDR_, which provides a block of IP addresses that are used by the {ocp-short} hosts. This block must not overlap another network block. The default value is `10.0.0.0/16`.
+
You can add an additional network by clicking *Add network*. You must have more than one network if you are using IPv6 addresses. 
. Add an optional _Ansible Automation Template_ to run either before or after your cluster installs or upgrades.
+
You can click *Add automation template* to create a template.  
. Review your information and select *Create* to create the cluster. 
+
*Note:* You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured under the management of {product-title-short}.

[#openstack-accessing-your-cluster]
== Accessing your cluster

To access a cluster that is managed by {product-title-short}, complete the following steps:

. From the {product-title-short} navigation menu, navigate to *Infrastructure* > *Clusters*.
. Select the name of the cluster that you created or want to access.
The cluster details are displayed.
. Select *Reveal credentials* to view the user name and password for the cluster.
Use these values when you log in to the cluster.
. Select *Console URL* to link to the cluster.
. Log in to the cluster by using the user ID and password that you found in step 3.
