[#creating-a-cluster-on-google-cloud-platform]
= Creating a cluster on Google Cloud Platform

Follow the procedure to create a {ocp} cluster on Google Cloud Platform (GCP).
For more information about Google Cloud Platform, see https://cloud.google.com/docs/overview[Google Cloud Platform].

* <<google_prerequisites,Prerequisites>>
* <<google_creating-your-cluster-with-the-console,Creating your cluster with the console>>
* <<google_accessing-your-cluster,Accessing your cluster>>

[#google_prerequisites]
== Prerequisites

You must have the following prerequisites before creating a cluster on GCP:

* A deployed {product-title} hub cluster
* Internet access for your {product-title} hub cluster so it can create the Kubernetes cluster on GCP
* GCP credential.
See link:../credentials/credential_google.adoc#creating-a-credential-for-google-cloud-platform[Creating a credential for Google Cloud Platform] for more information.
* A configured domain in GCP.
See https://cloud.google.com/endpoints/docs/openapi/dev-portal-setup-custom-domain[Setting up a custom domain] for instructions on how to configure a domain.
* GCP login credentials, which include user name and password.
* A {ocp-short} image pull secret.
See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/images/managing-images#using-image-pull-secrets[Using image pull secrets].

*Note:* If you change your cloud provider access key, you must manually update the provisioned cluster access key. For more information, see the known issue, link:../release_notes/known_issues.adoc#automatic-secret-updates-for-provisioned-clusters-is-not-supported[Automatic secret updates for provisioned clusters is not supported].

[#google_creating-your-cluster-with-the-console]
== Creating your cluster with the console

To create clusters from the {product-title} console, complete the following steps:

. From the navigation menu, navigate to *Infrastructure* > *Clusters*.
. On the _Clusters_ page, select *Create cluster*.
+
*Note:* This procedure is for creating a cluster.
If you have an existing cluster that you want to import, see xref:../clusters/import.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a target managed cluster to the hub cluster] for those steps.
. Select your Kubernetes distribution and *Google Cloud* for the infrastructure provider. The remaining steps are based on your selections.
. Select your credential from the available credentials on the list. If you do not have one configured, or want to configure a new one, select *Add credential*. See link:../credentials/credential_google.adoc#creating-a-credential-for-google-cloud-platform[Creating a credential for Google Cloud Platform] for more information about creating a credential.
. Add the details for your cluster:
.. Enter a name for your cluster.
This name is used in the hostname of the cluster. There are some restrictions that apply to naming your GCP cluster. These restrictions include not beginning the name with `goog` or containing a group of letters and numbers that resemble `google` anywhere in the name. See https://cloud.google.com/storage/docs/naming-buckets#requirements[Bucket naming guidelines] for the complete list of restrictions.
+
*Tip:* You can view the `yaml` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.
.. Specify a _Cluster set_, if you want to add it to an existing cluster set. If you do not have `cluster-admin` privileges when you are creating the cluster, you must select a cluster set on which you have `clusterset-admin` permissions to create the cluster. If you do not select a cluster set, the cluster creation fails. Contact your cluster administrator to provide you with `clusterset-admin` permissions to a cluster set if you do not have cluster set options to select.
.. Specify the _Base DNS domain_ information that you configured for your GCP account. If there is already a base domain associated with the selected credential, that value is populated in that field. You can change the value by overwriting it. This name is used in the hostname of the cluster.
See https://cloud.google.com/endpoints/docs/openapi/dev-portal-setup-custom-domain[Setting up a custom domain] for more information. 
.. Specify a _Release image_ that you want to use for the cluster. This identifies the version of the {ocp-short} image that is used to create the cluster. If the version that you want to use is available, you can select the image from the list of images. If the image that you want to use is not a standard image, you can enter the url to the image that you want to use. See xref:../clusters/release_images.adoc#release-images[Release images] for more information about release images.
.. Add the _Additional Labels_ that you want to associate with your cluster. These labels help to identify the cluster and limit search results.
. Enter details about the control plane pool. There are three control plane nodes that are created for your cluster in the control plane pool. The control plane nodes share the management of the cluster activity. The optional information includes the following fields:
.. Specify a _Region_ where you want to run your control plane pools. A closer region might provide faster performance, but a more distant region might be more distributed.
.. Specify an _Instance type_ for your control plane node. You can change the type and size of your instance after it is created. The default values are _n1-standard-1  - n1-standard-1 1 vCPU - General Purpose_.
. Enter details about your worker pools. You can create zero or more worker nodes in a worker pool to run the container workloads for the cluster. They can be in a single worker pool, or distributed across multiple worker pools. If zero worker nodes are specified, the control plane nodes also function as worker nodes. The optional information includes the following fields:
.. Add a name for your worker pool.
.. Specify an _Instance type_ for your worker pools. You can change the type and size of your instance after it is created. The default values are _n1-standard-4 - 4 vCPU 15 GiB RAM - General Purpose_.
.. Enter a _Node count_ for your worker pool. This setting is required when you define a worker pool.
+
You can define additional worker pools by clicking _Add worker pool_.
. Enter the networking details for your cluster. This information is required. Multiple networks are required for using IPv6.
.. Select your _Network type_. The default value is `OpenShiftSDN`. OVNKubernetes is the required setting for using IPv6. 
.. Select a _Cluster network CIDR_. This is a number and list of IP addresses that can be used for the pod IP addresses. This block must not overlap another network block. The default value is `10.128.0.0/14`.  
.. Specify the _Network host prefix_, which sets the subnet prefix length for each node. The default value is `23`. 
.. Specify the _Service network CIDR_, which provides a block of IP addresses for services. This block must not overlap another network block. The default value is `172.30.0.0/16`.
.. Specify the _Machine CIDR_, which provides a block of IP addresses that are used by the {ocp-short} hosts. This block must not overlap another network block. The default value is `10.0.0.0/16`.
+
You can add an additional network by clicking *Add network*. You must have more than one network if you are using IPv6 addresses. 
. Add an optional _Ansible Automation Template_ to run either before or after your cluster installs or upgrades.
+
You can click *Add automation template* to create a template.  
. Review your information and optionally customize it.
.. Click the *YAML* slider to *On* to view the `install-config.yaml` file content in the panel. 
.. Edit the YAML file with your custom settings. 

. Select *Create* to create the cluster. 
+
*Note:* You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured under the management of {product-title-short}. 

[#google_accessing-your-cluster]
== Accessing your cluster

To access a cluster that is managed by {product-title}, complete the following steps:

. From the {product-title} navigation menu, navigate to *Infrastructure* > *Clusters*.
. Select the name of the cluster that you created or want to access. The cluster details are displayed.
. Select *Reveal credentials* to view the user name and password for the cluster. Note these values to use when you log in to the cluster.
. Select *Console URL* to link to the cluster.
. Log in to the cluster by using the user ID and password that you found in step 3.
