[#discovery-credential]
= Add a credential to enable Discovery

Add a Red Hat OpenShift Cluster Manager credential so that you can discover clusters.

**Required access**: Administrator

[#prerequisites-discovery]
== Prerequisites

You need access to a https://cloud.redhat.com/[cloud.redhat.com] account.

[#add-credential]
== Add your credential

If you have no credentials, see the following process. *Best practice:* Create only one credential in each namespace.

. From the product navigation, click *Credentials*.
. Click the *Add credentails* button to get to the *Add credentials* page.
. Choose the Red Hat OpenShift Cluster Manager credential type, then click *Next*.
. Enter the following basic information for your credential: 
  - Enter any unique name for your credential.
  - Enter a namespace. You must have access to the namespace that you enter. All users assigned to this namespace can access resources. All discovered resources related to this credential are created in this namespace. Every credential that you create should belong to a unique, existing namespace.
. Click *Next*.
. Obtain, copy, and enter your Red Hat OpenShift Cluster Manager API token.
. Click *Next* to review your selections or return to a step. 
. Click *Add* to create your credential and return to the _Credentials_ page. *Note:* If your credential does not appear, you might need to refresh the page.
. From the _Credentials page_, you can add more credentials.
