[#discovery. import]
= Import discovered clusters

After you discover clusters, you can import clusters that appear in _Discovered clusters_.

. Navigate to the existing _Clusters_ page, and click on the _Discovered clusters_ tab.
. From the _Discovered_ row in the table, find the options and click *Import clusters*. 
. Fill out the form for the cluster that you want to import.
. Click *Save import and generate code* to begin importing. If you click *Cancel*, you return to the _Discovered clusters_ table. After loading, the import command is generated.
. From a terminal, run the generated command.
. Click *Launch to console*, which is added to an import form so you can launch to the imported, discovered cluster. 
+
Note: This *Launch to console* button only appears when importing a discovered cluster. Does not appear when manually importing a managed cluster.
. Click *View cluster* to return to the _Cluster details_ page.
. Click *Import another* in the following cases:
  . If importing a discovered cluster and you return to the table.
  . If manually importing a managed cluster, which resets the form.
  