[#discovery-credential]
= Add a credential to enable Discovery

Add a Red Hat OpenShift Cluster Manager credential so that you can discover clusters.

**Required access**: Administrator

[#prerequisites-discovery]
== Prerequisites

You need access to a https://cloud.redhat.com/[cloud.redhat.com] account.

[#add-credential]
== Add your credential

*Best practice:* Create only one credential in each namespace.

You need to add your credential to discover clusters. If you have no credentials, see the following process.

. From the product navigation, click *Credentials*.
. Click the *Add credentials* button to get to the _Add credentials_ page.
. Choose the Red Hat OpenShift Cluster Manager credential _type_, then click *Next*.
. Enter the following basic information for your credential: 
  - Enter any unique name for your credential.
  - Enter a namespace that you can access. All users assigned to this namespace can also access the resources. All discovered resources that are related to this credential are created in this same namespace. Every credential that you create must be assigned to a unique, existing namespace.
. Click *Next*.
. Obtain, copy, and enter your Red Hat OpenShift Cluster Manager API token.
. Click *Next* to review your selections or return to a step. 
. Click *Add* to create your credential and return to the _Credentials_ page. *Note:* If your credential does not appear, you might need to refresh the page.
. From the _Credentials page_, you can add more credentials.

If your credential is removed, or your Red Hat OpenShift Cluster Manager API token expires or is revoked, then the associated discovered clusters will be removed.
