[#hosted-control-planes-intro]
= Using hosted control plane clusters (Technology Preview)

{product-title} version 2.5 with the multicluster engine operator 2.0 can deploy {ocp} clusters by using two different control plane configurations. The standalone configuration uses multiple dedicated virtual machines or physical machines to host the {ocp-short} control plane. You can provision hosted control planes to provision the {ocp-short} control plane as pods on a hosting service cluster without the need for dedicated physical machines for each control-plane.

*Note:* This feature also works with the multicluster engine operator 2.0 without {product-title}.

For {product-title-short}, Amazon Web Services is supported as a Technology Preview. You can host the control planes for your {ocp} version 4.10.7 and later. 

The control plane is run as pods that are contained in a single namespace and is associated with the hosted control plane cluster. When {ocp-short} provisions this type of hosted cluster, it provisions a worker node independent of the control plane. 

See the following benefits of hosted control plane clusters:

* Saves cost by removing the need to host dedicated control plane nodes

* Introduces separation between the control plane and the workloads, which improves isolation and reduces configuration errors that can require changes

* Significantly decreases the cluster provisioning time by removing the requirement for control-plane node bootstrapping

* Supports turn-key deployments or fully customized {ocp-short} provisioning

See more in the following product documentation:

* xref:../clusters/hosted_control_planes_configure.adoc#hosted-control-planes-configure[Configuring hosted control planes]
* xref:../clusters/disable_hosted_control_planes.adoc#disable-hosted-control-planes[Disabling hosted control plane resources]
