[#importing-a-target-managed-cluster-to-the-hub-cluster]
= Importing a target managed cluster to the hub cluster

You can import clusters from different Kubernetes cloud providers.
After you import, the targeted cluster becomes a managed cluster for the {product-title} hub cluster.
Unless otherwise specified, complete the import tasks anywhere where you can access the hub cluster and the targeted managed cluster.

A hub cluster cannot manage _any_ other hub cluster, but can manage itself. The hub cluster is configured to automatically be imported and self-managed. You do not need to manually import the hub cluster. 

However, if you remove a hub cluster and try to import it again, you need to add the `local-cluster:true` label.

Choose from the following instructions to set up your managed cluster, either from the console or from the CLI:

*Required user type or access level*: Cluster administrator

* xref:../clusters/import_gui.adoc#importing-an-existing-cluster-with-the-console[Importing an existing cluster with the console]
* xref:../clusters/import_cli.adoc#importing-a-managed-cluster-with-the-cli[Importing a managed cluster with the CLI]
* xref:../clusters/modify_endpoint.adoc#modifying-the-klusterlet-addons-settings-of-your-cluster[Modifying the klusterlet addons settings of your cluster]
