[#creating-a-managedclustersetbinding]
== Creating a ManagedClusterSetBinding resource

Create a `ManagedClusterSetBinding` resource to bind a `ManagedClusterSet` resource to a namespace. Applications and policies that are created in the same namespace can only access managed clusters that are included in the bound managed cluster set resource. 

Access permissions to the namespace automatically apply to a managed cluster set that is bound to that namespace. If you have access permissions to access the namespace to which the managed cluster set is bound, you automatically have permissions to access any managed cluster set that is bound to that namespace. However, if you only have permissions to access the managed cluster set, you do not automatically have permissions to access other managed cluster sets on the namespace. If you do not see a managed cluster set, you might not have the required permissions to view it.

You can create a managed cluster set binding by using the console or the command line.  

[#creating-a-managedclustersetbinding-console]
=== Creating a ManagedClusterSetBinding by using the console
//heavy with easy UI procedure--please remove.

Complete the following steps to remove a cluster from a managed cluster set by using the {product-title-short} console:

. Access the cluster page by selecting *Infrastructure* > *Clusters* in the main navigation and select the _Cluster sets_ tab.

. Select the name of the cluster set that you want to create a binding for to view the cluster set details.

. Select *Actions* > *Edit namespace bindings*.

. On the _Edit namespace bindings_ page, select the namespace to which you want to bind the cluster set from the drop-down menu. The existing namespaces that have bindings to the cluster set are already selected. 

[#creating-a-managedclustersetbinding-cli]
=== Creating a ManagedClusterSetBinding by using the command line

To create a managed cluster set binding by using the command line, complete the following steps:

. Create the `ManagedClusterSetBinding` resource in your `yaml` file. When you create a managed cluster set binding, the name of the managed cluster set binding must match the name of the managed cluster set to bind. Your `ManagedClusterSetBinding` resource might resemble the following information:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  namespace: project1
  name: clusterset1
spec:
  clusterSet: clusterset1
----

. Ensure that you have the bind permission on the target managed cluster set. View the following example of a `ClusterRole` resource, which contains rules that allow the user to bind to `clusterset1`:

+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole1
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclustersets/bind"]
    resourceNames: ["clusterset1"]
    verbs: ["create"]
----
