[#assign-role-clustersets]
= Assigning users or groups Role-Based Access Control permissions to your ManagedClusterSet

You can assign users or groups to your cluster set that are provided by the configured identity providers on the hub cluster.

*Required access:* Cluster administrator

The `ManagedClusterSet` API offers two levels of RBAC permissions:

* Cluster set `admin`
** Full access permissions to all of the cluster and cluster pool resources that are assigned to the managed cluster set.
** Permission to create clusters, import clusters, and create cluster pools. The permissions must be assigned to the managed cluster set when the managed cluster set is created.
* Cluster set `view`
** Read only permissions to all of the cluster and cluster pool resources that are assigned to the managed cluster set.
** No permission to create clusters, import clusters, or create cluster pools.

Complete the following steps to assign users or groups to your managed cluster set from the {product-title-short} console:

. From the main navigation menu of the console, select *Infrastructure* > *Clusters*.

. Select the _Cluster sets_ tab.

. Select your target cluster set. 

. Select the _Access management_ tab. 

. Select *Add user or group*.

. Search for, and select the user or group that you want to provide access.

. Select the *Cluster set admin* or *Cluster set view* role to give to the selected user or user group. See link:../access_control/rbac.adoc#overview-of-roles[Overview of roles] for more information about the role permissions.

. Select *Add* to submit the changes.

Your user or group is displayed in the table. It might take a few seconds for the permission assignments for all of the managed cluster set resources to be propagated to your user or group.

// 
//doc the association between clusterpool with clustersets, can provide access to create clusters in the pool and can help provide access to many users. Are there special roles for a clusterpool? 
//anyone bound to clusterset roles are able gain access to the clusterpools
// viewer can't create objects in a clusterpool 

For more information about role-based actions, see link:../access_control/rbac.adoc#role-based-access-control[Role-based access control].

See link:../clusters/placement_managed.adoc[Using ManagedClusterSets with Placement] for placement information.
