[#creating-a-cluster-proxy]
= Creating a cluster in a proxy environment

You can create a {ocp} cluster when your hub cluster is connected through a proxy server.

One of the following situations must be true for the cluster creation to succeed:

* {product-title} has a private network connection with the managed cluster that you are creating, but the {product-title-short} and managed cluster access the Internet using a proxy.

* The managed cluster is on a infrastructure provider, but the firewall ports enable communication from the managed cluster to the hub cluster.

To create a cluster that is configured with a proxy, complete the following steps:

. Configure the cluster-wide-proxy setting on the hub cluster by adding the following information to your `install-config.yaml` file:
+
[source,yaml]
----
apiVersion: v1
kind: Proxy
baseDomain: <domain>
proxy:
  httpProxy: http://<username>:<password>@<proxy.example.com>:<port>
  httpsProxy: https://<username>:<password>@<proxy.example.com>:<port>
  noProxy: <wildcard-of-domain>,<provisioning-network/CIDR>,<BMC-address-range/CIDR>
----
+
Replace `username` with the username for your proxy server.
+
Replace `password` with the password to access your proxy server.
+
Replace `proxy.example.com` with the path of your proxy server.
+
Replace `port` with the communication port with the proxy server.
+
Replace `wildcard-of-domain` with an entry for domains that should bypass the proxy.
+ 
Replace `provisioning-network/CIDR` with the IP address of the provisioning network and the number of assigned IP addresses, in CIDR notation.
+
Replace `BMC-address-range/CIDR` with the BMC address and the number of addresses, in CIDR notation.
+
After you add the previous values, the settings are applied to your clusters. 

. Provision the cluster by completing the procedure for creating a cluster. See xref:../multicluster_engine/create.adoc#creating-a-cluster[Creating a cluster] to select your provider.

[#enable-cluster-wide-proxy-addon]
== Enabling cluster-wide proxy on existing cluster add-ons

You can configure the `KlusterletAddonConfig` in the cluster namespace to add the proxy environment variables to all of the klusterlet add-on pods of the {ocp} clusters that are managed by the hub cluster.

Complete the following steps to configure the `KlusterletAddonConfig` to add the 3 environment variables to the pods of the klusterlet add-ons:

. Open the `KlusterletAddonConfig` file that is in the namespace of the cluster that needs the proxy added.

. Edit the `.spec.proxyConfig` section of the file so it resembles the following example:
+
[source,yaml]
----
spec
  proxyConfig:
    httpProxy: "<proxy_not_secure>"
    httpsProxy: "<proxy_secure>" 
    noProxy: "<no_proxy>" 
----
+
Replace `proxy_not_secure` with the address of the proxy server for `http` requests. For example, `http://192.168.123.145:3128`.
+
Replace `proxy_secure` with the address of the proxy server for `https` requests. For example, `https://192.168.123.145:3128`. 
+
Replace `no_proxy` with a comma delimited list of IP addresses, hostnames, and domain names where traffic will not be routed through the proxy. For example, `.cluster.local,.svc,10.128.0.0/14,example.com`.
+
The `spec.proxyConfig` is an optional section. If the {ocp-short} cluster is created with cluster wide proxy configured on the {product-title-short} hub cluster, the cluster wide proxy configuration values are added to the pods of the klusterlet add-ons as environment variables when the following conditions are met:
+
* The `.spec.policyController.proxyPolicy` in the `addon` section is enabled and set to `OCPGlobalProxy`

* The `.spec.applicationManager.proxyPolocy` is enabled and set to `CustomProxy`.
+
**Note:** The default value of `proxyPolicy` in the `addon` section is `Disabled`.
+
See the following example:
+
[source,yaml]
----
apiVersion: agent.open-cluster-management.io/v1
    kind: KlusterletAddonConfig
    metadata:
      name: clusterName
      namespace: clusterName
    spec:
      proxyConfig:
        httpProxy: http://pxuser:12345@10.0.81.15:3128
        httpsProxy: http://pxuser:12345@10.0.81.15:3128
        noProxy: .cluster.local,.svc,10.128.0.0/14, example.com
      applicationManager:
        enabled: true
        proxyPolicy: CustomProxy
      policyController:
        enabled: true
        proxyPolicy: OCPGlobalProxy
      searchCollector:
        enabled: true
        proxyPolicy: Disabled
      certPolicyController:
        enabled: true
        proxyPolicy: Disabled
      iamPolicyController:
        enabled: true
        proxyPolicy: Disabled
----

Proxy is configured on your cluster add-ons. 
