[#resize-acm-imported]
= Scaling imported managed clusters 

Imported managed clusters do not have the same resources as clusters that were created by {product-title-short}. For that reason, the procedures for scaling the clusters is different. The documentation for the provider contains information about how to scale the clusters for imported clusters. 

See the following list of recommended settings for each available provider, but also see the documentation for more specific information:

* <<ocp-cluster-scale,{ocp-short} clusters>>
* <<amazon-elastic-kubernetes-services,Amazon Elastic Kubernetes Services>>
* <<google-kubernetes-engine,Google Kubernetes Engine>>
* <<microsoft-azure-kubernetes-service,Microsoft Azure Kubernetes Service>>
* <<vmware-vsphere,VMware vSphere>>
* <<openstack,Red Hat OpenStack Platform>>
* <<bare-metal-cluster,Bare metal cluster>>
* <<ibm-kubernetes-service,IBM Kubernetes Service>>
* <<ibm-power-systems,IBM Power systems>>
* <<ibm-z,IBM Z and LinuxONE>>

[#ocp-cluster-scale]
== {ocp-short} clusters

See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/scalability_and_performance/recommended-cluster-scaling-practices[Recommended cluster scaling practices] and link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/machine_management/manually-scaling-machineset[Manually scaling a MachineSet] in the {ocp-short} documentation that applies to the version that you are using. 

[#amazon-elastic-kubernetes-services]
== Amazon Elastic Kubernetes Services

If you are changing the number of nodes of an Amazon EKS cluster that you imported, see https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html[Cluster autoscaler] for information about scaling the cluster.

[#google-kubernetes-engine]
== Google Kubernetes Engine

If you are changing the number of nodes of a Google Kubernetes Engine cluster that you imported, see https://cloud.google.com/kubernetes-engine/docs/how-to/resizing-a-cluster[Resizing a cluster] for information about scaling the cluster.

[#microsoft-azure-kubernetes-service]
== Microsoft Azure Kubernetes Service

If you are changing the number of nodes of an Azure Kubernetes Services cluster that you imported, see https://docs.microsoft.com/en-us/azure/aks/scale-cluster[Scaling a cluster] for information about scaling the cluster.

[#vmware-vsphere]
== VMware vSphere

If you are changing the number of nodes of a VMware vSphere cluster that you imported, see https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.resmgmt.doc/GUID-755AB944-F3D0-43DD-82CD-8CDDDF8674E8.html[Edit cluster settings] for information about scaling the cluster.

[#openstack]
== Red Hat OpenStack Platform

If you are changing the number of nodes of a Red Hat OpenStack Platform cluster that you imported, see https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html/auto_scaling_for_instances/index[Auto scaling for instances] for information about scaling the cluster.

[#bare-metal-cluster]
== Bare metal cluster

If you are changing the number of nodes of a bare metal cluster that you imported, see https://docs.openshift.com/container-platform/4.9/installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster.html[Expanding the cluster] for information about scaling the cluster.

Note: Bare metal clusters are only supported when the hub cluster is {ocp-short} version 4.6, and later.

[#ibm-kubernetes-service]
== IBM Kubernetes Service

If you are changing the number of nodes of an IBM Kubernetes Service cluster that you imported, see https://cloud.ibm.com/docs/containers?topic=containers-add_workers[Adding worker nodes and zones to clusters] for information about scaling the cluster.

[#ibm-power-systems]
== IBM Power systems

If you are changing the number of nodes of an IBM Power systems cluster that you imported, see https://cloud.ibm.com/docs/containers?topic=containers-add_workers[need link] for information about scaling the cluster.

[#ibm-z]
== IBM Z and LinuxONE

If you are changing the number of nodes of an IBM Z and LinuxONE systems cluster that you imported, see https://cloud.ibm.com/docs/containers?topic=containers-add_workers[need link] for information about scaling the cluster.
