[#resizing-a-cluster]
= Resizing a cluster (Technology Preview)

You can customize your managed cluster specifications, such as virtual machine sizes and number of nodes. 

Many clusters that are managed by {product-title} can be scaled by using {product-title-short} console or command line and the `MachinePool` resource. A `MachinePool` resource is a Kubernetes resource on the Hub cluster that groups the `MachineSet` resources together on the managed cluster. The `MachinePool` resource uniformly configures a set of machine resources, including zone configurations, instance type, and root storage. It also helps you to manually configure the desired number of nodes or configure auto-scaling of nodes on the managed cluster.

[#resize-acm-created]
== Managed clusters created by {product-title-short}

Scaling clusters that were created by {product-title-short} using the `MachinePool` resource is a Technology Preview feature that is not supported for bare metal clusters that were created by {product-title-short}. 

[#machinepools-autoscale]
=== Autoscaling

Configuring autoscaling provides the flexibility of your cluster to scale as needed to lower your cost of resources by scaling down when traffic is low, and by scaling up to ensure that there are enough resources when there is a higher demand for resources. 

[#machinepools-autoscale-enable]
==== Enabling autoscaling

To enable autoscaling on your `MachinePool` resources using the {product-title-short} console, complete the following steps:

. In the {product-title-short} navigation, select *Infrastructure* > *Clusters*. 

. Click the name of your target cluster to view the details about the cluster.

. Select the _Machine pools_ tab to view the machine pool information.

. From the machine pools page, select *Enable autoscale* from the _Options_ menu for the target machine pool.

. Select the minimum and maximum number of machine set replicas. A machine set replica maps directly to a node on the cluster. 

. Click *Scale* to submit the changes. 
+
The changes might take several minutes to reflect on the console. You can view the status of the scaling operation by clicking *View machines* if the notification of the _Machine pools_ tab. 

To enable autoscaling on your `MachinePool` resources using the command line, complete the following steps:

. Enter the following command to view your list of machine pools:
+
----
oc get machinepools -n <managed-cluster-namespace>
----
Replace `managed-cluster-namespace` with the namespace of your target managed cluster.

. Enter the following command to edit the YAML file for the machine pool:
+
----
oc edit machinepool <name-of-MachinePool-resource> -n <namespace-of-managed-cluster>
----
Replace `name-of-MachinePool-resource` with the name of your `MachinePool` resource. 
+
Replace `namespace-of-managed-cluster` with the name of the namespace of your managed cluster.

. Delete the `spec.replicas` field from the YAML file.

. Add the `spec.autoscaling.minReplicas` setting and `spec.autoscaling.maxReplicas` fields to the resource YAML. 

. Add the minimum number of replicas to the `minReplicas` setting.

. Add the maximum number of replicas into the `maxReplicas` setting.

. Save the file to submit the changes.

Autoscaling is enabled for the machine pool.

[#machinepools-autoscale-disable]
==== Disabling autoscaling

You can disable autoscaling by using the console or the command line. 

To disable autoscaling by using the {product-title-short} console, complete the following steps:

. In the {product-title-short} navigation, select *Infrastructure* > *Clusters*. 

. Click the name of your target cluster to view the details about the cluster.

. Select the _Machine pools_ tab to view the machine pool information.

. From the machine pools page, select *Disable autoscale* from the _Options_ menu for the target machine pool.

. Select the number of machine set replicas that you want. A machine set replica maps directly with a node on the cluster. 

. Click *Scale* to submit the changes. It might take several minutes to display in the console.

. Click *View machines* in the notification on the _Machine pools_ tab to view the status of the scaling.

To disable autoscaling by using the command line, complete the following steps:

. Enter the following command to view your list of machine pools:
+
----
oc get machinepools -n <managed-cluster-namespace>
----
Replace `managed-cluster-namespace` with the namespace of your target managed cluster.

. Enter the following command to edit the YAML file for the machine pool:
+
----
oc edit machinepool <name-of-MachinePool-resource> -n <namespace-of-managed-cluster>
----
Replace `name-of-MachinePool-resource` with the name of your `MachinePool` resource. 
+
Replace `namespace-of-managed-cluster` with the name of the namespace of your managed cluster.

. Delete the `spec.autoscaling` field from the YAML file.

. Add the `spec.replicas` field to the resource YAML. 

. Add the number of replicas to the `replicas` setting.

. Save the file to submit the changes.

Autoscaling is disabled. 

[#machinepools-manual-scale-enable]
==== Manually scaling your cluster


 



Complete the following steps to enable autoscale for your cluster:








See the following list of recommended settings for each available provider, but also see the documentation for more specific information:

* <<amazon-web-services,Amazon Web Services>>
* <<google-cloud-platform,Google Cloud Platform>>
* <<microsoft-azure,Microsoft Azure>>
* <<vmware-vsphere,VMware vSphere>>
* <<openstack,Red Hat OpenStack Platform>>
* <<bare-metal-cluster,Bare metal cluster>>
* <<ibm-kubernetes-service,IBM Kubernetes Service>>

[#amazon-web-services]
== Amazon Web Services

You can change the number of nodes of a {ocp} cluster that was created in an Amazon Web Services environment by modifying the `MachineSet` parameters on the hub cluster.

*Note:* Because {product-title} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.

See https://docs.openshift.com/container-platform/4.7/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.7/machine_management/manually-scaling-machineset.html[Manually scaling a MachineSet] in the {ocp-short} documentation that applies to your version.

*Tip:* If you created the cluster by using the {product-title-short} console, then it is an {ocp-short} cluster.

If you are changing the number of nodes of an Amazon EKS cluster that you imported, see https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html[Cluster autoscaler] for information about scaling the cluster.

[#google-cloud-platform]
== Google Cloud Platform

You can change the number of nodes of an {ocp-short} cluster that was created in an Google Cloud Platform environment by modifying the `MachineSet` parameters on the hub cluster. 

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.
  
See https://docs.openshift.com/container-platform/4.7/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.7/machine_management/manually-scaling-machineset.html[Manually scaling a machine set] in the {ocp-short} documentation that applies to your version for more information about scaling your cluster.
*Tip:* If you created the cluster by using {product-title-short}, then it is an {ocp-short} cluster.

If you are changing the number of nodes of a Google Kubernetes Engine cluster that you imported, see https://cloud.google.com/kubernetes-engine/docs/how-to/resizing-a-cluster[Resizing a cluster] for information about scaling the cluster.

[#microsoft-azure]
== Microsoft Azure

You can change the number of nodes of an {ocp-short} cluster that was created in a Microsoft Azure environment by modifying the `MachineSet` parameters on the hub cluster.

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.

See https://docs.openshift.com/container-platform/4.7/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.7/machine_management/manually-scaling-machineset.html[Manually scaling a machine set] in the {ocp-short} documentation that applies to your version.
*Tip:* If you created the cluster by using {product-title-short}, then it is an {ocp-short} cluster.

If you are changing the number of nodes of an Azure Kubernetes Services cluster that you imported, see https://docs.microsoft.com/en-us/azure/aks/scale-cluster[Scaling a cluster] for information about scaling the cluster.

[#vmware-vsphere]
== VMware vSphere

You can change the number of nodes of an {ocp-short} cluster that was created in a VMware vSphere environment by modifying the `MachineSet` parameters on the hub cluster.

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.

See https://docs.openshift.com/container-platform/4.7/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.7/machine_management/manually-scaling-machineset.html[Manually scaling a machine set] in the {ocp-short} documentation that applies to your version.
*Tip:* If you created the cluster by using {product-title-short}, then it is an {ocp-short} cluster.

If you are changing the number of nodes of a VMware vSphere cluster that you imported, see https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.resmgmt.doc/GUID-755AB944-F3D0-43DD-82CD-8CDDDF8674E8.html[Edit cluster settings] for information about scaling the cluster.

[#openstack]
== Red Hat OpenStack Platform

You can change the number of nodes of an {ocp-short} cluster that was created in a Red Hat OpenShift Platform environment by modifying the `MachineSet` parameters on the hub cluster.

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.

See https://docs.openshift.com/container-platform/4.7/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.7/machine_management/manually-scaling-machineset.html[Manually scaling a machine set] in the {ocp-short} documentation that applies to your version.
*Tip:* If you created the cluster by using {product-title-short}, then it is an {ocp-short} cluster.

If you are changing the number of nodes of a Red Hat OpenStack Platform cluster that you imported, see https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html/auto_scaling_for_instances/index[Auto scaling for instances] for information about scaling the cluster.

[#bare-metal-cluster]
== Bare metal cluster

You can change the number of nodes of an {ocp-short} cluster that was created in a bare metal environment by modifying the `MachineSet` parameters on the hub cluster.

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.

See https://docs.openshift.com/container-platform/4.7/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.7/machine_management/manually-scaling-machineset.html[Manually scaling a machine set] in the {ocp-short} documentation that applies to your version.
*Tip:* If you created the cluster by using {product-title-short}, then it is an {ocp-short} cluster.

If you are changing the number of nodes of a bare metal cluster that you imported, see https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal-network-customizations.html[Installing a cluster on bare metal with network customizations] for information about scaling the cluster.

Note: Bare metal clusters are only supported when the hub cluster is {ocp-short} version 4.5, and later.

[#ibm-kubernetes-service]
== IBM Kubernetes Service

If you are changing the number of nodes of an IBM Kubernetes Service cluster that you imported, see https://cloud.ibm.com/docs/containers?topic=containers-add_workers[Adding worker nodes and zones to clusters] for information about scaling the cluster.

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.
