[#single-node-openshift]
= Creating a single node OpenShift cluster

You can create a single node OpenShift (SNO) cluster that contains only a single node. In a standard cluster, there are control plane nodes and separate worker nodes. This configuration can be helpful when you have many clusters that need to minimize their resource footprint. 

This procedure explains how to deploy a single SNO cluster. You can also test the procedure of provisioning multiple SNO clusters on edge resources by using the zero touch provisioning, which is a Technology Preview feature. For more information about that procedure, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/scalability_and_performance/ztp-deploying-disconnected[Deploying distributed units at scale in a disconnected environment] in the {ocp-short} documentation. 

*Important:* Creating a SNO cluster should not be used in production environments.

*Required access*: Administrator

[#sno_prerequisites]
== Prerequisites

* A {product-title} 2.4, or later, hub cluster that is running on {ocp} version 4.11, or later.
* Credentials to access the provider where you want to create your SNO cluster. The supported providers include: 
+
** Amazon Web Services
** Microsoft Azure
** Google Cloud Platform
** Red Hat OpenStack Platform
** VMware vSphere

[#sno_create]
== Create a Single-Node OpenShift cluster

To create a SNO cluster, complete the following steps:

Complete the steps in the {product-title-short} console for creating a cluster on one of the providers that are supported to run a SNO cluster in xref:../multicluster_engine/create.adoc#creating-a-cluster[Creating a cluster].

You must select {ocp-short} 4.11, or later In the _Release image_ field. If you enabled the feature, an option to select *Single node OpenShift* is displayed. 

*Note:* If you select an {ocp-short} version that is older than 4.11, the option to select _Single node OpenShift_ is not displayed.

When you select *Single node OpenShift* during the creation process, the _Worker pools_ option is removed from the procedure because there are no worker nodes in a SNO cluster. 

Add the `spec:skipMachinePools` parameter in the YAML content with a value of `true` by completing the following steps:

. If you cannot see the YAML content window, set the switch to *YAML:On* to view the content.

. Find the `spec` section for your cluster and add the following flag to the `spec` section:
+
[source,yaml]
----
skipMachinePools: true
----

*Important:* When you create an {ocp-short} SNO cluster on GCP, you must configure more CPU and memory resources than for a standard GCP cluster. The minimum requirements for a SNO cluster on GCP is 8 CPUs and 32 GB of memory. The standard requirements of 4 CPUs and 16 GB of memory is not stable for this type of cluster. 

[#dynamic-metrics-for-sno]
== Dynamic metrics for SNO clusters

Dynamic metrics collection supports automatic metric collection based on certain conditions. By default, a SNO cluster does not collect pod and container resource metrics. Once a SNO cluster reaches a specific level of resource consumption, the defined granular metrics are collected dynamically. When the cluster resource consumption is consistently less than the threshold for a period of time, granular metric collection stops.

The metrics are collected dynamically based on the conditions on the managed cluster specified by a collection rule. Because these metrics are collected dynamically, the following {product-title-short} Grafana dashboards do not display any data. When a collection rule is activated and the corresponding metrics are collected, the following panels display data for the duration of the time that the collection rule is initiated:

* Kubernetes / Compute Resources / Namespace (Pods)
* Kubernetes / Compute Resources / Namespace (Workloads)
* Kubernetes / Compute Resources / Nodes (Pods)
* Kubernetes / Compute Resources / Pod
* Kubernetes / Compute Resources / Workload

A collection rule includes the following conditions:

* A set of metrics to collect dynamically.
* Conditions written as a PromQL expression.
* A time interval for the collection, which must be set to `true`.
* A match expression to select clusters where the collect rule must be evaluated.

By default, collection rules are evaluated continuously on managed clusters every 30 seconds, or at a specific time interval. The lowest value between the collection interval and time interval takes precedence. Once the collection rule condition persists for the duration specified by the `for` attribute, the collection rule starts and the metrics specified by the rule are automatically collected on the managed cluster. Metrics collection stops automatically after the collection rule condition no longer exists on the managed cluster, at least 15 minutes after it starts.

The collection rules are grouped together as a parameter section named `collect_rules`, where it can be enabled or disabled as a group. {product-title-short} installation includes the collection rule group, `SNOResourceUsage` with two default collection rules: `HighCPUUsage` and `HighMemoryUsage`. The `HighCPUUsage` collection rule begins when the node CPU usage exceeds 70%. The `HighMemoryUsage` collection rule begins if the overall memory utilization of the SNO cluster exceeds 70% of the available node memory. Currently, the previously mentioned thresholds are fixed and cannot be changed. When a collection rule begins for more than the interval specified by the `for` attribute, the system automatically starts collecting the metrics that are specified in the `dynamic_metrics` section.

View the list of dynamic metrics that from the `collect_rules` section, in the following YAML file:

[source,yaml]
----
collect_rules:
  - group: SNOResourceUsage
    annotations:
      description: >
        By default, a SNO cluster does not collect pod and container resource metrics. Once a SNO cluster 
        reaches a level of resource consumption, these granular metrics are collected dynamically. 
        When the cluster resource consumption is consistently less than the threshold for a period of time, 
        collection of the granular metrics stops.
    selector:
      matchExpressions:
        - key: clusterType
          operator: In
          values: ["SNO"]
    rules:
    - collect: SNOHighCPUUsage
      annotations:
        description: >
          Collects the dynamic metrics specified if the cluster cpu usage is constantly more than 70% for 2 minutes
      expr: (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))) * 100 > 70
      for: 2m
      dynamic_metrics:
        names:
          - container_cpu_cfs_periods_total
          - container_cpu_cfs_throttled_periods_total
          - kube_pod_container_resource_limits 
          - kube_pod_container_resource_requests   
          - namespace_workload_pod:kube_pod_owner:relabel 
          - node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate 
          - node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate 
    - collect: SNOHighMemoryUsage
      annotations:
        description: >
          Collects the dynamic metrics specified if the cluster memory usage is constantly more than 70% for 2 minutes
      expr: (1 - sum(:node_memory_MemAvailable_bytes:sum) / sum(kube_node_status_allocatable{resource=\"memory\"})) * 100 > 70
      for: 2m
      dynamic_metrics:
        names:
          - kube_pod_container_resource_limits 
          - kube_pod_container_resource_requests 
          - namespace_workload_pod:kube_pod_owner:relabel
        matches:
          - __name__="container_memory_cache",container!=""
          - __name__="container_memory_rss",container!=""
          - __name__="container_memory_swap",container!=""
          - __name__="container_memory_working_set_bytes",container!=""
----

A `collect_rules.group` can be disabled in the `custom-allowlist` as shown in the following example. When a `collect_rules.group` is disabled, metrics collection reverts to the previous behavior. These metrics are collected at regularly, specified intervals:

[source,yaml]
----
collect_rules:
  - group: -SNOResourceUsage
---- 

The data is only displayed in Grafana when the rule is initiated.

