[#upgrading-your-cluster]
= Upgrading your cluster

After you create {ocp} clusters that you want to manage with {product-title}, you can use the {product-title} console to upgrade those clusters to the latest minor version that is available in the version channel that the managed cluster uses.

In a connected environment, the updates are automatically identified with notifications provided for each cluster that requires an upgrade in the {product-title-short} console. 

*Important:* The process for upgrading your clusters in a disconnected environment requires some additional steps to configure and mirror the required release images. It uses the operator for {cincinnati} to identify the upgrades. If you are in a disconnected environment, see xref:upgrade_cluster_discon.adoc#upgrading-disconnected-clusters[Upgrading disconnected clusters] for the required steps. 

*Notes:* 

To upgrade to a major version, you must verify that you meet all of the prerequisites for upgrading to that version. You must update the version channel on the managed cluster before you can upgrade the cluster with the console.

After you update the version channel on the managed cluster, the {product-title} console displays the latest versions that are available for the upgrade.

This method of upgrading only works for {ocp-short} managed clusters that are in a _Ready_ state. 

*Important:* You cannot upgrade Red Hat OpenShift Kubernetes Service managed clusters or {ocp-short} managed clusters on Red Hat OpenShift Dedicated by using the {product-title} console. 

To upgrade your cluster in a connected environment, complete the following steps:

. From the navigation menu, navigate to *Infrastructure* > *Clusters*. If an upgrade is available, it is shown in the _Distribution version_ column.

. Select the clusters in _Ready_ state that you want to upgrade. A cluster must be an {ocp-short} cluster to be upgraded with the console.
. Select *Upgrade*.
. Select the new version of each cluster.
. Select *Upgrade*.

If your cluster upgrade fails, the Operator generally retries the upgrade a few times, stops, and reports the status of the failing component. In some cases, the upgrade process continues to cycle through attempts to complete the process. Rolling your cluster back to a previous version following a failed upgrade is not supported. Contact Red Hat support for assistance if your cluster upgrade fails.

[#selecting-a-channel]
== Selecting a channel

You can use the {product-title-short} console to select a channel for your cluster upgrades on {ocp-short} version 4.6, or later. After selecting a channel, you are automatically reminded of cluster upgrades that are available for both Errata versions (4.8.1 > 4.8.2 > 4.8.3, and so on) and release versions (4.8 > 4.9, and so on).

To select a channel for your cluster, complete the following steps:

. From the {product-title-short} navigation, select *Infrastructure* > *Clusters*.

. Select the name of the cluster that you want to change to view the _Cluster details_ page. If a different channel is available for the cluster, an edit icon is displayed in the _Channel_ field.

. Click the edit icon to modify the setting in the field. 

. Select a channel in the _New channel_ field.

You can find the reminders for the available channel updates in the _Cluster details_ page of the cluster. 
