[#uninstalling-submariner]
= Uninstalling Submariner

You can uninstall the Submariner components from your clusters using the {product-title} console or the command-line. For Submariner versions earlier than 0.12, additional steps are needed to completely remove all data plane components.

[#uninstalling-submariner-console]
== Console method 

To uninstall Submariner from a cluster by using the {product-title-short} console, complete the following steps:

. From the {product-title-short} console navigation, select *Infrastructure* > *Clusters*, and select the _Cluster sets_ tab.

. Select the cluster set that contains the clusters from which you want to remove the Submariner components. 

. Select the *Submariner Add-ons* tab to view the clusters in the cluster set that have Submariner deployed. 

. In the _Actions_ menu for the cluster that you want to uninstall Submariner, select *Uninstall Add-on*. 

. Repeat those steps for other clusters from which you are removing Submariner.
+
*Tip:* You can remove the Submariner add-on from multiple clusters in the same cluster set by selecting multiple clusters and clicking *Actions*. Select *Uninstall Submariner add-ons*. 

If the version of Submariner that you are removing is earlier than version 0.12, continue with xref:../services/submariner/submariner_uninstall.adoc#uninstalling-submariner-manual[Manual removal steps for early versions of Submariner]. If the Submariner version is 0.12, or later, Submariner is removed. 

**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider. See xref:../submariner/submariner_uninstall.adoc#uninstalling-submariner-verifying[Verifying Submariner resource removal] for more information.  

[#uninstalling-submariner-cli]
== Command-line method  

To uninstall Submariner by using the command line, complete the following steps:

. Locate the clusters that contain the Submariner add-on by entering the following command:
+
----
oc get resource submariner-addon -n open-cluster-management
----

. Run a command similar to the following example to uninstall Submariner from the cluster:
+
----
oc delete resource submariner-addon -n <CLUSTER_NAME>
----
+
Replace `CLUSTER_NAME` with the name of the cluster.

. Confirm that you want to remove all of the Submariner components from the cluster. 

. Repeat the steps for each cluster to remove Submariner.

If the version of Submariner that you are removing is earlier than version 0.12, continue with xref:../services/submariner/submariner_uninstall.adoc#uninstalling-submariner-manual[Manual removal steps for early versions of Submariner]. If the Submariner version is 0.12, or later, Submariner is removed. 

**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider. See xref:../submariner/submariner_uninstall.adoc#uninstalling-submariner-verifying[Verifying Submariner resource removal] for more information.

[#uninstalling-submariner-manual]
== Manual removal steps for early versions of Submariner

When uninstalling versions of Submariner that are earlier than version 0.12, complete steps 5-8 in the  https://submariner.io/operations/cleanup/#manual-uninstall/[Manual Uninstall] section in the Submariner documentation.  

After completing those steps, your Submariner components are removed from the cluster. 

**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider. See xref:../submariner/submariner_uninstall.adoc#uninstalling-submariner-verifying[Verifying Submariner resource removal] for more information.

[#uninstalling-submariner-verifying]
== Verifying Submariner resource removal

After uninstalling Submariner, verify that all of the Submariner resources are removed from your clusters. If they remain on your clusters, some resources continue to accrue charges from infrastructure providers. Ensure that you have no additional Submariner resourceson your cluster by completing the following steps:

. Run the following command to list any Submariner resources that remain on the cluster:
+
----
oc get cluster <CLUSTER_NAME> grep submariner
----
+
Replace `CLUSTER_NAME` with the name of your cluster.

. Remove any resources on the list by entering the following command:
+
----
oc delete resource <RESOURCE_NAME> cluster <CLUSTER_NAME>
---- 
+
Replace `RESOURCE_NAME` with the name of the Submariner resource that you want to remove.

. Repeat steps 1-2 for each of the clusters until your search does not identify any resources. 

The Submariner resources are removed from your cluster.
