[#submariner-customizations]
= Customizing Submariner deployments

You can customize some of the settings of your Submariner deployments, including your Network Address Translation-Traversal (NATT) port, number of gateway nodes, and instance type of your gateway nodes. These customizations are consistent across all of the providers.

[#natt-port-custom]
== NATT port

If you want to customize your NATT port, customize and apply the following YAML content for your provider environment:

[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:
    credentialsSecret:
      name: <managed-cluster-name>-<provider>-creds
    IPSecNATTPort: <NATTPort>
----

* Replace `managed-cluster-namespace` with the namespace of your managed cluster.

* Replace `managed-cluster-name` with the name of your managed cluster

** AWS: Replace `provider` with `aws`. The value of `<managed-cluster-name>-aws-creds` is your AWS credential secret name, which you can find in the cluster namespace of your hub cluster.
** GCP: Replace `provider` with `gcp`. The value of `<managed-cluster-name>-gcp-creds` is your Google Cloud Platform credential secret name, which you can find in the cluster namespace of your hub cluster.

* Replace `managed-cluster-namespace` with the namespace of your managed cluster.

* Replace `managed-cluster-name` with the name of your managed cluster. The value of `managed-cluster-name-gcp-creds` is your Google Cloud Platform credential secret name, which you can find in the cluster namespace of your hub cluster.

* Replace `NATTPort` with the NATT port that you want to use.

*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.

To customize your NATT port in the VMware vSphere environment, customize and apply the following YAML content: 

[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:
    IPSecNATTPort: <NATTPort>
----

* Replace `managed-cluster-namespace` with the namespace of your managed cluster.

* Replace `NATTPort` with the NATT port that you want to use.

*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.

[#number-gateway-nodes]
== Number of gateway nodes

If you want to customize the number of your gateway nodes, customize and apply YAML content that is similar to the following example:

[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
   name: submariner
   namespace: <managed-cluster-namespace>
spec:
   credentialsSecret:
     name: <managed-cluster-name>-<provider>-creds
  gatewayConfig:
      gateways: <gateways>
----

* Replace `managed-cluster-namespace` with the namespace of your managed cluster.

* Replace `managed-cluster-name` with the name of your managed cluster. 

** AWS: Replace `provider` with `aws`. The value of `managed-cluster-name-aws-creds` is your AWS credential secret name, which you can find in the cluster namespace of your hub cluster. 

** GCP: Replace `provider` with `gcp`. The value of `<managed-cluster-name>-gcp-creds` is your Google Cloud Platform credential secret name, which you can find in the cluster namespace of your hub cluster.

* Replace `gateways` with the number of gateways that you want to use. If the value is greater than 1, the Submariner gateway automatically enables high availability.

*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.

If you want to customize the number of your gateway nodes in the VMware vSphere environment, customize and apply YAML content that is similar to the following example:

[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
   name: submariner
   namespace: <managed-cluster-namespace>
spec:
  gatewayConfig:
      gateways: <gateways>
----

* Replace `managed-cluster-namespace` with the namespace of your managed cluster.

* Replace `gateways` with the number of gateways that you want to use. If the value is greater than 1, the Submariner gateway automatically enables high availability.

[#instance-type-gateway-nodes]
== Instance types of gateway nodes

If you want to customize the instance type of your gateway node, customize and apply YAML content that is similar to the following example:

[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
   name: submariner
   namespace: <managed-cluster-namespace>
spec:
   credentialsSecret:
     name: <managed-cluster-name>-<provider>-creds
  gatewayConfig:
      instanceType: <instance-type>
----

* Replace `managed-cluster-namespace` with the namespace of your managed cluster.

* Replace `managed-cluster-name` with the name of your managed cluster. 

** AWS: Replace `provider` with `aws`. The value of `managed-cluster-name-aws-creds` is your AWS credential secret name, which you can find in the cluster namespace of your hub cluster. 

** GCP: Replace `provider` with `gcp`. The value of `<managed-cluster-name>-gcp-creds` is your Google Cloud Platform credential secret name, which you can find in the cluster namespace of your hub cluster.

* Replace `instance-type` with the AWS instance type that you want to use.

*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.

