[#preparing-selected-hosts-to-deploy-submariner]
= Preparing selected hosts to deploy Submariner

Before you deploy Submariner with {product-title}, you must manually prepare the clusters on the hosting environment for the connection. The requirements are different for different hosting environments, so follow the instructions for your hosting environment.

[#preparing-azure]
== Preparing Microsoft Azure for Submariner

To prepare the clusters on your Microsoft Azure for deploying the Submariner component, complete the following steps:

. Tag a node as a gateway node by running the following command:
+
----
kubectl label nodes <worker-node-name> "submariner.io/gateway=true" --overwrite
----

. Create a public IP and assign it to the VM of the node that was tagged as gateway node by running the following commands:
+
----
az network public-ip create --name <public-ip-name> --resource-group <res-group> -sku Standard
az network nic ip-config update --name <name>  --nic-name <gw-vm-nic> --resource-group <res-group>  --public-ip-address <public-ip-name>
----
+
Replace `res-group` with the resource group of the cluster.
+
Replace `gw-vm-nic` with the interface address.

. Create a network security group for the Submariner gateway by running the following command:
+
----
az network nsg create --name <gw-nsg-name> --resource-group <res-group>
----

. Create network security groups rules in your Azure environment to open the tunnel port (4500/UDP by default), NAT discovery port (4490/UDP by default) and metrics port (8080/TCP and 8081/TCP by default) for Submariner. These rules need to be created in both inbound and outbound directions for each of the ports.
+
----
az network nsg rule create --resource-group <res-group> \
--nsg-name <gw-nsg-name> --priority <priority> \
--name <name> --direction Inbound --access Allow \
--protocol <Protocol> --destination-port-ranges <port>

az network nsg rule create --resource-group <res-group> \
--nsg-name <gw-nsg-name> --priority <priority> \
--name <name> --direction Outbound --access Allow \
--protocol <Protocol> --destination-port-ranges <port>
----

. Create network security groups rules to allow communication by using the Encapsulated Security Payload (ESP) and Authentication Header (AH) protocols. These rules need to be created in both inbound and outbound directions for both of the protocols.
+
----
az network nsg rule create --resource-group <res-group> \
--nsg-name <gw-nsg-name> --priority <priority> \
--name <name> --direction Inbound --access Allow \
--protocol <Protocol> --destination-port-ranges 0-0

az network nsg rule create --resource-group <res-group> \
--nsg-name <gw-nsg-name> --priority <priority> \
--name <name> --direction Outbound --access Allow \
--protocol <Protocol> --destination-port-ranges 0-0
----

. Attach the security group to the gateway VM interface by entering the following command:
+
----
az network nic update -g <res-group> -n <gw-vm-nic>  --network-security-group <gw-nsg-name>
----

. Create network security group rules in your Azure environment to open the VXLAN port (4800/UDP by default) on the existing security groups (`<resource-group-name>-nsg` by default) that are associated with the worker and the main nodes.
+
----
az network nsg rule create --resource-group <res-group> \
--nsg-name <nsg-name> --priority <priority> \
--name <name> --direction Inbound --access Allow \
--protocol udp --destination-port-ranges <vxlan-port>

az network nsg rule create --resource-group <res-group> \
--nsg-name <nsg-name> --priority <priority> \
--name <name> --direction Outbound --access Allow \
--protocol udp --destination-port-ranges <vxlan-port>
----

*Important:* Ensure that a new gateway node is tagged as a gateway node when you reinstall Submariner. Reusing the current gateway after uninstalling Submariner result in the connections displaying an error state. This requirement is only applicable when you are using {product-title} with manual cloud preparation steps.

[#preparing-ibm]
== Preparing IBM Cloud for Submariner

There are two kinds of Red Hat OpenShift Kubernetes Service (ROKS) on IBM Cloud: the classic cluster and the second generation of compute infrastructure in a virtual private cloud (VPC). Submariner cannot run on the classic ROKS cluster since it cannot configure the IPsec ports for the classic cluster.

To configure the ROKS clusters on a VPC to use Submariner, complete the steps in the following links:

. Before you create a cluster, specify subnets for pods and services, which avoids overlapping CIDRs with other clusters. Make sure there are no overlapping pods and services CIDRs between clusters if you are using an existing cluster. See https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-subnets#vpc_basics[VPC Subnets] for the procedure.

. Attach a public gateway to subnets used in the cluster. See https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-subnets#vpc_basics_pgw[Public Gateway] for the procedure.

. Create inbound rules for the default security group of the cluster by completing the steps in https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-network-policy#security_groups_ui[Security Group]. Ensure that the firewall allows inbound and outbound traffic on 4500/UDP and 500/UDP ports for Gateway nodes, and allows inbound and outbound UDP/4800 for all the other nodes.

. Label a node that has the public gateway as `submariner.io/gateway=true` in the cluster.

. Refer to https://submariner.io/operations/deployment/calico/[Calico] to configure Calico CNI by creating IPPools in the cluster.

[#preparing-vm]
== Preparing VMware vSphere for Submariner 

Submariner uses IPsec to establish the secure tunnels between the clusters on the gateway nodes. You can use the default port or specify a custom port. When you run this procedure without specifying an IPsec NATT port, the default port is automatically used for the communication. The default port is 4500/UDP. 

Submariner uses virtual extensible LAN (VXLAN) to encapsulate traffic when it moves from the worker and master nodes to the gateway nodes. The VXLAN port cannot be customized, and is always port 4800/UDP.

Submariner uses 8080/TCP to send its metrics information among nodes in the cluster, this port cannot be customized.

The following ports must be opened by your VMWare vSphere administrator before you can enable Submariner:

.VMware vSphere and Submariner ports
|===
| Name | Default value | Customizable 

| IPsec NATT
| 4500/UDP
| Yes

| VXLAN
| 4800/UDP
| No

| Submariner metrics
| 8080/TCP
| No
|===

To prepare VMware vSphere clusters for deploying Submariner, complete the following steps:

. Ensure that the IPsec NATT, VXLAN, and metrics ports are open.

. Customize and apply YAML content that is similar to the following example:
+
[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:{}
----
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.
+
This configuration uses the default network address translation - traversal (NATT) port (4500/UDP) for your Submariner and one worker node is labeled as the Submariner gateway on your vSphere cluster.
+
Submariner uses IP security (IPsec) to establish the secure tunnels between the clusters on the gateway nodes. You can either use the default IPsec NATT port, or you can specify a different port that you configured. When you run this procedure without specifying an IPsec NATT port of 4500/UDP is automatically used for the communication.

[#preparing-bare]
== Preparing bare metal for Submariner

To prepare bare metal clusters for deploying Submariner, complete the following steps:

. Ensure that the IPsec NATT, VXLAN, and metrics ports are open.

. Customize and apply YAML content that is similar to the following example:
+
[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:{}
----
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.
+
This configuration uses the default network address translation - traversal (NATT) port (4500/UDP) for your Submariner and one worker node is labeled as the Submariner gateway on your bare metal cluster.
+
Submariner uses IP security (IPsec) to establish the secure tunnels between the clusters on the gateway nodes. You can either use the default IPsec NATT port, or you can specify a different port that you configured. When you run this procedure without specifying an IPsec NATT port of 4500/UDP is automatically used for the communication.

See xref:../submariner/submariner_customizations.adoc#submariner-customizations[Customizing Submariner deployments] for information about the customization options. 