[#deploying-submariner-disconnected]
= Deploying Submariner on disconnected clusters

To deploy Submariner with {product-title} on clusters disconnected clusters, you must first complete the steps outlined in link:../install/install_disconnected.adoc#install-on-disconnected-networks[Install in disconnected network environments].

[#configuring-submariner-disconnected]
== Configuring Submariner on disconnected clusters

After following the steps outlined in link:../install/install_disconnected.adoc#install-on-disconnected-networks[Install in disconnected network environments], you must configure Submariner during the installation to support deployment on disconnected clusters.

[#customizing-catalogsource-names]
=== Customizing _catalogSource_ names

By default, `submariner-addon` searches for a `catalogSource` with the name `redhat-operators`. When using a `catalogSource` with a different name, you must update the value of the `SubmarinerConfig.Spec.subscriptionConfig.Source` parameter in the `SubmarinerConfig` associated with your managed cluster with the custom name of the `catalogSource`.

[#configuring-submariner-disconnected]
=== Enabling _airGappedDeployment_ in _SubmarinerConfig_

When installing `submariner-addon` on a managed cluster from the {product-title} console, you can select the *Disconnected cluster* option so that Submariner does not call external servers.

If you are installing Submariner by using the APIs, you must set the `airGappedDeployment` parameter to `true` in the `SubmarinerConfig` associated with your managed cluster. 

