[#preparing-selected-hosts-to-deploy-submariner]
= Preparing selected hosts to deploy Submariner

Before you deploy Submariner with {product-title}, you must manually prepare the clusters on the hosting environment for the connection. The requirements are different for different hosting environments, so follow the instructions for your hosting environment.

[#preparing-ibm]
== Preparing IBM Cloud for Submariner

There are two kinds of Red Hat OpenShift Kubernetes Service (ROKS) on IBM Cloud: the classic cluster and the second generation of compute infrastructure in a virtual private cloud (VPC). Submariner cannot run on the classic ROKS cluster since it cannot configure the IPsec ports for the classic cluster.

To configure the ROKS clusters on a VPC to use Submariner, complete the steps in the following links:

. Before you create a cluster, specify subnets for pods and services, which avoids overlapping CIDRs with other clusters. Make sure there are no overlapping pods and services CIDRs between clusters if you are using an existing cluster. See https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-subnets#vpc_basics[VPC Subnets] for the procedure.

. Attach a public gateway to subnets used in the cluster. See https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-subnets#vpc_basics_pgw[Public Gateway] for the procedure.

. Create inbound rules for the default security group of the cluster by completing the steps in https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-network-policy#security_groups_ui[Security Group]. Ensure that the firewall allows inbound and outbound traffic on 4500/UDP and 500/UDP ports for Gateway nodes, and allows inbound and outbound UDP/4800 for all the other nodes.

. Label a node that has the public gateway as `submariner.io/gateway=true` in the cluster.

. Refer to https://submariner.io/operations/deployment/calico/[Calico] to configure Calico CNI by creating IPPools in the cluster.

[#preparing-vm]
== Preparing VMware vSphere for Submariner 

Submariner uses IPsec to establish the secure tunnels between the clusters on the gateway nodes. You can use the default port or specify a custom port. When you run this procedure without specifying an IPsec NATT port, the default port is automatically used for the communication. The default port is 4500/UDP. 

Submariner uses virtual extensible LAN (VXLAN) to encapsulate traffic when it moves from the worker and master nodes to the gateway nodes. The VXLAN port cannot be customized, and is always port 4800/UDP.

Submariner uses 8080/TCP to send its metrics information among nodes in the cluster, this port cannot be customized.

The following ports must be opened by your VMWare vSphere administrator before you can enable Submariner:

.VMware vSphere and Submariner ports
|===
| Name | Default value | Customizable 

| IPsec NATT
| 4500/UDP
| Yes

| VXLAN
| 4800/UDP
| No

| Submariner metrics
| 8080/TCP
| No
|===

To prepare VMware vSphere clusters for deploying Submariner, complete the following steps:

. Ensure that the IPsec NATT, VXLAN, and metrics ports are open.

. Customize and apply YAML content that is similar to the following example:
+
[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:{}
----
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.
+
This configuration uses the default network address translation - traversal (NATT) port (4500/UDP) for your Submariner and one worker node is labeled as the Submariner gateway on your vSphere cluster.
+
Submariner uses IP security (IPsec) to establish the secure tunnels between the clusters on the gateway nodes. You can either use the default IPsec NATT port, or you can specify a different port that you configured. When you run this procedure without specifying an IPsec NATT port of 4500/UDP is automatically used for the communication.

[#preparing-bare]
== Preparing bare metal for Submariner

To prepare bare metal clusters for deploying Submariner, complete the following steps:

. Ensure that the IPsec NATT, VXLAN, and metrics ports are open.

. Customize and apply YAML content that is similar to the following example:
+
[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:{}
----
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.
+
This configuration uses the default network address translation - traversal (NATT) port (4500/UDP) for your Submariner and one worker node is labeled as the Submariner gateway on your bare metal cluster.
+
Submariner uses IP security (IPsec) to establish the secure tunnels between the clusters on the gateway nodes. You can either use the default IPsec NATT port, or you can specify a different port that you configured. When you run this procedure without specifying an IPsec NATT port of 4500/UDP is automatically used for the communication.

See xref:../submariner/submariner_customizations.adoc#submariner-customizations[Customizing Submariner deployments] for information about the customization options. 

[#preparing-openstack]
== Preparing Red Hat OpenStack Platform for Submariner

You can use the `SubmarinerConfig` API to configure the Red Hat OpenStack Platform cluster to integrate with a Submariner deployment. To prepare Red Hat OpenStack Platform clusters for deploying Submariner, complete the following steps:

. Create a base 64-encoded file titled `clouds.yaml` with the authentication information for your Red Hat OpenStack Platform environment. The file should resemble the following example: 
+
[source,yaml]
----
clouds:
openstack:
auth:
   auth_url: https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000
   application_credential_id:
   application_credential_secret:
region_name: "regionOne"
interface: "public"
identity_api_version: 3
auth_type: "v3applicationcredential"
----

. Create a secret on your hub cluster in the namespace of your managed cluster that contains your Red Hat OpenStack Platform credential secret. 

.. Create a file named `openstack_secret.yaml` and add the following example content:
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
   name: <managed-cluster-name>-rhos-creds
   namespace: <managed-cluster-namespace>
type: Opaque
data:
   clouds.yaml: <clouds.yaml>
   cloud : <rhos-cloud-name>
----
+
Replace `managed-cluster-name` with the name of your managed cluster. The value of `managed-cluster-name-rhos-creds` is your Red Hat OpenStack Platform credential secret name, which you can find in the cluster namespace of your hub cluster.
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
Replace `clouds.yaml` with the path to your encoded Red Hat OpenStack Platform `clouds.yaml: $(base64 -w0 )` file.
+
Replace `rhos-cloud-name` with your encoded Red Hat OpenStack Platform cloud name `<cloud-name>: $base64 -w0 )`

.. Run the following command to apply the file:
+
----
oc apply -f openstack_secret.yaml
----

. If you created the managed cluster with {product-title-short}, or created the secret in the previous step, prepare the cluster.

.. Create a file named `submar_addon.yaml` with content that is similar to the following example: 
+
[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:
    credentialsSecret:
      name: <managed-cluster-name>-rhos-creds
----
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
Replace `managed-cluster-name` with the name of your managed cluster. The value of `managed-cluster-name-rhos-creds` is your Red Hat OpenStack Platform credential secret name, which you can find in the cluster namespace of your hub cluster.
+
*Note:* The name of the `SubmarinerConfig` custom resource must be `submariner`, as shown in the example.

.. Run the following command to apply the file:
+
----
oc apply -f submar_addon.yaml
----

This configuration automatically opens the Submariner required ports: network address translation - traversal (NATT) port (4500/UDP), virtual extensible LAN (VXLAN) port (4800/UCP), and Submariner metrics port (8080/TCP) on your RHOS instance. It also labels one worker node as the Submariner gateway and enables the public IP address of this node in your Red Hat OpenStack Platform cluster.

If you want to customize the Network Address Translation-Traversal (NATT) port, number of gateway nodes, or instance type of your gateway nodes for your deployment, see xref:../submariner/submariner_customizations.adoc#submariner-customizations[Customizing Submariner deployments] for the required steps.
