[#troubleshooting-failed-cluster-creation]
= Troubleshooting failed cluster creation

There are a few common causes for a failed cluster creation. 

[#symptom-cluster-creation]
== Symptom: Cluster creation fails

After you complete the procedure for creating a cluster, you cannot access it from the Red Hat Advanced Cluster Management console.

[#resolving-the-problem-cluster-creation]
== Resolving the problem:

. Determine if the managed cluster is available. You can check this in the _Clusters_ area of the Red Hat Advanced Cluster Management console. 

If it is not available, try recreating the managed cluster.

. Look for network or connectivity issues in the log of the `endpoint-connmgr` pod. 

If there are errors for connectivity problems, fix the connectivity issues and restart the `endpoint-connmgr` pod.

. Verify that the `klusterlet` is working correctly by checking the log for the `endpoint-workmgr` pod.

If the `klusterlet` is not working correctly, restart the `endpoint-workmgr` pod. 