[#troubleshooting]
= Troubleshooting

Before using the Troubleshooting guide, you can run the `oc admin mustgather` command to gather details, logs, and take steps in debugging issues. 

[#mustgather]
== Mustgather

To get started, learn about the troubleshooting scenarios, which includes use-cases for both using and not using the `mustgather` command to debug the issues.

* Scenario one: Use the _Troubleshooting guide_ to see if a solution to your problem is documented. The guide is organized by the major functions of the product.

+
With this scenario, you don't run the `mustgather` command before checking the guide.
+

For instance, if you are having trouble with creating a cluster, you might find a solution in the _Manage cluster_ section.
+

* Scenario two: User runs the `mustgather` command and uses the output to debug the issue.
+

* Scenario three: User runs `mustgather` to get info and share with Red Hat Support.

See the following procedure to start using the `mustgather` command:

. Learn about the `mustgather` command and install the prerequisites that you need at https://docs.openshift.com/container-platform/4.4/support/gathering-cluster-data.html[Red Hat Openshift Container Platform: Gathering data].

. After you install `oc`, be sure to change it to an executable file and add `oc` to your path.

. Log in to your hub cluster or log in to your managed cluster, whichever you need to troubleshoot.

. Run the following command, where you insert the image and the directory for the output:

+
----
oc adm must-gather --image=<image-name>--dest-dir=<directory>
----

. Go to your specified directory to see your output, which is organized in the following manner:

 - Two peer levels: `cluster-scoped-resources` and `namespace` resources.
 - Sub-level for each: API group for the custom resource definitions for both cluster-scope and namespace-scoped resources.
 - Next level for each: YAML file sorted by `kind`.

[#troubleshooting-guide]
== Troubleshooting guide

View the list of troubleshooting topics for Red Hat Advanced Cluster Management for Kubernetes:

* Installation

 To get to the original installing tasks, view link:../install/install_overview.adoc[Installing].

 ** xref:../troubleshoot_acm/install_operator_start.adoc#troubleshooting-multiclusterhub-operator-start[Troubleshooting multiclusterhub-operator start]
 
 **
 xref:../troubleshoot_acm/trouble_unistall_detach.adoc##troubleshooting-failed-unistallation-because-resources-exist[Troubleshooting failed uninstallation because resources exist]

* Cluster management

 To get to the original cluster management to link:..manage_cluster/intro.adoc[Managing your clusters].

 ** xref:../troubleshoot_acm/trouble_cluster_offline.adoc#troubleshooting-an-offline-cluster[Troubleshooting an offline cluster]
 ** xref:../troubleshoot_acm/trouble_import_status.adoc#troubleshooting-cluster-with-pending-import-status[Troubleshooting cluster with pending import status]
 ** xref:../troubleshoot_acm/trouble_console_status.adoc#troubleshooting-cluster-in-console-with-unknown-status[Troubleshooting cluster in console with unknown status]

* Application management

 To get to the original application management link:..manage_applications/app_management_overview.adoc[Managing applications].

 ** xref:../troubleshoot_acm/trouble_app_deploy.adoc#troubleshooting-application-kubernetes-deployment-version[Troubleshooting application Kubernetes deployment version]
* Governance, risk, and compliance

 To get to the original security guide, see link:../security/security_intro.adoc[Security].

 ** xref:../troubleshoot_acm/trouble_cert_webhook.adoc#troubleshooting-cert-manager-webhook[Troubleshooting cert-manager-webhook]

 