:_mod-docs-content-type: PROCEDURE

[#settings-limit-msa-agent]
= _tolerations_ and _nodeSelector_ settings do not affect the _managed-serviceaccount_ agent

[role="_abstract"]
The `tolerations` and `nodeSelector` settings configured on the `MultiClusterEngine` and `MultiClusterHub` resources do not affect the `managed-serviceaccount` agent deployed on the local cluster. 

The `managed-serviceaccount` add-on is not always required on the local cluster. If the `managed-serviceaccount` add-on is required, you can work around the issue by completing the following steps.

To learn more about how to use the `addonDeploymentConfig` custom resource to configure `tolerations` and `nodeSelector` for add-on, see link:../../add-ons/configure_klusterlet_addons.adoc#configure-klusterlet-addons[Configuring klusterlet add-ons].

.Procedure

. Create the `addonDeploymentConfig` custom resource.

. Set the `tolerations` and `nodeSelector` values for the local cluster and `managed-serviceaccount` agent.

. Update the `managed-serviceaccount` `ManagedClusterAddon` in the local cluster namespace to use the `addonDeploymentConfig` custom resource you created.
+
link:https://issues.redhat.com/browse/ACM-7523[ACM-7523]
