:_mod-docs-content-type: PROCEDURE

[#hypershift-capi-conflict]
= HyperShift operator and Cluster API components conflict

[role="_abstract"]
{acm-short} and {mce-short} enable the `hypershift` and `hypershift-local-hosting` components by default. To manage {rosa} clusters by using the `cluster-api` and `cluster-api-provider-aws` components, you must disable the `hypershift` and `hypershift-local-hosting` components to prevent API conflicts.

When you enable and then disable the `cluster-api` and `cluster-api-provider-aws` components, custom resource definitions of a higher version might remain in the cluster. You must manually remove the custom resource definitions before you re-enable the `hypershift-local-hosting` component.

.Procedure

. Remove the `clusterresourcesetbindings.addons.cluster.x-k8s.io` custom resource definition. Run the following command:

+
[source,bash]
----
oc delete crd clusterresourcesetbindings.addons.cluster.x-k8s.io
----

. Remove the `clusterresourcesets.addons.cluster.x-k8s.io` custom resource definition. Run the following command:

+
[source,bash]
----
oc delete crd clusterresourcesets.addons.cluster.x-k8s.io
----

. Remove the `clusters.cluster.x-k8s.io` custom resource definition. Run the following command:

+
[source,bash]
----
oc delete crd clusters.cluster.x-k8s.io
----

. Remove the `clusterclasses.cluster.x-k8s.io` custom resource definition. Run the following command:

+
[source,bash]
----
oc delete crd clusterclasses.cluster.x-k8s.io
----

. Remove the `machines.cluster.x-k8s.io` custom resource definition. Run the following command:

+
[source,bash]
----
oc delete crd machines.cluster.x-k8s.io
----

. Remove the `machinesets.cluster.x-k8s.io` custom resource definition. Run the following command:

+
[source,bash]
----
oc delete crd machinesets.cluster.x-k8s.io
----

. Remove the `machinedeployments.cluster.x-k8s.io` custom resource definition. Run the following command:

+
[source,bash]
----
oc delete crd machinedeployments.cluster.x-k8s.io
----

. Remove the `machinepools.cluster.x-k8s.io` custom resource definition. Run the following command:

+
[source,bash]
----
oc delete crd machinepools.cluster.x-k8s.io
----

. Remove the `machinehealthchecks.cluster.x-k8s.io` custom resource definition. Run the following command:

+
[source,bash]
----
oc delete crd machinehealthchecks.cluster.x-k8s.io
----

. Remove the `machinedrainrules.cluster.x-k8s.io` custom resource definition. Run the following command:

+
[source,bash]
----
oc delete crd machinedrainrules.cluster.x-k8s.io
----
