:_mod-docs-content-type: PROCEDURE

[#azure-auth-aro-hcp]
= Microsoft Azure authentication fails when creating Azure Red Hat OpenShift {hcp} clusters with Cluster API Provider for Azure

[role="_abstract"]
When you create Azure Red Hat OpenShift {hcp} clusters by using Cluster API Provider for Azure, the cluster creation might fail because of Microsoft Azure authentication errors.

To work around the issue, ensure you are connected to Microsoft Azure with your credentials. Complete the following steps:

.Procedure

. Verify your Microsoft Azure credentials secret. Run the following command. Replace `<cluster-namespace>` with the namespace of your cluster:

+
[source,bash]
----
oc get secret aso-credential -n <cluster-namespace> -o yaml
----

. Test the Microsot Azure connection. Run the following command:

+
[source,bash]
----
oc run azure-cli --rm -it --image=mcr.microsoft.com/azure-cli -- bash
----

. Log in to Microsoft Azure inside the pod. Run the following command. Replace `<client_id>`, `<client_secret>`, and `<tenant_id>` with your Microsoft Azure credentials:

+
[source,bash]
----
az login --service-principal --username <client_id> --password <client_secret> --tenant <tenant_id>
----
+
link:https://issues.redhat.com/browse/ACM-30244[ACM-30244]