:_mod-docs-content-type: CONCEPT

[#acm-search]
= Search

[role="_abstract"]
Search returns and lists each cluster with the resource that you search. For resources in the _hub_ cluster, the cluster name is displayed as _local-cluster_.

You can change the `local-cluster` name if the `enabled` field is set to `false`. You must use 34 or fewer characters for the `<your-local-cluster-name>` value. The `local-cluster` cannot be renamed if it is set as `enabled: true`.

*Note:* If you change the default name of your `local-cluster` to another value, the results appear within the changed local cluster name.

Your search results are grouped by `kind`, and each resource `kind` is grouped in a table. Search options depend on your cluster objects.
Refine your results with specific labels.

Learn about the {acm-short} Search service. Use Search to query resource data from your clusters. See the following documentation:

* xref:../search/search_console.adoc#search-service[Search service]
* xref:../search/create_search_collection.adoc#create-search-collection[Creating search configurable collection]
* xref:../search/custom_search_console.adoc#customize-search-console[Customizing search] 
* xref:../search/query_search_console.adoc#query-console[Querying in the console]
* xref:../search/search_klusterlet_addons.adoc#update-klusterlet-search[Updating klusterlet-addon-search deployments]
