[#update-klusterlet-search]
= Updating klusterlet-addon-search deployments

To collect the Kubernetes objects from the managed clusters, the `klusterlet-addon-search` pod is run on all the managed clusters where search is enabled. This deployment is run in the `open-cluster-management-agent-addon` namespace. A managed cluster with a high number of resources might require more memory for the `klusterlet-addon-search` deployment to function.

*Required access:* Cluster administrator

Resource requirements for the `klusterlet-addon-search` pod in a managed cluster can be specified in the `ManagedClusterAddon` custom resource in your {acm-short} hub cluster. There is a namespace for each managed cluster with the managed cluster name. Complete the following steps:

. Edit the `ManagedClusterAddon` custom resource from the namespace matching the managed cluster name. Run the following command to update the resource requirement in `xyz` managed cluster:

+
[source,bash]
----
oc edit managedclusteraddon search-collector -n xyz
----

. Append the resource requirements as annotations. When you define both `annotations` and `resourceRequirements`, the `annotations` value overrides the `resourceRequirements` value. View the following example:

+
[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  annotations: addon.open-cluster-management.io/search_memory_limit: 2048Mi
  addon.open-cluster-management.io/search_memory_request: 512Mi
----
+
*Notes:* 

- The annotation overrides the resource requirements on the managed clusters and automatically restarts the pod with new resource requirements.

- You can discover all resources defined in your managed cluster by using the API Explorer in the console. Alternatively, you can discover all resources by running the following command:
+
[source,bash]
----
oc api-resources
----

. Create an `AddonDeploymentConfig` resource and update the `klusterlet-addon-search` deployment resource requirements and limits. Your `AddonDeploymentConfig` resource might resemble the following example:

+
[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: search-addon-resources
  namespace: your-managed-ns
spec:
  resourceRequirements:
  - containerID: deployments:klusterlet-addon-search:collector
    resources:
      limits:
        memory: 1024Mi
      requests:
        memory: 512Mi
----

. Add the `backup` label to include the `AddOnDeploymentConfig` resource to the cluster backups. Run the following command:

+
[source,bash]
----
oc label addondeploymentconfig search-addon-resources -n <namespace-for-search-addon-resources> cluster.open-cluster-management.io/backup=""
----

. Update the `klusterlet-addon-search` deployment to use the new `AddonDeploymentConfig` resource. Run the following command:

+
[source,bash]
----
oc patch managedclusteraddon search-collector -n your-test-managed --type merge -p '{"spec": { "configs": [{"group": "addon.open-cluster-management.io","resource": "addondeploymentconfigs","name": "search-addon-resources","namespace": "your-test-managed"}]}}'
----
