:_mod-docs-content-type: CONCEPT

[#ansible-integration]
= Integration and components

[role="_abstract"]
You can integrate {aap-short} jobs into Git subscriptions. For instance, for a database front end and back end application, the database is required to be instantiated by using {aap-short} with an {aap-short} Job. The application is installed by a Git subscription. The database is instantiated _before_ you deploy the front end and back end application with the subscription.

The application subscription operator is enhanced to define two subfolders named `prehook` and `posthook`. Both folders are in the Git repository resource root path and contain all prehook and posthook {aap-short} jobs, respectively.

When the Git subscription is created, all of the prehook and posthook `AnsibleJob` resources are parsed and stored in memory as an object. The application subscription controller decides when to create the prehook and posthook `AnsibleJob` instances.

When you create a subscription custom resource, the Git branch and Git path references a Git repository root location. In the Git root location, the two subfolders `prehook` and `posthook` should contain at least one `Kind:AnsibleJob` resource.

* xref:../applications/ansible_prehook.adoc#prehook[Prehook]
* xref:../applications/ansible_posthook.adoc#posthook[Posthook]
