[#setting-up-ansible]
= Setting up {aap-short}

With {aap-short} jobs, you can automate tasks and integrate with external services, such as Slack and PagerDuty services. Your Git repository resource root path will contain `prehook` and `posthook` directories for {aap-short} jobs that run as part of deploying the application, updating the application, or removing the application from a cluster.

*Required access:* Cluster administrator

* <<prerequisites-for-ansible-integration,Prerequisites>>
* <<install-ansible,Installing {aap-short} Resource Operator>>

[#prerequisites-for-ansible-integration]
== Prerequisites 

* Install {ocp-short} 4.12 or later.

* Install {aap-short}. See link:https://docs.ansible.com/automation.html[Red Hat Ansible Automation Platform] documenation to install the latest supported version.

* Install the {aap-short} Resource Operator to connect {aap-short} jobs to the lifecycle of Git subscriptions. *Best practice:* The {aap-short} job template should be idempotent when it is run. 

* Check `PROMPT ON LAUNCH` on the template for both `INVENTORY` and `EXTRA VARIABLES`. See link:https://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html[Job templates] for more information.

[#install-ansible]
== Installing {aap-short} Resource Operator

. Log in to your {ocp-short} cluster console.
. Click *OperatorHub* in the console navigation.
. Search for and install the _{aap-short} Resource Operator_. *Note:* To submit prehook and posthook `AnsibleJobs`, install {aap} Resource Operator with corresponding version available on the following {ocp-short} versions: 

  - {ocp-short} 4.8 needs (AAP) Resource Operator early-access, stable-2.1, stable-2.2
  - {ocp-short} 4.9 needs (AAP) Resource Operator early-access, stable-2.1, stable-2.2 
  - {ocp-short} 4.10 and later needs (AAP) Resource Operator stable-2.1, stable-2.2

You can then create the credential from the _Credentials_ page in the console. Click *Add credential*, or access the page from the navigation. See link:../clusters/credentials/credential_ansible.adoc[Creating a credential for {aap-short}] for credential information.