:_mod-docs-content-type: PROCEDURE

[#ansible-secrets]
= Set up {aap-short} secrets

[role="_abstract"]
You must create an {aap-short} secret custom resources in the same subscription namespace. The {aap-short} secret is limited to the same subscription namespace.

.Procedure

. Create the secret from the console by filling in the `{aap-short} secret name` section. To create the secret using terminal, edit and apply the sample `yaml` file: 

+
*Note:* The `namespace` is the same namespace as the subscription namespace. The `stringData:token` and `host` are from the {aap-short}.

+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: toweraccess
  namespace: same-as-subscription
type: Opaque
stringData:
  token: ansible-tower-api-token
  host: https://ansible-tower-host-url
----

. Run the following command to add your YAML file:

+
[source,bash]
----
oc apply -f
----
+
When the app subscription controller creates prehook and posthook Ansible jobs, if the secret from subscription `spec.hooksecretref` is available, then it is sent to the `AnsibleJob` custom resources `spec.tower_auth_secret` and the `AnsibleJob` can access the {aap-short}.
