[#setting-up-ansible]
= Setting up {aap-short}

With {aap-short} jobs, you can automate tasks and integrate with external services, such as Slack and PagerDuty services. Your Git repository resource root path will contain `prehook` and `posthook` directories for {aap-short} jobs that run as part of deploying the application, updating the application, or removing the application from a cluster.

*Required access:* Cluster administrator

* <<prerequisites-for-ansible-integration,Prerequisites>>
* <<install-ansible,Installing {aap-short} Resource Operator>>

[#prerequisites-for-ansible-integration]
== Prerequisites 

* {ocp-short} 4.6 or later

* You must have {aap-short} installed. Install the latest supported version of {aap-short}. See https://docs.ansible.com/automation.html[Red Hat Ansible Automation Platform] documenation for more details.

* Install the {aap-short} Resource Operator to connect {aap-short} jobs to the lifecycle of Git subscriptions. For best results when using the AnsibleJob to launch {aap-short} jobs, the {aap-short} job template should be idempotent when it is run. 

Check `PROMPT ON LAUNCH` on the template for both INVENTORY and EXTRA VARIABLES. See https://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html[Job templates] for more information.

[#install-ansible]
== Installing {aap-short} Resource Operator

. Log in to your {ocp-short} cluster console.
. Click *OperatorHub* in the console navigation.
. Search for and install the _{aap-short} Resource Operator_. *Note:* To submit prehook and posthook `AnsibleJobs`, install {aap} Resource Operator with corresponding version available on different {ocp-short} versions:

  - {ocp-short} 4.6 needs (AAP) Resource Operator early-access 
  - {ocp-short} 4.7 needs (AAP) Resource Operator early-access, stable-2.1
  - {ocp-short} 4.8 needs (AAP) Resource Operator early-access, stable-2.1, stable-2.2
  - {ocp-short} 4.9 needs (AAP) Resource Operator early-access, stable-2.1, stable-2.2 
  - {ocp-short} 4.10 needs (AAP) Resource Operator stable-2.1, stable-2.2

You can then create the credential from the _Credentials_ page in the console. Click *Add credential* or access the page from the navigation. See link:../multicluster_engine/credentials/credential_ansible.adoc[Creating a credential for {aap-short} ] for credential information.

[#ansible-integration]
== Ansible integration and components

You can integrate {aap-short} jobs into Git subscriptions. For instance, for a database front-end and back-end application, the database is required to be instantiated using {aap-short} with an Ansible Job, and the application is installed by a Git subscription. The database is instantiated _before_ you deploy the front-end and back-end application with the subscription.

The application subscription operator is enhanced to define two subfolders: `prehook` and `posthook`. Both folders are in the Git repository resource root path and contain all prehook and posthook Ansible jobs, respectively.

When the Git subscription is created, all of the pre and post AnsibleJob resources are parsed and stored in memory as an object. The application subscription controller decides when to create the pre and post AnsibleJob instances.

When you create a subscription CR, the Git-branch and Git-path points to a Git repository root location. In the Git root location, the two subfolders `prehook` and `posthook` should contain at least one `Kind:AnsibleJob` resource.