[#channel-samples]
= Channel samples overview

View samples and YAML definitions that you can use to build your files. Channels (`channel.apps.open-cluster-management.io`) provide you with improved continuous integration and continuous delivery capabilities for creating and managing your {product-title} applications.

To use the OpenShift CLI tool, see the following procedure:

.. Compose and save your application YAML file with your preferred editing tool.
.. Run the following command to apply your file to an API server. Replace `filename` with the name of your file:
+
----
oc apply -f filename.yaml
----

.. Verify that your application resource is created by running the following command:
+
----
oc get application.app
----

* <<channel-yaml-structure,Channel YAML structure>>
* <<channel-yaml-table,Channel YAML table>>
* <<object-storage-bucket-object-storage-channel,Object storage bucket (ObjectBucket) channel>>
* <<helm-repository-channel,Helm repository (`HelmRepo`) channel>>
* <<github-repository-channel,Git (`Git`) repository channel>>

[#channel-yaml-structure]
== Channel YAML structure

For application samples that you can deploy, see the https://github.com/open-cluster-management/application-samples[`open-cluster-management`] repository.

The following YAML structures show the required fields for a channel and some of the common optional fields.
Your YAML structure needs to include some required fields and values. Depending on your application management requirements, you might need to include other optional fields and values.
You can compose your own YAML content with any tool and in the product console.

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name:
  namespace: # Each channel needs a unique namespace, except Git channel.
spec:
  sourceNamespaces:
  type:
  pathname:
  secretRef:
    name:
  gates:
    annotations:
  labels:
----

[#channel-yaml-table]
== Channel YAML table

|===
| Field | Description

| apiVersion
| Required. Set the value to `apps.open-cluster-management.io/v1`.

| kind
| Required. Set the value to `Channel` to indicate that the resource is a channel.

| metadata.name
| Required. The name of the channel.

| metadata.namespace
| Required. The namespace for the channel; Each channel needs a unique namespace, except the Git channel.

| spec.sourceNamespaces
| Optional. Identifies the namespace that the channel controller monitors for new or updated deployables to retrieve and promote to the channel.

| spec.type
| Required. The channel type. The supported types are: `HelmRepo`, `Git`, and `ObjectBucket` (Object storage in the console)

| spec.pathname
| Required for `HelmRepo`, `Git`, `ObjectBucket` channels. For a `HelmRepo` channel, set the value to be the URL for the Helm repository. For an `ObjectBucket` channel, set the value to be the URL for the Object storage. For a `Git` channel, set the value to be the HTTPS URL for the Git repository.

| spec.secretRef.name
| Optional. Identifies a Kubernetes Secret resource to use for authentication, such as for accessing a repository or chart.
You can use a secret for authentication with only `HelmRepo`, `ObjectBucket`, and `Git` type channels.

| spec.gates
| Optional. Defines requirements for promoting a deployable within the channel. If no requirements are set, any deployable that is added to the channel namespace or source is promoted to the channel. The `gates` value is only for `ObjectBucket` channel types and does not apply to `HelmRepo` and `Git` channel types, .

| spec.gates.annotations
| Optional. The annotations for the channel. Deployables must have matching annotations to be included in the channel.

| metadata.labels
| Optional. The labels for the channel.

| spec.insecureSkipVerify 
| Optional. Default value is `false`, if set `true`, the channel connection is built by skipping the authentication

|===

The definition structure for a channel can resemble the following YAML content:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: predev-ch
  namespace: ns-ch
  labels:
    app: nginx-app-details
spec:
  type: HelmRepo
  pathname: https://kubernetes-charts.storage.googleapis.com/
----

[#object-storage-bucket-object-storage-channel]
== Object storage bucket (ObjectBucket) channel

The following example channel definition abstracts an Object storage bucket as a channel:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
 name: dev
 namespace: ch-obj
spec:
 type: ObjectBucket
 pathname: [http://9.28.236.243:xxxx/dev] # URL is appended with the valid bucket name, which matches the channel name.
 secretRef:
   name: miniosecret
 gates:
   annotations:
     dev-ready: true
----

[#helm-repository-channel]
== Helm repository (`HelmRepo`) channel

The following example channel definition abstracts a Helm repository as a channel:

*Deprecation notice:* For {product-version}, specifying `insecureSkipVerify: "true"` in channel `ConfigMap` reference to skip Helm repo SSL certificate is deprecated. See the replacement in the following current sample, with `spec.insecureSkipVerify: true` that is used in the channel instead:

[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: hub-repo
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: Helm
  namespace: hub-repo
spec:
    pathname: [https://9.21.107.150:8443/helm-repo/charts] # URL points to a valid chart URL.
    insecureSkipVerify: true
    type: HelmRepo
----

The following channel definition shows another example of a Helm repository channel:

*Note:* For Helm, all Kubernetes resources contained within the Helm chart must have the label release `{{ .Release.Name }}`` for the application topology to display properly.
[source,YAML]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: predev-ch
  namespace: ns-ch
  labels:
    app: nginx-app-details
spec:
  type: HelmRepo
  pathname: https://kubernetes-charts.storage.googleapis.com/
----

[#github-repository-channel]
== Git (`Git`) repository channel

The following example channel definition displays an example of a channel for the Git Repository.
In the following example, `secretRef` refers to the user identity that is used to access the Git repo that is specified in the `pathname`. If you have a public repo, you do not need the `secretRef` label and value:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: hive-cluster-gitrepo
  namespace: gitops-cluster-lifecycle
spec:
  type: Git
  pathname: https://github.com/open-cluster-management/gitops-clusters.git
  secretRef:
    name: github-gitops-clusters
---
apiVersion: v1
kind: Secret
metadata:
  name: github-gitops-clusters
  namespace: gitops-cluster-lifecycle
data:
  user: dXNlcgo=            # Value of user and accessToken is Base 64 coded.
  accessToken: cGFzc3dvcmQ
----
