:_mod-docs-content-type: PROCEDURE

[#controller-change]
= Edit the controller flag

[role="_abstract"]
To configure `LeaderElection`, you change the following default values:

`leader-election-lease-duration`:: 137 seconds
`renew-deadline`:: 107 seconds
`retry-period`:: 26 seconds

See the following steps to change the `multicluster-operators-application`, `multicluster-operators-channel`, `multicluster-operators-standalone-subscription`, or `multicluster-operators-hub-subscription` controllers:

.Procedure

. Run the following command to pause your `multiclusterhub`:
+
[source,bash]
----
oc annotate mch -n open-cluster-management multiclusterhub mch-pause=true --overwrite=true
----

. Edit the `deployment` file by adding the controller name to the `oc edit` command. See the following example command:

+
[source,bash]
----
oc edit deployment -n open-cluster-management multicluster-operators-hub-subscription
----

. Locate the controller command flags by searching for `- command`.

. From the containers section in the controller, insert a `- command` flag. For instance, insert `RetryPeriod`.

. Save the file. The controller automatically restarts to apply the flag. 

. Repeat this procedure for each controller that you want to change.

. Run the following command to resume your `multiclusterhub`:
+
[source,bash]
----
oc annotate mch -n open-cluster-management multiclusterhub mch-pause=false --overwrite=true
----
+
See the following example output of a successful edit to the `-command`, where the `retryPeriod` flag doubles the previously mentioned default time to `52`, which is allotted to retry acquiring `leaderElection`:
+
[source,yaml]
----
command:                                                                                                                                                                 
- /usr/local/bin/multicluster-operators-subscription
- --sync-interval=60
- --retry-period=52
----
