:_mod-docs-content-type: PROCEDURE

[#configuring-a-rolling-update-for-a-subscription]
= Configure a rolling update for a subscription

[role="_abstract"]
If you have existing subscriptions that you want to configure to use a rolling update, you need to create your target subscription and update your initial existing subscription to include the required annotations.

[#deploy_pre]
.Prerequisites

* You have an initial subscription that references the initial version of a Kubernetes resource or Helm chart and a placement for defining the resource or chart deployment.
+
This initial subscription serves as the channel subscription and includes the settings for defining the channel and package information for the subscription.
+
For more information about how to define a subscription, see xref:../applications/allow_deny.adoc#creating-allow-deny-list[Create an allow and deny list as subscription administrator].

* The subscription that references the initial resource or chart version is deployed to your target managed clusters and has been used to deploy the initial version of the resource or chart to the same target managed clusters.
+
At this stage no rolling update is configured and any change to the initial version at the source is then deployed to all managed clusters.

[#procedure_deploy]
.Procedure

. Create the target subscription resource YAML definition to point to the newer version of the resource or chart to deploy.
+
This definition must use the same definition structure as any subscription application resource kind.
. Update the initial subscription YAML definition to include the following annotations to indicate that a rolling update is used for updating the subscription:
+
[source,yaml]
----
annotations:
  apps.open-cluster-management.io/rollingupdate-target:
  apps.open-cluster-management.io/rollingupdate-maxunavailable:
----
+
** The `apps.open-cluster-management.io/rollingupdate-target` annotation identifies the target subscription.
** The `apps.open-cluster-management.io/rollingupdate-maxunavailable` annotation identifies the maximum percentage of clusters that can be deployed at a time and rendered unavailable during the update.
The actual number of clusters is determined by rounding down to an absolute value.
By default, the maximum percentage is 25%.
** The definition does not include any other configurations for the managing the rolling update.
+
For example, the following snippet of a YAML definition shows sample values for these annotations:
+
[source,yaml]
----
metadata:
annotations:
    apps.open-cluster-management.io/rollingupdate-target: target-subscription-name
    apps.open-cluster-management.io/rollingupdate-maxunavaialble: 30
name: initial-subscription-name
namespace: default
----
+
In the preceding example, the rolling update includes 30% of clusters.
+
You can use the OpenShift CLI (oc) tool to add the annotations to an existing subscription instead of directly modifying the YAML definition.
Use the following command to add the annotations to a subscription:
+
[source,bash]
----
oc annotate --overwrite subscriptions.apps.open-cluster-management.io sub-orig -n ns-sub-1 apps.open-cluster-management.io/rollingupdate-target=sub-target apps.open-cluster-management.io/rollingupdate-maxunavaialble=30
----
+
With the subscription resources created or updated, the rolling update begins and the new target subscription and updated initial subscription are deployed to the managed clusters.
Then, the target subscription that is on the managed clusters is used to detect the new version of the resource or chart for deployment.

See subscription samples in xref:../applications/app_sample.adoc#application-samples[Application samples].
