
[#gitops-config]
= Configuring Managed Clusters for OpenShift GitOps operator

To configure GitOps, you can register a set of one or more {product-title} managed clusters to an instance of {ocp} GitOps operator. After registering, you can deploy applications to those clusters. Set up a continuous GitOps environment to automate application consistency across clusters in development, staging, and production environments.

[#prerequisites-argo]
== Prerequisites 

. You need to install the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/cicd/gitops[Red Hat OpenShift GitOps operator] on your {product-title}.

. Import one or more managed clusters.

[#register-gitops]
== Registering managed clusters to GitOps

. Create managed cluster sets and add managed clusters to those managed cluster sets. See the example for managed cluster sets in the https://github.com/open-cluster-management/multicloud-integrations/blob/main/examples/managedclusterset.yaml[multicloud-integrations managedclusterset].

+
See the link:../clusters/managedclustersets.adoc#managedclustersets[Creating and managing ManagedClusterSets] documentation for more information.

. Create managed cluster set _binding_ to the namespace where {ocp} GitOps is deployed.

+
See the example in the repository at https://github.com/stolostron/multicloud-integrations/blob/main/examples/managedclustersetbinding.yaml[multicloud-integrations managedclustersetbinding], which binds to the `openshift-gitops` namespace.

+
See the link:../clusters/managedclustersets.adoc#creating-a-managedclustersetbinding[Creating a ManagedClusterSetBinding resource] documentation for more information.

. In the namespace that is used in managed cluster set binding, create a placement custom resource to select a set of managed clusters to register to an {ocp-short} GitOps operator instance. You can use the example in the repository at https://github.com/stolostron/multicloud-integrations/blob/main/examples/placement.yaml[multicloud-integration placement]

+
See link:../clusters/placement_managed.adoc[Using ManagedClusterSets with Placement] for placement information. 

+
*Note:* Only {ocp-short} clusters are registered to an {ocp} GitOps operator instance, not other Kubernetes clusters.

. Create a `GitOpsCluster` custom resource to register the set of managed clusters from the placement decision to the specified instance of {ocp} GitOps. This enables the {ocp} GitOps instance to deploy applications to any of those {product-title-short} managed clusters.

+
Use the example in the repository at https://github.com/stolostron/multicloud-integrations/blob/main/examples/gitopscluster.yaml[multicloud-integrations gitops cluster].

+
*Note:* The referenced `Placement` resource must be in the same namespace as the `GitOpsCluster` resource.

+
See from the following sample that `placementRef.name` is `all-openshift-clusters`, and is specified as target clusters for the GitOps instance that is installed in `argoNamespace: openshift-gitops`. The `argoServer.cluster` specification requires the `local-cluster` value.

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-cluster-sample
  namespace: dev
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
----

. Save your changes. You can now follow the GitOps workflow to manage your applications. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/cicd/index#understanding-openshift-gitops[About GitOps] to learn more.

[#secret-gitops]
== GitOps token

When you integrate with the GitOps operator for every managed cluster that is bound to the GitOps namespace through the placement and `ManagedClusterSetBinding` custom resources, a secret with a token to access the `ManagedCluster` is created in the namespace. This is required for the GitOps controller to sync resources to the managed cluster. When a user is given administrator access to a GitOps namespace to perform application lifecycle operations, the user also gains access to this secret and `admin` level to the managed cluster. 

If this is not desired, instead of binding the user to the namespace-scoped `admin` role, use a more restrictive custom role with permissions required to work with application resources that can be created and used to bound the user. See the following `ClusterRole` example:


[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-set-admin
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets
  verbs:
  - get
  - list
  - watch
  - update
  - delete
  - deletecollection
  - patch
----

