[#tolerations-config]
= Configuring application placement tolerations for {product-title-short} and OpenShift GitOps

{product-title-short} provides a way for you to register managed clusters that deploy applications to Red Hat OpenShift GitOps.

In some unstable network scenarios, the managed clusters might be temporarily placed in `Unavailable` state. If a `Placement` resource is being used to facilitate the deployment of applications, add the following tolerations for the `Placement` resource to continue to include unavailable clusters. The following example shows a `Placement` resource with tolerations:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement
  namespace: ns1
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
----

[#additional-resources-tolerations]
== Additional resources

- Refer to xref:../applications/tolerations_config.adoc#gitops-config[Configuring managed clusters for OpenShift GitOps operator]. 

- Return to the beginning of the topic, <<tolerations-config,Configuring placement tolerations for {product-title-short} and OpenShift GitOps>>.

