[#managing-apps-with-object-storage-repositories]
= Managing apps with Object storage repositories

When you deploy Kubernetes resources using an application, the resources are located in specific repositories. Learn how to deploy resources from Object storage repositories in the following procedure. Learn more about the application model at xref:../applications/app_model.adoc#application-model-and-definitions[Application model and definitions].

*User required access:* A user role that can create applications. You can only perform actions that your role is assigned. Learn about access requirements from the link:../access_control/rbac.adoc#role-based-access-control[Role-based access control] documentation. 

* <<deploy-resources-from-object-storage-git-repo, Deploy resources from object storage>>
* <<sample-yaml-object, Sample YAML>>
* <<creating-aws-object-bucket, Creating your Amazon Web Services (AWS) S3 object bucket>>
* <<subscribing-to-aws-bucket, Subscribing to the object in the AWS bucket>>
* <<sample-aws-subscription, Sample AWS subscription>>

[#deploy-resources-object-storage]
== Deploy resources from object storage

When you deploy Kubernetes resources using an application, the resources are located in specific repositories. Learn how to deploy resources from object storage Git repositories in the following procedure:

. From the console navigation menu, click *Applications*.

. Click *Create application*.

+
For the following steps, select *YAML: On* to view the YAML in the console as you create your application. See YAML samples later in the topic.

. Enter the following values in the correct fields:
+
* Name: Enter a valid Kubernetes name for the application.
* Namespace: Select a namespace from the list. You can also create a namespace by using a valid Kubernetes name if you are assigned the correct access role.
 
. Choose *Object storage* from the list of repositories that you can use.

. Enter the required URL path or select an existing path.

+
If you select an existing Object storage repository path, you do not need to specify connection information if this is a private repository. The connection information is pre-set and you do not need to view these values. 

+
If you enter a new Object storage repository path, you can optionally enter Object storage connection information if this is a private Object storage repository.

. Enter values for the optional fields. Optional fields are defined in the fields or in the hover text.
 
. Set any optional pre and post-deployment tasks. 
 
. From _Select clusters to deploy_, you can update the placement rule information for your application. Choose from the following:

+
- Deploy on local cluster

- Deploy to all online clusters and local cluster

- Deploy application resources only on clusters matching specified labels

- You have the option to _Select existing placement configuration_ if you create an application in an existing namespace with placement rules already defined.
 
. From _Settings_, you can specify application behavior. To block or activate changes to your deployment during a specific time window, choose an option for _Deployment window_ and your _Time window configuration_.

. You can either choose another repository or Click *Save*.

. You are redirected to the _Overview_ page where you can view the details and topology.

[#sample-yaml-object]
== Sample YAML

The following example channel definition abstracts an object storage as a channel:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
 name: dev
 namespace: ch-obj
spec:
 type: Object storage
 pathname: [http://9.28.236.243:31311/dev] # URL is appended with the valid bucket name, which matches the channel name.
 secretRef:
   name: miniosecret
 gates:
   annotations:
     dev-ready: true
----

*Note:* To see REST API, use the link:../apis/api.adoc#apis[APIs].
 
[#creating-aws-object-bucket]
== Creating your Amazon Web Services (AWS) S3 object storage bucket

You can set up subscriptions to subscribe resources that are defined in the Amazon Simple Storage Service (Amazon S3) object storage service. See the following procedure:

. Log into the https://s3.console.aws.amazon.com/[AWS console] with your AWS account, user name, and password.

. Navigate to *Amazon S3* > *Buckets* to the bucket home page.

. Click *Create Bucket* to create your bucket.

. Select the *AWS region*, which is essential for connecting your AWS S3 object bucket.

. Create the bucket access token.
//is this pretty intuitive, how do they create?

. Navigate to your user name in the navigation bar, then from the drop-down menu, select *My Security Credentials*.

. Navigate to _Access keys for CLI, SDK, & API access_ in the _AWS IAM credentials_ tab and click on *Create access key*.

. Save your _Access key ID_ , _Secret access key_. 
 
. Upload your object YAML files to the bucket.

[#subscribing-to-aws-bucket]
== Subscribing to the object in the AWS bucket

. Create an object bucket type channel with a secret to specify the _AccessKeyID_, _SecretAccessKey_, and _Region_ for connecting the AWS bucket. The three fields are created when the AWS bucket is created.

. Add the URL. The URL identifies the channel in a AWS S3 bucket if the URL contains `s3://` or `s3 and aws` keywords. For example, see all of the following bucket URLs have AWS s3 bucket identifiers:

+
----
https://s3.console.aws.amazon.com/s3/buckets/xili-bucket-1
s3://xili-bucket-1/
https://xili-bucket-1.s3.amazonaws.com/
----

+
*Note:* The AWS S3 object bucket URL is not necessary to connect the bucket with the AWS S3 API. 

[#sample-aws-subscription]
== Sample AWS subscription

See the following complete AWS S3 object bucket channel sample YAML file:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: object-dev
  namespace: ch-object-dev
spec:
  type: ObjectBucket
  pathname: https://s3.console.aws.amazon.com/s3/buckets/xili-bucket-1
  secretRef:
    name: secret-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-dev
  namespace: ch-object-dev
stringData:
  AccessKeyID: <your AWS bucket access key id>
  SecretAccessKey: <your AWS bucket secret access key>
  Region: <your AWS  bucket region>
type: Opaque
----

You can continue to create other AWS subscription and placement rule objects.
//so just start back at the beginning or another topic?
