[#managing-apps-with-git-repositories]
= Managing apps with Git repositories

When you deploy Kubernetes resources using an application, the resources are located in specific repositories. Learn how to deploy resources from Git repositories in the following procedure. Learn more about the application model at xref:../applications/app_model.adoc#application-model-and-definitions[Application model and definitions].

*User required access:* A user role that can create applications. You can only perform actions that your role is assigned. Learn about access requirements from the link:../access_control/rbac.adoc#role-based-access-control[Role-based access control] documentation. 

. From the console navigation menu, click *Applications* to see listed applications and to create new applications.

. *Optional:* After you choose the kind of application you want to create, you can select *YAML: On* to view the YAML in the console as you create and edit your application. See the YAML samples later in the topic.

. Choose *Git* from the list of repositories that you can use and enter the values in the correct fields. Follow the guidance in the console and see the YAML editor change values based on your input.

+
*Notes:* 
+
- If you select an existing Git repository path, you do not need to specify connection information if this is a private repository. The connection information is pre-set and you do not need to view these values. 

+
- If you enter a new Git repository path, you can optionally enter Git connection information if this is a private Git repository.

+
- Notice the reconcile option. The `merge` option is the default selection, which means that new fields are added and existing fields are updated in the resource. You can choose to `replace`. With the `replace` option, the existing resource is replaced with the Git source. When the subscription reconcile rate is set to `low`, it can take up to one hour for the subscribed application resources to reconcile. On the card on the single application view, click *Sync* to reconcile manually. If set to `off`, it never reconciles. 
 
. Set any optional pre-deployment and post-deployment tasks. Set the Ansible Tower secret if you have Ansible Tower jobs that you want to run before or after the subscription deploys the application resources. The Ansible Tower tasks that define Ansible jobs must be placed within `prehook` and `posthook` folders in this repository.
//check this?

. You can click *Add credential* if you need to add a credential using the console. Follow the directions in the console. See more information at link:../credentials/credential_intro.adoc#managing-credentials-overview[Managing credentials overview].

. Click *Create*.

. You are redirected to the _Overview_ page where you can view the details and topology.

[#gitops-pattern]
== GitOps pattern

Learn best practices for organizing a Git repository to manage clusters.

[#repo-git-ops]
===  GitOps example directory

Folders in this example are defined and named, with each folder containing applications or configurations that are run on managed clusters:

 - Root folder `managed-subscriptions`: Contains subscriptions that target the `common-managed` folder.
 - Subfolder `apps/`: Used to subscribe applications in the `common-managed` folder with placement to `managed-clusters`.
 - Subfolder `config/`: Used to subscribe configurations in the `common-managed` folder with placement to `managed-clusters`.
 - Subfolder `policies/`: Used to apply policies with placement to `managed-clusters`.
 - Folder `root-subscription/`: The initial subscription for the hub cluster that subscribes the `managed-subscriptions` folder.

See the example of a directory:

[source,yaml]
----
common-managed/             
    apps/
      app-name-0/
      app-name-1/
    config/
      config001/
      config002/

managed-subscriptions      
    apps/                  
    config/                
    policies/              

root-subscription/         
----

[#gitops-subscription-flow]
=== GitOps flow

Your directory structure is created for the following subscription flow: `root-subscription` > `managed-subscriptions` > `common-managed`.

. A single subscription in `root-subscription/` is applied from the CLI terminal to the hub cluster. 

. Subscriptions and policies are downloaded and applied to the hub cluster from the `managed-subscription` folder.

 - The subscriptions and policies in the `managed-subscription` folder then perform work on the managed clusters based on the placement. 
 - Placement determines which `managed-clusters` each subscription or policy affects.  
 - The subscriptions or policies define what is on the clusters that match their placement.
 
. Subscriptions apply content from the `common-managed` folder to `managed-clusters` that match the placement rules. This also applies common applications and configurations to all `managed-clusters` that match the placement rules.

[#more-examples]
=== More examples
//link doesn't work, check on this

* For an example of `root-subscription/`, see https://github.com/stolostron/application-samples/tree/main/subscriptions/subscribe-all[application-subscribe-all].

* For examples of subscriptions that point to other folders in the same repository, see https://github.com/stolostron/application-samples/tree/main/subscriptions[subscribe-all].

* See an example of the `common-managed` folder with application artifacts in the https://github.com/stolostron/application-samples/tree/main/subscriptions/nginx[nginx-apps] repository.

* See policy examples in https://github.com/stolostron/policy-collection[Policy collection].