:_mod-docs-content-type: PROCEDURE

[#using-certificates-secure-https-connection]
= Use custom CA certificates for a secure HTTPS connection

[role="_abstract"]
You can use this connection method to securely connect to a privately hosted Git server with TLS certificates that are signed by the custom CA certificates. By doing so, you create a secure HTTPS connection. 

To use custom CA certificates for a secure HTTPS connection, complete the following steps:

.Procedure

. Create a `ConfigMap` to contain the object storage server root and intermediate CA certificates in the privacy enhanced mail (PEM) format. 
. Use the following YAML as your connection method: 

+
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: obj-ca
  namespace: ch-object-dev <1> 
data:
  caCerts: |
  -----BEGIN CERTIFICATE-----
  ... <2>
  -----END CERTIFICATE-----   
----
<1> Create the `ConfigMap` in the same namespace as the channel resource. 
<2> Add your secret.

. Configure the channel resource with the `ConfigMap` by using the following YAML as your connection method:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: object-dev
  namespace: ch-object-dev
spec:
  type: ObjectBucket
  pathname: <ObjectBucket HTTPS URL>
  configMapRef:
    name: obj-ca <1> 
----
<1> Get this object name by creating the `ConfigMap` like you did in the earlier step.
