:_mod-docs-content-type: PROCEDURE

[#creating-aws-object-bucket]
= Creating your Amazon Web Services (AWS) S3 object storage bucket

[role="_abstract"]
You can set up subscriptions to subscribe resources that are defined in the Amazon Simple Storage Service (Amazon S3) object storage service. See the following procedure:
//I cannot check this, do we want to continue with this content even though the process in their product may change? If so, please check this?

.Procedure

. Log in to the link:https://s3.console.aws.amazon.com/[AWS console] with your AWS account, user name, and password.

. Navigate to *Amazon S3* > *Buckets* to the bucket home page.

. Click *Create Bucket* to create your bucket.

. Select the *AWS region*, which is essential for connecting your AWS S3 object bucket.

. Create the bucket access token.

. Navigate to your user name in the navigation bar, then from the drop-down menu, select *My Security Credentials*.

. Navigate to _Access keys for CLI, SDK, & API access_ in the _AWS IAM credentials_ tab and click on *Create access key*.

. Save your _Access key ID_ , _Secret access key_. 
 
. Upload your object YAML files to the bucket.
