[#reconcile-options]
= Adding reconcile options

You can use the `apps.open-cluster-management.io/reconcile-option` annotation in individual resources to override the subscription-level reconcile option. 

For example, if you add `apps.open-cluster-management.io/reconcile-option: replace` annotation in the subscription and add `apps.open-cluster-management.io/reconcile-option: merge` annotation in a resource YAML in the subscribed Git repository, the resource is merged on the target cluster while other resources are replaced.

[#reconcile-frequency-git]
== Reconcile frequency Git channel

You can select reconcile frequency options: `high`, `medium`, `low`, and `off` in channel configuration to avoid unnecessary resource reconciliations and therefore prevent overload on subscription operator.

*Required access:* Administrator and cluster administrator

See the following definitions of the `settings:attribute:<value>`:

- `Off`: The deployed resources are not automatically reconciled. A change in the `Subscription` custom resource initiates a reconciliation. You can add or update a label or annotation.
- `Low`: The deployed resources are automatically reconciled every hour, even if there is no change in the source Git repository.
- `Medium`: This is the default setting. The subscription operator compares the currently deployed commit ID to the latest commit ID of the source repository every 3 minutes, and applies changes to target clusters. Every 15 minutes, all resources are reapplied from the source Git repository to the target clusters, even if there is no change in the repository.
- `High`: The deployed resources are automatically reconciled every two minutes, even if there is no change in the source Git repository.

You can set this by using the `apps.open-cluster-management.io/reconcile-rate` annotation in the channel custom resource that is referenced by subscription. 

See the following `name: git-channel` example:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git-channel
  namespace: sample
  annotations:
    apps.open-cluster-management.io/reconcile-rate: <value from the list>
spec:
  type: GitHub
  pathname: <Git URL>
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-subscription
  annotations:
    apps.open-cluster-management.io/git-path: <application1>
    apps.open-cluster-management.io/git-branch: <branch1>
spec:
  channel: sample/git-channel
  placement:
    local: true
----

In the previous example, all subscriptions that use `sample/git-channel` are assigned `low` reconciliation frequency. 

.. When the subscription reconcile rate is set to `low`, it can take up to one hour for the subscribed application resources to reconcile. On the card on the single application view, click *Sync* to reconcile manually. If set to `off`, it never reconciles. 

Regardless of the `reconcile-rate` setting in the channel, a subscription can turn the auto-reconciliation `off` by specifying `apps.open-cluster-management.io/reconcile-rate: off` annotation in the `Subscription` custom resource. 

See the following `git-channel` example: 

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git-channel
  namespace: sample
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  type: GitHub
  pathname: <Git URL>
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-subscription
  annotations:
    apps.open-cluster-management.io/git-path: application1
    apps.open-cluster-management.io/git-branch: branch1
    apps.open-cluster-management.io/reconcile-rate: "off"
spec:
  channel: sample/git-channel
  placement:
    local: true
----

See that the resources deployed by `git-subscription` are never automatically reconciled even if the `reconcile-rate` is set to `high` in the channel.

[#reconcile-frequency-helm]
== Reconcile frequency Helm channel

Every 15 minutes, the subscription operator compares currently deployed hash of your Helm chart to the hash from the source repository. Changes are applied to target clusters. The frequency of resource reconciliation impacts the performance of other application deployments and updates. 

For example, if there are hundreds of application subscriptions and you want to reconcile all subscriptions more frequently, the response time of reconciliation is slower.

Depending on the Kubernetes resources of the application, appropriate reconciliation frequency can improve performance.

- `Off`: The deployed resources are not automatically reconciled. A change in the Subscription custom resource initiates a reconciliation. You can add or update a label or annotation.
- `Low`: The subscription operator compares currently deployed hash to the hash of the source repository every hour and apply changes to target clusters when there is change.
- `Medium`: This is the default setting. The subscription operator compares currently deployed hash to the hash of the source repository every 15 minutes and apply changes to target clusters when there is change.
- `High`: The subscription operator compares currently deployed hash to the hash of the source repository every 2 minutes and apply changes to target clusters when there is change.

You can set this using `apps.open-cluster-management.io/reconcile-rate` annotation in the `Channel` custom resource that is referenced by subscription. See the following `helm-channel` example:

See the following `helm-channel` example: 

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: helm-channel
  namespace: sample
  annotations:
    apps.open-cluster-management.io/reconcile-rate: low
spec:
  type: HelmRepo
  pathname: <Helm repo URL>
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: helm-subscription
spec:
  channel: sample/helm-channel
  name: nginx-ingress
  packageOverrides:
  - packageName: nginx-ingress
    packageAlias: nginx-ingress-simple
    packageOverrides:
    - path: spec
      value:
        defaultBackend:
          replicaCount: 3
  placement:
    local: true
----

In this example, all subscriptions that uses `sample/helm-channel` are assigned a `low` reconciliation frequency. 

Regardless of the reconcile-rate setting in the channel, a subscription can turn the auto-reconciliation `off` by specifying `apps.open-cluster-management.io/reconcile-rate: off` annotation in the `Subscription` custom resource, as displayed in the following example:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: helm-channel
  namespace: sample
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  type: HelmRepo
  pathname: <Helm repo URL>
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: helm-subscription
  annotations:
    apps.open-cluster-management.io/reconcile-rate: "off"
spec:
  channel: sample/helm-channel
  name: nginx-ingress
  packageOverrides:
  - packageName: nginx-ingress
    packageAlias: nginx-ingress-simple
    packageOverrides:
    - path: spec
      value:
        defaultBackend:
          replicaCount: 3
  placement:
    local: true
----

In this example, the resources deployed by `helm-subscription` are never automatically reconciled, even if the `reconcile-rate` is set to `high` in the channel.