:_mod-docs-content-type: REFERENCE

[#application-level]
= SubscriptionReport application-level

[role="_abstract"]
*Deprecation:* Application _subscription_, and all processes that use Application subscription, is deprecated. See link:../gitops/gitops_overview.adoc#gitops-overview[GitOps overview] for updated function.

One application-level `subscriptionReport` for each application is located in `<namespace:<your-appsub-namespace>` in `appsub` namespace on the hub cluster and contains the following information:

- The overall status of the application for each managed cluster
- A list of all resources for the application
- A report summary with the total number of total clusters 
- A report summary with the total number of clusters where the application is in the status: `deployed`, `failed`, `propagationFailed`, and `inProgress`. 
 
*Note:* The `inProcess` status is the total minus `deployed`, minus `failed `, and minus `propagationFailed`.

See the following `SubscriptionReport` sample YAML file:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1alpha1
kind: subscriptionReport
metadata:
  labels:
    apps.open-cluster-management.io/hosting-subscription: <your-appsub-namespace>.<your-appsub-name>
  name: <your-appsub-name>
  namespace: <your-appsub-namespace>
reportType: Application
resources:
- apiVersion: v1
  kind: Service
  name: redis-master2
  namespace: playback-ns-2
- apiVersion: apps/v1
  kind: Deployment
  name: redis-master2
  namespace: playback-ns-2
- apiVersion: v1
  kind: Service
  name: redis-slave2
  namespace: playback-ns-2
- apiVersion: apps/v1
  kind: Deployment
  name: redis-slave2
  namespace: playback-ns-2
- apiVersion: v1
  kind: Service
  name: frontend2
  namespace: playback-ns-2
- apiVersion: apps/v1
  kind: Deployment
  name: frontend2
  namespace: playback-ns-2
results:
- result: deployed
  source: cluster-1                            //cluster 1 status
  timestamp:
    nanos: 0
    seconds: 0
- result: failed
  source: cluster-3                            //cluster 2 status
  timestamp:
    nanos: 0
    seconds: 0
- result: propagationFailed
  source: cluster-4                            //cluster 3 status
  timestamp:
    nanos: 0
    seconds: 0
summary:
  deployed: 8
  failed: 1
  inProgress: 0
  propagationFailed: 1
  clusters: 10
----
