:_mod-docs-content-type: PROCEDURE

[#cli-last-update]
= CLI Last Update Time

[role="_abstract"]
You can also get the Last Update Time of an AppSub on a given managed cluster when it is not practical to log in to each managed cluster to retrieve this information. Thus, an utility script was created to simplify the retrieval of the Last Update Time of an AppSub on a managed cluster. This script is designed to run on the Hub cluster. It creates a managedClusterView resource to get the AppSub from the managed cluster, and parses the data to get the Last Update Time.

.Procedure

. Download the CLI from link:https://github.com/open-cluster-management-io/multicloud-operators-subscription/blob/main/cmd/scripts/getLastUpdateTime.sh[multicloud-operators-subscription].

. Run the following command to retriev the `Last Update Time` of an `AppSub` on a managed cluster. This script is designed to run on the hub cluster. It creates a `managedClusterView` resource to get the AppSub from the managed cluster, and parses the data to get the Last Update Time:
+
[source,bash]
----
% getLastUpdateTime.sh -c <your-managed-cluster> -s <your-appsub-namespace> -n <your-appsub-name>
----
