:_mod-docs-content-type: PROCEDURE

[#same-namespace]
= Application to same namespace

[role="_abstract"]
*Deprecation:* Application _subscription_, and all processes that use Application subscription, is deprecated. See link:../gitops/gitops_overview.adoc#gitops-overview[GitOps overview] for updated function.

As a subscription administrator, you might want to deploy all application resources into the same namespace. 

You can deploy all application resources into the subscription namespace by xref:../applications/allow_deny.adoc#creating-allow-deny-list[Create an allow and deny list as subscription administrator].

.Procedure

* Add the `apps.open-cluster-management.io/current-namespace-scoped: true` annotation to the subscription YAML. For example, when a subscription administrator creates the following subscription, all three ConfigMaps in the previous example are created in `subscription-ns` namespace.
+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: subscription-example
  namespace: subscription-ns
  annotations:
    apps.open-cluster-management.io/git-path: sample-resources
    apps.open-cluster-management.io/reconcile-option: merge
    apps.open-cluster-management.io/current-namespace-scoped: "true"
spec:
  channel: channel-ns/somechannel
  placement:
    placementRef:
      name: dev-clusters
----
