:_mod-docs-content-type: PROCEDURE

[#subscribing-specific-tag]
= Subscribing to a specific tag

[role="_abstract"]
The subscription operator that is included in the `multicloud-operators-subscription` repository subscribes to the latest commit of specified branch of a Git repository by default. If you want to subscribe to a specific tag, you need to specify the tag annotation in the subscription.

.Procedure

* Specify the tag annotation in the subscription.
+
The following example, the YAML file displays how to specify a different tag with `apps.open-cluster-management.io/git-tag: <v1.0>`:
+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-mongodb-subscription
  annotations:
    apps.open-cluster-management.io/git-path: stable/ibm-mongodb-dev
    apps.open-cluster-management.io/git-tag: <v1.0>
    apps.open-cluster-management.io/git-clone-depth: 100
----
+
*Note:* If both Git desired commit and tag annotations are specified, the tag is ignored.
+
The `git-clone-depth` annotation is optional and set to `20` by default, which means the subscription controller retrieves the previous `20` commit history from the Git repository. If you specify much older `git-tag`, you need to specify `git-clone-depth` accordingly for the desired commit of the tag.
