:_mod-docs-content-type: REFERENCE

[#resource-overwrite-example]
= Resource overwrite example

[role="_abstract"]
*Applicable channel types:* Git, ObjectBucket (Object storage in the console)

*Note:* The resource overwrite option is not applicable to `helm` charts from the Git repository because the `helm` chart resources are managed by Helm.

In this example, the following ConfigMap already exists in the target cluster. 

[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-1
  namespace: sub-ns
data:
  name: user1
  age: 19
----

Subscribe the following sample resource YAML file from a Git repository and replace the existing ConfigMap. See the change in the `data` specification:

[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-1
  namespace: sub-ns
data:
  age: 20
----

.Additional resources

* xref:../applications/subscribe_git_merge.adoc#default-merge-option[Default merge option]
* xref:../applications/subscribe_git_mergeandown.adoc#mergeandown-option[mergeAndOwn option]
* xref:../applications/subscribe_git_replace.adoc#replace-option[Replace option]
