:_mod-docs-content-type: PROCEDURE

[#mce-manage-rbac]
= Managing cluster lifecycle RBAC for {mce-short}

[role="_abstract"]
Validate RBAC at the console level and at the API level. Enable or disable actions in the console based on user access role permissions.

.Procedure

View the following cluster lifecycle RBAC operations:

. Create and administer cluster role bindings for all managed clusters. For example, create a cluster role binding to the cluster role `open-cluster-management:cluster-manager-admin`.

+
This role is a super user, which has access to all resources and actions. You can create cluster-scoped `managedcluster` resources, the namespace for the resources that manage the managed cluster, and the resources in the namespace with this role. You might need to add the `username` of the ID that requires the role association to avoid permission errors. Run the following command:

+
[source,bash]
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:cluster-manager-admin --user=<username>
----

. Run the following command to administer a cluster role binding for a managed cluster named `cluster-name`. This role has read and write access to the cluster-scoped `managedcluster` resource. This is needed because the `managedcluster` is a cluster-scoped resource and not a namespace-scoped resource:

+
[source,bash]
----
oc create clusterrolebinding (role-binding-name) --clusterrole=open-cluster-management:admin:<cluster-name> --user=<username>
----

. Create a namespace role binding to the cluster role `admin` by entering the following command:

+
[source,bash]
----
oc create rolebinding <role-binding-name> -n <cluster-name> --clusterrole=admin --user=<username>
----
//+
//This role has read and write access to the resources in the namespace of the managed cluster.


. Create a cluster role binding for the `open-cluster-management:view:<cluster-name>` cluster role to view a managed cluster named `cluster-name` Enter the following command:

+
[source,bash]
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:view:<cluster-name> --user=<username>
----
//+
//This role has read access to the cluster-scoped `managedcluster` resource. This is needed because the `managedcluster` is a cluster-scoped resource.


. Create a namespace role binding to the cluster role `view` by entering the following command:

+
[source,bash]
----
oc create rolebinding <role-binding-name> -n <cluster-name> --clusterrole=view --user=<username>
----
//+
//This role has read-only access to the resources in the namespace of the managed cluster.

. View a list of the managed clusters that you can access by entering the following command:

+
[source,bash]
----
oc get managedclusters.clusterview.open-cluster-management.io
----
//+
//This command is used by administrators and users without cluster administrator privileges.

. View a list of the managed cluster sets that you can access by entering the following command:

+
[source,bash]
----
oc get managedclustersets.clusterview.open-cluster-management.io
----
//+
//This command is used by administrators and users without cluster administrator privileges.

. As a cluster administrator, use cluster pool provision clusters by creating a managed cluster set and grant administrator permission to roles by adding the role to the group. View the following examples:

+
- Grant `admin` permission to the `server-foundation-clusterset` managed cluster set with the following command:

+
[source,bash]
----
oc adm policy add-cluster-role-to-group open-cluster-management:clusterset-admin:server-foundation-clusterset 
server-foundation-team-admin
----

- Grant `view` permission to the `server-foundation-clusterset` managed cluster set with the following command:

+
[source,bash]
----
oc adm policy add-cluster-role-to-group open-cluster-management:clusterset-view:server-foundation-clusterset server-foundation-team-user
----

. Create a namespace for the cluster pool, `server-foundation-clusterpool`. View the following examples to grant role permissions:

+
- Grant `admin` permission to `server-foundation-clusterpool` for the `server-foundation-team-admin` by running the following commands:

+
[source,bash]
----
oc adm new-project server-foundation-clusterpool

oc adm policy add-role-to-group admin server-foundation-team-admin --namespace  server-foundation-clusterpool
----

. As a team administrator, create a cluster pool named `ocp46-aws-clusterpool` with a cluster set label, `cluster.open-cluster-management.io/clusterset=server-foundation-clusterset` in the cluster pool namespace:

+
- The `server-foundation-webhook` checks if the cluster pool has the cluster set label, and if the user has permission to create cluster pools in the cluster set.

- The `server-foundation-controller` grants `view` permission to the `server-foundation-clusterpool` namespace for `server-foundation-team-user`.

. When a cluster pool is created, the cluster pool creates a `clusterdeployment`. Continue reading for more details:
+
- The `server-foundation-controller` grants `admin` permission to the `clusterdeployment` namespace for `server-foundation-team-admin`.

- The `server-foundation-controller` grants `view` permission `clusterdeployment` namespace for `server-foundation-team-user`.
+
*Note:* As a `team-admin` and `team-user`, you have `admin` permission to the `clusterpool`, `clusterdeployment`, and `clusterclaim`.

.Additional resources

To learn more about each role, see xref:../clusters/about/mce_role_descriptions.adoc#mce-role-definitions[Overview of {mce} roles].