:_mod-docs-content-type: REFERENCE

[#sync-release-images]
= Synchronize available release images

[role="_abstract"]
If you have a {acm-short} hub cluster, which uses the `MultiClusterHub` operator to manage, upgrade, and install hub cluster components, you can synchronize the list of release images to ensure that you can select the latest available versions.

Release images are available in the link:https://github.com/stolostron/acm-hive-openshift-releases/tree/backplane-2.10[acm-hive-openshift-releases] repository and are updated frequently. 

There are three levels of stability of the release images. See the following table:

.Table of release images stability levels
|===
|Category |Description

|candidate
|The most current images, which are not tested and might have some bugs. 
|fast
|Images that are partially tested, but likely less stable than a stable version.
|stable
|These fully-tested images are confirmed to install and build clusters correctly.
|===

.Additional resources

* xref:../release_images/refresh_release_images.adoc#refresh-release-images[Refresh the release images list]
