[#advanced-config-engine]
= Advanced configuration 

The {mce-short} is installed using an operator that deploys all of the required components. The {mce-short} can be further configured during or after installation by adding one or more of the following attributes to the `MultiClusterEngine` custom resource:

[#local-cluster]
== Local-cluster enablement

By default, the cluster that is running {mce-short} manages itself. To install {mce-short} without the cluster managing itself, specify the following values in the `spec.overrides.components` settings in the `MultiClusterEngine` section:

[source,yaml]
----
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec: 
  overrides:
    components:
    - name: local-cluster
      enabled: false
----

* The `name` value identifies the hub cluster as a `local-cluster`.
* The `enabled` setting specifies whether the feature is enabled or disabled. When the value is `true`, the hub cluster manages itself. When the value is `false`, the hub cluster does not manage itself.

A hub cluster that is managed by itself is designated as the `local-cluster` in the list of clusters. 

[#custom-image-pull-secret]
== Custom image pull secret

If you plan to import Kubernetes clusters that were not created by {ocp-short} or the {mce-short}, generate a secret that contains your {ocp-short} pull secret information to access the entitled content from the distribution registry. 

The secret requirements for {ocp-short} clusters are automatically resolved by {ocp-short} and {mce}, so you do not have to create the secret if you are not importing other types of Kubernetes clusters to be managed.

*Important:* These secrets are namespace-specific, so make sure that you are in the namespace that you use for your engine.

 . Download your {ocp-short} pull secret file from link:https://cloud.redhat.com/openshift/install/pull-secret[cloud.redhat.com/openshift/install/pull-secret] by selecting *Download pull secret*. Your {ocp-short} pull secret is associated with your Red Hat Customer Portal ID, and is the same across all Kubernetes providers.

 . Run the following command to create your secret:
+
----
oc create secret generic <secret> -n <namespace> --from-file=.dockerconfigjson=<path-to-pull-secret> --type=kubernetes.io/dockerconfigjson
----
+
- Replace `secret` with the name of the secret that you want to create.
- Replace `namespace` with your project namespace, as the secrets are namespace-specific.
- Replace `path-to-pull-secret` with the path to your {ocp-short} pull secret that you downloaded.

The following example displays the `spec.imagePullSecret` template to use if you want to use a custom pull secret. Replace `secret` with the name of your pull secret:

[source,yaml]
----
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  imagePullSecret: <secret>
----

[#target-namespace]
== Target namespace

The operands can be installed in a designated namespace by specifying a location in the `MultiClusterEngine` custom resource. This namespace is created upon application of the `MultiClusterEngine` custom resource.

*Important:* If no target namespace is specified, the operator will install to the `multicluster-engine` namespace and will set it in the `MultiClusterEngine` custom resource specification.

The following example displays the `spec.targetNamespace` template that you can use to specify a target namespace. Replace `target` with the name of your destination namespace. *Note:* The `target` namespace cannot be the `default` namespace:

[source,yaml]
----
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  targetNamespace: <target>
----

[#availability-config]
== availabilityConfig

The hub cluster has two availabilities: `High` and `Basic`. By default, the hub cluster has an availability of `High`, which gives hub cluster components a `replicaCount` of `2`. This provides better support in cases of failover but consumes more resources than the `Basic` availability, which gives components a `replicaCount` of `1`.

*Important:* Set `spec.availabilityConfig` to `Basic` if you are using {mce-short} on a {sno} cluster.

The following examples shows the `spec.availabilityConfig` template with `Basic` availability:

[source,yaml]
----
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  availabilityConfig: "Basic"
----

[#node-selector]
== nodeSelector

You can define a set of node selectors in the `MultiClusterEngine` to install to specific nodes on your cluster. The following example shows `spec.nodeSelector` to assign pods to nodes with the label `node-role.kubernetes.io/infra`:

[source,yaml]
----
spec:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
----

[#tolerations]
== tolerations

You can define a list of tolerations to allow the `MultiClusterEngine` to tolerate specific taints defined on the cluster. The following example shows a `spec.tolerations` that matches a `node-role.kubernetes.io/infra` taint:

[source,yaml]
----
spec:
  tolerations:
  - key: node-role.kubernetes.io/infra
    effect: NoSchedule
    operator: Exists
----

The previous infra-node toleration is set on pods by default without specifying any tolerations in the configuration. Customizing tolerations in the configuration will replace this default behavior.

[#serviceaccount-addon-intro]
== ManagedServiceAccount add-on

By default, the `Managed-ServiceAccount` add-on is disabled. This component when enabled allows you to create or delete a service account on a managed cluster. To install with this add-on enabled, include the following in the `MultiClusterEngine` specification in `spec.overrides`:

[source,yaml]
----
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  overrides:
    components:
    - name: managedserviceaccount
      enabled: true
----

The `ManagedServiceAccount` add-on can be enabled after creating `MultiClusterEngine` by editing the resource on the command line and setting the `managedserviceaccount` component to `enabled: true`. Alternatively, you can run the following command and replace <multiclusterengine-name> with the name of your `MultiClusterEngine` resource.

----
oc patch MultiClusterEngine <multiclusterengine-name> --type=json -p='[{"op": "add", "path": "/spec/overrides/components/-","value":{"name":"managedserviceaccount","enabled":true}}]'
----
