[#config-infra-node-mce]
= Configuring infrastructure nodes for {mce-short}

Configure your {ocp-short} cluster to contain infrastructure nodes to run approved {mce-short} management components. Running components on infrastructure nodes avoids allocating {ocp-short} subscription quota for the nodes that are running {mce-short} management components.

After adding infrastructure nodes to your {ocp-short} cluster, follow the xref:./install_connected.adoc#installing-from-the-cli-mce[Installing from the {ocp-short} CLI] instructions and add the following configurations to the Operator Lifecycle Manager Subscription and `MultiClusterEngine` custom resource.

[#config-infra-nodes-ocp]
== Configuring infrastructure nodes to the {ocp-short} cluster

Follow the procedures that are described in link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/machine_management/creating-infrastructure-machinesets[Creating infrastructure machine sets] in the {ocp-short} documentation. Infrastructure nodes are configured with a Kubernetes `taints` and `labels` to keep non-management workloads from running on them.

For compatibility with the infrastructure node enablement, which is provided by {mce-short}, ensure your infrastructure nodes have the following `taints` and `labels` applied:

[source,yaml]
----
metadata:
  labels:
    node-role.kubernetes.io/infra: ""
spec:
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
----

[#infra-olm-subscription]
== Operator Lifecycle Manager subscription configuration

Configure your Operator Lifecycle Manager subscription/

. Add the following additional configuration before applying the Operator Lifecycle Manager Subscription:

+
[source,yaml]
----
spec:
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - key: node-role.kubernetes.io/infra
      effect: NoSchedule
      operator: Exists
----

. Update any add-ons to include the following node selectors and tolerations. You need to use the instructions xref:../add-ons/configure_klusterlet_addons.adoc#configure-klusterlet-addons[Configuring klusterlet add-ons]:

+
[source,yaml]
----
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - key: node-role.kubernetes.io/infra
      effect: NoSchedule
      operator: Exists
----

. If you used Red Hat OpenShift Data Foundation as a storage provisioner, make sure _Container Storage Interface_ pods can run on infrastructure nodes. Learn more at link:https://docs.redhat.com/it/documentation/red_hat_openshift_data_foundation/4.17/html/managing_and_allocating_storage_resources/managing-container-storage-interface-component-placements_rhodf#managing-container-storage-interface-component-placements_rhodf[Managing container storage interface (CSI) component placements] in the Red Hat OpenShift Data Foundation documentation.

[#infra-mce-add-config]
== MultiClusterEngine custom resource additional configuration

Add the following additional configuration before applying the `MultiClusterEngine` custom resource:

[source,yaml]
----
spec:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
----
