:_mod-docs-content-type: PROCEDURE

[#deploy-update-service]
= Deploying the {update-service} operator 

[role="_abstract"]
Deploy the {update-service} operator on your hub cluster to manage upgrades for disconnected clusters.

.Procedure

. Deploy the operator.

.. In the hub cluster, access the {ocp-catalog}
.. Select the **{update-service} Operator**. Update the default values if needed. The deployment of the operator creates a new project named `openshift-update-service`.
.. Deploy the operator. This creates the `openshift-update-service` project.
.. Verify that the operator pods are in the `running` state: `oc get pods -n openshift-update-service`.


. Deploy the {update-service} instance.

.. In the {ocp-short} console, navigate to **Installed Operators** > **{update-service} Operator**.
.. Select **Create Instance**.
.. Define the instance using your local registry details:

+
[source,yaml]
----
apiVersion: update-service.openshift.io/v1beta2
kind: update-service
metadata:
  name: openshift-cincinnati-instance
  namespace: openshift-update-service
spec:
  registry: <registry-host-name>:<port>
  replicas: 1
  repository: ${LOCAL_REGISTRY}/ocp4/release
  graphDataImage: '<host-name>:<port>/cincinnati-graph-data-container'
----

.. Select **Create** and verify the status with `oc get pods`.

.Next steps

When the {update-service} is running, you can apply policies to managed clusters to point to the local registry and update servic