:_mod-docs-content-type: PROCEDURE

[#deploy-policy-change-registry]
= Optional: Deploying a policy to change the default registry

[role="_abstract"]
{ocp-short} has a default image registry value that specifies where it finds the upgrade packages. In a disconnected environment, you can create a policy to replace that value with the path to your local image registry where you mirrored your release images. 

.Procedure 

The following steps only apply if you have mirrored your releases into your mirrored registry:

*Deprecated:* `PlacementRule`

. Log in to the {ocp-short} environment of your hub cluster.

. From the console, select *Governance* > *Create policy*.

. Set the *YAML* switch to _On_ to view the YAML version of the policy.

. Delete all of the content in the YAML code. 

. Paste the following YAML content into the window to create a custom `Policy` resource with a `ConfigurationPolicy` template and a `PlacementBinding` resource:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-mirror
  namespace: default
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition: 
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-image-content-source-policy
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1alpha1
                kind: ImageContentSourcePolicy
                metadata:
                  name: <your-local-mirror-name>
                spec:
                  repositoryDigestMirrors:
                    - mirrors:
                        - <your-registry>
                      source: registry.redhat.io
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-mirror
  namespace: default
placementRef:
  name: placement-policy-mirror
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-mirror
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-mirror
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      []  
----
+
* Replace `<your-local-mirror-name>` with your local mirror name.
* Replace `<your-registry>` with the path to your local mirror repository. You can find the path to your local mirror by running the `oc adm release mirror` command.
* `matchExpressions` selects all clusters if you do not specify any expressions.

. Select *Enforce if supported*.

. Select *Create* to create the policy. 

.Next steps

You can continue to xref:../install_upgrade/deploy_policy_change_location.adoc#deploy-policy-change-location[Optional: Deploying a policy to change the managed cluster location], or go to xref:../install_upgrade/upgrade_clusters_disconnected.adoc#upgrade-clusters-disconnected[Upgrading clusters in a disconnected environment] to view, select, and upgrade your cluster.

Return to xref:../install_upgrade/upgrade_cluster_overview.adoc#upgrade-clusters-mce-overview[Upgrading disconnected clusters by using policies] for an overview.