:_mod-docs-content-type: PROCEDURE

[#deploy-update-service-operator]
= Deploying the {update-service} operator 

[role="_abstract"]
Deploy the {update-service} operator on your hub cluster to manage upgrades for disconnected clusters.

.Procedure

See the following process to deploy the operator:

. In the hub cluster, access the {ocp-catalog}
. Select the **{update-service} Operator**. Update the default values if needed. The deployment of the operator creates a new project named `openshift-update-service`.
. Deploy the operator. This creates the `openshift-update-service` project.
. Verify that the operator pods are in the `running` state: `oc get pods -n openshift-update-service`.

.Next steps

When the {update-service} is running, proceed to xref:../install_upgrade/build_graph_init_update_service.adoc#build-graph-init[Building the graph data init container], which pulls the graph data information for available upgrades.

.Additional resources

Return to xref:../install_upgrade/upgrade_cluster_overview.adoc#upgrade-clusters-mce-overview[Upgrading disconnected clusters by using policies] for an overview.