:_mod-docs-content-type: PROCEDURE

[#deploy-policy-override-registry]
= Optional: Deploying a policy to override the default registry

[role="_abstract"]
The following steps only apply if you have mirrored your releases into your mirrored registry.

*Deprecated:* `PlacementRule`

{ocp-short} has a default image registry value that specifies where it finds the upgrade packages. In a disconnected environment, you can create a policy to replace that value with the path to your local image registry where you mirrored your release images. 

Complete the following steps to create the policy:

. Log in to the {ocp-short} environment of your hub cluster.

. From the console, select *Governance* > *Create policy*.

. Set the *YAML* switch to _On_ to view the YAML version of the policy.

. Delete all of the content in the YAML code. 

. Paste the following YAML content into the window to create a custom policy:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-mirror
  namespace: default
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition: 
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-image-content-source-policy
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1alpha1
                kind: ImageContentSourcePolicy
                metadata:
                  name: <your-local-mirror-name> <1>
                spec:
                  repositoryDigestMirrors:
                    - mirrors:
                        - <your-registry> <2>
                      source: registry.redhat.io
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-mirror
  namespace: default
placementRef:
  name: placement-policy-mirror
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-mirror
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-mirror
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      []  <3>
----
+
<1> Replace with your local mirror name.
<2> Replace with the path to your local mirror repository. You can find the path to your local mirror by running the `oc adm release mirror` command.
<3> Selects all clusters if not specified.

. Select *Enforce if supported*.

. Select *Create* to create the policy. 

[#deploy-policy-disconnect-catalog]
== Deploying a policy to deploy a disconnected catalog source

You can push the _Catalogsource_ policy to the managed cluster to change the default location from a connected location to your disconnected local registry.

Complete the following steps to change the default location:

. In the console menu, select *Governance* > *Create policy*.

. Set the `YAML` switch to _On_ to view the YAML version of the policy.

. Delete all of the content in the `YAML` code. 

. Paste the following `YAML` content into the window to create a custom policy:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-catalog
  namespace: default
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-catalog
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OperatorHub
                metadata:
                  name: cluster
                spec:
                  disableAllDefaultSources: true
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: CatalogSource
                metadata:
                  name: my-operator-catalog
                  namespace: openshift-marketplace
                spec:
                  sourceType: grpc
                  image: '<registry_host_name>:<port>/olm/redhat-operators:v1' <1>
                  displayName: My Operator Catalog
                  publisher: grpc
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-catalog
  namespace: default
placementRef:
  name: placement-policy-catalog
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-catalog
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-catalog
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      []  <2>
----
+
<1> Replace with the path to your local restricted catalog source image.
<2> Selects all clusters if not specified.

. Select *Enforce if supported*.

. Select *Create* to create the policy.

[#deploy-policy-cluster-parameter]
== Deploying a policy to change the managed cluster parameter

You can push the _ClusterVersion_ policy to the managed cluster to change the default location where it retrieves its upgrades.

Complete the following steps:

. From the managed cluster, confirm that the _ClusterVersion_ upstream parameter is currently the default public {update-service} operand by running the following command:

+
[source,bash]
----
oc get clusterversion -o yaml
----

. From the hub cluster, identify the route URL to the {update-service} operand by running the following command:

+
[source,bash]
----
oc get routes
----
+
Remember the result for later.

. In the hub cluster console menu, select *Governance* > *Create a policy*.

. Set the `YAML` switch to _On_ to view the YAML version of the policy.

. Delete all of the content in the `YAML` code. 

. Paste the following `YAML` content into the window to create a custom policy:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cluster-version
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: null
    policy.open-cluster-management.io/categories: null
    policy.open-cluster-management.io/controls: null
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-cluster-version
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterVersion
                metadata:
                  name: version
                spec:
                  channel: stable-4.4
                  upstream: >-
                    https://example-cincinnati-policy-engine-uri/api/upgrades_info/v1/graph <1>

---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-cluster-version
  namespace: default
placementRef:
  name: placement-policy-cluster-version
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-cluster-version
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-cluster-version
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      []
----
+
<1> Replace with the path to your hub cluster {update-service} operand.
Selects all clusters if not specified.
+
You can complete the following steps to determine the path to the operand:
+
.. Run the `oc get get routes -A` command on the hub cluster.
.. Find the route to `update-service`.
+
The path to the operand is the value in the `HOST/PORT` field.

. Select *Enforce if supported*. 

. Select *Create* to create the policy.

. In the managed cluster CLI, confirm that the upstream parameter in the `ClusterVersion` is updated with the local hub cluster {update-service} URL by running the following command:

+
[source,bash]
----
oc get clusterversion -o yaml
----

. Verify that the results resemble the following content:

+
[source,yaml]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
[..]
  spec:
    channel: stable-4.4
    upstream: https://<hub-cincinnati-uri>/api/upgrades_info/v1/graph
----