[#mce-install-intro]
= Installing and upgrading {mce-short}

The {mce-short} is a software operator that enhances cluster fleet management. The {mce-short} supports{ocp} and Kubernetes cluster lifecycle management across clouds and data centers. 

Access the _Support Matrix_ from the link:https://access.redhat.com/products/red-hat-advanced-cluster-management-for-kubernetes/[Red Hat Advanced Cluster Management for Kubernetes product information page] to learn about hub cluster and managed cluster requirements and support.

*Important:* You must install {mce-short} on a cluster that does not have {product-title} earlier than 2.5 installed. If you are using {product-title-short} version 2.5 or later, then multicluster engine for Kubernetes is already installed on the cluster with it.
//I don't think we need this?

See important information about supported browsers and features in the link:https://access.redhat.com/articles/7006302[The multicluster engine for Kubernetes operator 2.3 support matrix].

See the following documentation:

* xref:./install_connected.adoc#installing-while-connected-online-mce[Installing while connected online]
* xref:./install_disconnected.adoc#install-on-disconnected-networks[Installing on disconnected networks]
* xref:./upgrade_cluster.adoc#upgrading-your-cluster[Upgrading your cluster]
* xref:./uninstall.adoc#uninstalling-mce[Uninstalling]
* xref:./adv_config_install.adoc#advanced-config-engine[MultiClusterEngine advanced configuration]
