[#install-on-disconnected-networks]
= Install on disconnected networks

You might need to install the {mce-short} on {ocp} clusters that are not connected to the Internet. The procedure to install on a disconnected engine requires some of the same steps as the connected installation.

*Important:* You must install {mce-short} on a cluster that does not have Red Hat Advanced Cluster Management for Kubernetes earlier than 2.5 installed. The {mce-short} cannot co-exist with Red Hat Advanced Cluster Management for Kubernetes on versions earlier than 2.5 because they provide some of the same management components. It is recommended that you install {mce-short} on a cluster that has never previously installed Red Hat Advanced Cluster Management. If you are using Red Hat Advanced Cluster Management for Kubernetes at version 2.5.0 or later then {mce-short} is already installed on the cluster with it.

You must download copies of the packages to access them during the installation, rather than accessing them directly from the network during the installation.

* <<disconnect-prerequisites,Prerequisites>>
* <<confirm-ocp-installation-2,Confirm your {ocp-short} installation>>
* <<installing-in-a-disconnected-environment,Installing in a disconnected environment>>

[#disconnect-prerequisites]
== Prerequisites 

You must meet the following requirements before you install The {mce-short}:

* {ocp} version 4.12 or later must be deployed in your environment, and you must be logged in with the command line interface (CLI). 

* You need access to link:https://catalog.redhat.com/software/containers/search?p=1&application_categories_list=Container%20Platform%20%2F%20Management[catalog.redhat.com].
+
*Note:* For managing bare metal clusters, you must have {ocp-short} version 4.12 or later.
+
See the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/index[{ocp-short} version 4.12].

* Your {ocp} CLI must be version 4.12 or later, and configured to run `oc` commands.
* Your {ocp} permissions must allow you to create a namespace.
* You must have a workstation with Internet connection to download the dependencies for the operator.

[#confirm-ocp-installation-2]
== Confirm your {ocp-short} installation

* You must have a supported {ocp-short} version, including the registry and storage services, installed and working in your cluster. For information about {ocp-short} version 4.12, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/[{ocp-short} documentation].

* When and if you are connected, you can ensure that the {ocp-short} cluster is set up correctly by accessing the {ocp-short} web console with the following command:

+
----
kubectl -n openshift-console get route console
----
+
See the following example output:
+
----
console console-openshift-console.apps.new-coral.purple-chesterfield.com               
console   https   reencrypt/Redirect     None
----

+
The console URL in this example is: `https:// console-openshift-console.apps.new-coral.purple-chesterfield.com`.
Open the URL in your browser and check the result.

+
If the console URL displays `console-openshift-console.router.default.svc.cluster.local`, set the value for `openshift_master_default_subdomain` when you install {ocp-short}.

[#installing-in-a-disconnected-environment]
== Installing in a disconnected environment

*Important:* You need to download the required images to a mirroring registry to install the operators in a disconnected environment. Without the download, you might receive `ImagePullBackOff` errors during your deployment.

Follow these steps to install the {mce-short} in a disconnected environment:

. Create a mirror registry. If you do not already have a mirror registry, create one by completing the procedure in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/disconnected-installation-mirroring[Disconnected installation mirroring] topic of the Red Hat {ocp-short} documentation.

+
If you already have a mirror registry, you can configure and use your existing one.

. *Note:* For bare metal only, you need to provide the certificate information for the disconnected registry in your `install-config.yaml` file. To access the image in a protected disconnected registry, you must provide the certificate information so the {mce-short} can access the registry.

.. Copy the certificate information from the registry.
.. Open the `install-config.yaml` file in an editor.
.. Find the entry for `additionalTrustBundle: |`.
.. Add the certificate information after the `additionalTrustBundle` line. The resulting content should look similar to the following example:

+
[source,yaml]
----
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  certificate_content
  -----END CERTIFICATE-----
sshKey: >-
----

+ 
. *Important:* Additional mirrors for disconnected image registries are needed if the following Governance policies are required:

- Container Security Operator policy: Locate the images in the `registry.redhat.io/quay` source.

- Compliance Operator policy: Locate the images in the `registry.redhat.io/compliance` source.

- Gatekeeper Operator policy: Locate the images in the `registry.redhat.io/gatekeeper` source.
+
See the following example of mirrors lists for all three operators:

+
[source,yaml]
----
    - mirrors:
      - <your_registry>/rhacm2
      source: registry.redhat.io/rhacm2
    - mirrors:
      - <your_registry>/quay
      source: registry.redhat.io/quay
    - mirrors:
      - <your_registry>/compliance
      source: registry.redhat.io/compliance
----

. Save the `install-config.yaml` file.

. Create a YAML file that contains the `ImageContentSourcePolicy` with the name `mce-policy.yaml`. *Note:* If you modify this on a running cluster, it causes a rolling restart of all nodes.
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: mce-repo
spec:
  repositoryDigestMirrors:
  - mirrors:
    - mirror.registry.com:5000/multicluster-engine
    source: registry.redhat.io/multicluster-engine
----

. Apply the ImageContentSourcePolicy file by entering the following command:
+
----
oc apply -f mce-policy.yaml
----

. Enable the disconnected Operator Lifecycle Manager Red Hat Operators and Community Operators.
+
the {mce-short} is included in the Operator Lifecycle Manager Red Hat Operator catalog.

. Configure the disconnected Operator Lifecycle Manager for the Red Hat Operator catalog. Follow the steps in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/operators/administrator-tasks#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks] topic of the{ocp} documentation.

. Now that you have the image in the disconnected Operator Lifecycle Manager, continue to install the {mce-short} for Kubernetes from the  Operator Lifecycle Manager catalog.

See xref:./install_connected.adoc#installing-while-connected-online-mce[Installing while connected online] for the required steps.
