:_mod-docs-content-type: PROCEDURE

[#preparing-to-install-mce]
= Preparing to install {mce-short}

[role="_abstract"]
The {mce-short} is installed with {olm}, which manages the installation, upgrade, and removal of the components that encompass the {mce-short}. Learn how to prepare for installation.

*Required access:* Cluster administrator

*Important:* 

- You cannot install {mce-short} on a cluster that has a `ManagedCluster` resource configured in an external cluster. You must remove the `ManagedCluster` resource from the external cluster before you can install {mce-short}.

- For {ocp-short} Dedicated environment, the `dedicated-admin` role does not have the required permissions to create namespaces in the {ocp-short} Dedicated environment. You need _Cluster administrator_ permissions.

- By default, the {mce-short} components are installed on worker nodes of your {ocp-short} cluster without any additional configuration. You can install {mce-short} onto worker nodes by using the {ocp-catalog} console, or by using the {ocp-short} command-line interface.

- If you configured your {ocp-short} cluster with infrastructure nodes, you can install {mce-short} onto those infrastructure nodes by using the {ocp-short} command-line interface with additional resource parameters. See the _Installing multicluster engine on infrastructure nodes_ section for details.

- If you plan to import Kubernetes clusters that were not created by {ocp-short} or {mce-short}, you need to configure an image pull secret. For information about how to configure an image pull secret and other advanced configurations, see options in the xref:./adv_config_install.adoc#advanced-config-mce[Advanced configuration {mce-short}] section of this documentation. 

.Prerequisites

Before you install {mce-short}, see the following prerequisites:

* You need an {ocp-short} cluster with access to the {mce-short} in the {ocp-catalog} console. 

* You need access to the link:https://catalog.redhat.com/software/containers/search?p=1&application_categories_list=Container%20Platform%20%2F%20Management[catalog.redhat.com].

* Ensure your cluster does _not_ have a `ManagedCluster` resource configured in an external cluster.

* Confirm that a supported version of {ocp-short} is deployed in your environment, and you must be logged into with the {ocp-short} command-line interface. See the following install documentation:

  - link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/installation_overview/index[{ocp-short} Installing]

* Your {ocp-short} command-line interface must be configured to run `oc` commands. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the CLI] for information about installing and configuring.

* Your {ocp-short} permissions must allow you to create a namespace.

* You must have an Internet connection to access the dependencies for the operator.

* To install in a {ocp-short} Dedicated environment, see the following:

** You must have the {ocp-short} Dedicated environment configured and running.

** You must have `cluster-admin` authority to the {ocp-short} Dedicated environment where you are installing the engine.

* If you plan to create managed clusters by using the {ai} that is provided with {ocp}, see link:https://docs.redhat.com/en/documentation/assisted_installer_for_openshift_container_platform/2025/html/installing_openshift_container_platform_with_the_assisted_installer/prerequisites[Preparing to install with the {ai}] topic in the {ocp-short} documentation for the requirements. 

.Procedure

. Verify that {mce-short} is not already installed on your {ocp-short} cluster. The {mce-short} allows only one single installation on each {ocp-short} cluster. 

. To ensure that the {ocp-short} cluster is set up correctly, access the {ocp-short} web console with the following command:

+
[source,bash]
----
kubectl -n openshift-console get route console
----

+  
See the following example output:

+
[source,bash]
----
console console-openshift-console.apps.new-coral.purple-chesterfield.com               
console   https   reencrypt/Redirect     None
----

. Open the URL from your output in your browser and check the result. If the console URL displays `console-openshift-console.router.default.svc.cluster.local`, set the value for `openshift_master_default_subdomain` when you install {ocp-short}. See the following example of a URL: `https://console-openshift-console.apps.new-coral.purple-chesterfield.com`.

.Next steps

You can proceed to install {mce-short}. See xref:./install_connected.adoc#installing-while-connected-online-mce[Installing while connected online] for installation instructions.