:_mod-docs-content-type: PROCEDURE

[#apply-upgrade-policies]
= Upgrading clusters in a disconnected environment

[role="_abstract"]
You can view a list of available upgrades for your managed cluster. You can use the {acm-short} console to select a channel for your cluster upgrades on {ocp-short}. Those versions must be available on the mirror registry. After configuring the disconnected registry, {acm-short} and {update-service} use the disconnected registry to find if upgrades are available.

After configuring the disconnected registry, {acm-short} and {update-service} use the disconnected registry to find if upgrades are available. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/registry/configuring-registry-operator#images-configuration-cas_configuring-registry-operator[Configuring additional trust stores for image registry access] in the {ocp-short} documentation to learn more about the external registry CA certificate.

If no available upgrades are displayed, make sure that you have the release image of the current level of the cluster and at least one later level mirrored in the local repository.

If the release image for the current version of the cluster is not available, no upgrades are available.

.Procedure

Complete the following steps to view, select, and upgrade your cluster:

. From the console, select *Infrastructure* > *Clusters*.

. Select a cluster that is in the _Ready_ state.

. From the *Actions* menu, select *Upgrade cluster*. 

. Verify that the optional upgrade paths are available. *Note:* No available upgrade versions are shown if the current version is not mirrored into the local image repository.  

. Select a _channel_ for your cluster upgrades on {ocp-short}. Those versions must be available on the mirror registry.

. In the console, select *Infrastructure* > *Clusters*.

. Find the cluster that you want to upgrade. If there is an upgrade available, the *Distribution version* column for the cluster displays an upgrade available. 

. Select the _Options_ menu for that cluster, and select *Upgrade cluster*.

. Select the target version for the upgrade, and select *Upgrade*. 

If your cluster upgrade fails, the Operator generally retries the upgrade a few times, stops, and reports the status of the failing component. In some cases, the upgrade process continues to cycle through attempts to complete the process. Rolling your cluster back to a previous version after a failed upgrade is not supported. Contact Red Hat support for assistance if your cluster upgrade fails.