:_mod-docs-content-type: REFERENCE

[#upgrade-clusters-mce]
= Upgrading disconnected clusters by using policies

If you use the {acm-short} hub cluster to manage, upgrade, and install components with the the `MultiClusterHub` operator, you can use the {update-service} and {acm-short} policies to upgrade multiple clusters in a disconnected environment.

{update-service} is a separate operator and operand that monitors available versions for managed clusters and makes them accessible for upgrading in restricted networks.

{update-service} performs the following actions:
* Monitors upgrade availability for disconnected clusters.
* Identifies updates mirrored to your local site by using the graph data file.
* Notifies you of available upgrades via the console.

See the following procedures to prepare for and upgrade clusters in a disconnected environment:

* xref:../install_upgrade/preparing_disconnected_registry.adoc#preparing-disconnected-registry[Preparing the disconnected mirror registry] 
* xref:../install_upgrade/deploying_update_service.adoc#deploy-update-service[Deploying {update-service} in a disconnected environment]
* xref:../install_upgrade/applying_upgrade_policies.adoc#apply-upgrade-policies[Applying upgrade policies to managed clusters]