[#upgrading-mce]
= Upgrading {mce} 

[role="_abstract"]
Learn how to upgrade your {mce-short}. Control your {mce-short} upgrades by using the operator subscription settings in the {ocp-short} console.

*Required access:* {ocp-short} administrator

*Important:*

* Upgrades are always supported from the immediate previous version. You can upgrade to the next available feature release.
* If you are on a version with an *Extended Update Support* (EUS) status, you can upgrade to the next version, or you can skip to the next EUS version. 
* You can perform skip-level upgrades from `<2.x>` to `<2.x+2>` on even number versions of {mce-short}, starting with {acm-short} version 2.11. For instance, when you upgrade {mce-short} 2.6, which is an EUS version, you can choose to upgrade to version 2.8, which is also an EUS version.

.Procedure

You can upgrade your `MultiClusterEngine` resource from the console. Use the {olm} `operatorcondition` to control how versions are upgraded. When you initially deploy {mce-short} by using the operator, you make the following selections:

Channel:: Channel corresponds to the version of the product that you are installing. The initial channel setting is often the most current channel that was available at the time of installation.
Approval:: Approval specifies whether approval is required for updates within the channel, or if they are done automatically.
- If set to `Automatic`, then minor release updates in the selected channel are deployed without administrator intervention.
- If set to `Manual`, then each update to the minor release within the channel requires an administrator to approve the update.

You also use these settings when you upgrade to the latest version of {mce-short} by using the operator. Complete the following steps to upgrade your operator:

*Important:*

Downgrading a version is not supported. You cannot revert back to an earlier version after upgrading to a later version in the channel selection. You must uninstall the operator and reinstall it with the earlier version to use a previous version.

See the following procedure to upgrade your cluster:

. Log in to your {ocp-short} _Software Catalog_.
. In the {ocp-short} navigation, select *Operators* > *Installed operators*.
. Select the *{mce}* operator.
. Select the *Subscription* tab to edit the subscription settings.
. Ensure that the _Upgrade Status_ is labeled `Up to date`. This status indicates that the operator is at the latest level that is available in the selected channel. If the _Upgrade Status_ indicates that there is an upgrade pending, complete the following steps to update it to the latest minor release that is available in the channel:
.. Click the *Manual* setting in the _Approval_ field to edit the value.
.. Select *Automatic* to enable automatic updates.
.. Select *Save* to commit your change.
.. Wait for the automatic updates to be applied to the operator. The updates automatically add the required updates to the latest version in the selected channel. When all of the updated updates are complete, the _Upgrade Status_ field indicates an `Up to date` status.

+
*Note:* It can take up to 10 minutes for the `MultiClusterEngine` custom resource to finish upgrading. 

. Run the following command to verify the upgrade process is started:

+
[source,bash]
----
oc get mce
----

+
While in the process of upgrading, the `Status` displays `Updating`. After the upgrade is complete, the `Status` field changes to `Available` status.

. When the _Upgrade Status_ is `Up to date`, click the value in the _Channel_ field to edit the channel.
. Select the channel for the next available feature release, but do not attempt to skip a channel.

+
The {olm} `operatorcondition` resource checks for previous upgrades during the current upgrade process and prevents skipping versions. You can check that same resource status to see if the upgradable status is `true` or `false`.

. Click *Save* to save your changes.
. Wait for the automatic upgrade to complete. After the upgrade to the next feature release completes, the updates to the latest patch releases within the channel are deployed.
. If you have to upgrade to a later feature release, repeat steps 7-9 until your operator is at the latest level of the desired channel. Make sure that all of the patch releases are deployed for your final channel.
. Optional: You can set your _Approval_ setting to *Manual*, if you want your future updates within the channel to require manual approvals.
. If you performed a skip-level upgrade, see the following sub-steps to verify your upgrade:
.. Verify that the `csv` version from the previous release, for instance, `2.6` (EUS), is replaced with the upgraded version, for instance, `2.8` (EUS).
.. Verify that the `MultiClusterEngine` instance `status.currentVersion` specification value is set at `2.8` and matches the `desiredVersion` status, which is also set at `2.8`.

.Additional resources

For more information about upgrading your operator, see link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.17/html/operators/index[Operators] in the {ocp-short} documentation.