[#upgrade-disconnect-cluster-policy]
= Upgrading disconnected clusters by using policies

If you have the {acm} hub cluster, which uses the `MultiClusterHub` operator to manage, upgrade, and install hub cluster components, you can use {update-service} with {acm-short} policies to upgrade multiple clusters in a disconnected environment.

{update-service} is a separate operator and operand that monitors the available versions of your managed clusters and makes them available for upgrading in a disconnected environment. {update-service} can perform the following actions:

* Monitor when upgrades are available for your disconnected clusters.
* Identify which updates are mirrored to your local site for upgrading by using the graph data file.
* Notify you that an upgrade is available for your cluster by using the console.

* <<update-service-prereq,Prerequisites>>
* <<prepare-disconnect-mirror-registry,Prepare your disconnected mirror registry>>
* <<deploy-operator-update-service,Deploy the operator for {update-service}>>
* <<build-graph-data-init,Build the graph data init container>>
* <<configure-certificate-mirrored-registry,Configuring the certificate for the mirrored registry>>
* <<deploy-update-service,Deploy the {update-service} instance>>
* <<deploy-policy-override-registry,Optional: Deploying a policy to override the default registry>>
* <<deploy-policy-disconnect-catalog,Deploying a policy to deploy a disconnected catalog source>>
* <<deploy-policy-cluster-parameter,Deploying a policy to change the managed cluster parameter>>
* <<update-service-view-upgrades,Viewing available upgrades>>
* <<update-service-channel,Selecting a channel>>
* <<update-service-upgrade,Upgrading the cluster>>
* <<add-resources-upgrade-service,Additional resources>>

See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/registry/configuring-registry-operator#images-configuration-cas_configuring-registry-operator[Configuring additional trust stores for image registry access] in the {ocp-short} documentation to learn more about the external registry CA certificate.

[#update-service-prereq]
== Prerequisites

You must have the following prerequisites before you can use {update-service} to upgrade your disconnected clusters:

* You need to install {acm-short}. See the {acm-short} link:../install/install_overview.adoc#installing[Installing and upgrading] documentation.
* You need a hub cluster that is running on a supported {ocp} version with restricted OLM configured. See link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.16/html-single/operators/index#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks] for details about how to configure restricted OLM. Take note of the catalog source image when you configure restricted OLM.
* You need an {ocp-short} cluster that the hub cluster manages.
* You need access credentials to a local repository where you can mirror the cluster images. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/disconnected_installation_mirroring[Disconnected installation mirroring] for more information.
+
*Note:* The image for the current version of the cluster that you upgrade must remain available as one of the mirrored images. If an upgrade fails, the cluster reverts back to the version of the cluster when you tried to upgrade.

[#prepare-disconnect-mirror-registry]
== Preparing your disconnected mirror registry

You must mirror both the image that you want to upgrade to and the current image that you are upgrading from to your local mirror registry.

Complete the following steps to mirror the images:

. Create a script file with content that resembles the following example. Replace `<pull-secret>` with the path to your {ocp-short} pull secret:

+
[source,bash]
----
UPSTREAM_REGISTRY=quay.io
PRODUCT_REPO=openshift-release-dev
RELEASE_NAME=ocp-release
OCP_RELEASE=4.15.2-x86_64
LOCAL_REGISTRY=$(hostname):5000
LOCAL_SECRET_JSON=<pull-secret>

oc adm -a ${LOCAL_SECRET_JSON} release mirror \
--from=${UPSTREAM_REGISTRY}/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE} \
--to=${LOCAL_REGISTRY}/ocp4 \
--to-release-image=${LOCAL_REGISTRY}/ocp4/release:${OCP_RELEASE}
----

. Run the script to mirror the images, configure settings, and separate the release images from the release content.

[#deploy-operator-update-service]
== Deploying the operator for {update-service}

To deploy the operator for {update-service} in your {ocp-short} environment, complete the following steps:

. On your hub cluster, access the {ocp-short} operator hub. 
. Deploy the operator by selecting `{update-service} Operator` and update the default values if needed. The deployment of the operator creates a new project named `openshift-update-service`.
. Wait for the installation of the operator to finish. 

You can check the status of the installation by running the `oc get pods` command. Verify that the operator is in the `running` state.

[#build-graph-data-init]
== Building the graph data init container

{update-service} uses graph data information to find the available upgrades. In a connected environment, {update-service} pulls the graph data information for available upgrades directly from the link:https://github.com/openshift/cincinnati-graph-data[update-service graph data GitHub repository].

In a disconnected environment, you must make the graph data available in a local repository by using an `init container`.

Complete the following steps to create a graph data `init container`:

. Clone the _graph data_ Git repository by running the following command:

+
[source,bash]
----
git clone https://github.com/openshift/cincinnati-graph-data
----

. Create a file that has the information for your graph data `init`. You can find a sample link:https://github.com/openshift/cincinnati-operator/blob/master/dev/Dockerfile[Dockerfile] in the `cincinnati-operator` GitHub repository.
+
* The `FROM` value is the external registry where {update-service} finds the images.
* The `RUN` commands create the directory and package the upgrade files. 
* The `CMD` command copies the package file to the local repository and extracts the files for an upgrade.

. Run the following command to build the `graph data init container`:

+
[source,bash]
----
podman build -f <docker-path> -t <graph-path>:latest
----
+
Replace `<docker-path>` with the path to the file that you created in the previous step.
+
Replace `<graph-path>` with the path to your local graph data init container.

. Run the following command to push the `graph data init container`:

+
[source,bash]
----
podman push <graph-path>:latest --authfile=<pull-secret>.json
----
+
Replace `<graph-path>` with the path to your local graph data init container.
+
Replace `<pull-secret>` with the path to your pull secret file.

*Optional:* If you do not have `podman` installed, replace `podman` with `docker` in step three and four.

[#configure-certificate-mirrored-registry]
== Configuring the certificate for the mirrored registry 

If you are using a secure external container registry to store your mirrored {ocp-short} release images, {update-service} requires access to this registry to build an upgrade graph. 

Complete the following steps to configure your CA certificate to work with the {update-service} pod:

. Find the {ocp-short} external registry API, which is located in `image.config.openshift.io`. This is where the external registry CA certificate is stored. See _Configuring additional trust stores for image registry access_ in the additional resources section to learn more.

. Create a ConfigMap in the `openshift-config` namespace and add your CA certificate in the `updateservice-registry` section. See the following example:

+
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca
data:
  updateservice-registry: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
----

. Edit the `cluster` resource in the `image.config.openshift.io` API to set the `additionalTrustedCA` field to the name of the ConfigMap that you created. Run the following command and replace `<trusted_ca>` with the path to your new ConfigMap:

+
----
oc patch image.config.openshift.io cluster -p '{"spec":{"additionalTrustedCA":{"name":"<trusted_ca>"}}}' --type merge
----

The {update-service} Operator watches the `image.config.openshift.io` API and the ConfigMap you created in the `openshift-config` namespace for changes, then restarts the deployment if the CA cert has changed.

[#deploy-update-service]
== Deploying the {update-service} instance

When you finish deploying the {update-service} instance on your hub cluster, the instance is located where the images for the cluster upgrades are mirrored and made available to the disconnected managed cluster.

Complete the following steps to deploy the instance:

. If you do not want to use the default namespace of the operator, navigate to *Administration* > *Namespaces* in the console to change it.
. In the _Installed Operators_ section of the {ocp-short} console, select *{update-service} Operator*.
. Select *Create Instance* in the menu.
. Paste the contents from your {update-service} instance. Your YAML instance might resemble the following manifest:

+
[source,yaml]
----
apiVersion: update-service.openshift.io/v1beta2
kind: update-service
metadata:
  name: openshift-cincinnati-instance
  namespace: openshift-update-service
spec:
  registry: <registry-host-name>:<port> <1>
  replicas: 1
  repository: ${LOCAL_REGISTRY}/ocp4/release
  graphDataImage: '<host-name>:<port>/cincinnati-graph-data-container' <2>
----
+
<1> Replace with the path to your local disconnected registry for your images.
+
<2> Replace with the path to your graph data init container. This is the same value that you used when you ran the `podman push` command to push your graph data init container.

. Select *Create* to create the instance. 

. From the hub cluster CLI, enter the `oc get pods` command to view the status of the instance creation.

It might take a few minutes. The process is complete when the result of the command shows that the instance and the operator are running.

[#deploy-policy-override-registry]
== Optional: Deploying a policy to override the default registry

The following steps only apply if you have mirrored your releases into your mirrored registry.

*Deprecated:* `PlacementRule`

{ocp-short} has a default image registry value that specifies where it finds the upgrade packages. In a disconnected environment, you can create a policy to replace that value with the path to your local image registry where you mirrored your release images. 

Complete the following steps to create the policy:

. Log in to the {ocp-short} environment of your hub cluster.

. From the console, select *Governance* > *Create policy*.

. Set the *YAML* switch to _On_ to view the YAML version of the policy.

. Delete all of the content in the YAML code. 

. Paste the following YAML content into the window to create a custom policy:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-mirror
  namespace: default
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition: 
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-image-content-source-policy
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1alpha1
                kind: ImageContentSourcePolicy
                metadata:
                  name: <your-local-mirror-name> <1>
                spec:
                  repositoryDigestMirrors:
                    - mirrors:
                        - <your-registry> <2>
                      source: registry.redhat.io
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-mirror
  namespace: default
placementRef:
  name: placement-policy-mirror
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-mirror
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-mirror
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      []  <3>
----
+
<1> Replace with your local mirror name.
<2> Replace with the path to your local mirror repository. You can find the path to your local mirror by running the `oc adm release mirror` command.
<3> Selects all clusters if not specified.

. Select *Enforce if supported*.

. Select *Create* to create the policy. 

[#deploy-policy-disconnect-catalog]
== Deploying a policy to deploy a disconnected catalog source

You can push the _Catalogsource_ policy to the managed cluster to change the default location from a connected location to your disconnected local registry.

Complete the following steps to change the default location:

. In the console menu, select *Governance* > *Create policy*.

. Set the `YAML` switch to _On_ to view the YAML version of the policy.

. Delete all of the content in the `YAML` code. 

. Paste the following `YAML` content into the window to create a custom policy:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-catalog
  namespace: default
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-catalog
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OperatorHub
                metadata:
                  name: cluster
                spec:
                  disableAllDefaultSources: true
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: CatalogSource
                metadata:
                  name: my-operator-catalog
                  namespace: openshift-marketplace
                spec:
                  sourceType: grpc
                  image: '<registry_host_name>:<port>/olm/redhat-operators:v1' <1>
                  displayName: My Operator Catalog
                  publisher: grpc
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-catalog
  namespace: default
placementRef:
  name: placement-policy-catalog
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-catalog
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-catalog
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      []  <2>
----
+
<1> Replace with the path to your local restricted catalog source image.
<2> Selects all clusters if not specified.

. Select *Enforce if supported*.

. Select *Create* to create the policy.

[#deploy-policy-cluster-parameter]
== Deploying a policy to change the managed cluster parameter

You can push the _ClusterVersion_ policy to the managed cluster to change the default location where it retrieves its upgrades.

Complete the following steps:

. From the managed cluster, confirm that the _ClusterVersion_ upstream parameter is currently the default public {update-service} operand by running the following command:

+
[source,bash]
----
oc get clusterversion -o yaml
----

. From the hub cluster, identify the route URL to the {update-service} operand by running the following command:

+
[source,bash]
----
oc get routes
----
+
Remember the result for later.

. In the hub cluster console menu, select *Governance* > *Create a policy*.

. Set the `YAML` switch to _On_ to view the YAML version of the policy.

. Delete all of the content in the `YAML` code. 

. Paste the following `YAML` content into the window to create a custom policy:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cluster-version
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: null
    policy.open-cluster-management.io/categories: null
    policy.open-cluster-management.io/controls: null
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-cluster-version
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterVersion
                metadata:
                  name: version
                spec:
                  channel: stable-4.4
                  upstream: >-
                    https://example-cincinnati-policy-engine-uri/api/upgrades_info/v1/graph <1>

---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-cluster-version
  namespace: default
placementRef:
  name: placement-policy-cluster-version
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-cluster-version
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-cluster-version
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      [] <2> 
----
+
<1> Replace with the path to your hub cluster {update-service} operand.
Selects all clusters if not specified.
+
You can complete the following steps to determine the path to the operand:
+
.. Run the `oc get get routes -A` command on the hub cluster.
.. Find the route to `update-service`.
+
The path to the operand is the value in the `HOST/PORT` field.

. Select *Enforce if supported*. 

. Select *Create* to create the policy.

. In the managed cluster CLI, confirm that the upstream parameter in the `ClusterVersion` is updated with the local hub cluster {update-service} URL by running the following command:

+
[source,bash]
----
oc get clusterversion -o yaml
----

. Verify that the results resemble the following content:

+
[source,yaml]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
[..]
  spec:
    channel: stable-4.4
    upstream: https://<hub-cincinnati-uri>/api/upgrades_info/v1/graph
----

[#update-service-view-upgrades]
== Viewing available upgrades

You can view a list of available upgrades for your managed cluster by completing the following steps:

. From the console, select *Infrastructure* > *Clusters*.

. Select a cluster that is in the _Ready_ state.

. From the *Actions* menu, select *Upgrade cluster*. 

. Verify that the optional upgrade paths are available. 

*Note:* No available upgrade versions are shown if the current version is not mirrored into the local image repository.  

[#update-service-channel]
== Selecting a channel

You can use the {acm-short} console to select a channel for your cluster upgrades on {ocp-short}. Those versions must be available on the mirror registry.

Complete the steps in link:../clusters/install_upgrade/upgrade_cluster.adoc#selecting-a-channel[Selecting a channel] to specify a channel for your upgrades. 

[#update-service-upgrade]
== Upgrading the cluster

After configuring the disconnected registry, {acm-short} and {update-service} use the disconnected registry to find if upgrades are available.

If no available upgrades are displayed, make sure that you have the release image of the current level of the cluster and at least one later level mirrored in the local repository.

If the release image for the current version of the cluster is not available, no upgrades are available.

Complete the following steps to upgrade:

. In the console, select *Infrastructure* > *Clusters*.

. Find the cluster that you want to choose if there is an available upgrade. 

. If there is an upgrade available, the *Distribution version* column for the cluster shows an upgrade available. 

. Select the _Options_ menu for the cluster, and select *Upgrade cluster*.

. Select the target version for the upgrade, and select *Upgrade*. 

If your cluster upgrade fails, the Operator generally retries the upgrade a few times, stops, and reports the status of the failing component. In some cases, the upgrade process continues to cycle through attempts to complete the process. Rolling your cluster back to a previous version after a failed upgrade is not supported. Contact Red Hat support for assistance if your cluster upgrade fails.

[#add-resources-upgrade-service]
=== Additional resources

See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/registry/configuring-registry-operator#images-configuration-cas_configuring-registry-operator[Configuring additional trust stores for image registry access] in the {ocp-short} documentation to learn more about the external registry CA certificate.