:_mod-docs-content-type: PROCEDURE

[#cert-refresh-webhook]
= Refreshing a {acm-short} webhook certificate

[role="_abstract"]
You can refresh {acm-short} managed certificates, which are certificates that are created and managed by {acm-short} services.

Complete the following steps to refresh certificates managed by {acm-short}:

.Procedure

. Delete the secret that is associated with the {acm-short} managed certificate, and replace `<namespace>` and `<secret>` with the values that you want to use. Run the following command:

+
[source,bash]
----
oc delete secret -n <namespace> <secret>
----

. Restart the services that are associated with the {acm-short} managed certificates, and replace `<namespace>` and `<pod-label>` with the values for the {acm-short} managed cluster certificates. Run the following command:

+
[source,bash]
----
oc delete pod -n <namespace> -l <pod-label>
----
+
*Note:* If a `pod-label` is not specified, there is no service that must be restarted. The secret is recreated and used automatically.
