:_mod-docs-content-type: PROCEDURE

[#replacing-cert-alertmanager]
= Replacing certificates for _alertmanager_ route

[role="_abstract"]
If you do not want to use the {ocp-short} default ingress certificate, replace observability `alertmanager` certificates by updating the Alertmanager route.

.Procedure

. Examine the observability certificate with the following command:

+
[source,bash]
----
openssl x509  -noout -text -in ./observability.crt
----

. Change the common name (`CN`) on the certificate to `alertmanager`.

. Change the SAN in the `csr.cnf` configuration file with the hostname for your `alertmanager` route.

. Create the `alertmanager-byo-ca` Secret resource in the `open-cluster-management-observability` namespace by running the following command:

+
[source,bash]
----
oc -n open-cluster-management-observability create secret tls alertmanager-byo-ca --cert ./ca.crt --key ./ca.key
----

. Create the `alertmanager-byo-cert` `Secret` resource in the `open-cluster-management-observability` namespace by running the following command:

+
[source,bash]
----
oc -n open-cluster-management-observability create secret tls alertmanager-byo-cert --cert ./ingress.crt --key ./ingress.key
----
