:_mod-docs-content-type: REFERENCE

[#certificates-hub]
= {acm-short} hub cluster certificates

[role="_abstract"]
{ocp-short} default ingress certificate is a type of hub cluster certificate. After you install {acm-short}, Observability certificates are created and used by the Observability components to give mutual TLS for traffic between the hub and managed cluster. Access the Observability namespaces to retrieve and implement the different Observability certificates.

* The following certificates are a part of the `open-cluster-management-observability` namespace:

- `observability-server-ca-certs`: Has the CA certificate to sign server-side certificates
- `observability-client-ca-certs`: Has the CA certificate to sign client-side certificates
- `observability-server-certs`: Has the server certificate used by the `observability-observatorium-api` deployment
- `observability-grafana-certs`: Has the client certificate used by the `observability-rbac-query-proxy` deployment 

* The `open-cluster-management-addon-observability` namespace includes the following certificates on managed clusters:

- `observability-managed-cluster-certs`: Has the same server CA certificate as `observability-server-ca-certs` in the hub server
- `observability-controller-open-cluster-management.io-observability-signer-client-cert`: Has the client certificate used by the `metrics-collector-deployment` 

The CA certificates are valid for five years and other certificates are valid for one year. All Observability certificates are automatically refreshed upon expiration. View the following list to understand the effects when certificates are automatically renewed:

* Non-CA certificates are renewed automatically when the remaining valid time is no more than 73 days. After the certificate is renewed, the pods in the related deployments restart automatically to use the renewed certificates.

* CA certificates are renewed automatically when the remaining valid time is no more than one year. After the certificate is renewed, the old CA is not deleted but co-exist with the renewed ones. Both old and renewed certificates are used by related deployments, and continue to work. The old CA certificates are deleted when they expire.

* When a certificate is renewed, the traffic between the hub cluster and managed cluster is not interrupted.

View the following {acm-short} hub cluster certificates table:

.{acm-short} hub cluster certificates
|===
| Namespace | Secret name | Pod label

| open-cluster-management
| channels-apps-open-cluster-management-webhook-svc-ca
| app=multicluster-operators-channel

| open-cluster-management
| channels-apps-open-cluster-management-webhook-svc-signed-ca 
| app=multicluster-operators-channel

| open-cluster-management
| multicluster-operators-application-svc-ca
| app=multicluster-operators-application

| open-cluster-management
| multicluster-operators-application-svc-signed-ca
| app=multicluster-operators-application

| open-cluster-management-hub
| registration-webhook-serving-cert signer-secret
| Not required

| open-cluster-management-hub
| work-webhook-serving-cert
| Not required
|===
