:_mod-docs-content-type: PROCEDURE

[#customize-cert]
= Customizing your CA certificates for observability

[role="_abstract"]
When you install {acm}, only Certificate Authority (CA) certificates for observability are provided by default. If you do not want to use the default observability CA certificates, you can bring your own observability CA certificates before you enable observability. Customize your CA certificates for observability with the following steps:

*Required access:* Administrator

.Procedure

. Generate CA certificates for the server-side and the client-side by using OpenSSL commands.
.. To generate your CA RSA private keys for the server-side, run the following command:

+
[source,bash]
----
openssl genrsa -out serverCAKey.pem 2048
----

.. To generate your CA RSA private keys for the client-side, run the following command:

+
[source,bash]
----
openssl genrsa -out clientCAKey.pem 2048
----

. Generate the self-signed CA certificates using the private keys.
.. To generate the self-signed CA certificates for the server-side, run the following command:

+
[source,bash]
----
openssl req -x509 -sha256 -new -nodes -key serverCAKey.pem -days 1825 -out serverCACert.pem
----

.. To generate the self-signed CA certificates for the client-side, run the following command:

+
[source,bash]
----
openssl req -x509 -sha256 -new -nodes -key clientCAKey.pem -days 1825 -out clientCACert.pem
----

. To store and manage your CA certificates for observability, create `Secret` resources for each CA certificate.
.. Create the `observability-server-ca-certs` secret by using your certificate and private key. Run the following command:

+
[source,bash]
----
oc -n open-cluster-management-observability create secret tls observability-server-ca-certs --cert ./serverCACert.pem --key ./serverCAKey.pem
----

.. Create the `observability-client-ca-certs` secret by using your certificate and private key. Run the following command:

+
[source,bash]
----
oc -n open-cluster-management-observability create secret tls observability-client-ca-certs --cert ./clientCACert.pem --key ./clientCAKey.pem
----
