:_mod-docs-content-type: PROCEDURE

[#enable-cluster-permission-validate]
= Enabling validation for cluster permissions

[role="_abstract"]
Enable the `validate` specification within your `ClusterPermission` resources to check the existence of your `Role` and `ClusterRole` resources.

*Required access:* Cluster administrator

Complete the following steps:

. Create a `ClusterPermission` resource where you set the `validate` specification to `true`.Define the `roleBindings` and `clusterRoleBinding` that you want to validate.  
+
Your YAML file might resemble the following example where you configure the `ClusteerRole` to validate the `edit` `ClusterRole` for the `sa-sample-existing` `ServiceAccount`, and the `view` `ClusterRole` for `Group1`:

+
[source,yaml]
----
apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: clusterpermission-validate-sample
spec:
  validate: true
  roleBindings:
    - name: default-existing
      namespace: default
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subject:
        namespace: openshift-gitops
        kind: ServiceAccount
        name: sa-sample-existing
  clusterRoleBinding:
      name: crb-cluster1-argo-app-con-3-existing
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: view
      subject:
        apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: group1
----

. Apply your `clusterpermission-validate-sample` `ClusterPermission` by running the following command:

+
[source,bash]
----
oc apply clusterpermission-validate-sample.yaml
----
