:_mod-docs-content-type: PROCEDURE

[#create-cluster-permission-exist]
= Creating a cluster permission by using an existing role 

[role="_abstract"]
When you create a `ClusterPermission` resource, you automatically create new roles. You can still use the `ClusterPermission` resource with an existing role. 

*Required access:* Cluster administrator

.Prerequisites

* If you want to bind to the `ManagedServiceAccount` resource, you must have the `ManagedServiceAccount` add-on. For more information about enabling the `ManagedServiceAccount` add-on, see link:../add-ons/configure_klusterlet_addons.adoc[Configuring klusterlet add-ons].

.Procedure

. Create a `ClusterPermission` resource that uses an existing role by running the following command:

+
[source,bash]
----
oc create -f <clusterpermission-existing-role-yaml-file>.yaml
----

. Run the following command to apply your `ClusterPermission` resource that uses an existing `ClusterRole` resource:

+
[source,bash]
----
oc apply -f <clusterpermission-existing-role-yaml-file>.yaml
----

.. *Optional:* Add a name for your `roleBindings` specification if you do not want to use the default `ClusterPermission` name.
.. Add the configuration details of your existing `ClusterRole` on your managed cluster to the `roleRef` specification. Your `ClusterPermission` resource might resemble the following partial example:

+
[source,yaml]
----
apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: clusterpermission-existing-role-sample
spec:
  roleBindings:
    - name: default-rb-cluster1
      namespace: default
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: argocd-application-controller-1
      subject:
        namespace: openshift-gitops
        kind: ServiceAccount
        name: sa-sample-existing
    - name: kubevirt-rb-cluster1
      namespace: kubevirt
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: argocd-application-controller-2
      subject:
        apiGroup: rbac.authorization.k8s.io
        kind: User
        name: user1
----


.. *Optional:* Add a name for your `clusterRoleBinding` specification if you do not want to use the default `ClusterPermission` name. 
.. Add the configuration details of your existing `ClusterRole` on your managed cluster to the `roleRef` specification.

+
Your `ClusterPermission` resource might resemble the following partial example:

+
[source,yaml]
----
  clusterRoleBinding:
      name: crb-cluster1-argo-app-con-3
      roleRef: 
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: argocd-application-controller-3
      subject:
        apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: group1 
----
