[#creating-cluster-permission-reference]
= Creating a cluster permission resource to reference subjects 

If you create a `ClusterPermission` resource to reference different subjects, you can work with different subjects at the same time instead of only working on one subject at a time. 

*Required access:* Cluster administrator

.Prerequisites

- are there any prereqs for this?

.Procedure

Complete the following steps to create a `ClusterPermission` resource that references different subjects such as users, groups, and service accounts:

. Create a `ClusterPermission` resource that references different subjects by running the following command:

+
[source,bash]
----
oc create -f <clusterpermission-users-groups-yaml-file>.yaml
----

. Run the following command to apply your `ClusterPermission` resource that references different subjects:

+
[source,bash]
----
oc apply -f <clusterpermission-users-groups-yaml-file>.yaml
----

+
Your `ClusterPermission` resource might resemble the following YAML file with the specified `subjects` field: 

+
[source,yaml]
----
apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: clusterpermission-users-groups
spec:
  roleBindings:
    - namespace: default
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: argocd-application-controller-users-1
      subjects:
      - namespace: openshift-gitops
        kind: ServiceAccount
        name: sa-sample-existing
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: argo-users1
    - name: kubevirt-rb-cluster1-users1
      namespace: kube-system
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: argocd-application-controller-users-2
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: users1
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: users2
  clusterRoleBinding:
      name: crb-cluster1-argo-app-con-groups
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: argocd-application-controller-3
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: groups1
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: groups2
----
