[#fine-grain-ui-roles]
= Creating role assignments by using roles in the console

You can assign access permissions to a specific role from the Fleet Management console.

*Required access:* Cluster administrator

.Prerequisites

See the following requirements to begin using fine-grained role-based access control:

* Enable the fine-grained role-based access control. See xref:../secure_clusters/fine_grain_rbac_enable.adoc#fine-grain-enable[Enabling fine-grained role-based access control for virtualization] for the procedure.
* You must be logged in to the {ocp-short} console with cluster administrator or hub cluster administrator permissions.

.Procedure

. From the navigation menu, expand *User Management* and click *Roles*.

. Click the name of the role that you want to assign to identities.

. Click the *Role Assignments* tab.

. Click *Create role assignment*. The configuration window opens with the role information already populated.

. Select the *Identities* > *Users* or *Groups* that receive this role and click *Next*.

. In the *Scope* section, define the reach of the permissions by selecting one of the following options:
+
Global access:: Applies permissions to all clusters and namespaces in the hub.
Select cluster set:: Applies permissions to a specific group of clusters.
Select clusters:: Applies permissions to individual managed clusters.

. Click *Next*.

. If you did not select *Global access*, select the specific cluster sets or clusters from the list and click *Next*.

. Select the level of granularity for the assignment:
+
Cluster role assignment or Cluster set role assignment:: Grants access to all namespaces within the selection.
Project role assignment:: Limits access to specific common projects, which are namespaces.

. Click *Next*.

. If you selected *Project role assignment*, select the target projects and click *Next* and review the configuration summary for accuracy.

. Click *Create* to finalize the role assignment.

The new role assignment is created. You can verify the assignment by viewing the *Role Assignments* tab for either the selected role or the individual identities.