[#fine-grain-enable]
= Enabling fine-grained role-based access control for virtualization 

{acm} supports fine-grained role-based access control (RBAC) for virtual machine scenarios. As a cluster administrator, you can manage and control permissions at the namespace level and cluster level on your managed clusters. Grant permissions to a virtual machine namespace within a cluster without granting permission to the entire managed cluster.

Enabling fine-grained RBAC significantly changes how the console displays search results and manages access for application lifecycles, governance, and observability. 

*Required access:* Cluster administrator

To learn about {ocp-short} default and virtualization roles and permissions, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/virtualization/about#authorization_virt-security-policies[Authorization] in the {ocp-short} documentation.

See xref:../secure_clusters/rbac_implement_rhacm.adoc#rhacm-rbac-implement[Implementing role-based access control] for more details about {acm-short} role-based access.

.Prerequisites

See the following prerequisites that are needed to enable fine-grained role-based access control:

- Install a supported version of {ocp-virt} on your hub cluster. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/virtualization/installing[Virtualization - Installing].

- Install the Red Hat OpenShift Virtualization operator on the hub cluster and all managed clusters where you intend to manage virtual machines.
//new content

- You need virtual machines. 

- Learn about {ocp-short} default and virtualization roles and permissions, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/virtualization/about#authorization_virt-security-policies[Authorization] in the {ocp-short} documentation.

- For details on how to enable role-based access control, see xref:../secure_clusters/rbac_implement_rhacm.adoc#rhacm-rbac-implement[Implementing role-based access control].
//old content--do we need this

- You must have access to the following roles to complete live migration of your virtual machines: `kubevirt.io:admin`, `kubevirt.io-acm-hub:admin`, and `kubevirt.io-acm-managed:view`.
//how do they get access to these roles? 

*Important:* When you enable fine-grained RBAC, the following roles for {ocp-virt-short} are added automatically:

- `kubevirt.io:view`
- `kubevirt.io:edit`
- `kubevirt.io:admin`
- `kubevirt.io-acm-managed:admin`
- `kubevirt.io-acm-managed:view`
- `kubevirt.io-acm-hub:admin`
- `kubevirt.io-acm-hub:view`

- Configure the {acm-short} hub cluster and all managed clusters with the same identity providers (IdP). Users, groups, and group memberships must be identical across the environment to ensure that an identity authenticated on the hub cluster maps correctly to the same identity on the managed clusters.
// Do we need to say anything about how to do this?

- Ensure your hub cluster is self-managed as a `local-cluster`. You cannot use this feature if the `disableHubSelfManagement` parameter is set to `true`. By default, the hub cluster is self-managed. 
//do we need to say how to check this?

- Install the Migration Toolkit for Virtualization operator if you plan to perform VM migrations.
// Do we need to say how to do this? We don't have anything for this that I am aware of. 

*Note:* If you enable the `cnv-mtv-integrations` feature in {acm-short}, the system automatically installs and configures both the OpenShift Virtualization and MTV operators for you.
//should we say this earlier in the prerequisites? And do we need to say how to enable this feature?

.Procedure 

Complete the following steps to enable `fine-grained-rbac` in the `MultiClusterHub` resource. 

. Run the following command to edit the `MultiClusterHub` resource. Run `oc get mch -A` to get the name and namespace of the `MultiClusterHub` resource if you do not use the `open-cluster-management` namespace:

+
[source,bash]
----
oc edit mch -n open-cluster-management multiclusterhub
----

. Change the `configOverrides` specification from `enabled: false` to `enabled: true`.  See the following example with the feature enabled:

+
[source,yaml]
----
    - configOverrides: {}
      enabled: true
      name: fine-grained-rbac
----

. Label your `local-cluster` with `environment=virtualization`. Run the following command:

+
[source,bash]
----
oc label managedclusters local-cluster environment=virtualization
----

. Create a `ClusterRoleBinding` resource to add the `kubevirt.io-acm-hub:view` role. Run the following command:

+
[source,bash]
----
oc create clusterrolebinding <cluster-role-binding-name> --clusterrole=kubevirt.io-acm-hub:view --user=<user-name>
----

+
Your `ClusterRolebinding` resource might resemble the following YAML file:

+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt.io-acm-hub:view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: <cluster-role-name>
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: <user-name>
----

