[#fine-grain-rbac-cli]
= Implementing fine-grained role-based access control in the terminal (Technology Preview)

*Technology Preview:* {acm} supports fine-grained role-based access control (RBAC). As a cluster administrator, you can manage and control permissions with the `ClusterPermission` resource, which controls permissions at the namespace level and cluster level on your managed clusters. Grant permissions to a virtual machine namespace within a cluster without granting permission to the entire managed cluster.

Learn how to set up for fine-grained role-based access control (RBAC) and the `ClusterPermission` resource from the terminal.

*Required access:* Cluster administrator

See xref:../secure_clusters/rbac_implement_rhacm.adoc#rhacm-rbac-implement[Implementing role-based access control] for more details about {acm-short} role-based access.

.Prerequisites

See the following requirements to begin using fine-grained role-based access control:

* Your `MultiClusterHub` custom resource `spec.overrides.components` field for `search` must `enabled` to retrieve a list of managed clusters namespaces that can represent virtual machines that are used for access control.
* You need virtual machines. To learn about {ocp-short} default and virtualization roles and permissions, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/virtualization/about#authorization_virt-security-policies[Authorization] in the {ocp-short} documentation.
 
[#assign-fine-grain-rbac]
== Assigning fine-grained role-based access control in the terminal

You can grant access to the following roles for {ocp-virt-short}, which are extensions of the default roles:

- `kubevirt.io:view`: only view resources
- `kubevirt.io:edit`: modify resources
- `kubevirt.io:admin`: view, modify, delete resources; grant permissions

Complete the following steps:

. Enable `fine-grained-rbac-preview` in the `MultiClusterHub` resource. 

.. Run the following command:

+
[source,bash]
----
oc edit mch -n open-cluster-management multiclusterhub
----

.. Edit to change the `configOverrides` specification from `enabled: false` to `enabled: true`. See the following example with the feature enabled:

+
[source,yaml]
----
    - configOverrides: {}
      enabled: true
      name: fine-grained-rbac-preview
----
+
*Note:* Run `oc get mch -A` to get the name and namespace of the `MultiClusterHub` resource if you do not use the `open-cluster-management` namespace.

. Create a `ClusterRole` YAML file. Complete the following steps:
.. Define the name for your `ClusterRole` resource by changing the `name` parameter.
.. Add the names of the managed clusters that you want your `User` or `Group` to access. Each name must be unique.

+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <cluster-role-name> <1>
rules:
  - apiGroups: ["clusterview.open-cluster-management.io"]
    resources: ["kubevirtprojects"]
    verbs: ["list"]
  - apiGroups: ["clusterview.open-cluster-management.io"]
    resources: ["managedclusters"]
    verbs: ["list","get","watch"]
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclusters"]
    verbs: ["get"]
    resourceNames: ["<cluster-name-01>", "<cluster-name-02>", "<cluster-name-03>"] <2>
----

. Create a `ClusterRoleBinding` YAML file. Complete the following steps:
.. Define the name for your `ClusterRoleBinding` resource by changing the `name` parameter.
.. Ensure the name of the `roleRef` specification matches the name of your `ClusterRole` resource.
.. Configure the `subjects` specification by adding either the `User` or `Group` details.
.. Specify the name of the `User` or `Group`.

+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <role-binding-name>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: <cluster-role-name>
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: <user-name>
----

. Apply the `ClusterRole` resource. Run the following command and change the file name only if you changed it earlier in the process:

+
[source,bash]
----
oc apply -f <filename>.yml
----

