:_mod-docs-content-type: CONCEPT

[#fine-grain-mca]
= Fine-grained role-based access control _MulticlusterRoleAssignment_

[role="_abstract"]
The `MulticlusterRoleAssignment` custom resource provides a declarative method for defining role-based access control (RBAC) across a multicluster environment. You can use this resource to create a centralized definition on the hub cluster that specifies which users or groups receive permissions on targeted managed clusters.

When you apply a `MulticlusterRoleAssignment` resource, the system creates the corresponding standard Kubernetes RBAC bindings, either a `RoleBinding` or a `ClusterRoleBinding`, on the selected managed clusters.

.Additional resources

* xref:../secure_clusters/fine_grain_mca_spec.adoc#fine-grain-mca-spec[Resource specification]
* xref:../secure_clusters/fine_grain_mca_binding.adoc#fine-grain-mca-binding[Binding scope]
* xref:../secure_clusters/fine_grain_mca_placement.adoc#fine-grain-mca-placement[Placement examples]
* xref:../secure_clusters/fine_grain_mca_examples.adoc#fine-grain-mca-examples[_MulticlusterRoleAssignment_ examples for fine-grained role-based access control]
* xref:../secure_clusters/fine_grain_mca_custom.adoc#fine-grain-mca-custom[Managing custom roles with _MulticlusterRoleAssignment_]
