[#fine-grain-rbac-ui]
= Implementing fine-grained role-based access control with the console (Technology Preview)

*Technology Preview:* {acm} supports fine-grained role-based access control (RBAC). You can manage and control permissions at the namespace level and cluster level on your managed clusters. Grant permissions to a virtual machine namespace within a cluster without granting permission to the entire managed cluster.

Learn how to set up fine-grained RBAC from the console.

*Required access:* Cluster administrator

To learn about {ocp-short} default and virtualization roles and permissions, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/virtualization/about#authorization_virt-security-policies[Authorization] in the {ocp-short} documentation.

See xref:../secure_clusters/rbac_implement_rhacm.adoc#rhacm-rbac-implement[Implementing role-based access control] for more details about {acm-short} role-based access.

.Prerequisites

See the following requirements to begin using fine-grained role-based access control:

- You need to install the latest verrsion of {ocp-virt} on your hub cluster. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/virtualization/installing[Virtualization - Installing].
- To learn about {ocp-short} default and virtualization roles and permissions, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/virtualization/about#authorization_virt-security-policies[Authorization] in the {ocp-short} documentation.
- For details on how to enable role-based access control, see xref:../secure_clusters/rbac_implement_rhacm.adoc#rhacm-rbac-implement[Implementing role-based access control].

[#assign-fine-grain-rbac-ui]
== Assigning fine-grained role-based access control in the console

You can assign users to manage virtual machines with fine-grained role-based access control. Actions are disabled in the console if the user-role access is not permitted. Slide the *YAML* option on to see the data that you enter populate in the YAML editor.

You can grant access to the following roles for {ocp-virt-short}:

- `kubevirt.io:view`: only view resources
- `kubevirt.io:edit`: modify resources
- `kubevirt.io:admin`: view, modify, delete resources; grant permissions

To assign permissions to a user, complete the following steps:

. Navigate to your `MultiClusterHub` custom resource to edit the resource and enable the feature.
.. From the *local-cluster* view, click *Operators* > *Installed Operators* > *Advanced Cluster Management for Kubernetes*. 
.. Click the *MultiClusterHub* tab to edit the resource. 
.. Slide the *YAML* option on to see the data in the YAML editor.
.. In your `MultiClusterHub` custom resource `spec.overrides.components` field, set `fine-grained-rbac-preview` to `true` to enable the feature. Change the `configOverrides` specification to `enabled: true` in the YAML editor and save your changes. See the following example with `fine-grained-rbac-preview` enabled:

+
[source,yaml]
----
    - configOverrides: {}
      enabled: true
      name: fine-grained-rbac-preview
----

. Label your `local-cluster` with `environment=virtualization`. Run the following command:

+
[source,bash]
----
oc label managedclusters local-cluster environment=virtualization
----

. *Optional:* If the `observability` service is enabled, create an additional `RoleBinding` resource on the hub cluster so that users can view virtual machine details in Grafana.
. Navigate to the *Identities* page from the console by clicking *User Management* > *Identities*.
. To view existing users or groups on your hub cluster, select either the _Users_ or _Groups_ tab. 
. To view your existing role assignments, click the *Role assignments* tab.
. If you do not have any role assignments, create a role assignment by clicking the *Create role assignment* button.
. Select the scope of your role assignment.
. If you choose the *Select specific* option, a list of available clusters and namespaces appear.
. Select the specific cluster set where you want to assign the role.
. Move your selection to the _Chosen options_ section.
. Select the cluster set to see the list of _Select shared namespaces_.
. Select the namespaces that you want to target. 
. Select the *Create* button to create the role assignment. Your role assignment appears from the *Role assignments* tab.
