:_mod-docs-content-type: PROCEDURE

[#rbac-enable-governance]
= Enabling RBAC for Governance

[role="_abstract"]
For Governance actions, you need access to the namespace where the policy is created, along with access to the managed cluster where the policy is applied. The managed cluster must also be part of a `ManagedClusterSet` that is bound to the namespace.

After you select a namespace, such as `rhacm-policies`, with one or more bound `ManagedClusterSets`, and after you have access to create `Placement` objects in the namespace, complete the following steps:

.Procedure

. To create a `ClusterRole` named `rhacm-edit-policy` with `Policy`, `PlacementBinding`, and `PolicyAutomation` edit access, run the following command:

+
[source,bash]
----
oc create clusterrole rhacm-edit-policy --resource=policies.policy.open-cluster-management.io,placementbindings.policy.open-cluster-management.io,policyautomations.policy.open-cluster-management.io,policysets.policy.open-cluster-management.io --verb=create,delete,get,list,patch,update,watch
----

. To create a policy in the `rhacm-policies` namespace, create a namespace `RoleBinding`, such as `rhacm-edit-policy`, to the `rhacm-policies` namespace using the `ClusterRole` created previously. Run the following command:

+
[source,bash]
----
oc create rolebinding rhacm-edit-policy -n rhacm-policies --clusterrole=rhacm-edit-policy --user=<username>
----

. To view policy status of a managed cluster, you need permission to view policies in the managed cluster namespace on the hub cluster. If you do not have `view` access, such as through the OpenShift `view` `ClusterRole`, create a `ClusterRole`, such as `rhacm-view-policy`, with view access to policies with the following command:

+
[source,bash]
----
oc create clusterrole rhacm-view-policy --resource=policies.policy.open-cluster-management.io --verb=get,list,watch
----

. To bind the new `ClusterRole` to the managed cluster namespace, run the following command to create a namespace `RoleBinding`:

+
[source,bash]
----
oc create rolebinding rhacm-view-policy -n <cluster name> --clusterrole=rhacm-view-policy --user=<username>
----

.Additional resources

* link:../clusters/cluster_lifecycle/clusterset_intro.adoc#managedclustersets-intro[ManagedClusterSets Introduction]
