:_mod-docs-content-type: PROCEDURE

[#add-policy-policy-set]
= Adding a policy to a policy set 

[role="_abstract"]
Add an existing policy to a policy set from the command-line interface or console.

.Procedure
. Add a policy to a policy set from the command-line interface:

.. Run the following command to edit your policy set: 

+
[source,bash]
----
oc edit policysets <your-policyset-name>
----

. Add the policy name to the list in the `policies` section of the policy set. 

. Apply your added policy in the placement section of your policy set with the following command: 

+
[source,bash]
----
oc apply -f <your-added-policy.yaml>
----
+ 
*Note:* If you delete the placement binding, the policy is still placed by the policy set.

`PlacementBinding` and `Placement` are both created.

. Add a policy to a policy set from the console:

.. Add a policy to the policy set by selecting the _Policy sets_ tab. 

.. Select the Actions icon and select *Edit*. The _Edit policy set_ form appears.

.. Navigate to the _Policies_ section of the form to select a policy to add to the policy set. 
