[#adv-template-processing]
= Advanced template processing in configuration policies

Use both managed cluster and hub cluster templates to reduce the need to create separate policies for each target cluster or hardcode configuration values in the policy definitions. For security, both resource-specific and the generic lookup functions in hub cluster templates are restricted to the namespace of the policy on the hub cluster.

*Important:* If you use hub cluster templates to propagate secrets or other sensitive data, that causes sensitive data exposure in the managed cluster namespace on the hub cluster and on the managed clusters where that policy is distributed. The template content is expanded in the policy, and policies are not encrypted by the {ocp-short} ETCD encryption support. To address this, use `fromSecret` or `copySecretData`, which automatically encrypts the values from the secret, or `protect` to encrypt other values.

Continue reading for advanced template use-cases:

* <<special-annotation-processing,Special annotation for reprocessing>>
* <<raw-object-template-processing,Object template processing>>
* <<bypass-template-processing,Bypass template processing>>
* <<additional-resources-hub-temp,Additional resources>>

[#special-annotation-processing]
== Special annotation for reprocessing

Hub cluster templates are resolved to the data in the referenced resources during policy creation, or when the referenced resources are updated.

If you need to manually initiate an update, use the special annotation, `policy.open-cluster-management.io/trigger-update`, to indicate changes for the data referenced by the templates. Any change to the special annotation value automatically initiates template processing. Additionally, the latest contents of the referenced resource are read and updated in the policy definition that is propagated for processing on managed clusters. A way to use this annotation is to increment the value by one each time.

[#raw-object-template-processing]
== Object template processing

Set object templates with a YAML string representation. The `object-template-raw` parameter is an optional parameter that support if-else statements. You can specify conditions in the `object-templates` specification. The following example is defined to add the `species-category: mammal` label  to any ConfigMap in the `default` namespace that has a `name` key equal to `Sea Otter`:

[source,yaml]
----
object-templates-raw: |
{{- range (lookup "v1" "ConfigMap" "default" "").items }}
    {{- if eq .data.name "Sea Otter" }}
    - complianceType: musthave
      objectDefinition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: {{ .metadata.name }}
          namespace: {{ .metadata.namespace }}
          labels:
            species-category: mammal
    {{- end }}
    {{- end }}
----

*Note:* While `spec.object-templates` and `spec.object-templates-raw` are optional, at least one of the two parameter fields must be set. 
 
[#bypass-template-processing]
== Bypass template processing

You might create a policy that contains a template that is not intended to be processed by {product-title-short}. By default, {product-title-short} processes all templates. 

To bypass template processing for your hub cluster, you must change `{{ template content }}` to `{{ `{{ template content }}`` `}}`.

Alternatively, you can add the following annotation in the `ConfigurationPolicy` section of your `Policy`: `policy.open-cluster-management.io/disable-templates: "true"`. When this annotation is included, the previous workaround is not necessary. Template processing is bypassed for the `ConfigurationPolicy`.

[#additional-resources-hub-temp]
== Additional resources

* See xref:../governance/template_functions.adoc#template-functions[Template functions] for more details.
* Return to xref:../governance/template_support_intro.adoc#template-processing[Template processing].
* See xref:../governance/config_policy_ctrl.adockubernetes-configuration-policy-controller[Kubernetes configuration policy controller] for more details.
* Also refer to the link:https://docs.openshift.com/container-platform/4.11/security/encrypting-etcd.html[{ocp} etcd encryption documentation].
