:_mod-docs-content-type: PROCEDURE

[#ansible-integration-grc]
= Integrating {aap-short} with governance

[role="_abstract"]
Integrate {acm} governance capabilities with {aap} to enable automated remediation when policy violations occur. 

.Prerequisites

* A supported version of {ocp} installed.
* Install the latest supported version of {aap-short}. {acm-short} supports {aap-short} version 3.7.3 and later.

.Procedure

. Log in to the {ocp-short} cluster console.

. Navigate to the {olm} and select the *{aap-short} Resource Operator*. 

. In the _Update Channel_ section, select *`stable-2.x-cluster-scoped`*.

. Select the *All namespaces on the cluster (default)* installation mode to complete installation.

. *Optional:* You can install the {aap-short} Resource Operator on a cluster other than the hub cluster. If you install the {aap-short} Resource Operator on the hub cluster, the operator version must match the {aap-short} Tower version.

. Ensure that the {aap-short} job template is idempotent when you run it. If you do not have {aap-short} Resource Operator, you can find it from the {ocp-catalog}.

.Additional resources

* xref:../governance/create_policy_automation_cli.adoc#creating-policy-automation-cli[Creating a policy violation automation from the CLI]
* xref:../governance/create_policy_automation_console.adoc#creating-policy-automation-console[Creating a policy violation automation from the console]
* link:../applications/ansible_config.adoc#setting-up-ansible[Setting up Ansible tasks]
* link:https://docs.ansible.com/ansible-tower/[Red Hat {aap-short} documentation]