[#cert-manage]
= Managing certificates

Continue reading for information on how to refresh, replace, rotate, and list certificates.

- <<refresh-an-acm-webhook,Refreshing a {product-title-short} webhook certificate>>
- <<refresh-hub-cluster-managed-certificates,Refreshing hub cluster managed certificates>>
- <<replacing-cert-alertmanager,Replacing certificates for alertmanager route>>
- <<rotating-the-gatekeeper-webhook-certificate,Rotating the gatekeeper webhook certificate>>
- <<list-hub-cluster-managed-certificates,Listing hub cluster managed certificates>>

[#refresh-an-acm-webhook]
== Refreshing a {product-title-short} webhook certificate

You can refresh {ocp-short} managed certificates, which are certificates that are used by {product-title-short} webhooks. 

Complete the following steps to refresh {product-title-short} webhook certificate:

. Delete the secret that is associated with the {ocp-short} managed certificate by running the following command:
+
----
oc delete secret -n multicluster-engine ocm-webhook
----
+
*Note:* Some services might not have a secret that needs to be deleted.
. Restart the services that are associated with the {ocp-short} managed certificate(s) by running the following command:
+
----
oc delete pod -n multicluster-engine -l control-plane=ocm-webhook
----
+
*Important:* There are replicas of many services, each service must be restarted.

[#refresh-hub-cluster-managed-certificates]
== Refreshing hub cluster managed certificates 
//in terms of refreshing certificates, there is an ask to add instructions on refreshing certificates manually if the cert is not propagated by itself
//add reference to this section to cert_manage_overview.adoc
//request from the issue is to add instructions on how to update certificates after they are replaced
You can refresh a hub cluster managed certificate by running the `delete secret` command. When you identify the certificate that you need to refresh, delete the secret that is associated with the certificate. For example, you can delete a secret by running the following command::
+
[source,bash]
----
oc delete secret grc-0c925-grc-secrets -n open-cluster-management
----

*Note:* After you delete the secret, a new one is created. However, you must restart pods that use the secret manually so they can begin to use the new certificate.

[#replacing-cert-alertmanager]
== Replacing certificates for alertmanager route

You can replace alertmanager certificates by updating the alertmanager route, if you do not want to use the OpenShift default ingress certificate. Complete the following steps:

. Examine the observability certificate with the following command:
+
----
openssl x509  -noout -text -in ./observability.crt
----

. Change the common name (`CN`) on the certificate to `alertmanager`.

. Change the SAN in the `csr.cnf` configuration file with the hostname for your alertmanager route.

. Create the two following secrets in the `open-cluster-management-observability` namespace. Run the following commands:
+
----
oc -n open-cluster-management-observability create secret tls alertmanager-byo-ca --cert ./ca.crt --key ./ca.key

oc -n open-cluster-management-observability create secret tls alertmanager-byo-cert --cert ./ingress.crt --key ./ingress.key
----

[#rotating-the-gatekeeper-webhook-certificate]
== Rotating the gatekeeper webhook certificate

Complete the following steps to rotate the gatekeeper webhook certificate:

. Edit the secret that contains the certificate with the following command: 
+
----
oc edit secret -n openshift-gatekeeper-system gatekeeper-webhook-server-cert
----

. Delete the following content in the `data` section: `ca.crt`, `ca.key`, `tls.crt`, and `tls.key`.

. Restart the gatekeeper webhook service by deleting the `gatekeeper-controller-manager` pods with the following command:
+
----
oc delete pod -n openshift-gatekeeper-system -l control-plane=controller-manager
----

The gatekeeper webhook certificate is rotated. 
//If we want to keep the previous statement^, we must provide a verification step for the user to conform that the cert was rotated successfully

[#list-hub-cluster-managed-certificates]
== Listing hub cluster managed certificates

You can view a list of hub cluster managed certificates that use OpenShift Service Serving Certificates service internally. Run the following command to list the certificates: 

[source,bash]
----
for ns in multicluster-engine open-cluster-management ; do echo "$ns:" ; oc get secret -n $ns -o custom-columns=Name:.metadata.name,Expiration:.metadata.annotations.service\\.beta\\.openshift\\.io/expiry | grep -v '<none>' ; echo ""; done
----

For more information, see _OpenShift Service Serving Certificates_ in the _Additional resources_ section.

*Note:* If observability is enabled, there are additional namespaces where certificates are created.

[additional-resource-cert-manage]
== Additional resources

- link:https://docs.openshift.com/container-platform/4.11/security/certificates/service-serving-certificate.html[OpenShift Service Serving Certificates]
- xref:../governance/cert_manage_overview.adoc#cert-manage-overview[Managing certificates overview]
- Return to the beginning of this page, <<cert-manage,Managing certificates>>.