:_mod-docs-content-type: CONCEPT

[#cleanup-resources]
= Resource clean up for policies

[role="_abstract"]
Use the `pruneObjectBehavior` parameter in a configuration policy to clean up resources that are created by the policy. When `pruneObjectBehavior` is set, the related objects are only cleaned up after the configuration policy (or parent policy) associated with them is deleted. 

View the following descriptions of the values that can be used for the parameter:

`DeleteIfCreated`:: Cleans up any resources created by the policy.
`DeleteAll`:: Cleans up all resources managed by the policy.
`None`:: This is the default value and maintains the same behavior from previous releases, where no related resources are deleted.

You can set the value directly in the YAML file as you create a policy from the command line. 

From the console, you can select the value in the _Prune Object Behavior_ section of the _Policy templates_ step.

*Notes:*

* If a policy that installs an operator has the `pruneObjectBehavior` parameter defined, then additional clean up is needed to complete the operator uninstall. You might need to delete the operator `ClusterServiceVersion` object as part of this cleanup.

* As you disable the `config-policy-addon` resource on the managed cluster, the `pruneObjbectBehavior` is ignored. To automatically clean up the related resources on the policies, you must remove the policies from the managed cluster before the add-on is disabled.
