[#compliance-operator-policy]
= Compliance Operator policy

You can use the Compliance Operator to automate the inspection of numerous technical implementations and compare those against certain aspects of industry standards, benchmarks, and baselines. The Compliance Operator is not an auditor. To be compliant or certified with these various standards, you need to engage an authorized auditor such as a Qualified Security Assessor (QSA), Joint Authorization Board (JAB), or other industry recognized regulatory authority to assess your environment.  

Recommendations that are generated from the Compliance Operator are based on generally available information and practices regarding such standards, and might assist you with remediations, but actual compliance is your responsibility. Work with an authorized auditor to achieve compliance with a standard.

For the latest updates, see the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/security_and_compliance/compliance-operator#compliance-operator-release-notes[Compliance Operator release notes].


[#compliance-operator-policy-overview]
== Compliance Operator policy overview

You can install the Compliance Operator on your managed cluster by using the Compliance Operator policy. The Compliance Operator policy is created as a Kubernetes configuration policy in {acm-short}. {ocp-short} supports the Compliance Operator policy.

*Note:* The link:https://github.com/open-cluster-management/grc-ui/blob/main/src-web/components/common/templates/spec-comp-operator.yaml[Compliance operator policy] relies on the {ocp-short} Compliance Operator, which is not supported on the IBM Power or IBM Z architectures. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/security_and_compliance/compliance-operator#understanding-compliance-operator[Understanding the Compliance Operator] in the {ocp-short} documentation for more information about the Compliance Operator.

//is this note valid? who can confirm this? Is it important to mention which architecture do not support the Compliance Operator?

[#compliance-operator-resources]
== Compliance operator resources

When you create a compliance operator policy, the following resources are created:

- A compliance operator namespace (`openshift-compliance`) for the operator installation:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: comp-operator-ns
spec:
  remediationAction: inform # will be overridden by remediationAction in parent policy
  severity: high
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-compliance
----

- An operator group (`compliance-operator`) to specify the target namespace:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: comp-operator-operator-group
spec:
  remediationAction: inform # will be overridden by remediationAction in parent policy
  severity: high
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: compliance-operator
          namespace: openshift-compliance
        spec:
          targetNamespaces:
            - openshift-compliance
----

- A subscription (`comp-operator-subscription`) to reference the name and channel. The subscription pulls the profile, as a container, that it supports. See the following sample, with the current version replacing `4.x`:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: comp-operator-subscription
spec:
  remediationAction: inform  # will be overridden by remediationAction in parent policy
  severity: high
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: compliance-operator
          namespace: openshift-compliance
        spec:
          channel: "4.x"
          installPlanApproval: Automatic
          name: compliance-operator
          source: redhat-operators
          sourceNamespace: openshift-marketplace
----

After you install the compliance operator policy, the following pods are created: `compliance-operator`, `ocp4`, and `rhcos4`. See a sample of the link:https://github.com/open-cluster-management/policy-collection/blob/main/stable/CA-Security-Assessment-and-Authorization/policy-compliance-operator-install.yaml[`policy-compliance-operator-install.yaml`].

[#additional-resources-comp]
== Additional resources

- For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/security_and_compliance/index#compliance-operator-understanding[Managing the Compliance Operator] in the {ocp-short} documentation for more details.

- You can also create and apply the E8 scan policy and OpenShift CIS scan policy, after you have installed the compliance operator. For more information, see xref:../governance/e8_scan_policy.adoc#e8-scan-policy[E8 scan policy] and xref:../governance/ocp_cis_policy.adoc#ocp-cis-policy[OpenShift CIS scan policy].

- To learn about managing compliance operator policies, see xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies] for more details. Refer to xref:../governance/config_policy_ctrl.adoc#kubernetes-config-policy-controller[Kubernetes configuration policy controller] for more topics about configuration policies.
