:_mod-docs-content-type: CONCEPT

[#compliance-operator-policy]
= Compliance Operator policy

[role="_abstract"]
You can install the Compliance Operator on your managed cluster by using the Compliance Operator policy. The Compliance operator policy is created as a Kubernetes configuration policy in {acm-short}. {ocp-short} supports the compliance operator policy.

The Compliance Operator automates the inspection of numerous technical implementations and compare those against certain aspects of industry standards, benchmarks, and baselines. The Compliance Operator is not an auditing tool. To be compliant or certified with these various standards, you need to engage an authorized auditor such as a Qualified Security Assessor (QSA), Joint Authorization Board (JAB), or other industry recognized regulatory authority to assess your environment.  

Recommendations that are generated from the Compliance Operator are based on generally available information and practices regarding such standards, and might assist you with remediations, but actual compliance is your responsibility. Work with an authorized auditor to achieve compliance with a standard.

*Note:* The Compliance operator policy relies on the {ocp-short} Compliance Operator, which is not supported on the IBM Power or IBM Z architectures.

.Additional resources

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/security_and_compliance/compliance-operator#compliance-operator-release-notes[Compliance Operator release notes]

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/security_and_compliance/compliance-operator#understanding-compliance-operator[Understanding the Compliance Operator]

* link:https://github.com/open-cluster-management/grc-ui/blob/main/src-web/components/common/templates/spec-comp-operator.yaml[Compliance operator policy]

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html-single/security_and_compliance/index#compliance-operator-understanding[Managing the Compliance Operator]

* xref:../governance/e8_scan_policy.adoc#e8-scan-policy[E8 scan policy]

* xref:../governance/ocp_cis_policy.adoc#ocp-cis-policy[OpenShift CIS scan policy]

* xref:../governance/manage_policies.adoc#creating-security-policies[Creating security policies]

* xref:../governance/config_policy_ctrl.adoc#kubernetes-config-policy-controller[Kubernetes configuration policy controller]

* link:../governance/compliance_operator_resources.adoc#compliance-operator-resources[Compliance Operator resources]
