[#managing-pod-policies]
= Managing pod policies

Kubernetes configuration policy controller monitors the status of your pod policies.
Pod policies are applied to define the container rules for your pods.

Learn to create, apply, view, and update your pod policy:

* <<creating-a-pod-policy,Creating a pod policy>>
* <<updating-pod-policies,Updating pod policies>>
* <<deleting-a-pod-policy,Deleting a pod policy>>

[#creating-a-pod-policy]
== Creating a pod policy

You can create a YAML for your pod policy from the command line interface (CLI) or from the console.
View the following sections to create a pod policy:

[#creating-a-pod-policy-from-the-cli]
=== Creating a pod policy from the CLI

Complete the following steps to create a pod policy from the CLI:

. Create a YAML file for your pod policy by running the following command:
+
----
kubectl create -f podpolicy-1.yaml
----

. Apply the policy by running the following command:
+
----
kubectl apply -f <pod-policy-file-name>  --namespace=<namespace>
----

. List and verify the policies by running the following command:
+
----
kubectl get podpolicy --namespace=<namespace>
----

Your image pod policy is created from the CLI.

[#viewing-your-policy-from-the-cli]
==== Viewing your policy from the CLI

Complete the following steps to view your pod policy from the CLI:

. View details for a specific pod policy by running the following command:
+
----
kubectl get podpolicy <policy-name> -n <namespace> -o yaml
----

. View a description of your pod policy by running the following command:
+
----
kubectl describe podpolicy <name> -n <namespace>
----

[#creating-an-pod-policy-from-the-console]
=== Creating an pod policy from the console

As you create a pod policy from the console, a YAML file is also created in the YAML editor.
Complete the following steps to create the pod policy from the console:

. Log in to your {product-title} console.
. From the navigation menu, click *Governance*.
. Click *Create policy*.
. Select *Pod* from the _Specifications_ field.
Parameter values are automatically set.
You can edit your values.
. Click *Create*.

[discrete#viewing-your-pod-policy-from-the-console]
==== Viewing your pod policy from the console

You can view any pod policy and its status from the console.

. Log in to your cluster from the console.
. From the navigation menu, click *Governance* to view a table list of your policies.
+
*Note:* You can filter the table list of your policies by selecting the _Policies_ tab or _Cluster violations_ tab.

. Select one of your policies to view more details.
. View the policy violations by selecting the _Status_ tab.

[#updating-pod-policies]
== Updating pod policies

Learn to update pod policies by viewing the following section.

[#disabling-pod-policies]
=== Disabling pod policies

Complete the following steps to disable your pod policy:

. Log in to your {product-title} console.
. From the navigation menu, click *Governance* to view a table list of your policies.
. Disable your policy by clicking the *Actions* icon > *Disable*.
The _Disable Policy_ dialog box appears.
. Click *Disable policy*.

Your policy is disabled.

[#deleting-a-pod-policy]
== Deleting a pod policy

Delete the pod policy from the CLI or the console.

* Delete a pod policy from the CLI:
 .. Delete a pod policy by running the following command:

+
----
kubectl delete policy <podpolicy-name> -n <namespace>
----
+
After your policy is deleted, it is removed from your target cluster or clusters.

 .. Verify that your policy is removed by running the following command:
+
----
kubectl get policy <podpolicy-name> -n <namespace>
----
* Delete a pod policy from the console:
 .. From the navigation menu, click *Governance* to view a table list of your policies.
 .. Click the *Actions* icon for the policy you want to delete in the policy violation table.
 .. Click *Remove*.
 .. From the _Remove policy_ dialog box, click *Remove policy*.

Your pod policy is deleted.

To view a sample of a pod policy, see the _Pod policy sample_ from the xref:../governance/pod_policy.adoc#pod-policy-sample[Pod policy] page.
See xref:../governance/config_policy_ctrl.adoc#kubernetes-configuration-policy-controller[Kubernetes configuration policy controller] to learn about other configuration policies.
See xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies] to manage other policies.
