[#managing-security-policies]
= Managing security policies

Create a security policy to report and validate your cluster compliance based on your specified security standards, categories, and controls. To create a policy for {product-title}, you must create a YAML file on your managed clusters.

*Note*: You can copy and paste an existing policy in to the _Policy YAML_.
The values for the parameter fields are automatically entered when you paste your existing policy. You can also search the contents in your policy YAML file with the search feature.

View the following sections:

* <<creating-a-security-policy,Creating a security policy>>
** <<creating-a-security-policy-from-the-command-line-interface,Creating a security policy from the command line interface>>
** <<viewing-your-security-policy-from-the-cli,Viewing your security policy from the CLI>>
** <<creating-a-cluster-security-policy-from-the-console,Creating a cluster security policy from the console>>
** <<viewing-your-security-policy-from-the-console,Viewing your security policy from the console>>
** <<creating-policy-sets-cli,Creating policy sets from the CLI>>
** <<creating-policy-sets-ui,Creating policy sets from the console>>
* <<updating-security-policies,Updating security policies>>
** <<disabling-security-policies,Disabling security policies>>
* <<deleting-a-security-policy,Deleting a security policy>>
** <<deleting-policy-sets,Deleting policy sets from the console>>

[#creating-a-security-policy]
== Creating a security policy

You can create a security policy from the command line interface (CLI) or from the console.

**Required access**: Cluster administrator

*Important*: You must define a placement rule and placement binding to apply your policy to a specific cluster. Enter a valid value for the _Cluster selector_ field to define a `PlacementRule` and `PlacementBinding`. See https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements[Resources that support support set-based requirements] in the Kubernetes documentation for a valid expression. View the definitions of the objects that are required for your {product-title-short} policy:

* _PlacementRule_: Defines a _cluster selector_ where the policy must be deployed.
* _PlacementBinding_: Binds the placement to a placement rule.

View more descriptions of the policy YAML files in the xref:../governance/policy_example.adoc#policy-overview[Policy overview].

[#creating-a-security-policy-from-the-command-line-interface]
=== Creating a security policy from the command line interface

Complete the following steps to create a policy from the command line interface (CLI):

. Create a policy by running the following command:
+
----
kubectl create -f policy.yaml -n <namespace>
----

. Define the template that the policy uses.
Edit your `.yaml` file by adding a `templates` field to define a template.
Your policy might resemble the following YAML file:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy1
spec:
  remediationAction: "enforce" # or inform
  disabled: false # or true
  namespaces:
    include: ["default"]
    exclude: ["kube*"]
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          namespace: kube-system # will be inferred
          name: operator
        spec:
          remediationAction: "inform"
          object-templates:
          - complianceType: "musthave" # at this level, it means the role must exist and must have the following rules
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata:
              name: example
            objectDefinition:
              rules:
                - complianceType: "musthave" # at this level, it means if the role exists the rule is a musthave
                  apiGroups: ["extensions", "apps"]
                  resources: ["deployments"]
                  verbs: ["get", "list", "watch", "create", "delete","patch"]
----

. Define a `PlacementRule`.
Be sure to change the `PlacementRule` to specify the clusters where the policies need to be applied, either by `clusterNames`, or `clusterLabels`. View link:../applications/placement_sample.adoc#placement-rule-samples[Placement rule samples overview]
+
Your `PlacementRule` might resemble the following content:
+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement1
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterNames:
  - "cluster1"
  - "cluster2"
  clusterLabels:
    matchLabels:
      cloud: IBM
----

. Define a `PlacementBinding` to bind your policy and your `PlacementRule`.
Your `PlacementBinding` might resemble the following YAML sample:
+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding1
placementRef:
  name: placement1
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
- name: policy1
  apiGroup: policy.open-cluster-management.io
  kind: Policy
----

[#viewing-your-security-policy-from-the-cli]
==== Viewing your security policy from the CLI

Complete the following steps to view your security policy from the CLI:

. View details for a specific security policy by running the following command:
+
----
kubectl get securitypolicy <policy-name> -n <namespace> -o yaml
----

. View a description of your security policy by running the following command:
+
----
kubectl describe securitypolicy <name> -n <namespace>
----

[#creating-a-cluster-security-policy-from-the-console]
=== Creating a cluster security policy from the console

After you log into your {product-title-short}, navigate to the _Governance_ page and click *Create policy*.

As you create your new policy from the console, a YAML file is also created in the YAML editor. To view the YAML editor, select the toggle at the beginning of the _Create policy_ form to enable it.

Complete the _Create policy_ form, then select the *Submit* button. 

Your YAML file might resemble the following policy:

[source,yaml]
----
 apiVersion: policy.open-cluster-management.io/v1
 kind: Policy
 metadata:
   name: policy-pod
   annotations:
     policy.open-cluster-management.io/categories: 'SystemAndCommunicationsProtections,SystemAndInformationIntegrity'
     policy.open-cluster-management.io/controls: 'control example'
     policy.open-cluster-management.io/standards: 'NIST,HIPAA'
 spec:
   complianceType: musthave
   namespaces:
     exclude: ["kube*"]
     include: ["default"]
   object-templates:
   - complianceType: musthave
     objectDefinition:
       apiVersion: v1
       kind: Pod
       metadata:
         name: pod1
       spec:
         containers:
         - name: pod-name
           image: 'pod-image'
           ports:
           - containerPort: 80
   remediationAction: enforce
   disabled: false

 ---
 apiVersion: apps.open-cluster-management.io/v1
 kind: PlacementBinding
 metadata:
   name: binding-pod
 placementRef:
   name: placement-pod
   kind: PlacementRule
   apiGroup: apps.open-cluster-management.io
 subjects:
 - name: policy-pod
   kind: Policy
   apiGroup: policy.open-cluster-management.io

 ---
 apiVersion: apps.open-cluster-management.io/v1
 kind: PlacementRule
 metadata:
   name: placement-pod
 spec:
   clusterConditions:
     - type: ManagedClusterConditionAvailable
       status: "True"
   clusterLabels:
     matchLabels:
       cloud: "IBM"
----

Click *Create Policy*. A security policy is created from the console.

[#viewing-your-security-policy-from-the-console]
==== Viewing your security policy from the console

View any security policy and its status from the console.
Navigate to the _Governance_ page to view a table list of your policies. *Note*: You can filter the table list of your policies by selecting the _Policies_ tab or _Cluster violations_ tab.

Select one of your policies to view more details. The _Details_, _Clusters_, and _Templates_ tabs are displayed. When the cluster or policy status cannot be determined, the following message is displayed: `No status`.

[#creating-policy-sets-cli]
=== Creating policy sets from the CLI

By default, the policy set is created with no policies or placements. You must create a placement for the policy set and have at least one policy that exists on your cluster. When you create a policy set, you can add numerous policies. Run the following command to create a policy set from the CLI:

----
kubectl apply -f <policyset-filename>
----

[#creating-policy-sets-ui]
=== Creating policy sets from the console

From the navigation menu, select *Governance*. Then select the _Policy sets_ tab. Select the *Create policy set* button and complete the form. After you add the details for your policy set, select the *Submit* button.

View the stable `Policyets`, which require the policy generator for deployment, link:https://github.com/stolostron/policy-collection/tree/main/policygenerator/policy-sets/stable[PolicySets-- Stable].

[#updating-security-policies]
== Updating security policies

Learn to update security policies by viewing the following section.

[#adding-policy-set-cli]
=== Adding a policy to a policy set from the CLI

Run the following command to edit your policy set: `kubectl edit policysets your-policyset-name`

Add the policy name to the list in the `policies` section of the policy set. Apply your added policy in the placement section of your policy set with the following command: `kubectl apply -f your-added-policy.yaml`. A `PlacementBinding` and `PlacementRule` are created. *Note*: If you delete the placement binding, the policy is still placed by the policy set.

[#adding-a-policy-ui]
=== Adding a policy to a policy set from the console

Add a policy to the policy set by selecting the *_Policy sets_* tab. Select the Actions icon and select *Edit*. The _Edit policy set_ form appears.

Navigate to the _Policies_ section of the form to select a policy to add to the policy set. 

[#disabling-security-policies]
=== Disabling security policies

Your policy is enabled by default. Disable your policy from the console.

After you log into your {product-title} console, navigate to the _Governance_ page to view a table list of your policies.

Select the *Actions* icon > *Disable policy*. The _Disable Policy_ dialog box appears.

Click *Disable policy*. Your policy is disabled.

[#deleting-a-security-policy]
== Deleting a security policy

Delete a security policy from the CLI or the console.

* Delete a security policy from the CLI:
.. Delete a security policy by running the following command:
+
----
kubectl delete policy <securitypolicy-name> -n <open-cluster-management-namespace>
----
+
After your policy is deleted, it is removed from your target cluster or clusters. Verify that your policy is removed by running the following command: `kubectl get policy <securitypolicy-name> -n <open-cluster-management-namespace>`

* Delete a security policy from the console:
+
From the navigation menu, click *Governance* to view a table list of your policies. Click the *Actions* icon for the policy you want to delete in the policy violation table.
+
Click *Remove*. From the _Remove policy_ dialog box, click *Remove policy*

[#deleting-policy-sets]
=== Deleting policy sets from the console

From the _Policy sets_ tab, select the *Actions* icon for the policy set. When you click *Delete*, the _Permanently delete Policyset?_ dialogue box appears. 

Click the *Delete* button.

To manage other policies, see xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies] for more information.
Refer to xref:../governance/grc_intro.adoc#governance[Governance] for more topics about policies.
