[#managing-compliance-operator-policies]
= Managing compliance operator policies

Apply a compliance operator policy to install the {ocp} compliance operator. Learn to create, update, apply, view, and your compliance operator policy in the following sections.

* <<creating-a-compliance-operator-policy-from-the-console,Creating a compliance operator policy from the console>>
* <<updating-a-compliance-operator-policy,Updating a compliance operator policy>>
* <<deleting-a-compliance-operator-policy,Deleting a compliance operator policy>>

[#creating-a-compliance-operator-policy-from-the-console]
== Creating a compliance operator policy from the console

As you create a compliance operator policy from the console, a YAML file is also created in the YAML editor.

After you log into your hub cluster, select *Governance* from the navigation menu.
 
Click *Create policy*. As you complete the YAML form, select *ComplianceOperator* from the _Specifications_ field.

The following resources are created: compliance operator namespace (`openshift-compliance`), an operator group (`compliance-operator`), and a subscription (`comp-operator-subscription`).

*Note:* Enforce is supported. When you set the remediation action to `enforce` the policy installs the compliance operator. 

A compliance operator policy is created.

[#updating-a-compliance-operator-policy]
== Updating a compliance operator policy

Learn to update the compliance operator policy by viewing the following section.

[#viewing-a-compliance-operator-policy-from-the-console]
=== Viewing a compliance operator policy from the console

View any compliance operator policy and its status from the console.

After you log into your cluster from the console, click *Governance* from the navigation menu, to view a table list of your policies. *Note*: You can filter the table list of your policies by selecting the _Policies_ tab or _Cluster violations_ tab.

Select `policy-comp-operator` policy to view more details. View the policy violations by selecting the _Clusters_ or _Templates_ tab.

[#disabling-a-compliance-operator-policy]
=== Disabling a compliance operator policy

Disbale the compliance operator policy, `policy-comp-operator`. Similar to the instructions in the previous section, navigate to _Governance_ page to view `policy-comp-operator` in the table list.

Disable `policy-comp-operator` by clicking the *Actions* icon > *Disable*.
The _Disable Policy_ dialog box appears. Click *Disable policy*.

Your compliance operator policy is disabled.

[#deleting-a-compliance-operator-policy]
== Deleting a compliance operator policy

Delete the compliance operator policy from the CLI or the console.

* Delete compliance operator policy from the CLI:
 . Delete compliance operator policy by running the following command:
+
----
kubectl delete policy <policy-comp-operator-name> -n <namespace>
----
+
After your policy is deleted, it is removed from your target cluster or clusters.

 . Verify that your policy is removed by running the following command:
+
----
kubectl get policy <policy-comp-operator-name> -n <namespace>
----

* Delete compliance operator policy from the console:

  After you log into your cluster, navigate to the _Governance_ page to view the table list of your policies. Click the *Actions* icon for the `policy-comp-operator` policy to delete in the policy violation table.
 
  Click *Remove*. From the _Remove policy_ dialog box, click *Remove policy*.

Your compliance operator policy is deleted.

For more details about the compliance operator policy, see xref:../governance/compliance_operator_policy.adoc#compliance-operator-policy[Compliance operator policy].





