[#managing-configuration-policies]
= Managing configuration policies

Learn to create, apply, view, and update your configuration policies.

*Required access*: Administrator or cluster administrator

* <<creating-a-configuration-policy,Creating a configuration policy>>
* <<disabling-configuration-policies,Disabling configuration policies>>
* <<deleting-a-configuration-policy,Deleting a configuration policy>>

[#creating-a-configuration-policy]
== Creating a configuration policy

You can create a YAML file for your configuration policy from the command line interface (CLI) or from the console. As you create a configuration policy from the console, a YAML file is displayed in the YAML editor.

If you have an existing Kubernetes manifest, consider using the Policy Generator to automatically include the manifests in a policy. See the xref:../governance/policy_generator.adoc#policy-generator[Policy Generator] documentation. View the following sections to create a configuration policy:

[#creating-a-configuration-policy-from-the-cli]
=== Creating a configuration policy from the CLI

Complete the following steps to create a configuration policy from the (CLI):

. Create a YAML file for your configuration policy.
Run the following command:

+
[source,bash]
----
oc create -f configpolicy-1.yaml
----
+
Your configuration policy might resemble the following policy:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-1
  namespace: my-policies
policy-templates:
- apiVersion: policy.open-cluster-management.io/v1
  kind: ConfigurationPolicy
  metadata:
    name: mustonlyhave-configuration
  spec:
    namespaceSelector:
      include: ["default"]
      exclude: ["kube-system"]
    remediationAction: inform
    disabled: false
    complianceType: mustonlyhave
    object-templates:
----

. Apply the policy by running the following command:

+
[source,bash]
----
oc apply -f <policy-file-name>  --namespace=<namespace>
----

. Verify and list the policies by running the following command:

+
[source,bash]
----
oc get policies.policy.open-cluster-management.io --namespace=<namespace>
----

Your configuration policy is created.

[#viewing-your-configuration-policy-from-the-cli]
=== Viewing your configuration policy from the CLI

Complete the following steps to view your configuration policy from the CLI:

. View details for a specific configuration policy by running the following command:

+
[source,bash]
----
oc get policies.policy.open-cluster-management.io <policy-name> -n <namespace> -o yaml
----

. View a description of your configuration policy by running the following command:

+
[source,bash]
----
oc describe policies.policy.open-cluster-management.io <name> -n <namespace>
----

[#viewing-your-configuration-policy-from-the-console]
=== Viewing your configuration policy from the console

View any configuration policy and its status from the console.

After you log in to your cluster from the console, select *Governance* to view a table list of your policies. *Note:* You can filter the table list of your policies by selecting the _All policies_ tab or _Cluster violations_ tab. 

Select one of your policies to view more details. The _Details_, _Clusters_, and _Templates_ tabs are displayed.

[#disabling-configuration-policies]
== Disabling configuration policies

Disable your configuration policy. Similar to the instructions mentioned earlier, log in and navigate to the _Governance_ page to complete the tasks.

. Select the *Actions* icon for a configuration policy from the table list, then click *Disable*. The _Disable Policy_ dialog box appears.

. Click *Disable policy*.

The policy is disabled, but not deleted.

[#deleting-a-configuration-policy]
== Deleting a configuration policy

Delete a configuration policy from the CLI or the console. Complete the following steps:

. to delete the policy from your target cluster or clusters, run the following command:

+
[source,bash]
----
oc delete policies.policy.open-cluster-management.io <policy-name> -n <namespace>
----

. Verify that your policy is removed by running the following command:

+
[source,bash]
----
oc get policies.policy.open-cluster-management.io <policy-name> -n <namespace>
----

. To delete a configuration policy from the console, click the *Actions* icon for the policy you want to delete in the policy violation table and then click *Remove*. 

Your policy is deleted.

[#add-resource-config-pol]
== Additional resources

- See configuration policy samples that are supported by {acm-short} from the link:https://github.com/open-cluster-management/policy-collection/tree/main/stable/CM-Configuration-Management[CM-Configuration-Management folder].

- Alternatively, you can refer to the xref:../governance/supported_policies.adoc#configuration-policy-sample-table[Table of sample configuration policies] to view other configuration policies that are monitored by the controller. For details to manage other policies, refer to xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies]. 
