[#enable-integrity-shield]
= Enable integrity shield protection (Technology Preview)

Enable integrity shield protection in an {product-title} cluster to protect the integrity of Kubernetes resources. 

[#prerequisites-integrity-shield]
== Prerequisites

The following prerequisites are required to enable integrity shield protection on a {product-title-short} managed cluster:

* Install an {product-title-short} hub cluster that has one or more managed clusters, along with cluster administrator access to the cluster to use the `oc` or `kubectl` commands. 

* Install integrity shield. Before you instal the integrity shield, you must install an Open Policy Agent or gatekeeper on your cluster. Complete the following steps to install the integrity shield operator:
+
.. Install the integrity shield operator in your namespace by running the following command:
+
----
kubectl create -f https://raw.githubusercontent.com/open-cluster-management/integrity-shield/master/integrity-shield-operator/deploy/integrity-shield-operator-latest.yaml
----
//is there a specific namespace where this should be installed?

.. Install the integrity shield custom resource with the following command:
+
----
kubectl create -f https://raw.githubusercontent.com/open-cluster-management/integrity-shield/master/integrity-shield-operator/config/samples/apis_v1_integrityshield.yaml -n integrity-shield-operator-system
----

