:_mod-docs-content-type: PROCEDURE

[#enabling-standalone-hub-templating]
= Enable standalone hub cluster templating

[role="_abstract"]
Enable the `governance-standalone-hub-templating` add-on to resolve hub cluster templates on a managed cluster when you deploy configuration policies directly to managed clusters, for example, by using GitOps.

*Required access:* Cluster administrator

.Procedure

. Go to the managed cluster namespace on your hub cluster.
. Create a `ManagedClusterAddOn` resource named `governance-standalone-hub-templating` by applying the following YAML configuration:

+
[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: governance-standalone-hub-templating
  namespace: <cluster_name>
  labels:
    cluster.open-cluster-management.io/backup: ''
spec:
  installNamespace: open-cluster-management-agent-addon
----
+
*Notes:* 

* The `spec.installNamespace` field is deprecated.

* The agent on the managed cluster accesses the `ManagedCluster` resources on the hub cluster. You can use the `.ManagedClusterLabels` template variable in the hub cluster templates inside the `ConfigurationPolicies` that you deploy directly to the managed cluster.

. Grant specific permissions to the add-on group to allow the hub template to access other resources through functions like `lookup` or `fromConfigMap`.

.Additional resources

* xref:../governance/granting_addon_permissions.adoc#granting-permissions-standalone-hub-templating[Standalone hub cluster templating permissions]
