:_mod-docs-content-type: CONCEPT

[#etcd-resources]
= etcd encryption policy policy schema and parameters

[role="_abstract"]
Review the YAML structure of the `etcd-encryption` policy. The `etcd-encryption` policy is a Kubernetes configuration policy in {acm-short} that detects or enables encryption of sensitive data in the etcd data store. The Kubernetes configuration policy controller monitors the status of the `etcd-encryption` policy.

* etcd encryption policy YAML structure:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name:
  namespace:
  annotations:
    policy.open-cluster-management.io/standards:
    policy.open-cluster-management.io/categories:
    policy.open-cluster-management.io/controls:
    policy.open-cluster-management.io/description:
spec:
  remediationAction:
  disabled:
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name:
        spec:
          remediationAction:
          severity:
          object-templates:
            - complianceType:
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: APIServer
                metadata:
                  name:
                spec:
                  encryption:
                ...
----

* etcd encryption policy table:

.Parameter table
|===
| Field | Optional or required | Description

| `apiVersion`
| Required
| Set the value to `policy.open-cluster-management.io/v1`.

| `kind`
| Required
| Set the value to `Policy` to indicate the type of policy.

| `metadata.name`
| Required
| The name for identifying the policy resource.

| `metadata.namespace`
| Required
| The namespace of the policy.

| `spec.remediationAction`
| Optional
| Specifies the remediation of your policy. The parameter values are `enforce` and `inform`. This value is optional because it overrides any values provided in `spec.policy-templates`.

| `spec.disabled`
| Required
| Set the value to `true` or `false`. The `disabled` parameter provides the ability to enable and disable your policies.

| `spec.policy-templates[].objectDefinition`
| Required
| Lists configuration policies that contain Kubernetes objects to evaluate or apply on the managed clusters.
|===