[#gatekeeper-operator-installation]
== {gk-operator} installation

Use the {gk-operator} policy to install the {gk-operator} and Gatekeeper on a managed cluster. Learn to create, view, and update your {gk-operator} policies in the following sections.

*Required access*: Cluster administrator

- <<install-gatekeeper-operator-policy,Installing Gatekeeper using a {gk-operator} policy>>
- <<creating-a-gatekeeper-policy-from-the-console,Creating a Gatekeeper policy from the console>>
- <<gatekeeper-operator-sample,{gk-operator} custom resource>>
- <<../gatekeeper_yaml_table.adoc#gatekeeper-yaml-table,Gatekeeper YAML table>>
- <<upgrading-gatekeeper-gatekeeper-operator,Upgrading Gatekeeper and the {gk-operator}>>
- <<updating-gatekeeper-operator-policy,Updating {gk-operator} policy>>
- <<deleting-gatekeeper-operator-policy,Deleting {gk-operator} policy>>
- <<uninstalling-gatekeeper,Uninstalling Gatekeeper policy, Gatekeeper, and {gk-operator} policy>>

[#install-gatekeeper-operator-policy]
=== Installing Gatekeeper using a {gk-operator} policy

Use the governance framework to install the {gk-operator} with a `Policy`. During the install, the operator group and subscription pull the {gk-operator} to install it in your managed cluster using an `OperatorPolicy`. Then, a pair of `ConfigurationPolicy` resources create a Gatekeeper custom resource to configure and deploy Gatekeeper and monitor the deployment status. View the <<gatekeeper-operator-sample,{gk-operator} custom resource>> sample.

{gk-operator} policy is monitored by the {product-title-short} configuration policy controller, where `enforce` remediation action is supported. The {gk-operator} objects from the policy are created automatically by the controller when set to `enforce`.

[#creating-a-gatekeeper-policy-from-the-console]
=== Creating a Gatekeeper policy from the console

See the following procedure to create the policy from the console:

. Install the Gatekeeper policy by creating a policy from the console. Alternatively, you can navigate to the _Additional resources_ section for a reference to the sample YAML to deploy `policy-gatekeeper-operator.yaml`.

. After you log in to your cluster, navigate to the _Governance_ page.

. Select *Create policy*. 

. As you complete the form, select *Install Red Hat {gk-operator} policy* from the _Policy templates_ field. The parameter values for your policy are populated with default values, and the policy is set to `inform` by default.

. Once you're satisfied with the configuration, set your remediation action to `enforce` to install Gatekeeper on the managed clusters.

[#upgrading-gatekeeper-gatekeeper-operator]
== Upgrading Gatekeeper using a {gk-operator} policy

You can upgrade the versions for Gatekeeper and the {gk-operator}. When you install the {gk-operator} with the {gk-operator} policy, notice the value for `installPlanApproval`. The operator upgrades automatically when `installPlanApproval` is set to `Automatic`. 

You must approve the upgrade of the {gk-operator} manually for each managed cluster, when `installPlanApproval` is set to `Manual`.

[#updating-gatekeeper-operator-policy]
== Managing the {gk-operator} policy

Learn to update the {gk-operator} policy by viewing the following section.

[#viewing-gatekeeper-operator-policy-from-the-console]
=== Viewing the {gk-operator} policy from the console

View your {gk-operator} policy and the status from the console.

After you log in to your cluster from the console, click *Governance* and then select the _Policies_ tab to view a table list of your policies.

Select the `policy-gatekeeper-operator` policy to view more details. View the policy violations by selecting the _Clusters_ tab.

[#disabling-gatekeeper-operator-policy]
=== Disabling the {gk-operator} policy

Disable your {gk-operator} policy.

After you log in to your {product-title} console, navigate to the _Governance_ page to view a table list of your policies.

Select the *Actions* icon for the `policy-gatekeeper-operator` policy, then click *Disable*. The _Disable Policy_ dialog box appears.

Click *Disable policy*. Your `policy-gatekeeper-operator` policy is disabled.

[#deleting-gatekeeper-operator-policy]
== Deleting the {gk-operator} policy

Delete the {gk-operator} policy from the CLI or the console.

* Delete {gk-operator} policy from the CLI:
 .. Delete {gk-operator} policy by running the following command:
+
----
oc delete policies.policy.open-cluster-management.io <policy-gatekeeper-operator-name> -n <namespace>
----
+
After your policy is deleted, the policy is removed from your target cluster or clusters.

 .. Verify that your policy is removed by running the following command:
+
----
oc get policies.policy.open-cluster-management.io <policy-gatekeeper-operator-name> -n <namespace>
----

* Delete {gk-operator} policy from the console:
+
Navigate to the _Governance_ page to view a table list of your policies.
+
Similar to the previous console instructions, click the *Actions* icon for the `policy-gatekeeper-operator` policy. Click *Remove* to delete the policy. From the _Remove policy_ dialog box, click *Remove policy*.

Your {gk-operator} policy is deleted.

[#uninstalling-gatekeeper]
== Uninstalling Gatekeeper using a {gk-operator} policy

Complete the following steps to uninstall Gatekeeper policy, Gatekeeper, and {gk-operator} policy:

. Remove the Gatekeeper constraints and `ConstraintTemplate`s that are applied to your managed cluster:
.. Edit your {gk-operator} policy. Locate the `ConfigurationPolicy` template that you used to create the Gatekeeper `Constraint` and `ConstraintTemplate`.
.. Change the value for `complianceType` of the `ConfigurationPolicy` template to `mustnothave`.
.. Save and apply the policy.

. Remove Gatekeeper instance from your managed cluster:
.. Edit your {gk-operator} policy. Locate the `ConfigurationPolicy` template that you used to create the Gatekeeper custom resource.
.. Change the value for `complianceType` of the `ConfigurationPolicy` template to `mustnothave`.

. Remove the {gk-operator} that is on your managed cluster:
.. Edit your {gk-operator} policy. Locate the `OperatorPolicy` template that you used to create the {gk-operator} resources.
.. Change the value for `complianceType` of the `OperatorPolicy` template to `mustnothave`.

Gatekeeper and the {gk-operator} are uninstalled. If desired, you can now delete the {gk-operator} policy.

[#additional-resources-gk-operator]
== Additional resources

- See xref:../governance/gatekeeper/gatekeeper_operator_intro.adoc#gatekeeper-operator-intro[{gk-operator}] for details about the {gk-operator} upgrade channels and deployment.

- See xref:../governance/gatekeeper/gatekeeper_operator_{gk-latest}.adoc#gatekeeper-operator-sample-{gk-latest-tag}[{gk-operator} custom resource] for details about the custom resource provided for configuring the {gk-operator} deployment.

- See xref:../governance/gatekeeper_policy_constraints.adoc#gatekeeper-policy[Integrating Gatekeeper constraints and constraint templates] for details about deploying Gatekeeper constraints and `ConstraintTemplates` using the governance framework.

- See the link:https://github.com/open-cluster-management-io/policy-collection/blob/main/stable/CM-Configuration-Management/policy-gatekeeper-operator-downstream.yaml[Policy Gatekeeper] sample.

- See link:https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md#parameters[Gatekeeper Helm Chart] for an explanation of the optional parameters that can be used for the {gk-operator} policy.

- For a list of topics to integrate third-party policies with the product, see xref:../governance/third_party_policy_intro.adoc#integrate-third-party-policy-controllers[Integrate third-party policy controllers]. 
