[#gatekeeper-policy]
= Integrating Gatekeeper constraints and constraint templates

Gatekeeper is a validating webhook with auditing capabilities that can enforce custom resource definition-based policies that are run with the Open Policy Agent (OPA). You can install Gatekeeper on your cluster by using the Gatekeeper operator policy. Gatekeeper constraints can be used to evaluate Kubernetes resource compliance. You can leverage OPA as the policy engine, and use Rego as the policy language.

*Prerequisite:* A {product-title} or {ocp} Plus subscription is required to install Gatekeeper and apply Gatekeeper policies to your cluster. Gatekeeper is supported only on {ocp-short} versions, except version 3.11, supported by the latest version of {product-title-short}.

Gatekeeper policies are written using constraint templates (`ConstraintTemplates`) and constraints. View the following YAML examples that use Gatekeeper constraints in {product-title-short} policies:

* `ConstraintTemplates` and constraints: Use the Gatekeeper integration feature by using {product-title-short} policies for multicluster distribution of Gatekeeper constraints and Gatekeeper audit results aggregation on the hub cluster. The following example defines a Gatekeeper `ConstraintTemplate` and constraint (`K8sRequiredLabels`) to ensure the `gatekeeper` label is set on all namespaces:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: require-gatekeeper-labels-on-ns
spec:
  remediationAction: inform <1>
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: templates.gatekeeper.sh/v1beta1
        kind: ConstraintTemplate
        metadata:
          name: k8srequiredlabels
          annotations:
            policy.open-cluster-management.io/severity: low <2>
        spec:
          crd:
            spec:
              names:
                kind: K8sRequiredLabels
              validation:
                openAPIV3Schema:
                  properties:
                    labels:
                      type: array
                      items: string
          targets:
            - target: admission.k8s.gatekeeper.sh
              rego: |
                package k8srequiredlabels
                violation[{"msg": msg, "details": {"missing_labels": missing}}] {
                  provided := {label | input.review.object.metadata.labels[label]}
                  required := {label | label := input.parameters.labels[_]}
                  missing := required - provided
                  count(missing) > 0
                  msg := sprintf("you must provide labels: %v", [missing])
                }
    - objectDefinition:
        apiVersion: constraints.gatekeeper.sh/v1beta1
        kind: K8sRequiredLabels
        metadata:
          name: ns-must-have-gk
          annotations:
            policy.open-cluster-management.io/severity: low <2>
        spec:
          enforcementAction: dryrun
          match:
            kinds:
              - apiGroups: [""]
                kinds: ["Namespace"]
          parameters:
            labels: ["gatekeeper"]
----
+
<1> Since the `remediationAction` is set to `inform`, the `enforcementAction` field of the Gatekeeper constraint is overridden to `warn`. This means that Gatekeeper detects and warns you about creating or updating a namespace that is missing the `gatekeeper` label. If the policy `remediationAction` is set to `enforce`, the Gatekeeper constraint `enforcementAction` field is overridden to `deny`. In this context, this configuration prevents any user from creating or updating a namespace that is missing the `gatekeeper` label.
+
<2> *Optional:* Set a severity value for the `policy.open-cluster-management.io/severity` annotation for each Gatekeeper constraint or constraint template. Valid values are the same as for other {product-title-short} policy types: `low`, `medium`, `high`, or `critical`.
+
With the previous policy, you might receive the following policy status message: `warn - you must provide labels: {"gatekeeper"} (on Namespace default); warn - you must provide labels: {"gatekeeper"} (on Namespace gatekeeper-system)`. Once a policy containing Gatekeeper constraints or `ConstraintTemplates` is deleted, the constraints and `ConstraintTemplates` are also deleted from the managed cluster.
+
To view the Gatekeeper audit results for a specific managed cluster from the console, navigate to the policy template _Results_ page. If search is enabled, view the YAML of the Kubernetes objects that failed the audit. 
+
*Notes:* 

- The _Related resources_ section is only available when the audit results are generated by Gatekeeper version 3.9 or newer.
- The Gatekeeper audit functionality runs every minute by default. Audit results are sent back to the hub cluster to be viewed in the {product-title-short} policy status of the managed cluster.

* `policy-gatekeeper-admission`: Use the `policy-gatekeeper-admission` configuration policy within a {product-title-short} policy to check for Kubernetes API requests denied by the gatekeeper admission webhook:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: policy-gatekeeper-admission
spec:
  remediationAction: inform # will be overridden by remediationAction in parent policy
  severity: low
  object-templates:
    - complianceType: mustnothave
      objectDefinition:
        apiVersion: v1
        kind: Event
        metadata:
          namespace: openshift-gatekeeper-system # set it to the actual namespace where gatekeeper is running if different
          annotations:
            constraint_action: deny
            constraint_kind: K8sRequiredLabels
            constraint_name: ns-must-have-gk
            event_type: violation
----


[#additional-resources-gk]
== Additional resources

* See link:https://github.com/open-cluster-management-io/policy-collection/blob/main/stable/CM-Configuration-Management/policy-gatekeeper-operator-downstream.yaml[`policy-gatekeeper-operator.yaml`] for more details.

* For more details, see link:https://www.openpolicyagent.org/docs/latest/kubernetes-introduction/#what-is-opa-gatekeeper[What is OPA Gatekeeper].

* See xref:../governance/create_config_pol.adoc#managing-configuration-policies[Managing configuration policies] for more information about managing other policies.

* Refer to xref:../governance/grc_intro.adoc#governance[Governance] for more topics on the security framework. 
