:_mod-docs-content-type: CONCEPT

[#grc-dashboard]
= Governance dashboard

[role="_abstract"]
Use the Governance dashboard in the {acm-short} console to manage policies and policy set violations, and review fleet compliance from a single view.

* Governance page

+
The following tabs are displayed on the _Governance_ page: _Overview_, _Policy sets_, and _Policies_. Read the following descriptions to know which information is displayed:

- *Overview*
+
The following summary cards are displayed from the _Overview_ tab: _Policy set violations_, _Policy violations_, _Clusters_, _Categories_, _Controls_, and _Standards_.

- *Policy sets*
+
Create and manage hub cluster policy sets.

- *Policies*
+
** Create and manage security policies. The policy table displays the _Name_, _Namespace_, and  _Cluster violations_ of each policy.
+
** You can edit, enable or disable, set remediation to inform or enforce, or remove a policy by selecting the *Actions* icon. You can view the categories and standards of a specific policy by selecting the drop-down arrow to expand the row.
+
** Reorder your table columns in the _Manage column_ dialog box. Select the _Manage column_ icon for the dialog box to be displayed. To reorder your columns, select the _Reorder_ icon and move the column name. For columns that you want to appear in the table, click the checkbox for specific column names and select the *Save* button.

* Complete bulk actions by selecting multiple policies and clicking the *Actions* button. You can also customize your policy table by clicking the *Filter* button.
+
When you select a policy in the table list, the following tabs of information are displayed from the console:
+
** _Details_: Select the _Details_ tab to view policy details and placement details. In the _Placement_ table, the _Compliance_ column provides links to view the compliance of the clusters that are displayed.
** _Results_: Select the _Results_ tab to view a table list of all clusters that are associated to the policy. From the _Message_ column, click the *View details* link to view the template details, template YAML, and related resources. You can also view related resources. Click the *View history* link to view the violation message and a time of the last report.

.Additional resources

* link:../governance/manage_policies.adoc#creating-security-policies[Creating security policies]
* xref:../governance/create_config_pol.adoc#create-configuration-policies[Creating configuration policies]
* xref:../governance/gatekeeper_operator/manage_gk.adoc#managing-gk-policies[Managing the {gate} installation policies]
* link:../governance/grc_automation_config.adoc#grc-automation-config[Governance automation configuration]
* xref:../governance/ansible_grc.adoc#ansible-integration-grc[Integrating {aap-short} with governance]
* xref:../governance/grc_intro.adoc#governance[Governance]
