[#hub-templates]
= Support for hub cluster templates in configuration policies
//add whats new entry for the new functions
In addition to managed cluster templates that are dynamically customized to the target cluster, {product-title-short} also supports hub cluster templates to define configuration policies using values from the hub cluster. This combination reduces the need to create separate policies for each target cluster or hardcode configuration values in the policy definitions. 

Hub cluster templates are based on Golang text template specifications, and the `{{hub … hub}}` delimiter indicates a hub cluster template in a configuration policy.

For security, both resource-specific and the generic lookup functions in hub cluster templates are restricted to the namespace of the policy on the hub cluster. View the <<template-comparison-table,Comparison of hub and managed cluster templates>> for additional details.

*Important:* If you use hub cluster templates to propagate secrets or other sensitive data, the sensitive data exists in the managed cluster namespace on the hub cluster and on the managed clusters where that policy is distributed. The template content is expanded in the policy, and policies are not encrypted by the {ocp-short} ETCD encryption support. To address this, use `fromSecret`, which automatically encrypts the values from the Secret, or `protect` to encrypt other values.

[#template-processing]
== Template processing

A configuration policy definition can contain both hub cluster and managed cluster templates. Hub cluster templates are processed first on the hub cluster, then the policy definition with resolved hub cluster templates is propagated to the target clusters. On the managed cluster, the `ConfigurationPolicyController` processes any managed cluster templates in the policy definition and then enforces or verifies the fully resolved object definition.

[#special-annotation-processing]
== Special annotation for reprocessing

Hub cluster templates are resolved to the data in the referenced resources during policy creation, or when the referenced resources are updated.

If you need to manually initiate an update, use the special annotation, `policy.open-cluster-management.io/trigger-update`, to indicate changes for the data referenced by the templates. Any change to the special annotation value automatically initiates template processing. Additionally, the latest contents of the referenced resource are read and updated in the policy definition that is propagated for processing on managed clusters. A way to use this annotation is to increment the value by one each time.

[#bypass-template-processing]
== Bypass template processing

You might create a policy that contains a template that is not intended to be processed by {product-title-short}. By default, {product-title-short} processes all templates. 

To bypass template processing for your hub cluster, you must change `{{ template content }}` to `{{ `{{ template content }}`` `}}`.

Alternatively, you can add the following annotation in the `ConfigurationPolicy` section of your `Policy`: `policy.open-cluster-management.io/disable-templates: "true"`. When this annotation is included, the previous workaround is not necessary. Template processing is bypassed for the `ConfigurationPolicy`.

See the following table for a comparison of hub cluster and managed cluster templates:

[#template-comparison-table]
== Comparison of hub cluster and managed cluster templates

.Comparison table
|===
| Templates | Hub cluster | Managed cluster 

| Syntax
| Golang text template specification
| Golang text template specification

| Delimiter
| {{hub … hub}}
| {{ … }}

| Context
| A `.ManagedClusterName` variable is available, which at runtime, resolves to the name of the target cluster where the policy is propagated.
| No context variables

| Access control
| You can only reference namespaced Kubernetes objects that are in the same namespace as the `Policy` resource.
| You can reference any resource on the cluster.

| Functions
| A set of template functions that support dynamic access to Kubernetes resources and string manipulation. See <<template-functions,Template functions>> for more information. See the Access control row for lookup restrictions.

The `fromSecret` template function on the hub cluster stores the resulting value as an encrypted string on the replicated policy, in the managed cluster namespace. 

The equivalent call might use the following syntax: `{{hub "(lookup "v1" "Secret" "default" "my-hub-secret").data.message \| protect hub}}`
| A set of template functions support dynamic access to Kubernetes resources and string manipulation. See <<template-functions,Template functions>> for more information.

| Function output storage
| The output of template functions are stored in `Policy` resource objects in each applicable managed cluster namespace on the hub cluster, before it is synced to the managed cluster. This means that any sensitive results from template functions are readable by anyone with read access to the `Policy` resource objects on the hub cluster, and read access with `ConfigurationPolicy` resource objects on the managed clusters. Additionally, if link:https://docs.openshift.com/container-platform/4.11/security/encrypting-etcd.html[etcd encryption] is enabled, the `Policy` and `ConfigurationPolicy` resource objects are not encrypted. It is best to carefully consider this when using template functions that return sensitive output (e.g. from a secret).
| The output of template functions are not stored in policy related resource objects.

| Processing
| Processing occurs at runtime on the hub cluster during propagation of replicated policies to clusters. Policies and the hub cluster templates within the policies are processed on the hub cluster only when templates are created or updated.
| Processing occurs in the `ConfigurationPolicyController` on the managed cluster. Policies are processed periodically, which automatically updates the resolved object definition with data in the referenced resources.

| Processing errors
| Errors from the hub cluster templates are displayed as violations on the managed clusters the policy applies to.
| Errors from the managed cluster templates are displayed as violations on the specific target cluster where the violation occurred.
|===

[#additional-resources-hub-temp]

== Additional resources


