[#iam-policy-controller]
= IAM policy controller

The Identity and Access Management (IAM) policy controller can be used to receive notifications about IAM policies that are non-compliant.
The compliance check is based on the parameters that you configure in the IAM policy.

The IAM policy controller monitors for the desired maximum number of users with a particular cluster role (i.e. `ClusterRole`) in your cluster. The default cluster role to monitor is `cluster-admin`. The IAM policy controller communicates with the local Kubernetes API server. For more information, see https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions].

The IAM policy controller runs on your managed cluster. View the following sections to learn more:

* <<iam-policy-yaml-structure,IAM policy YAML structure>>
* <<iam-policy-yaml-table,IAM policy YAML table>>
* <<iam-policy-sample,IAM policy sample>>

[#iam-policy-yaml-structure]
== IAM policy YAML structure

View the following example of an IAM policy and review the parameters in the YAML table:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: IamPolicy 
metadata:
  name:
spec:
  clusterRole:
  severity:
  remediationAction: 
  maxClusterRoleBindingUsers:
  ignoreClusterRoleBindings:
----

[#iam-policy-yaml-table]
== IAM policy YAML table

View the following parameter table for descriptions:

.Parameter table
|===
| Field | Description

| apiVersion
| Required.
Set the value to `policy.open-cluster-management.io/v1`.

| kind
| Required.
Set the value to `Policy` to indicate the type of policy.

| metadata.name
| Required.
The name for identifying the policy resource.

| spec
| Required.
Add configuration details for your policy.

| spec.clusterRole
| Optional.
The cluster role (i.e. `ClusterRole`) to monitor. This defaults to `cluster-admin` if not specified.

| spec.severity
| Optional.
Informs the user of the severity when the policy is non-compliant. Use the following parameter values: `low`, `medium`, or `high`.

| spec.remediationAction
| Optional.
Specifies the remediation of your policy.
Enter  `inform`.

| spec.ignoreClusterRoleBindings
| Optional.
A list of regular expression (regex) values that indicate which cluster role binding names to ignore. These regular expression values must follow https://pkg.go.dev/regexp/syntax[Go regexp syntax]. By default, all cluster role bindings that have a name that starts with `system:` are ignored. It is recommended to set this to a stricter value. To not ignore any cluster role binding names, set the list to a single value of `.^` or some other regular expression that never matches.

| spec.maxClusterRoleBindingUsers
| Required.
Maximum number of IAM role bindings that are available before a policy is considered non-compliant.
|===


[#iam-policy-sample]
== IAM policy sample

See https://github.com/stolostron/policy-collection/blob/main/stable/AC-Access-Control/policy-limitclusteradmin.yaml[`policy-limitclusteradmin.yaml`] to view the IAM policy sample. See xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies] for more information.

Refer to xref:../governance/policy_controllers.adoc#policy-controllers[Policy controllers] for more topics.
