[#image-vulnerability-policy]
= Image vulnerability policy

Apply the image vulnerability policy to detect if container images have vulnerabilities by leveraging the Container Security Operator. The policy installs the Container Security Operator on your managed cluster if it is not installed.

The image vulnerability policy is checked by the Kubernetes configuration policy controller.
For more information about the Security Operator, see the _Container Security Operator_ from the link:https://github.com/quay/container-security-operator[Quay repository].

*Notes:*

* Image vulnerability policy is not functional during a disconnected installation.

* The Image vulnerability policy is not supported on the ARM architecture.

View the following sections to learn more:

* <<image-vulnerability-policy-yaml-structure,Image vulnerability policy YAML structure>>
* <<image-vulnerability-policy-sample,Image vulnerability policy sample>>

[#image-vulnerability-policy-yaml-structure]
== Image vulnerability policy YAML structure

When you create the container security operator policy, it involves the following policies:

- A policy that creates the subscription (`container-security-operator`) to reference the name and channel. This operator policy must have `spec.remediationAction` set to `enforce` to create the resources. View the following example:
+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: operatorpolicy-imagemanifestvuln
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Automatic
  subscription:
    name: container-security-operator
    namespace: openshift-operators
    source: redhat-operators
    sourceNamespace: openshift-marketplace
----

- An `inform` configuration policy to audit whether any `ImageManifestVuln` objects were created by the image vulnerability scans. View the following example:
+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: policy-imagemanifestvuln-example-imv
spec:
  remediationAction: inform  # will be overridden by remediationAction in parent policy
  severity: high
  namespaceSelector:
    exclude: ["kube-*"]
    include: ["*"]
  object-templates:
    - complianceType: mustnothave # mustnothave any ImageManifestVuln object
      objectDefinition:
        apiVersion: secscan.quay.redhat.com/v1alpha1
        kind: ImageManifestVuln # checking for a Kind
----

[#image-vulnerability-policy-sample]
== Image vulnerability policy sample

For more information, see: 

* See xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies] and `policy-imagemanifestvuln.yaml`. 
* Refer to xref:../governance/config_policy_ctrl.adoc#kubernetes-config-policy-controller[Kubernetes configuration policy controller] to view other configuration policies that are monitored by the configuration controller.
