[#integrity-shield]
= Integrity shield protection (Technology Preview)

Integrity shield is a tool that helps with integrity control for enforcing signature verification for any requests to create, or update resources. Integrity shield supports Open Policy Agent (OPA) and Gatekeeper, verifies if the requests have a signature, and blocks any unauthorized requests according to the defined constraint.

See the following integrity shield capabilities:

* Support the deployment of authorized Kubernetes manifests only.
* Support zero-drift in resource configuration unless the resource is added to the allowlist.
* Perform all integrity verification on the cluster such as enforcing the admission controller.
* Monitor resources continuously to report if unauthorized Kubernetes resources are deployed on the cluster.
* X509, GPG, and Sigstore signing are supported to sign Kubernetes manifest YAML files. Kubernetes integrity shield supports Sigstore signing by using the link:https://github.com/sigstore/k8s-manifest-sigstore[`k8s-manifest-sigstore`].

[#integrity-shield-arch]
== Integrity shield architecture

Integrity shield consists of two main components, API and Observer. Integrity shield operator supports the installation and management of the integrity shield components on your cluster. View the following description of the components:

* _Integrity shield API_ receives a Kubernetes resource from the OPA or gatekeeper, validates the resource that is included in the admission request, and sends the verification result to the OPA or gatekeeper. The integrity shield API uses the `verify-resource` feature of the `k8s-manifest-sigstore` internally to verify the Kubernetes manifest YAML file. Integrity shield API validates resources according to `ManifestingIntegrityConstraint`, which is a custom resource based on the constraint framework of OPA or gatekeeper.
* _Integrity shield Observer_ continuously verifies Kubernetes resources on clusters according to `ManifestingIntegrityConstraint` resources and exports the results to resources called, `ManifestIntegrityState`. Integrity shield Observer also uses `k8s-manifest-sigstore` to verify signatures.

// do we want to use either of the diagrams from the README? If yes, we need to put in a request to update the diagram
// will put in a request to add diagram
// Instead Kubernetes cluster use RHACM hub cluster
// View the following architecture diagram for the integrity shield operator

[#supported-versions]
== Supported versions

The following product versions support integrity shield protection:

* link:https://www.redhat.com/en/technologies/cloud-computing/openshift[{ocp} 4.7.1 and later]
* link:https://kubernetes.io/[Kubernetes v1.19.7 and later]
* link:https://github.com/open-policy-agent/gatekeeper[`gatekeeper-operator.v-.2.0`]
* link:https://github.com/open-policy-agent/gatekeeper[`gatekeeper v3.5`]

See xref:../governance/enable_integrity_shield.adoc#enable-integrity-shield[Enable integrity shield protection (Technology Preview)] for more details.
