[#manage-dashboard]
= Manage Governance dashboard

Manage your security policies and policy violations by using the _Governance_ dashboard to create, view, and edit your resources. You can create YAML files for your policies from the command line and console. Continue reading for details about the _Governance_ dashboard from the console.

[#grc-view]
== Governance page

The following tabs are displayed on the _Governance_ page _Overview_, _Policy sets_, and _Policies_. Read the following descriptions to know which information is displayed:

- *Overview*
+
The following summary cards are displayed from the _Overview_ tab: _Policy set violations_, _Policy violations_, _Clusters_, _Categories_, _Controls_, and _Standards_.

- *Policy sets*
+
Create and manage hub cluster policy sets.

- *Policies*
+
* Create and manage security policies. The table of policies list the following details of a policy: _Name_, _Namespace_, and  _Cluster violations_ are displayed.
+
* You can edit, enable or disable, set remediation to inform or enforce, or remove a policy by selecting the *Actions* icon. You can view the categories and standards of a specific policy by selecting the drop-down arrow to expand the row.
+
* Reorder your table columns in the _Manage column_ dialog box. Select the _Manage column_ icon for the dialog box to be displayed. To reorder your columns, select the _Reorder_ icon and move the column name. For columns that you want to appear in the table, click the check box for specific column names and select the *Save* button.

* Complete bulk actions by selecting multiple policies and clicking the *Actions* button. You can also customize your policy table by clicking the *Filter* button.
+
When you select a policy in the table list, the following tabs of information are displayed from the console:
+
** _Details_: Select the _Details_ tab to view policy details and placement details. In the _Placement_ table, the _Compliance_ column provides links to view the compliance of the clusters that are displayed.
** _Results_: Select the _Results_ tab to view a table list of all clusters that are associated to the policy. 
+
- From the _Message_ column, click the **View details** link to view the template details, template YAML, and related resources. You can also view related resources. Click the **View history** link to view the violation message and a time of the last report.


[#grc-automation-configuration]
== Governance automation configuration

If there is a configured automation for a specific policy, you can select the automation to view more details. View the following descriptions of the schedule frequency options for your automation:

- _Manual run_: Manually set this automation to run once. After the automation runs, it is set to `disabled`. *Note:* You can only select _Manual run_ mode when the schedule frequency is disabled.
- _Run once mode_: When a policy is violated, the automation runs one time. After the automation runs, it is set to `disabled`. After the automation is set to `disabled`, you must continue to run the automation manually. When you run _once mode_, the extra variable of `target_clusters` is automatically supplied with the list of clusters that violated the policy. The {aap-short} Job template must have `PROMPT ON LAUNCH` enabled for the `EXTRA VARIABLES` section (also known as `extra_vars`).
- _Run everyEvent mode_: When a policy is violated, the automation runs every time for each unique policy violation per managed cluster. Use the `DelayAfterRunSeconds` parameter to set the minimum seconds before an automation can be restarted on the same cluster. If the policy is violated multiple times during the delay period and kept in the violated state, the automation runs one time after the delay period. The default is 0 seconds and is only applicable for the `everyEvent` mode. When you run `everyEvent` mode, the extra variable of `target_clusters` and {aap-short} Job template is the same as _once mode_.
- _Disable automation_: When the scheduled automation is set to `disabled`, the automation does not run until the setting is updated.

The following variables are automatically provided in the `extra_vars` of the {aap-short} Job:

* `policy_name`: The name of the non-compliant root policy that initiates the {aap-short} job on the hub cluster.
* `policy_namespace`: The namespace of the root policy.
* `hub_cluster`: The name of the hub cluster, which is determined by the value in the `clusters` `DNS` object.
* `policy_sets`: This parameter contains all associated policy set names of the root policy. If the policy is not within a policy set, the `policy_set` parameter is empty.
* `policy_violations`: This parameter contains a list of non-compliant cluster names, and the value is the policy `status` field for each non-compliant cluster.

[#additional-resources-manage-grc]
== Additional resources

Review the following topics to learn more about creating and updating your security policies:

* xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies]
* xref:../governance/create_config_pol.adoc#managing-configuration-policies[Managing configuration policies]
* xref:../governance/create_gatekeeper.adoc#managing-gatekeeper-operator-policies[Managing gatekeeper policies]
* xref:../governance/ansible_grc.adoc#configuring-governance-ansible[Configuring {aap-short} for governance]
* xref:../governance/grc_intro.adoc#governance[Governance]
