[#memory-usage-policy]
= Memory usage policy

The Kubernetes configuration policy controller monitors the status of the memory usage policy. Use the memory usage policy to limit or restrict your memory and compute usage. For more information, see _Limit Ranges_ in the link:https://kubernetes.io/docs/concepts/policy/limit-range/[Kubernetes documentation].

Learn more details about the memory usage policy structure in the following sections:

* <<memory-usage-policy-yaml-structure,Memory usage policy YAML structure>>
* <<memory-usage-policy-table,Memory usage policy table>>
* <<memory-usage-policy-sample,Memory usage policy sample>>

[#memory-usage-policy-yaml-structure]
== Memory usage policy YAML structure

Your memory usage policy might resemble the following YAML file:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name:
  namespace:
  annotations:
    policy.open-cluster-management.io/standards:
    policy.open-cluster-management.io/categories:
    policy.open-cluster-management.io/controls:
    policy.open-cluster-management.io/description:
spec:
  remediationAction:
  disabled:
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name:
        spec:
          remediationAction:
          severity:
          namespaceSelector:
            exclude:
            include:
            matchLabels:
            matchExpressions:
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: LimitRange
                metadata:
                  name:
                spec:
                  limits:
                  - default:
                      memory:
                    defaultRequest:
                      memory:
                    type:
        ...
----

[#memory-usage-policy-table]
== Memory usage policy table

.Parameter table
|===
| Field | Optional or required | Description

| `apiVersion`
| Required
| Set the value to `policy.open-cluster-management.io/v1`.

| `kind`
| Required
| Set the value to `Policy` to indicate the type of policy.

| `metadata.name`
| Required
| The name for identifying the policy resource.

| `metadata.namespace`
| Required
| The namespace of the policy.

| `spec.remediationAction`
| Optional
| Specifies the remediation of your policy. The parameter values are `enforce` and `inform`. This value is optional because the value overrides any values provided in `spec.policy-templates`.

| `spec.disabled`
| Required
| Set the value to `true` or `false`. The `disabled` parameter provides the ability to enable and disable your policies.

| `spec.policy-templates[].objectDefinition`
| Required
| Used to list configuration policies containing Kubernetes objects that must be evaluated or applied to the managed clusters.
|===

[#memory-usage-policy-sample]
== Memory usage policy sample

See the link:https://github.com/open-cluster-management/policy-collection/blob/main/stable/SC-System-and-Communications-Protection/policy-limitmemory.yaml[`policy-limitmemory.yaml`] to view a sample of the policy. See xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies] for more details. Refer to the xref:../governance/policy_overview.adoc#policy-overview[Policy overview] documentation, and to xref:../governance/config_policy_ctrl.adoc#kubernetes-config-policy-controller[Kubernetes configuration policy controller] to view other configuration policies that are monitored by the controller.
