[#namespace-policy]
= Namespace policy

The Kubernetes configuration policy controller monitors the status of your namespace policy. Apply the namespace policy to define specific rules for your namespace.

Learn more details about the namespace policy structure in the following sections:

* <<namespace-policy-yaml-structure,Namespace policy YAML structure>>
* <<namespace-policy-yaml-table,Namespace policy table>>
* <<namespace-policy-sample,Namespace policy sample>>

[#namespace-policy-yaml-structure]
== Namespace policy YAML structure

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name:
  namespace:
  annotations:
    policy.open-cluster-management.io/standards:
    policy.open-cluster-management.io/categories:
    policy.open-cluster-management.io/controls:
    policy.open-cluster-management.io/description:
spec:
  remediationAction:
  disabled:
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name:
        spec:
          remediationAction:
          severity:
          object-templates:
            - complianceType:
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name:
                ...
----

[#namespace-policy-yaml-table]
== Namespace policy YAML table

|===
| Field | Optional or required | Description

| `apiVersion`
| Required
| Set the value to `policy.open-cluster-management.io/v1`.

| `kind`
| Required
| Set the value to `Policy` to indicate the type of policy.

| `metadata.name`
| Required
| The name for identifying the policy resource.

| `metadata.namespace`
| Required
| The namespace of the policy.

| `spec.remediationAction`
| Optional
| Specifies the remediation of your policy. The parameter values are `enforce` and `inform`. This value is optional because it overrides any values provided in `spec.policy-templates`.

| `spec.disabled`
| Required
| Set the value to `true` or `false`. The `disabled` parameter provides the ability to enable and disable your policies.

| `spec.policy-templates[].objectDefinition`
| Required
| Used to list configuration policies containing Kubernetes objects that must be evaluated or applied to the managed clusters.
|===

[#namespace-policy-sample]
== Namespace policy sample

See link:https://github.com/open-cluster-management/policy-collection/blob/main/stable/CM-Configuration-Management/policy-namespace.yaml[`policy-namespace.yaml`] to view the policy sample.

See xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies] for more details. Refer to  xref:../governance/policy_overview.adoc#policy-overview[Policy overview] documentation, and to the xref:../governance/config_policy_ctrl.adoc#kubernetes-config-policy-controller[Kubernetes configuration policy controller] to learn about other configuration policies.
