[#namespace-policy]
= Namespace policy

Kubernetes configuration policy controller monitors the status of your namespace policy.
Apply the namespace policy to define specific rules for your namespace.

Learn more details about the namespace policy structure in the following sections:

* <<namespace-policy-yaml-structure,Namespace policy YAML structure>>
* <<namespace-policy-yaml-table,Namespace policy YAML table>>
* <<namespace-policy-sample,Namespace policy sample>>

[#namespace-policy-yaml-structure]
== Namespace policy YAML structure

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-namespace-1
  namespace:
spec:
  complianceType:
  remediationAction:
  namespaces:
    exclude:
    include:
  object-templates:
    - complianceType:
      objectDefinition:
        kind:
        apiVersion:
        metadata:
          name:
    ...
----

[#namespace-policy-yaml-table]
== Namespace policy YAML table

|===
| Field | Description

| apiVersion
| Required.
Set the value to `policy.open-cluster-management.io/v1`.

| kind
| Required.
Set the value to `Policy` to indicate the type of policy.

| metadata.name
| Required.
The name for identifying the policy resource.

| metadata.namespaces
| Optional.

| spec.namespace
| Required.
The namespaces within the hub cluster that the policy is applied to.
Enter parameter values for `include`, which are the namespaces you want to apply to the policy to.
The `exclude` parameter specifies the namespaces you explicitly do not want to apply the policy to.
*Note*: A namespace that is specified in the object template of a policy controller overrides the namespace in the corresponding parent policy.

| remediationAction
| Optional.
Specifies the remediation of your policy.
The parameter values are `enforce` and `inform`.

| disabled
| Required.
Set the value to `true` or `false`.
The `disabled` parameter provides the ability to enable and disable your policies.

| spec.complianceType
| Required.
Set the value to `"musthave"`

| spec.object-template
| Optional.
Used to list any other Kubernetes object that must be evaluated or applied to the managed clusters.
|===

[#namespace-policy-sample]
== Namespace policy sample

See https://github.com/stolostron/policy-collection/blob/main/stable/CM-Configuration-Management/policy-namespace.yaml[`policy-namespace.yaml`] to view the policy sample.

See xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies] for more details. Refer to xref:../governance/config_policy_ctrl.adoc#kubernetes-configuration-policy-controller[Kubernetes configuration policy controller] to learn about other configuration policies.
