:_mod-docs-content-type: REFERENCE

[#pod-policy]
= Pod policy

[role="_abstract"]
The Kubernetes configuration policy controller monitors the status of your pod policies. Apply the pod policy to define the container rules for your pods. A pod must exist in your cluster to use this information.

* Your pod policy might resemble the following YAML file:

+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name:
  namespace:
  annotations:
    policy.open-cluster-management.io/standards:
    policy.open-cluster-management.io/categories:
    policy.open-cluster-management.io/controls:
    policy.open-cluster-management.io/description:
spec:
  remediationAction:
  disabled:
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name:
        spec:
          remediationAction:
          severity:
          namespaceSelector:
            exclude:
            include:
            matchLabels:
            matchExpressions:
          object-templates:
            - complianceType:
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  name:
                spec:
                  containers:
                  - image:
                    name:
                ...
----

+
* The `Policy` resource defines policy metadata, remediation action, and policy templates.
* The `ConfigurationPolicy` template enforces `Pod` resources on managed clusters.
* Use `namespaceSelector` to limit which namespaces are evaluated.
* The `object-templates` section defines the `Pod` spec rules to enforce.

* Pod policy table:

.Parameter table
|===
| Field | Optional or required | Description

| `apiVersion`
| Required
| Set the value to `policy.open-cluster-management.io/v1`.

| `kind`
| Required
| Set the value to `Policy` to indicate the type of policy.

| `metadata.name`
| Required
| The name for identifying the policy resource.

| `metadata.namespace`
| Required
| The namespace of the policy.

| `spec.remediationAction`
| Optional
| Specifies the remediation of your policy. The parameter values are `enforce` and `inform`. This value is optional because the value overrides any values provided in `spec.policy-templates`.

| `spec.disabled`
| Required
| Set the value to `true` or `false`. The `disabled` parameter provides the ability to enable and disable your policies.

| `spec.policy-templates[].objectDefinition`
| Required
| Used to list configuration policies containing Kubernetes objects that must be evaluated or applied to the managed clusters.
|===

.Additional resources

* xref:../governance/manage_policies.adoc#creating-security-policies[Creating security policies]
* xref:../governance/hub_policy_framework.adoc#hub-policy-framework[Hub cluster policy framework]
* xref:../governance/config_policy_ctrl.adoc#kubernetes-config-policy-controller[Kubernetes configuration policy controller]
* xref:../governance/create_config_pol.adoc#create-configuration-policies[Creating configuration policies]
