[#pod-policy]
= Pod policy

The Kubernetes configuration policy controller monitors the status of your pod policies. Apply the pod policy to define the container rules for your pods.
A pod must exist in your cluster to use this information.

Learn more details about the pod policy structure in the following sections:

* <<pod-policy-yaml-structure,Pod policy YAML structure>>
* <<pod-policy-table,Pod policy table>>
* <<pod-policy-sample,Pod policy sample>>

[#pod-policy-yaml-structure]
== Pod policy YAML structure

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name:
  namespace:
  annotations:
    policy.open-cluster-management.io/standards:
    policy.open-cluster-management.io/categories:
    policy.open-cluster-management.io/controls:
    policy.open-cluster-management.io/description:
spec:
  remediationAction:
  disabled:
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name:
        spec:
          remediationAction:
          severity:
          namespaceSelector:
            exclude:
            include:
            matchLabels:
            matchExpressions:
          object-templates:
            - complianceType:
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  name:
                spec:
                  containers:
                  - image:
                    name:
                ...
----

[#pod-policy-table]
== Pod policy table

.Parameter table
|===
| Field | Optional or required | Description

| `apiVersion`
| Required
| Set the value to `policy.open-cluster-management.io/v1`.

| `kind`
| Required
| Set the value to `Policy` to indicate the type of policy.

| `metadata.name`
| Required
| The name for identifying the policy resource.

| `metadata.namespace`
| Required
| The namespace of the policy.

| `spec.remediationAction`
| Optional
| Specifies the remediation of your policy. The parameter values are `enforce` and `inform`. This value is optional because the value overrides any values provided in `spec.policy-templates`.

| `spec.disabled`
| Required
| Set the value to `true` or `false`. The `disabled` parameter provides the ability to enable and disable your policies.

| `spec.policy-templates[].objectDefinition`
| Required
| Used to list configuration policies containing Kubernetes objects that must be evaluated or applied to the managed clusters.
|===

[#pod-policy-sample]
== Pod policy sample

See link:https://github.com/open-cluster-management/policy-collection/blob/main/stable/CM-Configuration-Management/policy-pod.yaml[`policy-pod.yaml`] to view the policy sample. 

Refer to xref:../governance/config_policy_ctrl.adoc#kubernetes-config-policy-controller[Kubernetes configuration policy controller] to view other configuration policies that are monitored by the configuration controller, and see the xref:../governance/policy_overview.adoc#policy-overview[Policy overview documentation] to see a full description of the policy YAML structure and additional fields. Return to xref:../governance/create_config_pol.adoc#managing-configuration-policies[Managing configuration policies] documentation to manage other policies.
