[#policy-controllers]
= Policy controllers introduction

Policy controllers monitor and report whether your cluster is compliant with a policy. Use the {product-title} policy framework by using the supported policy templates to apply policies managed by these controllers. The policy controllers manage Kubernetes custom resource definition instances.

Policy controllers check for policy violations, and can make the cluster status compliant if the controller supports the enforcement feature. View the following topics to learn more about the following {product-title} policy controllers:

* xref:../governance/config_policy_ctrl.adoc#kubernetes-config-policy-controller[Kubernetes configuration policy controller]
* xref:../governance/cert_policy_ctrl.adoc#certificate-policy-controller[Certificate policy controller]
* xref:../governance/iam_policy_ctrl.adoc#iam-policy-controller[IAM policy controller (Deprecated)]
* xref:../governance/policy_set_ctrl.adoc#policy-set-controller[Policy set controller]

*Important:* Only the configuration policy controller policies support the `enforce` feature. You must manually remediate policies, where the policy controller does not support the `enforce` feature.
