:_mod-docs-content-type: REFERENCE

[#policy-adv-config-api-server-rate]
= Configure API server request rate

[role="_abstract"]
The configuration policy controller `ManagedClusterAddOn` supports `client-qps` and `client-burst` annotations to control the rate of requests to the Kubernetes API server on each managed cluster.

The `client-qps` and `client-burst` annotations control the rate of requests the configuration policy controller makes to the Kubernetes API server on each managed cluster. Apply these annotations to the `ManagedClusterAddOn` named `config-policy-controller` in the managed cluster namespace on the hub cluster. By default, the request rate scales with the `policy-evaluation-concurrency` setting at `30` queries per second (QPS) with a burst value of `45`. Valid values are nonzero integers specified as quoted strings.

*Note:* Increased request rates improve configuration policy controller responsiveness and increase CPU and memory utilization on the Kubernetes API server and OpenShift API server.

The following YAML example sets QPS to `20` and burst to `100` on the managed cluster named `cluster1`:

[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: config-policy-controller
  namespace: cluster1
  annotations:
    client-qps: "20"
    client-burst: "100"
spec:
  installNamespace: open-cluster-management-agent-addon
----
+
* The `spec.installNamespace` field is deprecated. See _Product deprecations and removals_ for more information.

.Additional resources

* link:../clusters/release_notes/mce_deprecate_remove.adoc#mce-deprecation-removal[Product deprecations and removals]
