:_mod-docs-content-type: REFERENCE

[#policy-adv-config-governance-metrics]
= Governance metrics

[role="_abstract"]
The policy framework exposes metrics that show policy distribution and status on the hub cluster and managed clusters.

== policy_governance_info

The `policy_governance_info` metric records compliance status for root and propagated policies on the hub cluster.

The {ocp-short} monitoring component collects the `policy_governance_info` metric. If you enable observability, the component collects some aggregate data.

*Note:* If you enable observability, enter a query for the metric from the Grafana _Explore_ page. When you create a policy, you are creating a _root_ policy. The framework watches for root policies, `Placement` resources, and `PlacementBindings` resources to for information about where to create _propagated_ policies, to distribute the policy to managed clusters.

For both root and propagated policies, a metric of `0` is recorded if the policy is compliant, `1` if it is non-compliant, and `-1` if it is in an unknown or pending state.

The `policy_governance_info` metric uses the following labels:

- `type`: The label values are `root` or `propagated`.
- `policy`: The name of the associated root policy.
- `policy_namespace`: The namespace on the hub cluster where the root policy is defined.
- `cluster_namespace`: The namespace for the cluster where the policy is distributed.

These labels and values enable queries that can show us many things happening in the cluster that might be difficult to track.

*Note:* If you do not need the metrics, and you have any concerns about performance or security, you can disable the metric collection. Set the `DISABLE_REPORT_METRICS` environment variable to `true` in the propagator deployment. You can also add `policy_governance_info` metric to the observability allowlist as a custom metric. See _Adding custom metrics_ for more details.

== cluster_policy_governance_info

The `cluster_policy_governance_info` metric records compliance status for policies on managed clusters.

The {ocp-short} monitoring component collects the `cluster_policy_governance_info` metric. If you enable observability, the component collects the data.

*Note:* If you enable observability, enter a query for the metric from the Grafana _Explore_ page.

For managed cluster policies, a metric of `0` is recorded if the policy is compliant, `1` if it is not compliant, and `-1` if it is in an unknown or pending state.

The `cluster_policy_governance_info` metric uses the following labels:

- `kind`: The kind of the policy.
- `policy`: The name of the policy.
- `policy_namespace`: The namespace on the managed cluster where the policy is defined.
- `severity`: The severity specified on the policy.

Use these labels and values to enable detailed queries on changes in the cluster that might be difficult to track.

*Note:* You can also add `cluster_policy_governance_info` metric to the observability `allowlist` as a custom metric. For more details, see _Adding custom metrics_.

== config_policies_evaluation_duration_seconds

The `config_policies_evaluation_duration_seconds` histogram tracks how long the configuration policy controller takes to evaluate policies that are ready on a managed cluster.

The `config_policies_evaluation_duration_seconds` histogram tracks the number of seconds it takes to process all configuration policies that are ready to be evaluated on the cluster. Use the following metrics to query the histogram:

- `config_policies_evaluation_duration_seconds_bucket`: The buckets are cumulative and represent seconds with the following possible entries: 1, 3, 9, 10.5, 15, 30, 60, 90, 120, 180, 300, 450, 600, and greater.
- `config_policies_evaluation_duration_seconds_count`: The count of all events.
- `config_policies_evaluation_duration_seconds_sum`: The sum of all values.

Use the `config_policies_evaluation_duration_seconds` metric to determine if the `ConfigurationPolicy` `evaluationInterval` setting needs to be changed for resource intensive policies that do not need frequent evaluation. You can also increase the concurrency at the cost of higher resource utilization on the Kubernetes API server. See _Configure configuration policy controller concurrency_ for more details.

To receive information about the time used to evaluate configuration policies, perform a Prometheus query that resembles the following expression:

`rate(config_policies_evaluation_duration_seconds_sum[10m])/rate (config_policies_evaluation_duration_seconds_count[10m]`

The `config-policy-controller` pod running on managed clusters in the `open-cluster-management-agent-addon` namespace calculates the metric. The `config-policy-controller` does not send the metric to observability by default.

.Additional resources

* xref:../observability/customize_observability.adoc#adding-custom-metrics[Adding custom metrics]
* xref:../governance/policy_adv_config_config_policy_concurrency.adoc#policy-adv-config-config-policy-concurrency[Configure configuration policy controller concurrency]
