[#policy-controllers]
= Policy controllers

Policy controllers monitor and report whether your cluster is compliant with a policy. Use the {product-title} policy framework by using the out-of-the-box policy templates to apply predefined policy controllers and policies. The policy controllers are Kubernetes custom resource definition (CRD) instances.

For more information about CRDs, see https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions]. Policy controllers remediate policy violations to make the cluster status compliant.

View the following topics to learn more about the following {product-title} policy controllers:

* xref:../governance/config_policy_ctrl.adoc#kubernetes-configuration-policy-controller[Kubernetes configuration policy controller]
* xref:../governance/cert_policy_ctrl.adoc#certificate-policy-controller[Certificate policy controller]
* xref:../governance/iam_policy_ctrl.adoc#iam-policy-controller[IAM policy controller]
* xref:../governance/policy_set_ctrl.adoc#policy-set-controller[Policy set controller]

**Important**: Only the configuration policy controller policies support the `enforce` feature. You must manually remediate policies, where the policy controller does not support the `enforce` feature.

Refer to xref:../governance/grc_intro.adoc#governance[Governance] for more topics about managing your policies.
