[#policy-operator]
= Operator policy controller

The operator policy controller allows you to monitor and install Operator Lifecycle Manager (OLM) operators across your clusters. You can monitor the health of various pieces of the operator and you can specify how to automatically handle updates to the operator. You can also distribute an operator policy to managed clusters by using the governance framework and adding the policy to the `policy-templates` field of a policy on the hub cluster.

If the `remediationAction` for the operator policy is set to `enforce`, the controller creates resources on the target managed cluster to install the operator and approves updates based on the versions specified in the policy.

If the `remediationAction` set to `inform`, the controller only reports the status of the operator, including if any upgrades are available.

The primary field in an operator policy is `spec.subscription`. You must add information in the following fields to create an operator subscription:

- `channel`
- `name`
- `namespace`
- `source`
- `sourceNamespace` 

For more information, see the _Subscription_ topic in the {ocp} documentation.

You can use the `spec.versions` field in an operator policy to declare which versions of the operator are compliant. If the field is empty, any version running on the cluster is considered compliant. If the field is not empty, the version on the managed cluster must match one of the versions in the list for the policy to be compliant. If the policy is in `enforce` mode, it only approves updates to versions that are compliant.

See the following operator policy sample:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: quay-policy
spec:
  remediationAction: inform
  severity: medium
  complianceType: musthave
  operatorGroup: [optional]
    name: scoped-operator-group
    namespace: quay-opns
    targetNamespaces:
      - quay-opns
  subscription:
    channel: stable-3.10
    name: quay-operator
    namespace: quay-opns
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  versions:
    - quay-operator.v3.10.3
----

[#policy-operator-add-res]
= Additional resources

See the link:https://docs.openshift.com/container-platform/4.12/operators/understanding/olm/olm-understanding-olm.html#olm-subscription_olm-understanding-olm[Subscription] topic in the {ocp-short} documentation.
