[#policy-gen-install-operator]
= Generating a policy to install an Operator

A common use of {product-title-short} policies is to install an Operator on one or more managed {ocp} clusters. Continue reading to learn how to generate policies using the policy generator, and to install the OpenShift GitOps Operator with a generated policy:

* <<policy-install-ocp-gitops,Generating a policy that installs OpenShift GitOps>>
* <<policy-gen-install-compliance-operator,Generating a policy that installs the Compliance Operator>>
* <<policy-gen-install-on-openshift-gitops,Generating a policy that installs the Policy Generator on OpenShift GitOps (ArgoCD)>>
* <<related-resource-grc-gitops,Related resources>>

[#policy-install-ocp-gitops]
== Generating a policy that installs OpenShift GitOps

You can generate a policy that installs OpenShift GitOps by using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode, which is used in the following example. Create a `Subscription` manifest file called `openshift-gitops-subscription.yaml`, similar to the following example:

[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
----

To pin to a specific version of the operator, add the following parameter and value: `spec.startingCSV: openshift-gitops-operator.v<version>`. Replace `<version>` with your preferred version.

A `PolicyGenerator` configuration file is required. Use the configuration file named `policy-generator-config.yaml` to generate a policy to install OpenShift GitOps on all {ocp-short} managed clusters. See the following example:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-openshift-gitops
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      vendor: "OpenShift"
  remediationAction: enforce
policies:
  - name: install-openshift-gitops
    manifests:
      - path: openshift-gitops-subscription.yaml
----

The last required file is `kustomization.yaml`, which requires the following configuration:

[source,yaml]
----
generators:
  - policy-generator-config.yaml
----

The generated policy might resemble the following file:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-install-openshift-gitops
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-install-openshift-gitops
  namespace: policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-install-openshift-gitops
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: install-openshift-gitops
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
  name: install-openshift-gitops
  namespace: policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: install-openshift-gitops
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: openshift-gitops-operator
                  namespace: openshift-operators
                spec:
                  channel: stable
                  name: openshift-gitops-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
          remediationAction: enforce
          severity: low
----

Generated policies from manifests in the {ocp-short} documentation is supported. Any configuration guidance from the {ocp-short} documentation can be applied using the Policy Generator.

[#policy-gen-install-compliance-operator]
== Generating a policy that installs the Compliance Operator

For an operator that uses the _namespaced_ installation mode, such as the Compliance Operator, an `OperatorGroup` manifest is also required. 

Create a YAML file with a `Namespace`, a `Subscription`, and an `OperatorGroup` manifest called `compliance-operator.yaml`. The following example installs these manifests in the `compliance-operator` namespace:

[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-compliance
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
  channel: release-0.1
  name: compliance-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
  targetNamespaces:
    - compliance-operator
----

A `PolicyGenerator` configuration file is required. View the following `PolicyGenerator` policy example that installs the Compliance Operator on all {ocp-short} managed clusters:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-compliance-operator
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      vendor: "OpenShift"
  remediationAction: enforce
policies:
  - name: install-compliance-operator
    manifests:
      - path: compliance-operator.yaml
----

The last required file is `kustomization.yaml`, which requires the following configuration:

[source,yaml]
----
generators:
  - policy-generator-config.yaml
----

As a result, the generated policy resembles the following file:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-install-compliance-operator
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-install-compliance-operator
  namespace: policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-install-compliance-operator
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: install-compliance-operator
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
  name: install-compliance-operator
  namespace: policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: install-compliance-operator
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-compliance
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: compliance-operator
                  namespace: openshift-compliance
                spec:
                  channel: release-0.1
                  name: compliance-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: compliance-operator
                  namespace: openshift-compliance
                spec:
                  targetNamespaces:
                    - compliance-operator
          remediationAction: enforce
          severity: low
----

[#policy-gen-install-on-openshift-gitops]
== Integrating the Policy Generator with OpenShift GitOps (ArgoCD)

OpenShift GitOps, based on link:https://argoproj.github.io/argo-cd/[ArgoCD], can also be used to generate policies by using the Policy Generator through GitOps. Since the Policy Generator does not come preinstalled in the OpenShift GitOps container image, some customization must take place. In order to follow along, you must have the OpenShift GitOps Operator installed on the {product-title-short} hub cluster and be sure to log into the hub cluster.

In order for OpenShift GitOps to have access to the Policy Generator when you run Kustomize, an Init Container is required to copy the Policy Generator binary from the {product-title-short} Application Subscription container image to the OpenShift GitOps container. Additionally, OpenShift GitOps must be configured to provide the `--enable-alpha-plugins` flag when it runs Kustomize. Start editing the OpenShift GitOps `argocd` object with the following command:

[source,bash]
----
oc -n openshift-gitops edit argocd openshift-gitops
----

Then modify the OpenShift GitOps `argocd` object to contain the following additional YAML content. When a new major version of {product-title-short} is released and you want to update the Policy Generator to a newer version, you need to update the `registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel8` image used by the Init Container to a newer tag. View the following example and replace `<version>` with {product-version} or your desired {product-title-short} version:

[source,yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  kustomizeBuildOptions: --enable-alpha-plugins
  repo:
    env:
    - name: KUSTOMIZE_PLUGIN_HOME
      value: /etc/kustomize/plugin
    initContainers:
    - args:
      - -c
      - cp /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator
        /policy-generator/PolicyGenerator
      command:
      - /bin/bash
      image: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel8:v<version>
      name: policy-generator-install
      volumeMounts:
      - mountPath: /policy-generator
        name: policy-generator
    volumeMounts:
    - mountPath: /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator
      name: policy-generator
    volumes:
    - emptyDir: {}
      name: policy-generator
----

Now that OpenShift GitOps can use the policy generator, OpenShift GitOps must be granted access to create policies on the {product-title-short} hub cluster. Create the following `ClusterRole` resource called `openshift-gitops-policy-admin`, with access to create, read, update, and delete policies and placements. Your `ClusterRole` might resemble the following example:

[source,yaml]
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-policy-admin
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - policy.open-cluster-management.io
    resources:
      - policies
      - placementbindings
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - apps.open-cluster-management.io
    resources:
      - placementrules
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - placements
      - placements/status
      - placementdecisions
      - placementdecisions/status
----

Additionally, create a `ClusterRoleBinding` object to grant the OpenShift GitOps service account access to the `openshift-gitops-policy-admin` `ClusterRole`. Your `ClusterRoleBinding` might resemble the following resource:

[source,yaml]
----
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-policy-admin
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-policy-admin
----

[#related-resource-grc-gitops]
== Related resources

* See xref:../governance/deploy_gitops.adoc#deploying-policies-using-gitops[Deploying policies using GitOps] for more details.
* Return to the xref:../governance/third_party_policy.adoc#integrate-third-party-policy-controllers[Integrate third-party policy controllers] documentation.
* See link:https://docs.openshift.com/container-platform/4.12/cicd/gitops/understanding-openshift-gitops.html[Understanding OpenShift GitOps] and the link:https://cloud.redhat.com/learn/topics/operators[Operator] documentation for more details.
* See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/operators/administrator-tasks#olm-installing-operator-from-operatorhub-using-cli_olm-adding-operators-to-a-cluster[Adding Operators to a cluster - Installing from OperatorHub using the CLI] 
* See the link:https://docs.openshift.com/container-platform/4.12/security/compliance_operator/compliance-operator-understanding.html[Compliance Operator documentation] for more details. 
* See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/operators/administrator-tasks#olm-installing-operators-from-operatorhub_olm-adding-operators-to-a-cluster[_all namespaces_ installation mode].
* See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/operators/administrator-tasks#olm-installing-operators-from-operatorhub_olm-adding-operators-to-a-cluster[_namespaced_ installation mode].
* See link:https://docs.openshift.com/container-platform/4.10/nodes/containers/nodes-containers-init.html[Using Init Containers to perform tasks before a pod is deployed].
* See link:https://argoproj.github.io/argo-cd/[ArgoCD].
* View the following examples of YAML input that is supported in the {ocp-short} documentation:
- link:https://docs.openshift.com/container-platform/4.12/post_installation_configuration/cluster-tasks.html[Post-installation cluster tasks]
- link:https://docs.openshift.com/container-platform/4.12/security/audit-log-policy-config.html[Configuring the audit log policy]
- link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/logging/cluster-logging-external#cluster-logging-collector-log-forwarding-about_cluster-logging-external[About forwarding logs to third-party systems]


