:_mod-docs-content-type: REFERENCE

[#policy-adv-config-config-policy-concurrency]
= Configure configuration policy controller concurrency

[role="_abstract"]
The configuration policy controller `ManagedClusterAddOn` supports a `policy-evaluation-concurrency` annotation to control how many configuration policies are evaluated concurrently on each managed cluster.

The `policy-evaluation-concurrency` annotation controls how many configuration policies the controller evaluates concurrently on each managed cluster. Apply this annotation to the `ManagedClusterAddOn` named `config-policy-controller` in the managed cluster namespace on the hub cluster. The default value is `2`. Valid values are nonzero integers specified as quoted strings.

*Note:* Increased concurrency values increase CPU and memory utilization on the `config-policy-controller` pod, Kubernetes API server, and OpenShift API server.

The following YAML example sets concurrency to `5` on the managed cluster named `cluster1`:

[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: config-policy-controller
  namespace: cluster1
  annotations:
    policy-evaluation-concurrency: "5"
spec:
  installNamespace: open-cluster-management-agent-addon
----
