[#policy-deployment]
= Policy deployment

The Kubernetes API is used to define and interact with policies. You are responsible for ensuring that the environment meets internal enterprise security standards for software engineering, secure engineering, resiliency, security, and regulatory compliance for workloads hosted on Kubernetes clusters.

[#deployment-options]
== Deployment options

The `CertificatePolicy`, `ConfigurationPolicy`, and `OperatorPolicy` policies and Gatekeeper constraints can be deployed to your managed clusters in two ways. You can deploy policies to your managed clusters by using the _Hub cluster policy framework_ or _Deploying policies with external tools_. View the following descriptions of each option: 

Hub cluster policy framework:: The first approach is to leverage the policy framework on the hub cluster. This involves defining the policies and Gatekeeper constraints within a `Policy` object on the hub cluster and leveraging a `Placement` and `PlacementBinding` to select which clusters the policies get deployed to. The policy framework handles the delivery to the managed cluster and the status aggregation back to the hub cluster. The `Policy` objects are represented in the _Policies_ table in the {acm} console.

Deploying policies with external tools:: Alternatively, you can use an external tool, such as {gitops}, to deliver the policies and Gatekeeper constraints directly to the managed cluster. Your policies are shown in the _Discovered policies_ table in the {acm-short} console and can be a helpful option if a configuration management strategy is already in place, but there is a desire to supplement the strategy with {acm-short} policies.

[#pol-deployment-table]
=== Policy deployment comparison table

//added the table but still need to make updates and have questions
See the following comparison table to learn which option supports specific features, which helps you make a decision on which deployment strategy is more suitable for your use case:

|===
| Feature | Policy framework | Deployed with external tools

| Hub cluster templating
| Yes
| No

| Managed cluster templating
| Yes
| Yes

| {acm-short} console support
| Yes
| Yes, you can view policies that are deployed by external tools from the _Discover policies_ table. Policies that are deployed with external tools are not displayed from the Governance _Overview_ dashboard. You must enable Search on your managed cluster.

| Policy grouping
| Yes, you can have a combination of statuses and deployments through `Policy` and `PolicySet` resources.
| Yes, you can have a combination of statuses and deployments through `Policy` and `PolicySet` resources.

| Compliance history
| You can view the last 10 events per cluster per policy stored on the hub cluster.
| No, but you can scrape the compliance history from the controller logs on each managed cluster.

| Policy dependencies
| Yes
| No. Alternatively, you can use the Argo CD sync waves feature to define dependencies. 

| Policy Generator
| Yes
| No

| {gitops-short} health checks

You must complete extra configuration for Argo CD versions earlier than 2.13.
| Yes
| Yes

| Policy compliance history API (Technology Preview) 
| Yes
| No

| {gitops-short} applying native Kubernetes manifests and {acm-short} policy on the managed cluster
| No, you must deploy a policy on your {acm-short} hub cluster.
| Yes

| Policy compliance metric on the hub cluster for alerts
| Yes
| No

| Running Ansible jobs on policy noncompliance
| Yes, use the `PolicyAutomation` resource.
| No
|===

[#policy-deployment-add-resources]
== Additional resources

* xref:../governance/hub_policy_framework.adoc#hub-policy-framework[Hub cluster policy framework]
* xref:../governance/deploy_external_tools.adoc#deploy-external-tools[Deploying policies with external tools]