:_mod-docs-content-type: REFERENCE

[#policy-cli-tool]
= Command line _policytools_ overview

[role="_abstract"]
Review the `policytools` command-line tool. You can interact with policies locally to help with creating and debugging. The `policytools` command-line tool is available for download from the hub cluster console.

`template-resolver`:: The `template-resolver` is a subcommand for `policytools` that resolves managed cluster and hub cluster templates that are embedded in policies. The `template-resolver` reads from either a file, or from standard input.

+
To resolve a policy with hub cluster templates, you must provide the `--cluster-name` argument with the name of a managed cluster that is imported into {acm-short}, and you must provide the `--hub-kubeconfig` argument with the path to a `kubeconfig` file that references the hub cluster.

+
If the input policy uses the `.ObjectName` or `.ObjectNamespace` template variables, you need to set the values with the `--object-name` and `--object-namespace` arguments.

+
The `template-resolver` subcommand connects to the managed cluster and hub cluster to retrieve information that is necessary to resolve the templates. Provide paths by using the `--save-resources` and `--save-hub-resources` arguments to save the resources that the `template-resolver` retrieves. Those saved files can be used as inputs for the `dryrun` subcommand.

+
*Technology Preview:* The `policytools` command-line interface introduces a `--lint` argument for the `template-resolver` subcommand to print any linting issues, along with the resolved Go templates from the input policy. To generate a Static Analysis Results Interchange Format (SARIF) report of the linter results, specify a file path with the `--sarif` argument.

`dryrun`:: The `dryrun` is a subcommand for `policytools` that evaluates a `ConfigurationPolicy` resource locally by using static input resources for the cluster state.

+
To run a policy, add the path to the `ConfigurationPolicy` YAML by using the `--policy` flag. You can provide additional resource YAML files, which are used as the current cluster state. For example, if your policy defines a specific configuration for a namespace, provide the current namespace state to see what the policy does. Multiple resources can be in the same resource file.

+
To evaluate a policy against the current state of a live cluster, use the `--from-cluster` flag or set the `DRYRUN_FROM_CLUSTER` environment variable to `true`.  

The `dryrun` subcommand reads the current state of resources directly from the cluster that you configured in your `kubeconfig` file or from the cluster that is specified by the `KUBECONFIG` environment variable. In both these scenarios, the `dryun` subcommand does not gather information from the resource files. 

When you enable the `--from-cluster` flag, it ignores any YAML resource files that are provided as input. Enabling the  `--from-cluster` flag allows you to test a policy against your actual cluster state without manually exporting and supporting resource files.

+
By default, `dryrun` prints the differences between the desired states of objects that are defined in the policy and the current state of those resources, as well as compliance messages that the `ConfigurationPolicy` creates. 

To save the compliance messages to a separate file, use the `--messages-path` argument. To save the full policy status, including additional information about the related objects, use the `--status-path` argument.

+
If the policy is `NonCompliant` based on the input, the tool returns a non-zero exit code. To compare the resulting status against a known status, use the `--desired-status` argument. For example, to verify that the policy reports a missing resource, provide a YAML file with the missing resource inside a `.relatedObjects` list. To verify that the policy is `NonCompliant`, create a YAML file with the `compliant: NonCompliant` line.

.Additional resources

* link:../console/console.adoc#command-line-tools[Command line tools]
