[#policy-overview]
= Policy overview

Use the {product-title} security policy framework to create custom policy controllers and other policies.
Kubernetes custom resource definition (CRD) instance are used to create policies.
For more information about CRDs, see https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions].

Each {product-title} policy can have at least one or more templates.
For more details about the policy elements, view the following _Policy YAML table_ section on this page.

The policy requires a _PlacementRule_ or _Placement_ that defines the clusters that the policy document is applied to, and a _PlacementBinding_ that binds the {product-title} policy to the placement rule. For more on how to define a `PlacementRule`, see link:../applications/app_model.adoc#placement-rules[Placement rules] in the Application lifecycle documentation. For more on how to define a `Placement` see link:../clusters/placement_managed.adoc#placement-overview[Placement overview] in the Cluster lifecycle documentation.

*Important*:

* You must create the `PlacementBinding` and associate it with either the `PlacementRule` or a `Placement`.
+
*Best practice*: Use the command line interface (CLI) to make updates to the policies when you use the `Placement` resource.

* You can create a policy in any namespace on the hub cluster except the cluster namespace.
If you create a policy in the cluster namespace, it is deleted by {product-title}.
* Each client and provider is responsible for ensuring that their managed cloud environment meets internal enterprise security standards for software engineering, secure engineering, resiliency, security, and regulatory compliance for workloads hosted on Kubernetes clusters.
Use the governance and security capability to gain visibility and remediate configurations to meet standards.

Learn more details about the policy components in the following sections:

* <<policy-yaml-structure,Policy YAML structure>>
* <<policy-yaml-table,Policy YAML table>>
* <<policy-sample-file,Policy sample file>>
* <<placement-yaml-sample-file,Placement YAML sample file>>

[#policy-yaml-structure]
== Policy YAML structure

When you create a policy, you must include required parameter fields and values.
Depending on your policy controller, you might need to include other optional fields and values. View the following YAML structure for the explained parameter fields:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name:
  annotations:
    policy.open-cluster-management.io/standards:
    policy.open-cluster-management.io/categories:
    policy.open-cluster-management.io/controls:
spec:
  policy-templates:
    - objectDefinition:
        apiVersion:
        kind:
        metadata:
          name:
        spec:
  remediationAction:
  disabled:

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name:
placementRef:
  name:
  kind:
  apiGroup:
subjects:
- name:
  kind:
  apiGroup:
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name:
spec:
  clusterConditions:
  - type:
  clusterLabels:
    matchLabels:
      cloud:
----

[#policy-yaml-table]
== Policy YAML table

|===
| Field | Description

| apiVersion
| Required.
Set the value to `policy.open-cluster-management.io/v1`.

| kind
| Required.
Set the value to `Policy` to indicate the type of policy.

| metadata.name
| Required.
The name for identifying the policy resource.

| metadata.annotations
| Optional.
Used to specify a set of security details that describes the set of standards the policy is trying to validate. All annotations documented here are represented as a string that contains a comma-separated list.
*Note*: You can view policy violations based on the standards and categories that you define for your policy on the _Policies_ page, from the console.

| annotations.policy.open-cluster-management.io/standards
| The name or names of security standards the policy is related to.
For example, National Institute of Standards and Technology (NIST) and Payment Card Industry (PCI).

| annotations.policy.open-cluster-management.io/categories
| A security control category represent specific requirements for one or more standards.
For example, a System and Information Integrity category might indicate that your policy contains a data transfer protocol to protect personal information, as required by the HIPAA and PCI standards.

| annotations.policy.open-cluster-management.io/controls
| The name of the security control that is being checked.
For example, the certificate policy controller.

| spec.policy-templates
| Required.
Used to create one or more policies to apply to a managed cluster.

| spec.disabled
| Required.
Set the value to `true` or `false`.
The `disabled` parameter provides the ability to enable and disable your policies.

| spec.remediationAction
| Optional.
Specifies the remediation of your policy.
The parameter values are `enforce` and `inform`. If specified, the `spec.remediationAction` value that is defined overrides the `remediationAction` parameter defined in the child policy, from the `policy-templates` section. For example, if `spec.remediationAction` value section is set to `enforce`, then the `remediationAction` in the `policy-templates` section is set to `enforce` during runtime.
*Important*: Some policies might not support the enforce feature.
|===

[#policy-sample-file]
== Policy sample file

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-role
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-role-example
        spec:
          remediationAction: inform # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          namespaceSelector:
            include: ["default"]
          object-templates:
            - complianceType: mustonlyhave # role definition should exact match
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: sample-role
                rules:
                  - apiGroups: ["extensions", "apps"]
                    resources: ["deployments"]
                    verbs: ["get", "list", "watch", "delete","patch"]
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-role
placementRef:
  name: placement-policy-role
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-role
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-role
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
----

[#placement-yaml-sample-file]
== Placement YAML sample file

The `PlacementBinding` and `Placement` resources can be combined with the previous policy example to deploy the policy using the cluster `Placement` API instead of the `PlacementRule` API.

[source,yaml]
----
--- 
apiVersion: policy.open-cluster-management.io/v1 
kind: PlacementBinding 
metadata: 
  name: binding-policy-role
placementRef: 
  name: placement-policy-role 
  kind: Placement 
  apiGroup: cluster.open-cluster-management.io 
subjects: 
- name: policy-role 
  kind: Policy 
  apiGroup: policy.open-cluster-management.io 
--- 
//Depends on if governance would like to use v1beta1
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement 
metadata: 
  name: placement-policy-role 
spec:
  predicates: 
  - requiredClusterSelector: 
      labelSelector: 
        matchExpressions: 
          - {key: environment, operator: In, values: ["dev"]}
----

See xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies] to create and update a policy. You can also enable and update{product-title-short} policy controllers to validate the compliance of your policies. Refer to xref:../governance/policy_controllers.adoc#policy-controllers[Policy controllers].

To learn more policy topics, see xref:../governance/grc_intro.adoc#governance[Governance].
