:_mod-docs-content-type: REFERENCE

[#policy-adv-config-config-policy-concurrency]
= Configure configuration policy controller concurrency

[role="_abstract"]
You can configure the concurrency of the configuration policy controller for each managed cluster to change how many configuration policies it can evaluate at the same time. To change the default value of `2`, set the `policy-evaluation-concurrency` annotation with a nonzero integer within quotation marks. Then set the value on the `ManagedClusterAddOn` object name to `config-policy-controller` in the managed cluster namespace of the hub cluster.

*Note:* Increased concurrency values increase CPU and memory utilization on the `config-policy-controller` pod, Kubernetes API server, and OpenShift API server.

See the following YAML example where the concurrency is set to `5` on the managed cluster named `cluster1`:

[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: config-policy-controller
  namespace: cluster1
  annotations:
    policy-evaluation-concurrency: "5"
spec:
  installNamespace: open-cluster-management-agent-addon
----

*Note:* The `spec.installNamespace` field is deprecated. See link:../clusters/release_notes/mce_deprecate_remove.adoc#mce-deprecation-removal[Product deprecations and removals] to learn more.
