[#policy-controller-advanced-config]
= Policy controller advanced configuration 

You can customize policy controller configurations on your managed clusters using the `ManagedClusterAddOn` custom resources. The following `ManagedClusterAddOns` configure the policy framework, `governance-policy-framework`, `config-policy-controller`, `cert-policy-controller`, and `iam-policy-controller`.

*Required access:* Cluster administrator

[#configure-concurrency] 
== Configure the concurrency

You can configure the concurrency of the configuration policy controller for each managed cluster to change how many configuration policies it can evaluate at the same time. To change the default value of `2`, set the `policy-evaluation-concurrency` annotation with a non-zero integer within quotes. You can set the value on the `ManagedClusterAddOn` object called `config-policy-controller` in the managed cluster namespace of the hub cluster.

*Note:* Higher concurrency values increase CPU and memory utilization on the `config-policy-controller` pod, Kubernetes API server, and OpenShift API server.

In the following YAML example, concurrency is set to `5` on the managed cluster called `cluster1`:

[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: config-policy-controller
  namespace: cluster1
  annotations:
    policy-evaluation-concurrency: "5"
spec:
  installNamespace: open-cluster-management-agent-addon
----

[#configure-debug-log] 
== Configure debug log 

You can adjust the number of logs to be generated for each policy controller. To enable debug logging, add the `log-level` annotation with the value of `2` to the `ManagedClusterAddOn` custom resource. By default, the `log-level` is set to `0`. View the following example:  

[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: config-policy-controller
  namespace: cluster1
  annotations:
    log-level: "2"
spec:
  installNamespace: open-cluster-management-agent-addon
----

[#gov-metric]
== Governance metric

The policy framework exposes metrics that show policy distribution and compliance. Use the `policy_governance_info` metric on the hub cluster to view trends and analyze any policy failures. See the following topics for an overview of metrics:

[#metric-policy-governance-info]
=== Metric: policy_governance_info

The `policy_governance_info` is collected by {ocp-short} monitoring, and some aggregate data is collected by {product-title-short} observability, if it is enabled.

*Note:* If observability is enabled, you can enter a query for the metric from the Grafana _Explore_ page. 

When you create a policy, you are creating a _root_ policy. The framework watches for root policies as well as `PlacementRules` and `PlacementBindings`, to determine where to create _propagated_ policies in order to distribute the policy to managed clusters.
For both root and propagated policies, a metric of `0` is recorded if the policy is compliant, and `1` if it is non-compliant.

The `policy_governance_info` metric uses the following labels:

- `type`: The label values are `root` or `propagated`.
- `policy`: The name of the associated root policy.
- `policy_namespace`: The namespace on the hub cluster where the root policy was defined.
- `cluster_namespace`: The namespace for the cluster where the policy is distributed.

These labels and values enable queries that can show us many things happening in the cluster that might be difficult to track.

*Note:* If the metrics are not needed, and there are any concerns about performance or security, this feature can be disabled. Set the `DISABLE_REPORT_METRICS` environment variable to `true` in the propagator deployment. You can also add `policy_governance_info` metric to the observability allowlist as a custom metric. See link:../observability/customize_observability.adoc#adding-custom-metrics[Adding custom metrics] for more details.

[#metric-config-policies-evaluation-duration]
=== Metric: config_policies_evaluation_duration_

The `config_policies_evaluation_duration_` histogram tracks the number of seconds it takes to process all configuration policies that are ready to be evaluated on the cluster. Use the following metrics to query the histogram:

- `config_policies_evaluation_duration_seconds_bucket`: The buckets are cumulative and represent seconds with the following possible entries: 1, 3, 9, 10.5, 15, 30, 60, 90, 120, 180, 300, 450, 600, and greater.
- `config_policies_evaluation_duration_seconds_count`: The count of all events.
- `config_policies_evaluation_duration_seconds_sum`: The sum of all values.

Use `config_policies_evaluation_duration_` to determine if the `ConfigurationPolicy` `evaluationInterval` setting needs to be changed for resource intensive policies that do not need frequent evaluation. You can also increase the concurrency at the cost of higher resource utilization on the Kubernetes API server. See xref:../config_policy_ctrl.adoc#configure-config-policy-controller[Configure the configuration policy controller] for more details.

To receive information about the time used to evaluate configuration policies, perform a Prometheus query that resembles the following expression:

`rate(config_policies_evaluation_duration_seconds_sum[10m])/rate (config_policies_evaluation_duration_seconds_count[10m]`

The `config-policy-controller` pod running on managed clusters in the `open-cluster-management-agent-addon` namespace calculates the metric. The `config-policy-controller` does not send the metric to observability by default.

[#verify-configuration-changes]
== Verify configuration changes

When the new configuration is applied by the controller, the `ManifestApplied` parameter is updated in the `ManagedClusterAddOn`. That condition timestamp can be used to verify the configuration correctly. For example, this command can verify when the `cert-policy-controller` on the `local-cluster` was updated:

----
oc get -n local-cluster managedclusteraddon cert-policy-controller | grep -B4 'type: ManifestApplied'
----

You might receive the following output:

----
 - lastTransitionTime: "2023-01-26T15:42:22Z"
    message: manifests of addon are applied successfully
    reason: AddonManifestApplied
    status: "True"
    type: ManifestApplied
----

Return to the link:../governance/grc_intro.adoc#governance[Governance] page for more topics.
