[#policy-set-controller]
= Policy set controller

The policy set controller aggregates the policy status scoped to policies that are defined in the same namespace. Create a policy set (`PolicySet`) to group policies that in the same namespace. All policies in the `PolicySet` are placed together in a selected cluster by creating a `PlacementBinding` to bind the `PolicySet` and `Placement`.

Learn more details about the policy set structure in the following sections:

* <<policy-set-yaml-structure,Policy set controller YAML structure>>
* <<policy-set-table,Policy set controller YAML table>>
* <<policy-set-sample,Policy set CR sample>>

[#policy-set-yaml-structure]
== Policy set YAML structure

Your policy set might resemble the following YAML file:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: PolicySet
metadata:
  name: pci
  namespace: default  
spec:
  description: Policies for PCI compliance
  policies:
  - policy-pod
  - policy-namespace
----




[#policy-set-table]
== Policy set table


View the following parameter table for descriptions:

.Parameter table
|===
| Field | Description

| apiVersion
| Required.
Set the value to `policy.open-cluster-management.io/v1`.

| kind
| Required.
Set the value to `Policy` to indicate the type of policy.

| metadata.name
| Required.
The name for identifying the policy resource.

| spec
| Required.
Add configuration details for your policy.

| spec.clusterRole
| Optional.
The cluster role (i.e. `ClusterRole`) to monitor. This defaults to `cluster-admin` if not specified.

| spec.severity
| Optional.
Informs the user of the severity when the policy is non-compliant. Use the following parameter values: `low`, `medium`, or `high`.

| spec.remediationAction
| Optional.
Specifies the remediation of your policy.
Enter  `inform`.

| spec.ignoreClusterRoleBindings
| Optional.
A list of regular expression (regex) values that indicate which cluster role binding names to ignore. These regular expression values must follow https://pkg.go.dev/regexp/syntax[Go regexp syntax]. By default, all cluster role bindings that have a name that starts with `system:` are ignored. It is recommended to set this to a stricter value. To not ignore any cluster role binding names, set the list to a single value of `.^` or some other regular expression that never matches.

| spec.maxClusterRoleBindingUsers
| Required.
Maximum number of IAM role bindings that are available before a policy is considered non-compliant.
|===


[#iam-policy-sample]
== IAM policy sample

See https://github.com/stolostron/policy-collection/blob/main/stable/AC-Access-Control/policy-limitclusteradmin.yaml[`policy-limitclusteradmin.yaml`] to view the IAM policy sample. See xref:../governance/create_policy.adoc#managing-security-policies[Managing security policies] for more information.

Refer to xref:../governance/policy_controllers.adoc#policy-controllers[Policy controllers] for more topics.





[#policy-set-sample]
== Policy set sample

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: PolicySet
metadata:
  name: pci
  namespace: default  
spec:
  description: Policies for PCI compliance
  policies:
  - policy-pod
  - policy-namespace
status:
  compliant: NonCompliant
  placement:
  - placementBinding: binding1
    placement: placement1
    placementDecisions: 
    - placementDecision1               # could be multiple 
  results:
  - policy: policy-pod
    compliant: NonCompliant
    clusters: 
    - clusterName: managed1
      clusterNamespace: managed1
      compliant: Compliant
    - clusterName: managed2
      clusterNamespace: managed2
      compliant: NonCompliant
  - policy: policy-namespace
    message: policy-namespace not found
----

