[#role-policy]
= Role policy

The Kubernetes configuration policy controller monitors the status of role policies. Define roles in the `object-template` to set rules and permissions for specific roles in your cluster.

Learn more details about the role policy structure in the following sections:

* <<role-policy-yaml-structure,Role policy YAML structure>>
* <<role-policy-table,Role policy table>>
* <<role-policy-sample,Role policy sample>>

[#role-policy-yaml-structure]
== Role policy YAML structure

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name:
  namespace:
  annotations:
    policy.open-cluster-management.io/standards:
    policy.open-cluster-management.io/categories:
    policy.open-cluster-management.io/controls:
    policy.open-cluster-management.io/description:
spec:
  remediationAction:
  disabled:
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name:
        spec:
          remediationAction:
          severity:
          namespaceSelector:
            exclude:
            include:
            matchLabels:
            matchExpressions:
          object-templates:
            - complianceType:
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name:
                rules:
                  - apiGroups:
                    resources:
                    verbs:
                ...
----

[#role-policy-table]
== Role policy table

.Parameter table
|===
| Field | Optional or required | Description

| `apiVersion`
| Required
| Set the value to `policy.open-cluster-management.io/v1`.

| `kind`
| Required
| Set the value to `Policy` to indicate the type of policy.

| `metadata.name`
| Required
| The name for identifying the policy resource.

| `metadata.namespace`
| Required
| The namespace of the policy.

| `spec.remediationAction`
| Optional
| Specifies the remediation of your policy. The parameter values are `enforce` and `inform`. This value is optional because the value overrides any values provided in `spec.policy-templates`.

| `spec.disabled`
| Required
| Set the value to `true` or `false`. The `disabled` parameter provides the ability to enable and disable your policies.

| `spec.policy-templates[].objectDefinition`
| Required
| Used to list configuration policies containing Kubernetes objects that must be evaluated or applied to the managed clusters.
|===

[#role-policy-sample]
== Role policy sample

Apply a role policy to set rules and permissions for specific roles in your cluster. For more information on roles, see link:../access_control/rbac.adoc#role-based-access-control[Role-based access control]. View a sample of a role policy, see link:https://github.com/open-cluster-management/policy-collection/blob/main/stable/AC-Access-Control/policy-role.yaml[`policy-role.yaml`].

To learn how to manage role policies, refer to xref:../governance/create_config_pol.adoc#managing-configuration-policies[Managing configuration policies] for more information. See the xref:../governance/config_policy_ctrl.adoc#kubernetes-config-policy-controller[Kubernetes configuration policy controller] to view other configuration policies that are monitored the controller.
