[#security-context-constraints-policy]
= Security Context Constraints policy

Kubernetes configuration policy controller monitors the status of your Security Context Constraints (SCC) policy. Apply an Security Context Constraints (SCC) policy to control permissions for pods by defining conditions in the policy.

Learn more details about SCC policies in the following sections:

* <<scc-policy-yaml-structure,SCC policy YAML structure>>
* <<scc-policy-table,SCC policy table>>
* <<scc-policy-sample,SCC policy sample>>

[#scc-policy-yaml-structure]
== SCC policy YAML structure

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-scc
  namespace: open-cluster-management-policies
spec:
  complianceType:
  remediationAction:
  namespaces:
    exclude:
    include:
  object-templates:
    - complianceType:
      objectDefinition:
        apiVersion:
        kind: SecurityContextConstraints # restricted scc
        metadata:
          annotations:
            kubernetes.io/description:
          name: sample-restricted-scc
        allowHostDirVolumePlugin:
        allowHostIPC:
        allowHostNetwork:
        allowHostPID:
        allowHostPorts:
        allowPrivilegeEscalation:
        allowPrivilegedContainer:
        allowedCapabilities:
        defaultAddCapabilities:
        fsGroup:
         type:
        groups:
        - system:
        priority:
        readOnlyRootFilesystem:
        requiredDropCapabilities:
        runAsUser:
          type:
        seLinuxContext:
          type:
        supplementalGroups:
          type:
        users:
        volumes:
----

[#scc-policy-table]
== SCC policy table

|===
| Field | Description

| apiVersion
| Required.
Set the value to `policy.open-cluster-management.io/v1`.

| kind
| Required.
Set the value to `Policy` to indicate the type of policy.

| metadata.name
| Required.
The name to identify the policy resource.

| metadata.namespace
| Required.
The namespace within the managed cluster where the policy is created.

| spec.complianceType
| Required.
Set the value to `"musthave"`

| spec.remediationAction
| Required.
Specifies the remediation of your policy.
The parameter values are `enforce` and `inform`.
*Important*: Some policies might not support the enforce feature.

| spec.namespace
| Required.
Managed cluster namespace to which you want to apply the policy.
Enter parameter values for `include`, which are the namespaces you want to apply to the policy to.
The `exclude` parameter specifies the namespaces you explicitly do not want to apply the policy to.
*Note*: A namespace that is specified in the object template of a policy controller overrides the namespace in the corresponding parent policy.

| spec.object-template
| Required.
Used to list any other Kubernetes object that must be evaluated or applied to the managed clusters.
|===

For explanations on the contents of a SCC policy, see https://docs.openshift.com/container-platform/4.11/authentication/managing-security-context-constraints.html#security-context-constraints-about_configuring-internal-oauth[Managing Security Context Constraints] from the {ocp-short} documentation.

[#scc-policy-sample]
== SCC policy sample

Apply a Security context constraints (SCC) policy to control permissions for pods by defining conditions in the policy. For more information see, https://docs.openshift.com/container-platform/4.11/authentication/managing-security-context-constraints.html#security-context-constraints-about_configuring-internal-oauth[Managing Security Context Constraints (SCC)].

See https://github.com/stolostron/policy-collection/blob/main/stable/SC-System-and-Communications-Protection/policy-scc.yaml[`policy-scc.yaml`] to view the policy sample. See xref:../governance/create_config_pol.adoc#managing-configuration-policies[Managing configuration policies] for more information about managing other policies.

Refer to xref:../governance/config_policy_ctrl.adoc#kubernetes-configuration-policy-controller[Kubernetes configuration policy controller] to learn about other configuration policies.
