:_mod-docs-content-type: REFERENCE

[#lookup]
= lookup

[role="_abstract"]
The `lookup` function returns the Kubernetes resource as a JSON compatible map. When you use this function, enter the API version, kind, namespace, name, and optional label selectors of the Kubernetes resource. You must use the same namespace that is used for the policy within the hub cluster template. See xref:../governance/template_support_intro.adoc#template-processing[Template processing] for more details.

If the requested resource does not exist, an empty map is returned. If the resource does not exist and the value is provided to another template function, you might get the following error: `invalid value; expected string`.

*Note:* Use the `default` template function, so the correct type is provided to later template functions. See xref:../governance/template_functions.adoc#_sprig_open_source[Sprig open source].

View the following syntax for the function:

----
func lookup (apiversion string, kind string, namespace string, name string, labelselector ...string) (value string, err Error)
----

For label selector examples, see the reference to the _Kubernetes labels and selectors_ documentation, in xref:../governance/template_functions.adoc#template-functions[Additional resources]. View the following example of the configuration policy that enforces a Kubernetes resource on the target managed cluster:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: demo-lookup
spec:
  object-templates:
  - objectDefinition:
      ...
      data:
        app-name: sampleApp
        app-description: "this is a sample app"
        metrics-url: >-
          http://{{ (lookup "v1" "Service" "default" "metrics").spec.clusterIP }}:8080
----
+
* Configuration values can be set as key-value properties.
* The value for the `metrics-url` data key is a template that retrieves the `v1/Service` Kubernetes resource `metrics` from the `default` namespace, and is set to the value of the `spec.clusterIP` in the queried resource.
