:_mod-docs-content-type: REFERENCE

[#from-secret]
= fromSecret

[role="_abstract"]
The `fromSecret` function returns the value of the given data key in the secret.

View the following syntax for the function:

----
func fromSecret (ns string, secretName string, datakey string) (dataValue string, err error)
----

When you use this function, enter the namespace, name, and data key of a Kubernetes `Secret` resource. You must use the same namespace that is used for the policy when using the function in a hub cluster template. See xref:../governance/template_support_intro.adoc#template-processing[Template processing] for more details. 

View the following configuration policy that enforces a `Secret` resource on the target cluster:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: demo-fromsecret
spec:
  object-templates:
  - objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: demosecret
        namespace: test
      type: Opaque
      data:
        USER_NAME: YWRtaW4=
        PASSWORD: '{{ fromSecret "default" "localsecret" "PASSWORD" }}'
----
+
* You receive a policy violation if the Kubernetes `Secret` resource does not exist on the target cluster. If the data key does not exist on the target cluster, the value becomes an empty string.
* When you use the `fromSecret` function with hub cluster templates, the output is automatically encrypted using the xref:../governance/template_functions.adoc#_protect[protect] function to protect the value in flight to the managed cluster.
* The value for the `PASSWORD` data key is a template that references the secret on the target cluster.

*Important:* When you add multiline string values such as, certificates, always add `| toRawJson | toLiteral` syntax at the end of the template pipeline to handle line breaks. For example, if you are copying a certificate from a `Secret` resource and including it in a `ConfigMap` resource, your template pipeline might be similar to the following syntax:

----
ca.crt: '{{ fromSecret "openshift-config" "ca-config-map-secret" "ca.crt"  | base64dec | toRawJson | toLiteral }}'
----

- The `toRawJson` template function converts the input value to a JSON string with new lines escaped to not affect the YAML structure.
- The `toLiteral` template function removes the outer single quotes from the output. For example, when templates are processed for the `key: '{{ 'hello\nworld' | toRawJson }}'` template pipeline, the output is `key: '"hello\nworld"'`. The output of the `key: '{{ 'hello\nworld' | toRawJson | toLiteral }}'` template pipeline is `key: "hello\nworld"`.
 
