[#support-templates-in-config-policies]
= Template processing
//be sure to add info about hub and managed cluster templates and reason to use this feature 

Configuration policies support the inclusion of Golang text templates in the object definitions. These templates are resolved at runtime either on the hub cluster or the target managed cluster using configurations related to that cluster. This gives you the ability to define configuration policies with dynamic content, and inform or enforce Kubernetes resources that are customized to the target cluster.

A configuration policy definition can contain both hub cluster and managed cluster templates. Hub cluster templates are processed first on the hub cluster, then the policy definition with resolved hub cluster templates is propagated to the target clusters. On the managed cluster, the `ConfigurationPolicyController` processes any managed cluster templates in the policy definition and then enforces or verifies the fully resolved object definition.

The template syntax must be conformed to the Golang template language specification, and the resource definition generated from the resolved template must be a valid YAML. See the Golang documentation about _Package templates_ for more information. Any errors in template validation are recognized as policy violations. When you use a custom template function, the values are replaced at runtime.

*Important:* If you use hub cluster templates to propagate secrets or other sensitive data, the sensitive data exists in the managed cluster namespace on the hub cluster and on the managed clusters where that policy is distributed. The template content is expanded in the policy, and policies are not encrypted by the {ocp-short} ETCD encryption support. To address this, use `fromSecret`, which automatically encrypts the values from the Secret, or `protect` to encrypt other values.
//is the important note needed on both files?
Continue reading the following topics:

* xref:../governance/template_functions.adoc#template-functions[Template functions]
* xref:../governance/adv_template_process.adoc#adv-template-processing[Advanced template processing in configuration policies]




