[#support-templates-in-config-policies]
= Template processing
//be sure to add info about hub and managed cluster templates and reason to use this feature 
Configuration policies support the inclusion of Golang text templates in the object definitions. These templates are resolved at runtime either on the hub cluster or the target managed cluster using configurations related to that cluster. This gives you the ability to define configuration policies with dynamic content, and inform or enforce Kubernetes resources that are customized to the target cluster.

The template syntax must be conformed to the Golang template language specification, and the resource definition generated from the resolved template must be a valid YAML. See the Golang documentation about _Package templates_ for more information. Any errors in template validation are recognized as policy violations. When you use a custom template function, the values are replaced at runtime.

Continue reading the following topics:

* xref:../governance/template_functions.adoc#template-functions[Template functions]
//topic might be removed
* xref:../governance/hub_cluster_templates.adoc#hub-templates[Support for hub cluster templates in configuration policies]
