:_mod-docs-content-type: CONCEPT

[#template-functions]
= Template functions

[role="_abstract"]
Reference Kubernetes resources such as resource-specific and generic template functions on your hub cluster by using the `{{hub ... hub}}` delimiters, or on your managed cluster by using the  `{{ ... }}` delimiters. You can use resource-specific functions for convenience and to make the content of your resources more accessible.

If you use the generic function, `lookup`, which is more advanced, familiarize yourself with the YAML structure of the resource that is being looked up. In addition to these functions, utility functions such as `base64enc`, `base64dec`, `indent`, `autoindent`, `toInt`, `toBool`, and more are available.

To conform templates with YAML syntax, you must define templates in the policy resource as strings using quotes or a block character (`|` or `>`). This causes the resolved template value to also be a string. To override this, use `toInt` or `toBool` as the final function in the template to initiate further processing that forces the value to be interpreted as an integer or boolean respectively.

== _autoindent_

The `autoindent` function acts like the `indent` function that automatically determines the number of leading spaces based on the number of spaces before the template.

View the following example of the configuration policy that uses the `autoindent` function:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: demo-fromsecret
spec:
  object-templates:
  - objectDefinition:
      ...
      data:
        Ca-cert: >-
          {{ ( index ( lookup "v1" "Secret" "default" "mycert-tls"  ).data  "ca.pem"  ) |  base64dec | autoindent }}
----

== _toInt_

The `toInt` function casts and returns the integer value of the input value. When this is the last function in the template, there is further processing of the source content. This is to ensure that the value is interpreted as an integer by the YAML. When you use this function, enter the data that needs to be casted as an integer. View the following syntax for the function:

----
func toInt (input interface{}) (output int)
----

View the following example of the configuration policy that uses the `toInt` function:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: demo-template-function
spec:
  object-templates:
  - objectDefinition:
      ...
      spec:
        vlanid: >-
          {{ (fromConfigMap "site-config" "site1" "vlan")  | toInt }}
----

== _toBool_

The `toBool` function converts the input string into a boolean, and returns the boolean. When this is the last function in the template, there is further processing of the source content. This is to ensure that the value is interpreted as a boolean by the YAML. When you use this function, enter the string data that needs to be converted to a boolean. View the following syntax for the function:

----
func toBool (input string) (output bool)
----

View the following example of the configuration policy that uses the `toBool` function:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: demo-template-function
spec:
  object-templates:
  - objectDefinition:
      ...
      spec:
        enabled: >-
          {{ (fromConfigMap "site-config" "site1" "enabled")  | toBool }}
----

== _fromYaml_

The `fromYaml`, or `fromYAML`, function parses a YAML string into a Golang object. You can use this function with a `ConfigMap` resource that has a YAML string value.

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: demo-template-function
spec:
  object-templates:
  - objectDefinition:
      ...
      spec:
        replicas: >-
          {{ (fromConfigMap "default" "app-config" "config.yaml") | fromYaml | index "replicas" }}
----

== _toYaml_

The `toYaml`, or `toYAML`, function parses a Golang object into a YAML string. For a multiline result to be properly indented, you must pass the output to either the `autoindent` or `indent` function.

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: demo-template-function
spec:
  object-templates:
  - objectDefinition:
      ...
      data:
        config.yaml: |
          {{ dict "key1" "value1" "key2" "value2" | toYaml | autoindent }}
----

== _protect_

The `protect` function enables you to encrypt a string in a hub cluster policy template. It is automatically decrypted on the managed cluster when the policy is evaluated. View the following example of the configuration policy that uses the `protect` function:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: demo-template-function
spec:
  object-templates:
  - objectDefinition:
    ...
    spec:
      enabled: >-
        {{hub (lookup "v1" "Secret" "default" "my-hub-secret").data.message | protect hub}}
----

In the previous YAML example, there is an existing hub cluster policy template that is defined to use the `lookup` function. On the replicated policy in the managed cluster namespace, the value might resemble the following syntax: `$ocm_encrypted:okrrBqt72oI+3WT/0vxeI3vGa+wpLD7Z0ZxFMLvL204=`

Each encryption algorithm used is AES-CBC using 256-bit keys. Each encryption key is unique per managed cluster and is automatically rotated every 30 days.

This ensures that your decrypted value is to never be stored in the policy on the managed cluster.

To force an immediate rotation, delete the `policy.open-cluster-management.io/last-rotated` annotation on the `policy-encryption-key` Secret in the managed cluster namespace on the hub cluster. Policies are then reprocessed to use the new encryption key.

== _toLiteral_

The `toLiteral` function removes any quotation marks around the template string after it is processed. You can use this function to convert a JSON string from a config map field to a JSON value in the manifest. Run the following function to remove quotation marks from the `key` parameter value:

----
key: '{{ "[\"10.10.10.10\", \"1.1.1.1\"]" | toLiteral }}'
----

After using the `toLiteral` function, the following update is displayed:

----
key: ["10.10.10.10", "1.1.1.1"]
----

== _copySecretData_

The `copySecretData` function copies all of the `data` contents of the specified secret. View the following sample of the function:

[source,yaml]
----
...
objectDefinition:
  apiVersion: v1
  kind: Secret
  metadata:
    name: my-secret-copy
  data: '{{ copySecretData "default" "my-secret" }}'
----
+
* When you use this function with hub cluster templates, the output is automatically encrypted using the _protect_ function.

== _copyConfigMapData_

The `copyConfigMapData` function copies all of the `data` content of the specified config map. View the following sample of the function:

[source,yaml]
----
...
objectDefinition:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my-secret-copy
  data: '{{ copyConfigMapData "default" "my-configmap" }}'
----

== _getNodesWithExactRoles_

The `getNodesWithExactRoles` function returns a list of nodes with only the roles that you specify, and ignores nodes that have any additional roles except the `node-role.kubernetes.io/worker` role. View the following sample function where you are selecting `"infra"` nodes and ignoring the storage nodes:

[source,yaml]
----
...
objectDefinition:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my-configmap
    data:
      infraNode: |
        {{- range $i,$nd := (getNodesWithExactRoles "infra").items }}
        node{{ $i }}: {{ $nd.metadata.name }}
        {{- end }}
      replicas: {{ len ((getNodesWithExactRoles "infra").items) | toInt }}
----

== _hasNodesWithExactRoles_

The `hasNodesWithExactRoles` function returns the `true` value if the cluster contains nodes with only the roles that you specify, and ignores nodes that have any additional roles except the `node-role.kubernetes.io/worker` role. View the following sample of the function:

[source,yaml]
----
...
objectDefinition:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my-configmap
  data:
    key: '{{ hasNodesWithExactRoles "infra" }}'
----

== _skipObject_

The `skipObject` function is only available in managed cluster templates in a `ConfigurationPolicy` resource. Calling `{{ skipObject }}` at any time inside a Go template signals to skip that particular object for the policy. When you use the `skipObject` with the `objectSelector`, you can further filter objects selected by name. You can call `skipObject` by itself inside a conditional or with an optional boolean argument.

View the following example that selects objects that have the label `foo: bar`, but skips objects that have a name with the suffix `-prod`:

[source,yaml]
----
...
object-templates:
  - objectSelector:
      matchExpressions:
      - key: foo
        operator: In
        values:
        - bar
    objectDefinition:
      apiVersion: v1
      kind: ConfigMap
      data:
        key: '{{ skipObject (hasSuffix "-prod" .ObjectName) }}{{ hasNodesWithExactRoles "infra" }}'
----

== Sprig open source

{acm-short} supports most of the template functions from the `sprig` open source project, except for `env` and `expandenv`. View the following table:

.Table of supported, community Sprig functions
|===
| Sprig library | Functions 

| Cryptographic and security
| `htpasswd`

| Date
| `date`, `mustToDate`, `now`, `toDate`

| Default 
| `default`, `empty`, `fromJson`, `mustFromJson`, `ternary`, `toJson`, `toRawJson`, `mustToRawJson`

The `Json` functions listed are also aliased to an equivalent uppercase `JSON` function.

| Dictionaries and dict
| `dict`, `dig`, `get`, `hasKey`, `keys`, `merge`, `mustMerge`, `set`, `unset`, `values`

| Encoding
| `b64dec`, `b64enc`

| Flow control
| `fail`

| Integer math
| `add`, `mul`, `div`, `round`, `sub` 

| Integer slice
| `until`, `untilStep`, 

| Lists
| `append`, `has`, `list`, `mustAppend`, `mustHas`, `mustPrepend`, `mustSlice`, `prepend`, `slice`

| String lists
| `concat`, `join`, `sortAlpha`, `split`, `splitn`, `splitList`

| Strings
| `cat`, `contains`, `hasPrefix`, `hasSuffix`,  `lower`, `mustRegexFind`, `mustRegexFindAll`, `mustRegexMatch`, `quote`, `regexFind`, `regexFindAll`, `regexMatch`, `regexQuoteMeta`, `replace`, `substr`, `trim`, `trimAll`, `trunc`, `upper`

| Version comparison
| `semver`, `semverCompare`
|===

.Additional resources

* xref:../governance/template_function_from_secret.adoc#from-secret[fromSecret]
* xref:../governance/template_function_from_configmap.adoc#from-configmap[fromConfigMap]
* xref:../governance/template_function_from_cluster_claim.adoc#from-cluster-claim[fromClusterClaim]
* xref:../governance/template_function_lookup_cluster_claim.adoc#lookup-cluster-claim[lookupClusterClaim]
* xref:../governance/template_function_lookup.adoc#lookup[lookup]
* xref:../governance/template_function_base64enc.adoc#base64enc[base64enc]
* xref:../governance/template_function_base64dec.adoc#base64dec[base64dec]
* xref:../governance/template_function_indent.adoc#indent[indent]
* xref:../governance/template_support_intro.adoc#template-processing[Template processing]
* xref:../governance/adv_template_process.adoc#adv-template-processing[Advanced template processing in policies]
* xref:../governance/policy_cli_tool.adoc#policy-cli-tool[Policy command line interface]
* link:https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[Kubernetes labels and selectors]
* link:https://golang.org/pkg/text/template[Golang documentation - Package templates]
* link:https://masterminds.github.io/sprig/[Sprig Function Documentation]
