[#zettaset-policy-intro]
= ZettaSet policy

Kubernetes configuration policy controller monitors the status of your `ZettaSet` policy. Apply a `ZettaSet` policy to deploy the Zettaset application. The `Zettaset` policy uses the ConfigMap reloader to restart the deployment after the ConfigMap changes. The policy deploys a replica of the `zts-cmc-deployment` policy.

Learn more details about a `ZettaSet` policy in the following sections:

* <<zettaset-policy-yaml-structure,Zettaset policy YAML structure>>
* <<zettaset-policy-table,Zettaset policy table>>
* <<zettaset-policy-sample,Zettaset policy sample>>

[#zettaset-policy-yaml-structure]
== Zettaset policy YAML structure

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-zts-cmc
spec:
  remediationAction: 
  disabled: 
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-zts-cmc-reloader-deployment
        spec:
          remediationAction: 
          severity: 
          namespaceSelector:
            exclude:
            include:
          object-templates:
            - complianceType: 
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: reloader-reloader
                  labels:
                    app: 
                spec:
                  replicas: 
                  selector:
                    matchLabels:
                      app: 
                  template:
                    metadata:
                      labels:
                        app: 
                    spec:
                      containers:
                        - name: 
                          imagePullPolicy: 
                          image: 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-zts-cmc
        spec:
          remediationAction:  
          severity: 
          namespaceSelector:
            exclude:
            include:
          object-templates:
            - complianceType: 
              objectDefinition:
                apiVersion: 
                kind: Deployment
                metadata:
                  annotations:
                    configmap.reloader.stakater.com/reload: 
                  name: zts-cmc-app-deploy
                  labels:
                    app: 
                spec:
                  replicas: 
                  selector:
                    matchLabels:
                      app: 
                  template:
                    metadata:
                      labels:
                        app: 
                    spec:
                      containers:
                        - name: 
                          imagePullPolicy: 
                          image: 
                          env:
                           - name: 
                             valueFrom:
                               configMapKeyRef:
                                 name: 
                                 key: 
                          ports:
                            - containerPort: 
                      imagePullSecrets:
                        - name: 
----

[#zettaset-policy-table]
== Zettaset policy table

|===
| Field | Optional or required | Description

| `apiVersion`
| Required
| Set the value to `policy.open-cluster-management.io/v1`.

| `kind`
| Required
| Set the value to `Policy` to indicate the type of policy.

| `metadata.name`
| Required
| The name of the policy. 

| `metadata.annotations`
| Required
| Used to specify a set of security details that describes the set of standards the policy is trying to validate. All annotations documented here are represented as a string that contains a comma-separated list.
//^are there any default values? Is this required for the ZettaSet application 

| `spec.remediationAction`
| Required
| Specifies the remediation of your policy. The parameter values are `enforce` and `inform`. By default, the remediation action is set to `inform`.

| `spec.disabled`
| Required
| Set the value to `true` or `false`. The `disabled` parameter provides the ability to enable and disable your policy.

| `spec.policy-templates`
| Required
| List of policies that must be evaluated or applied. For this policy, the policy template defined uses the  `reloader` ConfigMap to restart the deployment. 

| `policy-templates.object-templates`
| Required
| List of application deployments. For this policy, the policy template defined uses a ConfigMap reloader to restart the deployment. 

| `policy-templates.complianceType`
| Required
| Set the value to `"musthave"`.

| `object-templates.objectDefinitions`
| Required
| Use the `reloader` ConfigMap.

| `policy-templates.objectDefinition`
| Required
| Define the configuration to deploy the replica of the Zettaset application.

| `spec.namespaceSelector`
| Required for namespaced objects that do not have a namespace specified
| Determines namespaces in the managed cluster that the object is applied to. The `include` and `exclude` parameters accept file path expressions to include and exclude namespaces by name. The `matchExpressions` and `matchLabels` parameters specify namespaces to include by label. See the link:https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[Kubernetes labels and selectors] documentation. The resulting list is compiled by using the intersection of results from all parameters.
|===

[#zettaset-policy-sample]
== Zettaset policy sample

See link:https://github.com/stolostron/policy-collection/blob/main/stable/CM-Configuration-Management/policy-zts-cmc.yaml[`policy-zts-cmc.yaml`] to view the complete policy. Refer to xref:../governance/create_config_pol.adoc#managing-configuration-policies[Managing configuration policies] for more information about other confirguration policies.
