[#zettaset-policy]
= ZettaSet policy

Kubernetes configuration policy controller monitors the status of your `ZettaSet` policy. Apply a `ZettaSet` policy to deploy the Zettaset application. It uses the ConfigMap reloader to restart the deployment when the ConfigMap changes. The policy deploys a replica of the `zts-cmc-deployment` policy.

Learn more details about SCC policies in the following sections:

* <<zettaset-policy-yaml-structure,Zettaset policy YAML structure>>
* <<zettaset-policy-table,Zettaset policy table>>
* <<zettaset-policy-sample,Zettaset policy sample>>

[#zettaset-policy-yaml-structure]
== Zettaset policy YAML structure
//for yaml examples, we usually leave them empty. Which parameters require a value? Can you help with providing the best structure for the user. Is the PLacementBinding required in this example since the policies are populated when it is selected in the UI
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-zts-cmc
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-zts-cmc-reloader-deployment
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: reloader-reloader
                  labels:
                    app: reloader-reloader
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      app: reloader-reloader
                  template:
                    metadata:
                      labels:
                        app: reloader-reloader
                    spec:
                      containers:
                        - name: reloader-reloader
                          imagePullPolicy: IfNotPresent
                          image: "stakater/reloader:v0.0.117"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-zts-cmc
        spec:
          remediationAction: inform 
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default 
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  annotations:
                    configmap.reloader.stakater.com/reload: "zts-cmc-configmap"
                  name: zts-cmc-app-deploy
                  labels:
                    app: zts-cmc-app
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      app: zts-cmc-app
                  template:
                    metadata:
                      labels:
                        app: zts-cmc-app
                    spec:
                      containers:
                        - name: zts-cmc
                          imagePullPolicy: Always
                          image: zettasetimg/test:zts-acm-web-application-0.0.2_commitid-a1b5f9
                          env:
                           - name: IP_ADDRESS_CMC
                             valueFrom:
                               configMapKeyRef:
                                 name: zts-cmc-configmap
                                 key: application.properties
                          ports:
                            - containerPort: 8080
                      imagePullSecrets:
                        - name: zts-dockerhub-token
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-zts-cmc
placementRef:
  name: placement-policy-zts-cmc
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-zts-cmc
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-zts-cmc
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
----

[#zettaset-policy-table]
== Zettaset policy table
//I also need help with completing the table
|===
| Field | Optional or required |Description

| apiVersion
| Required
| Set the value to `policy.open-cluster-management.io/v1`.

| kind
| Required
| Set the value to `Policy` to indicate the type of policy.

| metadata.name
| Required
| The name to identify the policy resource. 
//^I assume that the user cann use any name? Can the user only use policy-zts-cmc?

| metadata.annotations
| Optional
| Used to specify a set of security details that describes the set of standards the policy is trying to validate. All annotations documented here are represented as a string that contains a comma-separated list.
//^are there any default values? 

| spec.remediationAction
| Required
| Specifies the remediation of your policy. The parameter values are `enforce` and `inform`. By default, the remediation action is set to `inform`.

| spec.disabled
| Required
| Set the value to `true` or `false`. The `disabled` parameter provides the ability to enable and disable your policy.
//^it seems like this is a parameter that doesnt need to be mentioned. It is mentiioned in the Policy overview topic - policy_example.adoc

| spec.policy-templates
| Required
| List of application deployments. For this policy, the poliicy template defined uses a ConfigMap reloader to restart the deployment. 

| spec.complianceType
| Required
| Set the value to `"musthave"`.


| spec.namespace
| Required
| Managed cluster namespace to which you want to apply the policy. Enter parameter values for `include`, which are the namespaces you want to apply to the policy to.

The `exclude` parameter specifies the namespaces you explicitly do not want to apply the policy to.

*Note*: A namespace that is specified in the object template of a policy controller overrides the namespace in the corresponding parent policy.

| spec.object-template
| Required
| Used to list any other Kubernetes object that must be evaluated or applied to the managed clusters.
|===
