[#create-a-cluster]
= Creating a cluster

The multicluster engine for Kubernetes uses internal Hive components to create Red Hat OpenShift Container Platform clusters. See the following information to learn how to create clusters.

* <<create-a-cluster-with-clusterdeployment,Create a cluster with ClusterDeployment>>
* <<create-a-cluster-with-clusterpool,Create a cluster with cluster pool>>

[#create-a-cluster-with-clusterdeployment]
== Create a cluster with ClusterDeployment

A `ClusterDeployment` is a Hive custom resource. See the following documentation to learn how to create an individual cluster:

Follow the https://github.com/openshift/hive/blob/master/docs/using-hive.md#using-hive[Using Hive] documentation to create the `ClusterDeployment` custom resource.

[#create-a-cluster-with-clusterpool]
== Create a cluster with ClusterPool

A `ClusterPool` is also a Hive custom resource that is used to create multiple clusters. Create a cluster with the Hive `ClusterPool` API.

Follow the https://github.com/openshift/hive/blob/master/docs/clusterpools.md[Cluster Pools] documentation to provision a cluster.

[#troubleshoot-cluster-creation]
== Troubleshooting cluster creation

When creating a cluster, you must clone the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets/fast[clusterImageSets] repository and apply it to your hub cluster. You can then select the {ocp} release images when you create a cluster.
