[#creating-a-cluster-on-virtualization]
= Creating a cluster on Red Hat Virtualization

You can use the {product-title} console to create a {ocp} cluster on Red Hat Virtualization. 

When you create a cluster, the creation process uses the {ocp-short} installer with the Hive resource. If you have questions about cluster creation after completing this procedure, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/installing-on-rhv[Installing on RHV] in the {ocp-short} documentation for more information about the process.  

* <<virtualization_prerequisites,Prerequisites>>
* <<virtualization-creating-your-cluster-with-the-console,Creating your cluster with the console>>

[#virtualization_prerequisites]
== Prerequisites

See the following prerequisites before creating a cluster on Red Hat Virtualization:

* You must have a deployed {product-title} hub cluster.

* You need Internet access for your {product-title} hub cluster so it can create the Kubernetes cluster on Red Hat Virtualization.

* You need a Red Hat Virtualization credential. See link:../credentials/credential_virtualization.adoc#creating-a-credential-for-virtualization[Creating a credential for Red Hat Virtualization] for more information.

* You need a configured domain and virtual machine proxy for the oVirt Engine virtual machines. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/installing-on-rhv[Installing on RHV] in the {ocp} documentation for instructions on how to configure a domain.

* You must have Red Hat Virtualization login credentials, which include your Red Hat Customer Portal username and password. 

* You need an {ocp-short} image pull secret. You can download your pull secret from: https://console.redhat.com/openshift/install/pull-secret[Pull secret]. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/images/managing-images#using-image-pull-secrets[Using image pull secrets] for more information about pull secrets.

*Note:* If you change your cloud provider access key, you must manually update the provisioned cluster access key. For more information, see the known issue, link:../release_notes/known_issues.adoc#automatic-secret-updates-for-provisioned-clusters-is-not-supported[Automatic secret updates for provisioned clusters is not supported].

[#virtualization-creating-your-cluster-with-the-console]
== Creating your cluster with the console

To create a cluster from the {product-title} console, navigate to *Infrastructure* > *Clusters*. On the _Clusters_ page, click *Create cluster* and complete the steps in the console. 

*Note:* This procedure is for creating a cluster. If you have an existing cluster that you want to import, see xref:../clusters/import.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a target managed cluster to the hub cluster] for those steps.

If you need to create a credential, see link:../credentials/credential_virtualization.adoc#creating-a-credential-for-virtualization[Creating a credential for Red Hat Virtualization] for more information.

The name of your cluster is used in the hostname of the cluster.

*Important:* When you create a cluster, the {product-title-short} controller creates a namespace for the cluster and its resources. Ensure that you include only resources for that cluster instance in that namespace. Destroying the cluster deletes the namespace and all of the resources in it.

*Tip:* Select *YAML: On* to view content updates as you enter the information in the console.

If you want to add your cluster to an existing cluster set, you must have the correct permissions on the cluster set to add it. If you do not have `cluster-admin` privileges when you are creating the cluster, you must select a cluster set on which you have `clusterset-admin` permissions. If you do not have the correct permissions on the specified cluster set, the cluster creation fails. Contact your cluster administrator to provide you with `clusterset-admin` permissions to a cluster set if you do not have any cluster set options to select.

Every managed cluster must be associated with a managed cluster set. If you do not assign the managed cluster to a `ManagedClusterSet`, it is automatically added to the `default` managed cluster set.

If there is already a base DNS domain that is associated with the selected credential that you configured for your Red Hat Virtualization account, that value is populated in that field. You can overwrite the value to change it.

The release image identifies the version of the {ocp-short} image that is used to create the cluster. If the version that you want to use is available, you can select the image from the list of images. If the image that you want to use is not a standard image, you can enter the URL to the image that you want to use. See xref:../clusters/release_images.adoc#release-images[Release images] for more information about release images. 

The information for your node pools includes the number of Cores, Sockets, Memory, and Disk size for the the control plane pool. The three control plane nodes share the management of the cluster activity.

If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool. Valid values are _amd64_, _ppc64le_, _s390x_, and _aarch64_.

The worker pool information requires the pool name, number of cores, memory allocation, disk size allocation, and node count for your worker pools. Your worker nodes within the worker pool can be in a single worker pool, or distributed across multiple worker pools.  

The following networking details are required from your preconfigured oVirt environment. 

* oVirt network name

* API VIP: Specify the IP address to use for internal API communication.
+
*Note:* This value must match the name that you used to create the DNS records listed in the prerequisites section. If not provided, the DNS must be pre-configured so that `api.` resolves correctly.

* Ingress VIP: Specify the IP address to use for ingress traffic. 
+
*Note:* This value must match the name that you used to create the DNS records listed in the prerequisites section. If not provided, the DNS must be pre-configured so that `test.apps.` resolves correctly.

* Network type: The default value is `OpenShiftSDN`. OVNKubernetes is the required setting for using IPv6.

* Cluster network CIDR: This is a number and list of IP addresses that can be used for the pod IP addresses. This block must not overlap another network block. The default value is `10.128.0.0/14`. 

* Network host prefix: Set the subnet prefix length for each node. The default value is `23`.

* Service network CIDR: Provide a block of IP addresses for services. This block must not overlap another network block. The default value is `172.30.0.0/16`.

* Machine CIDR: Provide a block of IP addresses that are used by the {ocp-short} hosts. This block must not overlap another network block. The default value is `10.0.0.0/16`.
+
You can add an additional network by clicking *Add network*. You must have more than one network if you are using IPv6 addresses. 

Proxy information that is provided in the credential is automatically added to the proxy fields. You can use the information as it is, overwrite it, or add the information if you want to enable a proxy. The following list contains the required information for creating a proxy:  

* HTTP proxy URL: Specify the URL that should be used as a proxy for `HTTP` traffic. 

* HTTPS proxy URL: Specify the secure proxy URL that should be used for `HTTPS` traffic. If no value is provided, the same value as the `HTTP Proxy URL` is used for both `HTTP` and `HTTPS`.

* No proxy domains: Provide a comma-separated list of domains that should bypass the proxy. Begin a domain name with a period `.` to include all of the subdomains that are in that domain. Add an asterisk `*` to bypass the proxy for all destinations. 

* Additional trust bundle: Specify the contents of the certificate file that is required to access the mirror registry.

When you review your information and optionally customize it before creating the cluster, you can click the *YAML* switch *On* to view the `install-config.yaml` file content in the panel. You can edit the YAML file with your custom settings, if you have any updates.

*Note:* You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured under the management of {product-title-short}. 

Continue with xref:../clusters/access_cluster.adoc#accessing-your-cluster[Accessing your cluster] for instructions for accessing your cluster. 
