[#uninstalling]
= Uninstalling

When you uninstall multicluster engine for Kubernetes, you see two different levels of the process: A _custom resource removal_ and a _complete operator uninstall_. It might take up to five minutes to complete the uninstall process.

- The custom resource removal is the most basic type of uninstall that removes the custom resource of the `MultiClusterEngine` instance but leaves other required operator resources. This level of uninstall is helpful if you plan to reinstall using the same settings and components.

- The second level is a more complete uninstall that removes most operator components, excluding components such as custom resource definitions. When you continue with this step, it removes all of the components and subscriptions that were not removed with the custom resource removal. After this uninstall, you must reinstall the operator before reinstalling the custom resource.

[#prerequisite-detach]
== Prerequisite: Detach enabled services

Before you uninstall the multicluster engine for Kubernetes engine, you must detach all of the clusters that are managed by that engine. To avoid errors, detach all clusters that are still managed by the engine, then try to uninstall again.

* If you have managed clusters attached, you might see the following message.

+
----
Cannot delete MultiClusterEngine resource because ManagedCluster resource(s) exist
----

+
For more information about detaching clusters, see the _Removing a cluster from management_ section by selecting the information for your provider in xref:./cluster_create_cli.adoc#create-a-cluster[Creating a cluster]. 

[#removing-a-multiclusterengine-instance-by-using-commands]
== Removing resources by using commands

. If you have not already. ensure that your OpenShift Container Platform CLI is configured to run `oc` commands. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the OpenShift CLI] in the OpenShift Container Platform documentation for more information about how to configure the `oc` commands. 

. Change to your project namespace by entering the following command. Replace _namespace_ with the name of your project namespace:
+
----
oc project <namespace>
----

. Enter the following command to remove the `MultiClusterEngine` custom resource:
+
----
oc delete multiclusterengine --all
----
+
You can view the progress by entering the following command: 
+
----
oc get multiclusterengine -o yaml
----

. Enter the following commands to delete the multicluster-engine `ClusterServiceVersion` in the namespace it is installed in:
----
❯ oc get csv
NAME                         DISPLAY                              VERSION   REPLACES   PHASE
multicluster-engine.v2.0.0   multicluster engine for Kubernetes   2.0.0                Succeeded

❯ oc delete clusterserviceversion multicluster-engine.v2.0.0
❯ oc delete sub multicluster-engine
----

The CSV version shown here may be different.

[#deleting-the-components-by-using-the-console]
== Deleting the components by using the console

When you use the RedHat OpenShift Container Platform console to uninstall, you remove the operator. Complete the following steps to uninstall by using the console:

. In the OpenShift Container Platform console navigation, select *Operators* > *Installed Operators* > *multicluster engine for Kubernetes*.

. Remove the `MultiClusterEngine` custom resource.
.. Select the tab for _Multiclusterengine_.

.. Select the _Options_ menu for the MultiClusterEngine custom resource.

.. Select *Delete MultiClusterEngine*.

. Run the clean-up script according to the procedure in the following section.
+
*Tip:* If you plan to reinstall the same 
multicluster engine for Kubernetes version, you can skip the rest of the steps in this procedure and reinstall the custom resource.

. Navigate to *Installed Operators*.

. Remove the _
multicluster engine for Kubernetes_ operator by selecting the _Options_ menu and selecting *Uninstall operator*.

[#troubleshoot-uninstall]
== Troubleshooting Uninstall

If the multicluster engine custom resource is not being removed, remove any potential remaining artifacts by running the clean-up script. 

.. Copy the following script into a file:
+
----
#!/bin/bash
oc delete apiservice v1.admission.cluster.open-cluster-management.io v1.admission.work.open-cluster-management.io
oc delete validatingwebhookconfiguration multiclusterengines.multicluster.openshift.io
oc delete mce --all 
----