[#compliance-operator-policy]
= Compliance operator policy

Compliance operator is an operator that runs OpenSCAP and allows you to keep your {ocp} cluster compliant with the security benchmark that you need. You can install the compliance operator on your managed cluster by using the compliance operator policy. 

The compliance operator policy is created as a Kubernetes configuration policy in {product-title-short}. {ocp-short} 4.6 and later support the compliance operator policy. For more information, see _Understanding the Compliance Operator_ in the  link:https://docs.openshift.com/container-platform/4.6/security/compliance_operator/compliance-operator-understanding.html#compliance-operator-understanding[{ocp-short} documentation] for more details.

[#compliance-operator-resources]
== Compliance operator resources

When you create a compliance operator policy, the following resources are created:

- A compliance operator namespace (`openshift-compliance`) for the operator installation:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: comp-operator-ns
spec:
  remediationAction: inform # will be overridden by remediationAction in parent policy
  severity: high
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-compliance
----

- An operator group (`compliance-operator`) to specify the target namespace:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: comp-operator-operator-group
spec:
  remediationAction: inform # will be overridden by remediationAction in parent policy
  severity: high
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: compliance-operator
          namespace: openshift-compliance
        spec:
          targetNamespaces:
            - openshift-compliance
----

- A subscription to reference the name and channel. The subscription pulls the profile, as a container, that it supports:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: comp-operator-subscription
spec:
  remediationAction: inform  # will be overridden by remediationAction in parent policy
  severity: high
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: compliance-operator
          namespace: openshift-compliance
        spec:
          channel: "4.6"
          installPlanApproval: Automatic
          name: compliance-operator
          source: redhat-operators
          sourceNamespace: openshift-marketplace
----

After you install the compliance operator policy, the following pods are created: `compliance-operator`, `ocp4`, and `rhcos4`.

See xref:../security/create_compliance_operator.adoc#managing-compliance-operator-policy[Creating a compliance operator policy] for more details.