[#kubernetes-configuration-policy-controller]
= Kubernetes configuration policy controller

Configuration policy controller can be used to configure any Kubernetes resource and apply security policies across your clusters.

The configuration policy controller communicates with the local Kubernetes API server to get the list of your configurations that are in your cluster.
For more information about CRDs, see link:https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions].

The configuration policy controller is created on the hub cluster during installation.
Configuration policy controller supports the `enforce` feature and monitors the compliance of the following policies:

* xref:../security/memory_policy.adoc#memory-usage-policy[Memory usage policy]
* xref:../security/namespace_policy.adoc#namespace-policy[Namespace policy]
* xref:../security/image_vuln_policy.adoc#image-vulnerability-policy[Image vulnerability policy]
* xref:../security/pod_nginx_policy.adoc#pod-nginx-policy[Pod nginx policy]
* xref:../security/psp_policy.adoc#pod-security-policy[Pod security policy]
* xref:../security/role_policy.adoc#role-policy[Role policy]
* xref:../security/rolebinding_policy.adoc#rolebinding-policy[Rolebinding policy]
* xref:../security/scc_policy.adoc#security-context-constraints-policy[Security content constraints (SCC) policy]


When the `remediationAction` for the configuration policy is set to `enforce`, the controller creates a replicate policy on the target managed clusters.

[#configuration-policy-controller-yaml-structure]
== Configuration policy controller YAML structure

[source,yaml]
----
Name:         configuration-policy-example
Namespace:
Labels:
APIVersion:   policy.open-cluster-management.io/v1
Kind:         ConfigPolicy
Metadata:
  Finalizers:
    finalizer.policy.open-cluster-management.io
Spec:
  Conditions:
    Ownership:
    NamespaceSelector:
      Exclude:
      Include:
    RemediationAction:
 Status:
   CompliancyDetails:
     Configuration-Policy-Example:
       Default:
       Kube - Public:
   Compliant:          Compliant
 Events:
----

[#configuration-policy-sample]
== Configuration policy sample

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigPolicy
metadata:
  name: policy-config
spec:
  namespaceSelector:
    include: ["default"]
    exclude: []
  remediationAction: inform
    severity: low
    object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Pod
        metadata:
          name: nginx-pod
        spec:
          containers:
          - image: nginx:1.7.9
            name: nginx
            ports:
           - containerPort: 80

----

[#configuration-policy-yaml-table]
== Configuration policy YAML table

.Parameter table
|===
| Field | Description 

| apiVersion
| Required.
Set the value to `policy.open-cluster-management.io/v1`.

| kind
| Required.
Set the value to `ConfigPolicy` to indicate the type of policy.

| metadata.name
| Required. The name of the policy.

| spec
| Required.
Specifications of which configuration policy to monitor and how to remediate them.

| spec.namespaceSelector
| Required. The namespaces within the hub cluster that the policy is applied to.
Enter at least one namespace for the `include` parameter, which are the namespaces you want to apply to the policy to.
The `exclude` parameter specifies the namespaces you explicitly do not want to apply the policy to.

| spec.remediationAction
| Required. Specifies the remediation of your policy. Enter  `inform`

| remediationAction.severity
| Required. Specifies the severity when the policy is non-compliant. Use the following parameter values: `low`, `medium`, or `high`.

| remediationAction.complianceType
| Required. Used to list expected behavior for roles and other Kubernetes object that must be evaluated or applied to the managed clusters. You must use the following verbs as parameter values:

`mustonlyhave`: Indicates that an object must exist with the exact name and relevant fields.

`musthave`: Indicates an object must exist with the same name as specified object-template. The other fields in the template are a subset of what exists in the object.

`mustnothave`: Indicated that an object with the same name or labels cannot exist and need to be deleted, regardless of the specification or rules.
|===


Learn about how policies are applied on your hub cluster.
See xref:../security/policy_sample_intro.adoc#policy-samples[Policy samples] for more details.
Learn how to create and customize policies, xref:../security/manage_policy_overview.adoc#manage-security-policies[Manage security policies].

See xref:../security/policy_controllers.adoc#policy-controllers[Policy controllers] for more information about controllers.
