[#kubernetes-configuration-policy-controller]
= Kubernetes configuration policy controller

Configuration policy controller can be used to configure any Kubernetes resource and apply security policies across your clusters.

The configuration policy controller communicates with the local Kubernetes API server to get the list of your configurations that are in your cluster.
For more information about CRDs, see link:https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions].

The configuration policy controller is created on the hub cluster during installation.
Configuration policy controller supports the `enforce` feature and monitors the compliance of the following policies:

* Memory usage policy
* Namespace policy
* Image vulnerability policy
* Pod nginx policy
* Pod security policy
* Role policy
* Rolebinding policy
* Security content constraints (SCC) policy

When the `remediationAction` for the configuration policy is set to `enforce`, the controller creates a replicate policy on the target managed clusters.

[#configuration-policy-controller-yaml-structure]
== Configuration policy controller YAML structure

[source,yaml]
----
Name:         configuration-policy-example
Namespace:
Labels:
APIVersion:   policy.open-cluster-management.io/v1
Kind:         ConfigPolicy
Metadata:
  Finalizers:
    finalizer.policy.open-cluster-management.io
Spec:
  Conditions:
    Ownership:
    NamespaceSelector:
      Exclude:
      Include:
    RemediationAction:
 Status:
   CompliancyDetails:
     Configuration-Policy-Example:
       Default:
       Kube - Public:
   Compliant:          Compliant
 Events:
----

[#configuration-policy-controller-yaml-table]
== Configuration policy controller YAML table

|===
| Field | Description 

| Name
| Required.
// Add explanation


| Namespace
| Required.
// Add explanation


| Labels
| Optional.
// Add description

| APIVersion
| Required.
Set the value to `policy.open-cluster-management.io/v1`.

| Kind
| Required.
Set the value to `Policy` to indicate the type of policy.

| Metadata
| Required.
// add description


| Metadata.Finalizers
| Required.
// add description

| Spec
| Required.
Specifications of which configuration policy to monitor and how to remediate them.

| Spec.Conditions
| Required.
// add description


| Spec.Ownership
| Required.
// Add description


| Spec.NamespaceSelector
| Required.
// add description
Parameter values for `Include` and `Exclude`.


| Spec.RemediationAction
| Required.

| Spec.Status
| Required.
Reports the status of the policy.

| Status.CompliancyDetails
| Required.

| Status.Events
| Required.
|===

[#configuration-policy-sample]
== Configuration policy sample

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigPolicy
metadata:
  name: policy-config
spec:
  namespaceSelector:
    include: ["default"]
    exclude: []
  remediationAction: inform
    severity: low
    object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Pod
        metadata:
          name: nginx-pod
        spec:
          containers:
          - image: nginx:1.7.9
            name: nginx
            ports:
           - containerPort: 80

----

// Still need to add doc to create a custom controller #1224

Learn about how policies are applied on your hub cluster.
See xref:../security/policy_sample_intro.adoc#policy-samples[Policy samples] for more details.
Learn how to create and customize policies, see xref:../security/create_policy.adoc#managing-security-policies[Managing security policies].

See xref:../security/policy_controllers.adoc#policy-controllers[Policy controllers] for more information about controllers.
