[#managing-role-binding-policies]
= Managing role-binding policies

Learn to create, apply, view, and update your role-binding policies.

[#creating-a-role-binding-policy]
== Creating a role binding policy

You can create a YAML file for your role binding policy from the command line interface (CLI) or from the console.
View the following sections to create a role binding policy:

[#creating-a-role-binding-policy-from-the-cli]
=== Creating a role binding policy from the CLI

Complete the following steps to create a role binding policy from the CLI:

. Create a YAML file for your role binding policy.
Run the following command:
+
----
kubectl create -f rolebindingpolicy.yaml
----

. Apply the policy by running the following command:
+
----
kubectl apply -f <rolebinding-policy-file-name>  --namespace=<namespace>
----

. Verify and list the policies by running the following command:
+
----
kubectl get rolebindingpolicy --namespace=<namespace>
----

Your role binding policy is created.

[#viewing-your-role-binding-policy-from-the-cli]
==== Viewing your role binding policy from the CLI

Complete the following steps to view your role binding policy from the CLI:

. View details for a specific role binding policy by running the following command:
+
----
kubectl get rolebindingpolicy <policy-name> -n <namespace> -o yaml
----

. View a description of your role binding policy by running the following command:
+
----
kubectl describe rolebindingpolicy <name> -n <namespace>
----

[#creating-a-role-binding-policy-from-the-console]
=== Creating a role binding policy from the console

As you create a role binding policy from the console, a YAML file is also created in the YAML editor.
Complete the following steps to create a role binding policy from the console:

. Log in to your cluster from the console.
. From the navigation menu, click *Governance and risk*.
. Click *Create policy*.
. Enter or select the appropriate values for the following fields:
 ** Name
 ** Specifications
 ** Cluster selector
 ** Remediation action
 ** Standards
 ** Categories
 ** Controls
 ** Disabled
. Click *Create*.

A role binding policy is created.

[#viewing-your-role-binding-policy-from-the-console]
==== Viewing your role binding policy from the console

You can view any role binding policy and its status from the console.

. Log in to your cluster from the console.
. From the navigation menu, click *Governance and risk* to view a table list of your policies.
+
NOTE: You can filter the table list of your policies by selecting the _Policies_ tab or _Cluster violations_ tab.

. Select one of your policies to view more details.
. View the role binding policy violations by selecting the _Status_ tab.

[#updating-role-binding-policies]
== Updating role binding policies

Learn to update role binding policies by viewing the following section.

[#disabling-role-binding-policies]
=== Disabling role binding policies

Complete the following steps to disable your role binding policy:

. Log in to your {product-title} console.
. From the navigation menu, click *Govern risk* to view a table list of your policies.
. Disable your policy by clicking the *Actions* icon > *Disable*.
The _Disable Policy_ dialog box appears.
. Click *Disable policy*.

Your policy is disabled.

[#deleting-a-role-binding-policy]
=== Deleting a role binding policy

Delete the role binding policy from the CLI or the console.

* Delete a role binding policy from the CLI:
 .. Delete a role binding policy by running the following command:
+
----
kubectl delete policy <rolebinding-policy-name> -n <namespace>
----
+
After your policy is deleted, it is removed from your target cluster or clusters.

 .. Verify that your policy is removed by running the following command:
+
----
kubectl get policy <rolebinding-policy-name> -n <namespace>
----
* Delete a role binding policy from the console:
 .. From the navigation menu, click *Govern risk* to view a table list of your policies.
 .. Click the *Actions* icon for the policy you want to delete in the policy violation table.
 .. Click *Remove*.
 .. From the _Remove policy_ dialog box, click *Remove policy*.

Your role binding policy is deleted.

View a sample of a role binding policy, see _Role binding policy sample_ on the xref:../security/rolebinding_policy.adoc#role-binding-policy-sample[Role binding policy] page.
See xref:../security/config_policy_ctrl.adoc#kubernetes-configuration-policy-controller[Kubernetes configuration policy controller] to learn about other configuration policies.
See xref:../security/create_policy.adoc#managing-security-policies[Managing security policies] to manage other policies.
