[#gatekeeper-policy-integration]
= Gatekeeper policy integration

Learn to create, apply, view, and update your gatekeeper policies.

*Prerequisite*: You must install Gatekeeper. For more information see https://github.com/open-policy-agent/gatekeeper[`open-policy-agent/gatekeeper`] repository.

[#creating-a-gatekeeper-policy]
== Creating a gatekeeper policy

You can create a YAML file for your gatekeeper policy from the command line interface (CLI) or from the console. Use the {product-title} configuration policy to propagate the gatekeeper policy from the hub cluster to the managed cluster.
View the following sections to create a gatekeeper policy for the admission and auditing scenarios:

[#creating-a-gatekeeper-policy-for-admission]
=== Creating a gatekeeper policy for admission

Use the {produtc-title-short} configuration policy to look for events that are generated by the gatekeeper admission webhook. 

*Note:* Gatekeeper must be deployed with `emit-admission-events` set to `true`.

. Create a YAML file for your gatekeeper policy.
Run the following command:
+
----
kubectl create -f policy-gatekeeper.yaml
----
+
Your gatekeeper policy might resemble the following policy:



. Deploy Gatekeeper with the following command:
  
  ----
  
  ----


. Create a gatekeeper policy for admission. 
// do we want to mention updating the templates that are included with Gatekeeper? 

// Similiar to the Gatekeeper instructions? the speak about each template and its properties

// am i on the right path with this doc? Are users able to create custom gatekeeper policies or are they only able to integrate the controller? 
