[#managing-iam-policies]
= Managing IAM policies

Apply an IAM policy to check the number of cluster administrators that you allow in your managed cluster.
Learn to create, apply, view, and update your IAM policies in the following sections.

[#creating-an-iam-policy]
== Creating an IAM policy

You can create a YAML file for your IAM policy from the command line interface (CLI) or from the console.

[#creating-an-iam-policy-from-the-cli]
=== Creating an IAM policy from the CLI

Complete the following steps to create an IAM policy from the CLI:

. Create a YAML file with the IAM policy definition.
Run the following command:
+
----
kubectl create -f iam-policy-1.yaml
----
+
Your IAM policy might resemble the following YAML file:
+
[source,yaml]
----
apiVersion: iam.policies.ibm.com/v1alpha1
kind: IamPolicy
metadata:
  name: iam-grc-policy
  label:
    category: "System-Integrity"
spec:
  namespaceSelector:
    include: ["default","kube-*"]
    exclude: ["kube-system"]
  remediationAction: inform
  disabled: false
  maxClusterRoleBindingUsers: 5
----

. Apply the policy by running the following command:
+
----
kubectl apply -f <iam-policy-file-name>  --namespace=<mcm_namespace>
----

. Verify and list the policy by running the following command:
+
----
kubectl get <iam-policy-file-name> --namespace=<mcm_namespace>
----

Your IAM policy is created.

[#viewing-your-iam-policy-from-the-cli]
==== Viewing your IAM policy from the CLI

Complete the following steps to view your IAM policy:

. View details for specific IAM policy by running the following command:
+
----
kubectl get iampolicy <policy-name> -n <namespace> -o yaml
----

. View a description of your IAM policy by running the following command:
+
----
kubectl describe iampolicy <name> -n <namespace>
----

[#creating-an-iam-policy-from-the-console]
=== Creating an IAM policy from the console

As you create your IAM policy from the console, a YAML file is also created in the YAML editor.
Complete the following steps to create an IAM policy from the console:

. Log in to your cluster from the console.
. From the navigation menu, click *Govern risk*.
. Click *Create policy*.
. Enter or select the appropriate values for the following fields:
 ** Name
 ** Specifications
 ** Cluster selector
 ** Remediation action
 ** Standards
 ** Categories
 ** Controls
 ** Disabled
. Click *Create*.

An IAM policy is created.

[#viewing-your-iam-policy-from-the-console]
==== Viewing your IAM policy from the console

You can view any IAM policy and its status from the console.

. Log in to your cluster from the console.
. From the navigation menu, click *Govern risk* to view a table list of your policies.
+
NOTE: You can filter the table list of your policies by selecting the _All policies_ tab or _Cluster violations_ tab.

. Select one of your policies to view more details.
. View the IAM policy violations by selecting the _Violations_ tab.

[#updating-iam-policies]
== Updating IAM policies

Learn to update IAM policies by viewing the following section.

[#disabling-iam-policies]
=== Disabling IAM policies

Complete the following steps to disable your IAM policy:

. Log in to your Red Hat Advanced Cluster Management for Kubernetes console.
. From the navigation menu, click *Govern risk* to view a table list of your policies.
. Disable your policy by clicking the *Options* icon > *Disable*.
The _Disable Policy_ dialog box appears.
. Click *Disable policy*.

Your policy is disabled.

[#deleting-an-iam-policy]
=== Deleting an IAM policy

Delete a configuration policy from the CLI or the console.

* Delete an IAM policy from the CLI:
 .. Delete an IAM policy by running the following command:

+
----
  kubectl delete policy <iam-policy-name> -n <mcm namespace>
----
+
After your policy is deleted, it is removed from your target cluster or clusters.
 .. Verify that your policy is removed by running the following command:

+
----
  kubectl get policy <iam-policy-name> -n <mcm namespace>
----
* Delete an IAM policy from the console:
 .. From the navigation menu, click *Govern risk* to view a table list of your policies.
 .. Click the *Options* icon for the policy you want to delete in the policy violation table.
 .. Click *Remove*.
 .. From the _Remove policy_ dialog box, click *Remove policy*.

Your policy is deleted.

View the _IAM policy sample_ from the xref:iam-policy-controller[IAM policy controller] page.
See xref:manage-security-policies[Manage security policies] for more topics.
