[#gatekeeper-policy-operator-integration]
= Integrating gatekeeper operator policy

Use the gatekeeper operator policy to install the gatekeeper operator and gatekeeper on a managed cluster. You can create and configure a {product-title-short} gatekeeper operator policy to monitor customer resources (CR) that are created in the same namespace it is deployed.

*Required access*: Cluster administrator

+
[source,yaml]
----
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  # Add fields here
  image:
    image: docker.io/openpolicyagent/gatekeeper:v3.2.2
    imagePullPolicy: Always
  audit:
    replicas: 1
    logLevel: DEBUG
    auditInterval: 10s
    constraintViolationLimit: 55
    auditFromCache: Enabled
    auditChunkSize: 66
    emitAuditEvents: Enabled
    resources:
      limits:
        cpu: 500m
        memory: 150Mi
      requests:
        cpu: 500m
        memory: 130Mi
  validatingWebhook: Enabled
  webhook:
    replicas: 2
    logLevel: ERROR
    emitAdmissionEvents: Enabled
    failurePolicy: Fail
    resources:
      limits:
        cpu: 480m
        memory: 140Mi
      requests:
        cpu: 400m
        memory: 120Mi
  nodeSelector:
    region: "EMEA"
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              auditKey: "auditValue"
          topologyKey: topology.kubernetes.io/zone
  tolerations:
    - key: "Example"
      operator: "Exists"
      effect: "NoSchedule"
  podAnnotations:
    some-annotation: "this is a test"
    other-annotation: "another test"
----

[#gatekeeper-operator-policy]
== Installing gatekeeper using a gatekeeper operator policy

Use the governance framework to install the gatekeeper operator. Gatekeeper operator is available in the OpenShift Container Platform catalog. See _Adding Operators to a cluster_ in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[OpenShift Container Platform documentation] for more information.

Use the configuration policy controller install the gatekeeper operator policy. During the install, the operator group and subscription pull the gatekeeper operator to install it in your managed cluster. Then, the gatekeeper operator creates a gatekeeper CR to configure gatekeeper. 

Gatekeeper operator policy is monitored by the {product-title-short} configuration policy controller, where `enforce` remediation action is supported. Gatekeeper operator policies are created automatically by the controller when set to `enforce`.


[#creating-a-gatekeeper-policy]
=== Creating a gatekeeper policy

Complete the following steps to install the gatekeeper operator policy from the console:

. Log in to your cluster.
. From the navigation menu, click *Govern risk*.
. Create a policy by selecting *Create policy*.
. As you complete the form, select *GatekeeperOperator* from the _Specifications_ field. The parameter values for your policy are automatically populated and the policy is set to enforce to install Gatekeeper. See link:https://github.com/open-cluster-management/policy-collection/blob/master/community/CM-Configuration-Management/policy-gatekeeper-sample.yaml#L21-L65[policy-gatekeeper.yaml] to view an the sample.
+
*Note:* Consider that default values can be generated by the operator. See link:https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md[Gatekeeper Helm Chart] for an explanation of the optional parameters that can be used for the gatekeeper operator policy.  

For more information about integrating third-party policies with the product, see xref:../security/third_party_policy.adoc#integrate-third-party-policies[Integrate third-party policies]. 

