[#managing-configuration-policies]
= Managing configuration policies

Learn to create, apply, view, and update your configuration policies.

[#creating-a-configuration-policy]
== Creating a configuration policy

You can create a YAML file for your configuration policy from the command line interface (CLI) or from the console.
View the following sections to create a configuration policy:

[#creating-a-configuration-policy-from-the-cli]
=== Creating a configuration policy from the CLI

Complete the following steps to create a configuration policy from the (CLI):

. Create a YAML file for your configuration policy.
Run the following command:
+
----
kubectl create -f configpolicy-1.yaml
----
+
Your configuration policy might resemble the following policy:
+
[source,yaml]
----
  apiVersion: policy.open-cluster-management.io/v1
  kind: Policy
  metadata:
    name: policy-1
    namespace: kube-system
  spec:
    namespaces:
      include: ["default", "kube-*"]
      exclude: ["kube-system"]
    remediationAction: inform
    disabled: false
    complianceType: musthave
    object-templates:
   ...
----

. Apply the policy by running the following command:
+
----
kubectl apply -f <policy-file-name>  --namespace=<namespace>
----

. Verify and list the policies by running the following command:
+
----
kubectl get policy --namespace=<namespace>
----

Your configuration policy is created.

[#viewing-your-configuration-policy-from-the-cli]
==== Viewing your configuration policy from the CLI

Complete the following steps to view your configuration policy from the CLI:

. View details for a specific configuration policy by running the following command:
+
----
kubectl get policy <policy-name> -n <namespace> -o yaml
----

. View a description of your configuration policy by running the following command:
+
----
kubectl describe policy <name> -n <namespace>
----

[#creating-a-configuration-policy-from-the-console]
=== Creating a configuration policy from the console

As you create a configuration policy from the console, a YAML file is also created in the YAML editor.
Complete the following steps to create a configuration policy from the console:

. Log in to your cluster from the console.
. From the navigation menu, click *Governance and risk*.
. Click *Create policy*.
. Enter or select the appropriate values for the following fields:
 ** Name
 ** Namespace
 ** Specifications
 ** Cluster selector
 ** Remediation action
 ** Standards
 ** Categories
 ** Controls
 ** Disabled
. Click *Create*.

[#viewing-your-configuration-policy-from-the-console]
==== Viewing your configuration policy from the console

You can view any configuration policy and its status from the console.

. Log in to your cluster from the console.
. From the navigation menu, click *Govern risk* to view a table list of your policies.
+
NOTE: You can filter the table list of your policies by selecting the _All policies_ tab or _Cluster violations_ tab.

. Select one of your policies.
. View the policy violations by selecting the _Violations_ tab.

[#updating-configuration-policies]
== Updating configuration policies

Learn to update configuration policies by viewing the following section.

[#disabling-configuration-policies]
=== Disabling configuration policies

Complete the following steps to disable your configuration policy:

. Log in to your Red Hat Advanced Cluster Management for Kubernetes console.
. From the navigation menu, click *Govern risk* to view a table list of your policies.
. Disable your policy by clicking the *Options* icon > *Disable*.
The _Disable Policy_ dialog box appears.
. Click *Disable policy*.

Your policy is disabled.

[#deleting-a-configuration-policy]
== Deleting a configuration policy

Delete a configuration policy from the CLI or the console.

* Delete a configuration policy from the CLI:
 .. Delete a configuration policy by running the following command:

+
----
  kubectl delete policy <policy-name> -n <mcm namespace>
----
+
After your policy is deleted, it is removed from your target cluster or clusters.
 .. Verify that your policy is removed by running the following command:

+
----
  kubectl get policy <policy-name> -n <mcm namespace>
----
* Delete a configuration policy from the console:
 .. From the navigation menu, click *Govern risk* to view a table list of your policies.
 .. Click the *Options* icon for the policy you want to delete in the policy violation table.
 .. Click *Remove*.
 .. From the _Remove policy_ dialog box, click *Remove policy*.

Your policy is deleted.

View configuration policy samples, see xref:policy_sample_intro.adoc[Policy samples].
See xref:create_policy.adoc[Managing security policies] to manage other policies.
