[#managing-role-policies]
= Managing role policies

Kubernetes configuration policy controller monitors the status of role policies.
Apply a role policy to set rules and permissions for specific roles in your cluster.
Learn to create, apply, view, and update your role policy in the following sections.

[#creating-a-role-policy]
== Creating a role policy

You can create a YAML file for your role policy from the command line interface (CLI) or from the console.
View the following sections to create a role policy:

[#creating-a-role-policy-from-the-cli]
=== Creating a role policy from the CLI

Complete the following steps to create a role from the CLI:

. Create a YAML file for your role policy by running the following command:
+
----
kubectl create -f rolepolicy-1.yaml
----

. Apply the policy by running the following command:
+
----
kubectl apply -f <role-policy-file-name>  --namespace=<namespace>
----

. List and verify the policies by running the following command:
+
----
kubectl get rolepolicy --namespace=<namespace>
----

Your role policy is created from the CLI.

[#viewing-your-role-policy-from-the-cli]
==== Viewing your role policy from the CLI

Complete the following steps to view your role policy from the CLI:

. View details for a specific role policy by running the following command:
+
----
kubectl get rolepolicy <policy-name> -n <namespace> -o yaml
----

. View a description of your role policy by running the following command:
+
----
kubectl describe rolepolicy <name> -n <namespace>
----

[#creating-a-role-policy-from-the-console]
=== Creating a role policy from the console

As you create a role policy from the console, a YAML file is also created in the YAML editor.
Complete the following steps to create the role policy from the console:

. Log in to your {product-title} console.
. From the navigation menu, click *Govern risk*.
. Click *Create policy*.
. Select *Role* from the _Specifications_ field.
Parameter values are automatically set.
You can edit your values.
. Click *Create*.

[#viewing-your-role-policy-from-the-console]
==== Viewing your role policy from the console

You can view any role policy and its status from the console.

. Log in to your cluster from the console.
. From the navigation menu, click *Govern risk* to view a table list of your policies.
+
NOTE: You can filter the table list of your policies by selecting the _Policies_ tab or _Cluster violations_ tab.

. Select one of your policies to view more details.
. View the policy violations by selecting the _Status_ tab.

[#updating-role-policies]
== Updating role policies

Learn to update role policies by viewing the following section.

[#disabling-role-policies]
=== Disabling role policies

Complete the following steps to disable your role policy:

. Log in to your {product-title} console.
. From the navigation menu, click *Govern risk* to view a table list of your policies.
. Disable your policy by clicking the *Options* icon > *Disable*.
The _Disable Policy_ dialog box appears.
. Click *Disable policy*.

Your policy is disabled.

[#deleting-a-role-policy]
=== Deleting a role policy

Delete the role policy from the CLI or the console.

* Delete a role policy from the CLI:
 .. Delete a role policy by running the following command:
// verify command `namespace`
+
----
 kubectl delete policy <podsecurity-policy-name> -n <mcm namespace>
----
+
After your policy is deleted, it is removed from your target cluster or clusters.

 .. Verify that your policy is removed by running the following command:
+
----
 kubectl get policy <podsecurity-policy-name> -n <mcm namespace>
----
* Delete a role policy from the console:
 .. From the navigation menu, click *Govern risk* to view a table list of your policies.
 .. Click the *Options* icon for the policy you want to delete in the policy violation table.
 .. Click *Remove*.
 .. From the _Remove policy_ dialog box, click *Remove policy*.

Your role policy is deleted.

View a sample of a role policy, see _Role policy sample_ on the xref:../security/role_policy.adoc#role-policy-sample[Role policy] page.
See xref:../security/config_policy_ctrl.adoc#kubernetes-configuration-policy-controller[Kubernetes configuration policy controller] to learn about other configuration policies.
See xref:../security/create_policy.adoc#managing-security-policies[Managing security policies] to manage other policies.
