[#gatekeeper-policy-integration]
= Install Gatekeeper using the gatekeeper operator policy

Use the Gatekeeper operator to install the community version of Gatekeeper on a managed cluster. you can create and configure a Gatekeeper operator policy to monitor customer resources (CR) that are created in the same namespace it is deployed.

*Required access*: Cluster administrator

* <<gatekeeper-operator-policy,Creating a gatekeeper operator policy>>
* <<creating-a-gatekeeper-policy,Creating a gatekeeper policy>>
* <<creating-a-gatekeeper-policy-for-admission,Creating a gatekeeper policy for admission>>
* <<creating-a-gatekeeper-policy-for-audit,Creating a gatekeeper policy for audit>>

[#gatekeeper-operator-policy]
=== Creating a gatekeeper operator

Use the governance framework to install the Gatekeeper operator (`policy-gatekeeperoperator`). Gatekeeper operator is available in the OpenShift Container Platform catalog. See _Adding Operators to a cluster_ in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[OpenShift Container Platform documentation].

During the install, the operator group and subscription pull the Gatekeeper operator to install it on to your hub cluster. Also consider that default values can be generated by the operator. 

There are optional parameters that can be used in your gatekeeper policy. See the default YAML file for Gatekeeper and review the parameter descriptions: 

----
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  # Add fields here
  image:
    image: docker.io/openpolicyagent/gatekeeper:v3.2.2
    imagePullPolicy: Always
  audit:
    replicas: 1
    logLevel: DEBUG
    auditInterval: 10s
    constraintViolationLimit: 55
    auditFromCache: Enabled
    auditChunkSize: 66
    emitAuditEvents: Enabled
    resources:
      limits:
        cpu: 500m
        memory: 150Mi
      requests:
        cpu: 500m
        memory: 130Mi
  validatingWebhook: Enabled
  webhook:
    replicas: 2
    logLevel: ERROR
    emitAdmissionEvents: Enabled
    failurePolicy: Fail
    resources:
      limits:
        cpu: 480m
        memory: 140Mi
      requests:
        cpu: 400m
        memory: 120Mi
  nodeSelector:
    region: "EMEA"
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              auditKey: "auditValue"
          topologyKey: topology.kubernetes.io/zone
  tolerations:
    - key: "Example"
      operator: "Exists"
      effect: "NoSchedule"
  podAnnotations:
    some-annotation: "this is a test"
    other-annotation: "another test"
----

.Gatekeeper parameter descriptions
|===
| Parameter | Description | Default value

| auditInterval
| The frequency when audit is run.
| 60

| constraintViolationsLimit
| The maximum number of audit violations reported on a constraint.
| 20

| auditFromCache
| Collects the resources to audit from the Open Policy Agent (OPA) cache.
| false

| auditChunkSize
| Chunk size for listing cluster resources for audit (alpha feature)
| 0

| disableValidatingWebhook
| Disables the validating webhook
| false

| emitAdmissionEvents
| Emit K8s events in gatekeeper namespace for admission violations (alpha feature)
| false

| emitAuditEvents
| Emit K8s events in gatekeeper namespace for audit violations (alpha feature)
| false

| logLevel
| Minimum log level.
| INFO

| image.pullPolicy
| The image pull policy.
| IfNotPresent

| image.repository
| The image repository.
| openpolicyagent/gatekeeper

| image.release
| The image release tag to use
| Current release version: v3.3.0-beta.2

| image.pullSecrets
| Specify an array of imagePullSecrets.
| []

| resources
| The resource request or limits for the container image. 
| limits: 1 CPU, 512Mi, requests: 100mCPU, 256Mi

| nodeSelector
| The node selector to use for pod scheduling.
| kubernetes.io/os: linux

| affinity
| The node affinity to use for pod scheduling.
| {}

| tolerations
| The tolerations to use for pod scheduling.
| []

| replicas
| The number of Gatekeeper replicas to deploy for the webhook.
| 1

| podAnnotations
| The annotations to add to the Gatekeeper pods. 
| container.seccomp.security.alpha.kubernetes.io/manager: runtime/default

| secretAnnotations
| The annotations to add to the Gatekeeper secrets.
| {}

| customResourceDefinitions.create
| Indicates whether the release should install CRDs. Regardless of this value, Helm v3+ installs the CRDs if those are not present already. Use `--skip-crds` with helm install if you want to skip CRD creation.
| true
|===


Gatekeeper operator policy is monitored by the Red Hat Advanced Cluster Management configuration policy controller, where `enforce` remediation action is supported. Gatekeeper operator policies are created automatically by the controller when set to `enforce`.

Complete the following steps to install the gatekeeper operator policy from the console:

. Log in to your cluster.
. From the navigation menu, click *Govern risk*.
. Create a policy by selecting *Create policy*.
. As you complete the form, select *GatekeeperOperator* from the _Specifications_ field. The parameter values for your policy are automatically populated and the policy is set to enforce to install Gatekeeper.


[#creating-a-gatekeeper-policy]
== Creating a gatekeeper policy

You can create a YAML file for your gatekeeper policy from the command line interface (CLI). Use the {product-title} configuration policy to propagate the gatekeeper policy from the hub cluster to the managed cluster. View the following sections to create a gatekeeper policy for the admission and auditing scenarios:

[#creating-a-gatekeeper-policy-for-admission]
=== Creating a gatekeeper policy for admission

Use the {product-title-short} configuration policy to create a gatekeeper policy that looks for events that are generated by the gatekeeper admission webhook. 

*Note:* Gatekeeper must be deployed with `emit-admission-events` set to `true`.

Create a YAML file for your gatekeeper policy. Run the following command:

----
kubectl create -f policy-gatekeeper-admission.yaml
----

Your gatekeeper policy might resemble the following policy:

----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gatekeeper
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: 
    policy.open-cluster-management.io/categories: 
    policy.open-cluster-management.io/controls: 
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gatekeeper-k8srequiredlabels
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: templates.gatekeeper.sh/v1beta1
                kind: ConstraintTemplate
                metadata:
                  name: k8srequiredlabels
                spec:
                  crd:
                    spec:
                      names:
                        kind: K8sRequiredLabels
                      validation:
                        # Schema for the `parameters` field
                        openAPIV3Schema:
                          properties:
                            labels:
                              type: array
                              items: string
                  targets:
                    - target: admission.k8s.gatekeeper.sh
                      rego: |
                        package k8srequiredlabels
                        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
                          provided := {label | input.review.object.metadata.labels[label]}
                          required := {label | label := input.parameters.labels[_]}
                          missing := required - provided
                          count(missing) > 0
                          msg := sprintf("you must provide labels: %v", [missing])
                        }
            - complianceType: musthave
              objectDefinition:
                apiVersion: constraints.gatekeeper.sh/v1beta1
                kind: K8sRequiredLabels
                metadata:
                  name: ns-must-have-gk
                spec:
                  match:
                    kinds:
                      - apiGroups: [""]
                        kinds: ["Namespace"]
                  parameters:
                    labels: ["gatekeeper"]
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gatekeeper-admission
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: low
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Event
                metadata:
                  namespace: gatekeeper-system
                  annotations:
                    constraint_action: deny
                    constraint_kind: K8sRequiredLabels
                    constraint_name: ns-must-have-gk
                    event_type: violation
             
----        

[#creating-a-gatekeeper-policy-for-audit]
=== Creating a gatekeeper policy for audit

Use the product configuration policy to create a gatekeeper policy that periodically checks and evaluates existing resources against the gatekeeper policies. {product-title-short} configuration policy checks for the violations in the status field of the gatekeeper constraint.

Create a YAML file for your gatekeeper policy. Run the following command:

----
kubectl create -f policy-gatekeeper-audit.yaml
----

Your gatekeeper policy might resemble the following policy:

----
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gatekeeper
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: 
    policy.open-cluster-management.io/categories: 
    policy.open-cluster-management.io/controls: 
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gatekeeper-audit
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: constraints.gatekeeper.sh/v1beta1
                kind: K8sRequiredLabels
                metadata:
                  name: ns-must-have-gk
                status:
                  totalViolations: 0
                  violations: []
----


For more information about integrating third-party policies with the product, see xref:../security/third_party_policy.adoc#integrate-third-party-policies[Integrate third-party policies]. 

