[#creating-compliance-operator-policies]
= Creating compliance operator policies

Apply a compliance operator policy to install the {ocp} compliance operator. Learn to create, update, apply, view, and your compliance operator policy in the following sections.

[#creating-a-compliance-operator-policy-from-the-console]
== Creating a compliance operator policy from the console

As you create a compliance operator policy from the console, a YAML file is also created in the YAML editor. Complete the following steps to create a compliance operator policy from the console:

. Log in to your hub cluster.

. From the navigation menu, select *Govern risk*. 

. Click *Create policy*. As you complete the YAML form, select *ComplianceOperator* from the _Specifications_ field.
+ 
The following resources are created: compliance operator namespace (`openshift-compliance`), an operator group (`compliance-operator`), and a subscription (`comp-operator-subscription`).
+
*Note:* Enforce is supported. When you set the remediation action to `enforce` the policy installs the compliance operator.

A compliance operator policy is created.