[#managing-iam-policies]
= Managing IAM policies

Apply an IAM policy to check the number of cluster administrators that you allow in your managed cluster.
Learn to create, apply, view, and update your IAM policies in the following sections.

[#creating-an-iam-policy]
== Creating an IAM policy

You can create a YAML file for your IAM policy from the command line interface (CLI) or from the console.

[#creating-an-iam-policy-from-the-cli]
=== Creating an IAM policy from the CLI

Complete the following steps to create an IAM policy from the CLI:

. Create a YAML file with the IAM policy definition.
Run the following command:
+
----
kubectl create -f iam-policy-1.yaml
----
+
Your IAM policy might resemble the following YAML file:
+
[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: IamPolicy
metadata:
  name: iam-grc-policy
  label:
    category: "System-Integrity"
spec:
  namespaceSelector:
    include: ["default","kube-*"]
    exclude: ["kube-system"]
  remediationAction: inform
  disabled: false
  maxClusterRoleBindingUsers: 5
----

. Apply the policy by running the following command:
+
----
kubectl apply -f <iam-policy-file-name>  --namespace=<mcm_namespace>
----

. Verify and list the policy by running the following command:
+
----
kubectl get <iam-policy-file-name> --namespace=<mcm_namespace>
----

Your IAM policy is created.

[#viewing-your-iam-policy-from-the-cli]
==== Viewing your IAM policy from the CLI

Complete the following steps to view your IAM policy:

. View details for specific IAM policy by running the following command:
+
----
kubectl get iampolicy <policy-name> -n <namespace> -o yaml
----

. View a description of your IAM policy by running the following command:
+
----
kubectl describe iampolicy <name> -n <namespace>
----

[#creating-an-iam-policy-from-the-console]
=== Creating an IAM policy from the console

As you create your IAM policy from the console, a YAML file is also created in the YAML editor.
Complete the following steps to create an IAM policy from the console:

. Log in to your cluster from the console.
. From the navigation menu, click *Govern risk*.
. Click *Create policy*.
. From the _Create policy_ page, complete the following sections of the policy creation form:
.. Define your policy. Fill in the following parameter fields to complete the form: _Name_, _Namespace_, _Template_, _Enforce if supported_, and _Disable policy_.
.. Select a cluster selector to apply your policy. Click the drop-down menu to view a list of clusters to choose from. You can apply your policy to multiple clusters.
.. Customize the _Summary_ view from the dashboard by mapping your industry standards. Enter a value for the following parametes: _Standards_, _Categories_, _Controls_.
+
*Note*: You can copy and paste an existing policy in to the _Policy YAML_.
The values for the parameter fields are automatically entered when you paste your existing policy.
You can also search the contents in your policy YAML file with the search feature.
. Click *Create*.

An IAM policy is created.
//Figure out the value the useer would select to create specific policy ^
[#viewing-your-iam-policy-from-the-console]
==== Viewing your IAM policy from the console

You can view any IAM policy and its status from the console.

. Log in to your cluster from the console.
. From the navigation menu, click *Govern risk* to view a table list of your policies.
+
NOTE: You can filter the table list of your policies by selecting the _All policies_ tab or _Cluster violations_ tab.

. Select one of your policies to view more details.
. View the IAM policy violations by selecting the _Violations_ tab.

[#updating-iam-policies]
== Updating IAM policies

Learn to update IAM policies by viewing the following section.

[#disabling-iam-policies]
=== Disabling IAM policies

Complete the following steps to disable your IAM policy:

. Log in to your {product-title} console.
. From the navigation menu, click *Govern risk* to view a table list of your policies.
. Disable your policy by clicking the *Options* icon > *Disable*.
The _Disable Policy_ dialog box appears.
. Click *Disable policy*.

Your policy is disabled.

[#deleting-an-iam-policy]
=== Deleting an IAM policy

Delete a configuration policy from the CLI or the console.

* Delete an IAM policy from the CLI:
 .. Delete an IAM policy by running the following command:

+
----
  kubectl delete policy <iam-policy-name> -n <mcm namespace>
----
+
After your policy is deleted, it is removed from your target cluster or clusters.
 .. Verify that your policy is removed by running the following command:

+
----
  kubectl get policy <iam-policy-name> -n <mcm namespace>
----
* Delete an IAM policy from the console:
 .. From the navigation menu, click *Govern risk* to view a table list of your policies.
 .. Click the *Options* icon for the policy you want to delete in the policy violation table.
 .. Click *Remove*.
 .. From the _Remove policy_ dialog box, click *Remove policy*.

Your policy is deleted.

View the _IAM policy sample_ from the xref:../security/iam_policy_ctrl.adoc#iam-policy-controller[IAM policy controller] page.
See xref:../security/create_policy.adoc#managing-security-policies[Managing security policies] for more topics.
