[#credentials]
= Credentials

You can rotate your credentials for your {product-title} clusters.

[#rotating-credentials]
== Provider credentials

Connection secrets for a cloud provider can be rotated. See the following list of provider credentials:

[#aws-rotate]
=== Amazon Web Services

  - `aws_access_key_id`: Your provisioned cluster access key.
  - `aws_secret_access_key`: Your provisioned secret access key.

. View the resources in the namespace that has the same name as the cluster with the expired credential. 				
. Find the secret name `<cluster_name>-<cloud_provider>-creds`. For example: `my_cluster-aws-creds1`.				
. Edit the secret to replace the existing value with the updated value.	
		
//[#microsoft-azure]
//=== Microsoft Azure 
// clientId
// clientSecret
  
//[#vmware]
//=== VMware vSphere

//username
//password
//cacertificate
 
//[#gke-platform]
//=== Google Cloud Platform

//gcServiceAccountKey

[#rotating-agents]
== Agents

Agents are responsible for connections. See how you can rotate the following credentials:

 - `registration-agent`: Connects the registration agent to the hub cluster.
 - `work-agent`: Connects the work agent to the hub cluster.
 
+ 
To rotate credentials, delete the `hub-kubeconfig` secret to restart the registration pods.
 
 - `APIServer`: Connects agents and add-ons to the hub cluster.
 
+
. On the hub cluster, display the import command by entering the following command: 

+
----
oc get secret -n ${CLUSTER_NAME} ${CLUSTER_NAME}-import -ojsonpath='{.data.import\.yaml}' | base64 --decode  > import.yaml
----

+
. On the managed cluster, apply the `import.yaml` file. Run the following command: `oc apply -f import.yaml`.


