[#gatekeeper-policy]
= Gatekeeper policy

Gatekeeper is a validating webhook that enforces CustomResourceDefinition (CRD) based policies that are run with the Open Policy Agent (OPA). You can install gatekeeper on your cluster by using the gatekeeper operator policy. Gatekeeper policy can be used to evaluate Kubernetes resource compliance. You can leverage an OPA as the policy engine, and use Rego as the policy language.

The gatekeeper policy is created as a Kubernetes configuration policy. Gatekeeper policies include constraint templates (`ConstraintTemplates`), which are used to define specific constraints for your cluster. `ConstraintTemplates` informs which constraint template to enforce to the Gatekeeper. For more information, see the https://github.com/open-policy-agent/gatekeeper#gatekeeper[Gatekeeper].

Use constraint templates in your gatekeeper policy for the following scenarios:

* Admission scenario: Use the `policy-gatekeeper-admission` to check when a resource is created or updated to block new misconfigurations.
* Audit scenario: Use the `policy-gatekeeper-audit` to periodically check and evaluate existing resources against the gatekeeper policies that are enforced to detect exisiting miscongfigurations.

During the install, the operator group and subscription pull the Gatekeeper operator to install it on to your managed cluster. Then, the gatekeeper operator installs and configures Gatekeeper based on Gatekeeper CR. Also consider that default values can be generated by the operator. 

There are optional parameters that can be used in your gatekeeper policy. See the default YAML file for Gatekeeper and review the parameter descriptions: 

[source,yaml]
----
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  # Add fields here
  image:
    image: docker.io/openpolicyagent/gatekeeper:v3.2.2
    imagePullPolicy: Always
  audit:
    replicas: 1
    logLevel: DEBUG
    auditInterval: 10s
    constraintViolationLimit: 55
    auditFromCache: Enabled
    auditChunkSize: 66
    emitAuditEvents: Enabled
    resources:
      limits:
        cpu: 500m
        memory: 150Mi
      requests:
        cpu: 500m
        memory: 130Mi
  validatingWebhook: Enabled
  webhook:
    replicas: 2
    logLevel: ERROR
    emitAdmissionEvents: Enabled
    failurePolicy: Fail
    resources:
      limits:
        cpu: 480m
        memory: 140Mi
      requests:
        cpu: 400m
        memory: 120Mi
  nodeSelector:
    region: "EMEA"
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              auditKey: "auditValue"
          topologyKey: topology.kubernetes.io/zone
  tolerations:
    - key: "Example"
      operator: "Exists"
      effect: "NoSchedule"
  podAnnotations:
    some-annotation: "this is a test"
    other-annotation: "another test"
----

.Gatekeeper parameter descriptions
|===
| Parameter | Description | Default value

| auditInterval
| The frequency when audit is run.
| 60

| constraintViolationsLimit
| The maximum number of audit violations reported on a constraint.
| 20

| auditFromCache
| Collects the resources to audit from the Open Policy Agent (OPA) cache.
| false

| auditChunkSize
| Chunk size for listing cluster resources for audit (alpha feature)
| 0

| disableValidatingWebhook
| Disables the validating webhook
| false

| emitAdmissionEvents
| Emit K8s events in gatekeeper namespace for admission violations (alpha feature)
| false

| emitAuditEvents
| Emit K8s events in gatekeeper namespace for audit violations (alpha feature)
| false

| logLevel
| Minimum log level.
| INFO

| image.pullPolicy
| The image pull policy.
| IfNotPresent

| image.repository
| The image repository.
| openpolicyagent/gatekeeper

| image.release
| The image release tag to use
| Current release version: v3.3.0-beta.2

| image.pullSecrets
| Specify an array of imagePullSecrets.
| []

| resources
| The resource request or limits for the container image. 
| limits: 1 CPU, 512Mi, requests: 100mCPU, 256Mi

| nodeSelector
| The node selector to use for pod scheduling.
| kubernetes.io/os: linux

| affinity
| The node affinity to use for pod scheduling.
| {}

| tolerations
| The tolerations to use for pod scheduling.
| []

| replicas
| The number of Gatekeeper replicas to deploy for the webhook.
| 1

| podAnnotations
| The annotations to add to the Gatekeeper pods. 
| container.seccomp.security.alpha.kubernetes.io/manager: runtime/default

| secretAnnotations
| The annotations to add to the Gatekeeper secrets.
| {}

| customResourceDefinitions.create
| Indicates whether the release should install CRDs. Regardless of this value, Helm v3+ installs the CRDs if those are not present already. Use `--skip-crds` with helm install if you want to skip CRD creation.
| true
|===

For more information, see link:https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md[Gatekeeper Helm Chart].
Learn how to integrate Gatekeeper to create a gatekeeper policy, see xref:../security/create_gatekeeper.adoc#gatekeeper-policy-integration[Integrating Gatekeeper] for more details. Refer to xref:../security/grc_intro.adoc#governance-and-risk[Governance and risk] for more topics on the security framework.
