[#gatekeeper-policy]
= Gatekeeper policy

Gatekeeper is a validating webhook that enforces CustomResourceDefinition (CRD) based policies that are run with the Open Policy Agent (OPA). You can install Gatekeeper to integrate a gatekeeper policy with {product-title}. Gatekeeper policy can be used to evaluate Kubernetes resource compliance. You can leverage an OPA as the policy engine, and use Rego as the policy language.

The gatekeeper policy is created as a Kubernetes configuration policy. Gatekeeper policies include constraint templates (`ConstraintTemplates`), which are used to define specific constraints for your cluster. `ConstraintTemplates` informs which constraint template to enforce to the Gatekeeper. For more information, see the https://github.com/open-policy-agent/gatekeeper#gatekeeper[Gatekeeper].

Use constraint templates in your gatekeeper policy for the following scenarios:

* Admission scenario: Use the `policy-gatekeeper-admission` to check when a resource is created or updated to block new misconfigurations.
* Audit scenario: Use the `policy-gatekeeper-audit` to periodically check and evaluate existing resources against the gatekeeper policies that are enforced to detect exisiting miscongfigurations.

Learn how to integrate Gatekeeper to create a gatekeeper policy, see xref:../security/create_gatekeeper.adoc#gatekeeper-policy-integration[Integrating Gatekeeper] for more details. Refer to xref:../security/grc_intro.adoc#governance-and-risk[Governance and risk] for more topics on the security framework.
