[#iam-policy-controller]
= IAM policy controller

Identity and Access Management (IAM) policy controller can be used to receive notifications about IAM policies that are non-compliant.
The compliance check is based on the parameters that you configure in the IAM policy.

The IAM policy controller checks for compliance of the number of cluster administrators that you allow in your cluster.
IAM policy controller communicates with the local Kubernetes API server.
For more information, see link:https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions].

The IAM policy controller runs on your managed cluster.

[#iam-policy-yaml-structure]
== IAM policy YAML structure

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: IamPolicy
metadata:
  name: iam-grc-policy
  label:
    category: "System-Integrity"
spec:
  namespaceSelector:
    include:
    exclude:
  remediationAction:
  maxClusterRoleBindingUsers:
----

[#iam-policy-yaml-table]
== IAM policy YAMl table

|===
| Field | Description

| apiVersion
| Required.
Set the value to `policy.open-cluster-management.io/v1`.

| kind
| Required.
Set the value to `Policy` to indicate the type of policy.

| metadata.name
| Required.
The name for identifying the policy resource.

| metadata.label
| Optional.

| spec
| Required.
Add configuration details for your policy.

| spec.namespaceSelector
| Required.
The namespaces within the hub cluster that the policy is applied to.
Enter at least one namespace for the `include` parameter, which are the namespaces you want to apply to the policy to.
The `exclude` parameter specifies the namespaces you explicitly do not want to apply the policy to.
*Note*: A namespace that is specified in the object template of a policy controller overrides the namespace in the corresponding parent policy.

| spec.remediationAction
| Optional.
Specifies the remediation of your policy.
Enter  `inform`.

| spec.maxClusterRoleBindingUsers
| Required.
Maximum number of IAM rolebindings that are available before a policy is considered non-compliant.
|===

Learn how to manage an IAM policy, see link:create_iam_policy.adoc[Managing IAM policies] for more details.
Refer to link:policy_controllers.adoc[Policy controllers] for more topics.
