[#manage-security-policies]
= Manage security policies

Use the Governance and risk dashboard to create, view, and manage your security policies and policy violations. You can create YAML files for your policies from the CLI and console. 

From the _Policies_ page, you can customize your Summary view by filtering the violations by categories or standards, collapse the summary to see less information, and you can search for policies. You can also filter the violation table view by policies or cluster violations.

The table of policies list the following details of a policy: _Name_, _Namespace_, _Remediation_, _Cluster violation_, _Standards_, _Categories_, _Controls_, and _Last updated_. You can view which clusters a policy is applied to, edit a policy, disable a policy, or remove a policy by selecting the *Actions* icon.

When you select a policy in the table list, the following tabs of information are displayed from the console:

- _Overview_: Select the _Overview_ tab  view Details, Placement details, and a table list of Policy templates.

- _Status_: Select the _Status_ tab to view your violations. You can filter your violation view by _Templates_ or _Clusters_. 
.. When the table is filtered by _Templates_ the following information is provided in the tables: Cluster, Status, Message, Last report, and History. 
.. Select _Violation history_ for a specific policy to view a list of violation messages.

- _YAML_: Select the _YAML_ tab to view, and or edit your policy with the editor. Select the YAML toggle to view or hide the editor.


Review the following topics to learn more about creating and updating your security policies:

* xref:../security/create_policy.adoc#managing-security-policies[Managing security policies]
* xref:../security/create_config_pol.adoc#managing-configuration-policies[Managing configuration policies]
* xref:../security/create_image_vuln.adoc#managing-image-vulnerability-policies[Managing image vulnerability policies]
* xref:../security/create_memory_policy.adoc#managing-memory-usage-policies[Managing memory usage policies]
* xref:../security/create_ns_policy.adoc#managing-namespace-policies[Managing namespace policies]
* xref:../security/create_nginx_policy.adoc#managing-pod-nginx-policies[Managing pod nginx policies]
* xref:../security/create_psp_policy.adoc#managing-pod-security-policies[Managing pod security policies]
* xref:../security/create_role_policy.adoc#managing-role-policies[Managing role policies]
* xref:../security/create_rb_policy.adoc#managing-rolebinding-policies[Managing rolebinding policies]
* xref:../security/create_scc_policy.adoc#managing-security-context-constraints-policies[Managing Security Context Constraints policies]
* xref:../security/create_cert_pol.adoc#managing-certificate-policies[Managing certificate policies]
* xref:../security/create_iam_policy.adoc#creating-an-iam-policy[Managing IAM policies]
* xref:../security/create_etcd_pol.adoc#creating-an-encryption-policy[Managing ETCD encryption policies]
* xref:../security

Refer to xref:../security/grc_intro.adoc#governance-and-risk[Governance and risk] for more topics.
