[#pod-nginx-policy]
= Pod nginx policy

Kubernetes configuration policy controller monitors the status of you pod nginx policies.
Apply the pod policy to define the container rules for your pods.
A nginx pod must exist in your cluster.

[#pod-nginx-policy-yaml-structure]
== Pod nginx policy YAML structure

[source,yaml]
----
   apiVersion: policy.mcm.ibm.com/v1alpha1
   kind: Policy
   metadata:
     name: policy-pod
     namespace:
   spec:
     complianceType:
     remediationAction:
     namespaces:
       exclude:
       include:
     object-templates:
       - complianceType:
         objectDefinition:
           apiVersion:
           kind: Pod # nginx pod must exist
           metadata:
             name:
           spec:
             containers:
             - image:
               name:
               ports:
               - containerPort:
        ...
----

[#pod-nginx-policy-table]
== Pod nginx policy table

|===
| Field | Description |

| apiVersion
| Required.
Set the value to `policy.mcm.ibm.com/v1alpha1`.

| kind
| Required.
Set the value to `Policy` to indicate the type of policy.

| metadata.name
| Required.
The name for identifying the policy resource.

| metadata.namespaces
| Optional.

| spec.namespace
| Required. The namespaces within the hub cluster that the policy is applied to.
Enter parameter values for `include`, which are the namespaces you want to apply to the policy to.
The `exclude` parameter specifies the namespaces you explicitly do not want to apply the policy to.
*Note*: A namespace that is specified in the object template of a policy controller overrides the namespace in the corresponding parent policy.

| remediationAction
| Optional. Specifies the remediation of your policy.
The parameter values are `enforce` and `inform`.
*Important*: Some policies might not support the enforce feature.

| disabled
| Required. Set the value to `true` or `false`.
The `disabled` parameter provides the ability to enable and disable your policies.

| spec.complianceType
| Required. Set the value to `"musthave"`

| spec.object-template
| Optional. Used to list any other Kubernetes object that must be evaluated or applied to the managed clusters.

[#pod-nginx-policy-sample]
== Pod nginx policy sample

Your pod policy nginx policy might resemble the following YAML file:

[source,yaml]
----
   apiVersion: policy.mcm.ibm.com/v1alpha1
   kind: Policy
   metadata:
     name: policy-pod
     namespace: mcm
   spec:
     complianceType: musthave
     remediationAction: inform
     namespaces:
       exclude: ["kube-*"]
       include: ["default"]
     object-templates:
       - complianceType: musthave
         objectDefinition:
           apiVersion: v1
           kind: Pod # nginx pod must exist
           metadata:
             name: nginx-pod
           spec:
             containers:
             - image: nginx:1.7.9
               name: nginx
               ports:
               - containerPort: 80
        ...
----

Learn how to manage a pod nginx policy, see link:create_nginx_policy.md.adoc[Managing pod nginx policies] for more details.
View other configuration policies that are monitored by the configuration controller, see link:config_policy_ctrl.md.adoc[Kubernetes configuration policy controller].
See link:create_policy.md.adoc[Manage security policies] to manage other policies.
