[#policy-controllers]
= Policy controllers

Use the Red Hat Advanced Cluster Management for Kubernetes governance and risk policy framework to create custom policy controllers.
The policy controllers are Kubernetes CustomResourceDefinition (CRD) instance.
For more information about CRDs, see link:https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions].

Create and customize poolicy controllers and policies with the out of the box policy templates. Policy controllers monitor and report whether your cluster is compliant with policy. It can also enforce the policy to bring the cluster status to compliant. See xref:../create_policy_ctrl.adoc#creating-a-custom-policy-controller[Creating a custom policy controller] for more information.

**Important**: Some policy controllers might not support the enforce feature.
If the enforce feature is not supported by the controller, you must remediate it manually.
Only the configuration policy controller supports the `enforce` feature.

View the following topics to learn more about the following Red Hat Advanced Cluster Management for Kubernetes policy controllers:

* xref:../security/config_policy_ctrl.adoc#kubernetes-configuration-policy-controller[Kubernetes configuration policy controller]
* xref:../security/cert_policy_ctrl.adoc#certificate-policy-controller[Certificate policy controller]
* xref:../security/iam_policy_ctrl.adoc#iam-policy-controller[IAM policy controller]
* xref:../security/cis_policy_ctrl.adoc#cis-policy-controller[CIS policy controller]

Refer to xref:../security/compliance_intro.adoc#governance-and-risk[Governance and risk] for more topics about managing your policies.
