[#creating-a-credential-for-openstack]
= Creating a credential for Red Hat OpenStack

You need a credential to use {product-title} console to deploy and manage a {ocp} cluster on Red Hat OpenStack Platform. Note: Only {ocp-short} versions 4.5.x, and later, are supported.

Note: This procedure must be done before you can create a cluster with {product-title-short}.

[#openstack-credential-prerequisites]
== Prerequisites

You must have the following prerequisites before you create a credential:

* A deployed {product-title-short} hub cluster on {ocp-short} version 4.6 or later.
* Internet access for your {product-title-short} hub cluster so it can create the Kubernetes cluster on Red Hat OpenStack Platform.
* Red Hat OpenStack Platform login credentials and Red Hat OpenStack Platform requirements configured for {ocp-short} when using installer-provisioned infrastructure.
See https://docs.openshift.com/container-platform/4.6/installing/installing_openstack/installing-openstack-installer-custom.html[Installing a cluster on OpenStack].
* Download or create a `clouds.yaml` file for accessing the CloudStack API. Within the `clouds.yaml` file:
** Determine the cloud auth section name to use.
** Add a line for the *password*, immediately following the *username* line.

[#openstack-credential]
== Managing a credential by using the console

To create a credential from the {product-title} console, complete the steps in the console. 

Start at the navigation menu. Click *Credentials* to choose from existing credential options. *Tip:* Create a namespace specifically to host your credentials, for both convenience and added security.

. Add your Red Hat OpenStack Platform `clouds.yaml` file contents. The contents of the `clouds.yaml` file, including the password, provide the required information for connecting to the Red Hat OpenStack Platform server. The file contents *must* include the password, which you add to a new line immediately after the `username`.

. Add your Red Hat OpenStack Platform cloud name. This entry is the name specified in the cloud section of the `clouds.yaml` to use for establishing communication to the Red Hat OpenStack Platform server.

. You can optionally add a Base DNS domain for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential.

. Enter your Red Hat OpenShift Pull Secret.
You can download your pull secret from https://cloud.redhat.com/openshift/install/pull-secret[Pull secret].

. Add your SSH Private Key and SSH Public Key, which allows you to connect to the cluster.
You can use an existing key pair, or create a new one with key generation program.
See https://docs.openshift.com/container-platform/4.6/installing/installing_aws/installing-aws-default.html#ssh-agent-using_installing-aws-default[Generating an SSH private key and adding it to the agent] for more information.
. Click *Create*.
. Review the new credential information, then click *Add*. When you add the credential, it is added to the list of credentials.

You can create a cluster that uses this credential by completing the steps in link:../clusters/create_openstack.adoc#creating-a-cluster-on-openstack[Creating a cluster on Red Hat OpenStack Platform].

You can edit your credential in the console. 

When you are no longer managing a cluster that is using a credential, delete the credential to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.
