[#creating-a-credential-for-amazon-web-services]
= Creating a credential for Amazon Web Services

You need a credential to use {product-title} console to deploy and manage an {ocp} cluster on Amazon Web Services (AWS).

**Required access**: Edit

*Note:* This procedure must be done before you can create a cluster with {product-title}.

* <<aws_cred_prereqs>>,Prerequisites>>
* <<aws_cred_create>>,Creating a credential by using the console>>
* <<aws_cred_edit>>,Editing a credential by using the console>>
* <<aws_cred_delete>>,Deleting your credential>>

[#aws_cred_prereqs]
== Prerequisites

You must have the following prerequisites before creating a credential:

* A deployed {product-title} hub cluster
* Internet access for your {product-title} hub cluster so it can create the Kubernetes cluster on Amazon Web Services (AWS)
* AWS login credentials, which include access key ID and secret access key.
See https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html[Understanding and getting your security credentials].
* Account permissions that allow installing clusters on AWS.
See https://docs.openshift.com/container-platform/4.7/installing/installing_aws/installing-aws-account.html[Configuring an AWS account] for instructions on how to configure.

[#aws_cred_create]
== Creating a credential by using the console

To create a credential from the {product-title} console, complete the following steps:

. From the navigation menu, navigate to *Credentials*. Existing credentials are displayed.

. Select *Add credential*.
. Select *Amazon Web Services* as your provider.
. Add a name for your credential.
. Select a namespace for your credential from the list.
+
*Tip:* Create a namespace specifically to host your credentials, both for convenience and added security.

. You can optionally add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential.
. Add your _AWS access key ID_ for your AWS account.
Log in to https://console.aws.amazon.com/iam/home#/security_credentials[AWS] to find the ID.
. Add your _AWS Secret Access Key_.
. Enter your _Red Hat OpenShift pull secret_.
You can download your pull secret from https://cloud.redhat.com/openshift/install/pull-secret[Pull secret].
. Add your _SSH private key_ and _SSH public key_, which allows you to connect to the cluster.
You can use an existing key pair, or create a new one with key generation program.
See https://docs.openshift.com/container-platform/4.7/installing/installing_aws/installing-aws-default.html#ssh-agent-using_installing-aws-default[Generating an SSH private key and adding it to the agent] for more information about how to generate a key.
. Click *Create*.
When you create the credential, it is added to the list of credentials.

You can create a cluster that uses this credential by completing the steps in link:../clusters/create_ocp_aws.adoc#creating-a-cluster-on-amazon-web-services[Creating a cluster on Amazon Web Services].

[#aws_cred_edit]
== Editing a credential by using the console

Edit a credential for a {ocp} cluster on Amazon Web Services (AWS) by using the following steps:

. From the navigation menu, navigate to *Credentials*. Existing credentials are displayed.
. Find the credential you want to edit and click to update credential.
. Click *Edit* and enter new cloud credentials for Amazon Web Services (AWS).
. Click *Save* to update credentials.

If the cluster was created by using this provider connection, then the `<cluster-name>-aws-creds>` secret from `<cluster-namespace>` will get updated with the new credentials.

*Note:* Updating credentials does not work for cluster pool claimed clusters.

[#aws_cred_delete]
== Deleting your credential

When you are no longer managing a cluster that is using a credential, delete the credential to protect the information in the credential.

. From the navigation menu, navigate to *Credentials*.
. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.
. Select *Delete credentials* or *Delete credential*.
