[#creating-a-credential-for-openshift-cluster-manager]
= Creating a credential for Red Hat OpenShift Cluster Manager

Add an {ocm} credential so that you can discover clusters.

**Required access**: Administrator

[#prerequisites-discovery]
== Prerequisites

You need access to a https://console.redhat.com/[console.redhat.com] account. Enter the {ocm} API Token. This value can be obtained from https://console.redhat.com/openshift/token[console.redhat.com/openshift/token].


[#add-credential]
== Add your credential

*Best practice:* Create only one credential in each namespace.

You need to add your credential to discover clusters. If you have no credentials, see the following process.

. From the product navigation, click *Credentials*.

. Click the *Add credentials* button to get to the _Add credentials_ page.

. Choose the {ocm} credential _type_, then click *Next*.

. Enter the following basic information for your credential: 

  - Enter any unique name for your credential.
  - Enter a namespace that you can access. All users assigned to this namespace can also access the resources. All discovered resources that are related to this credential are created in this same namespace. Every credential that you create must be assigned to a unique, existing namespace.

. Click *Next*.

. Enter your {ocm} API token, which can be obtained from https://console.redhat.com/openshift/token[console.redhat.com/openshift/token].

. Click *Next* to review your selections or return to a step.

. Review the new credential information, then click *Add*. When you add the credential, it is added to the list of credentials.

== Deleting your credential

When you are no longer managing a cluster that is using a credential, delete the credential to protect the information in the credential.

. From the navigation menu, navigate to *Credentials*.
. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.
. Select *Delete credentials* or *Delete credential*.

If your credential is removed, or your {ocm} API token expires or is revoked, then the associated discovered clusters are removed.
