= Credentials

Credentials are used to connect and interact with cloud providers, infrastructure resources, and other integrated resources.

//credentials RBAC moved to RBAC topic

[#creating-credentials]
== Creating credentials

To create credentials from the console:

. From the left navigation menu, navigate to *Credentials*.
. Select *Add credential*.
. Select the type of credential.
. Enter the information to create the credential.

[#credentials-types]
== Credentials types

You can find information about where to find your credential in the documentation of the credential provider.

[#aws-cred]
=== Amazon Web Services

Use Amazon Web Services credentials to provision clusters on AWS:

See https://console.aws.amazon.com/iam/home#/security_credentials[AWS] to get your _access key ID_ and _secret access key_.

[azure-cred]
=== Microsoft Azure

Use Microsoft Azure credentials to provision clusters on Azure:

. Client ID: This value is generated as the `appId` property when you create a service principal with the following command: 
+
----
az ad sp create-for-rbac --role Contributor --name <service_principal>
----

. Client Secret: This value is generated as the `password` property when you create a service principal with the following command:
+
----
az ad sp create-for-rbac --role Contributor --name <service_principal>
----

. Subscription ID: This value is the `id` property in the output of the following command:
+
----
az account show
----

. Tenant ID: This value is the `tenantId` property in the output of the following command:
+
----
az account show
----

[google-cred]
=== Google Cloud Platform

Use Google Cloud Platform credentials to provision clusters on Google Cloud Platform.

. _Project ID_: Log in to https://console.cloud.google.com/apis/credentials/serviceaccountkey[Google Cloud Platform] to retrieve your settings.

. _Service account JSON key_

.. In the Google Cloud Platform main menu, select *IAM & Admin* and start the *Service Accounts applet*
.. Select *Create Service Account*.
.. Provide the `Name`, `Service account ID`, and `Description` of your service account.
.. Select *Create* to create the service account.
.. Select a role of *Owner*, and click *Continue*.
.. Click *Create Key*
.. Select *JSON*, and click *Create*. 
.. Save the resulting file to your computer.

[vmware-cred]
=== VMware vSphere

Use VMware vSphere credentials to provision clusters on VMware vSphere.

. vCenter server: The fully-qualified host name or IP address. The value must be defined in the vCenter server root CA certificate. If possible, use the fully-qualified host name.
. vCenter root CA certificate
.. You can download your certificate in the `download.zip` package with the certificate from your VMware vCenter server at: `https://<vCenter_address>/certs/download.zip`. 
+
Replace `vCenter_address` with the address of your vCenter server. 
.. Unpackage the `download.zip` file.
.. Use the certificate from the `certs/<platform>` directory that has a `.0` extension. *Tip:* You can use the `ls certs/<platform>` command to list all of the available certificates for your platform.
+
Replace `<platform>` with the abbreviation for your platform: `lin`, `mac`, or `win`. 
+
For example: `certs/lin/3a343545.0`

[openstack-cred]
=== Red Hat OpenStack Platform

Use Red Hat OpenStack Platform credentials to provision clusters on Red Hat OpenStack Platform.

. clouds.yaml: The contents of the `clouds.yaml` file, including the password, provide the required information for connecting to the Red Hat OpenStack Platform server. The file contents *must* include the password, which you add to a new line immediately after the `username`.

. cloud name: This entry is the name specified in the cloud section of the `clouds.yaml` to use for establishing communication to the Red Hat OpenStack Platform server.

=== Bare metal

Bare metal credentials are use to provision clusters on bare metal assets.

. _libvirt URI_: See https://libvirt.org/uri.html[Connection URIs] for more information.
. _list of SSH known hosts_

. For disconnected installations only:
+
.. _Image registry mirror_: This value contains the disconnected registry path. The path contains the hostname, port, and repository path to all of the installation images for disconnected installations. Example: `repository.com:5000/openshift/ocp-release`.
+
The path creates an image content source policy mapping in the `install-config.yaml` to the {ocp} release images. As an example, `repository.com:5000` produces this `imageContentSource` content:
+
----
imageContentSources:
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-release-nightly
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----
.. _Bootstrap OS image_: This value contains the URL to the image to use for the bootstrap machine.
.. _Cluster OS image_: This value contains the URL to the image to use for {ocp} cluster machines. 
.. _Additional trust bundle_: This value provides the contents of the certificate file that is required to access the mirror registry.
+
*Note:* If you are deploying managed clusters from a hub that is in a disconnected environment, and want them to be automatically imported post install, add an Image Content Source Policy to the `install-config.yaml` file by using the `YAML` editor. A sample entry is shown in the following example: 
+
----
imageContentSources:
- mirrors:
  - registry.example.com:5000/rhacm2
  source: registry.redhat.io/rhacm2
----

=== Red Hat Openshift Cluster Manager

Red Hat Openshift Cluster Manager credentials are use to discover and import clusters created on cloud.redhat.com.

=== Ansible Automation Platform

Ansible Automation Platform credentials are use to automate infrastructure by connecting to an Ansible Tower.

[#credentials-other]
== Other credentials

=== Red Hat OpenShift pull secret

The OpenShift pull secret is used to connect to the OpenShift registry and pull the OpenShift images used to setup an OpenShift cluster.
You can download your pull secret from https://cloud.redhat.com/openshift/install/pull-secret[Pull secret].

=== SSH keys

SSH keys are used to securely connect and configure infrastructure.
You can use an existing key pair, or create a new pair using a key generation program.
