:_mod-docs-content-type: CONCEPT

[#volsync-install-clusters]
= VolSync installation on managed clusters

[role="_abstract"]
VolSync installation on managed clusters places the VolSync operator in the `volsync-system` namespace. That deployment supports managed clusters that are not {ocp-short}, and is required on both the source and destination clusters for persistent volume claim replication.

If you installed VolSync as an {olm} operator on an {ocp-short} managed cluster in an earlier {acm-short} version, the VolSync {olm} operator is removed and replaced with the VolSync deployment in the `volsync-system` namespace.

VolSync can be installed with a managed cluster label or with a `ManagedClusterAddOn` resource on the hub cluster.

.Additional resources

* xref:../volsync/volsync_install_label_console.adoc#volsync-install-label[Install VolSync by adding a label in the console]
* xref:../volsync/volsync_install_label_cli.adoc#volsync-install-label-cli[Install VolSync by adding a label from the command line]
* xref:../volsync/volsync_install_mcao.adoc#volsync-install-mcaddon[Install VolSync by creating a ManagedClusterAddOn]
