:_mod-docs-content-type: PROCEDURE

[#rsync-replication-volsync]
[#volsync-rsync-clusters]
= Configure an Rsync replication

[role="_abstract"]
Configure a 1:1 asynchronous replication of a persistent volume claim across managed clusters by creating a `ReplicationDestination` on the destination cluster and a `ReplicationSource` on the source cluster by using Rsync. You can use Rsync-based replication for disaster recovery or for sending data to a remote site.

*Important:* Use Rsync-TLS instead of Rsync for enhanced security. By using Rsync-TLS, you can avoid using elevated user permissions that are not required for replicating persistent volumes.

For Rsync-based replication, configure custom resources on the source and destination clusters. The custom resources use the `address` value to connect the source to the destination, and the `sshKeys` to ensure that the transferred data is secure.

*Note:* You must copy the values for `address` and `sshKeys` from the destination to the source, so configure the destination before you configure the source.

.Prerequisites

* VolSync is installed on the source and destination managed clusters. See xref:../volsync/volsync_install.adoc#volsync-install-clusters[VolSync installation on managed clusters].
* At least two managed clusters for the same {acm-short} hub cluster
* Network connectivity between the clusters that you configure with VolSync. If the clusters are not on the same network, you can configure the link:../../networking/submariner/subm_intro.adoc#submariner[Submariner multicluster networking and service discovery] and use the `ClusterIP` value for `ServiceType`, or use a load balancer with the `LoadBalancer` value for `ServiceType`.
* The source persistent volume claim is on a CSI storage class

.Procedure

. Configure your destination cluster by completing the following steps:
.. Run the following command on the destination cluster to create the namespace:

+
[source,bash]
----
oc create ns <destination-ns>
----
+
Replace `destination-ns` with a name for the namespace that will contain your destination persistent volume claim.

.. Copy the following YAML content to create a new file called `replication_destination.yaml`:

+
[source,yaml]
----
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: <destination>
  namespace: <destination-ns>
spec:
  rsync:
    serviceType: LoadBalancer
    copyMethod: Snapshot
    capacity: 2Gi
    accessModes: [ReadWriteOnce]
    storageClassName: gp2-csi
    volumeSnapshotClassName: csi-aws-vsc
----
+
* For this example, the `serviceType` value of `LoadBalancer` is used. The load balancer service enables your source managed cluster to transfer information to a different destination managed cluster. You can use `ClusterIP` as the service type if your source and destinations are on the same cluster, or if you have Submariner network service configured. Note the address and the name of the secret to refer to when you configure the source cluster.
* Make sure that the `capacity` value matches the capacity of the persistent volume claim that is being replicated.
* Replace `destination` with the name of your replication destination custom resource.
* Replace `destination-ns` with the name of the namespace where your destination is located.

.. Run the following command on the destination cluster to create the `ReplicationDestination` resource:

+
[source,bash]
----
oc create -n <destination-ns> -f replication_destination.yaml
----
+
Replace `destination-ns` with the name of the namespace where your destination is located.
+
After the `ReplicationDestination` resource is created, the `.status.rsync.address` field provides the destination address for source-to-destination communication, and the `.status.rsync.sshKeys` field provides the name of the SSH key secret for secure data transfer.

.. Run the following command to copy the value of `.status.rsync.address` to use on the source cluster:

+
[source,bash]
----
ADDRESS=`oc get replicationdestination <destination> -n <destination-ns> --template={{.status.rsync.address}}`
echo $ADDRESS
----
+
* Replace `destination` with the name of your replication destination custom resource.
* Replace `destination-ns` with the name of the namespace where your destination is located.
+
The output should appear similar to the following example for an Amazon Web Services environment:

+
----
a831264645yhrjrjyer6f9e4a02eb2-5592c0b3d94dd376.elb.us-east-1.amazonaws.com
----

.. Run the following command to copy the name of the secret:

+
[source,bash]
----
SSHKEYS=`oc get replicationdestination <destination> -n <destination-ns> --template={{.status.rsync.sshKeys}}`
echo $SSHKEYS
----
+
* Replace `destination` with the name of your replication destination custom resource.
* Replace `destination-ns` with the name of the namespace where your destination is located.
+
Use the SSH keys secret name from the output when you configure the source cluster. The output might resemble the following name:

+
----
volsync-rsync-dst-src-destination-name
----

.. Copy the SSH secret from the destination cluster by entering the following command:

+
[source,bash]
----
oc get secret -n <destination-ns> $SSHKEYS -o yaml > /tmp/secret.yaml
----
+
Replace `destination-ns` with the namespace of the persistent volume claim where your destination is located.

.. Open the secret file by entering the following command:

+
[source,bash]
----
vi /tmp/secret.yaml
----

.. Change the namespace to the namespace of your source cluster. For this example, it is `source-ns`.
.. Remove the owner references (`.metadata.ownerReferences`).

.. On the source cluster, create the secret by entering the following command:

+
[source,bash]
----
oc create -f /tmp/secret.yaml
----

. Identify the source persistent volume claim that you want to replicate.
. Create the `ReplicationSource` resource on the source cluster. Your resource might resemble the following content:

+
[source,yaml]
----
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: <source>
  namespace: <source-ns>
spec:
  sourcePVC: <persistent_volume_claim>
  trigger:
    schedule: "*/3 * * * *"
  rsync:
    sshKeys: <mysshkeys>
    address: <my.host.com>
    copyMethod: Snapshot
    storageClassName: gp2-csi
    volumeSnapshotClassName: csi-aws-vsc
----
+
* Replace `source` with the name for your replication source custom resource.
* Replace `source-ns` with the namespace of the persistent volume claim where your source is located.
* Replace `persistent_volume_claim` with the name of your source persistent volume claim.
* Replace `mysshkeys` with the keys that you copied from the `.status.rsync.sshKeys` field of the `ReplicationDestination` when you configured it.
* Replace `my.host.com` with the host address that you copied from the `.status.rsync.address` field of the `ReplicationDestination` when you configured it.

.. On the source cluster, replace the `address` and `sshKeys` values with the values that you noted from the destination cluster, then create the resource:

+
[source,bash]
----
sed -i "s/<my.host.com>/$ADDRESS/g" replication_source.yaml
sed -i "s/<mysshkeys>/$SSHKEYS/g" replication_source.yaml
oc create -n <source-ns> -f replication_source.yaml
----
+
Replace `source-ns` with the namespace of the persistent volume claim where your source is located.
+
*Note:* You must create the file in the same namespace as the persistent volume claim that you want to replicate.

. Verify that the replication completed by running the following command on the `ReplicationSource` object:

+
[source,bash]
----
oc describe ReplicationSource -n <source-ns> <source>
----
+
* Replace `source-ns` with the namespace of the persistent volume claim where your source is located.
* Replace `source` with the name of your replication source custom resource.
If the replication was successful, the output should be similar to the following example:

+
----
Status:
  Conditions:
    Last Transition Time:  2021-10-14T20:48:00Z
    Message:               Synchronization in-progress
    Reason:                SyncInProgress
    Status:                True
    Type:                  Synchronizing
    Last Transition Time:  2021-10-14T20:41:41Z
    Message:               Reconcile complete
    Reason:                ReconcileComplete
    Status:                True
    Type:                  Reconciled
  Last Sync Duration:      5m20.764642395s
  Last Sync Time:          2021-10-14T20:47:01Z
  Next Sync Time:          2021-10-14T20:48:00Z
----
+
If the `Last Sync Time` has no time listed, then the replication is not complete.

.Additional resources

* xref:../volsync/volsync_rsync_tls.adoc#rsync-tls-replication-volsync[Configure an Rsync-TLS replication]
* xref:../volsync/volsync_convert_backup.adoc#volsync-convert-backup-pvc[Convert a replicated image to a persistent volume claim]
* link:https://volsync.readthedocs.io/en/latest/usage/index.html[Usage] in the VolSync documentation
* xref:../volsync/volsync_copy_params.adoc#volsync-copy-params[VolSync copy and storage parameters]
* xref:../volsync/volsync_schedule.adoc#volsync-schedule[VolSync replication schedule]
* xref:../volsync/volsync_copy_params.adoc#volsync-copy-params[VolSync copy and storage parameters]