:_mod-docs-content-type: REFERENCE

[#volsync-copy-params]
= VolSync copy and storage parameters

[role="_abstract"]
The `copyMethod`, `storageClassName`, and `volumeSnapshotClassName` fields control how VolSync creates a point-in-time copy of a persistent volume claim.

`copyMethod`::
Specifies whether a point-in-time copy is generated, and which method is used. Valid values include `Clone`, `Direct`, and `Snapshot`. If your storage driver supports cloning, `Clone` can be a more streamlined process for replication. For Restic backups, use `Clone` when you want to ensure that a point-in-time image is saved.

`storageClassName`::
Name of the storage class to use for the point-in-time copy. Specify this value when you use a storage class that is different from the default for your environment. If you omit the value on a `ReplicationSource`, the storage class of the source volume is used. If you omit the value on a `ReplicationDestination`, the system storage class is used.

`volumeSnapshotClassName`::
Name of the `VolumeSnapshotClass` to use when `copyMethod` is `Snapshot`. This value is not required for other `copyMethod` values. If you omit the value, the system default `VolumeSnapshotClass` is used.

.Additional resources

* xref:../volsync/volsync_rsync_tls.adoc#rsync-tls-replication-volsync[Configure an Rsync-TLS replication]
* xref:../volsync/volsync_rsync.adoc#rsync-replication-volsync[Configure an Rsync replication]
* xref:../volsync/volsync_restic.adoc#restic-backup-volsync[Configure a Restic backup]
* xref:../volsync/volsync_rclone.adoc#rclone-replication-volsync[Configure an Rclone replication]
