:_mod-docs-content-type: PROCEDURE

[#volsync-rsync-tls-copy-secret]
= Copy the Rsync-TLS key secret to the source cluster

[role="_abstract"]
Copy the Rsync-TLS key secret from the destination cluster to the source cluster so that the `ReplicationSource` can authenticate to the destination.

.Prerequisites

* You configured a `ReplicationDestination` and captured the `.status.rsyncTLS.keySecret` value. See xref:../volsync/volsync_rsync_tls_destination.adoc#volsync-rsync-tls-destination[Configure an Rsync-TLS replication destination].

.Procedure

. Copy the key secret from the destination cluster by entering the following command:

+
[source,bash]
----
oc get secret -n <destination-ns> $KEYSECRET -o yaml > /tmp/secret.yaml
----
+
Replace `destination-ns` with the namespace where your replication destination is located.

. Open the secret file by entering the following command:

+
[source,bash]
----
vi /tmp/secret.yaml
----

. Change the namespace to the namespace of your source cluster. For this example, it is `source-ns`.
. Remove the owner references (`.metadata.ownerReferences`).
. On the source cluster, create the secret by entering the following command:

+
[source,bash]
----
oc create -f /tmp/secret.yaml
----

.Next steps

To configure the `ReplicationSource`, see xref:../volsync/volsync_rsync_tls_source.adoc#volsync-rsync-tls-source[Configure an Rsync-TLS replication source].
