:_mod-docs-content-type: PROCEDURE

[#volsync-install-label]
= Install VolSync by adding a label in the console

[role="_abstract"]
Install VolSync on a managed cluster by adding the VolSync add-on label from the {acm-short} console.

.Prerequisites

* A configured {ocp} environment on a supported {acm-short} hub cluster
* The storage driver for the source persistent volume is CSI-compatible and supports snapshots

.Procedure

. Select a managed cluster from the *Clusters* page in the hub cluster console to view its details.
. In the *Labels* field, add the following label:

+
----
addons.open-cluster-management.io/volsync=true
----
+
The VolSync service pod is installed on the managed cluster.

. Add the same label to the other managed cluster.
. Run the following command on the hub cluster to confirm that the VolSync operator is installed:

+
[source,bash]
----
oc -n <managed-cluster-name> get ManagedClusterAddOn volsync
----
+
Replace `managed-cluster-name` with the name of the managed cluster.

. Verify that the command output shows that the `ManagedClusterAddOn` has a `Ready` status.
. Run the following command on the managed cluster to confirm that the VolSync operator is installed:

+
[source,bash]
----
kubectl -n volsync-system get deployment volsync
----

.Additional resources

* xref:../volsync/volsync_install_label_cli.adoc#volsync-install-label-cli[Install VolSync by adding a label from the command line]
* xref:../volsync/volsync_install_mcao.adoc#volsync-install-mcaddon[Install VolSync by creating a ManagedClusterAddOn]
