:_mod-docs-content-type: PROCEDURE

[#volsync-rsync-verify]
= Verify an Rsync replication

[role="_abstract"]
Verify that the Rsync replication completed by checking the status of the `ReplicationSource` object on the source cluster.

.Prerequisites

* You created a `ReplicationSource` on the source cluster. See xref:../volsync/volsync_rsync_source.adoc#volsync-rsync-source[Configure an Rsync replication source].

.Procedure

. Verify that the replication completed by running the following command on the `ReplicationSource` object:

+
[source,bash]
----
oc describe ReplicationSource -n <source-ns> <source>
----
+
* Replace `source-ns` with the namespace of the persistent volume claim where your source is located.
* Replace `source` with the name of your replication source custom resource.
+
If the replication was successful, the output should be similar to the following example:

+
----
Status:
  Conditions:
    Last Transition Time:  2021-10-14T20:48:00Z
    Message:               Synchronization in-progress
    Reason:                SyncInProgress
    Status:                True
    Type:                  Synchronizing
    Last Transition Time:  2021-10-14T20:41:41Z
    Message:               Reconcile complete
    Reason:                ReconcileComplete
    Status:                True
    Type:                  Reconciled
  Last Sync Duration:      5m20.764642395s
  Last Sync Time:          2021-10-14T20:47:01Z
  Next Sync Time:          2021-10-14T20:48:00Z
----
+
If the `Last Sync Time` has no time listed, then the replication is not complete.

.Additional resources

* xref:../volsync/volsync_rsync_tls.adoc#rsync-tls-replication-volsync[Configure an Rsync-TLS replication]
* xref:../volsync/volsync_convert_backup.adoc#volsync-convert-backup-pvc[Convert a replicated image to a persistent volume claim]
* link:https://volsync.readthedocs.io/en/latest/usage/index.html[Usage]
* xref:../volsync/volsync_copy_params.adoc#volsync-copy-params[VolSync copy and storage parameters]
* xref:../volsync/volsync_schedule.adoc#volsync-schedule[VolSync replication schedule]
