[#running-the-must-gather-command-to-troubleshoot]
= Running the must-gather command to troubleshoot

To get started with troubleshooting, learn about the troubleshooting scenarios for users to run the `must-gather` command to debug the issues, then see the procedures to start using the command.

*Required access:* Cluster administrator

[#scenarios]
== Must-gather scenarios

* *Scenario one:* Use the _Documented troubleshooting_ section to see if a solution to your problem is documented. The guide is organized by the major functions of the product.

+
With this scenario, you check the guide to see if your solution is in the documentation.
+

* *Scenario two:* If your problem is not documented with steps to resolve, run the `must-gather` command and use the output to debug the issue.

* *Scenario three:* If you cannot debug the issue using your output from the `must-gather` command, then share your output with Red Hat Support.

[#procedure]
== Must-gather procedure

See the following procedure to start using the `must-gather` command:

. Learn about the `must-gather` command and install the prerequisites that you need at https://docs.openshift.com/container-platform/4.8/support/gathering-cluster-data.html[Gathering data about your cluster] in the RedHat OpenShift Container Platform documentation.

. Log in to your cluster. For the usual use-case, you should run the `must-gather` while you are logged into your _engine_ cluster. 

+
*Note:* If you want to check your managed clusters, find the `gather-managed.log` file that is located in the the `cluster-scoped-resources` directory:
+

+
----
<your-directory>/cluster-scoped-resources/gather-managed.log>
----
+

Check for managed clusters that are not set `True` for the JOINED and AVAILABLE column. You can run the `must-gather` command on those clusters that are not connected with `True` status.

. Add the 
multicluster engine for Kubernetes image that is used for gathering data and the directory. Run the following command, where you insert the image and the directory for the output:
+
----
oc adm must-gather --image=registry.redhat.io/multicluster-engine/must-gather-rhel8:v2.2.0 --dest-dir=<directory>
----
  
. Go to your specified directory to see your output, which is organized in the following levels:

 - Two peer levels: `cluster-scoped-resources` and `namespace` resources.
 - Sub-level for each: API group for the custom resource definitions for both cluster-scope and namespace-scoped resources.
 - Next level for each: YAML file sorted by `kind`.

[#must-gather-disconnected]
== Must-gather in a disconnected environment

Complete the following steps to run the `must-gather` command in a disconnected environment: 

. In a disconnected environment, mirror the Red Hat operator catalog images into their mirror registry. For more information, see xref:./install_disconnected.adoc#install-on-disconnected-networks[Install on disconnected networks].

. Run the following command to extract logs, which reference the image from their mirror registry:

----
REGISTRY=registry.example.com:5000
IMAGE=$REGISTRY/multicluster-engine/must-gather-rhel8@sha256:ff9f37eb400dc1f7d07a9b6f2da9064992934b69847d17f59e385783c071b9d8

oc adm must-gather --image=$IMAGE --dest-dir=./data
----

You can open a bug for the product team https://bugzilla.redhat.com/[here].