[#using-grafana-dashboards]
= Using Grafana dashboards

Use Grafana dashboards to view hub cluster and managed cluster metrics.

* <<setting-up-the-grafana-developer-instance,Setting up the Grafana developer instance>>
* <<design-your-dashboard,Designing your Grafana dashboard>>
* <<uninstalling-the-grafana-developer-instance,Uninstalling the Grafana developer instance>>

[#setting-up-the-grafana-developer-instance]
== Setting up the Grafana developer instance

You can design your Grafana dashboard by creating a `grafana-dev` instance. Be sure to use the most current `grafana-dev` instance.

Complete the following steps to set up the Grafana developer instance:

. Clone the link:https://github.com/open-cluster-management/multicluster-observability-operator[`open-cluster-management/multicluster-observability-operator/`] repository, so that you are able to run the scripts that are in the `tools` folder.

. Run the `setup-grafana-dev.sh` to setup your Grafana instance. When you run the script the following resources are created: `secret/grafana-dev-config`, `deployment.apps/grafana-dev`, `service/grafana-dev`, `ingress.extensions/grafana-dev`, `persistentvolumeclaim/grafana-dev`:
+
----
./setup-grafana-dev.sh --deploy
secret/grafana-dev-config created
deployment.apps/grafana-dev created
service/grafana-dev created
serviceaccount/grafana-dev created
clusterrolebinding.rbac.authorization.k8s.io/open-cluster-management:grafana-crb-dev created
route.route.openshift.io/grafana-dev created
persistentvolumeclaim/grafana-dev created
oauthclient.oauth.openshift.io/grafana-proxy-client-dev created
deployment.apps/grafana-dev patched
service/grafana-dev patched
route.route.openshift.io/grafana-dev patched
oauthclient.oauth.openshift.io/grafana-proxy-client-dev patched
clusterrolebinding.rbac.authorization.k8s.io/open-cluster-management:grafana-crb-dev patched
----

. Switch the user role to Grafana administrator with the `switch-to-grafana-admin.sh` script.
+
.. Select the Grafana URL, `https:grafana-dev-open-cluster-management-observability.{OPENSHIFT_INGRESS_DOMAIN}`, and log in.
.. Then run the following command to add the switched user as Grafana administrator. For example, after you log in using `kubeadmin`, run following command:
+
----
./switch-to-grafana-admin.sh kube:admin
User <kube:admin> switched to be grafana admin
----

The Grafana developer instance is set up. 

[#verifying-grafana-version]
=== Verifying Grafana version

Verify the Grafana version from the command line interface (CLI) or from the Grafana user interface. 

After you log in to your hub cluster, access the `observabilty-grafana` pod terminal. Run the following command:

----
grafana-cli
----

The Grafana version that is currently deployed within the cluster environment is displayed.

Alternatively, you can navigate to the _Manage_ tab in the Grafana dashboard. Scroll to the end of the page, where the version is listed.

[#design-your-dashboard]
== Designing your Grafana dashboard

After you set up the Grafana instance, you can design the dashboard. Complete the following steps to refresh the Grafana console and design your dashboard:

. From the Grafana console, create a dashboard by selecting the *Create* icon from the navigation panel. Select *Dashboard*, and then click *Add new panel*.

. From the _New Dashboard/Edit Panel_ view, navigate to the _Query_ tab.

. Configure your query by selecting `Observatorium` from the data source selector and enter a PromQL query.

. From the Grafana dashboard header, click the *Save* icon that is in the dashboard header.

. Add a descriptive name and click *Save*. 

[#designing-your-grafana-dashboard-with-configmap]
=== Designing your Grafana dashboard with a ConfigMap

Design your Grafana dashboard with a ConfigMap. You can use the `generate-dashboard-configmap-yaml.sh` script to generate the dashboard ConfigMap, and to save the ConfigMap locally:

----
./generate-dashboard-configmap-yaml.sh "Your Dashboard Name"
Save dashboard <your-dashboard-name> to ./your-dashboard-name.yaml
----

If you do not have permissions to run the previously mentioned script, complete the following steps:

. Select a dashboard and click the *Dashboard settings* icon. 
. Click the *JSON Model* icon from the navigation panel.
. Copy the dashboard JSON data and paste it in the `_data_` section.
. Modify the `_name_` and replace `_$your-dashboard-name_`. Enter a universally unique identifier (UUID) in the `uid` field in `data.$your-dashboard-name.json.$$your_dashboard_json`. You can use a program such as _uuidegen_ to create a UUID. Your ConfigMap might resemble the following file:
+
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: $your-dashboard-name
  namespace: open-cluster-management-observability
  labels:
    grafana-custom-dashboard: "true"
data:
  $your-dashboard-name.json: |-
    $your_dashboard_json
----
+
*Notes:* 
+
- If your dashboard is created within the `grafana-dev` instance, you can take the name of the dashboard and pass it as an argument in the script. For example, a dashboard named _Demo Dashboard_ is created in the `grafana-dev` instance. From the CLI, you can run the following script:
+
----
./generate-dashboard-configmap-yaml.sh "Demo Dashboard"
----
+
After running the script, you might receive the following message:
+
----
Save dashboard <demo-dashboard> to ./demo-dashboard.yaml
----
- If your dashboard is not in the _General_ folder, you can specify the folder name in the `annotations` section of this ConfigMap:
+
----
annotations:
  observability.open-cluster-management.io/dashboard-folder: Custom
----
+
After you complete your updates for the ConfigMap, you can install it to import the dashboard to the Grafana instance.

Verify that the YAML file is created by applying the YAML from the CLI or {ocp-short} console. A ConfigMap within the `open-cluster-management-observability` namespace is created. Run the following command from the CLI:

----
oc apply -f demo-dashboard.yaml
----

From the {ocp-short} console, create the ConfigMap using the `demo-dashboard.yaml` file. The dashboard is located in the _Custom_ folder.


[#uninstalling-the-grafana-developer-instance]
== Uninstalling the Grafana developer instance

When you uninstall the instance, the related resources are also deleted. Run the following command:

----
./setup-grafana-dev.sh --clean
secret "grafana-dev-config" deleted
deployment.apps "grafana-dev" deleted
serviceaccount "grafana-dev" deleted
route.route.openshift.io "grafana-dev" deleted
persistentvolumeclaim "grafana-dev" deleted
oauthclient.oauth.openshift.io "grafana-proxy-client-dev" deleted
clusterrolebinding.rbac.authorization.k8s.io "open-cluster-management:grafana-crb-dev" deleted
----

[#additional-resource-grafana]
== Additional resources

* See xref:../observability/use_observability.adoc#exporting-metrics-to-external-endpoints[Exporting metrics to external endpoints].

* See link:https://man7.org/linux/man-pages/man1/uuidgen.1.html[uuidegen] for instructions to create a UUID.

* See xref:../observability/grafana_labels.adoc#using-managed-cluster-labels[Using managed cluster labels in Grafana] for more details.

* Return to the beginning of the page xref:../observability/design_grafana.adoc#using-grafana-dashboards[Using Grafana dashboard].

* For topics, see the xref:../observability/observe_environments_intro.adoc#observing-environments-intro[Observing environments introduction].
