[#integrate-rh-insights]
= Integrate observability with Red Hat insights

You can integrate {product-title} observability with Red Hat Insights to help identify existing or potential problems in your cluster. Red Hat Insights helps you to identify, prioritize, and resolve stability, performance, network, and security risks. {ocp} offers local health monitoring through OpenShift Cluster Manager. OpenShift Cluster Manager collects anonymized, aggregrated information about the health, usage, and size of the clusters. For more information, see https://access.redhat.com/documentation/en-us/red_hat_insights/2021/[Red Hat Insights product documentation].

*Required access*: Cluster administrator

[#prerequisites-obs-insights]
== Prerequisites

* Install Red Hat Insights
* Access to OpenShift Cluster Manager to view Red Hat Insights
* Outbound ports to communicate with (is there a global proxy used?)


You can use the search feature when you are deciding on which remediation to use. 

You can view the remediation options that are displayed from Insights. The remediation option display the _Description_ of the vulnerability, _Category_ that vulnerability is associated with, and the _Total risk_. You can add multiple labels to the _Category_ section.

The _Status_ card displays information about _Nodes_, _Applications_, _Policy violations_, and _Identified issues_. The _Nodes_ status informs you of the number of nodes that are inactive. The _Applications_ status directs you to the _Overview_ tab of the _Applications_ page. The _Policy violations_ status directs you to the _Governance_ page. The _Identified issues_ status displays the number of issues per severity. The risks used to triage the issues are the following severity levels: _Critical_, _Major_, _Low_, and _Warning_.

From the _Description_ section, you can select the link to the vulnerability. You can view steps to resolve your vulnerabilty by viewing the _How to remediate_ tab. You can also view why the vulnerability occurred by clicking the _Reason_ tab. 

[#integrating-insights]
== Integrating Red Hat Insights



[#viewing-vulnerabilities-insights]
== Viewing potential vulnerabilities from the console

You can view the vulnerabilities on a specific cluster by completing the following steps:

. Log in to your {product-title-short} cluster.
. From the navigation menu, select *Clusters*.
. Select a managed cluster from the table to view more details.
. From the _Status_ card, view the number of potential issues.
. Select the number of potential issue to view the severity diagram and remediation options for the issues.
. Click the link to the vulnerability to view steps on _How to remediate_ and the _Reason_ for the vulnerability.
. If there are more vulnerabilities, click *Back* to view the list of potential issues.