[#manage-insights]
= Managing insight PolicyReports

{product-title} `PolicyReports` are violations that are generated by the `insights-client`. The `PolicyReports` are used to define and configure alerts that are sent to incident management systems. When there is a violation, alerts from a `PolicyReport` are sent to incident management system.

View the following sections to learn how to manage and view insight `PolicyReports`:
//should proably add documentation on creating a PolicyReport if that can be done, or is it only generated by the insights-client? 
* <<search-insight-policy-report-violation,Searching for insight policy reports>>
* <<viewing-vulnerabilities-insights,Viewing identified issues from the console>>

[#search-insight-policy-report-violation]
== Searching for insight policy reports

You can search for a specific insight `PolicyReport` that has a violation, across your managed clusters. Complete the following steps to search for insight policy reports:

. Log in to your {product-title-short} hub cluster.
. Click the _Search_ icon in the console header to navigate to the _Search_ page.
. From the _Search_ page, enter the following query: `kind:policyreport`
. After you press enter, a table list of insight policy reports appear in the _Policyreport_ section.
+
*Note*: The `PolicyReport` name matches the name of the cluster. 
. You can also further specify your query by the insight policy violation and categories.
. When you select a `PolicyReport` name, you are redirected to the _Details_ page of the associated cluster. The _Insights_ sidebar is automatically displayed.
. If the search service is disabled and you want to search for an insight, run the following command from your hub cluster:
+
----
oc get policyreport --all-namespaces
----

[#viewing-vulnerabilities-insights]
== Viewing identified issues from the console

You can view the identified issues on a specific cluster by completing the following steps:

. Log in to your {product-title-short} cluster.
. From the navigation menu, select *Overview*. You can view details of the cluster issues and the severities from the _Cluster issues_ summary card.
. Select a severity to view the `PolicyReports` that are associated with the severity. You are directed to the _Search_ page, where the `PolicyReport` details are displayed.
. Select the `PolicyReport` name to be directed to the insight from the _Clusters_ page.
. Alternatively, you can select *Clusters* from the navigation menu.
. Select a managed cluster from the table to view more details.
. From the _Status_ card, view the number of identified issues.
. Select the number of potential issues to view the severity chart and recommended remediations for the issues.
. Click the link to the vulnerability to view steps on _How to remediate_ and the _Reason_ for the vulnerability.
. If there are more vulnerabilities that you want to view, click *Back* to view the list of potential issues.
+
*Note*: After the issue is resolved, the Red Hat Insights are received by {product-title-short} every 30 minutues and Red Hat Insights is updated every two hours.
. Verify the which component sent the alert message from the `PolicyReport`:
+
.. After you log in to your hub cluster and navigate to the _Governance_ page, select a specific `policyreport`. 
.. Select the _Status_ tab and click the *View details* link to view the `PolicyReport` YAML file.
.. Locate the `source` parameter, which informs you of the component that sent the violation. The value options are `grc` and `insights`.

Learn how to create custom alert rules for the `PolicyReports`, see xref:../observability/customize_observability.adoc#configuring-rules-for-alertmanager[Configuring rules for AlertManager] for more information.
