[#disable-right-size-virt]
= Disabling _RightSizingRecommendation_ for Virtualization workloads

Use `RightSizingRecommendation` for Virtualization to help you identify over-provisioned or under-utilized virtual machine resources across managed clusters. After you enable the observability service, the `RightSizingRecommendation` feature is enabled by default. You can disable the feature by editing the `MultiClusterObservability` custom resource on the hub cluster.

The `RightSizingRecommendation` feature uses the following resources:

The `rs-virt-config` `ConfigMap`:: Stores virtual machine configurations for placement and `PrometheusRule`.
The `rs-virt-prom-rules-policy` `Policy`:: Contains the Prometheus rules to evaluate resource usage.
The `rs-virt-placement` `Placement`:: Determines target clusters based on label selectors.
The `rs-virt-policyset-binding` `PlacementBinding`:: Binds the policy and placement together.

*Required access:* Editor

.Prerequisites

- You have the `MultiClusterObservability` operator enabled on your hub cluster. To learn how to enable the Observability, see xref:../observability_enable.adoc#enabling-observability-service[Enabling the Observability service].
- You have the {ocp-virt} operator installed on your related managed cluster or hub cluster. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/virtualization/installing#installing-virt[Installing {ocp-virt-short}].

.Procedure

Complete the following steps to disable right-sizing for your virtual machines:

. Open the `observability` instance configuration. Run the following command:

+
[source,bash]
----
oc edit multiclusterobservability observability
----

. Add the following lines to the `spec` section of your `MultiClusterObservability` custom resource:

+
[source,yaml]
----
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  capabilities:
    platform:
      analytics:
        virtualizationRightSizingRecommendation:
          enabled: false
. . .
----

. To enable `RightSizingRecommendation` for your virtual machines, set the `virtualizationRightSizingRecommendation.enabled:` parameter to `true`.

. View `RightSizingRecommendation` guides from your Grafana dashboard by selecting *RightSizing Recommendation* > *ACM Right-Sizing OpenShift Virtualization*.

+
*Note:* The CPU and memory information at the cluster level is displayed.

. To view CPU and memory details, and past resource usage for your virtual machines, select the name of your virtual machine.
