[#customizing-route-cert]
= Customizing route certificate

If you want to customize the {ocp-short} route certification, you must add the routes in the `alt_names` section. To ensure your {ocp-short} routes are accessible, add the following information: `alertmanager.apps.<domainname>`, `observatorium-api.apps.<domainname>`, `rbac-query-proxy.apps.<domainname>`.

*Note:* Users are responsible for certificate rotations and updates.

[#customizing-certificates-object-store]
== Customizing certificates for accessing the object store

You can configure secure connections with the observability object store by creating a `Secret` resource that contains the certificate authority and configuring the `MultiClusterObservability` custom resource. Complete the following steps:

. To validate the object store connection, create the `Secret` object in the file that contains the certificate authority by using the following command:

+
[source,bash]
----
oc create secret generic <tls_secret_name> --from-file=ca.crt=<path_to_file> -n open-cluster-management-observability
----

.. Alternatively, you can apply the following YAML to create the secret:

+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: <tls_secret_name>
  namespace: open-cluster-management-observability
type: Opaque
data:
  ca.crt: <base64_encoded_ca_certificate>
----
*Optional:* If you want to enable mutual TLS, you need to add the `public.crt` and `private.key` keys in the previous secret.

. Add the TLS secret details to the `metricObjectStorage` section by using the following command:

+
[source,bash]
----
oc edit mco observability -o yaml
----

+
Your file might resemble the following YAML:

+
[source,yaml]
----
metricObjectStorage:
  key: thanos.yaml
  name: thanos-object-storage
  tlsSecretName: tls-certs-secret <1>
  tlsSecretMountPath: /etc/<s3-directory>/certs <2>
----
<1> The value for `tlsSecretName` is the name of the `Secret` object that you previously created.
<2> The `/etc/<s3-directory>/certs/` path defined for the `tlsSecretMountPath` parameter specifies where the certificates are mounted in the Observability components. This path is required for the next step.

. Update the `thanos.yaml` definition in the `thanos-object-storage` secret by adding the `http_config.tls_config` section with the certificate details. View the following example. Replace values where needed:

+
[source,yaml]
----
thanos.yaml: |
   type: s3
   config:
     bucket: <bucket-name>
     endpoint: <s3.port>
     insecure: false <1>
     access_key: <s3-access>
     secret_key: <s3-secret>
     http_config:
       tls_config:
         ca_file: /etc/<s3-directory>/certs/ca.crt <2>
         insecure_skip_verify: false
----
<1> Set the `insecure` parameter to `false` to enable HTTPS.
<2> The path for the `ca_file` parameter must match the `tlsSecretMountPath` from the `MultiClusterObservability` custom resource. The `ca.crt` must match the key in the `<tls_secret_name>` `Secret` resource.
+
*Optional:* If you want to enable mutual TLS, you need to add the `cert_file` and `key_file` keys to the `tls_config` section. See the following example. Replace values where needed:

+
[source,yaml]
----
 thanos.yaml: |
    type: s3
    config:
      bucket: <bucket-name>
      endpoint: <s3.port>
      insecure: false
      access_key: <s3-access>
      secret_key: <s3-secret>
      http_config:
        tls_config:
          ca_file: /etc/<s3-directory>/certs/ca.crt <1>
          cert_file: /etc/<s3-directory>/certs/public.crt
          key_file: /etc/<s3-directory>/certs/private.key
          insecure_skip_verify: false
----
<1> The path for `ca_file`, `cert_file`, and `key_file` must match the `tlsSecretMountPath` from the `MultiClusterObservability` custom resource. The `ca.crt`, `public.crt`, and `private.crt` must match the respective key in the `tls_secret_name>` `Secret` resource.

. To verify that you can access the object store, check that the pods are deployed. Run the following command:

+
[source,bash]
----
oc -n open-cluster-management-observability get pods -l app.kubernetes.io/name=thanos-store
----

[#add-res-obs-cert]
== Additional resources

- For information about updating the certificate for the alertmanager route, see link:../secure_cluster/cert_manage.adoc#replacing-cert-alertmanager[Replacing certificates for Alertmanager].
