:_mod-docs-content-type: PROCEDURE

[#view-issues-console]
= Viewing identified Red Hat Insights issues from the console

[role="_abstract"]
View Red Hat Insights identified issues from the console by using the cluster issues summary card and the `PolicyReport` resource. The `PolicyReports` are used to define and configure alerts that are sent to incident management systems.

*Required access*: Cluster administrator

.Prerequisites

* Ensure that Red Hat Insights is enabled. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_lightspeed/1-latest/html-single/connecting_your_rhel_systems_through_the_red_hat_lightspeed_proxy/index#connecting-through-your-own-proxy[Connecting to Red Hat Insights through your own proxy].
* Install a supported version of {ocp-short}.
* Hub cluster user, who is registered to Red Hat OpenShift Cluster Manager, must be able to manage all the {acm-short} managed clusters in Red Hat OpenShift Cluster Manager.

.Procedure

. Log in to your {acm-short} cluster.
. Select *Overview* from the navigation menu. 
. Check the _Cluster issues_ summary card. Select a severity link to view the `PolicyReports` that are associated with that severity. Details of the cluster issues and the severities are displayed from the _Search_ page. Policy reports that are associated with the severity and have one or more issues appear.
. Select a policy report to view cluster details from the _Clusters_ page. The _Status_ card displays information about _Nodes_, _Applications_, _Policy violations_, and _Identified issues_.
. Select the *Number of identified issues* to view details. The _Identified issues_ card represents the information from Red Hat insights. The _Identified issues_ status displays the number of issues by severity. The triage levels used for the issues are the following severity categories: _Critical_, _Major_, _Low_, and _Warning_.
.. Alternatively, you can select *Clusters* from the navigation menu.
.. Select a managed cluster from the table to view more details. 
.. From the _Status_ card, view the number of identified issues.
. Select the number of potential issues to view the severity chart and recommended remediations for the issues from the _Potential issue_ side panel. You can also use the search feature to search for recommended remediations. The remediation option displays the _Description_ of the vulnerability, _Category_ that vulnerability is associated with, and the _Total risk_.
. Click the link to the vulnerability to view steps on _How to remediate_ and the _Reason_ for the vulnerability.
+
*Note:* When you resolve the issue, you receive the Red Hat Insights every 30 minutes, and Red Hat Insights is updated every two hours.

. Verify which component sent the alert message from the `PolicyReport`. 
.. Navigate to the _Governance_ page and select a specific `PolicyReport`.
.. Select the _Status_ tab and click the *View details* link to view the `PolicyReport` YAML file.
.. Locate the `source` parameter, which informs you of the component that sent the violation. The value options are `grc` and `insights`.

.Additional resources

* xref:../observability/obs_insights_risks_console.adoc#obs-insights-risks-pred[Viewing Red Hat Insights updated risk predictions]
* xref:../observability/obs_insights.adoc#obs-insights[Using observability with Red Hat Insights]