[#enable-mcoa]
= Enabling the multicluster observability add-on

Enable the multicluster observability add-on on your hub cluster to configure your metrics for your platform and user workloads. You are required to enable platform workloads and it is optional to enable user workloads.

When you enable `platform` and `userWorkloads` specifications, the `MultiClusterObservability` operator stops deploying the metrics collectors to your managed clusters and deploys the `multicluster-observability-addon-manager` in the `open-cluster-management-observability` namespace. The `multicluster-observability-addon-manager` deploys the new metrics collectors based on the `PrometheusAgent` resource defined on your hub cluster.

*Required access:* Cluster administrator

.Prerequisites

- You must enable the observability service on your hub cluster. For more details, see xref:../observability/observability_enable.adoc[Enabling the observability service].
- You must install the Red Hat OpenShift Cluster Observability Operator. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_openshift_cluster_observability_operator/1-latest/html-single/about_red_hat_openshift_cluster_observability_operator/index[Cluster Observability Operator overview].

.Procedure

Complete the following steps to enable the multicluster observability add-on on your hub cluster:

. To enable platform monitoring and user workload monitoring, add the `platform` and `userWorkloads` specification to your `MultiClusterObservability` resource. Run the following command:

+
[source,bash]
----
oc patch mco observability -n open-cluster-management-observability --type=merge -p '{"spec":{"capabilities":{"platform":{"metrics":{"default":{"enabled": true}}},"userWorkloads":{"metrics":{"default":{"enabled": true}}}}}}'
----
+
Your `MultiClusterObservability` resource might resemble the following file example:

+
[source,yaml]
----
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  capabilities:
    platform:
      metrics:
        default:
          enabled: true
    userWorkloads:
      metrics:
        default:
          enabled: true
----

. To verify that the default configuration resources for the multicluster observability add-on are created, open your `multicluster-observability-addon` `ClusterManagementAddon` resource. Run the following command:

+
[source,bash]
----
oc get prometheusagents -n open-cluster-management-observability
----

. Verify that the default configurations are added to your placements. Run the following command:

+
[source,bash]
----
oc get cma multicluster-observability-addon -o yaml | yq '.spec.installStrategy.placements'
----
