:_mod-docs-content-type: REFERENCE

[#obs-support]
= Observability support

[role="_abstract"]
Review the support information for the observability service and supported object storage options.

* {acm-short} is tested with and fully supported by Red Hat OpenShift Data Foundation.

* {acm-short} supports the function of the multicluster observability operator on user-provided third-party object storage that is S3 API compatible. The observability service uses Thanos supported, stable object stores.

* {acm-short} support efforts include reasonable efforts to identify root causes. If you open a support ticket and the root cause is the S3 compatible object storage that you provided, then you must open an issue using the customer support channels.

.Additional resources

* xref:../observability/obs_persistent_stores.adoc#obs-persistent-stores[Persistent stores used in the observability service]
* xref:../observability/observability_enable.adoc#enabling-observability-service[Enable the observability service]
* xref:../observability/observability_arch.adoc#observability-arch[Observability architecture]
