:_mod-docs-content-type: PROCEDURE

[#setting-up-grafana-developer-instance]
= Setting up the Grafana developer instance

[role="_abstract"]
Use Grafana dashboards to view hub cluster and managed cluster metrics. The data displayed in the Grafana alerts dashboard relies on `alerts` metrics originating from managed clusters. The `alerts` metric does not affect managed clusters forwarding alerts to the {acm-short} alert manager on the hub cluster. Therefore, the metrics and alerts have distinct propagation mechanisms and follow separate code paths.

Even if you see data in the Grafana alerts dashboard, that does not guarantee that the managed cluster alerts are successfully forwarding to the {acm-short} hub cluster alert manager. If the metrics are propagated from the managed clusters, you can view the data displayed in the Grafana alerts dashboard.

*Required access:* Cluster administrator

.Prerequisites

* You must clone the `multicluster-observability-operator` repository to access the required tools and scripts.

.Procedure

. Clone the `multicluster-observability-operator` repository so that you are able to run the scripts that are in the `tools` folder:

+
[source,bash]
----
git clone https://github.com/open-cluster-management/multicluster-observability-operator.git
cd multicluster-observability-operator/tools
----

. Run the `setup-grafana-dev.sh` script to set up your Grafana instance. When you run the script with the `--deploy` flag, the following resources are created: `secret/grafana-dev-config`, `deployment.apps/grafana-dev`, `service/grafana-dev`, `ingress.extensions/grafana-dev`, and `persistentvolumeclaim/grafana-dev`:

+
[source,bash]
----
./setup-grafana-dev.sh --deploy
----
+
Your output might resemble the following content:

+
[source,bash]
----
secret/grafana-dev-config created
deployment.apps/grafana-dev created
service/grafana-dev created
serviceaccount/grafana-dev created
clusterrolebinding.rbac.authorization.k8s.io/open-cluster-management:grafana-crb-dev created
route.route.openshift.io/grafana-dev created
persistentvolumeclaim/grafana-dev created
oauthclient.oauth.openshift.io/grafana-proxy-client-dev created
deployment.apps/grafana-dev patched
service/grafana-dev patched
route.route.openshift.io/grafana-dev patched
oauthclient.oauth.openshift.io/grafana-proxy-client-dev patched
clusterrolebinding.rbac.authorization.k8s.io/open-cluster-management:grafana-crb-dev patched
----

. Switch your user role to Grafana administrator by using the `switch-to-grafana-admin.sh` script:
.. Select the Grafana URL, `https:grafana-dev-open-cluster-management-observability.{OPENSHIFT_INGRESS_DOMAIN}`, then log in.
.. From the CLI, run the following command to add the logged-in user as a Grafana administrator. For example, log in as the `kubeadmin` by running the following command:

+
[source,bash]
----
./switch-to-grafana-admin.sh kube:admin
----
+
Your output might resemble the following content:

+
[source,bash]
----
User <kube:admin> switched to be grafana admin
----

.Additional resources

* xref:../observability/obs_verify_grafana_version.adoc[Verifying Grafana version]
* xref:../observability/obs_design_grafana_dashboard.adoc#designing-grafana-dashboard[Designing your Grafana dashboard]
* xref:../observability/obs_export_dashboard_configmap.adoc[Exporting Grafana dashboards with a config map]
* xref:../observability/obs_uninstall_grafana_instance.adoc[Uninstalling the Grafana developer instance]