:_mod-docs-content-type: PROCEDURE

[#adding-custom-metrics]
= Adding custom metrics

[role="_abstract"]
To monitor metrics from a remote cluster by using {acm}, check if the metric is exported as a Platform or a User workload metric. Use one of the following three methods to find the metric type:

* Find the metric type in the documentation of the solution you want to monitor.

* Find the metric type by contacting the support for your product.

* Find the metric type by checking the annotation that the `ServiceMonitor` for the observed resource uses.
- Platform metrics use `operator.prometheus.io/controller-id: openshift-platform-monitoring/prometheus-operator`.
- User workload metrics use `operator.prometheus.io/controller-id: openshift-user-workload-monitoring/prometheus-operator`.

You can also find `ServiceMonitors` in the console by going to *Observe* > *Targets* and choosing Platform or User from the *Source* filter in the top right. 

*Note:* The *Source* filter provides service monitor or target information, not a list of metrics.

*Required access:* Cluster administrator

.Procedure

. Add Platform metrics by creating a `ConfigMap` resource on the hub cluster in the `open-cluster-management-observability` namespace. Use `observability-metrics-custom-allowlist` as the name. See the following `ConfigMap` example that you can use to monitor Platform metrics:

+
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-custom-allowlist
  namespace: open-cluster-management-observability
data:
  metrics_list.yaml: |
    names:
      - node_memory_MemTotal_bytes
    recording_rules:
      - record: apiserver_request_duration_seconds:histogram_quantile_90
        expr: histogram_quantile(0.90,sum(rate(apiserver_request_duration_seconds_bucket {job=\"apiserver\", verb!=\"WATCH\"}[5m])) by (verb,le))
----
* *Optional:* Add the names of the custom metrics you want to collect from your managed cluster.
* *Optional:* Add one value for the `expr` and `record` parameter pair to define the query expression.
+
*Note:* The name for the metrics you collect is the same name that you define in your managed cluster `record` parameter. After you run the query expression, you get the metric value results. You can use one section or both sections, which applies to every cluster with monitoring enabled. 

. If you only want to collect custom metrics from a single managed cluster, use the following example and apply the config map on your managed cluster in the `open-cluster-management-addon-observability` namespace:

+
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-custom-allowlist
  namespace: open-cluster-management-addon-observability
data:
  metrics_list.yaml: |
    names:
      - node_memory_MemTotal_bytes
        recording_rules:
      - record: apiserver_request_duration_seconds:histogram_quantile_90
        expr: histogram_quantile(0.90,sum(rate(apiserver_request_duration_seconds_bucket{job="apiserver", verb!="WATCH"}[5m])) by (verb,le))
----
* *Optional:* Add the names of the custom metrics you want to collect from your managed cluster.
* *Optional:* Enter only one value for the `expr` and `record` parameter pair to define the query expression.
+
*Note:* The name for the metrics you collect is the same name that you define in your managed cluster `record` parameter. After you run the query expression, you get the metric value results. You can use one section or both sections.

.Additional resources

* xref:../observability/obs_add_uw_metrics.adoc#add-uw-metrics[Adding user workload metrics]
* xref:../observability/use_observability.adoc[Exporting metrics to external endpoints]
* xref:../observability/dynamic_metrics_sno.adoc[Dynamic metrics for {sno} clusters]
