[#obs-scale-metrics]
= Scaling metrics collection (Technology Preview)

To enhance performance in high-scale deployments, you can configure the `metrics-collector` to collect metrics in parallel with multiple workers. The default configuration uses a single worker to federate metrics. By increasing the number of workers in the metric collection process, you enable internal workers to shard `/federate` endpoint requests that are made to Prometheus on your managed cluster.

*Required access:* Cluster administrator

.Prerequisites

- You have the Observability service enabled on your hub and managed clusters. See xref:../observability/observability_enable.adoc#enabling-observability-service[Enabling the Observability service].

[#inc-dec-metric]
== Increasing and decreasing metrics collection

To increase and decrease metrics collection on your clusters, edit the `workers` parameter in the `multicluster-observability-operator` resource. Complete the following steps:

. If you want to use the same `workers` value for each of your managed clusters, set the value in your `MultiClusterObservability` custom resource definition. By default, the value is set to `1`. For example, change the `workers` parameter value to `4`. Your YAML file might resemble the following resource: 

+
[source,yaml]
----
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  observabilityAddonSpec:
    enableMetrics: true
    workers: 4
----

. *Optional:* If you want to override the `workers` parameter for specific clusters, add the `observability.open-cluster-management.io/addon-source: "override"` annotation to the `ObservabilityAddOn` specification of your managed cluster.
.. To revert the override, use the `observability.open-cluster-management.io/addon-source: "mco"` annotation.

. To verify the value of the `workers` parameter, check the values in the `MultiClusterObservability` custom resource.