:_mod-docs-content-type: PROCEDURE

[#view-explore-data-grafana]
= Viewing and exploring data by using Grafana dashboards

[role="_abstract"]
View the data from your managed clusters by accessing Grafana from the hub cluster. You can query specific alerts and add filters for the query. When you query historical data, manually set your query parameter options to control how much data is displayed from the dashboard.

*Note:* Do not set the `ObservabilitySpec.resources.CPU.limits` parameter if observability is enabled on single node managed clusters. When you set the CPU limits, it causes the observability pod to be counted against the capacity for your managed cluster. See the reference for _Management Workload Partitioning_ in the _Additional resources_ section.

Viewing {acm-short} dashboards::

When you enable the {acm-short} observability service, three dashboards become available. View the following dashboard descriptions:

* _Alert Analysis_: Overview dashboard of the alerts being generated within the managed cluster fleet.
* _Clusters by Alert_: Alert dashboard where you can filter by the alert name.
* _Alerts by Cluster_: Alert dashboard where you can filter by cluster, and view real-time data for alerts that are initiated or pending within the cluster environment.

.Procedure

. Explore the _cluster_infrastructure_provider_ alert from a {sno} cluster, run the following query expression: `cluster_infrastructure_provider{clusterType="SNO"}`

. From your hub cluster, select the *Grafana link* that is in the console header. 

. Edit your cluster dashboard by selecting *Edit Panel*.

. From the Query front-end data source in Grafana, click the _Query_ tab. 

. Select `$datasource`. 

. If you want to see more data, increase the value of the _Step_ parameter section. If the _Step_ parameter section is empty, it is automatically calculated.

. Find the _Custom query parameters_ field and select *`max_source_resolution=auto`*.

. To verify that the data is displayed, refresh your Grafana page.

. View the etcd table from the hub cluster dashboard in Grafana to learn the stability of the etcd as a data store. Select the Grafana link from your hub cluster to view the _etcd_ table data, which is collected from your hub cluster. The _Leader election changes_ across managed clusters are displayed.

. View the Kubernetes API server dashboards to see the total number of clusters that are exceeding or meeting the targeted _service-level objective_ (SLO) value for the past seven or 30-day period, offending and non-offending clusters, and API Server Request Duration.

. View the cluster fleet Kubernetes API service-level overview from the hub cluster dashboard in Grafana:

.. Navigate to the Grafana dashboard.
.. Access the managed dashboard menu by selecting *Kubernetes* > *Service-Level Overview* > *API Server*. The _Fleet Overview_ and _Top Cluster_ details are displayed. 

. View the Kubernetes API service-level overview table from the hub cluster dashboard in Grafana to see the error budget for the past seven or 30-day period, the remaining downtime, and trend. 

.. Navigate to the Grafana dashboard from your hub cluster.
.. Access the managed dashboard menu by selecting *Kubernetes* > *Service-Level Overview* > *API Server*. The _Fleet Overview_ and _Top Cluster_ details are displayed.

. View the {ocp-virt-short} dashboard to see comprehensive insights for each cluster with the {ocp-virt-short} operator installed. The state of the operator is displayed, which is determined by active {ocp-virt-short} alerts and the conditions of the Hyperconverged Cluster Operator. 

. View the number of running virtual machines and the operator version for each cluster. 

. Filter the dashboard by cluster name, operator health alerts, health impact of alerts, and alert severity.
