[#obs-scale-metrics]
= Scaling metrics collection (Technology Preview)

Scale the metrics collection for your clusters to increase or decrease the remote write requests that you receive. When you scale metrics collection, you are controlling the resource capacity for your cluster.

*Required access:* Cluster administrator

.Prerequisistes

- You have the Observability service enabled on your hub and managed clusters.

[inc-dec-metric]
== Increasing and decreasing metrics collection

To increase and decrease metrics collection on your clusters, you must edit the `workers` parameter in the `multicluster-observability-operator` resource. Complete the following steps:

. If you want to use the same `workers` value for each of your managed clusters, set the value in your `MultiClusterObservability` custom resource definition. By default, the value is set to `1`. Run the following example command to edit your `workers` parameter:

+
[source,bash]
----
need command if there is one the user can run
----

. *Optional:* If you want to override the `workers` parameter for specific clusters, add the `observability.open-cluster-management.io/addon-source: "override"` annotation to the `ObservabilityAddOn` specification of your managed cluster.
.. To revert the override, use the `observability.open-cluster-management.io/addon-source: "mco"` annotation.

. To verify the value of the `workers` parameter, check the arguments on the `metrics-collector` pods