:_mod-docs-content-type: PROCEDURE

[#add-uw-metrics]
= Adding user workload metrics

[role="_abstract"]
To collect custom workload metrics from managed clusters, create  `ConfigMap` resource named `observability-metrics-custom-allowlist` in a namespace.

.Procedure

. Set the configuration on the managed cluster in namespace where you want to capture the user workload metrics. The name must be `observability-metrics-custom-allowlist`.

. The following example monitors the User workload metric `sample_metrics` from the namespace `monitored_namespace`. If you create the configuration in the `open-cluster-management-addon-observability` namespace instead, the metrics are collected from all the namespaces of the managed cluster. See the following example:

[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-custom-allowlist
  namespace: <monitored_namespace>
data:
  uwl_metrics_list.yaml:
    names:
      - <sample_metrics>
----
* Add the namespace where you want to capture the metric.
* Add the value of the config map data in YAML format. Add list of metric names that you want to collect from the `test` namespace to the `names` section. After you create the config map, the observability collector collects and pushes the metrics from the target namespace to the hub cluster.

.Additional resources

* xref:../observability/obs_metrics.adoc#adding-custom-metrics[Adding custom metrics]