:_mod-docs-content-type: PROCEDURE

[#obs-insights]
= Using observability with Red Hat Insights

[role="_abstract"]
Red Hat Insights is integrated with {acm-short} observability, and is enabled to help identify existing or potential problems in your clusters. Red Hat Insights helps you to identify, prioritize, and resolve stability, performance, network, and security risks. {ocp} offers cluster health monitoring through Red Hat OpenShift Cluster Manager. Red Hat OpenShift Cluster Manager collects anonymized, aggregated information about the health, usage, and size of the clusters. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_lightspeed/1-latest[Red Hat Lightspeed product documentation].

When you create or import an OpenShift cluster, anonymized data from your managed cluster is automatically sent to Red Hat. This information is used to create insights, which provide cluster health information. {acm-short} administrator can use this health information to create alerts based on severity.

*Required access*: Cluster administrator

.Prerequisites

* Ensure that Red Hat Insights is enabled. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_lightspeed/1-latest/html-single/connecting_your_rhel_systems_through_the_red_hat_lightspeed_proxy/index#connecting-through-your-own-proxy[Connecting to Red Hat Lightspeed through your own proxy].
* Install a supported version of {ocp-short}.
* Hub cluster user, who is registered to Red Hat OpenShift Cluster Manager, must be able to manage all the {acm-short} managed clusters in Red Hat OpenShift Cluster Manager.

*Important:* {acm} `PolicyReports` are violations that are generated by the `insights-client`. The `PolicyReports` are used to define and configure alerts that are sent to incident management systems. When there is a violation, alerts from a `PolicyReport` are sent to incident management system.

.Procedure

. To search for insight policy reports, log in to your {acm-short} hub cluster.
. Select *Search* from the navigation menu.
. Enter the following query: `kind:PolicyReport`.
+
*Note:* The `PolicyReport` name matches the name of the cluster. 

. Specify your query with the insight policy violation and categories. When you select a `PolicyReport` name, you are redirected to the _Details_ page of the associated cluster. The _Insights_ sidebar is automatically displayed. 

. If the search service is disabled and you want to search for an insight, run the following command from your hub cluster:

+
[source,bash]
----
oc get policyreport --all-namespaces
----

.Additional resources

* xref:../observability/obs_view_insights_issues_console.adoc#view-issues-console[Viewing identified Red Hat Insights issues from the console]
* xref:../observability/obs_insights_risks_console.adoc#obs-insights-risks-pred[Viewing Red Hat Insights updated risk predictions]
* xref:../observability/customize_observability.adoc[Configuring Alertmanager]
* xref:../observe_environments_intro.adoc#observing-environments-intro[Observability service]