:_mod-docs-content-type: PROCEDURE

[#config-right-size-virt]
= Configuring _RightSizingRecommendation_ for Virtualization

[role="_abstract"]
You can customize the `RightSizingRecommendation` specification to optimize CPU and memory resources for your virtual machines. Edit the `MultiClusterObservability` resource.

.Prerequisites

- You have enabled the `RightSizingRecommendation` specification. For more information, see xref:../obs_right_size_virt.adoc[Enabling _RightSizingRecommendation_ for Virtualization workloads].

.Procedure

. Configure placement for your virtual machines by editing the `rs-virt-config` `ConfigMap` resource and defining the `placementConfiguration` parameter. Customize your placement to where the policy only applies to clusters with the `environment=prod` label, as displayed in the following example:

+
[source,yaml]
----
placementConfiguration: |
 spec:
   . . .
   predicates:
   - requiredClusterSelector:
       labelSelector:
         matchLabels:
           environment: prod
   . . .
----

. Configure `PrometheusRule` for your virtual machines by completing one of the following steps:

.. Define the namespaces that you want to include or exclude in the `namespaceFilterCriteria` specification.

.. Add a list of namespaces that you want to include in the `inclusionCriteria` specification.

.. Add a list of namespaces that you want to exclude in the `exclusionCriteria` specification.

+
*Note:* You cannot use both `inclusionCriteria` and `exclusionCriteria` at the same time.

.. To adjust the CPU and memory percentages, define the percentage usage.

+
See the following example where the `inclusionCriteria` specification includes `prod` and the `exclusionCriteria` excludes `openshift`:

+
[source,yaml]
----
. . .
  prometheusRuleConfig: |
   namespaceFilterCriteria:
    inclusionCriteria:
    - prod.*
    exclusionCriteria:
    - openshift.*
  labelFilterCriteria:
  - labelName: label_kubernetes_io_metadata_name
    inclusionCriteria:
    - prod
    - staging
    exclusionCriteria:
    - kube.*
  recommendationPercentage: 120
  . . .
----

. Configure your namespace binding. By default, the `RightSizingRecommendation` feature uses the `open-cluster-management-global-set` namespace for binding policies to clusters.

.. To bind generated policies to a different namespace and cluster set, use the `namespaceBinding` property. *Important:* Ensure that the target namespace is part of a valid `ClusterSet` before you apply the change. The policies that you generate might not apply to any clusters if there is no valid binding.

+
See the following example where the `<your-namespace-binding>` namespace is the value for `namespaceBinding`:

+
[source,yaml]
----
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  . . .
  capabilities:
    platform:
      analytics:
        virtualizationRightSizingRecommendation:
          enabled: true
          namespaceBinding: <your-namespace-binding>
  . . .
----
*Important:* Ensure that the target namespace is part of a valid `ClusterSet` before you apply the change. The policies that you generate might not apply to any clusters if there is no valid binding.
