[#config-right-size-virt]
= Configuring right-sizing for Virtualization (Technology Preview)

You can customize right-sizing for virtual machines by editing the `MultiClusterObservability` resource.

.Prerequisites

- You have enabled right-sizing guides for Virtualization.

[#config-right-size-placement-virt]
== Configuring placement for Virtualization

You can customize the placement configuration by making changes to the `placementConfiguration` property in the `rs-virt-config` `ConfigMap` resource.

See the following example where the policy only applies to clusters with the `environment=prod` label:

[source,yaml]
----
placementConfiguration: |
 spec:
   . . .
   predicates:
   - requiredClusterSelector:
       labelSelector:
         matchLabels:
           environment: prod
   . . .
----

[#config-right-size-prometheus-virt]
== Configuring `PrometheusRule` for Virtualization

You can customize the `PrometheusRule` resource by making changes to one of the following properties:

`namespaceFilterCriteria`:: Limit guides to specific namespaces. You can include or exclude this property.
`labelFilterCriteria`:: Filter namespaces with custom labels.
`recommendationPercentage`:: Adjust CPU and memory guide percentages.

See the following example:

[source,yaml]
----
. . .
  prometheusRuleConfig: |
   namespaceFilterCriteria:
    inclusionCriteria: <1>
    - prod.*
    exclusionCriteria: <2>
    - openshift.*
  labelFilterCriteria:
  - labelName: label_kubernetes_io_metadata_name
    inclusionCriteria:
    - prod
    - staging
    exclusionCriteria:
    - kube.*
  recommendationPercentage: 120 <3>
  . . .
----
<1> Use `inclusionCriteria` to filter namespaces that you want to include.
<2> Use `exclusionCriteria` to filer namespaces that you want to exclude.
+
*Note:* You cannot use both `inclusionCriteria` and `inclusionCriteria` at the same time.
<3> Set the percentage of actual usage.

[#config-right-size-namespace-virt]
== Configuring namespace binding for Virtualization

By default, the right-sizing feature uses the `open-cluster-management-global-set` namespace for binding policies to clusters.

To bind generated policies to a different namespace and cluster set, use the `namespaceBinding` property. See the following example:

[source,yaml]
----
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  . . .
  capabilities:
    platform:
      analytics:
        virtualizationRightSizingRecommendation:
          enabled: true
          namespaceBinding: <your-namespace-binding>
  . . .
----
*Important:* Ensure that the target namespace is part of a valid `ClusterSet` before you apply the change. The policies that you generate might not apply to any clusters if there is no valid binding.