:_mod-docs-content-type: PROCEDURE

[#silence-alerts]
= Silencing alerts

[role="_abstract"]
Add alerts that you do not want to receive. You can silence alerts by the alert name, match label, or time duration. After you add the alert that you want to silence, an ID is created. Your ID for your silenced alert might resemble the following string, `d839aca9-ed46-40be-84c4-dca8773671da`.

.Procedure

. To silence a {acm-short} alert, you must have access to the `alertmanager` pods in the `open-cluster-management-observability` namespace. Run the following command in the `observability-alertmanager-0` pod terminal to silence `SampleAlert`: 

+
[source,bash]
----
amtool silence add --alertmanager.url="http://localhost:9093" --author="user" --comment="Silencing sample alert" alertname="SampleAlert"
----

. Silence an alert by using multiple match labels. The following command uses `match-label-1` and `match-label-2`:

+
[source,bash]
----
amtool silence add --alertmanager.url="http://localhost:9093" --author="user" --comment="Silencing sample alert" <match-label-1>=<match-value-1> <match-label-2>=<match-value-2>
----

. If you want to silence an alert for a specific period of time, use the `--duration` flag. Run the following command to silence the `SampleAlert` for an hour:

+
[source,bash]
----
amtool silence add --alertmanager.url="http://localhost:9093" --author="user" --comment="Silencing sample alert" --duration="1h" alertname="SampleAlert"
----

. Define a start or end time for the silenced alert. Run the following command to silence the `SampleAlert` at a specific start time:

+
[source,bash]
----
amtool silence add --alertmanager.url="http://localhost:9093" --author="user" --comment="Silencing sample alert" --start="2023-04-14T15:04:05-07:00" alertname="SampleAlert"
----

. To view all silenced alerts that are created, run the following command:

+
[source,bash]
----
amtool silence --alertmanager.url="http://localhost:9093"
----

. If you no longer want to silence an alert, end the silencing by running the following command:

+
[source,bash]
----
amtool silence expire --alertmanager.url="http://localhost:9093" "d839aca9-ed46-40be-84c4-dca8773671da"
----

. To end the silencing of all alerts, run the following command:

+
[source,bash]
----
amtool silence expire --alertmanager.url="http://localhost:9093" $(amtool silence query --alertmanager.url="http://localhost:9093" -q) 
----