:_mod-docs-content-type: PROCEDURE

[#obs-disable-alert-forwarding]
= Disabling alert forwarding for managed clusters

[role="_abstract"]
To disable alert forwarding for managed clusters, add the `mco-disable-alerting: "true"` annotation to the `MultiClusterObservability` custom resource. When you set the `mco-disable-alerting: "true"` annotation, both the platform and user workload alerts are not forwarded to the Alertmanager on your hub cluster. The forwarding configuration on your managed clusters is reverted.

Configuration updates to the `cluster-monitoring-config` config map in the `openshift-monitoring` namespace are reverted. Setting the annotation ensures that the `cluster-monitoring-config` config map is not managed or updated by the observability operator endpoint. After you update the configuration, both platform and user workload Prometheus instances on your managed cluster restarts. Complete the following steps:

When the changes are reverted, a config map named `cluster-monitoring-reverted` is created in the `open-cluster-management-addon-observability` namespace. Any new, alert forward configurations that are manually added are not reverted from the config map.

.Procedure

. Run the following command to  set the `mco-disable-alerting` annotation to `"true"`:

+
[source,bash]
----
oc annotate MultiClusterObservability observability mco-disable-alerting=true
----
+
*Important:* You lose metrics when Prometheus on your managed cluster is not configured with a persistent volume.

. Verify that the hub cluster alert manager is no longer propagating managed cluster alerts to third-party messaging tools.