:_mod-docs-content-type: PROCEDURE

[#disable-obs]
= Disabling observability

[role="_abstract"]
You can disable observability to stop data collection on the {acm-short} hub cluster. Disable observability by removing observability components on all managed clusters.

.Procedure

. Update the `multicluster-observability-operator` resource by setting `enableMetrics` to `false`. Your updated resource might resemble the following change:

[source,yaml]
----
spec:
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
  observabilityAddonSpec:
    enableMetrics: false
  workers: 1 
----
* Use the `observabilityAddonSpec` parameter to define the global settings for all managed clusters that have the observability add-on enabled.
* Use the `enableMetrics` parameter to indicate that the observability add-on is enabled to push metrics to hub cluster server.

. Disable observability on a single cluster.

.. Add the `observability: disabled` label to the `managedclusters.cluster.open-cluster-management.io` custom resource.

.. From the {acm-short} console _Clusters_ page, add the `observability=disabled` label to the specified cluster.
+
*Note:* When a managed cluster with the observability component is detached, the `metrics-collector` deployments are removed.

. Remove observability to disable and uninstall the observability service.

.. From the {ocp-short} console navigation, select *Operators* > *Installed Operators* > *Advanced Cluster Manager for Kubernetes*. 

.. Click *Remove* for the `MultiClusterObservability` custom resource.
