:_mod-docs-content-type: PROCEDURE

[#config-proxy-obs]
= Configuring proxy settings for observability add-ons

[role="_abstract"]
Configure the proxy settings to allow the communications from the managed cluster to access the hub cluster through a HTTP and HTTPS proxy server. Typically, add-ons do not need any special configuration to support HTTP and HTTPS proxy servers between a hub cluster and a managed cluster. But if you enabled the observability add-on, you must complete the proxy configuration.

.Prerequisites

- You have a hub cluster. 
- You have enabled the proxy settings between the hub cluster and managed cluster.

.Procedure

. Configure proxy settings by navigating to the cluster namespace on your hub cluster. 
. Create an `AddOnDeploymentConfig` resource with the proxy settings by adding a `spec.proxyConfig` parameter. View the following YAML example:

+
[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: <addon-deploy-config-name>
  namespace: <managed-cluster-name>
spec:
  agentInstallNamespace: open-cluster-management-addon-observability
  proxyConfig:
    httpsProxy: "http://<username>:<password>@<ip>:<port>"
    noProxy: ".cluster.local,.svc,172.30.0.1"
----
* For the `httpsProxy` parameter, specify either a HTTP proxy or a HTTPS proxy.
* For the `noProxy` parameter, include the IP address of the `kube-apiserver`. 

. To get the IP address, run following command on your managed cluster: 

+
[source,bash]
----
oc -n default describe svc kubernetes | grep IP:
----
 
. Go to the `ManagedClusterAddOn` resource and update it by referencing the `AddOnDeploymentConfig` resource that you made. View the following YAML example:

+
[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: observability-controller
  namespace: <managed-cluster-name>
spec:
  installNamespace: open-cluster-management-addon-observability
  configs:
  - group: addon.open-cluster-management.io
    resource: addondeploymentconfigs
    name: <addon-deploy-config-name>
    namespace: <managed-cluster-name> 
----
+
*Note:* The `spec.installNamespace` field is deprecated. See link:../clusters/release_notes/mce_deprecate_remove.adoc#mce-deprecation-removal[Product deprecations and removals] to learn more.

. Verify the proxy settings. If you successfully configured the proxy settings, the metric collector deployed by the observability add-on agent on the managed cluster sends the data to the hub cluster. Complete the following steps:

.. Go to the hub cluster then the managed cluster on the Grafana dashboard. 
.. View the metrics for the proxy settings. 

== Disabling proxy settings for observability add-ons

[role="_abstract"]
If your development needs change, you might need to disable the proxy setting for the observability add-ons you configured for the hub cluster and managed cluster. You can disable the proxy settings for the observability add-on at any time.

//.Procedure

. Go to the `ManagedClusterAddOn` resource.
. Remove the referenced `AddOnDeploymentConfig` resource.
