[#obs-mcoa-intro]
= Multicluster observability add-on

Use the multicluster observability add-on to configure metrics collection by using names, matchers, and recording rules for both platform and user workloads. Edit your `ClusterManagementAddOn` resource, scale metric federation, and improve peformance and reduce data loss during network partitions between your managed and hub clusters.

== Managed cluster workloads

Managed cluster monitoring workloads use the Prometheus Operator and Prometheus Agent from the cluster observability operator. This integration provides the following benefits:

- Consistent lifecycle management for Prometheus components across managed clusters.
- Built-in configuration hooks and custom resources tailored for multicluster operation.
- A lightweight Prometheus Agent deployment model for remote-write scenarios.

The multicluster observability add-on utilizes the existing `obo-prometheus-operator` from Red Hat OpenShift Cluster Observabililty Operator on a managed cluster to reconcile Prometheus custom resources. If `obo-prometheus-operator` is not present, the multicluster observability add-on deploys `obo-prometheus-operator` within the configured `agentInstallNamespace`.

Both of the multicluster observability add-on and Cluster Observabililty Operator share the `monitoring.rhobs` API Group for the `ScrapeConfig` and `PrometheusAgent` resources.

For other managed clusters that are not OpenShift clusters, the following resources are deployed:

- Node exporter
- Kube state metrics
- Prometheus server

*Note:* The cluster ID of other managed clusters now use the `id.k8s.io` claim of the managed cluster while the current endpoint operator uses the cluster name.

== Configurable APIs

Control monitoring behavior on your managed clusters by configuring default resource configurations. The following default resources are required: `PrometheusAgent`, `ScrapeConfig`, and `PrometheusRule`. View the following descriptions of each API:

`PrometheusAgent`:: Defines an agent-focused Prometheus deployment optimized for remote-write workflows. Configures remote-write targets, scrape intervals, and resource limits. Use the `PrometheusAgent` resource to be your metrics collector.

`ScrapeConfig`:: Declarative scrape definitions for targets and discovery mechanisms. Configure `job_name`, `metrics_path`, `scheme`, `relabel_configs`, and TLS settings.

`PrometheusRule`:: Supports alerting and recording rule definitions that you can apply for each cluster or each tenant. Supports groups of rules with evaluation intervals and alert annotations or labels.

`ClusterManagementAddOn`:: Resources can include an `AddonDeploymentConfig` to customize the deployment of the multicluster observability add-on on managed clusters. You can use this configuration to set resource requests and limits for the Prometheus Agent pods deployed on managed clusters.

+
*Note:* A single `AddonDeploymentConfig` resource is used for all placements. 

== Default platform metrics

By default, the multicluster observability add-on collects platform metrics from your managed clusters. There are a set of `ScrapeConfig` resources that are automatically generated and deployed to all of your managed clusters. All placements that you reference within the `ClusterManagementAddOn` resource automatically receive the `ScrapeConfig` configurations.

The following default platform metrics are collected:

- `platform-metrics-hcp`, which is specific for the {hcp} platform
- `platform-metrics-virtualization`, which is specific for the {ocp-virt} platform
- `platform-metrics-alerts`, which is specific for custom alert rule metrics across all platforms
- `platform-metrics-default`, which is specific for default metrics across all platfroms

== Health status of the multicluster observability add-on

The multicluster observability add-on health status is reported through the `ManagedClusterAddOn` resource. From the {ocp} consolefor each managed cluster, the `ManagedClusterResource` is displayed in the _All Clusters_ view. The status is degraded if some resources are not deployed or the platform `PrometheusAgent` resource is not running.

The following alerting rules are pushed to all managed clusters:

`MetricsCollectorNotIngestingSamples`:: Alerts you when the `PrometheusAgent` resource is not federating any metrics.
`MetricsCollectorRemoteWriteFailures`:: Alerts you when there is a high failure rate for remote-write requests in the `PrometheusAgent` resource of your hub cluster.
`MetricsCollectorRemoteWriteBehind`:: Alerts you when the `PrometheusAgent` resource remote-write is too slow.

== Additional resources

- xref:../observability/obs_enable_mcoa.adoc#enable-mcoa[Enabling the multicluster observability add-on]
- xref:../observability/obs_mcoa_config_apis.adoc#config-apis-mcoa[Configuring APIs for the multicluster obsservability add-on]
- xref:../observability/obs_mcoa_add_custom_metrics.adoc#add-custom-metrics-mcoa[Adding custom metrics for the multicluster observability add-on]
- xref:../observability/obs_mcoa_federate.adoc#federate-uw[Federating user workloads from Cluster Observability Operator]
- xref:../observability/obs_mcoa_relabel.adoc#relabeling-mcoa-default-metrics[Relabeling default metrics for the multicluster observability add-on]
- xref:../observability/export_metrics_external.adoc#export-metrics-external[Exportng metrics to external endpoints for the multicluster observability add-on]

//- Alert forwarding for MCOA | Handling this topic in a separate PR, ACM-23758

