:_mod-docs-content-type: PROCEDURE

[#create-mco-resource]
= Creating the _MultiClusterObservability_ custom resource

[role="_abstract"]
Create the `MultiClusterObservability` custom resource to define the persistent volume storage sizes for various components. You must set the storage size during the initial creation of the `MultiClusterObservability` custom resource. Post-deployment changes take effect only if the storage class supports dynamic volume expansion.

.Procedure

. Create the `MultiClusterObservability` custom resource YAML file named `multiclusterobservability_cr.yaml`. View the following default YAML file for observability:

+
[source,yaml]
----
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  observabilityAddonSpec: {}
  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
----
+
*Note:* You might want to modify the value for the `retentionConfig` parameter in the `advanced` section. Depending on the number of managed clusters, you might want to update the amount of storage for stateful sets. If your S3 bucket is configured to use STS tokens, annotate the service accounts to use STS with S3 role. View the following configuration:

+
[source,yaml]
----
spec:
  advanced:
    compact:
       serviceAccountAnnotations:
           eks.amazonaws.com/role-arn: $S3_ROLE     
    store:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: $S3_ROLE       
    rule:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: $S3_ROLE
    receive:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: $S3_ROLE
    query:
       serviceAccountAnnotations:
          eks.amazonaws.com/role-arn: $S3_ROLE 
----
+
For more information, use the _API Explorer_ in the console, or an `oc` command.

. To deploy on infrastructure machine sets, you must set a label for your set by updating the `nodeSelector` in the `MultiClusterObservability` YAML file. Your YAML file might resemble the following content:

+
[source,yaml]
----
  nodeSelector:
    node-role.kubernetes.io/infra: ""
----

. Apply the observability YAML to your cluster by running the following command:

+
[source,bash]
----
oc apply -f multiclusterobservability_cr.yaml
----

+
*Note:* By default, if you do not define the `storageConfig.storageClass` field in the `MultiClusterObservability` custom resource, platform default `StorageClass` fields are populated in the `storageConfig` section of the `MultiClusterObservability` resource. For example, AWS default `storageClass` is set to `gp2`. 

. Verify default `storageClass` by running the following command:
 
+
[source,bash] 
----
oc get storageClass
----

+
See the following example output:

+
[source,bash] 
----
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   151m
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   151m
----

. Validate that the observability service is enabled and the data is populated by launching the Grafana dashboards. 

. Click the *Grafana link* that is near the console header, from either the console _Overview_ page or the _Clusters_ page.
 
. Access the `multicluster-observability-operator` deployment to verify that the `multicluster-observability-operator` pod is being deployed by the `multiclusterhub-operator` deployment. Run the following command:

+
[source,bash]
----
oc get deploy multicluster-observability-operator -n open-cluster-management --show-labels
----
+
You might receive the following results:

+
----
NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE   LABELS
multicluster-observability-operator   1/1     1            1           35m   installer.name=multiclusterhub,installer.namespace=open-cluster-management
----

. View the `labels` section of the `multicluster-observability-operator` deployment for labels that are associated with the resource. The `labels` section might contain the following details:

+
[source,yaml]
----
 labels:
    installer.name: multiclusterhub
    installer.namespace: open-cluster-management
----

. *Optional:* Add the `observability: disabled` cluster label to your clusters if you want to exclude specific managed clusters from collecting the observability data. 

.Additional resources

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/storage/expanding-persistent-volumes[Expanding persistent volumes from the {ocp} documentation]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html-single/machine_management/index#creating-infrastructure-machinesets[Creating infrastructure machine sets]
* link:https://thanos.io/v0.8/components/compact/#downsampling-resolution-and-retention[Thanos Downsampling resolution and retention]
