:_mod-docs-content-type: CONCEPT

[#obs-open-source-components]
= Observability open source components

[role="_abstract"]
The observability service uses open source observability tools from the community. Review the following descriptions of the tools that are part of the product observability service.

Thanos:: A toolkit of components that you can use to perform global querying across multiple Prometheus instances. For long-term storage of Prometheus data, persist it in any S3-compatible storage. You can also compose a highly available and scalable metrics system.

Prometheus:: A monitoring and alerting tool that you can use to collect metrics from your application and store these metrics as time-series data. Store all scraped samples locally, run rules to aggregate and record new time series from existing data, and generate alerts.

Alertmanager:: A tool to manage and receive alerts from Prometheus. Deduplicate, group, and route alerts to your integrations such as email, Slack, and PagerDuty. Configure Alertmanager to silence and inhibit specific alerts.

.Additional resources

* xref:../observability/observability_arch.adoc#observability-arch[Observability architecture]
* xref:../observability/obs_component_versions.adoc#obs-component-versions[Observability component versions]
* link:https://thanos.io/v0.36/thanos/getting-started.md/[Thanos documentation]
* link:https://prometheus.io/docs/introduction/overview/[Prometheus Overview]
* link:https://prometheus.io/docs/alerting/latest/alertmanager/[Alertmanager documentation]
