[#optimize-work-right-size]
= Optimizing workloads by using right-sizing guides for namespaces (Technology Preview)

You can implement right-sizing by enabling the feature in the `MultiClusterObservability` custom resource on the hub cluster. Enable right-sizing recommendations for your namespaces.

*Required access:* Editor

.Prerequisites

- The multicluster observability operator is enabled on the hub cluster.
- *Required access:* Editor

[#enable-right-size-prereq]
== Enabling right-sizing for namespaces (Technology Preview)

Complete the following steps to enable right-sizing:

. Open the observability instance configuration. Run the following command:

+
[source,bash]
----
oc edit multiclusterobservability observability
----

. Add the following lines to the `spec` section of your `MultiClusterObservability` custom resource:

+
[source,yaml]
----
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  capabilities:
    platform:
      analytics:
        namespaceRightSizingRecommendation:
          enabled: true
. . .
----
+
You can set `enabled:` to `false` to disable right-sizing.

After enabling right-sizing, the following resources are created automatically:

The `rs-namespace-config` `ConfigMap`:: Stores configurations for placement and `PrometheusRule`.
The `rs-prom-rules-policy` `Policy`:: Contains the Prometheus rules to evaluate resource usage.
The 
The `rs-placement` `Placement`:: Determines target clusters based on label selectors.
The 
The `rs-policyset-binding` `PlacementBinding`:: Binds the policy and placement together.

. View right-sizing guides by accessing *RightSizing Recommendation* > *ACM Right-Sizing Namespace* from your Grafana dashboard.
.. To view the aggregated data on Grafana, expand or collapse the dashboard by clicking the drop-down arrow. For example, expand the memory data by clicking the name of the dashboard.
