[#install-observability]
= Install observability service

Monitor the health of your managed clusters with the observability service (`multicluster-observability-operator`). 

//should add how users can install on a high availability environment vs. standard. seems like it is a easy //change. According to the google doc, the user would update the AvailabilityConfig parameter from High to //Basic and vice versa 

*Required access:* Cluster administrator

*Prerequisites*:

- You must have {product-title} hub cluster installed as a managed cluster to use the observability feature. 
- You must install Grafana. For more information, see https://grafana.com/docs/grafana/latest/installation/[Install Grafana].
- You must have data storage for the time series data. Configure your object store to create a storage solution. For example, Thanos can be used as a storage solution. Your object storage might resemble the following information:
+
----
type: s3
config:
  bucket: YOUR-BUCKET
  endpoint: S3-ENDPOINT
  insecure: true
  access_key: ACCESS_KEY
  secret_key: SECRET_KEY
----
+
For more information, see  _Object Storage_ in the https://thanos.io/tip/thanos/storage.md/#configuration[Thanos documentation]. 
- {ocp} must be installed. For more information, see https://docs.openshift.com/container-platform/4.5/architecture/architecture-installation.html[{ocp-short} installation overview].


[#enablement-for-observability]
== Enablement for observability

Enable the observability service by creating a `multicluster-observability` CustomResourceDefinition (CRD). Complete the following steps to enable the observability service: 

. Log in to your {product-title-short} hub cluster. 

. Create a namespace for the observability service with the following commad:

+
----
oc create-namespace open-cluster-management-observability
----

. Generate a pull-secret for the `observability` namespace by running the following command:
//--export flag is expected to be deprecated, command might need to be updated
+
----
oc get secret multiclusterhub-operator-pull-secret -n open-cluster-management --export -o yaml |   kubectl apply --namespace=open-cluster-management-observability -f -
----

. Create a secret for your object storage. Your secret must contain the credentials to your storage solution. For example, if you are using Thanos, run the following command:

+
----
kubectl create -f thanos-object-storage.yaml
----
+
Your secret might resemble the following file:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: YOUR_S3_BUCKET
      endpoint: YOUR_S3_ENDPOINT
      insecure: false
      access_key: YOUR_ACCESS_KEY
      secret_key: YOUR_SECRET_KEY

----

. Create a `MultiClusterObservability` CRD by running the following command:

+
----
kubectl create -f mco_cr.yaml
----
+
Your `MultiClusterObservability` CRD might resemble the following file:
+
----
apiVersion: observability.open-cluster-management.io/v1beta1
kind: MultiClusterObservability
metadata:
 name: observability
spec:
 storageConfigObject:
   metricObjectStorage:
     name: thanos-object-storage
     key: thanos.yaml
----

. Apply the observability YAML to your cluster by running the following command:
+
----
oc apply -f multiclusterobservability_cr.yaml
----

[#disable-observability]
== Disable observability 

Disable the observability service by scaling the `metrics-collector` deployment to zero. When the deployment is scaled to zero, data is no longer collected from Promethus.


//still working to add steps

[#uninstall-observability]
== Uninstall observability

Uninstall the observability service to 
//5236


