[#install-observability]
= Install observability service

Monitor the health of your managed clusters with the observability service (`multicluster-observability-operator`).

*Required access:* Cluster administrator

*Prerequisites*:

- You must install {ocp}. For more information, see https://docs.openshift.com/container-platform/4.5/architecture/architecture-installation.html[{ocp-short} installation overview]. 
- You must install {product-title}. See link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online] for more information.  
- You must have data storage for the time series data. Configure your object store to create a storage solution. For example, Thanos can be used as a storage solution. Your object storage might resemble the following information:
+
----
type: s3
config:
  bucket: YOUR-BUCKET
  endpoint: S3-ENDPOINT
  insecure: true
  access_key: ACCESS_KEY
  secret_key: SECRET_KEY
----
+
For more information, see  _Object Storage_ in the https://thanos.io/tip/thanos/storage.md/#configuration[Thanos documentation].
+
*Note*: If there is no object storage defined, the component installation might be stuck with the `Installing` status displayed. See link:../troubleshooting/trouble_observability.adoc#troubleshooting-observability[Troubleshooting observability] for more information.

[#enablement-for-observability]
== Enablement for observability

Enable the observability service by creating a MultiClusterObservability CustomResource (CR) instance. Complete the following steps to enable the observability service: 

. Log in to your {product-title-short} hub cluster. 
. Verify that the observaility components are installed:
.. For the `multicluster-observability-operator`, run the following command:
+
----
kubectl get pods -n open-cluster-management|grep observability
----

. Create a namespace for the observability service with the following commad:
+
----
oc create-namespace open-cluster-management-observability
----

. Generate a pull-secret for the `open-cluster-management-observability` namespace by running the following command:

+
----
oc get secret multiclusterhub-operator-pull-secret -n open-cluster-management --export -o yaml |  kubectl apply --namespace=open-cluster-management-observability -f -
----

. Create a secret for your object storage. Your secret must contain the credentials to your storage solution. For example, if you are using Thanos, run the following command:

+
----
kubectl create -f thanos-object-storage.yaml
----
+
Your secret might resemble the following file:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: YOUR_S3_BUCKET
      endpoint: YOUR_S3_ENDPOINT
      insecure: false
      access_key: YOUR_ACCESS_KEY
      secret_key: YOUR_SECRET_KEY

----

. Create a `MultiClusterObservability` resource for your managed cluster by running the following command:
+
Your `MultiClusterObservability` resource might resemble the following file:
+
----
apiVersion: observability.open-cluster-management.io/v1beta1
kind: MultiClusterObservability
metadata:
  name: observability #Your customized name of MulticlusterObservability CR
spec:
  availabilityConfig: High # Available values are High or Basic
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
  observabilityAddonSpec: # The ObservabilityAddonSpec defines the global settings for all managed clusters which have observability add-on enabled
    enableMetrics: true # EnableMetrics indicates the observability addon push metrics to hub server
    interval: 60 # Interval for the observability addon push metrics to hub server
  retentionResolution1h: 30d # How long to retain samples of 1 hour in bucket
  retentionResolution5m: 14d
  retentionResolutionRaw: 5d
  storageConfigObject: # Specifies the storage to be used by Observability
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
    statefulSetSize: 10Gi # The amount of storage applied to the Observability stateful sets, i.e. Thanos store, Rule, compact and receiver.
    statefulSetStorageClass:gp2
----

. Apply the observability YAML to your cluster by running the following command:
+
----
oc apply -f multiclusterobservability_cr.yaml
----
+
Based on the previous resource example, all of the pods in your `open-cluster-management-observability` namespace for Thanos, Grafana, and AlertManager are automatically installed after you install observability.

. View the installation status of the observability service for each managed cluster by running the following command:
+
----
oc get managedclusteraddon -n local-cluster observability-controller -o yaml
----
+
Your output might resemble the following resource:
+
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  creationTimestamp: "2020-10-19T19:19:32Z"
  generation: 1
  name: observability-controller
  namespace: local-cluster
  resourceVersion: "30409880"
  selfLink: /apis/addon.open-cluster-management.io/v1alpha1/namespaces/self/managedclusteraddons/observability-controller
  uid: ae1dacb7-4fe6-4abd-bef0-e479b6f44157
spec: {}
status:
  addOnConfiguration:
    crName: ""
    crdName: ""
  addOnMeta:
    description: ""
    displayName: ""
  conditions:
  - lastTransitionTime: "2020-10-22T14:10:55Z"
    message: Metrics collector deployed and functional
    reason: Deployed
    status: "True"
    type: Available
  - lastTransitionTime: "2020-10-22T14:10:55Z"
    message: enableMetrics is set to False
    reason: Disabled
    status: "False"
    type: Disabled
  - lastTransitionTime: "2020-10-22T14:10:55Z"
    message: Metrics collector deployment not successful
    reason: Degraded
    status: "False"
    type: Degraded
----

== Uninstall observability

Uninstall the observability service by completing the following steps:

. Log in to your hub cluster.
. Delete the `MultiClusterObservability` resource with the following command:
+
----
kubectl delete multicluster-observability-operator
----
+
When you delete the resource, the pods in the `open-cluster-management-observability` namespace on {product-title-short} hub cluster, and the pods in `open-cluster-management-addon-observability` namespace on all managed clusters are removed. 

*Important*:

- You must delete the observability service before you uninstall {product-title}.
- Your object storage is not effected after you uninstall the observability service.

Learn more on how to manage the observability service, see xref:../observability/manage_observe#managing-observability[Managing observability].


