[#observing-environments-intro]
= Observability service introduction
//Need to also complete modular effort | MJ | 05/02/23

The observability component is a service you can use to understand the state of your clusters. The observability service is deployed by the `multiclusterhub-operator` pod, which is complete during the {product-title-short} installation. By default, observability is enabled on your hub cluster.
//does it make sense to have the support section here? 
[#observability-support]
== Support

- {product-title-short} is tested with and fully supported by Red Hat OpenShift Data Foundation (formerly Red Hat OpenShift Container Storage). 

- {product-title-short} supports the function of the multicluster observability operator on user-provided third-party object storage that is S3 API compatible. The observability service uses Thanos supported, stable object stores.

- {product-title-short} use commercial, reasonable efforts to assist in the identification of the root cause. If a support ticket is raised and the root cause has been determined to be a result of the customer-provided S3 compatible object storage, then the issue must be resolved using the customer support channels.

- {product-title-short} does not commit to fix support tickets raised by customers, where the root cause identified is the S3 compatible object storage provider.

Read the following documentation for more details about the observability component:

* xref:../observability/observability_arch.adoc#observability-arch[Observability architecture]
* xref:../observability/observe_environments.adoc#observing-environments[Observing environments]
* xref:../observability/search_intro.adoc#searching-in-the-console-intro[Searching in the console introduction]
* xref:../observability/insights_intro.adoc#using-rh-insights[Using observability with Red Hat Insights]




 