[#observing-environments]
= Observing environments

You can use {product-title} to gain insight and optimize metrics from your clusters. Enable the observability service operator, `multicluster-observability-operator`, to monitor the health of your managed clusters. 

[#observability-service]
== Observability service

By default, observability is included with the product installation, but not enabled. Observability is disabled because an object store is required for the time series data. {product-title-short} supports the following stable object stores:

- link:https://docs.aws.amazon.com/whitepapers/latest/aws-overview/storage-services.html[Amazon S3] (or other S3 compatible object stores like Ceph)
- link:https://cloud.google.com/storage/docs/introduction[Google Cloud Storage]
- link:https://docs.microsoft.com/en-us/azure/storage/common/storage-introduction[Azure storage]


Observability includes Promethus AlertManager, which analyzes the managed clusters and communicates with third-party alerting systems. When the service is enabled, the `metrics-collector` pod is deployed automatically on your managed cluster to "scrape" data from OpenShift Prometheus. The data collected from Prometheus is then sent to the {product-title-short} hub cluster.

You can also create custom rules to customize alert messages. If you are not notified from the third-party messaging tool, you can use Grafana to view cluster data.

*Note*: When you import or create a cluster, observability is deployed automatically.

For more information about enabling observability, see link:../observability/observability_install.adoc#enable-observability[Enable observability service].

[#observability-console-pages]
== Observability console pages
You can also view metric data from your managed clusters by selecting the Grafana link from the following console pages: 

** _Overview_: Operation details across providers
** _Topology_: Visual data for clusters, applications, and policies

[#overview-page-observe]
=== Observe environments Overview page

You can view the following information about your clusters on the _Overview_ dashboard:

* Cluster, node, and pod counts across all clusters and for each provider
* Cluster status
* Cluster compliance
* Pod status

Many clickable elements on the dashboard open a search for related resources. Click on a provider card to view information for clusters from a single provider. You can personalize your view of the _Overview_ dashboard by clicking and dragging to reorganize the cards.

[#topology-page]
=== Topology page
 
The _Topology_ page uses information from ETCD to display Kubernetes objects within a cluster. You can view hub cluster resources. As you configure managed clusters, you see more clusters in the Topology view.

To reduce the graphics on the page, you can filter the view by Clusters, Namespaces, and Labels. You can also filter the design by selecting the icon that represents the Kubernetes objects.

Learn more about the tabs that are available from the Topology page:

* Clusters: You can monitor your cluster network, object network, and security policies in a graphical format.
View your hub clusters, all your managed clusters, and monitor security violations.
* Policies: View the policy, policy placement, and clusters that are being validated.
Check for violations for the selected policy.

