[#install-observability]
= Install observability service

Monitor the health of your managed clusters with the observability service (`multicluster-observability-operator`). 

//should add how users can install on a high availability environment vs. standard. seems like it is a easy //change. According to the google doc, the user would update the AvailabilityConfig parameter from High to //Basic and vice versa 

*Required access:* Cluster admininstrator

*Prerequisites*:

//in this case is the hub an OCP cluster, or is it dependent on what's the "central controller for the cluster"

- You must have a hub cluster installed. 
- You must install Grafana. For more information, see https://grafana.com/docs/grafana/latest/installation/[Install Grafana].
- You must have data storage for the time series data. Configure your object store to create a storage solution. For example, Thanos can be used as a storage solution. For more information, see  _Object Storage_ in the https://thanos.io/tip/thanos/storage.md/#configuration[Thanos documentation]. 
- {ocp} must be installed. For more information, see https://docs.openshift.com/container-platform/4.5/architecture/architecture-installation.html[{ocp-short} installation overview].
// Note from Brandi, is a managed cluster also required?

[#enablement-for-observability]
== Enablement for observability

Enable the observability service by creating a `multicluster-observability` CRD. Complete the following steps to enable the observability service: 

. Create and configure object storage for the observability service. Your object storage might resemble the following information:

+
----
type: s3
config:
  bucket: YOUR-BUCKET
  endpoint: S3-ENDPOINT
  insecure: true
  access_key: ACCESS_KEY
  secret_key: SECRET_KEY
----

. Log in to your hub cluster. 
//Log in to OCP or RHACM? It is two different logins.
. Create a namespace for the observability service with the following commad:

+
----
oc create-namespace open-cluster-management-observability
----

. Generate a pull-secret for the `observability` namespace by running the following command:
//--export flag is expected to be deprecated, command might need to be updated
+
----
oc get secret multiclusterhub-operator-pull-secret -n open-cluster-management --export -o yaml |   kubectl apply --namespace=open-cluster-management-observability -f -
----

. Create a secret for your object storage. Your secret must contain the credentials to your storage solution. For example, if you are using Thanos, run the following command:

+
----
kubectl create -f thanos-object-storage.yaml
----

. Create a MultiClusterObservability resource by running the following command:

+
----
kubectl create -f mco_cr.yaml
----

. You can also disable the observability service by scaling the `metrics-collector` deployment to zero. When the deployment is scaled to zero, data is no longer collected from Promethus.


//still working to add steps

[#uninstall-observability]
== Uninstall observability

//5236

//move this to managing the observability service page
Collect logs about new information that is created for observability resources with the `must-gather` command. For more information, see the _Must-gather_ section in the link:../troubleshooting/troubleshooting_intro.adoc[Troubleshooting documentation].
