[#observing-environments]
= Observing environments

Use {product-title} to visualize and monitor metrics from your clusters and cloud providers. You can install the observability service component, `multicluster-observability-operator`, to monitor the health of your managed clusters. The observability service is configured with AlertManager to communicate with third-party alerting systems. Observe your managed cluster data from PromQL and Grafana. 
//what data is seen in Grafana? CPU Memory, storage, etc.
When the observability service is installed, the following components are installed: 

* `multicluster-observability-operator`
* `multicluster-observability-addon`

Observability is installed on the hub cluster during installation. By default, observability is disabled. When you import or create a cluster, observability is deployed automatically. For more information, see link:../observability_install.adoc[Install observability service].

You can view metric data about your cluster by clicking *Observe environments* to see the following console pages: 

** _Overview_: Operation details across providers
** _Topology_: Visual data for clusters, applications, and policies

[#overview-page-observe]
== Observe environments Overview page

You can view the following information about your clusters on the _Overview_ dashboard:

* Cluster, node, and pod counts across all clusters and for each provider
* Cluster status
* Cluster compliance
* Pod status

Many clickable elements on the dashboard open a search for related resources. Click on a provider card to view information for clusters from a single provider. You can personalize your view of the _Overview_ dashboard by clicking and dragging to reorganize the cards.

[#topology-page]
== Topology page
//pull in Jorge about this blurb
The Topology page uses information from Weave Scope probe to display Kubernetes objects within a cluster. You can view hub cluster resources. As you configure managed clusters, you see more clusters in the Topology view.

To reduce the graphics on the page, you can filter the view by Clusters, Namespaces, and Labels. You can also filter the design by selecting the icon that represents the Kubernetes objects.

Learn more about the tabs that are available from the Topology page:

* Clusters: You can monitor your cluster network, object network, and security policies in a graphical format.
View your hub clusters, all your managed clusters, and monitor security violations.
* Policies: View the policy, policy placement, and clusters that are being validated.
Check for violations for the selected policy.

