[#install-observability]
= Install observability service

Monitor the health of your managed clusters with the observability service (`multicluster-observability-operator`).

*Required access:* Cluster administrator or the `open-cluster-management:cluster-manager-admin` role.

*Prerequisites*:

- You must install {ocp}. For more information, see https://docs.openshift.com/container-platform/4.5/architecture/architecture-installation.html[{ocp-short} installation overview]. 
- You must install {product-title}. See link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online] for more information.  
- You must have data storage for the time series data. Configure an object store to create a storage solution. For example, Thanos support different object stores to store the time series data, such as Amazon S3 and Ceph. For a complete list of the supported object stores, see link:https://thanos.io/tip/thanos/storage.md/[Thanos documentation]. If your storage is Amazon S3 or S3 compatible, then you need the following information to create a secret as explained in the <<enablement-for-observability,Enablement for observability>> section:
//update "For example.." for consistency 
// we only support the stable storages mentioned here: https://thanos.io/tip/thanos/storage.md/#configuration
+
----
type: s3
config:
  bucket: YOUR-BUCKET
  endpoint: S3-ENDPOINT
  insecure: true
  access_key: ACCESS_KEY
  secret_key: SECRET_KEY
----
+
For more information, see link:https://docs.aws.amazon.com/whitepapers/latest/aws-overview/storage-services.html[Amazon S3].
+
*Note*: If there is no object storage defined, the component installation might be stuck with the `Installing` status displayed. See link:../troubleshooting/trouble_observability.adoc#troubleshooting-observability[Troubleshooting observability] for more information.

[#enablement-for-observability]
== Enablement for observability

Enable the observability service by creating a MultiClusterObservability CustomResource (CR) instance. Complete the following steps to enable the observability service: 

. Log in to your {product-title-short} hub cluster. 
. Verify that the observaility components are installed:
.. To verify that the `multicluster-observability-operator`, run the following command:
+
----
kubectl get pods -n open-cluster-management|grep observability
----
.. To verify that the appropriate CRDs are present, run the following command: 
+
----
kubectl get crd|grep observ
----
+
The following CRDs must be displayed before you enable the component:
+
----
multiclusterobservabilities.observability.open-cluster-management.io   
observabilityaddons.observability.open-cluster-management.io          
observatoria.core.observatorium.io
----
. Create a namespace for the observability service with the following commad:
+
----
oc create-namespace open-cluster-management-observability
----

. Copy the `multiclusterhub-operator-pull-secret` from the `open-cluster-management` namespace to the `open-cluster-management-observability` namespace by running the following command:

+
----
oc get secret multiclusterhub-operator-pull-secret -n open-cluster-management --export -o yaml |  kubectl apply --namespace=open-cluster-management-observability -f -
----

. Create a secret for your object storage. Your secret must contain the credentials to your storage solution. For example, run the following command:

+
----
kubectl create -f thanos-object-storage.yaml
----
+
Your secret might resemble the following file (the following example is for Amazon S3 or S3 compatible):
+
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: YOUR_S3_BUCKET
      endpoint: YOUR_S3_ENDPOINT
      insecure: false
      access_key: YOUR_ACCESS_KEY
      secret_key: YOUR_SECRET_KEY

----

. Create the `MultiClusterObservability` custom resource (mco CR) for your managed cluster by completing the following steps:
+
.. Create the `MultiClusterObservability` custom resource YAML file named `multiclusterobservability_cr.yaml`. 

// Will receive info from Marco - For most cases, the default file might resemble the following file. For more details about the API, see link:../https://github.com/open-cluster-management/rhacm-docs/blob/2.1_stage/apis/observability.json.adoc
+
----
apiVersion: observability.open-cluster-management.io/v1beta1
kind: MultiClusterObservability
metadata:
  name: observability #Your customized name of MulticlusterObservability CR
spec:
  availabilityConfig: High # Available values are High or Basic
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
  observabilityAddonSpec: # The ObservabilityAddonSpec defines the global settings for all managed clusters which have observability add-on enabled
    enableMetrics: true # EnableMetrics indicates the observability addon push metrics to hub server
    interval: 60 # Interval for the observability addon push metrics to hub server
  retentionResolution1h: 30d # How long to retain samples of 1 hour in bucket
  retentionResolution5m: 14d
  retentionResolutionRaw: 5d
  storageConfigObject: # Specifies the storage to be used by Observability
    metricObjectStorage:
      name: aws-object-storage
      key: aws.yaml
    statefulSetSize: 10Gi # The amount of storage applied to the Observability stateful sets, i.e. Amazon S3 store, Rule, compact and receiver.
    statefulSetStorageClass:gp2
----

.. Apply the observability YAML to your cluster by running the following command:
+
----
oc apply -f multiclusterobservability_cr.yaml
----
+
All the pods in `open-cluster-management-observability` namespace for Thanos, Grafana and AlertManager are created. All the managed clusters connected to the {product-title-short} hub cluster to be able to send metrics back to the {product-title-short} Observability. Data is populated in the Grafana dashboard.

. Verify that the data is populated in the Grafana dashboard by completing the following steps:
.. Log on to the {product-title-short} console.
.. Navigate to the Observe Environments -> Overview page and click on the Grafana link on top right hand corner.
.. You can also view the data from the command line interface (CLI) for each of the managed clusters. For example, run the following command for the managed cluster, `local-cluster`:
+
----
oc get managedclusteraddon -n local-cluster observability-controller -o yaml
----
+
Your output might resemble the following resource:
+
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  creationTimestamp: "2020-10-19T19:19:32Z"
  generation: 1
  name: observability-controller
  namespace: local-cluster
  resourceVersion: "30409880"
  selfLink: /apis/addon.open-cluster-management.io/v1alpha1/namespaces/self/managedclusteraddons/observability-controller
  uid: ae1dacb7-4fe6-4abd-bef0-e479b6f44157
spec: {}
status:
  addOnConfiguration:
    crName: ""
    crdName: ""
  addOnMeta:
    description: ""
    displayName: ""
  conditions:
  - lastTransitionTime: "2020-10-22T14:10:55Z"
    message: Metrics collector deployed and functional
    reason: Deployed
    status: "True"
    type: Available
  - lastTransitionTime: "2020-10-22T14:10:55Z"
    message: enableMetrics is set to False
    reason: Disabled
    status: "False"
    type: Disabled
  - lastTransitionTime: "2020-10-22T14:10:55Z"
    message: Metrics collector deployment not successful
    reason: Degraded
    status: "False"
    type: Degraded
----

== Uninstall observability

Uninstall the observability service by completing the following steps:

. Log in to your hub cluster.
. Delete the `MultiClusterObservability` resource with the following command:
+
----
kubectl delete multicluster-observability-operator
----
+
When you delete the resource, the pods in the `open-cluster-management-observability` namespace on {product-title-short} hub cluster, and the pods in `open-cluster-management-addon-observability` namespace on all managed clusters are removed. 

*Important*:

- You must delete the observability service before you uninstall {product-title}.
- Your object storage is not effected after you uninstall the observability service.

Learn more on how to manage the observability service, see xref:../observability/manage_observe#managing-observability[Managing observability].


