[#enable-observability]
= Enable observability service

Monitor the health of your managed clusters with the observability service (`multicluster-observability-operator`).

*Required access:* Cluster administrator or the `open-cluster-management:cluster-manager-admin` role.

* <<prerequisites-observability,Prerequisites>>
* <<enabling-observability,Enabling observability>>
* <<creating-mco-cr,Creating the MultiClusterObservability CR>>
* <<enabling-observability-ocp,Enabling observability from the {ocp} console>>
* <<external-metric-query,Using the external metric query>>
* <<disabling-observability-resource,Disabling observability>>

[#prerequisites-observability]
== Prerequisites
 
- You must install {product-title}. See link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online] for more information.  
- You must configure an object store to create a storage solution. {product-title-short} supports the following cloud providers with stable object stores:

* https://aws.amazon.com/getting-started/hands-on/lightsail-object-storage/[Amazon Web Services S3 (AWS S3)]
* https://www.redhat.com/en/technologies/storage/ceph[Red Hat Ceph (S3 compatible API)]
* https://cloud.google.com/storage[Google Cloud Storage]
* https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction[Azure storage]
* https://www.redhat.com/en/technologies/storage/ceph[Red Hat OpenShift Data Foundation (formerly known as Red Hat OpenShift Container Storage)]
* https://www.ibm.com/docs/en/baw/20.x?topic=storage-preparing-cloud-public-roks[Red Hat OpenShift on IBM (ROKS)]
//* https://www.ibm.com/docs/en/spectrum-scale/5.0.5?topic=overview-s3-api[IBM Spectrum Scale]
+
*Important*: When you configure your object store, ensure that you meet the encryption requirements necessary when sensitive data is persisted. For more information on Thanos supported object stores, see https://thanos.io/tip/thanos/storage.md/#object-storage[Thanos documentation].

[#enabling-observability]
== Enabling observability

Enable the observability service by creating a `MultiClusterObservability` custom resource (CR) instance. Before you enable observability, see xref:../observability/observe_environments.adoc#observability-pod-capacity-requests[Observability pod capacity requests] for more information. Complete the following steps to enable the observability service: 

. Log in to your {product-title-short} hub cluster. 
. Create a namespace for the observability service with the following command:
+
----
oc create namespace open-cluster-management-observability
----

. Generate your pull-secret. If {product-title-short} is installed in the `open-cluster-management` namespace, run the following command:
 
+
----
DOCKER_CONFIG_JSON=`oc extract secret/multiclusterhub-operator-pull-secret -n open-cluster-management --to=-`
----
+
If the `multiclusterhub-operator-pull-secret` is not defined in the namespace, copy the `pull-secret` from the `openshift-config` namespace into the `open-cluster-management-observability` namespace. Run the following command:
+
----
DOCKER_CONFIG_JSON=`oc extract secret/pull-secret -n openshift-config --to=-`
----
+
Then, create the pull-secret in the `open-cluster-management-observability` namespace, run the following command:
+
----
oc create secret generic multiclusterhub-operator-pull-secret \
    -n open-cluster-management-observability \
    --from-literal=.dockerconfigjson="$DOCKER_CONFIG_JSON" \
    --type=kubernetes.io/dockerconfigjson
----

. Create a secret for your object storage for your cloud provider. Your secret must contain the credentials to your storage solution. For example, run the following command:
+
----
oc create -f thanos-object-storage.yaml -n open-cluster-management-observability
----
+
View the following examples of secrets for the supported object stores:

** For {product-title-short}, your secret might resemble the following file:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: YOUR_S3_BUCKET
      endpoint: YOUR_S3_ENDPOINT
      insecure: true
      access_key: YOUR_ACCESS_KEY
      secret_key: YOUR_SECRET_KEY
----

** For Amazon S3 or S3 compatible, your secret might resemble the following file:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: YOUR_S3_BUCKET
      endpoint: YOUR_S3_ENDPOINT
      insecure: true
      access_key: YOUR_ACCESS_KEY
      secret_key: YOUR_SECRET_KEY
----
+
For more details, see https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html[Amazon Simple Storage Service user guide].

** For Google, your secret might resemble the following file: 
+
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: GCS
    config:
      bucket: YOUR_GCS_BUCKET
      service_account: YOUR_SERVICE_ACCOUNT
----
+
For more details, see https://cloud.google.com/storage/docs/introduction[Google Cloud Storage].

** For Azure your secret might resemble the following file:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: AZURE
    config:
      storage_account: YOUR_STORAGE_ACCT
      storage_account_key: YOUR_STORAGE_KEY
      container: YOUR_CONTAINER
      endpoint: blob.core.windows.net
      max_retries: 0
----
+
For more details, see https://docs.microsoft.com/en-us/azure/storage/[Azure Storage documentation].

** For Red Hat OpenShift Data Foundation, your secret might resemble the following file:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: YOUR_RH_DATA_FOUNDATION_BUCKET
      endpoint: YOUR_RH_DATA_FOUNDATION_ENDPOINT
      insecure: false
      access_key: YOUR_RH_DATA_FOUNDATION_ACCESS_KEY
      secret_key: YOUR_RH_DATA_FOUNDATION_SECRET_KEY
----
+
For more details, see https://www.redhat.com/en/technologies/storage/ceph[Red Hat OpenShift Data Foundation].

** For Red Hat OpenShift on IBM (ROKS), your secret might resemble the following file:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: YOUR_ROKS_S3_BUCKET
      endpoint: YOUR_ROKS_S3_ENDPOINT
      insecure: true
      access_key: YOUR_ROKS_ACCESS_KEY
      secret_key: YOUR_ROKS_SECRET_KEY
----
+
For more details, follow the IBM Cloud documentation, https://cloud.ibm.com/objectstorage/create[Cloud Object Storage]. Be sure to use the service credentials to connect with the object storage. For more details, follow the IBM Cloud documentation, https://cloud.ibm.com/objectstorage/create%5BCloud[Cloud Object Store] and https://cloud.ibm.com/docs/cloud-object-storage/iam?topic=cloud-object-storage-service-credentials%5BService[Service Credentials].

. You can retrieve the S3 access key and secret key for your cloud providers with the following commands:
+
----
YOUR_CLOUD_PROVIDER_ACCESS_KEY=$(oc -n open-cluster-management-observability get secret <object-storage-secret> -o jsonpath="{.data.thanos\.yaml}" | base64 --decode | grep access_key | awk '{print $2}')

echo $ACCESS_KEY

YOUR_CLOUD_PROVIDER_SECRET_KEY=$(oc -n open-cluster-management-observability get secret <object-storage-secret> -o jsonpath="{.data.thanos\.yaml}" | base64 --decode | grep secret_key | awk '{print $2}')

echo $SECRET_KEY
----

[#creating-mco-cr]
=== Creating the MultiClusterObservability CR

Complete the following steps to create the `MultiClusterObservability` custom resource (CR) for your managed cluster:

. Create the `MultiClusterObservability` custom resource YAML file named `_multiclusterobservability_cr.yaml_`. 
+
View the following default YAML file for observability:
+
----
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  observabilityAddonSpec: {}
  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
----
+
You might want to modify the value for the `retentionConfig` parameter in the `advanced` section. For more information, see https://thanos.io/v0.8/components/compact/#downsampling-resolution-and-retention[Thanos Downsampling resolution and retention]. Depending on the number of managed clusters, you might want to update the amount of storage for stateful sets, see link:../apis/observability.json.adoc#observability-api[Observability API] for more information.
+
. To deploy on infrastructure machine sets, you must set a label for your set by updating the `_nodeSelector_` in the `MultiClusterObservability` YAML. Your YAML might resemble the following content:
+
----
  nodeSelector:
    node-role.kubernetes.io/infra: 
----
+
For more information, see https://docs.openshift.com/container-platform/4.8/machine_management/creating-infrastructure-machinesets.html[Creating infrastructure machine sets].

. Apply the observability YAML to your cluster by running the following command:
+
----
oc apply -f multiclusterobservability_cr.yaml
----
+
All the pods in `open-cluster-management-observability` namespace for Thanos, Grafana and AlertManager are created. All the managed clusters connected to the {product-title-short} hub cluster are enabled to send metrics back to the {product-title-short} Observability service.

. To validate that the observability service is enabled, launch the Grafana dashboards to make sure the data is populated. Complete the following steps:
.. Log in to the {product-title-short} console.
.. From the navigation menu, select *Home* > *Overview*.
.. Click the Grafana link that is near the console header to view the metrics from your managed clusters.
+
*Note*: If you want to exclude specific managed clusters from collecting the observability data, add the following cluster label to your clusters: `observability: disabled`.

The observability service is enabled. After you enable the observability service the following functionalities are initiated:

* All the alert managers from the managed clusters are forwarded to the {product-title-short} hub cluster.
* All the managed clusters that are connected to the {product-title-short} hub cluster are enabled to send alerts back to the {product-title-short} observability service. You can configure the {product-title-short} Alertmanager to take care of deduplicating, grouping, and routing the alerts to the correct receiver integration such as email, PagerDuty, or OpsGenie. You can also handle silencing and inhibition of the alerts.
+
*Note*: Alert forwarding to the {product-title-short} hub cluster feature is only supported by managed clusters with {ocp} version 4.8 or later. After you install {product-title-short} with observability enabled, alerts from {ocp-short} v4.8 and later are automatically forwarded to the hub cluster.

See xref:../observability/customize_observability.adoc#forward-alerts[Forwarding alerts] to learn more.

[#enabling-observability-ocp]
== Enabling observability from the {ocp} console

. Log in to your {ocp} cluster.
. From the navigation menu, select *Home* > *Projects*.
. Click the *Create Project* button. You must enter _open-cluster-management-observability_ for the name of the project. 
. Click *Create*.
. Create your image pull-secret:
.. Create your image pull-secret named, `multiclusterhub-operator-pull-secret` in the `open-cluster-management-observability` project. From the {ocp-short} console navigation menu, select *Workloads* > *Secrets*. 
.. Select the *Create* button > *Image Pull Secret*.
.. Complete the _Create Image Pul Secret_ form, then click *Create*.
. Create your object storage secret named, `thanos-object-storage` in the `open-cluster-management-observability` project. In this example, create an Amazon S3 object storage secret for the observability service:
.. From the {ocp-short} navigation menu, click *Workloads* > *Secrets*. 
.. Click the *Create* button > *From YAML*.
.. Enter your object storage secret details, then click *Create*.
+
*Note*: See step 4 of the <<enabling-observability,Enabling observability>> section to view an example of a secret.
. Create the `MultiClusterObservability` CR:
.. From the {ocp-short} navigation menu, select *Home* > *Explore*. 
.. Search for the `MultiClusterObservability` API resource by querying _MultiClusterObservability_. 
.. Select the `MultiClusterObservability` with version `v1beta2`, to view the resource details.
.. Select the _Instances_ tab and click the *Create MultiClusterObservability* button.
.. Enter your `MultiClusterObservability` instance details, then click *Create*
.. Verify the status of the `MultiClusterObservability` instance by viewing the _Conditions_ section. When you receive the following message, the obseravbility service is enabled successfully: `Observability components are deployed and running`

Observability is enabled from the {ocp-short} console.

[#external-metric-query]
=== Using the external metric query

Observability provides an external API for metrics to be queried through the OpenShift route, `rbac-query-proxy`. View the following tasks to use `rbac-query-proxy` route:

* You can get the details of the route with the following command:
+
----
oc get route rbac-query-proxy -n open-cluster-management-observability
----

* To access the `rbac-query-proxy` route, you must have an OpenShift OAuth access token. The token should be associated with a user or service account, which has permission to get namespaces. For more information, see https://docs.openshift.com/container-platform/4.8/authentication/managing-oauth-access-tokens.html[Managing user-owned OAuth access tokens].

* Get the default CA certificate and store the content of the key, `tls.crt`, in a local file. Run the following command:
+
----
oc get secrets -n openshift-ingress router-certs-default -o yaml
----

* Run the following command to query metrics:
+
----
curl --cacert ./ca.crt -H "Authorization: bearer {TOKEN}" https://{PROXY_ROUTE_URL}/api/v1/query?query={QUERY_EXPRESSION}
----
+
*Note*: The `QUERY_EXPRESSION` is the standard Prometheus query expression. For example, query the metrics `cluster_infrastructure_provider` by replacing the URL in the previously mentioned command, with the following URL: `https://{PROXY_ROUTE_URL}/api/v1/query?query=cluster_infrastructure_provider`. For more details, see https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying prometheus].

* You can also replace certificates for the `rbac-query-proxy` route:
** See link:../governance/cert_mgmt_ingress.adoc#openssl-commands-for-generating-a-certificate[OpenSSL commands for generating a certificate] to create certificates. When you customize the `csr.cnf`, update the `DNS.1` to the hostname for the `rbac-query-proxy` route.
** Run the following command to create `proxy-byo-ca` and `proxy-byo-cert` secrets using the generated certificates:
+
----
oc -n open-cluster-management-observability create secret tls proxy-byo-ca --cert ./ca.crt --key ./ca.key

oc -n open-cluster-management-observability create secret tls proxy-byo-cert --cert ./ingress.crt --key ./ingress.key
----

[#disabling-observability-resource]
== Disabling observability

To disable the observability service, uninstall the `observability` resource. See step 1 of link:../install/uninstall.adoc#removing-a-multiclusterhub-instance-by-using-commands[Removing a MultiClusterHub instance by using commands] for the procedure.

To learn more about customizing the observability service, see xref:../observability/customize_observability.adoc#customizing-observability[Customizing observability].


