:_mod-docs-content-type: PROCEDURE

[#enabling-observability-service]
= Enabling the observability service

[role="_abstract"]
When you enable the observability service on your hub cluster, the `multicluster-observability-operator` watches for new managed clusters and automatically deploys metric and alert collection services to the managed clusters. You can use metrics and configure Grafana dashboards to make cluster resource information visible, help you save cost, and prevent service disruptions.

Monitor the status of your managed clusters with the observability component, also known as the `multicluster-observability-operator` pod. Enable the observability service by creating a `MultiClusterObservability` custom resource instance.

*Required access:* Cluster administrator, the `open-cluster-management:cluster-manager-admin` role, or S3 administrator.

.Prerequisites
 
* You must install {acm}. See link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online] for more information.
* You must specify the `storageConfig.storageClass` field in the `MultiClusterObservability` custom resource if you do not want to use the platform default `storageClass`.
* Direct network access to the hub cluster is required. Network access to load balancers and proxies are not supported. For more information, see link:../networking/networking_intro.adoc#networking[Networking].
- Before you enable observability, see xref:../observability/observe_environments.adoc[Observability pod capacity requests] for more information.
- You must configure an object store to create a storage solution. 
+
*Important:* 
+
* When you configure your object store, ensure that you meet the encryption requirements that are necessary when sensitive data is persisted. The observability service uses Thanos supported, stable object stores.
* You must use a separate object storage bucket for each hub cluster. Each observability installation requires a dedicated, unique bucket. Multiple writes to the same storage path at the same time causes data corruption, historical metrics loss, and stops the Thanos Compactor. 
* {acm-short} supports the following cloud providers with stable object stores:

** Amazon Web Services S3 (AWS S3)
** Red Hat Ceph (S3 compatible API)
** Google Cloud Storage
** Azure storage
** Red Hat OpenShift Data Foundation, formerly known as Red Hat OpenShift Container Storage
** Red Hat OpenShift on IBM Cloud

- When observability is enabled or disabled on {ocp-short} managed clusters that are managed by {acm-short}, the observability endpoint operator updates the `cluster-monitoring-config` config map by adding additional `alertmanager` configuration that automatically restarts the local Prometheus.
- The observability endpoint operator updates the `cluster-monitoring-config` config map by adding additional `alertmanager` configurations that automatically restart the local Prometheus. When you insert the `alertmanager` configuration in the {ocp-short} managed cluster, the configuration removes the settings that relate to the retention field of the Prometheus metrics. 

.Procedure
 
. Log in to your {acm-short} hub cluster. 
. Create a namespace for the observability service with the following command:

+
[source,bash]
----
oc create namespace open-cluster-management-observability
----

. Generate your pull-secret. If {acm-short} is installed in the `open-cluster-management` namespace, run the following command:
 
+
[source,bash]
----
DOCKER_CONFIG_JSON=`oc extract secret/multiclusterhub-operator-pull-secret -n open-cluster-management --to=-`
----

.. If the `multiclusterhub-operator-pull-secret` is not defined in the namespace, copy the `pull-secret` from the `openshift-config` namespace into the `open-cluster-management-observability` namespace by running the following command:

+
[source,bash]
----
DOCKER_CONFIG_JSON=`oc extract secret/pull-secret -n openshift-config --to=-`
----

.. Create the pull-secret in the `open-cluster-management-observability` namespace by running the following command:

+
[source,bash]
----
oc create secret generic multiclusterhub-operator-pull-secret \
    -n open-cluster-management-observability \
    --from-literal=.dockerconfigjson="$DOCKER_CONFIG_JSON" \
    --type=kubernetes.io/dockerconfigjson
----
+
*Important:* If you modify the global pull secret for your cluster by using the {ocp-short} documentation, be sure to also update the global pull secret in the observability namespace. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/images/managing-images#images-update-global-pull-secret_using-image-pull-secrets[Updating the global pull secret] for more details.

. Create a secret for your object storage for your cloud provider. Your secret must contain the credentials to your storage solution. For example, run the following command:

+
[source,bash]
----
oc create -f thanos-object-storage.yaml -n open-cluster-management-observability
----
+
View the following examples of secrets for the supported object stores:

- For Amazon S3 or S3 compatible, your secret might resemble the following file:

+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: YOUR_S3_BUCKET
      endpoint: YOUR_S3_ENDPOINT
      insecure: true
      access_key: YOUR_ACCESS_KEY
      secret_key: YOUR_SECRET_KEY
----
* For the `endpoint` parameter, enter the URL without the protocol. Enter the URL for your Amazon S3 endpoint that might resemble the following URL: `s3.us-east-1.amazonaws.com`.
+
For more details, see the link:https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html[Amazon Simple Storage Service user guide].

- For Google Cloud Platform, your secret might resemble the following file: 

+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: GCS
    config:
      bucket: YOUR_GCS_BUCKET
      service_account: YOUR_SERVICE_ACCOUNT
----
+
For more details, see link:https://cloud.google.com/storage/docs/introduction[Google Cloud Storage].

- For Azure your secret might resemble the following file:

+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: AZURE
    config:
      storage_account: YOUR_STORAGE_ACCT
      storage_account_key: YOUR_STORAGE_KEY
      container: YOUR_CONTAINER
      endpoint: blob.core.windows.net
      max_retries: 0
----
* If you use the `msi_resource` path for the `endpoint` parameter, the endpoint authentication is complete by using the system-assigned managed identity. Your value must resemble the following endpoint: `https://<storage-account-name>.blob.core.windows.net`. 
* If you use the `user_assigned_id` path for the `endpoint` parameter, endpoint authentication is complete by using the user-assigned managed identity. When you use the `user_assigned_id`, the `msi_resource` endpoint default value is `https:<storage_account>.<endpoint>`.
For more details, see link:https://docs.microsoft.com/en-us/azure/storage/[Azure Storage documentation].
+
*Note:* If you use Azure as an object storage for a {ocp} cluster, the storage account associated with the cluster is not supported. You must create a new storage account.

- For Red Hat OpenShift Data Foundation, your secret might resemble the following file:

+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: YOUR_RH_DATA_FOUNDATION_BUCKET
      endpoint: YOUR_RH_DATA_FOUNDATION_ENDPOINT
      insecure: false
      access_key: YOUR_RH_DATA_FOUNDATION_ACCESS_KEY
      secret_key: YOUR_RH_DATA_FOUNDATION_SECRET_KEY
----
* For the `endpoint` parameter, enter the URL without the protocol. Enter the URL for your Red Hat OpenShift Data Foundation endpoint that might resemble the following URL: `example.redhat.com:443`.
+
For more details, see link:https://www.redhat.com/en/technologies/cloud-computing/openshift-data-foundation[Red Hat OpenShift Data Foundation].

- For Red Hat OpenShift on IBM (ROKS), your secret might resemble the following file:

+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: YOUR_ROKS_S3_BUCKET
      endpoint: YOUR_ROKS_S3_ENDPOINT
      insecure: true
      access_key: YOUR_ROKS_ACCESS_KEY
      secret_key: YOUR_ROKS_SECRET_KEY
----
- Enter the URL without the protocol. Enter the URL for your Red Hat OpenShift Data Foundation endpoint that might resemble the following URL: `example.redhat.com:443`.
+
For more details, follow the IBM Cloud documentation, link:https://cloud.ibm.com/objectstorage/create[Cloud Object Storage]. Be sure to use the service credentials to connect with the object storage. For more details, follow the IBM Cloud documentation, link:https://cloud.ibm.com/objectstorage/create%5BCloud[Cloud Object Store] and link:https://cloud.ibm.com/docs/cloud-object-storage/iam?topic=cloud-object-storage-service-credentials%5BService[Service Credentials].

.Additional resources

* link:https://aws.amazon.com/getting-started/hands-on/lightsail-object-storage/[Amazon Web Services S3 (AWS S3)]
* link:https://www.redhat.com/en/technologies/storage/ceph[Red Hat Ceph (S3 compatible API)]
* link:https://cloud.google.com/storage[Google Cloud Storage]
* link:https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction[Azure storage]
* link:https://www.redhat.com/en/technologies/cloud-computing/openshift-data-foundation[Red Hat OpenShift Data Foundation (formerly known as Red Hat OpenShift Container Storage)]
* link:https://www.ibm.com/docs/en/baw/20.x?topic=storage-preparing-cloud-public-roks[Red Hat OpenShift on IBM (ROKS)]
* xref:../observability/using_observability.adoc#using-observability[Using observability]
* xref:../observability/adv_config_obs.adoc#adv-config-obs[Observability advanced configuration]
* xref:../observability/observe_environments_intro.adoc#observing-environments-intro[Observability service]


