[#observing-environments-intro]
= Observability service introduction

The observability component is a service you can use to understand the health and utilization of clusters across your fleet. By default, multicluster observability operator is enabled during the installation of {product-title-short}. 

[#observability-support]
== Support

- {product-title-short} is tested with and fully supported by Red Hat OpenShift Data Foundation, formerly {ocp}. 

- {product-title-short} supports the function of the multicluster observability operator on user-provided third-party object storage that is S3 API compatible. The observability service uses Thanos supported, stable object stores.

- {product-title-short} use commercial, reasonable efforts to assist in the identification of the root cause. If a support ticket is raised and the root cause has been determined to be a result of the customer-provided S3 compatible object storage, then the issue must be resolved using the customer support channels.

- {product-title-short} does not commit to fix support tickets raised by customers, where the root cause identified is the S3 compatible object storage provider.

Read the following documentation for more details about the observability component:

* xref:../observability/observability_arch.adoc#observability-arch[Observability architecture]
* xref:../observability/observe_environments.adoc#observing-environments[Observability configuration]
* xref:../observability/observability_enable#enabling-observability-service[Enabling the observability service]
//looking to rename this section|MJ|10/11/23
* xref:../observability/use_observability.adoc#using-observability[Using observability]
* xref:../observability/customize_observability#customizing-observability[Customizing observability]
* xref:../observability/observability_alerts.adoc#observability-alerts[Observability alerts]
* xref:../observability/search_intro.adoc#searching-in-the-console-intro[Searching in the console introduction]
* xref:../observability/insights_intro.adoc#using-rh-insights[Using observability with Red Hat Insights]




 
