[#search-in-the-console]
= Search in the console

For {product-title}, search provides visibility into your Kubernetes resources across all of your clusters. Search indexes the Kubernetes resources and the relationships to other resources. You can create a `searchcustomization` custom resource (CR) to define the storage settings for search persistence if you want to change the storage class and storage size. 

* <<search-components,Search components>>
* <<search-customization,Search customization>>
** <<options-increase-memory,Options to increase the redisgraph memory>>
** <<update-search-limit,Updating saved search limit>>
* <<queries-in-the-console,Querying in the console>>
** <<search-argo,Querying ArgoCD applications>>
* <<updating-klusterlet-addons-managed,Updating klusterlet-addon-search deployments on managed clusters>>

[#search-components]
== Search components

The search architecture is composed of the following components:

- `search-collector`: Watches the Kubernetes resources, collects the resource metadata, computes relationships for resources across all of your managed clusters, and sends the collected data to the `search-indexer`. The `search-collector` on your managed cluster runs as a pod named, `klusterlet-addon-search`. 

- `search-indexer`: Receives resource metadata from the collectors and writes to PostgreSQL database. The `search-indexer` also watches resources in the hub cluster to keep track of active managed clusters.

- `search-api`: Provides access to all cluster data in the `search-indexer` through GraphQL and enforces role-based access control (RBAC).

- `search-postgres`: Stores collected data from all managed clusters in an instance of the PostgreSQL database.
Search is configured by default on the hub cluster. When you provision or manually import a managed cluster, the `klusterlet-addon-search` is enabled. If you want to disable search on your managed cluster, see link:../add-ons/modify_endpoint.adoc#modifying-the-klusterlet-add-ons-settings-of-your-cluster[Modifying the klusterlet add-ons settings of your cluster] for more information.

[#search-customization]
== Search customization

You can modify the default values in the `searchcustomization` custom resource. To view details of the custom resource, run the following command:

----
oc get search searchcustomization -o yaml
----

The search operator watches the `searchcustomization` custom resource, reconciles the changes and updates active pods. View the following descriptions of the configurations:

- PostgreSQL database storage: 
+
When you install {product-title-short}, the PostgreSQL database is configured to save the PostgreSQL data in an empty directory (`emptyDir`) volume. If the empty directory size is limited, you can save the PostgreSQL data on a Persistent Volume Claim (PVC) to improve search performance. You can select a storageclass from your {product-title-short} hub cluster to back up your search data. For example, if you select the `gp2` storageclass your configuration might resemble the following example:
+
[source,yaml]
----
apiVersion: search.open-cluster-management.io/v1alpha1
kind: SearchCustomization
metadata:
  name: searchcustomization
  namespace: open-cluster-management
  labels:
    cluster.open-cluster-management.io/backup: ""
spec:
  dbStorage:
  size: 10Gi
  storageClassName: gp2
----
+
This confirguration creates a PVC named `gp2-search` and is mounted to the `search-postgres` pod. By default, the storage size is `10Gi`. You can modify the storage size. For example, `20Gi` might be sufficient for about 200 managed clusters.

- PostgreSQL database configuration:
+
PostgreSQL supports database tuning to optimize your database performance. The tuning configurations can be specified using a ConfigMap. This ConfigMap contains the name-value pairs for the supported tuning parameters. See the following example command to create a ConfigMap with tuning parameters:
+
----
oc create configmap tuning-config --from-literal POSTGRESQL_SHARED_BUFFERS=128MB --from-literal POSTGRESQL_EFFECTIVE_CACHE_SIZE=128MB --from-literal WORK_MEM=64MB
----
+
Optimize PostgreSQL database configuration by using the previous ConfigMap. For example, add `tuning-config` as the parameter value: 
+
[source,yaml]
----
apiVersion: search.open-cluster-management.io/v1alpha1
kind: SearchCustomization
metadata:
  name: searchcustomization
  namespace: open-cluster-management
  labels:
    cluster.open-cluster-management.io/backup: ""
spec:
  dbConfig: tuning-config
  dbStorage:
  size: 10Gi
  storageClassName: gp2-search
----
+
- Optimize cost by tuning the pod memory requirements, replica count, and update log levels for active pods. Update the `deployment` section of the `searchcustomization` custom resource. There are four deployments managed by the `searchcustomization`, which can be updated individually. Your `searchcustomization` custom resource might resemble the following file:
+
[source,yaml]
----
apiVersion: search.open-cluster-management.io/v1alpha1
kind: SearchCustomization
metadata:
  name: searchcustomization
  namespace: open-cluster-management
spec:
  dbConfig: tuning-config
    deployments:
      collector:
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 250m
          memory: 64Mi
        indexer:
        replicaCount: 3
----

- Node placement for search pods:
+
You can update the `Placement` of search pods by using the `nodeSelector` parameter, or the `tolerations` parameter. View the following example configuration:
+
[source,yaml]
----
spec:
 dbStorage:
  size: 10Gi
 deployments:
  collector: {}
  database: {}
  indexer: {}
  queryapi: {}
 nodeSelector:
  node-role.kubernetes.io/infra: ""
 tolerations:
 - effect: NoSchedule
  key: node-role.kubernetes.io/infra
  operator: Exists
----

[#options-increase-memory]
=== Options to increase the redisgraph memory

Redisgraph is an in-memory database that needs linear growth of memory as the number of objects are cached. A {product-title-short} cluster with many managed clusters, or with a large number of Kubernetes objects require limit memory updates for the redisgraph pod (`search-redisgraph-0`).

By default, the redisgraph pod (`search-redisgraph-0`) is deployed with a memory limit of `4Gi`. If you are managing larger clusters, you might need to increase this limit by editing the `redisgraph_resource.limit_memory` for the `searchoperator` in the hub cluster namespace. For example, you can update the limit to `8Gi` with the following command:

----
oc patch searchoperator searchoperator --type='merge' -p '{"spec":{"redisgraph_resource":{"limit_memory":"8Gi"}}}'
----

After the change is made, the `search-redisgraph` pod automatically restarts with the updated configuration.

[#update-search-limit]
=== Updating saved search limit

By default, there is a limit of ten saved searches for eacch user. Only a user with the `administrator` role can update the limit by adding the following key value to the `console-config` ConfigMap, `key:value: SAVED_SEARCH_LIMIT: x`.

[#queries-in-the-console]
== Querying in the console

You can type any text value in the _Search box_ and results include anything with that value from any property, such as a name or namespace. Users are unable to search for values that contain an empty space.

For more specific search results, include the property selector in your search. You can combine related values for the property, for a more precise scope of your search. For example, search for `cluster:dev red` to receive results that match the string "red" in the `dev` cluster. 

View the following steps to make queries with search:

. Click *Search* in the navigation menu.
. Type a word in the _Search box_, then Search finds your resources that contain that value.
 ** As you search for resources, you receive other resources that are related to your original search result, which help you visualize how the resources interact with other resources in the system.
 ** Search returns and lists each cluster with the resource that you search.
For resources in the _hub_ cluster, the cluster name is displayed as _local-cluster_.
 ** Your search results are grouped by `kind`, and each resource `kind` is grouped in a table.
 ** Your search options depend on your cluster objects.
You can refine your results with specific labels.
Search is case-sensitive when you query labels.
See the following examples: name, namespace, status, and other resource fields.
Auto-complete provides suggestions to refine your search.
See the following example:
  *** Search for a single field, such as `kind:pod` to find all pod resources.
  *** Search for multiple fields, such as `kind:pod namespace:default` to find the pods in the default namespace.

+
*Notes:*

** You can also search with conditions by using characters, such as `+>, >=, <, <=, !=+`.
** When you search for more than one property selector with multiple values, the search returns either of the values that were queried. View the following examples:
*** When you search for `kind:pod name:a`, any pod named `a` is returned.
*** When you search for `kind:pod name:a,b`, any pod named `a` or `b` are returned.
*** Search for `kind:pod status:!Running` to find all pod resources where the status is not `Running`.
*** Search for `kind:pod restarts:>1` to find all pods that restarted at least twice.
. If you want to save your search, click the *Save search* icon.

[#search-argo]
=== Querying ArgoCD applications

When you search for an ArgoCD application, you are directed to the _Applications_ page. Complete the following steps to access the ArgoCD application from the _Search_ page:

. Log in to your {product-title-short} hub cluster.
. From the console header, select the _Search_ icon.
. Filter your query with the following values: `kind:application` and `apigroup:argoproj.io`
. Select an application to view. The _Application_ page displays an overview of information for the application.

[#updating-klusterlet-addons-managed]
== Updating _klusterlet-addon-search_ deployments on managed clusters

To collect the Kubernetes objects from the managed clusters, the `klusterlet-addon-search` pod is run on all the managed clusters where search is enabled. This deployment is run in the `open-cluster-management-agent-addon` namespace. A managed cluster with a high number of resources might require more memory for the `klusterlet-addon-search` deployment to function.

Resource requirements for the `klusterlet-addon-search` pod in a managed cluster can be specified in the `ManagedClusterAddon` custom resource in your {product-title-short} hub cluster. There is a namespace for each managed cluster with the managed cluster name. Edit the `ManagedClusterAddon` custom resource from the namespace matching the managed cluster name. Run the following command to update the resource requirement in `xyz` managed cluster:

----
oc edit managedclusteraddon search-collector -n xyz
----

Append the resource requirements as annotations. View the following example:

[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  annotations: addon.open-cluster-management.io/search_memory_limit: 2048Mi
  addon.open-cluster-management.io/search_memory_request: 512Mi
----

The annotation overrides the resource requirements on the managed clusters and automatically restarts the pod with new resource requirements.

Learn more about the {product-title} console, see link:../console/console_intro.adoc#web-console[Web console].
