:_mod-docs-content-type: PROCEDURE

[#using-observability]
= Using observability

[role="_abstract"]
Use the observability service to view the utilization of clusters across your fleet. There are lists of alerts affecting the health of the operator and separately includes all {ocp-virt-short} alerts, even those not impacting the health of the operator.

To access your endpoint by using the mutual TLS, which verifies the identities of both parties in a network connection, query metrics through the {ocp} `rbac-query-proxy` route with the observability external API.

*Required access:* Cluster administrator

.Procedure

. Query metrics using the observability API. Get the details of the route with the following command:

+
[source,bash]
----
export PROXY_ROUTE_URL=$(oc get route rbac-query-proxy -n open-cluster-management-observability -o jsonpath='{.spec.host}')
----

. To access the `rbac-query-proxy` route with your {ocp-short} OAuth access token, run the following command to get the token. The token must be associated with a user or service account, which has permission to get namespaces:

+
[source,bash]
----
MY_TOKEN=$(oc whoami --show-token)
----

. To access the `openshift-ingress` route, get the default CA certificate and store the content of the `tls.crt` key in a local file. Run the following command:

+
[source,bash]
----
oc -n openshift-ingress get secret router-certs-default -o jsonpath="{.data.tls\.crt}" | base64 -d > ca.crt
----
+
*Note:* The `router-certs-default` secret does not exist if your hub cluster is running on OpenShift Service on AWS. Instead, use the CA certificate that `spec.defaultCertificate.name` points to in the default ingress controller object. Store the content of the `tls.crt` key in a local file. Complete the following steps:

.. Get the name of the `spec.defaultCertificate.name` by running the following command:

+
[source,bash]
----
SECRET_NAME=$(oc get ingresscontroller default -n openshift-ingress-operator -o jsonpath=" {.spec.defaultCertificate.name}")
----

.. Extract the certificate from the secret by running the following command:
+
[source,bash]
----
oc get secret $SECRET_NAME -n openshift-ingress -o jsonpath=" {.data.tls\.crt}" | base64 -d > ca.crt
----

. To query metrics from the API, run the following command: 

+
[source,bash]
----
curl --cacert ./ca.crt -H "Authorization: Bearer ${MY_TOKEN}" https://${PROXY_ROUTE_URL}/api/v1/query?query=${QUERY_EXPRESSION}
----
+
*Note:* The `QUERY_EXPRESSION` is the standard Prometheus query expression. For example, query the metrics `cluster_infrastructure_provider` by replacing the URL in the previous command with the following URL: `https://{PROXY_ROUTE_URL}/api/v1/query?query=cluster_infrastructure_provider`. For more details, see link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus].

. If you want to configure custom certificates for the `rbac-query-proxy` route, see link:../secure_clusters/cert_byo_rbac_query.adoc#replace-cert-rbac[Replacing certificates for _rbac-query-proxy_ route].

.Additional resources

* xref:../observability/obs_view_grafana.adoc#view-explore-data-grafana[Viewing and exploring data by using Grafana dashboards]
* xref:../observability/observability_enable.adoc#enabling-observability-service[Enabling the observability service]
* xref:../observability/observe_environments_intro.adoc#observing-environments-intro[Observability service]
* link:https://prometheus.io/docs/concepts/remote_write_spec/[Prometheus Remote-Write specification]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/authentication_and_authorization/managing-oauth-access-tokens[Managing user-owned OAuth access tokens]