[#managing-applications]
= Managing applications

Review the following topics to learn more about creating, deploying, and managing your applications.
This guide assumes familiarity with Kubernetes concepts and terminology.
Key Kubernetes terms and components are not defined.
For more information about Kubernetes concepts, see https://kubernetes.io/docs/home/[Kubernetes Documentation].

The application management functions provide you with unified and simplified options for constructing and deploying applications and application updates.
With these functions, your developers and DevOps personnel can create and manage applications across environments through channel and subscription-based automation.

See the following topics:

* link:app_lifecycle.md.adoc[Application management lifecycle]
* link:app_model.md.adoc[Application model and definitions]
* link:managing_apps.md.adoc[Managing applications with the console]
* link:app_resources.md.adoc[Application resources]
* link:managing_channels.md.adoc[Creating and managing channels]
* link:managing_subscriptions.md.adoc[Creating and managing subscriptions]
* link:managing_placement_rules.md.adoc[Creating and managing placement rules]
* link:app_resources.md.adoc[Creating and managing application resources]
* link:managing_deployables.md.adoc[Managing deployables with a rolling update]
* link:deploying.md.adoc[Deploying by using application resources]
* link:managing_apps_console.md.adoc[Managing applications with the console]
* link:app_sample.md.adoc[Application resource samples]