[#application-resource-samples]
= Application resource samples

Within {product-title}, applications are composed of multiple application resources. You can use channel, subscription, and placement rule resources to help you deploy, update, and manage your overall applications.

Both single and multi-cluster applications use the same Kubernetes specifications, but multi-cluster applications involve more automation of the deployment and application management lifecycle.

All of the application component resources for {product-title} applications are defined in YAML file spec sections.
When you need to create or update an application component resource, you need to create or edit the appropriate spec section to include the labels for defining your resource.

View the following application resource samples:

* xref:../manage_applications/channel_sample.adoc#channel-samples[Channel samples]
* xref:../manage_applications/subscription_sample.adoc#subscription-samples[Subscription samples]
* xref:../manage_applications/placement_sample.adoc#placement-rule-samples[Placement rule samples]
* xref:../manage_applications/app_sample.adoc#application-samples[Application samples]
