[#application-samples]
= Application samples

View samples and YAML definitions that you can use to build your files.
Applications (`Application.app.k8s.io`) in {product-title} are used for viewing the application components.

For more information about creating and managing applications, see xref:../manage_applications/managing_apps.adoc#creating-and-managing-application-resources[Creating and managing application resources].

[#application-yaml-structure]
== Application YAML structure

To compose the application definition YAML content for creating or updating an application resource, your YAML structure needs to include some required fields and values.
Depending on your application requirements or application management requirements, you might need to include other optional fields and values.

The following YAML structure shows the required fields for an application and some of the common optional fields.

[source,yaml]
----
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name:
  namespace:
spec:
  selector:
    matchLabels:
      label_name: label_value
----

[#application-yaml-table]
== Application YAML table

|===
| Field |Value| Description

| apiVersion
| `app.k8s.io/v1beta1`
| Required

| kind
| `Application`
| Required


| metadata
|
|

|
| `name`: The name for identifying the application resource.
| Required


| 
| `namespace`: The namespace resource to use for the application.
|


| spec.selector.matchLabels
| 
`key:value` pair that are a Kubernetes label and value found on the subscription or subscriptions this application will be associated with. The label allows the application resource to find the related subscriptions by performing a label name and value match.

| Required
|

|===

The spec for defining these applications is based on the Application metadata descriptor custom resource definition that is provided by the Kubernetes Special Interest Group (SIG). Only the values shown in the table are required.

You can use this definition to help you compose your own application YAML content.
For more information about this definition, see https://github.com/kubernetes-sigs/application[Kubernetes SIG Application CRD community specification].

[#application-file-samples]
== Application file samples

The definition structure for an application can resemble the following example YAML content:

[source,yaml]
----
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: my-application
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      my-label: my-label-value
----
