[#application-model-and-definitions]
= Application model and definitions

The Application model consists of the following Kubernetes custom resources: channels, subscription, placement rules, and applications.

* Channels (`channel.apps.open-cluster-management.io`) define the source repositories that a cluster can subscribe to with a subscription and can be the following types: Git repositories, Helm release registries, objectstores, and resource template (deployable) namespace on the hub cluster.
Channels require individual namespaces, except Git channels, which can share a namespace with another Git channel.
* Subscriptions (`subscription.apps.open-cluster-management.io`) allow clusters to subscribe to a source repository (channel) that can be the following types: Git repository, Helm release registry, objectstore, or resource template (deployable) namespace.
Subscriptions can be applied locally to the hub or to managed-clusters.
* Placement rules (`placementrule.apps.open-cluster-management.io`) define the target clusters where subscriptions deploy and maintain the Kubernetes resources.
You can use placement rules to help you facilitate the multi-cluster deployment.
Placement rules can be shared across subscriptions.
* Applications (`application.app.k8s.io`) in {product-title} are used for grouping Kubernetes resources that make up an application.

For more information about creating and managing application resources, see:

* xref:../manage_applications/managing_channels.adoc#creating-and-managing-channels[Creating and managing channels]
* xref:../manage_applications/creating_subscriptions.adoc#creating-a-subscription[Creating and managing subscriptions]
* xref:../manage_applications/managing_placement_rules.adoc#creating-and-managing-placement-rules[Creating and managing placement rules]
* xref:../manage_applications/app_resources.adoc#application-resources[Creating and managing application resources]
