[#application-samples]
= Application samples

View samples and YAML definitions that you can use to build your files.
Applications (`Application.app.k8s.io`) in {product-title} are used for viewing the application components.

For more information about creating and managing applications, see xref:../manage_applications/managing_apps.adoc#creating-and-managing-application-resources[Creating and managing application resources].

[#application-yaml-structure]
== Application YAML structure

To compose the application definition YAML content for creating or updating an application resource, your YAML structure needs to include some required fields and values.
Depending on your application requirements or application management requirements, you might need to include other optional fields and values.

The following YAML structure shows the required fields for an application and some of the common optional fields.

[source,yaml]
----
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name:
  namespace:
  resourceVersion:
  annotations:
  labels:
    app:
    chart:
    heritage:
    name:
    release:
spec:
  componentKinds:
  - group:
    kind:
  descriptor:
  selector:
    matchExpressions:
    - key:
      operator:
      values:
----

[#application-yaml-table]
== Application YAML table

|===
| Field |Value| Description

| apiVersion
| Set the value to `app.k8s.io/v1beta1`.
| Required

| kind
| Set the value to `Application` to indicate the resource is an application resource.
| Required


| metadata
|
|

|
| name: The name for identifying the application resource.
| Required


| 
| namespace: The namespace resource to use for the application.
|

|
| resourceVersion: The version of the application resource.
| 

| 
| annotations: The annotations for the application.
| Optional

|
| labels: The labels for the deployable.
| Optional


| spec
|

|
|
|componentKinds: The list of the kinds of resources to be associated with the application.
| Optional

|
| selector.matchExpressions: Label selectors for associating other Kubernetes resources with the application. 

&#8226; key: Required when defining label selectors.
The Kubernetes label key that a resource needs to match. 

&#8226; values: Required when defining label selectors.
The Kubernetes label values that a resource needs to match.
| Optional
|

|===

The spec for defining these applications is based on the Application metadata descriptor custom resource definition that is provided by the Kubernetes Special Interest Group (SIG).
You can use this definition to help you compose your own application YAML content.
For more information about this definition, see https://github.com/kubernetes-sigs/application[Kubernetes SIG Application CRD community specification].

[#application-file-samples]
== Application file samples

The definition structure for an application can resemble the following example YAML content:

[source,yaml]
----
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: nginx-app-details
  name: nginx-app-3
  namespace: ns-sub-1
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: nginx-app-details
status: {}
----
