[#creating-channels]
= Creating channels

. Compose your channel definition YAML content.
To create or update a channel resource, you must first compose the YAML file that defines the resource.
For more information about the YAML structure, including the required fields, see <<channel-yaml-structure,Channel definition YAML structure>>.
. Ensure that you create your channel in a unique namespace.
All channels need an individual namespace, except Git channels, which can share a namespace with another channel.
. Optional.
If you are creating an `Namespace` type channel, create the namespace on your hub cluster.
+
The channel type can be specified with the `spec.sourceNamespaces` and `spec.type` fields of a channel spec.
When a channel is created and pointing to a source, the channel controller maintains the promotion of the deployables at the source. The controller also synchronizes the source and channel namespaces.
+
You can define the namespace as part of your YAML definition or use the Kubernetes command line interface (`kubectl`) tool to create the namespace. To use the Kubernetes CLI tool, run the following command. Replace `namespace name` with the name for your new namespace: 

+
----
kubectl create namespace <namespace name>`
----

. Optional.
If you need or want to use a Kubernetes Secret for authenticating the access to a repository or chart by the channel, create the Kubernetes Secret resource.
You can use the Kubernetes command line interface (`kubectl`) tool to create the Kubernetes Secret by running the following command:
+
----
kubectl create secret <secret name> generic --from-literal=user --from-literal=password=
----
+
You can use a secret for authentication with only `HelmRepo`, `ObjectBucket`, and `Git` type channels.
To associate a secret with a channel, include the `spec.secretRef.name` setting in your channel YAML definition.

. Create the channel within Red Hat Advanced Cluster Management for Kubernetes.
You can use the console, the Kubernetes command line interface (`kubectl`) tool, or REST API:
 ** To use the console,
  ... From the Navigation menu, click *Manage applications*.
The *Overview* tab for all applications opens.
  ... Click the *Resources* tab.
  ... Scroll to the _Resource pipeline_ section.
From the list of buttons, find and click *Channel*.
The _Create a Channel_ editor is displayed.
  ... Enter the YAML content to define your channel or directly update the default YAML template to meet your requirements.
  ... When you are finished, click *Save* to create the channel.
Your new channel displays within the *Resource pipeline* for the corresponding applications.

+
Alternatively, you can select to create a channel when you are working with a specific application.
  ... From the *Overview* tab for all applications, click the application from the *All applications* list.
The *Overview* tab for that application opens.
  ... Click the *Resources* tab for that application.
  ... Scroll to the _Resource pipeline_ section.
From the list of buttons to the right of the resource summary cards, click *Channel*.
The _Create a Channel_ editor is displayed.
  ... Enter the YAML content to define your channel or directly update the default YAML template to meet your requirements.
  ... When you are finished, click *Save* to create the channel.
Your new channel displays within the *Resource pipeline* for the application.
 ** To use the Kubernetes CLI tool,
  ... Compose and save your channel YAML file with your preferred editing tool.
  ... Run the following command to apply your file to an apiserver.
Replace `filename` with the name of your file:
+
----
kubectl apply -f filename.yaml
----

  ... Verify that your channel resource is created, by running the following command:
+
----
kubectl get Channel
----
+
Ensure that your new channel is listed in the resulting output.
 ** To use REST API, you need to use the link:../apis/channels.json[channel POST API].
