[#create-an-application]
= Create an application

. Compose your application definition YAML content.
To create or update an application resource, you must first compose the YAML file that defines the resource.
. Create the application within {product-title}.
You can use the console, the Kubernetes command line interface (`kubectl`) tool, or REST API:
 ** To use the console,
  ... Open the console.
  ... From the Navigation menu, click *Manage applications*.
The *Overview* tab for all applications opens.
  ... Click *New application*.
The _Create application_ window opens.
  ... Update or replace the default YAML content within the editor to define your application.
  ... When you are finished adding and editing the YAML, click *Save* to create the application.
Your new application displays within the list of applications on the *Overview* tab.
 ** To use the Kubernetes CLI tool,
  ... Compose and save your application YAML file with your preferred editing tool.
  ... Run the following command to apply your file to an apiserver.
Replace `filename` with the name of your file:
+
[source,shell]
----
kubectl apply -f filename.yaml
----

  ... Verify that your application resource is created by running the following command:
+
[source,shell]
----
kubectl get Application
----
+
Ensure that your new application is listed in the resulting output.
 ** To use REST API, use the xref:../apis/api.adoc#apis[APIs].
