[#deleting-a-subscription]
= Deleting a subscription

To delete a subscription, you can use the console, the Kubernetes command line interface (`kubectl`) tool, or REST API.

To use the console, complete the following procedure:

. From the navigation, click on *Manage applications*.
. Click the *Resources* tab.
. Find your subscription resource card that you want to delete.
. Click *Options* for more actions. 
. Click *Delete subscription*
. Verify when the list of all subscriptions is refreshed that the subscription you deleted is no longer displayed.

To use the Kubernetes CLI tool:

 . Run the following command to delete the subscription from a target namespace.
 . Replace `name` and `namespace` with the name of your subscription and your target namespace:
+
----
kubectl delete appsub <name> -n <namespace>
----

 . Verify that your subscription is deleted by running the following command:
+
----
kubectl get appsub <name>
----

See the Subscription API at link:../apis/api.adoc#apis[APIs].
