[#deleting-channel]
== Deleting channel

To delete a channel, you can use the console, the Kubernetes command line interface (`kubectl`) tool, or REST API.

* To use the console, use the console search to find and delete a channel:
 .. Open the console.
 .. Click the _Search_ icon in the _Header_ to open the _Search_ page.
 .. Within the search box, filter by `kind:channel` to view all channels.
 .. Within the list of all channels, select the _Options_ menu for the channel that you want to delete.
Click *Delete channel*.
 .. When the list of all channels is refreshed, the channel is no longer displayed.
* To use the Kubernetes CLI tool,
 .. Run the following command to delete the channel from a target namespace.
Replace `name` and `namespace` with the name of your channel and your target namespace:
+
----
kubectl delete Channel <name> -n <namespace>
----

 .. Verify that your channel is deleted by running the following command:
+
----
kubectl get Channel <name>
----
* To use REST API, use the link:../apis/channels.json[channel DELETE API].