[#managing-apps-with-helm-cluster-repositories]
= Managing apps with Helm repositories

1. From the console navigation menu, click *Manage applications*.

2. Click *Create application*.

3. Enter the following values in the correct fields:
 +
 .. Name: Enter an application name. This name can be any value.
 .. Namespace: Select a namespace from the list or create one, depending on user access role.

4. Choose *Helm* from the list of repositories that you can use.
+
With the Helm repository, you can....

5. Enter the required URL path.

6. Enter values for the optional fields. 

7. Set any optional pre and post-deployment tasks.

8. To block or activate changes to your deployment during a specific time window, choose an option for _Deployment window_ and your _Time window configuration_.

You can either choose another repository or Click *Save*.

  
*Note* To use the Kubernetes CLI tool,
  ... Compose and save your application YAML file with your preferred editing tool.
  ... Run the following command to apply your file to an apiserver.
Replace `filename` with the name of your file:
+
[source,shell]
----
kubectl apply -f filename.yaml
----

  ... Verify that your application resource is created by running the following command:
+
[source,shell]
----
kubectl get Application
----
+
Ensure that your new application is listed in the resulting output.
 ** To use REST API, use the link:../apis/api.adoc#apis[APIs].
