[#managing-secrets]
= Managing secrets

You can create Kubernetes secret resources to store authorization credentials and other sensitive information for your subscriptions and application components. By storing this information as secrets, you can separate the information from the application components that require the information to improve your data security.

Samples for resources, including secrets, are located in the xref:../manage_applications/app_sample.adoc#application-samples[Application resource samples] documentation.

[#kubernetes-secrets]
== Kubernetes secrets

Secrets (`Secret`) are Kubernetes resources that you can use to store authorization and other sensitive information, such as passwords, OAuth tokens, and SSH keys. 

With secrets, you can separate and store information securely, while using subscriptions to make information available where its needed.

For example, you can use image pull secrets, which include credentials for a private Docker image registry, your Kubernetes deployment references. 

By including image pull secrets in a managed cluster namespace where a subscription to a Helm chart or deployed Pod is included, the Helm chart or pod can then use the pull secret within the namespaced scope.

When you create and include a secret within a channel for deployment to managed clusters, that secret can be deployed to only the same namespace on the target managed clusters as the subscription (the subscription uses the same namespace on the hub and managed cluster).  

All secret data is encrypted end-to-end. On the hub cluster and the managed cluster, Kubernetes encrypts its secrets at rest. During transport, TLS encryption is used.

. Create a namespace where the _channel_ and _secret_ resources will be stored on the hub cluster. You only need to complete this step one time by running the following command:

+
----
oc create project SECRET_NAMESPACE
----
+

+
Alternately, you can run `oc apply -f FILENAME.yaml` to apply the following YAML sample. Copy and paste:
+

+
----
apiVersion: v1
kind: Namespace
metadata:
  name: SECRET_NAMESPACE
----
+

. Create a channel resource. The secret namespace needs to also contain a channel resource. Run the `oc apply -f FILENAME.yaml` command to apply the following sample YAML file:

+
----
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: CHANNEL_NAME
  namespace: SECRET_NAMESPACE
spec:
  type: Namespace
  pathname: SECRET_NAMESPACE
----
+

The following YAML definition table contains values for the keys need to be provided:

|===
| Key | Value

| name 
| A unique name for the channel, constrained to the dns format.

| namespace 
| Optional. If not provided, the channel is created in the environments current namespace. Must be the same as the secret you want to subscribe. 

| pathname 
| Should be the same value as the namespace.
|===

. Create your secrets by running the `oc apply -f FILENAME.yaml` command to apply the following sample YAML file. You can create as many secrets as you need: 
// UI steps in OCP can go here from the original document

+
----
apiVersion: v1
kind: Secret
metadata:
  annotations:
      apps.open-cluster-management.io/deployables: "true"
  name: SECRET_NAME
  namespace: SECRET_NAMESPACE
data:
----
+


The following YAML definition table contains values for the keys need to be provided:

|===
| Key | Value 

|name 
| A unique name, constrained to the dns format 

| namespace 
| Optional. If not provided, the secret is created in the environments current namespace 

|data 
| This is either YAML or a large string block that you want to store securely 
|===

. Create your subscriptions.

The subscription is used to subscribe one or more secrets from the channel and needs to be created in its own namespace. This namespace is propagated to the managed cluster,  and the secrets will be created there.
The following is a YAML definition, values for the following keys need to be provided:
| key | Value |
|:--:|:--:|
| name | A unique name, constrained to the dns format |
| namespace | Optional. If not provided, the subscription is created in the environments current namespace. This namespace will also be propagated to the Managed-Cluster.
| channel |  This is a combination of the Namespace name where the Channel resource is created and the Channel name |
| placement | Defines if the subscription runs local or will target managed clusters.
### Defines a local subscription placement
```yaml
placement:
  local: true
``` 

### Defines a Managed-Cluster (remote) subscription placement
```yaml
placement:
  placementRef:
    name: PLACEMENT_NAME
    kind: PlacementRule
```

### Subscription
```yaml
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: SUBSCRIPTION_NAME
  namespace: SUBSCRIPTION_NAMESPACE
spec:
  channel: CHANNEL_NAMESPACE/CHANNEL_NAME
  placement:
   local: true
```
Also because no override is specified, all secrets in the channel will be moved.
