[#creating-and-managing-channels]
= Creating and managing channels

Create and use channels when you need to improve the continuous integration and delivery capabilities for creating and managing your Red Hat Advanced Cluster Management for Kubernetes applications.
Channels are custom resource definitions that can help you streamline deployments and separate cluster access.
Samples for all resources, including channels, are located in the xref:../manage_applications/app_resource_samples.adoc#application-resource-samples[Application resource samples] documentation.

Channels (`channel.apps.open-cluster-management.io`) define a namespace within the hub cluster and point to a physical place where resources are stored for deployment.
There are four types of channels.
Each channel differs based on the type of source location where resources are stored:

* Kubernetes namespace (`Namespace`) + Uses deployables to store Kubernetes resource templates.
Subscription for this type of channel retrieves and deploys the template.
The namespaces that the channel monitors for new or updated deployables must be on the hub cluster.
* Object store (`ObjectBucket`) + Stores Kubernetes resource YAML files.
Each YAML file includes the template portion for one resource, not the full deployable object.
An object store can be populated with a deployable object that is on the hub cluster or directly from a continuous integration pipeline, or by including the required YAML files into the object store.
* Helm repository (`HelmRepo`) + Stores Helm charts.
For information about how to structure your charts, see https://helm.sh/docs/[Helm documentation].
* Git repository (`Git`) + Stores Kubernetes resources YAML files and unpackaged Helm charts.
These resources do not need to be wrapped or represented as deployables.
The channel controllers synchronize resources as deployables automatically.

Channels are created on the hub cluster by pointing to the location where resources are stored, such as a bucket within an object store, a Helm repository, a Git repository, or a namespace on the hub cluster.
Channels are defined with a `Channel` custom resource definition (CRD).

Channels reside in their own namespace for role-based access control.
The channel namespace is made available to a subscription operator on managed clusters when the cluster subscribes to the channel.
The operator can then get the secrets to access the actual channel.
The operator needs this access to check whether a deployable meets the channel requirements.

For more information about deployables and other application resources, see link:app_resources.md[Application resources].

The channel type can be specified with the `spec.sourceNamespaces` and `spec.type` fields of a channel spec.
When a channel is created and pointing to a source, the channel controller maintains the promotion of the deployables at the source.
The controller also synchronizes the source and channel namespaces.

Learn more about channels, then see the following tasks:

* xref:creating_channel.adoc[Creating channels] 
* xref:updating_channel.adoc[Updating channels] 
* xref:deleting_channel.adoc[Deleting channels] 
* xref:managing_deployment.adoc[Managing deployments with channels] 
* xref:channel_status.adoc[Channel status and synchronization] 
