[#subscribing-git-resources]
== Subscribing Git resources 

You can subscribe Git resources to multiple namespaces. To apply these resources in the specified namespaces other than the subscription namespace, see the following procedure.

By default, when you add a resource YAML from a Git repository subscribed by an `open-cluster-management.io/subscription` application, the namespace gets created, but the configmaps are created in the subscription namespace by default, even if a different namespace is specified for the resources or no namespace is specified. To change this default behavior, follow the procedure.

. Create one or more Red Hat OpenShift Container Platform users with administrator access. 

+
These users represent administrators for `app.open-cluster-management.io/subscription`. You can also put these 
users into an OpenShift group to represent a subscription administrative group.

. Log into your Red Hat Advanced Cluster Management for Kubernetes hub cluster.

. Add the following subjects into `open-cluster-management:subscription-admin` ClusterRoleBinding.

+
For example,
+
----
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: bob
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: subscription-admin
----
+
`open-cluster-management:subscription-admin` ClusterRoleBinding has no subject initially.

. Log in your Red Hat Advanced Cluster Management for Kubernetes cluster as the subscription administrator.

. Create a subscription. If this user creates a subscription that subscribes the following sample resource YAML from a Git repository, configmap `test-configmap-1` gets created in `multins` namespace and configmap `test-configmap-2` gets created in 'default'namespace and configmap `test-configmap-3` gets created in the subscription's namespace.

See the YAML file:

+
----
---
apiVersion: v1
kind: Namespace
metadata:
  name: multins
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-1
  namespace: multins
data:
  path: resource1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-2
  namespace: default
data:
  path: resource2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-3
data:
  path: resource3
----

