[#updating-a-subscription]
== Updating a subscription

. Compose the definition YAML content for your subscription.
. Create the subscription within {product-title}.
You can use the console, the Kubernetes CLI (`kubectl`) tool, or REST API:
 ** To use the console:
  ... Open the console.
  ... From the Navigation menu, click *Manage applications*.
The *Overview* tab for all applications opens.
  ... Click the *Resources* tab.
  ... Scroll down the page to *Resource pipeline* section.
Expand the row for the application that uses the subscription that you want to edit.
  ... For the subscription that you want to update, click the *Edit* icon for the YAML.
The *Edit subscription* window opens.
  ... Edit the YAML.
  ... When you are finished, click *Save* to update the subscription.

+
Alternatively, you can select to update the subscription when you are working with a specific application.
  ... From the *Overview* tab for all applications, click the application from the *All applications* list.
The *Overview* tab for that application opens.
  ... Click the *Resources* tab for that application.
  ... Scroll down the page to *Resource pipeline* section.
  ... For the subscription that you want to update, click the *Edit* icon for the YAML.
The *Edit subscription* window opens.
  ... Edit the YAML.
  ... When you are finished, click *Save* to update the subscription.

+
You can also use the console search to find and edit a subscription:
  ... Click the *Search* icon in the Header.
  ... Within the search box, filter by `kind:subscription` to view all subscriptions.
  ... Within the list of all subscriptions, click the subscription that you want to update.
The YAML for the subscription is displayed.
  ... Click *Edit* to enable editing the YAML content.
  ... When you are finished your edits, click *Save*.
Your changes are saved and applied automatically.
 ** To use the Kubernetes CLI tool, the steps are the same as for creating a subscription.
 ** To use REST API, use the link:../apis/api.adoc#apis[APIs].
