[#update-a-placement-rule]
= Update a placement rule

To update a placement rule that is a separate resource, you can use the console, the Kubernetes command line interface (`kubectl`) tool, or REST API.

* To use the console to edit a placement rule, complete the following steps:
 .. Open the console.
 .. Click the *Search* icon in the Header.
 .. Within the search box, filter by `kind:placementrule` to view all placement rules.
 .. Within the list of all placement rules, click the placement rule that you want to update.
The YAML for the rule is displayed.
 .. Click *Edit* to enable editing the YAML content.
 .. When you are finished your edits, click *Save*.
Your changes are saved and applied automatically.

+
Alternatively, you can select to edit the YAML from the Applications dashboard resource pipeline table.
 .. From the Navigation menu, click *Manage applications*.
The *Overview* tab for all applications opens.
 .. Click the *Resources* tab.
 .. Scroll to the *Resource pipeline* section.
Within the table that lists your applications, expand the row for the application that includes the subscription that is assigned the placement rule.
 .. From the expanded view for the application, you can see the available subscriptions for each channel.
The details for each subscription include any assigned placement rule.
Click the link for the placement rule to open the _Edit placement rule_ editor.
The YAML for the rule is displayed.
 .. When you are finished your edits, click *Save*.
Your changes are saved and applied automatically.
* To use the Kubernetes CLI tool, the steps are the same as for creating a placement rule.
* To use REST API, you need to use the link:../apis/api.adoc#apis[APIs].

To update a placement rule that is defined within the definition for a deployable or subscriptions, the steps are the same as for updating that resource.