[#updating-a-channel]
= Updating a channel

. Compose the definition updates for your channel.
For more information about the YAML structure, including the required fields, see <<channel-yaml-structure,Channel definition YAML structure>>.
. Update the definition.
You can use the console, the Kubernetes command line interface (`kubectl`) tool, or REST API:
 ** To use the console,
  ... Open the console.
  ... From the Navigation menu, click *Manage applications*.
The *Overview* tab for all applications opens.
  ... Click the *Resources* tab.
  ... Scroll down the page to *Resource pipeline* section.
Click the *YAML* edit icon for channel that you want to update.
The *Edit channel* window opens.
  ... Edit the YAML for the channel.
  ... When you are finished, click *Save* to update the channel.

+
You can also use the console search to find and edit a channel:
  ... From the Navigation menu, click *Search*.
  ... Within the search box, filter by `kind:channel` to view all channels.
  ... Within the list of all channels, click the channel that you want to update.
The YAML for the channel is displayed.
  ... Click *Edit* to enable editing the YAML content.
  ... When you are finished your edits, click *Save*.
Your changes are saved and applied automatically.
 ** To use the Kubernetes CLI tool, the steps are the same as for creating a channel.
 ** To use REST API, use the link:../apis/channels.json[channel PATCH API].