:_mod-docs-content-type: REFERENCE

[#backup-virt-configmap-ref]
= Virtualization policy _ConfigMap_ overview

[role="_abstract"]
When you install the policies on the hub cluster, the following `ConfigMap` resources are created on the hub cluster, in the `open-cluster-management-backup` namespace. When you place the virtualization policies on the hub or managed cluster, these `ConfigMap` resources define the backup and restore configuration for the virtualization policies. 

.`ConfigMap` properties for the `acm-dr-virt-install` policy
|===
| Name | Description | Type | Default value | Optional 
| `channel`| The channel defaults to the supported {oadp} version, which is based on the version of the {ocp-short} cluster. Use this property to overwrite the default value.| String | None| Yes
| `channelName`| {oadp} channel name. Set this property for custom installation, for example: `offline install`.| String | `redhat-oadp-operator`| Yes
| `subscriptionSource`| {oadp} subscription. Set this property for custom installation, for example: `offline install`.| String | `redhat-operators`| Yes
| `subscriptionSourceNamespace`| {oadp} subscription source. Set this property for custom installation, for example: `offline install`.| String | `openshift-marketplace`| Yes
| `subscriptionStartingCSV`| {oadp} subscription startingCSV.| String | None| Yes
| `subscriptionInstallPlanApproval`|{oadp} install plan. | String | Automatic| Yes
| `backupNS`| Namespace where {oadp} gets installed on the managed cluster.| String | None| No
| `credentials_hub_secret_name`| Name of the {oadp} secret that you use on the managed cluster.
A Secret with this name must exist on the hub cluster in the `open-cluster-management-backup` namespace. The install policy moves this secret to the hub cluster within the specified `backupNS` namespace.| String | None| No
| `credentials_name`| Name of the secret used by the {oadp} `DataProtectionApplication` resource on the managed cluster, when setting the Velero credential name.| JSON| None| No
| `dpa_name`| Name of the `DataProtectionApplication` resource that gets created on the managed cluster.| String | None| No
| `dpa_spec`| Valid JSON defining the `DataProtectionApplication` spec when created on the managed cluster.| JSON | None| No
|===

.`ConfigMap` properties for the `acm-dr-virt-backup` policy
|===
| Name | Description | Type | Default value | Optional 
| `scheduleTTL`|Backup expiration time.| String |`24h0m0s`| Yes
| `schedule_paused`| Set to `True` to pause the virtualization backup schedule. | String | False | Yes
| `schedule_hub_config_name`| Name of the `ConfigMap` that is used to define the valid cron jobs schedules. A `ConfigMap` with this name must exist on the hub cluster in the `open-cluster-management-backup` namespace.| String | None| Yes
|===

.`ConfigMap` properties for the `acm-dr-virt-restore` policy
|===
| Name | Description | Type | Default value | Optional 
| `restore_hub_config_name`| Name of the ConfigMap that is used to define the restore operation. This name must exist on the hub cluster in the `open-cluster-management-backup` namespace| String | None | No
|===

* Example of a `acm-dr-virt-schedule-cron` `ConfigMap`

+
Use the `acm-dr-virt-schedule-cron` `ConfigMap` to define the valid cron job schedules to use when you are scheduling a virtual machine backup. The `acm-dr-virt-schedule-cron` `ConfigMap` is created by the hub cluster backup component in the `open-cluster-management-backup` namespace and includes the following YAML: 

+
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
    metadata:
        name: acm-dr-virt-schedule-cron
        namespace: open-cluster-management-backup
    data:
        hourly: "0 */1 * * *"
        every_2_hours: "0 */2 * * *"
        every_3_hours: "0 */3 * * *"
        every_4_hours: "0 */4 * * *"
        every_5_hours: "0 */5 * * *"
        every_6_hours: "0 */6 * * *"
        twice_a_day: "0 */12 * * *"
        daily_8am: "0 8 * * *"
        every_sunday: "0 0 * * 0"
----

* Example `VirtualMachine` with a daily backup schedule

+
You can use any of the schedules created by the `acm-dr-virt-schedule-cron` `ConfigMap` to set the backup schedule for a `kubevirt.io.VirtualMachine`. For example, if you want to backup a virtual machine every day at 8am, add the following label to the virtual machine resource:

+
[source,yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-name
  labels:
    cluster.open-cluster-management.io/backup-vm: daily_8am
----

+
Since this `acm-dr-virt-schedule-cron` `ConfigMap` is created and managed by the hub cluster backup component, you cannot change any of the existing cron properties or delete them. The properties are recreated when the content is reconciled. You can only add new properties to the existing ones. For example, if you want to create a cron job to run every Saturday, add the following label to the existing `acm-dr-virt-schedule-cron` properties: `every_sunday: "0 0 * * SAT"`. 

* Example of complete restore operation in the `acm-dr-virt-restore-config` `ConfigMap`

+
Use the `acm-dr-virt-restore-config` `ConfigMap` to define the restore operations to be implemented by the `acm-dr-virt-restore` policy. Use the hub cluster backup component in the `open-cluster-management-backup` namespace to create the `ConfigMap`. For an example of a complete restore operation, see the following YAML sample:

+
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
 name: acm-dr-virt-restore-config
 namespace: open-cluster-management-backup
data:
 2a054d24-3235-4249-9c81-f58ebc6110c7_backupName: acm-rho-virt-schedule-every-10-hours-20250120230438
 2a054d24-3235-4249-9c81-f58ebc6110c7_restoreName: restore-20250120230438
 2a054d24-3235-4249-9c81-f58ebc6110c7_vmsUID: 2a054d24-3235-4249-9c81-f58ebc6110c7
 2a054d24-3235-4249-9c81-f58ebc6110c7_namespaceMapping: backup-ns-1=restore-ns-1{{ backup-ns-2=restore-ns-2}}
----
** `2a054d24-3235-4249-9c81-f58ebc6110c7` is the cluster ID where the restore operation is complete. `acm-rho-virt-schedule-every-10-hours-20250120230438` is the name of the backup that is used for the restore operation example. 
** `restore-20250120230438` is the name of the `Restore` resource that is created as a result of this restore operation.
** `2a054d24-3235-4249-9c81-f58ebc6110c7` is the UID of the virtual machine backed up with the `acm-rho-virt-schedule-every-10-hours-20250120230438` backup to be restored.
** `namespaceMapping` is an optional property and is used to restore resources in a different namespace than the initial resource. Any source namespaces not included in the map is restored into namespaces of the same name. `backup-ns-1=restore-ns-1 backup-ns-2=restore-ns-2` is a space separated list of namespace mapping. In this sample, backup resources created within the `backup-ns-1` namespace are restored within the `restore-ns-1` namespace. The `restore-ns-1` is created on the restore cluster if it does not exist. Similarly, resources created within the `backup-ns-2` are restored within the `restore-ns-2` namespace.

* Virtualization policies for your restore operations scenarios

** If you set the `clusterID_restoreName` property from the `acm-dr-virt-restore-config` `ConfigMap` to an empty value, then the restore resource created by the `acm-dr-virt-restore` policy on the cluster with `clusterID` gets deleted.
** If you set the `clusterID_restoreName` property from the `acm-dr-virt-restore-config` `ConfigMap` to a non-empty value, then the `acm-dr-virt-restore` policy creates a Velero `Restore` resource . The name of the Velero restore resource matches the `clusterID_restoreName` value. If the restore resource with this name is deleted from the restore cluster, the `acm-dr-virt-restore` policy recreates the resource, which results in the restore operation running again.

* Important considerations for your restore operations scenarios

** Do not delete the restore resource if you do not want to run the restore again. 
** Remove the value for the `clusterID_restoreName` parameter on the `acm-dr-virt-restore-config` `ConfigMap` when the restore operation gets verified to start. Doing this prevents you from having to rerun the restore operation if the `acm-dr-virt-restore` policy is disabled and enabled again. When you disable the `acm-dr-virt-restore` policy, all resources created by it on the restore cluster get cleaned up and recreated when you enable the policy again.

.Additional resources

* xref:../backup_virt_define_configmap.adoc#backup-virt-define-configmap[Defining policies with _ConfigMap_ resources] 
