:_mod-docs-content-type: PROCEDURE

[#backup-restore-vm]
= Backing up and restoring a virtual machine
//this is a task that should stand alone maybe with the other tasks?

You can back up virtual machines that run on a cluster or restore a virtual machine on a cluster by completing the following steps: 

.Procedure

. Enable the backup component on the hub cluster by setting the `cluster-backup` parameter in `MultiClusterHub` to `true`.
. To place the policies on the `cluster-name` cluster, add the `acm-virt-config` label to the `ManagedCluster` resource by applying the following YAML sample: 

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
 name: cluster-name
 labels:
   acm-virt-config: acm-dr-virt-config
----
* The `acm-dr-virt-config` that passes through the label annotation is a `acm-virt-config` ConfigMap. Read the `acm-dr-virt-config` ConfigMap section to understand how to configure {oadp} and backup storage location.

. Complete the following steps, depending on whether you want to backup or restore your virtual machine: 
.. Back up your virtual machine by adding the `cluster.open-cluster-management.io/backup-vm` to the `kubevirt.io.VirtualMachine` resource. Your `kubevirt.io.VirtualMachine` resource might resemble the following YAML sample:

+
[source,yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-name
  labels:
    cluster.open-cluster-management.io/backup-vm: daily_8am
----

.. Restore your virtual machine by updating the `acm-dr-restore-config` ConfigMap as described in the `acm-dr-virt-restore-config` section. 
