[#migrate-vm]
= Migrating virtual machines between clusters (Technology Preview)

Migrating virtual machines help you move resources during cluster upgrades, any time you need to clear a node for maintenance, or configuration changes. When you enable migration, the Kubevirt HyperConverged Operator is automatically installed on your managed clusters with the `acm/cnv-operator-install` label. The Migration Toolkit for Virtualization Operator is installed on your hub cluster.

.Prerequsites

- *Required access:* Cluster adminstrator
- You must have access to the `openshift-cnv` namespace.
- You have the latest version of {ocp-short} installed.
//is it required for users to have the latest version of OCP installed to complete migration on the hub cluster? This helps determine what version of OCP i need to link to

To start migration for virtual machines complete the following steps:

. Enable `mtv-integrations-preview` component for the integration of {ocp-virt}. 
.. Run the following command to edit your `multiclusterhub` instance:

+
[source,bash]
----
oc edit MultiClusterHub multiclusterhub -n open-cluster-management
----

.. From the `components` section, set the `enabled` parameter to `true` for the `cnv-mtv-integrations-preview` component.

. Verify that the Kubevirt `HyperConverged` Operator and Migration Toolkit for Virtualization add-on Operator are available on your cluster.
//is there a way for the user to check this from the CLI? Not sure if we will doc UI steps

. To designate a cluster as a source or target for the virtual machine migration, apply the following label to your clusters: `acm/cnv-operator-install: "true"`.

. Enable the Kubevirt cross-cluster migration from the {ocp-virt-short} console.
.. From the navigation menu, select *Virtualization* > *Overview*.
.. To access the preview features, click *Settings* > *Preview Features*.
.. Set _Enable Kubevirt cross cluster migration_ to `true`.

. _Optional:_ Configure your network for the live migration.
.. To configure your network for managed clusters within your `HyperConverged` resource, update the `customizedVariables` section with the network key and value to your `cnv-config` `AddOnDeploymentConfig` resource. Your `AddOnDeployment` resource might resemble the following sample:

+
[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: cnv-config
  namespace: open-cluster-management
spec:
  agentInstallNamespace: openshift-cnv
  customizedVariables:
    - name: LIVE_NETWORK_KEY
      value: network
    - name: LIVE_NETWORK_VALUE
      value: {{ NetworkAttachmentDefinition name like lm-network }}
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: kubevirt-hyperconverged-operator
  namespace: {{ managedcluster name }}
spec:
  installNamespace: openshift-cnv
  configs:
    - group: addon.open-cluster-management.io
      resource: addondeploymentconfigs
      name: cnv-config
      namespace: open-cluster-management
----

[#mig-add-res]
== Additional resources 

- To learn how to move virtual machines to other nodes in the cluster, see https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/virtualization/live-migration#virt-preserving-lm-perms_virt-about-live-migration[Live migration].
