:_mod-docs-content-type: PROCEDURE

[#migrate-virt-machines]
= Migrating virtual machines between clusters

[role="_abstract"]
Complete the following steps to enable virtual machine migration between clusters and verify that the required operators are available.

.Procedure

. Enable `cnv-mtv-integrations` component for the integration of {ocp-virt}. 
.. Run the following command to edit your `multiclusterhub` instance:

+
[source,bash]
----
oc edit MultiClusterHub multiclusterhub -n open-cluster-management
----

.. From the `components` specification, set the `enabled` parameter to `true` for the `cnv-mtv-integrations` component.

. Verify that the migration toolkit for virtualization is available on your cluster. Run the following command:

+
[source,bash]
----
oc get clustermanagementaddon mtv-operator  -o jsonpath='{.status.installProgressions[*].conditions[*].reason}
----
  
. Verify that the `kubevirt-hyperconverged` resource is available on your cluster with the following command:
  
+
[source,bash]
----
oc get clustermanagementaddon kubevirt-hyperconverged -o jsonpath='{.status.installProgressions[*].conditions[*].reason}
----
  
. Verify that the `kubevirt-hyperconverged-operator` is available on your cluster with the following command:

+
[source.bash]
----
oc get clustermanagementaddon kubevirt-hyperconverged-operator -o jsonpath='{.status.installProgressions[*].conditions[*].reason}
----

. To designate a cluster as a source or target for the virtual machine migration, apply the following label to your clusters: `acm/cnv-operator-install: "true"`.

. *Optional:* If you don't see the Virtualization console, run the following command:

+
[source,bash]
----
oc -n openshift-cnv patch hco kubevirt-hyperconverged --type='merge' -p '{"spec":{"featureGates":{"decentralizedLiveMigration":true}}}'
----

. *Optional:* If you want to further configure your environment in the managed cluster, edit the `HyperConverged` resource.
