[#migrate-vm]
= Migrating virtual machines between clusters (Technology Preview)

//still working
Migrating virtual machines help you transition resources during cluster upgrades or any time you need to clear a node for maintenance or configuration changes. When you enable migration, the Kubevirt `HyperConverged` Operator is automatically installed on your managed clusters with the `acm/cnv-operator-install` label. The Migration Toolkit for Virtualization add-on Operator is installed on your hub cluster.

.Prerequsites

- *Required access:* Cluster adminstrator
- You must have access to the `openshift-cnv` namespace.
- You have the latest version of {ocp-short} installed.
//is it required for users to have the latest version of OCP installed to complete migration on the hub cluster?

To start migration for virtual machines complete the following steps:

. Enable `mtv-integrations-preview` component for the integration of {ocp-virt}. 
.. Run the following command to edit your `multiclusterhub` instance:

+
[source,bash]
----
oc edit MultiClusterHub multiclusterhub -n open-cluster-management
----

.. From the `components` section, set the `enabled` parameter to `true` for the `mtv-integrations-preview` component.

. Verify that the Kubevirt `HyperConverged` Operator and Migration Toolkit for Virtualization add-on Operator are available on your cluster.
//is there a way for the user to check this from the CLI? Not sure if we will doc UI steps

. To designate a cluster as a source for the virtual machine migration, apply the following label to your clusters: `acm/cnv-operator-install: "true"`.

. To enable the Kubevirt cross-cluster migration

. _Optional:_ Configure your network for the live migration.
.. Update your `HyperConverged` resource by adding 

[#mig-add-res]
== Additional resources 

- Live migration: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/virtualization/live-migration#virt-preserving-lm-perms_virt-about-live-migration 