[#migrate-vm]
= Migrating virtual machines between clusters

Migrating virtual machines helps you move resources during cluster upgrades, times when you need to clear a node for maintenance, or during configuration changes. When you enable migration, the {ocp-virt} is automatically installed on your managed clusters with the `acm/cnv-operator-install` label. The migration toolkit for virtualization is also installed on your hub cluster.

*Required access:* Cluster administrator

.Prerequisites 

Before you perform migration operations or access the Fleet Virtualization console, ensure that the following requirements are met:

. Enable fine-grained RBAC on your clusters to assign and use the required roles. See xref:../secure_clusters/fine_grain_rbac_enable.adoc#fine-grain-enable[Enabling fine-grained role-based access control for virtualization].
. You need access to the `openshift-cnv` namespace.
. You must have the `kubevirt.io:admin` role on both the source and target clusters.
. Install the latest supported version of {ocp-short}. See the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/[OpenShift Container Platform overview].
. Understand the required roles for migration operations and access to the Fleet Virtualization console. See the following table for more information about the required roles:

+
.Required roles table
|===
| Role | Location | Purpose
| `acm-vm-fleet:admin` | Hub cluster | Perform migration operations and access the Fleet Virtualization console.
| `acm-vm-extended:admin` | Source and target clusters | Manage virtual machine extended and related resources.
| `acm-vm-cluster-migration:view` | Target cluster | Perform mandatory cluster version and {ocp-virt} operator readiness checks.
|===

.Procedure

To start migration for virtual machines complete the following steps:

. Enable `cnv-mtv-integrations` component for the integration of {ocp-virt}. 
.. Run the following command to edit your `multiclusterhub` instance:

+
[source,bash]
----
oc edit MultiClusterHub multiclusterhub -n open-cluster-management
----

.. From the `components` specification, set the `enabled` parameter to `true` for the `cnv-mtv-integrations` component.

. Verify that the migration toolkit for virtualization is available on your cluster. Run the following command:

+
[source,bash]
----
oc get clustermanagementaddon mtv-operator  -o jsonpath='{.status.installProgressions[*].conditions[*].reason}
----
  
. Verify that the `kubevirt-hyperconverged` resource is available on your cluster with the following command:
  
+
[source,bash]
----
oc get clustermanagementaddon kubevirt-hyperconverged -o jsonpath='{.status.installProgressions[*].conditions[*].reason}
----
  
. Verify that the `kubevirt-hyperconverged-operator` is available on your cluster with the following command:

+
[source.bash]
----
oc get clustermanagementaddon kubevirt-hyperconverged-operator -o jsonpath='{.status.installProgressions[*].conditions[*].reason}
----

. To designate a cluster as a source or target for the virtual machine migration, apply the following label to your clusters: `acm/cnv-operator-install: "true"`.

. Enable cross-cluster migration from the {ocp-virt-short} console. Complete the following steps:
.. From the navigation menu, select *Virtualization* > *Overview*.
.. To access the preview features, click *Settings* > *Preview Features*.
.. Set `Enable Kubevirt cross cluster migration` to `true`.

. *Optional:* If you want to further configure your environment in the managed cluster, edit the `HyperConverged` resource.

[#mig-add-res]
== Additional resources 

- To learn how to move virtual machines to other nodes in the cluster, see https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/virtualization/live-migration#virt-preserving-lm-perms_virt-about-live-migration[Live migration].
