[#deploying-submariner-console]
= Deploying Submariner with the console

The `submariner-addon` component is a *Technology Preview* feature.

You can deploy Submariner on {ocp} managed clusters that are deployed on Amazon Web Services, Google Cloud Platform, and VMware vSphere by using the {product-title} console. To deploy Submariner on other providers, follow the instructions in xref:../services/deploy_submariner_api.adoc#deploying-submariner-apis[Deploying Submariner with APIs]. Complete the following steps to deploy Submariner with the {product-title} console:

*Required access:* Cluster administrator

. From the console navigation menu, select *Infrastructure* > *Clusters*.

. On the Clusters page, select the *Cluster sets* tab. The clusters that you want enable with Submariner must be in the same cluster set. 

. If the clusters where you want to deploy Submariner are already in the same cluster set, skip to step 5 to deploy Submariner.

. If the clusters on which you want to deploy Submariner are not in the same cluster set, create a cluster set for them by completing the following steps: 

.. Select *Create cluster set*.

.. Name the cluster set, and select *Create*.

.. Select *Manage resource assignments* to assign clusters to the cluster set.

.. Select the managed clusters that you want to connect with Submariner to add them to the cluster set.

.. Select *Review* to view and confirm the clusters that you selected.

.. Select *Save* to save the cluster set, and view the resulting cluster set page.

. On the cluster set page, select the *Submariner add-ons* tab.

. Select *Install Submariner add-ons*.

. Select the clusters on which you want to deploy Submariner. 

. Enter the following information in the *Install Submariner add-ons* wizard:
+
* `AWS Access Key ID` - This field is only visible when you import an AWS cluster.
* `AWS Secret Access Key` - This field is only visible when you import an AWS cluster.
* `Google Cloud Platform service account JSON key` - This field is only visible when you import a Google Cloud Platform cluster.
* `Instance type` - The Amazon Web Services EC2 instance type of the gateway node that is created on the managed cluster. The default value is `m5n.large`. This field is only visible when your managed cluster environment is AWS.
* `IPsec IKE port` - The Submariner creates the IPsec tunnel between the clusters. This port allows Internet Key Exchange (IKE) protocol traffic on the Submariner gateway node to set up the IPsec tunnel. The default value is port `500`. If your managed cluster environment is VMware vSphere, ensure that this port is opened on your firewalls.
* `IPsec NAT-T port` - The Submariner creates the IPsec tunnel between the clusters.  This port is used for IPsec NAT traversal. The default value is port `4500`. If your managed cluster environment is VMware vSphere, ensure that this port is opened on your firewalls.
* `Gateway count` - The number of worker nodes that are used to deploy the Submariner gateway component on your managed cluster. The default value is `1`. If the value is greater than 1, the Submariner gateway HA is automatically enabled.
* `Cable driver` - The Submariner gateway cable driver.

. Select *Next* at the end of the wizard to move to the wizard for the next cluster, and complete the wizard for each of the remaining clusters that you selected. 

. Verify your configuration for each managed cluster.

. Click *Install* to deploy Submariner on the selected managed clusters. 
+
It might take several minutes for the installation and configuration to complete. You can check the Submariner status in the list on the *Submariner add-ons* tab.
+
* `Connection status` indicates how many Submariner connections are established on the managed cluster. 
+
* `Agent status` indicates whether Submariner is successfully deployed on the managed cluster. The console might report a status of `Degraded` until it is installed and configured. 
+
* `Gateway nodes labeled` indicates how many worker nodes are labeled with the Submariner gateway label: `submariner.io/gateway=true` on the managed cluster.
