[#volsync]
= Replicating persistent volumes with VolSync (Technology Preview)

VolSync is a Kubernetes operator that enables asynchronous replication of persistent volumes within a cluster, or across clusters with storage types that are not otherwise compatible for replication. It uses the Container Storage Interface (CSI) to overcome the compatibility limitation. After deploying the VolSync operator in your {ocp} environment, you can leverage it to create and maintain backup versions of your persistent data.

**Note:** VolSync does not meet the requirements of the FIPS standard. 

There are three methods that you can use to replicate when you use VolSync, which depend on the number of synchronization locations that you have. The Rsync method is used for this example. For information about the other methods and more information about Rsync, see https://volsync.readthedocs.io/en/latest/usage/index.html[Usage] in the VolSync documentation.  

* Rsync replication is a one-to-one replication of persistent volumes, and is likely to be the most commonly used. This is used for replicating data to a remote site. 

[#volsync-prereq]
== Prerequisites

Before installing VolSync on your clusters, you must have the following requirements:

* A configured {ocp} environment running a {product-title-short} version 2.4, or later, hub cluster.

* At least two configured clusters that are managed by the same {product-title-short} hub cluster.

[#volsync-install-clusters]
== Installing VolSync on the managed clusters

To enable VolSync on two clusters in your environment, you must install it on both the source and the target managed clusters. Complete the following steps to leverage the policy function in {product-title-short} to install VolSync:

. Deploy the required VolSync resources to the clusters.

.. In the {product-title-short} console navigation, select *Governance*. 

.. Select *Create policy* to start a new policy. The policy that you create uses an existing policy to install the VolSync resources.

.. Complete the required information for your application.

... Enter `policy-persistent-data-management` as the name of your application. This name corresponds to the policy that is created in the Git repository that deploys the VolSync content on all of your clusters that are managed by the hub. 

... Select the option for a Git repository, so you can reference the policy file.

... Use the following URL for the Git repository: \https://github.com/open-cluster-management/policy-collection.git.

... Select the `main` branch. 

... Add `stable/CM-Configuration-Management` for the path.

... Make sure you select the option to *Deploy to all online clusters and local-cluster*. This ensures that it is included on all of your managed clusters. 

.. Select `Save` to save your application. Within a few minutes, the application will start deploying to all of the clusters that are managed by your {product-title-short} hub cluster. 

. Change your default CSI configuration to your VolSync CSI instance. 
+
* Your steps might resemble the following procedure for an Amazon Web Services environment:

.. Change your default `StorageClass` by entering the following commands: 
+
----
kubectl annotate sc/gp2 storageclass.kubernetes.io/is-default-class="false" --overwrite
kubectl annotate sc/gp2-csi storageclass.kubernetes.io/is-default-class="true" --overwrite
----

.. Install a `VolumeSnapshotClass` by running the following command:
+
----
kubectl create -f - << SNAPCLASS
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: gp2-csi
driver: ebs.csi.aws.com
deletionPolicy: Delete
SNAPCLASS
----

.. Set `gp2-csi` as your default `VolumeSnapshotClass` by running the following command:
+
----
kubectl annotate volumesnapshotclass/gp2-csi snapshot.storage.kubernetes.io/is-default-class="true"
----
+
Your CSI is now configured on an Amazon Web Services environment.

* The steps might resemble the following for an Google Cloud Platform environment:

.. Change your default `StorageClass` by entering the following commands: 
+
----
kubectl annotate sc/standard storageclass.kubernetes.io/is-default-class="false" --overwrite
kubectl annotate sc/standard-csi storageclass.kubernetes.io/is-default-class="true" --overwrite
----

.. Install a `VolumeSnapshotClass` by running the following command:
+
----
kubectl create -f - << SNAPCLASS
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: gp2-csi
driver: ebs.csi.aws.com
deletionPolicy: Delete
SNAPCLASS
----

.. Set `standard-csi` as your default `VolumeSnapshotClass` by running the following command:
+
----
kubectl annotate volumesnapshotclass/standard-csi snapshot.storage.kubernetes.io/is-default-class="true"
----
+
Your CSI is now configured on a Google Cloud Platform environment.

. For Rsync-based replication, configure a custom resource on the source and target clusters.

.. Add the following minimal custom resource information to the YAML file of your target cluster:
+
[source,yaml]
----
---
apiVersion: volsync/v1alpha1
kind: ReplicationDestination
metadata:
  name: <destination_name>
  namespace: <destination_namespace>
spec:
  rsync:
    copyMethod: Snapshot
    capacity: 10Gi
    accessModes: ["ReadWriteOnce"]
----
+
Replace `destination_name` with the name of your destination volume.
+
Replace `destination_namespace` with the name of the namespace where your destination is located.

.. Add the following minimal custom resource information to the YAML file of your source cluster:
+
[source,yaml]
----
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: <name>
  namespace: <source_namespace>
spec:
  sourcePVC: <persistent_volume_claim>
  trigger:
    schedule: "*/5 * * * *"
  rsync:
    sshKeys: <volsync-rsync-destination-src-database-destination>
    address: <source.host.com>
    copyMethod: Clone
----
+
Replace `name` with a unique name for your source volume.
+
Replace `source_namespace` with the name of the namespace where your source is located.
+
Replace `persistent_volume_claim` with the name of your source claim.
+
Replace `volsync-rsync-destination-src-database-destination` with the keys that are generated in the `.status.rsync.address` field of the `ReplicationDestination` when it is created. 
+
Replace `source.host.com` with the host address of your source cluster. 


You can now set up the synchronization method of the persistent volume.

[#volsync-start]
== Scheduling your synchronization

You have a few options to select from when determining how you start your replications: always running, on a schedule, or manually. Scheduling your replications is an option that is the option that is often selected. 

The *Schedule* option runs replications at scheduled times. A schedule is defined by a `cronspec`, so the schedule can be configured as intervals of time or as specific times. The order of the schedule values are:

`"minute (0-59) hour (0-23) day-of-month (1-31) month (1-12) day-of-week (0-6)"`

The replication starts when the scheduled time occurs. Your setting for this replication option might resemble the following content:
+
[source,yaml]
----
spec:
  trigger:
    schedule: "*/6 * * * *"
----

After enabling one of these methods, your synchronization schedule runs according to the method that you configured. 
