[#gatekeeper-operator-installation-{gk-tag}]
== {gk-operator} installation

Use the {gk-operator} policy to install the {gk-operator} and Gatekeeper on a managed cluster. Learn to create, view, and update your {gk-operator} policies in the following sections.

*Required access*: Cluster administrator

- <<install-gatekeeper-operator-policy-{gk-tag},Installing Gatekeeper using a {gk-operator} policy>>
- <<creating-a-gatekeeper-policy-from-the-console-{gk-tag},Creating a Gatekeeper policy from the console>>
- <<gatekeeper-operator-sample-{gk-tag},{gk-operator} custom resource>>
- <<../gatekeeper_yaml_table.adoc#gatekeeper-yaml-table-{gk-tag},Gatekeeper YAML table>>
- <<upgrading-gatekeeper-gatekeeper-operator-{gk-tag},Upgrading Gatekeeper and the {gk-operator}>>
- <<updating-gatekeeper-operator-policy-{gk-tag},Updating {gk-operator} policy>>
- <<deleting-gatekeeper-operator-policy-{gk-tag},Deleting {gk-operator} policy>>
- <<uninstalling-gatekeeper-{gk-tag},Uninstalling Gatekeeper policy, Gatekeeper, and {gk-operator} policy>>

[#install-gatekeeper-operator-policy-{gk-tag}]
=== Installing the {gk-operator}

{gk-operator} is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[{ocp-short} documentation] for more information.

During the install, the operator group and subscription pull the {gk-operator} to install it on the cluster. Create a Gatekeeper custom resource to configure and deploy Gatekeeper. View the <<gatekeeper-operator-sample-{gk-tag},{gk-operator} custom resource>> sample.

include::gatekeeper_yaml_table.adoc[]

[#gatekeeper-audit-sync-{gk-tag}]
=== Configuring _auditFromCache_ for sync details

The {gk-operator} exposes a setting in the custom resource definition within the `auditFromCache` audit, which is disabled by default. If you enable `auditFromCache`, then you need to set `config.gatekeeper.sh` for the sync details. See link:https://open-policy-agent.github.io/gatekeeper/website/docs/audit/#configuring-audit[Configuring Audit] in the Gatekeeper documentation.

ifeval::[{gk-y-ver} >= 14]
The recommended setting for `auditFromCache` is `Automatic`. In this mode, the {gk-operator} collects resources from constraints that users install and then inserts those resources into the config resource. If the config resource does not exist, the operator creates it.

. Set `auditFromCache` to `Automatic` in the `Gatekeeper` resource, as displayed in the following example:

+
[source,yaml]
----
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper 
metadata: 
  name: gatekeeper 
spec: 
  audit: replicas: 2 
    logLevel: DEBUG 
    auditFromCache: Automatic
----

+
See that the {gk-operator} adds a `syncOnly` parameter section to the config file in the following example:

+
[source,yaml]
----
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
 name: config
 namespace: "openshift-gatekeeper-system"
spec:
 sync:
   syncOnly:
   - group: ""
     version: "v1"
     kind: "Namespace"
   - group: ""
     version: "v1"
     kind: "Pod"
----

. To get the explanation of the `sync` setting, run the following command from your terminal:

+
[source,bash]
----
oc explain gatekeeper.spec.audit.auditFromCache
----
endif::[]

[#additional-resources-gk-operator-{gk-tag}]
== Additional resources

- See xref:../gatekeeper_install_policy.adoc#gatekeeper-operator-installation#gatekeeper-policy[Installing the {gk-operator} using {product-title-short}] for details about deploying the {gk-operator} using an `OperatorPolicy` from the governance framework.

- See xref:../gatekeeper_policy_constraints.adoc#gatekeeper-policy[Integrating Gatekeeper constraints and constraint templates with {product-title-short}] for details about deploying Gatekeeper constraints and `ConstraintTemplates` using the governance framework.

- See the link:https://github.com/open-cluster-management-io/policy-collection/blob/main/stable/CM-Configuration-Management/policy-gatekeeper-operator-downstream.yaml[Policy Gatekeeper] sample.

- See link:https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md#parameters[Gatekeeper Helm Chart] for an explanation of the optional parameters that can be used for the {gk-operator} policy.

- For a list of topics to integrate third-party policies with the product, see xref:../governance/third_party_policy_intro.adoc#integrate-third-party-policy-controllers[Integrate third-party policy controllers]. 
