:gk-x-ver: 3
:gk-y-ver: 14
:gk-tag: {gk-x-ver}_{gk-y-ver}
:gk-version: {gk-x-ver}.{gk-y-ver}
[#gatekeeper-operator-v{gk-tag}]
= {gk-operator} v{gk-version}

[#whats-new-{gk-tag}]
== What's new in {gk-operator} v{gk-version}

* Gatekeeper is updated to the equivalent Open Policy Agent Gatekeeper version v3.14.
* The `Automatic` setting is added to the `auditFromCache` parameter. With this setting, the operator parses the constraints and populates the `spec.sync.syncOnly` field in the Gatekeeper `Config` object with the required resources for the constraints to function with the cache.
* The `operations` parameter is added to the webhook configuration in the operator, allowing configuration of API operations that the webhook responds to, in particular this allows you to add the `DELETE` operation. (See the documentation about link:https://open-policy-agent.github.io/gatekeeper/website/docs/customize-admission/#enable-validation-of-delete-operations[Validation of Delete Operations] for caveats on add `DELETE`.)
* Logging mutations (`logMutations`) and mutation annotations (`mutationAnnotations`) configurations are added to the operator configuration.

include::create_gatekeeper.adoc[{gk-operator} installation]
