:_mod-docs-content-type: PROCEDURE

[#creating-gcp-credential-api]
= Creating a credential for Google Cloud Platform with the API

[role="_abstract"]
You need a credential to use {mce-short} console to create and manage a {ocp} cluster on Google Cloud Platform (GCP). You need a credential to use {mce-short} console to create and manage a {ocp} cluster on Google Cloud Platform (GCP). You also need a credential to create a cluster with {mce-short}. You create an opaque secret with the API. To create a credential from the console, follow the steps in xref:../credentials/credential_google_ui.adoc#creating-gcp-credential-ui[Creating a credential for Google Cloud Platform in the console].

*Required access:* Edit

.Prerequisites

* A deployed {mce-short} hub cluster
* Internet access for your {mce-short} hub cluster so it can create the Kubernetes cluster on GCP
* GCP login credentials, which include user Google Cloud Platform Project ID and Google Cloud Platform service account JSON key. See _Creating and managing projects_.
* Account permissions that allow installing clusters on GCP. See _Configuring a GCP project_ for instructions on how to configure an account.

.Procedure

. Create an opaque secret for by using the API. Apply YAML content that is similar to the following example:

[source,yaml]
----
kind: Secret
metadata:
    name: <managed-cluster-name>-gcp-creds
    namespace: <managed-cluster-namespace>
type: Opaque
data:
    osServiceAccount.json: $(base64 -w0 "${GCP_CRED_JSON}")
----
+
*Notes:* 
* Opaque secrets are not visible in the console.
*Opaque secrets are created in the managed cluster namespace you chose. Hive uses the opaque secret to provision the cluster. When provisioning the cluster by using the {acm-short} console, the credentials you previoulsy created are copied to the managed cluster namespace as the opaque secret.

.Additional resources

* link:https://cloud.google.com/resource-manager/docs/creating-managing-projects[Creating and managing projects]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/installing_on_gcp/installing-gcp-account[Configuring a GCP project]
* link:https://console.cloud.google.com/apis/credentials/serviceaccountkey[Log in to GCP]
* link:https://cloud.google.com/iam/docs/service-accounts-create[Create service accounts] 
* link:https://console.redhat.com/openshift/install/pull-secret[Download your Red Hat OpenShift pull secret]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html-single/installing_on_azure/index#ssh-agent-using_installing-azure-preparing-ipi[Generating a key pair for cluster node SSH access]
* xref:../cluster_lifecycle/create_google.adoc#creating-a-cluster-on-google-cloud-platform[Creating a cluster on Google Cloud Platform]

