:_mod-docs-content-type: PROCEDURE

[#creating-a-credential-for-openstack-ui]
= Creating a credential for Red Hat OpenStack in the console

[role="_abstract"]
You need a credential to use {mce-short} console to deploy and manage a supported {ocp} cluster on Red Hat OpenStack Platform. You must create a credential for Red Hat OpenStack Platform before you can create a cluster with {mce-short}.

.Prerequisites

* A deployed hub cluster on a supported {ocp-short} version.
* Internet access for your hub cluster so it can create the Kubernetes cluster on Red Hat OpenStack Platform.
* Red Hat OpenStack Platform login credentials and Red Hat OpenStack Platform requirements configured for {ocp-short} when using installer-provisioned infrastructure. See _Installing a cluster on OpenStack with customizations_.
* Download or create a `clouds.yaml` file for accessing the CloudStack API. Within the `clouds.yaml` file:
** Determine the `cloud auth` section name to use.
** Add a line for the *password*, immediately following the *username* line.

.Procedure

. In the console, click *Credentials* to choose from existing credential options. 

. Create a name and namespace specifically to host your credentials, both for convenience and added security.

. *Optional:* Add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential.

. Add your Red Hat OpenStack Platform `clouds.yaml` file contents. The contents of the `clouds.yaml` file, including the password, provide the required information for connecting to the Red Hat OpenStack Platform server. The file contents must include the password, which you add to a new line immediately after the `username`.

. Add your Red Hat OpenStack Platform cloud name. This entry is the name that is specified in the cloud section of the `clouds.yaml` to use for establishing communication to the Red Hat OpenStack Platform server.

. *Optional*: For configurations that use an internal certificate authority, enter your certificate in the *Internal CA certificate* field to automatically update your `clouds.yaml` with the certificate information.

. *For disconnected installations only:* Complete the fields in the *Configuration for disconnected installation* subsection with the required information:
+
* _Cluster OS image_: This value contains the URL to the image to use for {ocp} cluster machines. 

* _Image content sources_: This value contains the disconnected registry path. The path contains the hostname, port, and repository path to all of the installation images for disconnected installations. Example: `repository.com:5000/openshift/ocp-release`. The path creates an image content source policy mapping in the `install-config.yaml` to the {ocp} release images. As an example, `repository.com:5000` produces this `imageContentSource` content:
+
[source,yaml]
----
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-release-nightly
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----

* _Additional trust bundle_: This value provides the contents of the certificate file that is required to access the mirror registry.
+
*Note:* If you are deploying managed clusters from a hub that is in a disconnected environment, and want them to be automatically imported post install, add an Image Content Source Policy to the `install-config.yaml` file by using the `YAML` editor. A sample entry is shown in the following example: 
+
[source,yaml]
----
- mirrors:
  - registry.example.com:5000/rhacm2
  source: registry.redhat.io/rhacm2
----

. If you want to enable a proxy, enter the proxy information.

. Enter your Red Hat OpenShift pull secret. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.

. Add your SSH Private Key and SSH Public Key, which allows you to connect to the cluster.
You can use an existing key pair, or create a new one with key generation program.

. Click *Create*.

. Review the new credential information, then click *Add*. When you add the credential, it is added to the list of credentials.

. Create a cluster that uses this credential by completing the steps in _Creating a cluster on Red Hat OpenStack Platform_. You can edit your credential in the console. 

. Delete the credential when you are no longer managing that cluster to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.

.Additional resources

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/installing_on_openstack/installing-openstack-installer-custom[Installing a cluster on OpenStack with customizations]
* link:https://console.redhat.com/openshift/install/pull-secret[Download your Red Hat OpenShift pull secret]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/installing_on_openstack/installing-openstack-installer-custom#ssh-agent-using_installing-openstack-installer-custom[Generating a key pair for cluster node SSH access]
* xref:../cluster_lifecycle/create_openstack.adoc#creating-a-cluster-on-openstack[Creating a cluster on Red Hat OpenStack Platform]
