:_mod-docs-content-type: PROCEDURE

[#creating-a-credential-hosted]
= Creating a credential for a hosted environment

[role="_abstract"]
You need a credential to use the console to deploy and manage a {ocp} cluster in an on-premises environment. The credential specifies the connections that are used for the cluster. 

*Required access:* Edit

.Prerequisites

* A hub cluster that is deployed.
* Internet access for your hub cluster so it can create the Kubernetes cluster on your infrastructure environment.
* For a disconnected environment, you must have a configured mirror registry where you can copy the release images for your cluster creation. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html-single/disconnected_environments/mirroring-in-disconnected-environments[Mirroring in disconnected environments] in the {ocp-short} documentation for more information.
* Account permissions that support installing clusters on the on-premises environment.

.Procedure

. In the console, click *Credentials* to choose from existing credential options. 

. Create a namespace specifically to host your credentials, both for convenience and added security.

. Select *Host inventory* for your credential type. 

. *Optional:* Add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential.

. Enter your _Red Hat OpenShift pull secret_. This pull secret is automatically entered when you create a cluster and specify this credential. You can download your pull secret from link:https://console.redhat.com/openshift/install/pull-secret[Pull secret]. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/images/managing-images#using-image-pull-secrets[Using image pull secrets] for more information about pull secrets.

. Enter your `SSH public key`. This `SSH public key` is also automatically entered when you create a cluster and specify this credential. 

. Select *Add* to create your credential.

. Delete the credential when you are no longer managing that cluster to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.

.Next steps

You can create a cluster that uses this credential by completing the steps in xref:../cluster_lifecycle/create_cluster_on_prem.adoc#creating-a-cluster-on-premises[Creating a cluster in an on-premises environment].