:_mod-docs-content-type: PROCEDURE

[#creating-credential-aws-api]
= Creating a credential for Amazon Web Services with the API

[role="_abstract"]
You need a credential to use {mce-short} console to deploy and manage an {ocp} cluster on Amazon Web Services (AWS). The credential is a prerequisite for creating a cluster with {mce-short}. You can also create a credential for AWS with the console. See xref:../credentials/credential_aws_ui.adoc#creating-credential-aws-ui[Creating a credential for Amazon Web Services in the console] for those steps.

*Required access:* Edit

.Prerequisites

* A deployed {mce-short} hub cluster.
* Internet access for your {mce-short} hub cluster so it can create the Kubernetes cluster on Amazon Web Services (AWS).
* AWS login credentials, which include access key ID and secret access key. See _Understanding and getting your security credentials_.
* Account permissions that allow installing clusters on AWS. See _Configuring an AWS account_ for instructions on how to configure an AWS account.

.Procedure

. Create an opaque secret by using the API. Apply YAML content in the YAML preview window that is similar to the following example:

+
[source,yaml]
----
kind: Secret
metadata:
    name: <managed-cluster-name>-aws-creds
    namespace: <managed-cluster-namespace>
type: Opaque
data:
    aws_access_key_id: $(echo -n "${AWS_KEY}" | base64 -w0)
    aws_secret_access_key: $(echo -n "${AWS_SECRET}" | base64 -w0)
----
+
*Notes:*

* Opaque secrets are not visible in the console.
* Opaque secrets are created in the managed cluster namespace you chose. Hive uses the opaque secret to provision the cluster. When provisioning the cluster by using the {acm-short} console, the credentials you previoulsy created are copied to the managed cluster namespace as the opaque secret.

. Add labels to your credentials to view your secret in the console. For example, the following AWS S3 Bucket `oc label secret` is appended with `type=awss3` and `credentials --from-file=....`:

+
[source,bash]
----
oc label secret hypershift-operator-oidc-provider-s3-credentials -n <your-local-cluster-name> "cluster.open-cluster-management.io/type=awss3"
oc label secret hypershift-operator-oidc-provider-s3-credentials -n <your-local-cluster-name> "cluster.open-cluster-management.io/credentials=credentials="
----

.Additional resources

* link:https://docs.aws.amazon.com/IAM/latest/UserGuide/security-creds.html[Understanding and getting your security credentials]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/installing_on_aws/index[Installing on AWS]
* link:https://console.aws.amazon.com/iam/home#/security_credentials[Log in to AWS]
* link:https://console.redhat.com/openshift/install/pull-secret[Download your Red Hat OpenShift pull secret]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html-single/installing_on_aws/index#installation-config-parameters-aws[Installation configuration parameters for AWS] 
* xref:../cluster_lifecycle/create_ocp_aws.adoc#creating-a-cluster-on-amazon-web-services[Creating a cluster on Amazon Web Services]
* xref:../cluster_lifecycle/create_aws_govcloud.adoc#creating-a-cluster-on-amazon-web-services[Creating a cluster on Amazon Web Services GovCloud]
