:_mod-docs-content-type: PROCEDURE

[#creating-gcp-credential-ui]
= Creating a credential for Google Cloud Platform in the console

[role="_abstract"]
You need a credential to use {mce-short} console to create and manage a {ocp} cluster on Google Cloud Platform (GCP). You also need a credential to create a cluster with {mce-short}. Create your credential from the console with the following steps. You can also create an opaque secret with the API by following the steps in xref:../credentials/credential_google_api.adoc#creating-gcp-credential-api[Creating a credential for Google Cloud Platform with the API].

*Required access:* Edit

.Prerequisites

* A deployed {mce-short} hub cluster
* Internet access for your {mce-short} hub cluster so it can create the Kubernetes cluster on GCP
* GCP login credentials, which include user Google Cloud Platform Project ID and Google Cloud Platform service account JSON key. See _Creating and managing projects_.
* Account permissions that allow installing clusters on GCP. See _Configuring a GCP project_ for instructions on how to configure an account.

.Procedure

. From the {mce-short} console, click *Credentials* > *Credential type* to choose from existing credential options.

. Create a name andnamespace specifically to host your credentials, for both convenience and security.

. *Optional:* Add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential.

. Add your _Google Cloud Platform project ID_ for your GCP account. See _Log in to GCP_ to retrieve your settings.

. Add your _Google Cloud Platform service account JSON key_. See the _Create service accounts_ documentation to create your service account JSON key. Follow the steps for the GCP console.

. Click *Proxy* to enter proxy information in the fields that are provided. 

. Enter your Red Hat OpenShift pull secret. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.

. Add your _SSH private key_ and _SSH public key_ so you can access the cluster. You can use an existing key pair, or create a new pair using a key generation program.

. Delete the credential when you are no longer managing that cluster to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.

.Next steps

* You can use this connection when you create a cluster by completing the steps in _Creating a cluster on Google Cloud Platform_. You can also edit your credential in the console. 

.Additional resources

* link:https://cloud.google.com/resource-manager/docs/creating-managing-projects[Creating and managing projects]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/installing_on_gcp/installing-gcp-account[Configuring a GCP project]
* link:https://console.cloud.google.com/apis/credentials/serviceaccountkey[Log in to GCP]
* link:https://cloud.google.com/iam/docs/service-accounts-create[Create service accounts] 
* link:https://console.redhat.com/openshift/install/pull-secret[Download your Red Hat OpenShift pull secret]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html-single/installing_on_azure/index#ssh-agent-using_installing-azure-preparing-ipi[Generating a key pair for cluster node SSH access]
* xref:../cluster_lifecycle/create_google.adoc#creating-a-cluster-on-google-cloud-platform[Creating a cluster on Google Cloud Platform]
