[#creating-a-credential-for-google-cloud-platform]
= Creating a credential for Google Cloud Platform

You need a credential to use {mce-short} console to create and manage a {ocp} cluster on Google Cloud Platform (GCP).

*Required access:* Edit

*Note:* This procedure is a prerequisite for creating a cluster with {mce-short}.

[#google_cred_prerequisites]
== Prerequisites

You must have the following prerequisites before creating a credential:

* A deployed {mce-short} hub cluster
* Internet access for your {mce-short} hub cluster so it can create the Kubernetes cluster on GCP
* GCP login credentials, which include user Google Cloud Platform Project ID and Google Cloud Platform service account JSON key. See _Creating and managing projects_.
* Account permissions that allow installing clusters on GCP. See _Configuring a GCP project_ for instructions on how to configure an account.

[#gcp_cred]
== Managing a credential by using the console

To create a credential from the {mce-short} console, complete the steps in the console. 

Start at the navigation menu. Click *Credentials* to choose from existing credential options. *Tip:* Create a namespace specifically to host your credentials, for both convenience and security.

You can optionally add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential. See the following steps:

. Add your _Google Cloud Platform project ID_ for your GCP account. See _Log in to GCP_ to retrieve your settings.

. Add your _Google Cloud Platform service account JSON key_. See the _Create service accounts_ documentation to create your service account JSON key. Follow the steps for the GCP console.

. Provide the contents for your new _Google Cloud Platform service account JSON key_.

. [[proxy-google]]If you want to enable a proxy, enter the proxy information: 
+
* HTTP proxy URL: The URL that should be used as a proxy for `HTTP` traffic. 

* HTTPS proxy URL: The secure proxy URL that should be used for `HTTPS` traffic. If no value is provided, the same value as the `HTTP Proxy URL` is used for both `HTTP` and `HTTPS`. 

* No proxy domains: A comma-separated list of domains that should bypass the proxy. Begin a domain name with a period `.` to include all of the subdomains that are in that domain. Add and asterisk `*` to bypass the proxy for all destinations. 

* Additional trust bundle: One or more additional CA certificates that are required for proxying HTTPS connections.

. Enter your Red Hat OpenShift pull secret. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.

. Add your _SSH private key_ and _SSH public key_ so you can access the cluster. You can use an existing key pair, or create a new pair using a key generation program.

You can use this connection when you create a cluster by completing the steps in _Creating a cluster on Google Cloud Platform_.

You can edit your credential in the console. 

When you are no longer managing a cluster that is using a credential, delete the credential to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.

[#gcp-create-opaque-secret-api]
== Creating an opaque secret by using the API

To create an opaque secret for Google Cloud Platform by using the API instead of the console, apply YAML content in the YAML preview window that is similar to the following example:

[source,yaml]
----
kind: Secret
metadata:
    name: <managed-cluster-name>-gcp-creds
    namespace: <managed-cluster-namespace>
type: Opaque
data:
    osServiceAccount.json: $(base64 -w0 "${GCP_CRED_JSON}")
----

*Notes:* 

- Opaque secrets are not visible in the console.

- Opaque secrets are created in the managed cluster namespace you chose. Hive uses the opaque secret to provision the cluster. When provisioning the cluster by using the {product-title-short} console, the credentials you previoulsy created are copied to the managed cluster namespace as the opaque secret.

[#gcp-cred-additional-resources]
== Additional resources

- See link:https://cloud.google.com/resource-manager/docs/creating-managing-projects[Creating and managing projects].

- See link:https://docs.openshift.com/container-platform/4.12/installing/installing_gcp/installing-gcp-account.html[Configuring a GCP project].

- link:https://console.cloud.google.com/apis/credentials/serviceaccountkey[Log in to GCP].

- See the link:https://cloud.google.com/iam/docs/creating-managing-service-accounts[Create service accounts] to create your service account JSON key.

- link:https://cloud.redhat.com/openshift/install/pull-secret[Download your Red Hat OpenShift pull secret].

- See link:https://docs.openshift.com/container-platform/4.12/installing/installing_gcp/installing-gcp-default.html#ssh-agent-using_installing-gcp-default[Generating an SSH private key and adding it to the agent] for more information about how to generate a key.

- See xref:../cluster_lifecycle/create_google.adoc#creating-a-cluster-on-google-cloud-platform[Creating a cluster on Google Cloud Platform].

Return to <<creating-a-credential-for-google-cloud-platform,Creating a credential for Google Cloud Platform>>.