[#creating-a-credential-for-an-on-premises-environment]
= Creating a credential for an on-premises environment

You need a credential to use the console to deploy and manage a {ocp} cluster in an on-premises environment. The credential specifies the connections that are used for the cluster. 

*Required access:* Edit

* <<on-prem-cred-prerequisites,Prerequisites>>
* <<on-prem-cred,Managing a credential by using the console>>

[#on-prem-cred-prerequisites]
== Prerequisites

You need the following prerequisites before creating a credential:

* A hub cluster that is deployed.
* Internet access for your hub cluster so it can create the Kubernetes cluster on your infrastructure environment.
* For a disconnected environment, you must have a configured mirror registry where you can copy the release images for your cluster creation. See link:https://docs.openshift.com/container-platform/4.12/installing/disconnected_install/installing-mirroring-disconnected.html[Mirroring images for a disconnected installation] in the {ocp-short} documentation for more information.
* Account permissions that support installing clusters on the on-premises environment.

[#on-prem-cred]
== Managing a credential by using the console

To create a credential from the console, complete the steps in the console. 

Start at the navigation menu. Click *Credentials* to choose from existing credential options. *Tip:* Create a namespace specifically to host your credentials, both for convenience and added security.

. Select *Host inventory* for your credential type. 

. You can optionally add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential. If you do not add the DNS domain, you can add it when you create your cluster.

. Enter your _Red Hat OpenShift pull secret_. This pull secret is automatically entered when you create a cluster and specify this credential.
You can download your pull secret from link:https://cloud.redhat.com/openshift/install/pull-secret[Pull secret]. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/images/managing-images#using-image-pull-secrets[Using image pull secrets] for more information about pull secrets.

. Enter your `SSH public key`. This `SSH public key` is also automatically entered when you create a cluster and specify this credential. 

. Select *Add* to create your credential.

You can create a cluster that uses this credential by completing the steps in xref:../cluster_lifecycle/create_cluster_on_prem.adoc#creating-a-cluster-on-premises[Creating a cluster in an on-premises environment].

When you are no longer managing a cluster that is using a credential, delete the credential to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.
