:_mod-docs-content-type: PROCEDURE

[#creating-a-credential-for-vmware-vsphere-console]
= Creating a credential for VMware vSphere in the console

[role="_abstract"]
You need a credential to use {mce-short} console to deploy and manage a {ocp} cluster on VMware vSphere. Create your credential from the console with the following steps. You can also create an opaque secret with the API by following the steps in xref:../credentials/credential_vm_api.adoc#creating-a-credential-for-vmware-vsphere-api[Creating a credential for VMware vSphere with the API].

*Required access:* Edit

.Prerequisites

* You must create a credential for VMware vSphere before you can create a cluster with {mce-short}.
* A deployed hub cluster on a supported {ocp-short} version.
* Internet access for your hub cluster so it can create the Kubernetes cluster on VMware vSphere.
* VMware vSphere login credentials and vCenter requirements configured for {ocp-short} when using installer-provisioned infrastructure. See _Installing a cluster on vSphere with customizations_. These credentials include the following information:
** vCenter account privileges.
** Cluster resources.
** DHCP available.
** ESXi hosts have time synchronized (for example, NTP).

.Procedure

. In the console, click *Credentials* to choose from existing credential options. 

. Create a name and namespace specifically to host your credentials, both for convenience and added security.

. Add your _VMware vCenter server fully-qualified host name or IP address_. The value must be defined in the vCenter server root CA certificate. If possible, use the fully-qualified host name.

. Add your _VMware vCenter username_.

. Add your _VMware vCenter password_.

. Add your _VMware vCenter root CA certificate_.

.. You can download your certificate in the `download.zip` package with the certificate from your VMware vCenter server at: `https://<vCenter_address>/certs/download.zip`. Replace _vCenter_address_ with the address to your vCenter server.

.. Unpackage the `download.zip`.

.. Use the certificates from the `certs/<platform>` directory that have a `.0` extension.
+
*Tip:* You can use the `ls certs/<platform>` command to list all of the available certificates for your platform.
+
Replace `_<platform>_` with the abbreviation for your platform: `lin`, `mac`, or `win`.
+
For example: `certs/lin/3a343545.0`
+
*Best practice:* Link together multiple certificates with a `.0` extension by running the `cat certs/lin/*.0 > ca.crt` command.
+
.. Add your _VMware vSphere cluster name_.
.. Add your _VMware vSphere datacenter_.
.. Add your _VMware vSphere default datastore_.
.. Add your _VMware vSphere disk type_.
.. Add your _VMware vSphere folder_.
.. Add your _VMware vSphere resource pool_.

. For disconnected installations only: Complete the fields in the *Configuration for disconnected installation* subsection with the required information:
+
* _Cluster OS image_: This value contains the URL to the image to use for {ocp} cluster machines.

* _Image content source_: This value contains the disconnected registry path. The path contains the hostname, port, and repository path to all of the installation images for disconnected installations. Example: `repository.com:5000/openshift/ocp-release`.
+
The path creates an image content source policy mapping in the `install-config.yaml` to the {ocp} release images. As an example, `repository.com:5000` produces this `imageContentSource` content:

+
[source,yaml]
----
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-release-nightly
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----
* _Additional trust bundle_: This value provides the contents of the certificate file that is required to access the mirror registry.

+
*Note:* If you are deploying managed clusters from a hub that is in a disconnected environment, and want them to be automatically imported post install, add an Image Content Source Policy to the `install-config.yaml` file by using the `YAML` editor. A sample entry is shown in the following example:

+
[source,yaml]
----
- mirrors:
  - registry.example.com:5000/rhacm2
  source: registry.redhat.io/rhacm2
----

. If you want to enable a proxy, enter the proxy information.

. Enter your Red Hat OpenShift pull secret. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.

. Add your _SSH private key_ and _SSH public key_, which allows you to connect to the cluster. You can use an existing key pair, or create a new one with key generation program.

. Click *Create*.

. Review the new credential information, then click *Add*. When you add the credential, it is added to the list of credentials.

. Create a cluster that uses this uses this credential by completing the steps in _Creating a cluster on VMware vSphere_.

. Edit your credential in the console.

. Delete the credential when you are no longer managing that cluster to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete

.Additional resources

- link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/installing_on_vmware_vsphere/installer-provisioned-infrastructure#installing-vsphere-installer-provisioned-customizations[Installing a cluster on vSphere with customizations]

- link:https://console.redhat.com/openshift/install/pull-secret[Download your Red Hat OpenShift pull secret]

- link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html-single/installing_on_vmware_vsphere/index#ssh-agent-using_ipi-vsphere-preparing-to-install[Generating a key pair for cluster node SSH access]

- xref:../cluster_lifecycle/create_vm.adoc#creating-a-cluster-on-vmware-vsphere[Creating a cluster on VMware vSphere]