[#creating-a-credential-for-vmware-vsphere]
= Creating a credential for VMware vSphere

You need a credential to use {mce-short} console to deploy and manage a {ocp} cluster on VMware vSphere.

*Required access:* Edit

*Notes:*

- You must create a credential for VMware vSphere before you can create a cluster with {mce-short}.

- {ocp-short} versions 4.12 and later are supported.

[#vsphere_cred_prerequisites]
== Prerequisites

You must have the following prerequisites before you create a credential:

* A deployed hub cluster on {ocp-short} version 4.12 or later.
* Internet access for your hub cluster so it can create the Kubernetes cluster on VMware vSphere.
* VMware vSphere login credentials and vCenter requirements configured for {ocp-short} when using installer-provisioned infrastructure. See _Installing a cluster on vSphere with customizations_. These credentials include the following information:
** vCenter account privileges.
** Cluster resources.
** DHCP available.
** ESXi hosts have time synchronized (for example, NTP).

[#vsphere_cred]
== Managing a credential by using the console

To create a credential from the {mce-short} console, complete the steps in the console.

Start at the navigation menu. Click *Credentials* to choose from existing credential options. *Tip:* Create a namespace specifically to host your credentials, both for convenience and added security.

You can optionally add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential. See the following steps:

. Add your _VMware vCenter server fully-qualified host name or IP address_. The value must be defined in the vCenter server root CA certificate. If possible, use the fully-qualified host name.

. Add your _VMware vCenter username_.

. Add your _VMware vCenter password_.

. Add your _VMware vCenter root CA certificate_.

.. You can download your certificate in the `download.zip` package with the certificate from your VMware vCenter server at: `https://<vCenter_address>/certs/download.zip`. Replace _vCenter_address_ with the address to your vCenter server.

.. Unpackage the `download.zip`.

.. Use the certificates from the `certs/<platform>` directory that have a `.0` extension.
+
*Tip:* You can use the `ls certs/<platform>` command to list all of the available certificates for your platform.
+
Replace `_<platform>_` with the abbreviation for your platform: `lin`, `mac`, or `win`.
+
For example: `certs/lin/3a343545.0`
+
*Best practice:* Link together multiple certificates with a `.0` extension by running the `cat certs/lin/*.0 > ca.crt` command.
+
.. Add your _VMware vSphere cluster name_.
.. Add your _VMware vSphere datacenter_.
.. Add your _VMware vSphere default datastore_.
.. Add your _VMware vSphere disk type_.
.. Add your _VMware vSphere folder_.
.. Add your _VMware vSphere resource pool_.

. [[disconnected-vm]]For disconnected installations only: Complete the fields in the *Configuration for disconnected installation* subsection with the required information:
+
* _Cluster OS image_: This value contains the URL to the image to use for {ocp} cluster machines.

* _Image content source_: This value contains the disconnected registry path. The path contains the hostname, port, and repository path to all of the installation images for disconnected installations. Example: `repository.com:5000/openshift/ocp-release`.
+
The path creates an image content source policy mapping in the `install-config.yaml` to the {ocp} release images. As an example, `repository.com:5000` produces this `imageContentSource` content:
+
[source,yaml]
----
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-release-nightly
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----
* _Additional trust bundle_: This value provides the contents of the certificate file that is required to access the mirror registry.
+
*Note:* If you are deploying managed clusters from a hub that is in a disconnected environment, and want them to be automatically imported post install, add an Image Content Source Policy to the `install-config.yaml` file by using the `YAML` editor. A sample entry is shown in the following example:
+
[source,yaml]
----
- mirrors:
  - registry.example.com:5000/rhacm2
  source: registry.redhat.io/rhacm2
----

. [[proxy-vm]]If you want to enable a proxy, enter the proxy information:
+
* HTTP proxy URL: The URL that should be used as a proxy for `HTTP` traffic.

* HTTPS proxy URL: The secure proxy URL that should be used for `HTTPS` traffic. If no value is provided, the same value as the `HTTP Proxy URL` is used for both `HTTP` and `HTTPS`.

* No proxy domains: A comma-separated list of domains that should bypass the proxy. Begin a domain name with a period `.` to include all of the subdomains that are in that domain. Add and asterisk `*` to bypass the proxy for all destinations.

* Additional trust bundle: One or more additional CA certificates that are required for proxying HTTPS connections.

. Enter your Red Hat OpenShift pull secret. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.

. Add your _SSH private key_ and _SSH public key_, which allows you to connect to the cluster.
+
You can use an existing key pair, or create a new one with key generation program.

You can create a cluster that uses this credential by completing the steps in _Creating a cluster on VMware vSphere_.

You can edit your credential in the console.

When you are no longer managing a cluster that is using a credential, delete the credential to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.

[#vsphere-create-opaque-secret-api]
== Creating an opaque secret by using the API

To create an opaque secret for VMware vSphere by using the API instead of the console, apply YAML content in the YAML preview window that is similar to the following example:

[source,yaml]
----
kind: Secret
metadata:
    name: <managed-cluster-name>-vsphere-creds
    namespace: <managed-cluster-namespace>
type: Opaque
data:
    username: $(echo -n "${VMW_USERNAME}" | base64 -w0)
    password.json: $(base64 -w0 "${VMW_PASSWORD}")
----

*Notes:*

- Opaque secrets are not visible in the console.

- Opaque secrets are created in the managed cluster namespace you chose. Hive uses the opaque secret to provision the cluster. When provisioning the cluster by using the {product-title-short} console, the credentials you previoulsy created are copied to the managed cluster namespace as the opaque secret.

[#vsphere-cred-additional-resources]
== Additional resources

- See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-vsphere#installing-vsphere-installer-provisioned-customizations[Installing a cluster on vSphere with customizations].

- link:https://cloud.redhat.com/openshift/install/pull-secret[Download your Red Hat OpenShift pull secret].

- See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-vsphere#ssh-agent-using_installing-vsphere-installer-provisioned[Generating a key pair for cluster node SSH access] for more information.

- See xref:../cluster_lifecycle/create_vm.adoc#creating-a-cluster-on-vmware-vsphere[Creating a cluster on VMware vSphere].

- Return to <<creating-a-credential-for-vmware-vsphere,Creating a credential for VMware vSphere>>.
