:_mod-docs-content-type: PROCEDURE

[#creating-credential-aws-ui]
= Creating a credential for Amazon Web Services in the console

[role="_abstract"]
You need a credential to use {mce-short} console to deploy and manage an {ocp} cluster on Amazon Web Services (AWS). This procedure must be done before you can create a cluster with {mce-short}. You can also create a credential for AWS with the API. See xref:../credentials/credential_aws_api.adoc#creating-credential-aws-api[Creating a credential for Amazon Web Services with the API] for those steps.

*Required access:* Edit

.Prerequisites

* A deployed {mce-short} hub cluster
* Internet access for your {mce-short} hub cluster so it can create the Kubernetes cluster on Amazon Web Services (AWS)
* AWS login credentials, which include access key ID and secret access key. See _Understanding and getting your security credentials_.
* Account permissions that allow installing clusters on AWS. See _Configuring an AWS account_ for instructions on how to configure an AWS account.

.Procedure

. In the console, click *Credentials* to choose from existing credential options. 

. Create a name and namespace specifically to host your credentials, both for convenience and added security.

. *Optional:* Add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential.

. Add your _AWS access key ID_ for your AWS account. See _Log in to AWS_ to find your ID.

. Provide the contents for your new _AWS Secret Access Key_.

. Click *Proxy* to enter proxy information in the fields that are provided. 

. Enter your {ocp-short} pull secret. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.

. Add your _SSH private key_ and _SSH public key_, which allows you to connect to the cluster. You can use an existing key pair, or create a new one with key generation program.

. Create a cluster that uses this credential by completing the steps in _Creating a cluster on Amazon Web Services_ or _Creating a cluster on Amazon Web Services GovCloud_.

. Edit your credential in the console. If the cluster was created by using this provider connection, then the `<cluster-name>-aws-creds>` secret from `<cluster-namespace>` is updated with the new credentials.
+
*Note:* Updating credentials does not work for cluster pool claimed clusters.

. You can also create an Amazon Simple Storage Service (S3) secret, complete the following substeps from the console:

.. Click *Add credential* > *AWS* > *S3 Bucket*. If you click *For Hosted Control Plane*, the name and namespace are provided. 

.. Enter information for the following fields that are provided:
+
* `bucket name`: Add the name of the S3 bucket.
* `aws_access_key_id`: Add your AWS access key ID for your AWS account. Log in to AWS to find your ID.
* `aws_secret_access_key`: Provide the contents for your new AWS Secret Access Key.
* `Region`: Enter your AWS region.

. Delete the credential when you are no longer managing that cluster to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.

.Additional resources

* link:https://docs.aws.amazon.com/IAM/latest/UserGuide/security-creds.html[Understanding and getting your security credentials]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/installing_on_aws/index[Installing on AWS]
* link:https://console.aws.amazon.com/iam/home#/security_credentials[Log in to AWS]
* link:https://console.redhat.com/openshift/install/pull-secret[Download your Red Hat OpenShift pull secret]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html-single/installing_on_aws/index#installation-config-parameters-aws[Installation configuration parameters for AWS] 
* xref:../cluster_lifecycle/create_ocp_aws.adoc#creating-a-cluster-on-amazon-web-services[Creating a cluster on Amazon Web Services]
* xref:../cluster_lifecycle/create_aws_govcloud.adoc#creating-a-cluster-on-amazon-web-services[Creating a cluster on Amazon Web Services GovCloud]