:_mod-docs-content-type: PROCEDURE

[#creating-a-credential-for-vmware-vsphere-api]
= Creating a credential for VMware vSphere with the API

[role="_abstract"]
Create an opaque secret with the API. You need a credential to use {mce-short} console to deploy and manage a {ocp} cluster on VMware vSphere. You can also create a credential from the console by following the steps in xref:../credentials/credential_vm_ui.adoc#creating-a-credential-for-vmware-vsphere-console[Creating a credential for VMware vSphere in the console].

*Required access:* Edit

.Prerequisites

* You must create a credential for VMware vSphere before you can create a cluster with {mce-short}.
* A deployed hub cluster on a supported {ocp-short} version.
* Internet access for your hub cluster so it can create the Kubernetes cluster on VMware vSphere.
* VMware vSphere login credentials and vCenter requirements configured for {ocp-short} when using installer-provisioned infrastructure. See _Installing a cluster on vSphere with customizations_. These credentials include the following information:
** vCenter account privileges.
** Cluster resources.
** DHCP available.
** ESXi hosts have time synchronized (for example, NTP).

.Procedure

* Create an opaque secret for by using the API. Apply YAML content that is similar to the following example:

+
[source,yaml]
----
kind: Secret
metadata:
    name: <managed-cluster-name>-vsphere-creds
    namespace: <managed-cluster-namespace>
type: Opaque
data:
    username: $(echo -n "${VMW_USERNAME}" | base64 -w0)
    password.json: $(base64 -w0 "${VMW_PASSWORD}")
----
+
*Notes:*
+
- Opaque secrets are not visible in the console.
- Opaque secrets are created in the managed cluster namespace you chose. Hive uses the opaque secret to provision the cluster. When provisioning the cluster by using the {acm-short} console, the credentials you previoulsy created are copied to the managed cluster namespace as the opaque secret.

.Additional resources

- link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/installing_on_vmware_vsphere/installer-provisioned-infrastructure#installing-vsphere-installer-provisioned-customizations[Installing a cluster on vSphere with customizations]

- link:https://console.redhat.com/openshift/install/pull-secret[Download your Red Hat OpenShift pull secret]

- link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html-single/installing_on_vmware_vsphere/index#ssh-agent-using_ipi-vsphere-preparing-to-install[Generating a key pair for cluster node SSH access]

- xref:../cluster_lifecycle/create_vm.adoc#creating-a-cluster-on-vmware-vsphere[Creating a cluster on VMware vSphere]
