:_mod-docs-content-type: PROCEDURE

[#creating-a-credential-for-openstack-api]
= Creating a credential for Red Hat OpenStack with the API

[role="_abstract"]
You need a credential to use {mce-short} console to deploy and manage a supported {ocp} cluster on Red Hat OpenStack Platform. You must create a credential for Red Hat OpenStack Platform before you can create a cluster with {mce-short}.

.Prerequisites

* A deployed hub cluster on a supported {ocp-short} version.
* Internet access for your hub cluster so it can create the Kubernetes cluster on Red Hat OpenStack Platform.
* Red Hat OpenStack Platform login credentials and Red Hat OpenStack Platform requirements configured for {ocp-short} when using installer-provisioned infrastructure. See _Installing a cluster on OpenStack with customizations_.
* Download or create a `clouds.yaml` file for accessing the CloudStack API. Within the `clouds.yaml` file:
** Determine the `cloud auth` section name to use.
** Add a line for the *password*, immediately following the *username* line.

.Procedure

* Create an opaque secret for by using the API. Apply YAML content that is similar to the following example:

+
[source,yaml]
----
kind: Secret
metadata:
    name: <managed-cluster-name>-osp-creds
    namespace: <managed-cluster-namespace>
type: Opaque
data:
    clouds.yaml: $(base64 -w0 "${OSP_CRED_YAML}") cloud: $(echo -n "openstack" | base64 -w0)
----
+
*Notes:* 

- Opaque secrets are not visible in the console.
- Opaque secrets are created in the managed cluster namespace you chose. Hive uses the opaque secret to provision the cluster. When provisioning the cluster by using the {acm-short} console, the credentials you previously created are copied to the managed cluster namespace as the opaque secret.

.Additional resources

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/installing_on_openstack/installing-openstack-installer-custom[Installing a cluster on OpenStack with customizations]
* link:https://console.redhat.com/openshift/install/pull-secret[Download your Red Hat OpenShift pull secret]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/installing_on_openstack/installing-openstack-installer-custom#ssh-agent-using_installing-openstack-installer-custom[Generating a key pair for cluster node SSH access]
* xref:../cluster_lifecycle/create_openstack.adoc#creating-a-cluster-on-openstack[Creating a cluster on Red Hat OpenStack Platform]

