[#glossary-of-terms]
= Glossary of terms

{product-title} consists of several multicluster components that are defined in the following sections.
Additionally, some common Kubernetes terms are used within the product.
Terms are listed alphabetically.

[#relevant-standardized-glossaries]
== Relevant standardized glossaries

* https://kubernetes.io/docs/reference/glossary/?fundamental=true[Kubernetes glossary]

[#red-hat-advanced-cluster-management-for-kubernetes-terms]
== {product-title} terms

[#a-term-app-life]
=== Application lifecycle

The processes that are used to manage application resources on your managed clusters.
A multicluster application uses a Kubernetes specification, but with additional automation of the deployment and lifecycle management of resources to individual clusters.

[#c-term-channel]
=== Channel

A custom resource definition that points to repositories where Kubernetes resources are stored, such as a Git repository, Helm chart repository, object store, or hub cluster namespace.
Channels support multiple subscriptions from multiple targets.

[#c-term-cluster-life]
=== Cluster lifecycle

Defines the process of creating, importing, and managing clusters across public and private clouds.

[#c-term-console]
=== Console

The graphical user interface for {product-title-short}.

[#deployable-d-term-deployable]
=== Deployable

A resource that retrieves the output of a build, packages the output with configuration properties, and installs the package in a predefined location so that it can be tested or run.

[#g-term-3-govern]
=== Governance and risk

The  {product-title-short} processes used to manage security and compliance.

[#h-term-hub]
=== Hub cluster

The central controller that runs in a {product-title} cluster.
From the hub cluster, you can access the console and components found on that console, as well as APIs.

[#m-term-managed]
=== Managed cluster

Created and imported clusters are managed by the klusterlet agent and its add-ons, which initiates a connection to the {product-title} hub cluster.

[#k-term-klusterlet]
=== Klusterlet

The agent that contains two controllers on the managed cluster that initiates a connection to the {product-title} hub cluster.

[#k-term-addon]
=== Klusterlet add-on

Specialized controller on the Klusterlet that provides additional management capability.

[#p-term-policy]
=== Placement policy

A policy that defines where the application components should be deployed and how many replicas there should be.

[#p-term-rule]
=== Placement rule

A rule that defines the target clusters where subscriptions are delivered.
For instance, verify the cluster name, resource annotations, or resource label(s).

[#s-term-sub]
=== Subscriptions

Identify Kubernetes resources within channels (resource repositories).
The subscription places the Kubernetes resources in the same namespace, where it is created on the subscribed target clusters.
