[#glossary-of-terms]
= Glossary of terms

{product-title} consists of several multicluster components that are defined in the following sections.
Additionally, some common Kubernetes terms are used within the product.
Terms are listed alphabetically.

[#relevant-standardized-glossaries]
== Relevant standardized glossaries

* https://kubernetes.io/docs/reference/glossary/?fundamental=true[Kubernetes glossary]

[#red-hat-advanced-cluster-management-for-kubernetes-terms]
== Red Hat Advanced Cluster Management for Kubernetes terms

[#a-term-app-life]
=== Application lifecycle

The processes that are used to manage application resources on your managed clusters.
A multicluster application uses a Kubernetes specification, but with additional automation of the deployment and lifecycle management of resources to individual clusters.

[#c-term-channel]
=== Channel

A custom resource definition that points to repositories where Kubernetes resources are stored, such as Git repositories, Helm chart repositories, ObjectStore repositories, or namespaces templates on the hub cluster. Channels support multiple subscriptions from multiple targets.

[#c-term-cluster-life]
=== Cluster lifecycle

Defines the process of creating, importing, and managing clusters across public and private clouds.

[#c-term-console]
=== Console

The graphical user interface for {product-title}.

[#deployable-d-term-deployable]
=== Deployable

A resource that retrieves the output of a build, packages the output with configuration properties, and installs the package in a pre-defined location so that it can be tested or run.

[#g-term-3-governance]
=== Governance

The {product-title} processes used to manage security and compliance.

[#h-term-hosted-cluster]
=== Hosted cluster

An {ocp-short} API endpoint that is managed by HyperShift.

[#h-term-hosted-cluster-infrastructure]
=== Hosted cluster infrastructure

Resources that exist in the customer cloud account, including network, compute, storage, and so on.

[#h-term-hosted-control-plane]
=== Hosted control plane

An {ocp-short} control plane that is running on the hosting service cluster, which is exposed by the API endpoint of a hosted cluster. The component parts of a control plane include `etcd`, `apiserver`, `kube-controller-manager`, `vpn`, and other components.

[#h-term-hosted-control-plane-infrastructure]
=== Hosted control plane infrastructure

Resources on the management cluster or external cloud provider that are prerequisites to running hosted control plane processes.

[#h-term-hosting-service-cluster]
=== Hosting service cluster

An {ocp-short} cluster that hosts the HyperShift operator and zero-to-many hosted clusters.

[#h-term-hosted-service-cluster-infrastructure]
=== Hosted service cluster infrastructure

Resources of the hosting service cluster, including network, compute, storage, and so on.

[#h-term-hub]
=== Hub cluster

The central controller that runs in a {product-title} cluster.
From the hub cluster, you can access the console and components found on that console, as well as APIs.

[#k-term-klusterlet]
=== klusterlet

The agent that contains two controllers on the managed cluster that initiates a connection to the {product-title} hub cluster.

[#k-term-addon]
=== Klusterlet add-on

Specialized controller on the Klusterlet that provides additional management capability.

[#m-term-managed]
=== Managed cluster

Created and imported clusters are managed by the klusterlet agent and its add-ons, which initiates a connection to the {product-title} hub cluster.

[#p-term-policy]
=== Placement policy

A policy that defines where the application components should be deployed and how many replicas there should be.

[#p-term-rule]
=== Placement rule

A rule that defines the target clusters where subscriptions are delivered.
For instance, verify the cluster name, resource annotations, or resource label(s).


[#s-term-sub]
=== Subscriptions

A resource that identifies the Kubernetes resources within channels (resource repositories), then places the Kubernetes resource on the target clusters.
