:_mod-docs-content-type: CONCEPT

[#glossary-of-terms]
= Glossary of terms

[role="_abstract"]
{acm} consists of several multicluster components that are defined in the following sections.
Additionally, some common Kubernetes terms are used within the product.
Terms are listed alphabetically.

== Relevant standardized glossaries

* link:https://kubernetes.io/docs/reference/glossary/?fundamental=true[Kubernetes glossary]

== Red Hat Advanced Cluster Management for Kubernetes terms

Application lifecycle::
The processes that are used to manage application resources on your managed clusters.
A multicluster application uses a Kubernetes specification, but with additional automation of the deployment and lifecycle management of resources to individual clusters.

Channel::
A custom resource definition that references repositories where Kubernetes resources are stored, such as Git repositories, Helm chart repositories, ObjectStore repositories, or namespaces templates on the hub cluster. Channels support multiple subscriptions from multiple targets.

Cluster lifecycle::
Defines the process of creating, importing, and managing clusters across public and private clouds.

Console::
The graphical user interface for {acm}.

Deployable::
A resource that retrieves the output of a build, packages the output with configuration properties, and installs the package in a pre-defined location so that it can be tested or run.

Governance::
The {acm} processes used to manage security and compliance.

Hosted cluster::
An {ocp-short} API endpoint that is managed by HyperShift.

Hosted cluster infrastructure::
Resources that exist in the customer cloud account, including network, compute, storage, and so on.

Hosted control plane::
An {ocp-short} control plane that is running on the hosting service cluster, which is exposed by the API endpoint of a hosted cluster. The component parts of a control plane include `etcd`, `apiserver`, `kube-controller-manager`, `vpn`, and other components.

Hosted control plane infrastructure::
Resources on the management cluster or external cloud provider that are prerequisites to running hosted control plane processes.

Hosting service cluster::
An {ocp-short} cluster that hosts the HyperShift operator and zero-to-many hosted clusters.

Hosted service cluster infrastructure::
Resources of the hosting service cluster, including network, compute, storage, and so on.

Hub cluster::
The central controller that runs in a {acm} cluster. From the hub cluster, you can access the console and components found on that console, as well as APIs.

klusterlet::
The agent that contains two controllers on the managed cluster that initiates a connection to the {acm} hub cluster.

Klusterlet add-on::
Specialized controller on the Klusterlet that provides additional management capability.

Managed cluster::
Created and imported clusters are managed by the klusterlet agent and its add-ons, which initiates a connection to the {acm} hub cluster.

Placement binding::
A resource that binds a placement to a policy.

Placement policy::
A policy that defines where the application components are deployed and how many replicas there are.

Subscriptions::
A resource that identifies the Kubernetes resources within channels (resource repositories), then places the Kubernetes resource on the target clusters.
