[#getting-started]
= Getting started

* <<introduction,Introduction>>
* <<install,Install>>
* <<manage-clusters,Manage clusters>>
* <<manage-applications,Manage applications>>
* <<manage-security,Manage security>>
* <<observability-quick, Observe clusters>>

[#introduction]
== Introduction

See the product architecture at xref:../about/architecture.adoc#multicluster-architecture[Multicluster architecture].  

After you learn about the hub cluster and managed cluster architecture, learn about the link:../about/supported_providers.adoc#supported-providers[Supported providers] in the _Clusters_ documentation, which lists the cloud provider cluster options.

The hub cluster is a {ocp} cluster version 4.6 or later, and can run on any https://docs.openshift.com/container-platform/4.10/architecture/architecture-installation.html[supported {ocp} infrastructure].

The xref:../about/glossary_terms.adoc#glossary-of-terms[Glossary of terms] defines common terms for the product.

If you experience problems, see the link:../troubleshooting/troubleshooting_intro.adoc#troubleshooting[Troubleshooting guide] to learn about the `must-gather` command and see documented troubleshooting tasks that might help resolve issues.

[#install]
== Install

. Before you install {product-title}, review the system configuration requirements and settings at link:../install/requirements.adoc#requirements-and-recommendations[Requirements and recommendations].
Get information about required operating systems and supported browsers.
For instance, you want to ensure that you have a supported {ocp} version so that you can set up your hub cluster.
. You also need to ensure that your hub cluster has the appropriate capacity. To prepare your hub cluster, see link:../install/cluster_size.adoc#sizing-your-cluster[Sizing your cluster].
. With a supported version of {ocp-short} installed and running on your hub cluster, you can proceed with link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online].

After installation, review the link:../console/console_intro.adoc#web-console[Web console] guide to learn how to access your console and what features are available in the console.

[#manage-clusters]
== Manage clusters

You are now ready to create and import clusters. From your hub cluster, you can create clusters from other Kubernetes services to manage, and you can view cluster information.

When you create a managed cluster, the new managed cluster imports automatically.

. If you have a cluster that you want to import manually, you can view link:../clusters/import.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a target managed cluster to the hub cluster] to learn how to import a managed cluster.
. When you no longer need to manage a cluster, you can detach that cluster from the _Cluster page_.

[#manage-applications]
== Manage applications

You can start managing applications on any created and imported managed clusters.
The types of resources that you can create are applications, channels, subscriptions, and placement rules.

. Learn more about the resources and how to create and manage them at link:../applications/app_management_overview.adoc#managing-applications[Managing applications].
Add or edit your `.yaml` file to create your resources.
. View and edit your resources from the _Applications Dashboard_.

[#manage-security]
== Manage security

You can also manage security and compliance across your created and imported managed clusters.

. Create a policy using the _policy_ templates.
See the link:../governance/policy_example.adoc#policy-overview[Policy overview] for details about how to create a policy with a `.yaml` file template.
. From the _Policies_ page, you can view a summary of cluster and policy violations.
. View your policies from the _Governance_ page in the console.
You can also view policy details from the cluster _Overview_.

[#observability-quick]
== Observe clusters

You can enable the observability service to gain insight and optimize your managed clusters. Enable the observability service operator (`multicluster-observability-operator`) to monitor the health of your managed clusters.

. Learn more about link:../observability/observe_environments.adoc#observing-environments[Observing environments] and how to link:../observability/observability_enable.adoc#enable-observability[Enable observability service].
. Learn about link:../observability/customize_observability.adoc#customizing-observability[Customizing observability].
