:_mod-docs-content-type: REFERENCE

[#auto-import-hcp]
= Automated import for discovered hosted clusters

[role="_abstract"]
Automated import of hosted clusters uses the `DiscoveredCluster` resource for faster cluster management, without manually importing individual clusters.

Automatic import of a discovered hosted cluster into {acm-short} enables all {acm-short} add-ons so that you can start managing the hosted clusters with the available management tools.

The hosted cluster is also _auto-imported_ into {mce-short}. Through the {mce-short} console, you can manage the hosted cluster lifecycle. However, you cannot manage the hosted cluster lifecycle from the {acm-short} console.

*Required access:* Cluster administrator

.Additional resources

* xref:../acm_hosted_cluster/acm_hcp_autoimport_config.adoc#config-hcp-autoimport[Configure settings for automatic import]
* xref:../acm_hosted_cluster/acm_hcp_create_placement.adoc#create-hcp-placement[Create the placement definition]
* xref:../acm_hosted_cluster/acm_hcp_bind_placement.adoc#bind-hcp-placement[Bind the import policy to a placement definition]
