:_mod-docs-content-type: REFERENCE

[#mce-acm-observability]
= Observability integration

[role="_abstract"]
With the {acm-short} observability feature, you can view health and utilization of clusters across your fleet. You can install {acm-short} and enable observability.

After you enable the `multicluster-observability` pod, you can use {acm-short} observability Grafana dashboards to view the following information about your hosted control planes:

* *ACM* > *Hosted Control Planes Overview* dashboard to see cluster capacity estimates for hosting hosted control planes, the related cluster resources, and the list and status of existing hosted control planes. See _Introduction to hosted control planes_.

* *ACM* > *Resources* > *Hosted Control Plane* dashboard that you can access from the _Overview_ page to see the resource utilization of the selected hosted control plane. See _Installing the hosted control planes command-line interface_.

To enable, see _Observability service_.

.Additional resources

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/hosted_control_planes/hosted-control-planes-overview#hosted-control-planes-overview_hcp-overview[Introduction to hosted control planes]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/hosted_control_planes/preparing-to-deploy-hosted-control-planes#installing-the-hosted-control-plane-command-line-interface[Installing the hosted control planes command-line interface]
* link:../../observability/observe_environments_intro.adoc#observing-environments-intro[Observability service]
