:_mod-docs-content-type: PROCEDURE

[#hosted-import-config]
= Configure {acm-short} to import {mce-short} clusters

[role="_abstract"]
Configure add-ons and install those add-ons in a different {mce-short} namespace so that the {mce-short} can self-manage with the `local-cluster` add-ons while {acm-short} manages {mce-short} at the same time. {mce-short} has a `local-cluster`, which is a hub cluster that is managed. The following default addons are enabled for this `local-cluster` in the `open-cluster-management-agent-addon` namespace:

- `cluster-proxy`
- `managed-serviceaccount`
- `work-manager`

 When your {mce-short} is imported into {acm-short}, {acm-short} enables the same set of add-ons to manage the {mce-short}. 

*Required access:* Cluster administrator

.Prerequisites

* You need one or more {mce-short} clusters that are not currently managed by any {acm-short} cluster. You cannot install {mce-short} in a managed cluster.
* You need a {acm-short} cluster that is set as your hub cluster.
* Install the `clusteradm` CLI by running the following command:
+
[source,bash]
----
curl -L https://raw.githubusercontent.com/open-cluster-management-io/clusteradm/main/install.sh | bash
----

.Procedure

. Log in to your {acm-short} with the CLI.

. Update the `hypershift-addon-deploy-config` install add-ons in the `open-cluster-management-agent-addon-discovery` namespace. Run the following command:

+
[source,bash]
----
oc patch addondeploymentconfig hypershift-addon-deploy-config -n multicluster-engine --type=merge -p '{"spec":{"customizedVariables":[{"name":"configureMceImport","value":"true"}]}}'
----

. Run the following command to verify that the add-ons for the {acm-short} `local-cluster` are re-installed into the namespace that you specified:

+
[source,bash]
----
oc get deployment -n open-cluster-management-agent-addon-discovery
----
+
See the following output example:
+
[source,bash]
----
NAME                                                  READY   STATUS    RESTARTS   AGE
application-manager-6b7f74b8f7-7sd25                  1/1     Running   0          1d15h
cluster-proxy-proxy-agent-7985ddfdb6-kng5p            3/3     Running   0          1d15h
klusterlet-addon-workmgr-55fd575b4b-rs5vz             1/1     Running   0          1d15h
managed-serviceaccount-addon-agent-54bd989b94-g6gz9   1/1     Running   0          1d15h
----

. Run the following command to check the status of your configuration:

+
[source,bash]
----
oc get configmap hypershift-addon-deploy-config-info -n multicluster-engine -o yaml
----
