:_mod-docs-content-type: PROCEDURE

[#create-host-inventory-console]
= Creating a host inventory by using the console

[role="_abstract"]
You can create a host inventory (infrastructure environment) to discover physical or virtual machines that you can install your {ocp-short} clusters on.

.Prerequisites

- You must enable the {cim} service. See xref:../assisted_installer/ai_enable_cim.adoc#enable-cim[Enabling the {cim} service] for more information.

.Procedure

Complete the following steps to create a host inventory by using the console:

. From the console, navigate to *Infrastructure* > *Host inventory* and click *Create infrastructure environment*.

. Add the required information to your host inventory settings. See xref:../assisted_installer/ai_create_console_ref.adoc#host-inventory-console-settings[Host inventory console settings] for more information about the settings.

. *Optional:* If you want to enable proxy settings for your hosts, select the setting to enable it.

.Next steps

If you need advanced configuration options that are not available in the console, continue to xref:../assisted_installer/ai_create_cli.adoc#create-host-inventory-cli[Creating a host inventory by using the command line interface].

If you do not need advanced configuration options, you can continue by configuring static networking, if required, and begin adding hosts to your infrastructure environment.

.Additional resources

- link:../../clusters/credentials/credential_on_prem.adoc#creating-a-credential-hosted[Creating a credential for a hosted environment]
- xref:../assisted_installer/ai_add_host_console.adoc#add-host-host-inventory-console[Adding hosts to the host inventory by using the console]
- xref:../assisted_installer/ai_auto_add_host_console.adoc#add-hosts-console[Automatically adding bare metal hosts to the host inventory]
