:_mod-docs-content-type:

[#hosting-ipxe-artifacts]
= Hosting iPXE artifacts with HTTP or HTTPS

[role="_abstract"]
After you create your host inventory (infrastructure environment), you can discover your hosts and add them to your inventory. You can configure how to host iPXE artifacts.

To add hosts to your inventory, choose a method to download an ISO file and attach it to each server. For example, you can download ISO files by using a virtual media, or by writing the ISO file to a USB drive.

*Important:* To prevent the installation from failing, keep the Discovery ISO media connected to the device during the installation process, and set each host to boot from the device one time.

.Prerequisites

- You must enable the {cim} service. See xref:../assisted_installer/ai_enable_cim.adoc#enable-cim[Enabling the {cim} service] for more information.
- You must create a host inventory. See xref:../assisted_installer/ai_create_console.adoc#create-host-inventory-console[Creating a host inventory by using the console] for more information.

.Procedure

Change how to host iPXE artifacts by completing the following steps:

. Edit the `spec.iPXEHTTPRoute` field in the `AgentServiceConfig` custom resource.

.. Set the field to `enabled` to use HTTP for iPXE artifacts.

.. Set the field to `disabled` to use HTTPS for iPXE artifacts.

. The default value is `disabled`. See the following example, where the `spec.iPXEHTTPRoute` field is set to `enabled`:

+
[source,yaml]
----
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
spec:
  iPXEHTTPRoute: enabled
----

+
If you set the value to `enabled`, the following endpoints are exposed through HTTP:

- `api/assisted-installer/v2/infra-envs/<id>/downloads/files?file_name=ipxe-script` in `assisted-service`
- `boot-artifacts/` and `images/<infra-env-id>/pxe-initrd` in `assisted-image-service`

.Additional resources

- To learn more about the `InfraEnv` resource, see xref:../assisted_installer/ai_create_cli.adoc#create-host-inventory-cli[Creating a host inventory by using the command line interface].
