[#manage-hub-cim]
= Managing a hub cluster by using {cim}

Importing and managing a hub cluster by using {cim} can simplify your cluster management by providing a single point of control.

By default, {cim} does not automatically manage your hub cluster. Enable the feature to add and manage additional hosts on your hub cluster by using {cim}.

.Prerequisites

- You must enable the {cim} service. See xref:../assisted_installer/ai_enable_cim.adoc#enable-cim[Enabling the {cim} service] for more information.

[#manage-hub-cim-steps]
== Enabling hub cluster management by using {cim}

Complete the following step to enable {cim} to manage your hub cluster:

. Annotate the `AgentServiceConfig` custom resource to enable `local-cluster` import. Run the following command:

+
[source,bash]
----
oc annotate agentserviceconfig agent agent-install.openshift.io/enable-local-cluster-import=true 
----

. Verify that the feature is enabled by checking if an `InfraEnv` custom resource is created for the `local-cluster`. Run the following command:

+
[source,bash]
----
oc get infraenv -n multicluster-engine 
----

[#add-res-manage-hub-cim]
== Additional resources

- See xref:../assisted_installer/ai_add_host_console.adoc#add-host-host-inventory-console[Adding hosts to the host inventory by using the console]
- See xref:../assisted_installer/ai_auto_add_host_console.adoc#auto-add-host-host-inventory-console[Automatically adding bare metal hosts to the host inventory by using the console]
