:_mod-docs-content-type:

[#cim-network-config]
= Configuring advanced networking for an infrastructure environment

[role="_abstract"]
For hosts that require networking beyond DHCP on a single interface, you must configure advanced networking. The required configuration includes creating one or more instances of the `NMStateConfig` resource that describes the networking for one or more hosts. 

Each `NMStateConfig` resource must contain a label that matches the `nmStateConfigLabelSelector` on your `InfraEnv` resource. See _Creating a host inventory by using the command line interface_ to learn more about the `nmStateConfigLabelSelector`.

The Discovery Image contains the network configurations defined in all referenced `NMStateConfig` resources. After booting, each host compares each configuration to its network interfaces and applies the appropriate configuration.

.Prerequisites

- You must enable the {cim} service. See xref:../assisted_installer/ai_enable_cim.adoc#enable-cim[Enabling the {cim} service] for more information.
- You must create a host inventory. See xref:../assisted_installer/ai_create_console.adoc#create-host-inventory-console[Creating a host inventory by using the console] for more information.

== Configuring advanced networking by using the command line interface

To configure advanced networking for your infrastructure environment by using the command line interface, complete the following steps:

. Create a file named `nmstateconfig.yaml` and add content that is similar to the following template. Replace values where needed:
+
[source,yaml]
----
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: mynmstateconfig
  namespace: <your-infraenv-namespace>
  labels:
    some-key: <some-value>
spec:
  config:
    interfaces:
      - name: eth0
        type: ethernet
        state: up
        mac-address: 02:00:00:80:12:14
        ipv4:
          enabled: true
          address:
            - ip: 192.168.111.30
              prefix-length: 24
          dhcp: false
      - name: eth1
        type: ethernet
        state: up
        mac-address: 02:00:00:80:12:15
        ipv4:
          enabled: true
          address:
            - ip: 192.168.140.30
              prefix-length: 24
          dhcp: false
    dns-resolver:
      config:
        server:
          - 192.168.126.1
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.111.1
          next-hop-interface: eth1
          table-id: 254
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.140.1
          next-hop-interface: eth1
          table-id: 254
  interfaces:
    - name: "eth0"
      macAddress: "02:00:00:80:12:14"
    - name: "eth1"
      macAddress: "02:00:00:80:12:15"
----
+
*Note:* The Image Service automatically creates a new image when you update any `InfraEnv` properties or change the `NMStateConfig` resources that match its label selector. If you add `NMStateConfig` resources after creating the `InfraEnv` resource, make sure that the `InfraEnv` creates a new Discovery Image by checking the `createdTime` property in your `InfraEnv`. If you already booted hosts, boot them again with the latest Discovery Image.
+
See xref:../assisted_installer/ai_network_ref.adoc#nmstateconfig-res-overview[NMStateConfig resource overview] for more information about the `NMStateConfig` resource fields.

. Apply the YAML content by running the following command:
+
----
oc apply -f nmstateconfig.yaml
----

.Additional resources

- xref:../assisted_installer/ai_create_cli.adoc#create-host-inventory-cli[Creating a host inventory by using the command line interface]
- link:https://nmstate.io/[Declarative Network API]
