[#cim-overview]
= Host inventory overview

The {cim} feature is an {ocp} install experience in {mce-short} that focuses on managing bare-metal hosts during their lifecycle.

The {ai} is an install method for {ocp-short} that uses agents to run pre-installation validations on the target hosts, and a central service to evaluate and track install progress.

The {infra} is a {mce-short} component that manages and installs the workloads that run the {ai} service.

You can use the console to create a host inventory, which is a pool of bare-metal or virtual machines that you can use to create on-premises {ocp-short} clusters. These clusters can be standalone, with dedicated machines for the control plane, or link:../../clusters/hosted_control_planes/hosted_intro.adoc#hosted-control-planes-intro[hosted control planes], where the control plane runs as pods on a hub cluster.

You can install standalone clusters by using the console, API, or GitOps by using Zero Touch Provisioning (ZTP). See link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.16/html-single/scalability_and_performance/index#installing-disconnected-rhacm_ztp-preparing-the-hub-cluster[Installing GitOps ZTP in a disconnected environment] in the {ocp} documentation for more information on ZTP.

A machine joins the host inventory after booting with a Discovery Image. The Discovery Image is a Red Hat CoreOS live image that contains the following:

- An agent that performs discovery, validation, and installation tasks.
- The necessary configuration for reaching the service on the hub cluster, including the endpoint, token, and static network configuration, if applicable.

You have one Discovery Image for each infrastructure environment, which is a set of hosts sharing a common set of properties. The `InfraEnv` custom resource definition represents this infrastructure environment and associated Discovery Image. You can specify the Red Hat Core OS version used for the Discovery Image by setting the `osImageVersion` field in the `InfraEnv` custom resource. If you do not specify a value, the latest Red Hat Core OS version is used.

After the host boots and the agent contacts the service, the service creates a new `Agent` custom resource on the hub cluster representing that host. The `Agent` resources make up the host inventory.

You can install hosts in the inventory as OpenShift nodes later. The agent writes the operating system to the disk, along with the necessary configuration, and reboots the host.

*Note:* {acm-short} and {cim} supports the Nutanix platform by using `AgentClusterInstall`, which requires additional configuration by creating the Nutanix virtual machines. To learn more, see link:https://docs.redhat.com/en/documentation/assisted_installer_for_openshift_container_platform/2024/html/installing_openshift_container_platform_with_the_assisted_installer/assembly_installing-on-nutanix[Optional: Installing on Nutanix] in the {ai} documentation.