:_mod-docs-content-type: PROCEDURE

[#remove-nodes-wo-bm]
= Removing managed cluster nodes without a bare metal host

[role="_abstract"]
You can remove managed cluster nodes from a managed cluster. Make sure to not delete `NMStateConfig` resources when you delete the agent and bare metal host. If you do not have a bare metal host on your hub cluster and you want to remove managed cluster nodes from a managed cluster, complete the following procedure:

.Prerequisites

- You need a hub cluster that is running on a supported {ocp-short} version
- Any static networking configuration required for the node to boot must be available.

.Procedure

. Unbind the agent by removing the `clusterDeploymentName` field from the `Agent` specification, or delete the `Agent` custom resource that corresponds with the node that you are removing.

. If you want to delete an `Agent` resource from the hub cluster, but do not want the node removed from the managed cluster, set the annotation `agent.agent-install.openshift.io/skip-spoke-cleanup` to `true` on the `Agent` resource before you remove it.

.Additional resources

- link:https://docs.openshift.com/container-platform/4.18/nodes/nodes/nodes-nodes-working.html#deleting-nodes[Deleting nodes]
