[#configuring-hosting-service-cluster-ibmz]
= Configuring the hosting cluster on 'x86' bare metal for IBM Z compute nodes (Technology Preview)

**Technology Preview:** Configuring the hosting cluster on 'x86' bare metal is in a Technology Preview status with limited support.

You can deploy hosted control planes by configuring a cluster to function as a hosting cluster. The hosting cluster is the {ocp-short} cluster where the control planes are hosted. The hosting cluster is also known as the _management_ cluster. 

*Note:* The _management_ cluster is not the _managed_ cluster. A managed cluster is a cluster that the hub cluster manages.

You can enable a managed cluster as a hosting cluster by using the `hypershift` add-on to deploy the HyperShift Operator on that cluster. Then, you can start to create the hosted cluster. 

The {mce-short} 2.4 supports only the default `local-cluster`, which is a hub cluster that is managed, and the hub cluster as the hosting cluster.

**Important:**

- To provision hosted control planes on bare metal, you can use the Agent platform. The Agent platform uses the Central Infrastructure Management (CIM) service to add worker nodes to a hosted cluster. For an introduction to the CIM service, see link:https://github.com/openshift/assisted-service/blob/master/docs/hive-integration/kube-api-getting-started.md[Kube API - Getting Started Guide].

- Each IBM Z system host must be started with the PXE images that is provided by the CIM. After each host starts, it runs an Agent process to discover the details of the host and completes the installation. An Agent custom resource represents each host.

- IBM Z does not support ISO boot. 

- When you create a hosted cluster with the Agent platform, HyperShift installs the Agent Cluster API provider in the hosted control plane namespace.

- When you scale up a node pool, a machine is created. The Cluster API provider finds an Agent that is approved, is passing validations, is not currently in use, and meets the requirements that are specified in the node pool specification. You can monitor the installation of an Agent by checking its status and conditions.

- When you scale down a node pool, Agents are unbound from the corresponding cluster. Before you reuse the clusters, you must boot the clusters by using the PXE image to update the number of nodes.

[#hosting-service-cluster-configure-prereq]
== Prerequisites

You must have the following prerequisites to configure a hosting cluster: 

* You need the {mce} 2.4 and later installed on an {ocp-short} cluster. The {mce-short} is automatically installed when you install {product-title-short}. You can also install {mce-short} without {product-title-short} as an Operator from the {ocp-short} OperatorHub.

* You need the {mce-short} must have at least one managed {ocp-short} cluster. The `local-cluster` is automatically imported in {mce-short} 2.4 and later. See xref:../install_upgrade/adv_config_install.adoc#advanced-config-engine[Advanced configuration] for more information about the `local-cluster`. You can check the status of your hub cluster by running the following command:
+
----
oc get managedclusters local-cluster
----

* You need a hosting cluster with at least three worker nodes to run the HyperShift Operator.

* You need to enable Central Infrastructure Management (CIM). For more information, see xref:../cluster_lifecycle/create_infra_env.adoc#enable-cim[Enabling the Central Infrastructure Management service].

* You need to install the hosted control plane command line interface. See xref:../clusters/hosted_control_planes/hosted_install_cli.adoc[Installing the hosted control plane command line interface].

[#infrastructure-reqs-bare-metal]
== IBM Z infrastructure requirements

The Agent platform does not create any infrastructure, but requires the following for infrastructure:

* Agents: An _Agent_ represents a host that is booted with a discovery image, or PXE image and is ready to be provisioned as an {ocp-short} node.

* DNS: The API and Ingress endpoints must be routable.

[#configuring-hcp-bare-metal]
== Configuring hosted control planes on 'x86' bare metal for IBM Z compute nodes

After you meet the prerequisites, complete the following steps to configure hosted control planes on bare metal:

. xref:../hosted_control_planes/hosted_create_bare_metal.adoc#creating-a-hosted-cluster-bm[Creating a hosted cluster on bare metal]
. xref:../hosted_control_planes/config_dns_bare-metal_ibmz.adoc#configuring-dns-hosted-control-plane-ibmz[Configure DNS for Hosted Control Plane for IBM Z]
. xref:../hosted_control_planes/hosted_infraenv_ibmz.adoc#hosted-control-planes-create-infraenv-ibmz[Creating an InfraEnv resource for hosted control planes on x86 bare metal for IBM Z compute nodes]

[#hcp-bare-metal-additional-resources]
=== Additional resources

* See xref:../hosted_control_planes/enable_or_disable_hosted.adoc#enable-or-disable-hosted-control-planes[Enabling or disabling the hosted control planes feature] to disable the hosted control planes feature or manually enable it.
