[#configure-hosted-disconnected]
= Configuring hosted control planes in a disconnected environment

In the context of hosted control planes, a disconnected environment is an {ocp-short} deployment that is not connected to the internet and that uses hosted control planes as a base.

[#mce_and_agent]
== Disconnected environment architecture

When you provision hosted control planes on bare metal, you use the Agent platform. The Agent platform uses the Central Infrastructure Management (CIM) service to add worker nodes to a hosted cluster. For an introduction to the central infrastructure management service, see xref:../cluster_lifecycle/cim_enable.adoc#enable-cim[Enabling the central infrastructure management service].

The Agent platform and {mce-short} work together to enable disconnected deployments, which are not connected to the internet and use hosted control planes as a base. 

[#configure-hosted-disconnected-networks]
== Configuring hosted control planes in a disconnected environment

You can deploy hosted control planes in a disconnected environment by using an IPv4, IPv6, or dual stack network. 

Before you complete any network-specific steps, complete the steps in xref:../hosted_control_planes/monitor_user_workload_disconnected.adoc#monitor-user-workload-disconnected[Monitoring user workload in a disconnected environment], which is a procedure that is required no matter which network you use.

Next, see the instructions that are related to one of the following networking configurations on bare metal servers or virtual machines: 

* xref:../hosted_control_planes/configure_hosted_disconnected_ipv4.adoc#configure-hosted-disconnected-ipv4[IPv4]
* xref:../hosted_control_planes/configure_hosted_disconnected_ipv6.adoc#configure-hosted-disconnected-ipv6[IPv6]
* xref:../hosted_control_planes/configure_hosted_disconnected_dual_stack.adoc#configure-hosted-disconnected-dual-stack[Dual stack]