[#create-hosted-clusters-kubevirt-default-ingress-dns]
= Default ingress and DNS behavior

Every {ocp-short} cluster includes a default application Ingress Controller, which must have an wildcard DNS record associated with it. By default, hosted clusters that are created by using the HyperShift KubeVirt provider automatically become a subdomain of the {ocp-short} cluster that the KubeVirt virtual machines run on.

For example, your {ocp-short} cluster might have the following default ingress DNS entry:

[source,bash]
----
*.apps.mgmt-cluster.example.com
----

As a result, a KubeVirt hosted cluster that is named `guest` and that runs on that underlying {ocp-short} cluster has the following default ingress:

[source,bash]
----
*.apps.guest.apps.mgmt-cluster.example.com
----

For the default ingress DNS to work properly, the cluster that hosts the KubeVirt virtual machines must allow wildcard DNS routes. You can configure this behavior by entering the following command:

----
oc patch ingresscontroller -n openshift-ingress-operator default --type=json -p '[{ "op": "add", "path": "/spec/routeAdmission", "value": {wildcardPolicy: "WildcardsAllowed"}}]'
----

*Note:* When you use the default hosted cluster ingress, connectivity is limited to HTTPS traffic over port 443. Plain HTTP traffic over port 80 is rejected. This limitation applies to only the default ingress behavior.

[#create-hosted-clusters-kubevirt-customized-ingress-dns]
== Customizing ingress and DNS behavior

If you do not want to use the default ingress and DNS behavior, you can configure a KubeVirt hosted cluster with a unique base domain at creation time. This option requires manual configuration steps during creation and involves three main steps: cluster creation, load balancer creation, and wildcard DNS configuration.

[#deploy-hosted-cluster-base-domain]
=== Deploying a hosted cluster that specifies the base domain

. To create a hosted cluster that specifies the base domain, enter the following commands:

+
----
export CLUSTER_NAME=example <1>
export PULL_SECRET="$HOME/pull-secret"
export MEM="6Gi"
export CPU="2"
export WORKER_COUNT="2"
export BASE_DOMAIN=hypershift.lab <2>

hcp create cluster kubevirt \
--name $CLUSTER_NAME \
--node-pool-replicas $WORKER_COUNT \
--pull-secret $PULL_SECRET \
--memory $MEM \
--cores $CPU \
--base-domain $BASE_DOMAIN
----
+
<1> The name of the hosted cluster, which for example purposes, is `example`.
+
<2> The base domain, which for example purposes, is `hypershift.lab`.
+
The result is a hosted cluster that has an ingress wildcard that is configured for the cluster name and the base domain, or as shown in this example, `.apps.example.hypershift.lab`. The hosted cluster does not finish the deployment, but remains in `Partial` status. Because you configured a base domain, you must ensure that the required DNS records and load balancer are in place.

. Enter the following command:

+
----
oc get --namespace clusters hostedclusters
----

+
See the following example output:

+
----
NAME            VERSION   KUBECONFIG                       PROGRESS   AVAILABLE   PROGRESSING   MESSAGE
example                   example-admin-kubeconfig         Partial    True        False         The hosted control plane is available
----

. Access the cluster by entering the following commands:

+
----
hcp create kubeconfig --name $CLUSTER_NAME > $CLUSTER_NAME-kubeconfig
----

+
----
oc --kubeconfig $CLUSTER_NAME-kubeconfig get co
----

+
See the following example output:

+
----
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
console                                    4.14.0    False       False         False      30m     RouteHealthAvailable: failed to GET route (https://console-openshift-console.apps.example.hypershift.lab): Get "https://console-openshift-console.apps.example.hypershift.lab": dial tcp: lookup console-openshift-console.apps.example.hypershift.lab on 172.31.0.10:53: no such host
.
.
.
ingress                                    4.14.0    True        False         True       28m     The "default" ingress controller reports Degraded=True: DegradedConditions: One or more other status conditions indicate a degraded state: CanaryChecksSucceeding=False (CanaryChecksRepetitiveFailures: Canary route checks for the default ingress controller are failing)
----

+
The next steps fixes the errors in the output.
+
*Note:* If your cluster is on bare metal, you might need MetalLB so that you can set up load balancer services. For more information, see _Optional: Configuring MetalLB_.

[#set-up-load-balancer]
=== Setting up the load balancer 

Set up the load balancer that routes to the KubeVirt VMs and assign a wildcard DNS entry to the load balancer IP address. You need to create a load balancer service that routes ingress traffic to the KubeVirt VMs. A `NodePort` service that exposes the hosted cluster ingress already exists, so you can export the node ports and create the load balancer service that targets those ports.

. Export the node ports by entering the following commands:

+
----
export HTTP_NODEPORT=$(oc --kubeconfig $CLUSTER_NAME-kubeconfig get services -n openshift-ingress router-nodeport-default -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort}')
export HTTPS_NODEPORT=$(oc --kubeconfig $CLUSTER_NAME-kubeconfig get services -n openshift-ingress router-nodeport-default -o jsonpath='{.spec.ports[?(@.name=="https")].nodePort}')
----

. Create the load balancer service by entering the following commands:

+
----
oc apply -f -
apiVersion: v1
kind: Service
metadata:
  labels:
    app: $CLUSTER_NAME
  name: $CLUSTER_NAME-apps
  namespace: clusters-$CLUSTER_NAME
spec:
  ports:
  - name: https-443
    port: 443
    protocol: TCP
    targetPort: ${HTTPS_NODEPORT}
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: ${HTTP_NODEPORT}
  selector:
    kubevirt.io: virt-launcher
  type: LoadBalancer
----

[#set-up-wildcard-dns]
=== Setting up a wildcard DNS 

Set up up a wildcard DNS record or CNAME that references the external IP of the load balancer service.

. Export the external IP by entering the following command:

+
----
export EXTERNAL_IP=$(oc -n clusters-$CLUSTER_NAME get service $CLUSTER_NAME-apps -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
----

. Configure a wildcard DNS entry that references the IP that is stored in the `$EXTERNAL_IP` path. View the following example DNS entry:

+
[source,bash]
----
*.apps.<hosted-cluster-name\>.<base-domain\>.
----

+
The DNS entry must be able to route inside and outside of the cluster. If you use the example input from step 1, for the cluster that has an external IP value of `192.168.20.30`, the DNS resolutions look like this example:

+
----
dig +short test.apps.example.hypershift.lab

192.168.20.30
----

. Check the hosted cluster status and ensure that it has moved from `Partial` to `Completed` by entering the following command:

+
----
oc get --namespace clusters hostedclusters
----

+
See the following example output:

+
----
NAME            VERSION   KUBECONFIG                       PROGRESS    AVAILABLE   PROGRESSING   MESSAGE
example         4.14.0    example-admin-kubeconfig         Completed   True        False         The hosted control plane is available
----

[#default-ingress-dns-additional-resources]
=== Additional resources

- xref:../hosted_control_planes/kubevirt_intro.adoc#hosted-control-planes-manage-kubevirt[Managing hosted control plane clusters on OpenShift Virtualization]
- xref:../hosted_control_planes/config_metallb_bm.adoc#hosting-service-cluster-configure-metallb-config[Optional: Configuring MetalLB]
- Return to the beginning of this topic, <<create-hosted-clusters-kubevirt-default-ingress-dns,Default ingress and DNS behavior>>.