[#create-hosted-clusters-kubevirt-default-ingress-dns]
= Default ingress and DNS behavior

Every {ocp-short} cluster includes a default application Ingress Controller, which must have an wildcard DNS record associated with it. By default, hosted clusters that are created by using the HyperShift KubeVirt provider automatically become a subdomain of the {ocp-short} cluster that the KubeVirt virtual machines run on.

For example, your {ocp-short} cluster might have the following default ingress DNS entry:

[source,bash]
----
*.apps.mgmt-cluster.example.com
----

As a result, a KubeVirt hosted cluster that is named `guest` and that runs on that underlying {ocp-short} cluster has the following default ingress:

[source,bash]
----
*.apps.guest.apps.mgmt-cluster.example.com
----

For the default ingress DNS to work properly, the cluster that hosts the KubeVirt virtual machines must allow wildcard DNS routes. You can configure this behavior by entering the following command:

----
oc patch ingresscontroller -n openshift-ingress-operator default --type=json -p '[{ "op": "add", "path": "/spec/routeAdmission", "value": {wildcardPolicy: "WildcardsAllowed"}}]'
----

*Note:* When you use the default hosted cluster ingress, connectivity is limited to HTTPS traffic over port 443. Plain HTTP traffic over port 80 is rejected. This limitation applies to only the default ingress behavior.

[#create-hosted-clusters-kubevirt-customized-ingress-dns]
== Customizing ingress and DNS behavior

If you do not want to use the default ingress and DNS behavior, you can configure a KubeVirt hosted cluster with a unique base domain at creation time. This option requires manual configuration steps during creation and involves three main steps: cluster creation, load balancer creation, and wildcard DNS configuration.

[#deploy-hosted-cluster-base-domain]
=== Deploying a hosted cluster that specifies the base domain

. To create a hosted cluster that specifies the base domain, enter the following command:

+
----
hcp create cluster kubevirt \
--name <hosted-cluster-name> \ <1>
--node-pool-replicas <worker-count> \ <2>
--pull-secret <path-to-pull-secret> \ <3>
--memory <value-for-memory> \ <4>
--cores <value-for-cpu> \ <5>
--base-domain <basedomain> <6>
----

<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the worker count, for example, `2`.
<3> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<4> Specify a value for memory, for example, `6Gi`.
<5> Specify a value for CPU, for example, `2`.
<6> Specify the base domain, for example, `hypershift.lab`.

As a result, the hosted cluster has an ingress wildcard that is configured for the cluster name and the base domain, for example, `.apps.example.hypershift.lab`. The hosted cluster remains in `Partial` status. Because, after creating a hosted cluster with unique base domain, you must configure the required DNS records and load balancer.

. View the status of your hosted cluster by entering the following command:

+
----
oc get --namespace clusters hostedclusters
----

+
See the following example output:

+
----
NAME            VERSION   KUBECONFIG                       PROGRESS   AVAILABLE   PROGRESSING   MESSAGE
example                   example-admin-kubeconfig         Partial    True        False         The hosted control plane is available
----

. Access the cluster by entering the following commands:

+
----
hcp create kubeconfig --name <hosted-cluster-name> > <hosted-cluster-name>-kubeconfig
----

+
----
oc --kubeconfig <hosted-cluster-name>-kubeconfig get co
----

+
See the following example output:

+
----
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
console                                    4.x.0     False       False         False      30m     RouteHealthAvailable: failed to GET route (https://console-openshift-console.apps.example.hypershift.lab): Get "https://console-openshift-console.apps.example.hypershift.lab": dial tcp: lookup console-openshift-console.apps.example.hypershift.lab on 172.31.0.10:53: no such host
ingress                                    4.x.0     True        False         True       28m     The "default" ingress controller reports Degraded=True: DegradedConditions: One or more other status conditions indicate a degraded state: CanaryChecksSucceeding=False (CanaryChecksRepetitiveFailures: Canary route checks for the default ingress controller are failing)
----
+
Replace `4.x.0` with the supported {ocp-short} version that you want to use.

+
The next steps fixes the errors in the output.
+
*Note:* If your hosted cluster is on bare metal, you might need MetalLB to set up load balancer services. For more information, see _Optional: Configuring MetalLB_.

[#set-up-load-balancer]
=== Setting up the load balancer

Set up the load balancer service that routes ingress traffic to the KubeVirt VMs and assigns a wildcard DNS entry to the load balancer IP address.

. A `NodePort` service that exposes the hosted cluster ingress already exists. You can export the node ports and create the load balancer service that targets those ports.

.. Get the HTTP node port by entering the following command:

+
----
oc --kubeconfig <hosted-cluster-name>-kubeconfig get services -n openshift-ingress router-nodeport-default -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort}'
----

+
Note the HTTP node port value to use in the next step.

.. Get the HTTPS node port by entering the following command:

+
----
oc --kubeconfig <hosted-cluster-name>-kubeconfig get services -n openshift-ingress router-nodeport-default -o jsonpath='{.spec.ports[?(@.name=="https")].nodePort}'
----

+
Note the HTTPS node port value to use in the next step.

. Create the load balancer service by entering the following command:

+
----
oc apply -f -
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <hosted-cluster-name>
  name: <hosted-cluster-name>-apps
  namespace: clusters-<hosted-cluster-name>
spec:
  ports:
  - name: https-443
    port: 443
    protocol: TCP
    targetPort: <https-node-port> <1>
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: <http-node-port> <2>
  selector:
    kubevirt.io: virt-launcher
  type: LoadBalancer
----

+
<1> Specify the HTTPS node port value that you noted in the previous step.
<2> Specify the HTTP node port value that you noted in the previous step.

[#set-up-wildcard-dns]
=== Setting up a wildcard DNS

Set up up a wildcard DNS record or CNAME that references the external IP of the load balancer service.

. Get the external IP address by entering the following command:

+
----
oc -n clusters-<hosted-cluster-name> get service <hosted-cluster-name>-apps -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
----

+
See the following example output:

+
----
192.168.20.30
----

. Configure a wildcard DNS entry that references the external IP address. View the following example DNS entry:

+
[source,bash]
----
*.apps.<hosted-cluster-name\>.<base-domain\>.
----

+
The DNS entry must be able to route inside and outside of the cluster. See the following DNS resolutions example:

+
----
dig +short test.apps.example.hypershift.lab

192.168.20.30
----

. Check that hosted cluster status has moved from `Partial` to `Completed` by entering the following command:

+
----
oc get --namespace clusters hostedclusters
----

+
See the following example output:

+
----
NAME            VERSION   KUBECONFIG                       PROGRESS    AVAILABLE   PROGRESSING   MESSAGE
example         4.x.0     example-admin-kubeconfig         Completed   True        False         The hosted control plane is available
----
+
Replace `4.x.0` with the supported {ocp-short} version that you want to use.

[#default-ingress-dns-additional-resources]
=== Additional resources

- xref:../hosted_control_planes/kubevirt_intro.adoc#hosted-control-planes-manage-kubevirt[Managing hosted control plane clusters on OpenShift Virtualization]
- xref:../hosted_control_planes/config_metallb_bm.adoc#hosting-service-cluster-configure-metallb-config[Optional: Configuring MetalLB]
- Return to the beginning of this topic, <<create-hosted-clusters-kubevirt-default-ingress-dns,Default ingress and DNS behavior>>.
