[#configure-hosted-disconnected-ipv4]
= Configuring hosted control planes on an IPv4 network

The steps to configure hosted control planes on an IPv4 network are as follows:

. <<ipv4-hypervisor,Configure the hypervisor>>
. Configure the DNS
. Deploy a registry
. Set up the management cluster
. Set up the web server
. Set up mirroring and image content sources
. Set up {mce-short}
. Configure TLS certificates
. Configure the hosted cluster
. Finish the deployment

[#ipv4-hypervisor]
== Configuring the hypervisor

The following information applies to virtual machine environments only.

. Ensure that you meet the following prerequisites:

+
//lahinson - sept 2023 - the upstream docs refer to this list as "bare metal requisites" even though the intro to the hypervisor section states that this section is for virtual machine environments only. Do these prerequisites also apply to virtual machine environments?

** CPU: The number of CPUs provided determines how many hosted clusters can run concurrently. In general, use 16 CPUs for each node for 3 nodes. For minimal development, you can use 12 CPUs for each node for 3 nodes.
** Memory: The amount of RAM affects how many hosted clusters can be hosted. Use 48 GB of RAM for each node. For minimal development, 18 GB of RAM might be sufficient.
** Storage: Use SSD storage for {mce-short}. 
*** Management cluster: 250 GB.
*** Registry: The storage needed depends on the number of releases, operators, and images that are hosted. An acceptable number might be 500 GB, preferably separated from the disk that hosts the hosted cluster.
*** Web server: The storage needed depends on the number of ISOs and images that are hosted. An acceptable number might be 500 GB.
** Production: For a production environment, separate the management cluster, the registry, and the web server on different disks. This example illustrates a possible configuration for production:
*** Registry: 2 TB
*** Management cluster: 500 GB
*** Web server: 2 TB

+
//lahinson - sept 2023 - adding comment to ensure proper formatting

. To deploy a virtual {ocp-short} management cluster, access the required packages by entering the following command:

+
----
sudo dnf install dnsmasq radvd vim golang podman bind-utils net-tools httpd-tools tree htop strace tmux -y
----

. Enable and start the Podman service by entering the following command:

+
----
systemctl enable --now podman
----

. To use kcli to deploy the {ocp-short} management cluster and other virtual components, install and configure the hypervisor by entering the following commands:

+
----
sudo yum -y install libvirt libvirt-daemon-driver-qemu qemu-kvm
----

+
----
sudo usermod -aG qemu,libvirt $(id -un)
----

+
----
sudo newgrp libvirt
----

+
----
sudo systemctl enable --now libvirtd
----

+
----
sudo dnf -y copr enable karmab/kcli
----

+
----
sudo dnf -y install kcli
----

+
----
sudo kcli create pool -p /var/lib/libvirt/images default
----

+
----
kcli create host kvm -H 127.0.0.1 local
----

+
----
sudo setfacl -m u:$(id -un):rwx /var/lib/libvirt/images
----

+
----
kcli create network  -c 192.168.122.0/24 default
----

. Enable the network dispatch manager to ensure that virtual machines can resolve the required domains, routes, and registries. To enable the network manager dispatcher, in the `/etc/NetworkManager/dispatcher.d/` directory, create a script named `forcedns` that contains the following content, replacing values as necessary to match your environment:

+
----
#!/bin/bash

export IP="192.168.126.1" <1>
export BASE_RESOLV_CONF="/run/NetworkManager/resolv.conf"

if ! [[ `grep -q "$IP" /etc/resolv.conf` ]]; then
export TMP_FILE=$(mktemp /etc/forcedns_resolv.conf.XXXXXX)
cp $BASE_RESOLV_CONF $TMP_FILE
chmod --reference=$BASE_RESOLV_CONF $TMP_FILE
sed -i -e "s/hypershiftbm.lab//" -e "s/search /& hypershiftbm.lab /" -e "0,/nameserver/s/nameserver/& $IP\n&/" $TMP_FILE
mv $TMP_FILE /etc/resolv.conf
fi
echo "ok"
----

+
<1> Modify the `IP` variable to point to the IP address of the hypervisor interface that hosts the {ocp-short} management cluster.

. After you create the file, add execution permissions by entering the following command:

+
----
chmod 755 /etc/NetworkManager/dispatcher.d/forcedns
----

. Run the script and verify that the output returns `ok`.

. Configure `ksushy` to simulate baseboard management controllers (BMCs) for the virtual machines. Enter the following commands:

+
----
sudo dnf install python3-pyOpenSSL.noarch python3-cherrypy -y
----

+
----
kcli create sushy-service --ssl --port 9000
----

+
----
sudo systemctl daemon-reload
----

+
----
systemctl enable --now ksushy
----

. Test whether the service is correctly functioning by entering the following command:

+
----
systemctl status ksushy
----

. If you are working in a development environment, configure the hypervisor system to allow various types of connections through different virtual networks within the environment.

+
*Note:* If you are working in a production environment, you must establish proper rules for the `firewalld` service and configure SELinux policies to maintain a secure environment. 

** For SELinux, enter the following command:

+
----
sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config; setenforce 0
----

** For `firewalld`, enter the following command:

+
----
systemctl disable --now firewalld
----

** For `libvirtd`, enter the following commands:

+
----
systemctl restart libvirtd
----

+
----
systemctl enable --now libvirtd
----

+
//lahinson - sept 2023 - adding comment to ensure proper formatting

Next, configure DNS for your environment.

[#ipv4-dns]
== Configuring DNS

This step is mandatory for both disconnected and connected environments in both virtual and bare metal environments. The key distinction lies in the location where the resources will be configured. In a non-virtual environment, use a solution like Bind instead of a lightweight solution like `dnsmasq`.

//lahinson - sept 2023 - if this step is mandatory for both connected and disconnected environments, does it override the info that we already have published for configuring DNS in the official docs? See https://github.com/stolostron/rhacm-docs/blob/2.9_stage/clusters/hosted_control_planes/hosted_bare_metal_dns.adoc and https://github.com/stolostron/rhacm-docs/blob/2.9_stage/clusters/hosted_control_planes/hosted_bare_metal_dns.adoc.

To enable name resolution in a virtual environment, complete the following steps:

. In the `/opt/dnsmasq/` directory, create the primary DNS configuration file for the `dnsmasq` server and name the file `dnsmasq.conf`.

. Add the following content to the file:

+
//lahinson - sept 2023 - strip comments out of file content, ask 

+
----
strict-order
bind-dynamic
#log-queries
bogus-priv
dhcp-authoritative

dhcp-range=ipv4,192.168.125.120,192.168.125.250,255.255.255.0,24h
dhcp-option=ipv4,option:dns-server,192.168.125.1
dhcp-option=ipv4,option:router,192.168.125.1

resolv-file=/opt/dnsmasq/upstream-resolv.conf
except-interface=lo
dhcp-lease-max=81
log-dhcp
no-hosts

# DHCP Reservations
dhcp-leasefile=/opt/dnsmasq/hosts.leases

# Include all files in a directory depending on the suffix
conf-dir=/opt/dnsmasq/include.d/*.ipv4
----

. Create the upstream resolver to delegate the non-local environment queries. In the `/opt/dnsmasq/upstream-resolv.conf` file, enter the following information:

+
----
nameserver 8.8.8.8
nameserver 8.8.4.4
----

. Create the different component DNS configurations. 

.. In the `/opt/dnsmasq/include.d/hosted-nodeport.ipv4` file, enter the following information:

+
----
## Nodeport
host-record=api-int.hosted-ipv4.hypershiftbm.lab,192.168.125.20
host-record=api-int.hosted-ipv4.hypershiftbm.lab,192.168.125.21
host-record=api-int.hosted-ipv4.hypershiftbm.lab,192.168.125.22
host-record=api.hosted-ipv4.hypershiftbm.lab,192.168.125.20
host-record=api.hosted-ipv4.hypershiftbm.lab,192.168.125.21
host-record=api.hosted-ipv4.hypershiftbm.lab,192.168.125.22

## Nodeport
## IMPORTANT!: You should point to the node which is exposing the router.
## You can also use MetalLB to expose the Apps wildcard.
address=/apps.hosted-ipv4.hypershiftbm.lab/192.168.125.30

## General
dhcp-host=aa:aa:aa:aa:02:01,hosted-ipv4-worker0,192.168.125.30
dhcp-host=aa:aa:aa:aa:02:02,hosted-ipv4-worker1,192.168.125.31
dhcp-host=aa:aa:aa:aa:02:03,hosted-ipv4-worker2,192.168.125.32
----

.. In the `/opt/dnsmasq/include.d/hub.ipv4` file, enter the following information:

+
----
host-record=api-int.hub-ipv4.hypershiftbm.lab,192.168.125.10
host-record=api.hub-ipv4.hypershiftbm.lab,192.168.125.10
address=/apps.hub-ipv4.hypershiftbm.lab/192.168.125.11
dhcp-host=aa:aa:aa:aa:02:01,ocp-master-0,192.168.125.20
dhcp-host=aa:aa:aa:aa:02:02,ocp-master-1,192.168.125.21
dhcp-host=aa:aa:aa:aa:02:03,ocp-master-2,192.168.125.22
dhcp-host=aa:aa:aa:aa:02:06,ocp-installer,192.168.125.25
dhcp-host=aa:aa:aa:aa:02:10,ocp-bootstrap,192.168.125.26
----

.. In the `/opt/dnsmasq/include.d/infra.ipv4` file, enter the following information:

+
----
host-record=registry.hypershiftbm.lab,192.168.125.1
----

+
//lahinson - sept 2023 - adding comment to ensure proper formatting

. Create a systemd service for the management of the dnsmasq service, and disable the default dnsmasq service. In the `/etc/systemd/system/dnsmasq-virt.service` file, enter the following information:

+
----
[Unit]
Description=DNS server for Openshift 4 Clusters.
After=network.target

[Service]
User=root
Group=root
ExecStart=/usr/sbin/dnsmasq -k --conf-file=/opt/dnsmasq/dnsmasq.conf

[Install]
WantedBy=multi-user.target
----

. Enter the following commands:

+
----
systemctl daemon-reload
----

+
----
systemctl disable --now dnsmasq
----

+
----
systemctl enable --now dnsmasq-virt
----

+
//lahinson - sept 2023 - adding comment to ensure proper formatting

[#ipv4-registry]
== Deploying a registry

[#ipv4-additional-resources]
=== Additional resources

* For more information about kcli, see the link:https://kcli.readthedocs.io/en/latest/[official kcli documentation].
