[#configure-hosted-disconnected]
= Configuring hosted control planes in a disconnected environment

The `hypershift-addon` managed cluster add-on enables the `--enable-uwm-telemetry-remote-write` option in the HyperShift Operator. By enabling that option, you ensure that user workload monitoring is enabled and that it can remotely write telemetry metrics from control planes. 

If you installed {mce-short} on {ocp-short} clusters that are not connected to the internet, when you try to run the user workload monitoring feature of the HyperShift Operator by entering the following command, the feature fails with an error:

----
oc get events -n hypershift
----

The error might look like this example:

----
LAST SEEN   TYPE      REASON           OBJECT                MESSAGE
4m46s       Warning   ReconcileError   deployment/operator   Failed to ensure UWM telemetry remote write: cannot get telemeter client secret: Secret "telemeter-client" not found
----

To avoid that error, you must disable the user workload monitoring option by creating a config map in the `local-cluster` namespace. You can create the config map either before or after you enable the add-on. The add-on agent reconfigures the HyperShift Operator.

. Create the following config map:

+
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: hypershift-operator-install-flags
  namespace: local-cluster
data:
  installFlagsToAdd: ""
  installFlagsToRemove: "--enable-uwm-telemetry-remote-write"
----

//For more information about the config map, see the HyperShift Operator configuration options. ADD LINK

[#verify-hosted-control-plane-feature]
== 