[#creating-a-hosted-cluster-kubevirt]
= Creating a hosted cluster with the KubeVirt platform

. To create a hosted cluster, use environment variables and the `hcp` command line interface:

+
----
export CLUSTER_NAME=example
export PULL_SECRET="$HOME/pull-secret"
export MEM="6Gi"
export CPU="2"
export WORKER_COUNT="2"

hcp create cluster kubevirt \
--name $CLUSTER_NAME \
--node-pool-replicas $WORKER_COUNT \
--pull-secret $PULL_SECRET \
--memory $MEM \
--cores $CPU
----
+
Replace values as necessary.
+
*Note:* You can use the `--release-image` flag to set up the hosted cluster with a specific {ocp-short} release.
+
A default node pool is created for the cluster with two virtual machine worker replicas according to the `--node-pool-replicas` flag.

. After a few moments, verify that the hosted control plane pods are running by entering the following command:

+
----
oc -n clusters-$CLUSTER_NAME get pods
----

+
See the following example output:

+
----
NAME                                                  READY   STATUS    RESTARTS   AGE
capi-provider-5cc7b74f47-n5gkr                        1/1     Running   0          3m
catalog-operator-5f799567b7-fd6jw                     2/2     Running   0          69s
certified-operators-catalog-784b9899f9-mrp6p          1/1     Running   0          66s
cluster-api-6bbc867966-l4dwl                          1/1     Running   0          66s
.
.
.
redhat-operators-catalog-9d5fd4d44-z8qqk              1/1     Running   0          66s
----

+
A hosted cluster that has worker nodes that are backed by KubeVirt virtual machines typically takes 10-15 minutes to be fully provisioned.

. To check the status of the hosted cluster, see the corresponding `HostedCluster` resource by entering the following command:

+
----
oc get --namespace clusters hostedclusters
----

+ 
See the following example output, which illustrates a fully provisioned `HostedCluster` object:

+
----
NAMESPACE   NAME      VERSION   KUBECONFIG                 PROGRESS    AVAILABLE   PROGRESSING   MESSAGE
clusters    example   4.12.7    example-admin-kubeconfig   Completed   True        False         The hosted control plane is available
----

Next, you can access the hosted cluster by following the instructions in xref:../hosted_control_planes/hosting_service_cluster_access.adoc#access-hosted-cluster[Accessing the hosted cluster].