[#create-hosted-multi-zone-aws]
= Creating a hosted cluster in multiple zones on AWS

Create a cluster, specifying the base domain of the public zone, by entering the following command:

----
hcp create cluster aws \
--name <hosted-cluster-name> \ <1>
--node-pool-replicas=<node-pool-replica-count> \ <2>
--base-domain <basedomain> \ <3>
--pull-secret <path-to-pull-secret> \ <4>
--sts-creds <path-to-aws-credentials> \ <5>
--role-arn <cli-role-arn> \ <6>
--region <region> \ <7>
--zones <zones> <8>
----

<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the node pool replica count, for example, `2`.
<3> Specify your base domain, for example, `example.com`.
<4> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<5> Specify the path to your AWS Security Token Service (STS) credentials file, for example, `/user/name/.aws/credentials`. This can be generated with "aws sts get-session-token --output json" command
<6> Specify the hcp CLI role ARN to assume. 
<7> Specify the AWS region name, for example, `us-east-1`.
<8> Specify availability zones within your AWS region, for example, `us-east-1a`, and `us-east-1b`.

For each specified zone, the following infrastructure is created:

* Public subnet
* Private subnet
* NAT gateway
* Private route table (public route table is shared across public subnets)

One `NodePool` resource is created for each zone. The node pool name is suffixed by the zone name. The private subnet for zone is set in `spec.platform.aws.subnet.id`.

[#create-hosted-multi-zone-aws-credentials]
== Providing credentials for creating a hosted cluster on AWS

When you create a hosted cluster by using the `hcp create cluster aws` command, you need to provide AWS account Security Token Service credentials that have permissions to create infrastructure resources for your cluster and a hcp CLI assume role ARN. Examples of infrastructure resources include VPCs, subnets, and NAT gateways.

See the following example:

----
hcp create cluster aws \
--name <hosted-cluster-name> \ <1>
--node-pool-replicas=<node-pool-replica-count> \ <2>
--base-domain <basedomain> \ <3>
--pull-secret <path-to-pull-secret> \ <4>
--sts-creds <path-to-aws-credentials> \ <5>
--role-arn <cli-role-arn> \ <6>
--region <region> <7>
----

<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the node pool replica count, for example, `2`.
<3> Specify your base domain, for example, `example.com`.
<4> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<5> Specify the path to your AWS Security Token Service (STS) credentials file, for example, `/user/name/.aws/credentials`. This can be generated with "aws sts get-session-token --output json" command
<6> Specify the hcp CLI role ARN to assume. 
<7> Specify the AWS region name, for example, `us-east-1`.

//lahinson - sept. 2023 - including comment to ensure proper formatting

[#create-hosted-aws-additional-resources]
== Additional resources

For instructions to install the AWS Elastic File Service (EFS) CSI Driver Operator on a hosted cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/storage/using-container-storage-interface-csi#efs-sts_persistent-storage-csi-aws-efs[Configuring AWS EFS CSI Driver Operator with Security Token Service].
