[#create-hosted-multi-zone-aws]
= Creating a hosted cluster in multiple zones on AWS

Before you create a hosted cluster on Amazon Web Services (AWS), you must create an AWS Identity and Access Management (IAM) role and AWS Security Token Service (STS) credentials. See xref:../../clusters/hosted_control_planes/create_role_sts_aws.adoc#create-role-sts-aws[Creating an AWS IAM role and STS credentials].

Create a hosted cluster in multiple zones on AWS by running the following command:

[source,bash]
----
hcp create cluster aws \
--name <hosted_cluster_name> \ <1>
--node-pool-replicas=<node_pool_replica_count> \ <2>
--base-domain <basedomain> \ <3>
--pull-secret <path_to_pull_secret> \ <4>
--role-arn <arn_role> \ <5>
--region <region> \ <6>
--zones <zones> <7>
--sts-creds <path_to_sts_credential_file> <8>
----

<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the node pool replica count, for example, `2`.
<3> Specify your base domain, for example, `example.com`.
<4> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<5> Specify the Amazon Resource Name (ARN), for example, `arn:aws:iam::820196288204:role/myrole`.
<6> Specify the AWS region name, for example, `us-east-1`.
<7> Specify availability zones within your AWS region, for example, `us-east-1a`, and `us-east-1b`.
<8> Specify the path to your AWS STS credentials file, for example, `/home/user/sts-creds/sts-creds.json`.

For each specified zone, the following infrastructure is created:

* Public subnet
* Private subnet
* NAT gateway
* Private route table (public route table is shared across public subnets)

One `NodePool` resource is created for each zone. The node pool name is suffixed by the zone name. The private subnet for zone is set in `spec.platform.aws.subnet.id`.

[#create-hosted-multi-zone-aws-credentials]
== Providing credentials for creating a hosted cluster on AWS

When you create a hosted cluster by using the `hcp create cluster aws` command, you need to provide AWS account credentials that have permissions to create infrastructure resources for your cluster. Examples of infrastructure resources include VPCs, subnets, and NAT gateways. You can provide the AWS credentials in two ways: by using the `--sts-creds` flag or by using the AWS cloud provider secret from {mce-short}.

[#create-hosted-multi-zone-aws-creds-flag]
=== Providing credentials by using the --sts-creds flag

You can use AWS STS credentials to create a hosted cluster by specifying the `--sts-creds` flag. Run the following command:

[source,bash]
----
hcp create cluster aws \
--name <hosted_cluster_name> \ <1>
--node-pool-replicas <node_pool_replica_count> \ <2>
--base-domain <basedomain> \ <3>
--pull-secret <path_to_pull_secret> \ <4>
--sts-creds <path_to_sts_credential_file> \ <5>
--region <region> <6>
--role-arn <arn_role> \ <7>
----

<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the node pool replica count, for example, `2`.
<3> Specify your base domain, for example, `example.com`.
<4> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<5> Specify the path to your AWS STS credentials file, for example, `/home/user/sts-creds/sts-creds.json`.
<6> Specify the AWS region name, for example, `us-east-1`.
<7> Specify the Amazon Resource Name (ARN), for example, `arn:aws:iam::820196288204:role/myrole`.

[#create-hosted-multi-zone-aws-cloud-provider-secret]
=== Providing credentials by using the AWS cloud provider secret

You can use the `hcp create cluster aws` command with the `--secret-creds` flag to provide AWS cloud provider secret. Complete the following steps:

. Create a hosted cluster by running the following command:

+
[source,bash]
----
hcp create cluster aws \
--name <hosted_cluster_name> \ <1>
--region <region> \ <2>
--namespace <hosted_cluster_namespace> \ <3>
--secret-creds <aws_secret_name> <4>
--sts-creds <path_to_sts_credential_file> <5>
--base-domain <basedomain> \ <6>
--pull-secret <path_to_pull_secret> \ <7>
--ssh-key-file <ssh_key> <8>
----

+
<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the AWS region name, for example, `us-east-1`.
<3> If the secret is not in the default `clusters` namespace, specify your hosted cluster namespace.
<4> Specify the AWS secret name, for example, `my-aws-cred`.
<5> Specify the path to your AWS STS credentials file, for example, `/home/user/sts-creds/sts-creds.json`.
<6> Specify your base domain, for example, `example.com`.
<7> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<8> Specify the SSH public key file to connect to the bastion. The default location for the SSH public key file is `~/.ssh/id_rsa.pub`.

+
. To create the secret by using the {mce-short} console, from the navigation menu, select *Credentials* and follow the credential creation steps in the console.

. To create the secret on the command line, enter the following command:

+
[source,bash]
----
oc create secret generic <aws_secret_name> -n <namespace> --from-literal=baseDomain=<basedomain> --from-literal=aws_access_key_id=<aws_access_key> --from-literal=aws_secret_access_key=<aws_secret_key> --from-literal=pullSecret='{"auths":{"cloud.openshift.com":{"auth":"<auth>", "email":"<email>"}, "quay.io":{"auth":"<auth>", "email":"<email>"} } }' --from-literal=ssh-publickey=<ssh_public_key> --from-literal=ssh-privatekey=<ssh_private_key>
----

+
The secret has the following format:

+
[source,yaml]
----
apiVersion: v1
metadata:
  name: <aws_secret_name> <1>
  namespace: <hosted_cluster_namespace> <2>
type: Opaque
kind: Secret
stringData:
  ssh-publickey:          # Value
  ssh-privatekey:         # Value
  pullSecret:             # Value, required
  baseDomain:             # Value, required
  aws_secret_access_key:  # Value, required
  aws_access_key_id:      # Value, required
----

[#create-hosted-aws-additional-resources]
== Additional resources

For instructions to install the AWS Elastic File Service (EFS) CSI Driver Operator on a hosted cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/storage/using-container-storage-interface-csi#efs-sts_persistent-storage-csi-aws-efs[Configuring AWS EFS CSI Driver Operator with Security Token Service].
