[#creating-a-hosted-cluster-bm]
= Creating a hosted cluster on bare metal

You can create a hosted cluster or import one. For instructions to import a hosted cluster, see _Importing a hosted cluster_.

. Create the hosted control plane namespace by entering the following command:

+
----
oc create ns <hosted-cluster-namespace>-<hosted-cluster-name>
----

+
Replace `<hosted-cluster-namespace>` with your hosted cluster namespace name, for example, `clusters`. Replace `<hosted-cluster-name>` with your hosted cluster name.

. Verify that you have a default storage class configured for your cluster. Otherwise, you might see pending PVCs. See the following example:

+
----
hcp create cluster agent \
    --name=<hosted-cluster-name> \ <1>
    --pull-secret=<path-to-pull-secret> \ <2>
    --agent-namespace=<hosted-control-plane-namespace> \ <3>
    --base-domain=<basedomain> \ <4>
    --api-server-address=api.<hosted-cluster-name>.<basedomain> \
    --etcd-storage-class=<etcd-storage-class> \ <5>
    --ssh-key  <path-to-ssh-key> \ <6>
    --namespace <hosted-cluster-namespace> \ <7>
    --control-plane-availability-policy SingleReplica \
    --release-image=quay.io/openshift-release-dev/ocp-release:<ocp-release> <8>
----

+
<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<3> Specify your hosted control plane namespace, for example, `clusters-example`. Ensure that agents are available in this namespace by using the `oc get agent -n <hosted-control-plane-namespace>` command.
<4> Specify your base domain, for example, `krnl.es`.
<5> Specify the etcd storage class name, for example, `lvm-storageclass`.
<6> Specify the path to your SSH public key. The default file path is `~/.ssh/id_rsa.pub`.
<7> Specify your hosted cluster namespace.
<8> Specify the supported {ocp-short} version that you want to use, for example, `4.14.0-x86_64`.

+
. After a few moments, verify that your hosted control plane pods are up and running by entering the following command:

+
----
oc -n <hosted-control-plane-namespace> get pods
----

+
See the following example output:

+
----
NAME                                             READY   STATUS    RESTARTS   AGE
capi-provider-7dcf5fc4c4-nr9sq                   1/1     Running   0          4m32s
catalog-operator-6cd867cc7-phb2q                 2/2     Running   0          2m50s
certified-operators-catalog-884c756c4-zdt64      1/1     Running   0          2m51s
cluster-api-f75d86f8c-56wfz                      1/1     Running   0          4m32s
cluster-autoscaler-7977864686-2rz4c              1/1     Running   0          4m13s
cluster-network-operator-754cf4ffd6-lwfm2        1/1     Running   0          2m51s
----

[#hosted-create-bare-metal-console]
== Creating a hosted cluster on bare metal by using the console

. Open the {ocp-short} web console and log in by entering your administrator credentials. For instructions to open the console, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-version}/html/web_console/web-console[Accessing the web console] in the {ocp-short} documentation.

. In the console header, ensure that **All Clusters** is selected.

. Click **Infrastructure > Clusters**.

. Click **Create cluster > Host inventory > Hosted control plane**.

+
The **Create cluster** page is displayed.

. On the **Create cluster** page, follow the prompts to enter details about the cluster, node pools, networking, and automation.

+
*Note:* As you enter details about the cluster, you might find the following tips useful:

** If you want to use predefined values to automatically populate fields in the console, you can create a host inventory credential. For more information, see _Creating a credential for an on-premises environment_.

** On the *Cluster details* page, the pull secret is your {ocp-short} pull secret that you use to access {ocp-short} resources. If you selected a host inventory credential, the pull secret is automatically populated.

** On the *Node pools* page, the namespace contains the hosts for the node pool. If you created a host inventory by using the console, the console creates a dedicated namespace.

** On the *Networking* page, you select an API server publishing strategy. The API server for the hosted cluster can be exposed either by using an existing load balancer or as a service of the `NodePort` type. A DNS entry must exist for the `api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}` setting that points to the destination where the API server can be reached. This entry can be a record that points to one of the nodes in the management cluster or a record that points to a load balancer that redirects incoming traffic to the Ingress pods.

. Review your entries and click **Create**.

+
The **Hosted cluster** view is displayed.

. Monitor the deployment of the hosted cluster in the **Hosted cluster** view.

. If you do not see information about the hosted cluster, ensure that **All Clusters** is selected, then click the cluster name.

. Wait until the control plane components are ready. This process can take a few minutes.

. To view the node pool status, scroll to the **NodePool** section. The process to install the nodes takes about 10 minutes. You can also click **Nodes** to confirm whether the nodes joined the hosted cluster.

[#hosted-create-bare-metal-additional-resources]
== Additional resources

* To create credentials that you can reuse when you create a hosted cluster with the console, see xref:../credentials/credential_on_prem.adoc#creating-a-credential-for-an-on-premises-environment[Creating a credential for an on-premises environment].

* To import a hosted cluster, see xref:../hosted_control_planes/import_hosted_cluster.adoc#importing-hosted-cluster[Manually importing a hosted control plane cluster].

* To access a hosted cluster, see xref:../hosted_control_planes/access_hosted_cluster.adoc#access-hosted-cluster[Accessing the hosted cluster].

* To add hosts to the host inventory by using the Discovery Image, see link:../cluster_lifecycle/cim_add_host.adoc[Adding hosts to the host inventory by using the Discovery Image].
