[#create-hosted-multi-zone-aws]
= Creating a hosted cluster in multiple zones on AWS

Before you create a hosted cluster on Amazon Web Services (AWS), you must create an AWS Identity and Access Management (IAM) role and AWS Security Token Service (STS) credentials. See xref:../../clusters/hosted_control_planes/create_role_sts_aws.adoc#create-role-sts-aws[Creating an AWS IAM role and STS credentials].

Create a hosted cluster in multiple zones on AWS by running the following command:

[source,bash]
----
hcp create cluster aws \
--name <hosted_cluster_name> \ <1>
--node-pool-replicas=<node_pool_replica_count> \ <2>
--base-domain <basedomain> \ <3>
--pull-secret <path_to_pull_secret> \ <4>
--role-arn <arn_role> \ <5>
--region <region> \ <6>
--zones <zones> <7>
--sts-creds <path_to_sts_credential_file> <8>
----

<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the node pool replica count, for example, `2`.
<3> Specify your base domain, for example, `example.com`.
<4> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<5> Specify the Amazon Resource Name (ARN), for example, `arn:aws:iam::820196288204:role/myrole`.
<6> Specify the AWS region name, for example, `us-east-1`.
<7> Specify availability zones within your AWS region, for example, `us-east-1a`, and `us-east-1b`.
<8> Specify the path to your AWS STS credentials file, for example, `/home/user/sts-creds/sts-creds.json`.

For each specified zone, the following infrastructure is created:

* Public subnet
* Private subnet
* NAT gateway
* Private route table (public route table is shared across public subnets)

One `NodePool` resource is created for each zone. The node pool name is suffixed by the zone name. The private subnet for zone is set in `spec.platform.aws.subnet.id`.

[#create-hosted-multi-zone-aws-credentials]
== Providing credentials for creating a hosted cluster on AWS

When you create a hosted cluster by using the `hcp create cluster aws` command, you need to provide AWS account credentials that have permissions to create infrastructure resources for your cluster. Examples of infrastructure resources include VPCs, subnets, and NAT gateways. You can provide the AWS credentials in two ways: by using the `--sts-creds` flag or by using the AWS cloud provider secret from {mce-short}.

[#create-hosted-multi-zone-aws-creds-flag]
=== Providing credentials by using the --sts-creds flag

You can use AWS STS credentials to create a hosted cluster by specifying the `--sts-creds` flag. Run the following command:

[source,bash]
----
hcp create cluster aws \
--name <hosted_cluster_name> \ <1>
--node-pool-replicas <node_pool_replica_count> \ <2>
--base-domain <basedomain> \ <3>
--pull-secret <path_to_pull_secret> \ <4>
--sts-creds <path_to_sts_credential_file> \ <5>
--region <region> <6>
--role-arn <arn_role> \ <7>
----

<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the node pool replica count, for example, `2`.
<3> Specify your base domain, for example, `example.com`.
<4> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<5> Specify the path to your AWS STS credentials file, for example, `/home/user/sts-creds/sts-creds.json`.
<6> Specify the AWS region name, for example, `us-east-1`.
<7> Specify the Amazon Resource Name (ARN), for example, `arn:aws:iam::820196288204:role/myrole`.

[#create-hosted-aws-additional-resources]
== Additional resources

For instructions to install the AWS Elastic File Service (EFS) CSI Driver Operator on a hosted cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/storage/using-container-storage-interface-csi#efs-sts_persistent-storage-csi-aws-efs[Configuring AWS EFS CSI Driver Operator with Security Token Service].
