[#hosted-deploy-cluster-aws]
= Deploying a hosted cluster on AWS

Before you deploy a hosted cluster on Amazon Web Services (AWS), you must perform the following actions:

* Set up the hosted control plane command line interface, `hcp`.
* Enable the `local-cluster` managed cluster as the hosting cluster.
* Create an AWS Identity and Access Management (IAM) role and AWS Security Token Service (STS) credentials. See xref:../../clusters/hosted_control_planes/create_role_sts_aws.adoc#create-role-sts-aws[Creating an AWS IAM role and STS credentials].

If you want to deploy a private hosted cluster, see _Deploying a private hosted cluster on AWS_.

To deploy a hosted cluster on AWS, complete the following steps:

. To create the hosted cluster, run the following command:

+
[source,bash]
----
hcp create cluster aws \
    --name <hosted_cluster_name> \ <1>
    --infra-id <infra_id> \ <2>
    --base-domain <basedomain> \ <3>
    --sts-creds <path_to_sts_credential_file> \ <4>
    --pull-secret <path_to_pull_secret> \ <5>
    --region <region> \ <6>
    --generate-ssh \
    --node-pool-replicas <node_pool_replica_count> \ <7>
    --namespace <hosted_cluster_namespace> \ <8>
    --role-arn <role_name> <9>
----

<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify your infrastructure name. You must provide the same value for `<hosted_cluster_name>` and `<infra_id>`. Otherwise the cluster might not appear correctly in the {mce} console.
<3> Specify your base domain, for example, `example.com`.
<4> Specify the path to your AWS STS credentials file, for example, `/home/user/sts-creds/sts-creds.json`.
<5> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<6> Specify the AWS region name, for example, `us-east-1`.
<7> Specify the node pool replica count, for example, `3`.
<8> By default, all `HostedCluster` and `NodePool` custom resources are created in the `clusters` namespace. You can use the `--namespace <namespace>` parameter, to create the `HostedCluster` and `NodePool` custom resources in a specific namespace.
<9> Specify the Amazon Resource Name (ARN), for example, `arn:aws:iam::820196288204:role/myrole`.

. Verify the status of your hosted cluster to check that the value of `AVAILABLE` is `True`. Run the following command:

+
[source,bash]
----
oc get hostedclusters -n <hosted_cluster_namespace>
----

. Get a list of your node pools by running the following command:

+
[source,bash]
----
oc get nodepools --namespace <hosted_cluster_namespace>
----
