[#hosted-deploy-cluster-aws]
= Deploying a hosted cluster on AWS

After you set up the hosted control plane command line interface, `hcp`, and enable the `local-cluster` as the hosting cluster, you can deploy a hosted cluster on AWS by completing the following steps. To deploy a private hosted cluster, see _Deploying a private hosted cluster on AWS_.

. To see descriptions for each variable, run the following command:

+
[source,bash]
----
hcp create cluster aws --help
----

. Verify that you are logged into your hub cluster.

. Run the following command to create the hosted cluster:

+
[source,bash]
----
hcp create cluster aws \
    --name <hosted_cluster_name> \ <1>
    --infra-id <infra_id> \ <2>
    --base-domain <basedomain> \ <3>
    --aws-creds <path_to_aws_creds> \ <4>
    --pull-secret <path_to_pull_secret> \ <5>
    --region <region> \ <6>
    --generate-ssh \
    --node-pool-replicas <node_pool_replica_count> \ <7>
    --namespace <hosted_cluster_namespace> <8>
----

<1> Specify the name of your hosted cluster, for instance, `example`. Verify that `<hosted_cluster_name>` and `<infra_id>` have the same values, otherwise the cluster might not appear correctly in the {mce} console.
<2> Specify the name for your infrastructure, for example, `clc-name-hs1`.
<3> Specify your base domain, for example, `dev09.red-chesterfield.com`.
<4> Specify the path to your AWS credentials file, for example, `/user/name/.aws/credentials`.
<5> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<6> Specify the AWS region name, for example, `us-east-1`.
<7> Specify the node pool replica count, for example, `2`.
<8> Specify your hosted cluster namespace, for example, `clusters`.

+
*Note:* By default, all `HostedCluster` and `NodePool` custom resources are created in the `clusters` namespace. If you specify the `--namespace <namespace>` parameter, `HostedCluster` and `NodePool` custom resources are created in the namespace you chose.

. You can check the status of your hosted cluster by running the following command:

+
[source,bash]
----
oc get hostedclusters -n <hosted_cluster_namespace>
----

. You can check your node pools by running the following command:

+
[source,bash]
----
oc get nodepools --namespace <hosted_cluster_namespace>
----
