[#destroy-hosted-control-planes]
= Destroying hosted clusters

Destroying hosted clusters does not disable the hosted control plane features. If you want to disable the feature, you must first destroy both the hosted cluster and the managed cluster resource on {mce}. Destroying only the hosted cluster, or only the managed cluster resource, might cause issues when you create the hosted cluster again, or if you are using the same managed cluster name. 

//* <<hypershift-cluster-destroy-aws,Destroying a hosted cluster on AWS>>
//* <<hypershift-cluster-destroy-bm,Destroying a hosted cluster on bare metal>>

[#hypershift-cluster-destroy]
== Destroying a hosted cluster

To destroy a hosted cluster and its managed cluster resource, complete the following steps:

. Delete the hosted cluster and its back-end resources by running the following command:
+
----
hypershift destroy cluster aws --name <cluster_name> --infra-id <infra_id> --aws-creds <aws-credentials> --base-domain <base_domain> --destroy-cloud-resources
----
+
Replace names where necessary.

. Delete the managed cluster resource on {mce} by running the following command:
+
----
oc delete managedcluster <cluster_name>
----
+
Replace `cluster_name` with the name of your cluster.

//[#hypershift-cluster-destroy-bm]
//== Destroying a hosted cluster on bare metal
