[#disable-hosted-control-planes]
= Disabling the hosted control plane feature

When disabling the hosted control plane cluster feature, you must destroy the hosted cluster and the managed cluster resource on {mce-short}. See xref:../hosted_control_planes/delete_hosted.adoc#destroy-hosted-control-planes[Destroying hosted control plane clusters] for more information.

[#hypershift-uninstall-operator]
== Uninstalling the HyperShift operator

To uninstall the HyperShift Operator and disable the `hypershift-addon` from the `local-cluster`, complete the following steps:

. Run the following command to ensure that there is no hosted cluster running:
+
----
oc get hostedcluster -A
----
+
*Important:* If a hosted cluster is running, the HyperShift Operator does not uninstall, even if the `hypershift-addon` is disabled.

. Disable the `hypershift-addon` by running the following command:
+
----
oc patch mce multiclusterengine --type=merge -p '{"spec":{"overrides":{"components":[{"name":"hypershift-local-hosting","enabled": false}]}}}'
----
+
*Tip:* You can also disable the hosted control plane feature from the {mce-short} console after disabling the `hypershift-addon`.
