[#dual-stack-finish-deployment]
= Finishing the hosted cluster deployment for a dual stack network

You can monitor the deployment of a hosted cluster from two perspectives: the control plane and the data plane.

[#dual-stack-monitor-hosted-cp]
== Monitoring the hosted cluster deployment by using the control plane

You can use the control plane to monitor the hosted cluster deployment.

. Export the hosted cluster `kubeconfig` file by entering the following command:

+
----
export KUBECONFIG=<path_to_hosted_cluster_kubeconfig>
----

. Observe the hosted cluster deployment progress by entering the following command:

+
----
watch "oc get pod -n hypershift;echo;echo;oc get pod -n <hosted_control_plane_namespace>;echo;echo;oc get bmh -A;echo;echo;oc get agent -A;echo;echo;oc get infraenv -A;echo;echo;oc get hostedcluster -A;echo;echo;oc get nodepool -A;echo;echo;"
----

This command provides information about the following artifacts:

* The HyperShift Operator
* The `HostedControlPlane` pod
* The bare metal hosts
* The agents
* The `InfraEnv` resource
* The `HostedCluster` and `NodePool` resources

[#dual-stack-monitor-hosted-dp]
== Monitoring the hosted cluster deployment by using the data plane

You can use the data plane to monitor how the Operators are progressing during the hosted cluster deployment process.

. Create a `kubeconfig` file for the hosted cluster by entering the following command:

+
----
hcp create kubeconfig --name <hosted_cluster_name> --namespace <hosted_cluster_namespace>
----

. Export the hosted cluster `kubeconfig` file by entering the following command:

+
----
export KUBECONFIG=<path_to_hosted_cluster_kubeconfig>
----

. Observe the status of the cluster version, nodes, and cluster Operators by entering the following command:

+
----
watch "oc get clusterversion,nodes,co"
----
