[#hosted-cluster-arm-aws]
= Enabling hosted clusters to run on different architectures (Technology Preview)

By default for hosted control planes on AWS, you use an AMD64 hosted cluster. However, you can enable hosted control planes to run on an ARM64 hosted cluster. 

You can also create node pools of different architecture types for the same hosted cluster. See the following table for compatible combinations of node pools and hosted clusters:

|===
| Hosted cluster | Node pool
| AMD64 | AMD64 or ARM64
| ARM64 | ARM64 or AMD64

|===

[#prerequisites-hosted-arm]
== Prerequisites

* You must have an {ocp-short} cluster with a 64-bit ARM infrastructure that is installed on Amazon Web Serivces (AWS). For more information, see link:https://console.redhat.com/openshift/install/aws/arm[Create an OpenShift Cluster: AWS (ARM)].
* You must create an AWS Identity and Access Management (IAM) role and AWS Security Token Service (STS) credentials. See xref:../../clusters/hosted_control_planes/create_role_sts_aws.adoc#create-role-sts-aws[Creating an AWS IAM role and STS credentials].

[#hosted-cluster-arm64]
== Running a hosted cluster on an ARM64 {ocp-short} cluster

You can run a hosted cluster on an ARM64 {ocp-short} cluster by overriding the default release image with a multi-architecture release image. Complete the following steps:

. Create a hosted cluster by running the following command:

+
[source,bash]
----
hcp create cluster aws \
--name <hosted_cluster_name> \ <1>
--node-pool-replicas <node_pool_replica_count> \ <2>
--base-domain <basedomain> \ <3>
--pull-secret <path_to_pull_secret> \ <4>
--sts-creds <path_to_sts_credential_file> \ <5>
--region <region> \ <6>
--release-image quay.io/openshift-release-dev/ocp-release:<ocp_release_image> \ <7>
--role-arn <role_name> \ <8>
--multi-arch <9>
----

+
<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the node pool replica count, for example, `3`.
<3> Specify your base domain, for example, `example.com`.
<4> Specify the path to your pull secret, for example, `/user/name/pullsecret`.
<5> Specify the path to your AWS STS credentials file, for example, `/home/user/sts-creds/sts-creds.json`.
<6> Specify the AWS region name, for example, `us-east-1`.
<7> Specify the supported {ocp-short} version that you want to use, for example, `4.14.0-x86_64`. If you are using a disconnected environment, replace `<ocp_release_image>` with the digest image. To extract the {ocp-short} release image digest, see _Extracting the {ocp-short} release image digest_.
<8> Specify the Amazon Resource Name (ARN), for example, `arn:aws:iam::820196288204:role/myrole`.
<9> The `multi-arch` flag indicates that the hosted cluster supports both `amd64` and `arm64` node pools. When you set the flag and supply a release image, the release image must be a multi-architecture release image. When you set the flag and supply a release stream, the release stream must be a multi-architecture release stream. If you do not set the `multi-arch` flag, the CLI automatically sets the flag to `true` and generates a log message. A node pool supports only one CPU architecture within the same node pool.

. Add a `NodePool` object to the hosted cluster by running the following command:

+
[source,bash]
----
hcp create nodepool aws \
--cluster-name <hosted_cluster_name> \ <1>
--name <nodepool_name> \ <2>
--node-count <node_pool_replica_count> <3>
----

+
<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the node pool name.
<3> Specify the node pool replica count, for example, `3`.


[#hosted-cluster-arm-node-pools]
== Creating ARM NodePool objects on AWS hosted clusters

You can schedule application workloads (`NodePool` objects) on 64-bit ARM and AMD64 from the same hosted control plane. You can define the `arch` field in the `NodePool` specification to set the required processor architecture for the `NodePool` object. The valid values for the `arch` field are as follows:

* `arm64`
* `amd64`

If you do not specify a value for the `arch` field, the `amd64` value is used by default.

[#hc-arm-nodepools-prereqs]
=== Prerequisites

You must have a multi-architecture image for the `HostedCluster` custom resource to use. You can access multi-architecture nightly images at https://multi.ocp.releases.ci.openshift.org/.

[#hc-arm-nodepools-aws]
=== Creating an ARM or AMD NodePool object on an AWS hosted cluster

To create an ARM or AMD `NodePool` object on a hosted cluster on AWS, complete the following steps:

. Add a `NodePool` object to the hosted cluster by running the following command:

+
[source,bash]
----
hcp create nodepool aws \
--cluster-name <hosted_cluster_name> \ <1>
--name <node_pool_name> \ <2>
--node-count <node_pool_replica_count> <3>
--arch <architecture> <4>
----

+
<1> Specify the name of your hosted cluster, for instance, `example`.
<2> Specify the node pool name.
<3> Specify the node pool replica count, for example, `3`.
<4> Specify the architecture type, such as `arm64` or `amd64`.