[#hosted-enable-private-link]
= Enabling AWS PrivateLink

If you plan to provision hosted control plane clusters on the AWS platform with PrivateLink, complete the following steps:

. Create an AWS credential secret for the HyperShift Operator and name it `hypershift-operator-private-link-credentials`. The secret must reside in the managed cluster namespace that is the namespace of the managed cluster being used as the hosting cluster. If you used `local-cluster`, create the secret in the `local-cluster` namespace.

. See the following table to confirm that the secret contains the required fields:

+
|===
| Field name | Description | Optional or required
| `region`
| Region for use with Private Link
| Required

| `aws-access-key-id`
| The credential access key id.
| Required

| `aws-secret-access-key`
| The credential access key secret.
| Required
|===

+
The following example shows the sample `hypershift-operator-private-link-credentials` secret template:

+
----
oc create secret generic hypershift-operator-private-link-credentials --from-literal=aws-access-key-id=<aws-access-key-id> --from-literal=aws-secret-access-key=<aws-secret-access-key> --from-literal=region=<region> -n local-cluster
----

+
*Note:* Disaster recovery backup for the secret is not automatically enabled. Run the following command to add the label that enables the `hypershift-operator-private-link-credentials` secret to be backed up for disaster recovery:

+
----
oc label secret hypershift-operator-private-link-credentials -n local-cluster cluster.open-cluster-management.io/backup=""
----