[#enable-or-disable-hosted-control-planes]
= Enabling or disabling the hosted control plane feature

The hosted control planes feature, as well as the `hypershift-addon` managed cluster add-on, are enabled by default. If you want to disable the feature, or if you disabled it and want to manually enable it, see the following procedures:

* <<hosted-enable-feature,Manually enabling the hosted control planes feature>>
* <<disable-hosted-control-planes,Disabling the hosted control planes feature>>

[#hosted-enable-feature]
== Manually enabling the hosted control planes feature

. You can run the following command to enable the feature:

+
[source,bash]
----
oc patch mce multiclusterengine --type=merge -p '{"spec":{"overrides":{"components":[{"name":"hypershift","enabled": true}]}}}' <1>
----

<1> The default `MultiClusterEngine` resource instance name is `multiclusterengine`. You can get the `MultiClusterEngine` name from your cluster by running the `$ oc get mce` command.

. Run the following command to verify that the `hypershift` and `hypershift-local-hosting` features are enabled in the `MultiClusterEngine` custom resource:

+
[source,bash]
----
oc get mce multiclusterengine -o yaml
----

+
The output resembles the following example:

+
[source,yaml]
----
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  overrides:
    components:
    - name: hypershift
      enabled: true
    - name: hypershift-local-hosting
      enabled: true
----

[#hosted-enable-hypershift-add-on-aws]
=== Manually enabling the hypershift-addon managed cluster add-on for local-cluster

To enable the `hypershift-addon` managed cluster add-on manually for `local-cluster`, complete the following steps:

. Create `hypershift-addon` by creating a YAML file that resembles the following configuration:
+
[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: hypershift-addon
  namespace: local-cluster
spec:
  installNamespace: open-cluster-management-agent-addon
----

. Apply the YAML file by running the following command:
+
----
oc apply -f <filename>.yaml
----
+
Replace `<filename>.yaml` with the name of the file that you created.

. Confirm that `hypershift-addon` is installed by running the following command:
+
----
oc get managedclusteraddons -n local-cluster hypershift-addon
----
+
See the following example output:
+
----
NAME               AVAILABLE   DEGRADED   PROGRESSING
hypershift-addon   True
----

After installing `hypershift-addon`, the hosting cluster is available to create and manage hosted clusters.

[#disable-hosted-control-planes]
== Disabling the hosted control planes feature

After disabling the hosted control planes feature and uninstalling the HyperShift Operator, you must destroy the hosted cluster and the managed cluster resource on {mce-short}. For more information, see the _Managing hosted control plane clusters_ topic.

[#hypershift-uninstall-operator]
=== Uninstalling the HyperShift Operator

To uninstall the HyperShift Operator and disable the `hypershift-addon` from the `local-cluster`, complete the following steps:

. Run the following command to ensure that there is no hosted cluster running:
+
----
oc get hostedcluster -A
----
+
*Important:* If a hosted cluster is running, the HyperShift Operator does not uninstall, even if `hypershift-addon` is disabled.

. Disable `hypershift-addon` by running the following command:
+
----
oc patch mce multiclusterengine --type=merge -p '{"spec":{"overrides":{"components":[{"name":"hypershift-local-hosting","enabled": false}]}}}' <1>
----
+
<1> The default `MultiClusterEngine` resource instance name is `multiclusterengine`. You can get the `MultiClusterEngine` name from your cluster by running the `$ oc get mce` command.
+
*Note:* You can also disable `hypershift-addon` for `local-cluster` from the {mce-short} console after disabling `hypershift-addon`.

[#hosted-disable-feature]
=== Disabling the hosted control planes feature

You must first uninstall the HyperShift Operator before disabling the hosted control planes feature.

. Run the following command to disable the hosted control planes feature:

+
[source,bash]
----
oc patch mce multiclusterengine --type=merge -p '{"spec":{"overrides":{"components":[{"name":"hypershift","enabled": false}]}}}' <1>
----

<1> The default `MultiClusterEngine` resource instance name is `multiclusterengine`. You can get the `MultiClusterEngine` name from your cluster by running the `$ oc get mce` command.

. Run the following command to verify that the `hypershift` and `hypershift-local-hosting` features are disabled in the `MultiClusterEngine` custom resource:

+
[source,bash]
----
oc get mce multiclusterengine -o yaml 
----

See the following example where `hypershift` and `hypershift-local-hosting` have their `enabled:` flags set to `false`:
[source,yaml]
----
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  overrides:
    components:
    - name: hypershift
      enabled: false
    - name: hypershift-local-hosting
      enabled: false
----

[#additional-resources-disable]
== Additional resources

* xref:../hosted_control_planes/aws_intro.adoc#hosting-service-cluster-configure-aws[Configuring hosted control plane clusters on AWS (Technology Preview)]
* xref:../hosted_control_planes/bm_intro.adoc#configuring-hosting-service-cluster-configure-bm[Configuring hosted control plane clusters on bare metal]
