[#hosted-enable-ext-dns-aws]
= Enabling external DNS

The control plane and the data plane are separate in hosted control planes. You can configure DNS in two independent areas:

- Ingress for workloads within the hosted cluster, such as the following domain: `*.apps.service-consumer-domain.com`

- Ingress for service endpoints within the management cluster, such as API or OAUTH endpoints through the service provider domain: `*.service-provider-domain.com`

The input for the `hostedCluster.spec.dns` manages the ingress for workloads within the hosted cluster. The input for `hostedCluster.spec.services.servicePublishingStrategy.route.hostname` manages the ingress for service endpoints within the management cluster.

External DNS creates name records for hosted cluster `Services` that specify a publishing type of `LoadBalancer` or `Route` and provide a hostname for that publishing type. For hosted clusters with `Private` or `PublicAndPrivate` endpoint access types, only the `APIServer` and `OAuth` services support hostnames. For `Private` hosted clusters, the DNS record resolves to a private IP address of a Virtual Private Cloud (VPC) endpoint in your VPC.

A hosted control plane exposes the following services:

* `APIServer`
* `OAuthServer`
* `Konnectivity`
* `Ignition`
* `OVNSbDb`
* `OIDC`

You can expose these services by using the `servicePublishingStrategy` field in the `HostedCluster` specification. By default, for the `LoadBalancer` and `Route` types of `servicePublishingStrategy`, you can publish the service in one of the following ways:

* By using the hostname of the load balancer that is in the status of the `Service` with the `LoadBalancer` type
* By using the `status.host` field of the `Route` resource

However, when you deploy hosted control planes in a managed service context, those methods can expose the ingress subdomain of the underlying management cluster and limit options for the management cluster lifecycle and disaster recovery.

When a DNS indirection is layered on the `LoadBalancer` and `Route` publishing types, a managed service operator can publish all public hosted cluster services by using a service-level domain. This architecture allows remapping on the DNS name to a new `LoadBalancer` or `Route` and does not expose the ingress domain of the management cluster. Hosted control planes uses external DNS to achieve that indirection layer.

You can deploy `external-dns` alongside the HyperShift Operator in the `hypershift` namespace of the management cluster. External DNS watches for `Services` or `Routes` that have the `external-dns.alpha.kubernetes.io/hostname` annotation. That annotation is used to create a DNS record that points to the `Service`, such as a record, or the `Route`, such as a CNAME record.

You can use external DNS on cloud environments only. For the other environments, you need to manually configure DNS and services.

For more information about external DNS, see link:https://github.com/kubernetes-sigs/external-dns[external DNS].

[#external-dns-prereqs-aws]
== Prerequisites

Before you can set up external DNS for hosted control planes, you must meet the following prerequisites:

* You created an external public domain

* You have access to the AWS Route53 Management console

[#set-up-external-dns-aws]
== Setting up external DNS for hosted control planes

To provision hosted control plane clusters with service-level DNS (external DNS), complete the following steps:

. Create an AWS credential secret for the HyperShift Operator and name it `hypershift-operator-external-dns-credentials` in the `local-cluster` namespace.

. See the following table to verify that the secret has the required fields:

+
|===
| Field name | Description | Optional or required

| `provider`
| The DNS provider that manages the service-level DNS zone.
| Required

| `domain-filter`
| The service-level domain.
| Required

| `credentials`
| The credential file that supports all external DNS types.
| Optional when you use AWS keys

| `aws-access-key-id`
| The credential access key id.
| Optional when you use the AWS DNS service

| `aws-secret-access-key`
| The credential access key secret.
| Optional when you use the AWS DNS service
|===

+
The following example shows the sample `hypershift-operator-external-dns-credentials` secret template:

+
[source,bash]
----
oc create secret generic hypershift-operator-external-dns-credentials --from-literal=provider=aws --from-literal=domain-filter=<domain_name> --from-file=credentials=<path_to_aws_credentials_file> -n local-cluster
----

+
*Note:* Disaster recovery backup for the secret is not automatically enabled. To back up the secret for disaster recovery, add the `hypershift-operator-external-dns-credentials` by entering the following command:

+
[source,bash]
----
oc label secret hypershift-operator-external-dns-credentials -n local-cluster cluster.open-cluster-management.io/backup=""
----

[#create-public-dns-hosted-zone-aws]
== Creating the public DNS hosted zone

The External DNS Operator uses the public DNS hosted zone to create your public hosted cluster.

You can create the public DNS hosted zone to use as the external DNS domain-filter. Complete the following steps in the AWS Route 53 management console:

. In the Route 53 management console, click *Create hosted zone*.

. On the *Hosted zone configuration* page, type a domain name, verify that *Publish hosted zone* is selected as the type, and click *Create hosted zone*.

. After the zone is created, on the *Records* tab, note the values in the *Value/Route traffic to* column.

. In the main domain, create an NS record to redirect the DNS requests to the delegated zone. In the *Value* field, enter the values that you noted in the previous step.

. Click *Create records*.

. Verify that the DNS hosted zone is working by creating a test entry in the new subzone and testing it with a `dig` command like the following example:

+
----
dig +short test.user-dest-public.aws.kerberos.com
192.168.1.1
----

. To create a hosted cluster that sets the hostname for `LoadBalancer` and `Route` services, enter the following command:

+
----
hcp create cluster aws --name=<hosted_cluster_name> --endpoint-access=PublicAndPrivate --external-dns-domain=<public_hosted_zone> ...
----
+
Replace `<public_hosted_zone>` with the public hosted zone that you created.

This example shows the resulting `services` block for the hosted cluster:

+
[source,yaml]
----
  platform:
    aws:
      endpointAccess: PublicAndPrivate
...
  services:
  - service: APIServer
    servicePublishingStrategy:
      route:
        hostname: api-example.service-provider-domain.com
      type: Route
  - service: OAuthServer
    servicePublishingStrategy:
      route:
        hostname: oauth-example.service-provider-domain.com
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
----

The Control Plane Operator creates the `Services` and `Routes` resources and annotates them with the `external-dns.alpha.kubernetes.io/hostname` annotation. For `Services` and `Routes`, the Control Plane Operator uses a value of the `hostname` parameter in the `servicePublishingStrategy` field for the service endpoints. To create the DNS records, you can use a mechanism, such as the `external-dns` deployment.

You can configure service-level DNS indirection for public services only. You cannot set `hostname` for private services because they use the `hypershift.local` private zone.

The following table notes when it is valid to set `hostname` for a service and endpoint combination:

|===
|Service |Public |PublicAndPrivate |Private

|`APIServer`
|Y
|Y
|N

|`OAuthServer`
|Y
|Y
|N

|`Konnectivity`
|Y
|N
|N

|`Ignition`
|Y
|N
|N
|===

[#deploy-cluster-cli-external-dns-aws]
== Deploying a cluster by using the command line interface and external DNS

To create a hosted cluster by using the `PublicAndPrivate` or `Public` publishing strategy, you must have the following artifacts configured in your management cluster:

* The public DNS hosted zone
* The External DNS Operator
* The HyperShift Operator

To deploy a hosted cluster by using the command line interface, complete the following steps:

. To access your management cluster, enter the following command:

+
[source,bash]
----
export KUBECONFIG=<path_to_management_cluster_kubeconfig>
----

. Verify that the External DNS Operator is running by entering the following command:

+
[source,bash]
----
oc get pod -n hypershift -lapp=external-dns
----

+
See the following example output:

+
----
NAME                            READY   STATUS    RESTARTS   AGE
external-dns-7c89788c69-rn8gp   1/1     Running   0          40s
----

. To create a hosted cluster by using external DNS, enter the following command:

+
[source,bash]
----
hypershift create cluster aws \
    --aws-creds <path_to_aws_credentials_file> \ <1>
    --instance-type <instance_type> \ <2>
    --region <region> \ <3>
    --auto-repair \
    --generate-ssh \
    --name <hosted_cluster_name> \ <4>
    --namespace clusters \
    --base-domain <service_consumer_domain> \ <5>
    --node-pool-replicas <node_replica_count> \ <6>
    --pull-secret <path_to_your_pull_secret> \ <7>
    --release-image quay.io/openshift-release-dev/ocp-release:<ocp_release_image> \ <8>
    --external-dns-domain=<service_provider_domain> \ <9>
    --endpoint-access=PublicAndPrivate <10>
----

+
<1> Specify the path to your AWS credentials file, for example, `/user/name/.aws/credentials`.
<2> Specify the instance type, for example, `m6i.xlarge`.
<3> Specify the AWS region, for example, `us-east-1`.
<4> Specify your hosted cluster name, for example, `my-external-aws`.
<5> Specify the public hosted zone that the service consumer owns, for example, `service-consumer-domain.com`.
<6> Specify the node replica count, for example, `2`.
<7> Specify the path to your pull secret file.
<8> Specify the supported {ocp-short} version that you want to use, for example, `4.14.0-x86_64`.
<9> Specify the public hosted zone that the service provider owns, for example, `service-provider-domain.com`.
<10> Set as `PublicAndPrivate`. You can use external DNS with `Public` or `PublicAndPrivate` configurations only.
