[#hosted-control-planes-create-infraenv]
= Creating an _InfraEnv_ resource for hosted control planes on bare metal

An `InfraEnv` is a environment where hosts that are starting the live ISO can join as agents. In this case, the agents are created in the same namespace as your hosted control plane.

. Create an `InfraEnv` resource:

.. Create a YAML file to contain the configuration:

+
[source,yaml]
----
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: ${HOSTED_CLUSTER_NAME}
  namespace: ${HOSTED_CONTROL_PLANE_NAMESPACE} <1>
spec:
  pullSecretRef:
    name: pull-secret
  sshAuthorizedKey: ${SSH_PUB_KEY}
----

+
<1> The namespace for hosted control plane pods.

.. Save the file as `infraenv-config.yaml`.

.. Apply the configuration by entering the following command:

+
----
oc apply -f infraenv-config.yaml
----

. To fetch the URL to download the live ISO that allows virtual machines or bare metal machines to join as agents, enter the following command:

+
----
oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get InfraEnv ${HOSTED_CLUSTER_NAME} -ojsonpath="{.status.isoDownloadURL}"
----

where `{$HOSTED_CONTROL_PLANE_NAMESPACE}` is the namespace for hosted control plane pods.

[#hosted-bare-metal-infraenv-console]
== Creating an _InfraEnv_ resource by using the console

To create an `InfraEnv` resource by using the web console, you create and configure a host inventory (infrastructure environment). Complete the following steps:

. In the console, click **Infrastructure > Host inventory**, and then click **Create infrastructure environment**.

. After you create the infrastructure environment, you can add bare metal hosts. From the **InfraEnv** view, click **Add hosts**. From the menu that is displayed, click **With BMC form**, and follow the prompts in the console.

. Download the ISO by clicking **Add hosts**. From the menu that is displayed, click **With Discovery ISO**, and follow the prompts in the console.