[#hosted-cluster-arm-aws]
= Enabling hosted control planes on an ARM64 {ocp-short} cluster

You can enable an ARM64-hosted control plane to operate with an {ocp-short} ARM64 data plane in a management cluster environment. This feature is available for hosted control planes on AWS only.

[#prerequisites-hosted-arm]
== Prerequisites

You must have an {ocp-short} cluster that was installed on a 64-bit ARM infrastructure. For more information, see link:https://console.redhat.com/openshift/install/aws/arm[Create an OpenShift Cluster: AWS (ARM)].

[#hosted-cluster-arm64]
== Running a hosted cluster on an ARM64 {ocp-short} cluster

To run a hosted cluster on an ARM64 {ocp-short} cluster, complete the following steps:

. Create a hosted cluster that overrides the default release image with a multi-architecture release image. 

+
For example, through the hosted control planes (`hcp`) command line interface, enter the following commands, and replace the cluster name, node pool replicas, base domain, pull secret, AWS credentials, and region with your information:

+
----
hcp create cluster aws \ 
--name $CLUSTER_NAME \
--node-pool-replicas=$NODEPOOL_REPLICAS \
--base-domain $BASE_DOMAIN \
--pull-secret $PULL_SECRET \
--aws-creds $AWS_CREDS \
--region $REGION \
--release-image quay.io/openshift-release-dev/ocp-release:4.13.0-rc.0-multi
----

+
This example adds a default `NodePool` object through the `--node-pool-replicas` flag.

. Add a 64-bit x_86 `NodePool` object to the hosted cluster.

+
For example, through the hosted control planes (`hcp`) command line interface, enter the following commands, being careful to replace the cluster name, node pool name, and node pool replicas with your information:

+
----
hcp create nodepool aws \
--cluster-name $CLUSTER_NAME \
--name $NODEPOOL_NAME \
--node-count=$NODEPOOL_REPLICAS
----