[#hosted-cluster-workload-distributing]
= Distributing hosted cluster workloads

Before you get started with hosted control planes for {ocp-short}, you must properly label nodes so that the pods of hosted clusters can be scheduled into infrastructure nodes. Node labeling is also important for the following reasons:

* To ensure high availability and proper workload deployment
* To ensure that control planes are well contained

[#hosted-cluster-labels-taints-overview]
== Labels and taints for management cluster nodes

//lahinson - sept. 2023 - do we need to add a note to prevent customers from using the management cluster for their workload?

As a management cluster administrator, you can use the following labels and taints in the management cluster nodes to schedule the control plane workload:

//lahinson - sept. 2023 - If we want to explain the implications of each label and taint, I'll need that info.

* `hypershift.openshift.io/hypershift.openshift.io/control-plane: true`
* `node-role.kubernetes.io/infra`
* `topology.kubernetes.io/zone`
* `hypershift.openshift.io/cluster: ${HostedControlPlane Namespace}`

Pods for a hosted cluster have tolerations, and the scheduler uses affinity rules to schedule them. Pods tolerate taints for `control-plane` and the `cluster` for the pods. The scheduler prioritizes the scheduling of pods into nodes that are labeled with `hypershift.openshift.io/control-plane` and `hypershift.openshift.io/cluster: ${HostedControlPlane Namespace}`.

For the `ControllerAvailabilityPolicy` option, use `HighlyAvailable`. When you use that option, you can schedule pods for each deployment within a hosted cluster across different failure domains by setting `topology.kubernetes.io/zone` as the topology key.

//lahinson - sept. 2023 - If we want to explain zone versus hostname, I'll need info for that.

*Important:* Proper node labeling, which is detailed in the following procedure, is a prerequisite to deploying hosted control planes.

[#hosted-cluster-schedule-pods-infra-nodes]
== Labeling nodes for hosted clusters

To enable a hosted cluster to require its pods to be scheduled into infrastructure nodes, set `HostedCluster.spec.nodeSelector`, as shown in the following example:

[source,yaml]
----
  spec:
    nodeSelector:
      role.kubernetes.io/infra: ""
----

This way, hosted control planes for each tenant are eligible infrastructure node workloads, and you do not need to entitle the underlying {ocp-short} nodes.

//lahinson - sept. 2023 - in the line above, should we replace "tenant" with something else? Maybe "hosted cluster"?

[#hosted-cluster-workload-distributing-priority]
== Priority classes

Four built-in priority classes influence the priority and preemption of the hosted cluster pods. You can create the pods in the management cluster in the following order from highest to lowest:

* `hypershift-operator`: HyperShift Operator pods.
* `hypershift-etcd`: Pods for etcd.
* `hypershift-api-critical`: Pods that are required for API calls and resource admission to succeed. These pods include pods such as `kube-apiserver`, aggregated API servers, and web hooks.
* `hypershift-control-plane`: Pods in the control plane that are not API-critical but still need elevated priority, such as the cluster version Operator.

[#hosted-cluster-workload-distributing-additional-resources]
== Additional resources

For more information about hosted control planes, see the following topics:

* xref:../hosted_control_planes/configure_hosted_bm.adoc#configuring-hosting-service-cluster-configure-bm[Configuring the hosting cluster on bare metal]
* xref:../hosted_control_planes/managing_hosted_bm.adoc#hosted-control-planes-manage-bm[Managing hosted control plane clusters on bare metal]
* xref:../hosted_control_planes/managing_hosted_kubevirt.adoc#hosted-control-planes-manage-kubevirt[Managing hosted control plane clusters on OpenShift Virtualization]
* xref:../hosted_control_planes/configure_hosted_aws.adoc#hosting-service-cluster-configure-aws[Configuring the hosting cluster on AWS (Technology Preview)]
* xref:../hosted_control_planes/managing_hosted_aws.adoc#hosted-control-planes-manage-aws[Managing hosted control planes on AWS (Technology Preview)]