[#hosted-bare-metal-adding-agents-ibmpower]
= Adding agents to the InfraEnv resource

You can add agents by manually configuring the machine to start with the live ISO.

. Download the live ISO and use it to start a host (bare metal or VM). The URL for the live ISO can be found in the `InfraEnv` resource, in the `status.isoDownloadURL` field. At startup, the host communicates with the Assisted Service and registers as an agent in the same namespace as the `InfraEnv` resource.

. To list the agents and some of their properties, enter the following command:

+
----
oc -n <hosted-control-plane-namespace> get agents
----

+
See the following example output:

+
----
NAME                                   CLUSTER   APPROVED   ROLE          STAGE
86f7ac75-4fc4-4b36-8130-40fa12602218                        auto-assign
e57a637f-745b-496e-971d-1abbf03341ba                        auto-assign
----

. After each agent is created, you can optionally set its `installation_disk_id` and `hostname` in the specification and approve the agent by entering the following commands: 

+
----
oc -n <hosted-control-plane-namespace> patch agent 86f7ac75-4fc4-4b36-8130-40fa12602218 -p '{"spec":{"installation_disk_id":"/dev/sda","approved":true,"hostname":"worker-0.example.krnl.es"}}' --type merge

oc -n <hosted-control-plane-namespace> patch agent 23d0c614-2caa-43f5-b7d3-0b3564688baa -p '{"spec":{"installation_disk_id":"/dev/sda","approved":true,"hostname":"worker-1.example.krnl.es"}}' --type merge
----

. To verify that the agents are approved for use, enter the following command and check the output:

+
----
oc -n <hosted-control-plane-namespace> get agents
----

+
See the following example output:

+
----
NAME                                   CLUSTER   APPROVED   ROLE          STAGE
86f7ac75-4fc4-4b36-8130-40fa12602218             true       auto-assign
e57a637f-745b-496e-971d-1abbf03341ba             true       auto-assign
----