[#importing-hosted-cluster]
= Manually importing a hosted control plane cluster

Hosted clusters are automatically imported into {mce-short} after the hosted control plane becomes available. If you want to import hosted clusters manually, complete the following steps:

. In the console, click *Infrastructure* > *Clusters* and select the hosted cluster that you want to import.

. Click *Import hosted cluster*.

+
*Note:* For your _discovered_ hosted cluster, you can also import from the console, but the cluster must be in an upgradable state. Import on your cluster is disabled if the hosted cluster is not in an upgradable state because the hosted control plane is not available. Click *Import* to begin the process. The status is `Importing` while the cluster receives updates and then changes to `Ready`.

[#manual-import-hosted-cluster-aws]
== Manually importing a hosted control plane cluster on AWS

You can also import a hosted control plane cluster on AWS with the command line interface by completing the following steps:

. Create your `ManagedCluster` resource by using the following sample YAML file:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:  
  annotations:    
    import.open-cluster-management.io/hosting-cluster-name: local-cluster    
    import.open-cluster-management.io/klusterlet-deploy-mode: Hosted
    open-cluster-management/created-via: hypershift  
  labels:    
    cloud: auto-detect    
    cluster.open-cluster-management.io/clusterset: default    
    name: <cluster_name>  
    vendor: OpenShift  
  name: <cluster_name>
spec:  
  hubAcceptsClient: true  
  leaseDurationSeconds: 60
----

+
Replace `<cluster_name>` with the name of your hosted cluster.

. Run the following command to apply the resource:

+
----
oc apply -f <file_name>
----

+
Replace <file_name> with the YAML file name you created in the previous step.

. Create your `KlusterletAddonConfig` resource by using the following sample YAML file. This only applies to {product-title-short}. If you have installed {mce-short} only, skip this step:

+
[source,yaml]
----
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: <cluster_name>
  namespace: <cluster_name>
spec:
  clusterName: <cluster_name>
  clusterNamespace: <cluster_name>
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: false
----

+
Replace `<cluster_name>` with the name of your hosted cluster.

. Run the following command to apply the resource:

+
----
oc apply -f <file_name>
----

+
Replace <file_name> with the YAML file name you created in the previous step.

. After the import process is complete, your hosted cluster becomes visible in the console. You can also check the status of your hosted cluster by running the following command:

+
----
oc get managedcluster <cluster_name>
----

[#importing-hosted-cluster-additional-resources]
== Additional resources

* For instructions to disable the automatic import of hosted clusters, see xref:../hosted_control_planes/disable_auto_import.adoc#hosted-disable-auto-import[Disabling the automatic import of hosted clusters into {mce-short}].