[#ipv6-mgmt-cluster]
= Setting up the management cluster for an IPv6 network

To set up an {ocp-short} management cluster, you can use dev-scripts, or if you are based on virtual machines, you can use the `kcli` tool. The following instructions are specific to the `kcli` tool.

. Ensure that the right networks are prepared for use in the hypervisor. The networks will host both the management and hosted clusters. Enter the following `kcli` command:

+
----
kcli create network -c 2620:52:0:1305::0/64 -P dhcp=false -P dns=false --domain dns.base.domain.name --nodhcp ipv6
----

+
where:

* `-c` specifies the CIDR for the network.
* `-P dhcp=false` configures the network to disable the DHCP, which is handled by the `dnsmasq` that you configured.
* `-P dns=false` configures the network to disable the DNS, which is also handled by the `dnsmasq` that you configured.
* `--domain` sets the domain to search.
* `dns.base.domain.name` is the DNS base domain name.
* `ipv6` is the name of the network that you are creating.

. After the network is created, review the following output:

+
----
[root@hypershiftbm ~]# kcli list network
Listing Networks...
+---------+--------+---------------------+-------+------------------+------+
| Network |  Type  |         Cidr        |  Dhcp |      Domain      | Mode |
+---------+--------+---------------------+-------+------------------+------+
| default | routed |   192.168.122.0/24  |  True |     default      | nat  |
| ipv4    | routed |   192.168.125.0/24  | False | dns.base.domain.name | nat  |
| ipv4    | routed | 2620:52:0:1305::/64 | False | dns.base.domain.name | nat  |
+---------+--------+---------------------+-------+------------------+------+
----

+
----
[root@hypershiftbm ~]# kcli info network ipv6
Providing information about network ipv6...
cidr: 2620:52:0:1305::/64
dhcp: false
domain: dns.base.domain.name
mode: nat
plan: kvirt
type: routed
----

. Ensure that the pull secret and `kcli` plan files are in place so that you can deploy the {ocp-short} management cluster:

.. Confirm that the pull secret is in the same folder as the `kcli` plan, and that the pull secret file is named `openshift_pull.json`.

.. Add the `kcli` plan, which contains the {ocp-short} definition, in the `mgmt-compact-hub-ipv6.yaml` file. Ensure that you update the file contents to match your environment:

+
[source,yaml]
----
plan: hub-ipv6
force: true
version: nightly
tag: "4.14.0-0.nightly-2023-08-29-102237"
cluster: "hub-ipv6"
ipv6: true
domain: dns.base.domain.name
api_ip: 2620:52:0:1305::2
ingress_ip: 2620:52:0:1305::3
disconnected_url: registry.dns.base.domain.name:5000
disconnected_update: true
disconnected_user: dummy
disconnected_password: dummy
disconnected_operators_version: v4.14
disconnected_operators:
- name: metallb-operator
- name: lvms-operator
  channels:
  - name: stable-4.13
disconnected_extra_images:
- quay.io/user-name/trbsht:latest
- quay.io/user-name/hypershift:BMSelfManage-v4.14-rc-v3
- registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.10
dualstack: false
disk_size: 200
extra_disks: [200]
memory: 48000
numcpus: 16
ctlplanes: 3
workers: 0
manifests: extra-manifests
metal3: true
network: ipv6
users_dev: developer
users_devpassword: developer
users_admin: admin
users_adminpassword: admin
metallb_pool: ipv6-virtual-network
metallb_ranges:
- 2620:52:0:1305::150-2620:52:0:1305::190
metallb_autoassign: true
apps:
- users
- lvms-operator
- metallb-operator
vmrules:
- hub-bootstrap:
    nets:
    - name: ipv6
      mac: aa:aa:aa:aa:03:10
- hub-ctlplane-0:
    nets:
    - name: ipv6
      mac: aa:aa:aa:aa:03:01
- hub-ctlplane-1:
    nets:
    - name: ipv6
      mac: aa:aa:aa:aa:03:02
- hub-ctlplane-2:
    nets:
    - name: ipv6
      mac: aa:aa:aa:aa:03:03
----

. To provision the management cluster, enter the following command:

+
----
kcli create cluster openshift --pf mgmt-compact-hub-ipv6.yaml
----

[#ipv6-mgmt-cluster-additional-resources]
== Additional resources

* For more information about the parameters in the `kcli` plan file, see link:https://kcli.readthedocs.io/en/latest/#how-to-use[Create a parameters.yml] in the official `kcli` documentation.