[#hosted-control-planes-manage-kubevirt]
= Managing hosted control plane clusters on OpenShift Virtualization

With hosted control planes and {ocp-virt}, you can create {ocp-short} clusters with worker nodes that are hosted by KubeVirt virtual machines. Hosted control planes on {ocp-virt-short} provides several benefits: 

* Enhances resource usage by packing hosted control planes and hosted clusters in the same underlying bare metal infrastructure
* Separates hosted control planes and hosted clusters to provide strong isolation
* Reduces cluster provision time by eliminating the bare metal node bootstrapping process
* Manages many releases under the same base {ocp-short} cluster

[#create-hosted-clusters-prereqs-kubevirt]
== Prerequisites

You must meet the following prerequisites to create an {ocp-short} cluster on {ocp-virt-short}:

- You need administrator access to an {ocp-short} cluster, version 4.12 or later, specified by the `KUBECONFIG` environment variable.
- The {ocp-short} managed cluster must have wildcard DNS routes enabled, as shown in the following DNS:

+
----
oc patch ingresscontroller -n openshift-ingress-operator default --type=json -p '[{ "op": "add", "path": "/spec/routeAdmission", "value": {wildcardPolicy: "WildcardsAllowed"}}]'
----
- The {ocp-short} managed cluster must have {ocp-virt-short} installed on it. For more information, see link:https://docs.openshift.com/container-platform/4.13/virt/install/installing-virt-web.html[Installing OpenShift Virtualization using the web console].
- The {ocp-short} managed cluster must be configured with OVNKubernetes as the default pod network CNI.
- The {ocp-short} managed cluster must have a default storage class. For more information, see link:https://docs.openshift.com/container-platform/4.13/post_installation_configuration/storage-configuration.html[Post-installation storage configuration]. The following example shows how to set a default storage class:

+
----
oc patch storageclass ocs-storagecluster-ceph-rbd -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
- You need a valid pull secret file for the `quay.io/openshift-release-dev` repository. For more information, see link:https://console.redhat.com/openshift/install/platform-agnostic/user-provisioned[Install OpenShift on any x86_64 platform with user-provisioned infrastructure].
- You need to xref:../hosted_control_planes/configure_hosted_aws.adoc#hosted-install-cli[install the hosted control plane command line interface (hcp) binary].
- Before you can provision your cluster, you need to configure a load balancer. For more information, see xref:../hosted_control_planes/hosting_service_cluster_configure_metallb.adoc#hosting-service-cluster-configure-metallb-config[Optional: Configuring MetalLB].

[#firewall-port-reqs-kubevirt]
== Firewall and port requirements

Ensure that you meet the firewall and port requirements so that ports can communicate between the management cluster, the control plane, and hosted clusters:

* The `kube-apiserver` service runs on port 6443 by default and requires ingress access for communication between the control plane components. 

** If you use the `NodePort` publishing strategy, ensure that the node port that is assigned to the `kube-apiserver` service is exposed.
** If you use MetalLB load balancing, allow ingress access to the IP range that is used for load balancer IP addresses.

* If you use the `NodePort` publishing strategy, use a firewall rule for the `ignition-server` and `Oauth-server` settings.

* The `konnectivity` agent, which establishes a reverse tunnel to allow bi-directional communication on the hosted cluster, requires egress access to the cluster API server address on port 6443. With that egress access, the agent can reach the `kube-apiserver` service.

** If the cluster API server address is an internal IP address, allow access from the workload subnets to the IP address on port 6443.
** If the address is an external IP address, allow egress on port 6443 to that external IP address from the nodes.

* If you change the default port of 6443, adjust the rules to reflect that change.
* Ensure that you open any ports that are required by the workloads that run in the clusters.
* Use firewall rules, security groups, or other access controls to restrict access to only required sources. Avoid exposing ports publicly unless necessary.
* For production deployments, use a load balancer to simplify access through a single IP address.

[#manage-hosted-cluster-ovn]
== Managing hosted control plane clusters on OpenShift Virtualization

To create a hosted control plane cluster on {ocp-virt-short}, see the following sections:

* xref:../hosted_control_planes/creating_a_hosted_cluster_kubevirt.adoc#creating-a-hosted-cluster-kubevirt[Creating a hosted cluster with the KubeVirt platform]
* xref:../hosted_control_planes/hosting_service_cluster_access.adoc#access-hosted-cluster[Accessing the hosted cluster]
* xref:../hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc#create-hosted-clusters-kubevirt-default-ingress-dns[Default ingress and DNS behavior]
* xref:../hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc#create-hosted-clusters-kubevirt-customized-ingress-dns[Customizing ingress and DNS behavior]
* xref:../hosted_control_planes/create_hosted_clusters_kubevirt_scaling_node_pool.adoc#create-hosted-clusters-kubevirt-scaling-node-pool[Scaling a node pool]
* xref:../hosted_control_planes/node_autoscaling_hosted_cluster.adoc#enable-node-auto-scaling-hosted-cluster[Enabling node auto-scaling for the hosted cluster]
* xref:../hosted_control_planes/create_hosted_clusters_kubevirt_scaling_node_pool.adoc#create-hosted-clusters-kubevirt-adding-node-pool[Adding node pools]
* xref:../hosted_control_planes/verifying_cluster_creation_kubevirt.adoc#verifying-cluster-creation-kubevirt[Verifying hosted cluster creation on OpenShift Virtualization]
* xref:../hosted_control_planes/configuring_storage_kubevirt.adoc#configuring-storage-kubevirt[Configuring storage for hosted control planes on OpenShift Virtualization]
* xref:../hosted_control_planes/hypershift_cluster_destroy_kubevirt.adoc#hypershift-cluster-destroy-kubevirt[Destroying a hosted cluster on OpenShift Virtualization]