[#hosted-control-planes-manage-bm]
= Managing hosted control plane clusters on bare metal

You can use the {mce} console or the hcp command line interface to create a {ocp} hosted cluster. The hosted cluster is automatically imported as a managed cluster. If you wish to disable this automatic import feature, refer to https://github.com/stolostron/rhacm-docs/blob/2.9_stage/clusters/hosted_control_planes/hosted_disable_auto_import.adoc.

Note: Each hosted cluster must have a unique name in order of {mce-short} to manage it.

[#hosted-prerequisites-bm]
== Prerequisites

You must configure hosted control planes for bare metal before you can create hosted control plane clusters. See xref:../../clusters/hosted_control_planes/configure_hosted_bm.adoc#configuring-hosting-service-cluster-configure-bm[Configuring the hosting cluster on bare metal] for more information.

[#hosted-manage-bare-metal]
== Managing hosted control plane clusters on bare metal

To manage hosted control planes on bare metal, see the following topics:

* xref:../hosted_control_planes/scaling_nodepool_hosted.adoc#scaling-the-nodepool[Scaling the NodePool object for a hosted cluster]
* xref:../hosted_control_planes/handling_ingress_hosted.adoc#handling-ingress[Handling Ingress in a hosted cluster on bare metal]
xref:../hosted_control_planes/node_autoscaling_hosted_cluster.adoc#enable-node-auto-scaling-hosted-cluster[Enabling node auto-scaling for the hosted cluster]
* xref:../hosted_control_planes/destroying_hosted_bare_metal.adoc#hypershift-cluster-destroy-bm[Destroying a hosted cluster on bare metal]

[#additional-resources-manage-bm]
=== Additional resources

* You can now deploy the SR-IOV Operator. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/networking/hardware-networks#sriov-operator-hosted-control-planes_configuring-sriov-operator[Deploying the SR-IOV Operator for hosted control planes] to learn more about deploying the SR-IOV Operator.

