[#hosted-control-planes-manage-bm-ibmz]
= Managing hosted control plane clusters on bare metal (Technology Preview)


You can use the {mce} for Kubernetes operator console to create and manage a Red Hat {ocp} hosted cluster. Hosted control planes are available as a Technology Preview on bare metal.

[#hosted-prerequisites-bm-ibmz]
== Prerequisites

You must configure hosted control planes for bare metal before you can create hosted control plane clusters. See xref:..//hosted_control_planes/configure_hosted_bm_ibmz.adoc#configuring-hosting-service-cluster-configure-ibmz[Configuring the hosting cluster on 'x86' bare metal for IBM Z compute nodes (Technology Preview)] for more information.


[#additional-resources-manage-bm]
=== Additional resources

* You can now deploy the SR-IOV Operator. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/networking/hardware-networks#sriov-operator-hosted-control-planes_configuring-sriov-operator[Deploying the SR-IOV Operator for hosted control planes] to learn more about deploying the SR-IOV Operator.
