[#mce-hosting-cluster]
= Using the {mce-short} hub cluster as a hosting cluster

By default, the {mce-short} hub cluster is configured as the only hosting cluster for all hosted control planes.

After installing {mce-short} and creating the `MultiClusterEngine` instance, {product-title-short} enables the following components automatically:

* `assisted-service`
* `cluster-lifecycle`
* `cluster-manager`
* `discovery`
* `hive`
* `server-foundation`
* `cluster-proxy-addon`
* `local-cluster`
* `hypershift-local-hosting`
* `hypershift`
* `managedserviceaccount`
* `console-mce`
* `multicluster-engine`

[#local-cluster-hypershift-addon]
== Understanding local-cluster and hypershift-addon

The `local-cluster` component creates a managed cluster, `local-cluster`. The `hypershift` component enables the hosted control plane feature and installs the `hypershift-addon` managed cluster add-on.

The `hypershift-addon` add-on enables the hosted control plane command line interface, `hcp`.

The `hypershift-local-hosting` component enables and deploys `hypershift-addon`for the `local-cluster`. Then, `hypershift-addon` installs the HyperShift Operator in the `hypershift` namespace.

Now, the {mce-short} hub cluster that is, `local-cluster` becomes a hosting cluster where you can create hosted control planes.

[#mce-hosting-cluster-create-destroy]
== Creating and deleting a hosted cluster on the {mce-short} hub cluster

You can download and use the hosted control plane command line interface, `hcp`, to create hosted clusters in the {mce-short} hub cluster. The `hypershift-addon` agent automatically imports the hosted clusters into the {mce-short} hub cluster. You can disable this auto-import feature.

From the {mce-short} hub cluster, you can use the `hcp create cluster` command to create a hosted cluster.

You can use the `hcp destroy cluster` command to delete the hosted cluster.

[#mce-hosting-cluster-scale]
== Scaling nodes on the {mce-short} hub cluster

All hosted control planes run on the nodes of the {mce-short} hub cluster. The number of hosted control planes that the cluster can host depends on the resource availability of the nodes. You can host more hosted control planes, by adding more nodes in the {mce-short} hub cluster.
