[#scaling-the-nodepool-ibmz]
= Scaling the NodePool object for a hosted cluster on IBM Z

The `NodePool` object is created when you create a hosted cluster. By scaling the `NodePool` object, you can add more compute nodes to the hosted control plane.

. Run the following command to scale the `NodePool` object to two nodes:

+
[source,bash]
----
oc -n <clusters_namespace> scale nodepool <nodepool_name> --replicas 2
----

+
The Cluster API agent provider randomly picks two agents that are then assigned to the hosted cluster. Those agents go through different states and finally join the hosted cluster as {ocp-short} nodes. The agents pass through the transition phases in the following order:

* `binding`
* `discovering`
* `insufficient`
* `installing`
* `installing-in-progress`
* `added-to-existing-cluster`

. Run the following command to see the status of a specific scaled agent:

+
[source,bash]
----
oc -n <hosted_control_plane_namespace> get agent -o jsonpath='{range .items[*]}BMH: {@.metadata.labels.agent-install\.openshift\.io/bmh} Agent: {@.metadata.name} State: {@.status.debugInfo.state}{"\n"}{end}'
----

+
See the following output:

+
[source,bash]
----
BMH: Agent: 50c23cda-cedc-9bbd-bcf1-9b3a5c75804d State: known-unbound
BMH: Agent: 5e498cd3-542c-e54f-0c58-ed43e28b568a State: insufficient
----

. Run the following command to see the transition phases:

+
[source,bash]
----
oc -n <hosted_control_plane_namespace> get agent
----

+
See the following output:

+
[source,bash]
----
NAME                                   CLUSTER           APPROVED       ROLE        STAGE
50c23cda-cedc-9bbd-bcf1-9b3a5c75804d   hosted-forwarder   true          auto-assign
5e498cd3-542c-e54f-0c58-ed43e28b568a                      true          auto-assign
da503cf1-a347-44f2-875c-4960ddb04091   hosted-forwarder   true          auto-assign
----

+
//lahinson - nov. 2023 - adding comment to ensure proper formatting

. Run the following command to generate the `kubeconfig` file to access the hosted cluster:

+
[source,bash]
----
hcp create kubeconfig --namespace <clusters_namespace> --name <hosted_cluster_namespace> > <hosted_cluster_name>.kubeconfig
----

. After the agents reach the `added-to-existing-cluster` state, verify that you can see the {ocp-short} nodes by entering the following command:

+
[source,bash]
----
oc --kubeconfig <hosted_cluster_name>.kubeconfig get nodes
----

+
See the following output:

+
[source,bash]
----
NAME                             STATUS   ROLES    AGE      VERSION
worker-zvm-0.hostedn.example.com Ready    worker   5m41s    v1.24.0+3882f8f
worker-zvm-1.hostedn.example.com Ready    worker   6m3s     v1.24.0+3882f8f
----

+
Cluster Operators start to reconcile by adding workloads to the nodes. 

. Enter the following command to verify that two machines were created when you scaled up the `NodePool` object:

+
[source,bash]
----
oc -n <hosted_control_plane_namespace> get machine.cluster.x-k8s.io
----

+
See the following output:

+
[source,bash]
----
NAME                                CLUSTER  NODENAME PROVIDERID     PHASE     AGE   VERSION
hosted-forwarder-79558597ff-5tbqp   hosted-forwarder-crqq5   worker-zvm-0.hostedn.example.com   agent://50c23cda-cedc-9bbd-bcf1-9b3a5c75804d   Running   41h   4.14.0
hosted-forwarder-79558597ff-lfjfk   hosted-forwarder-crqq5   worker-zvm-1.hostedn.example.com   agent://5e498cd3-542c-e54f-0c58-ed43e28b568a   Running   41h   4.14.0
----

. Run the following command to check the cluster version:

+
[source,bash]
----
oc --kubeconfig <hosted_cluster_name>.kubeconfig get clusterversion,co
----

+
See the following output:

+
[source,bash]
----
NAME                                         VERSION       AVAILABLE   PROGRESSING   SINCE   STATUS
clusterversion.config.openshift.io/version   4.14.0-ec.2   True        False         40h     Cluster version is 4.14.0-ec.2
----

. Run the following command to check the cluster operator status:

+
[source,bash]
----
oc --kubeconfig <hosted_cluster_name>.kubeconfig get clusteroperators
----

+
See the following output:

+
[source,bash]
----
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
console                                    4.14.2    True        False         False      5h34m   
csi-snapshot-controller                    4.14.2    True        False         False      5h47m   
dns                                        4.14.2    True        False         False      5h35m   
image-registry                             4.14.2    True        False         False      5h34m   
ingress                                    4.14.2    True        False         False      5h46m   
insights                                   4.14.2    True        False         False      5h35m   
kube-apiserver                             4.14.2    True        False         False      5h47m   
kube-controller-manager                    4.14.2    True        False         False      5h47m   
kube-scheduler                             4.14.2    True        False         False      5h47m   
kube-storage-version-migrator              4.14.2    True        False         False      5h35m   
monitoring                                 4.14.2    True        False         False      5h34m   
network                                    4.14.2    True        False         False      5h34m   
node-tuning                                4.14.2    True        False         False      5h35m   
openshift-apiserver                        4.14.2    True        False         False      5h47m   
openshift-controller-manager               4.14.2    True        False         False      5h47m   
openshift-samples                          4.14.2    True        False         False      5h34m   
operator-lifecycle-manager                 4.14.2    True        False         False      5h47m   
operator-lifecycle-manager-catalog         4.14.2    True        False         False      5h47m   
operator-lifecycle-manager-packageserver   4.14.2    True        False         False      5h47m   
service-ca                                 4.14.2    True        False         False      5h35m   
storage                                    4.14.2    True        False         False      5h47m   
----
