[#fips-readiness]
= FIPS readiness

FIPS readiness has been completed for {product-title}. {product-title-short} uses the same tools to make sure cryptography calls are passed to the Red Hat Enterprise Linux (RHEL) certified cryptographic modules that are used by {ocp}. For more details on OpenShift FIPS support see, link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/installing/installing-fips[Support for FIPS cryptography].

[#fips-limitations]
== Limitations 

Read the following limitations with {product-title-short} and FIPS.

* {ocp} only supports FIPS on the `x86_64` architecture. 

* Integrity Shield is a Technology Preview component that is not FIPS ready.

* Persistent Volume Claim (PVC) and S3 storage that is used by the search and observability components must be encrypted when you configure the provided storage. {product-title-short} does not provide storage encryption, see the {ocp-short} documentation, link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/installing/installing-fips[Support for FIPS cryptography].

* When you provision managed clusters using the {product-title-short} console, select the following check box in the _Cluster details_ section of the managed cluster creation to enable the FIPS standards: 
+
----
FIPS with information text: Use the Federal Information Processing Standards (FIPS) modules provided with Red Hat Enterprise Linux CoreOS instead of the default Kubernetes cryptography suite file before you deploy the new managed cluster.
----
