[#updating-the-cluster-pool-release-image]
= Updating the cluster pool release image

When the clusters in your cluster pool remain in hibernation for some time, the {ocp} release image of the clusters might become backlevel. If this happens, you can upgrade the version of the release image of the clusters that are in your cluster pool.  

*Required access*: Edit

Complete the following steps to update the {ocp-short} release image for the clusters in your cluster pool:

*Note:* This procedure does not update clusters from the cluster pool that are already claimed in the cluster pool. After you complete this procedure, the updates to the release images only apply to the following clusters that are related to the cluster pool:

* Clusters that are created by the cluster pool after updating the release image with this procedure.

* Clusters that are hibernating in the cluster pool. The existing hibernating clusters with the old release image are destroyed, and new clusters with the new release image replace them. 

--
. From the navigation menu, click *Infrastructure* > *Clusters*.

. Select the _Cluster pools_ tab.

. Find the name of the cluster pool that you want to update in the _Cluster pools_ table.

. Click the _Options_ menu for the _Cluster pools_ in the table, and select *Update release image*.

. Select a new release image to use for future cluster creations from this cluster pool.
--

The cluster pool release image is updated. 

*Tip:* You can update the release image for multiple cluster pools with one action by selecting the box for each of the the cluster pools and using the _Actions_ menu to update the release image for the selected cluster pools.
