[#managing-cluster-pools]
= Managing cluster pools (Technology Preview)

Cluster pools provide rapid and cost-effective access to configured {ocp} clusters on-demand and at scale. Cluster pools provision a configurable and scalable number of {ocp-short} clusters on Amazon Web Services, Google Cloud Platform, or Microsoft Azure that can be claimed when they are needed. They are especially useful when providing or replacing cluster environments for development, continuous integration, and production scenarios. You can specify a number of clusters to keep running so that they are available to be claimed immediately, while the remainder of the clusters will be kept in a hibernating state so that they can be resumed and claimed within a few minutes.

`ClusterClaim` resources are used to check out clusters from cluster pools. When a cluster claim is created, the pool assigns a running cluster to it. If no running clusters are available, a hibernating cluster is resumed to provide the cluster or a new cluster is provisioned. The cluster pool automatically creates new clusters and resumes hibernating clusters to maintain the specified size and number of available running clusters in the pool. 

* xref:../cluster_lifecycle/cluster_pool_create.adoc#creating-a-clusterpool[Creating a cluster pool]
* xref:../cluster_lifecycle/cluster_pool_claim_cluster.adoc#claiming-clusters-from-cluster-pools[Claiming clusters from cluster pools]
* xref:../cluster_lifecycle/cluster_pool_rel_img_update.adoc#updating-the-cluster-pool-release-image[Updating the cluster pool release image]
* xref:../cluster_lifecycle/scale_cluster_pool.adoc#scaling-cluster-pools[Scaling cluster pools]
* xref:../cluster_lifecycle/cluster_pool_destroy.adoc#destroying-a-cluster-pool[Destroying a cluster pool]

The procedure for creating a cluster pool is similar to the procedure for creating a cluster. Clusters in a cluster pool are not created for immediate use.