[#creating-an-infrastructure-environment]
= Creating an infrastructure environment

You can use the {product-title} console to create an infrastructure environment to manage your hosts and create clusters on those hosts.

* <<infra-env-prerequisites,Prerequisites>>
* <<enable-cim,Enable Central Infrastructure Management service>>
* <<creating-your-infra-env-with-the-console,Creating your infrastructure environment with the console>>
* <<accessing-your-infra-env,Accessing your infrastructure environment>>

Infrastructure environments support the following features:

- Zero-touch provisioning of clusters: Deploy clusters using a script. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/scalability_and_performance/ztp-deploying-disconnected[Deploying distributed units at scale in a disconnected environment] in the {ocp} documentation for more information.
- Late binding: Enable the host to be booted by an infrastructure administrator, and the creator of a cluster can bind a cluster to that host at a later time. The cluster creator does not have to have administrator privileges to the infrastructure when using late binding.
- Dual stack: Deploy clusters that have both IPv4 and IPv6 addresses. Dual stack uses the `OVN-Kubernetes` networking implementation to support multiple subnets. 
- Add remote worker nodes: Add remote worker nodes to your clusters after they are created and running, which provides flexibility of adding nodes in other locations for backup purposes.
- Static IP using NMState: Use the NMState API to define static IP addresses for your environment.

[#infra-env-prerequisites]
== Prerequisites

See the following prerequisites before creating an infrastructure environment:

* You must have a deployed {product-title-short} hub cluster on {ocp-short} version 4.11 or later.
* You need Internet access for your {product-title-short} hub cluster (connected), or a connection to an internal or mirror registry that has a connection to the Internet (disconnected) to retrieve the required images for creating the environment.
* You need a configured instance of the Central Infrastructure Management (CIM) feature on your hub cluster. 
* You need an {ocp-short} https://console.redhat.com/openshift/install/pull-secret[pull secret]. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/images/managing-images#using-image-pull-secrets[Using image pull secrets] for more information. 
* You need your SSH key that is in your `~/.ssh/id_rsa.pub` file, by default.
* You need a configured storage class. 
* *Disconnected environment only:* Complete the procedure for https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/scalability_and_performance/ztp-deploying-disconnected#ztp-acm-preparing-to-install-disconnected-acm_ztp-deploying-disconnected[Preparing the disconnected environment] in the {ocp-short} documentation.

[#enable-cim]
== Enabling the Central Infrastructure Management service

The CIM service is provided with {product-title-short} and deploys {ocp-short} clusters. CIM is deployed when you enable the MultiClusterHub Operator on the {product-title-short} hub cluster, but must be enabled.

To enable the CIM service, complete the following steps: 

. If your {product-title-short} hub cluster platform is bare metal, Red Hat OpenStack Platform, VMware vSphere, or was installed using the user-provisioned infrastructure (UPI) method and the platform is `None`, modify the `Provisioning` resource to allow the Bare Metal Operator to watch all namespaces by running the following command:
+
----
oc patch provisioning provisioning-configuration --type merge -p '{"spec":{"watchAllNamespaces": true }}'
----

. Create the `AgentServiceConfig` CR by completing the following steps:

.. Save the following `YAML` content in the `agent_service_config.yaml` file:
+
[source,yaml]
----
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
 name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: <db_volume_size> 
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: <fs_volume_size>
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: <img_volume_size>
  osImages: 
    - openshiftVersion: "<ocp_version>" 
      version: "<ocp_release_version>" 
      url: "<iso_url>" 
      rootFSUrl: "<root_fs_url>" 
      cpuArchitecture: "x86_64"
----
+
Replace `db_volume_size` with the volume size for the `databaseStorage` field, for example `50M`. This value specifies how much storage is is allocated for storing files like database tables and database views for the clusters. You might need to use a higher value if there are many clusters.
+
Replace `fs_volume_size` with the size of the volume for the `filesystemStorage` field, for example `50M`. This value specifies how much storage is allocated for storing logs, manifests, and `kubeconfig` files for the clusters. You might need to use a higher value if there are many clusters. 
+
Replace `img_volume_size` with the size of the volume for the `imageStorage` field, for example `10GB`. This value specifies how much storage is allocated for the images of the clusters. You need to allow 1 GB of image storage for each instance of Red Hat Enterprise Linux CoreOS that is running. You might need to use a higher value if there are many clusters and instances of Red Hat Enterprise Linux CoreOS.
+
Replace `ocp_version` with the {ocp-short} version to install, for example, `4.11`.
+
Replace `ocp_release_version` with the specific install version, for example, `49.83.202103251640-0`.
+
Replace `iso_url` with the ISO url, for example, `https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.10/4.10.3/rhcos-4.10.3-x86_64-live.x86_64.iso`. You can find other values at: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.10/4.10.3/.
+
Replace `root_fs_url` with the root FS image URL, for example, `https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.10/4.10.3/rhcos-4.10.3-x86_64-live-rootfs.x86_64.img`. You can find other values at: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.10/4.10.3/.

.. Create the AgentServiceConfig CR by running the following command:
+
----
oc create -f agent_service_config.yaml
----
+
The output might resemble the following example:
+
----
agentserviceconfig.agent-install.openshift.io/agent created
----

Your CIM service is configured. You can verify that it is healthy by checking the `assisted-service` and `assisted-image-service` deployments and ensuring that their pods are ready and running. 

[#creating-your-infra-env-with-the-console]
== Creating your infrastructure environment with the console

To create an infrastructure environment from the {product-title-short} console, complete the following steps:

. From the navigation menu, navigate to *Infrastructure* > *Infrastructure environments* and click *Create infrastructure environment*.
. Add the following information to your infrastructure environment settings: 
+
* Name: A unique name for your environment. 
* Network type: Specifies which types of hosts can be added to your environment. You can only use the static IP option when you are using bare metal hosts. 
* Location: Specifies the geographic location of the host. The geographic location can be used to easily determine where your data on a cluster is stored when you are creating the cluster. 
* Labels: Optional field where you can add labels to the infrastructure environment so you can more easily find and group the environment with other environments that share a characteristic. The selections that you made for the network type and location are automatically added to the list of labels.
* Pull secret: Your {ocp-short} https://console.redhat.com/openshift/install/pull-secret[pull secret] that enables you to access the {ocp-short} resources. 
* SSH public key: The SSH key that enables the secure communication with the hosts. This is generally in your `~/.ssh/id_rsa.pub` file, by default.
* If you want to enable proxy settings across all of your clusters, select the setting to enable it. This requires that you enter the following information: 
+
** HTTP Proxy URL: The URL that should be used when accessing the discovery service. 

** HTTPS Proxy URL: The secure proxy URL that should be used when accessing the discovery service. Note that the format must be `http`, as `https` is not yet supported. 

** No Proxy domains: A comma-separated list of domains that should bypass the proxy. Begin a domain name with a period `.` to include all of the subdomains that are in that domain. Add and asterisk `*` to bypass the proxy for all destinations. 

You can now continue by adding hosts to your infrastructure environment. 

[#accessing-your-infra-env]
== Accessing an infrastructure environment

To access an infrastructure environment, select *Infrastructure* > *Infrastructure environments* in the {product-title-short} console. Select your infrastructure environment from the list to view the details and hosts for that infrastructure environment.

