[#adding-clusters-to-a-managedclusterset]
= Adding a cluster to a ManagedClusterSet
//possibly part of scenario 2, but still need to add info about creating a cluster

After you create your `ManagedClusterSet`, you must add one or more managed clusters. You can add managed clusters to your managed cluster set by using either the console or the command line.

[#adding-clusters-to-a-managedclusterset-console]
== Adding clusters to a ManagedClusterSet by using the console

Complete the following steps to add a cluster to a managed cluster set by using the {product-title-short} console:

. If you just created your managed cluster set, select *Manage resource assignments* to go directly to the _Manage resource assignments_ page. Continue with step 6 of this procedure. 

. If your cluster already exists, access the cluster page by selecting *Infrastructure* > *Clusters* in the main navigation.

. Select the *Cluster sets* tab to view the available cluster sets. 

. Select the name of the cluster set that you want to add to the managed cluster sets to view the cluster set details.

. Select *Actions* > *Manage resource assignments*.

. On the _Manage resource assignments_ page, select the checkbox for the resources that you want to add to the cluster set. 

. Select *Review* to review your changes. 

. Select *Save* to save your changes. 
+
*Note:* If you move a managed cluster from one managed cluster set to another, you must have the required RBAC permission available on both managed cluster sets.  

[#adding-clusters-to-a-managedclusterset-cli]
== Adding clusters to a ManagedClusterSet by using the command line

Complete the following steps to add a cluster to a managed cluster set by using the command line:

. Ensure that there is an RBAC `ClusterRole` entry that allows you to create on a virtual subresource of `managedclustersets/join`. Without this permission, you cannot assign a managed cluster to a `ManagedClusterSet`. 
+
If this entry does not exist, add it to your `yaml` file. A sample entry resembles the following content:

+
[source,yaml]
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole1
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclustersets/join"]
    resourceNames: ["<clusterset1>"]
    verbs: ["create"]
----
+
Replace `clusterset1` with the name of your `ManagedClusterSet`.
+
*Note:* If you are moving a managed cluster from one `ManagedClusterSet` to another, you must have that permission available on both managed cluster sets. 

. Find the definition of the managed cluster in the `yaml` file. The section of the managed cluster definition where you add a label resembles the following content:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: cluster1
spec:
  hubAcceptsClient: true 
----
+
In this example, `cluster1` is the name of the managed cluster.

. Add a label that specifies the name of the `ManagedClusterSet` in the format: `cluster.open-cluster-management.io/clusterset: clusterset1`.
+
Your code resembles the following example:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: cluster1
  labels:
    cluster.open-cluster-management.io/clusterset: clusterset1
spec:
  hubAcceptsClient: true
----
+
In this example, `cluster1` is the cluster that is added to the managed cluster set names `clusterset1`.
+
*Note:* If the managed cluster was previously assigned to a managed cluster set that was deleted, the managed cluster might have a managed cluster set already specified to a cluster set that does not exist. If so, replace the name with the new one.
