[#creating-a-cluster-on-amazon-web-services]
= Creating a cluster on Amazon Web Services

You can use the {mce} console to create a {ocp} cluster on Amazon Web Services (AWS) or on AWS GovCloud. The few differences are identified in the procedure.  

AWS GovCloud provides cloud services that meet additional requirements that are required to store government documents on the cloud. When you create a cluster for AWS GovCloud, there are some additional steps to prepare your environment.

When you create a cluster, the creation process uses the {ocp-short} installer with the Hive resource. If you have questions about cluster creation after completing this procedure, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-aws[Installing on AWS] in the {ocp-short} documentation for more information about the process.  

* <<aws_prerequisites,Prerequisites>>
* <<aws-creating-your-cluster-with-the-console,Creating your cluster with the console>>

[#aws_prerequisites]
== Prerequisites

See the following prerequisites before creating a cluster on AWS or AWS GovCloud:

Standard AWS cluster creation prerequisites:

* You need Internet access for your {mce} hub cluster so it can create the Kubernetes cluster on Amazon Web Services.

* You need an AWS credential. See xref:../credentials/credential_aws.adoc#creating-a-credential-for-amazon-web-services[Creating a credential for Amazon Web Services] for more information.

* You need a configured domain in AWS. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-aws#installing-aws-account[Configuring an AWS account] for instructions on how to configure a domain.

* You must have Amazon Web Services (AWS) login credentials, which include user name, password, access key ID, and secret access key. See https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html[Understanding and Getting Your Security Credentials].

* You must have an {ocp-short} image pull secret. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/images/managing-images#using-image-pull-secrets[Using image pull secrets].

AWS GovCloud specific prerequisites:

* You must have an Amazon Virtual Private Cloud (VPC) with an existing {ocp} cluster for the hub cluster. The hub cluster name for this example is `hub-vpc` and uses {ocp-short} 4.11.13 with {mce} version 2.2 or {product-title} version 2.7 installed. This VPC must be different from the VPCs that are used for the managed cluster resources or the managed cluster service endpoints.

* You need a VPC where the managed cluster resources are deployed. This cannot be the same as the VPCs that are used for the hub cluster or the managed cluster service endpoints. 

* You need one or more VPCs that provide the managed cluster service endpoints. This cannot be the same as the VPCs that are used for the hub cluster or the ACM managed cluster resources.

* Ensure that the IP addresses of the VPCs that are specified by the Classless Inter-Domain Routing (CIDR) for the required VPCs do not overlap.

* You need a `HiveConfig` file that references a credential within the Hive namespace that has access to create resources on the VPC that you created for the ACM managed cluster resources.

*Note:* If you change your cloud provider access key on the cloud provider, you also need to manually update the corresponding credential for the cloud provider on the console of {mce}. This is required when your credentials expire on the cloud provider where the managed cluster is hosted and you try to delete the managed cluster.

[#preparing-to-create-a-cluster-on-aws-gov]
== Preparing to create an AWS GovCloud cluster

While creating an AWS GovCloud cluster is almost identical to creating a standard AWS cluster, you have to complete some additional procedures to your environment to prepare them for the AWS GovCloud cluster.

[#create-vpcs-aws-govcloud]
=== Create the VPCs for resources and endpoints

As listed in the prerequisites, two VPCs are required in addition to the VPC that contains the hub cluster. See https://docs.aws.amazon.com/vpc/latest/userguide/working-with-vpcs.html#Create-VPC[Create a VPC] in the Amazon Web Services documentation for specific steps for creating a VPC.

. Create a VPC for the managed cluster with private subnets. For this example, this VPC is named `managed01-vpc`.

. Create one or more VPCs for the managed cluster service endpoints with private subnets. For this example, this VPC is named `managed01-endpoint-vpc`.

[#configure-vpcs-aws-govcloud]
=== Configure the VPCs for resources and endpoints

Configure the peer connections, route tables, and security groups for the VPCs that you created. 

. Configure the peer connections. 
+
.. Create a peer connection named `px-s01-h01` between `managed01-vpc` and `hub01-vpc`.

.. Create a peer connection named `px-s01e-h01` between `managed01-e-vpc` and `hub01-vpc`.

.. Create a peer connection named `px-s01-s01e` between `managed01-vpc` and `managed01-e-vpc`.

. For each peer connection that you created, ensure that the peer connection is successfully accepted by both clusters.

. Ensure that all DNS settings are enabled.

. Configure the route tables by completing the following steps:
+
.. Update all `*-private` route tables for `managed01-vpc`.

... Add an entry with the destination of `hub01-vpc` CIDR to peer connection `px-s01-h01`.

... Add an entry with the destination of `managed01-e-vpc` CIDR to peer connection `px-s01-s01e`.

.. Update all `*-private` route tables for `managed01-e-vpc`.

... Add an entry with the destination of `hub01-vpc` CIDR to peer connection `px-s01e-h01`.

... Add an entry with destination of `managed01-vpc` CIDR to peer connection `px-s01-s01e`.

.. Update all `*-private` route tables for `hub01-vpc`.

... Add an entry with the destination of `managed01-e-vpc` CIDR to peer connection `px-s01e-h01`.

... Add an entry with destination of `managed01-vpc` CIDR to peer connection `px-s01-h01`.

.. Configure the security groups.

... Obtain the IDs of the main and worker security groups for the `hub01-vpc` cluster. 

... Update the default security group of `managed01-vpc` to create an inbound rule that accepts all traffic from the main and worker security groups of the hub cluster.

... Update the default security group of `managed01-e-vpc` to create an inbound rule that accepts all traffic from the main and worker security groups of the hub cluster. 

... Update the `hub01-vpc` main security group to create an inbound rule that accepts all traffic from the CIDR of the `managed01-vpc` cluster.

... Update the `hub01-vpc` main security group to create an inbound rule that accepts all traffic from the CIDR of the `managed01-e-vpc` cluster.

... Update the `hub01-vpc` worker security group to create an inbound rule that accepts all traffic from the CIDR of `managed01-vpc`.

... Update the `hub01-vpc` worker security group to create an inbound rule that accepts all traffic from the CIDR of `managed01-e-vpc`.

.. Ensure that there is a credential secret within the Hive namespace
+
The `HiveConfig` file needs to reference a credential within the Hive namespace that has permissions to create resources in a specific provided VPC. If the credential you are using to provision an AWS cluster in AWS Government is already in the Hive namespace, then you do not need to create another one. If the credential that you are using to provision an AWS cluster in AWS Government is not already in the Hive namespace, you can either replace your current credential or create an additional credential in the Hive namespace.
+
The `HiveConfig` file needs to be updated to include the following content:
+
* An AWS Government credential that has the required permissions to provision resources for the given VPC.

* The addresses of the VPCs for the Red Hat OpenShift cluster installation, as well as the service endpoints for the managed cluster. *Best practice:* Use different VPCs for the {ocp-short} cluster installation and the service endpoints.
+
The following example shows the credential content:
+
[source,yaml]
----
spec:
  awsPrivateLink:
    associatedVPCs:
    - credentialsSecretRef:
        name: clc-aws-cred
      region: us-gov-east-1
      vpcID: vpc-0d0db3e664ee45657
    credentialsSecretRef:
      name: clc-aws-cred
    dnsRecordType: ARecord
    endpointVPCInventory:
    - region: us-gov-east-1
      subnets:
      - availabilityZone: us-gov-east-1a
        subnetID: subnet-00bf8fcc779ac848a
      - availabilityZone: us-gov-east-1b
        subnetID: subnet-05ee95537be0a8e71
      - availabilityZone: us-gov-east-1c
        subnetID: subnet-0de5d0193103a0683
      vpcID: vpc-05ac209956ba057c5
----

For more information, refer to the https://github.com/openshift/hive/blob/master/docs/awsprivatelink.md#configuring-hive-to-enable-aws-private-link[Hive documentation].

[#aws-creating-your-cluster-with-the-console]
== Creating your cluster with the console

To create a cluster from the console, navigate to *Infrastructure* > *Clusters* > *Create cluster* *AWS* > *Standalone* and complete the steps in the console. 

*Note:* This procedure is for creating a cluster. If you have an existing cluster that you want to import, see xref:../cluster_lifecycle/import.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a target managed cluster to the hub cluster] for those steps.

The credential that you select must have access to the resources in an AWS GovCloud region, if you create an AWS GovCloud cluster. If you need to create a credential, see xref:../credentials/credential_aws.adoc#creating-a-credential-for-amazon-web-services[Creating a credential for Amazon Web Services] for more information.

The name of the cluster is used in the hostname of the cluster.

*Important:* When you create a cluster, the controller creates a namespace for the cluster and its resources. Ensure that you include only resources for that cluster instance in that namespace. Destroying the cluster deletes the namespace and all of the resources in it.

*Tip:* Select *YAML: On* to view content updates as you enter the information in the console.

If you want to add your cluster to an existing cluster set, you must have the correct permissions on the cluster set to add it. If you do not have `cluster-admin` privileges when you are creating the cluster, you must select a cluster set on which you have `clusterset-admin` permissions. If you do not have the correct permissions on the specified cluster set, the cluster creation fails. Contact your cluster administrator to provide you with `clusterset-admin` permissions to a cluster set if you do not have any cluster set options to select.

Every managed cluster must be associated with a managed cluster set. If you do not assign the managed cluster to a `ManagedClusterSet`, it is automatically added to the `default` managed cluster set.

If there is already a base DNS domain that is associated with the selected credential that you configured with your AWS account, that value is populated in the field. You can change the value by overwriting it. This name is used in the hostname of the cluster. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/installing/installing-on-aws#installing-aws-account[Configuring an AWS account] for more information.

The release image identifies the version of the {ocp-short} image that is used to create the cluster. If the version that you want to use is available, you can select the image from the list of images. If the image that you want to use is not a standard image, you can enter the URL to the image that you want to use. See xref:../cluster_lifecycle/release_images.adoc#release-images[Release images] for more information about release images.

The node pools include the control plane pool and the worker pools. The control plane nodes share the management of the cluster activity. The information includes the following fields:

* Region: The region where you create your cluster resources. If you are creating a cluster on an AWS GovCloud provider, you must include an AWS GovCloud region for your node pools. For example, `us-gov-west-1`.

* CPU architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool. Valid values are _amd64_, _ppc64le_, _s390x_, and _arm64_.

* Zones: Specify where you want to run your control plane pools. You can select multiple zones within the region for a more distributed group of control plane nodes. A closer zone might provide faster performance, but a more distant zone might be more distributed.

* Instance type: Specify the instance type for your control plane node. You can change the type and size of your instance after it is created. 

* Root storage: Specify the amount of root storage to allocate for the cluster. 

You can create zero or more worker nodes in a worker pool to run the container workloads for the cluster. They can be in a single worker pool, or distributed across multiple worker pools. If zero worker nodes are specified, the control plane nodes also function as worker nodes. The optional information includes the following fields:

* Pool name: Provide a unique name for your pool.

* Zones: Specify where you want to run your worker pools. You can select multiple zones within the region for a more distributed group of nodes. A closer zone might provide faster performance, but a more distant zone might be more distributed.

* Instance type: Specify the instance type of your worker pools. You can change the type and size of your instance after it is created.

* Node count: Specify the node count of your worker pool. This setting is required when you define a worker pool.

* Root storage: Specify the amount of root storage allocated for your worker pool. This setting is required when you define a worker pool.

Networking details are required for your cluster, and multiple networks are required for using IPv6. For an AWS GovCloud cluster, enter the values of the block of addresses of the Hive VPC in the _Machine CIDR field. You can add an additional network by clicking *Add network*. 

Proxy information that is provided in the credential is automatically added to the proxy fields. You can use the information as it is, overwrite it, or add the information if you want to enable a proxy. The following list contains the required information for creating a proxy:  

* HTTP proxy URL: Specify the URL that should be used as a proxy for `HTTP` traffic. 

* HTTPS proxy URL: Specify the secure proxy URL that should be used for `HTTPS` traffic. If no value is provided, the same value as the `HTTP Proxy URL` is used for both `HTTP` and `HTTPS`.

* No proxy domains: A comma-separated list of domains that should bypass the proxy. Begin a domain name with a period `.` to include all of the subdomains that are in that domain. Add an asterisk `*` to bypass the proxy for all destinations. 

* Additional trust bundle: One or more additional CA certificates that are required for proxying HTTPS connections.

When creating an AWS GovCloud cluster or using a private environment, complete the fields on the _AWS private configuration_ page with the AMI ID and the subnet values.

Ensure that the value of `spec:platform:aws:privateLink:enabled` is set to `true` in the `ClusterDeployment.yaml` file.  

When you review your information and optionally customize it before creating the cluster, you can select *YAML: On* to view the `install-config.yaml` file content in the panel. You can edit the YAML file with your custom settings, if you have any updates.

*Note:* You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured under the management of {mce}. 

Continue with xref:../cluster_lifecycle/access_cluster.adoc#accessing-your-cluster[Accessing your cluster] for instructions for accessing your cluster. 