[#disable-hosted-control-planes]
= Disabling the hosted control plane cluster

When disabling the hosted control plane cluster feature, you must destroy the HyperShift hosted cluster and the managed cluster resource on the multicluster engine. Deleting only the hosted cluster, or only the managed cluster resource, might cause issues when you create the hosted cluster again, or if you are using the same managed cluster name. 

[#hypershift-cluster-destroy]
== Destroying a HyperShift hosted cluster

To destroy a HyperShift hosted cluster, complete the following steps:

. Delete the hosted cluster and its backend resources by running a command that resembles the following:
+
----
oc hcp destroy cluster aws --name <cluster_name> --infra-id <infra_id> --aws-creds <aws-credentials> --base-domain <base_domain> --destroy-cloud-resources
----
+
Replace names where necessary.

. Delete the managed cluster resource on the multicluster engine by running the following command:

----
$ oc delete managedcluster <cluster_name>
----
+
Replace `cluster_name` with the name of your cluster.

[#hypershift-uninstall-operator]
== Uninstalling the HyperShift operator

To uninstall the HyperShift operator from a management or hosting service cluster, delete the `hypershift-addon` `ManagedClusterAddon` from the management cluster by running the following command:

----
oc delete managedclusteraddon -n local-cluster hypershift-addon
----
