[#config-infra-node-acm]
= Configuring infrastructure nodes for {acm-short}

Configure your {ocp-short} cluster to contain infrastructure nodes to run approved {acm-short} management components. Running components on infrastructure nodes avoids allocating {ocp-short} subscription quota for the nodes that are running {acm-short} management components.

After adding infrastructure nodes to your {ocp-short} cluster, follow the xref:../install/install_connected.adoc#installing-from-the-cli[Installing from the {ocp-short} CLI] instructions and add configurations to the {olm} subscription and `MultiClusterHub` custom resource.

[#config-infra-nodes-ocp]
== Configuring infrastructure nodes to the {ocp-short} cluster

Follow the procedures that are described in link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.16/html/machine_management/creating-infrastructure-machinesets[Creating infrastructure machine sets] in the {ocp-short} documentation. Infrastructure nodes are configured with a Kubernetes `taints` and `labels` to keep non-management workloads from running on them.

. To be compatible with the infrastructure node enablement provided by {acm-short}, ensure your infrastructure nodes have the following `taints` and `labels` applied:

+
[source,yaml]
----
metadata:
  labels:
    node-role.kubernetes.io/infra: ""
spec:
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
----

. Add the following additional configuration before applying the {olm} Subscription:

+
[source,yaml]
----
spec:
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - key: node-role.kubernetes.io/infra
      effect: NoSchedule
      operator: Exists
----

. Add the following additional configuration before you apply the `MultiClusterHub` custom resource:

+
[source,yaml]
----
spec:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
----



. . Use the instructions found at: https://github.com/stolostron/rhacm-docs/blob/2.13_stage/add-ons/configure_nodeselector_tolerations_addons.adoc to update any add-ons to include the following node selectors and tolerations

+
[source,yaml]

    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - key: node-role.kubernetes.io/infra
      effect: NoSchedule
      operator: Exists
----

