[#install-on-disconnected-networks]
= Install on disconnected networks

You might need to install {product-title} on Red Hat OpenShift Clusters that are not connected to the Internet.
The procedure to install on a disconnected hub requires some of the same steps as the connected installation.
You must download copies of the packages in order to access them during the installation, rather than accessing them directly from the network during the installation.

[#prerequisites-for-a-disconnected-installation]
== Prerequisites for a disconnected installation

You must meet the following requirements before you install {product-title}:

* {ocp} version 4.3, or later, must be deployed in your environment, and you must be logged into it with the command line interface (CLI). Note: For managing bare metal clusters, you must have {ocp-short} version 4.5, or later.
See the https://docs.openshift.com/container-platform/4.3/welcome/index.html[OpenShift version 4.3 documentation], https://docs.openshift.com/container-platform/4.4/welcome/index.html[OpenShift version 4.4 documentation], or https://docs.openshift.com/container-platform/4.5/welcome/index.html[OpenShift version 4.5 documentation].
* Your {ocp} CLI must be version 4.3, or later, and configured to run `oc` commands.
See https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_cli/getting-started-cli.html[Getting started with the CLI] for information about installing and configuring the Red Hat OpenShift CLI.
* Your {ocp} permissions must allow you to create a namespace.
* You must have a workstation with Internet connection to download the dependencies for the operator.

[#installing-red-hat-advanced-cluster-management-for-kubernetes-in-a-disconnected-environment]
== Installing Red Hat Advanced Cluster Management for Kubernetes in a disconnected environment

Follow these steps to install {product-title-short} in a disconnected environment:

. Create a mirror registry, if necessary.
+
If you do not already have a mirror registry, create one by completing the procedure in the https://docs.openshift.com/container-platform/4.4/installing/install_config/installing-restricted-networks-preparations.html#installing-restricted-networks-preparations[Creating a mirror registry for installation in a restricted network] topic of the {ocp} documentation.
+
If you already have a mirror registry, you can configure and use your existing one.

. Bare metal only: Provide the certificate information for the disconnected registry in your `install-config.yaml` file. To access the image in a protected disconnected registry, you must provide the certificate information so {product-title-short} can access the registry.
.. Copy the certificate information from the registry.
.. Open the `install-config.yaml` file in an editor.
.. Find the entry for `additionalTrustBundle: |`.
.. Add the certificate information after the `additionalTrustBundle` line. The resulting content should look similar to the following example:
+
....
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  certificate_content
  -----END CERTIFICATE-----
sshKey: >-
....
.. Save the `install-config.yaml` file.

. Deploy a {product-title-short} policy to replace the default registry value with the value of your local registry. For these steps, the policy is named _imageContentSourcePolicy_ for the managed cluster to replace the default registry with the path to the registry instance that you created.

.. From the {product-title-short} console, select *Govern risk* > *Create policy*.
.. Set the `YAML` switch to _On_ to view the YAML version of the policy.
.. Find the _Setup_ section and locate the _Custom policy template_.
.. Find the `imageContentSourcePolicy.yaml` file on the {product-title-short} hub cluster. This file was created when the restricted OLM was configured.
.. Copy the contents of the `imageContentSourcePolicy.yaml` into the _Custom Resource_ section of the _Custom policy template_.
... Replace *Unique name* with a name for your policy.
... Replace *Managed clusters* with the name of the managed cluster that you are updating in the _Cluster binding_ field. *Tip:* You can find this name by viewing the _Cluster details_ page in the {product-title-short} console. 
... Change the `items: spec: upstream:` value to the path to your local registry. This value points to where your disconnected images are stored.
+
See link:../security/create_policy.adoc#managing-security-policies[Managing security policies] for information about creating a policy. 
.. Select the box for *Enforce if supported*.
.. Select *Create* to create the policy. 

. Enable the disconnected Operator Lifecycle Manager (OLM) Red Hat Operators and Community Operators.
+
{product-title-short} is included in the OLM Red Hat Operator catalog.
+

. Configure the disconnected OLM for the Red Hat Operator catalog.
Follow the steps in the Using Operator Lifecycle Manager on restricted networks topic of the {ocp-short} documentation.
. Now that you have the image in the disconnected OLM, continue to install {product-title-short} from the OLM catalog.
See the steps in xref:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online] for the required steps.
