[#install-on-disconnected-networks]
= Install on disconnected networks

You might need to install {product-title} on {ocp} clusters that are not connected to the Internet. The procedure to install on a disconnected hub requires some of the same steps as the connected installation.

You must download copies of the packages to access them during the installation, rather than accessing them directly from the network during the installation.

Before you get started, review the xref:../install/requirements.adoc#requirements-and-recommendations[Requirements and recommendations] section, then see the following documentation:

* <<disconnect-prerequisites,Prerequisites>>
* <<confirm-ocp-installation-2,Confirm your {ocp-short} installation>>
* <<installing-in-a-disconnected-environment,Installing in a disconnected environment>>

[#disconnect-prerequisites]
== Prerequisites 

You must meet the following requirements before you install {product-title}:

* {ocp} version 4.8 or later must be deployed in your environment, and you must be logged in with the command line interface (CLI). 

* You need access to the https://catalog.redhat.com/software/containers/search?p=1&application_categories_list=Container%20Platform%20%2F%20Management[catalog.redhat.com].
+
*Note:* For managing bare metal clusters, you must have {ocp-short} version 4.8 or later.
+
See the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/index[{ocp-short} version 4.10], https://docs.openshift.com/container-platform/4.10/welcome/index.html[{ocp-short} version 4.10].

* Your {ocp} CLI must be version 4.8 or later, and configured to run `oc` commands. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the CLI] for information about installing and configuring the Red Hat OpenShift CLI.
* Your {ocp} permissions must allow you to create a namespace. Installation fails without a namespace.
* You must have a workstation with Internet connection to download the dependencies for the operator.

[#confirm-ocp-installation-2]
== Confirm your {ocp-short} installation

* You must have a supported {ocp-short} version, including the registry and storage services, installed and working in your cluster. For information about {ocp-short} version 4.10, see the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/[{ocp-short} Documentation].

* When and if you are connected, run the `kubectl -n openshift-console get route` command to access the {ocp-short} web console. See the following example output:
+
----
openshift-console          console             console-openshift-console.apps.new-coral.purple-chesterfield.com                       console              https   reencrypt/Redirect     None
----

+
The console URL in this example is: `https:// console-openshift-console.apps.new-coral.purple-chesterfield.com`. Open the URL in your browser and check the result.

+
If the console URL displays `console-openshift-console.router.default.svc.cluster.local`, set the value for `openshift_master_default_subdomain` when you install {ocp-short}.

See xref:../install/cluster_size.adoc#sizing-your-cluster[Sizing your cluster] to learn about setting up capacity for your hub cluster.

[#installing-in-a-disconnected-environment]
== Installing in a disconnected environment

*Important:* You need to download the required images to a mirroring registry to install the operators in a disconnected environment. Without the download, you might receive `ImagePullBackOff` errors during your deployment.

Follow these steps to install {product-title-short} in a disconnected environment:

. Create a mirror registry. If you do not already have a mirror registry, create one by completing the procedure in the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/disconnected-installation-mirroring#mirroring-images-disconnected-install[Mirroring images for a disconnected installation] topic of the {ocp} documentation.

+
If you already have a mirror registry, you can configure and use your existing one.

+
**Note:** Ensure you follow the steps in the {ocp-short} documentation at https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/post-installation_configuration/index#post-install-mirrored-catalogs[Populating OperatorHub from mirrored Operator catalogs].

. Mirror operator catalogs. Ensure that the operator catalogs are mirrored by following the procedure in https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/disconnected-installation-mirroring#olm-mirror-catalog_installing-mirroring-installation-images[Mirroring Operator catalogs for use with disconnected clusters].

**Notes:** 

- If you are pruning packages from the existing Red Hat Operators index image, ensure that both the `advanced-cluster-management` and `multicluster-engine` packages are pruned. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/operators/index#olm-pruning-index-image_olm-restricted-networks[Filtering a SQLite-based index image] for more information.

- During the process for https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/disconnected-installation-mirroring#olm-mirror-catalog-manifests_installing-mirroring-installation-images[Generated manifests], you will generate a `catalogSource.yaml` file in the manifest directory. You will use this sample file when you configure the disconnected {olm}.

- For bare metal only, you need to provide the certificate information for the disconnected registry in your `install-config.yaml` file. To access the image in a protected disconnected registry, you must provide the certificate information so {product-title-short} can access the registry.

.. Copy the certificate information from the registry.
.. Open the `install-config.yaml` file in an editor.
.. Find the entry for `additionalTrustBundle: |`.
.. Add the certificate information after the `additionalTrustBundle` line. The content result is similar to the following example:

+
[source,yaml]
----
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  certificate_content
  -----END CERTIFICATE-----
sshKey: >-
----

+ 
*Important:* Additional mirrors for disconnected image registries are needed if the following Governance policies are required:

+
 ** Container security operator policy: The images are located in the source `registry.redhat.io/quay`.

 ** Compliance operator policy: The images are located in the source `registry.redhat.io/compliance`.

 ** Gatekeeper operator policy: The images are located in the source `registry.redhat.io/rhacm2`.

+
See the following example of mirrors lists for all three operators:

+
[source,yaml]
----
    - mirrors:
      - <your_registry>/rhacm2
      source: registry.redhat.io/rhacm2
    - mirrors:
      - <your_registry>/quay
      source: registry.redhat.io/quay
    - mirrors:
      - <your_registry>/compliance
      source: registry.redhat.io/compliance
----

. Save the `install-config.yaml` file.

. Create a YAML file that contains the `ImageContentSourcePolicy` with the name `rhacm-policy.yaml`. *Note:* If you modify this on a running cluster, it causes a rolling restart of all nodes.

+
[source,yaml]
----
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: rhacm-repo
spec:
  repositoryDigestMirrors:
  - mirrors:
    - mirror.registry.com:5000/rhacm2
    source: registry.redhat.io/rhacm2
----

. Apply the `ImageContentSourcePolicy` file by entering the following command:
+
----
oc apply -f rhacm-policy.yaml
----

. Enable the disconnected {olm} Red Hat Operators and Community Operators. {product-title-short} is included in the {olm} Red Hat Operator catalog.

. Configure the disconnected {olm} for the Red Hat Operator catalog. Follow the steps in the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/operators/administrator-tasks#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks] topic of the {ocp} documentation.

+
* For the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/operators/administrator-tasks#olm-creating-catalog-from-index_olm-restricted-networks[Adding a catalog source to a cluster] step, use the `catalogSource.yaml` file that you created when mirroring the operator catalog.

+
* If you use your own `catalogSource.yaml` file and the catalog source name is different from the expected `redhat-operator-index`, you will need to add the following annotation to the `MultiClusterHub` custom resource with your catalog source in place of `my-operator-catalog`.

+
[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    installer.open-cluster-management.io/mce-subscription-spec: '{"source": "my-operator-catalog"}'
----

Now that you have the image in the disconnected {olm}, continue to install {product-title-short} for Kubernetes from the {olm} catalog.

See xref:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online] for the required steps, or return to the xref:../install/install_overview.adoc#installing[Installing] overview.
