[#install-on-disconnected-networks]
= Install on disconnected networks

You might need to install {product-title} on Red Hat OpenShift Clusters that are not connected to the Internet.
The procedure to install on a disconnected hub requires some of the same steps as the connected installation.
You must download copies of the packages in order to access them during the installation, rather than accessing them directly from the network during the installation.

[#prerequisites-for-a-disconnected-installation]
== Prerequisites for a disconnected installation

You must meet the following requirements before you install {product-title}:

* Red Hat OpenShift Container Platform version 4.3, or later, must be deployed in your environment, and you must be logged into it with the command line interface (CLI).
See the https://docs.openshift.com/container-platform/4.3/welcome/index.html[OpenShift version 4.3 documentation] or https://docs.openshift.com/container-platform/4.4/welcome/index.html[OpenShift version 4.4 documentation].
* Your Red Hat OpenShift Container Platform CLI must be version 4.3, or later, and configured to run `oc` commands.
See https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_cli/getting-started-cli.html[Getting started with the CLI] for information about installing and configuring the Red Hat OpenShift CLI.
* Your Red Hat OpenShift Container Platform permissions must allow you to create a namespace.
* You must have a workstation with Internet connection to download the dependencies for the operator.

[#installing-red-hat-advanced-cluster-management-for-kubernetes-in-a-disconnected-environment]
== Installing Red Hat Advanced Cluster Management for Kubernetes in a disconnected environment

Follow these steps to install Advanced Cluster Management for Kubernetes in a disconnected environment:

. Create a mirror registry, if necessary.
+
If you do not already have a mirror registry, create one by completing the procedure in the https://docs.openshift.com/container-platform/4.4/installing/install_config/installing-restricted-networks-preparations.html#installing-restricted-networks-preparations[Creating a mirror registry for installation in a restricted network] topic of the Red Hat OpenShift Container Platform documentation.
+
If you already have a mirror registry, you can configure and use your existing one.
+

. Enable the disconnected Operator Lifecycle Manager (OLM) Red Hat Operators and Community Operators.
+
Advanced Cluster Management for Kubernetes is included in the OLM Red Hat Operator catalog.
+

. Configure the disconnected OLM for the Red Hat Operator catalog.
Follow the steps in the Using Operator Lifecycle Manager on restricted networks topic of the Red Hat OpenShift Container Platform documentation.
. Now that you have the image in the disconnected OLM, continue to install Advanced Cluster Management for Kubernetes from the OLM catalog.
See the steps in xref:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online] for the required steps.
