[#install-on-disconnected-networks]
= Install in disconnected network environments

You might need to install {product-title} on {ocp} clusters that are not connected to the Internet. To install on a disconnected hub cluster, perform the following steps in addition to the usual install or upgrade steps for the connected network environment.

*Required access:* You need cluster administration access for all installation tasks.

Before you get started, review
the xref:../install/requirements.adoc#requirements-and-recommendations[Requirements and recommendations] section. Details are provided in the following sections:

* <<disconnect-prerequisites,Prerequisites>>
* <<disconnect-confirm-ocp-installation,Confirm your {ocp-short} installation>>
* <<disconnect-configure-olm,Configure Operator Lifecycle Manager>> 
* <<disconnect-configure-icsp,Configure image content source policies>>
* <<disconnect-install-op-and-hub,Install the {product-title} operator and hub>>

[#disconnect-prerequisites]
== Prerequisites 

You must meet the following requirements before you install {product-title}:

* Since you are installing in a disconnected network enviornment, you need access to a local image registry to hold mirrored OLM catalogs and operator images. You probably already set up a local image registry when installing the {ocp-short} cluster in this enviornment, so you should be able to use the same local image registry.

* You must have a workstation that has access to both the Internet, as well as your local mirror registry. 

* A supported {ocp} version must be deployed in your environment, and you must be logged in with the command line interface (CLI). See the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/index[{ocp-short} version 4.11 install documentation] for information on installing {ocp}. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the CLI] for information about installing and configuring `oc` commands with the Red Hat OpenShift CLI.

* Review xref:../install/cluster_size.adoc#sizing-your-cluster[Sizing your cluster] to learn about setting up capacity for your hub cluster.

[#disconnect-confirm-ocp-installation]
== Confirm your {ocp-short} installation

* When and if you are connected, run the `oc -n openshift-console get route` command to access the {ocp-short} web console. See the following example output:

+
----
openshift-console          console             console-openshift-console.apps.new-coral.purple-chesterfield.com                       console              https   reencrypt/Redirect     None
----

Open the URL in your browser and check the result. If the console URL displays `console-openshift-console.router.default.svc.cluster.local`, set the value for `openshift_master_default_subdomain` when you install {ocp-short}.

== Confirm availability of a local image registry

*Best practice:* Use your existing mirror registry for the OLM operator related content.

Installing {product-title} in a disconnected environment involves the use of a local mirror image registry. Because you have already completed the installation of the {ocp-short} cluster in your disconnected environment, you already set up a mirror registry for use during the {ocp} cluster installation.

If you do not already have a local image registry, create one by completing the procedure that is described in https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/installing/disconnected-installation-mirroring#mirroring-images-disconnected-install[Mirroring images for a disconnected installation] of the {ocp} documentation.

[#disconnect-configure-olm]
== Configure Operator Lifecycle Manager

Because {product-title} is packaged as an operator, installing, or upgrading it is completed by using Operator Lifecycle Manager (OLM).

In disconnected environments, OLM cannot access the standard operator sources that Red Hat provided operators because they are hosted on image registries that are not accessible from a disconnected cluster. Instead, a cluster administrator can enable the installation and upgrade of operators in a disconnected environment by using mirrored image registries and operator catalogs.

To prepare your disconnected cluster for installing {product-title}, follow the procedure described in the topic
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/operators/index#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks]in the {ocp-short} documentation.

[#additional-requirements]
=== Additional requirements 

When performing the previous procedures, note the the follow requirements specific to {product-title}:

[#disconnect-include-acm-pkgs]
==== Include required operator packages in your mirror catalog 

* Include required operator packages in your mirror catalog
Red Hat provides the {product-title} operator in the Red Hat operators catalog, which is delivered by the
`registry.redhat.io/redhat/redhat-operator-index` index image. When you prepare your mirror of this catalog index image, you can choose to either mirror the entire catalog as provided by Red Hat, or you can mirror a subset that contains only the operator packages that you intend to use.

If you are creating a full mirror catalog, no special considerations are needed as all of the packages required to install {product-title} are included. However, if you are creating a partial or filtered mirrored catalog, for which you identify particular packages to be included, you need to include the following package names in your list:

+
* `advanced-cluster-manager`
* `multicluster-engine`

* Use one the two mirroring procedures. 

+
- If you are creating the mirrored catalog or registry by using the OPM utility, `opm index prune`, include the following package names in the value of the `-p` option as shown in the example:

....
opm index prune \
   -f registry.redhat.io/redhat/redhat-operator-index:v4.10 \
   -p advanced-cluster-management,multicluster-engine \
   -t myregistry.example.com:5000/mirror/my-operator-index:v4.10
....

+
- If instead you are populating the mirrored catalog or registry by using the `oc-mirror` plugin, include the following package names in the packages list portion of your `ImageSetConfiguration`, as shown in the example:

+
[source,yaml]
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
     imageURL: myregistry.example.com:5000/mirror/oc-mirror-metadata
mirror:
  platform:
    channels:
    - name: stable-4.10
      type: ocp
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
    packages:
    - name: advanced-cluster-management
    - name: multicluster-engine
  additionalImages: []
  helm: {}
----  

[#config-olm-registry]
==== Configure OLM to use your mirror registry

When you have populated a local mirror registry with the previous packages that are required for installing {product-title}, complete the steps that are described in the topic https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/operators/index#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks] to make your mirror registry and catalog available on your disconnected cluster which include the following steps:

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/operators/index#olm-restricted-networks-operatorhub_olm-restricted-networks[Disabling the default OperatorHub sources]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/operators/index#olm-mirror-catalog_olm-restricted-networks[Mirroring the Operator catalog]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/operators/index#olm-creating-catalog-from-index_olm-restricted-networks[Adding a catalog source for your mirrored catalog]

[#note-source-name]
==== Note the catalog source name

As described in the procedures in the {ocp} documentation, you will add a catalog source to your disconnected cluster by adding a `CatalougSource` resource into the `openshift-marketplace` namespace by using a YAML file similar to the following example. Take note of the value of the `metadata.name` field, which you need later:

[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-mirror-catalog-source
  namespace: openshift-marketplace
spec:
  image: myregistry.example.com:5000/mirror/my-operator-index:v4.10
  sourceType: grpc
----  
 
You need the `metadata.name` field value for the annation in the `MulticlusterHub` resource that you create later in this procedure.

[#verify-required-package]
== Verify required packages are available

Operator Lifecycle Manager will poll catalog sources for available packages on a regular (timed) interval. After OLM polls the catalog source for your mirrored catalog, you can verify that the required packages are available from on your disconnected cluster by querying the available 
`PackageManifest` resources.

Run the following command, directed at your disconnected cluster:
....
oc -n openshift-marketplace get packagemanifests 
....

The list that is displayed should include entries showing the following packages as being supplied by 
the catalog source for your mirror catalog:

* `advanced-cluster-manager`
* `multicluster-engine`

[#disconnect-configure-icsp]
== Configure image content source policies

In order to have your cluster obtain container images for the {product-title} operator from your mirror registry,rather than from the internet-hosted registries, you must configure an `ImageContentSourcePolciy` on your disconnected cluster to redirected image references to your
mirror registry.  

If you mirrored your catalog using `oc adm catalog mirror` command, the needed image content source policy configuration will be in the `imageContentSourcePolicy.yaml` file inside of the `manifests-*`directory created by that command. 

If, instead, you used the oc-mirror plugin to mirror your catalog, the `imageContentSourcePolicy.yaml` file will instead be within the `oc-mirror-workspace/results-*` directory create by the oc-mirror plugin.

In either case, you can apply the policies to your disconnected command using an `oc apply` or `oc replace`
command such as:

....
oc replace -f ./<path>/imageContentSourcePolicy.yaml
....

The required image content source policy statements can vary based on how you created your
mirror registry, but will be similar to this example:

[source,yaml]
----
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - myregistry.example.com:5000/rhacm2
    source: registry.redhat.io/rhacm2
  - mirrors:
    - myregistry.example.com:5000/multicluster-engine
    source: registry.redhat.io/multicluster-engine
  - mirrors:
    - myregistry.example.com:5000/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - myregistry.example.com:5000/redhat
    source: registry.redhat.io/redhat
----

[#disconnect-install-op-and-hub]
== Install the {product-title} operator and hub

After you have configured OLM and {ocp} as described in earlier sections, you can install {product-title}
by using either the OperatorHub console or a CLI, following the same flow as is described in topic
xref:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online].

*Important:* Creating the `MulticlusterHub` resource is the beginning of the installation process of your hub cluster.

Because operator installation on a cluster requires the use of a non-default catalog source for the mirror catalog, a special annotation is needed in the `MulticlusterHub` resource to provide the name of the mirror catalog source to the operator.  The following example displays the required 
`mce-subscription-spec` annotation:

[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
   namespace: open-cluster-management
   name: hub
   annotations:
      installer.open-cluster-management.io/mce-subscription-spec: '{"source": "my-mirror-catalog-source"}'
spec: {}
----

If you are creating the resource with a CLI, include the `mce-subscription-spec` annotation in the YAML that you will use with the `oc apply` command to create the `MulticlusterHub` resource.

If you are creating the resource using the OPeratorHub console, switch to the YAML view and insert the annotation as previously shown.

*Important:* There is no field in the OperatorHub console for the annotation in the the _Field view_ panel to create the `MulticlusterHub`.

