[#installing]
= Installing and upgrading

Before you install, review the required hardware and system configuration for each product. You can install online on Linux with a supported version of {ocp}.

. You must have a supported version of {ocp-short}. For example, you can use Red Hat OpenShift Service on AWS, or Red Hat OpenShift Dedicated.

. You must install the {mce}.

FIPS notice: If you do not specify your own ciphers in `spec.ingress.sslCiphers`, then the `multiclusterhub-operator` provides a default list of ciphers. If you upgrade and want FIPS compliance, remove the following two ciphers from the `multiclusterhub` resource: `ECDHE-ECDSA-CHACHA20-POLY1305` and `ECDHE-RSA-CHACHA20-POLY1305`.

Access the link:https://access.redhat.com/articles/7027073/[Support matrix] to learn about hub cluster and managed cluster requirements and support.

Installing {product-title} sets up a multi-node cluster production environment. You can install {product-title} in either standard or high-availability configurations. View the following documentation for more information about the installation procedure:

* xref:../install/cluster_size.adoc#sizing-your-cluster[Sizing your cluster]
* xref:../install/perform_scale.adoc#performance-and-scalability[Performance and scalability]
* xref:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online]
* xref:../install/install_disconnected.adoc#install-on-disconnected-networks[Install on disconnected networks]
* xref:../install/adv_config_install.adoc#advanced-config-hub[MultiClusterHub advanced configuration]
* xref:../install/upgrade_hub.adoc#upgrading[Upgrading]
* xref:../install/upgrade_hub.adoc#upgrading-disconnected[Upgrading in a disconnected network environment]
* xref:../install/upgrade_cluster_disconnected_policies.adoc#upgrading-disconnected-clusters-policies[Upgrading disconnected clusters using policies]
* xref:../install/uninstall.adoc#uninstalling[Uninstalling]
