[#installing]
= Installing

Learn how to install and uninstall {product-title}. Before you install {product-title}, review the required hardware and system configuration for each product. You can install the {product-title} online on Linux with a supported version of {ocp}.

. You must have a supported version of {ocp-short} or Red Hat OpenShift Dedicated installed and configured.
. You must install the operator for {product-title} from the catalog.

Installing {product-title} sets up a multi-node cluster production environment. You can install {product-title} in either standard or high-availability configurations. After you install and deploy the {product-title}, view the following documentation for more information:

* xref:..install/#requirements-and-recommendations[Requirements and recommendations]
* xref:../install/plan_capacity#sizing-your-cluster[Sizing your cluster]
* xref:..install/perform_scale#resizing-a-cluster[Performance and scalability]
* xref:..install/install_connected.adoc#installing-while-connected-online[Installing while connected online]
* xref:..install/custom_resource.adoc#managedclustersets[ManagedClusterSets]
* xref:..install/ansible_job.adoc#creating-an-ansible-job-for-a-managed-cluster[Creating an AnsibleJob for a managed cluster]
* xref:..install/upgrade_cluster.adoc#upgrading-your-cluster[Upgrading your cluster]
* xref:..install/remove_managed_cluster.adoc#remove-managed-cluster[Removing a cluster from management]

