:_mod-docs-content-type: PROCEDURE

[#prepare-install-acm]
= Preparing for {acm-short} installation

[role="_abstract"]
Install {acm-short} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. 

* Because {acm-short} depends on and uses the {mce-short}, after you create the `MultiClusterHub` resource during installation, the {acm-short} operator automatically installs the {mce-short} operator and creates the `MultiClusterEngine` resource. 

* You must have an Internet connection to access the dependencies for the operator. 

* To import, you must use the `stable-2.0` channel of the klusterlet operator for {product-version}.

* *Required access:* Cluster administrator

* *{ocp-short} Dedicated environment required access:* You need `cluster-admin` permissions. By default the `dedicated-admin` role does not have the required permissions to create namespaces in the {ocp-short} Dedicated environment. 

* For full support information, see the link:https://access.redhat.com/articles/7133095[{acm-short} Support Matrix] and the link:https://access.redhat.com/support/policy/updates/advanced-cluster-management[Lifecycle and update policies for {acm-short}].

* By default, the hub cluster components are installed on worker nodes of your {ocp-short} cluster without any additional configuration. You can install the hub cluster on worker nodes by using the {ocp-catalog} console, or by using the {ocp-short} command-line interface.

* If you have configured your {ocp-short} cluster with infrastructure nodes, you can install the hub cluster on those infrastructure nodes by using the {ocp-short} command-line interface with additional resource parameters. See the _Installing the {acm-short} hub cluster on infrastructure node_ section for more details.

* If you plan to import Kubernetes clusters that are not {ocp-short} or {acm-short} clusters, you need to configure an image pull secret. 

* For information on how to configure advanced configurations, see options in the xref:../install/adv_config_install.adoc#advanced-config-hub[MultiClusterHub advanced configuration] section of the documentation. 

* If you previously installed {acm-short} on a cluster, then uninstalled, you need to follow the clean up procedure to remove artifacts. See xref:../install/cleanup_reinstall.adoc#cleanup-reinstall[Cleaning up artifacts before reinstalling] and follow the procedure.

.Procedure

. Ensure that your {ocp} cluster can access the {acm-short} operator in the {ocp-catalog} console. 

. Ensure that your {ocp-short} cluster is supported by your current {acm-short} version. See the link:https://access.redhat.com/articles/7133095[{acm-short} Support Matrix] for more information about the required {ocp-short} versions for each {acm-short} version.

. Access the catalog at link:https://catalog.redhat.com/software/containers/search?p=1&application_categories_list=Container%20Platform%20%2F%20Management[catalog.redhat.com].

. Install a supported version of {ocp-short} and the {ocp-short} command-line interface. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/installation_overview/index[{ocp-short} installing].

. Configure to run `oc` commands. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the CLI] for information.
.  Ensure that your permissions allow you to create a namespace. Without a namespace, installation fails.

. *Optional:* Install in a {ocp-short} Dedicated environment. You must have the {ocp-short} Dedicated environment configured and running and you must have `cluster-admin` authority to the {ocp-short} Dedicated environment where you are installing the hub cluster.

. Confirm your installation. Verify that a {acm-short} hub cluster is not already installed on your {ocp-short} cluster. You cannot have more than one hub cluster. You can only have one single {acm-short} hub cluster installation on each {ocp-short} cluster. Continue with the following steps if there is no {acm-short} hub cluster installed:

. To ensure that the {ocp-short} cluster is set up correctly, access the {ocp-short} web console with the following command:

+
[source,bash]
----
oc -n openshift-console get route
----

+
See the following example output:

+
[source,bash]
----
openshift-console console console-openshift-console.apps.new-coral.purple-chesterfield.com               
console   https   reencrypt/Redirect     None
----

. Open the URL in your browser and check the result. If the console URL displays `console-openshift-console.router.default.svc.cluster.local`, set the value for `openshift_master_default_subdomain` when you install {ocp-short}. See the following example of a URL: `https://console-openshift-console.apps.new-coral.purple-chesterfield.com`.

.Next steps

You can proceed to install {acm-short} from the console or the CLI. *Note:* For installing the {acm-short} hub cluster on infrastructure nodes, see _Configuring infrastructure nodes for {acm-short}_.
