[#requirements-and-recommendations]
= Requirements and recommendations

Before you install {product-title}, review the system configuration requirements and settings.

[#supported-operating-systems-and-platforms]
== Supported operating systems and platforms

See the following table for supported operating systems:

|===
| Platform | Operating system | {ocp} version

| Linux x86_64
| Red Hat Enterprise Linux 7.6, or later
| 4.4.3 or later, 4.5.2 or later (bare metal features only supported on 4.5 or later), 4.6.1 or later
|===

[#supported-browsers]
== Supported browsers

You can access the {product-title-short} console from Mozilla Firefox, Google Chrome, Microsoft Edge, and Safari.
See the following versions that are tested and supported:

|===
| Platform | Supported browsers

| Microsoft Windows
| Microsoft Edge - 44 or later, Mozilla Firefox - 82.0 or later, Google Chrome - Version 86.0 and later

| Linux
| Mozilla Firefox - 82.0 and later, Google Chrome - Version 86.0 and later

| macOS
| Mozilla Firefox - 82.0 and later, Google Chrome - Version 86.0 and later, Safari - 14.0 and later
|===

See the https://access.redhat.com/articles/5486041[{product-title} 2.1 Support Matrix] for additional information.

[#network-configuration]
== Network configuration

Configure your network settings to allow the following connections:

Hub cluster:

* Outbound connectivity to the API of the cloud provider
* Outbound connectivity to the Kubernetes API server of the provisioned managed cluster on port 6443
* Outbound connectivity from the hub cluster to the channel source, including GitHub, Object Store, and Helm repository. This is only required when you are using application lifecycle to connect to these sources.
* Outbound and inbound connectivity to the `WorkManager` service route on the managed cluster on port 443
* Inbound connectivity to the kube API server of the hub cluster from the managed cluster on port 6443
* Inbound connectivity for post-commit hook from GitHub to the hub cluster. This setting is only required when you use certain application management functions.

Managed cluster:

* Inbound connectivity to the Kubernetes API server from the hub cluster on port 6443
* Inbound connectivity to `WorkManager` service endpoint from the hub cluster on port 443
* Outbound connectivity to the Kubernetes API server of the hub cluster on port 6443
* Outbound connectivity from the managed cluster to the channel source, which includes GitHub, Object Store, and Helm repository. This is only required when you are using application lifecycle to connect to these sources.

See the https://access.redhat.com/articles/5486041[{product-title} 2.1 Support Matrix] for additional information.
