[#requirements-and-recommendations]
= Requirements and recommendations
:doctype: book

Before you install {product-title}, review the system configuration requirements and settings.

[#supported-operating-systems-and-platforms]
== Supported operating systems and platforms

See the following table for supported operating systems:

|===
| Platform | Operating system | {ocp-short} version

| Linux x86_64
| Red Hat Enterprise Linux 7.6, or later
| 4.3.18 or later, 4.4.4 or later, 4.5.2 or later (bare metal features only supported on 4.5, or later)
|===

[#supported-browsers]
== Supported browsers

You can access the {product-title} console from Mozilla Firefox, Google Chrome, Microsoft™ Edge, and Safari.
See the following versions that are tested and supported:

|===
| Platform | Supported browsers

| Microsoft Windows
| Microsoft Edge - latest, Mozilla Firefox - 74.0 or later, Google Chrome - Version 80.0 and later

| Linux
| Mozilla Firefox - 74.0 and later, Google Chrome - Version 80.0 and later

| macOS
| Mozilla Firefox - 74.0 and later, Google Chrome - Version 80.0 and later, Safari - 13.0.5 and later
|===

See the https://access.redhat.com/articles/5248271[{product-title} {product-version} Support matrix] for additional information.

[#Network configuration]
= Network configuration

Configure your network settings to allow the following connections:

Hub cluster:
* Outbound connectivity to cloud provider's API.
* Outbound connectivity to the Kubernetes API server of the provisioned `ManagedCluster` on port 6443.
* Outbound connectivity from the Hub to the channel source, including Github, Object Store, and Helm repository. This is only required when you are using application lifecycle to connect to these sources.
* Outbound and inbound connectivity to the `WorkManager` service route on the ManagedCluster on port 443.
* Inbound connectivity to the hub cluster's kube API server from the `ManagedCluster` on port 6443.
* Inbound connectivity for post-commit hook from GitHub to the Hub. This setting is only required when you use certain application management functions.


Managed cluster:
* Inbound connectivity to the Kubernetes API server from the hub cluster on port 6443.
* Inbound connectivity to `WorkManager` service endpoint from the hub cluster on port 443.
* Outbound connectivity to the hub cluster's Kubernetes API server on port 6443.
* Outbound connectivity from the Hub to channel source, including Github, Object Store, and Helm repository. This is only required when you are using application lifecycle to connect to these sources.
