[#requirements-and-recommendations]
= Requirements and recommendations

Before you install {product-title}, review the following system configuration requirements and settings:

* <<supported-operating-systems-and-platforms,Supported operating systems and platforms>>
* <<supported-browsers,Supported browsers>>

[#supported-operating-systems-and-platforms]
== Supported operating systems and platforms

To see recent information about hub cluster and managed cluster platforms, refer to the https://access.redhat.com/articles/6968787[{product-title-short} {product-version} Support matrix].


[#supported-browsers]
== Supported browsers

You can access the {product-title-short} console from Mozilla Firefox, Google Chrome, Microsoft Edge, and Safari.
See the following versions that are tested and supported:

|===
| Platform | Supported browsers

| Microsoft Windows
| Microsoft Edge - 44 or later, Mozilla Firefox - 82.0 or later, Google Chrome - Version 86.0 and later

| Linux
| Mozilla Firefox - 82.0 and later, Google Chrome - Version 86.0 and later

| macOS
| Mozilla Firefox - 82.0 and later, Google Chrome - Version 86.0 and later, Safari - 14.0 and later
|===