[#uninstalling]
= Uninstalling

When you uninstall {acm}, you see two different levels of the uninstall process: A _custom resource removal_ and a _complete operator uninstall_. The uninstall process can take up to 20 minutes and the process includes removing resources.

- The custom resource removal is the first and most basic type of uninstall that removes the custom resource of the `MultiClusterHub` instance, but leaves other required operator resources. This level of uninstall is helpful if you plan to reinstall with the same settings and components.


- The complete operator uninstall is the second level process that removes most operator components, excluding components such as custom resource definitions. When you continue with this step, it removes all of the components and subscriptions that were not removed with the custom resource removal. After this uninstall, you must reinstall the operator before reinstalling the custom resource.

[#prerequisite-detach]
== Prerequisites

* If you have managed clusters attached, you need to detach them. *Note:* This does not include the `local-cluster`, which is your self-managed hub cluster. For more information about detaching clusters, see the _Removing a cluster from management_ section in link:../clusters/cluster_lifecycle/create_intro.adoc#create-intro[Cluster creation introduction]. 

* If you use Discovery, you need to disable the function. From the console, go to the `Discovered Clusters` table and click *Disable cluster discovery*. Confirm that you want to remove the service. You can also use the terminal to disable Discovery with the following command:

+
[source,bash]
----
oc delete discoveryconfigs --all --all-namespaces
----

* If you use Agent Service Configuration, disable and remove the `AgentServiceConfig` resource.Complete the following steps:

.. Log in to your hub cluster.

.. Delete the `AgentServiceConfig` custom resource by entering the following command:

+
[source,bash]
----
oc delete agentserviceconfig --all
----

* If you use Observability, disable and remove the `MultiClusterObservability` custom resource. *Note:* Your object storage is not affected after you remove the Observability service.
See the following procedure:

.. Log in to your hub cluster.

.. Delete the `MultiClusterObservability` custom resource by entering the following command:

+
[source,bash]
----
oc delete mco observability
----

+
- To remove `MultiClusterObservability` custom resource with the console, see the following procedure:

.. If the `MultiClusterObservability` custom resource is installed, select the tab for _MultiClusterObservability_.

.. Select the *Options* menu for the `MultiClusterObservability` custom resource. 

.. Select *Delete MultiClusterObservability*. 

+
When you delete the resource, the pods in the `open-cluster-management-observability` namespace on {acm-short} hub cluster, and the pods in `open-cluster-management-addon-observability` namespace on all managed clusters are removed.

[#removing-a-multiclusterhub-instance-by-using-commands]
== Removing _multiclusterhub_ resources by using commands

Delete the `MultiClusterHub` custom resource and remove artifacts.

. If you have not already, ensure that your {ocp-short} CLI is configured to run `oc` commands. See link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the OpenShift CLI] in the {ocp-short} documentation for more information about how to configure the `oc` commands. 

. Change to your project namespace by entering the following command. Replace _namespace_ with the your project namespace:

+
[source,bash]
----
oc project <namespace>
----

. Enter the following command to delete the `MultiClusterHub` custom resource:

+
[source,bash]
----
oc delete multiclusterhub --all
----

. To view the progress, enter the following command: 

+
[source,bash]
----
oc get mch -o yaml
----

. Remove any potential remaining artifacts by running the clean-up script. Run this clean-up script if you plan to reinstall with an older version of {acm-short} on the same cluster. 

.. Copy the following script into a file:

+
[source,bash]
----
#!/bin/bash
ACM_NAMESPACE=<namespace>
oc delete mch --all -n $ACM_NAMESPACE
oc delete apiservice v1.admission.cluster.open-cluster-management.io v1.admission.work.open-cluster-management.io
oc delete clusterimageset --all
oc delete clusterrole multiclusterengines.multicluster.openshift.io-v1-admin multiclusterengines.multicluster.openshift.io-v1-crdview multiclusterengines.multicluster.openshift.io-v1-edit multiclusterengines.multicluster.openshift.io-v1-view open-cluster-management:addons:application-manager open-cluster-management:admin-aggregate open-cluster-management:cert-policy-controller-hub open-cluster-management:cluster-manager-admin-aggregate open-cluster-management:config-policy-controller-hub open-cluster-management:edit-aggregate open-cluster-management:iam-policy-controller-hub open-cluster-management:policy-framework-hub open-cluster-management:view-aggregate
oc delete crd klusterletaddonconfigs.agent.open-cluster-management.io placementbindings.policy.open-cluster-management.io policies.policy.open-cluster-management.io userpreferences.console.open-cluster-management.io discoveredclusters.discovery.open-cluster-management.io discoveryconfigs.discovery.open-cluster-management.io
oc delete mutatingwebhookconfiguration ocm-mutating-webhook managedclustermutators.admission.cluster.open-cluster-management.io multicluster-observability-operator
oc delete validatingwebhookconfiguration channels.apps.open.cluster.management.webhook.validator application-webhook-validator multiclusterhub-operator-validating-webhook ocm-validating-webhook multicluster-observability-operator multiclusterengines.multicluster.openshift.io
----

+
Replace `<namespace>` in the script with the name of the namespace where {acm-short} was installed.

+
*Important:* Ensure that you specify the correct namespace, as the namespace is cleaned out and deleted.

+
.. Run the script to remove any possible artifacts that remain from the previous installation. If there are no remaining artifacts, a message is returned that no resources were found.

Next you can uninstall the`MultiClusterHub` operator. *Note:* If you plan to reinstall the same {product-title-short} version, you do not need to uninstall the operator.

+
. Enter the following commands to delete the `ClusterServiceVersion` and `Subscription` in the namespace where it is installed. Replace the `2.x.0` value with the selected release:

+
[source,bash]
----
oc get csv
NAME                                 DISPLAY                                      VERSION   REPLACES   PHASE
advanced-cluster-management.v2.x.0   Advanced Cluster Management for Kubernetes   2.x.0                Succeeded

oc delete clusterserviceversion advanced-cluster-management.v2.x.0

oc get sub
NAME                        PACKAGE                       SOURCE                CHANNEL
acm-operator-subscription   advanced-cluster-management   acm-custom-registry   release-2.x

oc delete sub acm-operator-subscription
----
+
*Note:* The name of the subscription and version of the CSV might differ.

[#deleting-the-components-by-using-the-console]
== Deleting the components by using the console

When you use the {ocp} console to uninstall, you remove the `MultiClusterHub` resource to delete the object. Wait for the status, then delete the operator. Complete the following steps to uninstall by using the console:

. In the {ocp-short} console navigation, select *Operators* > *Installed Operators* > *Advanced Cluster Manager for Kubernetes*.

. Remove the `MultiClusterHub` custom resource.
.. Select the tab for _Multiclusterhub_.

.. Select the _Options_ menu for the `MultiClusterHub` custom resource.

.. Select *Delete MultiClusterHub*.

. Run the clean-up script according to the procedure in xref:../install/uninstall.adoc#removing-a-multiclusterhub-instance-by-using-commands[Removing a MultiClusterHub instance by using commands].
+
*Note:* If you plan to reinstall the same {acm-short} version, you can skip the rest of the steps in this procedure and reinstall the custom resource.

. Navigate to *Installed Operators*.

. Remove the _{acm-short}_ operator by selecting the _Options_ menu and selecting *Uninstall operator*.