[#uninstalling]
= Uninstalling

When you uninstall {product-title}, there are two different levels of the process.

The first level is a custom resource removal.
It is the most basic type of unistallation that removes the custom resource of the MultiClusterHub instance, but leaves other required components.
This level of uninstallation is helpful if you plan another installation that uses the same settings and components of the one that you are removing.
Your time to install the next version is reduced when you have all of the other components already installed.

The second level is a more complete uninstallation, except for a few items, like custom resource definitions.
This adds the removal of other required components and settings to the items that are removed.
When you continue with this step, it removes all of the components and subscriptions that were not removed with the custom resource removal.
If you complete this level of uninstallation, you must reinstall the operator before reinstalling the custom resource.

*Important:* Before you uninstall the {product-title-short} hub cluster, you must detach all of the clusters that are managed by that hub cluster. See, link:../troubleshooting/trouble_uninstall_detach.adoc[Troubleshooting failed uninstallation because resources exist] for the work around.

[#removing-a-multiclusterhub-instance-by-using-commands]
== Removing a MultiClusterHub instance by using commands

*Important:* Before you remove the MultiClusterHub instance, you must disable the observability custom resource, if it is running. See link:../observability/observability_install.adoc#disable-observability[Disable observability] for more information.

. Change to your project namespace by entering the following command:
+
----
oc project <namespace>
----
+
Replace _namespace_ with the name of your project namespace.

. Disable and remove the MultiClusterObservability custom resource, if it is running.

.. Log in to your hub cluster.

.. Delete the MultiClusterObservability custom resource by entering the following command:
+
----
oc delete mco observability
----
+
When you delete the resource, the pods in the `open-cluster-management-observability` namespace on {product-title-short} hub cluster, and the pods in `open-cluster-management-addon-observability` namespace on all managed clusters are removed. 
+
*Important*: Your object storage is not affected after you remove the observability service.

. Enter the following command to remove the MultiClusterHub custom resource:
+
----
oc delete multiclusterhub --all
----
+
It might take up to 20 minutes to complete the uninstall process. You can view the progress by entering the following command: 
+
----
oc get mch -o yaml
----

. Remove any remaining artifacts by running the clean-up script.

.. Install the Helm CLI binary version 3.2.0, or later, by following the instructions at https://helm.sh/docs/intro/install/[Installing Helm].

.. Ensure that your {ocp-short} CLI is configured to run `oc` commands. See https://docs.openshift.com/container-platform/4.5/cli_reference/openshift_cli/getting-started-cli.html[Getting started with the CLI] in the {ocp-short} documentation for more information about how to configure the `oc` commands. 

.. Copy the following script into a file:
+
----
#!/bin/bash
ACM_NAMESPACE=<namespace>
oc delete mch --all -n $ACM_NAMESPACE
helm ls --namespace $ACM_NAMESPACE | cut -f 1 | tail -n +2 | xargs -n 1 helm delete --namespace $ACM_NAMESPACE
oc delete apiservice v1.admission.cluster.open-cluster-management.io v1beta1.webhook.certmanager.k8s.io v1.admission.cluster.open-cluster-management.io v1.admission.work.open-cluster-management.io
oc delete clusterimageset --all
oc delete configmap -n $ACM_NAMESPACE cert-manager-controller cert-manager-cainjector-leader-election cert-manager-cainjector-leader-election-core
oc delete consolelink acm-console-link
oc delete crd klusterletaddonconfigs.agent.open-cluster-management.io placementbindings.policy.open-cluster-management.io policies.policy.open-cluster-management.io userpreferences.console.open-cluster-management.io
oc delete mutatingwebhookconfiguration cert-manager-webhook-v1alpha1
oc delete oauthclient multicloudingress
oc delete rolebinding -n kube-system cert-manager-webhook-webhook-authentication-reader
oc delete scc kui-proxy-scc
oc delete validatingwebhookconfiguration cert-manager-webhook-v1alpha1 
----
+
Replace `<namespace>` in the script with the name of the namespace where {product-title-short} was installed. Ensure that you specify the correct namespace, as the namespace is cleaned out and deleted. 

.. Run the script to remove the artifacts from the previous installation. 
+
*Tip:* If you plan to reinstall a new version and want to keep your other information, you can skip the rest of the steps in this procedure and reinstall.

. Enter the following command to remove all of the related components and subscriptions:
+
----
oc delete subs --all
----

. Enter the following command to delete the ClusterServiceVersion:
+
----
oc delete clusterserviceversion --all
----

[#deleting-the-components-by-using-the-console]
== Deleting the components by using the console

When you use the {ocp} console to uninstall, you remove the operator.
Complete the following steps to uninstall by using the console:

. In the {ocp-short} console navigation, select *Operators* > *Installed Operators* > *Advanced Cluster Manager for Kubernetes*.
. Remove the MultiClusterObservability custom resource, if installed.
.. If the MultiClusterObservability custom resource is installed, select the tab for _MultiClusterObservability_.
.. Select the _Options_ menu for the MultiClusterObservability custom resource. 
.. Select *Delete MultiClusterObservability*. 
. Remove the MultiClusterHub custom resource.
.. Select the tab for _Multiclusterhub_.
.. Select the _Options_ menu for the MultiClusterHub custom resource.
.. Select *Delete MultiClusterHub*.
+
It might take up to 20 minutes to complete the uninstall process.
. Run the clean-up script according to the procedure in xref:../install/uninstall.adoc#removing-a-multiclusterhub-instance-by-using-commands[Removing a MultiClusterHub instance by using commands].
+
*Tip:* If you plan to reinstall a new version and want to keep your other information, you can skip the rest of the steps in this procedure and reinstall.

. Navigate to *Installed Operators*.
. Remove the _Red Hat Advanced Cluster Management_ operator by selecting the _Options_ menu and selecting *Uninstall operator*.
