:_mod-docs-content-type: PROCEDURE

[#upgrading-hub]
= Upgrading your hub cluster

[role="_abstract"]
You control your {acm} upgrades by using the operator subscription settings in the {ocp} console. 

*Required access:* {ocp-short} administrator

.Prerequisites

* Before you upgrade, see xref:../upgrade_considerations.adoc#upgrade-considerations[Upgrade considerations for your hub cluster] to understand the upgrade requirements, limitations, and the potential impacts of an upgrade.

* Before you upgrade {ocp-short} on your {acm-short} hub cluster, ensure that you choose the {ocp-short} version that is supported by your current {acm-short} version. See the Support Matrix in link:https://access.redhat.com/articles/7133095[{acm-short} Support Matrix] for more information about the required {ocp-short} versions for each {acm-short} version.

.Procedure

. Log in to your {ocp-catalog}.

. In the {ocp-short} navigation, select *Ecosystem* > *Installed operators*.

. Select the *{acm}* operator.

. Select the _Subscription_ tab to edit the subscription settings.

. Ensure that the _Upgrade Status_ is labeled _Up to date_. This status indicates that the operator is at the latest level that is available in the selected channel. If the _Upgrade Status_ indicates that there is an upgrade pending, complete the following steps to update it to the latest minor release that is available in the channel:

.. Click the *Manual* setting in the _Approval_ field to edit the value. 

.. Select *Automatic* to enable automatic updates. 

.. Select *Save* to commit your change. 

.. Wait for the automatic updates to be applied to the operator. The updates automatically add the required updates to the latest version in the selected channel. When all of the updated updates are complete, the _Upgrade Status_ field indicates an `Up to date` status.
+
*Note:* It can take up to 10 minutes for the `MultiClusterHub` custom resource to finish upgrading. You can check whether the upgrade is still in process by entering the following command:

+
[source,bash]
----
oc get mch
----

+
While it is upgrading, the `Status` field shows the `Updating` status. After the upgrade is complete, the `Status` field shows the `Running` status.

. When the _Upgrade Status_ is `Up to date`, click the value in the _Channel_ field to edit the channel.  

. Select the channel for the next available feature release, but do not attempt to skip a channel.

+
**Important:** The {olm} `operatorcondition` resource checks for previous upgrades during the current upgrade process and prevents skipping versions. You can check that same resource status to see if the upgradable status is `true` or `false`.

. Click *Save* to save your changes.

. Wait for the automatic upgrade to complete. After the upgrade to the next feature release completes, the updates to the latest patch releases within the channel are deployed.

. If you have to upgrade to a later feature release, repeat steps 7-9 until your operator is at the latest level of the desired channel. Make sure that all of the patch releases are deployed for your final channel.   

. *Optional:* You can set your _Approval_ setting to *Manual*, if you want your future updates within the channel to require manual approvals.

. If you performed a skip-level upgrade, see the following sub steps to verify your upgrade:
.. Verify that the `csv` version from the previous release, for instance, `2.13` (EUS), is replaced with the upgraded version, for instance, `2.15` (EUS).
.. Verify that the `MultiClusterHub` instance `status.currentVersion` specification value is set at `2.15` and matches the `desiredVersion` status, which is also set at `2.15`.

For more information about upgrading your operator, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/operators/index[Operators] in the {ocp-short} documentation.

. *Optional:* If you are link:../clusters/cluster_lifecycle/cluster_pool_intro.adoc#managing-cluster-pools[Managing cluster pools (Technology Preview)], you need further configuration to stop automatic management of these cluster pools after upgrade.

. Set `cluster.open-cluster-management.io/createmanagedcluster: "false"` in the `ClusterClaim` `metadata.annotations`. 

.Results

All existing cluster claims are automatically imported when the product is upgraded unless you change this setting.
