:_mod-docs-content-type: PROCEDURE

[#upgrading-disconnected]
= Upgrading in a disconnected network environment

[role="_abstract"]
See the steps and information to update {acm-short} in a disconnected network environment. This information follows the updating procedure in xref:../install/upgrade_hub.adoc#upgrading-hub[Upgrading your hub cluster]. 

* The process starts by changing the upgrade channel in your {olm} subscription for {acm} to the channel for the new release. 

* Because of the special characteristics of the disconnected environment, you need to address the mirroring requirements before changing the update channel to start the upgrade process. 

* You might encounter important information that is related to the interdependency between the {acm-short} and {mce-short}. See xref:../install/install_disconnected.adoc#install-on-disconnected-networks[Installing in disconnected network environments] for consideration during install or upgrade.

.Procedure

. Ensure that required packages are updated in your mirror catalog.

.. Update your mirror catalog and registry to pick up the updated versions of the operator packages.During installation, or during a previous update, you created a mirror catalog and a registry that contains operator packages and images that are needed to install {acm-short} in a disconnected network environment. 

.. Ensure that your mirror catalog and registry include the following operator packages in the list of operators to be included or updated:

+
* `advanced-cluster-manager`
* `multicluster-engine`

. Verify your `MutliclusterHub` resource instance. During installation or a previous update, you created an instance of the `MulticlusterHub` resource, and due to the disconnected environment, you added a `mce-subscription-spec` annotation to that resource.

+
If you updated your mirror catalog and registry and got an updated catalog on the {ocp-short} cluster through a `CatalogSource` with the same name as the one that you previously used, you do not need to update your `MulticlusterHub` resource to update the `mce-subscriptino-spec` annotation.

+
If your mirrored catalog and registry resulted in a newly named `CatalogSource` being created, update the `mce-subscription-spec` annotation in your `MulticlusterHub` resource to reflect the new catalog source name.

. Upgrade with catalog mirroring

+
{acm-short} uses the related {mce-short} functionality to provide foundational services that were delivered as part of the product. {acm-short} automatically installs and manages the required {mce-short} and `MulticlusterEngine` resource instance as part of the hub cluster installation and upgrade.

+
In connected network environments, the cluster administrator can install or upgrade {acm-short} without special mirror catalogs and catalog sources. However, because installation of any {olm} operator in a disconnected environment involves the use of special mirror catalogs and catalog sources, as described in the earlier sections, some additional steps are necessary after installation.

. Update your procedures for populating the mirror catalog.

+
If when installing {acm-short} mirroring procedures created a full copy of the Red Hat Operators catalog, no special mirroring updates are required. Refresh your catalog to pick up the updated content for the new operator releases.

+
If your procedures populated mirror catalog that is a _filtered_ catalog, you need to update your mirroring procedures to ensure that the `multcluster-engine` operator package is included in the mirror catalog, in addition to the `advanced-cluster-management` package.

+
See the _Install in disconnected network environments_ topic for examples of the options to use when populating the mirror catalog. Update the operator-package lists that are used in your procedures to match these new requirements.

. Update your `MutliclusterHub` resource instance. You need a new annotation on the `MulticlusterHub` resource when the hub cluster is installed or upgraded in a disconnected environment.

+
*Best practice:* Update your `MulticlusterHub` resource instance to include the required annotation before you change the {olm} update channel in your {olm} subscription to the `advanced-cluster-management` operator package to start the upgrade. This update allows the upgrade to proceed without delay.


. Run the `oc edit` command to update your `Multiclusterub` resource to add the `mce-subscription-spec` annotation as displayed in the following example. Replace `<my-mirror-catalog-source>` from the example with the name of the `CatalogSource` resource located in the `openshift-marketplace` namespace for your mirror catalog:

+
[source,yaml]
----
metadata:
   annotations:
      installer.open-cluster-management.io/mce-subscription-spec: '{"source": "<my-mirror-catalog-source>"}'
----
+
*Important:* If you begin an upgrade before you add the annotation, the upgrade begins but stalls when the operator attempts to install a subscription to `multicluster-engine` in the background. The status of the `MulticlusterHub` resource continues to display `upgrading` during this time. To resolve this issue, run `oc edit` to add the `mce-subscription-spec` annotation as shown previously.

.Additional resources

xref:../install/install_disconnected.adoc#install-on-disconnected-networks[Installing in disconnected network environments]
