[#upgrading]
= Upgrading

*Important:* Upgrading from the product technology preview version 1.x of {product-title} to version 2.0 is not supported. You must uninstall the 1.x version and install version 2.0 as a clean install. 

When you install version 2.0, you can enable automatic upgrades within the same major release by selecting the *autormatic upgrade* setting. If you prefer to run manual updates, you can select *manual upgrade*. 

[#automatic-upgrade]
== Automatic upgrade

If you selected Automatic upgrades when you installed the Red Hat Advanced Cluster Management operator, the Operator Lifecycle Manager automatically upgrades the version when a compatible upgrade is available.
You do not have to do anything to upgrade.
This method ensures that you always have the latest version of the operator with the latest fixes.

[#manual-upgrade]
== Manual upgrade

If you selected Manual upgrades when you installed the Red Hat Advanced Cluster Management operator, the cluster administrator determines when an upgrade occurs.
When a compatible upgrade is available, the Operator Lifecycle Manager creates a request to upgrade.
Someone with cluster administrator access must approve the request to upgrade to the new version.

For more information about upgrading your operator, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html/operators/olm-adding-operators-to-a-cluster[Adding operators to a cluster].
