[#upgrading-by-using-the-operator]
= Upgrading by using the operator

You control your {product-title} upgrades by using the operator subscription settings in the {ocp} console. When you initially deploy {product-title-short} by using the operator, you make the following selections:

* Channel - Corresponds to the version of the product that you are installing. The initial channel setting is often the most current channel that was available at the time of installation. 

* Approval - Specifies whether approval is required for updates within the channel, or if they are done automatically. If set to `Automatic`, then minor release updates in the selected channel are deployed without administrator intervention. If the `Manual` setting is selected, then each update to the minor release within the channel requires an administrator to approve the update. 

You also use those settings when you upgrade {product-title-short} by using the operator. 

*Required access:* {ocp-short} administrator

Complete the following steps to upgrade your operator:

. Log in to your {ocp-short} operator hub.

. In the {ocp-short} navigation, select *Operators* > *Installed operators*.

. Select the *{product-title}* operator.

. Select the _Subscription_ tab to edit the subscription settings.

. Ensure that the _Upgrade Status_ is labeled _Up to date_. This status indicates that the operator is at the latest level that is available in the selected channel. If the _Upgrade Status_ indicates that there is an upgrade pending, complete the following steps to update it to the latest minor release that is available in the channel:

.. Click the *Manual* setting in the _Approval_ field to edit the value. 

.. Select *Automatic* to enable automatic updates. 

.. Select *Save* to commit your change. 

.. Wait for the automatic updates to be applied to the operator. The updates automatically add the required updates to the latest version in the selected channel. When all of the updates are complete, the _Upgrade Status_ field indicates _Up to date_.

. Now that the _Upgrade Status_ is *Up to date*, click the value in the _Channel_ field to edit it.  

. Select the channel for the next available feature release. You cannot skip channels when upgrading. 
+
*Important:* You cannot revert back to an earlier version after upgrading to a later version in the channel selection. You must uninstall the operator and reinstall it with the earlier version to use a previous version.

. Select *Save* to save your changes.

. Wait for the automatic upgrade to complete. After the upgrade to the next feature release completes, the updates to the latest patch releases within the channel are deployed.


. If you have to upgrade to a later feature release, repeat steps 7-9 until your operator is at the latest level of the desired channel. Make sure that all of the patch releases are deployed for your final channel.   

. Optional: You can set your _Approval_ setting to *Manual*, if you want your future updates within the channel to require manual approvals.

{product-title-short} is running at the latest version of the selected channel. 

For more information about upgrading your operator, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html/operators/olm-adding-operators-to-a-cluster[Adding operators to a cluster].
