[#upgrading-disconnected]
= Upgrading in a disconnected network environment

See the steps and information to upgrade {product-title} in a disconnected network environment. 

*Note:* This information follows the upgrading procedure in xref:../install/upgrade_hub.adoc#upgrading[Upgrading]. Review that procedure, then see the following information:

[#disconnect-upgrading]
== Upgrade from previous release

During your installation, or upgrade, you might encounter important information that is related to the interdependency between the {product-title} and {mce}. See xref:../install/install_disconnected.adoc#install-on-disconnected-networks[Install in disconnected network environments] for consideration during install or upgrade.

As is the case for upgrading in a connected network environment, the upgrade process is started by changing the upgrade channel in
your {olm} subscription for {product-title} to the upgrade channel for the new release. 

However, because of the special characteristics of the disconnected environment, you need to address the following mirroring requirements before changing the update channel to start the upgrade process:

. Ensure that required packages are updated in your mirror catalog.

+
During installation, or during a previous update, you created a mirror catalog and a registry that contains operator packages and images that are needed to install {product-title} in a disconnected network environment. To upgrade, you need to update your mirror catalog and registry to pick up the updated versions of the operator packages.

+
Similar to your installation actions, you need to ensure that your mirror catalog and registry include the following operator packages in the list of operators to be included or updated:

* `advanced-cluster-manager`
* `multicluster-engine`

. Verify your `MutliclusterHub` resource instance.

+
During installation or a previous update, you created an instance of the `MulticlusterHub` resource, and due to the disconnected environment, you added a `mce-subscription-spec` annotation to that resource.

+
If your procedures for updating your mirror catalog and registry resulted in the updated catalog being available on the {ocp-short} cluster through a `CatalogSource` with the same name as the one that you previously used, you do not need to update your `MulticlusterHub` resource to update the `mce-subscriptino-spec` annotation.

+
However, if your procedures for updating your mirrored catalog and registry resulted in a newly named `CatalogSource` being
created, update the `mce-subscription-spec` annotation in your `MulticlusterHub` resource to reflect the new catalog source name.

[#disconnect-upgrading-from-24]
== Upgrade from release 2.4

{product-title} release 2.5 and later uses the related {mce} functionality to provide foundational services that previously were delivered as part of {product-title}. Releases 2.5 and later of the {product-title} operator automatically install and manage the required {mce} and `MulticlusterEngine` resource instance as part of the hub cluster installation and upgrade.

In connected network environments, the cluster administrator can install or upgrade {product-title} without special mirror catalogs and catalog sources. However, because installation of any {olm} operator in a disconnected environment involves the use of special mirror catalogs and catalog sources (as described in the earlier sections), some additional steps are necessary beyond installation.

. Update your procedures for populating the mirror catalog

+
If, when installing {product-title} release 2.4 and later, mirroring procedures created a full copy of the Red Hat Operators catalog, no special mirroring updates are required. Refresh your catalog to pick up the updated content for the new operator releases.

+
However, if your procedures populated mirror catalog that is a _filtered_ catalog, you need to update your mirroring procedures to ensure that the `multcluster-engine` operator package is included in the mirror catalog, in addition to the `advanced-cluster-management` package.

+
See the xref:../install/install_disconnected.adoc#disconnect-include-acm-pkgs[Include required operator packages in your mirror catalog] topic, which provides examples of the options to use when populating the mirror catalog. Update the operator-package lists that are used in your procedures to match these new requirements.


. Update your `MutliclusterHub` resource instance.

+
As described in the xref:../install/install_disconnected.adoc#install-on-disconnected-networks[Install in disconnected network environments] topic, you need a new annotation on the `MulticlusterHub` resource when the hub cluster is installed or upgraded in a disconnected environment.

+
*Best practice:* Update your `MulticlusterHub` resource instance to include the required annotation before you change the {olm} update channel in your {olm} subscription to the `advanced-cluster-management` operator package to start the upgrade from release 2.4. This update allows the upgrade to proceed without delay.

+
Use the `oc edit` command to update your `Multiclusterub` resource to add the `mce-subscription-spec` annotation as displayed in the following example:

+
[source,yaml]
----
metadata:
   annotations:
      installer.open-cluster-management.io/mce-subscription-spec: '{"source": "<my-mirror-catalog-source>"}'
----

+
Replace `<my-mirror-catalog-source>` from the example with the name of the `CatalogSource` resource located in the `openshift-marketplace` namespace for your mirror catalog.

*Important:* If you begin an upgrade from release 2.4 to release 2.5 before you add the annotation, the upgrade begins but stalls when the operator attempts to install a subscription to `multicluster-engine` in the background. The status of the `MulticlusterHub` resource continues to display `upgrading` during this time.

To resolve this issue, run `oc edit` to add the `mce-subscription-spec` annotation as shown previously.
