[#creating-a-cluster-on-amazon-web-services]
= Creating a cluster on Amazon Web Services

You can use the {product-title} console to create a {ocp} cluster on Amazon Web Services (AWS).

[#aws_prerequisites]
== Prerequisites

You must have the following prerequisites before creating a cluster on AWS:

* A deployed {product-title} hub cluster
* Internet access for your {product-title} hub cluster so it can create the Kubernetes cluster on Amazon Web Services
* AWS provider connection.
See xref:../manage_cluster/prov_conn_aws.adoc#creating-a-provider-connection-for-amazon-web-services[Creating a provider connection for Amazon Web Services] for more information.
* A configured domain in AWS.
See https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-account.html[Configuring an AWS account] for instructions on how to configure a domain.
* Amazon Web Services (AWS) login credentials, which include user name, password, access key ID, and secret access key.
See https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html[Understanding and Getting Your Security Credentials].
* A Red Hat OpenShift image pull secret.
See https://docs.openshift.com/container-platform/4.3/openshift_images/managing_images/using-image-pull-secrets.html[Using image pull secrets].

[#aws_creating-your-cluster-with-the-red-hat-advanced-cluster-management-for-kubernetes-console]
== Creating your cluster with the {product-title} console

To create clusters from the {product-title} console, complete the following steps:

. From the navigation menu, navigate to *Automate infrastructure* > *Clusters*.
. On the Clusters page, Click *Add Cluster*.
. Select *Create a cluster*.
+
NOTE: This procedure is for creating a cluster.
If you have an existing cluster that you want to import, see xref:../manage_cluster/import.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a target managed cluster to the hub cluster] for those steps.

. Enter a name for your cluster.
This name is used in the hostname of the cluster.
+
TIP: You can view the `yaml` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.

. Select *Amazon Web Services* for the infrastructure platform.
. Specify a *Release image* that you want to use for the cluster.
This identifies the version of the {ocp} image that is used to create the cluster.
If the version that you want to use is available, you can select the image from the list of images.
If the image that you want to use is not a standard image, you can enter the url to the image that you want to use.
See xref:../manage_cluster/release_images.adoc#release-images[Release images] for more information about release images.
. Select your provider connection from the available connections on the list.
If you do not have one configured, or want to configure a new one, select *Add connection*. See xref:../manage_cluster/prov_conn_aws.adoc#creating-a-provider-connection-for-amazon-web-services[Creating a provider connection for Amazon Web Services] for more information about creating a provider connection.
. Enter the base domain information that you configured for your AWS account. If there is already a base domain associated with the selected provider connection, that value is populated in that field. You can change the value by overwriting it.
See https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-account.html[Configuring an AWS account] for more information.
This name is used in the hostname of the cluster.
. Add the _Labels_ that you want to associate with your cluster. These labels help to identify the cluster and limit search results.
. Configure the _Node pools_ for your cluster.
+
The node pools define the location and size of the nodes that are used for your cluster.
+
The _Region_ specifies where the nodes are located geographically.
A closer region might provide faster performance, but a more distant region might be more distributed.

 ** Master pool: There are three Master nodes that are created for your cluster in the master pool.
The master nodes share the management of the cluster activity.
You can select multiple zones within the region for a more distributed group of master nodes.
You can change the type and size of your instance after it is created, but you can also specify it in this section.
The default values are _mx4.xlarge - 4 vCPU, 16 GiB RAM - General Purpose_ with 500 GiB of root storage.
 ** Worker pools: You can create one or more worker nodes in a worker pool to run the container workloads for the cluster.
They can be in a single worker pool, or distributed across multiple worker pools.

. *Optional:* Configure the cluster networking options.
. *Optional:* Configure a label for the cluster.
. Click *Create*.
You can view your cluster details after the create and import process is complete.

+
NOTE: You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured under the management of {product-title}. 

[#aws_accessing-your-cluster]
== Accessing your cluster

To access a cluster that is managed by {product-title}, complete the following steps:

. From the {product-title} navigation menu, navigate to *Automate infrastructure* > *Clusters*.
. Select the name of the cluster that you created or want to access.
The cluster details are displayed.
. Select *Reveal credentials* to view the user name and password for the cluster.
Note these values to use when you log in to the cluster.
. Select *Console URL* to link to the cluster.
. Log in to the cluster by using the user ID and password that you found in step 3.
. Select the _Actions_ menu for the cluster that you want to access.
. Select *Launch to cluster*.
+
TIP: If you already know the log in credentials, you can access the cluster by selecting the _Actions_ menu for the cluster, and selecting *Launch to cluster*.

[#aws_removing-a-cluster-from-management]
== Removing a cluster from management

When you remove a {ocp} cluster from management that was created with {product-title}, you can either _detach_ it or _destroy_ it.

Detaching a cluster removes it from management, but does not completely delete it.
You can import it again, if you decide that you want to bring it back under management.
This is only an option when the cluster is in a _Ready_ state.

Destroying a cluster removes it from management and deletes the components of the cluster.
This is permanent, and it cannot be brought back under management after deletion.

. From the navigation menu, navigate to *Automate infrastructure* > *Clusters*.
. Select the option menu beside the cluster that you want to delete.
. Select *Destroy cluster* or *Detach cluster*.

TIP: You can detach or destroy multiple clusters by selecting the check boxes of the clusters that you want to detach or destroy.
Then select *Detach* or *Destroy*.
