[#creating-a-cluster-on-vmware-vsphere]
= Creating a cluster on VMware vSphere

You can use the {product-title} console to deploy a {ocp} cluster on VMware vSphere.

[#vsphere_prerequisites]
== Prerequisites

You must have the following prerequisites before creating a cluster on vSphere:

* A {product-title-short} hub cluster that is deployed on {ocp-short} version 4.5, or later.
* Internet access for your {product-title-short} hub cluster so it can create the Kubernetes cluster on vSphere.
* vSphere provider connection. See xref:../manage_cluster/prov_conn_vm.adoc#creating-a-provider-connection-for-vmware-vsphere[Creating a provider connection for VMware vSphere] for more information.
* A Red Hat OpenShift image pull secret. See https://docs.openshift.com/container-platform/4.5/openshift_images/managing_images/using-image-pull-secrets.html[Using image pull secrets].
* The following information for the VMware instance where you are deploying:
** Required static IP addresses for API and Ingress instances.
** DNS records for:
*** api.<cluster_name>.<base_domain> which must point to the static API VIP.
*** *.apps.<cluster_name>.<base_domain> which must point to the static IP address for Ingress VIP.

[#vsphere_creating-your-cluster-with-the-red-hat-advanced-cluster-management-for-kubernetes-console]
== Creating your cluster with the {product-title} console

To create clusters from the {product-title-short} console, complete the following steps:

. From the navigation menu, navigate to *Automate infrastructure* > *Clusters*.
. On the _Clusters_ page, click *Add Cluster*.
. Select *Create a cluster*.
+
*Note:* This procedure is for creating a cluster.
If you have an existing cluster that you want to import, see xref:../manage_cluster/import.adoc#importing-a-target-managed-cluster-to-the-hub-cluster[Importing a target managed cluster to the hub cluster] for those steps.

. Enter a name for your cluster.
This name is used in the hostname of the cluster. Note: This value must match the name that you used to create the DNS records listed in the provider connection prerequisites section.
+
*Tip:* You can view the `yaml` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.

. Select *VMware vSphere* for the infrastructure platform.
. Specify a *Release image* that you want to use for the cluster.
This identifies the version of the {ocp-short} image that is used to create the cluster.
If the version that you want to use is available, you can select the image from the list of images.
If the image that you want to use is not a standard image, you can enter the URL of the image that you want to use.
See xref:../manage_cluster/release_images.adoc#release-images[Release images] for more information. 
*Note:* Only release images for {ocp-short} versions 4.5.x and higher are supported.
. Select your provider connection from the available connections on the list.
If you do not have one configured, or want to configure a new one, select *Add connection*. See xref:../manage_cluster/prov_conn.adoc[Creating a provider connection] for more information about creating a provider connection.
. Enter the base domain information that you configured for your vSphere account. If there is already a base domain associated with the selected provider connection, that value is populated in that field. You can change the value by overwriting it. Note: This value must match the name that you used to create the DNS records listed in the prerequisites section.
This name is used in the hostname of the cluster.

. Add the _Labels_ that you want to associate with your cluster. These labels help to identify the cluster and limit search results.
. Configure the _Node pools_ for your cluster.
+
The node pools define the location and size of the nodes that are used for your cluster. 
+
You can create one or more worker nodes in a worker pool to run the container workloads for the cluster. They can be in a single worker pool, or distributed across multiple worker pools.

. Configure the cluster networking options, which are shown in the following list:
.. Network type - The VMware vSphere network name.
.. API VIP - The IP address to use for internal API communication. *Note:* This value must match the name that you used to create the DNS records listed in the prerequisites section. If not provided, the DNS must be pre-configured so that `api.` resolves correctly.
.. Ingress VIP - The IP address to use for ingress traffic. *Note:* This value must match the name that you used to create the DNS records listed in the prerequisites section. If not provided, the DNS must be pre-configured so that `test.apps.` resolves correctly.

. *Optional:* Configure a label for the cluster.
. Click *Create*.
You can view your cluster details after the create and import process is complete.
+
*Note:* When you create the cluster, it is automatically configured under the management of {product-title-short}. You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. 

[#vsphere_accessing-your-cluster]
== Accessing your cluster

To access a cluster that is managed by {product-title-short}, complete the following steps:

. If you already know the log in credentials, you can access the cluster by selecting the _Options_ menu for the cluster, and selecting *Launch to cluster*.
. If you do not know the log in credentials
.. From the {product-title-short} navigation menu, navigate to *Automate infrastructure* > *Clusters*.
.. Select the name of the cluster that you created or want to access.
The cluster details are displayed.
.. Select *Reveal credentials* to view the user name and password for the cluster.
Use these values when you log in to the cluster.
. Select *Console URL* to link to the cluster.
. Log in to the cluster by using the user ID and password that you found in step 3.
. Select the _Options_ menu for the cluster that you want to access.
. Select *Launch to cluster*.


[#vsphere_removing-a-cluster-from-management]
== Removing a cluster from management

When you remove an {ocp-short} cluster from management that was created with {product-title-short}, you can either _Detach_ it or _Destroy_ it.

Detaching a cluster removes it from management, but does not completely delete it.
You can import it again, if you decide that you want to bring it back under management.
This is only an option when the cluster is in a _Ready_ state.

Destroying a cluster removes it from management and deletes the components of the cluster.
This is permanent, and it cannot be brought back under management after deletion.

. From the navigation menu, navigate to *Automate infrastructure* > *Clusters*.
. Select the option menu beside the cluster that you want to delete.
. Select *Destroy cluster* or *Detach cluster*.
+
*Tip:* You can detach or destroy multiple clusters by selecting the check boxes of the clusters that you want to detach or destroy.
Then select *Detach* or *Destroy*.
