[#modifying-the-klusterlet-addons-settings-of-your-cluster]
= Modifying the klusterlet addons settings of your cluster

You can modify the settings of `klusterlet addon` to change your configuration using the hub cluster.

The `klusterlet addon` controller manages the functions that are enabled and disabled according to the settings in the `klusterletaddonconfigs.agent.open-cluster-management.io` Kubernetes resource.

The following settings can be updated in the `klusterletaddonconfigs.agent.open-cluster-management.io` Kubernetes resource:

|===
| Setting name | Value

| applicationmanager
| `true` or `false`

| policyController
| `true` or `false`

| searchCollector
| `true` or `false`

| certPolicyController
| `true` or `false`

| iamPolicyController
| `true` or `false`
|===

[#modify-using-the-console-on-the-hub-cluster]
== Modify using the console on the hub cluster

You can modify the settings of the `klusterletaddonconfigs.agent.open-cluster-management.io` resource by using the hub cluster.
Complete the following steps to change the settings:

. Authenticate into the Red Hat Advanced Cluster Management for Kubernetes console of the hub cluster.
. From the main menu of the hub cluster console, select *Search*.
. In the search parameters, enter the following value: `kind:klusterletaddonconfigs`
. Select the endpoint resource that you want to update.
. Find the `spec` section and select *Edit* to edit the content.
. Modify your settings.
. Select *Save* to apply your changes.

[#modify-using-the-command-line-on-the-hub-cluster]
== Modify using the command line on the hub cluister

You must have access to the <cluster-name> namespace to modify your settings by using the hub cluster.
Complete the following steps:

. Authenticate into the hub cluster.
. Enter the following command to edit the resource:
+
----
kubectl edit klusterletaddonconfigs.agent.open-cluster-management.io <cluster-name> -n <cluster-name>
----

. Find the `spec` section.
. Modify your settings, as necessary.
