[#creating-a-provider-connection]
= Creating a provider connection

A _provider connection_ is required to create a Red Hat OpenShift Container Platform cluster on a cloud service provider with Red Hat Advanced Cluster Management for Kubernetes.

The provider connection stores the access credentials and configuration information for a provider.
Each provider account requires its own provider connection, as does each domain on a single provider.

The following files detail the information that is required for creating a connection document for each supported provider:

* xref:prov_conn_aws.md.adoc#creating-a-provider-connection-for-amazon-web-services[Creating a provider connection for Amazon Web Services]
* xref:prov_conn_azure.md.adoc#creating-a-provider-connection-for-microsoft-azure[Creating a provider connection for Microsoft Azure]
* xref:prov_conn_google.md.adoc#creating-a-provider-connection-for-google-cloud-platform[Creating a provider connection for Google Cloud Platform]
* xref:prov_conn_bare.md.adoc#creating-a-provider-connection-for-bare-metal[Creating a provider connection for bare metal]
