[#creating-a-provider-connection-for-amazon-web-services]
= Creating a provider connection for Amazon Web Services

You need a provider connection to use {product-title} console to deploy and manage an OpenShift cluster on Amazon Web Services (AWS).

NOTE: This procedure must be done before you can create a cluster with {product-title}.

[#aws_prov_conn_prerequisites]
== Prerequisites

You must have the following prerequisites before creating a provider connection:

* A deployed {product-title} hub cluster
* Internet access for your {product-title} hub cluster so it can create the Kubernetes cluster on Amazon Web Services
* Amazon Web Services (AWS) login credentials, which include access key ID and secret access key.
See https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html[Understanding and getting your security credentials].
* Account permissions that allow installing clusters on AWS.
See https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account[Configuring an AWS account] for instructions on how to configure.

[#aws_provider_conn]
== Creating a provider connection by using the console

To create a provider connection from the {product-title} console, complete the following steps:

. From the navigation menu, navigate to *Automate infrastructure* > *Clusters*.
. On the _Clusters_ page, select the _Provider connections_ tab.
+
Existing provider connections are displayed.

. Select *Add a connection*.
. Select *Amazon Web Services* as your provider.
. Add a name for your provider connection.
. Select a namespace for your provider connection from the list.
+
TIP: Create a namespace specifically to host your provider connections, both for convenience and added security.

. You can optionally add a _Base DNS domain_ for your provider connection. If you add the base DNS domain to the provider connection, it is automatically populated in the correct field when you create a cluster with this provider connection.
. Add your _AWS Access Key ID_ for your Amazon Web Services account.
Log in to https://console.aws.amazon.com/iam/home#/security_credentials[AWS] to find the ID.
. Add your _AWS Secret Access Key ID_.
. Enter your _Red Hat OpenShift Pull Secret_.
You can download your pull secret from https://cloud.redhat.com/openshift/install/pull-secret[Pull secret].
. Add your _SSH Private Key_ and _SSH Public Key_, which allows you to connect to the cluster.
You can use an existing key pair, or create a new one with key generation program.
See https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-default.html#ssh-agent-using_installing-aws-default[Generating an SSH private key and adding it to the agent] for more information about how to generate a key.
. Click *Create*.
When you create the provider connection, it is added to the list of provider connections.

You can create a cluster that uses this provider connection by completing the steps in xref:../manage_cluster/create_ocp_aws.adoc#creating-a-cluster-on-amazon-web-services[Creating a cluster on Amazon Web Services].

[#aws_delete_provider_conn]
== Deleting your provider connection

When you are no longer managing a cluster that is using a provider connection, delete the provider connection to protect the information in the provider connection.

. From the navigation menu, navigate to *Automate infrastructure* > *Clusters*.
. Select *Provider connections*.
. Select the options menu beside the provider connection that you want to delete.
. Select *Delete connection*.
