[#release-images]
= Release images

When you create a cluster on a provider by using the {product-title}, you must specify a release image to use for the new cluster.
The release image specifies which version of {ocp} is used to build the cluster.

The files that reference the release images are `yaml` files that are maintained in the `acm-hive-openshift-releases` GitHub repository.
{product-title} uses those files to create the list of the available release images in the console.
The repository contains the `clusterImageSets` directory and the `subscription` directory, which are the directories that you use when working with the release images.

The `clusterImageSets` directory contains the following directories:

* Fast - Contains files that reference the latest two versions of the release images for each {ocp-short} version that is supported
* Releases - Contains files that reference all of the release images for each {ocp-short} version that is supported.
*Note:* These releases have not all been tested and determined to be stable.
* Stable - Contains files that reference the latest two stable versions of the release images for each {ocp-short} version that is supported.
The release images in this folder are tested and verified.

The `subscription` directory contains files that specify where the list of release images is pulled from.
The default release images for {product-title-short} are provided in a Quay.io directory.
They are referenced by the files in the https://github.com/open-cluster-management/acm-hive-openshift-releases[acm-hive-openshift-releases GitHub repository].
