[#remove-managed-cluster]
= Removing a cluster from management

When you remove an {ocp-short} cluster from management that was created with {product-title}, you can either _detach_ it or _destroy_ it.

Detaching a cluster removes it from management, but does not completely delete it.
You can import it again, if you decide that you want to bring it back under management.
This is only an option when the cluster is in a _Ready_ state.

Destroying a cluster removes it from management and deletes the components of the cluster.
This is permanent, and it cannot be brought back under management after deletion.

[#remove-a-cluster-by-using-the-console]
== Remove a cluster by using the console

. From the navigation menu, navigate to *Automate infrastructure* > *Clusters*.
. Select the option menu beside the cluster that you want to remove from management.
. Select *Destroy cluster* or *Detach cluster*.
+
*Tip:* You can detach or destroy multiple clusters by selecting the check boxes of the clusters that you want to detach or destroy.
Then select *Detach* or *Destroy*.

*Note:* If you attempt to detach the hub cluster, which is named `local-cluster`, be aware that the default setting of `disableHubSelfManagement` is `false`. This setting causes the hub cluster to reimport itself and manage itself when it is detached and it reconciles the `MultiClusterHub` controller. It might take hours for the hub cluster to complete the detachment process and reimport. If you want to reimport the hub cluster without waiting for the processes to finish, you can enter the following command to restart the `multiclusterhub-operator` pod and reimport faster:

----
oc delete po -n open-cluster-management `oc get pod -n open-cluster-management | grep multiclusterhub-operator| cut -d' ' -f1`
----

You can change the value of the hub cluster to not import automatically by changing the `disableHubSelfManagement` value to `true`, as described in link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online].

[#remove-a-cluster-by-using-the-cli]
== Remove a cluster by using the command line

To detach a managed cluster by using the command line of the hub cluster, run the following command: 

----
oc delete managedcluster $CLUSTER_NAME
----

*Note:* If you attempt to detach the hub cluster, which is named `local-cluster`, be aware that the default setting of `disableHubSelfManagement` is `false`. This setting causes the hub cluster to reimport itself and manage itself when it is detached and it reconciles the `MultiClusterHub` controller. It might take hours for the hub cluster to complete the detachment process and reimport. If you want to reimport the hub cluster without waiting for the processes to finish, you can enter the following command to restart the `multiclusterhub-operator` pod and reimport faster:

----
oc delete po -n open-cluster-management `oc get pod -n open-cluster-management | grep multiclusterhub-operator| cut -d' ' -f1`
----

You can change the value of the hub cluster to not import automatically by changing the `disableHubSelfManagement` value to `true`, as described in link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online].

[#removing-a-cluster-from-management-in-special-cases]
== Remove remaining resources after removing a cluster

If there are remaining resources on the managed cluster that you removed, there are additional steps that are required to ensure that you remove all of the remaining components. Situations when these extra steps are required include the following examples:

* The managed cluster was detached before it was completely created, and components like the `klusterlet` remain on the managed cluster. 

* The hub that was managing the cluster was lost or destroyed before detaching the managed cluster, and there is no way to detach the managed cluster from the hub. 

* The managed cluster was not in an online state when it was detached.

* The namespace of the managed cluster was not removed.

If one of these situations apply to your attempted detachment of a managed cluster, there are some resources that cannot be removed from managed cluster. Complete the following steps to detach the managed cluster:

. Make sure you have the `oc` command line interface configured.
. Make sure you have `KUBECONFIG` configured on your managed cluster.
+ 
If you run `oc get ns | grep open-cluster-management-agent` you should see two namespaces:
+
----
open-cluster-management-agent         Active   10m
open-cluster-management-agent-addon   Active   10m
----

. Download the link:https://github.com/open-cluster-management/deploy/blob/master/hack/cleanup-managed-cluster.sh[`cleanup-managed-cluster`] script from the `deploy` Git repository.
. Run the `cleanup-managed-cluster.sh` script by entering the following command:
+
----
./cleanup-managed-cluster.sh
----
. Run the following command to ensure that both namespaces are removed: 
+
----
oc get ns | grep open-cluster-management-agent 
----