[#resizing-a-cluster]
= Resizing a cluster

You can customize your managed cluster specifications, such as virtual machine sizes and number of nodes.
See the following list of recommended settings for each available provider, but also see the documentation for more specific information:

[#amazon-web-services]
== Amazon Web Services

You can change the number of nodes of a {ocp} cluster that was created in an Amazon Web Services environment by modifying the `MachineSet` parameters on the hub cluster.

*Note:* Because {product-title} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.

See https://docs.openshift.com/container-platform/4.5/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.5/machine_management/manually-scaling-machineset.html[Manually scaling a MachineSet] in the {ocp-short} documentation that applies to your version.

*Tip:* If you created the cluster by using the {product-title-short} console, then it is an {ocp-short} cluster.

If you are changing the number of nodes of an Amazon EKS cluster that you imported, see https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html[Cluster autoscaler] for information about scaling the cluster.

[#google-cloud-platform]
== Google Cloud Platform

You can change the number of nodes of a {ocp-short} cluster that was created in an Google Cloud Platform environment by modifying the `MachineSet` parameters on the hub cluster. 

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.
  
See https://docs.openshift.com/container-platform/4.5/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.5/machine_management/manually-scaling-machineset.html[Manually scaling a MachineSet] in the {ocp-short} documentation that applies to your version for more information about scaling your cluster.
*Tip:* If you created the cluster by using {product-title-short}, then it is an {ocp-short} cluster.

If you are changing the number of nodes of a Google Kubernetes Engine cluster that you imported, see https://cloud.google.com/kubernetes-engine/docs/how-to/resizing-a-cluster[Resizing a cluster] for information about scaling the cluster.

[#microsoft-azure]
== Microsoft Azure

You can change the number of nodes of a {ocp-short} cluster that was created in a Microsoft Azure environment by modifying the `MachineSet` parameters on the hub cluster.

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.

See https://docs.openshift.com/container-platform/4.5/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.5/machine_management/manually-scaling-machineset.html[Manually scaling a MachineSet] in the {ocp-short} documentation that applies to your version.
*Tip:* If you created the cluster by using {product-title-short}, then it is an {ocp-short} cluster.

If you are changing the number of nodes of an Azure Kubernetes Services cluster that you imported, see https://docs.microsoft.com/en-us/azure/aks/scale-cluster[Scaling a cluster] for information about scaling the cluster.

[#vmware-vsphere]
== VMware vSphere

You can change the number of nodes of a {ocp-short} cluster that was created in a VMware vSphere environment by modifying the `MachineSet` parameters on the hub cluster.

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.

See https://docs.openshift.com/container-platform/4.5/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.5/machine_management/manually-scaling-machineset.html[Manually scaling a MachineSet] in the {ocp-short} documentation that applies to your version.
*Tip:* If you created the cluster by using {product-title-short}, then it is an {ocp-short} cluster.

If you are changing the number of nodes of a VMware vSphere cluster that you imported, see https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.resmgmt.doc/GUID-755AB944-F3D0-43DD-82CD-8CDDDF8674E8.html[Edit cluster settings] for information about scaling the cluster.

[#bare-metal-cluster]
== Bare metal cluster

You can change the number of nodes of a {ocp-short} cluster that was created in a bare metal environment by modifying the `MachineSet` parameters on the hub cluster.

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.

See https://docs.openshift.com/container-platform/4.5/scalability_and_performance/recommended-cluster-scaling-practices.html[Recommended cluster scaling practices] and https://docs.openshift.com/container-platform/4.5/machine_management/manually-scaling-machineset.html[Manually scaling a MachineSet] in the {ocp-short} documentation that applies to your version.
*Tip:* If you created the cluster by using {product-title-short}, then it is an {ocp-short} cluster.

If you are changing the number of nodes of a bare metal cluster that you imported, see https://docs.openshift.com/container-platform/4.5/installing/installing_bare_metal/installing-bare-metal-network-customizations.html[Installing a cluster on bare metal with network customizations] for information about scaling the cluster.

Note: Bare metal clusters are only supported when the hub cluster is {ocp-short} version 4.5, and later.

[#ibm-kubernetes-service]
== IBM Kubernetes Service

If you are changing the number of nodes of an IBM Kubernetes Service cluster that you imported, see https://cloud.ibm.com/docs/containers?topic=containers-add_workers[Adding worker nodes and zones to clusters] for information about scaling the cluster.

*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove or add a node without changing the `MachineSet` parameter, nodes are added or removed to match the current value of that parameter.
