[#synchronizing-available-release-images]
= Synchronizing available release images

The release images are updated frequently, so you might want to synchronize the list of release images to ensure that you can select the latest available versions.
The release images are available in the https://github.com/open-cluster-management/acm-hive-openshift-releases[acm-hive-openshift-releases] GitHub repository.

There are three levels of stability of the release images:

.Stability levels of release images
|===
|Category |Description
|stable
|Fully tested images that are confirmed to install and build clusters correctly.

|fast
|Partially tested, but likely less stable than a stable version.

|candidate
|Not tested, but the most current image. Might have some bugs. 
===

Complete the following steps to refresh the list:

. Clone the https://github.com/open-cluster-management/acm-hive-openshift-releases[acm-hive-openshift-releases] GitHub repository.
. Connect to your Red Hat Advanced Cluster Management for Kubernetes hub cluster by entering the following command: 

+
----
oc apply -k subscription/
----
+
After about one minute, the latest two `fast` entries are available. 

. To synchronize your list of `stable` release images after you have cloned the `acm-hive-openshift-releases` GitHub repository, enter the following command to update the `stable` images:

+
----
make subscribe-stable
----
+
*Note:* You can only run this `make` command when you are using the Linux or MacOS operating system. If you are using the Windows operating system, enter the following command to update the `stable` images:

+
----
oc apply -f subscription-stable
----
+

After running this command, the list of available `stable` release images updates with the currently available images in about one minute.

   * To synchronize and display the fast release images, enter the following command:
   +
   ----
   make subscribe-fast
   ----
   +
   *Note:* You can only run this `make` command when you are using the Linux or MacOS operating system. If you are using the Windows operating system, enter the following command to updated the `fast` images:
   +
   ----
   oc apply -f subscription/subscription-fast.yaml
   ----
   +
   After running the command, the list of available `stable` and `fast` release images updates with the currently available images in about one minute.
   
   * To synchronize and display the `candidate` release images, enter the following command:
   +
   ----
   make subscribe-candidate
   ----
   +
   *Note:* You can only run this `make` command when you are using the Linux or MacOS operating system. If you are using the Windows operating system, enter the following command to updated the `candidate` images:
   +
   ----
   oc apply -f subscription/subscription-candidate.yaml
   ----
   +
   After running the command, the list of available `stable`, `fast`, and `candidate` release images updates with the currently available images in about 1 minute.

. View the list of currently available release images in the Red Hat Advanced Cluster Management console when you are creating a cluster.

. You can unsubscribe from any of these channels to stop viewing the updates by entering a command in the following format: 

+
----
oc delete -f subscription/subscription-stable
----
+
