[#addondeploymentconfig-api]
= AddOnDeploymentConfig API (v1alpha1)

[[_rhacm-docs_apis_addondeploymentconfig_jsonoverview]]
== Overview
This documentation is for the AddOnDeploymentConfig resource for {product-title}. The AddOnDeploymentConfig resource has four possible requests: create, query, delete, and update. 
AddOnDeploymentConfig represents a deployment configuration for an add-on.


=== Version information
[%hardbreaks]
__Version__ : 2.11.0


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* addon.open-cluster-management.io : Create and manage AddOnDeploymentConfigs


[[_rhacm-docs_apis_addondeploymentconfig_jsonpaths]]
== Paths

[[_rhacm-docs_apis_addondeploymentconfig_jsonqueryaddondeploymentconfigs]]
=== Query all AddOnDeploymentConfigs
....
GET /addon.open-cluster-management.io/v1alpha1/namespaces/{namespace}/addondeploymentconfigs
....


==== Description
Query your AddOnDeploymentConfigs for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `addondeploymentconfig/yaml`


==== Tags

* addon.open-cluster-management.io


[[_rhacm-docs_apis_addondeploymentconfig_jsoncreateaddondeploymentconfig]]
=== Create a AddOnDeploymentConfig
....
POST /addon.open-cluster-management.io/v1alpha1/namespaces/{namespace}/addondeploymentconfigs
....


==== Description
Create a AddOnDeploymentConfig.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Body*|*body* +
__required__|Parameters describing the AddOnDeploymentConfig binding to be created.|<<_rhacm-docs_apis_addondeploymentconfig_jsonaddondeploymentconfig,AddOnDeploymentConfig>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `addondeploymentconfig/yaml`


==== Tags

* addon.open-cluster-management.io


==== Example HTTP request

===== Request body
[source,json]
----
{
  "apiVersion": "addon.open-cluster-management.io/v1alpha1",
  "kind": "AddOnDeploymentConfig",
  "metadata": {
    "name": "deploy-config",
    "namespace": "open-cluster-management-hub"
  },
  "spec": {
    "nodePlacement": {
      "nodeSelector": {
        "node-dedicated": "acm-addon"
      },
      "tolerations": [
        {
          "effect": "NoSchedule",
          "key": "node-dedicated",
          "operator": "Equal",
          "value": "acm-addon"
        }
      ]
    }
  }
}
----


[[_rhacm-docs_apis_addondeploymentconfig_jsonqueryaddondeploymentconfig]]
=== Query a single AddOnDeploymentConfig
....
GET /addon.open-cluster-management.io/v1alpha1/namespaces/{namespace}/addondeploymentconfigs/{addondeploymentconfig_name}
....


==== Description
Query a single AddOnDeploymentConfig for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*addondeploymentconfig_name* +
__required__|Name of the AddOnDeploymentConfig that you want to query.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* addon.open-cluster-management.io


[[_rhacm-docs_apis_addondeploymentconfig_jsondeleteaddondeploymentconfig]]
=== Delete a AddOnDeploymentConfig
....
DELETE /addon.open-cluster-management.io/v1alpha1/namespaces/{namespace}/addondeploymentconfigs/{addondeploymentconfig_name}
....


==== Description
Delete a single AddOnDeploymentConfig.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*addondeploymentconfig_name* +
__required__|Name of the AddOnDeploymentConfig that you want to delete.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* addon.open-cluster-management.io


[[_rhacm-docs_apis_addondeploymentconfig_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_addondeploymentconfig_jsonaddondeploymentconfig]]
=== AddOnDeploymentConfig

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*apiVersion* +
__required__|Versioned schema of the AddOnDeploymentConfig. |string
|*kind* +
__required__|String value that represents the REST resource. |string
|*metadata* +
__required__|Metadata of the AddOnDeploymentConfig. |object
|*spec* +
__required__|Specification of the AddOnDeploymentConfig. |<<_rhacm-docs_apis_addondeploymentconfig_jsonaddondeploymentconfig_spec,spec>>
|===

[[_rhacm-docs_apis_addondeploymentconfig_jsonaddondeploymentconfig_spec]]
*spec*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*customizedVariables* +
__optional__|A list of name-value variables for the current add-on deployment. The add-on implementation can use these variables to render its add-on deployment. |<<_rhacm-docs_apis_addondeploymentconfig_jsonaddondeploymentconfig_customizedVariable,customizedVariable>> array
|*nodePlacement* +
__required__|Enables explicit control over the scheduling of the add-on agents on the managed cluster. |<<_rhacm-docs_apis_addondeploymentconfig_jsonaddondeploymentconfig_nodePlacement,nodePlacement>>
|===

[[_rhacm-docs_apis_addondeploymentconfig_jsonaddondeploymentconfig_customizedVariable]]
*customizedVariable*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*name* +
__required__|Name of this variable. |string
|*value* +
__optional__|Value of this variable. |string
|===

[[_rhacm-docs_apis_addondeploymentconfig_jsonaddondeploymentconfig_nodePlacement]]
*nodePlacement*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*nodeSelector* +
__optional__|Define which nodes the pods are scheduled to run on. When the `nodeSelector` is empty, the `nodeSelector` selects all nodes.|map[string]string
|*tolerations* +
__optional__|Applied to pods and used to schedule pods to any taint that matches the `<key,value,effect>` toleration using the matching operator (`<operator>`).|[]corev1.Toleration
|===
