[#clustersets-api]
= Clustersets API (v1beta2)

[[_rhacm-docs_apis_clusterset_jsonoverview]]
== Overview
This documentation is for the ClusterSet resource for {product-title}. The ClusterSet resource has four possible requests: create, query, delete, and update. The ManagedClusterSet defines a group of ManagedClusters. You can assign a ManagedCluster to a specific ManagedClusterSet by adding a label with the name `cluster.open-cluster-management.io/clusterset` on the ManagedCluster that refers to the ManagedClusterSet. You can only add or remove this label on a ManagedCluster when you have an RBAC rule that allows the `create` permissions on a virtual subresource of `managedclustersets/join`. You must have this permission on both the source and the target ManagedClusterSets to update this label.


=== Version information
[%hardbreaks]
__Version__ : 2.11.0


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* cluster.open-cluster-management.io : Create and manage Clustersets


[[_rhacm-docs_apis_clusterset_jsonpaths]]
== Paths

[[_rhacm-docs_apis_clusterset_jsonqueryclustersets]]
=== Query all clustersets
....
GET /cluster.open-cluster-management.io/v1beta2/managedclustersets
....


==== Description
Query your Clustersets for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `clusterset/yaml`


==== Tags

* cluster.open-cluster-management.io


[[_rhacm-docs_apis_clusterset_jsoncreateclusterset]]
=== Create a clusterset
....
POST /cluster.open-cluster-management.io/v1beta2/managedclustersets
....


==== Description
Create a Clusterset.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Body*|*body* +
__required__|Parameters describing the clusterset to be created.|<<_rhacm-docs_apis_clusterset_jsonclusterset,Clusterset>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `clusterset/yaml`


==== Tags

* cluster.open-cluster-management.io


==== Example HTTP request

===== Request body
[source,json]
----
{
  "apiVersion": "cluster.open-cluster-management.io/v1beta2",
  "kind": "ManagedClusterSet",
  "metadata": {
    "name": "clusterset1"
  },
  "spec": {
    "clusterSelector": {
      "selectorType": "ExclusiveClusterSetLabel"
    }
  },
  "status": {}
}
----


[[_rhacm-docs_apis_clusterset_jsonqueryclusterset]]
=== Query a single clusterset
....
GET /cluster.open-cluster-management.io/v1beta2/managedclustersets/{clusterset_name}
....


==== Description
Query a single clusterset for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*clusterset_name* +
__required__|Name of the clusterset that you want to query.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* cluster.open-cluster-management.io


[[_rhacm-docs_apis_clusterset_jsondeleteclusterset]]
=== Delete a clusterset
....
DELETE /cluster.open-cluster-management.io/v1beta2/managedclustersets/{clusterset_name}
....


==== Description
Delete a single clusterset.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*clusterset_name* +
__required__|Name of the clusterset that you want to delete.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* cluster.open-cluster-management.io




[[_rhacm-docs_apis_clusterset_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_clusterset_jsonclusterset]]
=== Clusterset

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|*apiVersion* +
__required__|string
|*kind* +
__required__|string
|*metadata* +
__required__|object
|===
