[#clusters-api]
= Clusters API

[[_rhacm-docs_apis_cluster_jsonoverview]]
== Overview
This documentation is for the cluster resource for {acm}. Cluster resource has four possible requests: create, query, delete and update. `ManagedCluster` represents the desired state and current status of a managed cluster. `ManagedCluster` is a cluster-scoped resource.


=== Version information
[%hardbreaks]
__Version__ : 2.10.0


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* cluster.open-cluster-management.io : Create and manage clusters


[[_rhacm-docs_apis_cluster_jsonpaths]]
== Paths

[[_rhacm-docs_apis_cluster_jsonqueryclusters]]
=== Query all clusters
....
GET /cluster.open-cluster-management.io/v1/managedclusters
....


==== Description
Query your clusters for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `cluster/yaml`


==== Tags

* cluster.open-cluster-management.io


[[_rhacm-docs_apis_cluster_jsoncreatecluster]]
=== Create a cluster
....
POST /cluster.open-cluster-management.io/v1/managedclusters
....


==== Description
Create a cluster


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Body*|*body* +
__required__|Parameters describing the cluster to be created.|<<_rhacm-docs_apis_cluster_jsoncluster,Cluster>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `cluster/yaml`


==== Tags

* cluster.open-cluster-management.io


==== Example HTTP request

===== Request body
[source,json]
----
{
  "apiVersion" : "cluster.open-cluster-management.io/v1",
  "kind" : "ManagedCluster",
  "metadata" : {
    "labels" : {
      "vendor" : "OpenShift"
    },
    "name" : "cluster1"
  },
  "spec": {
    "hubAcceptsClient": true,
    "managedClusterClientConfigs": [
      {
        "caBundle": "test",
        "url": "https://test.com"
      }
    ]
  },
  "status" : { }
}
----


[[_rhacm-docs_apis_cluster_jsonquerycluster]]
=== Query a single cluster
....
GET /cluster.open-cluster-management.io/v1/managedclusters/{cluster_name}
....


==== Description
Query a single cluster for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*cluster_name* +
__required__|Name of the cluster that you want to query.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* cluster.open-cluster-management.io


[[_rhacm-docs_apis_cluster_jsondeletecluster]]
=== Delete a cluster
....
DELETE /cluster.open-cluster-management.io/v1/managedclusters/{cluster_name}
....

....
DELETE /hive.openshift.io/v1/{cluster_name}/clusterdeployments/{cluster_name}
....

==== Description
Delete a single cluster


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*cluster_name* +
__required__|Name of the cluster that you want to delete.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* cluster.open-cluster-management.io




[[_rhacm-docs_apis_cluster_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_cluster_jsoncluster]]
=== Cluster

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*apiVersion* +
__required__|The versioned schema of the `ManagedCluster`.|string
|*kind* +
__required__|String value that represents the REST resource.|string
|*metadata* +
__required__|The metadata of the `ManagedCluster`.|object
|*spec* +
__required__|The specification of the `ManagedCluster`. |<<_rhacm-docs_apis_cluster_jsoncluster_spec,spec>>
|===

[[_rhacm-docs_apis_cluster_jsoncluster_spec]]
*spec*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*hubAcceptsClient* +
__required__|Specifies whether the hub can establish a connection with the klusterlet agent on the managed cluster. The default value is `false`, and can only be changed to `true` when you have an RBAC rule configured on the hub cluster that allows you to make updates to the virtual subresource
of `managedclusters/accept`.|bool
|*managedClusterClientConfigs* +
__optional__|Lists the apiserver addresses of the managed cluster.| <<_rhacm-docs_apis_cluster_jsoncluster_managedClusterClientConfigs,managedClusterClientConfigs>> array
|*leaseDurationSeconds* +
__optional__|Specifies the lease update time interval of the klusterlet agents on the managed cluster.
By default, the klusterlet agent updates its lease every 60 seconds.|integer (int32)
|*taints* +
__optional__|Prevents a managed cluster from being assigned to one or more managed cluster sets during scheduling.|<<_rhacm-docs_apis_cluster_jsoncluster_taint,taint>> array
|===

[[_rhacm-docs_apis_cluster_jsoncluster_managedClusterClientConfigs]]
*managedClusterClientConfigs*

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|*URL* +
__required__||string
|*CABundle* +
__optional__|*Pattern* :

[source,bash]
"^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==\|[A-Za-z0-9+/]{3}=)?$"
|string (byte)
|===

[[_rhacm-docs_apis_cluster_jsoncluster_taint]]
*taint*

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|*key* +
__required__|The taint key that is applied to a cluster.|string
|*value* +
__optional__|The taint value that corresponds to the taint key.|string
|*effect* +
__optional__|Effect of the taint on placements that do not tolerate the taint. Valid values are `NoSelect`, `PreferNoSelect`, and `NoSelectIfNew`.|string
|===




