[#discovery-config-api]
= DiscoveryConfig API

[[_rhacm-docs_apis_discoveryconfig_jsonoverview]]
== Overview
This documentation is for the DiscoveryConfig resource for {product-title}. The DiscoveryConfig resource has four possible requests: create, query, delete and update.


=== Version information
[%hardbreaks]
__Version__ : 2.3.0


=== Contact information
[%hardbreaks]
__Contact Email__ : apiteam@swagger.io


=== License information
[%hardbreaks]
__License__ : Apache 2.0
__License URL__ : http://www.apache.org/licenses/LICENSE-2.0.html
__Terms of service__ : http://swagger.io/terms/


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* discoveryconfigs.discovery.open-cluster-management.io : Create and manage DiscoveryConfigs


=== External Docs
[%hardbreaks]
__Description__ : Find out more about Swagger.
__URL__ : http://swagger.io


[[_rhacm-docs_apis_discoveryconfig_jsonpaths]]
== Paths

[[_rhacm-docs_apis_discoveryconfig_jsoncreatediscoveryconfig]]
=== Create a DiscoveryConfig
....
POST /app.k8s.io/v1alpha1/namespaces/{namespace}/discoveryconfigs
....


==== Description
Create a DiscoveryConfig.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|**Body**|**body** +
__required__|Parameters describing the DiscoveryConfig to be created.|<<_rhacm-docs_apis_DiscoveryConfig_jsonDiscoveryConfig,DiscoveryConfig>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `DiscoveryConfig/yaml`


==== Tags

* discoveryconfigs.discovery.open-cluster-management.io

===== Request body

[source,json]
----
{
  "apiVersion": "apiextensions.k8s.io/v1",
  "kind": "CustomResourceDefinition",
  "metadata": {
    "annotations": {
      "controller-gen.kubebuilder.io/version": "v0.4.1"
    },
    "creationTimestamp": null,
    "name": "discoveryconfigs.discovery.open-cluster-management.io"
  },
  "spec": {
    "group": "discovery.open-cluster-management.io",
    "names": {
      "kind": "DiscoveryConfig",
      "listKind": "DiscoveryConfigList",
      "plural": "discoveryconfigs",
      "singular": "discoveryconfig"
    },
    "scope": "Namespaced",
    "versions": [
      {
        "name": "v1alpha1",
        "schema": {
          "openAPIV3Schema": {
            "description": "DiscoveryConfig is the Schema for the discoveryconfigs API",
            "properties": {
              "apiVersion": {
                "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
                "type": "string"
              },
              "kind": {
                "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
                "type": "string"
              },
              "metadata": {
                "type": "object"
              },
              "spec": {
                "description": "DiscoveryConfigSpec defines the desired state of DiscoveryConfig",
                "properties": {
                  "credential": {
                    "description": "Credential is the secret containing credentials to connect to the OCM api on behalf of a user",
                    "type": "string"
                  },
                  "filters": {
                    "description": "Sets restrictions on what kind of clusters to discover",
                    "properties": {
                      "lastActive": {
                        "description": "LastActive is the last active in days of clusters to discover, determined by activity timestamp",
                        "type": "integer"
                      },
                      "openShiftVersions": {
                        "description": "OpenShiftVersions is the list of release versions of OpenShift of the form \"<Major>.<Minor>\"",
                        "items": {
                          "description": "Semver represents a partial semver string with the major and minor version in the form \"<Major>.<Minor>\". For example: \"4.5\"",
                          "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$",
                          "type": "string"
                        },
                        "type": "array"
                      }
                    },
                    "type": "object"
                  }
                },
                "required": [
                  "credential"
                ],
                "type": "object"
              },
              "status": {
                "description": "DiscoveryConfigStatus defines the observed state of DiscoveryConfig",
                "type": "object"
              }
            },
            "type": "object"
          }
        },
        "served": true,
        "storage": true,
        "subresources": {
          "status": {}
        }
      }
    ]
  },
  "status": {
    "acceptedNames": {
      "kind": "",
      "plural": ""
    },
    "conditions": [],
    "storedVersions": []
  }
}
----

[[_rhacm-docs_apis_mch_jsonqueryoperator]]
=== Query all DiscoveryConfigs
....
GET /operator.open-cluster-management.io/v1beta1/namespaces/{namespace}/operator
....


==== Description
Query your multicluster hub operator for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `operator/yaml`


==== Tags

* discoveryconfigs.discovery.open-cluster-management.io


[[_rhacm-docs_apis_mch_jsonquery_mch_operator]]
=== Query a DiscoveryConfig operator
....
GET /operator.open-cluster-management.io/v1beta1/namespaces/{namespace}/operator/{DiscoveryConfig_name}
....


==== Description
Query a single multicluster hub operator for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**application_name** +
__required__|Name of the application that you wan to query.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* discoveryconfigs.discovery.open-cluster-management.io


[[_rhacm-docs_apis_mch_jsondeleteoperator]]
=== Delete a DiscoveryConfig operator
....
DELETE /operator.open-cluster-management.io/v1beta1/namespaces/{namespace}/operator/{DiscoveryConfig_name}
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**application_name** +
__required__|Name of the multicluster hub operator that you want to delete.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* discoveryconfigs.discovery.open-cluster-management.io




[[_rhacm-docs_apis_mch_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_mch_json_parameters]]
=== Multicluster hub operator

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__required__| The versioned schema of the DiscoveryConfig. |string
|**kind** +
__required__|String value that represents the REST resource. |string
|**metadata** +
__required__|Describes rules that define the resource.|object
|**spec** +
__required__|The resource specification. | <<_rhacm-docs_apis_mch_jsonoperator_spec,spec>>
|===


[[_rhacm-docs_apis_mch_jsonoperator_spec]]
**spec**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|**availabilityConfig** +
__optional__|Specifies deployment replication for improved availability. The default value is `High`. |string
|**customCAConfigmap** +
__optional__|Provide the customized OpenShift default ingress CA certificate to {product-title-short}. |string
|**disableHubSelfManagement** +
__optional__|Disable automatic import of the hub cluster as a managed cluster. |boolean
|**disableUpdateClusterImageSets** +
__optional__|Disable automatic update of ClusterImageSets. |boolean
|**hive** +
__optional__|(Deprecated) An object that overrides for the default HiveConfig specification. |<<_rhacm-docs_apis_mch_jsonoperator_hive,hive>>
|**imagePullSecret** +
__optional__| Overrides pull secret for accessing DiscoveryConfig operand and endpoint images. |string
|**ingress** +
__optional__| Configuration options for ingress management. |<<_rhacm-docs_apis_mch_jsonoperator_ingress,ingress>>
|**nodeSelector** +
__optional__|Set the node selectors. |string
|**separateCertificateManagement** +
__optional__| (Deprecated) Install `cert-manager` into its own namespace. |boolean
|===

// deprecated items remain for 3 major releases 
[[_rhacm-docs_apis_mch_jsonoperator_hive]]
**hive**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|**additionalCertificateAuthorities** +
__optional__|(Deprecated) A list of references to secrets in the `hive` namespace that contain an additional Certificate Authority to use when communicating with target clusters. These certificate authorities are used in addition to any self-signed CA generated by each cluster on installation. |object
|**backup** +
__optional__|(Deprecated) Specifies the configuration for backup integration. If absent, backup integration is disabled. |<<_rhacm-docs_apis_mch_jsonoperator_backup,backup>>
|**externalDNS** +
__optional__| (Deprecated) Specifies configuration for `external-dns` if it is to be deployed by Hive. If absent, `external-dns` is not be deployed. |object
|**failedProvisionConfig** +
__required__| (Deprecated) Used to configure settings related to handling provision failures. |<<_rhacm-docs_apis_mch_jsonoperator_failedProvision,failedProvisionConfig>>
|**globalPullSecret** +
__optional__| (Deprecated) Used to specify a pull secret that is used globally by all of the cluster deployments. For each cluster deployment, the contents of `globalPullSecret` are merged with the specific pull secret for a cluster deployment (if specified), with precedence given to the contents of the pull secret for the cluster deployment. |object
|**maintenanceMode** +
__optional__| (Deprecated) Can be set to true to disable the hive controllers in situations where you need to ensure nothing is running that adds or acts upon finalizers on Hive types. This should rarely be needed. Sets replicas to `0` for the `hive-controllers` deployment to accomplish this.| boolean
|===

[[_rhacm-docs_apis_mch_jsonoperator_ingress]]
**ingress**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|**sslCiphers** +
__optional__| List of SSL ciphers enabled for management ingress. Defaults to full list of supported ciphers. |string
|===


[[_rhacm-docs_apis_mch_jsonoperator_backup]]
**backup**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|**minBackupPeriodSeconds** +
__optional__| (Deprecated) Specifies that a minimum of `MinBackupPeriodSeconds` occurs in between each backup. This is used to rate limit backups. This potentially batches together multiple changes into one backup. No backups are lost as changes happen during this interval are queued up and result in a backup happening once the interval has been completed. |integer
|**velero** + 
__optional__| (Deprecated) Velero specifies configuration for the Velero backup integration.|object
|===


[[_rhacm-docs_apis_mch_jsonoperator_failedProvision]]
**failedProvisionConfig**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|**skipGatherLogs** +
__optional__| (Deprecated) Disables functionality that attempts to gather full logs from the cluster if an installation fails for any reason. The logs are stored in a persistent volume for up to seven days. |boolean
|===


[[_rhacm-docs_apis_mch_jsonoperator_status]]
**status**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|**components** +
__optional__|The components of the status configuration. |object
|**conditions** +
__optional__|Contains the different conditions for the multicluster hub. | <<_rhacm-docs_apis_mch_jsonoperator_conditions,conditions>>
|**desiredVersion** +
__optional__| Indicates the desired version. |string
|**phase** +
__optional__| Represents the active phase of the DiscoveryConfig resource. The values that are used for this parameter are: `Pending`, `Running`, `Installing`, `Updating`, `Uninstalling` |string
|===

[[_rhacm-docs_apis_mch_jsonoperator_conditions]]
**conditions**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|**lastTransitionTime** +
__optional__| The last time the condition changed from one status to another. |string
|**lastUpdateTime** +
__optional__|The last time this condition was updated.|string
|**message** +
__required__|Message is a human-readable message indicating details about the last status change.|string
|**reason** +
__required__|A brief reason for why the condition status changed.|string
|**status** +
__required__|The status of the condition.|string
|**type** +
__required__|The type of the cluster condition.|string
|===

[[_rhacm-docs_apis_mch_jsonoperator_statusconditions]]
**StatusConditions**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|**kind** +
__required__| The resource `kind` that represents this status.|string
|**available** +
__required__|Indicates whether this component is properly running.|boolean
|**lastTransitionTime** +
__optional__| The last time the condition changed from one status to another. |metav1.time
|**lastUpdateTime** +
__optional__|The last time this condition was updated.|metav1.time
|**message** +
__required__|Message is a human-readable message indicating details about the last status change.|string
|**reason** +
__optional__|A brief reason for why the condition status changed.|string
|**status** +
__optional__|The status of the condition.|string
|**type** +
__optional__|The type of the cluster condition.|string
|===
