[#multicluster-hub-api]
= MultiClusterHub API


[[_rhacm-docs_apis_mch_jsonoverview]]
== Overview
This documentation is for the MultiClusterHub resource for {product-title}. MultiClusterHub resource has four possible requests: create, query, delete and update.


=== Version information
[%hardbreaks]
__Version__ : 2.3.0


=== Contact information
[%hardbreaks]
__Contact Email__ : apiteam@swagger.io


=== License information
[%hardbreaks]
__License__ : Apache 2.0
__License URL__ : http://www.apache.org/licenses/LICENSE-2.0.html
__Terms of service__ : http://swagger.io/terms/


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* multiclusterhubs.operator.open-cluster-management.io : Create and manage multicluster hubs


=== External Docs
[%hardbreaks]
__Description__ : Find out more about Swagger.
__URL__ : http://swagger.io




[[_rhacm-docs_apis_mch_jsonpaths]]
== Paths

[[_rhacm-docs_apis_mch_jsoncreatemch]]
=== Create a multicluster hub
....
POST /app.k8s.io/v1beta1/namespaces/{namespace}/mch
....


==== Description
Create a MultiClusterHub resource to define the configuration for an instance of the multicluster hub.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|**Body**|**body** +
__required__|Parameters describing the application to be created.|<<_rhacm-docs_apis_mch_jsonamch,>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `multiclusterhubs/yaml`


==== Tags

* multiclusterhubs.operator.open-cluster-management.io


==== Example HTTP request

===== Request body
[source,json]
----
{
  "apiVersion" : "apiextensions.k8s.io/v1",
  "kind" : "CustomResourceDefinition",
  "metadata" : {
    "name" : "multiclusterhubs.operator.open-cluster-management.io"
    },
  "spec" : {
    "group" : "operator.open-cluster-management.io"
    "names" : {
      "kind" : "MultiClusterHub"
      "listKind" : "MultiClusterHubList"
      "plural" : "multiclusterhubs"
      "shortNames" : {
      - "mch"
     "singular" : "multiclusterhub"
     }
    "scope" : "Namespaced"
    "versions" : {
    - "additionalPrinterColumns" : {
      - "description" : "The overall status of the multicluster hub"
        "jsonPath" : ".status.phase"
        "name": "Status"
        "type": "string"
      - "jsonPath": ".metadata.creationTimestamp"
        "name": "Age"
        "type": "date"
     "name": "v1"
     "schema": {
      "openAPIV3Schema":{
        "description": "MultiClusterHub defines the configuration for an instance of
          the MultiCluster Hub"
        "properties":{
          "apiVersion": {
            "description": "APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            "type": "string"
            }
          "kind": {
            "description": "Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            "type": "string"
            }
          "metadata":{
            "type": "object"
            }
          "spec": {
            "description": "MultiClusterHubSpec defines the desired state of MultiClusterHub"
            "properties": {
              "availabilityConfig": {
                "description": "Specifies deployment replication for improved availability.
                  Options are: Basic and High (default)"
                "type": "string"
                }
              "customCAConfigmap": {
                "description": "Provide the customized OpenShift default ingress CA certificate
                  to {product-title-short}"
                  }
                "type": "string"
                }
              "disableHubSelfManagement": {
                "description": "Disable automatic import of the hub cluster as a managed
                  cluster"
                "type": "boolean"
                }
              "disableUpdateClusterImageSets": {
                "description": "Disable automatic update of ClusterImageSets"
                "type": "boolean"
                }
              "hive": {
                "description": "(Deprecated) Overrides for the default HiveConfig specification"
                "properties": {
                  "additionalCertificateAuthorities": {
                    "description": "(Deprecated) AdditionalCertificateAuthorities is
                      a list of references to secrets in the 'hive' namespace that
                      contain an additional Certificate Authority to use when communicating
                      with target clusters. These certificate authorities are
                      used in addition to any self-signed CA generated by each cluster
                      on installation."
                    "items": {
                      "description": "LocalObjectReference contains the information
                        to let you locate the referenced object inside the same namespace."
                      "properties": {
                        "name": {
                          "description": "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?"
                          "type": "string"
                          }
                       "type": "object"
                      }
                     "type": "array"
                    }
                  "backup": {
                    "description": "(Deprecated) Backup specifies configuration for backup
                      integration. If absent, backup integration will be disabled."
                    "properties": {
                      minBackupPeriodSeconds:
                        description: (Deprecated) MinBackupPeriodSeconds specifies
                          that a minimum of MinBackupPeriodSeconds will occur in between
                          each backup. This is used to rate limit backups. This potentially
                          batches together multiple changes into 1 backup. No backups
                          will be lost as changes that happen during this interval
                          are queued up and will result in a backup happening once
                          the interval has been completed.
                        type: integer
                      velero:
                        description: (Deprecated) Velero specifies configuration for
                          the Velero backup integration.
                        properties:
                          enabled:
                            description: (Deprecated) Enabled dictates if Velero backup
                              integration is enabled. If not specified, the default
                              is disabled.
                            type: boolean
                        type: object
                    type: object
                  externalDNS:
                    description: (Deprecated) ExternalDNS specifies configuration
                      for external-dns if it is to be deployed by Hive. If absent,
                      external-dns will not be deployed.
                    properties:
                      aws:
                        description: (Deprecated) AWS contains AWS-specific settings
                          for external DNS
                        properties:
                          credentials:
                            description: (Deprecated) Credentials references a secret
                              that will be used to authenticate with AWS Route53.
                              It will need permission to manage entries in each of
                              the managed domains for this cluster. Secret should
                              have AWS keys named 'aws_access_key_id' and 'aws_secret_access_key'.
                            properties:
                              name:
                                description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                  TODO: Add other useful fields. apiVersion, kind,
                                  uid?'
                                type: string
                            type: object
                        type: object
                      gcp:
                        description: (Deprecated) GCP contains GCP-specific settings
                          for external DNS
                        properties:
                          credentials:
                            description: (Deprecated) Credentials references a secret
                              that will be used to authenticate with GCP DNS. It will
                              need permission to manage entries in each of the managed
                              domains for this cluster. Secret should have a key names
                              'osServiceAccount.json'. The credentials must specify
                              the project to use.
                            properties:
                              name:
                                description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                  TODO: Add other useful fields. apiVersion, kind,
                                  uid?'
                                type: string
                            type: object
                        type: object
                    type: object
                  failedProvisionConfig:
                    description: (Deprecated) FailedProvisionConfig is used to configure
                      settings related to handling provision failures.
                    properties:
                      skipGatherLogs:
                        description: (Deprecated) SkipGatherLogs disables functionality
                          that attempts to gather full logs from the cluster if an
                          installation fails for any reason. The logs will be stored
                          in a persistent volume for up to 7 days.
                        type: boolean
                    type: object
                  globalPullSecret:
                    description: (Deprecated) GlobalPullSecret is used to specify
                      a pull secret that will be used globally by all of the cluster
                      deployments. For each cluster deployment, the contents of GlobalPullSecret
                      will be merged with the specific pull secret for a cluster deployment(if
                      specified), with precedence given to the contents of the pull
                      secret for the cluster deployment.
                    properties:
                      name:
                        description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                          TODO: Add other useful fields. apiVersion, kind, uid?'
                        type: string
                    type: object
                  maintenanceMode:
                    description: (Deprecated) MaintenanceMode can be set to true to
                      disable the hive controllers in situations where we need to
                      ensure nothing is running that will add or act upon finalizers
                      on Hive types. This should rarely be needed. Sets replicas to
                      0 for the hive-controllers deployment to accomplish this.
                    type: boolean
                required:
                - failedProvisionConfig
                type: object
              imagePullSecret:
                description: Override pull secret for accessing MultiClusterHub operand
                  and endpoint images
                type: string
              ingress:
                description: Configuration options for ingress management
                properties:
                  sslCiphers:
                    description: List of SSL ciphers enabled for management ingress.
                      Defaults to full list of supported ciphers
                    items:
                      type: string
                    type: array
                type: object
              nodeSelector:
                additionalProperties:
                  type: string
                description: Set the nodeselectors
                type: object
              overrides:
                description: Developer Overrides
                properties:
                  imagePullPolicy:
                    description: Pull policy of the MultiCluster hub images
                    type: string
                type: object
              separateCertificateManagement:
                description: (Deprecated) Install cert-manager into its own namespace
                type: boolean
            type: object
          status:
            description: MultiClusterHubStatus defines the observed state of MultiClusterHub
            properties:
              components:
                additionalProperties:
                  description: StatusCondition contains condition information.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time the condition
                        changed from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: Message is a human-readable message indicating
                        details about the last status change.
                      type: string
                    reason:
                      description: Reason is a (brief) reason for the condition's
                        last status change.
                      type: string
                    status:
                      description: Status is the status of the condition. One of True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the cluster condition.
                      type: string
                  type: object
                description: Components []ComponentCondition `json:"manifests,omitempty"`
                type: object
              conditions:
                description: Conditions contains the different condition statuses
                  for the MultiClusterHub
                items:
                  description: StatusCondition contains condition information.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time the condition
                        changed from one status to another.
                      format: date-time
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      format: date-time
                      type: string
                    message:
                      description: Message is a human-readable message indicating
                        details about the last status change.
                      type: string
                    reason:
                      description: Reason is a (brief) reason for the condition's
                        last status change.
                      type: string
                    status:
                      description: Status is the status of the condition. One of True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the cluster condition.
                      type: string
                  type: object
                type: array
              currentVersion:
                description: CurrentVersion indicates the current version
                type: string
              desiredVersion:
                description: DesiredVersion indicates the desired version
                type: string
              phase:
                description: Represents the running phase of the MultiClusterHub
                type: string
            type: object
            }
        "type": "object"
    "served": "true"
    "storage": "true"
    "subresources": {
      "status": {}
      }
---


[[_rhacm-docs_apis_mch_jsonqueryapplications]]
=== Query all applications
....
GET /app.k8s.io/v1beta1/namespaces/{namespace}/applications
....


==== Description
Query your applications for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `application/yaml`


==== Tags

* multiclusterhubs.operator.open-cluster-management.io


[[_rhacm-docs_apis_mch_jsonqueryapplication]]
=== Query a single application
....
GET /app.k8s.io/v1beta1/namespaces/{namespace}/applications/{application_name}
....


==== Description
Query a single application for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**application_name** +
__required__|Name of the application that you wan to query.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* multiclusterhubs.operator.open-cluster-management.io


[[_rhacm-docs_apis_mch_jsondeleteapplication]]
=== Delete a application
....
DELETE /app.k8s.io/v1beta1/namespaces/{namespace}/applications/{application_name}
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**application_name** +
__required__|Name of the application that you want to delete.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* multiclusterhubs.operator.open-cluster-management.io




[[_rhacm-docs_apis_mch_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_mch_jsonapplication]]
=== Application

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**apiVersion** +
__required__|string
|**kind** +
__required__|string
|**metadata** +
__required__|object
|**spec** +
__required__|<<_rhacm-docs_apis_mch_jsonapplication_spec,spec>>
|===

[[_rhacm-docs_apis_mch_jsonapplication_spec]]
**spec**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**assemblyPhase** +
__optional__|string
|**componentKinds** +
__optional__|< object > array
|**descriptor** +
__optional__|<<_rhacm-docs_apis_mch_jsonapplication_descriptor,descriptor>>
|**info** +
__optional__|< <<_rhacm-docs_apis_mch_jsonapplication_info,info>> > array
|**selector** +
__optional__|object
|===

[[_rhacm-docs_apis_mch_jsonapplication_descriptor]]
**descriptor**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**description** +
__optional__|string
|**icons** +
__optional__|< <<_rhacm-docs_apis_mch_jsonapplication_descriptor_icons,icons>> > array
|**keywords** +
__optional__|< string > array
|**links** +
__optional__|< <<_rhacm-docs_apis_mch_jsonapplication_descriptor_links,links>> > array
|**maintainers** +
__optional__|< <<_rhacm-docs_apis_mch_jsonapplication_descriptor_maintainers,maintainers>> > array
|**notes** +
__optional__|string
|**owners** +
__optional__|< <<_rhacm-docs_apis_mch_jsonapplication_descriptor_owners,owners>> > array
|**type** +
__optional__|string
|**version** +
__optional__|string
|===

[[_rhacm-docs_apis_mch_jsonapplication_descriptor_icons]]
**icons**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**size** +
__optional__|string
|**src** +
__required__|string
|**type** +
__optional__|string
|===

[[_rhacm-docs_apis_mch_jsonapplication_descriptor_links]]
**links**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**description** +
__optional__|string
|**url** +
__optional__|string
|===

[[_rhacm-docs_apis_mch_jsonapplication_descriptor_maintainers]]
**maintainers**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**email** +
__optional__|string
|**name** +
__optional__|string
|**url** +
__optional__|string
|===

[[_rhacm-docs_apis_mch_jsonapplication_descriptor_owners]]
**owners**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**email** +
__optional__|string
|**name** +
__optional__|string
|**url** +
__optional__|string
|===

[[_rhacm-docs_apis_mch_jsonapplication_info]]
**info**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**name** +
__optional__|string
|**type** +
__optional__|string
|**value** +
__optional__|string
|**valueFrom** +
__optional__|<<_rhacm-docs_apis_mch_jsonapplication_info_valuefrom,valueFrom>>
|===

[[_rhacm-docs_apis_mch_jsonapplication_info_valuefrom]]
**valueFrom**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**configMapKeyRef** +
__optional__|<<_rhacm-docs_apis_mch_jsonapplication_info_valuefrom_configmapkeyref,configMapKeyRef>>
|**ingressRef** +
__optional__|<<_rhacm-docs_apis_mch_jsonapplication_info_valuefrom_ingressref,ingressRef>>
|**secretKeyRef** +
__optional__|<<_rhacm-docs_apis_mch_jsonapplication_info_valuefrom_secretkeyref,secretKeyRef>>
|**serviceRef** +
__optional__|<<_rhacm-docs_apis_mch_jsonapplication_info_valuefrom_serviceref,serviceRef>>
|**type** +
__optional__|string
|===

[[_rhacm-docs_apis_mch_jsonapplication_info_valuefrom_configmapkeyref]]
**configMapKeyRef**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**apiVersion** +
__optional__|string
|**fieldPath** +
__optional__|string
|**key** +
__optional__|string
|**kind** +
__optional__|string
|**name** +
__optional__|string
|**namespace** +
__optional__|string
|**resourceVersion** +
__optional__|string
|**uid** +
__optional__|string
|===

[[_rhacm-docs_apis_mch_jsonapplication_info_valuefrom_ingressref]]
**ingressRef**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**apiVersion** +
__optional__|string
|**fieldPath** +
__optional__|string
|**host** +
__optional__|string
|**kind** +
__optional__|string
|**name** +
__optional__|string
|**namespace** +
__optional__|string
|**path** +
__optional__|string
|**resourceVersion** +
__optional__|string
|**uid** +
__optional__|string
|===

[[_rhacm-docs_apis_mch_jsonapplication_info_valuefrom_secretkeyref]]
**secretKeyRef**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**apiVersion** +
__optional__|string
|**fieldPath** +
__optional__|string
|**key** +
__optional__|string
|**kind** +
__optional__|string
|**name** +
__optional__|string
|**namespace** +
__optional__|string
|**resourceVersion** +
__optional__|string
|**uid** +
__optional__|string
|===

[[_rhacm-docs_apis_mch_jsonapplication_info_valuefrom_serviceref]]
**serviceRef**

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**apiVersion** +
__optional__|string
|**fieldPath** +
__optional__|string
|**kind** +
__optional__|string
|**name** +
__optional__|string
|**namespace** +
__optional__|string
|**path** +
__optional__|string
|**port** +
__optional__|integer (int32)
|**resourceVersion** +
__optional__|string
|**uid** +
__optional__|string
|===
