[#observability-api]
= Observability API


[[_rhacm-docs_apis_multiclusterobservability_jsonoverview]]
== Overview
This documentation is for the MultiClusterObservability resource for {product-title}. The MultiClusterObservability resource has four possible requests: create, query, delete and update.


=== Version information
[%hardbreaks]
__Version__ : 2.1.0


=== Contact information
[%hardbreaks]
__Contact Email__ : apiteam@swagger.io


=== License information
[%hardbreaks]
__License__ : Apache 2.0
__License URL__ : http://www.apache.org/licenses/LICENSE-2.0.html
__Terms of service__ : http://swagger.io/terms/


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* observability.open-cluster-management.io : Create and manage multiclusterobservabilities 


=== External Docs
[%hardbreaks]
__Description__ : Find out more about Swagger.
__URL__ : http://swagger.io




[[_rhacm-docs_apis_multiclusterobservability_jsonpaths]]
== Paths

[[_rhacm-docs_apis_multiclusterobservability_jsoncreatemulticlusterobservability]]
=== Create a multiclusterobservability resource
....
POST /apis/observability.open-cluster-management.io/v1beta1/multiclusterobservabilities
....


==== Description
Create a MultiClusterObservability resource.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Body**|**body** +
__required__|Parameters describing the MultiClusterObservability resource to be created.|<<_rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability,MultiClusterObservability>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `application/yaml`


==== Tags

* observability.apps.open-cluster-management.io


==== Example HTTP request

===== Request body
[source,json]
----
{
  "apiVersion": "observability.open-cluster-management.io/v1beta1",
  "kind": "MultiClusterObservability",
  "metadata": {
    "name": "example"
  },
  "spec": {
    "storageConfigObject": {
      "metricObjectStorage": {
        "name": "thanos-object-storage",
        "key": "thanos.yaml"
      }
    }
  }
}
----


[[_rhacm-docs_apis_multiclusterobservability_jsonquerymulticlusterobservabilities]]
=== Query all multiclusterobservabilities
....
GET /apis/observability.open-cluster-management.io/v1beta1/multiclusterobservabilities
....


==== Description
Query your MultiClusterObservability resources for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `application/yaml`


==== Tags

* observability.apps.open-cluster-management.io


[[_rhacm-docs_apis_multiclusterobservability_jsonquerymulticlusterobservability]]
=== Query a single multiclusterobservability
....
GET /apis/observability.open-cluster-management.io/v1beta1/multiclusterobservabilities/{multiclusterobservability_name}
....


==== Description
Query a single MultiClusterObservability resource for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**multiclusterobservability_name** +
__required__|Name of the multiclusterobservability that you want to query.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* observability.apps.open-cluster-management.io


[[_rhacm-docs_apis_multiclusterobservability_jsondeletemulticlusterobservability]]
=== Delete a multiclusterobservability resource
....
DELETE /apis/observability.open-cluster-management.io/v1beta1/multiclusterobservabilities/{multiclusterobservability_name}
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**multiclusterobservability_name** +
__required__|Name of the multiclusterobservability that you want to delete.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* observability.apps.open-cluster-management.io




[[_rhacm-docs_apis_multiclusterobservability_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability]]
=== MultiClusterObservability

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__required__ | The versioned schema of the MultiClusterObservability. |string
|**kind** +
__required__|String value that represents the REST resource, MultiClusterObservability.| string
|**metadata** +
__required__| Describes rules that define the policy.| object
|**spec** +
__required__|<<_rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability_spec,spec>>
|===

[[_rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability_spec]]
**spec**

[options="header", cols=".^2a,.^6a,.^4a"]
|===
|Name|Description|Schema
|**availabilityConfig** +
__optional__|The parameter used to select high-availability support. This provides support in the case of a failover, and consumes more resources. +
 Options: `Basic` and `High`| string
|**enableDownSampling** +
__optional__| Enable or disable the downsample. Default value is `false`. If there is no downsampled data, the query is unavailable.| boolean
|**imagePullPolicy** +
__optional__| Pull policy for the Observability images.|string
|**imagePullSecret** +
__optional__| Pull secret for the Observability images.|string
|**nodeSelector** +
__optional__|Supports node selection constraints|object
|**observabilityAddonSpec** +
__optional__|The global settings for all managed clusters, which have the add-on enabled. |<<_rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability_observabilityaddonspec,observabilityAddonSpec>>
|**retentionResolution1h** +
__optional__|The amount of time to retain samples of resolution 2 (1 hour) in a bucket. Default value is 30 days (`30d`).|string
|**retentionResolution5m** +
__optional__|The amount of time to retain samples of resolution 1 (5 minutes) in a bucket. Default value is 14 days (`14d`).|string
|**retentionResolutionRaw** +
__optional__|The amount of time to retain raw samples of resolution in a bucket.|string
|**storageConfigObject** +
__required__|Specifies the storage to be used by Observability. |<<_rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability_storageconfigobject,storageConfigObject>>
|===

[[_rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability_observabilityaddonspec]]
**observabilityAddonSpec**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**enableMetrics** +
__optional__|Indicates if the observability add-on sends metrics to the hub cluster. Default value is `true`.| boolean
|**interval** +
__optional__|Interval for when the observability add-on sends metrics to the hub cluster. Default value is 60 seconds (`60s`). |integer
|===


[[_rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability_storageconfigobject]]
**storageConfigObject**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**metricObjectStorage** +
__required__|Object store to configure secrets for metrics.|<<_rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability_smetricobjectstorage,metricObjectStorage>>
|**statefulSetSize** +
__optional__|The amount of storage that is applied to the Observability stateful sets, i.e. Thanos store, rule, compact, and receiver. Default value is `10Gi`.|string
|**statefulSetStorageClass** +
__optional__|Specify the `storageClass` stateful sets. This storage is used for the object storage if `MetricObjectStorage` is configured for your operating system to create storage. Default value is `gp2`.|string
|===


[[_rhacm-docs_apis_multiclusterobservability_jsonmulticlusterobservability_smetricobjectstorage]]
**metricObjectStorage**

[options="header", cols=".^2,.^3a,.^4a"]
|===
|Name|Description|Schema
|**key** +
__required__|The key of the secret to select from. Must be a valid secret key.|string
|**name** +
__required__|Name of the `metricObjectStorage`.|string
|===


