[#placement-api]
= Placement API (v1beta1)

[[_rhacm-docs_apis_placement_jsonoverview]]
== Overview
This documentation is for the Placement resource for {acm}. The Placement resource has four possible requests: create, query, delete, and update. Placement defines a rule to select a set of ManagedClusters from the ManagedClusterSets that are bound to the placement namespace. A slice of PlacementDecisions with the label `cluster.open-cluster-management.io/placement={placement name}` is created to represent the ManagedClusters that are selected by this placement.


=== Version information
[%hardbreaks]
__Version__ : 2.11.0


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* cluster.open-cluster-management.io : Create and manage Placements


[[_rhacm-docs_apis_placement_jsonpaths]]
== Paths

[[_rhacm-docs_apis_placement_jsonqueryplacements]]
=== Query all Placements
....
GET /cluster.open-cluster-management.io/v1beta1/namespaces/{namespace}/placement
....


==== Description
Query your Placements for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `placement/yaml`


==== Tags

* cluster.open-cluster-management.io


[[_rhacm-docs_apis_placement_jsoncreateplacement]]
=== Create a Placement
....
POST /cluster.open-cluster-management.io/v1beta1/namespaces/{namespace}/placements
....


==== Description
Create a Placement.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Body*|*body* +
__required__|Parameters describing the placement binding to be created.|<<_rhacm-docs_apis_placement_jsonplacement,Placement>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `placement/yaml`


==== Tags

* cluster.open-cluster-management.io


==== Example HTTP request

===== Request body
[source,json]
----
{
  "apiVersion" : "cluster.open-cluster-management.io/v1beta1",
  "kind" : "Placement",
  "metadata" : {
    "name" : "placement1",
    "namespace": "ns1"
  },
  "spec": {
    "predicates": [
      {
        "requiredClusterSelector": {
          "labelSelector": {
            "matchLabels": {
              "vendor": "OpenShift"
            }
          }
        }
      }
    ]
  },
  "status" : { }
}
----


[[_rhacm-docs_apis_placement_jsonqueryplacement]]
=== Query a single Placement
....
GET /cluster.open-cluster-management.io/v1beta1/namespaces/{namespace}/placements/{placement_name}
....


==== Description
Query a single Placement for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*placement_name* +
__required__|Name of the Placement that you want to query.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* cluster.open-cluster-management.io


[[_rhacm-docs_apis_placement_jsondeleteplacement]]
=== Delete a Placement
....
DELETE /cluster.open-cluster-management.io/v1beta1/namespaces/{namespace}/placements/{placement_name}
....


==== Description
Delete a single Placement.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*placement_name* +
__required__|Name of the Placement that you want to delete.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* cluster.open-cluster-management.io




[[_rhacm-docs_apis_placement_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_placement_jsonplacement]]
=== Placement

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*apiVersion* +
__required__|Versioned schema of the Placement. |string
|*kind* +
__required__|String value that represents the REST resource. |string
|*metadata* +
__required__|Metadata of the Placement. |object
|*spec* +
__required__|Specification of the Placement. |<<_rhacm-docs_apis_placement_jsonplacement_spec,spec>>
|===

[[_rhacm-docs_apis_placement_jsonplacement_spec]]
*spec*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*clusterSets* +
__optional__|A subset of `ManagedClusterSets` from which the `ManagedClusters` are selected. If the `ManagedClusterSet` is empty, `ManagedClusters` are selected from the `ManagedClusterSets` that are bound to the Placement namespace. If the `ManagedClusterSet` contains `ManagedClusters`, `ManagedClusters` are selected from the intersection of this subset. The selected `ManagedClusterSets` are bound to the placement namespace. |string array
|*numberOfClusters* +
__optional__|Number of `ManagedClusters` that you want to be selected. |integer (int32)
|*predicates* +
__optional__|Subset of cluster predicates that select `ManagedClusters`. The conditional logic is _OR_. |<<_rhacm-docs_apis_placement_jsonplacement_clusterpredicate,clusterPredicate>> array
|*prioritizerPolicy* +
__optional__|Policy of the prioritizers. |<<_rhacm-docs_apis_placement_jsonplacement_prioritizerPolicy,prioritizerPolicy>>
|*tolerations* +
__optional__|Value that allows, but does not require, the managed clusters with certain taints to be selected by placements with matching tolerations.|<<_rhacm-docs_apis_placement_jsonplacement_toleration,toleration>> array
|===

[[_rhacm-docs_apis_placement_jsonplacement_clusterpredicate]]
*clusterPredicate*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*requiredClusterSelector* +
__optional__|A cluster selector to select `ManagedClusters` with a label and cluster claim. |<<_rhacm-docs_apis_placement_jsonplacement_clusterselector,clusterSelector>>
|===

[[_rhacm-docs_apis_placement_jsonplacement_clusterselector]]
*clusterSelector*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*labelSelector* +
__optional__|Selector of `ManagedClusters` by label. |object
|*claimSelector* +
__optional__|Selector of `ManagedClusters` by claim. |<<_rhacm-docs_apis_placement_jsonplacement_clusterclaimselector,clusterClaimSelector>>
|===

[[_rhacm-docs_apis_placement_jsonplacement_clusterclaimselector]]
*clusterClaimSelector*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*matchExpressions* +
__optional__|Subset of the cluster claim selector requirements. The conditional logic is _AND_. |< object > array
|===

[[_rhacm-docs_apis_placement_jsonplacement_prioritizerPolicy]]
*prioritizerPolicy*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*mode* +
__optional__|Either `Exact`, `Additive`, or "". The default value of "" is `Additive`. |string
|*configurations* +
__optional__|Configuration of the prioritizer. |<<_rhacm-docs_apis_placement_jsonplacement_prioritizerConfig,prioritizerConfig>> array
|===

[[_rhacm-docs_apis_placement_jsonplacement_prioritizerConfig]]
*prioritizerConfig*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*scoreCoordinate* +
__required__|Configuration of the prioritizer and score source.|<<_rhacm-docs_apis_placement_jsonplacement_scoreCoordinate,scoreCoordinate>>
|*weight* +
__optional__|Weight of the prioritizer score. The value must be within the range: [-10,10].| int32
|===

[[_rhacm-docs_apis_placement_jsonplacement_scoreCoordinate]]
*scoreCoordinate*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*type* +
__required__|Type of the prioritizer score. Valid values are "BuiltIn" or "AddOn".|string
|*builtIn* +
__optional__|Name of a `BuiltIn` prioritizer from the following options:
1) Balance: Balance the decisions among the clusters.
2) Steady: Ensure the existing decision is stabilized.
3) ResourceAllocatableCPU & ResourceAllocatableMemory: Sort clusters based on the allocatable resources.
4) Spread: Spread the workload evenly to topologies.| string
|*addOn* +
__optional__|When type is `AddOn`, `AddOn` defines the resource name and score name.| object
|===

[[_rhacm-docs_apis_placement_jsonplacement_toleration]]
*toleration*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*key* +
__optional__|Taint key that the toleration applies to. Empty means match all of the taint keys.|string
|*operator* +
__optional__|Relationship of a key to the value. Valid operators are `Exists` and `Equal`. The default value is `Equal`.|string
|*value* +
__optional__|Taint value that matches the toleration.| string
|*effect* +
__optional__|Taint effect to match. Empty means match all of the taint effects. When specified, allowed values are `NoSelect`, `PreferNoSelect`, and `NoSelectIfNew`.| string
|*tolerationSeconds* +
__optional__|Length of time that a taint is tolerated, after which the taint is not tolerated. The default value is nil, which indicates that there is no time limit on how long the taint is tolerated. | int64
|===
