[#policy-api]
= Policy API


[[_rhacm-docs_apis_policy_jsonoverview]]
== Overview
This documentation is for the Policy resource for {product-title}. The Policy resource has four possible requests: create, query, delete and update. 


=== Version information
[%hardbreaks]
__Version__ : 2.5.0


=== Contact information
[%hardbreaks]
__Contact Email__ : apiteam@swagger.io


=== License information
[%hardbreaks]
__License__ : Apache 2.0
__License URL__ : http://www.apache.org/licenses/LICENSE-2.0.html
__Terms of service__ : http://swagger.io/terms/


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS


=== Tags

* policy.open-cluster-management.io/v1 : Create and manage policies


=== External Docs
[%hardbreaks]
__Description__ : Find out more about Swagger.
__URL__ : http://swagger.io




[[_rhacm-docs_apis_policy_jsonpaths]]
== Paths

[[_rhacm-docs_apis_policy_jsoncreatepolicy]]
=== Create a policy
....
POST /policy.open-cluster-management.io/v1/v1alpha1/namespaces/{namespace}/policies/{policy_name}
....


==== Description
Create a policy.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|**Body**|**body** +
__required__|Parameters describing the policy to be created.|<<_rhacm-docs_apis_application_jsonapplication,Application>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `application/json`


==== Tags

* policy.open-cluster-management.io


==== Example HTTP request

===== Request body
[source,json]
----
{
  "apiVersion": "policy.open-cluster-management.io/v1",
  "kind": "Policy",
  "metadata": {
    "name": "test-policy-swagger",
    "description": "Example body for Policy API Swagger docs"
  },
  "spec": {
    "remediationAction": "enforce",
    "namespaces": {
      "include": [
        "default"
      ],
      "exclude": [
        "kube*"
      ]
    },
    "policy-templates": {
    "kind": "ConfigurationPolicy",
    "apiVersion": "policy.open-cluster-management.io/v1",
    "complianceType": "musthave",
    "metadataComplianceType": "musthave",
    "metadata": {
      "namespace": null,
      "name": "test-role"
    },
    "selector": {
      "matchLabels": {
        "cloud": "IBM"
      }
    },
    "spec" : {
      "object-templates": {
        "complianceType": "musthave",
        "metadataComplianceType": "musthave",
        "objectDefinition": {
          "apiVersion": "rbac.authorization.k8s.io/v1",
          "kind": "Role",
          "metadata": {
            "name": "role-policy",
          },
          "rules": [
            {
              "apiGroups": [
                "extensions",
                "apps"
              ],
              "resources": [
                "deployments"
              ],
              "verbs": [
                "get",
                "list",
                "watch",
                "delete"
              ]
            },
            {
              "apiGroups": [
                "core"
              ],
              "resources": [
                "pods"
              ],
              "verbs": [
                "create",
                "update",
                "patch"
              ]
            },
            {
              "apiGroups": [
                "core"
              ],
              "resources": [
                "secrets"
              ],
              "verbs": [
                "get",
                "watch",
                "list",
                "create",
                "delete",
                "update",
                "patch"
              ],
            },
          ],
        },
      },
    },
  },
----


[[_rhacm-docs_apis_policy_jsonquerypolicies]]
=== Query all policies
....
GET /policy.open-cluster-management.io/v1/namespaces/{namespace}/policies/{policy_name}
....


==== Description
Query your policies for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**namespace** +
__required__|Namespace that you want to apply the policy to, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Consumes

* `application/json`


==== Tags

* policy.open-cluster-management.io


[[_rhacm-docs_apis_policy_jsonquerypolicy]]
=== Query a single policy
....
GET /policy.open-cluster-management.io/v1/namespaces/{namespace}/policies/{policy_name}
....


==== Description
Query a single policy for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**policy_name** +
__required__|Name of the policy that you want to query.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* policy.open-cluster-management.io


[[_rhacm-docs_apis_policy_jsondeletepolicy]]
=== Delete a policy
....
DELETE /policy.open-cluster-management.io/v1/namespaces/{namespace}/policies/{policy_name}
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**policy_name** +
__required__|Name of the policy that you want to delete.|string
|**Path**|**namespace** +
__required__|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Success|No Content
|**403**|Access forbidden|No Content
|**404**|Resource not found|No Content
|**500**|Internal service error|No Content
|**503**|Service unavailable|No Content
|===


==== Tags

* policy.open-cluster-management.io




[[_rhacm-docs_apis_policy_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_policy_jsonpolicy]]
=== Policy

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__required__|The versioned schema of Policy. |string
|**kind** +
__required__|String value that represents the REST resource. |string
|**metadata** +
__required__|Describes rules that define the policy.| object
|**spec** +
__required__|<<_rhacm-docs_apis_policy_jsonpolicy_spec,spec>>
|===

[[_rhacm-docs_apis_policy_jsonpolicy_spec]]
**spec**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**remediationAction** +
__optional__|Value that represents how violations are handled as defined in the resource. | string
|**namespaceSelector** +
__required__|Value that represents which namespaces the policy is applied.|string
|<<_rhacm-docs_apis_policy_jsonpolicy_policytemplates, **policy-templates**>> +
__optional__|array
|===

[[_rhacm-docs_apis_policy_jsonpolicy_policytemplates]]
**policy-templates**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**apiVersion** +
__required__|The versioned schema of Policy.| string
|**kind** +
__optional__|String value that represents the REST resource.|string
|**metadata** +
__required__|Describes rules that define the policy. |object
| **complianceType** | Used to list expected behavior for roles and other Kubernetes object that must be evaluated or applied to the managed clusters.| string
| **metadataComplianceType** +
__optional__| Provides a way for users to process labels and annotations of an object differently than the other fields. The parameter value defaults to the same value of the `ComplianceType` parameter.  | string
|<<_rhacm-docs_apis_policy_jsonpolicy_selector,**clusterConditions**>> +
__optional__| Section to define labels.|string
|<<_rhacm-docs_apis_policy_jsonpolicy_rules,**rules**>> +
__optional__| |string
|===

[[_rhacm-docs_apis_policy_jsonpolicy_selector]]
**clusterConditions**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**matchLabels** +
__optional__| The label that is required for the policy to be applied to a namespace.|object
|**cloud** +
__optional__|The label that is required for the policy to be applied to a cloud provider. |string
|===

[[_rhacm-docs_apis_policy_jsonpolicy_rules]]
**rules**

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|**apiGroups** +
__required__| List of APIs that the rule applies to. |string
| **resources** +
__required__| A list of resource types.|object
|**verbs** +
__required__| A list of verbs. |string
|===



