[#search-query-api]
= Search query API

This API is not displayed through the {ocp} API Explorer. Continue reading to understand the Search query API capabilities.  

[[_rhacm-docs_apis_policy_jsonoverview]]
== Overview

This documentation describes how to expose the search API with a route and how to use the API to resolve search queries. The API is a GraphQL endpoint. You can use any client like curl or Postman.

=== Version information
[%hardbreaks]
_Version_ : 2.9.0

=== URI scheme
[%hardbreaks]
_BasePath_ : /searchapi/graphql
_Schemes_ : HTTPS

[[_search_query_api_access]]
=== Configure API access

The search operator must be installed on your managed cluster, and you must have access to the search API external to your cluster. Create a route to access the Search API external from your cluster with the following command:

[source,bash]
----
oc create route passthrough search-api --service=search-search-api -n open-cluster-management
----

==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**COOKIE** +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|**Path**|**cluster_name** +
__required__|Name of the cluster that you want to delete.|string
|===

== Schema design

[source,graphql]
----
input SearchFilter {
  property: String!
  values: [String]!
}
input SearchInput {
  keywords: [String]
  filters: [SearchFilter]
  limit: Int
  relatedKinds: [String]
}
type SearchResult {
count: Int
items: [Map]
related: [SearchRelatedResult]
}
type SearchRelatedResult {
kind: String!
count: Int
items: [Map]
}
----

=== Description table of query inputs
//are there any parameters that are required? 
|===
|Type|Description|Property

| SearchFilter
| Defines a key and value to filter results. When multiple values are provided for a property, it is interpreted as an "OR" operation. When multiple filters are provided, results match all filters and interpreted as an "AND" operation.
| string

| SearchInput
| Enter key words to receive a list of resources. When multiple keywords are provided, it is interpreted as an "AND" operation. 
| String

| limit
| Max number of results returned after entering the query. The default value is `10,000`. A value of `-1` means that the limit is removed.
| Integer
|===

=== Schema example

[source,json]
----
{
  "query": "type SearchResult {count: Intitems: [Map]related: [SearchRelatedResult]} type SearchRelatedResult {kind: String!count: Intitems: [Map]}",
  "variables": {
    "input": [
      {
        "keywords": [],
        "filters": [
          {
            "property": "kind",
            "values": [
              "Deployment"
            ]
          }
        ],
        "limit": 10
      }
    ]
  }
}
----

== Generic schema 

[source,graphql]
----
type Query {
  search(input: [SearchInput]): [SearchResult]
  searchComplete(property: String!, query: SearchInput, limit: Int): [String]
  searchSchema: Map
  messages: [Message]
}
----

== Supported queries

Continue reading to see the query types that are supported in JSON format.

=== Search for deployments

Query:

[source,graphql]
----
query mySearch($input: [SearchInput]) {
    searchResult: search(input: $input) {
    		items
        }
}
----

Variables:

[source,graphql]
----
{"input":[
    {
        "keywords":[],
        "filters":[
            {"property":"kind","values":["Deployment"]}],
        "limit":10
    }
]}
----

=== Search for pods

[source,json]
----
{
  "query": "query mySearch($input: [SearchInput]) { searchResult: search(input: $input) { items }}Variables:{\"input\":[ { \"keywords\":[], \"filters\":[ {\"property\":\"kind\",\"values\":[\"Pod\"]}], \"limit\":10 }]}",
  "variables": {
    "input": [
      {
        "keywords": [],
        "filters": [
          {
            "property": "kind",
            "values": [
              "Pod"
            ]
          }
        ],
        "limit": 10
      }
    ]
  }
}
----
