[#search-query-api]
= Search query API 

[[_rhacm-docs_apis_search_query_jsonoverview]]
== Overview
//it doesn't seem like this is a resource, I'm struggling with this doc
//I didn't see any YAML related to this
This documentation is for using the search query API for {product-title}. The search query API is a GraphQL endpoint that is accessed by using a route and can resolve search queries. The possible requests are query and update.

This endpoint should be created in the Search namespace.


=== Version information
[%hardbreaks]
__Version__ : 2.9.0


=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : Open API


=== Tags

* apiextensions.k8s.io/v1 : Configure the search query API


[[_rhacm-docs_apis_search_jsonpaths]]
== Paths

[[_rhacm-docs_apis_search_jsonconfigurequery]]
=== Configure API access
....
POST /searches.open-cluster-management.io/v1alpha1/namespaces/{namespace}/searches
....


==== Description

Create a route to access the API externally. The search query API is protected by using Kubernetes authentication. You must obtain your {ocp-short} API token and add it to the request as the Authorization header.

==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `search_query/yaml`


==== Tags

* searches.open-cluster-management.io


[[_rhacm-docs_apis_search_query_jsoncreatesearch_query]]
=== Create a query for Kubernetes resources
....
POST /searches.open-cluster-management.io/v1alpha1/namespaces/{namespace}/search_queries
....


==== Description
Create a search query for a deployment.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Body*|*body* +
_required_|Parameters that describe the  to be created.|<<_rhacm-docs_apis_search_query_jsonsearch_query,ManagedClusterAddOn>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `search_query/yaml`


==== Tags

* searches.open-cluster-management.io


==== Example HTTP request

===== Request body
[source,json]
----
query mySearch($input: [SearchInput]) {
    searchResult: search(input: $input) {
    		items
        }
}

{"input":[
    {
        "keywords":[],
        "filters":[
            {"property":"kind","values":["Deployment"]}],
        "limit":10
    }
]}    
----

[[_rhacm-docs_apis_search_query_jsonquerysearch]]
=== Create search query types
....
GET /searches.open-cluster-management.io/v1alpha1/namespaces/{namespace}/search/{search_name}
....


==== Description
Create types for your query results.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*search_name* +
__required__|Name of the type that you want to query.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* addon.open-cluster-management.io


[[_rhacm-docs_apis_search_jsondeletesearch]]
=== Delete a query
....
DELETE /searches.open-cluster-management.io/v1alpha1/namespaces/{namespace}/searches/{search_name}
....


==== Description
Delete a query.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*search_name* +
__required__|Name of the query that you want to delete.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* addon.open-cluster-management.io


[[_rhacm-docs_apis_search_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_search_jsonsearch]]
=== searchResults

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*apiVersion* +
__required__|Versioned schema of the ManagedClusterAddOn. |string
|*kind* +
__required__|String value that represents the REST resource. |string
|*metadata* +
__required__|Metadata of the ManagedClusterAddOn. |object
|*spec* +
__required__|Specification of the ManagedClusterAddOn. |<<_rhacm-docs_apis_search_jsonsearch_spec,spec>>
|===

[[_rhacm-docs_apis_search_jsonsearch_spec]]
*spec*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*installNamespace* +
__optional__|The namespace on the managed cluster to install the add-on agent. If it is not set, the open-cluster-management-agent-addon namespace is used to install the add-on agent. |string
|*configs* +
__optional__|A list of add-on configurations where the current add-on has its own configurations. |<<_rhacm-docs_apis_search_jsonsearch_addOnConfig,addOnConfig>> array
|===

[[_rhacm-docs_apis_search_jsonsearch_addOnConfig]]
*addOnConfig*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*group* +
__optional__|Group of the add-on configuration. |string
|*resource* +
__required__|Resource of the add-on configuration. |string
|*namespace* +
__optional__|Namespace of the add-on configuration. If this field is not set, the configuration is cluster-scope. |string
|*name* +
__required__|Name of the add-on configuration. |string
|===
