[#search-api]
= Search operator API


[[_rhacm-docs_apis_mch_jsonoverview]]
== Overview
This documentation is for the search operator resource for {product-title}. The search operator resource has four possible requests: create, query, delete and update.


=== Version information
[%hardbreaks]
_Version_ : 2.9.0


=== URI scheme
[%hardbreaks]
_BasePath_ : /kubernetes/apis
_Schemes_ : HTTPS


=== Tags

* search.operator.open-cluster-management.io : Create and manage multicluster hub operators


[[_rhacm-docs_apis_mch_jsonpaths]]
== Paths

[[_rhacm-docs_apis_mch_jsoncreatemch]]
=== Create a search resource
....
POST /operator.open-cluster-management.io/v1beta1/namespaces/{namespace}/mch
....


==== Description
Create a Search resource to define the configuration for an instance of the multicluster hub.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
_required_|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*namespace* +
_required_|Namespace that you want to use, for example, default.|string
|*Body*|*body* +
_required_|Parameters describing the multicluster hub to be created.|<<_rhacm-docs_apis_mch_jsondefinitions,Definitions>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `search/yaml`


==== Tags

* search.operator.open-cluster-management.io


==== Example HTTP request
//the yaml is really long, is the entire thing required? 
===== Request body

[source,json]
----
{
  "apiVersion": "apiextensions.k8s.io/v1",
  "kind": "CustomResourceDefinition",
  "metadata": {
    "name": "search.operator.open-cluster-management.io"
    },
  "spec": {
    "group": "operator.open-cluster-management.io",
    "names": {
      "kind": "Search",
      "listKind": "SearchList",
      "plural": "search",
      "shortNames": [
          "mch"
	  ],
     "singular": "multiclusterhub"
     },
    "scope": "Namespaced",
    "versions": [
        {
	    "additionalPrinterColumns": [
                {
		   "description": "The overall status of the multicluster hub.",
                   "jsonPath": ".status.phase",
                   "name": "Status",
                   "type": "string"
		   },
               {
	           "jsonPath": ".metadata.creationTimestamp",
                   "name": "Age",
                   "type": "date"
		   }
            ],
            "name": "v1",
            "schema": {
                "openAPIV3Schema": {
                    "description": "Search defines the configuration for an instance of
          the multiCluster hub.",
        "properties": {
            "apiVersion": {
                "description": "APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
                "type": "string"
            },
            "kind": {
                "description": "Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. The value is in CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
                "type": "string"
            },
            "metadata": {
                "type": "object"
            },
            "spec": {
                "description": "SearchSpec defines the desired state of Search.",
                "properties": {
                    "availabilityConfig": {
                        "description": "Specifies deployment replication for improved availability.
                  Options are: Basic and High (default).",
                        "type": "string"
                },
                "customCAConfigmap": {
                    "description": "Provide the customized OpenShift default ingress CA certificate
                  to {product-title-short}.",
                  }
                    "type": "string"
                },
        "disableHubSelfManagement": {
                    "description": "Disable automatic import of the hub cluster as a managed
                  cluster.",
                    "type": "boolean"
                },
        "disableUpdateClusterImageSets": {
                    "description": "Disable automatic update of ClusterImageSets.",
                    "type": "boolean"
                },
                "hive": {
                    "description": "(Deprecated) Overrides for the default HiveConfig specification.",
                    "properties": {
        "additionalCertificateAuthorities": {
        "description": "(Deprecated) AdditionalCertificateAuthorities is
                      a list of references to secrets in the 'hive' namespace that
                      contain an additional Certificate Authority to use when communicating
                      with target clusters. These certificate authorities are
                      used in addition to any self-signed CA generated by each cluster
                      on installation.",
                           "items": {
                    "description": "LocalObjectReference contains the information
                        to let you locate the referenced object inside the same namespace.",
                    "properties": {
                    "name": {
                        "description": "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
                        "type": "string"
                     }
		             },
                    "type": "object"
                      },
                           "type": "array"
                    },
                       "backup": {
                    "description": "(Deprecated) Backup specifies configuration for backup
                      integration. If absent, backup integration is disabled.",
                    "properties": {
                    "minBackupPeriodSeconds": {
                    "description": "(Deprecated) MinBackupPeriodSeconds specifies
                          that a minimum of MinBackupPeriodSeconds occurs in between
                          each backup. This is used to rate limit backups. This potentially
                          batches together multiple changes into one backup. No backups
                          are lost for changes that happen during the interval
                          that is queued up, and results in a backup once
                          the interval has been completed.",
                    "type": "integer"
                        },
                    "velero": {
                    "description": "(Deprecated) Velero specifies configuration for the Velero backup integration.",
		    "properties": {
			"enabled": {
			    "description": "(Deprecated) Enabled dictates if the Velero backup integration is enabled. If not specified, the default is disabled.",
			    "type": "boolean"
			}
		   },
		    "type": "object"
				        }
				  },
				        "type": "object"
				     },
		    "externalDNS": {
		    "description": "(Deprecated) ExternalDNS specifies configuration for external-dns if it is to be deployed by Hive. If absent, external-dns is not deployed.",
		    "properties": {
		    "aws": {
		    "description": "(Deprecated) AWS contains AWS-specific settings for external DNS.",
		    "properties": {
		        "credentials": {
			    "description": "(Deprecated) Credentials reference a secret that is used to authenticate with AWS Route53. It needs permission to manage entries in each of the managed domains for this cluster. Secret should have AWS keys named 'aws_access_key_id' and 'aws_secret_access_key'.",
			    "properties": {
				"name": {
																		            "description": "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
																		                             "type": "string"
						    }
					},
			    "type": "object"
			}
		},
		   "type": "object"
					},
		   "gcp": {
		   "description": "(Deprecated) GCP contains Google Cloud Platform specific settings for external DNS.",
		   "properties": {
		       "credentials": {
			   "description": "(Deprecated) Credentials reference a secret that is used to authenticate with GCP DNS. It needs permission to manage entries in each of the managed domains for this cluster. Secret should have a key names 'osServiceAccount.json'. The credentials must specify the project to use.",
			   "properties": {
			       "name": {
		   "description": "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
				   "type": "string"
							}
						},
			   "type": "object"
			}
		},
		"type": "object"
					}
				},
				      "type": "object"
					},
		"failedProvisionConfig": {
		"description": "(Deprecated) FailedProvisionConfig is used to configure settings related to handling provision failures.",
		"properties": {
		"skipGatherLogs": {
		"description": "(Deprecated) SkipGatherLogs disables functionality that attempts to gather full logs from the cluster if an installation fails for any reason. The logs are stored in a persistent volume for up to seven days.",
	        "type": "boolean"
				   }
				},
				  "type": "object"
				  },
		"globalPullSecret": {
		"description": "(Deprecated) GlobalPullSecret is used to specify a pull secret that is used globally by all of the cluster deployments. For each cluster deployment, the contents of GlobalPullSecret are merged with the specific pull secret for a cluster deployment(if specified), with precedence given to the contents of the pull secret for the cluster deployment.",
		"properties": {
		"name": {
		"description": "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
		"type": "string"
			                }
				},
				  "type": "object"
							},
		"maintenanceMode": {
	        "description": "(Deprecated) MaintenanceMode can be set to true to disable the Hive controllers in situations where you need to ensure nothing is running that adds or act upon finalizers on Hive types. This should rarely be needed. Sets replicas to zero for the 'hive-controllers' deployment to accomplish this.",
				  "type": "boolean"
							}
						},
			  "required": [
				         "failedProvisionConfig"
						     ],
			  "type": "object"
						 },
		"imagePullSecret": {
		    "description": "Override pull secret for accessing Search operand and endpoint images.",
		    "type": "string"
					},
		"ingress": {
		    "description": "Configuration options for ingress management.",
		    "properties": {
			"sslCiphers": {
	"description": "List of SSL ciphers enabled for management ingress. Defaults to full list of supported ciphers.",
			    "items": {
		    "type": "string"
					},
			    "type": "array"
						}
					},
			       "type": "object"
						},
			   "nodeSelector": {
		   "additionalProperties": {
				   "type": "string"
						},
			       "description": "Set the node selectors..",
			       "type": "object"
			},
			   "overrides": {
			       "description": "Developer overrides.",
			       "properties": {
		   "imagePullPolicy": {
		   "description": "Pull policy of the multicluster hub images.",
			               "type": "string"
							}
						},
			      "type": "object"
									},
		   "separateCertificateManagement": {
				     "description": "(Deprecated) Install cert-manager into its own namespace.",
				     "type": "boolean"
						    }
					   },
			   "type": "object"
		       },
		       "status": {
			 "description": "MulticlusterHubStatus defines the observed state of Search.",
			 "properties": {
			     "components": {
		      "additionalProperties": {
		      "description": "StatusCondition contains condition information.",
				      "properties": {
		      "lastTransitionTime": {
		      "description": "LastTransitionTime is the last time the condition changed from one status to another.",
		      "format": "date-time",
		      "type": "string"
					},
		      "message": {
		      "description": "Message is a human-readable message indicating\ndetails about the last status change.",
		      "type": "string"
						},
				          "reason": {
		      "description": "Reason is a (brief) reason for the last status change of the condition.",
		      "type": "string"
						},
					  "status": {
		      "description": "Status is the status of the condition. One of True, False, Unknown.",
		      "type": "string"
					},
					  "type": {
		      "description": "Type is the type of the cluster condition.",
		      "type": "string"
					}
				},
				     "type": "object"
						      },
				  "description": "Components []ComponentCondition `json:\"manifests,omitempty\"`",
				  "type": "object"
							},
			      "conditions": {
				  "description": "Conditions contain the different condition statuses for the Search.",
				  "items": {
		      "description": "StatusCondition contains condition information.",
				      "properties": {
		      "lastTransitionTime": {
		      "description": "LastTransitionTime is the last time the condition changed from one status to another.",
		      "format": "date-time",
		      "type": "string"
					},
		      "lastUpdateTime": {
		      "description": "The last time this condition was updated.",
		      "format": "date-time",
		      "type": "string"
					},
		      "message": {
		      "description": "Message is a human-readable message indicating details about the last status change.",
		      "type": "string"
						},
				          "reason": {
		      "description": "Reason is a (brief) reason for the last status change of the condition.",
		      "type": "string"
					},
					  "status": {
		      "description": "Status is the status of the condition. One of True, False, Unknown.",
		      "type": "string"
						},
					  "type": {
		      "description": "Type is the type of the cluster condition.",
		      "type": "string"
					}
				},
				     "type": "object"
						      },
				 "type": "array"
					},
			     "currentVersion": {
				 "description": "CurrentVersion indicates the current version..",
				 "type": "string"
						},
			     "desiredVersion": {
				 "description": "DesiredVersion indicates the desired version.",
				 "type": "string"
						 },
			     "phase": {
				 "description": "Represents the running phase of the Search",
				 "type": "string"
							}
						},
	                 "type": "object"
					   }
				   },
                "type": "object"
			        }
		         },
        "served": true,
        "storage": true,
        "subresources": {
	    "status": {}
	    }
	}
    ]
  }
}
----


[[_rhacm-docs_apis_mch_jsonqueryoperator]]
=== Query all Searches
....
GET /operator.open-cluster-management.io/v1beta1/namespaces/{namespace}/operator
....


==== Description
Query your multicluster hub operator for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
_required_|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*namespace* +
_required_|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Consumes

* `operator/yaml`


==== Tags

* search.operator.open-cluster-management.io


[[_rhacm-docs_apis_mch_jsonquery_mch_operator]]
=== Query a Search operator
....
GET /operator.open-cluster-management.io/v1beta1/namespaces/{namespace}/operator/{multiclusterhub_name}
....


==== Description
Query a single multicluster hub operator for more details.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
_required_|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*application_name* +
_required_|Name of the application that you wan to query.|string
|*Path*|*namespace* +
_required_|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* search.operator.open-cluster-management.io


[[_rhacm-docs_apis_mch_jsondeleteoperator]]
=== Delete a Search operator
....
DELETE /operator.open-cluster-management.io/v1beta1/namespaces/{namespace}/operator/{multiclusterhub_name}
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
_required_|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*application_name* +
_required_|Name of the multicluster hub operator that you want to delete.|string
|*Path*|*namespace* +
_required_|Namespace that you want to use, for example, default.|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===


==== Tags

* search.operator.open-cluster-management.io




[[_rhacm-docs_apis_mch_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_mch_json_parameters]]
=== Multicluster hub operator

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*apiVersion* +
_required_| The versioned schema of the Search. |string
|*kind* +
_required_|String value that represents the REST resource. |string
|*metadata* +
_required_|Describes rules that define the resource.|object
|*spec* +
_required_|The resource specification. | <<_rhacm-docs_apis_mch_jsonoperator_spec,spec>>
|===


[[_rhacm-docs_apis_mch_jsonoperator_spec]]
*spec*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|*availabilityConfig* +
_optional_|Specifies deployment replication for improved availability. The default value is `High`. |string
|*customCAConfigmap* +
_optional_|Provide the customized OpenShift default ingress CA certificate to {product-title-short}. |string
|*disableHubSelfManagement* +
_optional_|Disable automatic import of the hub cluster as a managed cluster. |boolean
|*disableUpdateClusterImageSets* +
_optional_|Disable automatic update of ClusterImageSets. |boolean
|*hive* +
_optional_|(Deprecated) An object that overrides for the default HiveConfig specification. |<<_rhacm-docs_apis_mch_jsonoperator_hive,hive>>
|*imagePullSecret* +
_optional_| Overrides pull secret for accessing Search operand and endpoint images. |string
|*ingress* +
_optional_| Configuration options for ingress management. |<<_rhacm-docs_apis_mch_jsonoperator_ingress,ingress>>
|*nodeSelector* +
_optional_|Set the node selectors. |string
|*separateCertificateManagement* +
_optional_| (Deprecated) Install `cert-manager` into its own namespace. |boolean
|===

// deprecated items remain for 3 major releases 
[[_rhacm-docs_apis_mch_jsonoperator_hive]]
*hive*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|*additionalCertificateAuthorities* +
_optional_|(Deprecated) A list of references to secrets in the `hive` namespace that contain an additional Certificate Authority to use when communicating with target clusters. These certificate authorities are used in addition to any self-signed CA generated by each cluster on installation. |object
|*backup* +
_optional_|(Deprecated) Specifies the configuration for backup integration. If absent, backup integration is disabled. |<<_rhacm-docs_apis_mch_jsonoperator_backup,backup>>
|*externalDNS* +
_optional_| (Deprecated) Specifies configuration for `external-dns` if it is to be deployed by Hive. If absent, `external-dns` is not be deployed. |object
|*failedProvisionConfig* +
_required_| (Deprecated) Used to configure settings related to handling provision failures. |<<_rhacm-docs_apis_mch_jsonoperator_failedProvision,failedProvisionConfig>>
|*globalPullSecret* +
_optional_| (Deprecated) Used to specify a pull secret that is used globally by all of the cluster deployments. For each cluster deployment, the contents of `globalPullSecret` are merged with the specific pull secret for a cluster deployment (if specified), with precedence given to the contents of the pull secret for the cluster deployment. |object
|*maintenanceMode* +
_optional_| (Deprecated) Can be set to true to disable the hive controllers in situations where you need to ensure nothing is running that adds or acts upon finalizers on Hive types. This should rarely be needed. Sets replicas to `0` for the `hive-controllers` deployment to accomplish this.| boolean
|===

[[_rhacm-docs_apis_mch_jsonoperator_ingress]]
*ingress*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|*sslCiphers* +
_optional_| List of SSL ciphers enabled for management ingress. Defaults to full list of supported ciphers. |string
|===


[[_rhacm-docs_apis_mch_jsonoperator_backup]]
*backup*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|*minBackupPeriodSeconds* +
_optional_| (Deprecated) Specifies that a minimum of `MinBackupPeriodSeconds` occurs in between each backup. This is used to rate limit backups. This potentially batches together multiple changes into one backup. No backups are lost as changes happen during this interval are queued up and result in a backup happening once the interval has been completed. |integer
|*velero* + 
_optional_| (Deprecated) Velero specifies configuration for the Velero backup integration.|object
|===


[[_rhacm-docs_apis_mch_jsonoperator_failedProvision]]
*failedProvisionConfig*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|*skipGatherLogs* +
_optional_| (Deprecated) Disables functionality that attempts to gather full logs from the cluster if an installation fails for any reason. The logs are stored in a persistent volume for up to seven days. |boolean
|===


[[_rhacm-docs_apis_mch_jsonoperator_status]]
*status*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|*components* +
_optional_|The components of the status configuration. |object
|*conditions* +
_optional_|Contains the different conditions for the multicluster hub. | <<_rhacm-docs_apis_mch_jsonoperator_conditions,conditions>>
|*desiredVersion* +
_optional_| Indicates the desired version. |string
|*phase* +
_optional_| Represents the active phase of the Search resource. The values that are used for this parameter are: `Pending`, `Running`, `Installing`, `Updating`, `Uninstalling` |string
|===

[[_rhacm-docs_apis_mch_jsonoperator_conditions]]
*conditions*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|*lastTransitionTime* +
_optional_| The last time the condition changed from one status to another. |string
|*lastUpdateTime* +
_optional_|The last time this condition was updated.|string
|*message* +
_required_|Message is a human-readable message indicating details about the last status change.|string
|*reason* +
_required_|A brief reason for why the condition status changed.|string
|*status* +
_required_|The status of the condition.|string
|*type* +
_required_|The type of the cluster condition.|string
|===

[[_rhacm-docs_apis_mch_jsonoperator_statusconditions]]
*StatusConditions*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|*kind* +
_required_| The resource `kind` that represents this status.|string
|*available* +
_required_|Indicates whether this component is properly running.|boolean
|*lastTransitionTime* +
_optional_| The last time the condition changed from one status to another. |metav1.time
|*lastUpdateTime* +
_optional_|The last time this condition was updated.|metav1.time
|*message* +
_required_|Message is a human-readable message indicating details about the last status change.|string
|*reason* +
_optional_|A brief reason for why the condition status changed.|string
|*status* +
_optional_|The status of the condition.|string
|*type* +
_optional_|The type of the cluster condition.|string
|===