[#creating-a-credential-for-microsoft-azure]
= Creating a credential for Microsoft Azure

You need a credential to use {product-title} console to create and manage a {ocp} cluster on Microsoft Azure or on Microsoft Azure Government.

**Required access**: Edit

*Note:* This procedure is a prerequisite for creating a cluster with {product-title}.

[#azure_cred_prerequisites]
== Prerequisites

You must have the following prerequisites before creating a credential:

* A deployed {product-title} hub cluster.
* Internet access for your {product-title} hub cluster so that it can create the Kubernetes cluster on Azure.
* Azure login credentials, which include your Base Domain Resource Group and Azure Service Principal JSON. See https://azure.microsoft.com/en-ca/features/azure-portal[azure.microsoft.com].
* Account permissions that allow installing clusters on Azure.
See https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-how-to-configure-portal[How to configure Cloud Services] and https://docs.openshift.com/container-platform/4.11/installing/installing_azure/installing-azure-account.html[Configuring an Azure account] for more information.

[#azure_cred]
== Managing a credential by using the console

To create a credential from the {product-title} console, complete the steps in the console. Start at the navigation menu. Click *Credentials* to choose from existing credential options. *Tip:* Create a namespace specifically to host your credentials, both for convenience and added security.

. *Optional:* Add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential.
. Select whether the environment for your cluster is `AzurePublicCloud` or `AzureUSGovernmentCloud`. The settings are different for the the Azure Government environment, so ensure that this is set correctly. 
. Add your _Base domain resource group name_ for your Azure account. This entry is the resource name that you created with your Azure account.
You can find your Base Domain Resource Group Name by selecting *Home* > *DNS Zones* in the Azure interface. See https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli[Create an Azure service principal with the Azure CLI] to find your base domain resource group name.

. In the {product-title-short}, provide the contents for your _Client ID_. This value is generated as the `appId` property when you create a service principal with the following command: 
+
----
az ad sp create-for-rbac --role Contributor --name <service_principal>
----
Replace _service_principal_ with the name of your service principal.
. Add your _Client Secret_. This value is generated as the `password` property when you create a service principal with the following command:
+
----
az ad sp create-for-rbac --role Contributor --name <service_principal>
----
Replace _service_principal_ with the name of your service principal.
. Add your _Subscription ID_. This value is the `id` property in the output of the following command:
+
----
az account show
----
. Add your _Tenant ID_. This value is the `tenantId` property in the output of the following command:
+
----
az account show
----

. [[proxy-azure]]If you want to enable a proxy, enter the proxy information: 
+
* HTTP proxy URL: The URL that should be used as a proxy for `HTTP` traffic. 

* HTTPS proxy URL: The secure proxy URL that should be used for `HTTPS` traffic. If no value is provided, the same value as the `HTTP Proxy URL` is used for both `HTTP` and `HTTPS`. 

* No proxy domains: A comma-separated list of domains that should bypass the proxy. Begin a domain name with a period `.` to include all of the subdomains that are in that domain. Add and asterisk `*` to bypass the proxy for all destinations. 

* Additional trust bundle: The contents of the certificate file that is required to access the mirror registry.

. Enter your _Red Hat OpenShift pull secret_. You can download your pull secret from https://cloud.redhat.com/openshift/install/pull-secret[Pull secret].

. Add your _SSH private key_ and _SSH public key_ to use to connect to the cluster. You can use an existing key pair, or create a new pair using a key generation program. See https://docs.openshift.com/container-platform/4.11/installing/installing_azure/installing-azure-default.html#ssh-agent-using_installing-azure-default[Generating an SSH private key and adding it to the agent] for more information about how to generate a key.

You can create a cluster that uses this credential by completing the steps in link:../multicluster_engine/create_azure.adoc#creating-a-cluster-on-microsoft-azure[Creating a cluster on Microsoft Azure].

You can edit your credential in the console. 

When you are no longer managing a cluster that is using a credential, delete the credential to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.
