[#creating-a-credential-for-virtualization]
= Creating a credential for Red Hat Virtualization

You need a credential to use {product-title} console to deploy and manage a {ocp} cluster on Red Hat Virtualization. 

*Note:* This procedure must be done before you can create a cluster with {product-title-short}.

[#virtualization-credential-prerequisites]
== Prerequisites

You must have the following prerequisites before you create a credential:

* A deployed {product-title-short} hub cluster on {ocp-short} version 4.7 or later.
* Internet access for your {product-title-short} hub cluster so it can create the Kubernetes cluster on Red Hat Virtualization.
* Red Hat Virtualization login credentials for a configured Red Hat Virtualization environment.
See https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.0/html-single/installation_guide/index[Installation Guide] in the Red Hat Virtualization documentation. The following list shows the required information:
** oVirt URL
** oVirt fully-qualified domain name (FQDN)
** oVirt username
** oVirt password
** oVirt CA/Certificate
* Optional: Proxy information, if you are enabling a proxy. 
* {ocp} pull secret information. You can download your pull secret from https://cloud.redhat.com/openshift/install/pull-secret[Pull secret].
* SSH private and public keys for transferring information for the final cluster. 
* Account permissions that allow installing clusters on oVirt.

[#virtualization-credential]
== Managing a credential by using the console

To create a credential from the {product-title} console, complete the steps in the console. 

Start at the navigation menu. Click *Credentials* to choose from existing credential options. *Tip:* Create a namespace specifically to host your credentials, for both convenience and added security.

. Add the basic information for your new credential. You can optionally add a Base DNS domain, which is automatically populated in the correct field when you create a cluster with this credential. If you do not add it to the credential, you can add it when you create the cluster.

. Add the required information for your Red Hat Virtualization environment. 

. [[proxy-virtualization]]If you want to enable a proxy, enter the proxy information: 
+
* HTTP Proxy URL: The URL that should be used as a proxy for `HTTP` traffic. 

* HTTPS Proxy URL: The secure proxy URL that should be used when using `HTTPS` traffic. If no value is provided, the same value as the `HTTP Proxy URL` is used for both `HTTP` and `HTTPS`. 

* No Proxy domains: A comma-separated list of domains that should bypass the proxy. Begin a domain name with a period `.` to include all of the subdomains that are in that domain. Add and asterisk `*` to bypass the proxy for all destinations. 

. Enter your {ocp} pull secret. You can download your pull secret from https://cloud.redhat.com/openshift/install/pull-secret[Pull secret].

. Add your SSH Private Key and SSH Public Key, which allows you to connect to the cluster. You can use an existing key pair, or create a new one with a key generation program. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/installing-on-rhv#ssh-agent-using_installing-rhv-default[Generating akey pair for cluster node SSH access] for more information.

. Review the new credential information, then click *Add*. When you add the credential, it is added to the list of credentials.

You can create a cluster that uses this credential by completing the steps in link:../multicluster_engine/create_virtualization.adoc#creating-a-cluster-on-virtualization[Creating a cluster on Red Hat Virtualization].

You can edit your credential in the console. 

When you are no longer managing a cluster that is using a credential, delete the credential to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.
