[#creating-a-credential-for-amazon-web-services]
= Creating a credential for Amazon Web Services

You need a credential to use {product-title} console to deploy and manage an {ocp} cluster on Amazon Web Services (AWS).

**Required access**: Edit

*Note:* This procedure must be done before you can create a cluster with {product-title}.

[#aws_cred_prereqs]
== Prerequisites

You must have the following prerequisites before creating a credential:

* A deployed {product-title} hub cluster
* Internet access for your {product-title} hub cluster so it can create the Kubernetes cluster on Amazon Web Services (AWS)
* AWS login credentials, which include access key ID and secret access key.
See https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html[Understanding and getting your security credentials].
* Account permissions that allow installing clusters on AWS.
See https://docs.openshift.com/container-platform/4.11/installing/installing_aws/installing-aws-account.html[Configuring an AWS account] for instructions on how to configure.

[#aws_cred_create]
== Managing a credential by using the console

To create a credential from the {product-title} console, complete the steps in the console. 

Start at the navigation menu. Click *Credentials* to choose from existing credential options. *Tip:* Create a namespace specifically to host your credentials, both for convenience and added security.

You can optionally add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential. See the following steps:

. Add your _AWS access key ID_ for your AWS account. Log in to https://console.aws.amazon.com/iam/home#/security_credentials[AWS] to find your ID.
. In the {product-title-short}, provide the contents for your new _AWS Secret Access Key_.
. [[proxy-aws]]If you want to enable a proxy, enter the proxy information: 
+
* HTTP proxy URL: The URL that should be used as a proxy for `HTTP` traffic. 

* HTTPS proxy URL: The secure proxy URL that should be used for `HTTPS` traffic. If no value is provided, the same value as the `HTTP Proxy URL` is used for both `HTTP` and `HTTPS`. 

* No proxy domains: A comma-separated list of domains that should bypass the proxy. Begin a domain name with a period `.` to include all of the subdomains that are in that domain. Add and asterisk `*` to bypass the proxy for all destinations. 

* Additional trust bundle: The contents of the certificate file that is required to access the mirror registry.
. Enter your _Red Hat OpenShift pull secret_. You can download your pull secret from https://cloud.redhat.com/openshift/install/pull-secret[Pull secret].
. Add your _SSH private key_ and _SSH public key_, which allows you to connect to the cluster. You can use an existing key pair, or create a new one with key generation program.

See https://docs.openshift.com/container-platform/4.11/installing/installing_aws/installing-aws-default.html#ssh-agent-using_installing-aws-default[Generating an SSH private key and adding it to the agent] for more information about how to generate a key.

You can create a cluster that uses this credential by completing the steps in link:../multicluster_engine/create_ocp_aws.adoc#creating-a-cluster-on-amazon-web-services[Creating a cluster on Amazon Web Services].

You can edit your credential in the console. If the cluster was created by using this provider connection, then the `<cluster-name>-aws-creds>` secret from `<cluster-namespace>` will get updated with the new credentials.

*Note:* Updating credentials does not work for cluster pool claimed clusters.

When you are no longer managing a cluster that is using a credential, delete the credential to protect the information in the credential. Select *Actions* to delete in bulk, or select the options menu beside the credential that you want to delete.
