[#managing-cluster-labels]
= Managing cluster labels

Add a label to your cluster to select group resources.
See link:https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[Labels and Selectors] for more information.

You can add new labels, remove existing labels, and edit existing labels for your clusters.
Complete the following steps to manage your labels:

. From the navigation menu, click *Automate infrastructure* > *Clusters*.
. Find your cluster in the _Clusters_ table.
. Click the *Options* icon to see more.
. Click *Edit Labels*.
. From the _Manage Labels_ dialog box, assign your label a value.
After you assign a value, your label might resemble the following:

----
  environment=Dev
----

. Click *Save*.

* If you want to remove an existing label, select a label and click the *Remove an item* icon.
* If you want to update an existing label, select and edit the label.
After editing your label, click the *Add a new item* icon.
+
Your label is updated.
+
Your created labels appear in the _Labels_ column.

*Note* You can also edit a cluster label from the cluster _Overview_ page by clicking *Actions* > *Edit labels* or the _Label edit_ button.

Learn more about the Red Hat Advanced Cluster Management for Kubernetes console, see link:console_intro.md.adoc[Web console].