[#managing-cluster-labels]
= Managing cluster labels

Add a label to your cluster to select group resources.
See link:https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[Labels and Selectors] for more information.

You can add new labels, remove existing labels, and edit existing labels for your clusters.
Complete the following steps to manage your labels:

. From the navigation menu, click *Automate infrastructure* > *Clusters*.
. Find your cluster in the _Clusters_ table.
. Click the *Options* icon to see more.
. Click *Edit Labels*.
. From the _Edit Labels_ dialog box, enter a label. Your entry might resemble the following content: Key=Value`. 
. Hit enter or space to add additional labels.
. Click *Add*, then click *Done*.

* If you want to remove an existing label, select a label and click the *Remove* icon.
* If you want to update an existing label, you can reassign it's key to a new value using the method above.

*Note*: You can also edit a cluster label from a cluster's _Overview_ page. From the navigation menu, click *Automate infrastructure* > *Clusters*. 
From the *Clusters* view, access a cluster's overview page by clicking the cluster's name, then *Actions**> *Edit labels*.

Learn more about the Red Hat Advanced Cluster Management for Kubernetes console, see xref:../console/console_intro.adoc#web-console[Web console].
