[#observability-in-the-console]
= Observability in the console

Learn more about console components that you can use to view, manage, or customize your console.

[#red-hat-advanced-cluster-management-for-kubernetes-console-components]
== Red Hat Advanced Cluster Management for Kubernetes console components

Red Hat Advanced Cluster Management for Kubernetes console components:

* <<access-your-console,Access your console>>
* <<welcome-page,Welcome page>>
* <<observe-environment-details,Observe environment details>>
* <<automate-infrastructure,Automate Infrastructure>>
* <<manage-applications,Manage applications>>
* <<topology-page,Topology page>>
* <<governance-and-risk-dashboard,Governance and risk dashboard>>

To learn about Search, see xref:search.adoc[Search in the console]

[#access-your-console]
== Access your console

* Access from the Red Hat OpenShift console:
 .. From the left-hand navigation, click *Networking* > *Routes*
 .. From the _Project_ menu, select the namespace where Red Hat Advanced Cluster Management for Kubernetes is installed.
 .. Find `multicloud-console` and click the URL from the `Location` column.
* Access the console from the Red Hat OpenShift CLI:
 .. While logged in to OpenShift, run the following command to find the route, where `<namespace-from-install>` is the namespace where you installed Red Hat Advanced Cluster Management for Kubernetes:

+
----
oc get routes -n <namespace-from-install>
----
 .. Find the `multicloud-console` name and the `Host/Port` columns to get your URL.

[#welcome-page]
== Welcome page

From the Red Hat Advanced Cluster Management for Kubernetes Welcome page, you get more information about the product and you can access header features, such as _Search_ and _Create resource_.
When you select _Create resource_, you can create a YAML file or JSON file for a deployment.
Also from the _Header_, you can click the *Help* (?) icon to view the _About_ page and the documentation.
From the _User_ menu, you can access the _Configure Client_ page.
Additionally, you can access the xref:vwt_search.adoc[Visual Web Terminal] from the header.

[#observe-environment-details]
== Observe environment details

Reorganize your dashboard.
You can personalize your view of the Overview dashboard by reorganizing the resource overview cards.
You can view the following information about your clusters:

* Name of the cloud service with the number of clusters
* Cluster compliance
* Pod details
* Pod status
* Cluster resources (VCPU/Memory usage)
* Storage usage

Additionally, the Heatmap displays color-coordinated boxes that represent the VCPU usage threshold of your nodes.

[#filtering-your-results]
=== Filtering your results

You can personalize your view of the page by using the filtering feature.
Click *Filter results* to specify what information is displayed on your page.

[#automate-infrastructure]
== Automate infrastructure

Create clusters or import existing clusters.
Scale up or down and delete clusters as needed.
For more information, see xref:../manage_cluster/intro.adoc[Managing your clusters with Red Hat Advanced Cluster Management for Kubernetes]

[#manage-applications]
== Manage applications

Click *New application* to edit a `.yaml` file and create your application.
Click Resources to view the information of each application.
For more information about application resources, see xref:../manage_applications/app_management_overview.adoc[Managing applications].

[#viewing-your-pod-health]
=== Viewing your pod health

View the pod health for all of your clusters by expanding the Heatmap.

Click *Show details* to view the map.
The size of the color-coordinated boxes represents the number of nodes on your cluster.
Hover your cursor over the box to view the response time of your cluster.

[#topology-page]
== Topology page

The Topology page uses information from Weave Scope probe to display Kubernetes objects within a cluster.
You can view hub cluster resources.
As you configure managed clusters, you see more clusters in the Topology view.

To reduce the graphics on the page, you can filter the view by Clusters, Namespaces, and Labels.
You can also filter the design by selecting the icon that represents the Kubernetes objects.

Learn more about the tabs that are available from the Topology page:

* Clusters: You can monitor your cluster network, object network, and security policies in a graphical format.
View your hub clusters, all your managed clusters, and monitor security violations.
* Policies: View the policy, policy placement, and clusters that are being validated.
Check for violations for the selected policy.

[#governance-and-risk-dashboard]
== Governance and risk dashboard

Use the Governance and risk dashboard to create and manage policies and policy controllers.
For more information, see xref:../security/compliance_intro.adoc[Governance and risk].
