[#accessing-your-console]
= Accessing your console

The {product-title} web console is integrated with the {ocp} web console as a console plug-in. You can access {product-title-short} within the {ocp-short} console from the cluster switcher by selecting *All Clusters*. The cluster switcher is a drop-down menu that initially displays `local-cluster`.

Select `local-cluster` when you want to use {ocp-short} console features on the cluster where you installed {product-title-short}. Select *All Clusters* when you want to use {product-title-short} features to manage your fleet of clusters.

If the cluster switcher is not present, the required console plug-ins might not be enabled. For new installations, the console plug-ins are enabled by default. If you upgraded from a previous version of {product-title-short} and want to enable the plug-ins, or if you want to disable the plug-ins, complete the following steps:

. To disable the plug-in, be sure you are in the _Administrator_ perspective in the {ocp-short} console.
. Find *Administration* in the navigation and click *Cluster Settings*, then click the _Configuration_ tab. 
. From the list of _Configuration resources_, click the **Console** resource with the `operator.openshift.io` API group, which contains cluster-wide configuration for the web console. 
. Select the _Console plug-ins_ tab. Both the `acm` and `mce` plug-ins are listed. 
. Modify plug-in status from the table. In a few moments, you are prompted to refresh the console.

*Note:* To enable and disable the console, see link:../install/adv_config_install.adoc#advanced-config-hub[MultiClusterHub advanced] for information.

To learn more about the {product-title} console, see xref:../console/console.adoc#console-overview[Console overview].
