[#accessing-your-console]
= Accessing your console

From the Red Hat OpenShift Container Platform web console, you can access the {product-title} console.
You can also access the console from your terminal after installation.
See all the options for accessing your console.

[#from-the-openshift-container-platform-web-console]
== From the OpenShift Container Platform web console

* You can click the *Application launcher* in the header and choose the _{product-title}_ option.
* You can also access the console from the left-hand navigation.
 ** Click *Networking* > *Routes*
 ** From the _Project_ menu, select the namespace where {product-title} is installed.
 ** Find `multicloud-console` and click the URL from the `Location` column.

[#from-the-red-hat-openshift-cli]
== From the Red Hat OpenShift CLI:

. While logged in to Red Hat OpenShift and after you install {product-title}, run the following command to find the route.
Here, `<namespace-from-install>` is the namespace where you installed the product:

----
  oc get routes -n <namespace-from-install>
----

. Find the `multicloud-console` name and the `Host/Port` columns to get your URL.

Learn more about the {product-title} console see, xref:../console/console_intro.adoc#web-console[Web console].
