[#accessing-your-console]
= Accessing your console

From the {ocp} web console, you can access the {product-title} console. You can also access the console from your terminal after installation. See all the options for accessing your console.

[#from-the-openshift-container-platform-web-console]
== From the OpenShift Container Platform web console

* *{ocp-short} 4.10 Technology Preview:* See the {ocp-short} documentation about https://docs.openshift.com/container-platform/4.10/web_console/dynamic-plug-ins.html#dynamic-plug-ins_dynamic-plug-ins[Adding a dynamic plug-in to the OpenShift Container Platform web console] to create and deploy a dynamic plug-in on your cluster that is loaded at run-time.

* For {ocp-short} 4.8 and later, you can launch {product-title-short} from the perspective switcher near the navigation menu. *Note:* Only for _earlier_ versions of {ocp-short}, you can click the *Application launcher* in the header and choose the _{product-title}_ option.

* You can also access the console from the left-hand navigation:

 ** Click *Networking* > *Routes*, then click on the URL from the _Location_ column. 
 ** From the _Project_ menu, select the namespace where {product-title} is installed. The default namespace is `open-cluster-management`.
 ** Click the `multicloud-console` URL from the _Location_ column.

[#from-the-red-hat-openshift-cli]
== From the Red Hat OpenShift CLI:

. While logged in to {ocp} and after you install {product-title}, run the following command to find the route.
Here, `<namespace-from-install>` is the namespace where you installed the product:

----
oc get routes -n <namespace-from-install>
----

. Find the `open-cluster-management` name and the `Host/Port` columns to get your URL.

Learn more about the {product-title} console, see xref:../console/console_intro.adoc#web-console[Web console].
