[#enable-vm-observability]
= Enabling virtual machine observability fields

By enabling observability fields on your virtual machine, you can more easily find virtual machine metrics on the {acm-short} and the {ocp-virt} consoles. 

If you have observability installed on your hub cluster, then you can access the observability fields on the {acm-short} console by completing either of the following sections. 

[#enable-vm-observability-vm-page]
== Enabling virtual machine observability fields through the virtual machine page

Access the observability fields through the virtual machine page by completing the following steps: 

. On the {acm-short} console, go to the `Virtual Machine` page. 
. On the `Grafana` dashboard, select the `Executive` dashboard then the `Clusters Overview` tab. 
. View the virtual machines available in your environment and enable the observability fields for your selected virtual machines. 

[#enable-vm-observability-vm-page]
== Enabling virtual machine observability fields through the _Launch links_ table cell 

Access the observability fields through the `Launch links` table cell by completing the following steps: 

. On the {acm-short} console, go to the `Launch links` table cell. 
. On the `Grafana` dashboard, select the `Executive` dashboard then the `Single Virtual Machine View` tab. 
. View the single, selected virtual machine and enable the observability fields for it. 