[#enable-vm-actions]
= Enabling virtual machine actions (Technology Preview)

To view `VirtualMachine` resources across all the clusters that {acm} manages, use the Search feature to list and filter the `VirtualMachine` resources created with the {ocp-virt}. You can also enable the following actions from the {acm-short} console on your `VirtualMachine` resources:

- Start
- Stop
- Restart
- Pause
- Unpause

*Required access:* Cluster administrator

[#vm-actions-prereq]
== Prerequisites

Confirm that the _ManagedServiceAccount_ add-on is enabled. See link:../clusters/install_upgrade/adv_config_install.adoc#serviceaccount-addon[ManagedServiceAccount add-on].

[#enable-actions-acm]
== Enabling virtual machine actions for {acm-short}

You can enable the virtual machine actions for {acm-short} by adding the `virtual-machine-preview=true` annotation to the search operator. Run the following command to add the annotation:

[source,bash]
----
oc annotate search search-v2-operator -n open-cluster-management virtual-machine-preview='true' - [ ]
----

You can verify that virtual machines actions for {acm-short} are enabled by checking the search operator status:

[source,yaml]
----
status:
  conditions:
    - lastTransitionTime: '2024-12-09T20:14:18Z'
      message: Virtual machine actions are enabled.
      reason: None
      status: 'True' 
      type: VirtualMachineActionsReady
----

[#disable-vm-actions]
== Disabling virtual machine actions

To disable virtual machine actions for {acm-short}, run the following command:

[source,bash]
----
oc patch configmap console-mce-config -n multicluster-engine -p '{"data": {"VIRTUAL_MACHINE_ACTIONS": "disabled"}}'
----

The virtual machine actions are disabled for {acm-short}.

[#delete-vm-actions]
== Deleting ManagedServiceAccounts and ClusterPermissions resources

To delete `ManagedServiceAccounts` and `ClusterPermissions` resources that use virtual machine actions, complete the following steps:

. To delete the resources, run the following command:

+
[source,bash]
----
oc delete managedserviceaccount,clusterpermission -A -l app=search
----
+
You might receive the following output:

+
[source,bash]
----
managedserviceaccount.authentication.open-cluster-management.io "vm-actor" deleted managedserviceaccount.authentication.open-cluster-management.io "vm-actor" deleted clusterpermission.rbac.open-cluster-management.io "vm-actions" deleted clusterpermission.rbac.open-cluster-management.io "vm-actions" deleted
----

. To confirm that the clean up is complete, run the following command:

+
[source,bash]
----
oc get managedserviceaccount,clusterpermission -A -l app=search
----

+
When the resources are deleted successfully, you receive the following message:

+
[source,bash]
----
"No resources found"
----

The `ManagedServiceAccounts` and `ClusterPermissions` resources are deleted.
