[#search-in-the-console]
= Search in the console

For {product-title}, search provides visibility into your resources across all of your clusters. Search uses Redisgraph (`redisgraph-tls`), an in-memory database, to store the Kubernetes resources and the resource relationships. Create a `searchcustomization` custom resource (CR) to define the storage settings for search persistence. 

[#search-customization]
== Search customization

When you install {product-title-short}, the product is configured to persist search index. The volume is used in the `search-redisgraph` `statefulset` definition with the volume name `persist`. Update the storage settings for search by updating the `searchcustomization` CR. Search customization is namespace-scoped and located where search is installed in the hub cluster. 

If your cluster has a defined default storage class, the search component creates a Persistent Volume Claim (PVC) of 10G on the storage class. Verify if there is a default storage class in your cluster by running the following command: `kubectl get storageclass`. 

If a default storage class is absent or search fails to create a PVC, search uses the `emptyDir` as a volume. You can disable persistence by updating the `persistence` flag to `false` in the customization CR, which turns off saving search index. Review the following scenarios when you update the `storageClass` flag and there is a failure to create the PVC:

* When the persistence flag is set to `True`:
** If the `storageClass` is set, search uses the provided storage class.
** If the `storageClass` is not set, search attempts to use the default storage class.
* When the persistence flag is set to `False`:
** The `storageClass` or `storageSize` has no effect.
** Search disables persistence.

A status for persistence can be retrieved from the search operator (`searchoperator`). See link:../apis/search.json.adoc#search-api[Search customization API] for more information.

[#queries-in-the-console]
== Queries in the console

You can type any text value in the _Search box_ and results include anything with that value from any property, such as a name or namespace. Users are unable to search for values that contain an empty space.

For more specific search results, include the property selector in your search. You can combine related values for the property, for a more precise scope of your search. For example, search for `cluster:dev red` to receive results that match the string "red" in the `dev` cluster. 

View the following steps to make queries with search:

. Click *Search* in the navigation menu.
. Type a word in the _Search box_, then Search finds your resources that contain that value.
 ** As you search for resources, you receive other resources that are related to your original search result, which help you visualize how the resources interact with other resources in the system.
 ** Search returns and lists each cluster with the resource that you search.
For resources in the _hub_ cluster, the cluster name is displayed as _local-cluster_.
 ** Your search results are grouped by `kind`, and each resource `kind` is grouped in a table.
 ** Your search options depend on your cluster objects.
You can refine your results with specific labels.
Search is case-sensitive when you query labels.
See the following examples: name, namespace, status, and other resource fields.
Auto-complete provides suggestions to refine your search.
See the following example:
  *** Search for a single field, such as `kind:pod` to find all pod resources.
  *** Search for multiple fields, such as `kind:pod namespace:default` to find the pods in the default namespace.

+
*Notes:*

** You can also search with conditions by using characters, such as `+>, >=, <, <=, !=+`.
** When you search for more than one property selector with multiple values, the search returns either of the values that were queried. View the following examples:
*** When you search for `kind:pod name:a`, any pod named `a` is returned.
*** When you search for `kind:pod name:a,b`, any pod named `a` or `b` are returned.
*** Search for `kind:pod status:!Running` to find all pod resources where the status is not `Running`.
*** Search for `kind:pod restarts:>1` to find all pods that restarted at least twice.
. If you want to save your search, click the *Save disk* icon.

Learn more about the {product-title} console, see xref:../console/console_intro.adoc#web-console[Web console].
