[#search-in-the-console]
= Search in the console

For {product-title}, search provides visibility into your Kubernetes resources across all of your clusters. Search indexes the Kubernetes resources and the relationships to other resources. You can create a `searchcustomization` custom resource (CR) to define the storage settings for search persistence if you want to change the storage class and storage size. 

* <<search-components,Search components>>
* <<search-customization,Search customization>>
** <<options-increase-memory,Options to increase the redisgraph memory>>
* <<queries-in-the-console,Queries in the console>>
** <<search-argo,Query ArgoCD applications>>

[#search-components]
== Search components

The search architecture is composed of the following components:

* *Collector*: Watches the Kubernetes resources and creates an index. The `search-collector` computes relationships for resources within the managed cluster.

* *Aggregator*: Receives data from the collector and writes to a database. The `search-aggregator` watches resources in the hub cluster, computes multicluster relationships, and tracks the activity from connected collectors.

* *Search API*: Provides access to the data in the search index and enforces role-based access control. 

Search is enabled by default. Search is also enabled when you provision or manually import a managed cluster. If you want to disable search on your managed cluster, see link:../clusters/modify_endpoint.adoc#modifying-the-klusterlet-add-ons-settings-of-your-cluster[Modifying the klusterlet add-ons settings of your cluster] for more information.

[#search-customization]
== Search customization

When you install {product-title-short}, the product is configured to persist the data in-memory to a file system. The StatefulSet `search-redisgraph` deploys the Redisgraph pod, which mounts the persistent volume named `persist`. If your cluster has a defined default storage class, the search component creates a Persistent Volume Claim (PVC) of 10Gi on the default storage class. If a default storage class does not exist in your cluster, search saves the index in an empty directory (`emptyDir`).

You can customize the storage settings for search by creating the `searchcustomization` CR. Search customization is namespace-scoped and located where search is installed in the hub cluster. View the following example of the search customization CR:

[source,yaml]
----
apiVersion: search.open-cluster-management.io/v1alpha1
kind: SearchCustomization
metadata:
  name: searchcustomization
  namespace: open-cluster-management
  labels:
    cluster.open-cluster-management.io/backup: ""
spec:
  persistence: true
  storageClass: gp2
  storageSize: 12Gi
----

Run the following command to view search customization CRD: 

----
oc get crd searchcustomizations.search.open-cluster-management.io -o yaml
----

You can disable persistence by updating the `persistence` flag to `false` in the customization CR, which turns off saving search index to the file system. A status for persistence can be retrieved from the search operator (`searchoperator`) CR. Run the following command to view search operator CR: `oc get searchoperator searchoperator -o yaml`. 

[#options-increase-memory]
=== Options to increase the redisgraph memory

Redisgraph is an in-memory database that needs linear growth of memory as the number of objects are cached. A {product-title-short} cluster with many managed clusters, or with a large number of Kubernetes objects require limit memory updates for the redisgraph pod (`search-redisgraph-0`).

By default, the redisgraph pod (`search-redisgraph-0`) is deployed with a memory limit of `4Gi`. If you are managing larger clusters, you might need to increase this limit by editing the `redisgraph_resource.limit_memory` for the `searchoperator` in the hub cluster namespace. For example, you can update the limit to `8Gi` with the following command:

----
oc patch searchoperator searchoperator --type='merge' -p '{"spec":{"redisgraph_resource":{"limit_memory":"8Gi"}}}'
----

After the change is made, the `search-redisgraph` pod automatically restarts with the updated configuration.

[#queries-in-the-console]
== Queries in the console

You can type any text value in the _Search box_ and results include anything with that value from any property, such as a name or namespace. Users are unable to search for values that contain an empty space.

For more specific search results, include the property selector in your search. You can combine related values for the property, for a more precise scope of your search. For example, search for `cluster:dev red` to receive results that match the string "red" in the `dev` cluster. 

View the following steps to make queries with search:

. Click *Search* in the navigation menu.
. Type a word in the _Search box_, then Search finds your resources that contain that value.
 ** As you search for resources, you receive other resources that are related to your original search result, which help you visualize how the resources interact with other resources in the system.
 ** Search returns and lists each cluster with the resource that you search.
For resources in the _hub_ cluster, the cluster name is displayed as _local-cluster_.
 ** Your search results are grouped by `kind`, and each resource `kind` is grouped in a table.
 ** Your search options depend on your cluster objects.
You can refine your results with specific labels.
Search is case-sensitive when you query labels.
See the following examples: name, namespace, status, and other resource fields.
Auto-complete provides suggestions to refine your search.
See the following example:
  *** Search for a single field, such as `kind:pod` to find all pod resources.
  *** Search for multiple fields, such as `kind:pod namespace:default` to find the pods in the default namespace.

+
*Notes:*

** You can also search with conditions by using characters, such as `+>, >=, <, <=, !=+`.
** When you search for more than one property selector with multiple values, the search returns either of the values that were queried. View the following examples:
*** When you search for `kind:pod name:a`, any pod named `a` is returned.
*** When you search for `kind:pod name:a,b`, any pod named `a` or `b` are returned.
*** Search for `kind:pod status:!Running` to find all pod resources where the status is not `Running`.
*** Search for `kind:pod restarts:>1` to find all pods that restarted at least twice.
. If you want to save your search, click the *Save search* icon.

[#search-argo]
=== Query ArgoCD applications

When you search for an ArgoCD application, you are directed to the _Applications_ page. Complete the following steps to access the ArgoCD application from the _Search_ page:

. Log in to your {product-title-short} hub cluster.
. From the console header, select the _Search_ icon.
. Filter your query with the following values: `kind:application` and `apigroup:argoproj.io`
. Select an application to view. The _Application_ page displays an overview of information for the application.

Learn more about the {product-title} console, see xref:../console/console_intro.adoc#web-console[Web console].
