
[#deprecations-removals-cluster-mce]
= Deprecations and removals Cluster lifecycle

Learn when parts of the product are deprecated or removed from {mce-short}. Consider the alternative actions in the _Recommended action_ and details, which display in the tables for the current release and for two prior releases. Tables are removed if no entries are added for that section this release.

*Deprecated:* {mce-short} 2.3 and earlier versions are no longer supported. The documentation might remain available, but without any Errata or other updates.

*Best practice:* Upgrade to the most recent version.

[#api-deprecations-info-cluster]
== API deprecations and removals

{mce-short} follows the Kubernetes deprecation guidelines for APIs. See the link:https://kubernetes.io/docs/reference/using-api/deprecation-policy/[Kubernetes Deprecation Policy] for more details about that policy. {mce-short} APIs are only deprecated or removed outside of the following timelines:

  - All `V1` APIs are generally available and supported for 12 months or three releases, whichever is greater. V1 APIs are not removed, but can be deprecated outside of that time limit.
  - All `beta` APIs are generally available for nine months or three releases, whichever is greater. Beta APIs are not removed outside of that time limit.
  - All `alpha` APIs are not required to be supported, but might be listed as deprecated or removed if it benefits users.

[#api-deprecations-cluster]
=== API deprecations

|===
| Product or category | Affected item | Version | Recommended action | More details and links

| ManagedServiceAccount
| The `v1alpha1` API is upgraded to `v1beta1` because `v1alpha1` is deprecated.
| 2.4
| Use `v1beta1`.
| None

|===

//[#api-removals-cluster]
//=== API removals

//|===
//| Product or category | Affected item | Version | Recommended action | More details and links
//|===

[#deprecations-cluster]
== Deprecations

A _deprecated_ component, feature, or service is supported, but no longer recommended for use and might become obsolete in future releases. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
| Product or category | Affected item | Version | Recommended action | More details and links
| Hosted control planes
| The `--aws-creds` flag is deprecated.
| 2.6
| Use the `--sts-creds` and `--role-arn` flags in the `hcp` command line interface.
| None
|===

[#removals]
== Removals

A _removed_ item is typically function that was deprecated in previous releases and is no longer available in the product. You must use alternatives for the removed function. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
|Product or category | Affected item | Version | Recommended action | More details and links

| Cluster lifecycle
| Create cluster on Red Hat Virtualization
| 2.6
| None
| None

| Cluster lifecycle
| Klusterlet {olm} Operator
| 2.6
| None
| None
|===
