[#errata-updates]
= Errata updates

For {mce-short}, the Errata updates are automatically applied when released.

*Important:* For reference, https://access.redhat.com/errata/#/[Errata] links and GitHub numbers might be added to the content and used internally. Links that require access might not be available for the user. 

FIPS notice: If you do not specify your own ciphers in `spec.ingress.sslCiphers`, then the `multiclusterhub-operator` provides a default list of ciphers. For 2.4, this list includes two ciphers that are _not_ FIPS approved. If you upgrade from a version 2.4.x or earlier and want FIPS compliance, remove the following two ciphers from the `multiclusterhub` resource: `ECDHE-ECDSA-CHACHA20-POLY1305` and `ECDHE-RSA-CHACHA20-POLY1305`.

== Errata 2.2.12

* Delivers updates to one or more of the product container images.

== Errata 2.2.11

* Delivers updates to one or more of the product container images.

* Fixes an issue where the managed cluster used deprecated region and zone labels. (link:https://issues.redhat.com/browse/ACM-8844[ACM-8844])

* Fixes an issue where the node regions and zones were incorrectly displayed from the _Topology_ view. (link:https://issues.redhat.com/browse/ACM-9004[ACM-9004])

== Errata 2.2.10

* Delivers updates to one or more of the product container images.


== Errata 2.2.9

* Delivers updates to one or more of the product container images and security fixes.

== Errata 2.2.8

* Delivers updates to one or more of the product container images and security fixes.

== Errata 2.2.7

* Delivers updates to one or more of the product container images and security fixes.

* Fixes an issue that caused the console to display an incorrect scaling alert when adding nodes to a managed cluster that is not part of Hive `MachinePools`. (link:https://issues.redhat.com/browse/ACM-5169[ACM-5169])

== Errata 2.2.6

* Fixes an issue that caused the klusterlet agent to fail when the total file size of secrets is too large. (link:https://issues.redhat.com/browse/ACM-5873[ACM-5873])

== Errata 2.2.5

* Delivers updates to one or more of the product container images and security fixes. 

== Errata 2.2.4

* Delivers updates to one or more of the product container images and security fixes.

== Errata 2.2.3

* Delivers updates to one or more of the product container images and security fixes.

== Errata 2.2.2

* Delivers updates to one or more of the product container images and security fixes.

== Errata 2.2.1

* Delivers updates to one or more of the product container images and security fixes.
