[#errata-updates-mce]
= Fixed issues for Cluster lifecycle with {mce-short}

By default, fixed issues for _errata_ releases are automatically applied when released. The details are published here when the release is available. If no release notes are listed, the product does not have an errata release at this time.

*Important:* For reference, Jira links and Jira numbers might be added to the content and used internally. Links that require access might not be available for the user. Learn about the types of link:https:access.redhat.com/security/updates/advisory[errata releases] from Red Hat.

== Errata 2.9.4

* Delivers updates to one or more product container images.

== Errata 2.9.3

* Delivers updates to one or more product container images.

== Errata 2.9.2

* Delivers updates to one or more product container images.

* Addresses an issue that might cause the console to become unavailable because of a `CrashLoopBackOff` condition by improving performance and increasing probe timeouts on the `console-mce-console` deployment.
link:https://issues.redhat.com/browse/ACM-25039[ACM-25039] 

== Errata 2.9.1

* Delivers updates to one or more product container images.

* Adds a missing link to the operator source code and repository on the OperatorHub installation page. The `annotation.repository` is updated to point to the correct repository URL.
link:https:issues.redhat.com/browse/ACM-22366[ACM-22366]
