[#known-issues-mce]
= Known issues for Cluster lifecycle with {mce-short}

Review the Known issues for _Cluster lifecycle with {mce-short}_ for this release, or known issues that continued from the previous release. 

Cluster management known issues and limitations are part of the _Cluster lifecycle with {mce-short}_ documentation. Known issues for {mce-short} integrated _with_ {acm-short} are documented in the link:../../release_notes/acm_release_notes.adoc#acm-release-notes[Release notes for {acm-short}]. 

*Important:* {ocp-short} release notes are not documented in this product documentation. For your {ocp-short} cluster, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17[{ocp-short} release notes].

* <<cluster-issues-install,Installation>>
* <<cluster-issues-mce,Cluster management>>
* <<cluster-issues-cim,Central infrastructure management>>

[#cluster-issues-install]
== Installation 

Learn about known issues and limitations during {mce-short} installation.

[#unclaimed-hive-clusters]
=== Unclaimed Hive clusters might be recreated during ClusterPool custom resource definition changes

During a {mce-short} upgrade or modification to the `ClusterPool` custom resource definition, Hive might delete and recreate all unclaimed clusters. This is expected behavior and ensures that unclaimed clusters reflect the latest configuration defined in the updated `ClusterPool` resource specification.

link:https://issues.redhat.com/browse/ACM-21686[ACM-21686]

[#installnamespace-field-limit]
=== _installNamespace_ field can only have one value

When enabling the `managed-serviceaccount` add-on, the `installNamespace` field in the `ManagedClusterAddOn` resource must have `open-cluster-management-agent-addon` as the value. Other values are ignored. The `managed-serviceaccount` add-on agent is always deployed in the `open-cluster-management-agent-addon` namespace on the managed cluster.

link:https://issues.redhat.com/browse/ACM-7523[ACM-7523]

[#cluster-issues-mce]
== Cluster management

Learn about Known issues for Cluster lifecycle with {mce-short}, such as issues with creating, discovering, importing, and removing clusters, and more cluster management issues for {mce-short}.

[#klusterlet-noexecute-taint]
=== Klusterlet add-on does not tolerate `node-role.kubernetes.io/infra` taint with `NoExecute` effect

If you use the `node-role.kubernetes.io/infra` taint with the `NoExecute` effect on your infrastructure nodes, your add-on pods might become stuck.

To work around the issue, either use the `NoSchedule` effect instead of `NoExecute` for the `node-role.kubernetes.io/infra` taint, or remove the `node-role.kubernetes.io/infra` taint from your infrastructure nodes.

link:https://issues.redhat.com/browse/ACM-15906[ACM-15906]

[#limitation-with-nmstate]
=== Limitation with _nmstate_

Develop quicker by configuring copy and paste features. To configure the `copy-from-mac` feature in the `assisted-installer`, you must add the `mac-address` to the `nmstate` definition interface and the `mac-mapping` interface. The `mac-mapping` interface is provided outside the `nmstate` definition interface. As a result, you must provide the same `mac-address` twice. 

link:https://issues.redhat.com/browse/ACM-9128[ACM-9128]

[#clusterset-label-not-removed]
=== Deleting a managed cluster set does not automatically remove its label

After you delete a `ManagedClusterSet`, the label that is added to each managed cluster that associates the cluster to the cluster set is not automatically removed. Manually remove the label from each of the managed clusters that were included in the deleted managed cluster set. The label resembles the following example: `cluster.open-cluster-management.io/clusterset:<ManagedClusterSet Name>`.

link:https://github.com/stolostron/backlog/issues/20727[ACM-20727]

[#hive-cluster-claim]
=== ClusterClaim error

If you create a Hive `ClusterClaim` against a `ClusterPool` and manually set the `ClusterClaimspec` lifetime field to an invalid golang time value, the product stops fulfilling and reconciling all `ClusterClaims`, not just the malformed claim.  

You see the following error in the `clusterclaim-controller` pod logs, which is a specific example with the `PoolName` and invalid `lifetime` included:

----
E0203 07:10:38.266841       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.ClusterClaim: failed to list *v1.ClusterClaim: v1.ClusterClaimList.Items: []v1.ClusterClaim: v1.ClusterClaim.v1.ClusterClaim.Spec: v1.ClusterClaimSpec.Lifetime: unmarshalerDecoder: time: unknown unit "w" in duration "1w", error found in #10 byte of ...|time":"1w"}},{"apiVe|..., bigger context ...|clusterPoolName":"policy-aas-hubs","lifetime":"1w"}},{"apiVersion":"hive.openshift.io/v1","kind":"Cl|...
----

You can delete the invalid claim.

If the malformed claim is deleted, claims begin successfully reconciling again without any further interaction.

link:https://github.com/stolostron/backlog/issues/19968[ACM-19968]

[#clusterimageset-fast-channel]
=== The product channel out of sync with provisioned cluster

The `clusterimageset` is in `fast` channel, but the provisioned cluster is in `stable` channel. Currently the product does not sync the `channel` to the provisioned {ocp-short} cluster. 

Change to the right channel in the {ocp-short} console. Click **Administration** > **Cluster Settings** > **Details Channel**.

link:https://github.com/stolostron/backlog/issues/18380[ACM-18380]

[#cluster-provision-fails-ansible-proxy]
=== Cluster provision with Ansible automation fails in proxy environment

An Automation template that is configured to automatically provision a managed cluster might fail when both of the following conditions are met: 

* The hub cluster has cluster-wide proxy enabled. 
* The {aap-short} can only be reached through the proxy.

link:https://github.com/stolostron/backlog/issues/17659[ACM-17659]

[#no-delete-cluster-namespace-before-remove-cluster]
=== Cannot delete managed cluster namespace manually

You cannot delete the namespace of a managed cluster manually. The managed cluster namespace is automatically deleted after the managed cluster is detached. If you delete the managed cluster namespace manually before the managed cluster is detached, the managed cluster shows a continuous terminating status after you delete the managed cluster. To delete this terminating managed cluster, manually remove the finalizers from the managed cluster that you detached.

link:https://github.com/stolostron/backlog/issues/13474[13474]

[#automatic-secret-updates-for-provisioned-clusters-is-not-supported]
=== Automatic secret updates for provisioned clusters is not supported

When you change your cloud provider access key on the cloud provider side, you also need to update the corresponding credential for this cloud provider on the console of {mce-short}. This is required when your credentials expire on the cloud provider where the managed cluster is hosted and you try to delete the managed cluster.

link:https://github.com/stolostron/backlog/issues/3706[ACM-3706]

[#cluster-might-not-be-destroyed]
=== Process to destroy a cluster does not complete

When you destroy a managed cluster, the status continues to display `Destroying` after one hour, and the cluster is not destroyed. To resolve this issue complete the following steps:

. Manually ensure that there are no orphaned resources on your cloud, and that all of the provider resources that are associated with the managed cluster are cleaned up.

. Open the `ClusterDeployment` information for the managed cluster that is being removed by entering the following command:
+
----
oc edit clusterdeployment/<mycluster> -n <namespace>
----
+
Replace `_mycluster_` with the name of the managed cluster that you are destroying.
+
Replace `_namespace_` with the namespace of the managed cluster.

. Remove the `hive.openshift.io/deprovision` finalizer to forcefully stop the process that is trying to clean up the cluster resources in the cloud.

. Save your changes and verify that `ClusterDeployment` is gone.

. Manually remove the namespace of the managed cluster by running the following command:

+
----
oc delete ns <namespace>
----
+
Replace `_namespace_` with the namespace of the managed cluster.

link:https://github.com/stolostron/backlog/issues/4748[ACM-4748]

[#no-upgrade-os-on-osd]
=== Cannot upgrade {ocp-short} managed clusters on {ocp-short} Dedicated with the console

You cannot use the {acm-short} console to upgrade {ocp-short} managed clusters that are in the {ocp-short} Dedicated environment.

link:https://github.com/stolostron/backlog/issues/8922[ACM-8922]

[#non-ocp-logs]
=== Non-{ocp-short} managed clusters require _ManagedServiceAccount_ or _LoadBalancer_ for pod logs 

The `ManagedServiceAccount` and cluster proxy add-ons are enabled by default in {acm-short} version 2.10 and newer. If the add-ons are disabled after upgrading, you must enable the `ManagedServiceAccount` and cluster proxy add-ons manually to use the pod log feature.

See link:../../clusters/install_upgrade/adv_config_install.adoc#serviceaccount-addon-intro[ManagedServiceAccount add-on] to learn how to enable `ManagedServiceAccount` and see link:../../clusters/cluster_lifecycle/cluster_proxy_addon_config.adoc#config-cluster-proxy-addon[Configuring cluster proxy add-ons] to learn how to enable a cluster proxy add-on.

- To learn how to enable `ManagedServiceAccount` add-on, see  link:../../clusters/install_upgrade/adv_config_install.adoc#serviceaccount-addon-intro[ManagedServiceAccount add-on]. 
- To learn how to enable a cluster proxy add-on, see link:../../clusters/cluster_lifecycle/cluster_proxy_addon.adoc#cluster-proxy-addon[Using cluster proxy add-ons].

link:https://issues.redhat.com/browse/ACM-11034[ACM-11034]

[#client-cannot-reach-ipxe-script]
=== Client cannot reach iPXE script

iPXE is an open source network boot firmware. See link:https://ipxe.org/[iPXE] for more details.

When booting a node, the URL length limitation in some DHCP servers cuts off the `ipxeScript` URL in the `InfraEnv` custom resource definition, resulting in the following error message in the console:

`no bootable devices`

To work around the issue, complete the following steps:

. Apply the `InfraEnv` custom resource definition when using an assisted installation to expose the `bootArtifacts`, which might resemble the following file:

[source,yaml]
----
status:
  agentLabelSelector:
    matchLabels:
      infraenvs.agent-install.openshift.io: qe2
  bootArtifacts:
    initrd: https://assisted-image-service-multicluster-engine.redhat.com/images/0000/pxe-initrd?api_key=0000000&arch=x86_64&version=4.11
    ipxeScript: https://assisted-service-multicluster-engine.redhat.com/api/assisted-install/v2/infra-envs/00000/downloads/files?api_key=000000000&file_name=ipxe-script
    kernel: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.12/latest/rhcos-live-kernel-x86_64
    rootfs: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.12/latest/rhcos-live-rootfs.x86_64.img
----

. Create a proxy server to expose the `bootArtifacts` with short URLs.

. Copy the `bootArtifacts` and add them them to the proxy by running the following commands:

+
----
for artifact in oc get infraenv qe2 -ojsonpath="{.status.bootArtifacts}" | jq ". | keys[]" | sed "s/\"//g"
do curl -k oc get infraenv qe2 -ojsonpath="{.status.bootArtifacts.${artifact}}"` -o $artifact 
----

. Add the `ipxeScript` artifact proxy URL to the `bootp` parameter in `libvirt.xml`.

link:https://github.com/stolostron/backlog/issues/25157[ACM-25157]

[#managedclusterset-api-limitation]
=== ManagedClusterSet API specification limitation

The `selectorType: LaberSelector` setting is not supported when using the link:../../apis/clusterset.json.adoc#clustersets-api[Clustersets API]. The `selectorType: ExclusiveClusterSetLabel` setting is supported.

link:https://issues.redhat.com/browse/ACM-6423[ACM-6423]

[#ocp-ded-support-curator]
=== The Cluster curator does not support {ocp-short} Dedicated clusters

When you upgrade an {ocp-short} Dedicated cluster by using the `ClusterCurator` resource, the upgrade fails because the Cluster curator does not support {ocp-short} Dedicated clusters.

link:https://issues.redhat.com/browse/ACM-10154[ACM-10154]

[#custom-ingress-domain-limitation]
=== Custom ingress domain is not applied correctly

You can specify a custom ingress domain by using the `ClusterDeployment` resource while installing a managed cluster, but the change is only applied after the installation by using the `SyncSet` resource. As a result, the `spec` field in the `clusterdeployment.yaml` file displays the custom ingress domain you specified, but the `status` still displays the default domain.

link:https://issues.redhat.com/browse/ACM-6279[ACM-6279]

[#settings-limit-msa-agent]
=== _tolerations_ and _nodeSelector_ settings do not affect the _managed-serviceaccount_ agent

The `tolerations` and `nodeSelector` settings configured on the `MultiClusterEngine` and `MultiClusterHub` resources do not affect the `managed-serviceaccount` agent deployed on the local cluster. The `managed-serviceaccount` add-on is not always required on the local cluster.

If the `managed-serviceaccount` add-on is required, you can work around the issue by completing the following steps:

. Create the `addonDeploymentConfig` custom resource.

. Set the `tolerations` and `nodeSelector` values for the local cluster and `managed-serviceaccount` agent.

. Update the `managed-serviceaccount` `ManagedClusterAddon` in the local cluster namespace to use the `addonDeploymentConfig` custom resource you created.

To learn more about how to use the `addonDeploymentConfig` custom resource to configure `tolerations` and `nodeSelector` for add-on, see link:../../add-ons/configure_klusterlet_addons.adoc#configure-klusterlet-addons[Configuring klusterlet add-ons].

link:https://issues.redhat.com/browse/ACM-7523[ACM-7523]
//this one doesn't match the issue we attached. GH is not the option here. --bcs 11/2025

[#cluster-issues-cim]
== Central infrastructure management

Learn about known issues and limitations for central infrastructure management with {mce-short}.

[#install-sno-ocp-infra]
=== A {sno} cluster installation requires a matching {ocp-short} with {infra}

If you want to install a {sno} cluster with an {ocp} version before 4.19, your `InfraEnv` custom resource and your booted host must use the same {ocp-short} version that you are using to install the {sno} cluster. The installation fails if the versions do not match.

To work around the issue, edit your `InfraEnv` resource before you boot a host with the Discovery ISO, and include the following content. Replace `<4.x>` with the `osImageVersion` that you want to install:

[source,yaml]
----
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
spec:
  osImageVersion: "<4.x>"
----

link:https://issues.redhat.com/browse/ACM-14943[ACM-14943]

[#boot-discovery-auto-add-host]
=== Cannot use host inventory to boot with the discovery image and add hosts automatically

You cannot use a host inventory, or `InfraEnv` custom resource, to both boot with the discovery image and add hosts automatically. If you used your previous `InfraEnv` resource for the `BareMetalHost` resource, and you want to boot the image yourself, you can work around the issue by creating a new `InfraEnv` resource.

link:https://issues.redhat.com/browse/ACM-14719[ACM-14719]

[#nodes-shut-down-bmh]
=== Nodes shut down after removing `BareMetalHost` resource

If you remove the `BareMetalHost` resource from a hub cluster, the nodes shut down. You can manually power on the nodes again.

link:https://issues.redhat.com/browse/ACM-15319[ACM-15319]
