[#new-features-mce]
= New features and enhancements for Cluster lifecycle with {mce-short}

Learn about {mce} 2.9 new features and enhancements, support, deprecations, removals, and fixed issues for errata releases. 

{mce-short} version 2.9 is released with {acm-short} version 2.14 for Cluster lifecycle management, but you can use stand-alone {mce-short} with your {ocp-short} hub cluster, as well. 

For full support information, including supported {ocp-short} versions, see the link:https://access.redhat.com/articles/7120837[{mce-short} Support Matrix]. For lifecycle information, see link:https://access.redhat.com/support/policy/updates/openshift[{ocp} Life Cycle policy].

Use {mce-short} features for creating, importing, managing, and destroying Kubernetes clusters across various infrastructure cloud providers, private clouds, and on-premises data centers.

*Important:* 

- Cluster management supports all providers that are certified through the Cloud Native Computing Foundation (CNCF) Kubernetes Conformance Program. Choose a vendor that is recognized by CNFC for your hybrid cloud multicluster management. See the following information about using CNFC providers:

- Learn how CNFC providers are certified at link:https://www.cncf.io/training/certification/software-conformance/[Certified Kubernetes Conformance].

- For Red Hat support information about CNFC third-party providers, see link:https://access.redhat.com/third-party-software-support[Red Hat support with third party components], or link:https://access.redhat.com/support/contact/[Contact Red Hat support].

- If you bring your own CNFC conformance certified cluster, you need to change the {ocp-short} CLI `oc` command to the Kubernetes CLI command, `kubectl`.

[#new-component-mce]
== New features and enhancements for each component

Learn more about new features for specific components.

*Note:* Some features and components are identified and released as link:https://access.redhat.com/support/offerings/techpreview[Technology Preview].

*Important:* The _hosted control planes for {ocp-short}_ documentation is located in the {ocp-short} documentation. See the link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/hosted_control_planes/hosted-control-planes-overview[Hosted control planes overview].

Learn about new features and enhancements that come with the {mce-short} installation:

- You can now change the name of your local cluster. By default, the cluster that is running {mce-short} is the _local cluster_, which is a hub cluster that manages itself. When the `enabled` field is set to `false`, which disables the local cluster feature, you can change the name. Use 34 or fewer characters for the `<your-local-cluster-name>` value. The `local-cluster` resource and the namespaces reflects the change.

Learn about new features and enhancements for Cluster lifecycle with {mce-short}:

- The `cluster-api` component is now generally available during {mce-short} installation to provide capabilities for Cluster API lifecycle from within a managed cluster. The `cluster-api-provider-aws` is also generally available during installation to provide Kubernetes-style APIs for cluster creation, configuration, and management for {rosa-hcp}. Both components are disabled by default.

- You can install an {ocp-short} managed cluster with the Cluster API by using the `metal3` infrastructure provider and the {ocp-short} assisted bootstrap and control plane providers. See xref:../cluster_api/install_capi_managed#capi-managed-assisted[Installing a managed cluster with Cluster API].

- Apply more comprehensive filters to the `DiscoveryConfig` resource, including infrastructure providers, cluster types, and regions. While most filters can be configured through both the terminal and the console, the `region` filter is currently available in the terminal only. To learn more, see link:../clusters/discovery/discovery_config_ui.adoc#discovery-view[View discovered clusters].


- You can now access the managed cluster `kube-apiserver` by using a hub cluster user token. To learn more, see xref:../cluster_lifecycle/cluster_proxy_addon_use#access-kube-apiserver-hub-token[Accessing the `kube-apiserver` of a managed cluster by using a hub cluster user token].
//why do this?

- You can now define a unique mirror registry for each cluster. To learn more, see xref:../assisted_installer/ai_mirror_reg.adoc#config-mirror-reg-cluster[Configuring mirror registries for each cluster].
//why do this

- You can now customize the automatic import strategy of managed clusters. To learn more, see xref:../cluster_lifecycle/adv_config_cluster.adoc#custom-auto-import-strat[Customizing the automatic import strategy].
//why do this, remove the "of managed clusters" copied from developer drafts

- You can now use any file name for the `OSImageCACert` `ConfigMap`. To learn more, see xref:../assisted_installer/ai_enable_cim#enable-cim-disconnected[Enabling {cim} in disconnected environments].
//why--and change some You cans when we know more about these

If you are using {mce-short} with {acm-short} installed afterwards, see the link:../../release_notes/acm_new.adoc#new-features-acm[New features and enhancements for {acm-short}] this release.

