[#errata-updates-mce]
= Fixed issues for Cluster lifecycle with {mce-short}

By default, fixed issues for _errata_ releases are automatically applied when released. The details are published here when the release is available. If no release notes are listed, the product does not have an errata release at this time.

*Important:* For reference, Jira links and Jira numbers might be added to the content and used internally. Links that require access might not be available for the user. Learn about the types of link:https:access.redhat.com/security/updates/advisory[errata releases] from Red Hat.

== Errata 2.9.2

* Delivers updates to one or more product container images.

* Addresses an issue that prevented disabling attachment of the default network when deploying an {hcp} cluster on {ocp-virt-short}. Users were not able to set the `attachDefaultNetwork` field to `false` before the fix.
link:https:issues.redhat.com/browse/ACM-24961[ACM-24961]

* Improves performance for the `console-mce` pod and ensure the pod handles requests more efficiently, preventing `CrashLoopBackOff` probe timeouts and stabilizing the pod to prevent unexpected restarts.
link:https://issues.redhat.com/browse/ACM-25039[ACM-25039] 
//Kevin--also in ACM

== Errata 2.9.1

* Delivers updates to one or more product container images.

* Adds a missing link to the operator source code and repository on the OperatorHub installation page. The `annotation.repository` is updated to point to the correct repository URL.
link:https:issues.redhat.com/browse/ACM-22366[ACM-22366]
