[#whats-new]
= What's new in cluster lifecycle with the {mce-short}


*Important:* Some features and components are identified and released as link:https://access.redhat.com/support/offerings/techpreview[Technology Preview].

Learn more about what is new this release:

* <<cluster-lifecycle, Cluster lifecycle>>
* <<credential, Credentials>>
* <<hosted-control-plane, Hosted control planes>>
* <<acm-integration-wn,{product-title-short} integration>>

[#cluster-lifecycle]
== Cluster lifecycle

Learn about what's new relating to Cluster lifecycle with {mce-short}.

You can now push custom labels to the automation job pod created by the `ClusterCurator`. See xref:../cluster_lifecycle/ansible_config_cluster.adoc#push-cl-cr-job-pod[Pushing custom labels from the _ClusterCurator_ resource to the automation job pod] to learn more.

You can now automatically apply configurations in the global `KlusterletConfig` on every managed cluster, without binding a managed cluster to a `KlusterletConfig` with an annotation. To learn more, see, xref:../cluster_lifecycle/adv_config_cluster.adoc#config-gloabl-klusterletconfig[Configuring the global _KlusterletConfig_].

[#credential]
== Credentials



[#hosted-control-plane]
== Hosted control planes



[#acm-integration-wn]
== {product-title-short} integration
