:_mod-docs-content-type: PROCEDURE

[#enabling-service-discovery-submariner]
= Enabling service discovery for Submariner

[role="_abstract"]
To make a service from a cluster visible and discoverable to other clusters in the managed cluster set, you must create a `ServiceExport` object. After a service is exported with a `ServiceExport` object, you can access the service by the following format: `<service>.<namespace>.svc.clusterset.local`. If multiple clusters export a service with the same name, and from the same namespace, they are recognized by other clusters as a single logical service. 

This example uses the `nginx` service in the `default` namespace, but you can discover any Kubernetes `ClusterIP` service or headless service: 

.Procedure

. Apply an instance of the `nginx` service on a managed cluster that is in the `ManagedClusterSet` by entering the following commands:

+
[source,bash]
----
oc -n default create deployment nginx --image=nginxinc/nginx-unprivileged:stable-alpine
oc -n default expose deployment nginx --port=8080
----

. Export the service by creating a `ServiceExport` entry by entering a command with the `subctl` tool that is similar to the following command:

+
[source,bash]
----
subctl export service --namespace <service-namespace> <service-name>
----
* Replace `service-namespace` with the name of the namespace where the service is located. In this example, it is `default`.
* Replace `service-name` with the name of the service that you are exporting. In this example, it is `nginx`.
* link:https://submariner.io/operations/deployment/subctl/#export[`export`]

. Run the following command from a different managed cluster to confirm that it can access the `nginx` service:

+
[source,bash]
----
oc -n default run --generator=run-pod/v1 tmp-shell --rm -i --tty --image quay.io/submariner/nettest -- /bin/bash curl nginx.default.svc.clusterset.local:8080
----
