:_mod-docs-content-type: PROCEDURE

[#preparing-aro-submariner-cli]
= Preparing Microsoft Azure Red Hat OpenShift for Submariner by using the CLI

[role="_abstract"]
The Microsoft Azure Red Hat OpenShift service combines various tools and resources that you can use to simplify the process of building container-based applications. To prepare Azure Red Hat OpenShift clusters for deploying Submariner by using the command line interface, complete the following steps:

.Procedure

. Install the link:https://learn.microsoft.com/en-us/cli/azure/install-azure-cli[Azure CLI].

. From the Azure CLI, run the following command to install the extension:

+
[source,bash]
----
az extension add --upgrade -s <path-to-extension>
----
* Replace `path-to-extension` with the path to where you downloaded the `.whl` extension file.

. Run the following command to verify that the CLI extension is being used:

+
[source,bash]
----
az extension list
----
+
If the extension is being used, the output might resemble the following example:
+
----
"experimental": false,
"extensionType": "whl",
"name": "aro",
"path": "<path-to-extension>",
"preview": true,
"version": "1.0.x"
----

. From the Azure CLI, register the preview feature by running the following command:

+
[source,bash]
----
az feature registration create --namespace Microsoft.RedHatOpenShift --name AdminKubeconfig
----

. Retrieve the administrator `kubeconfig` by running the following command:

+
[source,bash]
----
az aro get-admin-kubeconfig -g <resource group> -n <cluster resource name>
----
+
*Note:* The `az aro` command saves the `kubeconfig` to the local directory and uses the name `kubeconfig`. To use it, set the environment variable `KUBECONFIG` to match the path of the file. See the following example:

+
[source,bash]
----
export KUBECONFIG=<path-to-kubeconfig>
oc get nodes
----

See link:../../clusters/cluster_lifecycle/import_intro.adoc#import-intro[Cluster import introduction] to learn more about how to import a cluster.
