:_mod-docs-content-type: PROCEDURE

[#preparing-bare-metal-submariner]
= Preparing bare metal for Submariner

[role="_abstract"]
To prepare bare metal clusters for deploying Submariner, complete the following steps:

.Procedure

. Ensure that the firewall allows inbound/outbound traffic for external clients on the 4500/UDP and 4490/UDP ports for the Gateway nodes. Also, if the cluster is deployed with OpenShiftSDN CNI, allow inbound/outbound UDP/4800 traffic within the local cluster nodes.

. Customize and apply YAML content that is similar to the following example:

+
[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:
    gatewayConfig:
      gateways: 1
----
* The name must be `submariner`, as shown in the example.
* Replace with the name of your managed cluster.
+
This configuration xref:../submariner/subm_gateway_nodes.adoc#number-gateway-nodes[labels one of the worker nodes as the Submariner gateway] on your bare metal cluster.

. Identify the Gateway node configured by Submariner and enable firewall configurations to allow the IPsec NATT (UDP/4500) and NATDiscovery (UDP/4490) ports for external traffic.
