:_mod-docs-content-type: PROCEDURE

[#preparing-to-configure-submariner]
= Preparing to configure Submariner

[role="_abstract"]
{acm} provides Submariner as an add-on for your hub cluster. To prepare for configuring Submariner, complete the following steps:

.Procedure

. Ensure that you have a credential to access the hub cluster with `cluster-admin` permissions.

. Configure IP connectivity between the gateway nodes. When connecting two clusters, at least one of the clusters must be accessible to the gateway node by using its public or private IP address designated to the gateway node. See _Submariner NAT Traversal_ for more information.

. If you are using OVN Kubernetes, ensure that your clusters are on a supported version of {ocp-short}.

. If your {ocp-short} clusters use OpenShift SDN CNI, configure the firewall across all nodes in each of the managed clusters to allow 4800/UDP in both directions.

. Configure the firewall to allow 4500/UDP and 4490/UDP on the gateway nodes for establishing tunnels between the managed clusters.

. For {ocp-short} ARM deployments, use the `c6g.large` `instanceType` or any other available instance type.

. If the gateway nodes are directly reachable over their private IPs without any NAT in between, configure the firewall to allow the ESP protocol on the gateway nodes.
+
*Notes:* 
+
** This update is configured automatically when your clusters are deployed in an Amazon Web Services, Google Cloud Platform, Microsoft Azure, or Red Hat OpenStack environment. You must manually configure it for clusters on other environments and for the firewalls that protect private clouds.
** If you do not want to allow the ESP protocol in the firewall, you can force Submariner to encapsulate IPSec traffic in UDP by editing `SubmarinerConfig` and adding `forceUDPEncaps: true` to the `spec` section.

. For Red Hat OpenStack Services on OpenShift clusters, select a unique UDP port other than 4500 for IPsec NAT-T. The 4500 port is used by OpenStack services on OpenShift internally.

. *Technology Preview:* If Open Virtual Network Internet Protocol Security is enabled, enable `IPSecCertAuthMode` in the `SubmarinerConfig` resource. You can only change this setting during installation.

. Ensure that the `managedcluster` name follows the DNS label standard as defined in RFC 1123 and meets the following requirements:
+
** Contain 63 characters or fewer
** Contain only lowercase alphanumeric characters or '-'
** Start with an alphanumeric character
** End with an alphanumeric character

.Next steps 

. See the xref:../submariner/subm_ports_ref.adoc#submariner-ports[Submariner ports table] for information about the ports that Submariner uses for communication between clusters.
. Go to xref:../submariner/subm_vpc_config.adoc#subm-vpc-config[Configuring Submariner for an existing VPC].
. See the xref:../submariner/subm_globalnet.adoc#submariner-globalnet[Globalnet] documentation.

.Additional resources

* link:https://submariner.io/[Submariner documentation]
* link:https://submariner.io/operations/nat-traversal[Submariner NAT Traversal]
* link:https://submariner.io/getting-started/#prerequisites[Submariner prerequisites documentation]
* link:https://submariner.io/getting-started/architecture/globalnet/[Globalnet controller]
