[#configuring-submariner]
= Configuring Submariner

{product-title} provides Submariner as an add-on for your hub cluster. You can find more information about Submariner in the link:https://submariner.io/[Submariner open source project documentation].

[#submariner-prereqs]
== Prerequisites

Ensure that you have the following prerequisites before using Submariner:

* A credential to access the hub cluster with `cluster-admin` permissions.
* IP connectivity must be configured between the gateway nodes. When connecting two clusters, at least one of the clusters must be accessible to the gateway node using its public or private IP address designated to the gateway node. See link:https://submariner.io/operations/nat-traversal[Submariner NAT Traversal] for more information.
* If you are using OVN Kubernetes, clusters must be at {ocp} version 4.12 or later. 
* If your {ocp} clusters use OpenShift SDN CNI, the firewall configuration across all nodes in each of the managed clusters must allow 4800/UDP in both directions.
* The firewall configuration must allow 4500/UDP and 4490/UDP on the gateway nodes for establishing tunnels between the managed clusters.
* If the gateway nodes are directly reachable over their private IPs without any NAT in between, make sure that the firewall configuration allows the ESP protocol on the gateway nodes.
+
*Note:* This is configured automatically when your clusters are deployed in an Amazon Web Services, Google Cloud Platform, Microsoft Azure, or Red Hat OpenStack environment, but must be configured manually for clusters on other environments and for the firewalls that protect private clouds.
+
* The `managedcluster` name must follow the DNS label standard as defined in RFC 1123 and meet the following requirements:
** Contain 63 characters or fewer
** Contain only lowercase alphanumeric characters or '-'
** Start with an alphanumeric character
** End with an alphanumeric character

[#submariner-ports]
== Submariner ports table

View the following table to see which Submariner ports you need to enable:

|===
| Name | Default value | Customizable | Optional or required

| IPsec NATT
| 4500/UDP
| Yes
| Required

| VXLAN
| 4800/UDP
| No
| Required

| NAT discovery port
| 4490/UDP
| No
| Required
|===

See the link:https://submariner.io/getting-started/#prerequisites[Submariner upstream prerequisites documentation] for more detailed information about the prerequisites.

[#submariner-globalnet]
== Globalnet

Globalnet is a feature included with the Submariner add-on that supports connectivity between clusters with overlapping CIDRs. Globalnet is a cluster set wide configuration, and can be selected when the first managed cluster is added to the cluster set. When Globalnet is enabled, each managed cluster is allocated a global CIDR from the virtual Global Private Network. The global CIDR is used for supporting inter-cluster communication.

*Important:* You must enable Globalnet when clusters in a cluster set might have overlapping CIDRs.

After Submariner add-ons are installed on any clusters in the set, you cannot change the Globalnet setting. When using the console, the `ClusterAdmin` can enable Globalnet for a cluster set by selecting the option *Enable Globalnet* when enabling the Submariner add-on for clusters in the cluster set. After enabling Globalnet you cannot disable it, unless you remove Submariner.

When using the {product-title-short} APIs, the `ClusterAdmin` can enable Globalnet by creating a `submariner-broker` object in the `<ManagedClusterSet>-broker` namespace. 

The `ClusterAdmin` role has the required permissions to create this object in the broker namespace. The `ManagedClusterSetAdmin` role, which is sometimes created to act as a proxy administrator for the cluster set, does not have the required permissions. To provide the required permissions, the `ClusterAdmin` must associate the role permissions for the `access-to-brokers-submariner-crd` to the `ManagedClusterSetAdmin` user.

Complete the following steps to create the `submariner-broker` object:

. Retrieve the `<broker-namespace>` by running the following command:
+
----
oc get ManagedClusterSet <cluster-set-name> -o jsonpath="{.metadata.annotations['cluster\.open-cluster-management\.io/submariner-broker-ns']}"
----

. Create a `submariner-broker` object that specifies the Globalnet configuration by creating a YAML file named `submariner-broker`. Add content that resembles the following lines to the YAML file: 
+
[source,yaml]
----
apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
  name: submariner-broker
  namespace: <broker-namespace>
spec:
  globalnetEnabled: <true-or-false>
----
+
Replace `broker-namespace` with the name of your broker namespace. 
+
Replace `true-or-false` with `true` to enable Globalnet. 
+
*Note:* The `metadata` `name` parameter must be `submariner-broker`.

. Apply the file to your YAML file by entering the following command:
+
----
oc apply -f submariner-broker.yaml
----  

For more information about Globalnet, see link:https://submariner.io/getting-started/architecture/globalnet/[Globalnet controller] in the Submariner documentation.
