:_mod-docs-content-type: PROCEDURE

[#number-gateway-nodes]
= Number of gateway nodes

[role="_abstract"]
If you want to customize the number of your gateway nodes, customize and apply YAML content that is similar to the following example:

[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
   name: submariner
   namespace: <managed-cluster-namespace>
spec:
   credentialsSecret:
     name: <managed-cluster-name>-<provider>-creds
  gatewayConfig:
      gateways: <gateways>
----

* Replace `managed-cluster-namespace` with the namespace of your managed cluster.

* Replace `managed-cluster-name` with the name of your managed cluster. 

** AWS: Replace `provider` with `aws`. The value of `<managed-cluster-name>-aws-creds` is your AWS credential secret name, which you can find in the cluster namespace of your hub cluster. 

** GCP: Replace `provider` with `gcp`. The value of `<managed-cluster-name>-gcp-creds` is your Google Cloud Platform credential secret name, which you can find in the cluster namespace of your hub cluster.

** OpenStack: Replace `provider` with `osp`. The value of `<managed-cluster-name>-osp-creds` is your Red Hat OpenStack Platform credential secret name, which you can find in the cluster namespace of your hub cluster.

** Azure: Replace `provider` with `azure`. The value of `<managed-cluster-name>-azure-creds` is your Microsoft Azure credential secret name, which you can find in the cluster namespace of your hub cluster.

* Replace `gateways` with the number of gateways that you want to use. If the value is greater than 1, the Submariner gateway automatically enables high availability.

*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.
