[#configuring-submariner]
= Configuring Submariner

{acm} provides Submariner as an add-on for your hub cluster. To learn how to configure Submariner, read the following topics:

- <<submariner-prereqs,Prerequisites>>
- <<submariner-ports,Submariner ports table>>
- <<submariner-globalnet,Globalnet>>

[#submariner-prereqs]
== Prerequisites

Ensure that you have the following prerequisites before using Submariner:

* A credential to access the hub cluster with `cluster-admin` permissions.
* IP connectivity must be configured between the gateway nodes. When connecting two clusters, at least one of the clusters must be accessible to the gateway node by using its public or private IP address designated to the gateway node. See _Submariner NAT Traversal_ for more information.
* If you are using OVN Kubernetes, clusters must be on a supported version of {ocp-short}.
* If your {ocp-short} clusters use OpenShift SDN CNI, the firewall configuration across all nodes in each of the managed clusters must allow 4800/UDP in both directions.
* The firewall configuration must allow 4500/UDP and 4490/UDP on the gateway nodes for establishing tunnels between the managed clusters.
* For {ocp-short} ARM deployments, you must use the `c6g.large` `instanceType` or any other available instance type.
* If the gateway nodes are directly reachable over their private IPs without any NAT in between, make sure that the firewall configuration allows the ESP protocol on the gateway nodes.
+
*Note:* This is configured automatically when your clusters are deployed in an Amazon Web Services, Google Cloud Platform, Microsoft Azure, or Red Hat OpenStack environment, but must be configured manually for clusters on other environments and for the firewalls that protect private clouds.
+
* The `managedcluster` name must follow the DNS label standard as defined in RFC 1123 and meet the following requirements:
** Contain 63 characters or fewer
** Contain only lowercase alphanumeric characters or '-'
** Start with an alphanumeric character
** End with an alphanumeric character

[#submariner-ports]
== Submariner ports table

View the following table to see the Submariner ports that you must enable:

|===
| Name | Default value | Customizable | Optional or required

| IPsec NATT
| 4500/UDP
| Yes
| Required

| VXLAN
| 4800/UDP
| No
| Required

| NAT discovery port
| 4490/UDP
| No
| Required
|===

[#submariner-globalnet]
== Globalnet

Globalnet is a Submariner add-on feature that allows you to connect clusters with overlapping Classless Inter-Domain Routings (CIDRs), without changing the CIDRs on existing clusters. Globalnet is a cluster set-wide configuration that you can select when you add the first managed cluster to a cluster set.

If you enable Globalnet, every managed cluster receives a global CIDR from the virtual Global Private Network, which is used to facilitate inter-cluster communication.

*Important:* You must enable Globalnet when clusters in a cluster set might have overlapping CIDRs.

The `ClusterAdmin` can enable Globalnet in the console by selecting the option *Enable Globalnet* when enabling the Submariner add-on for clusters in the cluster set. If you want to disable Globalnet after enabling it, you must first remove all managed clusters from your cluster set.

[#submariner-globalnet-enable]
=== Enabling Globalnet by creating the _submariner-broker_ object

When using the {acm-short} APIs, the `ClusterAdmin` can enable Globalnet by creating a `submariner-broker` object in the `<ManagedClusterSet>-broker` namespace. 

The `ClusterAdmin` role has the required permissions to create the `submariner-broker` object in the broker namespace. The `ManagedClusterSetAdmin` role, which is sometimes created to act as a proxy administrator for the cluster set, does not have the required permissions.

To provide the required permissions, the `ClusterAdmin` must associate the role permissions for the `access-to-brokers-submariner-crd` to the `ManagedClusterSetAdmin` user.

Complete the following steps to enable Globalnet by creating the `submariner-broker` object:

. Retrieve the `<broker-namespace>` by running the following command:
+
----
oc get ManagedClusterSet <cluster-set-name> -o jsonpath="{.metadata.annotations['cluster\.open-cluster-management\.io/submariner-broker-ns']}"
----

. Create a `submariner-broker` object that specifies the Globalnet configuration by creating a YAML file named `submariner-broker`. Add content that resembles the following lines to the YAML file: 
+
[source,yaml]
----
apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
  name: submariner-broker <1>
  namespace: broker-namespace <2>
spec:
  globalnetEnabled: true-or-false <3>
----
+
<1> The name must be `submariner-broker`.
<2> Replace `broker-namespace` with the name of your broker namespace.
<3> Replace `true-or-false` with `true` to enable Globalnet.

. Apply the file by running the following command:
+
----
oc apply -f submariner-broker.yaml
----

[#subm-globalnet-numperip]
=== Configuring the number of global IPs

You can assign a configurable number of global IPs by changing the value of the `numberOfIPs` field in the `ClusterGlobalEgressIP` resource. The default value is 8. See the following example:

[source,yaml]
----
apiVersion: submariner.io/v1
kind: ClusterGlobalEgressIP
metadata:
  name: cluster-egress.submariner.io
spec:
  numberOfIPs: 8
----

[#subm-globalnet-resources]
=== Additional resources

- See the link:https://submariner.io/[Submariner documentation] to learn more about Submariner
- See link:https://submariner.io/operations/nat-traversal[Submariner NAT Traversal] for more information about IP connectivity between gateway nodes.
- See the link:https://submariner.io/getting-started/#prerequisites[Submariner prerequisites documentation] for more detailed information about the prerequisites.
- See link:https://submariner.io/getting-started/architecture/globalnet/[Globalnet controller] in the Submariner documentation for more information about Globalnet.
