:_mod-docs-content-type: CONCEPT

[#customized-submariner-subscription]
= Customized Submariner subscription 

[role="_abstract"]
The Submariner add-on automatically configures a subscription for Submariner; this ensures that the version of Submariner appropriate for the installed version of {acm-short} is installed and kept up-to-date. If you want to change this behavior, or if you want to manually control Submariner upgrades, you can customize the Submariner subscription.

When you use a customized Submariner subscription, you must complete the following fields:

* *Source:* The catalog source to use for the Submariner subscription. For example, `redhat-operators`. 
* *source Namespace:* The namespace of the catalog source. For example, `openshift-marketplace`.
* *Channel:* The channel to follow for the subscription. For example, for {acm-short} 2.12, enter `stable-0.19`.
* *Starting CSV (Optional):* The initial `ClusterServiceVersion`.  
* *Install Plan Approval:* The decision to manually or automatically approve install plans. 

*Note:* If you want to manually approve the install plan, you must use a customized Submariner subscription.  
