:_mod-docs-content-type: CONCEPT

[#submariner]
= Submariner multicluster networking and service discovery

[role="_abstract"]
Submariner is an open source tool that you can use with {acm} to provide direct networking and service discovery between two or more managed clusters in your environment, either on-premises or in the cloud. Submariner is compatible with Multi-Cluster Services API (link:https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api[Kubernetes Enhancements Proposal #1645]). For more information about Submariner, see the link:https://submariner.io/[Submariner site].

Submariner is not supported with all of the infrastructure providers that {acm-short} can manage. Refer to the link:https://access.redhat.com/articles/7142376[{acm-short} Support Matrix] for more details about the support levels of infrastructure providers, including which providers support xref:../submariner/deploy_subm_console.adoc#deploying-submariner-console[automated console deployments] or require xref:../submariner/deploy_subm_manual.adoc#deploying-submariner-manually[manual deployment].

See the following topics to learn more about how to use Submariner:

* xref:../submariner/subm_disconnected.adoc#deploying-submariner-disconnected[Deploying Submariner on disconnected clusters]
* xref:../submariner/subm_configure.adoc#configuring-submariner[Configuring Submariner]
* xref:../submariner/subm_ports_ref.adoc#submariner-ports[Submariner ports table]
* xref:../submariner/subm_vpc_config.adoc#subm-vpc-config[Configuring Submariner for an existing VPC]
* xref:../submariner/subm_globalnet.adoc#submariner-globalnet[Globalnet]
* xref:../submariner/subm_configure_rhos.adoc#configuring-submariner-rhos[Configuring Submariner for a {ocp} network]
* xref:../submariner/install_subctl.adoc#installing-subctl-command-utility[Installing the subctl command utility]
* xref:../submariner/deploy_subm_console.adoc#deploying-submariner-console[Deploying Submariner by using the console]
* xref:../submariner/deploy_subm_manual.adoc#deploying-submariner-manually[Deploying Submariner manually]
* xref:../submariner/subm_customize.adoc#customizing-submariner[Customizing Submariner deployments]
* xref:../submariner/service_discovery.adoc#managing-service-discovery-submariner[Managing service discovery for Submariner]
* xref:../submariner/uninstall_subm.adoc#uninstalling-submariner[Uninstalling Submariner]
