:_mod-docs-content-type: PROCEDURE

[#subm-vpc-config]
= Configuring Submariner for an existing VPC

[role="_abstract"]
If you installed your cluster into an existing Amazon Virtual Private Cloud (VPC) on Amazon Web Services (AWS), you must complete the following steps to configure Submariner:

.Procedure

. Open and edit the `SubmarinerConfig` file by running the following command. Replace values where needed:

+
[source,bash]
----
oc edit submarinerconfig -n <managed-cluster-ns> submariner
----

. Add the following annotations in the `metadata` field. Replace values where needed. All the IDs you need to add are alphanumeric:

+
[source,yaml]
----
annotations:
  submariner.io/control-plane-sg-id: <control-plane-group-id>
  submariner.io/subnet-id-list: <subnet-id-list>
  submariner.io/vpc-id: <custom-vpc-id>
  submariner.io/worker-sg-id: <worker-security-group-id>
----
* Replace with your control plane security group ID. Typically, you can find the ID from the control plane security group that has a name similar to `<infra-id>-master-sg>`.
* Replace with a comma-separated list of public subnet IDs in your custom VPC.
* Replace with your custom VPC ID.
* Replace with your worker security group ID. Typically, you can find the ID from the worker security group that has a name similar to `<infra-id>-worker-sg`.
