[#uninstalling-submariner]
= Uninstalling Submariner

You can uninstall the Submariner components from your clusters using the {product-title} console or the command-line. For Submariner versions earlier than 0.12, additional steps are needed to completely remove all data plane components. The Submariner uninstall is idempotent, so you can repeat steps without any issues.

[#uninstalling-submariner-console]
== Uninstalling Submariner by using the console

To uninstall Submariner from a cluster by using the console, complete the following steps:

. From the console navigation, select *Infrastructure* > *Clusters*, and select the _Cluster sets_ tab.

. Select the cluster set that contains the clusters from which you want to remove the Submariner components. 

. Select the *Submariner Add-ons* tab to view the clusters in the cluster set that have Submariner deployed. 

. In the _Actions_ menu for the cluster that you want to uninstall Submariner, select *Uninstall Add-on*. 

. In the _Actions_ menu for the cluster that you want to uninstall Submariner, select *Delete cluster sets*. 

. Repeat those steps for other clusters from which you are removing Submariner.
+
*Tip:* You can remove the Submariner add-on from multiple clusters in the same cluster set by selecting multiple clusters and clicking *Actions*. Select *Uninstall Submariner add-ons*. 

If the version of Submariner that you are removing is earlier than version 0.12, continue with <<uninstalling-submariner-manually,Uninstalling Submariner manually>>. If the Submariner version is 0.12 or later, Submariner is removed. 

*Important:* Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider. See <<verifying-subm-resource-removal,Verifying Submariner resource removal>> for more information.  

[#uninstalling-submariner-cli]
== Uninstalling Submariner by using the CLI

To uninstall Submariner by using the command line, complete the following steps:

. Remove the Submariner deployment for the cluster by running the following command:
+
----
oc -n <managed-cluster-namespace> delete managedclusteraddon submariner
----
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.

. Remove the cloud resources of the cluster by running the following command:
+
----
oc -n <managed-cluster-namespace> delete submarinerconfig submariner
----
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.

. Delete the cluster set to remove the broker details by running the following command:
+
----
oc delete managedclusterset <managedclusterset>
----
+
Replace `managedclusterset` with the name of your managed cluster set.

If the version of Submariner that you are removing is earlier than version 0.12, continue with <<uninstalling-submariner-manually,Uninstalling Submariner manually>>. If the Submariner version is 0.12 or later, Submariner is removed. 

**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider. See <<verifying-subm-resource-removal,Verifying Submariner resource removal>> for more information.

[#uninstalling-submariner-manually]
== Uninstalling Submariner manually

When uninstalling versions of Submariner that are earlier than version 0.12, complete steps 5-8 in the link:https://submariner.io/operations/cleanup/#manual-uninstall/[Manual Uninstall] section in the Submariner documentation.  

After completing those steps, your Submariner components are removed from the cluster. 

**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider. See <<verifying-subm-resource-removal,Verifying Submariner resource removal>> for more information.

[#verifying-subm-resource-removal]
== Verifying Submariner resource removal

After uninstalling Submariner, verify that all of the Submariner resources are removed from your clusters. If they remain on your clusters, some resources continue to accrue charges from infrastructure providers. Ensure that you have no additional Submariner resourceson your cluster by completing the following steps:

. Run the following command to list any Submariner resources that remain on the cluster:
+
----
oc get cluster <CLUSTER_NAME> grep submariner
----
+
Replace `CLUSTER_NAME` with the name of your cluster.

. Remove any resources on the list by entering the following command:
+
----
oc delete resource <RESOURCE_NAME> cluster <CLUSTER_NAME>
---- 
+
Replace `RESOURCE_NAME` with the name of the Submariner resource that you want to remove.

. Repeat steps 1-2 for each of the clusters until your search does not identify any resources. 

The Submariner resources are removed from your cluster.
