:_mod-docs-content-type: PROCEDURE

[#gitops-push-service-account]
= Create a custom service account for Argo CD Push model

[role="_abstract"]
Create a custom service account when you need a limited set of permissions for the Argo CD Push model on managed clusters. By using a different service account, you can control the permissions granted instead of using the default `application-manager` service account.

*Note:* Creating a custom service account is only available for the Push model.

*Required access:* Cluster administrator

.Prerequisites

* You have managed clusters registered with the {gitops} operator.

.Procedure

. Create a service account on a managed cluster by creating a `ManagedServiceAccount` resource on the hub cluster.

. Update the `GitOpsCluster` resource to use the managed service account that you created by adding the `managedServiceAccountRef` property. See the following example. Replace `<managed-sa-sample>` with the name of the service account you created:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-importer
  namespace: openshift-gitops
spec:
  managedServiceAccountRef: <managed-sa-sample>
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: gitops-placement
    namespace: openshift-gitops
----

. Verification

* Verify that the new Argo CD cluster secret is created. Run the following command. Replace `<managed-cluster>` with the name of the managed cluster and `<managed-sa-sample>` with the name of the service account you created:

+
[source,bash]
----
oc get secrets -n openshift-gitops <managed-cluster>-<managed-sa-sample>-cluster-secret
----
