:_mod-docs-content-type: CONCEPT

[#gitops_app_rollout_strategy]
= Implementing progressive rollout strategy by using _ApplicationSet_ resource (Technology Preview) 

[role="_abstract"]
By implementing the progressive rollout strategy to your application in your cluster fleet for both the push and pull model, you have a {gitops}-based process that makes changes safely across your entire cluster fleet. With the rollout strategy, you can orchestrate staged updates across different clusters. Additionally, you can promote changes throughout your label defined groups, such as development and product clusters. 

When you use the `ApplicationSet` resource for the progressive rollout strategy to your application, the `ApplicationSet` controller organizes the clusters for your application into groups. The controller processes one group at a time through the Argo CD health cycle, then only makes the group available if there is a `Healthy` status.

To learn more about implementing the progressive rollout strategy by using the `ApplicationSet` resource, complete the following sections: 


* xref:../gitops/gitops_enable_rollout_strategy.adoc#enabling-rollout-strategy[Enabling the progressive rollout strategy by using the _ApplicationSet_ resource]
* xref:../gitops/gitops_understand_appset_rollout.adoc#understanding-applicationset[Understanding a sample _ApplicationSet_ resource for the progressive rollout strategy]
* xref:../gitops/gitops_understand_labels_rollout.adoc#understanding-labels-applications[Understanding labels for applications that use the progressive rollout strategy]
* xref:../gitops/gitops_understand_git_rollout.adoc#understanding-changes-git-repository[Understanding changes to the Git repository that uses the progressive rollout strategy ]
