[#gitops-service-account-argo-cd]
= Creating a customized service account with Argo CD 

Create a service account on a managed cluster by creating a `managedserviceaccount` resource on the hub cluster. Use the `clusterpermission` resource to grant specific permissions to the service account.

By granting cluster permissions to your managed service accounts, you can deploy applications across managed clusters. 

Complete the following procedures:

. <<Creating a managed service account>> 
. <<Creating a cluster permission>> 
. <<Creating a managed service account in GitOpsCluster>> 
. <<Creating an Argo CD application>> 

== Creating a managed service account 

Create a managed service account so you can have cluster permissions for your other service accounts. When you create a managed service account, you simultaneously create a secret with the same name as the managed service account. This secret is in the cluster namespace for the hub cluster and contains the access token for the `managed-sa-sample` service account that is used in the Argo CD cluster secret.

. Ensure the `managedserviceaccount-preview` component is enabled by running, `oc edit mce multiclusterengine`. 
. For the `managedserviceaccount-preview` component, set `enabled=true`: 

+
[source,yaml]
----
% oc get mce multiclusterengine -o yaml 
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  availabilityConfig: High
  imagePullSecret: multiclusterhub-operator-pull-secret
  overrides:
    components:
    - enabled: true     =====> set enabled=true
      name: managedserviceaccount-preview
    ...
----

. Go to the hub cluster > `managed cluster` > `cluster1`. 
. To install the `managedserviceaccount` add-on on `cluster1`, apply the following YAML:

+
[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: managed-serviceaccount
  namespace: cluster1
spec:
  installNamespace: "open-cluster-management-agent-addon"
----

.  To verify the `managed-serviceaccount` add-on is running on the managed cluster, `cluster1`, run the following command: 

+
[source,yaml]
----
% oc get pods -n open-cluster-management-agent-addon
managed-serviceaccount-addon-agent-bb9799fbc-dwxzp   1/1     Running   0             47s
----

. To create the `managed-sa-sample` service account on `cluster1`, apply the following YAML on the hub cluster for the `managedserviceaccount` resource:

+
[source,yaml]
----
apiVersion: authentication.open-cluster-management.io/v1alpha1
kind: ManagedServiceAccount
metadata:
  name: managed-sa-sample
  namespace: cluster1
spec:
  rotation: {}
----

. To verify that the `managed-sa-sample` service account is created on `cluster1`, run the following command:  

+
[source,yaml]
----
// go to cluster1
% oc get sa -n open-cluster-management-agent-addon managed-sa-sample
----

. To access the secret for your managed service account, run the following command: 

+
[source,yaml]
----
// go to the hub cluster
% oc get secrets -n cluster1 managed-sa-sample
----

== Creating a cluster permission 

To grant permissions to the new service account, use the `clusterpermission` resource. The `clusterpermission` resource helps you deploy your applications. 

. To grant the `managed-sa-sample` service account permission to deploy your sample application, apply the following YAML: 

+
[source,yaml]
----
apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: clusterpermission-msa-subject-sample
  namespace: cluster1
spec:
  roles:
  - namespace: default
    rules:
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "create", "update", "delete", "patch"]
    - apiGroups: [""]
      resources: ["configmaps", "secrets", "pods", "podtemplates", "persistentvolumeclaims", "persistentvolumes"]
      verbs: ["get", "update", "list", "create", "delete", "patch"]
    - apiGroups: ["storage.k8s.io"]
      resources: ["*"]
      verbs: ["list"]
  - namespace: mortgage
    rules:
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "create", "update", "delete", "patch"]
    - apiGroups: [""]
      resources: ["configmaps", "secrets", "pods", "services", "namespace"]
      verbs: ["get", "update", "list", "create", "delete", "patch"]
  clusterRole:
    rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["get", "list"]
  roleBindings:
  - namespace: default
    roleRef:
      kind: Role
    subject:
      apiGroup: authentication.open-cluster-management.io
      kind: ManagedServiceAccount
      name: managed-sa-sample
  - namespace: mortgage
    roleRef:
      kind: Role
    subject:
      apiGroup: authentication.open-cluster-management.io
      kind: ManagedServiceAccount
      name: managed-sa-sample
  clusterRoleBinding:
    subject:
      apiGroup: authentication.open-cluster-management.io
      kind: ManagedServiceAccount
      name: managed-sa-sample
----

. Create a NC  `mortage` if one does not already exist. 
. Review the resources that are created on the `cluster1`. 

== Creating a managed service account in GitOpsCluster 

Use the GitOpsCluster to create the Argo CD cluster secret using the `managed-sa-sample` service account.

. To update the GitOpsCluster resource to add the `managedServiceAccountRef`, run the following YAML: 

+
[source,yaml]
----
spec:
  argoServer:
    argoNamespace: openshift-gitops
    cluster: local-cluster
  managedServiceAccountRef: managed-sa-sample
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: aws-app-placement
----

. To create a GitOpsCluster custom resource, run the following full YAML: 

+
[source,yaml]
----
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: openshift-gitops
spec:
  clusterSet: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: all-openshift-clusters
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: name
          operator: "In"
          values:
          - "cluster1"
---


apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-importer
  namespace: openshift-gitops
spec:
  managedServiceAccountRef: managed-sa-sample
  argoServer:
    cluster: notused
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
----

. Go to the `openshift-gitops` namespace and verify that there is a new Argo CD cluster secret with the name `cluster1-managed-sa-sample-cluster-secret`:

+
[source,yaml]
----
% oc get secrets -n openshift-gitops cluster1-managed-sa-sample-cluster-secret    
NAME                                        TYPE     DATA   AGE
cluster1-managed-sa-sample-cluster-secret   Opaque   3      4m2s
----

== Creating an Argo CD application 

Use your cluster secret to deliver an Argo CD application from the Argo CD UI. The Argo CD application is delivered by the managed service account, `managed-sa-sample`. 

. Log into the Argo CD console. 
. Click *Create a new application*. 
. Choose the cluster URL. 
. Go to your Argo CD application and verify that it has the given permissions, like roles and cluster roles, that you propagated to `cluster1`. 

