:_mod-docs-content-type: CONCEPT

[#understanding-changes-git-repository]
= Understanding changes to the Git repository that uses the progressive rollout strategy 

[role="_abstract"]
To start the progressive rollout strategy for your `ApplicationSet` resource on your cluster fleet, the Argo CD application checks your Git repository for committed changes. When there are committed changes, the progressive rollout strategy begins. 

When Argo CD starts the rollout strategy, the `ApplicationSet` controller detects the applications that have the `OutOfSync` status and schedules applications for a staged rollout. Based on the labels you use for your application groups, the `ApplicationSet` controller starts the first `RollingSync` step with the `env-dev` application group. 

From the Argo CD health cycle, you can watch each application group move from `OutOfSync` to a `Healthy` status. After all your application groups have a `Healthy` status, the `ApplicationSet` controller syncs the application group with the `env-qa` label,  then the application group with the `env-prod` label. After your last `env-prod` application group has a `Healthy` status, the progressive rollout strategy completes automatically and fully runs its strategy on your cluster fleet. 
