:_mod-docs-content-type: CONCEPT

[#gitops-service-account-argo-cd]
= Creating a customized service account for Argo CD push model

[role="_abstract"]
Create a service account on a managed cluster by creating a `ManagedServiceAccount` resource on the hub cluster. Use the `ClusterPermission` resource to grant specific permissions to the service account.

Creating a customzied service account for use with the Argo CD push model includes the following benefits: 

* An Application manager add-on runs on each managed cluster. By default, the Argo CD controller uses the service account Application manager to push these resources to the managed cluster. 
* The Application manager service account has a large set of permissions because the application subscription add-on uses the Application manager service to deploy applications on the managed cluster. Do not use the Application manager service account if you want a limited set of permissions. 
* You can specify a different service account that you want the Argo CD push model to use. When the Argo CD controller pushes resources from the centralized hub cluster to the managed cluster, you can use a different service account than the default Application manager. By using a different service account, you can control the permissions that are granted to this service account. 
* The service account must exist on the managed cluster. To facilitate the creation of the service account with the associated permissions, use the `ManagedServiceAccount` resource and the new `ClusterPermission` resource on the centralized hub cluster. 

After completing all the following procedures, you can grant cluster permissions to your managed service account. Having the cluster permissions, your managed service account has the necessary permissions to deploy your application resources on the managed clusters. Complete the following procedures:

.Additional resources

* link:../clusters/cluster_lifecycle/addon_managed_service.adoc#managed-serviceaccount-addon[Enabling ManagedServiceAccount add-ons]
* xref:../gitops/gitops_use_service_account.adoc#using-service-account[Using a managed service account in the _GitOpsCluster_ resource]
* xref:../gitops/gitops_create_argocd_app.adoc#creating-argocd-application[Creating an Argo CD application ]
* xref:../gitops/gitops_use_policy_msa.adoc#using-policy[Using policy to create managed service accounts and cluster permissions ]
