[#manage-gitops-addon]
= Managing the {gitops} add-on  

The {gitops-short} add-on automates the deployment and lifecycle management of the managed clusters. Based on your architecture and connectivity requirements, decide if you want to deploy the GitOps add-on with the `ArgoCD` agent component. Otherwise, you can deploy the {gitops-short} add-on without the `ArgoCD` agent. 

*Important:* If you enable the {gitops-short} add-on by using the `GitOpsCluster` custom resource, then the `GitOpsCluster` disables the `Push Model` for all applications.

When you enable the {gitops-short} add-on, you have the following deployment modes: 

* `Basic` mode: Deploys the {gitops-short} operator and the `ArgoCD`  instance on managed clusters through the `GitOpsCluster` custom resource. 

* `Agent` mode: Includes all basic mode components along with the `ArgoCD` agent for enhanced pull-based architecture. 

To enable the {gitops-short} add-on for your selected managed clusters, reference your `Placement` and use the `GitOpsCluster` custom resource as the interface for enabling. 

.Prerequisites 

If you want to enable the {gitops-short} add-on with the `ArgoCD` agent, use the `Agent` mode. See xref:../gitops/gitops_addon_with_argocd.adoc#enable-gitops-addon-with-argocd[Enabling {gitops} add-on with _ArgoCD_ agent] 

If you want to enable the {gitops-short} add-on without the `ArgoCD` agent, use the `Basic` mode. See xref:../gitops/gitops_addon_without_argocd.adoc#enable-gitops-addon-without-argocd[Enabling {gitops} add-on without the _ArgoCD_ agent]


== Configuring {gitops-short} add-on settings

The {gitops-short} add-on supports various configuration options to customize the deployment according to your requirements.

The {gitops-short} add-on supports the following configuration options in the `gitopsAddon` specification:

* `enabled`: Enable or disable the GitOps add-on. The default is `false`. 
* `gitOpsOperatorImage`: Custom container image for the GitOps operator.
* `gitOpsImage`: Custom container image for `ArgoCD` components.
* `redisImage`: Custom container image for `Redis`.
* `gitOpsOperatorNamespace`: Namespace where the GitOps operator is deployed. The default is `openshift-gitops-operator`.
* `gitOpsNamespace`: Namespace where `ArgoCD` instance is deployed. The default is`openshift-gitops`.
* `reconcileScope`: Control `ArgoCD` reconciliation scope that includes `All-Namespaces` or `Single-Namespace`. The default: `Single-Namespaces`.
* `overrideExistingConfigs`: Override existing `AddOnDeploymentConfig` values with new values from `GitOpsCluster` specification. Must be set to `true` when performing any uninstall operation. The default is `false`.
* `argoCDAgent`: `ArgoCD` agent configuration sub-section. 

The Argo CD Agent supports the following configuration options in the `argoCDAgent` specification:

* `enabled`: Enable or disable the agent. The default `false`.
* `propagateHubCA`: Propagate hub certified authority (CA) certificate to managed clusters. The default is `true`.
* `image`: Custom agent container image.
* `serverAddress`: Override the `ArgoCD` agent principal server address.
* `serverPort`: Override the  `ArgoCD` agent principal server port.
* `mode`: Agent operation mode. The default is `managed`.

To configure the {gitops-short} add-on setting, complete the following steps on your hub cluster: 

. Customize your container images for the {gitops-short} components by adding the YAML sample with the `GitOpsCluster`:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-custom-images
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    gitOpsOperatorImage: "registry.redhat.io/openshift-gitops-1/gitops-operator@sha256:..."
    gitOpsImage: "registry.redhat.io/openshift-gitops-1/argocd@sha256:..."
    redisImage: "registry.redhat.io/rhel8/redis-6@sha256:..."
----

. Apply the YAML sample by running the following command:  

+
[source,bash]
----
oc apply -f gitopscluster-example.yaml 
----

. Customize the namespaces where you deploy the the {gitops-short} components by adding the following YAML with the `GitOpsCluster`:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-custom-namespaces
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    gitOpsOperatorNamespace: openshift-gitops-operator
    gitOpsNamespace: openshift-gitops
----

. Apply the YAML sample by running the following command:  

+
[source,bash]
----
oc apply -f gitopscluster-example.yaml 
----

. Specify if the `ArgoCD` agent can reconcile application in all namespaces by adding the following YAML with the `GitOpsCluster`:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-reconcile-scope
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    reconcileScope: 
----
+
.. For the `reconcileScope` field, give it the `All-Namespaces` value if you want the `ArgoCD` instance to reconcile applications in all namespaces.
.. For the `reconcileScope` field, give it the `Single-Namespace` value if you want the the `ArgoCD` instance to only reconcile applications in its own namespace.

. Apply the YAML sample by running the following command:

+
[source,bash]
----
oc apply -f gitopscluster-example.yaml 
----


.Additional resources

You can skip specific {gitops-short} add-on functionalities that you do not want. See xref:../gitops/gitops_skip_addon.adoc#skip-gitops-addon[Skipping the {gitops-short} add-on enforcement].

To verify that your {gitops-short} add-on works, see xref:../gitops/gitops_verify_addon.adoc#verify-gitops-addon[Verifying the {gitops-short) add-on functions].

To verify that your `ArgoCD` agent works, see xref:../gitops/gitops_verify_argocd.adoc#verify-argocd-agent[Verifying the _ArgoCD_ agent function].

To learn more about {gitops-short}, see the following documentation: 

* xref:../gitops/gitops_push_pull.adoc#gitops-push-pull[Deploying Argo CD with Push and Pull model]
* xref:../gitops/gitops_registering.adoc#gitops-register[Registering managed clusters to {gitops} operator]
* xref:../gitops/gitops_console.adoc#gitops-console[GitOps console] 