:_mod-docs-content-type: PROCEDURE

[#manage-gitops-addon]
= Managing the {gitops} add-on  

[role="_abstract"]
The {gitops-short} add-on automates the deployment and lifecycle management of {gitops-short} on the managed clusters. Based on your architecture and connectivity requirements, decide if you want to deploy the GitOps add-on with the Argo CD Agent component. Otherwise, you can deploy the {gitops-short} add-on without the Argo CD Agent. 

*Important:* If you enable the {gitops-short} add-on by using the `GitOpsCluster` custom resource, then the `GitOpsCluster` disables the `Push Model` for all applications.

When you enable the {gitops-short} add-on, you have the following deployment modes: 

`Basic` mode:: Deploys the {gitops-short} operator and the `ArgoCD` instance on managed clusters through the `GitOpsCluster` custom resource. For {ocp-short} managed clusters, enable a deployment based on {olm} by setting `olmSubscription.enabled: true`.

`Agent` mode (Technology Preview):: Includes all `Basic` mode components along with the Argo CD Agent for enhanced pull-based architecture.

The {gitops-short} add-on supports various configuration options to customize the deployment according to your requirements.

The {gitops-short} add-on supports the following configuration options in the `gitopsAddon` specification:

`enabled`:: Enable or disable the GitOps add-on. The default value is `false`. 
`gitOpsOperatorImage`:: The only custom container image for the GitOps operator that you need to specify.
`overrideExistingConfigs`:: Override existing `AddOnDeploymentConfig` values with new values from `GitOpsCluster` specification. If you use the default value of `false`, existing config values are preserved and only new values are added. If you set the value to `true`, config values from the `GitOpsCluster` specification override existing values.
`olmSubscription`:: The {olm} subscription configuration. If you set `olmSubscription.enabled` to `true`, the add-on agent uses the {olm} subscription mode for the operator installation, regardless of {ocp} auto-detection.
`argoCDAgent`:: Argo CD Agent configuration.

The Argo CD Agent supports the following configuration options in the `argoCDAgent` specification:

`enabled`:: Enable or disable the agent. The default value is `false`.
`image`:: Custom agent container image.
`serverAddress`:: Override the `ArgoCD` agent principal server address.
`serverPort`:: Override the  `ArgoCD` agent principal server port.
`mode`:: Agent operation mode. The default is value is `managed`.

.Prerequisites 

- If you want to enable the {gitops-short} add-on with the Argo CD Agent, use the `Agent` mode. See xref:../gitops/gitops_addon_with_argocd.adoc#enable-gitops-addon-with-argocd[Enabling {gitops} add-on with Argo CD Agent].

- If you want to enable the {gitops-short} add-on without the Argo CD Agent, use the `Basic` mode. See xref:../gitops/gitops_addon_without_argocd.adoc#enable-gitops-addon-without-argocd[Enabling {gitops} add-on without the Argo CD Agent].

.Procedure

To enable the {gitops-short} add-on for your selected managed clusters, reference your `Placement` resource and use the `GitOpsCluster` custom resource for enabling. To configure the {gitops-short} add-on setting, complete the following steps on your hub cluster: 

. Customize your container images for the {gitops-short} components by adding the YAML sample with the `GitOpsCluster`:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-custom-images
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    gitOpsOperatorImage: "registry.redhat.io/openshift-gitops-1/gitops-operator@sha256:..."
    gitOpsImage: "registry.redhat.io/openshift-gitops-1/argocd@sha256:..."
    redisImage: "registry.redhat.io/rhel8/redis-6@sha256:..."
----

. Apply the YAML sample by running the following command:  

+
[source,bash]
----
oc apply -f gitopscluster-example.yaml 
----

. Customize the namespaces where you deploy the the {gitops-short} components by adding the following YAML with the `GitOpsCluster`:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-custom-namespaces
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    gitOpsOperatorNamespace: openshift-gitops-operator
    gitOpsNamespace: openshift-gitops
----

. Apply the YAML sample by running the following command:  

+
[source,bash]
----
oc apply -f gitopscluster-example.yaml 
----

. Specify if the Argo CD Agent can reconcile application in all namespaces.
.. If you want the `ArgoCD` instance to reconcile applications in all namespaces, set the `reconcileScope` field to `All-Namespaces`.
.. If you want the the `ArgoCD` instance to only reconcile applications in its own namespace, set the `reconcileScope` field to `Single-Namespace`. View the following `GitOpsCluster` resource file:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-reconcile-scope
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    reconcileScope: 
----

. Apply the YAML sample by running the following command:

+
[source,bash]
----
oc apply -f gitopscluster-example.yaml 
----

.Additional resources

- You can skip specific {gitops-short} add-on functionalities that you do not want. See xref:../gitops/gitops_skip_addon.adoc#skip-gitops-addon[Skipping the {gitops-short} add-on enforcement].

To verify that your {gitops-short} add-on works, see xref:../gitops/gitops_verify_addon.adoc#verify-gitops-addon[Verifying the {gitops-short} add-on functions].

- To verify that your Argo CD Agent works, see xref:../gitops/gitops_verify_argocd.adoc#verify-argocd-agent[Verifying the Argo CD Agent function].

- To learn more about {gitops-short}, see the following documentation: 

* xref:../gitops/gitops_push_pull.adoc#gitops-push-pull[Deploying Argo CD with Push and Pull model]
* xref:../gitops/gitops_registering.adoc#gitops-register[Registering managed clusters to {gitops} operator]
* xref:../gitops/gitops_console.adoc#gitops-console[GitOps console]
