:_mod-docs-content-type: PROCEDURE

[#customizing-your-repo]
= Customizing your local repository

[role="_abstract"]
Customize your local repository by consolidating the `stable` and `community` policies into a single folder. Remove the policies you do not want to use. Complete the following steps to customize your local repository:

. Create a new directory in the repository to hold the policies that you want to deploy. Be sure that you are in your local `policy-collection` repository on your main default branch for GitOps. Run the following command:

+
----
mkdir my-policies
----

. Copy all of the `stable` and `community` policies into your `my-policies` directory. Start with the `community` policies first, in case the `stable` folder contains duplicates of what is available in the community. Run the following commands:

+
----
cp -R community/* my-policies/

cp -R stable/* my-policies/
----
+
Now that you have all of the policies in a single parent directory structure, you can edit the policies in your fork.
+
*Tips:*

* It is best practice to remove the policies you are not planning to use.

* Learn about policies and the definition of the policies from the following list:

** Purpose: Understand what the policy does.

** Remediation Action: Does the policy only inform you of compliance, or enforce the policy and make changes? See the `spec.remediationAction` parameter. If changes are enforced, make sure you understand the functional expectation. Remember to check which policies support enforcement. For more information, view the _Validate_ section.
+
*Note:* The `spec.remediationAction` set for the policy overrides any remediation action that is set in the individual `spec.policy-templates`.

** Placement: What clusters is the policy deployed to? By default, most policies target the clusters with the `environment: dev` label. Some policies may target {ocp-short} clusters or another label. You can update or add additional labels to include other clusters. When there is no specific value, the policy is applied to all of your clusters. You can also create multiple copies of a policy and customize each one if you want to use a policy that is configured one way for one set of clusters and configured another way for another set of clusters.

