:_mod-docs-content-type: CONCEPT

[#arch-push]
= Architecture Push model

[role="_abstract"]
- With Push model, {ocp-short} GitOps applies resources _directly_ from a centralized hub cluster to the managed clusters.

- An Argo CD application that is running on the hub cluster communicates with the GitHub repository and deploys the manifests directly to the managed clusters.

- Push model implementation only contains the Argo CD application on the hub cluster, which has credentials for managed clusters. The Argo CD application on the hub cluster can deploy the applications to the managed clusters.

- *Important:* With a large number of managed clusters that require resource application, consider potential strain on the {gitops-short} GitOps controller memory and CPU usage. To optimize resource management, see link:https://docs.redhat.com/en/documentation/red_hat_openshift_gitops/1.12/html/managing_resource_use/configuring-resource-quota[Configuring resource quota or requests] in the {gitops} documentation.

- By default, the Push model is used to deploy the application unless you add the `apps.open-cluster-management.io/ocm-managed-cluster` and `apps.open-cluster-management.io/pull-to-ocm-managed-cluster` annotations to the template section of the `ApplicationSet`.
