:_mod-docs-content-type: CONCEPT

[#gitops-overview]
= {gitops} overview

[role="_abstract"]
{gitops} and Argo CD are integrated with {acm}. You can use the {gitops} Operator to manage applications across your managed clusters with Argo CD.

{acm} supports two main ways to use {gitops-short} with managed clusters: the *Push model* and the *Pull model*. In the Push model, the Argo CD server on the hub cluster deploys resources directly to managed clusters. In the Pull model, each managed cluster runs its own Argo CD instance and synchronizes it from Git.

All supported models use the `GitOpsCluster` custom resource for configuration and the `ApplicationSet` resource with a `clusterDecisionResource` generator to deploy applications across managed clusters.

*Important:* {acm-short} does not include entitlements for {gitops-short}. You need a separate {ocp} subscription for the following features:

* {gitops} (excluding the Argo CD Agent) requires an {ocp} subscription.
* The Argo CD Agent requires a Red Hat OpenShift Platform Plus subscription. The Argo CD Agent can run on {ocp-short} or in supported Kubernetes environments.

For more information, see the link:https://www.redhat.com/en/resources/self-managed-openshift-subscription-guide[Self-managed Red Hat OpenShift subscription guide].

See the following topics to get started:

* xref:../gitops/gitops_models.adoc#gitops-models[Understanding the Push and Pull models]
* xref:../gitops/gitops_placement.adoc#gitops-placement[Configuring Placement resources for {gitops-short}]
* xref:../gitops/gitops_push.adoc#gitops-push[Using the Push model]
* xref:../gitops/gitops_pull.adoc#gitops-pull[Using the Pull model]
* xref:../gitops/gitops_console.adoc#gitops-console[{gitops-short} console]
* xref:../gitops/gitops_policies.adoc#gitops-policies[Managing policy definitions with {gitops}]
* xref:../gitops/gitops_deprecated.adoc#gitops-deprecated[Deprecated APIs]
