[#verify-gitops-addon]
= Verifying the {gitops-short) add-on functions 

You can verify that your {gitops-short} add-on functions work by completing the following sections: 

== Verifying the _GitOpsCluster_ status

To check the `GitOpsCluster` status, complete the following steps: 

. View the `GitOpsCluster` resource status by running the following command:

+
[source,bash]
----
oc get gitopscluster <gitopscluster-name> -n openshift-gitops -o yaml
----

. Check the status conditions for specific failure information by running the following command:

+
[source,bash]
----
oc get gitopscluster <gitopscluster-name> -n openshift-gitops -o jsonpath='{.status.conditions}' | jq
----

See the following common condition types to check:

* `Ready` : Overall `GitOpsCluster` health
* `PlacementResolved` :  `Placement` resource status
* `ClustersRegistered` : Cluster registration status
* `ArgoCDAgentPrereqsReady` :  Agent prerequisites, if you have enabled the agent 
* `CertificatesReady` : TLS certificate status, if you have enabled the agent. 
* `ManifestWorksApplied` : `ManifestWork` propagation status if you have enabled the agent. 


== Verifying the {gitops-short} add-on controller logs

To check the {gitops-short} add-on controller logs, complete the following steps: 

. Go to the managed cluster. 
. Check the {gitops-short} add-on controller logs by running the following command:

+
[source,bash]
----
oc logs -n open-cluster-management-agent-addon -l app=gitops-addon
----

== Verifying the {gitops-short} operator

To confirm that the {gitops-short} operator works, complete the following steps: 

. Verify the operator is working by running the following command: 

+
[source,bash]
----
oc get pods -n openshift-gitops-operator
----

. Check operator logs by running the following command:

+
[source,bash]
----
oc logs -n openshift-gitops-operator -l control-plane=controller-manager
----