[#manage-gitops-addon]
= Managing the {gitops} add-on  

The {gitops-short} add-on automates the deployment and lifecycle management of the managed clusters. Based on your architecture and connectivity requirements, decide if you want to deploy the GitOps add-on with the `ArgoCD` agent component.

*Important:* If you enable the {gitops-short} add-on using the `GitOpsCluster` custom resource, then the `GitOpsCluster` disables the `Push Model` for all applications.

When you enable the {gitops-short} add-on, you have the following deployment modes: 

* `Basic` mode: Deploys the {gitops-short} operator and the `ArgoCD`  instance on managed clusters through the `GitOpsCluster` custom resource. 

* `Agent` mode: Includes all basic mode components along with the `ArgoCD` agent for enhanced pull-based architecture. 

To enable the GitOps add-on for your selected managed clusters, reference your `Placement` and use the `GitOpsCluster` custom resource as the interface for enabling. To enable and manage the GitOps add-on, complete the following sections: 

* <<Prerequisites, Prerequisites>>
* <<configure-gitops-addon, Configuring GitOps add-on settings>>
* <<skip-gitops-addon, Skipping the GitOps add-on enhancement>>
* <<skip-enforcements-argocd, Skipping enforcements by customizing the _ArgoCD_ custom resource>> 
* <<uninstall-gitops-addon, Uninstalling the GitOps add-on>>
* <<Additional-resources, Additional resources>> 

[#prerequisites]
== Prerequisites 

If you want to enable the GitOps add-on with the `ArgoCd` agent, use the `Agent` mode. This mode extends the basic GitOps add-on with the `ArgoCD` agent component, enabling a `Pull Model` architecture. Use the `Agent` mode in environments with network restrictions, enhanced security requirements, or when you implement a `Pull Model` for application delivery.  The `Advanced` pull model is powered by the `ArgoCD` agent and gives you a fully automated GitOps experience. 

If you want to enable the GitOps add-on without the `ArgoCD` agent, use the `Basic` mode. This mode enables the GitOps add-on to the managed clusters that you selected with the `Placement`. After enabling the add-on, the `Basic` mode deploys the {gitops-short} `ArgoCD` components that are suitable for the cluster workflows. 

Based on your decision, complete one of the following sections: 

* xref:../gitops/gitops_addon_with_argocd.adoc#enable-gitops-addon-with-argocd[Enabling {gitops} add-on with _ArgoCD_ agent]
* xref:../gitops/gitops_addon_without_argocd.adoc#enable-gitops-addon-without-argocd[Enabling {gitops} add-on without the  _ArgoCD_ agent]


[#configure-gitops-addon]
== Configuring {gitops-short} add-on settings

The {gitops-short} add-on supports various configuration options to customize the deployment according to your requirements.

The {gitops-short} add-on supports the following configuration options in the `gitopsAddon` specification:

* `enabled`: Enable or disable the GitOps add-on. The default is `false`. 
* `gitOpsOperatorImage`: Custom container image for the GitOps operator.
* `gitOpsImage`: Custom container image for `ArgoCD` components.
* `redisImage`: Custom container image for `Redis`.
* `gitOpsOperatorNamespace`: Namespace where the GitOps operator is deployed. The default is `openshift-gitops-operator`.
* `gitOpsNamespace`: Namespace where `ArgoCD` instance is deployed. The default is`openshift-gitops`.
* `reconcileScope`: Control `ArgoCD` reconciliation scope that includes `All-Namespaces` or `Single-Namespace`. The default: `Single-Namespaces`.
* `overrideExistingConfigs`: Override existing `AddOnDeploymentConfig` values with new values from GitOpsCluster spec. Must be set to `true` when performing any uninstall operation. The default is `false`.
* `argoCDAgent`: `ArgoCD` agent configuration sub-section. 

The Argo CD Agent supports the following configuration options in the `argoCDAgent` spec:

* `enabled`: Enable or disable the agent. The default `false`.
* `propagateHubCA`: Propagate hub certified authority (CA) certificate to managed clusters. The default is `true`.
* `image`: Custom agent container image
* `serverAddress`: Override `ArgoCD` Agent principal server address.
* `serverPort`: Override `ArgoCD` Agent principal server port.
* `mode`: Agent operation mode. The default is `managed`.
* `uninstall`: Uninstall only the agent while keeping the GitOps add-on. 

To configure the {gitops-short} add-on setting, complete the following steps: 

. Customize your container images for the {gitops-short} components by applying the following YAML:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-custom-images
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    gitOpsOperatorImage: "registry.redhat.io/openshift-gitops-1/gitops-operator@sha256:..."
    gitOpsImage: "registry.redhat.io/openshift-gitops-1/argocd@sha256:..."
    redisImage: "registry.redhat.io/rhel8/redis-6@sha256:..."
----

. Customize the namespaces where you deploy the the {gitops-short}components by applying the following YAML:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-custom-namespaces
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    gitOpsOperatorNamespace: openshift-gitops-operator
    gitOpsNamespace: openshift-gitops
----

. Specify if the `ArgoCD` agent can reconcile application in all namespaces or only in its namespace by applying the following YAML: 

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-reconcile-scope
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    reconcileScope: <1> or <2> 
----
+
<1> `All-Namespaces`: The `ArgoCD` instance that can reconcile applications in all namespaces.
<2> `Single-Namespace`: The `ArgoCD` instance that can only reconcile applications in its own namespace.

[#skip-gitops-addon]
== Skipping the {gitops-short} add-on enforcement

The {gitops-short} add-on enforces certain resources on the managed clusters to maintain consistency. You can skip enforcement for specific resources by adding the `gitops-addon.open-cluster-management.io/skip` annotation to those specific resources on the managed cluster. Skipping enforcements helps you when you need to customize the `ArgoCD` custom resource or other {gitops-short} components that the add-on manages.

When a resource on the managed cluster has the skip annotation, the {gitops-short} add-on does not update or manage that resource. The add-on checks for this annotation before applying any changes, allowing you to maintain custom configurations that are different from the default settings for the add-on.

*Note:* When using the skip annotation, ensure that your custom configurations are compatible with the {gitops-short} add-on requirements. Skipping enforcement means the {gitops-short} add-on does not manage or reconcile these resources, so you are responsible for maintaining their consistency and correctness.

To skip enforcement for a resource, add the following annotation to the resource on the managed cluster:

[source,yaml]
----
metadata:
  Annotations:
    gitops-addon.open-cluster-management.io/skip: "true"
----

For managing skip annotations across many managed clusters at scale, use the {acm-short} `Policy` to apply the annotation across the fleet. 

[#skip-enforcements-argocd]
== Skipping enforcements by customizing the _ArgoCD_ custom resource

Customizing the `ArgoCD` custom resource is a common use case to adjust resource limits, configure specific settings, or enable additional features. 

To skip enforcement by customizing the `ArgoCD` custom resource, complete the following steps:

. On the managed cluster, edit the `ArgoCD` custom resource:

+
[source,bash]
----
oc edit argocd openshift-gitops -n openshift-gitops
----

. Add the `gitops-addon.open-cluster-management.io/skip` annotation and set to `true`, as displayed in the following YAML:

+
[source,yaml]
----
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
  annotations:
    gitops-addon.open-cluster-management.io/skip: "true"
----

.  Optional: Override the existing configuration values that the `GitOpsCluster` maintains in the `AddOnDeploymentConfig` spec by applying the following yaml:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-override-config
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    overrideExistingConfigs: true
    gitOpsImage: "registry.redhat.io/openshift-gitops-1/argocd@sha256:..."
----

[#uninstall-gitops-addon]
== Uninstalling the {gitops-short} add-on

To completely uninstall the GitOps add-on, including its operator and the `GitOpsCluster` resource, complete the following steps:

. Set the `uninstall` flag in the `GitOpsCluster` and wait for uninstallation to complete.
. Delete the `GitOpsCluster` resource by running the following command: 

+
[source,bash]
----
oc delete gitopscluster gitops-clusters -n openshift-gitops
----

. Verify that the `ManagedClusterAddOn` resources are removed from managed cluster namespaces by running the following command: :
+
[source,bash]
----
oc get managedclusteraddon gitops-addon -n <managed-cluster-name>
----

[#additional-resources] 
== Additional resources

For help with troubleshooting, see xref:../troubleshooting/trouble_gitops_addon.adoc#troubleshooting-gitops-addon[Troubleshooting {gitops} add-on].

To learn more about {gitops-short}, see the following documentation: 

* xref:../gitops/gitops_push_pull.adoc#gitops-push-pull[Deploying Argo CD with Push and Pull model]
* xref:../gitops/gitops_registering.adoc#gitops-register[Registering managed clusters to {gitops} operator]
* xref:../gitops/gitops_console.adoc#gitops-console[GitOps console] 