:_mod-docs-content-type: PROCEDURE

[#enable-gitops-addon-with-argocd]
= Enabling {gitops} add-on with _ArgoCD_ agent (Technology Preview)

[role="_abstract"]
Use `Agent` mode for the pull model to enable the {gitops-short} add-on and receive application health statuses. This mode is for environments with network restrictions, enhanced security requirements, or when implementing a pull model for application delivery. The `Advanced` pull model uses the `ArgoCD` agent to deliver a fully automated {gitops-short} experience.

.Prerequisites

* {acm-short} hub cluster installed.
* Managed clusters registered with {acm-short}.
* {gitops-short} operator installed on the hub cluster.
* A `Placement` resource to select target managed clusters.
* `ManagedClusterSet` bound to the target namespace.
* {gitops-short} operator subscription configured with the `ArgoCD` agent environment.
* The `ArgoCD` custom resource is configured for the `Agent` mode. For more information see xref:../gitops/gitops_configure.adoc#configuring-argocd-agent[Configuring subscriptions and resources for Argo CD].

.Procedure 

Create a `GitOpsCluster` resource to manage the `ArgoCD` agent add-on deployment. To enable the advanced pull model for Argo CD Agent architecture, complete the following steps:

. On your managed cluster, create a `GitOpsCluster`` resource with the `ArgoCD` agent enabled by adding the following YAML sample: 

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-agent-clusters
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: production-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    argoCDAgent:
      enabled: true
----

. Apply the YAML sample by running the following command:  

+
[source,bash]
----
oc apply -f gitopscluster-example.yaml
----

== Verifying the _ArgoCD_ installation 

After the `ArgoCD` agent is successfully deployed, verify the completion of the advanced `Pull Model` workflow by creating an application on the hub cluster and confirming it works on the managed cluster. 

To verify the necessary installations and resources for successful deployment, complete the following steps:

. Check the `GitOpsCluster` status for specific `Agent` conditions by running the following command:

+
[source,bash]
----
oc get gitopscluster gitops-agent-clusters -n openshift-gitops -o jsonpath='{.status.conditions}' | jq
----

. Confirm that you see the following condition types in the status:

+
`Ready`:: The `GitOpsCluster` is ready and all the components are functioning. 
`PlacementResolved`:: The `Placement` reference is resolved and the managed clusters are retrieved. 
`ClustersRegistered`: The managed clusters are successfully registered with  the `ArgoCD` server.
`AddOnDeploymentConfigsReady`:: The `AddOnDeploymentConfigs` are created for all the managed clusters.
`ManagedClusterAddOnsReady`:: The `ManagedClusterAddons` creates and updates the managed clusters. 
`AddOnTemplateReady`:: The dynamic `AddOnTemplate` created for the `ArgoCD` agent mode. 
`ArgoCDAgentPrereqsReady`:: The agent prerequisites are set up.
`CertificatesReady`:: The TLS certificates are signed.
`ManifestWorksApplied`:: The CA certificates propagated to managed clusters.

. Create an `ArgoCD` application resource in the managed cluster namespace by adding the following YAML file: 

+
[source,yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: <managed cluster name>
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://<principal-external-ip:port>?agentName=<managed cluster name>
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
----

. Apply the YAML sample by running the following command: 

+
[source,bash]
----
oc apply -f application-example.yaml 
----

. On the managed cluster, verify the deployment of the application resources by running the following command:

+
[source,bash]
----
oc get all -n guestbook
----

. On the hub cluster, verify the application status appears by running the following command:

+
[source,bash]
----
oc get application guestbook -n <managed cluster name>
----

. Confirm that the status shows `Synced` when the application is successfully deployed.

.Additional resources 

Continue setting up the {gitops-short} add-on by completing xref:../gitops/gitops_manage_addon.adoc#manage-gitops-addon[Managing the {gitops} add-on].
