:_mod-docs-content-type: CONCEPT

[#gitops-console]
= GitOps console

[role="_abstract"]
Learn more about integrated {ocp-short} GitOps console features. Create and view applications, such as _ApplicationSet_, and _Argo CD_ types. An `ApplicationSet` represents Argo applications that are generated from the controller. 

- You click *Launch resource in Search* to search for related resources.

- Use _Search_ to find application resources by the component `kind` for each resource. 

*Important:* Available actions are based on your assigned role. Learn about access requirements from the link:../secure_clusters/rbac.adoc#role-based-access-control[Role-based access control] documentation.

.Prerequisites

See the following prerequisites and requirements to access the *Argo server* drop-down menu in the console and create an `ApplicationSet` resource:

- Create an Argo CD `ApplicationSet` resource. Click the *Automatically sync when cluster state changes* option in the *Sync policy* step.
    
- You need GitOps cluster resources and the GitOps operator installed to create an `ApplicationSet`.

.Additional resources

* xref:../gitops/gitops_query_argo_apps.adoc#querying-argo-apps[Querying Argo CD applications]
