[#gitops-register]
= Registering managed clusters to OpenShift GitOps operator

To configure GitOps with the Push model, you can register a set of one or more {product-title} managed clusters to an instance of {ocp} GitOps operator. After registering, you can deploy applications to those clusters. Set up a continuous GitOps environment to automate application consistency across clusters in development, staging, and production environments.

[#prerequisites-argo]
== Prerequisites 

. You need to install the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/cicd/gitops[Red Hat OpenShift GitOps operator] on your {product-title}.

. Import one or more managed clusters.

[#register-gitops]
== Registering managed clusters to GitOps

Complete the following steps to register managed clusters to GitOps:

. Create managed cluster sets and add managed clusters to those managed cluster sets. See the example for managed cluster sets in the link:https://github.com/stolostron/multicloud-integrations/blob/main/examples/openshift-gitops/managedclusterset.yaml[`multicloud-integrations managedclusterset`].

+
See the link:../clusters/cluster_lifecycle/create_clusterset.adoc#creating-a-managedclusterset[Creating a _ManagedClusterSet_] documentation for more information.

. Create a managed cluster set binding to the namespace where Red Hat OpenShift GitOps is deployed. For an example of binding the managed cluster to the `openshift-gitops` namespace, see the link:https://github.com/stolostron/multicloud-integrations/blob/main/examples/managedclustersetbinding.yaml[`multicloud-integrations`] managed clusterset binding example. In the _Additional resources_ section, see _Creating a ManagedClusterSetBinding resource_ for more general information about creating a `ManagedClusterSetBinding`. See link:../clusters/cluster_lifecycle/placement_filter.adoc[Filtering ManagedClusters from ManagedClusterSets] for placement information. 

. In the namespace that is used in managed cluster set binding, create a `Placement` custom resource to select a set of managed clusters to register to an {ocp-short} GitOps operator instance. Use the `multicloud-integration` placement example as a template. See _Using ManagedClusterSets with Placement_ for placement information. 
+
*Notes:* 
+
- Only {ocp-short} clusters are registered to an {ocp} GitOps operator instance, not other Kubernetes clusters.
- In some unstable network scenarios, the managed clusters might be temporarily placed in `unavailable` or `unreachable` state. See _Configuring placement tolerations for {product-title-short} and OpenShift GitOps_ for more details.

. Create a `GitOpsCluster` custom resource to register the set of managed clusters from the placement decision to the specified instance of OpenShift GitOps. This enables the OpenShift GitOps instance to deploy applications to any of those {product-title-short} managed clusters. Use the `_multicloud-integrations_` GitOps cluster example.
+
*Note:* The referenced `Placement` resource must be in the same namespace as the `GitOpsCluster` resource. See the following example:
+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-cluster-sample
  namespace: dev
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters <1>
----
<1> The `placementRef.name` value is `all-openshift-clusters`, and is specified as target clusters for the GitOps instance that is installed in `argoNamespace: openshift-gitops`. The `argoServer.cluster` specification requires the `local-cluster` value.

. Save your changes. You can now follow the GitOps workflow to manage your applications.

[#secret-gitops]
== GitOps token

When you integrate with the GitOps operator for every managed cluster that is bound to the GitOps namespace through the placement and `ManagedClusterSetBinding` custom resources, a secret with a token to access the `ManagedCluster` is created in the namespace. This is required for the GitOps controller to sync resources to the managed cluster. When a user is given administrator access to a GitOps namespace to perform application lifecycle operations, the user also gains access to this secret and `admin` level to the managed cluster. 

If this is not desired, instead of binding the user to the namespace-scoped `admin` role, use a more restrictive custom role with permissions required to work with application resources that can be created and used to bound the user. See the following `ClusterRole` example:


[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-set-admin
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets
  verbs:
  - get
  - list
  - watch
  - update
  - delete
  - deletecollection
  - patch
----

[#additional-resources-gitops]
== Additional resources
//OF | fix first link | Aug 28 23
- Refer to xref:../applications/gitops_config.adoc#tolerations-config[Configuring placement tolerations for {product-title-short} and OpenShift GitOps] for more details.

- See the link:https://github.com/open-cluster-management/multicloud-integrations/blob/main/examples/managedclusterset.yaml[`multicloud-integrations` managed cluster set] example.

- Refer to link:../clusters/cluster_lifecycle/create_clusterset.adoc#creating-a-managedclusterset[Creating a _ManagedClusterSet_] 

- See the link:https://github.com/stolostron/multicloud-integrations/blob/main/examples/placement.yaml[`multicloud-integration` placement] example.

- See link:../clusters/cluster_lifecycle/placement_overview.adoc[Placement overview] for placement information.

- See the link:https://github.com/stolostron/multicloud-integrations/blob/main/examples/gitopscluster.yaml[`multicloud-integrations` GitOps cluster] example.

- See the link:https://github.com/stolostron/multicloud-integrations/blob/main/examples/managedclustersetbinding.yaml[`multicloud-integrations` managed cluster set binding] example.

- See link:../clusters/cluster_lifecycle/create_clustersetbinding.adoc#creating-a-managedclustersetbinding[Creating a _ManagedClusterSetBinding_ resource] documentation for more information.

- See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/cicd/index#understanding-openshift-gitops[About GitOps] to learn more.
