:_mod-docs-content-type: PROCEDURE

[#skip-gitops-addon]
= Skipping the {gitops-short} add-on enforcement

[role="_abstract"]
The {gitops-short} add-on enforces certain resources on the managed clusters to maintain consistency. You can skip enforcement for specific resources by adding the `gitops-addon.open-cluster-management.io/skip` annotation to those specific resources on the managed cluster. Skipping enforcements helps you when you need to customize the `ArgoCD` custom resource or other {gitops-short} components that the add-on manages.

When a resource on the managed cluster has the skip annotation, the {gitops-short} add-on does not update or manage that resource. The add-on checks for this annotation before applying any changes, allowing you to maintain custom configurations that are different from the default settings for the add-on.

When using the skip annotation, ensure that your custom configurations are compatible with the {gitops-short} add-on requirements. Skipping enforcement means the {gitops-short} add-on does not manage or reconcile these resources, so you are responsible for maintaining their consistency and correctness.

*Required access:* Cluster administrator

.Prerequisites

- Are there any prereqs?

.Procedure

Customize the `ArgoCD` custom resource to adjust resource limits, configure specific settings, or enable additional features. Skip the {gitops-short} add-on enforcement by completing the following steps:

. To skip enforcement for a resource, add the following annotation to the `ArgoCD` custom resource on the managed cluster:

+
[source,yaml]
----
metadata:
  Annotations:
    gitops-addon.open-cluster-management.io/skip: "true"
----
+
*Note:* For managing skip annotations across many managed clusters at scale, use the {acm-short} `Policy` to apply the annotation across the fleet.

. Edit the `ArgoCD` custom resource on the managed cluster. Run the following command:

+
[source,bash]
----
oc edit argocd openshift-gitops -n openshift-gitops
----

. Add the `gitops-addon.open-cluster-management.io/skip` annotation and set to `true` to skip enforcement on the managed cluster. See the following YAML file:

+
[source,yaml]
----
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
  annotations:
    gitops-addon.open-cluster-management.io/skip: "true"
----

. Apply the YAML sample by running the following command:  

+
[source,bash]
----
oc apply -f argocd-example.yaml 
----

. *Optional*: Override the existing configuration values that the `GitOpsCluster` maintains in the `AddOnDeploymentConfig` specification by adding the following YAML sample:

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-override-config
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    overrideExistingConfigs: true
    gitOpsImage: "registry.redhat.io/openshift-gitops-1/argocd@sha256:..."
----

. Apply the YAML sample by running the following command 

+
[source,bash]
----
oc apply -f gitopscluster-example.yaml  
----

.Additional resources 

If you want to completely uninstall the {gitops-short} add-on, see xref:../gitops/gitops_uninstall_addon.adoc#uninstall-gitops-addon[Uninstalling the {gitops-short} add-on].
