:_mod-docs-content-type: PROCEDURE

[#gitops-policies]
= Managing policy definitions with {gitops}

*Required access:* Cluster administrator

With the `ArgoCD` resource, you can use {gitops} to manage policy definitions by giving {gitops-short} access to create policies on the hub cluster. Complete the following procedure to give {gitops-short} access to create policies on the hub cluster.

.Prerequisites

- You must log in to your hub cluster.

.Procedure

.Create a `ClusterRole` with access to create, read, update, and delete policies and placements. Use the following sample content:

+
[source,yaml]
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-policy-admin
rules:
  - verbs: [get, list, watch, create, update, patch, delete]
    apiGroups: [policy.open-cluster-management.io]
    resources: [policies, configurationpolicies, certificatepolicies, operatorpolicies, policysets, placementbindings]
  - verbs: [get, list, watch, create, update, patch, delete]
    apiGroups: [cluster.open-cluster-management.io]
    resources: [placements, placements/status, placementdecisions, placementdecisions/status]
----

. Create a `ClusterRoleBinding` with the following sample content:

+
[source,yaml]
----
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-policy-admin
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-policy-admin
----
+
*Notes:*
+
* Rhe `argocd.argoproj.io/compare-options: IgnoreExtraneous` annotation applies to replicated policies automatically.
* To hide replicated policies from Argo CD, set `spec.copyPolicyMetadata` to `false` on the policy definition.

. Configure the Init Container to copy the Policy Generator binary. Your `ArgoCD` resource might resemble the following example. Replace `<version>` with {product-version}:

[source,yaml]
----
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  kustomizeBuildOptions: --enable-alpha-plugins
  repo:
    env:
    - name: KUSTOMIZE_PLUGIN_HOME
      value: /etc/kustomize/plugin
    initContainers:
    - args: ["-c", "cp /policy-generator/PolicyGenerator-not-fips-compliant /policy-generator-tmp/PolicyGenerator"]
      command: ["/bin/bash"]
      image: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:v<version>
      name: policy-generator-install
      volumeMounts:
      - mountPath: /policy-generator-tmp
        name: policy-generator
    volumeMounts:
    - mountPath: /etc/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator
      name: policy-generator
    volumes:
    - emptyDir: {}
      name: policy-generator
----

. Configure policy health checks in {gitops-short}. Download and apply the health checks by running the following command:

+
[source,bash]
----
wget https://raw.githubusercontent.com/open-cluster-management-io/policy-collection/main/stable/CM-Configuration-Management/argocd-policy-healthchecks.yaml
----

. Apply the policy in the console navigating to *Governance* > *Create policy*.
