[#manage-gitops-argocd-appset]
= Managing the Argo CD _ApplicationSet_ resource in any namespace for Argo CD pull model (Technology Preview)  

With the Argo CD pull model, you can create `ApplicationSet` resources in any namespace on your hub clusters.

To fully manage your Argo CD `ApplicationSet` resources, complete the following sections:

*Required access:* Cluster administrator

.Prerequisites

* xref:../gitops/gitops_registering.adoc#gitops-register[Registering managed clusters to {gitops} operator]

== Enabling the _ApplicationSet_ resource in any namespace on the hub cluster 

To enable the Argo CD `ApplicationSet` resource in any namespace on your hub cluster, complete the following steps: 

. From your command-line interface, clone the GitHub repository by running the following command:

+
[source,bash]
----
git clone https://github.com/stolostron/multicloud-integrations
----

. Go to the GitHub repository that you cloned by running the following command: 

+
[source,bash]
----
cd multicloud-integrations/deploy/appset-any-namespace
----

. Enable the `ApplicationSet` resource in any namespace by running the following command: 

+
[source,bash]
----
 ./setup-appset-any-namespace.sh --namespace openshift-gitops --argocd-name openshift-gitops 
----

. Verify that the {gitops-short} instance restarted and is running on your hub cluster. Run the following command on your hub cluster: 

+
[source,bash]
----
oc get pods -n openshift-gitops 
----

== Enabling the _Application_ resource in any namespace on the managed clusters 

The {acm-short} {gitops-short} add-on launches a {gitops-short} instance that you can use to enable the `Application` resource in any namespace on your managed cluster. To enable the Argo CD `Application` resource in any namespace on the managed clusters, complete the following steps:

. Create a global `ManagedClusterSetBinding` resource by adding the following YAML file sample: 

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace: openshift-gitops
spec:
  clusterSet: global
----

. Apply the YAML file sample by running the following command: 

+
[source,bash]
----
oc apply -f managedclustersetbinding-example.yaml
----

. Create a `Placement` custom resource for selecting the managed clusters where the (gitops-short) add-on gets enabled. Add the following YAML file sample:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: all-openshift-clusters
  namespace: openshift-gitops
spec:
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
----

. Apply the YAML file sample by running the following command: 

+
[source,bash]
----
oc apply -f placement-example.yaml
----

. Create the `GitOpsCluster` resource and add the `gitopsAddon` specification. Your YAML file might resemble the following sample: 

+
[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-importer
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: notused
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    overrideExistingConfigs: true
    reconcileScope: All-Namespaces
----

. Apply the YAML file sample by running the following command: 

+
[source,bash]
----
oc apply -f gitopscluster-example.yaml
----

. Verify that the {gitops-short} instance restarted and is running on your managed clusters by running the following command on your managed clusters: 

+
[source,bash]
----
oc get pods -n openshift-gitops 
----

== Deploying the _ApplicationSet_ resource for standard configurations

You can create your Argo CD `ApplicationSet` resource in any custom namespace on your hub cluster. Deploy your Argo CD `ApplicationSet` resource through standard or advanced configurations. 

If you have limited support for role-based access control (RBAC), then you might want to deploy the `ApplicationSet` for standard configurations. 

For simple RBAC management, you can deploy the `ApplicationSet` for standard configurations, giving you the following benefits: 

* No namespaces specified in the GitHub repository resources.
* The destination of the workload namespace is specified in the `Application` template. 
* The `ApplicationSet` resource uses the default `AppProject` resource.

To deploy the `ApplicationSet` resource for standard configurations, complete the following steps: 

. In the `openshift-gitops` namespace, create a `Placement` resource.  
. Create the `ApplicationSet` resource in the `appset-2` namespace with the default `AppProject` by adding the following YAML sample:  

+
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  annotations:
  name: appset-2
----

. Apply the YAML sample by running the following command: 

+
[source,bashl]
----
oc apply -f namespace-example.yaml
----

. Create the `ApplicationSet` resource in the `appset-2` namespace with the default `AppProject` by adding the following YAML sample:  

+
[source,yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloworld
  namespace: appset-2                                                              
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: all-openshift-clusters
      requeueAfterSeconds: 30
  template:
    metadata:
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
      name: '{{name}}-helloworld'
    spec:
      destination:
        namespace: helloworld                                                          
        server: https://kubernetes.default.svc
      project: default                                                                         
      source:
        path: helloworld                                                                                             
        repoURL: https://github.com/stolostron/application-samples.git                   
        targetRevision: HEAD
      syncPolicy:
        automated: {}
----

. Apply the YAML sample by running the following command: 

+
[source,bashl
----
oc apply -f applicationset-example.yaml
----

* The `ApplicationSet` resource gets created in the `appset-2` namespace on your hub cluster.
* The `Application` resources get deployed to the `appset-2` namespace on your managed clusters.
* The `Application` resource deploys its workloads to the `Helloworld` namespace on your managed clusters.
* The default Argo CD `AppProject` configuration gets applied
* All the `Application` resources defined in the specified path of the GitHub repository are not namespace specific. 

== Deploying the _ApplicationSet_ resource for advanced configurations

If you have support for role-based access control (RBAC), then you have the option to deploy the `ApplicationSet` resource for advanced configurations.

You can deploy the `ApplicationSet` resource for advanced configurations with more RBAC management, giving you the following benefits:

* The `Application` resource workload namespaces specified in the GitHub repository resources. 
* The destination of the workload namespace that is specified in the `ApplicationSet` resource matches the GitHub repository.
* The `ApplicationSet` resource uses the custom Argo CD `AppProject` for RBAC control.

To deploy the `ApplicationSet` resource for advanced configurations, complete the following steps:

. In the `openshift-gitops` namespace, create a `Placement` resource. 
. Create the `ApplicationSet` resource in the `bgdk` namespace with the custom `bgdk` `AppProject` by adding the following YAML sample:  

+
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  annotations:
  name: bgdk
----

. Apply the YAML sample by running the following command: 

+
[source,bashl]
----
oc apply -f namespace-example.yaml
----

. Set the bgdk `AppProject` configuration in the {gitops-short} namespace by adding the following YAML sample:  

+
[source,yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bgdk                                                                               
  namespace: openshift-gitops
spec:
  sourceNamespaces:
  - bgdk
  sourceRepos:
  - https://github.com/redhat-developer-demos/openshift-gitops-examples.git
  destinations:
  - namespace: bgdk
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
----
* `sourceNamespaces` is the namespace where the `Application` itself  gets created.
* `sourceRepos` is the repository that the `Application` template uses.
* `destinations` is  the namespace  where the `Application` deploys its workloads.
* `clusterResourceWhitelist` is a cluster scoped resource list that the `Application` is allowed to deploy. In this scenario, this namespace kind is mandatory because the `Application` must create a new namespace.


. Apply the YAML sample by running the following command: 

+
[source,bashl]
----
oc apply -f appproject-example.yaml
----

. Apply the customized Argo CD `AppProject` configuration to the `ApplicationSet` resource.
by adding the following YAML sample:  

+
[source,yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgdk-2
  namespace: bgdk
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: all-openshift-clusters
      requeueAfterSeconds: 30
  template:
    metadata:
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
      name: '{{name}}-bgdk'
    spec:
      destination:
        namespace: bgdk
        server: https://kubernetes.default.svc
      project: bgdk                                                   
      source:
        path: apps/bgd/overlays/bgdk
        repoURL: https://github.com/redhat-developer-demos/openshift-gitops-examples.git
        targetRevision: HEAD
      syncPolicy:
        automated: {}
----

. Apply the YAML sample by running the following command: 

+
[source,bashl]
----
oc apply -f applicationset-example.yaml
----

== Additional resources 

To learn more about the `ArgoCD` `ApplicationSet`, see the following resources: 

* link:https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/[ApplicationSet in any namespace]
* link:https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/[Applications in any namespace] 
