:_mod-docs-content-type: PROCEDURE

[#gitops-push-service-account]
= Creating a customized service account for Argo CD Push model

[role="_abstract"]
Create a customized service account when you need a limited set of permissions for the Argo CD Push model on managed clusters.

*Required access:* Cluster administrator

*Note:* This capability is for the Push model only.

Create a service account on a managed cluster by creating a `ManagedServiceAccount` resource on the hub cluster. By using a different service account, you can control the permissions granted instead of using the default `application-manager` service account.

Update the `GitOpsCluster` resource to use the managed service account by adding the `managedServiceAccountRef` property:

[source,yaml]
----
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-importer
  namespace: openshift-gitops
spec:
  managedServiceAccountRef: <managed-sa-sample>
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: gitops-placement
    namespace: openshift-gitops
----

Verify that the new Argo CD cluster secret is created by running the following command:

[source,bash]
----
oc get secrets -n openshift-gitops <managed-cluster>-<managed-sa-sample>-cluster-secret
----
