:_mod-docs-content-type: CONCEPT

[#gitops-push-pull]
= Deploying Argo CD with Push and Pull model

[role="_abstract"]
Using a _Push model_, The Argo CD server on the hub cluster deploys the application resources on the managed clusters. For the _Pull model_, the application resources are propagated by the _Propagation controller_ to the managed clusters by using `manifestWork`.

For both models, the same `ApplicationSet` CRD is used to deploy the application to the managed cluster.

If your `openshift-gitops-ArgoCD-application-controller` service account is _not_ assigned as a cluster administrator, the {gitops} application controller might not deploy resources. The application status might send an error similar to the following error:

----
cannot create resource "services" in API group "" in the namespace
"mortgage",deployments.apps is forbidden: User
"system:serviceaccount:openshift-gitops:openshift-gitops-Argo CD-application-controller"
----

You must declare all application destination namespaces in the repository for the application and include the `managed-by` label in the namespaces. Refer to _Additional resources_ to learn how to declare a namespace.

See the following requirements to use the Argo CD _Pull_ model:

- The {gitops} operator must be installed on the hub cluster and the target managed clusters in the `openshift-gitops` namespace.

- The required hub cluster {ocp-short} {gitops-short} operator must be version 1.9.0 or later.

- The version of the {gitops} Operator on the hub cluster must be equal to or more recent than the version of the operator on the managed clusters.

- You need the _ApplicationSet controller_ to propagate the Argo CD application template for a managed cluster.

- Every managed cluster must have a cluster secret in the Argo CD server namespace on the hub cluster, which is required by the ArgoCD application set controller to propagate the Argo CD application template for a managed cluster.

+
To create the cluster secret, create a `gitOpsCluster` resource that contains a reference to a `placement` resource. The `placement` resource selects all the managed clusters that need to support the Pull model. When the {gitops-short} cluster controller reconciles, it creates the cluster secrets for the managed clusters in the Argo CD server namespace.

.Additional resources

* link:https://docs.redhat.com/en/documentation/red_hat_openshift_gitops/1.12/html/declarative_cluster_configuration/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations[Configuring an OpenShift cluster by deploying an application with cluster configurations]
* link:https://docs.redhat.com/en/documentation/red_hat_openshift_gitops/1.12/html/argo_cd_instance/setting-up-argocd-instance[Setting up an Argo CD instance]
* xref:../gitops/gitops_arch_push_pull.adoc#arch-push-pull[Architecture]
* xref:../gitops/gitops_create_appset_crd.adoc#crd-pull-model[Creating the _ApplicationSet_ custom resource]
* xref:../gitops/gitops_multicluster_appset_report.adoc#status-report[_MulticlusterApplicationSetReport_]