[#discovery-console]
= Configure Discovery with the console

Configure Discovery in the console to find your clusters. To configure the Discovery feature on your cluster, you must enable a `DiscoveryConfig` resource to connect to the {ocm} to find clusters that are a part of your organization. 

- You can create multiple `DiscoveryConfig` resources with separate credentials. 

- You can then import clusters that appear in the _Discovered clusters_ tab of the console. Use the product console to enable Discovery. 

- Discovered cluster resources reflect the filters that are specified in the `DiscoveryConfig` file, displaying only the resources that match the criteria that you listed in the cluster. 

//*Required access*:we actually need the role here

You need access to the namespace where the credential was created.

.Prerequisites

* You need a credential. See xref:../credentials/credential_ocm.adoc#creating-a-credential-for-openshift-cluster-manager[Creating a credential for {ocm}] to connect to {ocm}.

* You need access to the namespaces that were used to configure Discovery.

[#import-discovered]
== Import discovered clusters from the console

To manually import other infrastructure provider discovered clusters, complete the following steps:

. Go to the existing _Clusters_ page and click the *Discovered clusters* tab.
. From the _Discovered clusters_ table, find the cluster that you want to import. 
. From the options menu, choose *Import cluster*. 
. For discovered clusters, you can import manually using the documentation, or you can choose to import clusters automatically.
. To import automatically with your credentials or `kubeconfig` file, copy and paste the content.
. Click *Import*.
//please review this--I cannot test this in the console bc I don't have discovered clusters.

[#discovery-view]
== View discovered clusters 

After you set up your credentials and discover your clusters for import, you can view them in the console. While most filters are configured through both the terminal and the console, the `region` filter is currently available in the terminal only.

. Click *Clusters* > *Discovered clusters*.
//Infrastructor>Clusters?
. View the populated table with the following information:
    - _Name_ is the display name that is designated in {ocm}. If the cluster does not have a display name, a generated name based on the cluster console URL is displayed. If the console URL is missing or was modified manually in {ocm}, the cluster external ID is displayed.
    - _Namespace_ is the namespace where you created the credential and discovered clusters.
    - _Type_ is the discovered cluster Red Hat OpenShift type.
    - _Distribution version_ is the discovered cluster Red Hat OpenShift version.
    - _Infrastructure provider_ is the cloud provider of the discovered cluster. 
    - _Last active_ is the last time the discovered cluster was active.
    - _Created_ when the discovered cluster was created.
    - _Discovered_ when the discovered cluster was discovered.
    - _Cluster types_ is the platform type of the cluster, such as {ocp-short} or {rosa}.
    - _Infrastructure providers_ filters by where the cluster is running, such as Amazon Web Services (AWS) or Microsoft Azure.
. You can search for any information in the table, as well. For example, to show only _Discovered clusters_ in a particular namespace, search for that namespace.
. You can now click *Import cluster* to create managed clusters.
//please review this. I think this is old. 