[#import-discovered-auto-rosa]
= Import Discovered clusters automatically for ROSA clusters

Automatically import ROSA clsuters into your {product-title} hub cluster with the `discovery-operator`.

//== Prerequisites
//Are there any prereqs?
//* You nmust have access to the namespaces that were used to configure Discovery.

To automatically import the `DiscoveredCluster` resource, you must modify the resource and set the `importAsManagedCluster` field to `true`. 

. Log in to your hub cluster.
. Go to the `DiscoveredCluster` resource and set `importAsManagedCluster` to `true`. By setting the field to `true`, the `discovery-operator` imports the `DiscoveredCluster` resource, and creates a `ManagedCluster`, `KlusterletAddOnConfig`, (only if {product-title-short} is installed) and automatically imports `Secret` resources for your cluster.
+
Your `DiscoveredCluster` resource might resemble the following instance:

+
[source,yaml]
----
apiVersion: discovery.open-cluster-management.io/v1
kind: DiscoveredCluster
metadata:
  name: 28c17977-fc73-4050-b5cc-a5aa2d1d6892
  namespace: discovery
spec:
  openshiftVersion: 4.14.26
  isManagedCluster: false
  cloudProvider: aws   
  name: 28c17977-fc73-4050-b5cc-a5aa2d1d6892   
  displayName: rosa-dc
  status: Active
  importAsManagedCluster: true
  type: ROSA
----

. To verify that the `ManagedCluster` resource is imported, see...
//is there a message that appears for the user? Would the managed cluster resource appear somewhere else in the console?

[#import-rosa-policy]
== Importing ROSA cluster by using a policy
//Brandi is working on this in issue ACM-11278:https://issues.redhat.com/browse/ACM-11278

//Seems like this section needs to be removed from my PR. 
If you have {product-title-short} installed, you can automatically import a group of ROSA clusters by using a policy. Complete the following steps:

. Log in to your hub cluster. 
. From the navigation menu, select *Governance*. 
. Create a policy with the name `policy-rosa-autoimport` and deploy the policy. For an example of the policy, see link:https://github.com/stolostron/policy-collection/blob/main/community/CM-Configuration-Management/policy-rosa-autoimport.yaml[`policy-rosa-autoimport.yaml`]. 
//1. this is linked to the community folder and we avoid pointing to unstable examples
//2. we need to replace this link with an link to open-clsuter-management repo

