:_mod-docs-content-type: PROCEDURE

[#discovery-import-cli]
= Importing discovered {rosa} and hosted control plane clusters by using the CLI

[role="_abstract"]
Automatically import supported clusters into your hub cluster with the `Discovery-Operator` for faster cluster management, without manually importing individual clusters. The following procedure is an example of how to import your discovered {rosa} and hosted control planes clusters automatically by using the `Discovery-Operator` from the command-line interface.

*Required access:* Cluster administrator

.Prerequisites

* Discovery is enabled by default. If you changed default settings, you need to enable Discovery.
* You must set up the {rosa} command-line interface. See link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/4/html/rosa_cli/rosa-get-started-cli#rosa-get-started-cli[Getting started with the {rosa} CLI] documentation.

*Important:* For other Kubernetes providers, you must import these infrastructure provider `DiscoveredCluster` resources manually. Directly apply Kubernetes configurations to the other types of `DiscoveredCluster` resources. If you enable the `importAsManagedCluster` field from the `DiscoveredCluster` resource, it is not imported due to the Discovery webhook.

.Procedure

. To automatically import the `DiscoveredCluster` resource from the command-line interface. Set the `importAsManagedCluster` paramater to `true` by using the following command after you log in. Replace `<name>` and `<namespace>` with your name and namespace:

+
[source,bash]
----
oc patch discoveredcluster <name> -n <namespace> --type='json' -p='[{"op": "replace", "path": "/spec/importAsManagedCluster", "value": true}]'
----

. Run the following command to verify that the cluster was imported as a managed cluster:

+
[source,bash]
----
oc get managedcluster <name>
----

. To get a description of your {rosa} cluster ID, run the following command from the {rosa} command-line interface:

+
[source,bash]
----
rosa describe cluster --cluster=<cluster-name> | grep -o ^ID:.*
----
