[#policy-controllers]
= Policy controllers

Policy controllers monitor and report whether your cluster is compliant with a policy. Use the {product-title} policy framework by using the out of the box policy templates to apply predefined policy controllers, and policies. The policy controllers are Kubernetes custom resource definition (CRD) instance.
For more information about CRDs, see https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions]. Policy controllers remediate policy violations to make the cluster status be compliant.

You can create custom policies and policy controllers with the product policy framework. See xref:../risk_compliance/create_policy_ctrl.adoc#creating-a-custom-policy-controller[Creating a custom policy controller] for more information.

**Important**: Only the configuration policy controller supports the `enforce` feature. You must manually remediate policies, where the policy controller does not support the `enforce` feature.

View the following topics to learn more about the following {product-title} policy controllers:

* xref:../risk_compliance/config_policy_ctrl.adoc#kubernetes-configuration-policy-controller[Kubernetes configuration policy controller]
* xref:../risk_compliance/cert_policy_ctrl.adoc#certificate-policy-controller[Certificate policy controller]
* xref:../risk_compliance/iam_policy_ctrl.adoc#iam-policy-controller[IAM policy controller]

Refer to xref:../risk_compliance/grc_intro.adoc#governance[Governance] for more topics about managing your policies.
