:_mod-docs-content-type: PROCEDURE

[#update-ocp-cluster-curator]
= Updating {ocp-short} clusters with not-recommended versions by using the ClusterCurator

[role="_abstract"]
Upgrade your {ocp-short} cluster to a version with known issues when you need to test new features quickly.

*Required access:* Cluster administrator

[IMPORTANT]
====
Upgrading to an {ocp-short} cluster version with known issues can reduce performance and compatibility.
====

.Procedure

. Create a file named `clustercurator.yaml`.
. Add the following annotation to the file:
+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  annotations:
    cluster.open-cluster-management.io/upgrade-allow-not-recommended-versions: 'true'
  name: <name> <1>
  namespace: <namespace> <2>
spec:
  desiredCuration: upgrade
  upgrade:
    desiredUpdate: <4.x.x> <3>
    monitorTimeout: 120
----
<1> Add your cluster name.
<2> Add your cluster namespace.
<3> Add the {ocp-short} cluster version with known issues that you want to upgrade to.
. Apply the file. Run the following command:
+
[source,bash]
----
oc apply -f clustercurator.yaml
----

The `ClusterCurator` checks the `desiredUpdate` image digest version at startup in the conditional updates list. If the image digest is not found, the `ClusterCurator` uses the image tag instead.
