[#errata-acm]
= Fixed issues for {acm-short}

By default, fixed issues for _errata_ releases are automatically applied when released. The details are published here when the release is available. If no release notes are listed, the product does not have an errata release at this time.

*Important:* For reference, Jira links and Jira numbers might be added to the content and used internally. Links that require access might not be available for the user. Learn about the types of link:https://access.redhat.com/security/updates/advisory[errata releases] from Red Hat.

See link:../install/upgrade_hub.adoc#upgrading-by-using-the-operator[Upgrading by using the operator] for more information about upgrades.

*Important:* Cluster lifecycle components and features are within the {mce-short}, which is a software operator that enhances cluster fleet management. Release notes for {mce-short}-specific features are found in at link:../clusters/release_notes/mce_release_notes.adoc#mce-release-notes[Release notes for Cluster lifecycle with {mce-short}].

== Errata 2.15.1

* Delivers updates to one or more product container images.

* Fixes a problem where `ConfigurationPolicies` that check status incorrectly report that the policy is `Compliant` when the status field is missing. With this fix, `ConfigurationPolicies` properly report as `NonCompliant` until that status field matches what is defined in the policy.
link:https://issues.redhat.com/browse/ACM-28224[ACM-28224]

* Corrects the problem where the cluster monitoring config map contains duplicated `AlertmanagerConfigs` due to the change in the Alertmanager secret names in {acm-short} 2.15.
link:https://issues.redhat.com/browse/ACM-27841[ACM-27841]

* Fixes a blocker that occurred during cluster deprovisioning, causing the `BareMetalHost` deletion to hang due to a Foreground deletion policy deadlock with the `PreprovisioningImage`. 
https://issues.redhat.com/browse/ACM-27747[ACM-27747]

* Resolves an issue with rebooting baremetal hosts during the import process, which led to the hosts being reprovisioned, causing the `ClusterInstance` status to report `Provisioning in progress`.`ClusterInstance` status now correctly reflects a completed state for imported clusters that are already provisioned.
link:https://issues.redhat.com/browse/ACM-27639[ACM-27639]

* Fixes an issue where adding the `observability=disabled` label that failed to remove all observability add-on resources for a target managed cluster. With this fix, all observability add-on resources are removed when the label is added.
https://issues.redhat.com/browse/ACM-27632[ACM-27632]

* Optimizes the watcher controller to fix overconsumption of resources, specifically memory and CPU, which was causing scalability issues.The fix implements a `ReferenceCache` that maps configuration resources to the `ManifestWorks` that reference them.
link:https://issues.redhat.com/browse/ACM-27304[ACM-27304]

* Fixes an issue where the hub Alertmanager secrets in the `openshift-monitoring` namespace became too long, and therefore causing statefulset not to start. The Alertmanager secrets are now appended by a partial cluster ID instead of the cluster name.
link:https://issues.redhat.com/browse/ACM-27722[ACM-27722]