
[#deprecations-removals-acm]
= Deprecations and removals for {acm-short}

Learn when parts of the product are deprecated or removed from {acm}. Consider the alternative actions in the _Recommended action_ and details, which display in the tables for the current release and for two prior releases.

*Deprecated:* {acm-short} 2.7 and earlier versions are no longer supported. The documentation might remain available, but without any Errata or other updates.

*Best practice:* Upgrade to the most recent version.

*Important:* Cluster lifecycle components and features are within the {mce-short}, which is a software operator that enhances cluster fleet management. Release notes for {mce-short}-specific features are found in at link:../clusters/release_notes/mce_release_notes.adoc#mce-release-notes[Release notes for Cluster lifecycle with {mce-short}].

[#api-deprecations-info]
== API deprecations and removals

{acm-short} follows the Kubernetes deprecation guidelines for APIs. See the link:https://kubernetes.io/docs/reference/using-api/deprecation-policy/[Kubernetes Deprecation Policy] for more details about that policy. {acm-short} APIs are only deprecated or removed outside of the following timelines:
  
  - All `V1` APIs are generally available and supported for 12 months or three releases, whichever is greater. V1 APIs are not removed, but can be deprecated outside of that time limit.
  - All `beta` APIs are generally available for nine months or three releases, whichever is greater. Beta APIs are not removed outside of that time limit.
  - All `alpha` APIs are not required to be supported, but might be listed as deprecated or removed if it benefits users.

//[#api-removals]
//=== API removals

//|===
//| Product or category | Affected item | Version | Recommended action | More details and links

//|===


[#deprecations]
== {acm-short} deprecations

A _deprecated_ component, feature, or service is supported, but no longer recommended for use and might become obsolete in future releases. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
| Product or category | Affected item | Version | Recommended action | More details and links

| _Overview_ page
| {acm} search 
| 2.12
| Enable the _Fleet view_ switch to view the new default _Overview_ page.
| The previous layout of the {acm-short} _Overview_ page is deprecated.
|===

[#removals]
== Removals

A _removed_ item is typically function that was deprecated in previous releases and is no longer available in the product. You must use alternatives for the removed function. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
|Product or category | Affected item | Version | Recommended action | More details and links

| Governance
| IAM policy controller
| 2.11
| None
| 

| Policy compliance history API
| Governance 
| 2.13
| Use the existing policy metrics to see the compliance status changes. You can also view the `config-policy-controller` and `cert-policy-controller` pod logs to get a detailed compliance history for each managed cluster.
| For more information, see link:../governance/policy_ctrl_adv_config.adoc#policy-controller-advanced-config[Policy controller advanced configuration].
|===