:_mod-docs-content-type: PROCEDURE

[#policy-status-repeated-updates]
= Policy status shows repeated updates when enforced

[role="_abstract"]
If a policy is set to `remediationAction: enforce` and is repeatedly updated, the {acm-short} console shows repeated violations with successful updates. Repeated updates produce multiple policy events, which can cause the `governance-policy-framework-addon` pod to run out of memory and crash.

.Procedure

. Disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster if another controller or process is also updating the object with different values.
+
If the values are different, another controller or process might be updating them. Check the `metadata` of the object to help identify why the values are different.

. Disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster if the `objectDefinition` in the `ConfigurationPolicy` does not match because of Kubernetes processing the object when the policy is applied.
+
If the keys are different or missing, Kubernetes might have processed the keys before applying them to the object, such as removing keys containing default or empty values.

+
link:https://issues.redhat.com/browse/ACM-3109[ACM-3109]
