[#errata-acm]
= Fixed issues for {acm-short}

By default, fixed issues for _errata_ releases are automatically applied when released. The details are published here when the release is available. If no release notes are listed, the product does not have an errata release at this time.

*Important:* For reference, Jira links and Jira numbers might be added to the content and used internally. Links that require access might not be available for the user. Learn about the types of link:https://access.redhat.com/security/updates/advisory[errata releases] from Red Hat.

See link:../install/upgrade_hub.adoc#upgrading-by-using-the-operator[Upgrading by using the operator] for more information about upgrades.

*Important:* Cluster lifecycle components and features are within the {mce-short}, which is a software operator that enhances cluster fleet management. Release notes for {mce-short}-specific features are found in at link:../clusters/release_notes/mce_release_notes.adoc#mce-release-notes[Release notes for Cluster lifecycle with {mce-short}].

== Errata 2.9.1

* Delivers updates to one or more product container images.

* Fixes a validation error that occurred during the creation of user accounts with special characters in the email address, which caused failure. You can now use special characters in the email address.
link:https://issues.redhat.com/browse/ACM-22366[ACM-22366]
