[#errata-acm]
= Fixed issues for {acm-short}

By default, fixed issues for _errata_ releases are automatically applied when released. The details are published here when the release is available. If no release notes are listed, the product does not have an errata release at this time.

*Important:* For reference, Jira links and Jira numbers might be added to the content and used internally. Links that require access might not be available for the user. Learn about the types of link:https://access.redhat.com/security/updates/advisory[errata releases] from Red Hat.

See link:../install/upgrade_hub.adoc#upgrading-by-using-the-operator[Upgrading by using the operator] for more information about upgrades.

*Important:* Cluster lifecycle components and features are within the {mce-short}, which is a software operator that enhances cluster fleet management. Release notes for {mce-short}-specific features are found in at link:../clusters/release_notes/mce_release_notes.adoc#mce-release-notes[Release notes for Cluster lifecycle with {mce-short}].

== Errata 2.16.2

* Delivers updates to one or more product container images.

* Fixes a problem with the multicluster observability add-on node exporter pods, which failed to start on managed Kubernetes platforms such as Amazon EKS and Azure Kubernetes Service (AKS) when the `kube-rbac-proxy` container did not bind to port `19100` because the cloud provider already ran a node exporter on that port. The add-on now uses a separate internal listener port for node exporter, which prevents the port conflict.

link:https://issues.redhat.com/browse/ACM-30490[ACM-30490]

== Errata 2.16.1 (Deprecated)

* Delivers updates to one or more product container images.

* Fixes an issue on some S3 vendors that left empty folders existing on object storage after Thanos Compact deletes blocks.

link:https://redhat.atlassian.net/browse/ACM-32930[ACM-32930]