:_mod-docs-content-type: PROCEDURE

[#cluster-local-offline-reimport]
= Local-cluster status offline after reimporting with a different name

[role="_abstract"]
When you accidentally try to reimport the cluster named `local-cluster` as a cluster with a different name, the status for `local-cluster` and for the reimported cluster display `offline`.

To recover from this case, complete the following steps:

.Procedure

. Run the following command on the hub cluster to edit the setting for self-management of the hub cluster temporarily:
+
[source,bash]
----
oc edit mch -n open-cluster-management multiclusterhub
----

. Add the setting `spec.disableSelfManagement=true`.

. Run the following command on the hub cluster to delete and redeploy the local-cluster:
+
[source,bash]
----
oc delete managedcluster local-cluster
----

. Enter the following command to remove the `local-cluster` management setting: 
+
[source,bash]
----
oc edit mch -n open-cluster-management multiclusterhub
----

. Remove `spec.disableSelfManagement=true` that you previously added.

.Additional resources

* link:https://github.com/stolostron/backlog/issues/16977[GH-16977]
