[#errata-acm]
= Fixed issues for {acm-short}

By default, fixed issues for _errata_ releases are automatically applied when released. The details are published here when the release is available. If no release notes are listed, the product does not have an errata release at this time.

*Important:* For reference, Jira links and Jira numbers might be added to the content and used internally. Links that require access might not be available for the user. Learn about the types of link:https://access.redhat.com/security/updates/advisory[errata releases] from Red Hat.

See link:../install/upgrade_hub.adoc#upgrading-by-using-the-operator[Upgrading by using the operator] for more information about upgrades.

*Important:* Cluster lifecycle components and features are within the {mce-short}, which is a software operator that enhances cluster fleet management. Release notes for {mce-short}-specific features are found in at link:../clusters/release_notes/mce_release_notes.adoc#mce-release-notes[Release notes for Cluster lifecycle with {mce-short}].

== Errata 2.15.2

* Delivers updates to one or more product container images.

* Fixes the `TargetDown` alert from the `alertmanager-clientca-metric` config map, which did not update on certificate rotation.
link:https://redhat.atlassian.net/browse/ACM-20743[ACM-20743]

* Fixes a race condition where the observability add-on misidentified {ocp-short} clusters as non-{ocp-short} during provisioning, causing deployment failures. The add-on now waits for clusters to be fully identified, allowing the cluster version to settle before applying configuration.
link:https://redhat.atlassian.net/browse/ACM-27834[ACM-27834]

* Fixes `Image-based installation failures that were caused by the default `ImageClusterInstall` template not including the `AdditionalNTPSources` field from the `ClusterInstance` specification. Without the field, clusters used the NTP servers from the seed image instead of the production NTP servers, causing installation to fail. The template now correctly renders user-specified NTP sources into the `ImageClusterInstall` manifest.
link:https://redhat.atlassian.net/browse/ACM-32930[ACM-32930] 

* Resolves an issue where the hashring in the `observability-thanos-receive-controller` was not updating upon scaling due to missing pod permissions. The `observatorium-deployment` is now updated with the necessary RBAC permissions for the `thanos-receive-controller`, enabling it to access pod status.
link:https://redhat.atlassian.net/browse/ACM-26173[ACM-26173]

== Errata 2.15.1

* Delivers updates to one or more product container images.

* Fixes a problem where `ConfigurationPolicies` that check status incorrectly report that the policy is `Compliant` when the status field is missing. With this fix, `ConfigurationPolicies` properly report as `NonCompliant` until that status field matches what is defined in the policy.
link:https://issues.redhat.com/browse/ACM-28224[ACM-28224]

* Corrects the problem where the cluster monitoring config map contains duplicated `AlertmanagerConfigs` due to the change in the Alertmanager secret names in {acm-short} 2.15.
link:https://issues.redhat.com/browse/ACM-27841[ACM-27841]

* Fixes a blocker that occurred during cluster deprovisioning, causing the `BareMetalHost` deletion to hang due to a foreground deletion policy deadlock with the `PreprovisioningImage`. 
https://issues.redhat.com/browse/ACM-27747[ACM-27747]

* Resolves an issue where `ClusterInstance` status incorrectly reported `Provisioning in progress` for clusters imported after it was previously installed by using the Agent-Based Installer or the Installer-Provisioned Infrastructure. `ClusterInstance` status now correctly reflects a completed state for imported clusters that are already provisioned.
link:https://issues.redhat.com/browse/ACM-27639[ACM-27639]

* Fixes an issue where adding the `observability=disabled` label failed to remove all observability add-on resources for a target managed cluster. With this fix, all observability add-on resources are removed when the label is added.
https://issues.redhat.com/browse/ACM-27632[ACM-27632]

* Optimizes the watcher controller to fix overconsumption of resources, specifically memory and CPU, which was causing scalability issues. The fix optimizes the reconciliation process by implementing a lookup cache, which replaces the previous resource-intensive checks that are used to verify if updated `ConfigMaps` or `Secrets` are used by the `multicluster-observability-addon`.
link:https://issues.redhat.com/browse/ACM-27304[ACM-27304]

* Fixes an issue where the hub Alertmanager secrets in the `openshift-monitoring` namespace became too long, and therefore causing statefulset not to start. The Alertmanager secrets are now appended by a partial cluster ID instead of the cluster name.
link:https://issues.redhat.com/browse/ACM-27722[ACM-27722]
