:_mod-docs-content-type: PROCEDURE

[#search-postgres-crashloopbackoff]
= Search PostgreSQL pod is in CrashLoopBackoff state

[role="_abstract"]
The `search-postgres` pod is in `CrashLoopBackoff` state. If {acm-short} is deployed in a cluster with nodes that have the `hugepages` parameter enabled and the `search-postgres` pod gets scheduled in these nodes, then the pod does not start.

Complete the following steps to increase the memory of the `search-postgres` pod:

.Procedure

. Pause the `search-operator` pod with the following command:
+
[source,bash]
----
oc annotate search search-v2-operator search-pause=true
----

. Update the `search-postgres` deployment with a limit for the `hugepages` parameter. Run the following command to set the `hugepages` parameter to `512Mi`:
+
[source,bash]
----
oc patch deployment search-postgres --type json -p '[{"op": "add", "path": "/spec/template/spec/containers/0/resources/limits/hugepages-2Mi", "value":"512Mi"}]'
----

. Before you verify the memory usage for the pod, make sure your `search-postgres` pod is in the `Running` state. Run the following command:
+
[source,bash]
----
oc get pod <your-postgres-pod-name>  -o jsonpath="Status: {.status.phase}"
----

. Run the following command to verify the memory usage of the `search-postgres` pod:
+
[source,bash]
----
oc get pod <your-postgres-pod-name> -o jsonpath='{.spec.containers[0].resources.limits.hugepages-2Mi}'
----
+
The following value appears: `512Mi`.

+
link:https://issues.redhat.com/browse/ACM-7467[ACM-7467]
