
[#deprecations-removals]
= Deprecations and removals

Learn when parts of the product are deprecated or removed.

*Note:* A _stabilized_ item is not planned for deprecation or removal from a subsequent release of a product, but is no longer updated or developed. 

Consider the alternative actions in the _Recommended action_ and details that are provided in a table only if stabilized functions are listed for the current release.

[#deprecations]
== Deprecations

A _deprecated_ item is supported, but no longer recommended for use and might become obsolete. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
|Product or category | Affected item | Status | Version | Recommended action | More details and links
|===

[#removals]
== Removals

A _removed_ item is typically function that was deprecated in previous releases and is no longer available in the product. You must use alternative features as a replacement for the removed function. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
|Product or category | Affected item | Status | Version | Recommended action | More details and links
|===