
[#deprecations-removals]
= Deprecations and removals

Learn when parts of the product are deprecated or removed from {product-title}. Consider the alternative actions in the _Recommended action_ and details, which display in the tables for the current release and for two prior releases.

[#api-deprecations-info]
== API deprecations and removals

{product-title-short} follows the Kubernetes deprecation guidelines for APIs. See the https://kubernetes.io/docs/reference/using-api/deprecation-policy/[Kubernetes Deprecation Policy] for more details about that policy. 

{product-title-short} APIs are only deprecated or removed outside of the following timelines:
  
  - All `V1` APIs are generally available and supported for 12 months or three releases, whichever is greater. V1 APIs are not removed, but can be deprecated outside of that time limit.
  - All `beta` APIs are generally available for nine months or three releases, whichever is greater. Beta APIs are not removed outside of that time limit.
  - All `alpha` APIs are not required to be supported, but might be listed as deprecated or removed if it benefits users.
  
//[#api-deprecations]
//=== API deprecations

[#deprecations]
== {product-title-short} deprecations

A _deprecated_ component, feature, or service is supported, but no longer recommended for use and might become obsolete in future releases. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
|Product or category | Affected item | Version | Recommended action | More details and links

| Application management
| `HelmRepo` channel specification: usage of `insecureSkipVerify: "true"` is no longer inside the `configMapRef`
| 2.2
| Use `insecureSkipVerify: "true"` in the channel without the `configMapRef`
| See the YAML sample for the change.

|===


[#removals]
== Removals

A _removed_ item is typically function that was deprecated in previous releases and is no longer available in the product. You must use alternatives for the removed function. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
|Product or category | Affected item | Version | Recommended action | More details and links

| Observability Topology
| Topology access from _Observe environments_ removed completely
| 2.2
| None
| Application topology is located in _Application management_ and no longer in the _Observability console_.

| Application management
| Channel type: Namespace, removed completely
| 2.2
| None
| None
|===
