
[#deprecations-removals]
= Deprecations and removals

Learn when parts of the product are deprecated or removed from {product-title}. Consider the alternative actions in the _Recommended action_ and details, which display in the tables for the current release and for two prior releases.

*Important:* The 2.6 and earlier versions of {product-title-short} are _removed_ and no longer supported. Documentation for versions 2.6 and earlier are not updated. The documentation might remain available, but is deprecated without any Errata or other updates available.

*Best practice:* Upgrade to the most recent version of {product-title-short}.

[#api-deprecations-info]
== API deprecations and removals

{product-title-short} follows the Kubernetes deprecation guidelines for APIs. See the link:https://kubernetes.io/docs/reference/using-api/deprecation-policy/[Kubernetes Deprecation Policy] for more details about that policy. {product-title-short} APIs are only deprecated or removed outside of the following timelines:
  
  - All `V1` APIs are generally available and supported for 12 months or three releases, whichever is greater. V1 APIs are not removed, but can be deprecated outside of that time limit.
  - All `beta` APIs are generally available for nine months or three releases, whichever is greater. Beta APIs are not removed outside of that time limit.
  - All `alpha` APIs are not required to be supported, but might be listed as deprecated or removed if it benefits users.

[#api-removals]
=== API removals

|===
| Product or category | Affected item | Version | Recommended action | More details and links

| ManagedClusterSets
| The `v1beta1` API is removed.
| 2.9
| Use `v1beta2` instead.
| ManagedClusterSets.cluster.open-cluster-management.io

| ManagedClusterSetBindings
| The `v1beta1` API is removed.
| 2.9
| Use `v1beta2` instead.
| ManagedClusterSetBindings.cluster.open-cluster-management.io

|===


[#deprecations]
== {product-title-short} deprecations

A _deprecated_ component, feature, or service is supported, but no longer recommended for use and might become obsolete in future releases. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
| Product or category | Affected item | Version | Recommended action | More details and links

| Features supported on {ocp-short} 3.11
| Various components
| 2.9
| None
| link:https://access.redhat.com/support/policy/updates/openshift[Life Cycle Policy]

| Governance
| IAM policy controller
| 2.9
| None
| 

| Governance
| Container security operator 
| {ocp-short} 3.11
| None
| See link:../release_notes/known_issues_governance.adoc#container-security-operator-not-available-ocp[Container security operator is not available in {ocp-short} 3.11]

| Installer
| `ingress.sslCiphers` field in `operator.open-cluster-management.io_multiclusterhubs_crd.yaml`
| 2.9
| None
| See link:../install/adv_config_install.adoc[Advanced Configuration] for configuring install. If you uppgrade your {product-title} version and originally had a `MultiClusterHub` custom resource with the `spec.ingress.sslCiphers` field defined, the field is still recognized, but is deprecated and has no effect.

| Applications and Governance
| `PlacementRule`
| 2.8
| Use `Placement` anywhere that you might use `PlacementRule`.
| While `PlacementRule` is still available, it is not supported and the console displays `Placement` by default.

|===

[#removals]
== Removals

A _removed_ item is typically function that was deprecated in previous releases and is no longer available in the product. You must use alternatives for the removed function. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
|Product or category | Affected item | Version | Recommended action | More details and links

|===

[#iam-policy-controller]
== IAM policy controller 

The Identity and Access Management (IAM) policy controller can be used to receive notifications about IAM policies that are non-compliant. The compliance check is based on the parameters that you configure in the IAM policy. The IAM policy is provided in the `policy-templates` field of the policy on the hub cluster and is propagated to the selected managed clusters by the governance framework. See the xref:../governance/policy_overview.adoc#policy-yaml-structure[Policy YAML structure] documentation for more details on the hub cluster policy.

The IAM policy controller monitors for the desired maximum number of users with a particular cluster role (i.e. `ClusterRole`) in your cluster. The default cluster role to monitor is `cluster-admin`. The IAM policy controller communicates with the local Kubernetes API server.

The IAM policy controller runs on your managed cluster. View the following sections to learn more:

* <<iam-policy-yaml-structure,IAM policy YAML structure>>
* <<iam-policy-yaml-table,IAM policy YAML table>>

[#iam-policy-yaml-structure]
=== IAM policy YAML structure

View the following example of an IAM policy and review the parameters in the YAML table:

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: IamPolicy 
metadata:
  name:
spec:
  clusterRole:
  severity:
  remediationAction: 
  maxClusterRoleBindingUsers:
  ignoreClusterRoleBindings:
----

[#iam-policy-yaml-table]
=== IAM policy YAML table

View the following parameter table for descriptions:

.Parameter table
|===
| Field | Optional or required | Description

| `apiVersion`
| Required
| Set the value to `policy.open-cluster-management.io/v1`.

| `kind`
| Required
| Set the value to `Policy` to indicate the type of policy.

| `metadata.name`
| Required
| The name for identifying the policy resource.

| `spec.clusterRole`
| Optional
| The cluster role (i.e. `ClusterRole`) to monitor. This defaults to `cluster-admin` if not specified.

| `spec.severity`
| Optional
| Informs the user of the severity when the policy is non-compliant. Use the following parameter values: `low`, `medium`, `high`, or `critical`.

| `spec.remediationAction`
| Optional
| Specifies the remediation of your policy.
Enter `inform`. The IAM policy controller only supports the `inform` feature.

| `spec.ignoreClusterRoleBindings`
| Optional
| A list of regular expression (regex) values that indicate which cluster role binding names to ignore. These regular expression values must follow link:https://pkg.go.dev/regexp/syntax[Go regexp syntax]. By default, all cluster role bindings that have a name that starts with `system:` are ignored. It is recommended to set this to a stricter value. To not ignore any cluster role binding names, set the list to a single value of `.^` or some other regular expression that never matches.

| `spec.maxClusterRoleBindingUsers`
| Required
| Maximum number of IAM role bindings that are available before a policy is considered non-compliant.
|===