
[#deprecations-removals]
= Deprecations and removals

Learn when parts of the product are deprecated or removed.

*Note:* A _stabilized_ item is not deprecated or removed from a release of a product, but is no longer updated or developed. For instance, if an API is replaced with a new version in a release, but no longer updated, it can be listed in this topic as _stabilized_. The API is still available for one to three more releases before deprecated or removed.

Consider the alternative actions in the _Recommended action_ and details that are provided in a table only if stabilized functions are listed for the current release.

[#deprecations]
== Deprecations

A _deprecated_ item is supported, but no longer recommended for use and might become obsolete. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
|Product or category | Affected item | Version | Recommended action | More details and links

| Application management
| `HelmRepo` channel specification: usage of `insecureSkipVerify: "true"` is no longer inside the `configMapRef`
| 2.2
| Use `insecureSkipVerify: "true"` in the channel without the `configMapRef`
| See the YAML sample for the change.

|===

[#removals]
== Removals

A _removed_ item is typically function that was deprecated in previous releases and is no longer available in the product. You must use alternative features as a replacement for the removed function. Consider the alternative actions in the _Recommended action_ and details that are provided in the following table:

|===
|Product or category | Affected item | Version | Recommended action | More details and links
|===
