[#errata-updates]
= Errata updates

By default, Errata updates are automatically applied when released. See link:../install/upgrade_hub.adoc#upgrading-by-using-the-operator[Upgrading by using the operator] for more information.

*Important:* For reference, link:https://access.redhat.com/errata/#/[Errata] links and GitHub numbers might be added to the content and used internally. Links that require access might not be available for the user. 

== Errata 2.1.1

View a summarized list of {product-title} Errata 2.1.1 updates:

* Updated the `certificate` and `iam` policy controllers to fix an issue that prevented them from correctly maintaining the history of policy violations. (GitHub 6014)

* Increased VMware managed cluster default worker node values (4 CPU, 2 core, 16384 MB memory) to align with other providers. (GitHub 6206)

* Fixed an issue that caused a temporary error on the create resources page after you detach a managed cluster. (GitHub 6299)

* Fixed an issue in which the *Merge updates* option changed to `unset` after closing, modifying, and reopening an application. (GitHub 6349)

* Fixed an issue that prevented the complete clean up of a Microsoft Azure managed cluster after the addition of the cluster failed. (GitHub 6353)

* Fixed an issue that prevented the application topology from displaying the correct resource nodes after it deployed a `helm` type application to `local-cluster`. The application topology now displays all types of applications. (GitHub 6400)

* Application subscriptions: Enabled the `packageOverrides` YAML content for the Git `kustomization.yaml` file to use the path that is identified in the annotation of the subscription by default. (GitHub 6476)

* Fixed an issue that prevented subscription overrides from working when multiple subscriptions shared the same Git channel with the same branch. (GitHub 6476)

* Fixed an issue where policies using the `musthave` compliance type on a list of objects behaved similarly to the `mustonlyhave` compliance type. You can now specify as few as one field in a list of objects, and a `musthave` policy marks it as compliant as long as one object in the list has a field that matches the one specified in the policy. (GitHub 6492)

* Resolved an issue that configures all Thanos receivers so that every time-series stores 3 copies. It also ensures that every time-series is successfully written to at least 2 Thanos receivers in the target hashring. (GitHub 6547)

* Fixed an issue that caused the `merge update` setting to clear after selecting the setting when creating the application with the *Create* wizard , then opening it in an editor. (GitHub 6554)

* Fixed an issue that caused policies to display a `noncompliant` status. (GitHub 6630)

* Fixed an issue that occurred when the Git webhook was enabled on channel and subscription, but the subscribed resources were not applied to the target clusters. (GitHub 6785)

* Resolved an issue that can cause the `create resource` command to fail with a `Forbidden` error on the first load. (GitHub 6798)

* Exposed the following additional metrics with the {product-title-short} observability components for persistent volumes:

** `kubelet_volume_stats_available_bytes`
** `kubelet_volume_stats_capacity_bytes`
** `kube_persistentvolume_status_phase`
+
These metrics are not explicitly exposed in any dashboards or alert rules, but you can query them and set custom alert rules for them. (GitHub 6891)

* Fixed selection and deleselection inconsistencies when creating a new Policy. (GitHub 6897)

* Fixed an issue that caused bare metal clusters to fail to upgrade to 2.1.0 due to memory errors. (GitHub 6898) (link:https://bugzilla.redhat.com/show_bug.cgi?id=1895799[Bugzilla 1895799])

* Fixed an issue that required a pull secret in the `open-cluster-management-observability` namespace to successfully install the observability components. With this change, you are not required to create a pull secret to install the observability components. (GitHub 6911)

* Fixed an issue that caused the Governance and risk dashboard to take a long time to load. (GitHub 6925)

* Corrected a PATH error when starting a new Visual Web Terminal session. (GitHub 6928)

* Fixed a possible timing issue of the observability components in managed clusters changing to use incorrect images when the observability operator is restarted at runtime. (GitHub 6942)

* Added instructions for applying a fix to work around a failed application creation from a private Git repository. (GitHub 6952) (link:https://bugzilla.redhat.com/show_bug.cgi?id=1896341[Bugzilla 1896341])

* Fixed an issue that prevented the `klusterlet-addon-controller` from being recognized when it is in a namespace other than the `open-cluster-management` namespace. (GitHub 6986)

* Fixed an issue that caused the configuration policy controller to crash when an object template checked a field for a list, but found something set to that field that is not the expected list. (GitHub 7135)

* Fixed an issue in which the template editor YAML filters out the placementRule `status: 'True'` setting when making changes to an application deployed on all online clusters.
+
If you manually enter `status: 'True'` in the YAML editor for the placementRule before saving the updated application, the setting is retained. (GitHub 7152)

* Completed other general changes and bug fixes to code and documentation that are not listed.
