[#errata-updates]
= Errata updates

By default, Errata updates are automatically applied when released. See link:../install/upgrade_hub.adoc#upgrading-by-using-the-operator[Upgrading by using the operator] for more information.

*Important:* For reference, https://access.redhat.com/errata/#/[Errata] links and GitHub numbers might be added to the content and used internally. Links that require access might not be available for the user. 

FIPS notice: If you do not specify your own ciphers in `spec.ingress.sslCiphers`, then the `multiclusterhub-operator` provides a default list of ciphers. For 2.4, this list includes two ciphers that are _not_ FIPS approved. If you upgrade from a version 2.4.x or earlier and want FIPS compliance, remove the following two ciphers from the `multiclusterhub` resource: `ECDHE-ECDSA-CHACHA20-POLY1305` and `ECDHE-RSA-CHACHA20-POLY1305`.

== Errata 2.4.6

* Fixes an issue that sometimes results in a blank Applications _Overview_ page. (https://bugzilla.redhat.com/show_bug.cgi?id=2036197[Bugzilla #2036197])

* Removes the deprecated APIs from the cluster creation process. (https://bugzilla.redhat.com/show_bug.cgi?id=2041540[Bugzilla #2041540])

* You can now use blank spaces in the network name when creating VMware vSphere cluster. (https://bugzilla.redhat.com/show_bug.cgi?id=2074766[Bugzilla #2074766])

* Resolves a missing option to update the `local-cluster` in the {product-title-short}, and an issue that caused the same cluster to hang when the update was manually applied by using the {ocp-short} console. (https://bugzilla.redhat.com/show_bug.cgi?id=2079418[Bugzilla #2079418])

* Fixed an issue that prevented clusters from being created using {product-title-short} 2.4 after upgrading incrementally from {product-title-short} version 2.2. (https://bugzilla.redhat.com/show_bug.cgi?id=2089490[Bugzilla #2089490])

* Provisioning network settings are now optional to support bare metal deployments that do not require a provisioning network. (https://bugzilla.redhat.com/show_bug.cgi?id=2096406[Bugzilla #2096406])

* Fixes an issue that caused the existing cluster to be destroyed when attempting to create a cluster pool with the same name and namespace as an existing cluster. (https://bugzilla.redhat.com/show_bug.cgi?id=2102436[Bugzilla #2102436])

* Delivers updates to one or more of the product container images.

== Errata 2.4.5

* Fixes an observability upgrade issue. (Bugzilla #2087277)  

* Resolves unavailable search and failure in Redis that caused a large volume of error logs. Health monitoring is fixed to allow the search component to recover and reduce the log verbosity. (Bugzilla #2065318)

* Fixes a problem with creating a managed VMware cluster that is stuck in `creating` phase without feedback. (Bugzilla #1937078)

== Errata 2.4.4

* Fixes an issue that displayed a status of `Creating` for a cluster, though invalid information that was provided for the cluster caused the creation to fail. (Bugzilla #1995380)  

* Resolves an issue that linked to an extra log-in page, which sometimes caused an infinite loop when logging in or an automatic log-off after one hour. (Bugzilla #2061958)

* Delivers updates to one or more of the product container images.

== Errata 2.4.3

* Fixes an issue that prevented a cluster from being created by {product-title-short} when it uses an ecdsa-sha2-nistp521 ssh key. (Bugzilla #2048500)

* Delivers updates to one or more of the product container images.

== Errata 2.4.2

* Fixes an issue that prevented some policies that support `LimitRange` from adopting the changes to some of the attributes after the pod is restarted. (GitHub #19160)

* Delivers updates to one or more of the product container images.

== Errata 2.4.1

* Filters out all of the policies that are sourced by governance and risk from the `PolicyReport` data shown on the managed cluster details view, as the count for those policies is displayed elsewhere on that page. (GitHub #17438)

* Removes the optional sample `imagepullsecret` parameter in the Operatorhub Installation console to prevent accidental use of a pull secret that does not exist on their cluster. (GitHub #17884)

* Fixes an issue that caused a hibernating cluster in a cluster pool to hang in `Detaching` status when you destroy the cluster and the managed cluster status does not become `Unknown`. After upgrading to ACM 2.4.1, all clusters that were hung in a `Detaching` status, along with their namespaces, automatically terminate and resume expected behavior. No manual intervention should be required to clean up these clusters or their namespaces on the hub cluster. (GitHub #18249)

* Removes the required step to enable the feature gate to add a central infrastructure management (CIM) environment.

* Fixes an issue that prevented the validation errors caused by a failed `ClusterDeployment` from surfacing in the `ClusterPool` console. (Bugzilla #1995380)

* Delivers updates to one or more of the product container images.

