[#errata-updates]
= Errata updates

By default, errata updates are automatically applied when released. See link:../install/upgrade_hub.adoc#upgrading-by-using-the-operator[Upgrading by using the operator] for more information.

*Important:* For reference, https://access.redhat.com/errata/#/[Errata] links and GitHub numbers might be added to the content and used internally. Links that require access might not be available for the user. 

FIPS notice: If you do not specify your own ciphers in `spec.ingress.sslCiphers`, then the `multiclusterhub-operator` provides a default list of ciphers. For 2.3, this list includes two ciphers that are _not_ FIPS approved. If you upgrade from a version 2.3.x or earlier and want FIPS compliance, remove the following two ciphers from the `multiclusterhub` resource: `ECDHE-ECDSA-CHACHA20-POLY1305` and `ECDHE-RSA-CHACHA20-POLY1305`.

== Errata 2.3.2

View a summarized list of {product-title} Errata 2.3.2 updates:

* Fixes the links from the console to the credentials documentation. (GitHub #14993)

* Fixes the issue that prevented the multicluster observability operands from successfully upgrading. (Bugzilla #1993188)

* Delivers updates to one or more of the product container images.

== Errata 2.3.1

Fixes issues from the 2.3 version of a few product images.


