[#errata-updates]
= Errata updates

By default, Errata updates are automatically applied when released. See link:../install/upgrade_hub.adoc#upgrading-by-using-the-operator[Upgrading by using the operator] for more information.

*Important:* For reference, https://access.redhat.com/errata/#/[Errata] links and GitHub numbers might be added to the content and used internally. Links that require access might not be available for the user. 

== Errata 2.2.2

View a summarized list of {product-title} Errata 2.2.1 updates:

* This Errata addresses multiple container image updates. 
//CVEs: Do not link.

* Updated an issue with an existing policy in the `create policy` form displaying a blank page. (https://bugzilla.redhat.com/show_bug.cgi?id=1940588[Bugzilla 1940588])

* Added the Gatekeeper operator policy, which is now available in the **Create policy** specification drop-down menu. (GitHub 10447)

* Fixed an _Application topology_ deployment status issue. The Helm resources chart now displays the resource deployment status when the custom alias doesn't match the package name. (GitHub 10401)

* Fixed an issue with `ObservabilityAddon` in `terminating` status. (GitHub 10012)

* Added ability to create Azure clusters for all possible regions. (GitHub 9700)

* Fixed an issue with custom certificate authority on hub cluster. Submariner agent can now connect. (GitHub 9894)

* Fixed an issue with `packageOverrides` that were incorrectly specified in subscription CR. Errors occurred on a pod on the hub cluster, or the `klusterlet-addon-appmgr` pod on the managed cluster. The log now ignores the override. (GitHub 9700)

* Updated the Visual Web Terminal CLI to support {ocp-short} version 4.7. (GitHub 9640)

* Updated import cluster commands with double quotes to handle un-escaped characters. Be sure to use base64 with `-d` option. (GitHub 10748)

* Fixed an issue with the cluster YAML editor. (https://bugzilla.redhat.com/show_bug.cgi?id=1941778[Bugzilla 1941778])

* Fixed a bare metal issues, as it was not selected for a provisioning cluster. (GitHub 9850)

* Added support for NodeJS version 14 from version 12 to limit vulnerabilities in the base image. (GitHub 9540)

* Updated the `ServiceExport` API version in the base image. (GitHub 9840)

* Fixed bare metal reuse issue. Now when a `clusterdeployment` is deleted, the bare metal asset that was originally reference can be reused for another `clusterdeployment`. (GitHub 9272)

* Fixed a bare metal issue that caused updates too frequently. (GitHub 9463)

* Changed the Application management default reconcile rate to 15 minutes. The reconcile rate is also now configurable. (GitHub 10644)


(GitHub 9272, 10693) --waiting

== Errata 2.2.1

View a summarized list of {product-title} Errata 2.2.1 updates:

This Errata release delivers a new set of container images.

