[#errata-updates]
= Errata updates

By default, Errata updates are automatically applied when released. See link:../install/upgrade_hub.adoc#upgrading-by-using-the-operator[Upgrading by using the operator] for more information.

*Important:* For reference, https://access.redhat.com/errata/#/[Errata] links and GitHub numbers might be added to the content and used internally. Links that require access might not be available for the user. 

FIPS notice: If you do not specify your own ciphers in `spec.ingress.sslCiphers`, then the `multiclusterhub-operator` provides a default list of ciphers. For 2.4, this list includes two ciphers that are _not_ FIPS approved. If you upgrade from a version 2.4.x or earlier and want FIPS compliance, remove the following two ciphers from the `multiclusterhub` resource: `ECDHE-ECDSA-CHACHA20-POLY1305` and `ECDHE-RSA-CHACHA20-POLY1305`.


== Errata 2.5.1

* Fixes a bug that removed some applications that were deployed on the managed cluster. (link:..https://bugzilla.redhat.com/show_bug.cgi?id=2101453[Bugzilla 2101453])

* Resolves a console error in the _Overview_ page, which displayed `The backend service is unavailable`. (link:..https://bugzilla.redhat.com/show_bug.cgi?id=2096389[Bugzilla 2096389])

* Resolved a cluster add-on console issue with unhealthy status or failure for the policy add-on. (link:..https://bugzilla.redhat.com/show_bug.cgi?id=2088270[Bugzilla 2088270])

