[#errata-updates]
= Errata updates

By default, errata updates are automatically applied when released. See link:../install/upgrade_hub.adoc#upgrading-by-using-the-operator[Upgrading by using the operator] for more information.

*Important:* 

- {ocp} 4.5 is not supported with 2.2.4 and later errata releases. You must run {ocp} version 4.6 to upgrade to {product-title-short} version 2.2.4 or later. If you cannot upgrade your {ocp} version to 4.6, you can continue to use {product-title-short} version 2.2.3. 

- For reference, link:https://access.redhat.com/errata/#/[Errata] links and GitHub numbers might be added to the content and used internally. Links that require access might not be available for the user.

== Errata 2.2.8

View a summarized list of {product-title} Errata 2.2.8 updates:

* Fixes an issue that caused an application to be deleted when it was reconciled. The deletion was caused by a bad application manifest, such as incorrect kustomization, in a subscribed Git repository. With this fix, an error message is displayed in the application topology UI when there is a bad manifest, but the deployed application is not deleted. (Bugzilla 1972947)

* Decreases the number of unnecessary secrets that are created so the `cert manager` can start with less memory consumption. (GitHub 13127)

* Fixed an issue that caused some {ocp} version 4.8 observability metrics to not display in the Grafana UI. (GitHub 14821)

* Delivers updates to one or more of the product container images.

== Errata 2.2.7

View a summarized list of {product-title} Errata 2.2.7 updates:

This errata release delivers updates to one or more of the product container images.

== Errata 2.2.6

*Important:* See information in the previous notes.

{ocp} 4.8 is supported with 2.2.6 and later. *Important: {ocp} 4.8 for bare metal does not work for this release.

View a summarized list of fixes that the {product-title} Errata provides:

* Fixes issues with imported clusters. Imported clusters from {ocp-short} 3.11 in metrics visibility appear as other {ocp-short} clusters appear. (GitHub 13162)

* Fixes deployment failure with an application that subscribes to a Helm chart from a Git repository server with a custom CA certificate. Configure the application channel with either `insecureSkipVerify: true` to avoid custom CA verification, or add the custom CA certificates to the channel configuration. (GitHub 14467)

* Updates RedisGraph StatefulSet for metadata and specification updates to fix upgrade issues. (GitHub 13661)

* Fixes the compare and sort functionality of the Configuration Policy Controller to stop a continual increase of the Kubernetes resource on a managed cluster that is configured by the policy controller. (https://bugzilla.redhat.com/show_bug.cgi?id=1973772[Bugzilla 1973772])

* Updates the configuration policy namespace selection to identify the policy as `NonCompliant` when any selected namespace is `NonCompliant`. (https://bugzilla.redhat.com/show_bug.cgi?id=1969845[Bugzilla 1969845])

* Removes the use of the `SelfLink` attribute in `cert-manager` for compatibility with {ocp-short} 4.8. (GitHub 13121)

* Fixes an issue with `SecurityConstraintContext` policy, which prevented the search operator pod from starting. Updates the Docker image to run with a non-root user by default and updates the security context in the search operator deployment with `runAsNonRoot`, which starts the container with a non-root user. (https://bugzilla.redhat.com/show_bug.cgi?id=1967953[Bugzilla 1967953])

* Adds various container updates.

* Fixes an issue with bare metal asset fields not populating correctly. (GitHub 9850)

== Errata 2.2.5

*Important:* See information in the previous notes.

View a summarized list of fixes that the {product-title} Errata provides:

* Fixes multiple certificate issues.

* Adds labels to the Search redisgraph StatefulSet so that the pod is restarted automatically when certificates are refreshed. (GitHub 12299)

== Errata 2.2.4

*Important:* See information in the previous notes.

View a summarized list of fixes that the {product-title} Errata provides:

* Fixes issue with `placementrule` and `placementbinding` not being deleted when a disabled policy in the console was deleted. (GitHub 12689)

* Removes channel role and role binding that was created in the product system namespace. This fix avoids exposing system secrets to managed cluster service accounts. (GitHub 12319)

* Resolves a problem in Observability with the `endpoint-observability-operator` pod. Communication from managed cluster to hub cluster caused a `certificate signed by unknown authority` error if the hub cluster was installed on IBM cloud. (GitHub 11125)

* Fixes an issue with Hive controller not showing the correct version. (GitHub 12013)

* Fixes an issue with Observability crash. (https://bugzilla.redhat.com/show_bug.cgi?id=1967890[Bugzilla 1967890])

== Errata 2.2.3

View a summarized list of fixes that the {product-title} Errata provides:

* Adds a control category to the compliance operator policy. (GitHub 11234)

* Updates the YAML editor to display an error when an invalid `imageSetRef` is specified in the `ClusterDeployment`. (https://bugzilla.redhat.com/show_bug.cgi?id=1946244[Bugzilla 1946244])

* Fixes a console issue for imported clusters. (GitHub 11119)

* Adds quotation marks around `name` and `namespace` in YAML files to ensure the values are entered as a string. (https://bugzilla.redhat.com/show_bug.cgi?id=1936883[Bugzilla 1936883])

* Upgrades the Kustomize API module version to `0.8.5` to support a Kubernetes-sigs fix. (GitHub 11362)

* Adds support for the `GET` cluster role for non-administrator users to access managed clusters. The clusters list that is created and returned by the `PlacementRule` contains only the clusters that the user can access. ((https://bugzilla.redhat.com/show_bug.cgi?id=1949225)[Bugzilla 1946244])

* Adds an upgrade for the Gatekeeper and Gatekeeper Operator base images. (Github 12038) 

== Errata 2.2.2

View a summarized list of fixes that the {product-title} Errata provides:

* This errata addresses multiple security issues and container image updates. 
//CVEs: Do not link.

* Resolves an issue with an existing policy in the _create policy_ form displaying a blank page. (https://bugzilla.redhat.com/show_bug.cgi?id=1940588[Bugzilla 1940588])

* Adds the gatekeeper operator policy, which is now available in the **Create policy** specification drop-down menu. (GitHub 10447)

* Fixes an _Application topology_ deployment status issue. The Helm resources chart now displays the resource deployment status when the custom alias does not match the package name. (GitHub 10401)

* Fixes an issue with `ObservabilityAddon` in `terminating` status. (GitHub 10012)

* Adds the ability to create Azure clusters for all possible regions. (GitHub 9700)

* Fixes an issue with custom certificate authority on the hub cluster. Submariner agent can now connect. (GitHub 9894)

* Fixes an issue with `packageOverrides` that were incorrectly specified in subscription CR. Errors occurred on a pod on the hub cluster, or the `klusterlet-addon-appmgr` pod on the managed cluster. The log now ignores the override. (GitHub 9700)

* Updates the Visual Web Terminal CLI to support {ocp-short} version 4.7. (GitHub 9640)

* Updates import cluster commands with double quotes to handle unescaped characters. Be sure to use base64 with the `-d` option. (GitHub 10748)

* Fixes an issue with the cluster YAML editor. (https://bugzilla.redhat.com/show_bug.cgi?id=1941778[Bugzilla 1941778])

* Adds support for NodeJS version 14 from version 12 to limit vulnerabilities in the base image. (GitHub 9540)

* Updates the `ServiceExport` API version in the base image. (https://bugzilla.redhat.com/show_bug.cgi?id=1936528[Bugzilla 1936528])

* Fixes a bare metal asset issue where assets that were originally referenced in `clusterdeployment` could not be reused for another `clusterdeployment`. (GitHub 9272)

* Fixes a bare metal issue that caused updates too frequently. (GitHub 9463)

* Changes the Application management default reconcile rate to 15 minutes. The reconcile rate is also now configurable. (GitHub 10644)

* Fixes resource issues with the default alert manager by removing the `KubeAPIServerLatency` rule. (GitHub 10693)

* Updates role-based access control. Added authorization for the `Viewer` role to create and delete the `ManagedClusterView` resource, and added authorization for `cluster-manager-admin` users to `get` and view logs for pods. (GitHub 11243, 11242)

== Errata 2.2.1

View a summarized list of {product-title} Errata 2.2.1 updates:

This errata release delivers a new set of container images.

