[#fix-pack-updates]
= Fix pack updates

== Fix pack 2.0.2

Fix pack 2.0.2 resolves a rare problem that caused some managed cluster imports to
fail after upgrading from version 2.0.0 to version 2.0.1. You must upgrade to
fix pack 2.0.1 before upgrading to fix pack 2.0.2.

== Fix pack 2.0.1

View a summarized list of {product-title} fix pack 2.0.1 updates. 
 
. The cluster import process was improved. 
. Upgraded the `oc` and `kubectl` CLIs to the latest versions for the Visual Web Terminal.
. Administrator (`admin`) role access to the pod logs of managed clusters is fixed.
. The product uninstallation process was improved.
. Added a label for `Bare metal` to the Cloud field options list, on the _Importing a cluster_ page.
. The default `Network type` when you create a cluster is updated from OpenShiftSDN to OVNKubernetes.
. Subscriptions support `kustomization.yaml` files that contains an inline patch where the patch content inside the file is a single string.
. Improved how cloud providers manage sensitive data. 
. Removed DNS virtual IP parameter from the create cluster flow.
. Overview page does not become blank when clusters are detached.
