[#fix-pack-updates]
= Fix pack updates

View a summarized list of {product-title} fix pack 2.0.1 updates.

. {product-title} is bundled with the most recent version of `oc` (v4.5) and `kubectl` (v1.18) CLIs in the Visual Web Terminal.

// ^ Might say, "Upgraded the oc and kubectl CLIs for the Visual Web Terminal."

. As a user with an administrator role, you can access pod logs of managed cluster.

// are there steps documented on how to do this? If not, maybe it should not be in FP, but a new issue be created and labeled 2.0 doc refresh.

// Administrator role access to the pod logs of managed clusters is fixed.

. Search component CustomResourceDefinition (CRD) is removed during uninstallation. 

// Since the related issue #3689^ has been fixed, should the troubleshoot topic Troubleshooting reinstallation failure be removed? 

// Might say, "The uninstall script was improved"

. Added a label for `Bare metal` to the Cloud field options list, on the _Importing a cluster_ page.

. The default network type is updated from OpenShiftSDN to OVNKubernetes to support IPV6.

. As a user with the cluster role administrator role, you can manage your bare metal assets. 

// ^is bm tech preview for 2.0.1? Should we mention tech preview fixes as well? 

// Cluster role administrator access to manage bare metal assets is fixed. 

. Subscriptions support `kustomization.yaml` files that contains an inline patch where the patch content inside the file as a single string.

. The Secret Access Key ID for your cloud provider is hidden when you edit the provider connection.

// ^ maybe a note can be added to each cloud provider connection page in the doc

. Fixed the {product-title} version that is displayed in the About dialogue box.

. Internal DNS service is not supported.

// ^ not sure if this needs to be listed; on the last FP removed services were not mentioned

. Fixed issue with the Overview page, where cluster details did not display after managed clusters were detached.