[#fix-pack-updates]
= Fix pack updates

== Fix pack 2.0.3

View a summarized list of {product-title} fix pack 2.0.3 updates:

. Added upgrade and install improvements and fixes.
. Resolved resource leaks in `open-cluster-management`, which created system instability.
. Improvements with Bare metal workload messaging since worker nodes not required.
. Baremetal provider connection edit function fixed along with other baremetal usability issues.
. Resolved webhook validation error that caused uninstall failure.
. Fixed Klusterlet search pods crash.
. Added policy improvements.
. Fixed inconsistencies and added improvement in the console in the following areas: 
+
.. Instability in _Application overview_ page list of created applications.
.. Fixed _Governance and risk_ page not displayed if a policy annotation is missing.
.. Topology inconsistencies for policy violations fixed
.. Refresh settings on Policy violation pages fixed.
.. Fixed subscriptions propagated but failing in the console.
.. Cloud providers list scroll added to show Baremetal.
.. Enabled DNS VIP field in baremetal cluster create console.

== Fix pack 2.0.2

Fix pack 2.0.2 resolves a rare problem that caused some managed cluster imports to
fail after upgrading from version 2.0.0 to version 2.0.1. You must upgrade to
fix pack 2.0.1 before upgrading to fix pack 2.0.2.

== Fix pack 2.0.1

View a summarized list of {product-title} fix pack 2.0.1 updates. 
 
. The cluster import process was improved. 
. Upgraded the `oc` and `kubectl` CLIs to the latest versions for the Visual Web Terminal.
. Administrator (`admin`) role access to the pod logs of managed clusters is fixed.
. The product uninstallation process was improved.
. Added a label for `Bare metal` to the Cloud field options list, on the _Importing a cluster_ page.
. The default `Network type` when you create a cluster is updated from OpenShiftSDN to OVNKubernetes.
. Subscriptions support `kustomization.yaml` files that contains an inline patch where the patch content inside the file is a single string.
. Improved how cloud providers manage sensitive data. 
. Removed DNS virtual IP parameter from the create cluster flow.
. Overview page does not become blank when clusters are detached.
