[#known-issues_submariner]
= Known issues for Submariner

////
Please follow this format:

Title of known issue, be sure to match header and make title, header unique

Hidden comment: Release: #issue
Known issue process and when to write:

- Doesn't work the way it should
- Straightforward to describe
- Good to know before getting started
- Quick workaround, of any
- Applies to most, if not all, users
- Something that is likely to be fixed next release (never preannounce)
- Always comment with the issue number and version: //2.4:19417
- Link to customer BugZilla ONLY if it helps; don't link to internal BZs and GH issues.

Or consider a troubleshooting topic.
////

Review the known issues for Submariner. The following list contains known issues for this release, or known issues that continued from the previous release. 

For your {ocp} cluster, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/release_notes/ocp-4-12-release-notes#ocp-4-12-known-issues[{ocp-short} known issues]. 

For more about deprecations and removals, see http:..release_notes/deprecate_remove.adoc#deprecations-removals[Deprecations and removals] in the release notes.

[#not-all-infrastructure]
== Not all of the infrastructure providers that {product-title-short} can manage are supported

Submariner is not supported with all of the infrastructure providers that {product-title-short} can manage. Refer to the https://access.redhat.com/articles/6978968[{product-title-short} support matrix] for a list of supported providers.

[#headless-services-globalnet]
== Limited headless services support
//2.5:24159

Service discovery is not supported for headless services without selectors when using Globalnet.

[#submariner-vxlan]
== Deployments that use VXLAN when NAT is enabled are not supported
//2.5:24258

Only non-NAT deployments support Submariner deployments with the VXLAN cable driver.

[#submariner-ovn-k8]
== OVN Kubernetes requires OCP 4.11 and later
//2.6:25275

If you are using the OVN Kubernetes CNI network, you need Red Hat OpenShift 4.11 or later.

[#globalnet-limitations]
== Globalnet limitations
//2.5:26901

Globalnet is not supported with Red Hat OpenShift Data Foundation disaster recovery solutions. Make sure to use a non-overlapping range of private IP addresses for the cluster and service networks in each cluster for regional disaster recovery scenarios.

[#certificates-prevent-connection-broker]
== Self-signed certificates might prevent connection to broker
//2.7:27008

Self-signed certificates on the broker might prevent joined clusters from connecting to the broker. The connection fails with certificate validation errors. You can disable broker certificate validation by setting `InsecureBrokerConnection` to `true` in the relevant `SubmarinerConfig` object. See the following example:

[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
   name: submariner
   namespace: <managed-cluster-namespace>
spec:
   insecureBrokerConnection: true
----