[#known-issues-install]
= Installation known issues

Review the known issues for installing and upgrading. The following list contains known issues for this release, or known issues that continued from the previous release. 

For your {ocp} cluster, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/release_notes/#ocp-4-15-known-issues[{ocp-short} known issues]. 

For more about deprecations and removals, see xref:../release_notes/acm_deprecate_remove.adoc#deprecations-removals-acm[Deprecations and removals for {acm-short}].

== Console _Role Assignments_ page fails after you upgrade from the {previous-version} to {product-version}

After you upgrade {acm-short} {previous-version} to {acm-short} {product-version}, the *Role Assignments* page in the console fails to load. 

This issue only impacts clusters that are upgraded from {previous-version} to {product-version}, not new installations of {acm-short} {product-version}.

This issue occurs because of changes in the `MulticlusterRoleAssignment` custom resource definition. The `clusterSelection.placements` field is now required. However, `MulticlusterRoleAssignment` resources that were created in {acm-short} {previous-version} do not have this field populated. 

To resolve this issue, delete and recreate all `MulticlusterRoleAssignment` resources after upgrading. See the following steps:

. Export your existing `MulticlusterRoleAssignment` resources to back up all configurations.
. Delete the existing `MulticlusterRoleAssignment` resources. Run the following command:

+
[source,bash]
----
oc delete multiclusterroleassignment --all
----

. Recreate the resources with the required `clusterSelection.placements` field populated.

. Navigate to *User Management* > *Role Assignments* in the console to confirm that the page loads successfully without errors and check for your role assignments.

link:https://redhat.atlassian.net/browse/ACM-33106[ACM-33106].

[#uninstall-manual-remove-cr]
== Uninstalling and reinstalling earlier versions with an upgrade can fail

Uninstalling {acm-short} from {ocp-short} can cause issues if you later want to install earlier versions and then upgrade. For instance, when you uninstall {acm-short}, then install an earlier version of {acm-short} and upgrade that version, the upgrade might fail. The upgrade fails if the custom resources were not removed.

Follow the link:../install/cleanup_reinstall.adoc#cleanup-reinstall[Cleaning up artifacts before reinstalling] procedure to prevent this problem.

link:https://issues.redhat.com/browse/ACM-14343[ACM-14343]

[#add-on-stuck-upgrade]
== The _kubevirt-hyperconverged_ add-on is stuck in `in progress` status during upgrade from {acm-short} {product-version-prev} to {product-version}

During an upgrade from {acm-short} {product-version-prev} to {product-version}, the `kubevirt-hyperconverged-operator` resource is not cleaned up and you receive the following error in the `ManifestWork` resource:

[source,bash]
----
Failed to apply manifest: operatorpolicies.policy.open-cluster-management.io
"kubevirt-hyperconverged-operator" is forbidden: User
"system:serviceaccount:open-cluster-management-agent:klusterlet-work-sa"
cannot get resource "operatorpolicies" in API group
"policy.open-cluster-management.io" in the namespace "open-cluster-management-policies"
----

To resolve the issue, complete the following steps:

. Remove existing resources. Run the following commands:

+
[source,bash]
----
oc delete clustermanagementaddon kubevirt-hyperconverged-operator --ignore-not-found

oc delete addontemplate kubevirt-hyperconverged-operator --ignore-not-found
----

. Get the namespace that is specified in the `installer.namespace` label of the `kubevirt-hyperconverged` `ClusterManagementAddOn` resource. Run the following command and record the output to use in step 4:

+
[source,bash]
----
oc get clustermanagementaddon kubevirt-hyperconverged -o jsonpath='{.metadata.labels.installer\.namespace}'
----

. Delete the previous `ClusterManagementAddOn` resource, which is version `v1alpha1`. Run the following command:

+
[source,bash]
----
oc delete clustermanagementaddon kubevirt-hyperconverged
----

. Create the `ClusterManagementAddOn` resource. See the following example and replace `<installer_namespace>` with the value that you retrieved in the previous step:

+
[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1beta1
kind: ClusterManagementAddOn
metadata:
  name: kubevirt-hyperconverged
  annotations:
    addon.open-cluster-management.io/lifecycle: "addon-manager"
spec:
  addOnMeta:
    description: Kubevirt Hyperconverged
    displayName: Kubevirt Hyperconverged
  defaultConfigs:
    - group: addon.open-cluster-management.io
      resource: addontemplates
      name: kubevirt-hyperconverged
  installStrategy:
    type: Placements
    placements:
    - name: openshift-cnv
      namespace: <installer_namespace>
----

. Run the following command to apply your resource:

+
[source,bash]
----
oc apply -f <filename.yaml
----

link:https://issues.redhat.com/browse/ACM-31036[ACM-31036]

