:_mod-docs-content-type: CONCEPT

[#known-issues-virt]
= Virtualization known issues

Review the known issues for {acm-short} Virtualization capability. The following list contains known issues for this release, or known issues that continued from the previous release. 

For your {ocp} cluster, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/release_notes/ocp-4-20-release-notes#ocp-release-known-issues_release-notes[{ocp-short} known issues]. 

For more about deprecations and removals, see xref:../release_notes/acm_deprecate_remove.adoc#deprecations-removals-acm[Deprecations and removals for {acm-short}].

See the following known issues and limitations that might occur while using {ocp-virt} with {acm-short}:

* xref:../release_notes/acm_virt_ocp_version.adoc#virtualization-requires-4-20-1-or-later[{acm-short} Virtualization requires {ocp-virt} 4.20.1 or later]
* xref:../release_notes/acm_search_vm_resources.adoc#search-result-for-only-virtual-machine-resources-are-display[Search result for only virtual machine resources are displayed]
