[#known-issues-intro]
= Known issues

////
Please follow this format:

Title of known issue, be sure to match header and make title, header unique

Hidden comment: Release: #issue
Known issue process and when to write:

- Doesn't work the way it should
- Straightforward to describe
- Good to know before getting started
- Quick workaround, of any
- Applies to most, if not all, users
- Something that is likely to be fixed next release (never preannounce)
- Always comment with the issue number and version: //2.4:19417
- Link to customer BugZilla ONLY if it helps; don't link to internal BZs and GH issues.
- Place the rare Documentation known issue in the intro, as well as any intro to other product or technology release notes the user needs, like OCP or MCE.

Or consider a troubleshooting topic.
////

Review the known issues for {product-title}. The following list contains known issues for this release, or known issues that continued from the previous release. 

Cluster management or _Cluster lifecycle_ is provided by the {mce-short} with or without {product-title-short}. See the following known issues and limitations for Cluster management that apply to {product-title-short} only. Most cluster management known issues are located in the Cluster lifecycle documentation at link:../clusters/release_notes/known_issues.adoc#known-issues-cluster[Cluster lifecycle known issues]. 

For your {ocp} cluster, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/release_notes/ocp-4-12-release-notes#ocp-4-12-known-issues[{ocp-short} known issues]. 

For more about deprecations and removals, see http:..release_notes/deprecate_remove.adoc#deprecations-removals[Deprecations and removals] in the release notes.


* <<documentation-known-issues,Documentation known issues>>
* <<installation-known-issues,Installation known issues>>
* <<web-console-known-issues,Web console known issues>>
** <<observability-known-issues,Observability known issues>>
* <<cluster-management-issues,Cluster management known issues>>
* <<application-management-known-issues,Application management known issues>>
* <<governance-known-issues,Governance known issues>>
* <<backup-known-issues,Backup and restore known issues>>
* <<submariner-known-issues,Submariner known issues>>