[#known-issues-global-hub]
= Multicluster global hub Operator known issues

////
Please follow this format:

Title of known issue, be sure to match header and make title, header unique

Hidden comment: Release: #issue
Known issue process and when to write:

- Doesn't work the way it should
- Straightforward to describe
- Good to know before getting started
- Quick workaround, of any
- Applies to most, if not all, users
- Something that is likely to be fixed next release (never preannounce)
- Always comment with the issue number and version: //2.4:19417
- Link to customer BugZilla ONLY if it helps; don't link to internal BZs and GH issues.

Or consider a troubleshooting topic.
////

Review the known issues for the {global-hub} Operator. The following list contains known issues for this release, or known issues that continued from the previous release. For your {ocp-short} cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/release_notes/ocp-4-12-release-notes#ocp-4-12-known-issues[{ocp-short} known issues].

[#kafka-topics-after-upgrade]
== The {global-hub} operand does not use Kafka topics

There are three topics named `spec`, `status` and `event` in your Kafka cluster. You can configure these Kafka topics after you upgrade Kafka to {global-hub} 1.3 or later. After this upgrade, you only have two topics in the system: one for `spec` path and one for `status` path. The default external topic is `gh-spec` and `gh-status`. 

The {global-hub} operand provides the data and values for the {global-hub} operator to work. After upgrading {global-hub}, align the topics between your Kafka clusters and the {global-hub} operand. You can either create the  `gh-spec` and `gh-status` topics in your Kafka cluster, or you can update the {global-hub} operand to use the existing topics, such as: `spec` and `event`. 

Use the following YAML sample to update your {global-hub} operand to use the Kafka topics:

[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1alpha4
kind: MulticlusterGlobalHub
...
spec:
  availabilityConfig: Basic
  dataLayer:
    kafka:
      topics:
        specTopic: spec
        statusTopic: event
    postgres:
      retention: 18m
  enableMetrics: false
----

[#kafka-operator-keeps-restarting]
== Kafka operator keeps restarting 

In the Federal Information Processing Standard (FIPS) environment, the Kafka operator keeps restarting because of the out-of-memory (OOM) state. To fix this issue, set the resource limit to at least `512M`. For detailed steps on how to set this limit, see link:https://access.redhat.com/documentation/en-us/red_hat_amq_streams/2.6/html/deploying_and_managing_amq_streams_on_openshift/deploy-intro_str#assembly-fips-support-str[amq stream doc].

[#backup-and-restore-known-issues]
== Backup and restore known issues 

If your original {global-hub} cluster crashes, the {global-hub} loses its generated events and `cron` jobs. Even if you restore the new {global-hub} cluster, the events and `cron` jobs are not restored. To workaround this issue, you can manually run the `cron` job, see link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/multicluster_global_hub/multicluster-global-hub#global-hub-compliance-manual[Running the summarization process manually].

[#managed-cluster-not-counted]
== Managed cluster displays but is not counted

A managed cluster that is not created successfully, meaning `clusterclaim id.k8s.io` does not exist in the managed cluster, is not counted in the policy compliance dashboards, but shows in the policy console. 

[#operator-hyperlink]
== The {global-hub} is installed on {ocp-short} 4.13 hyperlinks might redirect home

If the {global-hub} Operator is installed on {ocp-short} 4.13, all hyperlinks that link to the managed clusters list and detail pages in dashboards might redirect to the {acm-short} home page. 

You need to manually go to your target page.

[#no-new-page-group-filter]
== The standard group filter cannot pass to the new page

In the _Global Hub Policy Group Compliancy Overview_ hub dashboards, you can check one data point by clicking *View Offending Policies for standard group*, but after you click this link to go to the offending page, the standard group filter cannot pass to the new page. 

This is also an issue for the *Cluster Group Compliancy Overview*.

[#cannot-redirect-ocp-cluster-obs]
== Cannot redirect to {ocp-short} 3.11 cluster _Observability_ page

If a managed hub cluster imports an {ocp-short} 3.11 cluster (deprecated) as managed cluster, it cannot redirect to the _Observability_ page in the *Global Hub* > *Overview* dashboard.

You need to manually navigate to your target page.
