[#known-issues-cluster]
= Cluster management known issues and limitations

Review the known issues for _Cluster management_ with {acm-short}. The following list contains Known issues this release, or known issues that continued from the previous release.

For Cluster management with the stand-alone {mce-short} known issues and limitations, see link:../clusters/release_notes/mce_known_issues.adoc#known-issues-mce[Cluster lifecycle known issues and limitations] in the {mce-short} documentation.

[#hub-cluster-one-way-limits]
== Hub cluster communication limitations

The following limitations occur if the hub cluster is not able to reach or communicate with the managed cluster:

- You cannot create a new managed cluster by using the console. You are still able to import a managed cluster manually by using the command line interface or by using the *Run import commands manually* option in the console.
- If you deploy an Application or ApplicationSet by using the console, or if you import a managed cluster into ArgoCD, the hub cluster ArgoCD controller calls the managed cluster API server. You can use AppSub or the ArgoCD pull model to work around the issue.

link:https://issues.redhat.com/browse/ACM-6292[ACM-6292]


[#local-cluster-auto]
== The local-cluster might not be automatically recreated

If the local-cluster is deleted while `disableHubSelfManagement` is set to `false`, the local-cluster is recreated by the `MulticlusterHub` operator. After you detach a local-cluster, the local-cluster might not be automatically recreated. 

- To resolve this issue, modify a resource that is watched by the `MulticlusterHub` operator. See the following example:

+
----
oc delete deployment multiclusterhub-repo -n <namespace>
----

- To properly detach the local-cluster, set the `disableHubSelfManagement` to true in the `MultiClusterHub`.

link:https://github.com/stolostron/backlog/issues/17790[ACM-17790]

[#cluster-local-offline-reimport]
== Local-cluster status offline after reimporting with a different name

When you accidentally try to reimport the cluster named `local-cluster` as a cluster with a different name, the status for `local-cluster` and for the reimported cluster display `offline`.

To recover from this case, complete the following steps:

. Run the following command on the hub cluster to edit the setting for self-management of the hub cluster temporarily:
+
----
oc edit mch -n open-cluster-management multiclusterhub
----

. Add the setting `spec.disableSelfManagement=true`.

. Run the following command on the hub cluster to delete and redeploy the local-cluster:
+
----
oc delete managedcluster local-cluster
----

. Enter the following command to remove the `local-cluster` management setting: 
+
----
oc edit mch -n open-cluster-management multiclusterhub
----

. Remove `spec.disableSelfManagement=true` that you previously added.

link:https://github.com/stolostron/backlog/issues/16977[ACM-16977]

[#hub-managed-clusters-clock]
== Hub cluster and managed clusters clock not synced

Hub cluster and manage cluster time might become out-of-sync, displaying in the console `unknown` and eventually `available` within a few minutes. Ensure that the {ocp-short} hub cluster time is configured correctly. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/installation_configuration/installing-customizing[Customizing nodes].

link:https://github.com/stolostron/backlog/issues/5636[ACM-5636]
