[#known-issues-install]
= Installation known issues

Review the known issues for installing and upgrading. The following list contains known issues for this release, or known issues that continued from the previous release. 

For your {ocp} cluster, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/release_notes/#ocp-4-15-known-issues[{ocp-short} known issues]. 

For more about deprecations and removals, see xref:../release_notes/acm_deprecate_remove.adoc#deprecations-removals-acm[Deprecations and removals for {acm-short}].

[#uninstall-manual-remove-cr]
== Uninstalling and reinstalling earlier versions with an upgrade can fail

Uninstalling {acm-short} from {ocp-short} can cause issues if you later want to install earlier versions and then upgrade. For instance, when you uninstall {acm-short}, then install an earlier version of {acm-short} and upgrade that version, the upgrade might fail. The upgrade fails if the custom resources were not removed.

Follow the link:../install/cleanup_reinstall.adoc#cleanup-reinstall[Cleaning up artifacts before reinstalling] procedure to prevent this problem.

link:https://issues.redhat.com/browse/ACM-14343[ACM-14343]