[#known-issues-console]
= Console known issues

Review the known issues for the console. The following list contains known issues for this release, or known issues that continued from the previous release. 

For your {ocp} cluster, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/release_notes#ocp-4-15-known-issues[{ocp-short} known issues]. 

For more about deprecations and removals, see xref:../release_notes/acm_deprecate_remove.adoc#deprecations-removals-acm[Deprecations and removals for {acm-short}].

[#klusterlet-addon-search-crashing]
== _klusterlet-addon-search_ pod fails

The `klusterlet-addon-search` pod fails because the memory limit is reached. You must update the memory request and limit by customizing the `klusterlet-addon-search`   deployment on your managed cluster. Edit the `ManagedclusterAddon` custom resource named `search-collector`, on your hub cluster. Add the following annotations to the   `search-collector` and update the memory, `addon.open-cluster-management.io/search_memory_request=512Mi` and `addon.open-cluster-management.io/                          search_memory_limit=1024Mi`.

For example, if you have a managed cluster named `foobar`, run the following command to change the memory request to `512Mi` and the memory limit to `1024Mi`:

----
oc annotate managedclusteraddon search-collector -n foobar \
addon.open-cluster-management.io/search_memory_request=512Mi \
addon.open-cluster-management.io/search_memory_limit=1024Mi
----

link:https://github.com/stolostron/backlog/issues/27173[ACM-27173]

[#search-display-node-managed]
== Search does not display node information from the managed cluster

Search maps RBAC for resources in the hub cluster. Depending on user RBAC settings, users might not see node data from the managed cluster. Results from search might be different from what is displayed on the _Nodes_ page for a cluster.

link:https://github.com/stolostron/backlog/issues/4598[ACM-4598]

[#cannot-upgrade-osd-ui]
== Cannot upgrade OpenShift Dedicated in console

From the console you can request an upgrade for OpenShift Dedicated clusters, but the upgrade fails with the `Cannot upgrade non openshift cluster` error message. Currently there is no workaround. 

link:https://issues.redhat.com/browse/ACM-10143[ACM-10143]
//remove when ACM-10077 is merged and closed --bcs 11/18/25

[#search-postgres-crashloopbackoff]
== Search PostgreSQL pod is in CrashLoopBackoff state

The `search-postgres` pod is in `CrashLoopBackoff` state. If {acm-short} is deployed in a cluster with nodes that have the `hugepages` parameter enabled and the `search-postgres` pod gets scheduled in these nodes, then the pod does not start.

Complete the following steps to increase the memory of the `search-postgres` pod:

. Pause the `search-operator` pod with the following command:
+
[source,bash]
----
oc annotate search search-v2-operator search-pause=true
----

. Update the `search-postgres` deployment with a limit for the `hugepages` parameter. Run the following command to set the `hugepages` parameter to `512Mi`:
+
[source,bash]
----
oc patch deployment search-postgres --type json -p '[{"op": "add", "path": "/spec/template/spec/containers/0/resources/limits/hugepages-2Mi", "value":"512Mi"}]'
----

. Before you verify the memory usage for the pod, make sure your `search-postgres` pod is in the `Running` state. Run the following command:
+
[source,bash]
----
oc get pod <your-postgres-pod-name>  -o jsonpath="Status: {.status.phase}"
----

. Run the following command to verify the memory usage of the `search-postgres` pod:
+
[source,bash]
----
oc get pod <your-postgres-pod-name> -o jsonpath='{.spec.containers[0].resources.limits.hugepages-2Mi}'
----

The following value appears: `512Mi`.

link:https://issues.redhat.com/browse/ACM-7467[ACM-7467]

[#cannot-edit-namespace-bindings-for-cluster-set]
== Cannot edit namespace bindings for cluster set

When you edit namespace bindings for a cluster set with the `admin` role or `bind` role, you might encounter an error that resembles the following message:

`ResourceError: managedclustersetbindings.cluster.open-cluster-management.io "<cluster-set>" is forbidden: User "<user>" cannot create/delete resource "managedclustersetbindings" in API group "cluster.open-cluster-management.io" in the namespace "<namespace>".`

To resolve the issue, make sure you also have permission to create or delete a `ManagedClusterSetBinding` resource in the namespace you want to bind. The role bindings only allow you to bind the cluster set to the namespace.

link:https://github.com/stolostron/backlog/issues/25389[ACM-25389]

[#scrolling-hosted]
== Horizontal scrolling does not work after provisioning hosted control plane cluster

After provisioning a hosted control plane cluster, you might not be able to scroll horizontally in the cluster overview of the {acm-short} console if the `ClusterVersionUpgradeable` parameter is too long. You cannot view the hidden data as a result.

To work around the issue, zoom out by using your browser zoom controls, increase your {acm-short} console window size, or copy and paste the text to a different location.

link:https://github.com/stolostron/backlog/issues/27107[ACM-27107]

[#cluster-id-ocm-console]
== Issues with entering the _cluster-ID_ in the OpenShift Cloud Manager console

If you did not access the `cluster-ID` in the OpenShift Cloud Manager console, you can still get a description of your {rosa} `cluster-ID` from the terminal. You need the {rosa} command line interface. See link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/4/html/rosa_cli/rosa-get-started-cli#rosa-get-started-cli[Getting started with the {rosa} CLI] documentation.

To get the `cluster-ID`, run the following command from the {rosa} command line interface:

[source,bash]
----
rosa describe cluster --cluster=<cluster-name> | grep -o ’^ID:.*
----

link:https://issues.redhat.com/browse/ACM-10651[ACM-10651]
//this one is not right. --bcs 11/18/25
