:_mod-docs-content-type: CONCEPT

[#known-issues-governance]
= Governance known issues

[role="_abstract"]
Review the known issues for Governance. The following list contains known issues for this release, or known issues that continued from the previous release. 

For your {ocp} cluster, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/release_notes/#ocp-4-15-known-issues[{ocp-short} known issues].

For more about deprecations and removals, see xref:../release_notes/acm_deprecate_remove.adoc#deprecations-removals-acm[Deprecations and removals for {acm-short}].

* xref:../release_notes/acm_config_policy_stuck.adoc#config-policy-stuck[Configuration policy listed compliant when namespace is stuck in _Terminating_ state]
* xref:../release_notes/acm_configurationpolicy_crd_terminating.adoc#configurationpolicy-crd-terminating[_ConfigurationPolicy_ stuck in terminating]
* xref:../release_notes/acm_policy_status_repeated_updates.adoc#policy-status-repeated-updates[Policy status shows repeated updates when enforced]
* xref:../release_notes/acm_kyverno_no_status.adoc#kyverno-no-status[Kyverno policies no longer report a status for the latest version]
