[#known-issues-install]
= Installation known issues

////
Please follow this format:

Title of known issue, be sure to match header and make title, header unique

Hidden comment: Release: #issue
Known issue process and when to write:

- Doesn't work the way it should
- Straightforward to describe
- Good to know before getting started
- Quick workaround, of any
- Applies to most, if not all, users
- Something that is likely to be fixed next release (never preannounce)
- Always comment with the issue number and version: //2.4:19417
- Link to customer BugZilla ONLY if it helps; don't link to internal BZs and GH issues.

Or consider a troubleshooting topic.
////

Review the known issues for installation. The following list contains known issues for this release, or known issues that continued from the previous release. 

For your {ocp} cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/release_notes/ocp-4-12-release-notes#ocp-4-12-known-issues[{ocp-short} known issues]. 

For more about deprecations and removals, see xref:../release_notes/deprecate_remove.adoc#deprecations-removals[Deprecations and removals].

[#install-arm-diable]
== Infrastructure operator error with ARM converged flow
//2.9: 8558
 
When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.

. Run the following command to create a `ConfigMap` resource:

+
----
oc create -f
----

. Apply your file by running `oc apply -f`. See the following file sample with `ALLOW_CONVERGED_FLOW` set to `false`:

+
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-assisted-service-config
  namespace: assisted-installer
data:
  ALLOW_CONVERGED_FLOW: false
----

. Annotate the `agentserviceconfig` with the following command:

+
----
oc annotate --overwrite AgentServiceConfig agent unsupported.agent-install.openshift.io/assisted-service-configmap=my-assisted-service-config
----

The agent appears in the inventory when the issue is resolved.

[#upgrade-remaining-resource]
== Deprecated resources remain after upgrade to Errata releases
//2.6X: 26987

After you upgrade from 2.4.x to 2.5.x, and then to 2.6.x, deprecated resources in the managed cluster namespace might remain. You need to manually delete these deprecated resources if version 2.6.x was upgraded from 2.4.x:

*Note:* You need to wait 30 minutes or more before you upgrade from version 2.5.x to version 2.6.x.

You can delete from the console, or you can run a command similar to the following example for the resources you want to delete:

----
oc delete -n <managed cluster namespace> managedclusteraddons.addon.open-cluster-management.io <resource-name> 
----
 
See the list of deprecated resources that might remain:

----
managedclusteraddons.addon.open-cluster-management.io:
policy-controller
manifestworks.work.open-cluster-management.io:
-klusterlet-addon-appmgr
-klusterlet-addon-certpolicyctrl
-klusterlet-addon-crds
-klusterlet-addon-iampolicyctrl
-klusterlet-addon-operator
-klusterlet-addon-policyctrl
-klusterlet-addon-workmgr
----

[#upgrade-pod-not-up]
== Pods might not come back up after upgrading {product-title-short}
// 2.5, 2.4: 23730

After upgrading {product-title-short} to a new version, a few pods that belong to a `StatefulSet` might remain in a `failed` state. This infrequent event is caused by a known link:https://github.com/kubernetes/kubernetes/issues/60164[Kubernetes issue].

As a workaround for this problem, delete the failed pod. Kubernetes automatically relaunches it with the correct settings.

[#openshift-container-platform-cluster-upgrade-failed-status]
== OpenShift Container Platform cluster upgrade failed status
// 2.0.0:3442

When an {ocp-short} cluster is in the upgrade stage, the cluster pods are restarted and the cluster might remain in `upgrade failed` status for a variation of 1-5 minutes. This behavior is expected and resolves after a few minutes.

[#create-multiclusterengine-button-not-working]
== Create MultiClusterEngine button not working
//2.6:25641

After installing {product-title} in the {ocp} console, a pop-up window with the following message appears:

`MultiClusterEngine required`

`Create a MultiClusterEngine instance to use this Operator.`

The *Create MultiClusterEngine* button in the pop-up window message might not work. To work around the issue, select *Create instance* in the MultiClusterEngine tile in the Provided APIs section.
