[#known-issues-install]
= Installation known issues

////
Please follow this format:

Title of known issue, be sure to match header and make title, header unique

Hidden comment: Release: #issue
Known issue process and when to write:

- Doesn't work the way it should
- Straightforward to describe
- Good to know before getting started
- Quick workaround, of any
- Applies to most, if not all, users
- Something that is likely to be fixed next release (never preannounce)
- Always comment with the issue number and version: //2.4:19417
- Link to customer BugZilla ONLY if it helps; don't link to internal BZs and GH issues.

Or consider a troubleshooting topic.
////

Review the known issues for installing and upgrading. The following list contains known issues for this release, or known issues that continued from the previous release. 

For your {ocp} cluster, see link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.17/html/release_notes/#ocp-4-15-known-issues[{ocp-short} known issues]. 

For more about deprecations and removals, see xref:../release_notes/acm_deprecate_remove.adoc#deprecations-removals-acm[Deprecations and removals for {acm-short}].

[#uninstall-manual-remove-cr]
== Uninstalling and reinstalling earlier versions with an upgrade can fail
//2.10:10953 and 2:12:14343, to name a few issues for this

Uninstalling {acm-short} from {ocp-short} can cause issues if you later want to install earlier versions and then upgrade. For instance, when you uninstall {acm-short}, then install an earlier version of {acm-short} and upgrade that version, the upgrade might fail. The upgrade fails if the custom resources were not removed.

Follow the link:../install/cleanup_reinstall.adoc#cleanup-reinstall[Cleaning up artifacts before reinstalling] procedure to prevent this problem.

[#install-siteconfig-ibbf]
== Cannot remove data image resources after a cluster reinstallation with Image-Based Break/Fix

If you change the `spec.nodes.<node-id>.bmcAddress` field while reinstalling a cluster with the Image-Based Break/Fix, the {sco} is unable to contact the original machine nd cannot delete the data image resources from the original cluster. To work around this issue, remove the finalizer from the data image resources before reinstalling a cluster with Image-Based Break/Fix.

* To remove the finalizer from the data image resources, run the following command:

+
[source,bash]
----
$ oc patch dataimages.metal3.io -n target-0 target-0-0 --patch '{"metadata":{"finalizers":[]}}' --type merge 
dataimage.metal3.io/target-0-0 patched
----