[#whats-new-in-red-hat-advanced-cluster-management-for-kubernetes]
= What's new in Red Hat Advanced Cluster Management for Kubernetes 

{product-title} provides visibility of your entire Kubernetes domain with built-in governance, cluster lifecycle management, and application lifecycle management.

* Get an overview of {product-title} from link:../about/welcome.adoc#welcome-to-red-hat-advanced-cluster-management-for-kubernetes[Welcome to {product-title}].

* See the link:../about/architecture.adoc#multicluster-architecture[Multicluster architecture] topic to learn more about major components of the product.

* The link:../about/quick_start.adoc#getting-started[Getting started] guide references common tasks that get you started, as well as the _Troubleshooting guide_.

[#installation]
== Installation

See link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online] for more information.

[#observability]
== Observability

* You can now install the observability service (`multicluster-observability-operator`) to monitor and optimize the health of your managed clusters. You can view the collected data and logs from Grafana dashboards. For more information see, link:../observability/observe_intro.adoc#observing-environments[Observing environments].

[#web-console]
== Web console

Use the web console to access, view, and manage your cluster from a central view. You can access your {product-title-short} console from {ocp}, monitor cluster data and details, use the search component across your cluster and with Visual Web Terminal, and manage cluster labels. To learn more details about the console components, see link:../console/console_intro.adoc#web-console[Web console].

[#cluster-management]
== Cluster management

* new 2.1: * Create clusters on the VMware vSphere service provider.
You can now provision and manage {ocp} clusters on the VMware vSphere Kubernetes cloud service provider.

See link:../manage_cluster/create_vm.adoc#creating-a-cluster-on-vmware-vsphere[Creating a cluster on VMware vSphere] for more information. 

* You can now group clusters and give user access to the group by creating ManagedClusterSet resources.  For more information, see link:../managed_cluster/custom_resource.adoc#creating-a-managedclusterset-resource[Creating a ManagedClusterSet resource].

[#application-management]
== Application management

{product-title} application managment improved usability with console configuration for managing resources. You can now create an application with supported channels in the console, edit YAML, configure secret settings, and more. See link:../manage_applications/app_resources.adoc#managing-application-resources[Managing application resources].

{product-title} Ansible Tower integration is available as technology preview so that you can deploy and manage Ansible jobs from the console. You can also view the job status in the _Resource topology_. See link:..manage_applications/app_console.adoc#application-console[Application console].

As part of application management, you can integrate Ansible Tower jobs into Git subscriptions. Automate tasks and integrate with external services, such as Slack and PagerDuty services. To learn more about working with Ansible, see link:..manage_applications/ansible_config.adoc#setting-up-ansible[Setting up Ansible Tower tasks (Technology preview)].

For all the application management changes and improved documentation, see link:../manage_applications/app_management_overview.adoc#managing-applications[Managing applications].

[#security-and-compliance]
== Security and compliance

* {product-title} supports several roles and uses Kubernetes authorization mechanisms. For more information, see link:../security/rbac.adoc#role-based-access-control[Role-based access control]. 

* For the certificate policy controller, you can now use the `disallowedSANPattern` parameter to check DNS names against patterns. For more information, view the link:../security/cert_policy_ctrl.adoc#certificate-policy-controller-yaml-table[Certificate policy controller YAML table]. 

* You can now contribute to the open source community, `open-cluster-management/policy-collection` by adding policies with the product governance framework. 

* You can now view the history voliation of your policy from the _Status_ tab. For more information, see link:../security/manage_policy_overview.adoc#manage-security-policies[Manage security policies]. 


See link:../security/grc_intro.adoc#governance-and-risk[Governance and risk] to learn more about the dashboard and the policy framework.

