[#whats-new-in-red-hat-advanced-cluster-management-for-kubernetes]
= What's new in Red Hat Advanced Cluster Management for Kubernetes

Red Hat Advanced Cluster Management for Kubernetes provides visibility of your entire Kubernetes domain with built-in governance, cluster lifecycle and application lifecycle management.

Get an overview of Red Hat Advanced Cluster Management for Kubernetes from link:../about/welcome.adoc[Welcome to Red Hat Advanced Cluster Management for Kubernetes].
See the link:../about/architecture.adoc[Multicluster architecture] topic to learn more about major components of the product.

To learn about the Red Hat Advanced Cluster Management for Kubernetes console capabilities, see link:../console/console.adoc[Observability in the console].

[#installation]
== Installation

With operator-based installation, you can install a working Red Hat OpenShift cluster on a configured cloud provider, such as Amazon Web Services, in less than 10 minutes.
See link:../install/install_connected.adoc[Installing while connected online] for more information.

[#cluster-management]
== Cluster management

* Create clusters on various Kubernetes cloud service providers.
You can provision and manage Red Hat OpenShift Container Platform clusters on selected Kubernetes cloud service providers.
See link:../manage_cluster/create.adoc[Creating a cluster with Red Hat Advanced Cluster Management for Kubernetes] for more information.
* Import existing Kubernetes clusters.
Import your existing Kubernetes clusters that are hosted on popular cloud service providers, or on private clouds to manage your clusters conveniently in one place.
See link:../manage_cluster/import.adoc[Importing a target managed cluster to the hub cluster] for more information.
* Manage all of your Red Hat OpenShift Container Platform cluster upgrades in one interface.
You can upgrade imported and provisioned Red Hat OpenShift Container Platform clusters either individually or in groups by using the console.

[#application-management]
== Application management

Deploy and maintain business applications distributed across your clusters.
This is accomplished through subscription-based automation.
You can also view the complete picture of your applications and their resource statuses from the topology page in the console.
For more information, see link:../manage_applications/app_management_overview.adoc[Managing applications].

* Subscriptions are Kubernetes resources that serve as sets of definitions for identifying Kubernetes resources (in GitHub, Objectstores, or hub deployables) and Helm charts within channels by using annotations, labels, and versions.
* Application resources are used to group and view the components across your applications.
* Placement rules define where and how your applications are subscribed.
Use placement rules to help you facilitate multicluster deployments.
* Channel resources define the source you subscribe to get your application components. (Git, Objectstore, Helm repository or templates (deployables) on the hub.

[#security-and-compliance]
== Security and compliance

Red Hat Advanced Cluster Management for Kubernetes supports several roles and use Kubernetes authorization mechanisms. For more information, see link:../security/rbac.adoc[Role-based access control]. 
// this file is being created in an active pr

With the Governance and risk dashboard, you can view and manage the number of security risks and policy violations in your clusters and applications.
Create custom policy controllers to report and validate the compliance of your policies on your cluster.
Enable and manage the following policy controllers that are installed by default:

* link:../security/cert_policy_ctrl.adoc[Certificate policy controller]
* link:../security/config_policy_ctrl.adoc[Kubernetes configuration policy controller]
* link:../security/iam_policy_ctrl.adoc[IAM policy controller]

See link:../security/grc_intro.adoc[Governance and risk] to learn more about the dashboard and the policy framework.

As you create policies, use the policy element, `templates` to describe how your resource is defined.
For more information about the policy elements, see link:../security/manage_policy_overview.adoc[Policy overview].
