[#whats-new]
= What's new in {product-title}

{product-title} provides visibility of your entire Kubernetes domain with built-in governance, cluster lifecycle management, and application lifecycle management, along with observability. With this release, you can move towards managing clusters in more environments, GitOps integration for applications, and more. 

Access the link:https://access.redhat.com/articles/7027073/[Support matrix] to learn about hub cluster and managed cluster requirements and support.

*Important:* Some features and components are identified and released as link:https://access.redhat.com/support/offerings/techpreview[Technology Preview].

* <<installation,Installation>>
* <<cluster-whats-new,Clusters>>
* <<global-hub-whats-new,multicluster global hub>>
* <<application-whats-new,Applications>>
* <<observability-whats-new,Observability>>
* <<governance-whats-new,Governance>>
* <<dr4hub-whats-new,Backup and restore>>
* <<net-whats-new,Networking>>

[#installation]
== Installation

//needs link

[#cluster-whats-new]
== Cluster 

Cluster lifecycle components and features are within the {mce-short}, which is a software operator that enhances cluster fleet management. The {mce-short} supports {ocp} and Kubernetes cluster lifecycle management across clouds and data centers. {ocp-short} is a prerequisite for this technology.

The documentation for {mce-short} (cluster) is in a different section of the product documentation.

View release notes, as well as tasks and support information at link:../clusters/cluster_mce_overview.adoc#cluster_mce_overview[Cluster lifecycle overview].

[#global-hub-whats-new]
== multicluster global hub 

See the link:../global_hub/global_hub_overview.adoc#multicluster-global-hub[multicluster global hub] documentation for more information. 

[#application-whats-new]
== Applications

With the new field, `.status.subscription`, you can see the overall subscription status. Previously, you only had the package status that indicated the status of an individual package. 

For other Application topics, see link:../applications/app_management_overview.adoc#managing-applications[Managing applications].

[#observability-whats-new]
== Observability

See link:../observability/observe_environments_intro.adoc#observing-environments-intro[Observability service introduction].

[#governance-whats-new]
== Governance

* Configure the operations of the Gatekeeper operator webhook to manage admission events. See link:../governance/create_gatekeeper.adoc#managing-gatekeeper-operator-policies[Managing Gatekeeper operator policies] for details.

* Enable the Policy Generator to process Helm charts and add descriptions to policies. See the link:../governance/policy_generator.adoc#policy-gen-yaml-table[Policy Generator configuration reference table] for more details.

* You can enable diff logging for `ConfigurationPolicy` resources using the `recordDiff` parameter in the `ConfigurationPolicy` resource. The difference between the `object-template` and the object on the managed cluster is logged inside the `config-policy-controller` pod on the managed cluster. See link:../governance/policy_ctrl_adv_config.adoc#configure-debug-log[Configure debug log] for details.

* You can enable the Policy Generator to process Helm charts and add descriptions to policies. See the link:../governance/policy_generator.adoc#policy-gen-yaml-table[Policy Generator configuration reference table] for more details.

* You can now configure the concurrency of the governance framework. See link:../governance/policy_ctrl_adv_config.adoc#policy-controller-advanced-config[Policy controller advanced configuration] for more details.

* The Gatekeeper operator exposes a setting in the custom resource definition within the `auditFromCache` audit, which is disabled by default. If you enable `auditFromCache`, then you need to set `config.gatekeeper.sh` for the sync details. See link:../governance/create_gatekeeper.adoc#managing-gatekeeper-operator-policies[Managing Gatekeeper operator policies] for details.

* Enable the `auditEventsInvolvedNamespace` to manage which namespace audit event to create, and the `admissionEventsInvolvedNamespace` to to manage which namespace admission event to create. See link:../governance/create_gatekeeper.adoc#managing-gatekeeper-operator-policies[Managing Gatekeeper operator policies].

* *Technology Preview:* You can monitor and install Operator Lifecycle Manager (OLM) operators across your clusters by using the operator policy controller. See link:../governance/policy_operator.adoc#policy-operator[Operator policy controller (Technology Preview)] for more information.

See link:../governance/grc_intro.adoc#governance[Governance] to learn more about the dashboard and the policy framework.

[#dr4hub-whats-new]
== Backup and restore

With {product-title-short} 2.10 or later, the `backup-restore-enabled` policy includes a new policy template named, `OADP-channel`. Use the `OADP-channel` template to prevent your backup and restore operator from running with the wrong custom resource definitions (CRDs). For more details, see link:../business_continuity/backup_restore/backup_validate.adoc[Validating your backup or restore configurations].

When you enable the backup component on the `MultiClusterHub`, the cluster backup and restore operator Helm chart installs {product-title-short} policies. With {product-title-short} version 2.10 or later, a new policy named, `backup-restore-auto-import`, informs you about issues with the automatic managed clusters import feature. For more details, see link:../business_continuity/backup_restore/backup_validate.adoc[Validating your backup or restore configurations].   

See link:../business_continuity/backup_restore/backup_intro.adoc#backup-intro[Backup and restore] to learn about disaster recovery solutions for your hub cluster.

[#net-whats-new]
== Networking

You can deploy Submariner on IBM Power Systems Virtual Server. See link:../networking/submariner/deploy_subm_console.adoc#deploying-submariner-console[Deploying Submariner by using the console] to learn more.

See link:../networking/networking_intro.adoc#networking[Networking].

[#whats-new-learn-more]
== Learn more about this release

* Get an overview of {product-title} from link:../about/welcome.adoc#welcome-to-red-hat-advanced-cluster-management-for-kubernetes[Welcome to {product-title}].

* See more release notes, such as _Known Issues and Limitations_ in the {product-title-short} xref:../release_notes/release_notes.adoc#release-notes[Release notes].

* See the link:../about/architecture.adoc#multicluster-architecture[Multicluster architecture] topic to learn more about major components of the product.

* See support information and more in the {product-title-short} link:../troubleshooting/troubleshooting_intro.adoc#troubleshooting[Troubleshooting] guide.

* Access the open source _Open Cluster Management_ repository for interaction, growth, and contributions from the open community. To get involved, see link:https://open-cluster-management.io/[open-cluster-management.io]. Visit the link:https://github.com/open-cluster-management-io[GitHub repository] for more information.
