[#whats-new-in-red-hat-advanced-cluster-management-for-kubernetes]
= What's new in Red Hat Advanced Cluster Management for Kubernetes 

{product-title} is now a generally available product. See what is available in version 2.1.

{product-title} provides visibility of your entire Kubernetes domain with built-in governance, cluster lifecycle management, and application lifecycle management.

* Get an overview of {product-title} from link:../about/welcome.adoc#welcome-to-red-hat-advanced-cluster-management-for-kubernetes[Welcome to {product-title}].

* See the link:../about/architecture.adoc#multicluster-architecture[Multicluster architecture] topic to learn more about major components of the product.

* The link:../about/quick_start.adoc#getting-started[Getting started] guide references common tasks that get you started, as well as the _Troubleshooting guide_.

[#installation]
== Installation

See link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online] for more information.

[#cluster-management]
== Cluster management


* new 2.1: * Create clusters on the VMware vSphere service provider.
You can now provision and manage {ocp} clusters on the VMware vSphere Kubernetes cloud service provider.
See link:../manage_cluster/create_vm.adoc#creating-a-cluster-on-vmware-vsphere[Creating a cluster on VMware vSphere] for more information. 

* Install the observability service (`multicluster-observability-operator`) to monitor and optimize the health of your managed clusters. You can view the collected data and logs from Grafana dashboards. For more information see, _Observability service_ section in the link:../console/observability.adoc[{product-title} console components documentation].

[#application-management]
== Application management




For more information, see link:../manage_applications/app_management_overview.adoc#managing-applications[Managing applications].

[#security-and-compliance]
== Security and compliance

{product-title} supports several roles and uses Kubernetes authorization mechanisms. For more information, see link:../security/rbac.adoc#role-based-access-control[Role-based access control]. 

With the Governance and risk dashboard, you can view and manage the number of security risks and policy violations in your clusters and applications.


See link:../security/grc_intro.adoc#governance-and-risk[Governance and risk] to learn more about the dashboard and the policy framework.

