[#trouble-aro-hcp-capz-create]
= Troubleshooting issues when creating Microsoft Azure Red Hat OpenShift {hcp} clusters by using Cluster API Provider for Azure

When using Cluster API Provider for Azure to create Azure Red Hat OpenShift {hcp} clusters, you might encounter problems that prevent cluster creation, or the process might require more information.

== Symptom: Issues when creating clusters

After creating an Azure Red Hat OpenShift {hcp} cluster by using Cluster API Provider for Azure, your cluster does not appear when you check the cluster status, or the cluster `AVAILABLE` status is `False`.

== Resolving the problem: Issues when creating clusters

To troubleshoot issues when creating Azure Red Hat OpenShift {hcp} cluster by using Cluster API Provider for Azure, complete the following steps:

. Verify that {mce} components are enabled. Run the following command to get the full component status:

+
[source,bash]
----
oc get mce multiclusterengine -o yaml | yq '.spec.overrides.components'
----

. Check if specific components are enabled. Run the following command:

+
[source,bash]
----
oc get mce multiclusterengine -o json | \
  jq -r '.spec.overrides.components[] | select(.name == "cluster-api")'
----

. If cluster creation still fails, check the controller logs for the Cluster API, Cluster API Provider for Azure, and Azure Service Operator for troubleshooting details. Complete the following steps:

. View Cluster API controller logs. Run the following command:

+
[source,bash]
----
oc logs -n multicluster-engine deployment/capi-controller-manager --tail=100
----

. View Cluster API Provider for Azure controller logs. Run the following command. Replace `<cluster_name>` with the name of your cluster:

+
[source,bash]
----
oc logs -n multicluster-engine deployment/capz-controller-manager --tail=100 | grep <cluster_name>
----

. View Azure Service Operator controller logs. Run thefollowing command:

+
[source,bash]
----
oc logs -n multicluster-engine deployment/azureserviceoperator-controller-manager --tail=100
----
