[#troubleshooting-network-config-bm]
= Troubleshooting network configuration for bare metal clusters

When you have a cluster that is installed by the Infrastructure Operator for Red Hat OpenShift, you must manually update the network configuration for your hub cluster to install workers.
 
[#symptom-worker-node-fail]
== Symptom: Installation for day two workers fails

At the Discover phase, the host cannot configure the network. Check for the following symptoms and messages:
----
This host is pending user action. Host timed out when pulling ignition. Check the host console...
----

Also check all the MCs (we need this actual term) from the `/sysroot/etc/NetworkManager/system-connections/` or `/sysroot/etc/sysconfig/network-scripts/` file paths. 

Check the failing host for the following messages:
----
system: Stopped Create Volatile Files and Directories...
----
----
system: Stopped target Swap...
----

[#resolving-cluster-rotating-agents]
== Resolving the problem: Manually configure the network

Perform the following task to manually configure your network:

. Delete the node from your hub cluster.
. Create your cluster from the console again.
. Add or append the following annotation to the BMH of the new node:

----
"bmac.agent-install.openshift.io/installer-args": "[\"--append-karg\", \"coreos.force_persist_ip\"]"
----

The node starts the installation, and after the Discovery phase, merges the network configuration between your changes and the initial phase.

