[#upgrade-managed-missing-ocp]
= Troubleshooting an attempt to upgrade managed cluster with missing {ocp-short} version 

You do not see the {ocp-short} version that you want in the console when you attempt to upgrade your managed cluster in the console.

[#symptom-missing-ocp]
== Symptom: Upgrading managed cluster with missing {ocp-short} version

When you attempt to upgrade a managed cluster from the console and click *Upgrade available* in the _Cluster details_ view to choose the {ocp-short} version from the dropdown list, the version is missing.

[#resolve-missing-ocp]
== Resolving the problem: Upgrading managed cluster with missing {ocp-short} version

See the following procedure:

. Ensure the version you want is included in the status of the `ClusterVersion` resource on the managed cluster. Run the following command:

+
[source,bash]
----
oc get clusterversion version -o jsonpath='{.status.availableUpdates[*].version}'
----

+
If your expected version is not displayed, then the version is not applicable for this managed cluster.

. Check if the `ManagedClusterInfo` resource includes the version on the hub cluster. Run the following command:

+
[source,bash]
----
oc -n <cluster_name> get managedclusterinfo <cluster_name> -o jsonpath='{.status.distributionInfo.ocp.availableUpdates[*]}'
----

. If the version is included, check to see if there is a `ClusterCurator` resource with a failure on the hub cluster. Run the following command:

+
[source,bash]
----
oc -n <cluster_name> get ClusterCurator <cluster_name> -o yaml
----

. If the `ClusterCurator` resource exists and the status of its `clustercurator-job` condition is `False`, delete the `ClusterCurator` resource from the hub cluster. Run the following command:

+
[source,bash]
----
oc -n <cluster_name> delete ClusterCurator <cluster_name>
----

. If the `ManagedClusterInfo` resource does not include the version, check the `work-manager` add-on log on the managed cluster and fix errors that are reported. Run the following command and replace the pod name with the real name in your environment:

+
[source,bash]
----
oc -n open-cluster-management-agent-addon logs klusterlet-addon-workmgr-<your_pod_name>
----