[#troubleshooting-cluster-status-offline-available-mce]
= Troubleshooting cluster status changing from offline to available

The status of the managed cluster alternates between `offline` and `available` without any manual change to the environment or cluster. 

[#symptom-cluster-status-changing-from-offline-to-available-mce]
== Symptom: Cluster status changing from offline to available

When the network that connects the managed cluster to the hub cluster is unstable, the status of the managed cluster that is reported by the hub cluster cycles between `offline` and `available`. 

[#resolving-the-problem-cluster-status-changing-from-offline-to-available-mce]
== Resolving the problem: Cluster status changing from offline to available

To attempt to resolve this issue, complete the following steps:

. Edit your `ManagedCluster` specification on the hub cluster by entering the following command:
+
----
oc edit managedcluster <cluster-name>
----
Replace _cluster-name_ with the name of your managed cluster.

. Increase the value of `leaseDurationSeconds` in your `ManagedCluster` specification. The default value is 60 seconds, and the offline grace period for the managed cluster is 5 minutes, which is 5 times the `leaseDurationSeconds`. This might not be enough time to maintain the connection with the network issues. Specify a greater amount of time for the lease. For example, setting `leaseDurationSeconds` to 240 seconds provides a 20 minute offline grace period.
