[#trouble-aro-hcp-capz-create]
= Troubleshooting issues when creating Microsoft Azure Red Hat OpenShift {hcp} clusters by using Cluster API Provider for Azure

When creating Azure Red Hat OpenShift {hcp} clusters by using Cluster API Provider for Azure, you might encounter issues that prevent you from creating the cluster, or require you to get additional information before you can resolve the problem.

== Symptom: Issues when creating Microsoft Azure Red Hat OpenShift {hcp} clusters by using Cluster API Provider for Azure

You are not able to create an Azure Red Hat OpenShift {hcp} cluster by using Cluster API Provider for Azure.

== Resolving the problem: Issues when creating Microsoft Azure Red Hat OpenShift {hcp} clusters by using Cluster API Provider for Azure

To troubleshoot issues when creating Azure Red Hat OpenShift {hcp} cluster by using Cluster API Provider for Azure, complete the following steps:

. Verify that {mce} components are enabled. Run the following command to get the full component status:

+
[source,bash]
----
oc get mce multiclusterengine -o yaml | yq '.spec.overrides.components'
----

. Check if specific components are enabled. Run the following command:

+
[source,bash]
----
oc get mce multiclusterengine -o json | \
  jq -r '.spec.overrides.components[] | select(.name == "cluster-api")'
----

If you are still not able to create the cluster, you might need more information to troubleshoot the issue. View the Cluster API, Cluster API Provider for Azure, and Azure Service Operator controller logs to get more information. Complete the following steps:

. View Cluster API controller logs. Run the following command:

+
[source,bash]
----
oc logs -n multicluster-engine deployment/capi-controller-manager --tail=100
----

. View Cluster API Provider for Azure controller logs. Run the following command. Replace `<cluster_name>` with the name of your cluster:

+
[source,bash]
----
oc logs -n multicluster-engine deployment/capz-controller-manager --tail=100 | grep <cluster_name>
----

. View Azure Service Operator controller logs. Run thefollowing command:

+
[source,bash]
----
oc logs -n multicluster-engine deployment/azureserviceoperator-controller-manager --tail=100
----
