[#ts-hcp-nodes-bm]
= Symptom: Nodes fail to be added to hosted control planes on bare metal

When you scale up a hosted control planes cluster with nodes that were provisioned by using Assisted Installer, the host fails to pull the ignition with a URL that contains port 22642. That URL is invalid for hosted control planes and indicates that an issue exists with the cluster.

[#identifying-ts-hcp-nodes-bm]
== Identifying the problem: Nodes fail to be added to hosted control planes on bare metal

. To determine the issue, review the assisted-service logs:
+
[source,bash]
----
oc logs -n multicluster-engine <assisted_service_pod_name> <1>
----
+
<1> Specify the Assisted Service pod name.

. In the logs, find errors that resemble these examples:
+
[source,bash]
----
error="failed to get pull secret for update: invalid pull secret data in secret pull-secret"
----
+
[source,bash]
----
pull secret must contain auth for \"registry.redhat.io\"
----

[#resolving-ts-hcp-nodes-bm]
== Resolving the problem: Nodes fail to be added to hosted control planes on bare metal

. To fix this issue, follow the instructions in "Add the pull secret to the namespace".

[#add-resources-ts-hcp-nodes-bm]
== Additional resources

* xref:../cluster_lifecycle/create_cluster_on_prem.adoc#on-prem-creating-your-cluster-with-the-cli-pull-secret[Add the pull secret to the namespace]