[#cluster-templates]
= Cluster templates overview

Cluster templates are data-driven templates that are used to generate the set of installation artifacts.
These templates follow the Golang text and template format, and they are instantiated by using data from the `ClusterInstance` CR.

This enables dynamic creation of installation manifests for each target cluster that has similar configurations, but with different values.

You can also create multiple sets based on the different installation methods or cluster topologies.

There are two types of cluster templates described in the following list:
//we introduce lists and anything before a colon to tell an screen reader to alert the user about what follows. 

* *Cluster-level:* Templates that must reference only cluster-specific fields.
* *Node-level:* Templates that can reference both cluster-specific and node-specific fields.

You can customize the templated fields. The {sco} supports all link:https://masterminds.github.io/sprig/[sprig library functions].

Additionally, the `ClusterInstance` API provides a function that you can use while creating your custom manifests:
//we need to introduce this with more than just a colon. Also removing "new" because other than in release notes, we don't write new because it will eventually not be new (maintaince required to go remove it)

`toYaml`:: The `toYaml` function encodes an item into a YAML string. If the item cannot be converted to YAML the function returns an empty string.
// is this a definition? 

See the following example of the `.toYaml` specification in the `ClusterInstance.Spec.Proxy` field:

[source,yaml]
----
[...]
{{ if .Spec.Proxy }}
  proxy:
{{ .Spec.Proxy | toYaml | indent 4 }}
{{ end }}
[...]
----

The {sco} provides the following default, validated, and immutable set of templates in the same namespace in which the operator is installed:

.Default set of templates
|===
|Installation method|Template type|File name|Template content

.2+|Assisted Installer
|Cluster-level templates
|`ai-cluster-templates-v1.yaml`
|`AgentClusterInstall`
`ClusterDeployment`
`InfraEnv`
`KlusterletAddonConfig`
`ManagedCluster`

|Node-level templates
|`ai-node-templates-v1.yaml`
|`BareMetalHost`
`NMStateConfig`

.2+|Image-based Install Operator
|Cluster-level templates
|`ibi-cluster-templates-v1.yaml`
|`ClusterDeployment`
`KlusterletAddonConfig`
`ManagedCluster`

|Node-level templates
|`ibi-node-templates-v1.yaml`
|`BareMetalHost`
`ImageClusterInstall`
`NetworkConfigMap`
|===

//we don't normally have these midtopic but I am opened to it, we just should have a line before it introducing the user to why these are here:

* <<special-template-variables,Special template variables>>
* <<sync-wave-annotation,Manifest order with the `siteconfig.open-cluster-management.io/sync-wave` annotation>>

[#special-template-variables]
== Special template variables

The {sco} provides a set of special template variables that you can use in your templates. See the following list:

- *`CurrentNode`* The {sco} explicitly controls the iteration of the node objects and exposes this variable to access all the content for the current node being handled in templating.
- *`InstallConfigOverrides`* Contains the merged `networkType`, `cpuPartitioningMode` and `installConfigOverrides` content.
- *`ControlPlaneAgents`* Consists of the number of control plane agents and it is automatically derived from the `ClusterInstance` node objects.
- *`WorkerAgents`* Consists of the number of worker agents and it is automatically derived from the `ClusterInstance` node objects.

Capitalize the field name in the text template to create a custom templated field.

For example, the `ClusterInstance` `spec` field is referenced with the `.Spec` prefix.
However, you must reference special variable fields with the `.SpecialVars` prefix.

*Important:* Instead of using the `.Spec.Nodes` prefix for the `spec.nodes` field, you must reference it with the `.SpecialVars.CurrentNode` special template variable.

For example, if you want to specify the `name` and `namespace` for your current node by using the `CurrentNode` special template variable, use the field names in the following form:

[source,yaml]
----
name: "{{ .SpecialVars.CurrentNode.HostName }}"
namespace: "{{ .Spec.ClusterName }}"
----

[#sync-wave-annotation]
== Manifest order with the `siteconfig.open-cluster-management.io/sync-wave` annotation
//I think we can make this header a bit more concise, can we remove the annotation since we are putting it directly below
// Customizing manifest order (?), though that uses a verb and this is not followed by steps; the way it is right now, Manifest looks like a verb. So we need to either work on the title or build a procedure here, I think:

You can control the order in which manifests are created, updated, and deleted by using the `siteconfig.open-cluster-management.io/sync-wave` annotation. The annotation takes an integer as a value, and that integer constitutes as a _wave_.

You can add one or several manifests to a single wave. If you do not specify a value, the annotation takes the default value of `0`.

The {sco} reconciles the manifests in ascending order when creating or updating resources and it deletes resources in descending order.

In the following example, if the {sco} creates or updates the manifests, the `AgentClusterInstall` and `ClusterDeployment` CRs are reconciled in the first wave, while `KlusterletAddonConfig` and `ManagedCluster` CRs are reconciled in the third wave.
//should we have an example here?

If the {sco} deletes the resources, `KlusterletAddonConfig` and `ManagedCluster` CRs are the first to be deleted, while the `AgentClusterInstall` and `ClusterDeployment` CRs are the last.

include::../siteconfig/siteconfig_ai_cluster_templates_v1.adoc[]
//we will need to visit this, as we don't use them