[#siteconfig-intro]
= {sco}

The {sco} offers a template-driven cluster provisioning solution, which allows you to provision clusters with all available installation methods.
The {sco} introduces the unified `ClusterInstance` API, which is derived from the `SiteConfig` API of the `SiteConfig` generator kustomize plugin.
The `ClusterInstance` API decouples parameters that define a cluster from the manner in which the cluster is deployed.
This separation removes certain limitations that are presented by the `SiteConfig` kustomize plugin in the current xref:../../edge_computing/ztp-deploying-far-edge-sites.adoc#ztp-deploying-far-edge-sites[{ztp-first} flow], such as agent cluster installations and scalability constraints posed by ArgoCD.
Using the unified `ClusterInstance` API, the {sco} offers the following improvements:

Isolation:: Separates cluster definition from the installation method. The `ClusterInstance` CR captures the cluster definition, while cluster templates capture the cluster architecture and installation methods.
Unification:: The {sco} unifies both Git and non-Git workflows. Users can apply the `ClusterInstance` CR directly on the hub cluster or synchronize them through a GitOps solution, like ArgoCD.
Consistency:: Maintains a consistent API across all installation methods, whether using the Assisted Installer, the Image Based Install Operator, or any other custom template-based approach.
Scalability:: Achieves greater scalability per cluster than the `SiteConfig` kustomize plugin.
Flexibility:: Provides users with more power to deploy and install clusters by using custom cluster templates.
Troubleshooting:: Offers insightful information regarding cluster deployment status and rendered manifests, significantly enhancing the troubleshooting experience.

For more information about the Image Based Install Operator and the Assisted Installer, see https://access.redhat.com/articles/7075493[Image-based installations for {sno}] and link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/installing/installing-on-premise-with-assisted-installer[Installing an on-premise cluster using the {ai-full}]

* xref:../siteconfig/siteconfig_flow#operator-flow[The {sco} flow]
* xref:../siteconfig/cluster-templates.adoc#cluster-templates[Cluster templates overview]

////
Temporarily leaving this for my reference for the structure and links.

include::../siteconfig/siteconfig-operator-flow.adoc

include::../siteconfig/clusterinstance-cr-reference.adoc              |
include::../siteconfig/clusterinstance-cr-config-parameters.adoc      | These 3 topics will move to a separate PR, under the API docs
include::../siteconfig/clusterinstance-cr-conditions-reference.adoc   |

include::../siteconfig/cluster-templates.adoc

include::siteconfig/create-custom-cluster-templates.adoc

include::siteconfig/cnf-deploying-siteconfig-operator.adoc[leveloffset=+1]

include::siteconfig/cnf-installing-clusters.adoc[leveloffset=+1]

* xref:../../installing/installing_on_prem_assisted/installing-on-prem-assisted.adoc#installing-on-prem-assisted[Installing an on-premise cluster using the {ai-full}]

* xref::../../edge_computing/installing_with_siteconfig_operator/cnf-understanding-siteconfig-operator#cnf-clusterinstance-conditions-reference_siteconfig-operator[ClusterInstance CR conditions]

include::siteconfig/cnf-deprovisioning-clusters.adoc[leveloffset=+1]
////
