:_mod-docs-content-type: PROCEDURE

[#restore-data-initial-hub]
= Restore data to the initial hub cluster

[role="_abstract"]
After you run a hub cluster disaster recovery simulation, you can restore your data to the initial hub cluster, then use it as your primary hub cluster. Complete the following steps to restore your data to the initial hub cluster after running a disaster recovery simulation.

When you conduct a disaster recovery operation test, you simulate a primary hub cluster failure and restore its data to a new hub cluster, verifying that your backup and restore process works. After your disaster recovery test simulation completes, return to the primary hub cluster and make it the active hub cluster that manages the cluster fleet.

.Prerequisites

* If the primary hub cluster must stay active during the disaster recovery simulation, complete xref:../backup_restore/backup_active_restore.adoc[Run the restore operation while the primary hub cluster is active] before you begin.

.Procedure

. After you restore hub cluster data, make the new hub cluster the active hub cluster. See _Activate the new hub cluster_ in the _Additional resources_ section.
. If you want to use the initial primary hub cluster, see _Return to the primary hub cluster_ in the _Additional resources_ section.
. After you activate your primary hub cluster, enable the backup schedule. See _Enable the backup schedule on the primary hub cluster_ in the _Additional resources_ section.

.Additional resource

* xref:../backup_restore/backup_restore_hub_activate.adoc[Activate the new hub cluster]
* xref:../backup_restore/backup_restore_hub_return.adoc[Return to the primary hub cluster]
* xref:../backup_restore/backup_restore_hub_enable_schedule.adoc[Enable the backup schedule on the primary hub cluster]
