:_mod-docs-content-type: PROCEDURE

[#dr4hub-install-oadp-custom]
= Install a custom OADP version

[role="_abstract"]
Customize the OADP version installed by the backup and restore operator by setting an annotation on your `MultiClusterHub` resource.

.Procedure

. To override the OADP version installed by the backup and restore operator, use the following annotation on the `MultiClusterHub` resource:

+
[source,yaml]
----
installer.open-cluster-management.io/oadp-subscription-spec: '{"channel": "stable-1.4"}'
----
+
*Important:* If you use this option to get a different OADP version than the one installed by default by the backup and restore operator, make sure this version is supported on the {ocp} version used by the hub cluster. Use this override option with caution because it can result in unsupported configurations.

. *Optional:* To install a specific OADP version of the operator, set your annotation. For example, if you want to install OADP from the `stable-1.5` channel and select a specific version of the operator, set the `startingCSV` property on the `installer.open-cluster-management.io/oadp-subscription-spec` annotation. Your `MultiClusterHub` resource might resemble the following example:

+
[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    installer.open-cluster-management.io/oadp-subscription-spec: '{"channel": "stable-1.5","installPlanApproval": "Automatic","name":
      "redhat-oadp-operator","source": "redhat-operators","sourceNamespace": "openshift-marketplace" "startingCSV": “oadp-operator.v5.0.2”}'
  name: multiclusterhub
spec: {}
----

. Enable the `cluster-backup` option on the `MultiClusterHub` resource by setting `cluster-back` to `true`.
. To verify that the OADP operator uses the `oadp-subscription-spec` annotation properties, confirm that the subscription YAML for the OADP operator includes the properties that are specified by the annotation.
