[#backup-existing-clusters]
= Understanding outcomes for existing managed clusters during the restore process

Before you run the restore operation for existing hub clusters, understand the following constraints: 

* Existing managed cluster are detached during the restore process.
* There are more resources on the restore hub cluster than the backup hub cluster.

[#existing-clusters-detached]
== Existing managed clusters are detached during the restore process

A detached managed cluster has content that does not match the content of the backup hub cluster. When you run a restore operation on your hub cluster that already manages some clusters and the `cleanupBeforeRestore` option set to `CleanupRestored`, the following outcomes occur:  

* Only when an earlier backup creates the `ManagedCluster` resources, the `velero.io/backup-name: backupName` label annotation is set, and the backup managed clusters are not part of the restored backup, managed clusters are detached and the data is cleaned on the managed clusters.
 
* When the `ManagedCluster` resources are not created by an earlier backup and do not have the `velero.io/backup-name: backupName` label annotation, `ManagedCluster` resources are not cleaned up. The managed clusters continue to be managed by your hub cluster.

[#restore-hub-resources]
== Restore hub cluster has more resources than the backup hub cluster

If your restore operation uses a hub with earlier created user data, then the restore operation results in a hub that does not have the exact content as the primary hub. The user data includes the following resources: `policy`, `application`, `credential`, or any custom resource defined by the user. A restore operation with the `cleanupBeforeRestore` option set to `CleanupRestored` is not going to clean up these resources because they were created by the users and not created by an earlier backup. 

If you intend to use an existing hub for a restore hub configuration and expect that the hub has the same content as the backup hub after the restore is completed, tag any resource that would be part of a hub backup with the `velero.io/backup-name: backupName` label annotation. To do so, complete the following documentation: xref:../backup_restore/backup_tag_resources.adoc#backup-tagging-resources[Tagging resources].


