[#backup-restore-obs]
= Backup and restore for Observability

The Observability service uses an S3-compatible object store to persist all time-series data collected from managed clusters. Because Observability is a stateful service, it is sensitive to active and passive failover patterns. You must configure Oservability to ensure data continuity and integrity during hub cluster migration or failover.

The Observability service automatically adds the `cluster.open-cluster-management.io/backup` label to Observability-related resources to be included in the standard product backup and restore processes.

.Resources that are automatically backuped up and restored
|====
| Resource type | Resource name  

.5+| ConfigMaps 
| `observability-metrics-custom-allowlist`
| `thanos-ruler-custom-rules`
| `alertmanager-config`
| `policy-acs-central-status`
| Any ConfigMap labeled with `grafana-custom-dashboard`

.9+| Secrets
| `thanos-object-storage`
| `observability-server-ca-certs`
| `observability-client-ca-certs`
| `observability-server-certs`
| `observability-grafana-certs`
| `alertmanager-byo-ca`
| `alertmanager-byo-cert`
| `proxy-byo-ca`
| `proxy-byo-cert`
|====

//== Additional resources
//still figuring out how to separate concept vs procedure
== Manually backup required Observability resources

Some Observability resources must be manually backed up and restored to ensure continuity across hub clusters.

Complete the following steps to manually back the `observatorium` resource and the `MultiClusterObservability` custom resource:

. To preserve the tenant ID of the `observatorium` resource during the restore, run the following command:

+
[source,bash]
----
oc get observatorium -n open-cluster-management-observability -o yaml > observatorium-backup.yaml
----

. To backup the `observability` deployment, run the following command:

+
[source,bash]
----
oc get mco observability -o yaml > mco-cr-backup.yaml
----

