[#config-hcp-backup]
= Backup and restore for hosted control planes and hosted clusters

The {ocp-short} {hcp} disaster recovery documentation describes how to install the {oadp} operator, how to create {oadp} resources, and how to use the {oadp} to backup and restore hosted clusters. See the following additional information about backup and restore for hosted clusters that applies to {acm-short}:

* Restore the hosted clusters before you restore the {acm-short} hub cluster. Find the process to restore hosted clusters at link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/hosted_control_planes/high-availability-for-hosted-control-planes#hcp-disaster-recovery-oadp[OpenShift Hosted Control Plane Disaster Recovery documentation]. However, you do not need to install the {oadp} operator in the `openshift-adp` namespace.

* For {acm-short}, you can enable backup and restore and use the {oadp} operator that is installed by the backup and restore component. 

* {oadp} resources, such as `DataProtectionApplication`, `BackupSchedule`, `Backup` and `Restore` for your hosted clusters, are created in the `open-cluster-management-backup` namespace.

* See the link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/hosted_control_planes/high-availability-for-hosted-control-planes#hcp-backup-restore-aws-overview_hcp-disaster-recovery-aws[Overview of Hosted Cluster backup and restore process] for more information about the backup and restore process.