:_mod-docs-content-type: PROCEDURE

[#dr4hub-install-backup-and-restore]
= Install the backup and restore operator

[role="_abstract"]
Install and enable the backup and restore operator on hub clusters by setting up your hub cluster. The cluster backup and restore operator is not installed automatically. 

.Prerequisites

* From your {ocp} cluster, install the {acm-short} operator version {product-version}. The `MultiClusterHub` resource is automatically created when you install {acm-short}, and displays the following status: `Running`.

Complete the following steps to set up your hub cluster for the installation.

.Procedure

. Enable the backup operator for your hub clusters. See 
_Enabling the backup operator for your hub clusters_.
. Create a storage location secret. See _Creating the storage location secret_.
. Install the OADP operator. See _Installing the OADP operator_.
. Optional: Install a custom OADP version. See _Installing a custom OADP version_.
. Create a `DataProtectionApplication` resource. See _Creating a _DataProtectionApplication_ resource_.
. If you are in a disconnected environment, enable the backup and restore component. See _Enabling the backup and restore component in a disconnected environment_.

.Additional resources

* xref:../backup_restore/backup_install_storage_secret.adoc#creating-the-storage-location-secret[Creating the storage location secret]
* xref:../backup_restore/backup_install_enable_backup_operator.adoc#enabling-backup-operator-clusters[Enabling the backup operator for your hub clusters]
* xref:../backup_restore/backup_install_oadp.adoc#installing-the-oadp-operator[Installing the OADP operator]
* xref:../backup_restore/backup_install_oadp_custom.adoc#installing-custom-oadp[Installing a custom OADP version]
* xref:../backup_restore/backup_install_dpa.adoc#creating-a-dataprotectionapplication-resource[Creating a _DataProtectionApplication_ resource]
* xref:../backup_restore/backup_install_disconnected.adoc#enabling-the-backup-and-restore-component-in-a-disconnected-environment[Enabling the backup and restore component in a disconnected environment]
