:_mod-docs-content-type: PROCEDURE

[#restore-activation-resources]
= Restore activation resources

[role="_abstract"]
Restore activation data so the hub cluster can manage the clusters.

.Prerequisites

* Before you restore the activation data on the passive hub cluster, shut down the previous hub cluster where the backup was created. If the primary hub cluster is still running, it attempts to reconnect with the managed clusters that are no longer available, based on the reconciliation procedure running on this hub cluster.

.Procedure

. Restore activation resources when you want the hub cluster to manage the clusters.
+
Use the `restore-acm-passive-activate` sample. In this case it is assumed that the other data has been restored already on the hub cluster that is using the passive resource.
+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: restore-acm-passive-activate
  namespace: open-cluster-management-backup
spec:
  cleanupBeforeRestore: CleanupRestored
  veleroManagedClustersBackupName: latest
  veleroCredentialsBackupName: skip
  veleroResourcesBackupName: skip
----
+
You have some options to restore activation resources, depending on how you restored the passive resources:
+
* If you used the `restore-acm-passive-sync cluster.open-cluster-management.io` resource as documented in xref:../backup_restore/backup_restore_passive.adoc#restore-passive-resources-check-backups[Restore passive resources while checking for backups], update the `veleroManagedClustersBackupName` value to `latest` on this resource. As a result, the managed cluster resources and the `restore-acm-passive-sync` resource are restored.
* If you restored the passive resources as a one time operation, or did not restore any resources yet, choose to restore all resources.

. Restore managed cluster activation data. Apply the `cluster.open-cluster-management.io/backup: cluster-activation` label.
+
*Note:* Managed cluster activation data or other activation data resources are stored by the managed clusters backup and by the resource-generic backups. when you use the  When the activation data is restored on a new hub cluster, managed clusters are being actively managed by the hub cluster where the restore is run. See _Schedule backups_ to learn how you can use the operator.

. Restore all resources. To restore all the data, use the following `restore-acm` sample: 

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: restore-acm
  namespace: open-cluster-management-backup
spec:
  cleanupBeforeRestore: None
  veleroManagedClustersBackupName: latest
  veleroCredentialsBackupName: latest
  veleroResourcesBackupName: latest
----

. Get the status of the restore operation by running the following command: 

+
[source,bash]
----
oc describe -n open-cluster-management-backup restore-acm
----

.Additional resources

* xref:../backup_restore/backup_schedule.adoc#using-backup-restore[Schedule backups]
