:_mod-docs-content-type: PROCEDURE

[#prepare-new-hub]
= Prepare the new hub cluster

[role="_abstract"]
To restore a hub cluster and ensure that it is the same as the initial hub cluster, use a new hub cluster when you run the hub restore operation. 

When you use a new hub cluster, you prevent any pre-existing user data from interfering with the restoration. You also ensure that the new hub cluster only has the backup data, making the cluster the same as the initial hub cluster. 

.Prerequisites

* In a disaster recovery simulation, you might need to return back to your initial hub cluster instead of using a new hub cluster. To return to your initial hub cluster, complete the steps in xref:../backup_restore/backup_restore_hub_return.adoc#restore-hub-return-primary[Return to the primary hub cluster].

* *Important:* To prevent managed clusters from switching back and forth between the old and new hub clusters, stop the initial hub cluster before running the restore operation and the new cluster becomes the active hub cluster. To keep the initial hub cluster active during or after the restore operation, complete the steps in xref:../backup_restore/backup_active_restore_prepare.adoc#active-restore-prepare[Prepare the primary hub cluster].

.Procedure

* Before running the restore operation on a new hub cluster, you need to manually configure the hub cluster and install the same operators as on the initial hub cluster. You must install the {acm-short} operator in the same namespace as the initial hub cluster, create the _DataProtectionApplication_ resource, and then connect to the same storage location where the initial hub cluster previously backed up data.
+
*Note:* Use the same configuration as on the initial hub cluster for the `MultiClusterHub` resource created by the {acm-short} operator, including any changes to the `MultiClusterEngine` resource.
+
For example, if the initial hub cluster has any other operators installed, such as {aap-short}, {gitops}, `cert-manager`, you have to install them before running the restore operation. This ensures that the new hub cluster is configured in the same way as the initial hub cluster.

.Additional resources

* xref:../backup_restore/backup_restore_newer_version.adoc#run-restore-operation[Run a restore operation on a hub cluster with a newer version]
