[#restore-data-initial-hub]
= Restoring data to the initial hub cluster

After you run a hub cluster disaster recovery simulation, you can restore your data to the initial hub cluster, then use it as your primary hub cluster.

When you conduct a disaster recovery operation test, you simulate a primary hub cluster failure and restore its data to a new hub cluster, verifying that your backup and restore process works. After your disaster recovery test simulation completes, return to the primary hub cluster and make it the active hub cluster that manages the cluster fleet.

Complete the following sections to restore your data to the initial hub cluster after running a disaster recovery simulation.

[#prepare-primary-hub]
== Preparing the primary hub cluster 

To prepare the primary hub cluster to stay active during the restore process, complete the following task, xref:../backup_restore/backup_active_restore.adoc#keep-hub-active-restore[Running the restore operation while the primary hub cluster is active]. 

[#making-active-hub]
== Making the new hub cluster the active hub cluster  

To begin the simulation, you must make the new hub cluster the active hub cluster by completing the following steps:

. Run the restore operation on the new hub cluster to make it the active hub cluster.
. To verify that the managed clusters are now connected to the new hub cluster, check the status of the managed clusters from the cluster console. 
. Run your disaster recovery simulation tests on the new hub cluster.

[#returning-primary-hub]
== Returning to the primary hub cluster 

After your disaster recovery tests finishes, complete the following steps to  return to the primary hub cluster and make it the active hub cluster that manages the cluster fleet. 

. Create a backup on the restore hub cluster by applying the following resource: 

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
metadata:
 name: schedule-acm-msa
 namespace: open-cluster-management-backup
spec:
 veleroSchedule: "0 */1 * * *"
 veleroTtl: 120h
 useManagedServiceAccount: true
 paused: false
----

. Make sure the {acm-short} backups are generated and have the `Completed` status.
. Pause the backup schedule by setting the `paused=true` property on the `schedule-acm-msa BackupSchedule` resource.
. Restore all the resources from the secondary hub cluster backup by applying the following restore resource: 

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
 name: restore-acm
 namespace: open-cluster-management-backup
spec:
 cleanupBeforeRestore: CleanupRestored
 veleroManagedClustersBackupName: latest
 veleroCredentialsBackupName: latest
 veleroResourcesBackupName: latest
----
+
*Note:* When you set the `cleanupBeforeRestore` property to `CleanupRestored`, a cleanup operation runs after all resources are restored. This cleanup operation removes any hub resource that is not part of the restored backup. 

[#enabling-backup-schedule]
== Enabling the backup schedule on the primary hub cluster 

Now that the initial hub cluster is the primary hub cluster again, enable the backup schedule on the primary hub cluster by completing the following steps:

. Go to the primary hub cluster.
. Apply the following `BackupSchedule` resource: 

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
metadata:
 name: schedule-acm-msa
 namespace: open-cluster-management-backup
spec:
 veleroSchedule: "0 */1 * * *"
 veleroTtl: 120h
 useManagedServiceAccount: true
 paused: false
----
+
*Note:* The second hub cluster can be used again as the secondary hub cluster in the `active-passive` configuration.