[#config-velero-res-limit]
= Configuring Velero resource requests and limits
//check this file for limits
 
When you install the backup and restore operator, a `DataProtectionApplication` resource is created to manage the Velero deployment on the hub cluster. By default,

The Velero pod is set to the default CPU and memory limits. If your cluster backs up a large number of resources, you might need to update the Velero resource requests and limits. If you do not update the values, the Velero pod might fail due to an out-of-memory error.
 
== Increasing resources to support more clusters

. Update the `DataProtectionApplication` resource and add the following `resourceAllocations` template. The following example works with 2000 clusters:

+
[source,yaml]
----
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero
  namespace: open-cluster-management-backup
spec:
...
  configuration:
...
    velero:
      podConfig:
        resourceAllocations:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 256Mi
----

== Additional resources

- Refer to the link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.17/html/backup_and_restore/oadp-application-backup-and-restore#default-velero-cloud-provider-plugins[Default Velero cloud provider plugins] topic in the {ocp} documentation to find out more about the `DataProtectionApplication` parameters.

- Refer to the link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/backup_and_restore/index#cpu-and-memory-requirement-for-configurations[CPU and memory requirement for configurations] topic in the {ocp-short} documentation for more details about the backup and restore CPU and memory requirements based on cluster usage.
