[#backup-existing-hub]
= Using an existing hub cluster as a restore hub cluster

If you use a restore hub as a cluster with resources that a user created before the restore operation, you must understand the following constraints: 

* The existing managed cluster can be detached during the restore process.
* The restore hub cluster can have more resources than the backup hub cluster.

[#existing-clusters-detached]
== Existing managed clusters can be detached during the restore process

If the hub you plan to use for the restore operation already manages some clusters, expect the following outcomes when you run a restore operation with the `cleanupBeforeRestore` option set to `CleanupRestored`:  

* If an earlier backup created the `ManagedCluster` resources, then the `velero.io/backup-name: backupName` label annotation is set. Therefore, if you run a restore operation and use the `cleanupBeforeRestore=CleanupRestored` option, the clusters are detached and the data is cleaned up on the managed clusters. This only occurs if the backup managed clusters resources are not part of the restored backup.
* If the `ManagedCluster` resource does not have the `velero.io/backup-name: backupName` label annotation, and the user runs a restore operation with the `cleanupBeforeRestore` option set to `CleanupRestored`, then these managed cluster resources are not cleaned up since they were not created by an earlier backup. Therefore, these managed clusters continue to be managed by this hub, even though these clusters were not managed by the backup hub, and this hub does not match the content of the backup hub.

[#restore-hub-resources]
== Restore hub can have more resources than the backup hub

If your restore operation uses a hub with earlier created user data, then the restore operation results in a hub that does not have the exact content as the primary hub. The user data includes the following resources: `policy`, `application`, `credential`, or any custom resource defined by the user. A restore operation with the `cleanupBeforeRestore` option set to `CleanupRestored` is not going to clean up these resources because they were created by the users and not created by an earlier backup. 

If you intend to use an existing hub for a restore hub configuration and expect that the hub has the same content as the backup hub after the restore is completed, tag any resource that would be part of a hub backup with the `velero.io/backup-name: backupName` label annotation. Tagging the resources with the Velero annotation marks them as being generated by an earlier restore.

[#prerequisite-resources]
=== Prerequisite 

* On the restore hub, update the `DataProtectionApplication` resource and set the storage location to a new, temporary location. You do not want to create the backup used to tag the restore hub resources in the same storage location with the backup hub. Before you tag the resources, make sure you set the storage location to a different location than the backup hub.

[#tagging-resources]
=== Tagging resources 

To tag user created resources on the restore hub with the `velero.io/backup-name: backupName` label, complete the following steps: 

. On the restore hub, create a `BackupSchedule` resource to generate a backup that has all these hub resources by using the following YAML:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
metadata:
 name: schedule-acm-msa
 namespace: open-cluster-management-backup
spec:
 veleroSchedule: 0 */1 * * *
 veleroTtl: 120h
 useManagedServiceAccount: true
 paused: false
----

. Verify that the `BackupSchedule` has created the hub backup resources and their status is `Completed`.
. Pause the `BackupSchedule` schedule and stop generating backups by setting the property `paused=true` on the `schedule-acm-msa BackupSchedule`.
.. *Note:* You cannot run a restore operation on the hub cluster if the `BackupSchedule` is enabled, so you pause the `BackupSchedule` to run a restore operation.
. Run a restore operation by using the following yaml: 

+
[source,yaml]
----
kind: Restore
metadata:
name: restore-acm
namespace: open-cluster-management-backup
spec:
cleanupBeforeRestore: None
veleroManagedClustersBackupName: latest
veleroCredentialsBackupName: latest
veleroResourcesBackupName: latest
excludedResources: # exclude managed cluster resources
 - ManagedCluster
excludedNamespaces: # exclude managed cluster namespaces
  - managed-cls-1
  - managed-cls-2
  - managed-cls-n
----

After you complete these steps, the operator goes over each resource which is part of the hub backup and tags it with the `velero.io/backup-name: backupName` , where `backupName` is the name of the latest backup. 

[#understanding-resources]
=== Understanding the tagged resources 

After tagging the resources, you can use the hub as a restore cluster. Update the `DataProtectionApplication` storage location to point to the storage location of the backup hub so you can run a restore operation using the hub backup resources. All the restore hub resources are tagged now with the `velero.io/backup-name label`, so they show as being generated by an earlier restore. Therefore, any restore operation that you run on this hub cluster using the `cleanupBeforeRestore` option set to `CleanupRestored` cleans up the data that is not part of the restored backup.

*Important:*

* Do not use the restore operation with the `cleanupBeforeRestore` option set to `CleanupRestored` if you have managed clusters on this hub created by an earlier restore operation which are not part of the restored backup. Otherwise, they get detached from the hub and managed cluster resources deleted. 
* Having this constraint, you could use an existing hub as a restore hub in the following situations:
** There are no managed clusters on this restore hub. 
** There are managed clusters on the restore hub and you do not expect the restore hub user data to be the same with the one available with the restored backup.
** The names of the managed clusters from the restore hub do not collide with any of the managed cluster names from the backup hub.


