:_mod-docs-content-type: PROCEDURE

[#dr4hub-install-dpa]
= Create a _DataProtectionApplication_ resource

[role="_abstract"]
Create an instance of the `DataProtectionApplication` resource for your active and passive hub clusters.

.Procedure

. From the {ocp} console, select *Operators* > *Installed Operators*.
. Click `Create instance` within the _DataProtectionApplication_ dialog box.
. Create the Velero instance by selecting configurations using the {ocp-short} console or by using a YAML file as mentioned in the `DataProtectionApplication` example.
. Set the `DataProtectionApplication` namespace to `open-cluster-management-backup`.
. Set the specification (`spec:`) values appropriately for the `DataProtectionApplication` resource. Then click *Create*.

+
If you intend on using the default backup storage location, set the following value, `default: true` in the `backupStorageLocations` section. View the following `DataProtectionApplication` resource sample:

+
[source,yaml]
----
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-sample
spec:
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - aws
    restic:
      enable: true
  backupLocations:
    - name: default
      velero:
        provider: aws
        default: true
        objectStorage:
          bucket: my-bucket
          prefix: my-prefix
        config:
          region: us-east-1
          profile: "default"
        credential:
          name: cloud-credentials
          key: cloud
  snapshotLocations:
    - name: default
      velero:
        provider: aws
        config:
          region: us-west-2
          profile: "default"
----
