[#managed-cluster-activation-data]
= Restoring managed cluster activation data

Managed cluster activation data or other activation data, is a backup resource. When the activation data is restored on a new hub cluster, managed clusters are then being actively managed by the hub cluster where the restore is run. Activation data resources are stored by the managed clusters backup and by the resource-generic backup, when you use the `cluster.open-cluster-management.io/backup: cluster-activation` label. 

See _Scheduling and restoring backups_ to learn how you can use the operator.

[#preparing-clusters-activation-data]
== Preparing clusters before restoring activation data

Before you restore the activation data on the passive hub cluster, shut down the previous hub cluster where the backup was created. If the primary hub cluster is still running, it attempts to reconnect with the managed clusters that are no longer available, based on the reconciliation procedure running on this hub cluster.

//is there a command that the user should run to shut the cluster down? Is there a button they should select from the console? 

[#dr4hub-activation-resources]
== Additional resources

- See xref:../backup_restore/backup_schedule.adoc#using-backup-restore[Scheduling and restoring backups].

- See link:../../install/adv_config_install.adoc#disable-hub-self-management[_disableHubSelfManagement_]
