:_mod-docs-content-type: REFERENCE

[#backup-schedule-status]
= BackupSchedule status

[role="_abstract"]
Review the descriptions of the various `BackupSchedule` statuses.

`Enabled`::
The `BackupSchedule` is running and generating backups.

`FailedValidation`::
An error prevents the `BackupSchedule` from running. As a result, the `BackupSchedule` is not generating backups, but instead, it is reconciling and waiting for the error to be fixed. Look at the `BackupSchedule` status section for the reason why the resource is not valid. After the error is addressed, the `BackupSchedule` status changes to `Enabled`, and the resource starts generating backups.

`BackupCollision`::
The `BackupSchedule` is not generating backups. Look at the `BackupSchedule` status section for the reason why the resource status is `BackupCollision`. To start creating backups, delete this resource and create a new one.

`Paused`::
If you paused the {acm-short} backup schedule by using the `BackupSchedule.paused` property, the Velero schedules created by the `BackupSchedule` resources get deleted and no new hub backups get generated. If you update the `BackupSchedule.paused` property to `False`, the `BackupSchedule` resource status returns to `Enabled` and the Velero schedules get recreated.

.Additional resources

* xref:../backup_restore/backup_schedule_collisions.adoc#understand-backup-collision[Understanding backup collisions]
* xref:../backup_restore/backup_schedule_prevent_collisions.adoc#prevent-backup-collision[Preventing backup collisions]
