:_mod-docs-content-type: PROCEDURE

[#dr4hub-install-enable-backup-operator]
= Enable the backup operator for your hub clusters

[role="_abstract"]
Enable the backup operator for your active and passive hub clusters. The cluster backup and restore operator can be enabled by updating the `MultiClusterHub` resource. When the operator is enabled, the operator resources are installed.

If the `MultiClusterHub` resource is already created, you can install or uninstall the cluster backup operator by editing the `MultiClusterHub` resource. Set `cluster-backup` to `false`, if you want to uninstall the cluster backup operator.

.Procedure

. Enable the cluster backup and restore operator, `cluster-backup`, by updating the `MultiClusterHub` resource and setting the `cluster-backup` parameter to `true`. Your `MultiClusterHub` resource might resemble following example:

+
[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: High
  enableClusterBackup: false
  imagePullSecret: multiclusterhub-operator-pull-secret
  ingress:
    sslCiphers:
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
  overrides:
    components:
      - enabled: true
        name: multiclusterhub-repo
      - enabled: true
        name: search
      - enabled: true
        name: management-ingress
      - enabled: true
        name: console
      - enabled: true
        name: insights
      - enabled: true
        name: grc
      - enabled: true
        name: cluster-lifecycle
      - enabled: true
        name: volsync
      - enabled: true
        name: multicluster-engine
      - enabled: true
        name: cluster-backup
  separateCertificateManagement: false
----

.. For the {oadp} (OADP) operator installation, the automatic installation is the default. In this default situation, the OADP operator automatically installs in the same namespace where you enabled the `cluster-backup` component.
.. In certain cases, you must manually install the OADP operator. If your hub cluster runs on AWS cloud and uses AWS Security Token Service (STS) authentication, you must manually install the OADP operator before you enable the backup component. The STS configurations require an Amazon Resource Name (ARN) token that you must configure during the OADP operator installation.
. Ensure that the restore hub cluster uses the same {acm-short} version that the backup hub cluster uses. You cannot restore a backup on a hub cluster with a version earlier than the one used by the backup hub cluster.
. Manually configure the restore hub cluster by completing the following steps:
.. Install all operators that are installed on the active hub cluster and in the same namespace as the active hub cluster.
.. Verify that the new hub cluster is configured the same way as the backup hub cluster.
.. Use the same namespace name as the backup hub cluster when you install the backup and restore operator and any operators that are configured on the backup hub cluster.
. Create the `DataProtectionApplication` resource on the passive hub cluster by completing the following steps:
.. Create the `DataProtectionApplication` resource on both the active and passive hub cluster.
.. For the restore hub cluster, when you create the `DataProtectionApplication` resource, use the same storage location as the backup hub.

.Additional resources

* link:https://velero.io/[Velero]

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/backup_and_restore/oadp-application-backup-and-restore[AWS S3 compatible backup storage providers]

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/backup_and_restore/oadp-application-backup-and-restore[_DataProtectionApplication_]
