:_mod-docs-content-type: CONCEPT

[#config-hcp-backup]
= Backup and restore for {hcp} overview

[role="_abstract"]
When using {acm-short} to manage hosted clusters with {mce-short} hosting clusters, you can back up and restore the management capability of both the {acm-short} hub cluster and the hosted clusters.

See the _{ocp-short} {hcp} disaster recovery_ documentation to help you install the {oadp} operator, create {oadp} resources, and use the {oadp} to backup and restore hosted clusters. Then, note the differences in the {acm-short} process.

For {acm-short}, enable backup and restore and use the {oadp} operator that is installed by the backup and restore component.

{oadp} resources, such as `DataProtectionApplication`, `BackupSchedule`, `Backup` and `Restore` for your hosted clusters, are created in the `open-cluster-management-backup` namespace.

.Additional resources

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/hosted_control_planes/high-availability-for-hosted-control-planes[OpenShift Hosted Control Plane Disaster Recovery documentation]

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/hosted_control_planes/high-availability-for-hosted-control-planes[Overview of Hosted Cluster backup and restore process]

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/hosted_control_planes/high-availability-for-hosted-control-planes#hcp-disaster-recovery-oadp[Disaster recovery for a hosted cluster by using OADP]

* xref:../backup_restore/backup_hcp_scope.adoc[Backup scope for hosted clusters]

* xref:../backup_restore/backup_restore_hcp_mngmt.adoc[Restoring {hcp} management configuration]
