:_mod-docs-content-type: CONCEPT

[#understanding-backup-collisions]
= Backup collisions

[role="_abstract"]
Backup collisions might occur if the hub cluster changes status from passive to primary hub cluster, or from primary to passive, and different hub clusters back up data at the same storage location. 

As a result, the latest backups are generated by a hub cluster that is no longer set as the primary hub cluster. This hub cluster still produces backups because the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled.

When you run a restore operation in a controlled environment, such as a disaster recovery test operation, you can prevent a backup collision when you use the `BackupSchedule` `paused` property on the backup hub cluster. Before you restore the resources on the new hub cluster, pause the `BackupSchedule` resource on the backup hub by setting the `paused=true` property on the `BackupSchedule` resource.

See the following list to learn about scenarios that might cause a backup collision:

* The primary hub cluster fails unexpectedly, which is caused by the following conditions:
** Communication from the primary hub cluster to the initial hub cluster fails.
** The initial hub cluster backup data is restored on a secondary hub cluster, called secondary hub cluster.
** The administrator creates the `BackupSchedule.cluster.open-cluster-management.io` resource on the secondary hub cluster, which is now the primary hub cluster and generates backup data to the common storage location.
** The initial hub cluster unexpectedly starts working again.
+
Since the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled on the initial hub cluster, the initial hub cluster resumes writing backups to the same storage location as the secondary hub cluster. Both hub clusters are now writing backup data at the same storage location. Any hub cluster restoring the latest backups from this storage location might use the initial hub cluster data instead of the secondary hub cluster data.

* The administrator tests a disaster scenario by making the secondary hub cluster a primary hub cluster, which is caused by the following conditions:
** The initial hub cluster is stopped.
** The initial hub cluster backup data is restored on the secondary hub cluster.
** The administrator creates the `BackupSchedule.cluster.open-cluster-management.io` resource on the secondary hub cluster, which is now the primary hub cluster and generates backup data to the common storage location.
** After the disaster test is completed, the administrator reverts to the earlier state and makes the initial hub cluster the primary hub cluster again. 
** The initial hub cluster starts while the secondary hub cluster is still active.
+
Since the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled on the secondary hub cluster, it writes backups at the same storage location that corrupts the backup data. Any hub cluster that restores the latest backups from this location might use the secondary hub cluster data instead of the initial hub cluster data. In this scenario, stop the secondary hub cluster first or pause the `BackupSchedule.cluster.open-cluster-management.io` resource on the secondary hub cluster before you start the initial hub cluster to avoid the backup collision issue.

* The administrator tests a disaster scenario by making the secondary hub cluster a primary hub cluster, without stopping the initial hub cluster first, causing the following conditions: 
** The initial hub cluster is still running.
** The initial hub cluster backup data is restored on the secondary hub cluster, including managed clusters backup. Therefore, the secondary hub cluster is now the active cluster.
** Since the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled on the initial hub cluster, it writes backups at the same storage location which corrupts the backup data. For example, any hub cluster restoring the latest backups from this location might use the initial hub cluster data instead of the secondary hub cluster data. To avoid data corruption, the initial hub cluster `BackupSchedule` resource status automatically changes to `BackupCollision`. In this scenario, to avoid getting into this backup collision state, stop the initial hub cluster first or delete the `BackupSchedule.cluster.open-cluster-management.io` resource on the initial hub cluster before restoring managed clusters data on  the secondary hub cluster.

.Additional resources

* xref:../backup_restore/backup_schedule_prevent_collisions.adoc[Prevent backup collisions]