[#managed-cluster-activation-data]
= Restoring managed cluster activation data

Managed cluster activation data or other activation data, is a backup resource. When the activation data is restored on a new hub cluster, managed clusters are then being actively managed by the hub cluster where the restore is run. Activation data resources are stored by the managed clusters backup and by the resource-generic backup, when you use the `cluster.open-cluster-management.io/backup: cluster-activation` label. 

See _Scheduling and restoring backups_ to learn how you can use the operator.

[#preparing-clusters-activation-data]
== Preparing clusters before restoring activation data

Before restoring activation data on the new hub cluster, complete the following steps to avoid data corruption or cluster loss:

. Shut down the primary cluster.
+
Before you restore the activation data on the passive hub cluster, shut down the previous hub cluster where the backup was created. If the primary hub cluster is still running, it attempts to reconnect with the managed clusters that are no longer available, based on the reconciliation procedure running on this hub cluster.

. If you want to use an existing managed cluster as the restore hub, set `disableHubSelfManagement` to `true` in the `MultiClusterHub`.
+
For more information, see the _disableHubSelfManagement_ topic.
+
See the following example where `spec.disableHubSelfManagement` is set to `true`:
+
[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: <namespace>
spec:
  disableHubSelfManagement: true
----

*Note:* If the self managing option is not disabled on the restore hub cluster before the activation data is moved to the restore hub cluster, the `local-cluster` klusterlet and the klusterlet in the managed cluster namespace conflict. As a result, the restore hub cluster is managed by itself by using the managed cluster and by using the restored managed cluster. If you detach the managed cluster as part of the detach operation, the managed cluster receives a deprovision request, which results in restore hub cluster removal.

[#dr4hub-activation-resources]
== Additional resources

- See xref:../backup_restore/backup_schedule.adoc#using-backup-restore[Scheduling and restoring backups].

- See link:../../install/adv_config_install.adoc#disable-hub-self-management[_disableHubSelfManagement_]

- Return to <<managed-cluster-activation-data,Managed cluster activation data>>
