:_mod-docs-content-type: REFERENCE

[#backup-schedule-resource-groups]
= Backup resource groups

[role="_abstract"]
Resources are separately backed up in the following groups.

`Credentials` backup::
Backup file that stores Hive credentials, {acm-short}, and user-created credentials and ConfigMaps.

`Resources` backup::
Contains one backup for the {acm-short} resources and one for generic resources. These resources use the `cluster.open-cluster-management.io/backup` label.

`ManagedClusters` backup::
Contains only resources that activate the managed cluster connection to the hub cluster, where the backup is restored.

*Note:* The _resources backup_ file contains managed cluster-specific resources, but does not contain the subset of resources that connect managed clusters to the hub cluster. The resources that connect managed clusters are called activation resources and are contained in the managed clusters backup. When you restore backups only for the _credentials_ and _resources_ backup on a new hub cluster, the new hub cluster shows all managed clusters that are created by using the Hive API in a detached state. The managed clusters that are imported on the primary hub cluster by using the import operation appear only when the activation data is restored on the passive hub cluster. The managed clusters are still connected to the original hub cluster that created the backup files.

When the activation data is restored, only managed clusters created by using the Hive API are automatically connected with the new hub cluster. All other managed clusters appear in a _Pending_ state. You need to manually reattach them to the new cluster.
