:_mod-docs-content-type: REFERENCE

[#restore-backup-advanced]
= Advanced restore options

[role="_abstract"]
Use advanced restore options defined by the `velero.io.restore` specification to filter the resources that you restore.

There are advanced restore options that are defined by the `velero.io.restore` specification. You can use these advanced restore options to filter out resources that you want to restore.

For example, you can use the following YAML sample to restore resources only from the `vb-managed-cls-2` managed cluster namespace and to exclude the global `ManagedCluster` resources:

[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: restore-filter-sample
  namespace: open-cluster-management-backup
spec:
  cleanupBeforeRestore: None
  veleroCredentialsBackupName: latest
  veleroResourcesBackupName: latest
  veleroManagedClustersBackupName: latest
  excludedResources:
    - ManagedCluster
  includedNamespaces:
    - vb-managed-cls-2
----

If you want more options for the `velero.io.restore` specification when you create the {acm} restore resource, see the following restore filters:

[source,yaml]
----
spec:
  includedResources
  includedNamespaces
  excludedResources
  excludedNamespaces
  LabelSelector
  OrLabelSelector
----

*Note:* For any of the Velero restore filters, set the `cleanupBeforeRestore` field to `None` to prevent having to clean up hub cluster resources that are part of the restored backup, but are not being restored because of the applied filter.

.Additional resources

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/backup_and_restore/oadp-application-backup-and-restore[_DataProtectionApplication_]
* link:../../clusters/cluster_lifecycle/import_cli.adoc[Importing the cluster with the auto import secret]
