[#install-backup-and-restore]
= Installing the backup and restore operator

The cluster backup and restore operator is not installed automatically. Continue reading to learn how to install and enable the operator.

*Notes:*

- Custom resource definitons are cluster-scoped, so you cannot have two different versions of OADP or Velero installed on the same cluster. If you have two different versions, one version runs with the wrong custom resource definitions.

- If you did not enable the cluster backup and restore operator on the `MultiClusterHub` resource, the OADP Operator and Velero custom resource definition are still installed on the hub cluster. The `MultiClusterHub` resource reconciles the OADP and Velero custom resource definitions with the version that is used by the OADP Operator, which is installed when you enabled the cluster backup and restore operator. As a result, you cannot install another version of OADP or Velero on the hub cluster, unless your version uses the same custom resource definitions as the OADP Operator that is installed when you enabled the backup and restore operator.

- The backup component works with the OADP Operator that is installed in the component namespace. 

Velero is installed with the OADP Operator on the {product-title} hub cluster. It is used to backup and restore {product-title-short} hub cluster resources. 

For a list of supported storage providers for Velero, see _S3-Compatible object store providers_.

[#prerequisites-backup-restore]
== Prerequisites

You must meet the following prerequisites to enable and use the backup and restore operator.

=== Create the storage location secret

. Complete the steps for link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/backup_and_restore/oadp-application-backup-and-restore#oadp-creating-default-secret_installing-oadp-aws[Creating a default Secret] for the cloud storage where the backups are saved. You must create the secret resource in the OADP Operator namespace, which is located in the backup component namespace.

=== Enable backup operator

. From your {ocp} cluster, install the {product-title} operator version {product-version}.x. The `MultiClusterHub` resource is automatically created when you install {product-title-short}, and displays the following status: `Running`.
. The cluster backup and restore operator must be installed manually. Enable the cluster backup and restore operator (`cluster-backup`). Edit the `MultiClusterHub` resource by setting the `cluster-backup` parameter to `true`. This installs the OADP operator in the same namespace with the backup component.
. Before you run the restore operation on the passive hub cluster, manually configure the hub cluster and install all operators on the active hub cluster and in the same namespace as the active hub cluster. 
. Ensure that the {product-title-short} operator is installed in the same namespace as the initial hub cluster. Then create the `DataProtectionApplication` resource and connect to the same storage location where the initial hub cluster backed up data. 

=== Create a `DataProtectionApplication` resource

Complete the following steps to create an instance of the `DataProtectionApplication` resource:

. From the {ocp} console, select *Operators* > *Installed Operators*.
. Click `Create instance` under DataProtectionApplication.
. Create the Velero instance by selecting configurations using the {ocp-short) console or by using a YAML file as mentioned in the `DataProtectionApplication` example.
. Set the `DataProtectionApplication` namespace to `open-cluster-management-backup`.
. Set the specification (`spec:`) values appropriately for the `DataProtectionApplication` resource. Then click *Create*.
+
If you intend on using the default backup storage location, set the following value, `default: true` in the `backupStorageLocations` section. View the following `DataProtectionApplication` resource sample:
+
[source,yaml]
----
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-sample
spec:
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - aws
    restic:
      enable: true
  backupLocations:
    - name: default
      velero:
        provider: aws
        default: true
        objectStorage:
          bucket: my-bucket
          prefix: my-prefix
        config:
          region: us-east-1
          profile: "default"
        credential:
          name: cloud-credentials
          key: cloud
  snapshotLocations:
    - name: default
      velero:
        provider: aws
        config:
          region: us-west-2
          profile: "default"
----
+
See an example to create the _DataProtectionApplication_ resource.

** Before you run the restore operation, verify that other operators, such as {aap-short}, {ocp} GitOps, or certificate manager are installed. This ensures that the new hub cluster is configured the same way as the initial hub cluster.

** The passive hub cluster must use the same namespace names as the initial hub cluster when you install the backup and restore operator, and any other operators that are configured on the previous hub cluster.

=== For disconnected environments

Complete the following additional steps when you enable the backup and restore component with {ocp} in a disconnected environment:

. Update the `MultiClusterHub` resource with the follwing annotation to override the source from which the OADP operator is installed. Create the annotation before the `cluster-backup` component is enabled on the `MultiClusterHub` resource:
+
[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    installer.open-cluster-management.io/oadp-subscription-spec: '{"source": "redhat-operator-index"}'
----
+
. The `redhat-operator-index` is a custom name and represents the name of the `CatalogSource` resource that you define and use to access Red Hat OpenShift Operators in the disconnected environment. Run the following command to retrieve the `catalogsource`:
+
----
oc get catalogsource -A
----
+
The output might resemble the following:
+
----
NAMESPACE               NAME                         DISPLAY                       TYPE   PUBLISHER   AGE
openshift-marketplace   acm-custom-registry          Advanced Cluster Management   grpc   Red Hat     42h
openshift-marketplace   multiclusterengine-catalog   MultiCluster Engine           grpc   Red Hat     42h
openshift-marketplace   redhat-operator-index                                      grpc               42h
----

[#enabling-backup-restore]
== Enabling the backup and restore operator

The cluster backup and restore operator can be enabled when the `MultiClusterHub` resource is created for the first time. The `cluster-backup` parameter is set to `true`. When the operator is enabled, the operator resources are installed.

If the `MultiClusterHub` resource is already created, you can install or uninstall the cluster backup operator by editing the `MultiClusterHub` resource. Set `cluster-backup` to `false`, if you want to uninstall the cluster backup operator.

When the backup and restore operator is enabled, your `MultiClusterHub` resource might resemble the following YAML file:

[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
  kind: MultiClusterHub
  metadata:
    name: multiclusterhub
    namespace: open-cluster-management
  spec:
    availabilityConfig: High
    enableClusterBackup: false
    imagePullSecret: multiclusterhub-operator-pull-secret
    ingress:
      sslCiphers:
        - ECDHE-ECDSA-AES256-GCM-SHA384
        - ECDHE-RSA-AES256-GCM-SHA384
        - ECDHE-ECDSA-AES128-GCM-SHA256
        - ECDHE-RSA-AES128-GCM-SHA256
    overrides:
      components:
        - enabled: true
          name: multiclusterhub-repo
        - enabled: true
          name: search
        - enabled: true
          name: management-ingress
        - enabled: true
          name: console
        - enabled: true
          name: insights
        - enabled: true
          name: grc
        - enabled: true
          name: cluster-lifecycle
        - enabled: true
          name: volsync
        - enabled: true
          name: multicluster-engine
        - enabled: true
          name: cluster-backup
    separateCertificateManagement: false
----

[#dr4hub-install-resources]
== Additional resources

- See link:https://velero.io/[Velero].

- See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/backup_and_restore/oadp-application-backup-and-restore#oadp-s3-compatible-backup-storage-providers_about-installing-oadp[AWS S3 compatible backup storage providers] in the {ocp-short} documentation for a list of supported Velero storage providers.

- Learn more about the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/backup_and_restore/oadp-application-backup-and-restore#oadp-installing-dpa_installing-oadp-aws[_DataProtectionApplication_] resource.

- Return to <<install-backup-and-restore,Installing the backup and restore operator>>
