:_mod-docs-content-type: PROCEDURE

[#dr4hub-install-enable-operator]
= Enable the backup and restore operator

[role="_abstract"]
Enable or disable the cluster backup and restore operator on the `MultiClusterHub` resource.

The cluster backup and restore operator can be enabled when the `MultiClusterHub` resource is created for the first time. The `cluster-backup` parameter is set to `true`. When the operator is enabled, the operator resources are installed.

If the `MultiClusterHub` resource is already created, you can install or uninstall the cluster backup operator by editing the `MultiClusterHub` resource. Set `cluster-backup` to `false`, if you want to uninstall the cluster backup operator.

When the backup and restore operator is enabled, your `MultiClusterHub` resource might resemble the following YAML file:

[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
  kind: MultiClusterHub
  metadata:
    name: multiclusterhub
    namespace: open-cluster-management
  spec:
    availabilityConfig: High
    enableClusterBackup: false
    imagePullSecret: multiclusterhub-operator-pull-secret
    ingress:
      sslCiphers:
        - ECDHE-ECDSA-AES256-GCM-SHA384
        - ECDHE-RSA-AES256-GCM-SHA384
        - ECDHE-ECDSA-AES128-GCM-SHA256
        - ECDHE-RSA-AES128-GCM-SHA256
    overrides:
      components:
        - enabled: true
          name: multiclusterhub-repo
        - enabled: true
          name: search
        - enabled: true
          name: management-ingress
        - enabled: true
          name: console
        - enabled: true
          name: insights
        - enabled: true
          name: grc
        - enabled: true
          name: cluster-lifecycle
        - enabled: true
          name: volsync
        - enabled: true
          name: multicluster-engine
        - enabled: true
          name: cluster-backup
    separateCertificateManagement: false
----

.Additional resources

* link:https://velero.io/[Velero]

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/backup_and_restore/oadp-application-backup-and-restore[AWS S3 compatible backup storage providers]

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/backup_and_restore/oadp-application-backup-and-restore[_DataProtectionApplication_]
