:_mod-docs-content-type: PROCEDURE

[#using-backup-restore]
= Scheduling backups

[role="_abstract"]
By scheduling a backup, you help ensure your data remains protected and accessible.

.Procedure

. Run the following command to create a `backupschedule.cluster.open-cluster-management.io` resource:

+
[source,bash]
----
oc create -f cluster_v1beta1_backupschedule.yaml
----
+
Your `cluster_v1beta1_backupschedule.yaml` resource might resemble the following file:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
metadata:
  name: schedule-acm
  namespace: open-cluster-management-backup
spec:
  veleroSchedule: 0 */2 * * *
  veleroTtl: 120h
  useManagedServiceAccount: true
  paused: false
----
+
* The `veleroSchedule` is a required property and defines a cron job for scheduling the backups. In the earlier example, it creates a backup every 2 hours.
* The `veleroTtl` is an optional property and defines the expiration time for a scheduled backup resource. If not specified, the maximum default value set by Velero is used, which is `720h`. It deletes scheduled backups after `120h`. 
* The `useManagedServiceAccount` is an optional property which can enable the automatic import feature, importing clusters in a restore operation. If you set it to `true`, it enables the automatic import feature, importing clusters in a restore operation.
* The `paused` is an optional property which can pause the backup schedule. If you set it to `true`, it pauses the backup schedule, deleting all Velero schedules created by this resource. 

. Check the status of your `backupschedule.cluster.open-cluster-management.io` resource, which displays the definition for the three `schedule.velero.io` resources. Run the following command:

+
[source,bash]
----
oc get BackupSchedule -n open-cluster-management-backup
----

. As a reminder, the restore operation is run on a different hub cluster for restore scenarios. To initiate a restore operation, create a `restore.cluster.open-cluster-management.io` resource on the hub cluster where you want to restore backups.
+
*Note:* When you restore a backup on a new hub cluster, make sure that you shut down the previous hub cluster where the backup was created. If it is running, the previous hub cluster tries to reimport the managed clusters as soon as the managed cluster reconciliation finds that the managed clusters are no longer available.

. View the list of scheduled resources. Run the following command:

+
[source,bash]
----
oc get schedules -A | grep acm
----
+
*Note:* Resources are backed up separately in the `Credentials`, `Resources`, and `ManagedClusters` groups.

.Additional resources

* xref:../backup_restore/backup_schedule_resource_groups.adoc[Backup resource groups]
* xref:../backup_restore/backup_schedule_status.adoc[BackupSchedule status]
* xref:../backup_restore/backup_schedule_collisions.adoc[Backup collisions]
* xref:../backup_restore/backup_schedule_prevent_collisions.adoc[Preventing backup collisions]
* xref:../backup_restore/backup_restore.adoc[Restoring a backup]
* xref:../backup_restore/backup_intro.adoc[Backup and restore] 
