:_mod-docs-content-type: PROCEDURE

[#tagging-resources]
= Tagging user resources with the backup label 

[role="_abstract"]
When you use an existing hub cluster for a restore hub cluster configuration, decide what user-created resource that you want to include in the hub cluster, then tag that resource with the `velero.io/backup-name: backupName` label. If you tag these resources with the Velero annotation, it looks like the resources were generated by an earlier restore. 

Because of the Velero annotation,  when you run a hub restore operation and set the `cleanupBeforeRestore` option to `CleanupRestored` on the restore resource, user resources that are not part of your current restored backup would get cleaned up. As a result, you can restore hub data on an existing cluster and produce a cluster that is the same as the initial hub.
 
[#prerequisite-resources]
.Prerequisites

* Review the scenarios of using an existing hub cluster as a restore hub cluster with resources that you created before the restore operation. See xref:../backup_restore/use_existing_hub_cluster.adoc#using-existing-hub[Scenarios when using an existing hub cluster as a restore hub cluster].
* On the restore hub cluster, update the `DataProtectionApplication` resource and set the storage location to a new, temporary location. You do not want to create the backup used to tag the restore hub cluster resources in the same storage location with the backup hub cluster. 
* Before you tag the resources, make sure you set the storage location to a different location than the backup hub cluster.

.Procedure

. Tag the resources with the Velero label. See xref:../backup_restore/tag_resources_velero.adoc#tagging-resources-velero[Tagging resources with the velero label].
