:_mod-docs-content-type: REFERENCE

[#siteconfig-manifest-order]
= Customization of the manifests order

[role="_abstract"]
The `siteconfig.open-cluster-management.io/sync-wave` annotation controls the order in which manifests are created, updated, and deleted. The annotation takes an integer as a _wave_; you can add one or several manifests to a single wave, and the default value is `0` if you do not specify a value. The {sco} reconciles the manifests in ascending order when creating or updating resources and deletes resources in descending order.

In the following example, if the {sco} creates or updates the manifests, the `AgentClusterInstall` and `ClusterDeployment` custom resources are reconciled in the first wave, while `KlusterletAddonConfig` and `ManagedCluster` custom resources are reconciled in the third wave:

[source,yaml]
----
apiVersion: v1
data:
  AgentClusterInstall: |-
    ...
        siteconfig.open-cluster-management.io/sync-wave: "1"
    ...
  ClusterDeployment: |-
    ...
        siteconfig.open-cluster-management.io/sync-wave: "1"
    ...
  InfraEnv: |-
    ...
        siteconfig.open-cluster-management.io/sync-wave: "2"
    ...
  KlusterletAddonConfig: |-
    ...
        siteconfig.open-cluster-management.io/sync-wave: "3"
    ...
  ManagedCluster: |-
    ...
        siteconfig.open-cluster-management.io/sync-wave: "3"
    ...
kind: ConfigMap
metadata:
  name: assisted-installer-templates
  namespace: example-namespace
----

If the {sco} deletes the resources, `KlusterletAddonConfig` and `ManagedCluster` custom resources are the first to be deleted, while the `AgentClusterInstall` and `ClusterDeployment` custom resources are the last.

.Additional resources

* xref:../siteconfig/siteconfig_installation_templates.adoc#siteconfig-templates[Installation templates]
