:_mod-docs-content-type: PROCEDURE

[#initiate-ibbf-reinstallation]
= Initiate the Image-Based Break/Fix cluster reinstallation

[role="_abstract"]
Initiate the Image-Based Break/Fix cluster reinstallation by updating the `ClusterInstance` resource.

*Required access:* Cluster administrator

.Prerequisites

* The cluster is a {sno} cluster installed using the Image Based Install provisioning method.
* The faulty hardware is replaced with a new node with identical specifications.

.Procedure

To initiate the Image-Based Break/Fix cluster reinstallation, update the `ClusterInstance` resource by setting the `spec.reinstall.generation` field and updating the `spec.nodes` object with the changed hardware information.

. Modify the `spec.reinstall.generation` field and update the `spec.nodes` object in the `ClusterInstance` resource with the new node details:

+
[source,yaml]
----
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: `ClusterInstance`
metadata:
  name: clusterinstance-example
  namespace: some-namespace
spec:
  ...
  reinstall:
    generation: "unique-generation-string"
    preservationMode: "ClusterIdentity"
  nodes:
    - bmcAddress: <new-node-bmcAddress>
      bootMACAddress: <new-node-bootMACAddress>
      rootDeviceHints: <new-node-rootDeviceHints>
      nodeNetwork:
        interfaces:
          macAddress: <new-node-macAddress>
          ...
      ...
----

. Apply the changes. See the following options:

.. If you are using {gitops-short} ZTP, push to your Git repository and wait for Argo CD to synchronize the changes.

.. To manually apply your changes, run the following command on the hub cluster:

+
[source,bash]
----
oc apply -f clusterinstance-example.yaml
----
