[#scale-out-worker-nodes]
= Scaling out a {sno} cluster with the {sco}

Scale out your managed cluster that was installed by the {sco}. You can scale out your cluster by adding a worker node.

*Required access:* Cluster administrator

[#scale-out-preq]
== Prerequisites

* If using GitOps ZTP, you have configured your GitOps ZTP environment. To configure your environment, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/edge_computing/ztp-preparing-the-hub-cluster[Preparing the hub cluster for GitOps ZTP].
* You have the default installation templates. To get familiar with the default templates, see xref:../siteconfig/siteconfig_installation_templates.adoc#default-templates[Default set of templates].
* You have installed your cluster with the {sco}. To install a cluster with the {sco}, see xref:../siteconfig/siteconfig_install_clusters.adoc#install-clusters[Installing {sno} clusters with the {sco}].
* You have set the `spec.clusterType` to `"SNO"`.

[#scale-out-annotation]
== Adding a worker node

Add a worker node by updating your `ClusterInstance` custom resource that is used to provision your cluster.

Complete the following steps to add a worker node to the managed cluster:

. Define a new node object in the existing `ClusterInstance` custom resource:

+
[source,yaml]
----
spec:
  ...
  nodes:
    - hostName: "<host_name>"
      role: "worker"
      templateRefs:
        - name: ai-node-templates-v1
          namespace: rhacm
      bmcAddress: "<bmc_address>"
      bmcCredentialsName:
        name: "<bmc_credentials_name>"
      bootMACAddress: "<boot_mac_address>"
...
----

. Apply the changes. See the following options:

.. If you are using {acm-short} without {gitops}, run the following command on the hub cluster:

+
[source,terminal]
----
oc apply -f <clusterinstance>.yaml
----

.. If you are using GitOps ZTP, push to your Git repository and wait for Argo CD to synchronize the changes.

. Verify that a new `BareMetalHost` resource is added by running the following command on the hub cluster:

+
[source,terminal]
----
oc get bmh -n <clusterinstance_namespace> --watch --kubeconfig <hub_cluster_kubeconfig_filename>
----

+
See the following example output:

+
[source,terminal]
----
NAME                        STATE          CONSUMER   ONLINE   ERROR   AGE
master-node1.example.com    provisioned               true             81m
worker-node2.example.com    provisioning              true             44m
----

. Verify that a new `Agent` resource is added by running the following command on the hub cluster:

+
[source,terminal]
----
oc get agents -n <clusterinstance_namespace> --kubeconfig <hub_cluster_kubeconfig_filename>
----

+
See the following example output:

+
[source,terminal]
----
NAME                       CLUSTER                   APPROVED    ROLE     STAGE
master-node1.example.com   <managed_cluster_name>    true        master   Done
master-node2.example.com   <managed_cluster_name>    true        master   Done
master-node3.example.com   <managed_cluster_name>    true        master   Done
worker-node1.example.com   <managed_cluster_name>    false       worker 
worker-node2.example.com   <managed_cluster_name>    true        worker   Starting installation
worker-node2.example.com   <managed_cluster_name>    true        worker   Installing
worker-node2.example.com   <managed_cluster_name>    true        worker   Writing image to disk
worker-node2.example.com   <managed_cluster_name>    true        worker   Waiting for control plane
worker-node2.example.com   <managed_cluster_name>    true        worker   Rebooting
worker-node2.example.com   <managed_cluster_name>    true        worker   Joined
worker-node2.example.com   <managed_cluster_name>    true        worker   Done
----

. Verify that a new `Node` resource is added by running the following command on the managed cluster:

+
[source,terminal]
----
oc get nodes --kubeconfig <managed_cluster_kubeconfig_filename>
----

+
See the following example output:

+
[source,terminal]
----
NAME                       STATUS    ROLES                  AGE   VERSION
worker-node2.example.com   Ready     worker                 1h    v1.30.5
worker-node1.example.com   Ready     worker                 19h   v1.30.5
master-node1.example.com   Ready     control-plane,master   19h   v1.30.5
master-node2.example.com   Ready     control-plane,master   19h   v1.30.5
master-node3.example.com   Ready     control-plane,master   19h   v1.30.5
----