:_mod-docs-content-type: CONCEPT

[#ibbf-hardware-replacement]
= Hardware replacement with Image-Based Break/Fix for {sno} (Technology Preview)

[role="_abstract"]
The Image-Based Break/Fix feature utilizes the cluster reinstallation mechanism of the {sco} to simplify {sno} hardware replacement. The feature minimizes downtime by preserving the original identity of the cluster. The Image-Based Break/Fix feature retains critical cluster details, including identifiers, cryptographic keys, such as `kubeconfig`, and authentication credentials, which enables the replacement node to seamlessly assume the identity of the failed hardware.

Designed for identical hardware replacements in {sno} clusters installed using the Image Based Install method, Image-Based Break/Fix introduces a GitOps-compatible, declarative API. Users can initiate hardware replacement with a single Git commit. Powered by the {sco} and {ibio}, Image-Based Break/Fix enables cluster redeployment using the existing `ClusterInstance` custom resource.

With Image-Based Break/Fix, {ocp-short} users gain a resilient, automated, and GitOps-native solution for quickly restoring {sno} clusters after hardware failures.

The Image-Based Break/Fix workflow is similar to the cluster reinstallation workflow with certain differences.
To familiarize yourself with the differences in the workflows, see the high-level overview of the Image-Based Break/Fix cluster reinstallation workflow:

* The {sco} reinstallation service is enabled.
* A cluster reinstallation is initiated.
* The `spec.reinstall.preservationMode` is set to `"ClusterIdentity"`.
* The `spec.nodes` object is updated with the changed hardware information.
* *Note*: The {ibio} automatically labels cluster identity resources.
* The reinstallation progress is monitored.
* During cluster provisioning, the operators consuming the installation manifests provision the cluster using the newly generated manifests.
* *Note*: The {ibio} detects the preserved cluster identity data and incorporates it into the configuration ISO image.
* The cluster is verified as provisioned and available.
* The `kubeconfig` that is associated with the failed hardware is used to access the reinstalled spoke cluster. See _Cluster reinstallation with the {sco} (Technology Preview)_.

.Additional resources

* xref:../siteconfig/siteconfig_cluster_reinstallation.adoc#cluster-reinstallation[Cluster reinstallation with the {sco} (Technology Preview)]
* xref:../siteconfig/siteconfig_ibbf_initiate.adoc#initiate-ibbf-reinstallation[Initiate the Image-Based Break/Fix cluster reinstallation]
