[#siteconfig-intro]
= {sco}

The {sco} offers a template-driven cluster provisioning solution, which allows you to provision clusters with all available installation methods.

The {sco} introduces the unified `ClusterInstance` API, which is derived from the `SiteConfig` API of the `SiteConfig` generator kustomize plugin.

The `ClusterInstance` API decouples parameters that define a cluster from the manner in which the cluster is deployed.

This separation removes certain limitations that are presented by the `SiteConfig` kustomize plugin in the current link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/edge_computing/ztp-deploying-far-edge-sites[GitOps Zero Touch Provisioning (ZTP) flow], such as agent cluster installations and scalability constraints posed by ArgoCD.

Using the unified `ClusterInstance` API, the {sco} offers the following improvements:

Isolation:: Separates the cluster definition from the installation method. The `ClusterInstance` CR captures the cluster definition, while installation templates capture the cluster architecture and installation methods.

Unification:: The {sco} unifies both Git and non-Git workflows. You can apply the `ClusterInstance` CR directly on the hub cluster, or synchronize resources through a GitOps solution, such as ArgoCD.

Consistency:: Maintains a consistent API across all installation methods, whether using the {ai}, the Image Based Install Operator, or any other custom template-based approach.

Scalability:: Achieves greater scalability for each cluster than the `SiteConfig` kustomize plugin.

Flexibility:: Provides you with more power to deploy and install clusters by using custom templates.

Troubleshooting:: Offers insightful information regarding cluster deployment status and rendered manifests, significantly enhancing the troubleshooting experience.

For more information about the Image Based Install Operator and the Assisted Installer, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/edge_computing/image-based-installation-for-single-node-openshift[Image-based installations for {sno}] and link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/installing_an_on-premise_cluster_with_the_agent-based_installer/index[Installing an on-premise cluster using the Assisted Installer]

[#operator-flow]
== The {sco} flow

The {sco} dynamically generates installation manifests based on user-defined templates that are instantiated from the data in the `ClusterInstance` CR.

You can source the `ClusterInstance` CR from your Git repository through ArgoCD, or you can create it directly on the hub cluster manually or through external tools and workflows.

The following is a high-level overview of the process:

. You create one or more sets of installation templates on the hub cluster.
. You create a `ClusterInstance` CR that references those installation templates and supporting manifests.
. After the resources are created, the {sco} reconciles the `ClusterInstance` CR by populating the templated fields that are referenced in the CR.
. The {sco} validates and renders the installation manifests, then the Operator performs a dry run.
. If the dry run is successful, the manifests are created, then the underlying Operators consume and process the manifests.
. The installation begins.
. The {sco} continuously monitors for changes in the associated `ClusterDeployment` resource and updates the `ClusterInstance` CR's `status` field accordingly.

* xref:../siteconfig/siteconfig_installation_templates.adoc#installation-templates[Installation templates overview]
* xref:../siteconfig/siteconfig_enable.adoc#enable[Enabling the {sco}]
* xref:../siteconfig/siteconfig_install_clusters.adoc#install-clusters[Installing {sno} clusters with the {sco}]
* xref:../siteconfig/siteconfig_deprovision_clusters.adoc#deprovision-clusters[Deprovisioning {sno} clusters with the {sco}]
* xref:../siteconfig/siteconfig_create_custom_templates.adoc#create-custom-templates[Creating custom templates with the {sco}]