:_mod-docs-content-type: PROCEDURE

[#create-custom-templates]
= Create custom templates with the {sco}

[role="_abstract"]
Create user-defined templates that are not provided in the default set of templates. Complete the following steps to create a custom template.

*Required access:* Cluster administrator

.Procedure

. Create a YAML file named `my-custom-secret.yaml` that contains the cluster-level template in a `ConfigMap` object:

+
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-custom-secret
  namespace: rhacm
data:
  MySecret: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ .Spec.ClusterName }}-my-custom-secret-key"
      namespace: "clusters"
      annotations:
        siteconfig.open-cluster-management.io/sync-wave: "1"
    type: Opaque
    data:
      key: <key>
----
+
* The `siteconfig.open-cluster-management.io/sync-wave` annotation controls in which order manifests are created, updated, or deleted.

. Apply the custom template on the hub cluster by running the following command:

+
[source,terminal]
----
oc apply -f my-custom-secret.yaml
----

. Reference your template in the `ClusterInstance` custom resource named `clusterinstance-my-custom-secret.yaml`:

+
[source,yaml]
----
spec:
    ...
  templateRefs:
    - name: ai-cluster-templates-v1.yaml
      namespace: rhacm
    - name: my-custom-secret.yaml
      namespace: rhacm
    ...
----

. Apply the `ClusterInstance` custom resource by running the following command:

+
[source,terminal]
----
oc apply -f clusterinstance-my-custom-secret.yaml
----
