:_mod-docs-content-type: REFERENCE

[#siteconfig-templates]
= Installation templates

[role="_abstract"]
Installation templates are data-driven templates that are used to generate the set of installation artifacts. These templates follow the Golang `text/template` format, and are instantiated by using data from the `ClusterInstance` custom resource. This enables dynamic creation of installation manifests for each target cluster that has similar configurations, but with different values.

You can also create multiple sets based on the different installation methods or cluster topologies. The {sco} supports the following types of installation templates:

Cluster-level:: Templates that must reference only cluster-specific fields.
Node-level:: Templates that can reference both cluster-specific and node-specific fields.


* xref:../siteconfig/siteconfig_template_functions.adoc#template-functions[Template functions]
* xref:../siteconfig/siteconfig_default_templates.adoc#siteconfig-default-templates[Default set of templates]
* xref:../siteconfig/siteconfig_template_variables.adoc#siteconfig-template-variables[Special template variables]
* xref:../siteconfig/siteconfig_manifest_order.adoc#siteconfig-manifest-order[Customization of the manifests order]
* xref:../siteconfig/siteconfig_extra_annotations.adoc#siteconfig-annotations-labels[Configuration of additional annotations and labels]
* xref:../siteconfig/siteconfig_permissible_changes.adoc#siteconfig-permissible-changes[Permissible changes after provisioning]
