:_mod-docs-content-type: PROCEDURE

[#enable-cluster-reinstallation]
= Enable cluster reinstallation

[role="_abstract"]
Enable cluster reinstallation in the `siteconfig-operator-configuration` `ConfigMap` resource. You must explicitly enable cluster reinstallation in the `siteconfig-operator-configuration` `ConfigMap` resource, which you can complete well before initiating the process. By default, reinstallation is disabled.

*Required access:* Cluster administrator

.Procedure

. Set the `NAMESPACE` environment variable to match the namespace where the {sco} is installed. Run the following command:

+
[source,bash]
----
NAMESPACE=<namespace>
----

. Verify the current configuration by running the following command:

+
[source,bash]
----
oc get configmap siteconfig-operator-configuration -n $NAMESPACE -o yaml
----

+
*Example output:*

+
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
    name: siteconfig-operator-configuration
    namespace: <namespace>
data:
    allowReinstalls: false
    ...  
----
+
* The namespace where the {sco} is installed.
* Set to `true` to enable reinstallation.

+
*Note:* The operator continuously monitors the `siteconfig-operator-configuration` `ConfigMap` resource for changes.

. To enable cluster reinstallation, update the `ConfigMap` resource by setting the `data.allowReinstalls` field to `true`. Run the following command:

+
[source,bash]
----
oc patch configmap siteconfig-operator-configuration \  
    -n $NAMESPACE \  
    --type=json \  
    -p '[{"op": "replace", "path": "/data/allowReinstalls", "value": "true"}]'  
----

. Verify the update by running the following command:

+
[source,bash]
----
oc get configmap siteconfig-operator-configuration -n $NAMESPACE -o yaml  
----
