[#install-templates]
= Installation templates overview

installation templates are data-driven templates that are used to generate the set of installation artifacts.
These templates follow the Golang text and template format, and they are instantiated by using data from the `ClusterInstance` CR.

This enables dynamic creation of installation manifests for each target cluster that has similar configurations, but with different values.

You can also create multiple sets based on the different installation methods or cluster topologies.

There are two types of installation templates described in the following list:

Cluster-level:: Templates that must reference only cluster-specific fields.
Node-level:: Templates that can reference both cluster-specific and node-specific fields.

* <<template-functions,Template functions>>
* <<default-templates,Default set of templates>>
* <<special-template-variables,Special template variables>>
* <<custom-manifest-order,Customization of the manifests order>>

[#template-functions]
== Template functions

You can customize the templated fields. The {sco} supports all link:https://masterminds.github.io/sprig/[sprig library functions].

Additionally, the `ClusterInstance` API provides the following function that you can use while creating your custom manifests:

`toYaml`:: The `toYaml` function encodes an item into a YAML string. If the item cannot be converted to YAML the function returns an empty string.

See the following example of the `.toYaml` specification in the `ClusterInstance.Spec.Proxy` field:

[source,yaml]
----
{{ if .Spec.Proxy }}
  proxy:
{{ .Spec.Proxy | toYaml | indent 4 }}
{{ end }}
----

[#default-templates]
== Default set of templates

The {sco} provides the following default, validated, and immutable set of templates in the same namespace in which the operator is installed:

|===
|Installation method|Template type|File name|Template content

.2+|Assisted Installer
|Cluster-level templates
|`ai-cluster-templates-v1.yaml`
|`AgentClusterInstall` +
`ClusterDeployment` +
`InfraEnv` +
`KlusterletAddonConfig` +
`ManagedCluster`

|Node-level templates
|`ai-node-templates-v1.yaml`
|`BareMetalHost` +
`NMStateConfig`

.2+|Image-based Install Operator
|Cluster-level templates
|`ibi-cluster-templates-v1.yaml`
|`ClusterDeployment` +
`KlusterletAddonConfig` +
`ManagedCluster`

|Node-level templates
|`ibi-node-templates-v1.yaml`
|`BareMetalHost` +
`ImageClusterInstall` +
`NetworkConfigMap`
|===

*Note:* Certain fields are only relevant to either the Assisted Installer or the IBI Operator installation method. For more information, see xref::../../apis/clusterinstance.json.adoc#clusterInstance-api[ClusterInstance API].

[#special-template-variables]
== Special template variables

The {sco} provides a set of special template variables that you can use in your templates. See the following list:

`CurrentNode`:: The {sco} explicitly controls the iteration of the node objects and exposes this variable to access all the content for the current node being handled in templating.
`InstallConfigOverrides`:: Contains the merged `networkType`, `cpuPartitioningMode` and `installConfigOverrides` content.
`ControlPlaneAgents`:: Consists of the number of control plane agents and it is automatically derived from the `ClusterInstance` node objects.
`WorkerAgents`:: Consists of the number of worker agents and it is automatically derived from the `ClusterInstance` node objects.

Capitalize the field name in the text template to create a custom templated field.

For example, the `ClusterInstance` `spec` field is referenced with the `.Spec` prefix.
However, you must reference special variable fields with the `.SpecialVars` prefix.

*Important:* Instead of using the `.Spec.Nodes` prefix for the `spec.nodes` field, you must reference it with the `.SpecialVars.CurrentNode` special template variable.

For example, if you want to specify the `name` and `namespace` for your current node by using the `CurrentNode` special template variable, use the field names in the following form:

[source,yaml]
----
name: "{{ .SpecialVars.CurrentNode.HostName }}"
namespace: "{{ .Spec.ClusterName }}"
----

[#custom-manifest-order]
== Customization of the manifests order

You can control the order in which manifests are created, updated, and deleted by using the `siteconfig.open-cluster-management.io/sync-wave` annotation. The annotation takes an integer as a value, and that integer constitutes as a _wave_.

You can add one or several manifests to a single wave. If you do not specify a value, the annotation takes the default value of `0`.

The {sco} reconciles the manifests in ascending order when creating or updating resources and it deletes resources in descending order.

In the following example, if the {sco} creates or updates the manifests, the `AgentClusterInstall` and `ClusterDeployment` CRs are reconciled in the first wave, while `KlusterletAddonConfig` and `ManagedCluster` CRs are reconciled in the third wave.

[source,yaml]
----
apiVersion: v1
data:
  AgentClusterInstall: |-
    ...
        siteconfig.open-cluster-management.io/sync-wave: "1"
    ...
  ClusterDeployment: |-
    ...
        siteconfig.open-cluster-management.io/sync-wave: "1"
    ...
  InfraEnv: |-
    ...
        siteconfig.open-cluster-management.io/sync-wave: "2"
    ...
  KlusterletAddonConfig: |-
    ...
        siteconfig.open-cluster-management.io/sync-wave: "3"
    ...
  ManagedCluster: |-
    ...
        siteconfig.open-cluster-management.io/sync-wave: "3"
    ...
kind: ConfigMap
metadata:
  name: assisted-installer-templates
  namespace: example-namespace
----

If the {sco} deletes the resources, `KlusterletAddonConfig` and `ManagedCluster` CRs are the first to be deleted, while the `AgentClusterInstall` and `ClusterDeployment` CRs are the last.