:_mod-docs-content-type: REFERENCE

[#siteconfig-annotations-labels]
= Configuration of additional annotations and labels

[role="_abstract"]
The {sco} applies additional annotations and labels to the manifests that you specify in the `ClusterInstance` resource. You can configure them for cluster-level and node-level installation manifests by using the `extraAnnotations` and `extraLabels` fields in the `ClusterInstance` API. A manifest type is required so that the {sco} applies them to all matching manifests. The annotations and labels are arbitrary, and you can set any key and value pairs that are meaningful to your applications.

*Note:* The additional annotations and labels are only applied to the resources that were rendered through the referenced templates.

View the following example application of `extraAnnotations` and `extraLabels`:

[source,yaml]
----
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: "example-sno"
  namespace: "example-sno"
spec:
  [...]
  clusterName: "example-sno"
  extraAnnotations:
    ClusterDeployment:
      myClusterAnnotation: success
  extraLabels:
    ManagedCluster:
      common: "true"
      group-du: ""
  nodes:
    - hostName: "example-sno.example.redhat.com"
      role: "master"
      extraAnnotations:
        BareMetalHost:
          myNodeAnnotation: success
      extraLabels:
        BareMetalHost:
          "testExtraLabel": "success"
----

* This field supports cluster-level annotations and labels that the {sco} applies to the the `ManagedCluster` and `ClusterDeployment` manifests.
* This field supports node-level annotations and labels that the {sco} applies to the `BareMetalHost` manifest.
* The `extraAnnotations` in this `BareMetalHost` example is `myNodeAnnotation`.
* The `extraLabels` in this `BareMetalHost` example is `testExtraLabel`.

You can verify that your additional labels with the following command:

[source,terminal]
----
oc get managedclusters example-sno -ojsonpath='{.metadata.labels}' | jq
----

View the following example of applied labels:

[source,json]
----
{
  "common": "true",
  "group-du": "",
  ...
}
----

The following command verifies that your additional annotations:

[source,terminal]
----
oc get bmh example-sno.example.redhat.com -n example-sno -ojsonpath='{.metadata.annotations}' | jq
----

View the following example of applied annotations:

[source,json]
----
{
  "myNodeAnnotation": "success",
  ...
}
----
