[#uninstalling-submariner]
= Uninstalling Submariner

You can uninstall the Submariner components from your cluster. Depending on the deployed version of Submariner on the cluster, you can use the automatic or manual method for uninstalling the Submariner components. The automatic method is recommended for removing Submariner version .12, or later. Use the manual method to remove versions before version 0.12. 

[#uninstalling-submariner-automatic]
== Automatic method  

To uninstall Submariner version 0.12, or later, complete the following steps:

. Ensure that you have the `subctl` tool installed. See link:../services/submariner.adoc#submariner-subctl[subctl command utility] for information about installing the `subctl` command utility.

. Run a command similar to the following example to uninstall Submariner from the cluster:
+
----
subctl uninstall --kubeconfig <output/kubeconfigs/cluster-1>
----
+
Replace `output/kubeconfigs/cluster-1` with the path to the `kubeconfig` files for your cluster named `cluster-1`.

. Confirm that you want to remove all of the Submariner components from the cluster. 

. Repeat the steps for each cluster to remove Submariner.

After running those steps on each cluster, Submariner is removed. 

[#uninstalling-submariner-manual]
== Manual method

When uninstalling versions of Submariner that are versions before version 0.12, you must use the manual method. To uninstall using the manual method, complete the procedure that is described in https://submariner.io/operations/cleanup/[Uninstalling Submariner] in the Submariner documentation.  

Your Submariner components are removed from the cluster. 
