[#uninstalling-submariner]
= Uninstalling Submariner

You can uninstall the Submariner components from your clusters. Select from the three methods that you can use based on your preference and the version of Submariner that you are removing. You can use the {product-title} console if you like the console. If you prefer a command-line removal, you can also use the automatic or manual method for uninstalling the Submariner components, depending on the version of Submariner that you are uninstalling. The automatic method is only available for version 0.12, and later, and is best practice for removing those versions of Submariner. Use the manual method to remove versions before version 0.12. 

[#uninstalling-submariner-console]
== Console method 

To uninstall Submariner from a cluster by using the {product-title-short} console, complete the following steps:

. From the {product-title-short} console, select *Infrastructure* > *Clusters*.

. Select the _Cluster sets_ tab to view a list of cluster sets. 

. Select the cluster set that contains the clusters from which you want to remove the Submariner components. 

. Select the *Submariner Add-ons* tab to view the clusters in the cluster set that have Submariner deployed. 

. In the _Actions_ menu for the cluster that you want to uninstall Submariner, select *Uninstall Submariner*. 

. Repeat those steps for other clusters from which you are removing Submariner.

Submariner is removed from the clusters.  

#uninstalling-submariner-automatic]
== Automatic method  

To uninstall Submariner version 0.12, or later, complete the following steps:

. Ensure that you have the `subctl` tool installed. See link:../services/submariner.adoc#submariner-subctl[subctl command utility] for information about installing the `subctl` command utility.

. Run a command similar to the following example to uninstall Submariner from the cluster:
+
----
subctl uninstall --kubeconfig <output/kubeconfigs/cluster-1>
----
+
Replace `output/kubeconfigs/cluster-1` with the path to the `kubeconfig` files for your cluster named `cluster-1`.

. Confirm that you want to remove all of the Submariner components from the cluster. 

. Repeat the steps for each cluster to remove Submariner.

After running those steps on each cluster, Submariner is removed. 

[#uninstalling-submariner-manual]
== Manual method

When uninstalling versions of Submariner that are versions before version 0.12, you must use the manual method. To uninstall using the manual method, complete the procedure that is described in https://submariner.io/operations/cleanup/[Uninstalling Submariner] in the Submariner documentation.  

Your Submariner components are removed from the cluster. 
