[#uninstalling-submariner]
= Uninstalling Submariner

You can uninstall the Submariner components from your clusters using the {product-title} console or the command-line. For Submariner versions earlier than 0.12, additional steps are needed to completely remove all data plane components.

[#uninstalling-submariner-console]
== Console method 

To uninstall Submariner from a cluster by using the {product-title-short} console, complete the following steps:

. From the {product-title-short} console navigation, select *Infrastructure* > *Clusters*, and select the _Cluster sets_ tab.

. Select the cluster set that contains the clusters from which you want to remove the Submariner components. 

. Select the *Submariner Add-ons* tab to view the clusters in the cluster set that have Submariner deployed. 

. In the _Actions_ menu for the cluster that you want to uninstall Submariner, select *Uninstall Submariner*. 

. Repeat those steps for other clusters from which you are removing Submariner.

Submariner is removed from the clusters.

**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider.   

#uninstalling-submariner-cli]
== Command-line method  

To uninstall Submariner by using the command line, complete the following steps:

. Locate the clusters that contain the Submariner add-on by entering the following command:
+
----
oc get resource submariner-addon -n open-cluster-management
----

. Run a command similar to the following example to uninstall Submariner from the cluster:
+
----
oc delete resource submariner-addon -n <CLUSTER_NAME>
----
+
Replace `CLUSTER_NAME` with the name of the cluster.

. Confirm that you want to remove all of the Submariner components from the cluster. 

. Repeat the steps for each cluster to remove Submariner.

If the version of Submariner that you are removing is earlier than version 0.12, continue with xref:../services/submariner/submariner_uninstall.adoc##uninstalling-submariner-manual[Manual removal steps for early version of Submariner]. If the Submariner version is 0.12, or later, Submariner is removed. 

**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider.

[#uninstalling-submariner-manual]
== Manual method

When uninstalling versions of Submariner that are earlier than version 0.12, you must complete the additional steps, 5-8, that are provided in the  https://submariner.io/operations/cleanup/#manual-uninstall/[Manual Uninstall] section in the Submariner documentation.  

. For {ocp-short} deployments, delete Lighthouse entry from `default` DNS.
+
.. For each participating cluster, create a file named `new-dns` that looks similar to the following example: 
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1
  kind: DNS
  metadata:
    finalizers:
    - dns.operator.openshift.io/dns-controller
    name: default
  spec:
    servers: []
  issue the following command:
----

.. Apply the file by entering the following command:
+
----
oc apply -f new-dns
----

+
This deletes the Lighthouse entry from the `Data` section in `Corefile` of the configmap.

   ```bash
   #lighthouse-start AUTO-GENERATED SECTION. DO NOT EDIT
   clusterset.local:53 {
       forward . 100.3.185.93
   }
   #lighthouse-end
   ```
   Verify that the Lighthouse entry is deleted from `Corefile` of `dns-default` configmap by running
   following command on an OpenShift cluster

   ```bash
   kubectl describe configmap dns-default -n openshift-dns
   ```

   For Kubernetes deployments, manually edit the `Corefile` of `coredns` configmap and delete the
   Lighthouse entry by issuing below commands

   ```bash
   kubectl edit cm coredns -n kube-system
   ```

   This will also restart the `coredns`. Below command can also be issued to manually restart `coredns`.

   ```bash
   kubectl rollout restart -n kube-system deployment/coredns
   ```

   Verify that the Lighthouse entry is deleted from `Data` section in `Corefile` of `dns-default`
   config map by running following command on a Kubernetes cluster

   ```bash
   kubectl describe configmap coredns -n kube-system
   ```

   {{% notice note %}}
   Following commands need to be executed from inside the cluster nodes.
   {{% /notice %}}

6. Remove Submariner's iptables chains

   On all nodes in each participating cluster, issue the following commands:

   ```bash
   iptables --flush SUBMARINER-INPUT
   iptables -D INPUT $(iptables -L INPUT --line-numbers | grep SUBMARINER-INPUT | awk '{print $1}')
   iptables --delete-chain SUBMARINER-INPUT

   iptables -t nat --flush SUBMARINER-POSTROUTING
   iptables -t nat -D POSTROUTING $(iptables -t nat -L POSTROUTING --line-numbers | grep SUBMARINER-POSTROUTING | awk '{print $1}')
   iptables -t nat --delete-chain SUBMARINER-POSTROUTING

   iptables -t mangle --flush SUBMARINER-POSTROUTING
   iptables -t mangle -D POSTROUTING $(iptables -t mangle -L POSTROUTING --line-numbers | grep SUBMARINER-POSTROUTING | awk '{print $1}')
   iptables -t mangle --delete-chain SUBMARINER-POSTROUTING

   ipset destroy SUBMARINER-LOCALCIDRS
   ipset destroy SUBMARINER-REMOTECIDRS
   ```

   If Globalnet is enabled in the setup, additionally issue the following commands on gateway nodes:

   ```bash
   iptables -t nat --flush SUBMARINER-GN-INGRESS
   iptables -t nat -D PREROUTING $(iptables -t nat -L PREROUTING --line-numbers | grep SUBMARINER-GN-INGRESS | awk '{print $1}')
   iptables -t nat --delete-chain SUBMARINER-GN-INGRESS

   iptables -t nat --flush SUBMARINER-GN-EGRESS
   iptables -t nat --delete-chain SUBMARINER-GN-EGRESS

   iptables -t nat -t nat --flush SUBMARINER-GN-MARK
   iptables -t nat --delete-chain SUBMARINER-GN-MARK
   ```

7. Delete the `vx-submariner` interface

   On all nodes in each participating cluster, issue the following command:

   ```bash
   ip link delete vx-submariner
   ```

8. If Globalnet release 0.9 (or earlier) is enabled in the setup, issue the following commands to remove the
   annotations from all the Pods and Services.

   For each participating cluster, issue the following command:

   ```bash
   for ns in `kubectl get ns -o jsonpath="{.items[*].metadata.name}"`; do
       kubectl annotate pods -n $ns --all submariner.io/globalIp-
       kubectl annotate services -n $ns --all submariner.io/globalIp-
   done
   ```


Your Submariner components are removed from the cluster. 

**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider.
