[#deploying-submariner-manually]
= Deploying Submariner manually

Before you deploy Submariner with {product-title}, you must prepare the clusters on the hosting environment for the connection. Currently, you can use the `SubmarinerConfig` API to automatically prepare the clusters on Amazon Web Services, Google Cloud Platform and VMware vSphere. For other platforms, you need to prepare them manually, see xref:#preparing-the-hosts-to-deploy-submariner[Preparing the hosts to deploy Submariner] for the steps.

[#preparing-the-hosts-to-deploy-submariner]
== Preparing the hosts to deploy Submariner

Before you deploy Submariner with {product-title-short}, you must prepare the clusters on the hosting environment for the connection. The requirements vary for different hosting environments, so follow the instructions for your hosting environment.

[#preparing-aws]
=== Preparing Amazon Web Services to deploy Submariner

You can use the `SubmarinerConfig` API to configure the AWS cluster to integrate with a Submariner deployment. Follow the steps that apply to your situation to prepare AWS to install Submariner:

. If you did not create the managed cluster with {product-title-short}, you must manually create a secret on your hub cluster in the namespace of your managed cluster that contains your AWS credential secret. If you created the cluster with {product-title-short}, skip to step 2.
+
To create the secret, enter the commands that contain information that is similar to the following example and YAML. Apply the YAML content after customizing it with your information:
+
----
export AWS_ACCESS_KEY_ID=<aws-access-key-id>
export AWS_SECRET_ACCESS_KEY=<aws-secret-access-key>
----
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
    name: <managed-cluster-name>-aws-creds
    namespace: <managed-cluster-namespace>
type: Opaque
data:
    aws_access_key_id: $(echo -n ${AWS_ACCESS_KEY_ID} | base64 -w0)
    aws_secret_access_key: $(echo -n ${AWS_SECRET_ACCESS_KEY} | base64 -w0)
----
+
Replace `managed-cluster-name` with the name of your managed cluster.
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
Replace `aws-access-key-id` with your AWS access key ID.
+
Replace `aws-secret-access-key` with your AWS access key.

. If you created the managed cluster with {product-title-short}, or after you create the secret in the previous step, prepare the cluster by applying YAML content that is similar to the following example:

+
[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:
    gatewayConfig:
	    aws:
	        instanceType: c5d.large
    credentialsSecret:
      name: <managed-cluster-name>-aws-creds
----
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
Replace `managed-cluster-name` with the name of your managed cluster. The value of `managed-cluster-name-aws-creds` is your AWS credential secret name, which you can find in the cluster namespace of your hub cluster. 
+
*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.
+
This configuration automatically opens the Submariner required ports: network address translation - traversal (NATT) port (4500/UDP), virtual extensible LAN (VXLAN) port (4800/UCP), and Submariner metrics port (8080/TCP) on your AWS instance. It also creates one AWS instance as the Submariner gateway with the AWS instance type `c5d.large`.
 
[#preparing-gcp]
=== Preparing Google Cloud Platform to deploy Submariner

You can use the `SubmarinerConfig` API to configure the Google Cloud Platform cluster to integrate with a Submariner deployment. Follow the steps that apply to your situation to prepare Google Cloud Platform to install Submariner:

. If you did not create the managed cluster with {product-title-short}, you must manually create a secret on your hub cluster in the namespace of your managed cluster that contains your Google Cloud Platform credential secret. If you created the cluster with {product-title-short}, then skip to step 2.
+
To create the secret, customize and apply YAML content that is similar to the following example:
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
    name: <managed-cluster-name>-gcp-creds
    namespace: <managed-cluster-namespace>
type: Opaque
data:
    osServiceAccount.json: <gcp-os-service-account-json-file-content>
----
+
Replace `managed-cluster-name` with the name of your managed cluster. The value of `managed-cluster-name-aws-creds` is your Google Cloud Platform credential secret name, which you can find in the cluster namespace of your hub cluster.
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
Replace `gcp-os-service-account-json-file-content` with the contents of your encoded Google Cloud Platform `osServiceAccount.json: $(base64 -w0 )` file.

. If you created the managed cluster with {product-title-short}, or you have already created the secret in the previous step, prepare the cluster by customizing and applying YAML content that is similar to the following example:
+
[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:
    credentialsSecret:
      name: <managed-cluster-name>-gcp-creds
----
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
Replace `managed-cluster-name` with the name of your managed cluster. The value of `managed-cluster-name-gcp-creds` is your Google Cloud Platform credential secret name, which you can find in the cluster namespace of your hub cluster. 
+
*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.
+
This configuration automatically opens the Submariner required ports: network address translation - traversal (NATT) port (4500/UDP), virtual extensible LAN (VXLAN) port (4800/UCP), and Submariner metrics port (8080/TCP) on your Google Cloud Platform instance. It also labels one worker node as the Submariner gateway and enables the public IP address of this node in your Google Cloud Platform cluster.

[#preparing-vm]
=== Preparing to deploy Submariner on VMware vSphere

Submariner uses IPsec to establish the secure tunnels between the clusters on the gateway nodes. You can use the default port or specify a custom port. When you run this procedure without specifying an IPsec NATT port, the default port is automatically used for the communication. The default port is 4500/UDP. 

Submariner uses virtual extensible LAN (VXLAN) to encapsulate traffic when it moves from the worker and master nodes to the gateway nodes. The VXLAN port cannot be customized, and is always port 4800/UDP.

Submariner uses 8080/TCP to send its metrics information among nodes in the cluster, this port cannot be customized.

The following ports must be opened by your VMWare vSphere administrator before you can enable Submariner:

.VMware vSphere and Submariner ports
|===
| Name | Default value | Customizable 

| IPsec NATT
| 4500/UDP
| Yes

| VXLAN
| 4800/UDP
| No

| Submariner metrics
| 8080/TCP
| No
|===

To prepare VMware vSphere clusters for deploying Submariner, complete the following steps:

. Ensure that the IPsec NATT, VXLAN, and metrics ports are open.

. Customize and apply YAML content that is similar to the following example:
+
[source,yaml]
----
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
    name: submariner
    namespace: <managed-cluster-namespace>
spec:{}
----
+
Replace `managed-cluster-namespace` with the namespace of your managed cluster.
+
*Note:* The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.
+
This configuration uses the default network address translation - traversal (NATT) port (4500/UDP) for your Submariner and one worker node is labeled as the Submariner gateway on your vSphere cluster.
+
Submariner uses IP security (IPsec) to establish the secure tunnels between the clusters on the gateway nodes. You can either use the default IPsec NATT port, or you can specify a different port that you configured. When you run this procedure without specifying an IPsec NATT port of 4500/UDP is automatically used for the communication.

[#deploying-submariner-mcaddon-api]
== Deploy Submariner with the ManagedClusterAddOn API

To deploy Submariner by using the `ManagedClusterAddOn` API, complete the following steps:

. Create a `ManagedClusterSet` on the hub cluster by using the instructions provided in link:../../clusters/managedclustersets.adoc#managedclustersets[Creating and managing ManagedClusterSets]. Your entry for the `ManagedClusterSet` should resemble the following content:

+
[source,yaml]
----   
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSet
metadata:
  name: <managed-cluster-set-name>
----
+
Replace `managed-cluster-set-name` with a name for the `ManagedClusterSet` that you are creating.
+
*Note:* The maximum length of the name of the Kubernetes namespace is 63 characters, so the maximum length of the `<managed-cluster-set-name>` is 56 characters. If the length of `<managed-cluster-set-name>` exceeds 56, the `<managed-cluster-set-name>` is truncated from the head.
+
After the `ManagedClusterSet` is created, the `submariner-addon` creates a namespace called `<managed-cluster-set-name>-broker` and deploys the Submariner broker to it.

. Create the `Broker` configuration on the hub cluster in the `<managed-cluster-set-name>-broker` namespace by customizing and applying YAML content that is similar to the following example:
+
[source,yaml]
----
apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
     name: submariner-broker
     namespace: <managed-cluster-set-name>-broker
spec:
     globalnetEnabled: false
----
+
Replace `managed-cluster-set-name` with the name of the managed cluster. 
+
Set the the value of `globalnetEnabled` to `true` if you want to enable Submariner Globalnet in the `ManagedClusterSet`.

. Add one managed cluster to the `ManagedClusterSet` by entering the following command:
+
----
oc label managedclusters <managed-cluster-name> "cluster.open-cluster-management.io/clusterset=<managed-cluster-set-name>" --overwrite
----
+
Replace `<managed-cluster-name>` with the name of the managed cluster that you want to add to the `ManagedClusterSet`.
+
Replace `<managed-cluster-set-name>` with the name of the `ManagedClusterSet` to which you want to add the managed cluster. 

.  Deploy Submariner on the managed cluster by customizing and applying YAML content that is similar to the following example:
+
[source,yaml]
----
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
     name: submariner
     namespace: <managed-cluster-name>
spec:
     installNamespace: submariner-operator
----
+
Replace `managed-cluster-name` with the name of the managed cluster that you want to use with Submariner. 
+
The `installNamespace` field in the spec of the `ManagedClusterAddOn` is the namespace on the managed cluster where it installs Submariner. Currently, Submariner must be installed in the `submariner-operator` namespace.
+
After the `ManagedClusterAddOn` is created, the `submariner-addon` deploys Submariner to the `submariner-operator` namespace on the managed cluster. You can view the deployment status of Submariner from the status of this `ManagedClusterAddOn`.
+
*Note:* The name of `ManagedClusterAddOn` must be `submariner`.

. Repeat steps three and four for all of the managed clusters that you want to enable Submariner on.

. After Submariner is deployed on the managed cluster, you can verify the Submariner deployment status by checking the status of submariner `ManagedClusterAddOn` by entering the following command: 
+
----
oc -n <managed-cluster-name> get managedclusteraddons submariner -oyaml
----
+
Replace `managed-cluster-name` with the name of the managed cluster.
+
In the status of the Submariner `ManagedClusterAddOn`, three conditions indicate the  deployment status of Submariner:
+
* `SubmarinerGatewayNodesLabeled` condition indicates whether there are labeled Submariner gateway nodes on the managed cluster.
* `SubmarinerAgentDegraded` condition indicates whether the Submariner is successfully deployed on the managed cluster.
* `SubmarinerConnectionDegraded` condition indicates how many connections are established on the managed cluster with Submariner.
