[#creating-a-credential-for-bare-metal]
= Creating a credential for bare metal

You need a credential to use {product-title} console to deploy and manage a {ocp} cluster in a bare metal environment.

* <<bare_cred_prerequisites,Prerequisites>>
* <<bare_cred,Creating a credential by using the console>>
* <<bare_delete_cred,Deleting your credential>>

[#bare_cred_prerequisites]
== Prerequisites

You need the following prerequisites before creating a credential:

* A {product-title} hub cluster that is deployed.
When managing bare metal clusters, you must have the hub cluster installed on {ocp} version 4.5, or later.
* Internet access for your {product-title} hub cluster so it can create the Kubernetes cluster on your bare metal server
* Your bare metal server login credentials, which include the libvirt URI, SSH Private Key, and a list of SSH known hosts;
see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/installing_on_bare_metal/installing-on-bare-metal#ssh-agent-using_installing-bare-metal[Generating an SSH private key and adding it to the agent]
* Account permissions that allow installing clusters on the bare metal infrastructure

[#bare_cred]
== Creating a credential by using the console

To create a credential from the {product-title} console, complete the following steps:

. From the navigation menu, navigate to *Credentials*. Existing credentials are displayed.

. Select *Add credential*.
. Select *Bare metal* as your provider.
. Add a name for your credential.
. Select a namespace for your credential from the list.
+
*Tip:* Create a namespace specifically to host your credentials, both for convenience and added security.

. You can optionally add a _Base DNS domain_ for your credential. If you add the base DNS domain to the credential, it is automatically populated in the correct field when you create a cluster with this credential.
. Add your _libvirt URI_.
See https://libvirt.org/uri.html[Connection URIs] for more information.
. Add a list of your SSH known hosts.
. Enter your _Red Hat OpenShift pull secret_.
You can download your pull secret from https://cloud.redhat.com/openshift/install/pull-secret[Pull secret].
. Add your _SSH private key_ and your _SSH public key_ so you can access the cluster.
You can use an existing key, or use a key generation program to create a new one.
See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/installing_on_bare_metal/installing-on-bare-metal#ssh-agent-using_installing-bare-metal[Generating an SSH private key and adding it to the agent] for more information about how to generate a key.
. For disconnected installations only: Complete the fields in the *Configuration for disconnected installation* subsection with the required information:
+
* _Image registry mirror_: This value contains the disconnected registry path. The path contains the hostname, port, and repository path to all of the installation images for disconnected installations. Example: `repository.com:5000/openshift/ocp-release`.
+
The path creates an image content source policy mapping in the `install-config.yaml` to the {ocp} release images. As an example, `repository.com:5000` produces this `imageContentSource` content:
+
----
imageContentSources:
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-release-nightly
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.example.com:5000/ocp4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----
* _Bootstrap OS image_: This value contains the URL to the image to use for the bootstrap machine.
* _Cluster OS image_: This value contains the URL to the image to use for {ocp} cluster machines. 
* _Additional trust bundle_: This value provides the contents of the certificate file that is required to access the mirror registry.
+
*Note:* If you are deploying managed clusters from a hub that is in a disconnected environment, and want them to be automatically imported post install, add an Image Content Source Policy to the `install-config.yaml` file by using the `YAML` editor. A sample entry is shown in the following example: 
+
----
imageContentSources:
- mirrors:
  - registry.example.com:5000/rhacm2
  source: registry.redhat.io/rhacm2
----

. Click *Create*.
When you create the credential, it is added to the list of credentials.

You can create a cluster that uses this credential by completing the steps in xref:../clusters/create_bare.adoc#creating-a-cluster-on-bare-metal[Creating a cluster on bare metal].

[#bare_delete_cred]
== Deleting your credential

When you are no longer managing a cluster that is using a credential, delete the credential to protect the information in the credential.

. From the navigation menu, navigate to *Credentials*.
. Select the options menu for the credential that you want to delete.
. Select *Delete credential*.
