[#access-control]
= Access control and cluster credentials

Access control and cluster credentials might need to manually be created and managed. You must configure _authentication_ service requirements for {product-title} to onboard workloads to Identity and Access Management (IAM). For more information see, _Understanding authentication_ in https://docs.openshift.com/container-platform/4.7/authentication/understanding-authentication.html[Understanding authentication] in the {ocp-short} documentation.

You can also create and rotate your cluster credentials. A _credential_ is required to create a {ocp} cluster on a cloud service provider with {product-title}. The credential stores the access information for a cloud provider. Each provider account requires its own credential, as does each domain on a single provider.

Role-based access control and authentication identifies the user associated roles and cluster credentials. See the following files for information about access and credentials.

**Required access**: Cluster administrator

* xref:../access_control/rbac.adoc#role-based-access-control[Role-based access control]
* xref:../access_control/credential_aws.adoc#creating-a-credential-for-amazon-web-services[Creating a credential for Amazon Web Services]
* xref:../access_control/credential_azure.adoc#creating-a-credential-for-microsoft-azure[Creating a credential for Microsoft Azure]
* xref:../access_control/credential_google.adoc#creating-a-credential-for-google-cloud-platform[Creating a credential for Google Cloud Platform]
* xref:../access_control/credential_vm.adoc#creating-a-credential-for-vmware-vsphere[Creating a credential for VMware vSphere]
* xref:../access_control/credential_openstack.adoc#creating-a-credential-for-openstack[Creating a credential for Red Hat OpenStack Platform]
* xref:../access_control/credential_bare.adoc#creating-a-credential-for-bare-metal[Creating a credential for bare metal]

