[#rhacm-rbac-implement]
= Implementing role-based access control

{product-title} RBAC is validated at the console level and at the API level. Actions in the console can be enabled or disabled based on user access role permissions. 

The {mce-short} is a prerequisite and the cluster lifecycle function of {product-title-short}. To manage RBAC for clusters with the {mce-short}, use the RBAC guidance from the cluster lifecycle link:../clusters/about/rbac_mce.adoc#mce-rbac[{mce} Role-based access control] documentation. 

View the following sections for more information on RBAC for specific lifecycles for {product-title-short}:

* <<application-lifecycle-RBAC,Application lifecycle RBAC>>
** <<console-api-rbac-application,Console and API RBAC table for application lifecycle>>
* <<governance-lifecycle-RBAC,Governance lifecycle RBAC>>
** <<console-api-rbac-gov,Console and API RBAC table for governance lifecycle>>
* <<observability-RBAC,Observability RBAC>>
** <<console-api-rbac-obs,Console and API RBAC table for observability lifecycle>>

[#application-lifecycle-RBAC]
== Application lifecycle RBAC

When you create an application, the `_subscription_` namespace is created and the configuration map is created in the `_subscription_` namespace. You must also have access to the `_channel_` namespace. When you want to apply a subscription, you must be a subscription administrator. For more information on managing applications, see link:../applications/allow_deny.adoc#creating-allow-deny-list[Creating an allow and deny list as subscription administrator]. 

View the following application lifecycle RBAC operations:

- Create and administer applications on all managed clusters with a user named `username`. You must create a cluster role binding and bind it to `username`. Run the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:cluster-manager-admin --user=<username>
----
+
This role is a super user, which has access to all resources and actions. You can create the namespace for the application and all application resources in the namespace with this role.

- Create applications that deploy resources to multiple namespaces. You must create a cluster role binding to the `open-cluster-management:subscription-admin` cluster role, and bind it to a user named `username`. Run the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:subscription-admin --user=<username>
----

- Create and administer applications in the `cluster-name` managed cluster, with the `username` user. You must create a cluster role binding to the `open-cluster-management:admin:<cluster-name>` cluster role and bind it to `username` by entering the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:admin:<cluster-name> --user=<username>
----
+
This role has read and write access to all `application` resources on the managed cluster, `cluster-name`. Repeat this if access for other managed clusters is required.

- Create a namespace role binding to the `application` namespace using the `admin` role and bind it to `username` by entering the following command:
+
----
oc create rolebinding <role-binding-name> -n <application-namespace> --clusterrole=admin --user=<username>
----
+
This role has read and write access to all `application` resources in the `application` namspace. Repeat this if access for other applications is required or if the application deploys to multiple namespaces.

- You can create applications that deploy resources to multiple namespaces. Create a cluster role binding to the `open-cluster-management:subscription-admin` cluster role and bind it to `username` by entering the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:subscription-admin --user=<username>
----

- To view an application on a managed cluster named `cluster-name` with the user named `username`, create a cluster role binding to the `open-cluster-management:view:` cluster role and bind it to `username`. Enter the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:view:<cluster-name> --user=<username>
----
+
This role has read access to all `application` resources on the managed cluster, `cluster-name`. Repeat this if access for other managed clusters is required.

- Create a namespace role binding to the `application` namespace using the `view` role and bind it to `username`. Enter the following command:
+
----
oc create rolebinding <role-binding-name> -n <application-namespace> --clusterrole=view --user=<username>
----
+
This role has read access to all `application` resources in the `application` namspace. Repeat this if access for other applications is required.

[#console-api-rbac-application]
=== Console and API RBAC table for application lifecycle

View the following console and API RBAC tables for Application lifecycle:

.Console RBAC table for application lifecycle
|===
| Resource | Admin | Edit | View

| Application
| create, read, update, delete
| create, read, update, delete
| read

| Channel
| create, read, update, delete
| create, read, update, delete
| read

| Subscription
| create, read, update, delete
| create, read, update, delete
| read

|===

.API RBAC table for application lifecycle
|===
| API | Admin | Edit | View

| `applications.app.k8s.io`
| create, read, update, delete
| create, read, update, delete
| read

| `channels.apps.open-cluster-management.io`
| create, read, update, delete
| create, read, update, delete
| read

| `deployables.apps.open-cluster-management.io`
| create, read, update, delete
| create, read, update, delete
| read

| `helmreleases.apps.open-cluster-management.io`
| create, read, update, delete
| create, read, update, delete
| read

| `placements.apps.open-cluster-management.io`
| create, read, update, delete
| create, read, update, delete
| read

| `placementrules.apps.open-cluster-management.io` (Deprecated)
| create, read, update, delete
| create, read, update, delete
| read

| `subscriptions.apps.open-cluster-management.io`
| create, read, update, delete
| create, read, update, delete
| read

| `configmaps`
| create, read, update, delete
| create, read, update, delete
| read

| `secrets`
| create, read, update, delete
| create, read, update, delete
| read

| `namespaces`
| create, read, update, delete
| create, read, update, delete
| read
|===


[#governance-lifecycle-RBAC]
== Governance lifecycle RBAC

When a policy is created, the policy is created in the cluster. Roles for the governance lifecycle are namespace-scoped. A user must also have access to the managed cluster. 

To perform governance lifecycle operations, users must have access to the namespace where the policy is created, along with access to the managed cluster where the policy is applied.

View the following operations:

- To create a policy in the `policy` namespace and apply it in a managed cluster named `cluster-name`, create a namespace role binding to the `policy` namespace using the `open-cluster-management:admin:<cluster-name>` cluster role. Run the following command:
+
----
oc create rolebinding <role-binding-name> -n <policy-namespace> --clusterrole=open-cluster-management:admin:<cluster-name> --user=<username>
----

- To view a policy in a managed cluster, create a cluster role binding to `open-cluster-management:view:<cluster-name>` cluster role and bind it to the `view` role with the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:view:<cluster-name> --user=<username>
----

[#console-api-rbac-gov]
=== Console and API RBAC table for governance lifecycle

View the following console and API RBAC tables for governance lifecycle:

.Console RBAC table for governance lifecycle
|===
| Resource | Admin | Edit | View

| Policies
| create, read, update, delete
| read, update
| read

| PlacementBindings
| create, read, update, delete
| read, update
| read

| Placements
| create, read, update, delete
| read, update
| read

| PlacementRules (deprecated)
| create, read, update, delete
| read, update
| read

| PolicyAutomations
| create, read, update, delete
| read, update
| read
|===

.API RBAC table for governance lifecycle
|===
| API | Admin | Edit | View

| `policies.policy.open-cluster-management.io`
| create, read, update, delete
| read, update
| read

| `placementbindings.policy.open-cluster-management.io`
| create, read, update, delete
| read, update
| read

| `policyautomations.policy.open-cluster-management.io`
| create, read, update, delete
| read, update
| read
|===

[#observability-RBAC]
== Observability RBAC

To view the observability metrics for a managed cluster, you must have `view` access to that managed cluster on the hub cluster. View the following list of observability features:

* Access managed cluster metrics.
+
Users are denied access to managed cluster metrics, if they are not assigned to the `view` role for the managed cluster on the hub cluster. Run the following command to verify if a user has the authority to create a `managedClusterView` role in the managed cluster namespace:
+
----
oc auth can-i create ManagedClusterView -n <managedClusterName> --as=<user>
----
+
As a cluster administrator, create a `managedClusterView` role in the managed cluster namespace. Run the following command:
+
----
oc create role create-managedclusterview --verb=create --resource=managedclusterviews -n <managedClusterName>
----
+
Then apply and bind the role to a user by creating a role bind. Run the following command:
+
----
oc create rolebinding user-create-managedclusterview-binding --role=create-managedclusterview --user=<user>  -n <managedClusterName>
----

* Search for resources.
+
To verify if a user has access to resource types, use the following command:
+
----
oc auth can-i list <resource-type> -n <namespace> --as=<rbac-user>
----
+
*Note:* `<resource-type>` must be plural.

* To view observability data in Grafana, you must have a `RoleBinding` resource in the same namespace of the managed cluster.
+
View the following `RoleBinding` example:
+
[source,yaml]
----
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: <replace-with-name-of-rolebinding>
 namespace: <replace-with-name-of-managedcluster-namespace>
subjects:
 - kind: <replace with User|Group|ServiceAccount>
   apiGroup: rbac.authorization.k8s.io
   name: <replace with name of User|Group|ServiceAccount>
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: view
----

See link:../governance/rolebinding_policy.adoc#role-binding-policy[Role binding policy] for more information. See link:../observability/customize_observability.adoc#customizing-observability[Customizing observability] to configure observability.

[#console-api-rbac-obs]
=== Console and API RBAC table for observability lifecycle

To manage components of observability, view the following API RBAC table:

.API RBAC table for observability

|===
| API | Admin | Edit | View
| `multiclusterobservabilities.observability.open-cluster-management.io`
| create, read, update, and delete
| read, update
| read

| `searchcustomizations.search.open-cluster-management.io`
| create, get, list, watch, update, delete, patch
| -
| -

| `policyreports.wgpolicyk8s.io`
| get, list, watch
| get, list, watch
| get, list, watch
|===

Continue to learn about securing your cluster, see link:../governance/security_overview.adoc#security[Risk and compliance].
