[#role-based-access-control]
= Role-based access control

{product-title} supports role-based access control (RBAC). Your role determines the actions that you can perform. RBAC is based on the authorization mechanisms in Kubernetes, similar to {ocp}. For more information about RBAC, see the OpenShift _RBAC_ overview in the https://docs.openshift.com/container-platform/4.7/authentication/using-rbac.html[{ocp-short} documentation].

*Note*: Action buttons are disabled from the console if the user-role access is impermissible.

View the following sections for details of supported RBAC by component:

* <<overview-of-roles,Overview of roles>>
* <<rbac-implementation,RBAC implementation>>
* <<cluster-lifecycle-RBAC,Cluster lifecycle RBAC>>
* <<application-lifecycle-RBAC,Application lifecycle RBAC>>
* <<governance-lifecycle-RBAC,Governance lifecycle RBAC>>
* <<observability-RBAC,Observability RBAC>>

// for server foundation meeting, will managed cluster roles that are generate will automatically include the Kubernetes ns (admin and view)? is the managed cluster set in the build? will the provision role be ready for 2.3?

[#overview-of-roles]
== Overview of roles

Some product resources are cluster-wide and some are namespace-scoped. You must apply cluster role bindings and namespace role bindings to your users for consistent access controls. View the table list of the following role definitions that are supported in {product-title}:

// suggestion from James: consider replacing table with just a list since the length of the role names are long 
//possibly call out if its a kubernetes role vs acm role? How can we doc this ? We can ask QE for some help with how it can be labeled. Built-in Kubernetes roles does not limit the access; everyone receives admin access in that specific ns. What are the recommended roles for ACM, add note/blurb explaining the Kube access
//clarify why a cluster and namespace binding is needed, think that a role binding is only required
//cluster role binding and role binding (in the ns) How can the user utilize the managedcluster set role

.Role definition table
|===
| Role | Definition
| *cluster-admin*
| This is an {ocp-short} default role. A user with cluster binding to the `cluster-admin` role is an {ocp-short} super user, who has all access. 
| *open-cluster-management:cluster-manager-admin*
| A user with cluster binding to the `cluster-manager-admin` role is a {product-title} super user, who has all access. This role allows the user to create a `ManagedCluster` resource.

//might not have provision role, but there might be self-provision where the user can create any project and objects in the project (Jian will double check and confirm), cluster-wide ability to manage clusters
//add provision cluster role
//| *open-cluster-management:cluster-provisoner*
//| A user with cluster 

//add roles for machine clusterpools, kubernetes admin and view roles (no new roles should be added tho)
//is a ns role required? when a user is bound to a role, cluster role bindings are created in the cluster ns (James-only using clusterset?) , it'll bind to admin
//and view in a specific namespace. Clusterset is a "beta feature" featured flags that would need to be enabled

| *open-cluster-management:admin:managed-cluster-<managed_cluster_name>*
| A user with cluster binding to the `managed-cluster-<managed_cluster_name>` role has administrator access to the `ManagedCluster` resource named,  `managedcluster-<managed_cluster_name>`. When a user has a managed cluster, this role is automatically created.
| *open-cluster-management:view:managed-cluster-<managed_cluster_name>*
| A user with cluster binding to the `managed-cluster-<managed_cluster_name>` role has view access to the `ManagedCluster` resource named,  `managedcluster-<managed_cluster_name>`.

| *open-cluster-management:managedclusterset:admin:managed-clusterset-<managed_clusterset_name>*
| A user with cluster binding to the `managed-clusterset-<managed_clusterset_name>` role has administrator access to `ManagedCluster` resource named `<managed_clusterset_name>`. The user also has administrator access to `managedcluster.cluster.open-cluster-management.io`, `clusterclaim.hive.openshit.io`, `clusterdeployment.hive.openshit.io`, and `clusterpool.hive.openshit.io` resources, which has the managed cluster set labels: `cluster.open-cluster-management.io` and `clusterset=managed-clusterset-<managed_clusterset_name>`. A role binding is automatically generated when you are using a cluster set. See link:../manage_cluster/custom_resource.adoc#managedclustersets[ManagedClusterSets] to learn how to manage the resource.

| *open-cluster-management:managedclusterset:view:managed-clusterset-<managed_clusterset_name>*
| A user with cluster binding to the `managed-clusterset-<managed_clusterset_name>` role has view access to the `ManagedCluster` resource named, `managedclusterset-<managed_clusterset_name>`. The user also has view access to `managedcluster.cluster.open-cluster-management.io`, `clusterclaim.hive.openshit.io`, `clusterdeployment.hive.openshit.io`, and `clusterpool.hive.openshit.io` resources, which has the managed cluster set labels: `cluster.open-cluster-management.io`, `clusterset=managed-clusterset-<managed_clusterset_name>`. For more details on how to manage managed cluster set resources, see link:../clusters/custom_resource.adoc#managedclustersets[ManagedClusterSets].

| *open-cluster-management:subscription-admin*
| A user with the `subscription-admin` role can create Git subscriptions that deploy resources to multiple namespaces. The resources are specified in Kubernetes resource YAML files in the subscribed Git repository. *Note*: When a non-subscription-admin user creates a subscription, all resources are deployed into the subscription namespace regardless of specified namespaces in the resources. For more information, see the <<application-lifecycle-RBAC,Application lifecycle RBAC>> section.

| *admin, edit, view*
| Admin, edit, and view are {ocp-short} default roles. A user with a namespace-scoped binding to these roles has access to `open-cluster-management` resources in a specific namespace, while cluster-wide binding to the same roles gives access to all of the `open-cluster-management` resources cluster-wide.
|===

*Important*:

* Any user can create projects from {ocp-short}, which gives administrator role permissions for the namespace.

* If a user does not have role access to a cluster, the cluster name is not visible. The cluster name is displayed with the following symbol: `-`.

[#rbac-implementation]
== RBAC implementation

//what are the recommended roles for each pillar in ACM? who can access secrets (credentials and provider connections),
//which roles can delete and manage a cluster [provide access for other users to manage a cluster] Can you see secrets within a ns w/Kubernetes
//replace content in the permissions table with content from previously asked questions
//add a section on WHO can create clusters, show oc commands to complete the tasks presented. Similar format to the cluster lifecycle section; adding instructions onto respective page


RBAC is validated at the console level and at the API level. Actions in the console can be enabled or disabled based on user access role permissions. View the following sections for more information on RBAC for specific lifecycles in the product.

[#cluster-lifecycle-RBAC]
=== Cluster lifecycle RBAC

View the following cluster lifecycle RBAC operations.

* To create and administer all managed clusters:

** Create a cluster role binding to the cluster role `open-cluster-management:cluster-manager-admin` by entering the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:cluster-manager-admin
----
+
This role is a super user, which has access to all resources and actions. You can create cluster-scoped `managedcluster` resources, the namespace for the resources that manage the managed cluster, and the resources in the namespace with this role. You can also access provider connections and bare metal assets that are used to create managed clusters with this role.


* To administer a managed cluster named `cluster-name`:

** Create a cluster role binding to the cluster role `open-cluster-management:admin:<cluster-name>` by entering the following command:

+
----
oc create clusterrolebinding (role-binding-name) --clusterrole=open-cluster-management:admin:<cluster-name>
----
+
This role has read and write access to the cluster-scoped `managedcluster` resource. This is needed because the `managedcluster` is a cluster-scoped resource and not a namespace-scoped resource.


** Create a namespace role binding to the cluster role `admin` by entering the following command:
+
----
oc create rolebinding <role-binding-name> -n <cluster-name> --clusterrole=admin
----
+
This role has read and write access to the resources in the namespace of the managed cluster.


* To view a managed cluster named `cluster-name`:

** Create a cluster role binding to the cluster role `open-cluster-management:view:<cluster-name>` by entering the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:view:<cluster-name>
----
+
This role has read access to the cluster-scoped `managedcluster` resource. This is needed because the `managedcluster` is a cluster-scoped resource and not a namespace-scoped resource.


** Create a namespace role binding to the cluster role `view` by entering the following command:
+
----
oc create rolebinding <role-binding-name> -n <cluster-name> --clusterrole=view
----
+
This role has read-only access to the resources in the namespace of the managed cluster.

//clarify how these actions relate to our product; recently changed Actions to Resource for accuracy
View the following console and API RBAC tables for cluster lifecycle:

.Console RBAC table for cluster lifecycle
|===
| Resource | Admin | Edit | View 

| Clusters
| read, update, delete
| read, update
| read

| Cluster sets
| get, update, bind, join
| edit role not mentioned
| get


| Managed clusters
| read, update, delete
| no edit role mentioned
| get, update

| Provider connections
| create, read, update, and delete
| create, read, update, and delete
| read

| Bare metal asset
| create, read, update, delete
| read, update
| read
|===

.API RBAC table for cluster lifecycle
|===
| API | Admin | Edit | View


| managedclusters.cluster.open-cluster-management.io
| create, read, update, delete
| read, update
| read

| baremetalassets.inventory.open-cluster-management.io
| create, read, update, delete
| read, update
| read

| klusterletaddonconfigs.agent.open-cluster-management.io
| create, read, update, delete
| read, update
| read

| managedclusteractions.action.open-cluster-management.io
| create, read, update, delete
| read, update
| read

| managedclusterviews.view.open-cluster-management.io
| create, read, update, delete
| read, update
| read

| managedclusterinfos.internal.open-cluster-management.io
| create, read, update, delete
| read, update
| read

| manifestworks.work.open-cluster-management.io
| create, read, update, delete
| read, update
| read
|===

//provide examples of how to set a group and how to use a clusterpool and clusterset, pain point is managing new clusters, clusterpools help this pain point

[#application-lifecycle-RBAC]
=== Application lifecycle RBAC

When you create an application, the `_subscription_` namespace is created and the configuration map is created in the `_subscription_` namespace. You must also have access to the `_channel_` namespace. When you want to apply a subscription, you must be a subscription administrator. For more information on managing applications, see link:../applications/managing_subscriptions.adoc#creating-and-managing-subscriptions[Creating and managing subscriptions]. 

View the following application lifecycle RBAC operations:

* To create and administer application on all managed clusters with a user named `username`:

** Create a cluster role binding to the `open-cluster-management:cluster-manager-admin` cluster role and bind it to `username`, run the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:cluster-manager-admin --user=<username>
----
+
This role is a super user, which has access to all resources and actions. You can create the namespace for the application and all application resources in the namespace with this role.

* Optionally, you can create applications that deploy resources to multiple namespaces:

** Create a cluster role binding to the `open-cluster-management:subscription-admin` cluster role, and bind it to a user named `username`. Run the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:subscription-admin --user=<username>
----

* To create and administer an application named `application-name` in the `cluster-name` managed cluster, with `username` user:

** Create a cluster role binding to the `open-cluster-management:admin:` cluster role and bind it to `username` by entering the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:admin:<cluster-name> --user=<username>
----
+
This role has read and write access to all `application` resources on the managed cluster, `cluster-name`. Repeat this if access for other managed clusters is required.

** Create a namespace role binding to the `application` namespace using the `admin` role and bind it to `username` by entering the following command:
+
----
oc create rolebinding <role-binding-name> -n <application-namespace> --clusterrole=admin --user=<username>
----
+
This role has read and write access to all `application` resources in the `application` namspace. Repeat this if access for other applications is required or if the application deploys to multiple namespaces.

* Optionally, you can create applications that deploy resources to multiple namespaces:

** Create a cluster role binding to the open-cluster-management:subscription-admin cluster role and bind it to `username` by entering the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:subscription-admin --user=<username>
----

* To view an application on a managed cluster named `cluster-name` with the user named `username`:

** Create a cluster role binding to the `open-cluster-management:view:` cluster role  and bind it to `username` by entering the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:view:<cluster-name> --user=<username>
----
+
This role has read access to all `application` resources on the managed cluster, `cluster-name`. Repeat this if access for other managed clusters is required.

** Create a namespace role binding to the `application` namespace using the `view` role and bind it to `username`. Enter the following command:
+
----
oc create rolebinding <role-binding-name> -n <application-namespace> --clusterrole=view --user=<username>
----
+
This role has read access to all `application` resources in the `application` namspace. Repeat this if access for other applications is required.


View the following console and API RBAC tables for Application lifecycle:

.Console RBAC table for Application lifecycle
|===
| Resource | Admin | Edit | View

| Application
| create, read, update, delete
| create, read, update, delete
| read

| Channel
| create, read, update, delete
| create, read, update, delete
| read

| Subscription
| create, read, update, delete
| create, read, update, delete
| read

| Placement rule
| create, read, update, delete
| create, read, update, delete
| read
|===

.API RBAC table for application lifecycle
|===
| API | Admin | Edit | View

| applications.app.k8s.io
| create, read, update, delete
| create, read, update, delete
| read

| channels.apps.open-cluster-management.io
| create, read, update, delete
| create, read, update, delete
| read

| deployables.apps.open-cluster-management.io
| create, read, update, delete
| create, read, update, delete
| read

| helmreleases.apps.open-cluster-management.io
| create, read, update, delete
| create, read, update, delete
| read

| placementrules.apps.open-cluster-management.io
| create, read, update, delete
| create, read, update, delete
| read

| subscriptions.apps.open-cluster-management.io
| create, read, update, delete
| create, read, update, delete
| read

| configmaps
| create, read, update, delete
| create, read, update, delete
| read

| secrets
| create, read, update, delete
| create, read, update, delete
| read

| namespaces
| create, read, update, delete
| create, read, update, delete
| read
|===


[#governance-lifecycle-RBAC]
=== Governance lifecycle RBAC

When a policy is created, the policy is created in a namespace. Roles for the governance lifecycle are namespace-scoped. A user must also have access to the `managedcluster` namespace. 

To perform governance lifecycle operations, users must have access to the namespace where the policy is created, along with access to the `managedcluster` namespace where the policy is applied.

View the following examples:

* To create a policy in the `policy` namespace and apply it in a managed cluster named `cluster-name`:

** Create a namespace role binding to the `policy` namespace using the `open-cluster-management:admin:` role. Run the following command:
+
----
oc create rolebinding <role-binding-name> -n <policy-namespace> --clusterrole=admin --user=<username>
----

* To view a policy in a managed cluster:

** Create a cluster role binding to `open-cluster-management:admin:` cluster role and bind it to the `view` role with the following command:
+
----
oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:view:<cluster-name> --user=<username>
----


View the following console and API RBAC tables for governance lifecycle:

.Console RBAC table for governance lifecycle
|===
| Resource | Admin | Edit | View

| Policies
| create, read, update, delete
| read, update
| read

| PlacementBindings
| create, read, update, delete
| read, update
| read

| PlacementRules
| create, read, update, delete
| read, update
| read
|===

.API RBAC table for Governance lifecycle
|===
| API | Admin | Edit | View

| policies.policy.open-cluster-management.io
| create, read, update, delete
| read, update
| read

| placementbindings.policy.open-cluster-management.io
| create, read, update, delete
| read, update
| read
|===

[#observability-RBAC]
=== Observability RBAC

To use the observability features, you must be assigned the `cluster-admin` or the `open-cluster-management:cluster-manager-admin` role. View the following list of observability features:

//To access the managed cluster metrics run the following command:
* Access managed cluster metrics.
* Search for resources.
* Use the Visual Web Terminal if you have access to the managed cluster.

To create, update, and delete the `MultiClusterObservability` custom resource. View the following RBAC table:

.API RBAC table for observability

|===
| API | Admin | Edit | View
| multiclusterobservabilities.observability.open-cluster-management.io
| create, read, update, and delete
| -
| -
|===

To continue to learn more about securing your cluster, see link:../risk_compliance/security_intro.adoc#security[Security].
