[#gh-cronjob-compliance-data-restore]
= Restoring compliance data

The Grafana Datasource is mainly from a table named `history.local_compliance`. Its records are generated by a summarization routine that starts nightly at 00:00:00. You do not typically need to run the summary process manually. In some cases, unexpected errors might occur when running the compliance job, so it is necessary to manually log in to the database to run the entire summary process to recover the data that is not generated. You can follow the procedure in link:../global_hub/global_hub_compliance.adoc#global-hub-compliance-manual[Running the summarization process manually] to recover the data.

[#gh-manually-upgrade-tables]
== Optional: Manually upgrading the existing tables to partition tables

If you have installed an early version of {global-hub} before GA, then you need to upgrade your tables to be compatible with the current {global-hub} operator. The main purpose of the upgrade is to convert the `event.local_policies`, `event.local_root_policies`, and `history.local_compliance` tables into partitioned tables. 

The following example shows the conversion of the `event.local_policies` table with the date set for `2023-08`. The upgrade steps of the other two tables are similar. 

. Ensure that the target is partitioned.
+
----
SELECT relname, relkind FROM pg_class WHERE relname = 'local_policies';
----
+
The table output is similar to the following example:
+
|===
|relname | relkind | local_policies | r
|===
+
If the `relkind` is `p`, the current table is partitioned. If it is, then you can skip the remaining step and upgrade the other tables.

. Convert the regular table to the partitioned table.
+
[source,sql]
----
-- start a transaction
BEGIN;
-- Rename the legacy TABLE_NAME
ALTER TABLE event.local_policies RENAME TO local_policies_old;
-- Partition tables: https://github.com/stolostron/multicluster-global-hub/blob/main/operator/pkg/controllers/hubofhubs/database/2.tables.sql#L283-L318
CREATE TABLE IF NOT EXISTS event.local_policies (
    event_name character varying(63) NOT NULL,
    policy_id uuid NOT NULL,
    cluster_id uuid NOT NULL,
    leaf_hub_name character varying(63) NOT NULL,
    message text,
    reason text,
    count integer NOT NULL DEFAULT 0,
    source jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    compliance local_status.compliance_type NOT NULL,
    -- Rename the constraint to avoid conflicts
    CONSTRAINT local_policies_unique_partition_constraint UNIQUE (event_name, count, created_at)
) PARTITION BY RANGE (created_at);
-- Create partitions, load the old data to the previous partition table
CREATE TABLE IF NOT EXISTS event.local_policies_2023_08 PARTITION OF event.local_policies FOR VALUES FROM ('2023-08-01') TO ('2023-09-01');
CREATE TABLE IF NOT EXISTS event.local_policies_2023_07 PARTITION OF event.local_policies FOR VALUES FROM ('2000-01-01') TO ('2023-08-01');

-- Move the records from regular table to partition table
INSERT INTO event.local_policies SELECT * FROM event.local_polcies_old;
DROP TABLE IF EXISTS event.local_policies_old;
-- commit the transaction
COMMIT;
----
+
You can replace the following values according to the table name and current date:

* `event.local_policies_2023_08` is the partition name with the suffix of the **current month**, taking August as an example

* `'2023-08-01'` and `'2023-09-01'` are the minimum and maximum boundaries of the current month partition
  
* `event.local_policies_2023_07` is the partition name with the suffix of the **previous month**(July)

* `'2000-01-01'` and `'2023-08-01'` are the minimum and maximum boundaries of the previous month partition
