[#troubleshooting-restore-finishedwitherrors]
= Troubleshooting restore status finishes with errors

After you restore a backup, resources are restored correctly but the {acm-short} restore resource shows a `FinishedWithErrors` status.

[#symptom-restore-finishedwitherrors]
== Symptom: Troubleshooting restore status finishes with errors

{acm-short} shows a `FinishedWithErrors` status and one or more of the Velero restore resources created by the {acm-short} restore show a `PartiallyFailed` status.

[#resolving-restore-finishedwitherrors]
== Resolving the problem: Troubleshooting restore status finishes with errors

If you restore from a backup that is empty, you can safely ignore the `FinishedWithErrors` status.

{acm} restore shows a cumulative status for all Velero restore resources. If one status is `PartiallyFailed` and the others are `Completed`, the cumulative status you see is `PartiallyFailed` to notify you that there is at least one issue.

To resolve the issue, check the status for all individual Velero restore resources with a `PartiallyFailed` status and view the logs for more details. You can get the log from the object storage directly, or download it from the OADP Operator by using the `DownloadRequest` custom resource.

To create a `DownloadRequest` from the console, complete the following steps:

. Navigate to *Operators* > *Installed Operators* > *Create DownloadRequest*.

. Select `BackupLog` as your *Kind* and follow the console instructions to complete the `DownloadRequest` creation.
