[#title-observability-storage-used-up]
== Storage in mounted persistent volume is used up

Metrics will stored in observability-observatorium-thanos-receive-default-* pod and retention period is 4 days. If the storage of the mounted persistent volume on that pod is used up. Metrics collector will be failied to push metrics to hub cluster.

[#symptom-observability-storage-used-up]
=== Symptom: Storage in mounted persistent volume is used up
In logs of metrics-collector-deployment-* pod in namespace open-cluster-management-addon-observability of managed cluster, you can find error message `no space left on device`.

[#resolving-observability-storage-used-up]
=== Resolving the problem: Storage in mounted persistent volume is used up
If you have this problem, complete the following steps:

. Expand the persistent volume claim used by observability-observatorium-thanos-receive-default-* pod
. Restart observability-observatorium-thanos-receive-default-* pod in namespace open-cluster-management-observability of hub cluster
