[#observability-undesired-label-in-managedcluster]
== Undesired label value in _managedcluster_ resource

When you import a managed cluster, the observability components are installed by default. Your placement rule might resemble the following information: 

---
status:
  decisions:
  - clusterName: sample-managed-cluster
    clusterNamespace: sample-managed-cluster
---

If the managed cluster is not included in the placement rule, the observability components are not installed. 


[#symptom-observability-undesired-label-in-managedcluster]
=== Symptom: Undesired label value in managedcluster resource

If you find that the imported cluster is not included, the observability service for your managed cluster resource might be disabled.

[#resolving-observability-undesired-label-in-managedcluster]
=== Resolving the problem: Undesired label value in managedcluster resource

If you have this problem, enable the observability service by updating the labels in the `managedcluster` resource. When you enable the service, the `vendor:OpenShift` label is added to represent the target managed cluster. *Note*: Observability service is only supported on {ocp-short} managed cluster. 

Complete the following steps:

//how does the user access the resource?

. Change the `observability` parameter to `enabled`.
. Verify that {ocp-short} is listed as a target managed cluster. 



















has labelwih value `disabled` in , complete the following steps:



If you have this problem the managedcluster resource does not have label "vendor" with value "OpenShift", complete the following steps:

. Make sure the  target managed cluster is OpenShift platform. If not, that's desired behavior.


















For an imported managed cluster, it will has observability components installed by default. The cluster should be included in the placementrule `observability` like below:
---
status:
  decisions:
  - clusterName: sample-managed-cluster
    clusterNamespace: sample-managed-cluster
---
If the managed cluster is not included in the placementrule, which will lead to observability not installed in this cluster.