[#observability-undesired-label-in-managedcluster]
== Undesired label value in _managedcluster_ resource

When you import a managed cluster, the observability components are installed by default. Your placement rule might resemble the following information: 

----
status:
  decisions:
  - clusterName: sample-managed-cluster
    clusterNamespace: sample-managed-cluster
----

If the managed cluster is not included in the placement rule, the observability components are not installed. 


[#symptom-observability-undesired-label-in-managedcluster]
=== Symptom: Undesired label value in managedcluster resource

If you find that the imported cluster is not included, the observability service for your managed cluster resource might be disabled. 

*Remember*: When you enable the service, the `vendor:OpenShift` label is added to represent the target managed cluster. Observability service is only supported on {ocp-short} managed cluster.

[#resolving-observability-undesired-label-in-managedcluster]
=== Resolving the problem: Undesired label value in managedcluster resource

If you have this problem, enable the observability service for the target managed cluster and update labels in the `managedcluster` resource.

Complete the following steps:
// HOW DOES THE USER GET TO THE RESOURCE? IS THERE A COMMAND THAT THEY SHOULD RUN?

. Change the `observability` parameter to `enabled` within placementrule:
----
  oc edit placementrule -n open-cluster-management-observability
----
. Verify that OpenShift is listed as vendor for the target managed cluster.
----
  oc get managedcluster <CLUSTER NAME> -o yaml
----
Value for `metadata.labels.vendor` should be `OpenShift`