[#troubleshooting-global-hub-must-gather]
= Troubleshooting with the _must-gather_ command 

[#symptom-errors-global-hub-mustgather]
== Symptom: Errors with {global-hub}

You might experience various errors with {global-hub}. You can run the `must-gather` command for troubleshooting issues with {global-hub}.

[#resolving-the-problem-must-gather]
== Resolving the problem: Running the _must-gather_ command for dubugging

Run the `must-gather` command to gather details, logs, and take steps in debugging issues. This debugging information is also useful when you open a support request. The `oc adm must-gather` CLI command collects the information from your cluster that is often needed for debugging issues, including:

* Resource definitions
* Service logs

[#global-hub-must-gather-prereq]
=== Prerequisites

You must meet the following prerequisites to run the `must-gather` command: 

* Access to the global hub and managed hub clusters as a user with the `cluster-admin` role.

* The {ocp-short} CLI (oc) installed.

[#global-hub-must-gather-running]
=== Running the must-gather command

Complete the following procedure to collect information by using the must-gather command:

. Learn about the `must-gather` command and install the prerequisites that you need by reading the link:https://docs.redhat.com/documentation/en-us/openshift_container_platform/4.16/html/support/gathering-cluster-data[Gathering data about your cluster] in the {ocp-short} documentation.

. Log in to your global hub cluster and run the following command:

+
[source,bash]
----
oc adm must-gather
----

. If you want to check your managed hub clusters, run the `must-gather` command on those clusters.

The following information is collected from the `must-gather` command: 

* Two peer levels: `cluster-scoped-resources` and `namespaces` resources.

* Sub-level for each: API group for the custom resource definitions for both cluster-scope and namespace-scoped resources.

* Next level for each: YAML file sorted by kind.

* For the global hub cluster, you can check the `PostgresCluster` and `Kafka` in the `namespaces` resources.

* For the global hub cluster, you can check the {global-hub} related pods and logs in `pods` of `namespaces` resources.

* For the managed hub cluster, you can check the {global-hub} agent pods and logs in `pods` of `namespaces` resources.
