[#troubleshooting-accessing-grafana]
= Troubleshooting accessing the Grafana 

[#symptom-global-hub-grafana]
== Symptom: {global-hub} Grafana cannot be accessed 

If {global-hub} is running on {ocp-short} 4.16, you cannot access the Grafana console due to the wrong `oauth-proxy` image. {product-title-short} 2.10.4 supports {ocp-short} 4.16, enabling you to get the `oauth-proxy` image from {product-title-short} 2.10.4.     

[#resolving-the-problem-manually-update-image]
== Resolving the problem: Manually update the image

To access your Grafana console, manually update the `oauth-proxy` image with the {product-title-short} bundle image. To update the `oauth-proxy` image, complete the following steps: 

. Get the correct `oauth-proxy` image from the `mch-image-manifest-xxx` by running the following:
+
----
oc get cm -n open-cluster-management mch-image-manifest-xxx -ojsonpath={.data.oauth_proxy_416_and_up} 
----
+
. Update the deployment image in the {global-hub} CSV with the correct image by running the following: 
+
----
oc edit csv multicluster-global-hub-operator-rh.v1.1.1 -n multicluster-global-hub 
----
+
. Find the value for `RELATED_IMAGE_OAUTH_PROXY` and replace it with the output you received from Step 1. 