[#troubleshooting-hub-cluster-metrics-missing]
= Troubleshooting hub cluster metrics missing

Hub cluster metrics might not be collected.

[#symptom-hub-cluster-metrics-missing]
== Symptom: Metrics for hub cluster is missing

If the metrics service is missing on the hub cluster, then metrics are not collected. 

[#identifying-the-problem-hub-cluster-metrics-missing]
== Identifying the problem: Metric for hub cluster is missing

Check for the metrics service on the hub cluster with the following command:

[source,bash]
----
oc get svc -n open-cluster-management hub-subscription-metrics
----

Results are displayed. If the `hub-subscription-metrics` is not listed, you must manually add the metric service.


[#resolving-the-problem-klusterlet-is-in-the-degraded-condition]
== Resolving the problem: Metric for hub cluster is missing

As a cluster administrator, create the metrics service for the hub cluster. Complete the following steps: 

. Create and apply the metrics `Service` resource
+
[source,bash]
----
oc apply -f -
----
+
[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hub-subscription-metrics
  name: hub-subscription-metrics
  namespace: open-cluster-management
spec:
  ports:
    - name: metrics
      port: 8381
      protocol: TCP
      targetPort: 8381
  selector:
    app: multicluster-operators-hub-subscription
  sessionAffinity: None
  type: ClusterIP
----

. Verify that the metrics service is created. Run the following command:
+
[source,bash]
----
oc get svc -n open-cluster-management hub-subscription-metrics
----

The metrics service is now available on the hub cluster.
