
[#troubleshopoting-cluster-with-already-exists-error]
= Troubleshooting cluster with already exists error

If you are unable to import an :ocp-short: cluster into :product-title-short: `MultiClusterHub` and receive an `AlreadyExists` error, follow the procedure to troubleshoot the problem.

[#symptom-cluster-already-exists-error-log]
== Symptom: Already exists error log when importing :ocp-short: cluster

An error log shows up when importing an :ocp-short: cluster into :product-title-short: `MultiClusterHub`:

----
error log:
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "klusterlets.operator.open-cluster-management.io" already exists
The cluster cannot be imported because its Klusterlet CRD already exists.
Either the cluster was already imported, or it was not detached completely during a previous detach process.
Detach the existing cluster before trying the import again."
----

[#identifying-problem-already-exists-ocp-import]
== Identifying the problem: Already exists when importing :ocp-short: cluster

Check if there are any :product-title-short:-related resources on the cluster that you want to import to new the :product-title-short: `MultiClusterHub` by running the following commands:

----
oc get all -n open-cluster-management-agent
oc get all -n open-cluster-management-agent-addon
----

[#resolving-problem-already-exists-ocp-import]
== Resolving the problem: Already exists when importing :ocp-short: cluster

Run the following link:https://github.com/stolostron/deploy/blob/master/hack/cleanup-managed-cluster.sh[`cleanup-managed-cluster.sh`] script on the managed cluster to remove pre-existing ACM resources:

----
#!/bin/bash
###############################################################################
# Copyright (c) 2020 Red Hat, Inc.
###############################################################################

if [ -z "${OPERATOR_NAMESPACE}" ]; then
OPERATOR_NAMESPACE="open-cluster-management-agent-addon"
fi

if [ -z "${KLUSTERLET_NAMESPACE}" ]; then
KLUSTERLET_NAMESPACE="open-cluster-management-agent"
fi

KUBECTL=oc

# Force delete klusterlet
echo "attempt to delete klusterlet"
${KUBECTL} delete klusterlet klusterlet --timeout=60s
${KUBECTL} delete namespace ${KLUSTERLET_NAMESPACE} --wait=false
echo "force removing klusterlet"
${KUBECTL} patch klusterlet klusterlet --type="json" -p '[{"op": "remove", "path":"/metadata/finalizers"}]'
echo "removing klusterlet crd"
${KUBECTL} delete crd klusterlets.operator.open-cluster-management.io --timeout=30s

# Force delete all component CRDs if they still exist
component_crds=(
applicationmanagers.agent.open-cluster-management.io
certpolicycontrollers.agent.open-cluster-management.io
iampolicycontrollers.agent.open-cluster-management.io
policycontrollers.agent.open-cluster-management.io
searchcollectors.agent.open-cluster-management.io
workmanagers.agent.open-cluster-management.io
appliedmanifestworks.work.open-cluster-management.io
)

for crd in "${component_crds[@]}"; do
echo "force delete all CustomResourceDefinition ${crd} resources..."
for resource in `${KUBECTL} get ${crd} -o name -n ${OPERATOR_NAMESPACE}`; do
echo "attempt to delete ${crd} resource ${resource}..."
${KUBECTL} delete ${resource} -n ${OPERATOR_NAMESPACE} --timeout=30s
echo "force remove ${crd} resource ${resource}..."
${KUBECTL} patch ${resource} -n ${OPERATOR_NAMESPACE} --type="json" -p '[{"op": "remove", "path":"/metadata/finalizers"}]'
done
echo "force delete all CustomResourceDefinition ${crd} resources..."
${KUBECTL} delete crd ${crd}
done

${KUBECTL} delete namespace ${OPERATOR_NAMESPACE}
----

