[#troubleshooting-the-search-collector-pod]
= Troubleshooting the search collector pod

The `search-collector` crashes and the status displayed is a `CrashLoopback` error.

[#symptom-reinstallation-failure-search]
== Symptom: Reinstallation failure

Afer you install IBM Cloud Pak for Multicloud Manager, the `search-collector` status displays a `CrashLoopback` error. 

[#resolving-the-problem-reinstallation-failure-search]
== Resolving the problem: Reinstallation failure

You must increase the memory limit in the `search-collector` deployment. Complete the following steps to increase the memory limit:

. Log in to your {ocp} hub cluster. 
. Access the `search-collector` deployment by running the following command:
+
----
oc edit deployment $(oc get deployment -l component=search-collector -o jsonpath='{.items[0].metadata.name}')
----

. Edit the container's resource limit for memory using the `.spec.template.spec.containers.resources.limits` field:
+
----
spec:
  template:
    spec:
      containers:
        resources:
          limits:
            memory: 863Mi
          requests:
            cpu: 25m
            memory: 64Mi
----

. Apply and save changes to your deployment.

The memory limits for the `search-collector` deployment are increased.
