[#troubleshooting-shared-memory]
= Troubleshooting PostgreSQL shared memory error

If you have a large environment, you might encounter a PostgreSQL shared memory error that impacts search results and the topology view for applications.
 
[#symptom-shared-memory]
== Symptom: PostgreSQL shared memory error

An error message resembling the following appears in the `search-api` logs: `ERROR: could not resize shared memory segment "/PostgreSQL.1083654800" to 25031264 bytes: No space left on device (SQLSTATE 53100)`

[#resolving-shared-memory]
== Resolving the problem: PostgreSQL shared memory error

To resolve the issue, increase the database memory. Add environment variables to specify a value for your resource variables. For example, increase the memory for the following variables, `POSTGRESQL_EFFECTIVE_CACHE_SIZE` and `POSTGRESQL_SHARED_BUFFERS`. View the following `Search` custom resource:
+
[source,yaml]
----
apiVersion: search.open-cluster-management.io/v1alpha1
kind: Search
metadata:
  name: search-v2-operator
  namespace: open-cluster-management
spec:
  dbConfig: tuning-config
  deployments:
    collector:
      resources: <1>
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 250m
          memory: 64Mi
    indexer:
      replicaCount: 3
    database: <2>
        envVar:
          - name: POSTGRESQL_EFFECTIVE_CACHE_SIZE
            value: 1024MB
          - name: POSTGRESQL_SHARED_BUFFERS
            value: 512MB
          - name: WORK_MEM
            value: 128MB
    queryapi:
      arguments: <3>
      - -v=3
----

. Run the following command to restart the `postgres` and `api` pod.
+
----
oc delete pod search-postgres-xyz search-api-xzy
----

. To verify your changes, open the `search-postgres` YAML file and confirm that the changes you made to `postgresql.conf:` are present by running the following command:
+
----
oc get cm search-postgres -n ocm -o yaml
----

See link:../observability/search_intro.adoc#search-customization[Search customization and configurations] for more information on adding environment variables.