[#troubleshooting-cluster-creation-on-vmware-vsphere]
= Troubleshooting cluster creation on VMware vSphere

If you experience a problem when creating a {ocp} cluster on VMware vSphere, see the following troubleshooting information to see if one of them addresses your problem.

== Managed cluster creation fails with certificate IP SAN error

[#symptom-vsphere-fails-cert-ip-san]
=== Symptom: Managed cluster creation fails with certificate IP SAN error

After creating a new {ocp} cluster on VMware vSphere, the cluster fails with an error message that indicates a certificate IP SAN error.  

[#identifying-the-problem-vsphere-fails-cert-ip-san]
=== Identifying the problem: Managed cluster creation fails with certificate IP SAN error

The deployment of the managed cluster fails and returns the following errors in the deployment log:

----
time="2020-08-07T15:27:55Z" level=error msg="Error: error setting up new vSphere SOAP client: Post https://147.1.1.1/sdk: x509: cannot validate certificate for xx.xx.xx.xx because it doesn't contain any IP SANs"
time="2020-08-07T15:27:55Z" level=error
----

[#resolving-the-problem-vsphere-fails-cert-ip-san]
=== Resolving the problem: Managed cluster creation fails with certificate IP SAN error

Use the VMware vCenter server fully-qualified host name instead of the IP address in the provider connection. You can also update the VMware vCenter CA certificate to contain the IP SAN. 

== Managed cluster creation fails with unknown certificate authority

[#symptom-vsphere-fails-cert-unknown]
=== Symptom: Managed cluster creation fails with unknown certificate authority

After creating a new {ocp} cluster on VMware vSphere, the cluster fails because the certificate is signed by an unknown authority.

[#identifying-the-problem-vsphere-fails-cert-unknown]
=== Identifying the problem: Managed cluster creation fails with unknown certificate authority

The deployment of the managed cluster fails and returns the following errors in the deployment log:

----
Error: error setting up new vSphere SOAP client: Post https://vspherehost.com/sdk: x509: certificate signed by unknown authority"
----

[#resolving-the-problem-vsphere-fails-cert-unknown]
=== Resolving the problem: Managed cluster creation fails with unknown certificate authority

Ensure you entered the correct certificate from the certificate authority when creating the provider connection.

== Managed cluster creation fails with expired certificate

[#symptom-vsphere-fails-cert-expired]
=== Symptom: Managed cluster creation fails with expired certificate

After creating a new {ocp} cluster on VMware vSphere, the cluster fails because the certificate is expired or is not yet valid.

[#identifying-the-problem-vsphere-fails-cert-expired]
=== Identifying the problem: Managed cluster creation fails with expired certificate

The deployment of the managed cluster fails and returns the following errors in the deployment log:

----
x509: certificate has expired or is not yet valid
----

[#resolving-the-problem-vsphere-fails-cert-expired]
=== Resolving the problem: Managed cluster creation fails with expired certificate

Ensure that the time on your ESXi hosts is synchronized.

==Managed cluster creation fails with insufficient privilege for tagging

[#symptom-vsphere-fails-tag]
=== Symptom: Managed cluster creation fails with insufficient privilege for tagging

After creating a new {ocp} cluster on VMware vSphere, the cluster fails because there is insufficient privilege to use tagging.

[#identifying-the-problem-vsphere-fails-tag]
=== Identifying the problem: Managed cluster creation fails with insufficient privilege for tagging

The deployment of the managed cluster fails and returns the following errors in the deployment log:

----
time="2020-08-07T19:41:58Z" level=debug msg="vsphere_tag_category.category: Creating..."
time="2020-08-07T19:41:58Z" level=error
time="2020-08-07T19:41:58Z" level=error msg="Error: could not create category: POST https://vspherehost.com/rest/com/vmware/cis/tagging/category: 403 Forbidden"
time="2020-08-07T19:41:58Z" level=error
time="2020-08-07T19:41:58Z" level=error msg="  on ../tmp/openshift-install-436877649/main.tf line 54, in resource \"vsphere_tag_category\" \"category\":"
time="2020-08-07T19:41:58Z" level=error msg="  54: resource \"vsphere_tag_category\" \"category\" {"
----

[#resolving-the-problem-vsphere-fails-tag]
=== Resolving the problem: Managed cluster creation fails with insufficient privilege for tagging

Ensure that your VMware vCenter required account privileges are correct. See https://docs.openshift.com/container-platform/4.5/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#registry-removed_installing-vsphere-installer-provisioned[Image registry removed during information] for more information. 

== Managed cluster creation fails with invalid dnsVIP

[#symptom-vsphere-fails-dnsvip]
=== Symptom: Managed cluster creation fails with invalid dnsVIP

After creating a new {ocp} cluster on VMware vSphere, the cluster fails because there is an invalid dnsVIP.

[#identifying-the-problem-vsphere-fails-dnsvip]
=== Identifying the problem: Managed cluster creation fails with invalid dnsVIP

If you see the following message when trying to deploy a new managed cluster with VMware vSphere, it is because you have an older {ocp-short} release image that does not support VMware Installer Provisioned Infrastructure (IPI):

----
failed to fetch Master Machines: failed to load asset \\\"Install Config\\\": invalid \\\"install-config.yaml\\\" file: platform.vsphere.dnsVIP: Invalid value: \\\"\\\": \\\"\\\" is not a valid IP
----

[#resolving-the-problem-vsphere-fails-dnsvip]
=== Resolving the problem: Managed cluster creation fails with invalid dnsVIP

Select a release image from a later version of {ocp-short} that supports VMware Installer Provisioned Infrastructure.  

== Managed cluster creation fails with incorrect network type

[#symptom-vsphere-fails-network]
=== Symptom: Managed cluster creation fails with incorrect network type

After creating a new {ocp} cluster on VMware vSphere, the cluster fails because there is an incorrect network type specified.

[#identifying-the-problem-vsphere-fails-network]
=== Identifying the problem: Managed cluster creation fails with incorrect network type

If you see the following message when trying to deploy a new managed cluster with VMware vSphere, it is because you have an older {ocp-short} image that does not support VMware Installer Provisioned Infrastructure (IPI):

----
time="2020-08-11T14:31:38-04:00" level=debug msg="vsphereprivate_import_ova.import: Creating..."
time="2020-08-11T14:31:39-04:00" level=error
time="2020-08-11T14:31:39-04:00" level=error msg="Error: rpc error: code = Unavailable desc = transport is closing"
time="2020-08-11T14:31:39-04:00" level=error
time="2020-08-11T14:31:39-04:00" level=error
time="2020-08-11T14:31:39-04:00" level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply Terraform: failed to complete the change"
----

[#resolving-the-problem-vsphere-fails-network]
=== Resolving the problem: Managed cluster creation fails with incorrect network type

Select a valid VMware vSphere network type for the specified VMware cluster. 

== Managed cluster creation fails with an error processing disk changes

[#symptom-vsphere-fails-disk]
=== Symptom: Adding the VMware vSphere managed cluster fails due to an error processing disk changes

After creating a new {ocp} cluster on VMware vSphere, the cluster fails because there is an error when processing disk changes.

[#identifying-the-problem-vsphere-fails-disk]
=== Identifying the problem: Adding the VMware vSphere managed cluster fails due to an error processing disk changes

A message similar to the following is displayed in the logs:

----
ERROR                                              
ERROR Error: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: ServerFaultCode: NoPermission: RESOURCE (vm-71:2000), ACTION (queryAssociatedProfile): RESOURCE (vm-71), ACTION (PolicyIDByVirtualDisk) 
Resolving the problem:
Use the VMware vSphere client to give the user All privileges for Profile-driven Storage Privileges
[#resolving-the-problem-vsphere-fails-network]
----

=== Resolving the problem: Adding the VMware vSphere managed cluster fails due to an error processing disk changes

Select a valid VMware vSphere network type for the specified VMware cluster. 



