[#trouble-import-fail-secret]
= Troubleshooting a failed imported cluster secret after upgrade 

[#symptom-import-fail-secret]
== Symptom: Troubleshooting a failed imported cluster secret after upgrade

After an upgrade from {product-title} version 2.0.0 to version 2.0.1, your cluster import in the {product-title-short} console might fail with the following message: 

----
Failed to fetch import yaml secret
----

[#identify-import-fail-secret]
== Identifying the problem: Troubleshooting a failed imported cluster secret after upgrade

To confirm that the issue can be resolved by the steps that follow, complete the following steps:

. Run the following command to change to your {product-title-short} installation namespace:
+
----
oc project <namespace>
----
+
Replace _<namespace>_ with your {product-title-short} installation namespace. If you used the default value, it is `open-cluster-management`.

. Run the following command to determine if the `managedcluster-import-controller` has the required permission:
+
----
oc get $(oc get clusterrole -o name | grep managedcluster-import-controller) -o yaml| grep apiservers
----
+
If the command returns an empty response, then complete the step in the _Resolving the problem_ section to fix the problem.

[#resolving-import-fail-secret]
== Resolving the problem: Troubleshooting a failed imported cluster secret after upgrade

To resolve the problem, enter the following command to restart the `multicluster-operators-standalone-subscription` service:

----
oc delete $(oc get pod -o name | grep multicluster-operators-standalone-subscription)
----

