[#trouble-submariner-general]
= Troubleshooting Submariner not connecting after installation

If Submariner does not run correctly after you configure it, see the following steps to identify and resolve the problem. 

[#symptom-trouble-submariner-general]
== Symptom: Submariner not connecting after installation

Your Submariner network is not communicating after installation.

[#identifying-trouble-submariner-general]
== Identifying the problem: Submariner not connecting after installation

If the network connectivity is not established after deploying Submariner, begin the troubleshooting steps. Note that it might take several minutes for the processes to complete when you deploy Submariner.

[#resolving-trouble-submariner-general]
== Resolving the problem: Submariner not connecting after installation

When Submariner does not run correctly after deployment, see the following steps and resources to diagnose the problem:

. Check for the following requirements to determine whether the components of Submariner deployed correctly:
+
* The `submariner-addon` pod is running in the `open-cluster-management` namespace of your hub cluster. 

* The following pods are running in the `submariner-operator` namespace of each managed cluster:
+
** submariner-addon
** submariner-gateway
** submariner-routeagent
** submariner-operator
** submariner-globalnet (only if Globalnet is enabled in the ClusterSet)
** submariner-lighthouse-agent
** submariner-lighthouse-coredns
** submariner-networkplugin-syncer (only if the specified CNI value is `OVNKubernetes`)
** submariner-metrics-proxy

. Run the `subctl diagnose all` command to check the status of the required pods, with the exception of the `submariner-addon` pods. 

. Open an issue. If the other steps do not identify the problem, open an issue with the following information: 
+
.. Run the `subctl gather` to collect all the relevant Submariner logs and add them to the issue. A directory is created in the path you ran the command that contains the logs. Compress that directory into a .tar.gz archive and attach it to the issue.

.. Capture the information for the `submariner` instance of the `ManagedClusterAddon` resource type, and for the `submariner` instance of the `SubmarinerConfig` resource type from the `ManagedCluster` namespace on the hub cluster.

.. Provide the following information in your issue, as well as the other template information:
+
* What happened?
* What you expected to happen?
* How do you reproduce it (as minimally and precisely as possible)?
* Anything else that we need to know?
* Environment information:
** {product-title-version} version
** Diagnose information gathered (use the `subctl diagnose all` command)
** Gather information (use the `subctl gather` command)
** Cloud provider or hardware configuration:
*** OS (use the `cat /etc/os-release` command)
*** Kernel (use the `uname -a` command)
** Install tools
** Other environment information that might be useful
