[#grc-policy-framework-pod-crash]
= Troubleshooting _governance-policy-framework-addon_ pod on managed clusters

The `governance-policy-framework-addon` pod crashes on managed clusters.

[#symptom-grc-policy-framework-pod]
== Symptom: Troubleshooting _governance-policy-framework-addon_ pod on managed clusters

When you run out of memory because there are too many policy events created from continuous compliance changes, the `governance-policy-framework-addon` pod crashes.

You might receive the following pod status:

[source,bash]
----
OOMKilled
----

[#resolving-grc-policy-framework-pod]
== Resolving the problem: Troubleshooting _governance-policy-framework-addon_ pod on managed clusters

To resolve this error, you must reduce the cached memory for the pod. Complete the following steps:

. To reduce the memory cache for the fields to the bare minimum value, run the following command:

+
[source,bash]
----
func TransformStripManagedFields() toolscache.TransformFunc
----
//whats the minimum version? 

. Limit the events that are cached by configuring your policy controllers to send events with a label that denotes it as a status update. The `status-sync` controller uses the label selector to watch API request.
//is there an example of the configuration? 

//is there a verification step to make sure the policy events are no longer cached?