[#observability-undesired-label-in-managedcluster]
= Undesired label value in managedcluster resource

When you import a managed cluster, the observability components are installed by default. Your placement rule might resemble the following information: 

----
status:
  decisions:
  - clusterName: sample-managed-cluster
    clusterNamespace: sample-managed-cluster
----

If the managed cluster is not included in the placement rule, the observability components are not installed. 


[#symptom-observability-undesired-label-in-managedcluster]
== Symptom: Undesired label value in managedcluster resource

If you find that the imported cluster is not included, the observability service for your managed cluster resource might be disabled. 

*Remember*: When you enable the service, the `vendor:OpenShift` label is added to represent the target managed cluster. Observability service is only supported on {ocp-short} managed cluster.

[#resolving-observability-undesired-label-in-managedcluster]
== Resolving the problem: Undesired label value in managedcluster resource

If you have this problem, enable the observability service for the target managed cluster and update labels in the `managedcluster` resource.

Complete the following steps:

. Log in to your {product-title-short} cluster.
. Change the `observability` parameter value to `enabled` by updating the placement rule. Run the following command:
+
----
oc edit placementrule -n open-cluster-management-observability
----

. Verify that OpenShift is listed as vendor for the target managed cluster by running the following command:
+
----
oc get managedcluster <CLUSTER NAME> -o yaml
----
+
Update the `metadata.labels.vendor` parameter value to `OpenShift`.
