[#troubleshooting-cluster-creation-on-openstack]
= Troubleshooting cluster creation on OpenStack

If you experience a problem when creating a {ocp} cluster on OpenStack, see the following troubleshooting information to see if one of them addresses your problem. 

== Managed cluster creation fails with unknown authority error

[#symptom-openstack-fails]
=== Symptom: Managed cluster creation fails with unknown authority error

After creating a new {ocp} cluster on OpenStack using self-signed certificates, the cluster fails with the an error message that indicates an unknown authority error.

[#identifying-the-problem-openstack-fails]
=== Identifying the problem: Managed cluster creation fails with unknown authority error

The deployment of the managed cluster fails and returns the following error message:

`x509: certificate signed by unknown authority`

[#resolving-the-problem-openstack-fails]
=== Resolving the problem: Managed cluster creation fails with unknown authority error

Verify that the following steps are configured correctly:

. The `clouds.yaml` file must specify the path to the `cabundle` file in the `cacerts` parameter. The `cacert` is passed to the OpenShift installer when generating the ignition shim. See the following example:

[source,yaml]
----
clouds:
openstack:
cacert: "/etc/pki/ca-trust/source/anchors/ca.crt"
----

. The `certificatesSecretRef` paremeter must reference a secret with a file name matching the `cacert` file. See the following example:

[source,yaml]
----
spec:
baseDomain: dev09.red-chesterfield.com
clusterName: txue-osspoke
platform:
openstack:
cloud: openstack
credentialsSecretRef:
name: txue-osspoke-openstack-creds
certificatesSecretRef:
name: txue-osspoke-openstack-certificatebundle
----

To create a secret with a matching file name, run the following command:

```
oc create secret generic txue-osspoke-openstack-certificatebundle --from-file=ca.crt=ca.crt.pem -n $CLUSTERNAME
```

. The size of the `clouds.yaml` `cacert` must be less than 63 thousand bytes.




