[#troubleshooting-shared-memory]
= Troubleshooting PostgreSQL shared memory error

If you have a large environment, you might encounter a PostgreSQL shared memory error that impacts search results and the topology view for applications.
 
[#symptom-shared-memory]
== Symptom: PostgreSQL shared memory error

An error message resembling the following appears in the `search-api` logs: `ERROR: could not resize shared memory segment "/PostgreSQL.1083654800" to 25031264 bytes: No space left on device (SQLSTATE 53100)`

[#resolving-shared-memory]
== Resolving the problem: PostgreSQL shared memory error

To resolve the issue, update the PostgreSQL resources found in the `search-postgres` ConfigMap. Complete the following steps to update the resources:

. Run the following command to switch to the `open-cluster-management` project:
+
----
oc project open-cluster-management
----

. Increase the `search-postgres` pod memory. The following command increases the memory to `16Gi`:
+
----
oc patch search -n open-cluster-management search-v2-operator --type json -p '[{"op": "add", "path": "/spec/deployments/database/resources", "value": {"limits": {"memory": "16Gi"}, "requests": {"memory": "32Mi", "cpu": "25m"}}}]'
----

. Run the following command to prevent the search operator from overwriting your changes:
+
----
oc annotate search search-v2-operator search-pause=true
----

. Run the following command to update the resources in the `search-postgres` YAML file:
+
----
oc edit cm search-postgres -n open-cluster-management
----
+
See the following example for increasing resources:
+
[source,yaml]
----
  postgresql.conf: |-
    work_mem = '128MB' # Higher values allocate more memory
    max_parallel_workers_per_gather = '0' # Disables parallel queries
    shared_buffers = '1GB' # Higher values allocate more memory
----
+
Make sure to save your changes before exiting.

. Run the following command to restart the `postgres` and `api` pod.
+
----
oc delete pod search-postgres-xyz search-api-xzy
----

. To verify your changes, open the `search-postgres` YAML file and confirm that the changes you made to `postgresql.conf:` are present by running the following command:
+
----
oc get cm search-postgres -n open-cluster-management -o yaml
----

See link:../observability/search_console.adoc#search-customization[Search customization and configurations] for more information on adding environment variables.
