[#troubleshooting-grafana]
= Troubleshooting grafana

When you query some time-consuming metrics in the Grafana explorer, you might encounter a `Gateway Time-out` error.

[#symptom-grafana-explorer-gateway-timeout]
== Symptom: Grafana explorer gateway timeout

If you hit the `Gateway Time-out` error when you query some time-consuming metrics in the Grafana explorer, it is possible that the timeout is caused by the `multicloud-console` route in the `open-cluster-management` namespace.

[#resolving-grafana-explorer-gateway-timeout]
== Resolving the problem: Configure the _multicloud-console_ route

If you have this problem, complete the following steps:

. Verify that the default configuration of Grafana has expected timeout settings:
.. To verify that the default timeout setting of Grafana, run the following command:
+
----
oc get secret grafana-config -n open-cluster-management-observability -o jsonpath="{.data.grafana\.ini}" | base64 -d | grep dataproxy -A 4
----
+
The following timeout settings should be displayed:
+
----
[dataproxy]
timeout = 300
dial_timeout = 30
keep_alive_seconds = 300
----
.. To verify the default data source query timeout for Grafana, run the following command: 
+
----
oc get secret/grafana-datasources -n open-cluster-management-observability -o jsonpath="{.data.datasources\.yaml}" | base64 -d | grep queryTimeout
----
+
The following timeout settings should be displayed:
+
----
queryTimeout: 300s
----
. If you verified the default configuration of Grafana has expected timeout settings, then you can configure the `multicloud-console` route in the `open-cluster-management` namespace by running the following commmand:
+
----
oc annotate route multicloud-console -n open-cluster-management --overwrite haproxy.router.openshift.io/timeout=300s
----

Refresh the Grafana page and try to query the metrics again. The `Gateway Time-out` error is no loonger displayed.
