[#troubleshooting-imported-clusters-offline-after-certificate-change]
= Troubleshooting imported clusters offline after certificate change

Installing a custom `apiserver` certificate is supported, but one or more clusters that were imported before you changed the certificate information can have an `offline` status. 

[#symptom-clusters-offline-after-certificate-change]
== Symptom: Clusters offline after certificate change

After you complete the procedure for updating a certificate secret, one or more of your clusters that were online are now displaying an `offline` status in the {product-title} console.

[#identifying-clusters-offline-after-certificate-change]
== Identifying the problem: Clusters offline after certificate change 

After updating the information for a custom API server certificate, clusters that were imported and running before the new certificate are now in an `offline` state. 

The errors that indicate that the certificate is the problem are found in the logs for the pods in the `open-cluster-management-agent` namespace of the offline managed cluster. The following examples are similar to the errors that are displayed in the logs: 

*Log of `work-agent`:*

----
E0917 03:04:05.874759       1 manifestwork_controller.go:179] Reconcile work test-1-klusterlet-addon-workmgr fails with err: Failed to update work status with err Get "https://api.aaa-ocp.dev02.location.com:6443/apis/cluster.management.io/v1/namespaces/test-1/manifestworks/test-1-klusterlet-addon-workmgr": x509: certificate signed by unknown authority
E0917 03:04:05.874887       1 base_controller.go:231] "ManifestWorkAgent" controller failed to sync "test-1-klusterlet-addon-workmgr", err: Failed to update work status with err Get "api.aaa-ocp.dev02.location.com:6443/apis/cluster.management.io/v1/namespaces/test-1/manifestworks/test-1-klusterlet-addon-workmgr": x509: certificate signed by unknown authority
E0917 03:04:37.245859       1 reflector.go:127] k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.ManifestWork: failed to list *v1.ManifestWork: Get "api.aaa-ocp.dev02.location.com:6443/apis/cluster.management.io/v1/namespaces/test-1/manifestworks?resourceVersion=607424": x509: certificate signed by unknown authority
----

*Log of `registration-agent`:*

----
I0917 02:27:41.525026       1 event.go:282] Event(v1.ObjectReference{Kind:"Namespace", Namespace:"open-cluster-management-agent", Name:"open-cluster-management-agent", UID:"", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'ManagedClusterAvailableConditionUpdated' update managed cluster "test-1" available condition to "True", due to "Managed cluster is available"
E0917 02:58:26.315984       1 reflector.go:127] k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1beta1.CertificateSigningRequest: Get "https://api.aaa-ocp.dev02.location.com:6443/apis/cluster.management.io/v1/managedclusters?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dtest-1&resourceVersion=607408&timeout=9m33s&timeoutSeconds=573&watch=true"": x509: certificate signed by unknown authority
E0917 02:58:26.598343       1 reflector.go:127] k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.ManagedCluster: Get "https://api.aaa-ocp.dev02.location.com:6443/apis/cluster.management.io/v1/managedclusters?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dtest-1&resourceVersion=607408&timeout=9m33s&timeoutSeconds=573&watch=true": x509: certificate signed by unknown authority
E0917 02:58:27.613963       1 reflector.go:127] k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.ManagedCluster: failed to list *v1.ManagedCluster: Get "https://api.aaa-ocp.dev02.location.com:6443/apis/cluster.management.io/v1/managedclusters?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dtest-1&resourceVersion=607408&timeout=9m33s&timeoutSeconds=573&watch=true"": x509: certificate signed by unknown authority
----

[#resolving-clusters-offline-after-certificate-change]
== Resolving the problem: Clusters offline after certificate change

If your managed cluster is `local-cluster`, or your managed cluster was created by using {product-title}, your cluster resynchronizes every 10 minutes and you must 10 minutes or longer for your managed cluster to reimport.

To reimport your managed cluster immediately, you can delete your managed cluster import secret on the hub cluster and reimport it by using {product-title-short} by running the following command:

----
oc delete secret -n <cluster_name> <cluster_name>-import
----
+
Replace `<cluster_name>` with the name of the managed cluster that you want to import.

If you want to reimport a managed cluster that was imported by using {product-title-short}, run the following command to import the managed cluster again:

. On the hub cluster, recreate the managed cluster import secret by running the following command:
+
----
oc delete secret -n <cluster_name> <cluster_name>-import
----
+
Replace `<cluster_name>` with the name of the managed cluster that you want to import.

. On the hub cluster, expose the managed cluster import secret to a YAML file by running the following command:
+
----
oc get secret -n <cluster_name> <cluster_name>-import -ojsonpath='{.data.import\.yaml}' | base64 --decode  > import.yaml
----
+
Replace `<cluster_name>` with the name of the managed cluster that you want to import.

. On the managed cluster, apply the `import.yaml` fileby running the following command:
+
----
oc apply -f import.yaml
----
