[#troubleshooting-oadp-crd]
= Troubleshooting OADP custom resoure definitions

The `MultiClusterHub` resource overwrites Velero and the OADP custom resource definitions with resources that are shipped and supported by the backup and restore component, even if the `cluster-backup` flag is set to `false`.
 
[#symptom-oadp-crd]
== Symptom: OADP custom resoure definitions

If you try to install the OADP operator manually, your installation fails if the version you are installing does not use the same custom resource definitions that are installed by the backup and restore component.

[#resolving-oadp-crd]
== Resolving the problem: OADP custom resoure definitions

To temporarily work around the issue, you can pause the `MultiClusterHub` reconciliation in test environments. Run the following command before installing the OADP operator manually, which prevents the `MultiClusterHub` from updating the custom resource definitions installed by your OADP operator version:

----
oc annotate mch multiclusterhub -n open-cluster-management mch-pause=true
----