[#troubleshooting-postgresql]
= Troubleshooting the PostgreSQL connection

When the RHACM hub has issues connecting to the PostgreSQL server, you may see Kubernetes events in the RHACM namespace with the following command:

----
oc -n open-cluster-management get events --field-selector reason=OCMComplianceEventsDBError
----

The details are limited and will instruct you to view the Governance Policy Propagator logs for further details. To do so you may use the following command:

----
oc -n open-cluster-management logs -l name=governance-policy-propagator -f
----
 

In the logs, you may see an error message such as this, which indicates the password is not correctly specified.

2024-03-05T12:17:14.500-0500	info	compliance-events-api	complianceeventsapi/complianceeventsapi_controller.go:261	The database connection failed: pq: password authentication failed for user "rhacm-policy-compliance-history"

[#symptom-cluster-rotating-agents]
== Symptom: Expired credentials for agents



[#resolving-cluster-rotating-agents]
== Resolving the problem: Manually rotate credentials for agents

