[#troubleshooting-ocp-311-cluster-import-failure]
= Troubleshooting OpenShift Container Platform version 3.11 cluster import failure  

[#symptom-ocp-311-cluster-import-failure]
== Symptom: OpenShift Container Platform version 3.11 cluster import failure

After you attempt to import a {ocp} version 3.11 cluster, the import fails with a log message that resembles the following content:

----
customresourcedefinition.apiextensions.k8s.io/klusterlets.operator.open-cluster-management.io configured
clusterrole.rbac.authorization.k8s.io/klusterlet configured
clusterrole.rbac.authorization.k8s.io/open-cluster-management:klusterlet-admin-aggregate-clusterrole configured
clusterrolebinding.rbac.authorization.k8s.io/klusterlet configured
namespace/open-cluster-management-agent configured
secret/open-cluster-management-image-pull-credentials unchanged
serviceaccount/klusterlet configured
deployment.apps/klusterlet unchanged
klusterlet.operator.open-cluster-management.io/klusterlet configured
Error from server (BadRequest): error when creating "STDIN": Secret in version "v1" cannot be handled as a Secret:
v1.Secret.ObjectMeta:
v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 1313, error found in #10 byte of ...|dhruy45="},"kind":"|..., bigger context ...|tye56u56u568yuo7i67i67i67o556574i"},"kind":"Secret","metadata":{"annotations":{"kube|...
---- 

[#identifying-ocp-311-cluster-import-failure]
== Identifying the problem: OpenShift Container Platform version 3.11 cluster import failure 

This often occurs because the installed version of the `kubectl` command-line tool is 1.11, or earlier. Run the following command to see which version of the `kubectl` command-line tool you are running:

----
kubectl version
----

If the returned data lists version 1.11, or earlier, complete one of the fixes in _Resolving the problem: OpenShift Container Platform version 3.11 cluster import failure_.

[#resolving-ocp-311-cluster-import-failure]
== Resolving the problem: OpenShift Container Platform version 3.11 cluster import failure 

You can resolve this issue by completing one of the following procedures:

* Install the latest version of the `kubectl` command-line tool.
+
. Download the latest version of the `kubectl` tool from: https://kubernetes.io/docs/tasks/tools/install-kubectl/[Install and Set Up kubectl] in the Kubernetes documentation.  
. Import the cluster again after upgrading your `kubectl` tool.

* Run a file that contains the import command.
+
. Start the procedure in link:../manage_cluster/import_cli.adoc#importing-a-managed-cluster-with-the-cli[Importing a managed cluster with the CLI].

. When you create the command to import your cluster, copy that command into a YAML file named `import.yaml`.

. Run the following command to import the cluster again from the file:
+
----
oc apply -f import.yaml
----
