[#trouble-import-fail-secret]
= Troubleshooting a failed imported cluster secret after upgrade 

[#symptom-import-fail-secret]
== Symptom: Troubleshooting a failed imported cluster secret after upgrade

After an upgrade, your cluster import in the {product-title} console might fail with the following message: 

----
Failed to fetch import yaml secret
----

[#identify-import-fail-secret]
== Identifying the problem: Troubleshooting a failed imported cluster secret after upgrade

To confirm that the issue can be resolved by the steps that follow, complete the following steps:
. Run the following command to change to your project namespace:
+
----
oc project <namespace>
----
+
Replace _<namespace>_ with your project namespace.

. Run the following command to determine if the `managedcluster-import-controller` is running:
+
----
oc get $(oc get clusterrole -o name | grep managedcluster-import-controller) -o yaml| grep apiservers
----
+
If the command returns an empty response, then complete the steps in the _Resolving the problem_ section to fix the problem.

[#resolving-import-fail-secret]
== Resolving the problem: Troubleshooting a failed imported cluster secret after upgrade

To resolve the problem, enter the following command to restart the `multicluster-operators-standalone-subscription` service:
+
----
oc delete $(oc get pod -o name | grep multicluster-operators-standalone-subscription)
----
Replace _name_ with the name of the pod that you were trying to import.

