[#troubleshooting-an-offline-cluster]
= Troubleshooting an offline cluster

There are a few common causes for a cluster showing an offline status. 

[#symptom-cluster-offline]
== Symptom: Cluster status is offline

After you complete the procedure for creating a cluster, you cannot access it from the {product-title-short} console, and it shows a status of `offline`.

[#resolving-cluster-offline]
== Resolving the problem: Cluster status is offline

. Determine if the managed cluster is available. You can check this in the _Clusters_ area of the {product-title-short} console. 

+
If it is not available, try restarting the managed cluster.

. If the managed cluster status is still offline, complete the following steps:

.. Run the `oc get managedcluster <cluster_name> -o yaml` command on the hub cluster. Replace `<cluster_name>` with the name of your cluster.
.. Find the `status.conditions` section.
.. Check the messages for `type: ManagedClusterConditionAvailable` and resolve any problems. 

