[#global-hub-upgrade-postgres]
= Recovering data from the upgraded built-in PostgreSQL (Deprecated)


Starting with {global-hub} version 1.4.0, the built-in Postgres database is upgraded to version 16. This upgrade replaces the earlier `multicluster-global-hub-postgres` instance with the new `multicluster-global-hub-postgressql` instance.

By default, this upgrade automatically re-syncs real-time data, such as `policies` and `clusters`, to the new Postgres instance. Historical data, such as `event` and `history` tables, are not automatically recovered.

If you want to keep historical data, complete the following sections: 

* <<restoring-data, Restoring historical data>>
* <<deleting-legacy-postgres, Deleting legacy built-in postgres data>>

[#restoring-data]
== Restoring historical data

When the {global-hub} upgrade to version 1.4.0 removes your historical data, recover your data by completing the following steps:

. Clone the {acm} Git repository to access the shell script that you need to recover your data by running the following command: 

+
[source,bash]
----
git clone -b release-2.13 https://github.com/stolostron/multicluster-global-hub.git
----

. Restore your history tables by completing the following steps: 

.. If the default namespace is `multicluster-global-hub`, run the following shell script: 

+
[source,bash]
----
./doc/upgrade/restore_history_tables.sh
----

.. If the namespace is not specified as `multicluster-global-hub`, set the {global-hub} namespace when you run the following shell script: 

+
[source,bash]
----
./doc/upgrade/restore_history_tables.sh <1>
----
<1> The {global-hub} that you installed. 

. Restore your event tables by completing the following steps: 

.. If the default namespace is `multicluster-global-hub`, run the following shell script: 

+
[source,bash]
----
./doc/upgrade/restore_event_tables.sh
----

.. If the namespace is not specified as `multicluster-global-hub`, set the {global-hub} namespace when you run the following shell script: 

+
[source,bash]
----
./doc/upgrade/restore_event_tables.sh <1>
----
<1> The {global-hub} that you installed. 

[#deleting-legacy-postgres]
== Deleting legacy built-in Postgres data

After {global-hub} upgrades to version 1.4.0, it switches to the new built-in Postgres instance. The global hub operator does not automatically delete resources associated with the legacy Postgres instance. To delete the legacy Postgres resources, complete the following steps:

. If the default namespace is `multicluster-global-hub`, run the following shell script: 

+
[source,bash]
----
./doc/upgrade/cleanup_legacy_postgres.sh
----

. If the namespace is not specified as `multicluster-global-hub`, set the {global-hub} namespace when you run the following shell script: 

+
[source,bash]
----
./doc/upgrade/cleanup_legacy_postgres.sh <1>
----
<1> The {global-hub} that you installed. 