[#global-hub-install-acm]
= Installing {global-hub} on an existing {acm-short} hub cluster

You can install {global-hub} in an existing {acm-short} hub cluster and enable the {global-hub} agent in {acm-short}. Learn about the following capabilities: 

* When you install {global-hub} in an {acm-short} hub cluster, Kafka receives this information and stores it in the {global-hub} database, giving you access to the clusters, policies, and events. 
* Kafka stores this information, so as a Kafka consumer, you can access other components. For example: you can integrate with Red Hat Advanced Cluster Security and Red Hat Event-Driven Ansible. 
* Your data is stored in the {global-hub} database so you can view the cluster and policy information in the Grafana dashboards. 

To install {global-hub} on an existing {acm-short} hub cluster, you must set the `installAgentOnLocal` field to `true` by applying the following YAML sample:

[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1alpha4
kind: MulticlusterGlobalHub
metadata:
  name: multiclusterglobalhub
  namespace: multicluster-global-hub
spec:
  enableMetrics: true
  installAgentOnLocal: true
  dataLayer:
    kafka:
      topics:
        specTopic: gh-spec
        statusTopic: gh-status.*
    postgres:
      retention: 18m
  availabilityConfig: High
----

The {global-hub} agent is now automatically installed on an existing {acm-short} hub cluster, and you can create a `MultiClusterGlobalHub` custom resource by completing the following procedures: 

* xref:../global_hub/global_hub_install_connected.adoc#global-hub-install-connected[Installing Multicluster Global Hub in a connected environment]
* xref:../global_hub/global_hub_install_disconnected.adoc#global-hub-install-disconnected[Installing Multicluster Global Hub in a disconnected environment]

*Note:* If you enabled the `MultiClusterObservability` custom resource in the {acm-short} after you installed {global-hub}, then any new update for the `MultiClusterObservability` custom resource does not take effect.
