:_mod-docs-content-type: REFERENCE

[#global-hub-migrate-process]
= Managed cluster migration process

[role="_abstract"]
By using {global-hub} to migrate your managed clusters, you have a unified process that helps you reorganize workloads, move clusters and their resources together, automate cluster registration and cleanup, and track individual steps with detailed status updates. To migrate your managed clusters, you need the following components:

* The {global-hub} operator to organize the migration workflow.
* The `source` {acm-short} hub cluster to manage the clusters and the associated resources.
* The `target` {acm-short} hub cluster to receive the migrated clusters and the associated resources.

With {global-hub}, you can manage large fleets of clusters by implementing the event-driven architecture of {global-hub}. {global-hub} connects itself to your managed hub clusters. With the {global-hub} event-based design, you can enable {global-hub} to communicate, organize, synchronize, and transfer resources and cluster states among all your hub clusters.

The managed cluster migration process requires coordination between a `source` and `target` {acm-short} hub cluster. The `multicluster-global-hub-agent` performs the migration tasks on the `source` and `target` hub clusters. The `multicluster-global-hub-manager` controls the flow of the migration between the `source` and `target` hub clusters and manages the `ManagedClusterMigration` resources.

During the managed cluster migration, the `source` and `target` hub clusters go through different phases. These phases and their conditions help track the status changes of the hub clusters throughout the migration process. See the following table for an outline of each phase and its condition:

.Phase and condition
|===
| Phase | Condition

| `Pending`
| Performs one migration at a time. Other migrations remain `Pending`.

| `Validating`
| Verifies that the clusters and hub clusters are valid.

| `Initializing`
| Prepares the `target` and `source` hub cluster.

| `Deploying`
| Migrates selected clusters and their resources.

| `Registering`
| Restarts the registration of the cluster to the `target` hub cluster.

| `Cleaning`
| Cleans the resources from both `target` and `source` hub cluster and manages the `rollback` if needed.

| `Completed`
| Confirms the migrations are successfully completed.

| `Failed`
| Confirms that the migration has failed and includes this failure message in the `status`.
|===

See the following table for the supported versions and the corresponding {global-hub} `source`, and `target` hub versions:

.Supported versions
|===
| {global-hub} version for migration | `source` hub version | `target` hub version

| {global-hub} 1.5
| {acm-short} 2.14
| {acm-short} 2.14

| {global-hub} 1.5
| {acm-short} 2.13
| {acm-short} 2.14
|===

To fully migrate your managed clusters, you need to complete the following procedures:

* xref:../global_hub/global_hub_migrate_prep.adoc#global-hub-migrate-prep[Preparing your {global-hub} environment for migration]
* xref:../global_hub/global_hub_migrate_clusters.adoc#global-hub-migrate-clusters[Migrating managed clusters]
* xref:../global_hub/global_hub_migrate_status.adoc#global-hub-migrate-status[Tracking the migration status]

.Additional resources

* xref:../global_hub/global_hub_import_hub_default.adoc#global-hub-importing-managed-hub-in-default-mode[Importing a managed hub cluster in the default mode]
* xref:../global_hub/global_hub_import_hub_hosted.adoc#global-hub-importing-in-hosted-mode[Importing a managed hub cluster in the hosted mode]
