:_mod-docs-content-type: PROCEDURE

[#ztp-create-resource-static]
= Creating a _ManagedClusterMigration_ resource to migrate a static list

[role="_abstract"]
To start the {global-hub} ZTP cluster migration, you must create a `ManagedClusterMigration` custom resource. You can define the clusters to migrate by using a _static_ list, or by using a _dynamic_ placement resource. If you have a _static_ list of managed clusters to migrate, use this procedure to create the migration resource.

*Required access:* Cluster administrator

.Procedure

. Create a file that is named `migration-static.yaml` with the following content where the `local-cluster` and the `hub2` represents the source cluster and target clusters:

+
[source,yaml]
----
apiVersion: global-hub.open-cluster-management.io/v1alpha1
kind: ManagedClusterMigration
metadata:
  name: ztp-sno-migration
  namespace: multicluster-global-hub
spec:
  to: local-cluster
  from: hub2
  includedManagedClusters:
    - sno1
    - sno2
    - sno3
  supportedConfigs:
    stageTimeout: 15m
----

. Apply the resource to the {global-hub} by running the following command:

+
[source,bash]
----
oc apply -f migration-static.yaml
----

. Proceed to xref:../global_hub/global_hub_ztp_create_resource_verify.adoc#ztp-create-resource-verify[Verifying the migration resource status].
