[#multicluster-global-hub]
= Multicluster global hub

The multicluster global hub is a set of components that enable you to import one or more hub clusters and manage them from a single hub cluster.

After importing the hub clusters as managed hub clusters, you can use multicluster global hub to complete the following tasks across all of the managed hub clusters:

* Report the policy compliance status and trend
* Report the compliance states for the past 30 days
* Inventory all managed hubs and managed clusters on the overview page
* Detect and alert in cases of irregular policy behavior
* Create policy lifecycle changes that are ready for the Kafka event-driven architecture

The multicluster global hub is useful when a single hub cluster cannot manage the large number of clusters in a high-scale environment. When this happens, you divide the clusters into smaller groups of clusters and configure a hub cluster for each group. 

It is often inconvenient to view the data on multiple hub clusters for the managed clusters that are managed by that hub cluster. The multicluster global hub provides an easier way to view information from multiple hubs by designating multiple hub clusters as managed hub clusters. The global hub cluster manages the other hub clusters and gathers summarized information from the managed hub clusters.

- xref:../global_hub/global_hub_release_notes.adoc#global-hub-release-notes[Multicluster global hub release notes]
    - xref:../global_hub/global_hub_known_issues.adoc#known-issues-global-hub[Multicluster global hub known issues]
    - xref:../global_hub/global_hub_architecture.adoc#global-hub-architecture[Multicluster global hub architecture]

- xref:../global_hub/global_hub_install_upgrade.adoc#global-hub-install[Installing]

- xref:../global_hub/global_hub_existing_components.adoc#global-hub-integrating-existing-components[Integrating existing components]

- xref:../global_hub/global_hub_configuring.adoc#global-hub-configuring[Configuring the multicluster global hub]

- xref:../global_hub/global_hub_troubleshooting_intro.adoc#global-hub-troubleshooting-intro[Troubleshooting]

////
    - xref:../global_hub/global_hub_installing.adoc#global-hub-install[Installing multicluster global hub]

    - xref:../global_hub/global_hub_upgrading.adoc#global-hub-upgrading[Upgrading multicluster global hub]
    -xref:../global_hub/global_hub_uninstalling.adoc#global-hub-uninstalling[Uninstalling multicluster global hub]


////



