:_mod-docs-content-type: PROCEDURE

[#global-hub-integrating-postgres]
= Integrating an existing version of PostgreSQL

[role="_abstract"]
If you have your own PostgreSQL relational database, you can use it as the storage for {global-hub}. The minimum required storage size is 20 GB. This amount can store three managed hubs with 250 managed clusters and 50 policies per managed hub for 18 months.

You need to create a secret that is named `multicluster-global-hub-storage` in the `multicluster-global-hub` namespace. The secret must contain the following fields:

* `database_uri`: Used to create the database and insert data. Your value must resemble the following format: `postgres://<user>:<password>@<host>:<port>/<database>?sslmode=<mode>`.
* `database_uri_with_readonlyuser`: Used to query data by the instance of Grafana that is used by {global-hub}. This value is optional. Your value must resemble the following format: `postgres://<user>:<password>@<host>:<port>/<database>?sslmode=<mode>`.
* `ca.crt`: Optional, based on the `sslmode` value.

.Procedure

. Verify that your cluster has the minimum required storage size of 20 GB.

. Create the secret by running the following command:

+
[source,bash]
----
oc create secret generic multicluster-global-hub-storage -n multicluster-global-hub \
    --from-literal=database_uri=<postgresql-uri> \
    --from-literal=database_uri_with_readonlyuser=<postgresql-uri-with-readonlyuser> \
    --from-file=ca.crt=<CA-for-postgres-server>
----

+
The host must be accessible from the {global-hub} cluster. If your PostgreSQL database is in a Kubernetes cluster, consider using the service type with `nodePort` or `LoadBalancer` to expose the database. For more information, see link:../troubleshooting/trouble_access_postgres.adoc#gh-access-provisioned-postgres-database[Accessing the provisioned PostgreSQL database for troubleshooting].
