[#global-hub-importing-managed-hub-in-default-mode]
= Importing a managed hub cluster in the default mode

Import an existing hub cluster as a managed hub cluster, which is the local-cluster, to help you control your different environments when you develop and deploy your applications. 

[#global-hub-importing-default-prereq]
== Prerequisites

. Disable the the local cluster setting in the existing hub cluster by setting the `disableHubSelfManagement` setting to `true` in the `multiclusterhub` custom resource. This setting disables the automatic import of the hub cluster as a managed cluster.
. Import the managed hub cluster by completing the steps in link:../clusters/cluster_lifecycle/import_intro.adoc#import-intro[Cluster import introduction].

[#global-hub-importing-managed-hub]
== Importing a managed hub cluster

To import an existing hub cluster as a managed hub cluster, complete the following steps:

. Set the label `global-hub.open-cluster-management.io/deploy-mode=default` to the `managedcluster` when you import the managed hub cluster. 
. Check the {global-hub} agent status to ensure that the agent is running in the managed hub cluster. Run the following command:
+
----
oc get managedclusteraddon multicluster-global-hub-controller -n <managed_hub_cluster_name>
----

*Note:* If you upgrade {global-hub} from 1.4.x, you must manually add the label `global-hub.open-cluster-management.io/deploy-mode=default` to all the managed hub clusters.
