[#global-hub-install-acm]
= Installing {global-hub} on an existing {acm-short} hub cluster (Technology Preview)

When you create the `MultiClusterGlobalHub` custom resource (CR), you must set the field, `installAgentOnLocal`, to `true`. The `installAgentOnLocal` field determines if you can deploy {global-hub}  on an existing  {acm-short} hub cluster.  

Before you create `MultiClusterGlobalHub` custom resource (CR), you must complete the following procedures: 

* xref:../global_hub/global_hub_install_connected.adoc#global-hub-install-connected[Installing Multicluster Global Hub in a connected environment]
* xref:../global_hub/global_hub_install_disconnected.adoc#global-hub-install-disconnected[Installing Multicluster Global Hub in a disconnected environment]

To install {global-hub} on an existing {acm-short} hub cluster, complete the following steps:

. In the {global-hub} grafana, create a `MultiClusterGlobalHub` CR. 
. Set the field, `installAgentOnLocal`, to `true`. 
. In the {global-hub} grafana dashboard, go to the namespace, `multicluster-global-hub-agent`.
. Verify that the hub cluster name is `local-cluster`.

The {global-hub} agent is now installed on an existing {acm-short} hub cluster. 

