[#global-hub-install-acm]
= Installing {global-hub} on an existing {acm-short} hub cluster

You can install {global-hub} in an existing {acm-short} hub cluster and enable the {global-hub} agent in {acm-short}. Learn more about the capabilities: 

* You have access to all the clusters, policies, and events in the {global-hub} database, because when you install {global-hub} in an {acm-short} hub cluster, Kafka received this information and stores it in the database. 
* Since Kafka has this information, you can easily access other components that Kafka consume, for example: you can integrate with Red Hat Advanced Cluster Security and Red Hat Event-Driven Ansible. 
* Since your data gets stored in the {global-hub} database, you can view the cluster and policy information in the Grafana dashboards. 

Before you can install {global-hub} in an existing {acm-short} hub cluster, you must create a `MultiClusterGlobalHub` custom resource (CR), by completing the following procedures: 

* xref:../global_hub/global_hub_install_connected.adoc#global-hub-install-connected[Installing Multicluster Global Hub in a connected environment]
* xref:../global_hub/global_hub_install_disconnected.adoc#global-hub-install-disconnected[Installing Multicluster Global Hub in a disconnected environment]

*Note:* If you enabled the `MultiClusterObservability` CR in the {acm-short}, after you installed {globalhub}, then any new update for the `MultiClusterObservability` CR does not take effect.

To install {global-hub} on an existing {acm-short} hub cluster, you must set the `installAgentOnLocal` field to `true` by applying the following YAML sample:

[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1alpha4
kind: MulticlusterGlobalHub
metadata:
  name: multiclusterglobalhub
  namespace: multicluster-global-hub
spec:
  enableMetrics: true
  installAgentOnLocal: true
  dataLayer:
    kafka:
      topics:
        specTopic: gh-spec
        statusTopic: gh-status.*
    postgres:
      retention: 18m
  availabilityConfig: High
----

The {global-hub} agent is now automatically installed on an existing {acm-short} hub cluster. 