:_mod-docs-content-type: PROCEDURE

[#global-hub-migrate-status]
= Tracking the migration status

[role="_abstract"]
During the migration process, you can track the statuses of your managed clusters by using the {global-hub} `ConfigMap` or the migration custom resource.

*Required access:* Cluster administrator

{global-hub} automatically creates a `ConfigMap` which gives you a detailed cluster list, telling you if the cluster migration fails or succeeds. The migration custom resource gives you the status of the entire migration process.

.Procedure

. View the migration status from the `ConfigMap` by running the following command:

+
[source,bash]
----
oc get configmap <migration-name> -n <global-hub-namespace> -o yaml
----

. Ensure that the `ConfigMap` that you see resembles the following sample:

+
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-sample
  namespace: multicluster-global-hub
data:
  success: '["cluster1","cluster3"]'
  failure: '["cluster2"]'
----

. To view the tracking status from the migration custom resource, verify that its migration status is `True`, and that it resembles the following sample:

+
[source,yaml]
----
status:
  conditions:
    - type: ResourceValidated
      status: "True"
      message: Migration resources have been validated
    - type: ResourceInitialized
      status: "True"
      message: All source and target hubs have been initialized
    - type: ResourceDeployed
      status: "True"
      message: Resources have been successfully deployed to the target hub cluster
    - type: ClusterRegistered
      status: "True"
      message: All migrated clusters have been successfully registered
    - type: ResourceCleaned
      status: "True"
      message: Resources have been successfully cleaned up from the hub clusters
  phase: Completed
----
