[#global-hub-migrating-managed-clusters]
= Migrating managed clusters (Technology Preview)

You can access a Technology Preview  migration feature in {global-hub} 1.5. With this feature, you can migrate managed clusters in the following situations: across {acm} versions, from one {acm-short} hub cluster to another, and the associated Kubernetes resources, such as,  `ConfigMaps` and `Secrets`. 

By using {global-hub} to migrate your managed cluster, you have a unified process that helps you perform the following actions: 

* Reorganize workloads among {acm-short} hub clusters. 
* Move clusters and their resources together. 
* Automate cluster registration and cleanup. 
* Tracks individual steps with detailed status updates. 

To fully migrate your managed clusters and to understand the process, complete the following sections: 

. <<prerequisites, Prerequisites>> 
. <<understanding-migration, Understanding the managed cluster migration process>> 
. <<preparing-migration-environment, Preparing the migration environment>> 
. <<migrating-managed-clusters, Migrating managed clusters>> 

[#prerequisites]
== Prerequisites 

To migrate your managed clusters, you need the following components: 

* The {global-hub} operator to organize the migration workflow.
* The `source` {acm-short} hub to manage the clusters and their associated resources. 
* The `target`{acm-short} hub to receive the migrated clusters and their associated resources. 

[#understanding-migration]
== Managed cluster migration process 

With {global-hub}, you can manage large fleets of clusters by implementing the event-driven architecture of {global-hub}. {global-hub} connects itself to your managed hub clusters. With the {global-hub} event-based design, you can enable {global-hub} to communicate, organize, synchronize, and transfer resources and cluster states among all you hub clusters.  

The manage cluster migration process requires coordination between a `source` hub and `target` {acm-short} hub. The `multicluster-global-hub-agent` performs the migrations tasks on the `source` and `target` hubs. The `multicluster-global-hub-manager` controls the flow of the migration between the `source` and `target` hub and manages the `ManagedClusterMigration` resources. 

During the managed cluster migration, the `source` and `target` hubs go through different phases. These phases and their conditions help track the status changes of the hubs throughout the migration process. See the following table for an outline of each phase and its condition:  

.Table list of _Phase_ and _Condition_
|===
| Phase | Condition 

| `Pending`
| Performs one migration at a time. Other migrations remain `Pending`. 

| `Validating`
| Verifies that the clusters and hub clusters are valid. 

| `Initializing`
| Prepares the `target` hub and `source` hub. 

| `Deploying`
| Migrates selected clusters and their resources. 

| `Registering`
| Restarts the registration of the cluster to the `target` hub. 

| `Cleaning`
| Cleans the resources from both `target` and `source` hub and manages the `rollback` if needed. 

| `Completed`
| Confirms the migrations are successfully completed. 

| `Failed`
| Confirms that the migration has failed and includes this failure message in the `status`.  
|===

*Note:* The `Validating` phase does not check resources such as `ConfigMap` and `Secret`. If you specify resources that do not exist in the `source` hub, the migration fails in the `Deploying` phase. 

[#preparing-migration-environment]
== Preparing the migration environment 

To prepare your {global-hub} migration environment, create a Brownfield environment. You create a Brownfield environment by deploying the {global-hub} control plane directly into the `source` and `target` {acm-short} hub. Then, you configure the {global-hub} migration environment into the Brownfield environment that you created and import the `source` hub in the `Hosted` mode. 

Complete the following steps: 

. Install the {global-hub} operator in the `source` {acm-short} hub. 
. Enable the `local-cluster` in the {global-hub} custom operator that is running in the `source` {acm-short} hub. 
. Create the {global-hub} operand and enable the {global-hub} agent to run locally by applying the following YAML:

+
[source,yaml]
----
  apiVersion: operator.open-cluster-management.io/v1alpha4
  kind: MulticlusterGlobalHub
  metadata:
    name: multiclusterglobalhub
    namespace: multicluster-global-hub
  spec:
    availabilityConfig: High
    installAgentOnLocal: true
----
+
. Import the target {acm-short} hub cluster into {global-hub} that is in the `Hosted` mode by adding the following label to the managed hub cluster:

+
[oc,bash]
----
global-hub.open-cluster-management.io/deploy-mode=hosted
----


[#migrating-managed-clusters]
== Migrating managed clusters 

After you configure your {global-hub} migration environment, migrate your managed clusters. For an example of migrating the sample, `cluster1`
and its associated resources from `hub1` to `hub2`, complete the following steps: 

. Start the migration by create a `ManagedClusterMigration` resource in the {global-hub} migration environment by applying the following YAML: 

+
[source,yaml]
----
apiVersion: global-hub.open-cluster-management.io/v1alpha1
kind: ManagedClusterMigration
metadata:
  name: migration-sample
spec:
  from: local-cluster <1>
  includedManagedClusters: 
    - cluster1 <2> 
  includedResources: <3> 
    - configmap/default/foo
    - secret/cluster1/bar
  to: hub2 <4> 
----
<1> The `source` hub is a `local-cluster` that {global-hub} installed in `hub1`. 
<2> The managed cluster that is named `cluster1` and is being migrated to `hub2`. The managed cluster in `hub1` and `hub2` must be different from one another. 
<3> Specifies the Kubernetes resources for you to migrate by using the format, `kind/namespace/name`. For example: 
* `configmap/default/foo` is a `Configmap` in the `default` namespace that is named `foo`.
* `secret/cluster1/bar` is a `Secret` in the `cluster1` namespace that is named `bar`. 
<4> The `target` hub is `hub2`. 
+ 
. In the `status` resource section, verify that your migration status resembles the following status: 

+
[source,bash]
----
status:
  conditions:
    - type: ResourceValidated
      status: "True"
      message: Migration resources have been validated
    - type: ResourceInitialized
      status: "True"
      message: All source and target hubs have been initialized
    - type: ResourceDeployed
      status: "True"
      message: Resources have been successfully deployed to the target hub cluster
    - type: ClusterRegistered
      status: "True"
      message: All migrated clusters have been successfully registered
    - type: ResourceCleaned
      status: "True"
      message: Resources have been successfully cleaned up from the hub clusters
  phase: Completed
----



