:_mod-docs-content-type: PROCEDURE

[#global-hub-migrate-clusters]
= Migrating managed clusters

[role="_abstract"]
After you configure your {global-hub} migration environment, migrate your managed clusters. You can create a `ManagedClusterMigration` resource in the {global-hub} migration environment by directly selecting your managed clusters by name or by using a `Placement` resource.

*Required access:* Cluster administrator

.Prerequisites

* Complete xref:../global_hub/global_hub_migrate_prep.adoc#global-hub-migrate-prep[Preparing the migration environment].

== Migrating managed clusters by name

To migrate the `cluster1` sample and the associated resources from `hub1` to `hub2` hub clusters, complete the following steps to migrate your specific managed clusters by name:

.Procedure

. Go to your {global-hub} namespace.

. Apply the following YAML file:

+
[source,yaml]
----
apiVersion: global-hub.open-cluster-management.io/v1alpha1
kind: ManagedClusterMigration
metadata:
  name: migration-sample
spec:
  from: local-cluster
  includedManagedClusters:
    - cluster1
    - cluster2
  to: hub2
----
+
* The `source` hub cluster is a `local-cluster` that {global-hub} installed in `hub1` hub cluster.
* The managed clusters that are being migrated to `hub2` hub cluster. The managed cluster in `hub1` and `hub2` hub clusters must be different from one another.
* The `target` hub cluster is `hub2`.

== Migrating managed clusters with a Placement resource

To migrate your managed clusters with the `Placement` resource, complete the following steps:

.Procedure

. Go to your {global-hub} namespace.

. Select clusters based on labels, cluster properties, or other criteria defined in your `Placement` resource.

. Apply the following YAML file:

+
[source,yaml]
----
apiVersion: global-hub.open-cluster-management.io/v1alpha1
kind: ManagedClusterMigration
metadata:
  name: migration-placement-sample
spec:
  from: local-cluster
  includedManagedClustersPlacementRef: production-clusters
  to: hub2
----
+
* The `source` hub cluster is a `local-cluster` that {global-hub} installed in `hub1` hub cluster.
* The `Placement` resource that has the name `production-clusters` and that defines which clusters get migrated. You must define the `Placement` resource in the {global-hub} agent namespace of the source hub cluster. For example, you can name the `Placement` resource `multicluster-global-hub` or `multicluster-global-hub-agent`.
* The `target` hub cluster is `hub2`.

. Specify the `includedManagedClusters` or `includedManagedClustersPlacementRef` cluster type to include in your migration. Include only one of these cluster types in your migration because they cannot exist together.
