[#global-hub-install]
= Installing in disconnected network environments

Multicluster global hub is installed through {olm}, which manages the installation, upgrade, and removal of the components that encompass the multicluster global hub. 

To install multicluster cluster global hub on a disconnected hub cluster, perform the following steps in addition to the usual install or upgrade steps that are for the connected network environment.

*Required access:* Cluster administrator is required for all installation and upgrade tasks.

* <<global-hub-install-prerequisites,Prerequisites>>
* <<global-hub-install-dependencies,Dependencies>>
* <<global-hub-installing-connected,Installing Multicluster global hub in a connected environment>>
* <<global-hub-installing-disconnected,Installing Multicluster global hub in a disconnected environment>>
* <<additional-resource-custom-global-hub-install,Additional resources>>

[#global-hub-install-prerequisites]
== Prerequisites

You must meet the following requirements before you install multicluster global:

- An image registry and a bastion host that has access to both the internet and to your mirror registry.

- You must install {product-title} version 2.7, or later on your cluster

- You must install the {ocp} `oc` command line interface. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/cli_tools/openshift-cli-oc#cli-getting-started[Installing the {ocp-short} CLI]. 

- You must install the `opm` command line interface. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/cli_tools/opm-cli[Installing the opm CLI].

- You must install the {ocp-short} `oc-mirror` command line interface. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/installing/disconnected-installation-mirroring#installing-mirroring-disconnected[Mirroring images for a disconnected installation using the oc-mirror plugin].

- Confirm the availability of your local image registry. *Best practice*: Use your existing mirror registry for the {olm} related content. Because you have already completed the installation of the {ocp-short} cluster in your disconnected environment, the mirror registry is created.
+
If you do not already have a local image registry, create one by completing the procedure that is described in link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/installing/disconnected-installation-mirroring#mirroring-images-disconnected-install[Mirroring images for a disconnected installation] of the {ocp-short} documentation.

- You must configure {olm}. In disconnected environments, {olm} cannot access the standard Red Hat operator sources that are provided because they are hosted on image registries that are not accessible from a disconnected cluster. Instead, a cluster administrator can enable the installation and upgrade of operators in a disconnected environment by using mirrored image registries and operator catalogs.

- Prepare your disconnected cluster to install multicluster global hub. Complete the following procedure in the {ocp-short} documentation, link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/operators/index#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks].

- Add operator packages in the mirror catalog.
+
Include the required operator packages in your mirror catalog. Red Hat provides the Multicluster Global Hub and AMQ Streams operators in the Red Hat operators catalog, which are delivered by the `registry.redhat.io/redhat/redhat-operator-index` index image. When you prepare your mirror of this catalog index image, you can choose to either mirror the entire catalog as provided by Red Hat, or you can mirror a subset that contains only the operator packages that you intend to use.
+
If you are creating a full mirror catalog, no special considerations are needed as all of the packages required to install multicluster global hub and AMQ Streams are included. However, if you are creating a partial or filtered mirrored catalog, for which you identify particular packages to be included, you need to include the following package names in your list:

- `multicluster-global-hub-operator-product` 
- `amq-streams`


//which procedure it best for the user? 
//are these procedures a part of the prereqisites?
//Create the mirrored catalog or registry by using the `oc-mirror` plug-in

//OR

//Create the mirrored catalog or registry by using the OPM utility

//Are all of the tasks between lines 53-228 considered prerequisite steps? 
//seems like the following should be in a seperate file
[#installing-global-hub]
== Installing the multicluster global hub operator from the command line interface

. Install the operator from the OperatorHub using the command line interface.
.. Create the `OpertorGroup` resource. Each namespace can have only one operator group. Run the following command:
+
[source,bash]
----
oc apply -f ./global-hub-og.yaml
----
+
Your resource might resemble the following content:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: global-hub-operator-sdk-og <1>
    namespace: multicluster-global-hub <2>
  spec:
    targetNamespaces:
    - multicluster-global-hub
----
+
<1> Replace `global-hub-operator-sdk-og` with the name of your operator group.
<2> Replace `multicluster-global-hub` namespace with your project namespace.
+
Save the `global-hub-og.yaml file`.

.. Create the `Subscription` resource. Run the following command:
+
[source,bash]
----
oc apply -f ./subscription.yaml
----
+
Your resource might resemble the following YAML file:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: multicluster-global-hub-operator
    namespace: multicluster-global-hub <1>
  spec:
    channel: alpha
    installPlanApproval: Automatic
    name: multicluster-global-hub-operator
    source: my-mirror-catalog-source
    sourceNamespace: openshift-marketplace
----
+
<1> Replace the `multicluster-global-hub` namespace with your project namespace.

.. Verify that the pods are running for the multicluster global hub operator. Run the following command:
+
[source,bash]
----
oc get pods -n multicluster-global-hub
----
+
The following information might be displayed:
+
[source,bash]
----
NAME                                                READY   STATUS    RESTARTS   AGE
multicluster-global-hub-operator-687584cb7c-fnftj   1/1     Running   0          2m12s
----

.. Get a description of the `multicluster-global-hub-operator` pod with the following command:
+
[source,bash]
----
oc describe pod -n multicluster-global-hub multicluster-global-hub-operator-687584cb7c-fnftj
----
+
The following information might be displayed:
+
[source,bash]
----
...
  Events:
  Type    Reason          Age    From               Message
  ----    ------          ----   ----               -------
  Normal  Scheduled       2m52s  default-scheduler  Successfully assigned multicluster-global-hub/multicluster-global-hub-operator-5546668786-f7b7v to ip-10-0-137-91.ec2.internal
  Normal  AddedInterface  2m50s  multus             Add eth0 [10.128.1.7/23] from openshift-sdn
  Normal  Pulling         2m49s  kubelet            Pulling image "registry.redhat.io/multicluster-globalhub/multicluster-global-hub-operator@sha256:f385a9cfa78442526d6721fc7aa182ec6b98dffdabc78e2732bf9adbc5c8e0df"
  Normal  Pulled          2m35s  kubelet            Successfully pulled image "registry.redhat.io/multicluster-globalhub/multicluster-global-hub-operator@sha256:f385a9cfa78442526d6721fc7aa182ec6b98dffdabc78e2732bf9adbc5c8e0df" in 14.180033246s
  Normal  Created         2m35s  kubelet            Created container multicluster-global-hub-operator
  Normal  Started         2m35s  kubelet            Started container multicluster-global-hub-operator
  ...
----

//need to replace the link
[#installing-global-hub]
=== Installing the Multicluster Global Hub Operator from the {ocp} console

You can also install and subscribe an Operator from OperatorHub using the {ocp-short} web console. For more details, see link:ttps://docs.openshift.com/container-platform/4.11/operators/admin/olm-adding-operators-to-cluster.html[here].

//Is this required for the install of multicluster global hub? 
== Import the managed hub using customized image registry


[#additional-resource-custom-global-hub-install]
== Additional resources
//need to double check these links and point to the correct files
- For more information about mirroring an Operator catalog, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/operators/index#olm-mirror-catalog_olm-restricted-networks[Mirroring an Operator catalog].

- For more information about accessing images from private registries, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/operators/index#olm-accessing-images-private-registries_olm-managing-custom-catalogs[Accessing images for Operators from private registries].

- For more information about adding a catalog source, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/operators/index#olm-creating-catalog-from-index_olm-restricted-networks[Adding a catalog source to a cluster].

- For more information about installing the Open Cluster Management project, see link:https://github.com/stolostron/deploy[Deploy].

- For more information about installing {product-title-short} in a disconnected environment, see link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/install/installing#install-on-disconnected-networks[Install in disconnected network environments].

- For more information about mirroring images, see link:https://docs.openshift.com/container-platform/4.11/installing/disconnected_install/installing-mirroring-installation-images.html#installing-mirroring-installation-images[Mirroring images for a disconnected installation].

- For more information about the Operator SDK Intregration with OLM, see link:https://sdk.operatorframework.io/docs/olm-integration/[Operator SDK Integration with Operator Lifecycle Manager].

- For more information about the `ManagedClusterImageRegistry` custom resource definition, see link:https://github.com/stolostron/multicloud-operators-foundation/blob/main/docs/imageregistry/imageregistry.md[ManagedClusterImageRegistry CRD].
