[#global-hub-compliance-manual]
= Running the summarization process manually

You can manually run the summarization process to restore the initial compliance state of the day when the job is not triggered or has not failed running. To manually run the summarization process, complete the following steps: 

. Use the earlier day's compliance history as the initial state for the recovery day's history.
. Connect to the database.
+ 
You can use clients such as `pgAdmin` and `tablePlush` to connect to the {global-hub} database. Or, you can directly connect to the database on the cluster by running the following command:
+
----
oc exec -it multicluster-global-hub-postgres-0 -n multicluster-global-hub -- psql -d hoh
----
       
. Decide the date when you want the summarization process to run, for example: `2023-07-06` 
+
Find the local compliance job failure information from the dashboard metrics or the `history.local_compliance_job_log` table. In this example, the date is, `2023-07-06`, so you know that `2023-07-06` is the date when you need to manually run the summary processes.

. Recover the initial compliance of `2023-07-06` by running the following SQL: 
+
----
-- call the func to generate the initial data of '2023-07-06' by inheriting '2023-07-05'
CALL history.generate_local_compliance('2024-07-06');
----