:_mod-docs-content-type: PROCEDURE

[#global-hub-integrating-kafka]
= Integrating an existing version of Kafka

[role="_abstract"]
If you have your own instance of Kafka, you can use it as the transport for {global-hub}.

.Procedure

. If you do not have a persistent volume for your Kafka instance, create one.

. Create a secret that is named `multicluster-global-hub-transport` in the `multicluster-global-hub` namespace.

.. Extract the information in the following required fields:
+
* `bootstrap.servers`: Specifies the Kafka bootstrap servers.
* `ca.crt`: Required if you use the `KafkaUser` custom resource to configure authentication credentials. See link:https://strimzi.io/docs/operators/latest/deploying.html#con-securing-client-authentication-str[User authentication] in the Strimzi documentation for the required steps to extract the `ca.crt` certificate from the secret.
* `client.crt`: Required. See link:https://strimzi.io/docs/operators/latest/deploying.html#con-securing-client-authentication-str[User authentication] in the Strimzi documentation for the steps to extract the `user.crt` certificate from the secret.
* `client.key`: Required. See link:https://strimzi.io/docs/operators/latest/deploying.html#con-securing-client-authentication-str[User authentication] in the Strimzi documentation for the steps to extract the `user.key` from the secret.

.. Create the secret by running the following command, replacing the values with your extracted values where necessary:

+
[source,bash]
----
oc create secret generic multicluster-global-hub-transport -n multicluster-global-hub \
    --from-literal=bootstrap_server=<kafka-bootstrap-server-address> \
    --from-file=ca.crt=<CA-cert-for-kafka-server> \
    --from-file=client.crt=<Client-cert-for-kafka-server> \
    --from-file=client.key=<Client-key-for-kafka-server>
----

. If automatic topic creation is configured on your Kafka instance, skip this step. If it is not configured, create the `spec` and `status` topics manually.

. Ensure that the {global-hub} user that accesses Kafka has permission to read data from the topics and write data to the topics.
