[#global-hub-install]
= Installing

Multicluster global hub is installed through {olm}, which manages the installation, upgrade, and removal of the components that encompass the multicluster global hub. 

* <<global-hub-install-prerequisites,Prerequisites>>
* <<global-hub-install-support-matrix,Support matrix>>
* <<global-hub-installing-connected,Installing Multicluster global hub in a connected environment>>
* <<global-hub-installing-disconnected,Installing multicluster global hub in a disconnected environment>>
* <<additional-resource-custom-global-hub-install,Additional resources>>

[#global-hub-install-prerequisites]
== Prerequisites

Before you install multicluster global hub, see the following requirements:

*Required access:* Cluster administrator. *{ocp-short} Dedicated environment required access:* You must have `cluster-admin` permissions. By default `dedicated-admin` role does not have the required permissions to create namespaces in the {ocp-short} Dedicated environment. 

* {product-title} version 2.7 or later must be installed and configured. link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9[Learn more details about {product-title-short}].

* Networking requirements: The managed hub is also a managed cluster of global hub in {product-title-short}. The network configuration in {product-title-short} is necessary. See link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/networking/networking[Networking] for {product-title-short} networking details.

** Global hub networking requirements

    | Direction | Protocol | Connection | Port (if specified) | Source address |	Destination address |
    | ------ | ------ | ------ | ------ |------ | ------ |
    | Inbound from browser of the user | HTTPS | User need to access the Grafana dashboard | 443 | Browser of the user | IP address of Grafana route |
    | Outbound to Kafka Cluster | HTTPS | Global hub manager need to get data from Kafka cluster | 443 | multicluster-global-hub-manager-xxx pod | Kafka route host |
    | Outbound to PostgreSQL database | HTTPS | Global hub manager need to persist data to PostgreSQL database | 443 | multicluster-global-hub-manager-xxx pod | IP address of the PostgreSQL database |

** Managed hub networking requirements

    | Direction | Protocol | Connection | Port (if specified) | Source address |	Destination address |
    | ------ | ------ | ------ | ------ | ------ | ------ |
    | Outbound to Kafka Cluster | HTTPS | Global hub agent need to sync cluster info and policy info to Kafka cluster | 443 | multicluster-global-hub-agent pod | Kafka route host |

* link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/install/installing#sizing-your-cluster[Sizing your {product-title-short} cluster]

** *Minimum requirements for Crunchy PostgreSQL*

    | vCPU | Memory | Storage size | Namespace |
    | ---- | ------ | ------ | ------ |
    | 100m | 2G | 20Gi*3 | multicluster-global-hub-postgres
    | 10m | 500M | N/A | multicluster-global-hub-postgres
    
** *Minimum requirements for Strimzi*

    | vCPU | Memory | Storage size | Namespace |
    | ---- | ------ | ------ | ------ |
    | 100m | 8G | 20Gi*3 | kafka


* *Optional:* Configured middleware. Multicluster global hub has built-in Kafka, PostgreSQL, and Grafana, but you can use your own configured Kafka, PostgreSQL, and Grafana. See xref:../global_hub/global_hub_existing_components.adoc#global-hub-integrating-existing-components[Integrating existing components] for more details.

[#global-hub-install-support-matrix]
== Support matrix

See the link:https://access.redhat.com/articles/7033110[multicluster global hub support matrix] for information about supported versions. 

[#global-hub-installing-connected]
== Installing Multicluster global hub in a connected environment

To install the Multicluster global hub operator in a connected environment by using the {ocp-short} console, complete the following steps:

. Log in to the {ocp-short} console as a user with the `cluster-admin` role.

. In the navigation, select *Operators* and the _OperatorHub_ icon.

. Search for and select the *Multicluster global hub operator*.

. Click *Install* to start the installation.

. After the installation completes, check the status on the _Installed Operators_ page.

. Click *Multicluster global hub operator* to go to the _Operator_ page.

. Click the *Multicluster global hub* tab to see the `multicluster global hub` instance.

. Click *Create multicluster global hub* to create the `multicluster global hub` instance.

. Enter the required information and click *Create* to create the `multicluster global hub` instance.

*Notes:* 
. The multicluster global hub is only available for the x86 platform.
. The policy and application are disabled in {product-title-short} after the multicluster global hub is installed.
    
[#global-hub-installing-disconnected]
== Installing multicluster global hub in a disconnected environment

If a network connection is not available, you can deploy the multicluster global hub operator in a disconnected environment.

[#global-hub-installing-disconnected-prereq]
=== Additional prereqisites for installing in a disconnected environment

You must meet the following requirements before you install multicluster global hub in a disconnected environment:

- An image registry and a bastion host that have access to both the Internet and to your mirror registry

- Operator Lifecycle Manager link:https://docs.openshift.com/container-platform/4.11/operators/understanding/olm/olm-understanding-olm.html[{olm}] installed on your cluster

- The link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/cli_tools/openshift-cli-oc#cli-getting-started[oc], link:https://docs.openshift.com/container-platform/4.13/cli_reference/opm/cli-opm-install.html[opm], and link:https://docs.openshift.com/container-platform/4.13/installing/disconnected_install/installing-mirroring-disconnected.html#installation-oc-mirror-installing-plugin_installing-mirroring-disconnected[oc-mirror] plugins

[#global-hub-installing-disconnected-mirror]
==== Configure a mirror registry

You must use a mirror image registry when installing Multicluster global hub in a disconnected environment. The image registry ensures that your clusters only use container images that satisfy your organizational controls on external content. 

Because you have already completed the installation of the {ocp-short} in your disconnected environment, you already set up a mirror registry during the {ocp-short} cluster installation.

You can complete the following procedures to provision the mirror registry for the global hub:

- link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/disconnected-installation-mirroring#creating-mirror-registry[Create a mirror registry]

- link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/disconnected-installation-mirroring#installing-mirroring-installation-images[Mirroring images for a disconnected installation]

[#global-hub-packages-in-catalog]
==== Creating operator packages in your catalog

* Include the required operator packages in your mirror catalog. 
+
Red Hat provides the multicluster global hub and AMQ Streams operators in the Red Hat operator catalog, which are delivered by the `registry.redhat.io/redhat/redhat-operator-index` index image. When you prepare your mirror of this catalog index image, you can choose to either mirror the entire catalog as provided by Red Hat. You can also mirror a subset that contains only the operator packages that you intend to use.
+
If you are creating a full mirror catalog, no special considerations are needed as all of the packages required to install multicluster global hub and AMQ Streams are included. If you are creating a partial or filtered mirrored catalog, for which you identify particular packages to be included, you need to include the following package names in your list:

  ** `multicluster-global-hub-operator-product` 
  ** `amq-streams`

* Mirror the catalog images to the registry with one of the following procedures.

** Create the mirrored catalog or registry by using the `oc-mirror` plug-in
+
. Generate the `imageset-config.yaml`
+
[source,yaml]
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
      imageURL: myregistry.example.com:5000/mirror/oc-mirror-metadata
mirror:
  platform:
    channels:
    - name: stable-4.12
      type: ocp
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
    packages:
    - name: multicluster-global-hub-operator-product
    - name: amq-streams
  additionalImages: []
  helm: {}
----

. Mirror the imageset directly to the target mirror registry `oc mirror --config=./imageset-config.yaml docker://myregistry.example.com:5000`
  
. Mirror the imageset in a fully disconnected environment. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/disconnected-installation-mirroring#doc-wrapper[Disconnected installation mirroring] for more details.

** Create the mirrored catalog or registry by using the OPM utility
+
. Build and push multicluster global hub index image
+
[source,shell]
----
$ mkdir multicluster-global-hub-mirror 

$ opm render registry.redhat.io/redhat/redhat-operator-index:v4.12 | jq 'select(.package=="multicluster-global-hub-operator-product" or .name=="multicluster-global-hub-operator-product" or .package=="amq-streams" or .name=="amq-streams")' > multicluster-global-hub-mirror/index.json

$ opm generate dockerfile multicluster-global-hub-mirror

$ docker build -f multicluster-global-hub-mirror.Dockerfile -t myregistry.example.com:5000/mirror/multicluster-global-hub-operator-index:v4.12 .

$ docker push myregistry.example.com:5000/mirror/multicluster-global-hub-operator-index:v4.12
----

. Mirror the catalog images:
+
[source,shell]
----
$ oc adm catalog mirror myregistry.example.com:5000/mirror/multicluster-global-hub-operator-index:v4.12 your-local-private-registry --manifests-only=true --to-manifests=multicluster-globalhub-manifest --index-filter-by-os=linux/amd64
----

. Push the images:
+
[source,shell]
----
$ oc image mirror -f multicluster-globalhub-manifest/mapping.txt -a <imagepullsecret> --filter-by-os=.* --keep-manifest-list --continue-on-error=true --skip-multiple-scopes
----

* Configure to use your mirror registry
+
You have populated a local mirror registry with the previous packages that are required for installing Multicluster Global Hub, complete the steps that are described in the topic link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/operators/index#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks] to make your mirror registry and catalog available on your disconnected cluster, which includes the following steps:

** link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/operators/index#olm-restricted-networks-operatorhub_olm-restricted-networks[Disabling the default OperatorHub sources]

** link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/operators/index#olm-mirror-catalog_olm-restricted-networks[Mirroring the Operator catalog]

** link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/operators/index#olm-creating-catalog-from-index_olm-restricted-networks[Adding a catalog source for your mirrored catalog]

** Find the catalog source name
+
As described in the previous procedures, You need to add a CatalogSource to your disconnected cluster. **Important:** Take note of the value of the `metadata.name` field, which you will need later.
+
Add the `CatalogSource` into the `openshift-marketplace` namespace by using a YAML file similar to the following example:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-mirror-catalog-source
  namespace: openshift-marketplace
spec:
  image: myregistry.example.com:5000/mirror/my-operator-index:v4.12
  sourceType: grpc
  secrets:
  - <global-hub-secret>
----

** Verify required packages are available
+
OLM polls catalog sources for available packages on a regular timed interval. After OLM polls the catalog source for your mirrored catalog, you can verify that the required packages are available from on your disconnected cluster by querying the available PackageManifest resources.
+
Run the command `oc -n openshift-marketplace get packagemanifests`, directed at your disconnected cluster.
The list that is displayed should include entries showing that the following packages are supplied by the catalog source for your mirror catalog:
+
*** `multicluster-global-hub-operator-product`
*** `amq-streams`





[#global-hub-installing-disconnected-icsp]
==== Create an ImageContentSourcePolicy

You can configure an `ImageContentSourcePolicy` on your disconnected cluster to redirect image references to your mirror registry. This enables you to have your cluster obtain container images for the global hub operator on your mirror registry, rather than from the Internet-hosted registries. 

*Note:* The `ImageContentSourcePolicy` can only support the image mirror with image digest.

If you mirrored your catalog using the `oc adm catalog mirror` command, the needed image content source policy configuration is in the `imageContentSourcePolicy.yaml` file inside of the `manifests-*` directory that is created by that command.

If you used the `oc-mirror` plug-in to mirror your catalog instead, the `imageContentSourcePolicy.yaml` file is within the `oc-mirror-workspace/results-*` directory created by the oc-mirror plug-in.

In either case, you can apply the policies to your disconnected command using an `oc apply` or `oc replace` command such as `oc replace -f ./<path>/imageContentSourcePolicy.yaml`

The required image content source policy statements can vary based on how you created your mirror registry, but are similar to this example:
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: global-hub-operator-icsp
spec:
  repositoryDigestMirrors:
  - mirrors:
    - myregistry.example.com:5000/multicluster-globalhub
    source: registry.redhat.io/multicluster-globalhub
  - mirrors:
    - myregistry.example.com:5000/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - myregistry.example.com:5000/redhat
    source: registry.redhat.io/redhat
----

You can configure different image registries for different managed hubs with `ManagedClusterImageRegistry`. See link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html-single/clusters/index#import-cluster-managedclusterimageregistry[Importing a cluster that has a ManagedClusterImageRegistry] to use the `ManagedClusterImageRegistry` API to replace the agent image.

By completing the previous step, a label and an annotation are added to the selected `ManagedCluster`. This means that the agent image in the cluster is replaced with the mirror image.

* Label: `open-cluster-management.io/image-registry=<namespace.managedclusterimageregistry-name>`
* Annotation: `open-cluster-management.io/image-registries: <image-registry-info>`

[#global-hub-installing-disconnected-pull-secret]
==== Configure the image pull secret

If the Operator or Operand images that are referenced by a subscribed Operator require access to a private registry, you can either link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/operators/index#olm-creating-catalog-from-index_olm-managing-custom-catalogs[provide access to all namespaces in the cluster, or to individual target tenant namespaces]. 

[#global-hub-installing-disconnected-pull-secret-generic]
===== Configure the global hub image pull secret in an {ocp-short} cluster

*Note:* Applying the image pull secret on a pre-existing cluster causes a rolling restart of all of the nodes.

. Export the user name from the pull secret:
+
----
export USER=<the-registry-user>
----

. Export the password from the pull secret:
+
----
export PASSWORD=<the-registry-password>
----

. Copy the pull secret:
+
----
oc get secret/pull-secret -n openshift-config --template='{{index .data ".dockerconfigjson" | base64decode}}' > pull_secret.yaml
----

. Log in using the pull secret:
+
----
oc registry login --registry=${REGISTRY} --auth-basic="$USER:$PASSWORD" --to=pull_secret.yaml
----

. Specify the global hub image pull secret:
+
----
oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=pull_secret.yaml
----

. Remove the old pull secret:
+
----
rm pull_secret.yaml
----

[#global-hub-installing-disconnected-pull-secret-individual-namespace]
===== Configure the global hub image pull secret to an individual namespace

. Create the secret in the tenant namespace by running the following command:
+
----
oc create secret generic <secret_name> -n <tenant_namespace> \
--from-file=.dockerconfigjson=<path/to/registry/credentials> \
--type=kubernetes.io/dockerconfigjson
----

. Link the secret to the service account for your operator or operand:
+
----
oc secrets link <operator_sa> -n <tenant_namespace> <secret_name> --for=pull
----

[#global-hub-installing-disconnected-create-catalogsource-object]
==== Create the CatalogSource object

Ensure that you completed the steps in xref:../global_hub/global_hub_install_upgrade.adoc#global-hub-installing-disconnected-pull-secret[Configure the image pull secret] before creating a `CatalogSource` object.

. Run the following command to create the `catalogsource.yaml` file:
+
----
cat ./doc/disconnected_environment/catalogsource.yaml
----

. Add the following content to the `catalogsource.yaml` file: 
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: global-hub-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: global-hub-operator-catalog
  sourceType: grpc
  grpcPodConfig: {}
  secrets:
  - <global-hub-secret>
  image: ${REGISTRY}/multicluster-global-hub-operator-catalog:v${VERSION}
  publisher: global-hub-squad  
----

. Add the contents of the file to the environment variables by running the following command: 
+
----
envsubst < ./doc/disconnected_environment/catalogsource.yaml
----

. Apply the file by running the following command:
+
----
oc apply -f -./doc/disconnected_environment/catalogsource.yaml
----

Operator License Manager (OLM) polls catalog sources for available packages on a timed interval. After OLM polls the catalog source for your mirrored catalog, you can verify that the required packages are available on your disconnected cluster by querying the available `PackageManifest` resources:

----
oc get packagemanifest multicluster-global-hub-operator
----
+ 
The results resemble the following example: 
+
----
NAME                               CATALOG               AGE
multicluster-global-hub-operator   Community Operators   28m
----


[#global-hub-installing-disconnected-installing-operator]
=== Installing the the Global Hub Operator

[#global-hub-installing-disconnected-installing-operator-cli]
==== Installing the the Global Hub Operator by using the CLI

Complete the following steps to install the Global Hub Operator by using the CLI: 

. Create the `OperatorGroup`.
+
Each namespace can have only one operator group. Replace `global-hub-operator-sdk-og` with the name of your operator group, and replace `multicluster-global-hub` namespace with your project namespace.

.. Create the `operatorgroup.yaml` file:
+
----
cat ./doc/disconnected_environment/operatorgroup.yaml 
----

.. Add the following content to your `operatorgroup.yaml` file: 
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: <global-hub-operator-sdk-og>
  namespace: <multicluster-global-hub>
spec:
  targetNamespaces:
   - open-cluster-management
----

.. Apply the `operatorgroup.yaml` file:
+
----
oc apply -f ./doc/disconnected_environment/operatorgroup.yaml   
----
 
. Create the `Subscription`.
+
Replace the `multicluster-global-hub` namespace with your project namespace.
  
.. Create the `subscription.yaml` file:
+
----
cat ./doc/disconnected_environment/subscription.yaml
----

.. Add the following content to your `subscription.yaml` file:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-global-hub-operator
  namespace: <multicluster-global-hub>
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: multicluster-global-hub-operator
  source: global-hub-operator-catalog
  sourceNamespace: openshift-marketplace
----

.. Apply the `subscription.yaml` file:
+
----
oc apply -f ./doc/disconnected_environment/subscription.yaml
----
  
. Check the status of the Global Hub Operator.
+
Replace the `multicluster-global-hub` namespace with your project namespace.

.. Display the status of the pods in the namespace:
+
----
oc get pods -n <multicluster-global-hub>
----
+
The results resemble the following example:
+
----
NAME                                                READY   STATUS    RESTARTS   AGE
multicluster-global-hub-operator-687584cb7c-fnftj   1/1     Running   0          2m12s
----  

.. Display the event information for the pods in the `multicluster-global-hub` namespace: 
+ 
----
oc describe pod -n multicluster-global-hub
----
+
The results look similar to the following events:
+
----
multicluster-global-hub-operator-687584cb7c-fnftj
...
Events:
Type    Reason          Age    From               Message
------    ------          -----   -----               -------
Normal  Scheduled       2m52s  default-scheduler  Successfully assigned open-cluster-management/multicluster-global-hub-operator-5546668786-f7b7v to ip-10-0-137-91.ec2.internal
Normal  AddedInterface  2m50s  multus             Add eth0 [10.128.1.7/23] from openshift-sdn
Normal  Pulling         2m49s  kubelet            Pulling image "registry.redhat.io/multicluster-globalhub/multicluster-global-hub-operator@sha256:f385a9cfa78442526d6721fc7aa182ec6b98dffdabc78e2732bf9adbc5c8e0df"
Normal  Pulled          2m35s  kubelet            Successfully pulled image "registry.redhat.io/multicluster-globalhub/multicluster-global-hub-operator@sha256:f385a9cfa78442526d6721fc7aa182ec6b98dffdabc78e2732bf9adbc5c8e0df" in 14.180033246s
Normal  Created         2m35s  kubelet            Created container multicluster-global-hub-operator
Normal  Started         2m35s  kubelet            Started container multicluster-global-hub-operator
...
----

[#global-hub-installing-disconnected-installing-operator-console]
==== Installing the the Global Hub Operator by using the console

You can install and subscribe an Operator from OperatorHub using the {ocp} web console. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[Adding Operators to a cluster] for the procedure.

[#global-hub-installing-disconnected-import-managed-hub-custom-image-registry]
=== Import the managed hub using the customized image registry

Complete the following steps to import the managed hub using the customized image registry:

. Configure the image registry annotations in the `MulticlusterGlobalHub` custom resource:
+
.. Add an annotation to the `MulticlusterGlobalHub` custom resource and specify the image pull secret and image pull policy.
+
[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1alpha4
kind: MulticlusterGlobalHub
metadata:
  annotations:
    mgh-image-repository: <private-image-registry>
  name: multiclusterglobalhub
  namespace: open-cluster-management
spec:
  imagePullPolicy: Always
  imagePullSecret: ecr-image-pull-secret
----
+
This is the global configuration, and all of your managed hubs use the same image registry and image pull secret.

To support different image registries for different managed hubs, use the `ManagedClusterImageRegistry` API to import the managed hub.

. Configure the `ManagedClusterImageRegistry`.
+
See link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html-single/clusters/index#import-cluster-managedclusterimageregistry[Importing a cluster that has a ManagedClusterImageRegistry] to import the clusters using the `ManagedClusterImageRegistry` API. to replace the agent image.
+
.. Create a `managedclusterregistry.yaml` file with the following contents:
+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cluster.open-cluster-management.io/clusterset: <cluster-set>
    vendor: auto-detect
    cloud: auto-detect
  name: <managed-hub>
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: <cluster-set>
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: <cluster-set>
  namespace: <placement-namespace>
spec:
  clusterSet: <cluster-set>
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: <placement-name>
  namespace: <placement-namespace>
spec:
  clusterSets:
    - <cluster-set>
  tolerations:
  - key: "cluster.open-cluster-management.io/unreachable"
    operator: Exists
----

. Create the `ManagedClusterImageRegistry` to replace the `Agent image`.
+
[source,yaml]
----
apiVersion: imageregistry.open-cluster-management.io/v1alpha1
kind: ManagedClusterImageRegistry
metadata:
  name: <global-hub-cluster-image-registry>
  namespace: <placement-namespace>
spec:
  placementRef:
    group: cluster.open-cluster-management.io
    resource: placements
    name: <placement-name>
  pullSecret:
    name: <image-pull-secret>
  registries:
    - mirror: <mirror-image-registry>
      source: <source-image-registry>
----

By completing the previous steps, a label and an annotation are added to the selected `ManagedCluster`. This means that the agent image in the cluster are replaced with the mirror image.

* Label: `open-cluster-management.io/image-registry=<namespace.managedclusterimageregistry-name>`

* Annotation: `open-cluster-management.io/image-registries: <image-registry-info>`

[#additional-resource-custom-global-hub-install]
== Additional resources

- For more information about mirroring an Operator catalog, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/operators/index#olm-mirror-catalog_olm-restricted-networks[Mirroring an Operator catalog].

- For more information about accessing images from private registries, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/operators/index#olm-accessing-images-private-registries_olm-managing-custom-catalogs[Accessing images for Operators from private registries].

- For more information about adding a catalog source, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/operators/index#olm-creating-catalog-from-index_olm-restricted-networks[Adding a catalog source to a cluster].

- For more information about installing the Open Cluster Management project, see link:https://github.com/stolostron/deploy[Deploy].

- For more information about installing {product-title-short} in a disconnected environment, see link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/install/installing#install-on-disconnected-networks[Install in disconnected network environments].

- For more information about mirroring images, see link:https://docs.openshift.com/container-platform/4.12/installing/disconnected_install/installing-mirroring-installation-images.html#installing-mirroring-installation-images[Mirroring images for a disconnected installation].

- For more information about the Operator SDK Intregration with OLM, see link:https://sdk.operatorframework.io/docs/olm-integration/[Operator SDK Integration with Operator Lifecycle Manager].

- For more information about the `ManagedClusterImageRegistry` custom resource definition, see link:https://github.com/stolostron/multicloud-operators-foundation/blob/main/docs/imageregistry/imageregistry.md[ManagedClusterImageRegistry CRD].
