[#global-hub-grafana-alerts]
= Grafana alerts (Technology Preview)

There are three Grafana alerts that you can configure. These alerts are stored in configmap `multicluster-global-hub-default-alerting`. These alerts notify you of suspicious policies, suspicious clusters compliance status change, and failed cron jobs.

* Suspicious policy change - This alert rule watches the suspicious policies change. If the following events occur more than 5 times in 1 hour, it creates notifications.
+
- A policy was enabled/disabled.
- A policy was updated.

* Suspicious cluster compliance status change - This alert rule watches the cluster compliance status and policy events for a cluster. There are two rules in this alert:
+
- Cluster compliance status changes frequently. If a cluster compliance status changes from `compliance` to `non-compliance` more than three times in one hour, it creates notifications.
- Too many policy events in a cluster. For a policy in a cluster, if there are more than 20 events in five minutes, it creates notifications. If this alert is always firing, the data in the `event.local_policies` table increases too fast.

* Cron Job Failed - This alert watches the cronjobs that are described in xref:../global_hub/global_hub_config_cronjobs.adoc#global-hub-configuring-cronjobs[Configuring the cronjobs] for failed events. There are two rules in this alert:
+
- Local compliance job failed. If this alert rule creates notifications, it means the local compliance status synchronization job failed. It might cause the data in the `history.local_compliance` table to be lost. Run the job manually, if necessary.
- Data Retention Job Failed. If this alert rule starts creating notifications, it means the data retention job failed. You can run it manually.

[#global-hub-delete-grafana-alert-rule]
== Deleting a default Grafana alert rule

If the default Grafana alert rules do not provide useful information for your needs, you can delete the Grafana alert rule by including a `deleteRules` section in the `multicluster-global-hub-custom-alerting` configmap. See xref:../global_hub_configuring.adoc#global-hub-customize-grafana-alerting-resources[Customize Grafana alerting resources] for more information about the `multicluster-global-hub-custom-alerting` configmap.

To delete all of the default alerts, the `deleteRules` configuration section should resemble the following example:

----
    deleteRules:
      - orgId: 1
        uid: globalhub_suspicious_policy_change
      - orgId: 1
        uid: globalhub_cluster_compliance_status_change_frequently
      - orgId: 1
        uid: globalhub_high_number_of_policy_events
      - orgId: 1
        uid: globalhub_data_retention_job
      - orgId: 1
        uid: globalhub_local_compliance_job
----

[#global-hub-customize-grafana-alerts]
== Customizing Grafana alerts

{global-hub-cap} supports creating custom Grafana alerts. Complete the following steps to customize your Grafana alerts:

[#global-hub-customize-grafana-ini-file]
=== Customizing your grafana.ini file

To customize your `grafana.ini` file, create a secret named `multicluster-global-hub-custom-grafana-config` in the namespace where you installed your {global-hub} operator. The secret data key must be: `grafana.ini`. 
 
The following code shows an example. Replace the required information with your own:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: multicluster-global-hub-custom-grafana-config
  namespace: multicluster-global-hub
type: Opaque
stringData:
  grafana.ini: |
    [smtp]
    enabled = true
    host = smtp.google.com:465
    user = [example@google.com]
    password = [xxx]
    ;cert_file =
    ;key_file =
    skip_verify = true
    from_address = [example@google.com]
    from_name = Grafana 
    # EHLO identity in SMTP dialog (defaults to instance_name)
    ;ehlo_identity = dashboard.example.com
----

*Note:* you cannot configure the section that already contains the `multicluster-global-hub-default-grafana-config` secret.

[#global-hub-customize-grafana-alerting-resources]
=== Customizing Grafana alerting resources

Global hub supports customizing the alerting resources which is explained in link:https://grafana.com/docs/grafana/v10.1/alerting/set-up/provision-alerting-resources/file-provisioning/[Create and manage alerting resources using file provisioning] in the Grafana documentation. 

To customize the alerting resources, create a configmap named `multicluster-global-hub-custom-alerting` in the `multicluster-global-hub` namespace.

The configmap data key must be named: `alerting.yaml`. 

The following code shows an example:

[source,yaml]
----
apiVersion: v1
data:
  alerting.yaml: |
    contactPoints:
      - orgId: 1
        name: globalhub_policy
        receivers:
          - uid: globalhub_policy_alert_email
            type: email
            settings:
              addresses: [example@redhat.com]
              singleEmail: false
          - uid: globalhub_policy_alert_slack
            type: slack
            settings:
              url: [Slack Webhook URL]
              title: |
                {{ template "globalhub.policy.title" . }}
              text: |
                {{ template "globalhub.policy.message" . }}              
    policies:
      - orgId: 1
        receiver: globalhub_policy
        group_by: ['grafana_folder', 'alertname']
        matchers:
          - grafana_folder = Policy
        repeat_interval: 1d
    deleteRules:
      - orgId: 1
        uid: [Alert Rule Uid]
    muteTimes:
      - orgId: 1
        name: mti_1
        time_intervals:
          - times:
              - start_time: '06:00'
                end_time: '23:59'
                location: 'UTC'
            weekdays: ['monday:wednesday', 'saturday', 'sunday']
            months: ['1:3', 'may:august', 'december']
            years: ['2020:2022', '2030']
            days_of_month: ['1:5', '-3:-1']
kind: ConfigMap
metadata:
  name: multicluster-global-hub-custom-alerting
  namespace: multicluster-global-hub
----
