[#create-migration-resource]
= Creating the migration resource

To initiate the {global-hub} ZTP cluster migration, you must create a `ManagedClusterMigration` custom resource. You can define the clusters to migrate by using a static list, or by using a dynamic placement resource.

== Creating a _ManagedClusterMigration_ resource to migrate by using a static list

If you have a specific list of managed clusters to migrate, see the following procedure to create the resource:

.Procedure

. Create a file that is named `migration-static.yaml` with the following content where the `local-cluster` and the `hub2` representing the source and hub clusters:

+
[source,yaml]
----
apiVersion: global-hub.open-cluster-management.io/v1alpha1
kind: ManagedClusterMigration
metadata:
  name: ztp-sno-migration
  namespace: multicluster-global-hub
spec:
  to: local-cluster
  from: hub2
  includedManagedClusters:
    - sno1
    - sno2
    - sno3
  supportedConfigs:
    stageTimeout: 15m
----

. Apply the resource to the {global-hub} by running the following command:

+
[source,bash]
----
oc apply -f migration-static.yaml
----

. Proceed to the _Verifying the migration status_ section at the end of this procedure.

== Creating a _ManagedClusterMigration_ resource to migrate by using dynamic placement

Use this method to select clusters that are dynamically based on labels and placement rules.

.Procedure

. Create a file that is named `migration-placement.yaml` with the following content to define the `clusterSet` binding and `Placemen`t on the source hub cluster:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace: multicluster-global-hub-agent
spec:
  clusterSet: global
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: migration-50
  namespace: multicluster-global-hub-agent
spec:
  numberOfClusters: 50
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: NotIn
              values:
                - "true"
----

. Apply the placement resources to the source hub cluster by running the following command:

+
[source,bash]
----
oc apply -f migration-placement.yaml
----

. Create a file named `migration-resource.yaml` with the following content to initiate the migration on the {global-hub}:

+
[source,yaml]
----
apiVersion: global-hub.open-cluster-management.io/v1alpha1
kind: ManagedClusterMigration
metadata:
  name: ztp-sno-migration
  namespace: multicluster-global-hub
spec:
  to: local-cluster
  from: hub2
  includedManagedClustersPlacementRef: migration-50
  supportedConfigs:
    stageTimeout: 15m
----

. Apply the migration resource to the {global-hub} by running the following command:

+
[source,bash]
----
oc apply -f migration-resource.yaml
----

[[verifying-migration-status]]
== Verifying the migration status

After you apply the migration resource, verify the progress of the migration.

.Procedure

. Check the status of the `ManagedClusterMigration` resource by running the following command:

+
[source,bash]
----
oc get managedclustermigration ztp-sno-migration -n multicluster-global-hub -o yaml
----

. Review the `status` section of the output. The migration is complete when the status indicates that all clusters have reached the `Completed` stage.