[#global-hub-accessing-grafana-data]
= Accessing the Grafana data

The Grafana data is exposed through the route. Run the following command to display the login URL:

----
oc get route multicluster-global-hub-grafana -n <the-namespace-of-multicluster-global-hub-instance>
----

The authentication method of this URL is same as authenticating to the {ocp} console.

To learn more about what you can view with the Grafana dashboards, see the following sections: 

* <<policy-grafana-dashboards,Viewing policy status with Grafana dashboards>>
* <<strimzi-grafana-dashboards,Viewing Strimzi information with Grafana dashboards>>
* <<postgres-grafana-dashboards,Viewing Postgres information with Grafana dashboards>>
* <<cluster-grafana-dashboards,Viewing cluster information with Grafana dashboards >>

[#policy-grafana-dashboards]
== Viewing policy status with Grafana dashboards

After accessing the global hub Grafana data, you can monitor the policies that were configured through the hub cluster environments that are managed.

From the {global-hub} dashboard, you can identify the compliance status of the policies of the system over a selected time range. The policy compliance status is updated daily, so the dashboard does not display the status of the current day until the following day.

To navigate the {global-hub} dashboards, you can observe and filter the policy data by grouping them by `policy` or by `cluster`. 

If you prefer to examine the policy data by using the `policy` grouping, start from the and the dashboard called `Global Hub - Policy Group Compliancy Overview`. 

This dashboard allows you to filter the policy data based on `standard`, `category`, and `control`. After selecting a specific point in time on the graph, you are directed to the `Global Hub - Offending Policies` dashboard. The `Global Hub - Offending Policies` dashboard lists the non-compliant or unknown policies at that time. After selecting a target policy, you can view related events and see what has changed by accessing the `Global Hub - What's Changed / Policies` dashboard.

Similarly, if you want to examine the policy data by `cluster` grouping, begin by using the `Global Hub - Cluster Group Compliancy Overview` dashboard. The navigation flow is identical to the `policy` grouping flow, but you select filters that are related to the cluster, such as managed cluster `labels` and `values`. Instead of viewing policy events for all clusters, after reaching the `Global Hub - What's Changed / Clusters` dashboard, you can view policy events related to an individual cluster.

[#strimzi-grafana-dashboards]
== Viewing Strimzi information with Grafana dashboards

To understand the health and performance of your Kafka deployment and Postgres database, collect their metrics. When you check the metrics, you can identify issues before they become critical and make informed decisions about resource allocation and capacity planning. If you do not collect and check the metrics, you might have limited visibility into the behavior of your Kafka deployment, making troubleshooting more difficult. 

You can check the dashboards and their metrics in the {global-hub} Grafana. In the Strimzi folder, you can view the following dashboards: 

* {global-hub} - Strimzi Operator
* {global-hub} - Strimzi Kafka
* {global-hub} - Strimzi Zookeeper 

[#postgres-grafana-dashboards]
== Viewing Postgres information with Grafana dashboards (Technology Preview)

To understand the health and performance of your Postgres config, collect and check the Postgres metrics in the Grafana dashboard. In the Postgres folder, you can view the following dashboard: 

* {global-hub} - PostgresSQL Database 

[#cluster-grafana-dashboards]
== Viewing cluster information with Grafana dashboards 

To filter your managed clusters and to view their details and events, use the Grafana dashboards. With the Grafana dashboard, you can filter your managed clusters based on: `hub`, `labels` and `name`. Additionally, you can view the distribution of your managed clusters based on: `hub`, `status`, `cloud`, and `version`.  

In the Cluster folder, you can view the following dashboard: 

* {global-hub} - Cluster Overview  