:_mod-docs-content-type: PROCEDURE

[#global-hub-upgrade-postgres-restore]
= Restoring historical data (Deprecated)

[role="_abstract"]
Starting with {global-hub} version 1.4.0, the built-in PostgreSQL database is upgraded to version 16. This upgrade replaces the earlier `multicluster-global-hub-postgres` instance with the new `multicluster-global-hub-postgressql` instance.

By default, this upgrade automatically re-syncs real-time data, such as `policies` and `clusters`, to the new Postgres instance. Historical data, such as `event` and `history` tables, are not automatically recovered.

When the {global-hub} upgrade to version 1.4.0 removes your historical data, recover your data by completing the following steps:

.Procedure

. Clone the {acm} Git repository to access the shell script that you need to recover your data by running the following command:

+
[source,bash]
----
git clone -b release-2.13 https://github.com/stolostron/multicluster-global-hub.git
----

. Restore your history tables by completing the following steps. Use the {global-hub} that you installed:

.. If the default namespace is `multicluster-global-hub`, run the following shell script:

+
[source,bash]
----
./doc/upgrade/restore_history_tables.sh
----

.. If the namespace is not specified as `multicluster-global-hub`, set the {global-hub} namespace when you run the following shell script:

+
[source,bash]
----
./doc/upgrade/restore_history_tables.sh
----

. Restore your event tables by completing the following steps:

.. If the default namespace is `multicluster-global-hub`, run the following shell script:

+
[source,bash]
----
./doc/upgrade/restore_event_tables.sh
----

.. If the namespace is not specified as `multicluster-global-hub`, set the {global-hub} namespace when you run the following shell script:

+
[source,bash]
----
./doc/upgrade/restore_event_tables.sh
----
