[#backup-for-global-hub]
= Backup for {global-hub} (Technology Preview)

Use {global-hub} with {product-title-short} backup and restore features for recovery solutions and to access basic resources. To learn more about how these features help you, see xref:../business_continuity/backup_restore/backup_intro.adoc#backup-intro[backup and restore]. 

{global-hub} also supports backup `postgres pvc` by using the `acm-hub-pvc-backup`. To ensure your {global-hub} can support the backup `postgres pvc`, you must have the current version of VolySync and {product-title-short}. For detailed steps on backing up your data, see link:https://github.com/open-cluster-management-io/policy-collection/tree/main/community/CM-Configuration-Management/acm-hub-pvc-backup[acm-hub-pvc-backup]. 

== Restoring {global-hub} backup and restore  

If you need to restore your {global-hub} cluster, see xref:../business_continuity/backup_restore/backup_intro.adoc#preparing-the-new-hub-cluster[prepare the new hub cluster]. Install the {global-hub} operator but do not create the {global-hub} custom resource (CR) because the CR is automatically restored.  
