
[#preparing-hubs-for-migration]
= Preparing the hub clusters for migration

To migrate managed clusters between hub clusters, you must configure the target hub cluster to match the source hub cluster environment and establish connectivity through the {global-hub}.
//Is this just for ZTP?

.Prerequisites

* Ensure all managed clusters are connected by network to the target hub cluster.
* Verify version compatibility. See xref:../global_hub/ztp-migration-overview.adoc#ztp-migration-overview[Zero Touch Provisioning migration overview] for supported versions of {acm-short} and {ocp-short}.
. Install the {acm-short} operator on the target hub cluster. See link:https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.15/html/install/installing-the-operator-on-the-target-hub[Installing from the Software Catalog console].

. Create a YAML file to enable the `siteconfig` operator as you see in the following example where `siteconfig` is set to `enabled: true`:

+
[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  overrides:
    components:
      - name: siteconfig
        enabled: true
----

. Apply the file to your cluster. Run the following command:

+
[source,bash]
----
oc apply -f <name>siteconfig.yaml
----

. Verify that the `siteconfig-controller-manager` deployment is in the `available` status. Run the following command:

+
[source,bash]
----
oc get deployment -n open-cluster-management siteconfig-controller-manager
----

//. Prepare the target hub for Zero Touch Provisioning (ZTP) by following the link:https://github.com/openshift-kni/telco-reference/blob/main/telco-ran/configuration/argocd/README.md#preparation-of-hub-cluster-for-ztp[ZTP hub preparation guide].
//we cannot link to the ZTP guide in the telco reference doc--please point me to the correct official documentation for ZTP hub preparation and I will update the link accordingly--if not we need to document the steps here in the migration guide.--please give me those steps that we need.
//. *Optional:* If observability is enabled on the source hub, configure it on the target hub by following the link:https://github.com/stolostron/multicluster-observability-operator[Multicluster Observability Operator guide].
//cannot point to this
//. Install the {global-hub} operator on the target hub. See the link:https://github.com/stolostron/multicluster-global-hub#run-the-operator-in-the-cluster[{global-hub} installation guide].
//cannot point to this

. Create a YAML file to enable the `ManagedServiceAccount` component. See the following example where `managedserviceaccount` is set to `enabled: true`:

+
[source,yaml]
----
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  overrides:
    components:
      - name: managedserviceaccount
        enabled: true
----

. Apply the file to your cluster. Run the following command:

+
[source,bash]
----
oc apply -f mce-msa.yaml
----

. Import the source hub cluster as a managed hub cluster to the {global-hub}. Find instructions at 

+
*Important:* You must include the `global-hub.open-cluster-management.io/deploy-mode: hosted` label during the import process for the migration to function.

For detailed instructions, see link:https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.15/html/clusters/cluster_mce_overview#import-intro[Import].
//find name of this topic