:_mod-docs-content-type: PROCEDURE

[#refresh-release-images]
= Refresh the release images list

[role="_abstract"]
Refresh and synchronize the list of release images to ensure that the console reflects the latest stable or fast-channel release images needed to build or provision new clusters.

.Prerequisites

* You are running a Linux or Mac operating system.

.Procedure

. If the installer-managed `acm-hive-openshift-releases` subscription is enabled, disable the subscription by setting the value of `disableUpdateClusterImageSets` to `true` in the `MultiClusterHub` resource. 

. Clone the link:https://github.com/stolostron/acm-hive-openshift-releases/tree/backplane-2.10[acm-hive-openshift-releases] GitHub repository.

. Remove the subscription by running the following command:

+
[source,bash]
----
oc delete -f subscribe/subscription-fast
----

. Synchronize and display the `candidate` release images. Run the following command:

+
[source,bash]
----
make subscribe-candidate
----
+
*Note:* After about one minute, the latest list of `candidate` release images is available.

. Synchronize and display the `fast` release images. Run the following command:

+
[source,bash]
----
make subscribe-fast
----
+
*Note:* After about one minute, the latest list of `fast` release images is available.

. Connect to the `stable` release images and synchronize your {acm-short} hub cluster. Run the following command:

+
[source,bash]
----
make subscribe-stable
----
+
*Note:*After about one minute, the list of available `candidate`, `fast`, and `stable` release images updates with the currently available images.

. *Optional:* Unsubscribe from any of these channels to stop viewing the updates by running the following command: 

+
[source,bash]
----
oc delete -f subscribe/subscription-fast
----

.Verification

. View the list of currently available release images in the {acm-short} console when you are creating a cluster.
