[#scrapping-prometheus]
= Scrapping with Prometheus

//need a description here, why they user wants to do this.

[#scrapping-hub]
== Scrapping the hub cluster

//need a description here, why they user wants to do this.

. Create a _ServiceMonitor_ for collecting services exposing metrics. Note: for _OCP_ _metadata.namespace_ should be `+openshift-monitoring+`. Run the following command:

----
oc apply -f
----

[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hub-subscription-metrics
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - open-cluster-management
  selector:
    matchLabels:
      app: hub-subscription-metrics
----

. Create a _Role_ for setting the permissions for monitoring:

----
oc apply -f
----

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s-monitoring
  namespace: open-cluster-management
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
----

. Create a _RoleBinding_ for Binding the _Role_ to Prometheus’ monitoring
_ServiceAccount_:

____
Note: for _OCP_ _subjects[0].namespace_ should be
`+openshift-monitoring+`.
____

----
oc apply -f
----

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s-monitoring-binding
  namespace: open-cluster-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s-monitoring
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
----

. Verify. In `+Prometheus+`’s dashboard, run the following query to look up
metrics reported by the Subscription Operator Metrics Service:

----
{service="hub-subscription-metrics"}
----

[#scrapping-managed]
== Scrapping the managed cluster

. Create a _ServiceMonitor_ for collecting services exposing metrics:

____
Note: for _OCP_ _metadata.namespace_ should be `+openshift-monitoring+`.
____

----
oc apply -f
----

[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mc-subscription-metrics
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - open-cluster-management-agent-addon
  selector:
    matchLabels:
      app: mc-subscription-metrics
----

. Create a _Role_ for setting the permissions for monitoring:

----
oc apply -f
----

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s-monitoring
  namespace: open-cluster-management-agent-addon
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
----

. Create a _RoleBinding_ for Binding the _Role_ to Prometheus’ monitoring
_ServiceAccount_:

____
Note: for _OCP_ _subjects[0].namespace_ should be
`+openshift-monitoring+`.
____

----
oc apply -f
----

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s-monitoring-binding
  namespace: open-cluster-management-agent-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s-monitoring
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
----

. Verify In `+Prometheus+`’s dashboard, run the following query to look up
metrics reported by the Subscription Operator Metrics Service:

----
{service="mc-subscription-metrics"}
----

[#scrapping-standalone]
== Scrapping the standalone cluster

. Create a _ServiceMonitor_ for collecting services exposing metrics:

____
Note: for _OCP_ _metadata.namespace_ should be `+openshift-monitoring+`.
____


[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: standalone-subscription-metrics
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - open-cluster-management
  selector:
    matchLabels:
      app: standalone-subscription-metrics
----

. Create a _Role_ for setting the permissions for monitoring:

----
oc apply -f
----

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s-monitoring
  namespace: open-cluster-management
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
EOF
----

. Create a _RoleBinding_ for Binding the _Role_ to Prometheus’ monitoring
_ServiceAccount_:

____
Note: for _OCP_ _subjects[0].namespace_ should be
`+openshift-monitoring+`.
____

----
oc apply -f
----

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s-monitoring-binding
  namespace: open-cluster-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s-monitoring
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
----

. Verification In `+Prometheus+`’s dashboard, run the following query to look up
metrics reported by the Subscription Operator Metrics Service:

----
{service="standalone-subscription-metrics"}
----